### ISSUE TITLE
Any ideas when this will be ready for testing? 

### ISSUE THREAD

**Issue by Delonvdv** [nystudio107/craft-seomatic#1]
I tried grabbing this through composer and get the following:
 [UnexpectedValueException]                                                                                                                        
  Could not parse version constraint //github.com/aelvan/Imager-Craft/seomatic: Invalid version string "//github.com/aelvan/Imager-Craft/seomatic"

**Comment by khalwat** [comment]
You're really not supposed to be using it yet. :)

I'm using it, but I don't want things to randomly break on people. I'm hoping to have something ready by the end of the month.
