### ISSUE TITLE
FrontendTemplateContainer causing GraphQL error

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-seomatic#1000]
### Describe the bug
SEOmatic is trying to output a value for `FrontendTemplateContainer` and erroring at `/src/services/MetaContainers.php`, lines 558 and 622 (if you are passing in `asArray: true`).

_NOTE: This might be an edge case since this is happening in one site and not another one in a similar setup._

### To reproduce
Steps to reproduce the behaviour:
1. Perform a root or nested GraphQL query and include a query for `seomatic` containers.

### Expected behaviour
Using this query:

```GraphQL
{
  entry(uri: "my-uri", site: "default") {
    title
    uri
    seomatic(asArray:true) {
      metaTitleContainer
      metaTagContainer
      metaLinkContainer
      metaScriptContainer
      metaJsonLdContainer
      metaSiteVarsContainer
    }
  }
}
```

... you should get back only the requested containers back from GraphQL. Currently I'm receiving this error:

```
yii\\base\\ErrorHandler::handleError(8, 'Trying to access array offset on value of type null', '/var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php', 622)
```

It seems that `Seomatic::$plugin->frontendTemplates->frontendTemplateContainer` is coming up `null`. It also seems that the `FrontendTemplateContainer` is meant to be included in the GraphQL results even if it's not being requested.

Doing a check for `frontendTemplateContainer` does allow queries to go through and it doesn't render anything in the `FrontendTemplateContainer` container:

```php
if ($type === FrontendTemplateContainer::CONTAINER_TYPE) {
    $renderedTemplates = [];
    if (Seomatic::$plugin->frontendTemplates->frontendTemplateContainer['data'] ?? data) {
        $frontendTemplateContainers = Seomatic::$plugin->frontendTemplates->frontendTemplateContainer['data'];
        foreach ($frontendTemplateContainers as $name => $frontendTemplateContainer) {
            if ($frontendTemplateContainer->include) {
                $result = $frontendTemplateContainer->render([
                ]);
                $renderedTemplates[] = [$name => $result];
            }
        }
    }

    return $renderedTemplates;
}
```

---

This is all the same if you include the `frontendTemplateContainer` field:

```
seomatic(asArray:true) {
  metaTitleContainer
  metaTagContainer
  metaLinkContainer
  metaScriptContainer
  metaJsonLdContainer
  metaSiteVarsContainer
  frontendTemplateContainer
}
```

... or if you run any single field:

```
seomatic(asArray:true) {
  metaTitleContainer
}
```

### Versions
- Plugin version: 3.4.15
- Craft version: Craft Pro 3.7.16 (also tested this on 3.7.13 and 3.7.14)

**Comment by sjcallender** [comment]
We're seeing this as of 3.4.9. Everything works on 3.4.8.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/ffe2c8d595d2f0cdca56b8fbe94889f8b1d7dbe4

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.16”,
```
Then do a `composer clear-cache && composer update`

**Comment by wbrowar** [comment]
Thanks for fixing that! The `dev-develop as 3.4.16` version fixed the issue for me.

Line 558 is also affected and it might be good to add the same check there so you wouldn't run into this error when `asArray` is set to `false`.

https://github.com/nystudio107/craft-seomatic/blob/develop/src/services/MetaContainers.php#L558
