### ISSUE TITLE
Incorrect canonical URL when using SEO Settings field to override, fetching via GraphQL

### ISSUE THREAD

**Issue by howells** [nystudio107/craft-seomatic#1001]
### Describe the bug
When using the SEO Settings field, overriding an entry's canonical URL and then fetching it via GraphQL doesn't appear to work. I've tried this on two separate installs, using SEOmatic 3.4.15 and 3.4.10 with the same behaviour.

### To reproduce
Steps to reproduce the behaviour:
1. Set up default canonicals for a given section, e.g. {entry.url}
2. Add SEO Settings field to the section
3. Update an entry's canonical to something else
4. Fetch seomatic data using the snippet below, and check the canonical link in metaLinkContainer

```
... on recipes_recipe_Entry {
	seomatic {
		metaTitleContainer
		metaTagContainer
		metaLinkContainer
		metaScriptContainer
		metaJsonLdContainer
		metaSiteVarsContainer
	}
}
```

### Expected behaviour
The canonical link within metaLinkContainer should be the url entered into the entry's SEO Settings, not the section default.

### Versions
- Plugin version: 3.4.15 and 3.4.10
- Craft version: 3.5.19.1 and 3.7.13

**Comment by khalwat** [comment]
Ah, right you are. It is using the URI of the entry itself. Will fix.

**Comment by howells** [comment]
Brilliant thanks

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/0c217a648d3bd0366665201e0470a80bc9ab71a4

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.16”,
```
Then do a `composer clear-cache && composer update`

**Comment by howells** [comment]
@khalwat thanks, it didn't seem to work though: when I tried to edit an entry whose canonical I had previously updated, I get the attached error.

<img width="1513" alt="CleanShot 2021-10-13 at 18 09 42@2x" src="https://user-images.githubusercontent.com/145849/137180815-fab55ac3-c0db-4c38-adcd-d15f8c681c10.png">

**Comment by khalwat** [comment]
@howells 

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/cd1b488da1df0cdd56e174a957574b15853dd37f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.17”,
```
Then do a `composer clear-cache && composer update`

**Comment by howells** [comment]
@khalwat that works now thanks! 

But think it's revealed another issue, in that it seems you can't add a canonical that is a url of a completely separate website.

There's is a circumstance where you will want to provide a canonical URL for a given entry that belongs to a separate website; so you're essentially handing over the single source of truth for a piece of content to another site (in my client's case, it's part of a sponsorship deal where their sponsor is leveraging my client's authority for a piece of content, if that makes sense). So could it be tweaked to allow any arbitrary external URL?

**Comment by khalwat** [comment]
> But think it's revealed another issue, in that it seems you can't add a canonical that is a url of a completely separate website.

What goes wrong when you try? I was able to add `https://woof.com` as the canonical URL in an entry in an SEO Settings field, and it appeared when I queried it with GraphQL.

**Comment by howells** [comment]
@khalwat the site's domain is always used instead of the one entered. For example, if I enter: `https://www.externaldomain.com/this/canonical`, seomatic would return `https://www.websitedomain.com/this/canonical`, i.e. ignore the host but but append the path to the site's url.

**Comment by khalwat** [comment]
Show me how you're doing this? Here's what I did, I put this in the SEO Settings field:

<img width="814" alt="Screen Shot 2021-10-14 at 7 56 52 AM" src="https://user-images.githubusercontent.com/7570798/137312842-8cfa0e83-b1b5-46b9-975e-5f28b39d9ddc.png">

...and when I output the result in GraphQL, I get this:

<img width="814" alt="Screen Shot 2021-10-14 at 7 57 03 AM" src="https://user-images.githubusercontent.com/7570798/137312893-d9c8ba31-6b7e-429a-94f6-40afbd82f45f.png">

...are you trying to set the canonical URL somewhere else?

**Comment by howells** [comment]
@khalwat yup that's how I'm doing it:

<img width="792" alt="CleanShot 2021-10-14 at 13 14 50@2x" src="https://user-images.githubusercontent.com/145849/137315425-8b931dc7-10e6-4c05-bf76-120d380445c7.png">

and on querying, the site's url is shown:

![CleanShot 2021-10-14 at 13 16 35@2x](https://user-images.githubusercontent.com/145849/137315617-72dcfadb-8b6e-4002-99aa-d5e816cb8f41.png)

And then with the same, external domain, appending a path:

<img width="824" alt="CleanShot 2021-10-14 at 13 17 51@2x" src="https://user-images.githubusercontent.com/145849/137315752-b18912d1-9a88-487f-acbc-a321af7bc0c5.png">

results in the path just being appended to the site url, rather than using the domain I actually entered:

![CleanShot 2021-10-14 at 13 18 37@2x](https://user-images.githubusercontent.com/145849/137315900-de870779-11e7-47f1-9e13-8f7681c1b7e8.png)

**Comment by khalwat** [comment]
Are you using SEOmatic's SiteURL Override feature or something?

**Comment by howells** [comment]
@khalwat ah yes, using an alias pointing to my client site:

<img width="1482" alt="CleanShot 2021-10-14 at 13 21 45@2x" src="https://user-images.githubusercontent.com/145849/137316354-4e13d964-34d9-483c-9281-dd6745d891ca.png">

So that'll be the issue: is there a workaround?

**Comment by khalwat** [comment]
The Site URL Override tells it to override *any* of the URLs you present to SEOmatic so... I think you have a bit of a catch-22 here.

**Comment by howells** [comment]
@khalwat yeah you're right, I've worked out a way to get around this so it's not an issue. Thanks for sorting out the bug generally.
