### ISSUE TITLE
Automatically add extra attribute to all seomatic meta tags (for use in conjunction with react-helmet)

### ISSUE THREAD

**Issue by m9dfukc** [nystudio107/craft-seomatic#1003]
### Question
Is there a "automatic" way (or hook) to add custom attributes to every single meta tag that seomatic renders? I know there is [this](https://nystudio107.com/docs/seomatic/using.html#extra-tag-attributes) but that would require to go over every single element manually.

### Additional context
I am using react with [react-helmet](https://github.com/nfl/react-helmet) inside my craft website which requires `data-react-helmet="true"` [to be set](https://github.com/nfl/react-helmet/issues/341) on the existing meta tags in order to overwrite/replace these tags and avoid duplicate meta tags.

**Comment by khalwat** [comment]
There's no automatic way to do that, but you could iterate over all of the tags and add them yourself... but are you using Craft "headless" in this scenario?

Typically you wouldn't be using React Helmet unless you were using it headless, and React was rendering the entire page.

**Comment by m9dfukc** [comment]
No I am not using craft in headless mode. but instead I have a hybrid page where certain parts come from craft and then other parts come from a custom api rendered inside the craft frame with react. some pages only contain static content (craft) others are more of a SPA nature and craft only provides the basic frame around (nav, header, footer ...). On these dynamic pages I would like to overwrite certain parts seomatic.

**Comment by khalwat** [comment]
In an ideal world, you'll make life easier for yourself if in this hybrid setup, you decide who will control rendering the SEO data. You can override anything SEOmatic outputs using the Twig APIs built into it:

https://nystudio107.com/docs/seomatic/using.html#twig-templating

Here are some extended examples of manipulating the JSON-LD:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

If you've decided that you want React Helmet to take over the rendering, you can do something like:

```twig
    {# Tag container #}
    {% set container = seomatic.tag.container() %}
    {% for tag in container.data %}
        {% do tag.tagAttrs({
            "data-react-helmet": true,
        }) %}
    {% endfor %}
    {# Link container #}
    {% set container = seomatic.link.container() %}
    {% for tag in container.data %}
        {% do tag.tagAttrs({
            "data-react-helmet": true,
        }) %}
    {% endfor %}
    {# Script container #}
    {% set container = seomatic.script.container() %}
    {% for tag in container.data %}
        {% do tag.tagAttrs({
            "data-react-helmet": true,
        }) %}
    {% endfor %}
    {# JsonLd container #}
    {% set container = seomatic.jsonLd.container() %}
    {% for tag in container.data %}
        {% do tag.tagAttrs({
            "data-react-helmet": true,
        }) %}
    {% endfor %}

```

ref: https://nystudio107.com/docs/seomatic/using.html#extra-tag-attributes

**Comment by m9dfukc** [comment]
Yeah my whole setup is a bit convoluted ;) 

Thank you for the examples, I think I gonna use that approach ... guess we can close this issue!
