### ISSUE TITLE
Stray // for Matomo script and "typo"

### ISSUE THREAD

**Issue by philipboomy** [nystudio107/craft-seomatic#1004]
### Describe the bug
I think there are some stray "//" in the code which causes 2 "//" to be output. See here https://share.getcloudapp.com/nOu5YmA7
I believe its these here: https://github.com/nystudio107/craft-seomatic/blob/c93847b8a597ba1bf882f218ee42121b557fc62b/src/templates/_frontend/scripts/matomoAnalytics.twig#L10

Also I think you forgot to replace "Fathom" with "Matomo" in the settings page https://share.getcloudapp.com/DOu6j8XX
/seomatic/tracking/matomo/default

### Versions
- Plugin version: 3.4.15

**Comment by khalwat** [comment]
@philipboomy that's what they list on their page:

https://developer.matomo.org/guides/tracking-javascript-guide

I'm guessing it is an error on their end?

The typo was already fixed, but apparently didn't propagate to your created containers -> https://github.com/nystudio107/craft-seomatic/blob/develop/src/seomatic-config/globalmeta/ScriptContainer.php#L391

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/c5788fdc6545732a322bb5ff49b1b3c0e26431d0
