### ISSUE TITLE
Incorrect url when querying nonexistent uri via GraphQL

### ISSUE THREAD

**Issue by OscarBarrett** [nystudio107/craft-seomatic#1005]
### Describe the bug
e.g. for the following query

```graphql
query {
  seomatic(uri: "/this-does-not-exist") {
    metaTitleContainer
    metaTagContainer
    metaLinkContainer
    metaScriptContainer
    metaJsonLdContainer
    metaSiteVarsContainer
  }
}
```

Running this in the GraphQL explorer, I get `<host>/actions/graphql/api` for the following items:
- og:url
- Canonical URL
- JsonLd: mainEntityOfPage, url

### Expected behaviour
I assume it should parrot the requested uri back instead.

### Versions
- Plugin version: 3.4.17
- Craft version: 3.7.17

**Comment by khalwat** [comment]
I'm thinking probably it should return nothing (or some kind of error)?

**Comment by OscarBarrett** [comment]
Either of those options should be fine. The fields/interface are nullable so allow for the first

**Comment by khalwat** [comment]
Turns out to be a little involved to simulate a full "does this URI resolve to something" properly, but I think I have an idea of how to do it.

Though in the context of what we're trying to do here, it might be proper to just ensure the request resolves to an element of some kind.

**Comment by OscarBarrett** [comment]
@khalwat Just checking if you made a change here, or is this a wontfix for now?

**Comment by khalwat** [comment]
I have not made any changes as of yet; it's taken a lower priority, as it's a bit involved, and relatively niche.
