### ISSUE TITLE
rel="canonical" tag only added if environment set to live

### ISSUE THREAD

**Issue by harrison-drift** [nystudio107/craft-seomatic#1006]
### Describe the bug
The `link rel="canonical" tag is only added when using the Automatic Render Enabled setting if the environment is set to live. For local and staging it is not added. 

### To reproduce
Steps to reproduce the behaviour:
1. Go to /admin/seomatic/plugin
2. Enable "Automatic Render Enabled"
3. Enable "Manually Set SEOmatic Environment"
4. Set environment to anything other than "live"
5. Go to your site and see how the canonical tag is not present.
6. Change the environemtn back to "live"
7. Go to your site and see how the canonical tag is present

### Expected behaviour
I'd expect the canonical tag to show no matter the environement or it at least an explanation as to why it's not added somewhere

### Versions
- Plugin version: 3.4.17
- Craft version: 3.7.17.2 Pro

**Comment by harrison-drift** [comment]
Seems it mentioned [here](https://github.com/nystudio107/craft-seomatic/blob/7fb6d59fb3efc7d9888ab3f5fd6c23a13d2d3450/docs/docs/configuring.md#multi-environment-config-settings)

But maybe it could be written in the plugin or documented under "What is addeed using the Automatic Render Enabled" setting?

**Comment by khalwat** [comment]
The Canonical URL does not render for pages where Robots/indexing is not enabled. Robots/indexing is automatically disabled for you by default when in local dev or staging environments.

https://www.searchenginejournal.com/google-dont-mix-noindex-relcanonical/262607/

The "automatic render" or not should not affect this, if it somehow is, then that's a bug we should look into.

**Comment by harrison-drift** [comment]
@khalwat Sure, but is there no way I can enable canonicals without enabling robots at the same time? Seems like they should at least be seperate so that I can confirm everythings working?

I've got an SEO agency looking to confirm canonicals are in place for their crawlers, but would rather the staging site not be indexed by a search engine

**Comment by khalwat** [comment]
Well, that's the thing... everything _is_ working correctly. Many SEO tools will flag an error if indexing is off for a page, but a canonical URL is present. Your SEO company should be aware of this.

This is noted in the SEOmatic documentation here:

https://nystudio107.com/docs/seomatic/configuring.html#multi-environment-config-settings

If you really truly want to do this, you set the SEOmatic environment to Production, and manually change the Robots tag to `noindex` but I'd recommend against it in general.

**Comment by khalwat** [comment]
So I thought about it, and I'll add a config setting for you to always display Canonical URLs. Just make sure you toggle it off after testing has been done.

**Comment by khalwat** [comment]
Added in: https://github.com/nystudio107/craft-seomatic/commit/102e70a5819bb91690c49f88b6b029cf6f5097a8

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.18”,
```
Then do a `composer clear-cache && composer update`
