### ISSUE TITLE
Twig expressions no longer working

### ISSUE THREAD

**Issue by jmauzyk** [nystudio107/craft-seomatic#1007]
### Describe the bug
It looks like after a recent update to SEOmatic (not sure exactly when), content SEO set in the CP via Twig expressions aren't working. For example, our blog posts were set to use a Custom URL for the OpenGraph Image Source using the Twig expression below to select the first image from a set of matrix blocks, or fall back to the category's image if one wasn't found:

```
{entry.blogPostElements.type('image').one().image.one().getUrl({mode: 'crop', width: 1200, height: 630, quality: 82, position: 'center-center'}) ??? entry.blog.one().cardImage.one().getUrl({mode: 'crop', width: 1200, height: 630, quality: 82, position: 'center-center'})}
```

However, this is no longer working. I've tried single and double brackets and it doesn't seem to make a difference. Was there a change to how image URLs are supposed to be set by Twig expression in the CP?

### Versions
- Plugin version: 3.4.17
- Craft version: 3.7.17.1

**Comment by khalwat** [comment]
I'd suggest getting your expression working in your Entry Twig template, and then pasting it into the SEOmatic field. Without having your setup here, I'm not sure exactly what the error could be by looking at the expression.

This _should_ be valid, I'd think:

```
{{ entry.blogPostElements.type('image').one().image.one().getUrl({mode: 'crop', width: 1200, height: 630, quality: 82, position: 'center-center'}) ??? entry.blog.one().cardImage.one().getUrl({mode: 'crop', width: 1200, height: 630, quality: 82, position: 'center-center'}) }}
```

**Comment by jmauzyk** [comment]
I tested out setting this in the twig template using `{% do seomatic.meta.ogImage() %}` and it works as expected. Unfortunately, after copying over to the SEOmatic content field in the CP, it no longer works and ends up just outputting our site URL as the `og:image` content.

**Comment by khalwat** [comment]
Interesting. Can you simply the expression until it does work, e.g.:

```twig
{{ entry.blogPostElements.type('image').one().image.one().getUrl({mode: 'crop', width: 1200, height: 630, quality: 82, position: 'center-center'})  }}
```

Also check your `web.log` for any potential errors?

**Comment by jmauzyk** [comment]
Aha! So it has to do with the hash for image transforms. It works when I enter it as:

```
{{ entry.blogPostElements.type('image').one().image.one().getUrl({'mode': 'crop', 'width': 1200, 'height': 630, 'quality': 82, 'position': 'center-center'}) }}
```

Without the hash keys quoted, it throws the following errors:
```
2021-10-22 11:11:12 [-][10982][fa0r0d8lpdadl4em0sd6g4s84f][error][nystudio107\seomatic\helpers\MetaValue::parseMetaString] Error rendering `{{ entry.blogPostElements.type('image').one().image.one().getUrl({mode: 'crop', width: 1200, height: 630, quality: 82, position: 'center-center'}) }}` -> A hash key must be a quoted string, a number, a name, or an expression enclosed in parentheses (unexpected token "punctuation" of value "{" in "__string_template__974a4adf63eaa087844ab9eca35f0ef859cb46571e7ebe50545d6605668f9ddf" at line 1. - {{ entry.blogPostElements.type('image').one().image.one().getUrl({mode: 'crop', width: 1200, height: 630, quality: 82, position: 'center-center'}) }}
2021-10-22 11:11:12 [-][10982][fa0r0d8lpdadl4em0sd6g4s84f][error][Twig\Error\SyntaxError] Twig\Error\SyntaxError: A hash key must be a quoted string, a number, a name, or an expression enclosed in parentheses (unexpected token "punctuation" of value "{" in "__string_template__974a4adf63eaa087844ab9eca35f0ef859cb46571e7ebe50545d6605668f9ddf" at line 1. in /home/parktool/parktoolweb2019/vendor/twig/twig/src/ExpressionParser.php:385
```

Any idea why this would now require quoted hash keys?

**Comment by khalwat** [comment]
Doesn't make a whole lot of sense to me... if it works in a template, it should work in the field, they are both just using Twig to parse them. But it's an error thrown by Twig:

https://github.com/twigphp/Twig/blob/3.x/src/ExpressionParser.php#L382

**Comment by khalwat** [comment]
Ah wait, I think I see something.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/564f43eca7e1ea2e2a519e19a70560fef0f1d918

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.18”,
```
Then do a `composer clear-cache && composer update`

**Comment by jmauzyk** [comment]
Thanks for working through this with me!
