### ISSUE TITLE
Matomo script URL contains 2x https://

### ISSUE THREAD

**Issue by philipboomy** [nystudio107/craft-seomatic#1008]
### Describe the bug
Matomo is trying to load the script from https://https//cdn.matomo.cloud/xxxx.matomo.cloud/container_xxxxx.js/matomo.js (see 2x https://)

Related to this #1004 

Thanks

**Comment by khalwat** [comment]
Show me what the Matomo script looks like in SEOmatic on the Tracking Scripts page (not the rendered version)

**Comment by philipboomy** [comment]
The client added this `https://cdn.matomo.cloud/xxxxxxx.matomo.cloud/container_xxxxxL.js` which I can now seem to be wrong. That is used when using Matomo tag. What should have been added was this https://xxxxxxxxx.matomo.cloud/ but that will output 2x https:// as well.

https://share.getcloudapp.com/kpu65QDp

I am also looking at this and wondering about the g.src url. That seems to be partly missing https://share.getcloudapp.com/llukJZLQ

**Comment by khalwat** [comment]
Right. Edit the source to look like this:

https://raw.githubusercontent.com/nystudio107/craft-seomatic/develop/src/templates/_frontend/scripts/matomoAnalytics.twig

```twig
{% if siteId.value is defined and siteId.value and scriptUrl.value is defined and scriptUrl.value | length %}
var _paq = window._paq = window._paq || [];
{% if sendPageView.value %}
_paq.push(['trackPageView']);
{% endif %}
{% if sendPageView.value %}
_paq.push(['enableLinkTracking']);
{% endif %}
(function() {
var u="{{ scriptUrl.value }}";
_paq.push(['setTrackerUrl', u+'matomo.php']);
_paq.push(['setSiteId', {{ siteId.value }}]);
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
})();
{% endif %}
```

That's the change I made here: https://github.com/nystudio107/craft-seomatic/commit/c5788fdc6545732a322bb5ff49b1b3c0e26431d0

**Comment by philipboomy** [comment]
Thanks!
