### ISSUE TITLE
Twig tags showing up in template when using meta variables

### ISSUE THREAD

**Issue by turnstylerj** [nystudio107/craft-seomatic#1009]
## Description

Encountering an odd issue on a fresh install with no SEO settings customization, when trying to use SEOmatic variables in an entry template template like `{{ seomatic.meta.seoTitle }}`, the value showing up on the front end is a plain text representation of the reference, i.e. `{{ entry.title }}` literally output on the page rather than the title.

Using `{{ seomatic.meta.seoTitle }}`:
![Screen Shot 2021-10-26 at 3 07 44 PM](https://user-images.githubusercontent.com/42223501/138968008-7194d72e-7fe1-4e7f-a3ed-e4d10acd10f9.png)
Using `{{ entry.title }}`:
![Screen Shot 2021-10-26 at 3 15 28 PM](https://user-images.githubusercontent.com/42223501/138968774-a511e7e4-95c8-46ac-8874-a42a5f574a45.png)

### Additional Information
The page title/meta tags are being populated correctly. When looking in the SEOmatic content settings for this channel, the SEO Title Source was by default set to "Custom Text" with the title reference in it:

![Screen Shot 2021-10-26 at 3 11 18 PM](https://user-images.githubusercontent.com/42223501/138968376-28c78b8d-47fe-454b-a5be-3a5fd8eebaec.png)

This seemed odd, so I switched it to "From Field" with source "Title", and now the same `{{ seomatic.meta.seoTitle }}` variable outputs the tag for the SEOmatic helper on the front end:

![Screen Shot 2021-10-26 at 3 13 38 PM](https://user-images.githubusercontent.com/42223501/138968575-4f2db0c5-5c1a-4e28-a510-75358e264c34.png)

## To reproduce
Steps to reproduce the behaviour:
1. Output the page title in a template using `{{ seomatic.meta.seoTitle }}`.

### Expected behaviour
The page title is output directly on the page, as it does when using `{{ entry.title }}`.

## Versions
- Plugin version: 3.4.17
- Craft version: 3.7.18

**Comment by khalwat** [comment]
Can you tell me if you're able to reproduce it with this version?

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.18”,
```
Then do a `composer clear-cache && composer update`

**Comment by turnstylerj** [comment]
Able to repro on that version as well.

**Comment by khalwat** [comment]
Something sounds very wrong to me... I'm wholly unable to reproduce, and it'd break an awful lot of sites if this were a generic problem. What could be different here?

**Comment by turnstylerj** [comment]
Hmm yeah, feels very strange. Just weird that other template variables are working fine, but the SEOmatic meta tags are behaving this way. I'll experiment with it a bit and see if I can narrow down what might be different.

**Comment by khalwat** [comment]
Are you able to replicate the issue on any other sites that use SEOmatic?

**Comment by khalwat** [comment]
It's expected that some of the SEOmatic fields will have Twig in them. You want to do something with the parsed result, you'd need to do something like:

```twig
{{ seomatic.meta.parsedValue('seoTitle') }}
```

as described here: <https://nystudio107.com/docs/seomatic/using.html#seomatic-variables>

**Comment by brandondeweese** [comment]
This definitely happening to me. Just upgraded too..

Spits out:
<img width="1237" alt="Screen Shot 2022-02-10 at 10 09 08 PM" src="https://user-images.githubusercontent.com/18017918/153545012-08c632b3-e7b5-43d8-86a8-11ad7dd251fe.png">

from:
{{ seomatic.meta.seoTitle }}

**Comment by khalwat** [comment]
@brandondeweese this is normal. See the response just above your post.

**Comment by brandondeweese** [comment]
Yep. I see. Sorry about that.
