### ISSUE TITLE
Ecommerce Tracking revenue data is not appearing in Google Analytics

### ISSUE THREAD

**Issue by APAMRIT** [nystudio107/craft-seomatic#1010]
SEOmatic plugin has been installed and ecommerce tracking has been enabled and configured to an analytics UA code, but there is no revenue data appearing in analytics. Please could you look into this

Thanks

**Comment by khalwat** [comment]
All SEOmatic does is make the script available to you. You need to implement it as per https://developers.google.com/tag-manager/enhanced-ecommerce

**Comment by APAMRIT** [comment]
Hi,

I've found that the code is on the website, but no data is still coming through, please could you look into this?

Thanks

**Comment by khalwat** [comment]
This is not something for me to look into.

SEOmatic makes the tracking script available, but it will not do anything at all unless you write the code yourself for Google Enhanced Ecommerce, as discussed here: 

https://developers.google.com/tag-manager/enhanced-ecommerce
