### ISSUE TITLE
Facebook OpenGraph Site Name Position Source not honoring setting

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft-seomatic#1011]
See attached. The SEOmatic preview is correct, but when FB scrapes it, the setting is not honored. Only puts the Site name befor the site title.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Global SEO > Facebook
2. Change "Facebook OpenGraph Site Name Position Source" to "After"
3. Go to Content SEO > Any Entry > Facebook
4. Change "Facebook OpenGraph Site Name Position Source" to "Same as Global Facebook OpenGraph Site Name Position"

### Expected behaviour
I expect the Facebook OpenGraph Site Name Position to be "After" on FB or Slack (it's off on Slack, too) and not just the SEOmatic preview.

### Screenshots
See attached.

### Versions
- Plugin version: 3.4.17
- Craft version: Craft Pro 3.7.2

![global](https://user-images.githubusercontent.com/18017918/140835843-71df3e21-3014-4426-905d-e94a926adabd.png)
![content](https://user-images.githubusercontent.com/18017918/140835848-14e8519b-7a79-48db-9431-b4862b42fc48.png)
0
![FB-Debugger-results](https://user-images.githubusercontent.com/18017918/140835884-0cd237ed-cfc4-4f91-b711-fca5151d65d1.jpeg)

**Comment by khalwat** [comment]
View the source of your website -- search on `og:title` to find a tag that looks like this:

```
<meta content="Homepage | Project" property="og:title">
```

I was able to switch positions of the site name, and have both the preview in the CP, and the generated source code on the frontend be correct.

Assuming you're able to do the same, the issue is merely a caching one -- Facebook and/or Slack both cache results from pages, so they don't have to re-fetch them each time.

**Comment by brandondeweese** [comment]
Sorry Andrew. Cleared my cache, and I'm not getting any changes. It should mirror the SEO title, and as you can see, it's not. Preview on the content SEO > Facebook is correct but the page's Preview is incorrect.

![Screen Shot 2021-11-08 at 11 11 16 PM](https://user-images.githubusercontent.com/18017918/140878312-9232acd5-fcd7-4c14-babc-12a356d11617.png)
![Screen Shot 2021-11-08 at 11 12 10 PM](https://user-images.githubusercontent.com/18017918/140878420-8ecf55b9-8687-4ed9-b077-060bd07ccd7d.png)

**Comment by brandondeweese** [comment]
Never mind. I had it incorrectly set at the entry level. Sorry to waste your time here.

**Comment by khalwat** [comment]
No worries, glad it's sorted!
