### ISSUE TITLE
Section sitemap not enabled when overridden in entry

### ISSUE THREAD

**Issue by howells** [nystudio107/craft-seomatic#1012]
### Describe the bug
I want only a handful of entries for a given section to be included in a sitemap, so it makes sense to me that I would disable the sitemap for the section in SEOmatic > Content SEO > Section > Sitemap, but then on the entry's SEO Settings field enable it for those entries I want to include in a sitemap. However, doing this means that the sitemap isn't actually made available for the section.

### To reproduce
Disable sitemap for section; enable sitemap on a per-entry basis. Visit sitemap, see that it isn't available.

### Expected behaviour
Sitemap is generated for the section, with only the specified entries included.

**Comment by khalwat** [comment]
Unfortunately, the solution here is to keep the sitemap enabled, and then disable all of the entries you do not want in the sitemap.

It would be relatively expensive to scan an every sitemap (enabled or not) looking for entries that are enabled to determine whether the sitemap itself is enabled or not.

From a logistical POV, the "Sitemap Enabled" is a higher-level switch than the per-entry setting.
