### ISSUE TITLE
Update the rendering order to optimise performance

### ISSUE THREAD

**Issue by jan-dh** [nystudio107/craft-seomatic#1013]
### Is your feature request related to a problem? Please describe.
As I was optimising my head tag with the info of this [talk](https://speakerdeck.com/csswizardry/get-your-head-straight), I found out by using the [test tool](https://csswizardry.com/ct/) that at the moment the title tag is being rendered pretty far down the header tag, which is not ideal.

### Describe the solution you would like
The ideal order is shown here:
https://speakerdeck.com/csswizardry/get-your-head-straight?slide=34

![image](https://user-images.githubusercontent.com/5801781/142198428-7ce859e7-f32a-4a36-8066-1abb81a43885.png)

This means especially the title tag should be rendered al the way at the top.

### Describe alternatives you have considered
The current solution atm would to disable the SEOmatic automatic rendering and handle the different rendering parts yourself. If this could work out of the box, that would be awesome.

**Comment by khalwat** [comment]
The `<title>` tag location isn't going to affect performance (unlike some of the other things in Harry's talk), but I will have a look. Unfortunately, we may be at the mercy of the Yii2 layer that is actually doing the tag injection here.

**Comment by khalwat** [comment]
In the interim, if you want precise control over where everything is rendered, you can turn off ** Automatic Render Enabled**, and then output the tags yourself where you want them with `seomatic.tag.render()`, `seomatic.link.render()`, etc.



https://nystudio107.com/docs/seomatic/configuring.html#plugin-settings

**Comment by jan-dh** [comment]
Ok, solved this by doing:

``` 
 {% set titleContainer = seomatic.title.container() %}
 {% do titleContainer.include(false) %}
<meta charset="utf-8">
 {{ seomatic.title.render() }}
```
 
to prevent duplicate title output. Works like a charm 🎉
