### ISSUE TITLE
CP resources not loading after update to 3.4.19

### ISSUE THREAD

**Issue by jimirobaer** [nystudio107/craft-seomatic#1015]
### Describe the bug

Unsure why it is happening, but since the latest update of SEOmatic, Craft CMS is unable to load the resources used by SEOmatic in a multi-site environment.

SEOmatic is trying to load its cpresources from an url containing the active language inside the URL (eg. '/nl'). I can't verify it is caused by a wrong configuration from my end, but other resources by Craft CMS and plugins load just fine.

I cleared all caches but didn't fix the issue.

### To reproduce
Steps to reproduce the behaviour:
1. Update or install latest version of SEOmatic
2. Open Dashboard and navigate to an entry where a SEOmatic field is placed
3. Look at Requests and see 404s for all SEOmatic requests

### Screenshots

<img width="1463" alt="Screenshot 2021-11-18 at 10 10 08" src="https://user-images.githubusercontent.com/8984769/142385777-c5b4976a-273c-4253-a9ef-d1ab1bfbd4be.png">

### Versions
- Plugin version: 3.4.19
- Craft version: 3.7.21

**Comment by khalwat** [comment]
Nothing has changed that I'm aware of with how SEOmatic loads its resources in some time. Please double-check to ensure this isn't some kind of a configuration issue on your end?

What is your site URL set to?

**Comment by jimirobaer** [comment]
> Nothing has changed that I'm aware of with how SEOmatic loads its resources in some time. Please double-check to ensure this isn't some kind of a configuration issue on your end?
> 
> What is your site URL set to?

I'm sorry, the problem was related to a change in our @web override on our part. Sorry, I should have checked better before taking the time to create this problem. 😉

**Comment by khalwat** [comment]
No worries at all!
