### ISSUE TITLE
Multiple queries to entity brand logo 

### ISSUE THREAD

**Issue by CraigPedleyCF** [nystudio107/craft-seomatic#1016]
We are seeing 24 repeat queries for the brand logo on one page load. 

`SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`id` AS `siteSettingsId`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `elements`.`canonicalId`, `elements`.`dateLastMerged`, `assets`.`volumeId`, `assets`.`folderId`, `assets`.`filename`, `assets`.`kind`, `assets`.`width`, `assets`.`height`, `assets`.`size`, `assets`.`focalPoint`, `assets`.`keptFile`, `assets`.`dateModified`, `volumeFolders`.`path` AS `folderPath`, `assets`.`uploaderId`, `content`.`id` AS `contentId`, `content`.`title`, `content`.`field_address`, `content`.`field_applyUrl`, `content`.`field_available_arksfuat`, `content`.`field_bio`, `content`.`field_byline`, `content`.`field_cableDownloadSpeed_ytiidtsw`, `content`.`field_cableUploadSpeed_aiatxsqk`, `content`.`field_careersCity`, `content`.`field_copperAdslDownloadSpeed_qcshuurv`, `content`.`field_copperAdslUploadSpeed_exemcgwv`, `content`.`field_customField`, `content`.`field_defaultBlockHeadline`, `content`.`field_defaultBlockText`, `content`.`field_department`, `content`.`field_description_ksltqibg`, `content`.`field_experienceLevel`, `content`.`field_fibreToTheCabinetDownloadSpeed_ukmwrarp`, `content`.`field_fibreToTheCabinetUploadSpeed_cnkhwzsl`, `content`.`field_function`, `content`.`field_heading`, `content`.`field_imageDarken`, `content`.`field_industry`, `content`.`field_interestRegisteredMessage_dmjdsjpg`, `content`.`field_isFeatured_wbgrlfec`, `content`.`field_isPopular_tooxbfmt`, `content`.`field_jobAd`, `content`.`field_jobTitle_kdlqogmo`, `content`.`field_lastName`, `content`.`field_latitude`, `content`.`field_legacyContent`, `content`.`field_linkedin_xbbseesn`, `content`.`field_longitude`, `content`.`field_officeDownloadSpeed_wnsargvb`, `content`.`field_officeUploadSpeed_kdtbjlmb`, `content`.`field_pinCategory`, `content`.`field_postingUrl`, `content`.`field_redirectUrl_kxknflmn`, `content`.`field_referralUrl`, `content`.`field_region`, `content`.`field_remote`, `content`.`field_residentialDownloadSpeed_vnpeqznu`, `content`.`field_residentialUploadSpeed_vvkormwe`, `content`.`field_roleType`, `content`.`field_scripts_fxfgauay`, `content`.`field_seoDescription_hdklgwzc`, `content`.`field_smartrecruitersCreator`, `content`.`field_smartrecruitersCreatorAvatar`, `content`.`field_smartrecruitersId`, `content`.`field_smartrecruitersRefNumber`, `content`.`field_smartrecruitersUuid`, `content`.`field_tooltipContent`, `content`.`field_typeOfEmployment`, `content`.`field_unavailablePermanently_flrhtpdt`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `assets` `assets` ON `assets`.`id` = `elements`.`id`
INNER JOIN `volumefolders` `volumeFolders` ON `volumeFolders`.`id` = `assets`.`folderId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`elements`.`id`=76922) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)
ORDER BY `elements`.`dateCreated` DESC
LIMIT 1) `subquery`
INNER JOIN `assets` `assets` ON `assets`.`id` = `subquery`.`elementsId`
INNER JOIN `volumefolders` `volumeFolders` ON `volumeFolders`.`id` = `assets`.`folderId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `elements`.`dateCreated` DESC`

### To reproduce
Remove and re-add the brand identity logos.

### Versions
- Plugin version: 3.4.17
- Craft version: 3.7.17

**Comment by khalwat** [comment]
What are your timings on these queries?

**Comment by CraigPedleyCF** [comment]
This is what we're getting from the Craft debug toolbar.
![image](https://user-images.githubusercontent.com/94613434/142593372-98dccfc4-62da-4b1d-9b05-bbcdcc621b23.png)

**Comment by khalwat** [comment]
According to that screenshot, the queries are taking `0.8ms` and `1.2ms` respectively, which I think is a non-issue given the timings?

**Comment by CraigPedleyCF** [comment]
I am just trying debug why our local environment is so slow. This just doesn't seem very efficient and probably isn't my only issue.

**Comment by khalwat** [comment]
Well, let me know what you end up uncovering.

All SEOmatic is doing is a essentially `craft.app.assets.getElementById()` -- I can probably put a memorization cache on this but I don't think it'll help much in terms of the performance issues you're experiencing.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/38db9055c31e9dd0c4f0bd90c7679a4ea4ed164e

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.20”,
```
Then do a `composer clear-cache && composer update`

**Comment by CraigPedleyCF** [comment]
That works great, thank you. It helps clear out the duplicated query column on the toolbar so we can spot our own queries.
