### ISSUE TITLE
Is it possible to disable `displayPreviewSidebar` per section/channel/page?

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#1017]
### Question
Is it possible to disable displayPreviewSidebar per section?
I have a section that only admins can access to view a series of card designs that are then used as modules throughout the site. So these have a template (admin protected) and site Url so the admin can view the card in array of styles etc when they edit/create. However, I don't need this to be SEO optimised and also I would like to remove the Preview Sidebar from this section.

is there a way to disable these on a section/channel/page basis? 
Also what is the best way to remove this from the 'content SEO Setup' so it doesn't show here and also doesn't negatively impact the scores for this on the dashboard?

**Comment by khalwat** [comment]
The only way to not have it show up in a given section is if the section doesn't have public URLs.

So you should just be able to turn public URLs off for this special section. For previewing the designs, you could just set up a preview template for it, so there wouldn't need to be a frontend template.

Hope that helps.

**Comment by terryupton** [comment]
What do you mean setup a preview template? How would the author access it? If I removed the preview urls in the section then I don't think they'd be able to access it. Am I missing your point?
Thanks.

**Comment by khalwat** [comment]
I thought you might be able to set your own preview targets in Craft CMS without the section having public URLs, but maybe not?

https://craftcms.com/docs/3.x/entries.html#preview-targets
