### ISSUE TITLE
What is the `displayAnalysisSidebar` setting for and what does it do?

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#1018]
### Question
I see a setting for `displayAnalysisSidebar` but I cannot figure out what this is and what it does?
I can't see any Analysis in the sidebar on any entry and I have enabled and disabled.
Is this a legacy setting that is now redundant?

Thanks.

**Comment by khalwat** [comment]
It's not legacy, it's unused -- but it will be used in SEOmatic Pro (once finished :) )
