### ISSUE TITLE
Structured Data - How to set nested values

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#1019]
### Question
I want to add a review to my mainEntityOfPage. So I do the following:
```
 {% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{%set review = craft.entries.section('review').relatedTo(product).one() %}
  {% set author = seomatic.jsonLd.create({
            'type': 'Author',
            'name': review.reviewer
        }) %}
        {% do mainEntity.review(
            seomatic.jsonLd.create({
                'type': 'Review',
                'reviewBody': review.text,
                'author': author
            })
        ) %}
        ```

But SEOmatic removes the author from the review json, why is this?

**Comment by khalwat** [comment]
> But SEOmatic removes the author from the review json, why is this?

`Author` is not a valid schema.org type: https://schema.org/Author

The `author` property of the `Review` schema must be either an `Organization` or a `Person`:

https://schema.org/Review
