### ISSUE TITLE
How to use asset field for SEO image description?

### ISSUE THREAD

**Issue by KatieMFritz** [nystudio107/craft-seomatic#102]
My entries all have a `featuredImage` field, which is an asset.

My assets all have a required `altText` field (plain text) - see screenshot.

**I'm using each entry's `featuredImage` for its SEO Image Source, and I'd like to just pull in the `altText` field that already exists. (How) can I do that in the SEO Image Description Source?**

![screenshot-safs msu edu-2018 05 04-18-43-19](https://user-images.githubusercontent.com/7085184/39656012-0b99bbea-4fcb-11e8-8090-9a75a26da135.png)

**Comment by khalwat** [comment]
This is a case where something like the SEO Images field I discussed:

https://github.com/nystudio107/craft-seomatic/issues/52

...would be useful.  But you can do it yourself with your setup by switching the Image Description source to "Custom" and doing something described here:

https://github.com/nystudio107/craft-seomatic#content-seo-admincp-fields

...such as:

```twig
{entry.someAsset.altText}
```

**Comment by KatieMFritz** [comment]
That worked - thanks!

**Comment by terryupton** [comment]
Should something like this work?
As it seems to fall over on the last bit.
`{entry.teaserImage.one.alt|default(entry.teaserImage.one.title)}`

So this works ok:
`{entry.teaserImage.one.alt|default('Test')}`
and this works ok:
`{entry.teaserImage.one.title}`

But when combined like so, i just get the default fallback from the global field.
`{entry.teaserImage.one.alt|default(entry.teaserImage.one.title)}`

**Comment by khalwat** [comment]
Best advice I can give you is to get it working in a Twig template first, and then paste it into the field @terryupton

**Comment by terryupton** [comment]
Thanks @khalwat but the code does work inside the twig template.
` {{ entry.teaserImage.one.alt|default(entry.teaserImage.one.title) }}`

**Comment by khalwat** [comment]
I'm not sure @terryupton -- but there isn't anything special about how SEOmatic renders that template, it's using Twig internally to do so.

I guess you can try:

```
{{ object.entry.teaserImage.one.alt|default(object.entry.teaserImage.one.title) }}
```

**Comment by terryupton** [comment]
Yeah that has worked. Thanks @khalwat 👍

**Comment by khalwat** [comment]
Check out this feature in SEOmatic 3.1.50 that'll probably make your life easier:

[SEOmatic's ??? Empty Coalesce operator](https://github.com/nystudio107/craft-seomatic#seomatics--empty-coalesce-operator)
