### ISSUE TITLE
Remove or refresh SEOmatic sitemap

### ISSUE THREAD

**Issue by seomatic** [nystudio107/craft-seomatic#1020]
Hi, the SEOmatic sitemap.xml redirects to https://www.wsps.ca/sitemaps-2-sitemap.xml. There are older broken links in the list. How the sitemap can be refreshed? There is no way to remove the site map from the plugin itself. 
Thank you.

**Comment by khalwat** [comment]
What specifically are the broken links? SEOmatic generates the links in the sitemap from Craft's entries, so they should be accurate, assuming Craft is configured properly.

**Comment by seomatic** [comment]
Hi Andrew,

Here is an example of site maps with broken links:

Sitemaps (34 total)
Last Modified
https://www.wsps.ca/sitemaps-2-categorygroup-audiences-2-sitemap.xml
2021-06-14 14:17
https://www.wsps.ca/sitemaps-2-section-communityGroups-2-sitemap.xml
2021-05-10 08:57
https://www.wsps.ca/sitemaps-2-section-contactUs-2-sitemap.xml
2021-11-19 13:09
https://www.wsps.ca/sitemaps-2-categorygroup-eventType-2-sitemap.xml
2021-04-27 17:16
https://www.wsps.ca/sitemaps-2-section-events-2-sitemap.xml
2021-04-28 10:40
https://www.wsps.ca/sitemaps-2-categorygroup-expertise-2-sitemap.xml
2021-07-05 11:11
https://www.wsps.ca/sitemaps-2-section-facts-2-sitemap.xml
2021-05-21 16:50
https://www.wsps.ca/sitemaps-2-section-home-2-sitemap.xml
2021-11-29 13:35
https://www.wsps.ca/sitemaps-2-section-importantUpdates-2-sitemap.xml
2021-11-29 13:24
https://www.wsps.ca/sitemaps-2-categorygroup-importantUpdatesType-2-sitemap.xml
2021-06-10 18:33
https://www.wsps.ca/sitemaps-2-categorygroup-jurisdiction-2-sitemap.xml
2021-06-02 10:22
https://www.wsps.ca/sitemaps-2-categorygroup-languages-2-sitemap.xml
2021-04-27 17:19
https://www.wsps.ca/sitemaps-2-categorygroup-legislationStatus-2-sitemap.xml
2021-04-27 17:19
https://www.wsps.ca/sitemaps-2-section-legislationUpdates-2-sitemap.xml

We launched the site on August 23, 2021. For some reason the structure of the old site is included in the site map.

Also the sitemap settings page is different than what I see on your plugin page (not too much to do here):

***@***.***


Thanks,
Ovi


Ovi Berghezan
Digital Producer/Web Designer, Digital/Direct Marketing
T 416 948 9805

**Comment by khalwat** [comment]
so I clicked on a number of those links in the sitemap, and they all route to pages in Craft CMS

Is it possible that you still have the sold sections in place in Craft? If so, SEOmatic will generate sitemaps for them. You need to remove the old sections that are no longer in use.

**Comment by seomatic** [comment]
We don’t have these pages in Craft. What we can do?

Thanks.

Ovi Berghezan
Digital Producer/Web Designer, Digital/Direct Marketing
T 416 948 9805

**Comment by khalwat** [comment]
Clear your caches? If those pages are not in Craft anymore, they should not be generated by SEOmatic.

**Comment by seomatic** [comment]
OK, this worked! The old sitemap links are still there – but the content is empty:

***@***.***

The SEOmatic will automatically generate new sitemaps? We don’t have a way to setup queue jobs.

Thanks,
Ovi

Ovi Berghezan
Digital Producer/Web Designer, Digital/Direct Marketing
T 416 948 9805

**Comment by khalwat** [comment]
If you want to start clean, you can uninstall and re-install the SEOmatic plugin. You would then need to reconfigure it, though.
