### ISSUE TITLE
Problem using Twig code in Custom URL when Twitter/Facebook OpenGraph Image Source is set to Same As SEO Image

### ISSUE THREAD

**Issue by KarlBishop** [nystudio107/craft-seomatic#1021]
I'm trying to use Twig code in a Custom URL for **SEO Image Source**, with **Twitter Image Source** and **Facebook OpenGraph Image Source** both set to "Same As SEO Image"... but the image does not work for the Twitter and FB slots.

When I change **SEO Image Source** from "From Asset Field" to "Custom URL" there is pre-generated code in the field that looks like this:

    {{ seomatic.helper.socialTransform(entry.shareImage[0], "base", 1, "crop") }}

But when I save this code, I see "No Image Set" in entry Twitter/FB Previews and there is no output in the HTML for twitter:image or og:image.

If I change the Twitter/FB slots to Custom URL at this point, I see this pre-generated code:

    {{ seomatic.meta.seoDescription }}

However, if I change the **SEO Image Source** back to "From Asset Field", and reset the Twitter/FB slots to Custom URL, I see different pre-generated code for each of them:

    {{ seomatic.helper.socialTransform(entry.shareImage[0], seomatic.helper.twitterTransform(), 1, "crop") }}
    {{ seomatic.helper.socialTransform(entry.shareImage[0], "facebook", 1, "crop") }}

I found I can get everything working as desired if I enter separate Custom URLs for all three fields... but I expected the Twitter and Facebook slots to work when set to "Same As SEO Image".

### Versions
- Plugin version: 3.4.20
- Craft version: Craft Pro 3.7.23

**Comment by khalwat** [comment]
Yeah, known issue -- unfortunately you need to do what you've done here, putting that same custom code in each of them.
