### ISSUE TITLE
Content SEO Robots setting not always being respected

### ISSUE THREAD

**Issue by mijewe** [nystudio107/craft-seomatic#1022]
### Describe the bug
- The robots meta tag on my homepage was being rendered as robots="none".
- The Content SEO Robots dropdown for the homepage was set to robots="all".
- Cleared all caches, including SEOmatic metadata caches - no change.
- I overwrote the robots setting on the homepage entry SEO field, cleared cache, no change.
- I overwrote the SEO Title field on the homepage to in order to give it a kick, cleared caches, and then the robots override was respected properly.

### Expected behaviour
- the robots setting to be pulled from the Content SEO.
- when updating the entry SEO field, for the metadata caches to be cleared without needing to manually clear caches

### Versions
- Plugin version: 3.4.17
- Craft version: Craft Pro 3.7.20

**Comment by khalwat** [comment]
When you're saying "entry SEO field" do you mean that you have an SEO Settings field in the layout for the homepage?

**Comment by khalwat** [comment]
Please re-save the home page settings in Content SEO, this should eliminate the issue.

**Comment by daniellelecomte** [comment]
Having this same issue on a site for the home page only. Resaving the Content SEO settings and clearing caching had no effect.

SEOmatic 3.3.37
Craft Pro 3.5.17.1

**Comment by khalwat** [comment]
@daniellelecomte can you file a new issue, and provide detail such as screenshots of settings, URLs to the pages affected, etc?
