### ISSUE TITLE
Seomatic includes disabled sites in sitemaps

### ISSUE THREAD

**Issue by hiasl** [nystudio107/craft-seomatic#1023]
### Describe the bug
We have 12 sites in our craft instance, 4 are disabled. When sitemaps are generated via `craft seomatic/sitemap/generate` they are still generated for disabled sites as well (which is less of a problem except it takes time). 
But: Sitemaps of enabled sites still contain `alternate links` to the disabled other sites, which leads to URLs which 404

### To reproduce
Steps to reproduce the behaviour:
1. Have a Craft installation with multiple sites (in one group)
2. Have at least one of the sites disabled
3. Create an entry, which is available in all including the disabled one
4. Create the sitemaps
5. Look at the sitemaps, and the alternate links.

### Expected behaviour
Only entries of enabled sites should be referenced in sitemaps.

### Versions
- Plugin version: 3.4.20
- Craft version: 3.7.24

**Comment by khalwat** [comment]
How are you disabling these sites?

**Comment by hiasl** [comment]
- Settings > Sites (I guess there should be more than 1...)
- Choose any site (except for the primary)
- On the right side is a lightswitch to enable/disable this this (below the save button), see below:
![Bildschirmfoto 2021-12-03 um 15 45 08](https://user-images.githubusercontent.com/800026/144621727-a46c9a4d-100f-4539-b715-6d819fe32ce4.png)

**Comment by khalwat** [comment]
So the ability to disable sites wasn't added until Craft CMS 3.5 -- looks like I actually lobbied for it too:

https://github.com/craftcms/cms/issues/3005

Currently, SEOmatic keys off of the `hasUrls` site setting so additional conditional logic will need to be added to check to see if Craft is > 3.5.0 and if so, also check the `enabled` setting in the site itself.

**Comment by khalwat** [comment]
Addressed in the above commits.

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.21”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
@hiasl lmk how you go

**Comment by hiasl** [comment]
sorry, was out of office today. I will give you feedback within the next days. thanks for the quick fix.

**Comment by hiasl** [comment]
@khalwat thanks for the fix, we installed it and it works (we checked it with the released version).
