### ISSUE TITLE
Unexpected truncation when using angle bracket in title or description

### ISSUE THREAD

**Issue by elivz** [nystudio107/craft-seomatic#1024]
### Describe the bug
Not sure this is really a bug, per se, but a quirk that I wanted to have documented in the Issues for future searchability. Because SEOmatic runs the title or description text through PHP's `strip_tags` function, a less-than angle bracket immediately followed by another character (e.g. an ascii arrow like `<-` or `<=`, an ascii heart `<3`, or a math equation like `3<4`) will be seen as an HTML tag and everything from that point on in the text will be removed.

I believe this is the expected behavior of the `strip_tags` function. But probably not what content editors would expect when they are setting the SEO values.

### To reproduce
Steps to reproduce the behaviour:
1. Set an entry's title to: `I <3 puppies`
2. Save and check the SEO preview or front-end meta tags.
3. The title will be displayed as `I`

### Versions
- Plugin version: 3.4.20
- Craft version: 3.6.18

**Comment by khalwat** [comment]
Yeah the `strip_tags` is done to prevent injection vulnerabilities; arguably these could be left alone when _pulling_ from content, if we want to assume that content is always safe. I'm just not sure if that's the best assumption.

An alternative might be some kind of way of removing HTML tags that is smarter than `strip_tags`

**Comment by elivz** [comment]
Yeah, definitely wouldn't want to remove sanitation entirely. I haven't tested it extensively, but I wonder if something like this would work:

```
\craft\helpers\HtmlPurifier::process('I <3 <em>puppies</em>', [ 'HTML.Allowed' => '' ]);
// returns: "I &lt;3 puppies"
```

**Comment by khalwat** [comment]
Good idea! Now you can test it extensively... :)

Addressed in the above commit.

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.21”,
```
Then do a `composer clear-cache && composer update`

**Comment by elivz** [comment]
Hmmm, not quite working yet. Looks like SEOmatic renders out the encoded characters verbatim.

![Screen Shot 2021-12-03 at 3 57 52 PM](https://user-images.githubusercontent.com/62592/144671955-567fdb68-43e3-4bf6-8100-03a28eaba935.png)

**Comment by khalwat** [comment]
Yeah not sure how to turn that off in HTML Purifier? Googling didn't help much either...

**Comment by khalwat** [comment]
Okay, I removed the explicit `html_entity_decode()` -- perhaps it was doing it twice.

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.21”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
The updates I pushed have it working as expected with `I <3 Strawberries` in my titles

**Comment by elivz** [comment]
Yep, looking good on my end now too. Thanks!
