### ISSUE TITLE
Include priceValidUntil in product structured data in Craft Commerce

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#1027]
Out of the box SEOmatic supports some structured data for products. However, after a new launch of a Commerce website, I was alerted by Google Search Console of some warnings.

The following warnings were found on your site:
Missing field 'review'
Missing field 'priceValidUntil'
Missing field 'aggregateRating'
No global identifier provided (e.g. gtin, mpn, isbn)
Missing field 'brand'

Whilst most of these fields cannot be assumed and I have raised a thread about global identifier here #1026 I also believe we should discuss and consider auto populating `priceValidUntil`.

My thoughts on this are as follows:

- In most instances we would want to automate this and so a sensible default is perhaps of use. It could still be overwritten and adjusted should users have an edge-case or different take. 
- We would normally get this value based on parameters of the commerce/shop/product anyway, so it would make sense to automate this. 
- In it's default state, this would perhaps set a fixed period (maybe a year) and this would be updated regular (when and how, I will leave open to suggestions).
- If there is a sale, then we would want this to be adjusted based on the sale date (if there is one) and again this points to automation.
- It feels to laborious not to automate this and in reality, how would we know if this date was to change (i.e a sale) if the system/site is managed by a customer. So again, this for me points to automation.

Happy to hear any thoughts on this, but I feel that we would have all the information from the system to enable this to be populated.

**Comment by khalwat** [comment]
All of the items you listed are _warnings_ not errors, and it may make sense for some sites to implement them, and it may not for others.

After reviewing this, I'm not sure it makes sense to have SEOmatic attempt to populate `priceValidUntil`. If this is something that makes sense for your commerce setup to have listed (for many, it may not), you should implement the custom code to do so ala:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

**Comment by bossanova808** [comment]
Should someone dig this up, and want to get rid of `priceValidUntil` warnings, here's a quick direct example of how you might do this in a product page...Andrew's documentation is superb, but a lot to wade through, so sometimes it's useful to have a concrete example to refer to.

Non variant product page:
```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{# Default to prices being valid for 3 months, basically just to get rid of Google warnings...#}
{% set priceValidUntil = now | date_modify('+3 months') | atom %}
{% set offers = mainEntity.offers | merge({'priceValidUntil': priceValidUntil}) %}
{% do mainEntity.offers(offers) %}
```

More about this, showing an example for a variant product listing at https://craftcms.stackexchange.com/questions/36697/outputting-structured-product-attributes-in-json-ld-code-with-seomatic/36701#36701

**Comment by khalwat** [comment]
Thx @bossanova808 -- I should note that the warnings from Google are just that... Google will still consume the JSON-LD, they just _recommend_ that you have certain fields set.

Errors are the only things that indicate that the JSON-LD is not being consumed by Google.

**Comment by bossanova808** [comment]
Indeed...but they send you these emails that make you feel it's a problem ;)
