### ISSUE TITLE
Variables from the .env are not processed properly 

### ISSUE THREAD

**Issue by alexanderloewe** [nystudio107/craft-seomatic#1028]
Variables from the .env are not processed properly, inside the structured data. See the screenshot below.

<img width="498" alt="Bildschirmfoto 2021-12-11 um 22 00 58" src="https://user-images.githubusercontent.com/69263307/145820347-471b985f-cff0-44e7-bab9-1842b833b6b7.png">

**Comment by khalwat** [comment]
Correct, that's not going to work. `.env` variables only work if they are the entirety of a string.

I'd suggest switching to using aliases, if that's what you want to do here.
