### ISSUE TITLE
Unable to specify canonical URL within site

### ISSUE THREAD

**Issue by davist11** [nystudio107/craft-seomatic#1029]
### Describe the bug
For the Commerce products on our site, we want to _always_ output a canonical URL to the correct variant.

`shop/{slug}` - Displays the default variant
`shop/{slug}?variant={variantId}` - Display a specific variant of that product (this could also be the default variant)

I was trying to output the canonical URL to always have the query string.

```twig
{% set selectedVariant = product.defaultVariant %}
{% if selectedVariantId != product.defaultVariant.id %}
    {% set selectedVariant = product.variants | where(variant => variant.id == selectedVariantId) | first %}
{% endif %}

{% do seomatic.meta.canonicalUrl(selectedVariant.url) %}
```

But, it seems like because of this code, you can't set the canonical URL to something else within the site. Should that code on line 211 be `=== false` ?

https://github.com/nystudio107/craft-seomatic/blob/b1ee8b9f5de58f677bf3ffc034af5665abf31725/src/models/MetaGlobalVars.php#L205-L219

Because I can successfully do

```twig
{% do seomatic.meta.canonicalUrl('http://google.com') %}
```

### To reproduce
Steps to reproduce the behaviour:
1. Try to override the `meta.canonicalUrl` to another URL within the site you are currently on
2. See that the output will end up using the value from `{seomatic.helper.safeCanonicalUrl()}`

### Expected behaviour
I expected to be able to set the canonical URL to a URL with the site

### Versions
- Plugin version: 3.4.17
- Craft version: Craft Pro 3.7.19.1

**Comment by khalwat** [comment]
So the expression:
```php
             if (strpos($this->canonicalUrl, 'craft.app.request.pathInfo') !== false) { 
```
..will only be truthy if the text `craft.app.request.pathInfo`  _is_ found in the string, so that logic is correct: https://www.php.net/manual/en/function.strpos.php

As you noted, this works for you:
```twig
{% do seomatic.meta.canonicalUrl('http://google.com') %}
```

So if I had to guess, something else is amiss in the way you're setting the `canonicalUrl`. Because you should be able to set it to whatever you want.

**Comment by davist11** [comment]
> ..will only be truthy if the text craft.app.request.pathInfo is found in the string, so that logic is correct

Right exactly. So the URL of the request is `http://site.com/shop/be-ew-a-00001`, and I am setting the `canonicalUrl` to `http://site.com/shop/be-ew-a-00001?variant=1234`. So that condition would be truthty, and then the `canonicalUrl` would be reset `$this->canonicalUrl = '{seomatic.helper.safeCanonicalUrl()}';`

**Comment by khalwat** [comment]
But it's the _literal_ text `craft.app.request.pathInfo` that it's looking for, not the value that might be in `craft.app.request.pathInfo`

That check is in there to update older settings that by default had `craft.app.request.pathInfo` in them.

**Comment by davist11** [comment]
Ahhh, duh. Ok, lemme dig in and see if I can see why this value won't work

**Comment by davist11** [comment]
Ok, so tracked something down. The canonical url property is stripping query params from the string passed in.

```twig
{% do seomatic.meta.canonicalUrl('http://google.com?variant=123') %}
```

Results in

```html
<link href="http://google.com" rel="canonical">
```

Any thoughts?

**Comment by khalwat** [comment]
It's not considered best practice to have URL params in the canonical URL; SEOmatic strips them out by default:

https://moz.com/community/q/topic/57629/why-is-rel-canonical-pointing-at-a-url-with-parameters-bad
