### ISSUE TITLE
humans.txt <link> generated even when disabled

### ISSUE THREAD

**Issue by evanwarner** [nystudio107/craft-seomatic#103]
Disabling humans.txt correctly results in a 404 page, but I'm noticing this is still generated in my site's head:
`<link type="text/plain" href="/humans.txt" rel="author">`

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/2d4ab873d19a3f4b4ca25abcfd31b79c19d2f9d3
