### ISSUE TITLE
Twig SEO Image Source not working in Content SEO

### ISSUE THREAD

**Issue by bavocorteville** [nystudio107/craft-seomatic#1030]
### Describe the bug
Using a twig expression in Content SEO doesn't seem to work. If I use the same code for the entry itself (override), the image will be used correctly.

I'm using the following code: 
`{{ entry.fieldHero.one().fieldImage.one().getUrl({'mode': 'crop', 'width': 1200, 'height': 630, 'quality': 82, 'position': 'center-center'})|default(null) }}`

fieldHero is a Neo field.

### Versions
- Plugin version: 3.4.21
- Craft version: 3.7.25.1

**Comment by khalwat** [comment]
If you put this code into the template for that section, does it work?

All SEOmatic does is render that Twig code, and use the result.

**Comment by bavocorteville** [comment]
Since I use eager loading in the template, it obviously only works in the template if I replace `fieldImage.one() `with `fieldImage|first`. I've tested both the `|first` and the `.one()` in content SEO but both do not work. `.one()` does work if I use the override for the SEO field of the entry (same value as in content SEO).

![image](https://user-images.githubusercontent.com/2085698/146222573-2fd43bb0-c818-4a30-bb70-ce5bd7e726a4.png)

![image](https://user-images.githubusercontent.com/2085698/146222454-753c4b18-6984-4750-9b31-06e5ab34ea1f.png)

**Comment by khalwat** [comment]
So again, all SEOmatic is doing is rendering your Twig code, and use the result.

Are you sure the issue isn't that you need to _also_ put this Twig code into your Facebook and Twitter settings?

**Comment by bavocorteville** [comment]
You're right. If I change "same as SEO image" in Facebook's Content SEO to "custom URL" it works correctly. My problem has been solved with this, although you would expect that with the original settings it should also work.
