### ISSUE TITLE
SEO Settings Field Error - Trying to get property 'metaBundleSettings' of non-object

### ISSUE THREAD

**Issue by mcjackson18** [nystudio107/craft-seomatic#1031]
After adding the SEO Settings field to certain elements and trying to edit the element in the CP the error _Trying to get property 'metaBundleSettings' of non-object_ is shown.

For example, using Verbb's Gift Voucher plugin and adding the field to a voucher field layout.

![Screenshot 2021-12-15 at 13 38 55](https://user-images.githubusercontent.com/39083512/146197691-3d9b511e-70aa-4ace-bb0c-ffbddd0a0a7f.png)

**Versions**
SEOmatic version: 3.4.21
Craft version: 3.7.25.1
Gift Voucher version: 2.7.0

**Comment by khalwat** [comment]
Is this happening only with Voucher elements?

I've never used the plugin, but it seems like adding an SEO Settings field to a Voucher field layout probably doesn't make sense? Do Vouchers have URLs?

**Comment by mcjackson18** [comment]
@khalwat, thanks for quick reply. Vouchers are purchasables and so have a page where a user can purchase a gift voucher.

I was also getting the error with Verbb's Events elements but I see there's been up an update to the plugin to add support for SEOmatic (using EVENT_REGISTER_SEO_ELEMENT_TYPES).

I take it this means the Gift Voucher plugin needs updating rather than it being a bug in SEOmatic?

**Comment by khalwat** [comment]
Well, it's arguable whether it should be built into SEOmatic, or built into the plugin providing the functionality. But it could go in either place.

I'll have a chat with Josh to see what he thinks.

Regardless, SEOmatic shouldn't be throwing an error if no SEO Element is available for the type.

**Comment by mcjackson18** [comment]
Thanks @khalwat. After some further testing we're also getting the same error with our own Bundles plugin (custom purchasables which have their own URLs).

**Comment by khalwat** [comment]
Right, and that's what I'd expect. SEOmatic can't automatically pull information from custom elements.

But it at least should not error.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/c5594dbda0d3df35cda8641e7862743c3e2eb8c4

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.22”,
```
Then do a `composer clear-cache && composer update`

**Comment by mcjackson18** [comment]
All working now, thanks for the quick fix.
