### ISSUE TITLE
How to add custom Canonical tag on Certain Blogs?

### ISSUE THREAD

**Issue by 1gauravlakhani** [nystudio107/craft-seomatic#1032]
### Question
Hi Team, 

How do we add custom canonical tag on some of the blogs? 

### Additional context
Add any other context or screenshots about the support request here.

**Comment by khalwat** [comment]
There are many ways to do this, either via Twig code:

https://nystudio107.com/docs/seomatic/using.html#twig-templating

...or via the CP.

Probably the easiest way is for you to add an SEO Settings field to your Blog field layout, and override the canonical URL field as needed there.
