### ISSUE TITLE
Fetching tracking scrips data with GraphQL

### ISSUE THREAD

**Issue by Stalex89** [nystudio107/craft-seomatic#1033]
Hello, is there a way to fetch the tracking scripts data with GraphQL queries ? I cannot find something in the documentation (also checked the GraphQL example, found nothing there).

Thank you

**Comment by khalwat** [comment]
Yes, example here: https://nystudio107.com/docs/seomatic/advanced.html#graphql-query-support

```graphql
{
  seomatic (uri: "/") {
      metaScriptContainer
  }
}
```

**Comment by Stalex89** [comment]
Thank you for the answer, however I still get no data from GraphQL response, is there something more to be set besides Google Analytics Measurement/Tracking ID to make it work ?

PHP version | 7.4.26
Database driver & version | MySQL 8.0.27
Craft edition & version | Craft Pro 3.7.25.1
SEOmatic version | 3.4.20

<img width="631" alt="Screenshot 2021-12-17 at 09 50 44" src="https://user-images.githubusercontent.com/23526237/146517236-39304952-c6af-4a2e-9ca8-05b058500bc6.png">

<img width="1683" alt="Screenshot 2021-12-17 at 09 51 18" src="https://user-images.githubusercontent.com/23526237/146517251-0e7da506-a2d1-4d2e-8f15-4bc9024f0614.png">

**Comment by khalwat** [comment]
Your environment is set to `local` -- by default, all tracking scripts are disabled in the local environment.

You can override the environment if you wish to test that as per: https://nystudio107.com/docs/seomatic/advanced.html#graphql-query-support

```graphql
{
  seomatic (uri: "/" environment: live) {
      metaScriptContainer
  }
}
```
