### ISSUE TITLE
MainEntityOfPage not returning the main Entity of the page

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#1034]
### Describe the bug
Not sure why this is happening, but we have a setup where we add a couple of additional fields for the our Commerce Products:

The code looks like this:
```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{% if mainEntity  %}

    {% do mainEntity.brand(
        seomatic.jsonLd.create({
            'type': 'Brand',
            'name': product.brand.one.title ?? currentSite.name,
        })
    ) %}

    {% if product.ean %}
        {% do mainEntity.gtin(product.ean) %}
    {% endif %}

    {% set review = reviews.all()|first %}
    {% if review %}
        {% do mainEntity.aggregateRating(
            seomatic.jsonLd.create({
                'type': 'AggregateRating',
                'ratingValue': product.aggregatedRating,
                'reviewCount': reviews.count()
            })
        ) %}

    {% endif %}
{% endif %}
```

It works fine in one set-up, but not in another. here it throws:
Invalid Argument – yii\base\InvalidArgumentException
Property brand doesn't exist

So on further inspection, the mainEntityOfPage seems to be the class `WebPage`. However, the settings for the products are correctly set to Product. And the generated JSON is set to:

```

{
--
  | "@context": "http://schema.org",
  | "@graph": [
  | {
  | "@type": "Product",
  | "mainEntityOfPage": "https://leenders.nitro/babboe-e-carve-db-v-db-a",
  | "name": "test",
  | "offers": {
  | "@type": "Offer",
  | "availability": "http://schema.org/InStock",
  | "offeredBy": {
  | "@id": "https://leenders.nitro/#identity"
  | },
  | "price": "3499.00",
  | "priceCurrency": "EUR",
  | "seller": {
  | "@id": "https://leenders.nitro/#identity"
  | },
  | "url": "https://leenders.nitro/babboe-e-carve-db-v-db-a"
  | },
  | "sku": "817548-0",
  | "url": "https://leenders.nitro/babboe-e-carve-db-v-db-a"
  | },


```

So why does 
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}

Return a WebPage instance, instead of a Product instance?

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Versions
- Plugin version:
- Craft version:

**Comment by khalwat** [comment]
I don't have enough information to help you, other than to say that you should look for differences between the setup where it works, and the setup where it does not.

**Comment by lenvanessen** [comment]
@khalwat but if i'm not mistaken:
`{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}`

Should have returned a `Product` class in this instance right, since the `type` of the json that is generated by SEOmatic is `Product` and not `WebPage`?

**Comment by lenvanessen** [comment]
@khalwat even though the Content Seo settings showed Product, for some reason it wasn't set. After resaving those settings it worked.

**Comment by khalwat** [comment]
Correct, the `mainEntityOfPage` should be of the `Product` class if that's what it is set to. Check to ensure it isn't being overridden somewhere?

**Comment by webtrend** [comment]
Thanks works now
