### ISSUE TITLE
Having trouble getting the expected robots value when toggling override for an entry. 

### ISSUE THREAD

**Issue by joshuapease** [nystudio107/craft-seomatic#1036]
### Question
Not sure if this is a bug or if I should be accessing the robots value for an entry in a different way. 

I'm accessing the robots value for an entry like so:

```
{{ entry.seo.metaGlobalVars.robots }}
```

When I manually override an entry's robots value to `none` I get the expected string of `none` in my template. 

<img width="420" src="https://user-images.githubusercontent.com/2145998/148470771-0a3fa411-a952-4161-8ebd-35ed3d3c095c.png">

However, when I turn off that override and save. I still get the `none` value printed in my template. The `none` value is also still present for that element in the `craft_content` table. 

<img width="420" src="https://user-images.githubusercontent.com/2145998/148470952-17a018f6-aa3c-4273-9353-59a0b39ab387.png">

Is there a different way that I should get the inherited value of robots for an entry?

**Comment by khalwat** [comment]
When you turn it off, the value is still there, it is just not overriding it.

What is it that you're attempting to do here? Normally you shouldn't need to access an SEO Settings field value in this manner?

If you want to get the current computed value for a route, you should look at:

```twig
{{ seomatic.meta.robots }}
```

https://nystudio107.com/docs/seomatic/using.html#general-variables

**Comment by khalwat** [comment]
Let me know if you need further assistance with this.

**Comment by joshuapease** [comment]
Thanks for your help. I guess I was a little thrown off by these docs https://nystudio107.com/docs/seomatic/fields.html#template-access. 

My example of using it in a template doesn't make tons of sense, I was just using that to try and debug and explain the issue I was hitting. 

The real use case I'm trying to solve is to send the correct Robots value over to Algolia (Using Scout's `transformer` method)  so I can filter out entries that have Robots set to `none` or `noEntries`.

In that scenario, I'm not actually on a route. Is there any way to pass a route over to SEOMatic so I could get the computed `robots`.

**Comment by khalwat** [comment]
Are you doing this via Twig or PHP or...?

**Comment by khalwat** [comment]
In Twig, you'd do something like:

```twig
{% do seomatic.helper.loadMetadataForUri(URI, SITE_ID) %}
```

..and then access `{{ seomatic.meta.robots }}`

In PHP you'd do:

```php
Seomatic::$plugin->helper->loadMetadataForUri(string $uri = '', int $siteId = null)
```

**Comment by joshuapease** [comment]
I'm doing it in PHP. 

Seems like the following is how I'd get that computed robots value? 

```php
Seomatic::$plugin->metaContainers->metaGlobalVars->robots;
```

**Comment by khalwat** [comment]
Yep

**Comment by MangoMarcus** [comment]
> In Twig, you'd do something like:
> 
> {% do seomatic.helper.loadMetadataForUri(URI, SITE_ID) %}
> 
> ..and then access `{{ seomatic.meta.robots }}`
> 
> In PHP you'd do:
> 
> Seomatic::$plugin->helper->loadMetadataForUri(string $uri = '', int $siteId = null)

@khalwat It would be good to get this recommendation in the documentation. It seems a somewhat common use case, mine is also to check the "robots" value of an arbitrary entry, in order to exclude them from an Algolia index using the Scout plugin.


Thanks!
