### ISSUE TITLE
GraphQL : SEOmatic field missing on Solspace calendar events

### ISSUE THREAD

**Issue by denisyilmaz** [nystudio107/craft-seomatic#1037]
### Describe the bug
I don't know if this is the right place to report this bug (if this is something Solspace would need to solve, please let me know).

When adding SEOmatic to a project I am able to query for the `seomatic` fields on all my entry types. But with Solspace events, which can be queried with … 
```gql
{
  solspace_calendar {
    event {
      id
      slug
      title
      url
      seomatic {
        metaTitleContainer
      }
    }
  }
}
```
… it is not possible to retrieve the SEOmatic fields for these events within GQL.

### To reproduce
Steps to reproduce the behaviour:
1. Add Solspace Calendar Plugin and SEOmatic and add a default event
2. Go into the GraphQL Explorer inside Craft CMS CP
3. Query for:
```gql
{
  solspace_calendar {
    event {
      id
      slug
      title
      url
      seomatic {
        metaTitleContainer
      }
    }
  }
}
```
4. See error message:  
```json
{
  "errors": [
    {
      "message": "Cannot query field \"seomatic\" on type \"CalendarEventInterface\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 8,
          "column": 7
        }
      ]
    }
  ]
}
```

### Expected behaviour
I would expect the `seomatic` field being available to `CalendarEventInterface` elements the same way as for `EntryInterface` elements.

#### Alternative expected behaviour
Another solution would be to be able to query the SEOmatic field by entry ID. Currently it is only possible to query by `uri`. But Solspace GraphQL implementation does not return a `uri` (only the `slug` and the full `url`)

Example:
```gql
{
  solspace_calendar {
    event {
      id
      slug
      title
      url
    }
  }
  seomatic(id: 123, siteId: 1) {
    metaTitleContainer
  }
}
```

### Versions
- Plugin version: 3.4.21
- Solspace Calendar version: 3.3.8
- Craft version: 3.7.28

**Comment by khalwat** [comment]
I think we know what needs doing to fix this

**Comment by khalwat** [comment]
Fixed in: https://github.com/nystudio107/craft-seomatic/commit/8f65afcf6ecbf0ab6e2bad3cc2a0f0e4293205af

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.22”,
```
Then do a `composer clear-cache && composer update`

**Comment by denisyilmaz** [comment]
hm, i've tried this here locally but am unable to query the `seomatic`field after updating to `3.4.22`:

![image](https://user-images.githubusercontent.com/4189607/149288472-b3273dd4-fd31-418c-9607-ba14da0c13ad.png)

from `composer.lock` file for version confirmation:
```
    "aliases": [
        {
            "package": "nystudio107/craft-seomatic",
            "version": "dev-develop",
            "alias": "3.4.22",
            "alias_normalized": "3.4.22.0"
        }
    ],
```

i cleared cache etc. nothing helped getting the new feature to work.

**Comment by khalwat** [comment]
It's possible that some work might need to be done from Solspace to make this happen -- can you open a ticket for them as well, and link them to this one?

**Comment by khalwat** [comment]
@denisyilmaz never mind, I figured out what was wrong. We just need to wait until after plugins are loaded before registering our types, otherwise we miss any types that plugins like Solspace Calendar may register

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/e2b23c2798fd5156ba27877662d80ef6d850a2be

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.23”,
```
Then do a `composer clear-cache && composer update`

**Comment by denisyilmaz** [comment]
@khalwat sorry for my late response. I was only able to work on the project again now. After updating to the released 3.4.23 I tested it on my local environment but am not able to query for the `seomatic` field inside a solspace event.

before i dig deeper on what might cause this on my end, can you confirm that this is working in a local environment?

**Comment by khalwat** [comment]
@denisyilmaz can you clear all caches first, including any GraphQL caches?

**Comment by khalwat** [comment]
So @denisyilmaz I just tested it with this query:

```graphql
{
  solspace_calendar {
    event {
      id
      slug
      title
      url
    }
  }
  seomatic {
    metaTitleContainer
  }
}
```

...and it's working as expected:

<img width="829" alt="Screen Shot 2022-02-05 at 4 49 10 PM" src="https://user-images.githubusercontent.com/7570798/152660159-043bc0cc-a419-44fb-be9e-ead564a86b1f.png">

Please make sure you have cleared your GraphQL schema caches

**Comment by denisyilmaz** [comment]
@khalwat in your query the `seomatic` field is not inside the event object, so you are querying for the metaTitle of the homepage. Which is working fine.
What is your result If you move the field into the event object itself?

**Comment by khalwat** [comment]
So I logged every type that comes through in the `TypeManager::EVENT_DEFINE_GQL_TYPE_FIELDS` event:

```
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: ElementInterface
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: StructureInterface
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: UserInterface
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: User
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: Element
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: EntryInterface
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: FileContents
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: homepage_homepage_Entry
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: blog_blog_Entry
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: blog_review_Entry
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: AssetInterface
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: site_Asset
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: GlobalSetInterface
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: globals_GlobalSet
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: CategoryInterface
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: category_Category
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: VariantInterface
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: clothing_Variant
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: ProductInterface
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: clothing_Product
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: default_Event
2022-02-06 21:57:13 [-][1][-][trace][nystudio107\seomatic\{closure}] typeName: Sale
```
and it doesn't appear that Solspace Calendar actually registers a generic `CalendarEventInterface` at all, it only registers the specific event fields, in the form of `handle_Event` (you can see them registering the `default_Event` type in the above listing.

Registering the generic interface for the element type (`EventInterface::getName()` in this case, or `CalendarEventInterface`) is something all of the other element types do.

If they are able to add this to Solspace Calendar, then SEOmatic will work with it as you desire. Without them adding this support, though, unfortunately it won't work.

**Comment by denisyilmaz** [comment]
@khalwat thanks for the insight. I will create a FR on Solspace to ask them if its possible for them to register the generic interface.
Just out of curiosity: if the `default_Event` type is registered, shouldn't this work then?
```gql
{
  solspace_calendar {
    event {
      id
      slug
      title
      url
      ... on default_Event {
        seomatic {
          metaTitleContainer
        }
      }
    }
  }
}
```

Because I tested this and it does not work. Is the `CalendarEventInterface` needed to work with `default_Event`?

**Comment by khalwat** [comment]
No, that wouldn't work because SEOmatic registers its types on the generic interfaces. It doesn't know about every single instance of the element.

**Comment by denisyilmaz** [comment]
i see, thanks for the explenation!

I think you already saw this: solspace updated the plugin and its now possible to query for the `seomatic` fields inside the events object!
so this is resolved! 👍
