### ISSUE TITLE
Client added SEOmatic on prod before it was added locally

### ISSUE THREAD

**Issue by rossnorthrup** [nystudio107/craft-seomatic#1038]
### Question
A client added and licensed SEOmatic on the production site prior to this being added locally and I am having issues syncing my local to prod since Seomatic is already there. I would like to keep the version they licensed however I am having issues lining up the project config.
Any advice on taking prod project config, adding it locally and pushing it back up?

**Comment by khalwat** [comment]
So this isn't really specific to SEOmatic, but if you're going to use Project Config, probably you want to set `allowAdminChanges` to `false` in your `config/general.php`.

This will prevent admin changes from being made on the production site, which is the core of the issue you're running into here.

More on how to use Project Config without tears here:

https://craftcms.com/docs/3.x/project-config.html#environment-setup

Hope this helps!
