### ISSUE TITLE
Frontend Templates GraphQL Query Not Respecting `site` or `siteId` params (always loading default)

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#1039]
### Describe the bug
I'm trying to be able to load robots.txt for multiple sites via GraphQL, and I'm using the docs from https://nystudio107.com/docs/seomatic/advanced.html#frontend-templates-graphql-queries as a guideline.

I'm able to get `robots.txt` to come up via GQL, but only for the default site (and by this I mean the site we created first, and as it just so happens the handle of the site is `default`). Using both `siteID` and `site` seem ineffective.

I've tried the same query in Next, as well as the GraphQL tool that comes with Craft and gotten the same results (could it be my query?)

```
{
  seomatic {
    frontendTemplates(site: "australia", type: robots) {
      filename
      contents
    }
  }
}
```
(where "australia" is just a site handle that's not the first site we created in our Craft instance)

### To reproduce
1. Go to `SEOmatic` from the sidebar,  then `Global SEO`
2. Click on `Robots`
3. Change the site to the site want to change the robots for using the dropdown at the upper left
4. Make changes (either arbitrary or meaningful), save, refresh the page to make sure that changes are persisting
5. Go to `GraphQL` on the sidebar, then the `GraphiQL` link
6. Enter the query from above, but leave `site` blank. It should return a robots.txt (the one from the first site in Craft)
7. Enter the query from above, but leave `site` filled in, and _not_ the first site in the list.
8. The results from 6 & 7 should be different (meaning that the `site` parameter is being used)

### Expected behaviour
When using the query from https://nystudio107.com/docs/seomatic/advanced.html#frontend-templates-graphql-queries, I expect that `site` pulls in the `robots.txt` for each different site as definied within seomatic

I have several different sites on the same instance of Craft that each need their own version of robots.txt and I would like to serve them up headless via Graphql

### Versions
- Plugin version: `3.4.21`
- Craft version: `3.7.28`

**Comment by khalwat** [comment]
Fixed in: https://github.com/nystudio107/craft-seomatic/commit/0ce6b4deab5e8a0cc9da90debdd7163628dfc8fb

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.22”,
```
Then do a `composer clear-cache && composer update`

**Comment by ghost** [comment]
Checked this out today and seems to work. Thanks so much 🙇‍♂️
