### ISSUE TITLE
Changing Section / Category handle breaks Content SEO page

### ISSUE THREAD

**Issue by mark-chief** [nystudio107/craft-seomatic#104]
Craft v3.0.6
SEOmatic v 3.0.1

Renaming a Section or Category group handle breaks the "SEOmatic > Content SEO > Section Title" page.

`Call to a member function getEntryTypes() on null`

The Section or Category title doesn't update either. In the below screenshot it should be "Features", "Sectors" and "Primary Categories". I guess this is the reason for above, as they link off to URLs with the old handle in them.

<img width="347" alt="screen shot 2018-05-10 at 11 42 14" src="https://user-images.githubusercontent.com/18699249/39866149-595653a4-5447-11e8-84c9-5ae8099f650f.png">

**Comment by khalwat** [comment]
Internally referencing things by by `id` rather than `handle` should fix the issue.

**Comment by boldenamsterdam** [comment]
Looks similar as the old bug we found ( #63 )

We are also experiencing the issue again. Is there maybe a status update?
If so, then we can communicate this with a client of ours 🙂

Thnx! ✌️

**Comment by boldenamsterdam** [comment]
Hi @khalwat 

Can you help us out?

Our client is having issues, i.e. an incorrect sitemap – and we would love to manage their exceptions on how/when we can resolve this.

Looking forward hearing from you, thanks in advance!

**Comment by khalwat** [comment]
I'm definitely definitely to be fixing this.

**Comment by khalwat** [comment]
As a temporary fix @boldenamsterdam you can uninstall and re-install the plugin, and it will fix any renamed section handles. You will however lose any data you've entered into SEOmatic.

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-seomatic/commit/85018e8f317b3d0d8061072be500e72a43f4ea4c

Once SEOmatic 3.0.24 is released, you'll just need to go to the Section in question via Settings -> Sections, click on the section, and click Save.
