### ISSUE TITLE
All sitemaps get cleared when changing a seomatic plugin setting

### ISSUE THREAD

**Issue by WHITE-developer** [nystudio107/craft-seomatic#1041]
### Describe the bug
As soon as you change any seomatic setting, for example a "Content SEO" section, all sitemaps get removed (and also our blitz caching). I can imagine that it should refresh when you edit the sitemap settings there, but everything seems like a bug?

### To reproduce
Steps to reproduce the behaviour:
1. Make sure all the sitemaps are generated
2. Do any change in the seomatic plugin
3. All sitemaps are removed now and have to regenerate

### Expected behaviour
The sitemaps should still exist. Maybe only when you change a sitemap setting it should remove.

### Versions
- Plugin version: 3.4.22
- Craft version: Craft Pro 3.7.28

**Comment by khalwat** [comment]
This is normal and expected behavior. When changes are made, the caches invalidate, and the sitemaps get regenerated.

Sitemaps only ever exist in generated form in a cache.

Settings outside of the sitemap settings can also affect the content of the generated sitemaps.
