### ISSUE TITLE
Sitemaps still being automatically generated although setting is disabled

### ISSUE THREAD

**Issue by andreasbecker** [nystudio107/craft-seomatic#1042]
### Describe the bug
**Regenerate Sitemaps Automatically** is disabled but the jobs are still added to the queue. Already released all jobs from the queue by executing `./craft queue/release all`

### To reproduce
Steps to reproduce the behaviour:
1. Disable "Regenerate Sitemaps Automatically"
2. Save an entry
3. Check if a sitemap generation job was added to the queue

### Expected behaviour
Jobs for regenerating sitemaps should not being added to the queue

### Screenshots
![Bildschirmfoto 2022-01-18 um 15 00 29](https://user-images.githubusercontent.com/661734/149952911-89c0e929-5f3c-4b67-9fea-3de2235f82cb.png)

![Bildschirmfoto 2022-01-18 um 15 04 46](https://user-images.githubusercontent.com/661734/149952907-70a357c8-fef1-4944-9e0c-8d8c3e83d3df.png)

### Versions
- Plugin version: 3.4.21
- Craft version: 3.7.26

**Comment by khalwat** [comment]
I'm unable to reproduce this issue. I killed the queue runner container so queue jobs would stay pending, and then did the steps to reproduce above:


https://user-images.githubusercontent.com/7570798/149969718-91b25d41-7913-4a23-9837-d047cbda8320.mov

No queue jobs were generated with the **Regenerate Sitemaps Automatically** setting off

I can offer you two potential causes for what you're seeing:

1. Sitemaps will be regenerated if they don't exist in the cache (or the data cache was somehow cleared), and someone hits the sitemap on the frontend, which would cause it to need to be regenerated
2. Blitz does something to trigger the sitemap regeneration
