### ISSUE TITLE
Two different sites overwrite each others SEO Output

### ISSUE THREAD

**Issue by martinherweg** [nystudio107/craft-seomatic#1045]
### Question
We have some weird behaviour for two client sites, only on the homepage one site has the output of the other and when I clear the SEOmatic metadata cache of the site displaying the wrong data it displays the correct data on the cleared site but then the other sites homepage is using the data from the cleared site.

The sites are https://pl-klinik.de/ which uses the SEO data of https://kinexon.com/ right now.

It happened after we updated SEOmatic on pl-klinik to 3.4.21

I have no clue what to check anymore so any direction would be appreciated thanks.

### Additional context
- Checked compiled templates on the server, there seems no evidence of the other site
- In the seomatic_metabundles table it's the same, no content of the other site.
- kinexon.com runs SEOmatic 3.3.30

Thanks for the help.

**Comment by khalwat** [comment]
Are you running these two sites on the same VPS? If so, this is due to you having the same cache shared amongst both sites.

You set this via `id` setting -> https://github.com/craftcms/craft/blob/main/config/app.php#L23

**Comment by martinherweg** [comment]
@khalwat Hey Andrew, thanks for the very fast answer.

Yes the two sites are on the same VPS as far as I know, but they both have their own users both for server and database.
There was no id set but now that I've set it the error is still happening.

Cheers,
Martin

**Comment by khalwat** [comment]
You set them both to a totally separate id, and restarted the various services?

What caching method is being used on the site(s)?

**Comment by martinherweg** [comment]
Yes on the totally seperate ids, for the rest I'll come back to you tomorrow when our Dev Ops person is back in.

On the caching site it's using basic craft caching, no static or redis.

**Comment by khalwat** [comment]
This is almost certainly the same cache being used by both sites in some manner or form, I can't think of how else this could occur.

**Comment by martinhellwagner** [comment]
@khalwat 

You were absolutely right: we had the same key prefix in the Memcache config of the two projects in question. Corrected that to use the App ID from the `.env` file instead. Thanks for pointing us in the right direction! 🙏🏼
