### ISSUE TITLE
Twitter / Facebook Image Source still visible when field turned off

### ISSUE THREAD

**Issue by spib** [nystudio107/craft-seomatic#1047]
We have an SEO Settings field (called seoPage) assigned to a field layout. We then updated the field settings to turn on the twitter and facebook tabs and enabled Title, Description and Image fields for each tab. 

We then turned off the Image field for both Facebook and Twitter tabs, but when you edit an entry where that field is present, the Twitter Image and Facebook Image fields are both still visible

![image](https://user-images.githubusercontent.com/512036/151163220-79cd29e0-6353-4dc8-b426-241c5c6a6802.png)

![image](https://user-images.githubusercontent.com/512036/151163116-271ce952-ee91-4133-a134-4c5de6665c3e.png)

Is this expected? And is there any way around it?

**Comment by khalwat** [comment]
Not expected. I will have a look.

**Comment by khalwat** [comment]
@spib what version of SEOmatic are you using? I'm unable to replicate this with the current version, 3.4.23.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/8178b3ae75e854e2fb651e2ee96268515759fa49

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.23”,
```
Then do a `composer clear-cache && composer update`

**Comment by spib** [comment]
Yep, that worked, thanks for much for the quick response

**Comment by khalwat** [comment]
It will be released shortly.
