### ISSUE TITLE
Remaining characters not shown when pasting

### ISSUE THREAD

**Issue by karensg** [nystudio107/craft-seomatic#1049]
### Describe the bug
When pasting a long text into the SEO description field, the remaining characters are now shown.

### To reproduce
1. Go to SEO Tab
2. Paste a long text
3. Notice that the remaining characters are not shown

### Screenshots
![image](https://user-images.githubusercontent.com/359682/151217701-6d46b21f-a8ff-40bc-9305-443e4e3b8c4d.png)

### Versions
- Plugin version: latest: 3.4.22
- Craft version: 3.7.30.1

**Comment by khalwat** [comment]
This is a plain old text field provided by Craft, with a limit on the number of characters that it accepts set in SEOmatic -> Plugin Settings -> Titles where you can change the **Max SEO Description Length** to whatever you like.

**Comment by karensg** [comment]
Did some more extra testing, let me clarify.
When you first click "Override", you are not able to fill in more than 160 characters. After you refresh the page, you actually are:
![image](https://user-images.githubusercontent.com/359682/151550292-ce1be8ef-7601-4e18-87d6-2fe7ffa15120.png)
What is the reason this the different behavior? I think that the second option would be better.

**Comment by khalwat** [comment]
That was a good one @karensg 

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/42466f75b95773af8b8a46d07a8cb5ba79bbd456

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.23”,
```
Then do a `composer clear-cache && composer update`
