### ISSUE TITLE
Enabling gtag.js doesn't render gtagBody.twig

### ISSUE THREAD

**Issue by apticknor** [nystudio107/craft-seomatic#105]
I have enabled gtag via the control panel.

![screen shot 2018-05-11 at 1 25 53 pm](https://user-images.githubusercontent.com/2294059/39940438-e9cecbe6-551e-11e8-8c2c-92afb4e8d13f.png)

Then checked my source to see that the code has been generated. I see the gtagHead.twig template rendered properly but the script for gtag itself isn't anywhere in the markup.

![screen shot 2018-05-11 at 1 27 56 pm](https://user-images.githubusercontent.com/2294059/39940501-244bde94-551f-11e8-8900-7a67b5388de6.png)

After digging around in the repo I found the template - gtagBody.twig but the code doesn't seem to ever render it. I tried debugging and dumping values in the `MetaScript.php` model with no luck. I also poked around the `ScriptContainer.php` comparing how other analytics are included and noticed there wasn't a bodyTemplate defined. Again I tried making some modifications without any luck.

Hoping you can point me in the right direction to get the gtag.js script included.

Thanks!

**Comment by apticknor** [comment]
Also, I grepped the codebase and `gtagBody.twig` isn't found anywhere in the codebase.

**Comment by khalwat** [comment]
So the source template file is definitely there:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/templates/_frontend/scripts/gtagBody.twig

...but you're right, it's lacking the appropriate settings are missing:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/globalmeta/ScriptContainer.php#L105

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/c805e4148566b48b92970320003bcc86c6e0dce6
