### ISSUE TITLE
Setting unknown property: nystudio107\seomatic\models\MetaLink::as

### ISSUE THREAD

**Issue by DowleyDeveloped** [nystudio107/craft-seomatic#1050]
### Is your feature request related to a problem? Please describe.

With Preloading Images/Fonts etc on the site, it'd be useful to be able to use the seomatic.link.create to do this within templates for things in Matrixes.  Currently if you add it, you get a warning.

### Describe the solution you would like

Can we add "as" to the MetaLink model?

**Comment by khalwat** [comment]
You can do this with `tagAttrs` -> https://nystudio107.com/docs/seomatic/using.html#extra-tag-attributes
