### ISSUE TITLE
Blank Content SEO

### ISSUE THREAD

**Issue by bigpxl** [nystudio107/craft-seomatic#1051]
On one of our sites the SEOmatic plugin doesn't generate any rows in the sematic_metabundles table. So whenever we go to setup content seo, it's completely blank even though there are a bunch of sections. I've tried all of the basic troubleshooting steps (reinstalling, adding new sections, checking for errors in the console and log files) and haven't been able to find any reason for it.

**License:**
OKK43/UNDTQ652IHM3KL&7PJ$EUC8JO^W/T!X0DPZ#2PU/+NDM5K5&$GXK7PTE^N$&QFA%5L9S0+%I86%0T=JUBBLODX38UHY70MMHUV/=C5L4WV=G16D0^74ZC0=L2EL/FUE$R/3A+44%GU%OGW275!%86IRGU2%P6ONB#BC7%L43^8BXEZJ$A4=2R!EPK4IBNPWW&AFOR&RE=CA4JBZ$0GILD$+A!5AH+G=47GUDA!IFDSUE4FH*62RJ

**Comment by khalwat** [comment]
Can you please check to ensure that your site has the **This site has its own base URL** checkbox set, and you also have a Site URL entered for the site?

**Comment by khalwat** [comment]
Will re-open if additional information is provided.

**Comment by bigpxl** [comment]
Hi Khalwat, that was the issue! I've added the base url, and reinstalled the plugin, and now everything is working. Thanks!
