### ISSUE TITLE
SEOmatic Field error Component class 'nystudio107\seomatic\fields\SeoSettings' belongs to a disabled plugin (SEOmatic).

### ISSUE THREAD

**Issue by joepagan** [nystudio107/craft-seomatic#1052]
### Describe the bug

Get this field error:

![image](https://user-images.githubusercontent.com/2337910/151623788-2113102f-2554-4579-b52c-61c116fa0f67.png)

Despite the plugin being enabled:

![image](https://user-images.githubusercontent.com/2337910/151623913-9cd9f7c4-e6a9-4f42-a4bc-71eae4585946.png)

some context, I've had this plugin installed for a while, applied the fields, disabled a little while on a local app, done a couple of craft updates while it was disabled, and a ./craft update on seomatic itself (while disabled).

Let me know if you need more info

### To reproduce
Steps to reproduce the behaviour:

disable/enable - no difference
uninstall/install - no difference

### Expected behaviour

no error when plugin enabled

### Versions
- Plugin version: 3.4.22
- Craft version: 3.7.27.2

**Comment by khalwat** [comment]
So I'm not sure how this could be an error related to SEOmatic. Plugins and their enabled/disabled state are handled by Craft CMS. 

SEOmatic doesn't do anything special in this regard, so I'm not sure what to say. I'd suggest filing this with Craft CMS as an issue. Happy to help if I'm incorrect on this, but I'm pretty sure this has nothing to do with SEOmatic.

**Comment by joepagan** [comment]
Fair enough will do!

**Comment by khalwat** [comment]
If I had to guess, it might have something to do with the settings in the db vs. the settings in Project Config
