### ISSUE TITLE
Duplicate sitemap entries in robots.txt

### ISSUE THREAD

**Issue by sjelfull** [nystudio107/craft-seomatic#1053]
### Describe the bug

It seems like I'm seeing duplicate sitemap entries in robots.txt after upgrading:

![image](https://user-images.githubusercontent.com/10508/151782721-7c5e8b82-eeee-4e07-823e-7d0f3a1d7515.png)

Note the lower and uppercase `sitemap/Sitemap` keys.

This is the robots.txt config:

![image](https://user-images.githubusercontent.com/10508/151782919-9f5df107-704e-4415-ab8a-e374959341f6.png)

Is this expected? Seems weird since it doesn't match what is set in the template.

### To reproduce
Steps to reproduce the behaviour:

1. Have multiple sites
2. Use the default robots.txt template with multiple sites:
```
# robots.txt for {{ siteUrl }}

Sitemap: {{ seomatic.helper.sitemapIndexForSiteId() }}
Sitemap: {{ seomatic.helper.sitemapIndexForSiteId(3) }}
Sitemap: {{ seomatic.helper.sitemapIndexForSiteId(4) }}
Sitemap: {{ seomatic.helper.sitemapIndexForSiteId(5) }}
Sitemap: {{ seomatic.helper.sitemapIndexForSiteId(6) }}
```

### Expected behaviour

I expect to only see one set of sitemap entries.

### Versions
- Plugin version: SEOMatic 3.4.22
- Craft version: Craft Pro 3.7.30.1

**Comment by khalwat** [comment]
That's not the default robots.txt -- that looks like this: https://github.com/nystudio107/craft-seomatic/blob/develop/src/templates/_frontend/pages/robots.twig

I'm guessing at some point you edited this to look like what is in the screenshot.

You can just copy the default code back in if you like.

**Comment by sjelfull** [comment]
Thanks. I did not, but someone probably did, and reverting it fixes the problem.

**Comment by khalwat** [comment]
I meant the royal _you_ :) Glad you have it sorted.
