### ISSUE TITLE
Unencoded filename breaks `twitter:image`

### ISSUE THREAD

**Issue by markhuot** [nystudio107/craft-seomatic#1054]
### Describe the bug
When using a "Twitter Image Source" with a filename that contains spaces the Meta Tag seems to run the meta content through `url_decode` which breaks the Twitter share. Twitter requires the meta tag to be URL encoded or it will not display the image.

### To reproduce
Steps to reproduce the behaviour:
1. Upload a file with a space in the name, for example `Foo Bar Baz.jpg`
2. Select that image as the "Twitter Image Source" via an assets field or using Custom URL. I used `{{ seomatic.helper.socialTransform(entry.heroImage, 'twitter') }}`. I tested this by manually selecting an image and saw the same issues.
3. Notice the `<meta` tag is printed with a `content=` attribute that contains `content=".../Foo Bar Baz.jpg"`
4. In `./craft shell` you can run `nystudio107\seomatic\Seomatic::getInstance()->helper->socialTransform($image, 'twitter');` and that _will_ return a properly URL encoded filename. So the issue seems to be when the `<meta` tag is output.

### Expected behaviour
The content attribute of `<meta name="twitter:image" content="..."/>` should _not_ be `url_decod`ed

### Versions
- Plugin version: 3.4.15 (I'm working to get this updated to the latest version)
- Craft version: 3.7.26

**Comment by khalwat** [comment]
Yeah update to the latest version first thing IMO

As for the encoding, that's actually done via Yii2's `Html::tag()` routine:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/models/MetaTag.php#L185

I'd be a little surprised if something were amiss with that.

**Comment by khalwat** [comment]
This all looks/works fine to me. I ended up with this in the meta tags:

```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@woofer">
<meta name="twitter:creator" content="@woofer">
<meta name="twitter:title" content="Homepage">
<meta name="twitter:image" content="http://localhost:8000/assets/site/_800x418_crop_center-center_82_none/Foo-Bar-Baz.jpg?mtime=1644350708">
<meta name="twitter:image:width" content="800">
<meta name="twitter:image:height" content="418">
```

This is after uploading and using a file named: `Foo Bar Baz.jpg`
![Foo Bar Baz](https://user-images.githubusercontent.com/7570798/153067276-a09a2087-bf51-4621-8efa-0bde650890aa.jpg)
