### ISSUE TITLE
SEO Image Source not correct in Preview or in code

### ISSUE THREAD

**Issue by angieherrera** [nystudio107/craft-seomatic#1056]
In a blog section I have the SEO Image Source to use the Featured Image field like so:
![CleanShot 2022-02-02 at 12 32 49](https://user-images.githubusercontent.com/442434/152232765-1b39e5f9-7181-4300-8511-ce1b88fbd3cb.png)

Here's the Featured Image:
![CleanShot 2022-02-02 at 12 33 00](https://user-images.githubusercontent.com/442434/152232802-e4efa89f-c177-4a97-b101-81176d629e4a.png)

However, the preview shows the default/fallback image I set under Global settings:
![CleanShot 2022-02-02 at 12 36 10](https://user-images.githubusercontent.com/442434/152233255-7541d2e4-378c-4703-9573-1bf16d2ef41f.png)
![CleanShot 2022-02-02 at 12 34 39](https://user-images.githubusercontent.com/442434/152233263-9f2d4f46-6c81-4b7b-94f7-718d74a75506.png)

Even if I override the field manually, the image doesn't update:
![CleanShot 2022-02-02 at 12 22 15](https://user-images.githubusercontent.com/442434/152233309-e27cfb27-1c4d-4c27-a28e-af865c1e5d75.png)

This isn't happening just in the Craft CP though - looking at the source code or running the entry URL through an OpenGraph checker shows the fallback image.

Not sure what's going on here. As far as I know this has been working, but perhaps the client only just noticed.

This is on Craft 3.7.28 and SEOmatic 3.4.22.

**Comment by khalwat** [comment]
Do you have anything at all set for the Content SEO settings for this section? I have vague memories of it not overriding properly if nothing is set in Content SEO, but only Global SEO

**Comment by angieherrera** [comment]
Yep - Content SEO is set to use the Featured Image (similar to the first screenshot).

**Comment by khalwat** [comment]
Any chance you could send a db dump & composer.json for your project to: andrew@nystudio107.com

?

**Comment by angieherrera** [comment]
Will do!

**Comment by khalwat** [comment]
I am unable to reproduce this locally

1) set it up locally
2) only thing I changed in DB was set the password hash to a known one
3) logged in, went to the exact same entry
4) looked at the broken image links and uploaded an image to fix that
5) the seo images are the images set up on the featured image field

![Screen_Shot_2022-02-04_at_09 39 47](https://user-images.githubusercontent.com/7570798/152557623-4ec8585c-96f6-453f-9e5c-2c43ebc23764.png)

Could this potentially be some kind of caching issue? Have you cleared all caches?

**Comment by angieherrera** [comment]
🤔 I cleared all caches and still seeing the same default image rather than the override (even if I choose the Custom Image) option.

**Comment by khalwat** [comment]
Any chance we could do a screen share at some point to have a look?

You can book it here:

https://savvycal.com/nystudio107/chat

**Comment by angieherrera** [comment]
Booked!

**Comment by khalwat** [comment]
Current theory is that this is related to images and/or image transforms not working correctly on the server, which results in a `null` SEO image, which causes it to not override the global setting.

**Comment by angieherrera** [comment]
The issue ended up being a permissions issue for the assets directories on the server. Specifically, incorrect owner and group was causing transforms to fail.

**Comment by khalwat** [comment]
@angieherrera ahhhhhh glad to hear our suspicions were correct!
