### ISSUE TITLE
Error applying Project Config when it contains a new Single Section

### ISSUE THREAD

**Issue by NickHolder** [nystudio107/craft-seomatic#1057]
### Describe the bug
Applying project-config changes that contain a new Single section will error saying the section (that you are creating) has no entry type.

I've been able to reproduce this issue on an in production site and a fresh install.

### To reproduce
Steps to reproduce the behaviour:
1. Install Craft Pro Trial
2. Install SEOmatic Trial
3. Export the DB
4. Create a new Single section
5. Import the exported DB
5. Touch project config
6. Apply project config

### Expected behaviour
Project config should apply without error and add your new Single section.

### Screenshots
<img width="735" alt="Screenshot 2022-02-07 at 09 59 15" src="https://user-images.githubusercontent.com/1211987/152781416-e6ff1266-2c35-4fdd-8c85-e8299d57e8c4.png">
<img width="1214" alt="Screenshot 2022-02-07 at 10 26 00" src="https://user-images.githubusercontent.com/1211987/152781534-cb33df78-8d49-470e-a85d-7cba34041454.png">

### Versions
- Plugin version: 3.4.23
- Craft version: 3.7.30.1
- PHP version: 7.4.25
- MySQL version:  5.7.23
- Laravel Valet 2.16.1

**Comment by khalwat** [comment]
Unclear to me what SEOmatic would have to do with this? I think probably this should be reported to Pixel & Tonic -> 

https://github.com/craftcms/cms/issues

or

support@craftcms.com

Can you provide some full stack traces/logs that show SEOmatic being in the mix here?

**Comment by NickHolder** [comment]
Thanks for your reply. I will also report this on the craftcms repo.

It's very odd as SEOmatic does not appear in the stack trace of the error. SEOmatic does appear in the web.log and console.log but it looks like only for it’s Loaded Event. However whilst trying to debug this issue our team disabled each of the 10+ plugins on the site we are building and only disabling SEOmatic allowed us to apply the project config containing a new Single successfully, and it is reproducible on a fresh craft install with only SEOmatic added. 

[project-config-error.txt](https://github.com/nystudio107/craft-seomatic/files/8023506/project-config-error.txt)
[project-config-console.log](https://github.com/nystudio107/craft-seomatic/files/8023507/project-config-console.log)
[project-config-web.log](https://github.com/nystudio107/craft-seomatic/files/8023508/project-config-web.log)

**Comment by khalwat** [comment]
Are you saying that you cannot reproduce the issues without SEOmatic installed?

**Comment by khalwat** [comment]
Here's the stack trace:

```
2022-02-08 01:58:45 [-][1][lnl94fl85bv4u1e4q15ki0shon][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Section 1 has no entry types in *******/repo/matic-test/vendor/craftcms/cms/src/elements/Entry.php:1157
Stack trace:
#0 *******/repo/matic-test/vendor/craftcms/cms/src/elements/Entry.php(1519): craft\elements\Entry->getType()
#1 *******/repo/matic-test/vendor/craftcms/cms/src/elements/Entry.php(1617): craft\elements\Entry->updateTitle()
#2 *******/repo/matic-test/vendor/craftcms/cms/src/services/Elements.php(2493): craft\elements\Entry->beforeSave(true)
#3 *******/repo/matic-test/vendor/craftcms/cms/src/services/Elements.php(784): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, false, NULL)
#4 *******/repo/matic-test/vendor/craftcms/cms/src/services/Sections.php(1564): craft\services\Elements->saveElement(Object(craft\elements\Entry), false)
#5 *******/repo/matic-test/vendor/craftcms/cms/src/services/Sections.php(1235): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section))
#6 *******/repo/matic-test/vendor/craftcms/cms/src/base/ApplicationTrait.php(1681): craft\services\Sections->handleChangedEntryType(Object(craft\events\ConfigEvent))
#7 *******/repo/matic-test/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#8 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#9 *******/repo/matic-test/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#10 *******/repo/matic-test/vendor/craftcms/cms/src/services/ProjectConfig.php(750): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#11 *******/repo/matic-test/vendor/craftcms/cms/src/services/ProjectConfig.php(1309): craft\services\ProjectConfig->_processConfigChangesInternal('entryTypes.d418...', false, NULL, true)
#12 *******/repo/matic-test/vendor/craftcms/cms/src/services/ProjectConfig.php(574): craft\services\ProjectConfig->_applyChanges(Array)
#13 *******/repo/matic-test/vendor/craftcms/cms/src/controllers/ConfigSyncController.php(56): craft\services\ProjectConfig->applyYamlChanges()
#14 [internal function]: craft\controllers\ConfigSyncController->actionApplyYamlChanges()
#15 *******/repo/matic-test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 *******/repo/matic-test/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#17 *******/repo/matic-test/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('apply-yaml-chan...', Array)
#18 *******/repo/matic-test/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('config-sync/app...', Array)
#19 *******/repo/matic-test/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('config-sync/app...', Array)
#20 *******/repo/matic-test/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 *******/repo/matic-test/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 *******/repo/matic-test/web/index.php(12): yii\base\Application->run()
```

I don't see SEOmatic involved here? Happy to help if it does end up being involved somehow tho.

**Comment by NickHolder** [comment]
> Are you saying that you cannot reproduce the issues without SEOmatic installed?

Sorry, yes we can only reproduce the issue with SEOmatic installed. Even on a new Craft install with only SEOmatic installed.

**Comment by khalwat** [comment]
That's really, really strange. I would expect to see SEOmatic somewhere in the mix here.

**Comment by NickHolder** [comment]
Yeah very odd, and it's only when you create a new Single Section so far for us not Channel or Structure.
