### ISSUE TITLE
SeoElements::getSeoElementByMetaBundleType() must be of the type string, null given

### ISSUE THREAD

**Issue by digitalleapagency** [nystudio107/craft-seomatic#1058]
### Describe the bug
Whenever I try to open the SEOMatic settings after the latest update I get this error. Stacktrace of the error below. Feels that something might have gone wrong when updating on DB site?

### To reproduce
1. Open SEO Matic settings

### Stacktrace of the error
```
TypeError: Argument 1 passed to nystudio107\seomatic\services\SeoElements::getSeoElementByMetaBundleType() must be of the type string, null given, called in /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php on line 750 and defined in /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/SeoElements.php:82
Stack trace:
#0 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(750): nystudio107\seomatic\services\SeoElements->getSeoElementByMetaBundleType()
#1 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(708): nystudio107\seomatic\services\MetaBundles->pruneVestigialMetaBundle()
#2 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php(156): nystudio107\seomatic\services\MetaBundles->pruneVestigialMetaBundles()
#3 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionDashboard()
#4 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#6 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#7 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#8 /var/www/proudly/public_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#9 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest()
#10 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#11 /var/www/proudly/public_html/web/index.php(26): yii\base\Application->run()
#12 {main}
```

### Versions
- Plugin version: 3.4.23
- Craft version: 3.7.30.1
- PHP Version:  7.4.27

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d3e169824ed2f92d73ed182f2d20c5f578b0f67f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.24”,
```
Then do a `composer clear-cache && composer update`

**Comment by digitalleapagency** [comment]
Thanks for the update Khalwat. This does trigger another issue on our end now however. Will try to explain it down here:

### Describe the bug
When re-enabling the plugin with the new version it triggers a site wide error now.

`Argument 1 passed to nystudio107\seomatic\services\SeoElements::getSeoElementByMetaBundleType() must be of the type string, null given, called in /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php on line 186`

### To Reproduce
1. Update composer to the latest dev version
2. Enable the plugin

### Stacktrace of the error
```
TypeError: Argument 1 passed to nystudio107\seomatic\services\SeoElements::getSeoElementByMetaBundleType() must be of the type string, null given, called in /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php on line 186 and defined in /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/SeoElements.php:82
Stack trace:
#0 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(186): nystudio107\seomatic\services\SeoElements->getSeoElementByMetaBundleType()
#1 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(156): nystudio107\seomatic\services\MetaBundles->syncBundleWithConfig()
#2 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(555): nystudio107\seomatic\services\MetaBundles->getGlobalMetaBundle()
#3 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(58): nystudio107\seomatic\services\MetaContainers->loadGlobalMetaContainers()
#4 /var/www/proudly/public_html/vendor/twig/twig/src/ExtensionSet.php(329): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#5 /var/www/proudly/public_html/vendor/twig/twig/src/Environment.php(927): Twig\ExtensionSet->getGlobals()
#6 /var/www/proudly/public_html/vendor/twig/twig/src/Environment.php(947): Twig\Environment->getGlobals()
#7 /var/www/proudly/public_html/vendor/twig/twig/src/Template.php(378): Twig\Environment->mergeGlobals()
#8 /var/www/proudly/public_html/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#9 /var/www/proudly/public_html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#10 /var/www/proudly/public_html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#11 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render()
#12 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate()
#13 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate()
#14 /var/www/proudly/public_html/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate()
#15 [internal function]: craft\controllers\TemplatesController->actionRender()
#16 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#17 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#18 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#19 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#20 /var/www/proudly/public_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#21 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest()
#22 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#23 /var/www/proudly/public_html/web/index.php(26): yii\base\Application->run()
#24 {main}
```

**Comment by digitalleapagency** [comment]
When I would update line 186 and add an empty string instead of the $sourceBundleType variable it works but saving something triggers another error. Stacktrace of that one below.

### Stacktrace of the error
`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sourceBundleType' cannot be null in /var/www/proudly/public_html/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/Schema.php(431): yii\db\Command->execute()
#3 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\Schema->insert()
#4 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()
#5 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#6 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(342): yii\db\BaseActiveRecord->save()
#7 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(696): nystudio107\seomatic\services\MetaBundles->updateMetaBundle()
#8 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/Seomatic.php(513): nystudio107\seomatic\services\MetaBundles->invalidateMetaBundleByElement()
#9 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}()
#10 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#11 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#12 /var/www/proudly/public_html/vendor/craftcms/cms/src/services/Elements.php(2818): yii\base\Component->trigger()
#13 /var/www/proudly/public_html/vendor/craftcms/cms/src/services/Elements.php(784): craft\services\Elements->_saveElementInternal()
#14 /var/www/proudly/public_html/vendor/craftcms/cms/src/controllers/EntriesController.php(403): craft\services\Elements->saveElement()
#15 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#16 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#17 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#18 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#19 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#20 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction()
#21 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest()
#22 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#23 /var/www/proudly/public_html/web/index.php(26): yii\base\Application->run()
#24 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sourceBundleType' cannot be null
The SQL being executed was: INSERT INTO `seomatic_metabundles` (`bundleVersion`, `sourceBundleType`, `sourceId`, `sourceName`, `sourceHandle`, `sourceType`, `typeId`, `sourceTemplate`, `sourceSiteId`, `sourceAltSiteSettings`, `sourceDateUpdated`, `metaGlobalVars`, `metaSiteVars`, `metaSitemapVars`, `metaContainers`, `redirectsContainer`, `frontendTemplatesContainer`, `metaBundleSettings`, `dateCreated`, `dateUpdated`, `uid`) VALUES (NULL, NULL, 9, '', NULL, NULL, NULL, '', 79, '{\"1\":{\"id\":9,\"sectionId\":9,\"siteId\":1,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"en-us\"},\"28\":{\"id\":293,\"sectionId\":9,\"siteId\":28,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"en\"},\"56\":{\"id\":1421,\"sectionId\":9,\"siteId\":56,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"uk\"},\"57\":{\"id\":1420,\"sectionId\":9,\"siteId\":57,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"en\"},\"58\":{\"id\":1450,\"sectionId\":9,\"siteId\":58,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"nl\"},\"59\":{\"id\":1471,\"sectionId\":9,\"siteId\":59,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"nl\"},\"60\":{\"id\":1470,\"sectionId\":9,\"siteId\":60,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"fr\"},\"61\":{\"id\":1472,\"sectionId\":9,\"siteId\":61,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"en\"},\"76\":{\"id\":1754,\"sectionId\":9,\"siteId\":76,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"af\"},\"77\":{\"id\":1770,\"sectionId\":9,\"siteId\":77,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"nl\"},\"78\":{\"id\":1786,\"sectionId\":9,\"siteId\":78,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"af\"},\"79\":{\"id\":1803,\"sectionId\":9,\"siteId\":79,\"enabledByDefault\":true,\"hasUrls\":true,\"uriFormat\":\"culture/{slug}\",\"template\":\"pages/culture/_index\",\"language\":\"nl-nl\"}}', '2022-02-09 10:29:39', '{\"language\":null,\"mainEntityOfPage\":\"WebPage\",\"seoTitle\":\"{entry.title}\",\"siteNamePosition\":\"\",\"seoDescription\":\"\",\"seoKeywords\":\"\",\"seoImage\":\"\",\"seoImageWidth\":\"\",\"seoImageHeight\":\"\",\"seoImageDescription\":\"\",\"canonicalUrl\":\"{entry.url}\",\"robots\":\"\",\"ogType\":\"website\",\"ogTitle\":\"{seomatic.meta.seoTitle}\",\"ogSiteNamePosition\":\"\",\"ogDescription\":\"{seomatic.meta.seoDescription}\",\"ogImage\":\"{seomatic.meta.seoImage}\",\"ogImageWidth\":\"{seomatic.meta.seoImageWidth}\",\"ogImageHeight\":\"{seomatic.meta.seoImageHeight}\",\"ogImageDescription\":\"{seomatic.meta.seoImageDescription}\",\"twitterCard\":\"summary_large_image\",\"twitterCreator\":\"{seomatic.site.twitterHandle}\",\"twitterTitle\":\"{seomatic.meta.seoTitle}\",\"twitterSiteNamePosition\":\"\",\"twitterDescription\":\"{seomatic.meta.seoDescription}\",\"twitterImage\":\"{seomatic.meta.seoImage}\",\"twitterImageWidth\":\"{seomatic.meta.seoImageWidth}\",\"twitterImageHeight\":\"{seomatic.meta.seoImageHeight}\",\"twitterImageDescription\":\"{seomatic.meta.seoImageDescription}\",\"inherited\":[],\"overrides\":[]}', '{\"siteName\":\"Proudly\",\"identity\":null,\"creator\":null,\"twitterHandle\":\"\",\"facebookProfileId\":\"\",\"facebookAppId\":\"\",\"googleSiteVerification\":\"\",\"bingSiteVerification\":\"\",\"pinterestSiteVerification\":\"\",\"facebookSiteVerification\":\"\",\"sameAsLinks\":[],\"siteLinksSearchTarget\":\"\",\"siteLinksQueryInput\":\"\",\"referrer\":\"no-referrer-when-downgrade\",\"additionalSitemapUrls\":[],\"additionalSitemapUrlsDateUpdated\":null,\"additionalSitemaps\":[]}', '{\"sitemapUrls\":true,\"sitemapAssets\":true,\"sitemapFiles\":true,\"sitemapAltLinks\":true,\"sitemapChangeFreq\":\"weekly\",\"sitemapPriority\":0.5,\"sitemapLimit\":null,\"structureDepth\":null,\"sitemapImageFieldMap\":[{\"property\":\"title\",\"field\":\"title\"},{\"property\":\"caption\",\"field\":\"\"},{\"property\":\"geo_location\",\"field\":\"\"},{\"property\":\"license\",\"field\":\"\"}],\"sitemapVideoFieldMap\":[{\"property\":\"title\",\"field\":\"title\"},{\"property\":\"description\",\"field\":\"\"},{\"property\":\"thumbnailLoc\",\"field\":\"\"},{\"property\":\"duration\",\"field\":\"\"},{\"property\":\"category\",\"field\":\"\"}],\"inherited\":[],\"overrides\":[]}', '{\"MetaTagContainergeneral\":{\"data\":[],\"name\":\"General\",\"description\":\"General Meta Tags\",\"class\":\"nystudio107\\\\seomatic\\\\models\\\\MetaTagContainer\",\"handle\":\"general\",\"include\":true,\"dependencies\":[],\"clearCache\":false},\"MetaTagContaineropengraph\":{\"data\":[],\"name\":\"Facebook\",\"description\":\"Facebook OpenGraph Meta Tags\",\"class\":\"nystudio107\\\\seomatic\\\\models\\\\MetaTagContainer\",\"handle\":\"opengraph\",\"include\":true,\"dependencies\":[],\"clearCache\":false},\"MetaTagContainertwitter\":{\"data\":[],\"name\":\"Twitter\",\"description\":\"Twitter Card Meta Tags\",\"class\":\"nystudio107\\\\seomatic\\\\models\\\\MetaTagContainer\",\"handle\":\"twitter\",\"include\":true,\"dependencies\":[],\"clearCache\":false},\"MetaTagContainermiscellaneous\":{\"data\":[],\"name\":\"Miscellaneous\",\"description\":\"Miscellaneous Meta Tags\",\"class\":\"nystudio107\\\\seomatic\\\\models\\\\MetaTagContainer\",\"handle\":\"miscellaneous\",\"include\":true,\"dependencies\":[],\"clearCache\":false},\"MetaLinkContainergeneral\":{\"data\":[],\"name\":\"General\",\"description\":\"Link Tags\",\"class\":\"nystudio107\\\\seomatic\\\\models\\\\MetaLinkContainer\",\"handle\":\"general\",\"include\":true,\"dependencies\":[],\"clearCache\":false},\"MetaScriptContainergeneral\":{\"data\":[],\"position\":1,\"name\":\"General\",\"description\":\"Script Tags\",\"class\":\"nystudio107\\\\seomatic\\\\models\\\\MetaScriptContainer\",\"handle\":\"general\",\"include\":true,\"dependencies\":[],\"clearCache\":false},\"MetaJsonLdContainergeneral\":{\"data\":{\"mainEntityOfPage\":{\"breadcrumb\":null,\"lastReviewed\":null,\"mainContentOfPage\":null,\"primaryImageOfPage\":null,\"relatedLink\":null,\"reviewedBy\":null,\"significantLink\":null,\"speakable\":null,\"specialty\":null,\"about\":null,\"abstract\":null,\"accessMode\":null,\"accessModeSufficient\":null,\"accessibilityAPI\":null,\"accessibilityControl\":null,\"accessibilityFeature\":null,\"accessibilityHazard\":null,\"accessibilitySummary\":null,\"accountablePerson\":null,\"acquireLicensePage\":null,\"aggregateRating\":null,\"alternativeHeadline\":null,\"associatedMedia\":null,\"audience\":null,\"audio\":null,\"author\":{\"id\":\"{parseEnv(seomatic.site.identity.genericUrl)}#identity\"},\"award\":null,\"character\":null,\"citation\":null,\"comment\":null,\"commentCount\":null,\"conditionsOfAccess\":null,\"contentLocation\":null,\"contentRating\":null,\"contentReferenceTime\":null,\"contributor\":null,\"copyrightHolder\":{\"id\":\"{parseEnv(seomatic.site.identity.genericUrl)}#identity\"},\"copyrightYear\":\"{entry.postDate | date(\\\"Y\\\")}\",\"correction\":null,\"creativeWorkStatus\":null,\"creator\":{\"id\":\"{parseEnv(seomatic.site.identity.genericUrl)}#creator\"},\"dateCreated\":false,\"dateModified\":\"{entry.dateUpdated |atom}\",\"datePublished\":\"{entry.postDate |atom}\",\"discussionUrl\":null,\"editor\":null,\"educationalAlignment\":null,\"educationalUse\":null,\"encoding\":null,\"encodingFormat\":null,\"exampleOfWork\":null,\"expires\":null,\"funder\":null,\"genre\":null,\"hasPart\":null,\"headline\":\"{seomatic.meta.seoTitle}\",\"inLanguage\":\"{seomatic.meta.language}\",\"interactionStatistic\":null,\"interactivityType\":null,\"isAccessibleForFree\":null,\"isBasedOn\":null,\"isFamilyFriendly\":null,\"isPartOf\":null,\"keywords\":null,\"learningResourceType\":null,\"license\":null,\"locationCreated\":null,\"mainEntity\":null,\"maintainer\":null,\"material\":null,\"materialExtent\":null,\"mentions\":null,\"offers\":null,\"position\":null,\"producer\":null,\"provider\":null,\"publication\":null,\"publisher\":{\"id\":\"{parseEnv(seomatic.site.identity.genericUrl)}#creator\"},\"publisherImprint\":null,\"publishingPrinciples\":null,\"recordedAt\":null,\"releasedEvent\":null,\"review\":null,\"schemaVersion\":null,\"sdDatePublished\":null,\"sdLicense\":null,\"sdPublisher\":null,\"sourceOrganization\":null,\"spatial\":null,\"spatialCoverage\":null,\"sponsor\":null,\"temporal\":null,\"temporalCoverage\":null,\"text\":null,\"thumbnailUrl\":null,\"timeRequired\":null,\"translationOfWork\":null,\"translator\":null,\"typicalAgeRange\":null,\"usageInfo\":null,\"version\":null,\"video\":null,\"workExample\":null,\"workTranslation\":null,\"additionalType\":null,\"alternateName\":null,\"description\":\"{seomatic.meta.seoDescription}\",\"disambiguatingDescription\":null,\"identifier\":null,\"image\":{\"type\":\"ImageObject\",\"url\":\"{seomatic.meta.seoImage}\"},\"mainEntityOfPage\":\"{seomatic.meta.canonicalUrl}\",\"name\":\"{seomatic.meta.seoTitle}\",\"potentialAction\":{\"type\":\"SearchAction\",\"target\":\"{seomatic.site.siteLinksSearchTarget}\",\"query-input\":\"{seomatic.helper.siteLinksQueryInput()}\"},\"sameAs\":null,\"subjectOf\":null,\"url\":\"{seomatic.meta.canonicalUrl}\",\"context\":\"http://schema.org\",\"type\":\"{seomatic.meta.mainEntityOfPage}\",\"id\":null,\"graph\":null,\"include\":true,\"key\":\"mainEntityOfPage\",\"environment\":null,\"dependencies\":null,\"tagAttrs\":[],\"nonce\":null}},\"name\":\"General\",\"description\":\"JsonLd Tags\",\"class\":\"nystudio107\\\\seomatic\\\\models\\\\MetaJsonLdContainer\",\"handle\":\"general\",\"include\":true,\"dependencies\":[],\"clearCache\":false},\"MetaTitleContainergeneral\":{\"data\":{\"title\":{\"title\":\"{seomatic.meta.seoTitle}\",\"siteName\":\"{seomatic.site.siteName}\",\"siteNamePosition\":\"{seomatic.meta.siteNamePosition}\",\"separatorChar\":\"{seomatic.config.separatorChar}\",\"include\":true,\"key\":\"title\",\"environment\":null,\"dependencies\":null,\"tagAttrs\":[]}},\"name\":\"General\",\"description\":\"Meta Title Tag\",\"class\":\"nystudio107\\\\seomatic\\\\models\\\\MetaTitleContainer\",\"handle\":\"general\",\"include\":true,\"dependencies\":[],\"clearCache\":false}}', '[]', '{\"data\":[],\"name\":null,\"description\":null,\"class\":\"nystudio107\\\\seomatic\\\\models\\\\FrontendTemplateContainer\",\"handle\":null,\"include\":true,\"dependencies\":null,\"clearCache\":false}', '{\"siteType\":\"CreativeWork\",\"siteSubType\":\"WebPage\",\"siteSpecificType\":\"\",\"seoTitleSource\":\"fromField\",\"seoTitleField\":\"title\",\"siteNamePositionSource\":\"sameAsGlobal\",\"seoDescriptionSource\":\"fromCustom\",\"seoDescriptionField\":\"\",\"seoKeywordsSource\":\"fromCustom\",\"seoKeywordsField\":\"\",\"seoImageIds\":[],\"seoImageSource\":\"fromAsset\",\"seoImageField\":\"\",\"seoImageTransform\":true,\"seoImageTransformMode\":\"crop\",\"seoImageDescriptionSource\":\"fromCustom\",\"seoImageDescriptionField\":\"\",\"twitterCreatorSource\":\"sameAsSite\",\"twitterCreatorField\":\"\",\"twitterTitleSource\":\"sameAsSeo\",\"twitterTitleField\":\"\",\"twitterSiteNamePositionSource\":\"sameAsGlobal\",\"twitterDescriptionSource\":\"sameAsSeo\",\"twitterDescriptionField\":\"\",\"twitterImageIds\":[],\"twitterImageSource\":\"sameAsSeo\",\"twitterImageField\":\"\",\"twitterImageTransform\":true,\"twitterImageTransformMode\":\"crop\",\"twitterImageDescriptionSource\":\"sameAsSeo\",\"twitterImageDescriptionField\":\"\",\"ogTitleSource\":\"sameAsSeo\",\"ogTitleField\":\"\",\"ogSiteNamePositionSource\":\"sameAsGlobal\",\"ogDescriptionSource\":\"sameAsSeo\",\"ogDescriptionField\":\"\",\"ogImageIds\":[],\"ogImageSource\":\"sameAsSeo\",\"ogImageField\":\"\",\"ogImageTransform\":true,\"ogImageTransformMode\":\"crop\",\"ogImageDescriptionSource\":\"sameAsSeo\",\"ogImageDescriptionField\":\"\"}', '2022-02-09 10:29:40', '2022-02-09 10:29:40', 'addcaaa3-c380-4097-a1f2-8c26a3112524') in /var/www/proudly/public_html/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/Schema.php(431): yii\db\Command->execute()
#3 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\Schema->insert()
#4 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()
#5 /var/www/proudly/public_html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#6 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(342): yii\db\BaseActiveRecord->save()
#7 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(696): nystudio107\seomatic\services\MetaBundles->updateMetaBundle()
#8 /var/www/proudly/public_html/vendor/nystudio107/craft-seomatic/src/Seomatic.php(513): nystudio107\seomatic\services\MetaBundles->invalidateMetaBundleByElement()
#9 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}()
#10 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#11 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#12 /var/www/proudly/public_html/vendor/craftcms/cms/src/services/Elements.php(2818): yii\base\Component->trigger()
#13 /var/www/proudly/public_html/vendor/craftcms/cms/src/services/Elements.php(784): craft\services\Elements->_saveElementInternal()
#14 /var/www/proudly/public_html/vendor/craftcms/cms/src/controllers/EntriesController.php(403): craft\services\Elements->saveElement()
#15 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#16 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#17 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#18 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#19 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#20 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction()
#21 /var/www/proudly/public_html/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest()
#22 /var/www/proudly/public_html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#23 /var/www/proudly/public_html/web/index.php(26): yii\base\Application->run()
#24 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'sourceBundleType' cannot be null
)
`

**Comment by khalwat** [comment]
It sounds to me like somewhere data has become corrupted, can you uninstall and re-install the plugin?

**Comment by khalwat** [comment]
Ok, I made another fix. I think somewhere, some data is in the database that should not be there, but this may guard against the errors you have run into.

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/38b60c9b37cff8d7ac1a70a05a10245d83766253

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.24”,
```
Then do a `composer clear-cache && composer update`
