### ISSUE TITLE
All entries in section missing a new language alternate link, and one entry is missing additional links

### ISSUE THREAD

**Issue by mizziness** [nystudio107/craft-seomatic#1060]
### Describe the bug

When comparing the `metaLinkContainer` data for two entries that are both in the same section and have the same settings, one page shows all available alternative urls and one is missing two of its links. This happens both on the rendered page (the HTML output) and the data returned by GraphQL.  See the Screenshots section for examples.

Additionally, none of these entries show alternative language links for the new Japanese language site at all. 

### To reproduce
Any new entries I create in this section inherit the same bug.

### Expected behaviour

If two entries are in the same section and share all of the same settings in Seomatic (both on the section level and the entry level), then I would expect the metaLinkContainer data to be comparable and contain the same data nodes.

### Screenshots

Below, Entry A is correct and entry B is missing `canonical`, `x-default`.

Entry A: `seomatic(uri: "/platform")`:

```
{
  "data": {
    "seomatic": {
      "metaLinkContainer": "<link href=\"https://www.applause.com/platform\" rel=\"canonical\"><link href=\"https://www.applause.com\" rel=\"home\"><link type=\"text/plain\" href=\"https://www.applause.com/humans.txt\" rel=\"author\"><link href=\"https://www.applause.com/fr/plateforme-de-tests\" rel=\"alternate\" hreflang=\"fr-fr\"><link href=\"https://www.applause.com/de/testing-mit-applause\" rel=\"alternate\" hreflang=\"de-de\"><link href=\"https://www.applause.com/platform\" rel=\"alternate\" hreflang=\"x-default\"><link href=\"https://www.applause.com/platform\" rel=\"alternate\" hreflang=\"en-us\">"
    }
  }
}
```

Entry B: `seomatic(uri: "/applause-testing-platform")`

```
{
  "data": {
    "seomatic": {
      "metaLinkContainer": "<link href=\"https://www.applause.com/applause-testing-platform\" rel=\"canonical\"><link href=\"https://www.applause.com\" rel=\"home\"><link type=\"text/plain\" href=\"https://www.applause.com/humans.txt\" rel=\"author\"><link href=\"https://www.applause.com/fr/product-excellence-platform\" rel=\"alternate\" hreflang=\"fr-fr\"><link href=\"https://www.applause.com/de/product-excellence-platform\" rel=\"alternate\" hreflang=\"de-de\">"
    }
  }
}
```

### Another Example

Entry ID [223219](https://www.applause.com/who-we-are) has data in all 4 languages and is set up in Seomatic, but the alternate links show it is missing the Japanese language:

```
<link href="https://www.applause.com/who-we-are" rel="canonical">
<link href="https://www.applause.com/" rel="home">
<link type="text/plain" href="https://www.applause.com/humans.txt" rel="author">
<link href="https://www.applause.com/fr/qui-sommes-nous" rel="alternate" hreflang="fr-fr">
<link href="https://www.applause.com/de/wer-wir-sind" rel="alternate" hreflang="de-de">
<link href="https://www.applause.com/who-we-are" rel="alternate" hreflang="x-default">
<link href="https://www.applause.com/who-we-are" rel="alternate" hreflang="en-us">
```

### Things I have tried

- Triple checked all SEO settings in the admin area and on the entries
- Cleared cache (a lot, after every step)
- Manually disabling/enabling sitemap settings in Seomatic admin
- Manually disabling/enabling alternate link settings in Seomatic admin
- Manually disabling/enabling the entries in question entirely
- Resaving entries via back-end and cli
- Checked for updates to plugins and software - up to date
- Checked in staging environment and local - issue persists 

### Versions

- PHP version	7.4.3
- Craft Pro version 3.7.30.1
- SEO version 3.4.23

**Comment by khalwat** [comment]
Do these entries actually have content propagated to the additional languages, and have public URLs enabled?

Do any of them have an SEO Settings field that could be overriding the Robots setting?

There aren't too many conditions that would cause it to not render the alt URLs:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/DynamicMeta.php#L616

https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/Sitemap.php#L216

**Comment by mizziness** [comment]
> Do these entries actually have content propagated to the additional languages, and have public URLs enabled?

Yes, they do:

https://www.applause.com/applause-testing-platform
https://www.applause.com/de/product-excellence-platform
https://www.applause.com/fr/product-excellence-platform
https://www.applause.com/ja/product-excellence-platform

All are the same entry ID, 600004.

None of this is rendered with any custom templating and is all done via the plugin settings - I was hoping to not have to override on the template level because this is out-of-the-box functionality.

There is no custom routing or url rules, either.  All of this is just plain stuff.

**Comment by khalwat** [comment]
Assuming you are not using an SEO Settings field, SEOmatic's settings are the same for the entire section, so if the output differs from entry to entry, I would suspect it has something to do with the entry in particular, and perhaps how the sites are set up/grouped.

Do you have all of your sites in the same site group, as discussed here? 

https://nystudio107.com/docs/seomatic/technologies.html#multi-site-language-locale-support

Looking at the source to: https://www.applause.com/applause-testing-platform I see:

```html
<link href="https://www.applause.com/applause-testing-platform" rel="canonical">
<link href="https://www.applause.com/fr/product-excellence-platform" rel="alternate" hreflang="fr-fr">
<link href="https://www.applause.com/de/product-excellence-platform" rel="alternate" hreflang="de-de">
```

(Japanese is missing)

Looking at the source to: https://www.applause.com/ja/product-excellence-platform I see:

```html
<link href="https://www.applause.com/ja/product-excellence-platform" rel="canonical">
<link href="https://www.applause.com/fr/product-excellence-platform" rel="alternate" hreflang="fr-fr">
<link href="https://www.applause.com/de/product-excellence-platform" rel="alternate" hreflang="de-de">
```

(English is missing)

I think it is likely that something isn't quite configured right, I'm not seeing anything in the code that seems a likely candidate. 

Do you have an SEO Settings field in this Section's field layout?

**Comment by mizziness** [comment]
Yup, sure do, here are the settings for the page in Japanese:

![image](https://user-images.githubusercontent.com/4164335/153056521-374c0448-dbee-48d3-8301-5799315515e5.png)

![image](https://user-images.githubusercontent.com/4164335/153057458-391218a8-fd48-43e0-a2e3-a5a3aa965dad.png)

**Comment by khalwat** [comment]
I think there's too much going on here; would you be able to schedule a time we could screen share and step through it?

https://savvycal.com/nystudio107/chat

Caveat: I'm out of town this Thursday and Friday

**Comment by mizziness** [comment]
Absolutely!  I appreciate the willingness to help! <3

**Comment by khalwat** [comment]
Actually, before you book it -- I think you may be right after all that it could be related to the issue you linked to.

I have a fix for that, let me merge it in and we can see if that takes care of it for you.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/b7727307a0f58cba26f2e4c904dc3ef8db0b8828

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.24”,
```
Then do a `composer clear-cache && composer update`

To trigger it, if you go to edit the new site, then click on Save, it should trigger the resaving of the MetaBundles.

lmk how you go!

**Comment by mizziness** [comment]
Thanks! Just tried it out, but it doesn't seem to have fixed it. Steps followed:

- Used `"nystudio107/craft-seomatic": "dev-develop as 3.4.24",` in composer.json
- Ran `composer clear-cache && composer update`
- Confirmed Seomatic shows as version `dev-develop` in Craft cpanel
- Resaved all sites through Settings > Sites 
- Resaved all site settings through SEO > Site Settings
- Cleared CraftCMS caches, browser cache, and Cloudfront caches entirely

I did see several jobs run after saving via Settings > Sites, and the settings in SEO > Site Settings for Japanese had been wiped out - no biggie, not much to change.  Updated those and checked the Content settings for the section again, too. Still no dice.

Did I miss anything?

**Comment by khalwat** [comment]
If you go to the Sitemap Settings for the newly added Japanese site in SEOmatic -> Content SEO and save the changes there, does anything change?

Essentially that's what the pushed fix should have done, which is to default and save the site settings, which are saved in the `seomatic_metabundles` table.

Are you able to see if those look to be set correctly?

**Comment by khalwat** [comment]
Also if you could send your db & composer.json to: andrew@nystudio107.com that'd be helpful too

**Comment by mizziness** [comment]
> If you go to the Sitemap Settings for the newly added Japanese site in SEOmatic -> Content SEO and save the changes there, does anything change?

I tried this and no, no changes.  No jobs were created, either - I have the cli open and listening to the queue to see if it does anything.

Yes, will totally send them to you :) The database is *huge* - I apologize in advance.

**Comment by khalwat** [comment]
It doesn't create a queue job to resave the metabundles

**Comment by khalwat** [comment]
@mizziness if you sent the db & composer.json I did not receive them.

**Comment by khalwat** [comment]
Ping @mizziness

**Comment by khalwat** [comment]
Will re-open if additional information is provided.
