### ISSUE TITLE
Update/Save Tracking Scripts - Results in Full Site Breakage (array_merge(): error)

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#1063]
### Describe the bug
Adding/Updating Facebook Pixel ID results in a full site breakage with the following error:
`array_merge(): Expected parameter 2 to be an array, string given`

<img width="1123" alt="Screenshot 2022-02-11 at 16 15 16" src="https://user-images.githubusercontent.com/5698596/153630227-0b574969-3228-4792-9b21-d982e1de35a3.png">

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Tracking Scripts"
2. Click on "Facebook Pixel"
3.  Enter/Update the 'Facebook Pixel ID' and click save
4. Load the front-end and see the error `array_merge(): Expected parameter 2 to be an array, string given`

The same thing occurs even if you remove the  'Facebook Pixel ID' and hit save.
The same thing also occurs even if you try and set it via a ENV variable.
The only way to avoid this error is to Disable it entirely. 

### Screenshots
<img width="1123" alt="Screenshot 2022-02-11 at 16 15 16" src="https://user-images.githubusercontent.com/5698596/153630227-0b574969-3228-4792-9b21-d982e1de35a3.png">

### Versions
- Plugin version: 3.4.24
- Craft version: Craft Pro 3.7.32

**Comment by terryupton** [comment]
I think this might be a wider problem that actually affects all the Tracking Scripts.
I have just tested another tracking script (Google Analytics) one to see if it resulted in the same error and it did upon save.

Is this perhaps related to the new feature in the latest release 
`Added the ability to set <script> tag attributes for tracking scripts`

**Comment by khalwat** [comment]
Fixed in 3.4.25 https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.25
