### ISSUE TITLE
Content SEO disappeared suddenly 

### ISSUE THREAD

**Issue by market-south** [nystudio107/craft-seomatic#1064]
### Describe the bug
I am currently setting up a website with SEOmatic plugin, while setting up the conntent seo, it was working fine. From today, suddenly it started to be empty as belo

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Screenshots
![image](https://user-images.githubusercontent.com/91921916/153964007-9a50587f-960e-4c12-aedb-093ed3047655.png)

### Versions
- Plugin version: 3.4.25
- Craft version:3.7.32

**Comment by khalwat** [comment]
Does the website not have any sections at all yet?

What changed between when it was seemingly working, and now when it is not?

The plugin shouldn't just stop functioning in this manner, so something must have changed somewhere?

**Comment by lukew-cogapp** [comment]
HI Andrew,

We've also just experienced this issue. We have Solspace Calendar installed and made a change to one of the calendar/event content SEO settings.

We have several sections in the CMS and it was working fine before we saved this.

We have an error logging enabled, so hopefully that will help. SEOMatic is on the latest version and Craft is on 3.7.32

`array_slice(): Argument #3 ($length) must be of type ?int, string given`

`/app/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php in array_slice at line 1353`

The request that caused this error was:
```
curl \
 --compressed \
 -H "Accept: application/json, text/plain, */*" \
 -H "Accept-Encoding: gzip, deflate, br" \
 -H "Accept-Language: en-GB,en-US;q=0.9,en;q=0.8" \
 -H "Content-Length: " \
 -H "Content-Type: " \
 -H "Host: cms.mitmuseum.org" \
 -H "Mod-Rewrite: On" \
 -H "Referer: https://foo.bar/seomatic/content/default" \
 -H "Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"98\", \"Google Chrome\";v=\"98\"" \
 -H "Sec-Ch-Ua-Mobile: ?0" \
 -H "Sec-Ch-Ua-Platform: \"macOS\"" \
 -H "Sec-Fetch-Dest: empty" \
 -H "Sec-Fetch-Mode: cors" \
 -H "Sec-Fetch-Site: same-origin" \
 -H "Traceparent: 00-16d4976834882ca604cb976327d64c59-a4d0bb80467512e2-00" \
 -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36" \
 -H "X-Client-Ip: 185.95.77.130" \
 -H "X-Client-Ssl: on" \
 -H "X-Client-Verify: NONE" \
 -H "X-Forwarded-For: 185.95.77.130" \
 -H "X-Forwarded-Proto: https" \
 -H "X-Original-Route: https://foo.bar/" \
 "https://foo.bar/index.php?p=actions%2Fseomatic%2Fcontent-seo%2Fmeta-bundles&page=1&per_page=20&siteId=1&sort=sourceName%7Casc"
```

**Comment by khalwat** [comment]
@lukew-cogapp can you get me a complete stack trace for this error?

**Comment by khalwat** [comment]
Also if either of you are able to get a db dump and `composer.json` you can send to andrew@nystudio107.com that would be helpful!

**Comment by khalwat** [comment]
Are you using Solspace Calendar as well @market-south ?

**Comment by khalwat** [comment]
Pushed a potential fix in: https://github.com/nystudio107/craft-seomatic/commit/898f8e4ed88eb7ca8d9823993f577778f88d5ec1

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.26”,
```
Then do a `composer clear-cache && composer update`

**Comment by market-south** [comment]
Hi All,

I can understand that content SEO will not be accessible if the base URL is not set for the site. But in my case, the base URL exists and in addition to this, we noticed that the channel entries are picking the global SEO while they have their own SEO meta details. I tried to clear the cache under utilities, yet not resolvable. 

@khalwat no, I am not using Solspace Calendar 


Can you please advise on this?

**Comment by khalwat** [comment]
@market-south we'll likely have to arrange a video call to have a look, but it feels like something isn't configured quite right.

**Comment by khalwat** [comment]
@market-south If you want to help diagnose it, do the following:

1. Delete all of your logs in `storage/logs/`
2. Load the Content SEO page
3. Send all of the logs to andrew@nystudio107.com 

Essentially, I need more information to help you resolve this. This is not a general problem that I'm able to reproduce on any of my test sites, or client sites that use SEOmatic.

**Comment by lukew-cogapp** [comment]
Please note that I have tracked the problem down to disabling one of the following Sitemap related options:
![image](https://user-images.githubusercontent.com/83020016/154952156-01c52c21-b83e-48e3-b5c0-92d83a1e3669.png)

I'll email you the logs.

composer.json:

```
{
  "name": "craftcms/craft",
  "description": "Craft CMS",
  "keywords": [
    "craft",
    "cms",
    "craftcms",
    "project"
  ],
  "license": "0BSD",
  "homepage": "https://craftcms.com/",
  "type": "project",
  "support": {
    "email": "support@craftcms.com",
    "issues": "https://github.com/craftcms/cms/issues",
    "forum": "https://craftcms.stackexchange.com/",
    "source": "https://github.com/craftcms/cms",
    "docs": "https://craftcms.com/docs",
    "rss": "https://craftcms.com/changelog.rss"
  },
  "require": {
    "carlcs/craft-redactorcustomstyles": "^3.0",
    "craftcms/aws-s3": "^1.3",
    "craftcms/cms": "3.7.32",
    "craftcms/redactor": "^2.9",
    "diginov/craft-sentry-logger": "^1.2",
    "nystudio107/craft-seomatic": "^3.4",
    "platformsh/config-reader": "^2.4",
    "solspace/craft3-calendar": "^3.3",
    "verbb/expanded-singles": "1.1.5",
    "verbb/super-table": "2.7.1",
    "vlucas/phpdotenv": "^3.4.0"
  },
  "require-dev": {
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.2.5"
    },
    "allow-plugins": {
      "yiisoft/yii2-composer": true,
      "craftcms/plugin-installer": true
    }
  },
  "scripts": {
    "post-create-project-cmd": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\"",
      "@php -r \"unlink('composer.json');\"",
      "@php -r \"rename('composer.json.default', 'composer.json');\"",
      "@composer dump-autoload -o",
      "@php craft setup/welcome"
    ]
  }
}

```

**Comment by lukew-cogapp** [comment]
@khalwat I can confirm that the fix you referred to here, made the Content SEO come back:
`    "nystudio107/craft-seomatic": "dev-develop as 3.4.26",`

**Comment by market-south** [comment]
@khalwat Upgrading the plugin to the latest version resolved the content SEO issue. But we are still having problems with the channel entries picking the global SEO meta details and not their own meta details. 

Please note: single and structure entries are working fine by picking their own meta tags that are set up in the content SEO.  And we are able to see the correct meta tags of the channel entries when previewing the SEO.

Can you please advise on this.

**Comment by khalwat** [comment]
@market-south Can you start a new issue for this new/different problem with as much detail in terms of screenshots, settings, etc. as possible please?
