### ISSUE TITLE
Getting `Undefined index: security` when upgrading from 3.3.29 to 3.4.25

### ISSUE THREAD

**Issue by aaronbushnell** [nystudio107/craft-seomatic#1065]
### Describe the bug
I have a site that, after I updated SEOmatic from 3.3.29 to 3.4.25, the global content control panel area (/admin/seomatic/global/general/en_us) errors out with...

```
yii\base\ErrorException: Undefined index: security in /../src/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php:307
Stack trace:
#0 /../src/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/...', 307)
#1 /../src/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php(307): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/...', 307, Array)
#2 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionGlobal('general', 'en_us', NULL, NULL)
#3 /../src/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /../src/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /../src/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('global', Array)
#6 /../src/vendor/craftcms/cms/src/web/Application.php(292): yii\base\Module->runAction('seomatic/settin...', Array)
#7 /../src/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('seomatic/settin...', Array)
#8 /../src/vendor/craftcms/cms/src/web/Application.php(277): yii\web\Application->handleRequest(Object(craft\web\Request))
#9 /../src/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /../src/public/index.php(21): yii\base\Application->run()
#11 /.composer/vendor/laravel/valet/server.php(235): require('/...')
#12 {main}
```

### To reproduce
Steps to reproduce the behaviour:
1. When on SEOmatic 3.3.29, use `php craft update seomatic` to get to the latest version
2. Navigate to the Global Content control panel area in SEOmatic after update

### Expected behaviour
I expected that, if a table/index is missing, SEOmatic would attempt to create it so that this area is visible and does not error

### Versions
- Plugin version: 3.4.25
- Craft version: 3.7.32

**Comment by khalwat** [comment]
So... something is not right here. Changes were made that should update your bundles to have the appropriate settings.

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/c98982fd4efca797e36f015fdf54926ab751f71f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.26”,
```
Then do a `composer clear-cache && composer update`

**Comment by aaronbushnell** [comment]
Hm, still no dice on this one. If it's helpful I can provide you with the composer.json file and a copy of our database, @khalwat?

**Comment by khalwat** [comment]
@aaronbushnell can you verify for me that this actual code is in the file on the machine you're testing from?

https://github.com/nystudio107/craft-seomatic/commit/c98982fd4efca797e36f015fdf54926ab751f71f#diff-c3edda52a0935a5f66e70f65d9b0c895c7073699fcfd3d25cbca22740775eec9R389

It should look like this now:

```php
            // Handle an edge-case where a migration didn't work properly to add SECURITY_TXT_HANDLE
            if (!isset($templateContainers[FrontendTemplates::SECURITY_TXT_HANDLE])) {
                $globalMetaBundle = Seomatic::$plugin->metaBundles->createGlobalMetaBundleForSite($siteId, $metaBundle);
                $templateContainers[FrontendTemplates::SECURITY_TXT_HANDLE] =
                    $globalMetaBundle->frontendTemplatesContainer->data[FrontendTemplates::SECURITY_TXT_HANDLE];
            }
            $variables['securityTemplate'] = $templateContainers[FrontendTemplates::SECURITY_TXT_HANDLE];
```

And if that code is there, can you show me the error you're seeing now?

**Comment by khalwat** [comment]
Also, verify for me that your `src/seomatic-config/globalmeta/FrontendTemplatesContainer.php` looks like this:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/seomatic-config/globalmeta/FrontendTemplatesContainer.php#L52

**Comment by aaronbushnell** [comment]
Ah, good catch @khalwat! It was the lack of a `FrontendTemplates::SECURITY_TXT_HANDLE` in the `seomatic-config/globalmeta/FrontendTemplatesContainer.php` file.

Adding that has me situated here, thanks!

**Comment by khalwat** [comment]
@aaronbushnell You might want to re-install from scratch, it sounds to me like what you have installed is not the full current build, for whatever reason.

**Comment by aaronbushnell** [comment]
Hey @khalwat I _think_ it's just because I have my own `src/config/seomatic-config/globalmeta/FrontendTemplatesContainer.php` which was lacking the proper `security` key. Are you thinking that's not the case? Because this is what it was before when it was throwing that error:

```php
<?php


use nystudio107\seomatic\services\FrontendTemplates;
use nystudio107\seomatic\models\FrontendTemplateContainer;

return [
    'name'        => 'Frontend Templates',
    'description' => 'Templates that are rendered on the frontend',
    'handle'      => FrontendTemplates::FRONTENDTEMPLATES_CONTAINER,
    'class'       => (string)FrontendTemplateContainer::class,
    'include'     => true,
    'data'        => [
        FrontendTemplates::HUMANS_TXT_HANDLE => [
            'handle'          => FrontendTemplates::HUMANS_TXT_HANDLE,
            'path'            => 'humans.txt',
            'template'        => '_frontend/pages/humans.twig',
            'controller'      => 'frontend-template',
            'action'          => 'humans',
            'include'         => false,
            'templateString'  => '',
        ],
        FrontendTemplates::ROBOTS_TXT_HANDLE => [
            'handle'          => FrontendTemplates::ROBOTS_TXT_HANDLE,
            'path'            => 'robots.txt',
            'template'        => '_frontend/pages/robots.twig',
            'controller'      => 'frontend-template',
            'action'          => 'robots',
            'include'         => false,
            'templateString'  => '',
        ],
        FrontendTemplates::ADS_TXT_HANDLE => [
            'handle'          => FrontendTemplates::ADS_TXT_HANDLE,
            'path'            => 'ads.txt',
            'template'        => '_frontend/pages/ads.twig',
            'controller'      => 'frontend-template',
            'action'          => 'ads',
            'include'         => false,
            'templateString'  => '',
        ],
    ],
];
```

**Comment by khalwat** [comment]
Ah yes. That would do it. :)

**Comment by aaronbushnell** [comment]
Thanks a bunch for the quick assist here! 🙌
