### ISSUE TITLE
"Facebook OpenGraph Site Name Position Source" in Global SEO Missing " Same as Site Name Position" Option

### ISSUE THREAD

**Issue by jalendport** [nystudio107/craft-seomatic#1066]
### Describe the bug
After configuring how I want my site name positioned relative to the page title on the Global SEO > General page, I expect to be able to use the "Same as Site Name Position" option on the Facebook tab just like I can on the Twitter tab.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/6537823/154154613-4ef65bd9-3d27-4914-9fa8-069129d7a713.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/6537823/154154661-cb50dca2-fc6a-4529-af9f-d4fb8a3c6b3c.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/6537823/154154692-11340c84-90ab-46b1-ac7b-e5af137b3cff.png">

As it stands currently I'm only given the option to select "Custom Position" and then I have to redefine my choice in two places.

### Versions
- Plugin version: 3.4.20
- Craft version: 3.7.25.1

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/93e6777bea4f0956255f65251a59bb8a5838ef7e

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.26”,
```
Then do a `composer clear-cache && composer update`
