### ISSUE TITLE
Main Entity of Page override not working

### ISSUE THREAD

**Issue by bengreenbank** [nystudio107/craft-seomatic#1067]
### Describe the bug
In the SEOMatic field type, when I try to override the 'main entity of page' option, the dropdown doesn't appear below it.

![Screenshot 2022-02-18 at 10 44 40](https://user-images.githubusercontent.com/61185468/154668291-96f02e70-17a5-43da-93c5-f10ea6f6a04f.png)

### To reproduce
Steps to reproduce the behaviour:
1. Go to an entry with the SEOMatic field added.
2. Click on the override for 'main entity of page'.
3. See there is no dropdown available.

### Expected behaviour
The dropdown should be available to override the main page entity.

### Versions
- Plugin version: 3.4.25
- Craft version: 3.7.29 (Also tried with 3.7.32 but no luck)

**Comment by khalwat** [comment]
I'm unable to reproduce this:

<img width="732" alt="Screen Shot 2022-02-18 at 9 05 14 AM" src="https://user-images.githubusercontent.com/7570798/154697265-ec76ef45-8b3e-4722-a06d-3ee10484d0c4.png">

Can you check your JavaScript console to see if any errors are present?

Also try installing the plugin from scratch, to make sure the installation is complete.

**Comment by bengreenbank** [comment]
Thanks for getting back to me. I am getting this console error. Not sure if it's related.

<img width="1787" alt="Screenshot 2022-02-18 at 16 39 52" src="https://user-images.githubusercontent.com/61185468/154724866-307e38bd-7610-4a89-9c02-8bd3cfdce952.png">

I'm hesitatnt to uninstall the plugin just yet, as I don't want to delete any client field data.

**Comment by khalwat** [comment]
I'm not saying to uninstall the plugin... I mean delete it from the `vendor/` directory and re-install it via `composer install` or whatever method you're using.

Do you have anything else running that could potentially be loading scripts on this entry page? Another plugin, or some custom scripts or the like?

**Comment by khalwat** [comment]
Will re-open if more information is provided

**Comment by bengreenbank** [comment]
Hi. It seems the cause was a custom plug-in of ours that was running a conflicting version of the Vue axios package. We will investigate next week and let you know the outcome.

Thanks for the support!
