### ISSUE TITLE
Fathom Script Tag Attributes added on wrong script tag?

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft-seomatic#1068]
### Describe the bug
I'm attempting to add additional attribute (data-spa="auto") to the script tag. I assumed it would be placed on the script tag for the fathom script url just like "Excluded Domains" or "Site ID", but looks like it's being added on the script tag below.

### To reproduce
Steps to reproduce the behaviour:
1. SEOMatic > Tracking Scripts > Fathom
2. Enable, got to "Script Tag Attributes". Add a row. In the table, dd "data-spa" in "Attribute Name" and "auto" in "Attribute Value".
3. Refresh website pages and inspect script tags in head/foot.

### Expected behaviour
Expected it would be placed on the script tag for the fathom script url just like "Excluded Domains" or "Site ID".

### Screenshots
![Screen Shot 2022-02-18 at 8 31 16 AM](https://user-images.githubusercontent.com/18017918/154723839-2c039b2e-2a34-433f-ba77-f1272c44328b.png)

### Versions
- Plugin version: 3.4.25
- Craft version: Craft Solo 3.7.33

**Comment by khalwat** [comment]
No, that gets added to the `<script>` tag itself, as in your screenshot.

If you want to add it to the URL that is passed along to Fathom, edit the Twig template code for the script and add it there.

**Comment by brandondeweese** [comment]
The Script Template?

I tried to paste 'tag.setAttribute("data-spa", "auto");',  and when I save it, it disappears.

I'm assuming I'm still doing it wrong.

**Comment by khalwat** [comment]
So I think I figured it out... and it's a weird one. If you hit Command-S to save, it is not saving the changes you make to the script.

If you click on the Save button though, the changes will be saved.

**Comment by khalwat** [comment]
Okay so I figured out why it wasn't saving for you. If you save the settings by clicking on the Save button, everything works.

If you save the settings by hitting Command-S, it doesn't save any changes to the template code. Bug.

**Comment by khalwat** [comment]
Addressed the Command-S issue in: https://github.com/nystudio107/craft-seomatic/commit/f8509fe5ae9db0eb3422ebd4a33848b24fb742a0

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.26”,
```
Then do a `composer clear-cache && composer update`

**Comment by brandondeweese** [comment]
Thanks!
