### ISSUE TITLE
Global Variables cause downtime while create a new Draft

### ISSUE THREAD

**Issue by internetztube** [nystudio107/craft-seomatic#1071]
### Describe the bug
When creating a Draft or a Provisional Draft the whole Craft CMS Instance gets unresponsive. I dug my way through all the installed plugins and I found out that `image-optimize` and `seomatic` are causing this problem. 
I "resolved" the issue by commenting out the initialization of `SeomaticVariable` in `SeomaticTwigExtension`. 
https://github.com/internetztube/craft-seomatic/commit/3c07280b8d45acd1ded214a768c6b4db908d548b

Also see: https://github.com/nystudio107/craft-imageoptimize/pull/317

### To reproduce
1. Go to an entry with many matrix/neo blocks, so creating a draft takes a while.
2. Change an input value to trigger the creation of a provisional draft -or- click "Create a Draft".
3. While the loading spinner is spinning, try to open a different page like Dashboard or Utilities.
4. Those pages don't load until the draft saving process is complete.

### Expected behavior
Other pages should still open while creating a draft.

### Versions
- Plugin version: 3.4.26
- Craft version: 3.7.34

**Comment by khalwat** [comment]
This sounds to me a lot like an issue with Craft, which is potentially exacerbated by a combination of installed plugins.

**Comment by internetztube** [comment]
I disabled all plugins except Neo and Seomatic/ImageOptimize. Only works again when Seomatic and Image Optimize are deactivated. 
Do you want me to send you database dump plus project files so you can test it yourself?

**Comment by khalwat** [comment]
Try disabling the plugins one at a time. What happens, for instance, if you disable just the Neo plugin?

Are you using SEOmatic and ImageOptimize on any other websites, and are you seeing issues there as well?

**Comment by khalwat** [comment]
@internetztube ?

**Comment by internetztube** [comment]
Have not been able to reproduce the problem on a new craft instance with Matrix blocks instead of Neo blocks. However, we still have the problem. 😞
As mentioned before, when the lines of code in the PRs are commented out, the CMS does not block any more during the creation of a draft.

**Comment by khalwat** [comment]
Right, but it needs that service to load frontend resources.

Could it potentially be that something is timing out trying to load a URL? Possible server issue?

Does this happen on production, or on local dev, or both?

**Comment by khalwat** [comment]
Here's what doesn't make sense to me. You say you need to comment out this line from `ImageOptimize.php`:

https://github.com/nystudio107/craft-imageoptimize/pull/317/files

All this will do is cause the ViteService to instantiate itself, which calls the `::init()` method, that does this:

```php
    /**
     * @inheritDoc
     */
    public function init()
    {
        parent::init();
        // Only bother if this is a CP request
        $request = Craft::$app->getRequest();
        if (!$request->getIsCpRequest()) {
            return;
        }
        $this->invalidateCaches();
        // See if the $pluginDevServerEnvVar env var exists, and if not, don't run off of the dev server
        $useDevServer = getenv($this->pluginDevServerEnvVar);
        if ($useDevServer === false) {
            $this->useDevServer = false;
        }
        // If we have no asset bundle class, or the dev server is running, don't swap in our `/cpresources/` paths
        if (!$this->assetClass || $this->devServerRunning()) {
            return;
        }
        // If we're in a plugin, make sure the caches are unique
        if ($this->assetClass) {
            $this->cacheKeySuffix = $this->assetClass;
        }
        // Map the $manifestPath and $serverPublic to the hashed `/cpresources/` path & URL for our AssetBundle
        $bundle = new $this->assetClass();
        $baseAssetsUrl = Craft::$app->assetManager->getPublishedUrl(
            $bundle->sourcePath,
            true
        );
        $this->manifestPath = FileHelper::createUrl($bundle->sourcePath, self::MANIFEST_FILE_NAME);
        if ($baseAssetsUrl !== false) {
            $this->serverPublic = $baseAssetsUrl;
        }
    }
```

I'm not seeing anything in here that could/should have an impact.

**Comment by khalwat** [comment]
Any word from P&T @internetztube ?

**Comment by internetztube** [comment]
Not yet. @khalwat

**Comment by khalwat** [comment]
Let me know if you want to book a time we can look at it together to see if we can uncover anything on our own.

Are you able to replicate this issue on local dev as well as on production?

**Comment by angrybrad** [comment]
This should be resolved in https://github.com/craftcms/cms/commit/f9df875249402d8066761ba5ad90d76627d98b03 which will be in the next Craft release.

**Comment by khalwat** [comment]
Great, thanks @angrybrad !
