### ISSUE TITLE
Channel entries picking up the global meta details and not their own meta details

### ISSUE THREAD

**Issue by market-south** [nystudio107/craft-seomatic#1073]
### Describe the bug

Channel entries pick the global SEO meta details and not their own meta details in the front-end. we are able to see the correct meta tags of the individual channel entries when previewing the SEO in the CMS.
Please note: single and structure entries are working fine by picking their own meta tags that are set up in the content SEO. 

### To reproduce

Sorry I couldn't recreate this issue on other websites we build after that. I guess this is something to do specifically with this website. 

### Expected behaviour
We expect the channel entries to use the meta tag details that was set up in the Content SE.
### Screenshots

![image](https://user-images.githubusercontent.com/91921916/156051300-c8d78b4d-3d36-4f13-9dd5-392176c315f3.png)

![image](https://user-images.githubusercontent.com/91921916/156051350-78079553-145d-4389-82d2-8439e51c2932.png)

![image](https://user-images.githubusercontent.com/91921916/156051376-c6274295-97a0-4a76-b7b6-5845a3994bbf.png)

![image](https://user-images.githubusercontent.com/91921916/156051393-84af1ca2-fd7a-481f-8179-40e010662724.png)

Attached are the screenshots of the front end and from the SEO preview in CMS.
- Red colour: Structure entry
- Yellow colour: Channel entry

From the screenshot, you could see the structure entry is showing in an exact way in the front end. But the channel entry is picking the global SEO and not the one from its SEO settings. 

### Versions
- Plugin version: 3.4.26
- Craft version: 3.7.29

**Comment by khalwat** [comment]
Can you please check your code to see if you are _also_ including your own OG tags in your Twig templates? Because that `class="md"` isn't something that SEOmatic would be adding...

**Comment by market-south** [comment]
We are not including our own OG tags. 
We have a script on this website that will add "sm", "md", "lg", "xl" to the tags based on the screen size to apply different styles. 
We also have this script on another two Craft websites with SEOmatic plugin which are working fine.

**Comment by khalwat** [comment]
So I guess what I'd suggest doing if things are working fine on two other websites using SEOmatic is to look for the differences in the way you have things configured/set up for the ones that work vs. the one that does not.

**Comment by khalwat** [comment]
Will re-open if more information is provided.
