### ISSUE TITLE
security.txt Error rendering template string validator error when using seomatic variables

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-seomatic#1076]
### Describe the bug

I was trying to use the variable `{{ seomatic.site.twitterHandle }}` in the security.txt template, but I get the following error when trying to save the template from the validator.

> Error rendering template string -> Impossible to access an attribute ("twitterHandle") on a null variable in "__string_template__3a15b736956a8d59329a7db121ce36f9bc7dfec14996f4292eca08ace3cb293f" at line 3.

### Expected behaviour

The security.txt to be able to be saved with seomatic variables in use. It seems to work with other twig variables i.e. `{{ craft.something }}`

### Screenshots

![image](https://user-images.githubusercontent.com/8067792/156737742-3530be87-c206-44ac-bb4c-68ce57a5f1ad.png)

### Versions
- Plugin version: 3.4.26
- Craft version: 3.7.35

**Comment by khalwat** [comment]
SEOmatic's variables aren't injected in the context in which the "frontend templates" render currently.

Many of them wouldn't make sense in that context, so rather than having caveats or exceptions, I figured it made the most sense to just not include it.

**Comment by jamesmacwhite** [comment]
OK thanks for confirming, isn't this statement a bit leading though based on the current behaviour? I guess text fields means single line input, rather than multi line or other fields.

![image](https://user-images.githubusercontent.com/8067792/158648611-2e139fd2-ac62-44f9-add6-d0b3b6fc741c.png)

**Comment by khalwat** [comment]
Very misleading. Let me have a look at this.

**Comment by khalwat** [comment]
Oh wow my bad @jamesmacwhite -- this actually ends up being a bug in the `TwigExpressionValidator` class. I'm on it.

**Comment by khalwat** [comment]
So the information I gave you previously was completely wrong, sorry @jamesmacwhite -- I misremembered my intent.

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/0838a0c7149da1c3fb75168af3f14406644264b5

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.28”,
```
Then do a `composer clear-cache && composer update`

**Comment by jamesmacwhite** [comment]
@khalwat Thanks for looking into this and identifying the issue! No worries, glad I was able to flag it and get the bug fixed in the Twig validator!
