### ISSUE TITLE
Save entry in Control Panel hanging, timing out on update of craft_seomatic_metabundles

### ISSUE THREAD

**Issue by chadcrowell** [nystudio107/craft-seomatic#1079]
### Question
In the past few weeks, we have entries from certain sections hanging on save, even if nothing is changed in the entry. Many times the save executes after about 30-45 seconds, and occasionally it fails with:

SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
The SQL being executed was: UPDATE `craft_seomatic_metabundles` SET `dateUpdated`='2022-03-11 18:47:59', `sourceDateUpdated`='2022-03-11 18:47:59' WHERE `id`=10
Error Info: Array
(
    [0] => HY000
    [1] => 1205
    [2] => Lock wait timeout exceeded; try restarting transaction
)
↵
Caused by: PDOException

SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
in /srv/users/gcxadmin/apps/gcx-website/vendor/yiisoft/yii2/db/Command.php at line 1302

Is there a setting to disable this update on save in SeoMatic, or some other way to debug this particular query/transaction?

Craft CMS 3.7.36
Seomatic 3.4.26 (updated from 3.4.22 on 2/21)
Many other plugins but nothing newly installed
Site has been online for almost a year

**Comment by khalwat** [comment]
It's very unlikely this has anything to do with SEOmatic -- it sounds like whatever Craft is doing has the database locked for too long, and thus SEOmatic is unable to execute that database call. It's a very simple database transaction.

I'd be happy to help if this does somehow end up being related to SEOmatic, but I'm pretty sure it's going to end up being Craft or environmental.
