### ISSUE TITLE
Craft global set fields return NULL when SEOmatic is enabled

### ISSUE THREAD

**Issue by jimstrike** [nystudio107/craft-seomatic#108]
Craft global set fields return NULL when I enable SEOmatic. I have a global set called "companyInfo" and all text fields (text, redactor, number, email) added to its layout are returning NULL. 

"Entries" field type is working as normal. I am using Craft 3.0.6. I haven't tested with other field types.

**Comment by khalwat** [comment]
Try updating to Craft CMS 3.0.7; I think they may have changed some of how this works?

**Comment by jimstrike** [comment]
Updating Craft to 3.0.7 fixed the issue.

**Comment by nfourtythree** [comment]
I am still getting this issue with `Craft 3.0.11` and `SEOmatic 3.0.22` have a video of the issue here: http://x.n43.me/2e281H2K3a3p disabling SEOmatic shows the data again

**Comment by nfourtythree** [comment]
@khalwat any thoughts on this one? Let me know if you need extra info or need to jump on a screen share or anything

**Comment by khalwat** [comment]
This ends up being due to a custom site module that @nfourtythree had; likely he ran into this: https://github.com/craftcms/cms/issues/3028
