### ISSUE TITLE
missing message file

### ISSUE THREAD

**Issue by hiasl** [nystudio107/craft-seomatic#1082]
### Describe the bug
We are getting an error in the logs that a message file is missing:
`The message file for category 'seomatic' does not exist: /app/vendor/nystudio107/craft-seomatic/src/translations/de-DE/seomatic.php Fallback file does not exist as well: /app/vendor/nystudio107/craft-seomatic/src/translations/de/seomatic.php`

How can I fix this:
1.) I do not know why I would need a message file for this?
2.) The error is logged for frontend URLs, not CP Urls. Why is seomatic looking for this with frontend urls, isn't this unnecessary overhead?
3.) How can I fix this as the path is expected to be in the vendor folder? I would actually prefer Seomatic from even looking for the file.

### Versions
- Plugin version: 3.4.25
- Craft version: 3.7.22

Thank you!

**Comment by khalwat** [comment]
There is no German localization for SEOmatic currently, AFAIK you should not be seeing this message in production. It's a Yii/Craft-ism for any string you use that might need to be translated.

So this isn't something that "SEOmatic" is doing necessarily, it's something that all plugins/modules in Craft do.

If you want to track down exactly where it's coming from, I'd need to see the complete stack trace from the error.

I can say that the overhead is likely so tiny that it isn't measurable.

**Comment by khalwat** [comment]
Can re-open if more discussion is needed.
