### ISSUE TITLE
GraphQL explorer erroring out with seomatic related errors

### ISSUE THREAD

**Issue by J-Protz** [nystudio107/craft-seomatic#1083]
### Describe the bug
GraphQL Explorer reporting interface errors; not sure when error was introduced. Seems to still work via API endpoints and even when querying via explorer, but then it'll load an error seconds later.

I'm unsure if this is potentially causing issues elsewhere. I haven't used the explorer in a few months, was just showing a coworker it and the error popped up. It also seemingly stops autocomplete from working.

### To reproduce
Go to GQL explorer
Wait, or write a query.

### Expected behaviour
The normal explorer behavior with no errors.

### Screenshots

<img width="1918" alt="Screen Shot 2022-03-18 at 12 37 14 PM" src="https://user-images.githubusercontent.com/70289763/159044857-90dfc498-4355-4cdb-8243-7140fd23d8ed.png">

### Versions
- Plugin version:3.4.27
- Craft version:3.7.36

**Comment by khalwat** [comment]
I'm unable to reproduce this here:

<img width="1031" alt="Screen Shot 2022-03-18 at 12 43 56 PM" src="https://user-images.githubusercontent.com/7570798/159046066-e88877ff-b63c-4823-af6a-676451ce5e0f.png">

I'd suggest trying to clear your caches & invalidate the GraphQL schema. I'm pretty sure this isn't an issue in SEOmatic, but happy to re-open or continue to assist if you find otherwise!

**Comment by J-Protz** [comment]
Thank you for the quick reply - surprised I didn't consider caches. I just cleared everything from utilities -> caches, but the error is persisting. Any other ideas?

**Comment by khalwat** [comment]
Do you have a field named "seomatic" by any chance?

**Comment by J-Protz** [comment]
....Turns out I do indeed. It's just SEO settings and not referenced anywhere that I know of. I guess I should change it? Weird it never caused any issues until recently!

**Comment by khalwat** [comment]
Worth a shot -- try changing the name / handle to something else like maybe just "SEO" or something

**Comment by J-Protz** [comment]
Change of field + another cache bust did it! 10/10 you're a genius :)
