### ISSUE TITLE
Feature Request: Link to main sitemap on Dashboard

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#1085]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

I can never remember how to find the sitemap generated by SEOmatic.  A prominent link/button, to the main sitemap, on the SEOmatic dashboard would be helpful

### Describe the solution you would like
A clear and concise description of what you would like to have happen.

A prominent link/button, to the main sitemap, on the SEOmatic dashboard would be helpful

![image](https://user-images.githubusercontent.com/6899490/159924702-990db826-deed-4bb2-b679-bce267424219.png)

**Comment by khalwat** [comment]
What would the use-case be here? It should always be at: `/sitemap.xml` the standard location

**Comment by CreateSean** [comment]
clients keep asking where the sitemap is at launch. I can never remember - but if there's a button there anyone can find it easily.

**Comment by CreateSean** [comment]
Yet once again I had to google to find out where the sitemap xml is located. Would be really handy to include it in the dashboard cause then the client would know where to find it too.

**Comment by khalwat** [comment]
Acknowledged.

**Comment by khalwat** [comment]
So this is my bad... I feel really dumb for not remembering this, but I went to go add this feature to SEOmatic, and it's already there! :)

<img width="1275" alt="Screenshot 2023-04-30 at 4 33 52 PM" src="https://user-images.githubusercontent.com/7570798/235375087-011b0c78-6db3-4ea3-85be-474f7cb9cc79.png">

But really it should be in the Global sitemap settings page too. So I'll add it there.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/66034359e63aa7b943e11ad0260dd739ba3f9ff5 & https://github.com/nystudio107/craft-seomatic/commit/10bfaa51c2486f77459dc07cd21f756e018f40a2

<img width="1275" alt="Screenshot 2023-04-30 at 4 50 08 PM" src="https://user-images.githubusercontent.com/7570798/235375926-2c5e2c55-5335-495d-80eb-c5d97e958819.png">


Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.53”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.24”,
```
Then do a `composer clear-cache && composer update`
