### ISSUE TITLE
sitemap.xml not found

### ISSUE THREAD

**Issue by QUACK07** [nystudio107/craft-seomatic#1086]
### Question
Hi team, I have a question about what is necessary for sitemap to work?

### Additional context
I have a local env, and everything on it works fine on the hub dashboard but when I try to open a sitemaps.xml I got a Not found error

I have been tried ./craft seomatic/sitemap/generate and it runs ok, with no errors, but I can't see sitemaps yet.

<img width="634" alt="Screen Shot 2022-03-24 at 17 48 46" src="https://user-images.githubusercontent.com/17518469/160028047-cdc7957f-3149-43ce-bc77-2cf6743bf712.png">

**Comment by khalwat** [comment]
It should be:

`sitemap.xml` -- no plural on that

If that doesn't work, it's very likely some kind of a local dev setup issue. Make sure you don't have any server rewrite rules applied to `sitemap.xml`

**Comment by QUACK07** [comment]
I´m working with PHP -S, and it doesn't have any error or rewrite rule on it, actually when I run the generate, everything runs ok

**Comment by khalwat** [comment]
That's likely why -- you're using a single-process web server so queue jobs can't run in a separate process. I'd recommend setting up a local dev environment using one of the available tools like Valet, DDEV, Nitro, etc.
