### ISSUE TITLE
jsonLd breadcrumbList includes entries that are disabled

### ISSUE THREAD

**Issue by FrDH** [nystudio107/craft-seomatic#1088]
### Describe the bug
The jsonLd breadcrumbList includes entries what are disabled and there is no way of telling they are disabled.
In other words, the ListItem.item points to a 404

### To reproduce
Create a subpage in a structure and disable its parent, visit the subpage and check the breadcrumblist.

### Expected behaviour
I guess a disabled page should not appear in the breadcrumblist at all or it should not have an `item` setting, but for us a simple "disabled" flag or something the like would be sufficient.

### Versions
- Plugin version: 3.4.28
- Craft version: 3.7.37

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/b2d5e8100edcdf9d8a92389f67b14ef7458bf491

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.29”,
```
Then do a `composer clear-cache && composer update`
