### ISSUE TITLE
Add custom routes to the Sitemap

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-seomatic#109]
Add any custom routes as a separate Sitemap index, with all of the routes listed in that Sitemap.

**Comment by ryanmasuga** [comment]
We could do this in the Sitemap module we used to use on our Craft 2 sites, so it would be nice to see here as an option. Good for pages that don't really even need a single, or that are very deep and don't belong to any specific section.

**Comment by khalwat** [comment]
This was added in SEOmatic 3.1.3. There is also the ability to do it via a plugin/module:

```php
use nystudio107\seomatic\events\RegisterSitemapUrlsEvent;
use nystudio107\seomatic\SitemapCustomTemplate;
use yii\base\Event;
Event::on(SitemapCustomTemplate::class, SitemapCustomTemplate::EVENT_REGISTER_SITEMAP_URLS, function(RegisterSitemapUrlsEvent $e) {
$e->sitemapUrls[] => [
         'loc' => $url,
         'changefreq' => $changeFreq,
         'priority' => $priority,
         'lastmod' => $lastMod,
     ];
 });
```
