### ISSUE TITLE
Wrong JsonLd data for unavailable product

### ISSUE THREAD

**Issue by bavocorteville** [nystudio107/craft-seomatic#1090]
### Describe the bug
When a product is not available for purchase, the JsonLd showing wrong data:
- availability is in stock
- price is visible

### Expected behaviour
The availability and price should be removed from the JsonLd.

### Versions
- Plugin version: 3.4.28 
- Craft version: 3.7.37

**Comment by khalwat** [comment]
Tell me what you'd constitute as an "unavailable" product? Also you can change the JSON-LD as you see fit:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#robust-twig-api

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

**Comment by nitech** [comment]
@khalwat Was this ever fixed? The default output of json-ld should relate to whether the product is purchasable or not. Atm. a lot of my customers non-purchasable products are displayed in Google as purchasable, in stock and with a price, even though they are not.

**Comment by khalwat** [comment]
@nitech Tell me what you'd constitute as a "non-purchasable" product?

**Comment by nitech** [comment]
A product that we have and want to display on our website, but we can't sell online because it's more a "concept" than a product. Instead of allowing the customer to purchase the product, we display a contact form where they can get in contact with the correct sales person. 

Or it could be, like in our case, that we have launched the site without the ability to purchase any product at all. We use Craft Commerce for organizing and editing the products, we plan to launch a webshop at some point, but in the mean while we make info about the products available, but we don't disclose the price as there is no integration with the ERP-system yet, and thus the prices are (mostly) outdated. 

In the template itself we check if the product is purchasable (which btw is a "native" boolean in Craft Commerce, not something I came up with), and if true we display the price in the product info and if not, we hide. 

What I miss is the json-ld relating to the purchasable lightswitch.

**Comment by khalwat** [comment]
So the basic idea is that SEOmatic provides some reasonable defaults for JSON-LD product info, shown here:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/seomatic-config/productmeta/JsonLdContainer.php#L31

If the changes you're suggesting are something that would be generic to everyone, then I'd be happy to look at what you think the code should look like for the default values.

If you have more complex logic, then the idea is you write some Twig template code to express that, and modify the JSON-LD to suit your liking, examples of which are here:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#robust-twig-api

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

**Comment by nitech** [comment]
When "Available for purchase" is off: 

![image](https://user-images.githubusercontent.com/1279436/197153308-aa29eb64-c36d-4ea9-ab6b-f6772dd24be1.png)

I believe the JSON-ld data should omit the entire offers-attribute, since there is in fact no offer. 

```
'offers' => [
    'type' => 'Offer',
    'url' => '{{ seomatic.meta.canonicalUrl }}',
    'price' => '{{ product.getDefaultVariant().getPrice()|number_format(2, ".", "") }}',
    'priceCurrency' => '{{ craft.commerce.paymentCurrencies.primaryPaymentCurrencyIso() }}',
    'offeredBy' => [
        'id' => '{{ parseEnv(seomatic.site.identity.genericUrl) }}#identity',
    ],
    'seller' => [
        'id' => '{{ parseEnv(seomatic.site.identity.genericUrl) }}#identity',
    ],
    'availability' => 'http://schema.org/{% if product.hasUnlimitedStock or product.totalStock > 0 %}InStock{% else %}OutOfStock{% endif %}',
],
```

**Comment by nitech** [comment]
Alternatively perhaps you could show me how I can manipulate the data before outputting it to the webpage? 

I find some examples of adding to the JSON-ld object, but I can't seem to see an example of how to remove data: 
https://nystudio107.com/docs/seomatic/using.html#json-ld-meta-object-functions-seomatic-jsonld

**Comment by khalwat** [comment]
@nitech whole bunch of examples of manipulating the data here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

**Comment by nitech** [comment]
Thanks, this worked. I used this twig-snippet: 

```twig
{# Modify json-ld by removing offers if not available for purchase #}
{% if (product is defined) %}
    {% if (not product.availableForPurchase) %}
        {% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
        {% do mainEntity.setAttributes({
            'offers': ''
        }) %}
    {% endif %}
{% endif %}
```

I do however notice that Google Console is not quite happy (and I can't add review or aggregateOffers): 

![image](https://user-images.githubusercontent.com/1279436/201035673-70edab98-6311-4810-8cee-4c47bd72f1fa.png)

Do you think it would be more happy if I only removed the price and not the entire offer? How would I modify the twig code to do that, if so?

**Comment by khalwat** [comment]
I think it would be more happy if `offers` existed, but expressed no price, yes. Though based on the verbiage, it'd also be fine with you removing `offers` if you added in `aggregateRating` or `review` as well.

For a look at modifying existing JSON-LD, there are a number of examples in the article I linked to above.
