### ISSUE TITLE
hreflang and x-default not rendering

### ISSUE THREAD

**Issue by tsawitzki** [nystudio107/craft-seomatic#1091]
### Describe the bug
I have two locales setup in the CP: EN and DE, both in the same sitegroup (as requested by SEOmatic docs).
SEOmatic is set to "autorender" and puts out all the the meta data as expected – except for the `hreflang` indications although the feature is explicitely activated in the plugin settings.

### To reproduce
Steps to reproduce the behaviour:
1. Setup new locale in same sitegroup
2. Translate entries to new locale
3. Make sure all "hreflang" switches in SEOmatic’s settings are checked/activated
4. Have frontend render any locale entry
5. Check source code
6. See all SEOmatic data rendered, except the important `hreflang` and `x-default` tags

### Expected behaviour
With the switches activated I’d expect to see proper meta references to the translated version of the entry. No idea why it is ignored?

- Plugin version: 3.4.28
- Craft version: 3.7.37

**Comment by khalwat** [comment]
SEOmatic will automatically make `hreflang` links for any CMS content that is translated into another locale, assuming that it is enabled, has a URL, and the translation method is correct.

Can you give me detail with screenshots, links, etc. to help me help you here?

**Comment by tsawitzki** [comment]
Hey @khalwat, find a few screenshots attached which should explain my setup better. Hope that helps?
(Apologies upfront if I missed a very basic point setting it up.

![Bildschirmfoto 2022-04-01 um 12 19 53](https://user-images.githubusercontent.com/9975042/161246259-7337304d-6717-41db-8ec5-d42241553359.jpg)
![Bildschirmfoto 2022-04-01 um 12 27 08](https://user-images.githubusercontent.com/9975042/161246302-32b88478-e458-4ef4-8d31-d83bf4bc103d.jpg)
![Bildschirmfoto 2022-04-01 um 12 24 11](https://user-images.githubusercontent.com/9975042/161246329-8c05a4b9-1da0-4e07-9794-7258926f1a9f.jpg)
![Bildschirmfoto 2022-04-01 um 12 22 08](https://user-images.githubusercontent.com/9975042/161246343-96738ac7-ac1b-496d-838b-3285ff9e0b2e.jpg)
)

**Comment by khalwat** [comment]
Is the English site enabled, and does it have URLs? Ensure that **This site has its own base URL** is checked, and there is an actual **Base URL** entered.

**Comment by tsawitzki** [comment]
Site is enabled (green dot), switch at "This site has …" is checked and the Base URL is `@web/en`

**Comment by khalwat** [comment]
Something must not be right with the multi-site setup... in the screenshot you're showing, I'm only seeing a single `og:locale` for example... which makes it seem like it's not even seeing the `en` site for some reason.

**Comment by tsawitzki** [comment]
@khalwat ok, weird. How can I further assist you for debugging this?

**Comment by khalwat** [comment]
So here's an example test site I have with two languages in the same site group (`plugindev`):

<img width="1163" alt="Screen Shot 2022-04-04 at 2 30 09 PM" src="https://user-images.githubusercontent.com/7570798/161608490-6ff47186-cef5-480e-b470-aee479a2f8db.png">

They are both enabled and set to have their own base URL:

<img width="1163" alt="Screen Shot 2022-04-04 at 2 30 51 PM" src="https://user-images.githubusercontent.com/7570798/161608610-4491370d-f773-4a17-9ae2-0e8df7458df1.png">
<img width="1163" alt="Screen Shot 2022-04-04 at 2 31 24 PM" src="https://user-images.githubusercontent.com/7570798/161608664-40b034ba-9fa0-4753-9917-fdae33ea866e.png">

The Homepage single is enabled for both sites:

<img width="1163" alt="Screen Shot 2022-04-04 at 2 32 21 PM" src="https://user-images.githubusercontent.com/7570798/161608895-1eb5711c-1064-4ea6-8d10-b2025d1c46c4.png">

....and the Single is set to be enabled for both languages:

<img width="1159" alt="Screen Shot 2022-04-04 at 2 33 14 PM" src="https://user-images.githubusercontent.com/7570798/161609030-31a17c71-1017-4ba2-9465-83dd7f7eb532.png">

...which results in SEOmatic generating this on the home page:

```html
<title>🚧 Project | Homepage</title><meta name="generator" content="SEOmatic">
<meta name="referrer" content="no-referrer-when-downgrade">
<meta name="robots" content="none">
<meta content="en_US" property="og:locale">
<meta content="es_ES" property="og:locale:alternate">
<meta content="Project" property="og:site_name">
<meta content="website" property="og:type">
<meta content="http://localhost:8003/" property="og:url">
<meta content="Homepage" property="og:title">
<link href="http://localhost:8003" rel="home">
<link type="text/plain" href="http://localhost:8003/humans.txt" rel="author">
<link href="http://localhost:8003/es" rel="alternate" hreflang="es">
<link href="http://localhost:8003" rel="alternate" hreflang="x-default">
<link href="http://localhost:8003" rel="alternate" hreflang="en-us">
```

...so maybe look for any differences in your setup?

**Comment by khalwat** [comment]
Does that help @tsawitzki ?

**Comment by tsawitzki** [comment]
@khalwat Thanks for the screenshots, Andrew! I double-checked and I can confirm that I have everything setup exactly as in your screenshots. I am sorry to say that I have no clue what I could be doing wrong …

**Comment by tsawitzki** [comment]
@khalwat the only thing that differs from your example is that I have no Single section setup for the homepage, I only work inside a Structure and a few more Channels (see the attached screenshot). As I see that you have the dedicated homepage Checkboxes clicked for boths sites: I have only a "Homepage" entry within my Structure that is set to the system native slug `__home__` in both languages.
Just in case that this might be the culprit, I attached my Structure setup.

![Bildschirmfoto 2022-04-06 um 11 26 33](https://user-images.githubusercontent.com/9975042/161944100-d7541ddb-ebbe-4bae-b5fa-09a90354b521.jpg)
?

**Comment by khalwat** [comment]
Well, does the problem happen on any other pages, or just the homepage in particular?

Do you have any other Craft projects that use SEOmatic, and are you running into this issue with them as well?

**Comment by tsawitzki** [comment]
All pages actually, and not, it’s not happening with the other project where I have multi language support and SEOmatic running …

**Comment by khalwat** [comment]
I would look for differences between the project you have where it works, and the project you have where it does not work.

**Comment by khalwat** [comment]
Will re-open if more information comes to light. Short of that, the only thing we could do is a screen share.

**Comment by tsawitzki** [comment]
@khalwat please let me know how we could arrange that and what fees would apply. shall I write you through your website contact?

**Comment by khalwat** [comment]
You can book it here:

https://savvycal.com/nystudio107/chat

You'll need a version of your website running in local dev that we'll be able to hack on a bit to see what is going wrong.

**Comment by khalwat** [comment]
I waited on our meeting for 15 minutes, then gave up.

Please re-schedule a meeting if you'd like to try to meet up again.

**Comment by khalwat** [comment]
This ended up being that the **Sitemap Enabled** setting was off in SEOmatic -> Content SEO -> Sitemap
