### ISSUE TITLE
`Failed to set unsafe attribute` errors

### ISSUE THREAD

**Issue by jrrdnx** [nystudio107/craft-seomatic#1092]
### Describe the bug
I have a Careers channel in place with custom fields mapping to all of the properties from the [JobPosting schema](https://schema.org/JobPosting).  On the `_entry` template for that channel, I'm getting the Main Entity and calling setAttributes() like so:
```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{% do mainEntity.setAttributes({
    ...
    'estimatedSalary' : entry.estimatedSalary,
    'eligibilityToWorkRequirement' : entry.eligibilityToWorkRequirement,
    'experienceInPlaceOfEducation' : entry.experienceInPlaceOfEducation,
    'hiringOrganization' : seomatic.site.siteName,
    ...
}) %}
```

Both the `eligibilityToWorkRequirement` and `experienceInPlaceOfEducation` are missing from the JSON output. I've verified both are showing the correct output elsewhere in the template outside of this block (a string of 'test' for the former, and an integer of `1` for the latter as it's a Lightswitch field).

In the web.log file, these are both referenced as follows:
```
2022-03-29 15:13:39 [-][161][1vuthtauunab2umjboqvlbn12l][trace][yii\base\Model::onUnsafeAttribute] Failed to set unsafe attribute 'eligibilityToWorkRequirement' in 'nystudio107\seomatic\models\jsonld\JobPosting'.
2022-03-29 15:13:39 [-][161][1vuthtauunab2umjboqvlbn12l][trace][yii\base\Model::onUnsafeAttribute] Failed to set unsafe attribute 'experienceInPlaceOfEducation' in 'nystudio107\seomatic\models\jsonld\JobPosting'.
```

### Versions
- Plugin version: 3.4.28
- Craft version: 3.7.37

**Comment by jrrdnx** [comment]
After some additional digging while creating this issue, it appears neither of those properties are currently present in `src/models/jsonld/JobPosting.php` so I'd be happy to submit a pull request to add those and any other missing properties unless you have a way of doing this programmatically as schema.org is updated.

However, I'm now curious. It seems like a ton of data to have included in all of those files in `src/models/jsonld/` with all of the properties, descriptions, expected types, etc. Is this being utilized anywhere within the plugin that would negate having to create all of these fields manually?

**Comment by khalwat** [comment]
Yes, these properties were added in a relatively recent update to the schema.org types, that's why they aren't present in the SEOmatic models.

**Comment by khalwat** [comment]
This is something I've been working on a long-term fix to, we just need to do some testing: https://github.com/nystudio107/schemagen

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d9c97e0fc60782d15e6963339c6a3408b48cbce0 & https://github.com/nystudio107/craft-seomatic/commit/895cfa31bd41098610df23a34bf390235d9f58a2

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.31”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.1”,
```
Then do a `composer clear-cache && composer update`
