### ISSUE TITLE
TURN OFF SEO field in preview

### ISSUE THREAD

**Issue by wmdhosting** [nystudio107/craft-seomatic#1095]
Can you add option in settings to TURN OFF SEO field in preview
![Snag_169289d8](https://user-images.githubusercontent.com/76176291/161265427-67cf12bb-bacf-4967-ba0c-f8f9a943c5de.png)

**Comment by khalwat** [comment]
You can do that via the **SEO Preview** setting in the SEO Settings field settings:

<img width="534" alt="Screen Shot 2022-04-01 at 12 41 59 PM" src="https://user-images.githubusercontent.com/7570798/161306370-74c97059-6a72-4f3b-904b-65fa4018a3cd.png">
