### ISSUE TITLE
Google search results image  

### ISSUE THREAD

**Issue by wmdhosting** [nystudio107/craft-seomatic#1096]
Just info: Testing last couple months  with SEO image.

1. Google for search results show image that is in asset field, not  image specifed as SEO image.
2. Cant get in any way to show whole image, allways is shown just part of image no matter transform mode.

**Comment by khalwat** [comment]
You can _suggest_ to Google what to use for an SEO image, but you cannot _tell_ it what it should use. It sounds like Google is not using the image that is being suggested, but that's beyond our control unfortunately.
