### ISSUE TITLE
The sitemap just disappears at a certain moment

### ISSUE THREAD

**Issue by Romanavr** [nystudio107/craft-seomatic#1098]
### Describe the bug
We have about ten sites where SEOmatic is used. Everywhere a different set of plugins, somewhere blitz is used, somewhere not, somewhere it is cached through redis, somewhere by default (locally).
But on all sites, sooner or later, the sitemap simply disappears, this can happen after a few hours or in 1 day, after the moment the sitemap was generated through the console or by clicking on the link in index of sitemaps, doesn't matter.
There are no errors in the logs, the date cache is not cleared, the devMode is turned off, there was an idea. that blitz is to blame, but clearing its cache does not kill cache of the sitemap. 
I will add that the daemon is running 24/7 for `queue/listen --verbose`, so nothing will change if you go to the control panel

### To reproduce
Generate a sitemap and wait a few hours or a day.

### Expected behaviour
The sitemap should not be removed by itself.

### Screenshots
-

### Versions
- Plugin version:  since 3.4.26
- Craft version: since 3.7.34

**Comment by khalwat** [comment]
Can you give me a URL where I can see this happening?

When you say it "disappears" what does that mean? Wheat do you see when you try to load it?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/71c8eac092fdf590e10c570f2230a51156790e32

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.29”,
```
Then do a `composer clear-cache && composer update`
