### ISSUE TITLE
Multisite same S3 bucket different cloudfront volume url in sitemap

### ISSUE THREAD

**Issue by WHITE-developer** [nystudio107/craft-seomatic#1099]
Not sure if it's a question or bug or FR, but this is the case:
We have a multi site environment, all sharing the same S3 bucket.
We want to use cloudfront with a custom cname so the cloudfront url is branded for the sites.
To accomplish that we set an alias for the volume Base URL and then override that alias in a module based on the current site.

But it seems that the sitemap generation is always using the default site to get the volume base url.
Any ideas?

defaultsite.com -> static.defaultsite.com
secondsite.com -> static.secondsite.com instead of static.defaultsite.com

**Comment by khalwat** [comment]
Probably your custom module code that swaps in an alias isn't running in the context of sitemap generation.

I'd suggest just setting up a separate Asset Volume for each site that all point to the same S3 bucket.
