### ISSUE TITLE
gtag is not working

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft-seomatic#110]
Hello,

Please see the attached image.

![screenshot-2018 05 16-14-40-29](https://user-images.githubusercontent.com/1551388/40117430-3f172cf0-5917-11e8-9ea3-e40c9f5ebd65.png)

The source code look like this

`

<script type="b092e8913fb6a57229396bb8-">window.dataLayer = window.dataLayer \|\| [];
--
  | function gtag(){dataLayer.push(arguments)};
  | gtag('js', new Date());
  | gtag('config', 'UA-89873242-1', {'send_page_view': true,'anonymize_ip': false,'link_attribution': false,'allow_display_features': true,});
  | gtag('config', 'AW-927368289', {'send_page_view': true});</script>

`

analytics and adwords tracking are not working.

	
SEOmatic 3.0.13

**Comment by khalwat** [comment]
Right you are. This should be fixed in https://github.com/nystudio107/craft-seomatic/commit/14034d526360bfbe7b67396684879d5da0adde44
