### ISSUE TITLE
Structured data with syntax errors detected

### ISSUE THREAD

**Issue by toddpadwick** [nystudio107/craft-seomatic#1101]
### Describe the bug
I am using Graphql to query SEOMatic meta.
However, in one of our sites, we've got the following Google Search Console error:
'Structured data with syntax errors detected'

The way in which we're querying this meta containers is the same on all our sites, but this site is the only one that's returning these errors: https://usrem.co/
Here is a screenshot of the two errors along with the code snippets that seem to be affected
![Screenshot 2022-04-08 at 13 48 30](https://user-images.githubusercontent.com/36191462/162430021-090217d3-6937-4f99-97b3-d323ce72b715.png)

![Screenshot 2022-04-08 at 13 48 27](https://user-images.githubusercontent.com/36191462/162430037-6557c329-da27-4fc7-ad34-d20024b66dc7.png)

![Screenshot 2022-04-08 at 13 48 33](https://user-images.githubusercontent.com/36191462/162430045-9ace2428-f0be-46cd-a676-f8e7419341eb.png)

### Versions
- Plugin version:3.4.28
- Craft version:Craft Pro 3.7.37

**Comment by khalwat** [comment]
This doesn't look like an issue caused by SEOmatic -- it looks like whatever you're doing to render the JSON-LD via Nuxt is not working as expected.

If you have other similar sites that are working correctly, I'd suggest comparing what is different between them.
