### ISSUE TITLE
[Craft4] Cannot assign null to property nystudio107\seomatic\Seomatic::$cacheDuration of type int

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft-seomatic#1102]
### Describe the bug

Played a bit around with Craft4 and the latest SEOMatic Version. If I disabled the devMode I run in this error:

`Cannot assign null to property nystudio107\seomatic\Seomatic::$cacheDuration of type int`

debugged a bit in `src/seomatic.php` and did a `var_dump(self::$settings->metaCacheDuration)` and the output was "null" string(4)

### To reproduce
Steps to reproduce the behaviour:
1. Disable devMode within local environment

### Screenshots
![CleanShot 2022-04-08 at 18 40 50](https://user-images.githubusercontent.com/764292/162485272-5eca9810-8e7c-47fc-b31a-d081f8be2916.png)

### Versions
- Plugin version: v4.x-dev
- Craft version: Craft 4 Beta 4

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/e5af69e67a210bdc112f3fd4fa9ed5fb1472d5b1
