### ISSUE TITLE
live preview breaks after SEOmatic installation

### ISSUE THREAD

**Issue by quickstar** [nystudio107/craft-seomatic#1103]
### Describe the bug
As soon as we've installed the SEOmatic plugin to our Craft instance, the default life preview as well as the preview of Craft seems completely broken. Instead of the showing our page content only the SEO preview is shown. 
If I disable `Display Sidebar SEO Preview` as well as `Add Social Media Preview Target` setting in the SEOmatic plugin the respective buttons completely disappear in craft.

### Versions
- Plugin version: 3.4.29
- Craft version:Craft Pro 3.7.38

**Comment by khalwat** [comment]
This is no an issue with SEOmatic, this is an issue with Craft CMS, and missing preview targets for the channel in question.

Apparently the issue can happen when upgrading from Solo to Pro.

See here for details: https://github.com/nystudio107/craft-seomatic/issues/684#issuecomment-658467862

**Comment by quickstar** [comment]
Wow that was fast! Indeed we recently did upgrade to the Pro edition! Thanks very much for #684 works like a charm 🚀
