### ISSUE TITLE
Same issues, different install. Please update Content SEO docs. 

### ISSUE THREAD

**Issue by outline4** [nystudio107/craft-seomatic#1104]
Hi, 

Every time I use the SEOmatic plugin I seem to run into the same issues.  

I hope you'll find the time to clarify some stuff that I haven't really found in the documentation. 

It's the Content SEO section that gives me the most headaches. 

### SEO Title Source
I want to display the field `cf_metaTitle` if it exists and as a fallback the `title` field:
So in "Content SEO" under "SEO Title Source" I specify "Custom Text" and enter the following: 
`{{ entry.cf_metaTitle ??? entry.title }}`  
This works! YAY! 

### SEO Description Source
For the Meta description I want to use the field `cf_metaDescription` and if not filled out the meta description I defined in Global  SEO under SEO Description Source with Custom Text.  
So to my understanding I need to specify the following:   
`{{ entry.cf_metaDescription ??? seomatic.meta.seoDescription }}` but that doesn't work?!  
instead this works:  
`{{ entry.cf_metaDescription ??? global.seoDescription }}`  
I don't even know where I found out about the `global`thing, but it's definetly not in the docs... 

### SEO Keywords Source
So I want to add keywords to the global keywords when the field `cf_meta_keywords` is filled in. 
This would be the following code:  
`{{ entry.cf_meta_keywords ? entry.cf_meta_keywords ~ ',' ~ global.seoKeywords : global.seoKeywords }}`  
this will become this:  
<img width="767" alt="Bildschirmfoto 2022-04-12 um 15 48 37" src="https://user-images.githubusercontent.com/145828/163002507-077091a6-7bf2-4407-9e4c-4e50256e44fc.png">

By this time I am already a little frustrated. 

### SEO Image Source
So following my logic I want to be able to either display an image from a  custom field `entry.cf_metaImage` or the image I've specified under Global SEO:  
`{{ seomatic.helper.socialTransform(entry.cf_metaImage[0], "base", 1, "crop") ??? seomatic.helper.socialTransform(global.seoImage[0], "base", 1, "crop") }}`  
This looks about right, not? Somehow this works in one channel and in the other channel only this works: 
`{{ seomatic.helper.socialTransform(entry.cf_metaImage[0], "base", 1, "crop") ??? seomatic.helper.socialTransform(seomatic.meta.seoImage[0], "base", 1, "crop") }}`

Now I am frustrated and I regret using SEOmatic for this is so easy to code otherwise. 

COULD YOU PLEASE PUT SOME EXAMPLES IN THE [DOCS](https://nystudio107.com/docs/seomatic/configuring.html#general-1). 
It's somehow the most important area, and there's literally nothing written about it. Also, it could be that I've been missing some crucial doc somehow?! Please enlighten me if so! 

Sorry for my rant, but I've been hoping for better documentation for at least 2 years. 

Otherwise I love what you are doing! You must be a great guy and I value your contributions to craft cms! 

– Stefan

**Comment by khalwat** [comment]
> ### SEO Description Source
> For the Meta description I want to use the field `cf_metaDescription` and if not filled out the meta description I defined in Global  SEO under SEO Description Source with Custom Text.  
> So to my understanding I need to specify the following:   
> `{{ entry.cf_metaDescription ??? seomatic.meta.seoDescription }}` but that doesn't work?!  
> instead this works:  
> `{{ entry.cf_metaDescription ??? global.seoDescription }}`  
> I don't even know where I found out about the `global`thing, but it's definetly not in the docs... 

I don't know what `global.` is, so it makes sense that it isn't in the documentation. I think this is overly complicated, the way SEOmatic works is that if any value is empty, it'll fall back on the Global SEO.

So for this setting, you shouldn't need any Twig code at all, and can probably use tell it to pull from the `cf_metaDescription` field... because if that ends up being empty, it'll fall back on the global SEO description automatically.

> ### SEO Image Source
> So following my logic I want to be able to either display an image from a  custom field `entry.cf_metaImage` or the image I've specified under Global SEO:  
> `{{ seomatic.helper.socialTransform(entry.cf_metaImage[0], "base", 1, "crop") ??? seomatic.helper.socialTransform(global.seoImage[0], "base", 1, "crop") }}`  
> This looks about right, not? Somehow this works in one channel and in the other channel only this works: 
> `{{ seomatic.helper.socialTransform(entry.cf_metaImage[0], "base", 1, "crop") ??? seomatic.helper.socialTransform(seomatic.meta.seoImage[0], "base", 1, "crop") }}`
> 

What I recommend doing is getting your Twig code working the way you want it in your entry template, and then you can just paste it into the SEOmatic field.

In any event, this is another case where you actually probably don't need any Twig code at all. Instead, set the image to **From Asset Field:** then choose `cf_metaImage` and that should do it. If there's no image in `cf_metaImage` then it'll automatically fall back on the global SEO image.

Let me know if you have any other questions.

**Comment by outline4** [comment]
Hi Andrew,   
Thanks for getting back to me. I've just tried what you told me to do and it works perfectly. I feel a little dumb now and I don't know why I didn't even try it? Maybe because the Meta Title needs customisation anyways...

"**If any value is empty, it'll fall back on the Global SEO**".  
This would be exactly the phrase I would expect in the "Content SEO -> General" documentation! Could you please add this?

How could I achieve what I wanted to achieve with "SEO Keywords Source" in my initial question? 

And if I wanted to do it the complicated way, what would be the right syntax for this?:
`{{ entry.cf_metaDescription ??? global.seoDescription }}`

Thanks  
– Stefan

**Comment by khalwat** [comment]
> This would be exactly the phrase I would expect in the "Content SEO -> General" documentation! Could you please add this?

Will do.

> How could I achieve what I wanted to achieve with "SEO Keywords Source" in my initial question?

So this is arguably a bug... we don't let you put Twig code into the SEO Keywords field. It uses a tokenized input system.

So if you wanted to do what you're trying to do, you could do it via Twig code on the template pages themselves. I'd generally suggest not doing it, though, as the meta keywords tag is entirely ignored by Google, and can even be to your detriment if it looks like you're "keyword stuffing".

I typically just set it to extract keywords from the content, and just let it be.

> 
> And if I wanted to do it the complicated way, what would be the right syntax for this?:
> {{ entry.cf_metaDescription ??? global.seoDescription }}

I'm honestly not sure what `global` is in this context.

**Comment by outline4** [comment]
> So this is arguably a bug... we don't let you put Twig code into the SEO Keywords field. It uses a tokenized input system.

So what could we do about it? 

Maybe instead of "Custom Text" a "Twig Code" option might be something? With code completion etc.  
This could be interesting for the other fields as well.  

> I typically just set it to extract keywords from the content, and just let it be.

Yeah, I think that's a great way for keywords. I just wanted to know if this is a bug or if I am doing something wrong. 

> I'm honestly not sure what `global` is in this context.

`global.seoDescription`would be in "Global SEO -> general -> SEO Description Source -> Custom Text"

**Comment by khalwat** [comment]
I've been exploring your idea of ditching the token field in favor of the Twig editor field, with nice autocomplete, etc.

I'm thinking it makes sense for the Global SEO and Content SEO settings, but probably the SEO Settings field should remain as-is because it's probably more in line with what the content authors are expecting.

I also have it on my list to work something into the docs, if that meta cascade isn't documented, that is indeed a glaring omission, my apologies.

**Comment by khalwat** [comment]
@outline4 something like this is where I'm headed...


https://user-images.githubusercontent.com/7570798/164250771-12d1c8d3-6bed-4264-91ea-756aee5f87d4.mov

**Comment by outline4** [comment]
This is quite powerful! 

I like ♥︎

**Comment by khalwat** [comment]
So your idea has taken me on a bit of a sidetrack, but has ended up with something much bigger and better:

https://github.com/nystudio107/craft-twigfield

Now everyone can use it in their plugins (or even on the frontend).

Expect the SEOmatic integration and docs update soon. Thanks for your idea & patience @outline4

**Comment by khalwat** [comment]
@outline4 released:

https://twitter.com/nystudio107/status/1539651968087359488

Craft 3: https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.33

Craft 4: https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.3

...and the docs updated with your suggestions: https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

**Comment by outline4** [comment]
Thank you sooooo much! 
♥︎
