### ISSUE TITLE
GraphQL "array" output gives empty arrays where null would be more appropriate

### ISSUE THREAD

**Issue by tremby** [nystudio107/craft-seomatic#1105]
### Describe the bug

The JSON output when `asArray` is switched on (thanks for pointing me to this feature earlier!) is misleading when there's no output for a given key. It gives `[]` (an empty array) when there's no data, vs `{...}` (a populated object) when there is.

### To reproduce
Steps to reproduce the behaviour:
1. Query for eg `seomatic(asHtml: true) { metaTagContainer }` on an entry which has no description or keywords
2. See output, we have `"keywords": [], "description": []`
3. Query for the same thing on an entry which has a description and keywords
4. See output, we have `"keywords": {"content": "blah,etc","name":"keywords"}, "description":{"content":"some description","name":"description"}`

### Expected behaviour
`"keywords":null,"description":null`

### Versions
- Plugin version: 4.0.0-beta.7
- Craft version: 4.0.x-dev at 38a1659

### Opinions
The empty-array output led me to believe there could be any number of tags associated with those properties, but in fact it means there's no data for that, and there can be a maximum of one. A null would be a much better indicator of this.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/c5373ce06583c2aefc38cfaa60022c2e97c07892

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.0-beta.8”,
```
Then do a `composer clear-cache && composer update`

**Comment by tremby** [comment]
Thank you so much!

Are there going to be any surprises in this data structure? For example, could any of these properties ever suddenly give anything other than `null` or an object, such as an array of two objects? One which jumps out at me and encourages me to ask is `alternate` -- I've definitely seen multiple `alternate` links on a page before.

The structure of `metaTitleContainer` is a little odd; after parsing JSON I have

```
  "metaTitleContainer": {
    "title": {
      "title": "🚧 My Site | Some page"
    }
  }
```

whereas it could just be `"metaTitleContainer": "🚧 My Site | Some page"`. But I understand if it keeps things tidy/simple/consistent in the code.

**Comment by khalwat** [comment]
Not that I'm aware of -- many people take the data from SEOmatic and dump it to Helmet (or Vue Meta or whatever, depending on your framework of choice). Sometimes with a little massaging, other times directly.

I actually have plans to write little helper functions that do just that, for the popular frameworks. But it's pretty much a `NOP` in most cases.

**Comment by tremby** [comment]
What if there are multiple alternate languages?

**Comment by khalwat** [comment]
Those would be in separate queries, as that's how Craft separates languages. You'd pass in a different `siteId`

**Comment by tremby** [comment]
No, I mean links to the different language versions of the current page.
`<link rel="alternate" hreflang="fr" href="url-of-this-page-in-french">`
I only bring it up because that's a common way you can get multiple `<link rel="alternate">` tags, and the codebase looks like these alternate language links are dealt with, though I may be misreading. (There can be other kinds of "alternate" too, like RSS feeds etc, though I don't think that's part of SEOmatic's scope.)

**Comment by tremby** [comment]
I'm looking for example at src/helpers/DynamicMeta.php, addMetaLinkHrefLang.

**Comment by khalwat** [comment]
So here's what the output looks like for your example `alternate`:

```json
  "alternate": [
    {
      "href": "http://localhost:8004/es",
      "hreflang": "es",
      "rel": "alternate"
    },
    {
      "href": "http://localhost:8004",
      "hreflang": "x-default",
      "rel": "alternate"
    },
    {
      "href": "http://localhost:8004",
      "hreflang": "en-us",
      "rel": "alternate"
    }
  ]
```

So any tags that have repeating values will return an array of results.

**Comment by tremby** [comment]
OK, thanks for looking into it and confirming.

I guess I should code as if this could theoretically happen on any of the keys in the links tags structure or the meta tags structure.

I know in this ticket I asked for null if there's no object, but in light of it potentially being multiple objects, I now think it'd be better to always have an array which has zero or more objects. Right now I believe each property could be either null, a single object, or an array of 2+ objects, and I need to test for and handle all those cases.

It's less code for me and probably simpler for you too if it's always an array. In that scenario all I'd have to do is `Object.values(JSON.parse(seomatic.metaLinkContainer)).flat().map((props, i) => <link key={i} {...props} />)`, and similar for the meta tags, and I'm done.

Even simpler (I'd skip the Object.values and the flat() call) if all the link tags were in a single array (`metaLinkContainer: [{href: "x", hreflang: "es", rel: "alternate"}, {href: "y", hreflang: "fr", rel: "alternate"}, {href: "z", rel: "canonical"}, ...]`) rather than split by purpose (`metaLinkContainer: { alternate: ..., canonical: ..., ... }`) , though maybe there are use cases for handling them separately which I'm not seeing.

**Comment by tremby** [comment]
Actually code right now really isn't that much worse. I can handle all the cases with

```js
Object.values(JSON.parse(seomatic.metaLinkContainer))
.flat()
.filter((tag) => tag != null)
.map((props, i) => <link key={i} {...props} />)
```

But presuming you want to keep the separate types of links/metatags separate, I maintain that an array which is sometimes empty and sometimes has one item and sometimes more than one would be the most consistent interface, and I'd say most intuitive to the developer. Exploring the GQL endpoint and seeing some properties with `[]` and some with `[{ ... }]` would give all the necessary clues, I think.

**Comment by khalwat** [comment]
> But presuming you want to keep the separate types of links/metatags separate, I maintain that an array which is sometimes empty and sometimes has one item and sometimes more than one would be the most consistent interface, and I'd say most intuitive to the developer. 

But didn't you just have me change it from that to a value that is `null` rather than an empty array?

If what you're saying is that the value should _always_ be an array, even if there is one item... I think that's arguable. I went with the route that schema.org uses for their types, for instance, all of which can either be the thing, or an array of the things.

https://schema.org/Thing

**Comment by tremby** [comment]
> But didn't you just have me change it from that to a value that is null rather than an empty array?

Yes (and I did point that out in my message above!)

> If what you're saying is that the value should always be an array, even if there is one item... I think that's arguable.

Yes, that's exactly what I'm saying. It provides a consistent and intuitive interface.

Originally it was `{...}` if there was a tag, `[]` if there was no tag, and (unknown to me at the time) `[{...}, {...}, ...]` if there was more than one tag. I think you must have agreed that this is a weird situation -- an empty array on 0 (or 2+, unknown to me), and a single item if there's 1.

Why's it weird? Well I was seeing this in the response:

```json
"metaLinkContainer": {
  "canonical": { "href": "...", "rel": "canonical" },
  "author": { "href": "...", "rel": "author", "type": "text/plain" },
  "publisher": [],
  "alternate": []
}
```

The above raises a bunch of questions. Why are they different data structures? Maybe there's only ever exactly one canonical link, and one author, and publishers and alternate can have zero or more? But why could publisher and alternate have more than one while author couldn't? So does empty array just mean no data? *Can* canonical and author have more than one? What if there's no author, do I get a null, or an empty object, or an empty array, or what?

You made the change to be `null` in the 0 case. Then we have this:

```json
"metaLinkContainer": {
  "canonical": { "href": "...", "rel": "canonical" },
  "author": { "href": "...", "rel": "author", "type": "text/plain" },
  "publisher": null,
  "alternate": null
}
```

The above raises far fewer questions. I would assume right away that each item can have zero or one entry -- null or an object. But then I start to remember that it's somewhat common to have multiple "alternate" links.

So that's why I asked about whether there might be surprises such as more than one tag for a given property, mentioning `alternate` links, and you said you didn't think so, until I reminded you of alternate languages.

So now we've got:

```json
"metaLinkContainer": {
  "canonical": { "href": "...", "rel": "canonical" },
  "author": { "href": "...", "rel": "author", "type": "text/plain" },
  "publisher": null,
  "alternate": [{ "href": "...", "hreflang": "fr", "rel": "alternate" }, { "href": "...", "hreflang": "es", "rel": "alternate" }]
}
```

I.e. `null` on zero, `{...}` on one, and `[{...}, {...}, ...]` on 2+. I still think that's weird, now that I know the 2+ case exists. The danger is that the 2+ case might be rare, and so a developer might not notice that it exists, and make the exact faulty assumptions I imagined above, below the previous example.

> I went with the route that schema.org uses for their types, for instance, all of which can either be the thing, or an array of the things.

Would they really do an empty array if there were zero entries? I can't find an example of that. But it doesn't matter. I guess that scheme is fine if the documentation is there to state all the possible forms the data can be returned in, and I suppose it might make the data structures a little slimmer. It's necessarily more code to handle though, and that documentation needs to be there or the developer will have no idea and write brittle code.

So yes, if you're still willing to change the structure, I suggest either:

```json
"metaLinkContainer": {
  "canonical": [{ "href": "...", "rel": "canonical" }],
  "author": [{ "href": "...", "rel": "author", "type": "text/plain" }],
  "publisher": [],
  "alternate": [{ "href": "...", "hreflang": "fr", "rel": "alternate" }, { "href": "...", "hreflang": "es", "rel": "alternate" }]
}
```

(and similar for metaTagContainer, i.e. always an array no matter how many tags)

Or, even simpler IMO since the type buckets are redundant information and I can't think why someone would need them separated:

```json
"metaLinkContainer": [
  { "href": "...", "rel": "canonical" },
  { "href": "...", "rel": "author", "type": "text/plain" },
  { "href": "...", "hreflang": "fr", "rel": "alternate" },
  { "href": "...", "hreflang": "es", "rel": "alternate" }
]
```

(and again similar for metaTagContainer).

With either of those forms, I don't think any questions get raised at all, and the simple assumptions are going to be right. I think?

And as mentioned briefly above it'd be nice if `metaTitleContainer` just pointed straight to a title string rather than it being nested a couple of levels deeper.

**Comment by khalwat** [comment]
I'm unlikely to change the structure at this point, given that a number of endpoints rely on it in its current format.

I do agree with you that having everything be an array can be nicer from a consistency standpoint, however there is also something to be said for having it be the most convenient for the 99% case... and the vast majority of the tags will occur only once.

Now arguably another thing that could be done is just having multiple tags for each thing, but then we're just punting the single vs. multiple things problem elsewhere in the API, to when we look up the tag by name.

Far more likely is I write the helper stubs I mentioned earlier, at least near-term.

Potentially in the future, I could revisit it when I'm prepared to make a breaking API change. Understand that there are other internal structures involved here beyond just the eventual GraphQL API output, which reflect on the shape of the data.

**Comment by tremby** [comment]
> there is also something to be said for having it be the most convenient for the 99% case... and the vast majority of the tags will occur only once.

But then the site suddenly crashes when someone edits some SEO settings, because suddenly you've hit the 1% and the developer didn't handle the array case. That shouldn't be encouraged. I also demonstrated above that the code to handle the more consistent forms is simpler, and less misleading too. So I guess it depends what you mean by convenient.

> Potentially in the future, I could revisit it when I'm prepared to make a breaking API change.

Was changing `[]` to `null` not one? You're in 4.0.0-beta, isn't this the perfect time for breaking changes?

**Comment by khalwat** [comment]
> But then the site suddenly crashes when someone edits some SEO settings, because suddenly you've hit the 1% and the developer didn't handle the array case. That shouldn't be encouraged. I also demonstrated above that the code to handle the more consistent forms is simpler, and less misleading too. So I guess it depends what you mean by convenient.

There are other scenarios I could contrive which would result in the opposite happening.

But it boils down to: should I break everyone's implementation due to an arguable change in the output that one developer has asked for?

> Was changing [] to null not one? You're in 4.0.0-beta, isn't this the perfect time for breaking changes?

The change you're asking for has further-reaching implications than you might realize.

The only way I could reasonably make the change now would be to change it only in the GraphQL API layer, which isn't something I'm particularly fond of.

**Comment by tremby** [comment]
> But it boils down to: should I break everyone's implementation due to an arguable change in the output that one developer has asked for?

Well you might have already.

If anyone was doing

```js
function SeomaticLinkTag(thing) {
  if (Array.isArray(thing) && thing.length === 0) {
    // No tag, render nothing
    return null;
  }
  return <link {...thing} />;
  // or eg return <link rel={thing.rel} href={thing.href} />;
}
```

that'll break, because they're now getting a null instead of an empty array. (It'd also break if it's an array of multiple tags.)

If you want to avoid breaking changes, maybe it'd be best to roll back the null change.

**Comment by khalwat** [comment]
Reverted in: https://github.com/nystudio107/craft-seomatic/commit/1da2b822473edc01bc3eaf532ea5b59ac48ef7ae

**Comment by khalwat** [comment]
> So yes, if you're still willing to change the structure, I suggest either:
> 
> ```json
> "metaLinkContainer": {
>   "canonical": [{ "href": "...", "rel": "canonical" }],
>   "author": [{ "href": "...", "rel": "author", "type": "text/plain" }],
>   "publisher": [],
>   "alternate": [{ "href": "...", "hreflang": "fr", "rel": "alternate" }, { "href": "...", "hreflang": "es", "rel": "alternate" }]
> }
> ```
> 
> (and similar for metaTagContainer, i.e. always an array no matter how many tags)
> 
> Or, even simpler IMO since the type buckets are redundant information and I can't think why someone would need them separated:
> 
> ```json
> "metaLinkContainer": [
>   { "href": "...", "rel": "canonical" },
>   { "href": "...", "rel": "author", "type": "text/plain" },
>   { "href": "...", "hreflang": "fr", "rel": "alternate" },
>   { "href": "...", "hreflang": "es", "rel": "alternate" }
> ]
> ```
> 

If I were to change it, it'd be the former rather than the latter. The problem with the latter data structure is that there's no good way to find a specific tag you're looking for, other than iterating through all of the tags.

There are frontend cases where it's very useful to be able to just pluck out specific tags, rather than consuming them all, and having to iterate through the array of tags each time to look for a specific one would be unnecessarily costly.

Having the tags indexed by the handle rather than it being just "tag soup" I think is more useful.

So if anything, everything would be an array... either an empty array, or an array of `n` items (even if `n` is 1 most of the time). It's even arguable whether tags that are empty should be included at all IMO, but probably it's more transparent than having some items (seemingly randomly) not appear.

**Comment by tremby** [comment]
All sounds good to me.

> There are frontend cases where it's very useful to be able to just pluck out specific tags

Just out of curiosity, what sort of cases? I couldn't think of any.

**Comment by khalwat** [comment]
I've seen many sites created with SEOmatic that are a hybrid of using some meta tags under user control (generated by SEOmatic), and some meta tags that are under programmer control.

I have also seen many sites where all of the tags from SEOmatic will be used, but one may be replaced or one may use some data from the user (via SEOmatic) but augmented by the programmer in frontend code.

Many sites will just use the SEO information from SEOmatic whole-hog -- but many don't. Having the data structure be unindexed "tag soup" seems unwise to me for this reason, even if it feels better from an OCD standpoint.
