### ISSUE TITLE
Can't save any configuration in SEOmatic → Site Settings → Social Media

### ISSUE THREAD

**Issue by tremby** [nystudio107/craft-seomatic#1107]
### Describe the bug

Nothing I enter in the social media config page will save.

### To reproduce
Steps to reproduce the behaviour:
1. Go to control panel → SEOmatic → Site Settings → Social Media
2. Enter anything in any of the fields
3. Click to save
4. No errors are shown but the fields are no longer populated

### Expected behaviour
Fields are saved and repopulated in the form when looking again.

### Versions
- Plugin version: a6aa50e
- Craft version: 792e2260

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/52623113703778365d967303b71b500a84368fe7

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.0-beta.8”,
```
Then do a `composer clear-cache && composer update`
