### ISSUE TITLE
I'm getting back <meta name="robots" content="none"> even though "all" is configured site-wide

### ISSUE THREAD

**Issue by tremby** [nystudio107/craft-seomatic#1108]
### Describe the bug

I have a page with no special robots configuration. All SEOmatic configuration I can find which I think should apply to it is set to "all". But via the GraphQL API (didn't look elsewhere) I'm given `none` in the robots field.

### To reproduce
Steps to reproduce the behaviour:
1. I've added an SEOmatic field to the entry type's fields, but have done nothing in there except fill in a description. Default configuration, so there's not even an option to change "robots"
2. Query GQL for SEOmatic fields
3. See in the response `"robots": { "content": "none", "name": "robots" }`

### Expected behaviour
Either `"robots": null` or `"robots": { "content": "all", "name": "robots" }`

### Versions
- Plugin version: a6aa50e
- Craft version: 792e2260

**Comment by khalwat** [comment]
Probably because you are in local dev, with `devMode` on. This is done intentionally, to prevent Google from indexing local dev or staging sites, or anything not meant for production.

You can pass in the `environment` you want the settings from in your queries if you like: https://nystudio107.com/docs/seomatic/advanced.html#graphql-query-support

```graphql
{
  seomatic (uri: "/", environment: staging) {
      metaTitleContainer
      metaTagContainer
      metaLinkContainer
      metaScriptContainer
      metaJsonLdContainer
      metaSiteVarsContainer
  }
}
```

**Comment by tremby** [comment]
Ahh, thank you. Sorry for the noise. Yes, if I set it to `live` I see `all`.

**Comment by khalwat** [comment]
There is also a Plugin Setting where you can override the auto-determined environment if you want.
