### ISSUE TITLE
XML validation errors in sitemaps caused by unescaped entities

### ISSUE THREAD

**Issue by mgburns** [nystudio107/craft-seomatic#111]
We have an image in one of our sitemaps with a `&` character that is causing validation errors, preventing Google from parsing it. Not sure if it's true for other fields outside of image titles.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/1648c4e77640d4575783b1937cd4b14dc685ab0c
