### ISSUE TITLE
GQL: `siteId` option on `frontendTemplates` field not working as expected

### ISSUE THREAD

**Issue by tremby** [nystudio107/craft-seomatic#1110]
### Describe the bug
I am not able to retrieve the different humans.txt files for different sites of a multisite Craft instance via GQL.

### To reproduce
Steps to reproduce the behaviour:
1. Have a multisite Craft
2. Set a different humans.txt template for earch
3. Query such as `curl -H "Authorization: Bearer abc123abc123" -H "Content-Type: application/graphql" http://yoursite/graphql -d "{ seomatic(asArray: true, siteId: 1) { frontendTemplates(type: humans) { contents } } }"`
4. See output
5. Query for a different siteId such as `curl -H "Authorization: Bearer abc123abc123" -H "Content-Type: application/graphql" http://yoursite/graphql -d "{ seomatic(asArray: true, siteId: 2) { frontendTemplates(type: humans) { contents } } }"`
6. See the same output

In my case I am seeing the template for site 2 rendered in both cases. If I query for site 0 (which I don't think exists -- or maybe 0 is supposed to mean default) I again get the template for site 2. If I query for site 3, which certainly does not exist, I get an error.
 
### Expected behaviour
The humans.txt for the site I asked for is returned.

### Versions
- Plugin version: 4.0.0-beta at 38ea2a52
- Craft version: 4 beta at 792e226

**Comment by khalwat** [comment]
Are you sure you have the siteId's correct? Seems to work as expected at least using GraphiQL:

```graphql
{
  seomatic {
    frontendTemplates(siteId: 2 type: humans) {
      filename,
      contents
    }
  }
}
```

Perhaps you need to have the parameters for `frontendTemplates` on that part of the GraphQL query, rather than the parent?

The parameters are documented here: https://nystudio107.com/docs/seomatic/advanced.html#frontend-templates-graphql-queries

**Comment by tremby** [comment]
Oh. Yeah, moving them down to the `frontendTemplates` field made the difference. Thank you.

I really would have expected it being passed at the `seomatic` level to set a default for any fields requested inside. Maybe that's not reasonable, I'm not sure. I can't think of a Craft-provided query to test it on.

In any case, why would it default to giving me results about site 2, which is not my default site? Hm, I tested on one of Craft's own fields, and it has the same behaviour. That is, if I query from graphiql it defaults to site 1, but if I query from elsewhere with a bearer token (the token allows access to all sites) it defaults to site 2. That's super weird; I'll report it upstream.

Thanks again.

**Comment by khalwat** [comment]
Internally, because they aren't really connected with any particular request, they are implemented as separate queries. I'm not sure if there is a way for it to inherit things like `siteId` from the parent `seomatic` query if an argument isn't provided, though.

I will have a look.

**Comment by tremby** [comment]
The `asArray` option when applied to the parent `seomatic` trickles down to nested fields. That's likely what I thought `siteId` would work the same way.

**Comment by khalwat** [comment]
The `asArray` option doesn't trickle down to nested queries like `frontendTemplates`, however.
