### ISSUE TITLE
Can't save on any of the tabs of the "plugin settings" page

### ISSUE THREAD

**Issue by tremby** [nystudio107/craft-seomatic#1112]
### Describe the bug
I can't save on any of the tabs of the "plugin settings" page. I get a "Couldn't save plugin settings." toast error.

The log (at debug level, but without SQL query logging) is close to 9 megabytes just for this single interaction and I've put it here: http://sprunge.us/IHVYff

I don't see any obvious errors in it.

### To reproduce
Steps to reproduce the behaviour:
1. Go to control panel -> SEOmatic -> plugin settings
2. Click to save, whether or not anything has been edited
3. See error message
4. Hit refresh to see any changes you made did not save

### Expected behaviour
Settings save

### Screenshots
![screen](https://user-images.githubusercontent.com/199635/163482876-e101e8b6-8810-400c-a8eb-b2652760dedb.png)

### Versions
- Plugin version: 4 beta at 38ea2a52
- Craft version: 4 beta at 4cc24cbb

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/321cf1f2ea978039e237ed81eaa67b1db7315512
