### ISSUE TITLE
Google Search Console Error "contentUrl"

### ISSUE THREAD

**Issue by rettoson** [nystudio107/craft-seomatic#1116]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.

For the past several months, Google Search Console has been showing an error on every page related to the schema seomatic generates saying 

"Missing field "contentUrl" (in "logo")".    Drilling down leads to the following screenshot.   

![contentUrl error](https://user-images.githubusercontent.com/103870006/163700166-6492ed30-5f3b-4a21-af01-4d8bdfb77573.png)

Thanks 
### Additional context
Add any other context or screenshots about the support request here.

**Comment by khalwat** [comment]
Can you provide a live URL to one of the pages in question?

`ImageObject` schemas shouldn't require `contentUrl` -- is `url` not filled in?

**Comment by khalwat** [comment]
Will re-open if additional information is provided.

**Comment by joostclevis** [comment]
@khalwat I'm running into the same issue when providing the Creator info. By url you mean the Entity URL? 
I've filled that and receive the same error.

**Comment by khalwat** [comment]
The `url` field in the `ImageObject` is what I was referring to
