### ISSUE TITLE
Overwrite breadcrumb list for GraphQL

### ISSUE THREAD

**Issue by denisyilmaz** [nystudio107/craft-seomatic#1117]
We are using SEOmatic in a headless environment. There we want to show the breadcrumb for each page.
In your examples you are showing a way to create a custom JSON-LD object if there is the need to overwrite the breadcrumb list. For example we have a channel entry type "news" and a single entry type "news overview" where the items are children of.

Is there a way to overwrite the JSON-LD object for seomatic outside of twig templates? And/or to set a single entry type as the parent of a channel entry type that seomatic would honor when creating the breadcrumb list?

**Comment by khalwat** [comment]
You can do this via PHP as well if you like -- I assume you have this sorted, however?
