### ISSUE TITLE
Google Analytics 4 Replacing Universal Analytics - How does this affect SEOMatic?

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft-seomatic#1118]
### Question
I've been getting constant emails from Google saying they are sunsetting Universal Analytics by July of next year and replacing with "Analytics 4." Since SEOMatic just has you put in your property ID and it takes care of the rest of the script, should I wait until v4 is supported before making the switch?

**Comment by khalwat** [comment]
SEOmatic already supports GA 4 -- you'd select **gtag.js** after you've converted your property over in Google Analytics.

<img width="1562" alt="Screen Shot 2022-04-19 at 11 18 49 AM" src="https://user-images.githubusercontent.com/7570798/164038332-bfc2b42c-5c87-45b2-98a9-d9bcb9030e01.png">

**Comment by jonlongnecker** [comment]
Perfect, thanks for clarifying!
