### ISSUE TITLE
Sitemap has not been generated yet

### ISSUE THREAD

**Issue by hiasl** [nystudio107/craft-seomatic#1119]
### Question
Hey Andrew,
I'm experiencing a strange behavior which I do not understand: Whenever I open the sitemaps in my browser, it tells me, that they have not been generated yet, although we have a cronjob for this (see further down).

I can call the sitemap cronjob from the shell and it works and also my log file contains the typical output of the cronjob.

Do you have any idea, why the sitemaps get lost? 

### Additional context
- We have SEOmatic on a production site/mode and 2 cronjobs like this
```
* * * * * flock -xn /data/www/aaa/tmp/craft.queue.aaa.prod.lck -c "/usr/bin/nice -n 10 php7.4 /data/www/aaa/web/aaa.com/craft queue/run" > /data/www/aaa/tmp/craft.queue.aaa.prod.log 2>&1
0 23 * * * flock -xn /data/www/aaa/tmp/craft.seomatic.aaa.prod.lck -c "/usr/bin/nice -n 10 php7.4 /data/www/aaa/web/aaa.com/craft seomatic/sitemap/generate" > /data/www/aaa/tmp/craft.seomatic.aaa.prod.log 2>&1
```

- Cache is in REDIS
- SEOmatic: 3.4.22
- Craft Pro 3.7.28

<br class="Apple-interchange-newline">

**Comment by khalwat** [comment]
Sitemaps are generated via Queue job because large sitemaps can take a long time to generate. Then they are cached. My guess is that something is happening that clears the sitemap cache.

Probably better than a cron job here would be to have a queue runner: 

https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms

So queue jobs, including sitemap regeneration, is done automatically on-demmand.

I would also suggest updating to the latest version of SEOmatic, as a change was made in 3.4.29 to roll back an earlier change, which will cause the sitemaps to respond via web request regardless.

**Comment by hiasl** [comment]
Thanks!

**Comment by AdamChlan** [comment]
@khalwat Quick question on about versions after 3.4.29. Should the initial web request after a cache clear still result in a `This sitemap has not been generated yet.` message? That seems to be what we are seeing. Then on reload, we see the sitemap. We're just wanting to make sure that Google does not get thrown if this happens.

**Comment by khalwat** [comment]
> On Sep 7, 2022, at 1:37 PM, Adam Chlan ***@***.***> wrote:
> 
> @khalwat Quick question on about versions after 3.4.29. Should the initial web request after a cache clear still result in a This sitemap has not been generated yet. message? That seems to be what we are seeing. Then on reload, we see the sitemap. We're just wanting to make sure that Google does not get thrown if this happens.
> 
> 

First, I would update to the latest version, which is 3.4.37 as of this writing.

So the initial web request should generate the sitemap for you, assuming you haven’t told SEOmatic not to via config.

In any event, SEOmatic properly sets the response code as Google recommends if the sitemap isn’t generated, with a timestamp telling it to check back in 30 minutes.

/andrew

**Comment by AdamChlan** [comment]
Very cool. Thanks for the clarification.
