### ISSUE TITLE
Unable to disable tracking scripts from templates

### ISSUE THREAD

**Issue by mgburns** [nystudio107/craft-seomatic#112]
I'm using the following code to disable tracking conditionally (thanks, GDPR ;)):

```
{% do seomatic.script.get('googleTagManager').include(false) %}
```

I noticed that it wasn't working, and when I `{{dump(seomatic.script.get('googleAnalytics'))}}` it I see that it's actually showing the contents for the `facebookPixel` script.

Also curious if there's an alternate / better way to disable all tracking scripts?

**Comment by mgburns** [comment]
Also -- I'm doing this from a `local` environment, which as I understood it shouldn't be rendering tracking scripts to begin with but that does not appear to be the case. Potentially another bug?

**Comment by khalwat** [comment]
So this is a multi-part bug heh.

Fixed issue of it not returning the proper script in: https://github.com/nystudio107/craft-seomatic/commit/35dd1b6c7c86a957c9112845704506b1ba6419dc

Fixed the per-environment exclusion issue: https://github.com/nystudio107/craft-seomatic/commit/ce28b52def218cca573170a9871aca57bb6d8189
