### ISSUE TITLE
overwriting container settings need an extra pageload

### ISSUE THREAD

**Issue by aloco** [nystudio107/craft-seomatic#1121]
### Describe the bug
Hi, not sure if this is a bug or something I am overlooking. We got SEO advice and they told us to set pages with query params to noindex, follow and no canonical url

I am overwriting the container settings just before `</body>`
```
        {% if craft.request.getQueryString() %}
            {% do seomatic.meta.robots('noindex, follow') %}
            {% do seomatic.meta.canonicalUrl('') %}
            {% do seomatic.script.container().clearCache(true) %}
        {% endif %}
```
However it seems like pages with query params need an extra page load to reflect this overwrite.

### To reproduce
Steps to reproduce the behaviour:

- add my twig snippet just before `</body>`
- call testsite.test/ -> you will get robots with "all" ✅
- call testsite.test/?test=123 -> you will get robots with "all" ❌
- call again testsite.test/?test=123 -> you will get robots with "noindex, follow" ✅
- call again testsite.test/ -> you will get robots with "all" ✅

### Versions
- Plugin version: 3.4.30
- Craft version: 3.7.38

**Comment by khalwat** [comment]
> We got SEO advice and they told us to set pages with query params to noindex, follow and no canonical URL

I think this is likely not great advice. Rather, just set the Canonical URL properly, and you're done.

> However it seems like pages with query params need an extra page load to reflect this overwrite.

You are going up against the SEOmatic cache. This article explains it, and how to work with it: https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting

But again, my suggestion is that you do not follow the advice you've been given, and instead just set the canonical URL to properly point to the URL without query parameters, and you are done.
