### ISSUE TITLE
[FR] Ability to use the title field of an image as SEO Image Description Source

### ISSUE THREAD

**Issue by Antimated** [nystudio107/craft-seomatic#1122]
### Is your feature request related to a problem? Please describe.
I'd like to have the possibility to use the title field of an image as the SEO Image Description Source.

### Describe the solution you would like

Whipped up a small screenshot where you can select an image field's "Title" field. Maybe add the possibility to select other text fields that are linked to an asset volume.
![Screenshot 2022-04-26 at 13 04 54](https://user-images.githubusercontent.com/2869409/165286626-2da9f0bb-42cc-407d-a43a-645b8bf72fb1.png)

Does this sound like something worth implementing? Now I have to manually add the description of an image to every page where I want to add an SEO image description.

**Comment by khalwat** [comment]
You can do this now with custom Twig, something like:

```
{{ entry.heroImage.title }}
```

...and that should do it!
