### ISSUE TITLE
Can I add tracking script settings to seomatic.php?

### ISSUE THREAD

**Issue by KatieMFritz** [nystudio107/craft-seomatic#1123]
### Question
Is it possible to control the `Google gtag.js` and `Google Tag Manager` settings through the `seomatic.php` file? 

### Additional context
I want to use Google Tag manager only on production, but if the settings are saved in the database, I'm afraid they'll get added to other environments when we copy the prod db.

1. Is that a correct assumption, that if I set GTM information for one site, then copy the database to another site, the GTM info will come with it?
2. If so, how can I set this data in `config/seomatic.php`?

Thanks, Andrew!

<img width="1188" alt="Screen Shot 2022-04-26 at 6 33 20 PM" src="https://user-images.githubusercontent.com/7085184/165403629-fdc878fe-27b4-4851-9b61-e4e39b4e4705.png">

**Comment by khalwat** [comment]
SEOmatic automatically will disable tracking scripts in all environments other than live production by default.

So you should be all set, unless I'm misunderstanding something?

**Comment by KatieMFritz** [comment]
That sounds correct! Thanks.

**Comment by siebird** [comment]
We've had this happen a few times when the tracking script switches inadvertently got disabled or the IDs went missing. I'm not able to track down when this happens, so I want a way to always make sure the tracking scripts are enabled in production.

```use craft\helpers\App;

return [
    '*' => [
        'pluginName' => 'SEO',
        ...
    ],

    'live' => [
        'scripts' => [
            'gtag' => [
                'include' => true,
                'containerId' => App::env('GTAG_CONTAINER_ID'),
                ...
            ]
        ],
    ],
];
```
