### ISSUE TITLE
SEO title source fetches title from old entry

### ISSUE THREAD

**Issue by JefCosh** [nystudio107/craft-seomatic#1124]
### Describe the bug
The title for the SEO uses an old entry. This issue has a similar behavior as https://github.com/nystudio107/craft-seomatic/issues/186. 

### Screenshots
![image](https://user-images.githubusercontent.com/102239374/165487366-560b42e1-569a-4c48-82a4-9a9b59c72841.png)

### Versions
- Plugin version: 3.4.30
- Craft version: 3.6.17

**Comment by khalwat** [comment]
I've attempted to reproduce this, but I'm unable to do so. Can we set up a time to screen share and have a look at your setup?

https://savvycal.com/nystudio107/chat

**Comment by khalwat** [comment]
Will re-open if additional information is provided.
