### ISSUE TITLE
Feed Me integration class missing return types for Craft 4

### ISSUE THREAD

**Issue by bencarr** [nystudio107/craft-seomatic#1125]
### Describe the bug
When running the latest Craft 4-compatible beta of SEOmatic on a site running the RC for Craft 4 and the latest beta of Feed Me, the `SeoSettings` Feed Me integration class is missing the return types on `getMappingTemplate()` and `parseField()` to make it compatible with Feed Me's `FieldInterface`. 

Happy to PR the change, but wasn't sure what approach is preferred since the integration class could also exist in sites not running Feed Me 5, whose `FieldInterface` won't include those return types.

### To reproduce
Steps to reproduce the behaviour:
1. Install `craftcms/cms:^4.0.0-RC1`, `nystudio107/craft-seomatic:^4.0.0-beta.8`, and `craftcms/feed-me:^5.0.0-beta.2`
2. Create a feed in Feed Me and proceed to the field mapping step
3. Mapping step will not load, and error logs contain the error

```
 PHP Compile Error 'yii\base\ErrorException' with message 'Declaration of nystudio107\seomatic\integrations\feedme\SeoSettings::getMappingTemplate() must be compatible with craft\feedme\base\FieldInterface::getMappingTemplate(): string'

in /var/www/vendor/nystudio107/craft-seomatic/src/integrations/feedme/SeoSettings.php:48
```

### Versions
- Plugin version: 4.0.0-beta.8
- Craft version: 4.0.0-RC1
- Feed Me version: 5.0.0-beta.2

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/bb2d1d0db3af227664f9e5744a7335e8b507f1bc

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.0-beta.9”,
```
Then do a `composer clear-cache && composer update`
