### ISSUE TITLE
Twitter SEO Images 

### ISSUE THREAD

**Issue by gazlawn22** [nystudio107/craft-seomatic#1126]
### Question

We're finding on every site that we've tested that Twitter is not displaying an image preview when we're trying to share it. Happens no matter what type of twitter card we use, summary/summary with large image. The image doesn't appear when shared as a tweet, or when previewed through the Twitter Debugger.

We've checked things like the robots and all looks fine there, and other validators, facebook, linkedIn etc, all appear fine, it just seems specific to Twitter.

To make things stranger, some pages, e.g. the home page DO generate a twitter image, where as a news page for example does not.

### Additional context

The issue was rasised by a clients on two seperate sites this week so we're unsure if there is something on Twitters end that has changed that you might be aware of?

**Comment by khalwat** [comment]
Twitter is sometimes a little flakey about these things.

Have you tried validating things with the Twitter Card Validator? https://cards-dev.twitter.com/validator

**Comment by gazlawn22** [comment]
Yeah, have tried it through that and no change, apennding urls with a param etc. We were thinking it would be something randon on Twitters end, as for example, on this page, 1 of the 9 posts do actually pull in the image with the post... Just a pain the others don't - https://franwen.com/news

If you have any thoughts though would be good to hear, but thnaks for coming back.

**Comment by khalwat** [comment]
If you can verify by viewing the source that the proper `twitter:image` tag is there, and it passes the Twitter Validator... it's going to be something on Twitter's end.

I checked the page you linked to:

```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@cwmnifranwen">
<meta name="twitter:creator" content="@cwmnifranwen">
<meta name="twitter:title" content="Newyddion | Frân Wen">
<meta name="twitter:description" content="Cwmni theatr Cymraeg i blant a phobl ifanc. Welsh language theatre for children and young people.">
<meta name="twitter:image" content="https://franwen.com/content/images/_800x418_crop_center-center_82_none/NewsSgwar.jpg?mtime=1640124028">
<meta name="twitter:image:width" content="800">
<meta name="twitter:image:height" content="418">
<meta name="twitter:image:alt" content="Newyddion">
```

The tags all look right, and the linked to image seems fine too: https://franwen.com/content/images/_800x418_crop_center-center_82_none/NewsSgwar.jpg
