### ISSUE TITLE
Contents of `config/seomatic-config/globalmeta/Creator.php` not being applied to front end output

### ISSUE THREAD

**Issue by johndwells** [nystudio107/craft-seomatic#1127]
I've tried this a couple of times now, still to no avail. I've taken this file:

https://github.com/nystudio107/craft/blob/craft-vite/cms/config/seomatic-config/globalmeta/Creator.php

And dropped it into an existing project, and if I view `/humans.txt` it doesn't output the Creator's name or other information.

I then tried creating a fresh project using that repo, and it's the same result - the contents of Creator.php are not reflected in the Twig output, they are overridden by what has been stored in the DB (filled in from the migration).

### To reproduce

Steps to reproduce the behaviour:
1. Follow examples to install https://github.com/nystudio107/craft
2. Once running (e.g. `make up`), modify the contents of `config/seomatic-config/globalmeta/Creator.php`
3. Visit `/humans.txt` to see no changes take effect :(

### Versions
- Plugin version: 3.4.30
- Craft version: 3.7.39

**Comment by khalwat** [comment]
All of the settings in `seomatic-config` are only applied when the meta containers are first created.

None of them are intended to override anything in the database, but rather serve as a template for initially creating what will end up in the database.

**Comment by johndwells** [comment]
@khalwat Ah! OK that's quite different from what I'd understood. Glad I asked before trying again!
