### ISSUE TITLE
YAML updates wipe out SEOMatic Content SEO settings for Commerce Products

### ISSUE THREAD

**Issue by nealmckinney** [nystudio107/craft-seomatic#1129]
### Describe the bug
We are developing locally and updating a staging site via git (buddy). Each time we do a deploy involving yaml files from adding admin fields locally, after merging changes on the Staging environment my custom settings in SEOMatic > Content SEO for Content Type Product get wiped out. We are using Craft Commerce Lite, and Craft and all plugins are still in trial mode.

### To reproduce
1: Commit a change involving a yaml file.
2: SEOMatic > Content SEO > Product and see that custom settings for SEO Description and SEO Image Source have been erased.

### Expected behavior:
I would expect my custom settings to be retained since this should be stored in the DB, not in yaml config files.

### Versions
- Plugin version: 3.4.30 Trial
- Craft version: 3.7.39

**Comment by nealmckinney** [comment]
Update: I think this only happens when new fields are added to Commerce Products.

**Comment by khalwat** [comment]
Are you sure it happens when new fields are added? Are you making _any_ other changes to the Commerce Products?

**Comment by khalwat** [comment]
Will re-open if additional information is provided.
