### ISSUE TITLE
SEO Settings field tab click hides content

### ISSUE THREAD

**Issue by ajp** [nystudio107/craft-seomatic#1131]
### Describe the bug
I'm unable to edit any content on additional tabs in my SEO Settings field. As soon as I click on a tab, the related tab-content div is hidden (class `hidden` added).

### To reproduce
Steps to reproduce the behaviour:
1. Go to an entry with an SEO Settings field.
2. Click on any of the field's tabs including "General". 
3. All tab-content markup is marked hidden (class added called `hidden`).

### Expected behaviour
Clicking the tab, I expected the selected tab's related `tab-content` div to be visible.

### Additional Notes:
Was reproduced by coworker.
Was reproduced in a new single and new entry type.
Was reproduced in a new channel and new entry type.

### Screencast / Screenshots
![Screen Capture on 2022-05-04 at 09-08-57](https://user-images.githubusercontent.com/1015261/166687820-d0cc927d-ef6f-4e75-bf59-b73ea02fb4ae.gif)

Field Settings:
![Screen Shot 2022-05-04 at 9 09 12 AM](https://user-images.githubusercontent.com/1015261/166687775-3fd9bfe0-e19f-48c2-86fa-c42a3ab4703b.png)

### Versions
- Plugin version: `4.0.0-beta.8`
- Craft version: `4.0.0-RC2`

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/f39b9c60df44a42b0697ac39f0d84739efcdb8a3

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.0-beta.9”,
```
Then do a `composer clear-cache && composer update`

**Comment by ajp** [comment]
Thanks @khalwat !
