### ISSUE TITLE
Content SEO no longer showing content entry sections

### ISSUE THREAD

**Issue by ja5ee** [nystudio107/craft-seomatic#1134]
We have lost entry types in the Content SEO Section of the SEOMatic Plugin. In the content configuration - settings are populated with 8 unique sections all defined by entry types - most are channels with pages being structure.

The result of this is that "content SEO" is not populating and our sitemap is no longer generating.

Here's a screenshot of the SEOMatic Dashboard
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/66383726/166507632-53c75dfe-52c6-43ba-bd32-fc9c73381bdc.png">

Here's a screenshot of the SEOMatic Content SEO Entries
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/66383726/166507764-f8f787de-e6e5-4c4d-b26b-6352f9ac2cb7.png">

And when checking /sitemap.xml
<img width="933" alt="image" src="https://user-images.githubusercontent.com/66383726/166507869-e2719b07-1f55-45b8-bd89-a75adc56732d.png">

### Expected behaviour
This used to be populated. Don't know exactly when it started failing, but doesn't appear that the data is populating.

We have tried uninstalling and re-installing - but get the same results. 

Other plugins include:
Blitz
Navigation
NEO
GDPR Cookie Consent

### Versions
- Plugin version: 3.4.28
- Craft version: 3.7.37

@simb

**Comment by khalwat** [comment]
Check your Sites -- it's most likely that they are not enabled anymore.

Also I'd recommend updating to the latest version of the plugin, and also checking your logs for errors.

**Comment by ja5ee** [comment]
So our Sitemaps are enabled. 
<img width="710" alt="image" src="https://user-images.githubusercontent.com/66383726/167511379-db7bad2d-b2ee-4542-84d2-28006af7f257.png">

Also, updated SEOMatic to current version.

Still no Content in "Content SEO" and Sitemaps are not generating.

In the Content SEO, it used to list all the Entry types with controls for managing default content from existing fields. It's all completely empty. 

Why would it stop pulling the Sections Content?
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/66383726/167511565-73e69cb3-91c8-433e-9eea-a50beff99f09.png">

Thank you.

**Comment by khalwat** [comment]
The place I want you to go is not the Plugin Settings, but rather the Sitemaps Settings under Content SEO:

<img width="1491" alt="Screen Shot 2022-05-09 at 6 55 43 PM" src="https://user-images.githubusercontent.com/7570798/167511747-c18d7aec-bb53-49f1-984d-023d73a96925.png">

**Comment by khalwat** [comment]
Some of your Sections are working fine, others are not. So compare the settings for the sections that are working with the ones that are not.

You can also check the **General** settings under Content SEO to ensure that your Robots setting is set to All

**Comment by khalwat** [comment]
Also when I say to check your Sites, I mean to go here:

Settings -> Sites

...and ensure your site has its own Base URL, with that option checked:

<img width="1491" alt="Screen Shot 2022-05-09 at 6 57 55 PM" src="https://user-images.githubusercontent.com/7570798/167512009-aa9f7ac6-96f2-4ff4-968f-ba29cdeafb66.png">

**Comment by ja5ee** [comment]
Here's the content SEO ... it doesn't have the Settings Section to go to Sitemap
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/66383726/167512454-2e9b3b67-03f4-46bc-9731-1b65b9291197.png">

For the Sites ... I went there and the site is there.
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/66383726/167512604-f66b624f-235a-4f1e-bc89-57c1bd99924c.png">

Thx.

**Comment by ja5ee** [comment]
In the content SEO section, we definitely do not have the left rail with "SETTINGS - general / twitter / facebook / sitemap"

Thx.

**Comment by khalwat** [comment]
Please set a Base URL for your site by checking **[x] This site has its own Base URL** checkbox, and entering a URL

**Comment by ja5ee** [comment]
Question on this ... I know you closed this issue. We're currently setting the Base URL with an Environment Variable in Fortrabbit. 

Does this have to be set in the admin to work? Is the ENV VAR no longer functioning as it used to?

@khalwat

**Comment by khalwat** [comment]
If that checkbox is not checked, then the `hasUrls` for that site is set to `false` -- which SEOmatic and other things look at to determine whether or not the site has any public URLs.

If a site has no public URLs, SEOmatic uses that as a trigger to not provide an SEO information for that site.

You can still use your environment variable, just set that in the field that appears after you check **[x] This site has its own Base URL**

See here for setting up sites: https://craftcms.com/docs/3.x/sites.html#step-1-create-the-site-in-settings
