### ISSUE TITLE
Change primary topic in structured json data using twig directives?

### ISSUE THREAD

**Issue by webtrend** [nystudio107/craft-seomatic#1135]
### Question
How do I change primary topic in structured data of a page programmatically using twig template directives?
Currently, it is pulling topic from the global settings (Main Entity of Page) and it looks like this:

`<html>
<body>

{
--
  | "@context": "http://schema.org",
  | "@graph": [
  | {
  | "@type": "WebSite",
  | "author": {

</body>
</html>`

I want to change @type from "WebSite" to "Article" for a particular URL route which has its own template and therefore I can control the structured data using twig directives. I made several attempts using the examples from the documentation but have been unsuccessful so far. 

Some help will be appreciated. Thanks.

**Comment by khalwat** [comment]
There are a whole bunch of examples here:

https://nystudio107.com/docs/seomatic/using.html#json-ld-meta-object-functions-seomatic-jsonld

and here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

**Comment by khalwat** [comment]
> I want to change @type from "WebSite" to "Article" for a particular URL route which has its own template and therefore I can control the structured data using twig directives. I made several attempts using the examples from the documentation but have been unsuccessful so far.

If all you want to do is change the type, though, you can do that via Content SEO settings, which let you have section-level settings. For instance, in my Blog section, the Main Entity of Page is set to Article

There is also a SEO Settings field, which can be used to change this on a per-entry basis, but typically that isn't needed

**Comment by webtrend** [comment]
Thanks for your prompt response. I had tried seomatic.jsonLD.create method when I posted this question but the issue is that it does not overwrite the original but it creates a new entry in the json. So for example when I do this

    {% do seomatic.jsonLd.create({
           'type': 'Article',

The json output looks like this

       "@graph": [
         {
                 "@type": "WebSite"
                 "author": {
          ...
                    },
           ... 
           },
         {
             "@type": "Article",
              ....
          }
          ]
          
How do I overwrite the automatically generated @type declaration? What am I missing?

**Comment by khalwat** [comment]
Again, you should not need to do this. You should be able to set the JSON-LD type to whatever you want via Content SEO in the Craft CP:

https://nystudio107.com/docs/seomatic/configuring.html#content-seo

But if you really want to do it manually, you'll need to pass the key `mainEntityOfPage` to have it replace it:

```twig
{% set myJsonLd = seomatic.jsonLd.create({
    'key': 'mainEntityOfPage',
    'type': 'Article',
    'name': 'Some Blog',
    'url': 'https://nystudio107.com/blog',
}) %}
```
