### ISSUE TITLE
Define custom Sitemap URLs

### ISSUE THREAD

**Issue by martinhellwagner** [nystudio107/craft-seomatic#1136]
### Question
I was wondering if it's possible to define custom Sitemap URLs for the sitemap index and referenced sitemaps. At the moment, our sitemaps are located at `https://www.domain.com/sitemaps-2-sitemap.xml`, but the domain owner doesn't allow us to access this namespace. Thus, we'd like the sitemap index to be located at `https://www.domain.com/c/sitemaps-2-sitemap.xml`, for the simple reason that the `/c` namespace is entirely mapped to Craft CMS. Is that possible?

**Comment by khalwat** [comment]
Yes it is. You can do this in SEOmatic > Site Settings > Sitemaps

https://nystudio107.com/docs/seomatic/configuring.html#additional-sitemaps

<img width="1336" alt="Screen Shot 2022-05-10 at 12 26 08 PM" src="https://user-images.githubusercontent.com/7570798/167677242-5d98800f-21b2-4dd9-a8a3-43bd601f9261.png">

There are also events you can listen to, if you want to do something custom in PHP:

https://nystudio107.com/docs/seomatic/advanced.html#registersitemapurlsevent

**Comment by martinhellwagner** [comment]
@khalwat 

But how can I, in this case, use the sitemaps that SEOmatic creates for me? In my understanding, referncing additional sitemaps requires me to provide my own sitemaps, not make use of the ones that SEOmatic creates for me.

**Comment by khalwat** [comment]
I see, I'm sorry, I misread your original question.

What you're trying to do may not be to spec in any event:

https://www.sitemaps.org/protocol.html#location

> The location of a Sitemap file determines the set of URLs that can be included in that Sitemap. A Sitemap file located at http://example.com/catalog/sitemap.xml can include any URLs starting with http://example.com/catalog/ but can not include URLs starting with http://example.com/images/.

So if you put these files in `/c/` they could only reference URLs in `/c/` which doesn't appear to me to be how your site is set up?

**Comment by martinhellwagner** [comment]
In fact, that would even be okay. Everything in the scope of this project runs under `https://www.domain.com/c/...` except the homepage (which runs under `https://www.domain.com/blog`). However, the Site URL for this project is still `https://www.domain.com` because of another project in the same Craft installation. So if we can somehow manage to access the sitemaps under `https://www.domain.com/c/sitemaps-2-sitemap.xml`, that would be great!

**Comment by khalwat** [comment]
If that's the case, then your Craft CMS site URL should be defined as `https://www.domain.com/c/` and everything should work as expected in SEOmatic.

If you're unable to do _that_, then you can try looking into the Site URL Override config feature in SEOmatic: https://github.com/nystudio107/craft-seomatic/blob/develop/src/config.php#L141

**Comment by martinhellwagner** [comment]
I'm afraid changing the Site URL is impossible, since URLs like `https://www.domain.com/presse` and `https://www.domain.com/lp/mobileapp` are present in the same multisite. If we're manually overriding the Site URL, then the sitemaps for those two sites are probably not generated correctly, right?

**Comment by khalwat** [comment]
I think for this fairly custom setup, you're going to need to do some extra work. You could do something like once per day, run a cron job that `curl`s the sitemaps from where they are, to where you want them to be, for instance.

**Comment by martinhellwagner** [comment]
Yes, I think I'll have to investigate further. Thanks for the help though! 🙂

**Comment by martinhellwagner** [comment]
@khalwat 

One more question: I'm currently setting the robots tag for sites like https://www.domain.com/brutto/3000 or https://www.domain.com/c/brutto-netto-rechner/3000 manually using `{% do seomatic.meta.robots('all') %}` – only https://www.domain.com/c/brutto-netto-rechner should have `{% do seomatic.meta.robots('none') %}`.

However, after deployment and Blitz cache warming, some pages still have "none" as their robots tag. Is it possible that, if Blitz encounters a 500 server error (which sometimes occurs when e.g. the API doesn't respond in time) when caching these pages, the robots tag is not set correctly?

What's more, the pages that are wrongly classified also lack the `og:url` attribute. Could that information be of any help?

**Comment by khalwat** [comment]
You probably shouldn't be manually setting the robots tags manually unless there's some edge case you're encountering?

SEOmatic will set it automatically for you based on the environment you're on: https://nystudio107.com/docs/seomatic/configuring.html#multi-environment-config-settings

Is there a reason you're attempting to set this tag manually?

**Comment by martinhellwagner** [comment]
Yes, in this case we need to set the tag manually – or at least make sure it's definitely set. The reason is that we have a custom routing for these pages in place, which makes them not "pages" coming Craft CMS per se, but which are rather routed to a template with Sprig components that is then Blitz-cached.
