### ISSUE TITLE
"Brand" & "SKU" snippets with mainEntityOfPage equal to "Product"

### ISSUE THREAD

**Issue by Romanavr** [nystudio107/craft-seomatic#1138]
### Question
Greetings, i have next environment:
- **Craft CMS** 3.7.38
- **Craft Commerce** 3.4.14
- **SEOmatic** 3.4.29

I'm trying to make snippets (schema) for a product via [JSON-LD](https://nystudio107.com/docs/seomatic/using.html#json-ld-meta-object-functions-seomatic-jsonld).
So my mainEntityOfPage is "product" and some thing seems not working correctly or I'm missing something.
I can't make "brand" & "sku" snippet for product, e.g. "brand" snippet works for **identity**, but not for **product**, example of piece of code below.

Most of the attributes(offers, review, aggregateRating) work, but not these two.
I tried to do it also through the "{% do %}" tag, like with identity, but it didn't help, moreover, craft starts complaining [about the wrong property](https://i.imgur.com/ZSg18O6.png) (probably that's the issue, like this property is not set for a mainEntityOfPage of product type)

```
{% do seomatic.meta.setAttributes({
  mainEntityOfPage: "Product",
  ...
}) %}

{% set mainEntity = seomatic.jsonLd.get("mainEntityOfPage") %}

{% do mainEntity.brand(brandJsonLd) %}
```

On output i'm getting "<script type="application/ld+json">...." with my data except "brand" & "sku" properties.

What am I missing?

```
 ...

  {% set brandJsonLd = seomatic.jsonLd.create({
    'type': 'Brand',
    'name': 'My Brand',
  }, false) %}

  {% set aggregateOffersJsonLd = seomatic.jsonLd.create({
    'type': 'AggregateOffer',
    'lowPrice': '1',
    'highPrice': '100',
    'offerCount': productVariants|length,
    'priceCurrency': 'USD',
  }, false) %}

  {% do mainEntity.setAttributes({
    'sku': 'Test SKU 12345',
    'aggregateRating': aggregateRatingJsonLd,
    'offers': aggregateOffersJsonLd,
    'review': reviewsJsonLtdArray,
    'brand': aggregateOffersJsonLd,
  }) %}
  
  {% set identity = seomatic.jsonLd.get('identity') %}
  {% do identity.brand(brandJsonLd) %}

```

### Additional context
https://developers.google.com/search/docs/advanced/structured-data/product
https://i.imgur.com/4K8tbrX.png

**Comment by Romanavr** [comment]
I found how to deal with it. If it will be useful to someone https://nystudio107.com/blog/annotated-json-ld-structured-data-examples#nys-tu-dio107-com-plugin-page.

```
  {% do mainEntity.setAttributes({
    'aggregateRating': aggregateRatingJsonLd,
    'offers': aggregateOffersJsonLd,
    'review': reviewsJsonLtdArray,
  }) %}

  {# Some properties can only be overwritten like this #}
  {% set productConfig = mainEntity.getAttributes() | merge({
    'type': 'Product',
    'sku': product.sku,
    'brand': brandJsonLd,
  }) %}

  {% set product = seomatic.jsonLd.create(productConfig) %}
```

**Comment by khalwat** [comment]
Glad you have it sorted!
