### ISSUE TITLE
Using site variable inside GraphQL does not seem to support query variables.

### ISSUE THREAD

**Issue by mutschelknauss** [nystudio107/craft-seomatic#1139]
Hi SeoMatic team,

Thanks for all your hard work, we are a big fan of your plugin and use it in quite a few of our client websites.

Perhaps i'm doing something obvious wrong, sorry for your time then

It seems that when using Seomatic trough Craft as GraphQL and you want to use site handle to grab information from a certain site, it only allows for hardcoded strings as a paramater. When using a variable within the graphql explorer inside Craft, it complains that seomatic expects a string. While using this same variable to fetch native craft entries does work with this siteHandle variable.

### Expected behaviour
Expecting to pass the same site variable to Seomatic as passing a site variable to Seomatic fields.

### Screenshots
Example of failing query, passing the site as a Query Variable.
<img width="1438" alt="Screenshot 2022-05-13 at 14 52 18" src="https://user-images.githubusercontent.com/2486945/168287115-e0863ed7-0aa7-45b3-8bcf-5a4e30c7b580.png">

Example of working query, hardcoding the site inside the GraphQL contents

<img width="1436" alt="Screenshot 2022-05-13 at 14 50 59" src="https://user-images.githubusercontent.com/2486945/168286852-07ec307d-de0f-491d-9dce-68be98748f26.png">

### Versions
- Plugin version: 3.4.30
- Craft version: 3.7.41

**Comment by khalwat** [comment]
All sorted?

**Comment by mutschelknauss** [comment]
Hi @khalwat  

Yeah I've found a work around instead as I was a bit in a rush. 
Still not sure why it's not working as I thought it would, below you can find my work-around, for anyone coming across the same perhaps.

GraphQl Query:
```
query GlobalQuery($site:[String], $seoUri:String, $seoSite:String) {
    seomatic(asArray: true, uri: $seoUri, site: $seoSite) {
      metaTitleContainer
      metaTagContainer
      metaLinkContainer
      metaScriptContainer
      metaJsonLdContainer
    }
    navigation: globalSet(site: $site, handle: ["navigation"]) {
        ...NavigationFragment
    }
 }
 ```
 
 Query Variables:
 ```
 {
  "site": "rinusRO",
  "seoUri": "training/id/50443",
  "seoSite": "rinusRO"
}
 ```


So what I did was passing the same query variable twice under a different key (site & seoSite). And within the GraphQL I format the `$site` query as `$site:[String]` but format the `$seoSite` query fro Seomatic as `$seoSite:String`.

Could be that i'm not understanding GraphQL properly but i would expect both Craft Entries and SeoMatic siteHandle variables to be formatted the same way.
