### ISSUE TITLE
Error when clicking 'Site Settings' menu option in control panel

### ISSUE THREAD

**Issue by pauljohnston** [nystudio107/craft-seomatic#114]
Impossible to access an attribute ("helper") on a null variable.

in /vendor/nystudio107/craft-seomatic/src/templates/settings/_includes/mainEntityOfPage-partial.twig at line 15

`options: seomatic.helper.getSingleTypeMenu(''),`

Seomatic version 3.0.15
Craft version 3.0.8

Let me know if you need any more info

**Comment by khalwat** [comment]
This has been fixed in 3.0.16: https://github.com/nystudio107/craft-seomatic/releases/tag/3.0.16
