### ISSUE TITLE
Sitemap with 503 error in tools like Semrush

### ISSUE THREAD

**Issue by jwmatlock** [nystudio107/craft-seomatic#1143]
We have a number of sites now, different servers, where different audit tools, like Semrush, flag the sitemap link with a 503 error. First thought the sitemaps were getting trapped in the queue manager (and there may still be something related to that). We installed Async to try and resolve that, but we're still seeing sitemaps getting flagged with a 503. Typically, by the time we check on it, the sitemap loads, but on occasion, we have seen the sitemap pull up a 503. Ideas?

**Comment by khalwat** [comment]
What version of SEOmatic are you running? And what version of Craft CMS?

**Comment by jwmatlock** [comment]
Craft 3.7.31
3.4.23

**Comment by khalwat** [comment]
Please update to the latest version of SEOmatic, 3.4.30 at the time of this writing

This issue was addressed in 3.4.29: https://github.com/nystudio107/craft-seomatic/blob/develop/CHANGELOG.md#3429---20220408

Also, `503` is the correct error code which tells GoogleBot to "try again later", with SEOmatic setting the [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) appropriately.

**Comment by aaronlax** [comment]
I am having the same issue with multiple sites, and have updated per your instruction. SEMrush now can see the top level sitemap (sitemaps-1-sitemap.xml) but reports a 503 error for every subsequent .xml listed on that page. I have never seen a 503 error in the browser, and google search console does not report any issues.

**Comment by khalwat** [comment]
@aaronlax that says to me that it might be an issue with SEMrush?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d7ab612044ba7cbd011e273ae31bfcb2d0231050 & https://github.com/nystudio107/craft-seomatic/commit/309fb39907876169a5215208abce4a7526c81a98

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.39”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.9”,
```
Then do a `composer clear-cache && composer update`
