### ISSUE TITLE
Craft 4.0 - 500

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#1145]
### Describe the bug
Just upgrade from Craft 3 to 4, and seomatic throws a 500 error 

An Error occurred while handling another error:
TypeError: Cannot assign null to property craft\validators\DateTimeValidator::$tooEarly of type string in /home/xx/releases/20220519111253/vendor/yiisoft/yii2/caching/Cache.php:138
Stack trace:
#0 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/caching/Cache.php(138): unserialize()
#1 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/caching/Cache.php(603): yii\caching\Cache->get()
#2 /home/xx/releases/20220519111253/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(271): yii\caching\Cache->getOrSet()
#3 /home/xx/releases/20220519111253/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(249): nystudio107\seomatic\services\MetaContainers->parseGlobalVars()
#4 /home/xx/releases/20220519111253/vendor/nystudio107/craft-seomatic/src/Seomatic.php(785): nystudio107\seomatic\services\MetaContainers->includeMetaContainers()
#5 [internal function]: nystudio107\seomatic\Seomatic::nystudio107\seomatic\{closure}()
#6 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#7 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#8 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/web/View.php(180): yii\base\Component->trigger()
#9 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/View.php(1747): yii\web\View->endPage()
#10 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/View.php(468): craft\web\View->endPage()
#11 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate()
#12 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format()
#13 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
#14 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#15 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#16 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/ErrorHandler.php(185): yii\web\ErrorHandler->renderException()
#17 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException()
#18 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/ErrorHandler.php(64): yii\base\ErrorHandler->handleException()
#19 [internal function]: craft\web\ErrorHandler->handleException()
#20 {main}
Previous exception:
TypeError: Cannot assign null to property craft\validators\DateTimeValidator::$tooEarly of type string in /home/xx/releases/20220519111253/vendor/yiisoft/yii2/caching/Cache.php:138
Stack trace:
#0 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/caching/Cache.php(138): unserialize()
#1 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/caching/Cache.php(603): yii\caching\Cache->get()
#2 /home/xx/releases/20220519111253/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(271): yii\caching\Cache->getOrSet()
#3 /home/xx/releases/20220519111253/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(249): nystudio107\seomatic\services\MetaContainers->parseGlobalVars()
#4 /home/xx/releases/20220519111253/vendor/nystudio107/craft-seomatic/src/Seomatic.php(785): nystudio107\seomatic\services\MetaContainers->includeMetaContainers()
#5 [internal function]: nystudio107\seomatic\Seomatic::nystudio107\seomatic\{closure}()
#6 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#7 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#8 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/web/View.php(180): yii\base\Component->trigger()
#9 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/View.php(1747): yii\web\View->endPage()
#10 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/View.php(468): craft\web\View->endPage()
#11 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate()
#12 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format()
#13 /home/xx/releases/20220519111253/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
#14 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#15 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#16 /home/xx/releases/20220519111253/web/index.php(24): yii\base\Application->run()
#17 {main}

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Versions
- Plugin version:
- Craft version:

**Comment by lenvanessen** [comment]
Clearing cache fixed

**Comment by danjrichardson** [comment]
> Clearing cache fixed

Phew, thanks. This bricked a site for me but a cache clear through the CP fixed the issue.

**Comment by khalwat** [comment]
Yeah in general, I'd suggest clearing all caches on updates, similar to what I do here:

https://nystudio107.com/blog/updating-craft-cms-without-headaches#composer-2-0

**Comment by khalwat** [comment]
Related: https://github.com/craftcms/cms/issues/11455
