### ISSUE TITLE
DataLayer overwritten when using gtag.js and Google Tag Manager

### ISSUE THREAD

**Issue by CraigPedleyCF** [nystudio107/craft-seomatic#1146]
### Describe the bug
Is there an issue with the order of gtag and Google Tag Manager are added. 
`
<title>Home | SiteName</title>
<script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments)};
gtag('js', new Date());
gtag('config', 'UA-XXXXXXX-2', {'send_page_view': true,'anonymize_ip': false,'link_attribution': false,'allow_display_features': false});
</script>
<script>dataLayer = [];
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXXXX');
</script><meta name="generator" content="SEOmatic">
`

It seems dataLayer = []; is overwriting the previous data layer pushed. This means custom gtag events are not fired. 

This line in the script template seems to be causing the issue.

{{ dataLayerVariableName.value }} = [{% if dataLayer is defined and dataLayer %}{{ dataLayer |json_encode() |raw }}{% endif %}];

### Versions
- Plugin version: 3.4.22
- Craft version: 3.7.38

**Comment by khalwat** [comment]
Yes, the idea is that you're using Twig to construct your data layer, or that you add any custom events after the above Twig code has been executed.

If neither are the case for you, then you can change the Twig code that comes as a default with SEOmatic to whatever suits your needs. The template provided is what most people will want in most cases, but it is fully customizable, so you can change it to be whatever you need it to be.
