### ISSUE TITLE
Stop auto rendering of SEOMatic for alternate .env

### ISSUE THREAD

**Issue by chadcrowell** [nystudio107/craft-seomatic#1147]
### Question
I have a site with SEOMatic (both Craft 3 and SEOMatic up to date) with a unique requirement. The site has standard Craft setup using .env files for local and production environments and an `$ENVIRONMENT` variable in the .env.

This site is for a medical hardware manufacturer. Their sales reps go to a lot of appointments inside of hospitals and clinics where wifi or internet is not available. So that they have the entire website of product info available, I download a copy of the site in a localized manner (using wget through Site Sucker app) and then wrap it in an iPad app using Cordova. It is deployed to the sales staff via an enterprise distribution App Store. This works great but I have noticed that both SEOmatic data and Webperf code are rendered in the localized version of the site that goes into the app and would like to avoid that.

How I make the localized version of the site: Let's say the main site is `www.domain.com`. The alternate version that is downloaded via wget is at `tblt.domain.com`. This is not a separate site within Craft, it is the default `www` site. When the site is loaded using the `tblt` domain, I set some unique .env vars using separate .env files that override the regular .env file. This is what my index.php file looks like to enable this:

```
<?php
/**
 * Craft web bootstrap file
 */

// Set path constants
define('CRAFT_BASE_PATH', dirname(__DIR__));
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load dotenv?
// @HACK #2: CDC 20210727
// Change phpdotenv loading syntax to expose override function below
// https://stackoverflow.com/questions/41958880/use-multiple-env-files
if (class_exists('Dotenv\Dotenv') && file_exists(CRAFT_BASE_PATH.'/.env')) {
    $dotenv = new \Dotenv\Dotenv(CRAFT_BASE_PATH);
    $dotenv->load();
}

// Override some .env vars for TBLT version of site
if ((strpos($_SERVER['HTTP_HOST'], 'tblt.') !== false) && (file_exists(CRAFT_BASE_PATH.'/.env.tblt'))) {
    $dotenv = new \Dotenv\Dotenv(CRAFT_BASE_PATH, '.env.tblt');
    $dotenv->overload();
}
// @ENDHACK

// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
```

There are only a few vars set in the `.env.tblt` file, and they override defaults for the same vars that are set in the regular `.env` file. I use those vars throughout my templates to evaluate if some content should be shown, or not (videos loaded via Vimeo, for instance, aren't shown in the iPad app version of the site). 

One of the .env vars I have is `$SEOMATIC_ENV` which, on the standard production site is set to `live`, and on the `.env.tblt` is set to `staging`. I have `Manually Set SEOmatic Environment` in the SEOMatic settings set to `true` and `$SEOMATIC_ENV` set as the `Environment` value in the Plugin settings. On the SEOMatic dashboard for `www.domain.com` I see that the environment is live and for `tblt.domain.com` it is shown as staging. However, when I view source for the `tblt` version of the homepage, the GTM code is in there rendered. My expectation is that when SEOMatic's environment is not `live`, its code would not be rendered on the front end. I have tried both `live` and `production` as the `$SEOMATIC_ENV` value with the same results.

Is there a better way to get it to not render on this alternate version of the site? Since they are the same site within Craft's eyes, I can't use any sort of `currentSite.handle`, but I do have a globally available .env var `$IS_TBLT` which is true or false that I can use. But I would think I don't need to do any of this within the templates. It seems like what I have setup should work but I think SEOMatic may be too smart for me here.

**Comment by khalwat** [comment]
Probably, it is just cached.  What I think you should _also_ do is set `APP_ID` as an environment variable, so that this "other" site has a separate cache key, and is cached separately. 

https://craftcms.com/docs/3.x/config/#cache-component

https://github.com/nystudio107/devmode/blob/develop/cms/config/app.php#L31

If that doesn't do it, you can also just disable SEOmatic programmatically (either via PHP or via Twig) via `seomatic.config.renderEnabled`:

https://nystudio107.com/docs/seomatic/using.html#config-variables-seomatic-config

https://github.com/nystudio107/devmode/blob/develop/cms/templates/feed.json#L5
