### ISSUE TITLE
SEO content not coming through

### ISSUE THREAD

**Issue by fritkotparking** [nystudio107/craft-seomatic#115]
I made a structured section for Blog articles and created 2 entries for this.
I defined some content fields for SEO (title, description, keywords, image) and filled everything in.
The first Blog entry has all the right content (SEO Title etc.), but the other entry doesn't get the SEO content and falls back on the default settings>
(I tried to create more entries, but they all have the same issue)

SEO settings:
![image](https://user-images.githubusercontent.com/1456835/40264158-595bb508-5b61-11e8-9b44-1a0169635655.png)

SEO preview (content is in Dutch, but you can see the difference in Title and Description)
![image](https://user-images.githubusercontent.com/1456835/40264165-7b05bb68-5b61-11e8-8348-86c231569509.png)

**Comment by khalwat** [comment]
In SEOmatic -> Content SEO did you set up the Sections to pull from these fields that you created? Can we see what your Content SEO settings look like for this section?

Also in general, with SEOmatic for Craft 3, you shouldn't need to create separate fields for things like SEO Title, SEO Keywords, etc. Instead you can just set the settings in the Content SEO section to pull from existing content fields.

Or if you _really_ want to let someone put in custom titles/descriptions, you can just use the SEO Settings field that comes with SEOmatic.

**Comment by khalwat** [comment]
@fritkotparking ?

**Comment by fritkotparking** [comment]
Hi Andrew,

sorry I forgot to reply - we were able to buy seomatic and update to the
latest version. We're not encountering any problems at the moment.

Kind regards,
Stijn
