### ISSUE TITLE
Plugin Settings should not be available when admin changes are disallowed 

### ISSUE THREAD

**Issue by JeanLucEsser** [nystudio107/craft-seomatic#1150]
The plugin settings page can be accessed even when admin changes are disallowed.

As you mentioned in [discord](https://discord.com/channels/456442477667418113/575387375610626063/981630291019976744), resolution should be two fold: 1) there should be no hyperlink in that case and 2) going directly to the URL should throw an error.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/14908712/171485621-d5de1e93-5b11-4f34-bb8b-708120391888.png">

### Versions
- Plugin version: 4.0.1
- Craft version: 4.0.3

**Comment by khalwat** [comment]
What we should do here is check for permissions on each page, and also not display the hyperlink if admin changes are off.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/6005404930d2d3384982d7c0cceabfe777bea9db & https://github.com/nystudio107/craft-seomatic/commit/304fe60eee35dec55d6e1cbf8efa296952d10283

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.32”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.2”,
```
Then do a `composer clear-cache && composer update`
