### ISSUE TITLE
Discrepancy between metaTagContainer and metaJsonLdContainer images in GQL query

### ISSUE THREAD

**Issue by dguillory** [nystudio107/craft-seomatic#1152]
### Describe the bug
When querying entries via GraphQL, the images returned by the metaTagContainer and metaJsonLdContainer aren't matching. The metaJsonLdContainer image is always correct, but the meta og:image is either incorrect, or just empty. (Sorry in advance if this isn't a bug, but I'm baffled.)

### To reproduce
Steps to reproduce the behaviour:
1. Set an entry's SEO image source to any custom image or asset field
2. Query the entry's metaTagContainer and metaJsonLdContainer
3. See the expected image in metaJsonLdContainer, and a different result in metaTagContainer

### Expected behaviour
metaTagContainer and metaJsonLdContainer returning the same image set in the SEO image source

### Versions
- Plugin version: 3.4.31
- Craft version: 3.7.44

**Comment by khalwat** [comment]
Probably this is because it's not the same image in both cases. In the case of the `og:image` it is pulling from whatever the **Facebook OpenGraph Image** is set to, whereas what is in the `metaJsonLdContainer` that's just whatever the `seoImage` is set to.
