### ISSUE TITLE
Compatibility error with Wordsmith plugin 4.0.1

### ISSUE THREAD

**Issue by cloudgrayau** [nystudio107/craft-seomatic#1153]
It seems that SEOMatic 4.0.1 forces the use of "davechild/textstatistics 1.0.2", where as latest version of Wordsmith (4.0.1) requires "davechild/textstatistics ^1.0.3" to be installed.

Can you please upgrade SEOMatic to use ^1.0.3 or above? Thanks!

[@topshelfcraft](https://github.com/TopShelfCraft/Wordsmith)

**Comment by khalwat** [comment]
This was pinned to a specific version because of the PHP requirements, but it should be possible to update it now:

https://github.com/DaveChild/Text-Statistics/issues/48

**Comment by johndwells** [comment]
Came here to post the same issue. 🙏

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/2a9aaaf7ea06c4678fd4ae8fd4ae023bc05692cc

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.2”,
```
Then do a `composer clear-cache && composer update`
