### ISSUE TITLE
Blank sitemap on front end, but visible in source code

### ISSUE THREAD

**Issue by iamtompickering** [nystudio107/craft-seomatic#1155]
### Describe the bug
On our production environment, for some reason the sitemap is showing up blank on the front end. If I view the source of the page though, I can see what looks like the correct code. 

This is just happening on production, viewing the sitemaps frontend locally works fine. 

I've tried regenerating the sitemap vi the CLI but this had no effect. 

Any reasons why this might be happening?!

### Versions
- Plugin version: 3.4.30
- Craft version: 3.7.40.1

EDIT: Just noticed Firefox is giving some further insight to the errors happening. Any idea why the below error might be happening?

```
XML Parsing Error: syntax error
Location: https://xxxxxxxx.co.uk/sitemaps-1-sitemap.xml/sitemap.xsl
Line Number 1, Column 1:
<!doctype html><html
^
```

Also have spotted the following in the logs

```
2022-06-13 14:55:31 [-][705][rr27mtkf099lijkfapg0i3tgdl][error][yii\web\HttpException:404] yii\web\NotFoundHttpException: Template not found: sitemaps-1-sitemap.xml/sitemap.xsl in /xxxxxx/xxxxxx/xxxxxx.co.uk/vendor/craftcms/cms/src/controllers/TemplatesController.php:94
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender()
#1 /xxxxxx/xxxxxx/xxxxxx.co.uk/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /xxxxxx/xxxxxx/xxxxxx.co.uk/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#3 /xxxxxx/xxxxxx/xxxxxx.co.uk/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#4 /xxxxxx/xxxxxx/xxxxxx.co.uk/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction()
#5 /xxxxxx/xxxxxx/xxxxxx.co.uk/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#6 /xxxxxx/xxxxxx/xxxxxx.co.uk/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest()
#7 /xxxxxx/xxxxxx/xxxxxx.co.uk/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#8 /xxxxxx/xxxxxx/xxxxxx.co.uk/web/index.php(21): yii\base\Application->run()
#9 {main}
2022-06-13 14:55:31 [-][705][rr27mtkf099lijkfapg0i3tgdl][info][application] $_GET = [
    'p' => 'sitemaps-1-sitemap.xml/sitemap.xsl/'
]
```

**Comment by khalwat** [comment]
So the sitemap is there, the `. xsl ` that you see in the logs is just to create a human-readable version of the sitemap. Bots will still find and consume the sitemap.

`. xsl ` files are essentially  XML stylesheets.

As for why it isn't working, I think it's possible that there's a server config issue on your end potentially? For some reason it's treating `sitemaps-1-sitemap.xml` is a directory, and thus is looking for the `.xsl` stylesheet in `sitemaps-1-sitemap.xml/sitemap.xsl` when it really should be looking for just `sitemap.xsl`

Given that this is working with the current SEOmatic on every site I'm able to check, I'm pretty sure this is going to be a server config issue on your end.

https://nystudio107.com/sitemaps-1-sitemap.xml

https://devmode.fm/sitemaps-1-sitemap.xml
