### ISSUE TITLE
GraphQL: frontendTemplates requesting disabled file results in error

### ISSUE THREAD

**Issue by d--j** [nystudio107/craft-seomatic#1156]
### Describe the bug
When the GraphQL client requests a frontendTemplate that is disabled, SEOMatic returns an error (Undefined array key "ads").

```gql
query {
  seomatic {
    frontendTemplates(type:ads) {
      contents
    }
  }
}
```
### To reproduce
Steps to reproduce the behaviour:
1. Go to "SEOMatic -> Global SEO -> Ads" and disable ads.txt
2. Execute the GraphQL query to get ads.txt
3. The response has errors
```json
{
  "errors": [
    {
      "debugMessage": "Undefined array key \"ads\"",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "file": "/app/app/vendor/nystudio107/craft-seomatic/src/gql/resolvers/FrontendContainerResolver.php",
      "line": 56,
      "trace": [
        {
          "file": "/app/app/vendor/craftcms/cms/src/web/ErrorHandler.php",
          "line": 77,
          "call": "yii\\base\\ErrorHandler::handleError(2, 'Undefined array key \"ads\"', '/app/app/vendor/nystudio107/craft-seomatic/src/gql/resolvers/FrontendContainerResolver.php', 56)"
        },
        {
          "file": "/app/app/vendor/nystudio107/craft-seomatic/src/gql/resolvers/FrontendContainerResolver.php",
          "line": 56,
          "call": "craft\\web\\ErrorHandler::handleError(2, 'Undefined array key \"ads\"', '/app/app/vendor/nystudio107/craft-seomatic/src/gql/resolvers/FrontendContainerResolver.php', 56)"
        },
        {
          "file": "/app/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 623,
          "call": "nystudio107\\seomatic\\gql\\resolvers\\FrontendContainerResolver::getContainerFiles(array(7), array(1), array(2), instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        ...
      ]
    }
  ],
  "data": {
    "seomatic": {
      "frontendTemplates": null
    }
  }
}
```

### Expected behaviour
The GraphQL query should not return `errors`, only the expexted `null` value or an empty array:
```json
{
  "data": {
    "seomatic": {
      "frontendTemplates": null
    }
  }
}
```

### Versions
- Plugin version:  4.0.1
- Craft version: Craft Pro 4.0.4

### Possible Fix

change
https://github.com/nystudio107/craft-seomatic/blob/36686d1d11abb53390f434571f7abc72a2d8a752/src/gql/resolvers/FrontendContainerResolver.php#L54-L58

to

```diff
         if (!empty($arguments['type'])) {
+            if (!array_key_exists($arguments['type'], $containerItems)) {
+                return null;
+            }
             $containerItems = [
                 $arguments['type'] => $containerItems[$arguments['type']]
             ];
         }
```

**Comment by khalwat** [comment]
I like your fix idea, thx

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/54f1fcbcb61d2825419297a5657d0ad611d9a8e6& https://github.com/nystudio107/craft-seomatic/commit/110702756a5c827db006ca0ca2bc1c45c569d5e4

It now returns an empty array

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.32”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.2”,
```
Then do a `composer clear-cache && composer update`
