### ISSUE TITLE
Accessing admin/seomatic/site throws Twig merge filter error

### ISSUE THREAD

**Issue by sevfurneaux** [nystudio107/craft-seomatic#116]
When accessing admin/seomatic/site, the following error is thrown:

`Twig_Error_Runtime: The merge filter only works with arrays or "Traversable", got "NULL" as second argument. in /app/vendor/nystudio107/craft-seomatic/src/templates/settings/site/identity.twig:35`

**Comment by khalwat** [comment]
What version of Craft CMS and what version of SEOmatic are you using? Try updating to the latest for both?

**Comment by sevfurneaux** [comment]
We’re using Craft 3.0.8 and SEOMatic 3.0.15.

**Comment by khalwat** [comment]
Can you get me a more complete error, perhaps with a stack trace or such?

**Comment by khalwat** [comment]
Please update to SEOmatic 3.0.18 and let me know if it fixes it for you?

**Comment by sevfurneaux** [comment]
Thanks, updated to 3.0.18 and that is now fixed 👍
