### ISSUE TITLE
Template loading error after update

### ISSUE THREAD

**Issue by akdesign** [nystudio107/craft-seomatic#1161]
I'm getting the error below after the update of SEOmatic to version 3.4.33. CMS works fine if I disable the plugin.

Unable to find the template “twigfield/twigfield” in "seomatic/settings/_includes/fields/_seoTitle.twig" at line 19.

1. in /var/www/site/Craft-3.6.15/vendor/craftcms/cms/src/web/twig/TemplateLoader.php.                                at line 116
    */
    private function _resolveTemplate(string $name): string
    {
        $template = $this->view->resolveTemplate($name);
 
        if ($template !== false) {
            return $template;
        }
 
        throw new TemplateLoaderException($name, Craft::t('app', 'Unable to find the template “{template}”.', ['template' => $name]));
    }
]

**Comment by khalwat** [comment]
Please do `composer update` to ensure that the `nystudio107/craft-twigfield` package gets installed.

It is listed in the "require" section of the plugin's `composer.json`: https://github.com/nystudio107/craft-seomatic/blob/develop/composer.json#L38

**Comment by alanski66** [comment]
Ive got this error after running composer update and can verify that craft-twigfield package is in nystudio vendor directory. Rain stopped play :(

**Comment by alanski66** [comment]
Uninstalled and reinstalled and all ok now

**Comment by khalwat** [comment]
In general, I'd recommend doing updates via the CLI rather than the Craft CP GUI, if possible.

See this article:

https://nystudio107.com/blog/updating-craft-cms-without-headaches

**Comment by sg-modlab** [comment]
@khalwat FWIW I just did updates via CLI and am having this same issue. Did a composer update as suggested above and that didn't fix it. Looking at trying the composer uninstall and then install now.

**Comment by khalwat** [comment]
That's pretty odd... @sg-modlab lmk what you find.

**Comment by sg-modlab** [comment]
@khalwat I had the darnedest time with this one. Ended up having to SSH to to servers and first do a composer remove and then a composer require of SEOmatic to get things right. Not sure why so tricky for me.

**Comment by khalwat** [comment]
Related: https://github.com/nystudio107/craft-twigfield/issues/2

**Comment by khalwat** [comment]
I'm really sorry about this, we didn't catch it in local dev because it apparently rears its ugly head only right after first install/update.

Addressed in: https://github.com/nystudio107/craft-twigfield/commit/ba5a1044af3d49217f801d04316fd40626d991aa

Released as Twigfield 1.0.8: https://github.com/nystudio107/craft-twigfield/releases/tag/1.0.8

You should be able to do:

```
composer update nystudio107/craft-twigfield
```

...and it'll pull down the latest version of Twigfield (1.0.8 is the version with the fix in it). If for some reason it gets stubborn, you can do:

```
composer require nystudio107/craft-twigfield "^1.0.8"
```

**Comment by sg-modlab** [comment]
@khalwat Thanks. For those of us who reinstalled SEOMatic as recently as yesterday, is this updated needed or more for us moving forward and/or for other sites we'll update.

**Comment by khalwat** [comment]
@sg-modlab while it should work either way, I'd suggest updating.  it's a one-liner!

**Comment by khalwat** [comment]
Also if anyone in this thread can verify for me that the fix above works for you, I'd appreciate it!

**Comment by khalwat** [comment]
If you still have this issue, check to see if you see a line like this after doing `composer update nystudio107/craft-twigfield`:

```
Do you trust "yiisoft/yii2-composer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] 
```

If so, you need to update the `allow-plugins` in your `composer.json` as per:

https://github.com/craftcms/cms/issues/11500#issuecomment-1165688915

Also you should say `y` to the question it's asking, otherwise Twigfield can't be properly installed.

**Comment by sg-modlab** [comment]
Andrew, hope to do another update shortly and will test and confirm if someone else doesn’t sooner.

Yes, I did see this line.

•
Seth Giammanco (he/him)
Principal, Strategy & Technology
***@***.***
mod-lab.com

**Comment by akdesign** [comment]
Thank you, the composer update fix the issue.

**Comment by khalwat** [comment]
@sg-modlab You're going to need to do what is discussed here:

https://github.com/craftcms/cms/issues/11500#issuecomment-1165688915

After July 2022, Composer is going to enforce this, so you'll have to do it sooner or later anyway.

More discussion of this here:

https://github.com/craftcms/craft/pull/74

**Comment by jamie-jenks** [comment]
Just a FYI -

Ended up running around in circles trying to fix this. Tried adding the new composer.json line 
```

"config": {
    "allow-plugins": {
        "craftcms/plugin-installer": true,
        "yiisoft/yii2-composer": true
    },
}

```

Followed by a ```composer update```  and it still wasn't working.

Had to follow @sg-modlab  suggestion of removing then requiring SEOmatic to get this working again.

**Comment by khalwat** [comment]
@jamie-jenks welp, you're going to need that stuff added to the `composer.json` after July 2022 for Composer anyway so... there's that. :)

**Comment by cweiper** [comment]
@khalwat, I am just running into this same issue in the past few days. Any pages with the SEO field and the SEO plugin backend itself are erroring out in production with the following error from above:

[web.ERROR] [craft\web\twig\TemplateLoaderException] Unable to find the template “codeeditor/codeEditor” in "seomatic/settings/_includes/fields/_seoTitle.twig" at line 20

The past few days my resolution has been to just remove the vendor folder entirely and re-run composer install, but its very destructive. The reason it keeps becoming an issue is we deploy versions to our server and the problem keeps coming back, the only thing I can think of is the deploy resetting us back to some state that does not work.

My local repository does not have this issue either. Let me know if there is anything else I can add to help troubleshoot.

I am running on Craft 4.9.3 and SEOmatic 4.0.48

**Comment by khalwat** [comment]
@cweiper I'm pretty sure this is going to end up being a devops/deployment issue on your end somehow. It sounds like something is getting borked with the Composer package that is being installed.

I'm not aware of any issues with the SEOmatic package, so I'm guessing it is very likely to be something on your end that is causing it.

Given that you're not seeing in it local dev, I would focus on your deployments, and on your production server.
