### ISSUE TITLE
SEOmatic field settings showing override for sitemap images when only Sitemap Enabled is expected

### ISSUE THREAD

**Issue by mike-moreau** [nystudio107/craft-seomatic#1163]
### Describe the bug
I am using an Seomatic field type with "Sitemap Enabled" as the only checked configuration option in the “Sitemap” tab.

But options for sitemap image overrides are appearing also.

### To reproduce
Steps to reproduce the behaviour:
1. Add a seomatic field type
2. Configure with options for "Sitemap Enabled" only
3. Check appearance of field on an entry

### Expected behaviour
Expect to see only "Sitemap Enabled" as the option

### Versions
- Plugin version: 3.4.30
- Craft version: 3.7.42
<img width="558" alt="Screen Shot 2022-05-27 at 1 08 15 PM" src="https://user-images.githubusercontent.com/92817780/175538117-e4c50c7b-4f05-4a92-ae49-2878d223fbad.png">
<img width="603" alt="Screen Shot 2022-05-27 at 1 08 44 PM" src="https://user-images.githubusercontent.com/92817780/175538219-9c9484d5-3cab-4df6-977a-1ae477925b76.png">

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/56171ee8e567d4ac2a29af915526a3f0fc9a7094 & https://github.com/nystudio107/craft-seomatic/commit/14c42616de40bb2d30f2e3a64accfd74d2ca06c8

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.41”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.11”,
```
Then do a `composer clear-cache && composer update`
