### ISSUE TITLE
Robots/Humans button in CP links to 404 with multisite

### ISSUE THREAD

**Issue by modelesque** [nystudio107/craft-seomatic#1168]
### Describe the bug
We have 6 sites in our Craft install. Each site represents a language in a country. We have 3 countries, 2 languages per country. Every site has a locale segment in the URL; there's never just a `.com`. We have "Site Groups define logically separate sites" switched on in our SEOmatic plugin settings.

When I go to either the "Robots" or "Humans" settings pages in the CP and click the button to open up either document, I see a 404 because the URL includes the locale URI segment (`/de-de/robots.txt`, for example) when the files should be located at the root.

### To reproduce
Steps to reproduce the behaviour:
1. Switch on "Site Groups define logically separate sites" in the SEOmatic plugin settings.
2. Make sure Craft's primary Site has a locale at the end like `de-de`.
3. Go to either the "Humans" or "Robots" pages in SEOmatic's settings CP area.
4. Click the gray button at the top right that says "View robots.txt".
5. See the 404 page.

### Expected behaviour
The files should open up at the root.

### Versions
- Plugin version: 3.4.33
- Craft version: 3.7.45

**Comment by khalwat** [comment]
Addressed in: <https://github.com/nystudio107/craft-seomatic/commit/63c9f87460082c087da3c300a3146afc44f26f15> & <https://github.com/nystudio107/craft-seomatic/commit/506f8605818c68dbeea426bda47d3bf6a08bddb8>

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.36”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.6”,
```
Then do a `composer clear-cache && composer update`
