### ISSUE TITLE
Choosing field for SEO Keywords Source returns error

### ISSUE THREAD

**Issue by ryanirelan** [nystudio107/craft-seomatic#117]
`Argument 1 passed to nystudio107\seomatic\services\Helper::extractKeywords() must be of the type string, null given, called in /[redacted]/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1605`

Unable to access the Content SEO settings for that Section.

**Comment by khalwat** [comment]
What versions of Craft and SEOmatic are we working with here?

**Comment by khalwat** [comment]
Is it possible that you have no text fields at all in this Section?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/ef2a127d206a954c893eae117a4450c841d25df1
