### ISSUE TITLE
Calendar Event showing in Content SEO for site.

### ISSUE THREAD

**Issue by webrgp** [nystudio107/craft-seomatic#1170]
![Screen Shot 2022-06-29 at 3 20 17 PM](https://user-images.githubusercontent.com/994788/176536285-560d30f6-21be-438a-ad2d-4c8c6211a89f.png)

And when I try to configure it gives me the "Template not found: seomatic/edit-content/general/event/ccmnh-eventsIccmnh"

### Versions
- Plugin version: 4.0.5
- Craft version: 4.0.6
- Solspace Calendar: 4.0.0-beta.6

**Comment by khalwat** [comment]
I'm unable to replicate this using Solspace Calendar `4.0.0-beta.6` -- the URL does look strange to me though, what is the actual name of the calendar here? `ccmnh-eventsIccmnh` seems like it should be `ccmnh-events`, no? Not sure where the `Iccmnh` is coming from?

**Comment by webrgp** [comment]
Forgot to mention that it's in a multi-site setup, and I've mistyped.

`Template not found: seomatic/edit-content/general/event/ccmnh-events/ccmnh`
![ccmnh nitro_admin_seomatic_edit-content_general_event_ccmnh-events_ccmnh_site=ccmnh](https://user-images.githubusercontent.com/994788/176550029-4c69a25f-ddb1-484b-a661-5b937d04e2c2.png)

**Comment by khalwat** [comment]
...and is `ccmnh` the valid name of one of your sites?

**Comment by khalwat** [comment]
Also do you get 404's for _anything else_ in the Content SEO settings? Something isn't right here, it's as if the Yii2 router isn't picking up the route that SEOmatic registers properly, or the URL is malformed in some way.

Is there anything else that could be interfering with URL routing in the mix, in terms of server rewrites or other such things?

**Comment by webrgp** [comment]
Yes, it's one of the sites.
No, it only happens with the calendar events.

**Comment by khalwat** [comment]
aha -- I think I know what it is. It's the dash in the name, which doesn't match the `handle` route param

**Comment by khalwat** [comment]
So technically, they probably shouldn't be including characters like `-`'s in their handles but...

Addressed in: <https://github.com/nystudio107/craft-seomatic/commit/3b49d3db184347de207795874178ee21eb5d4468> & <https://github.com/nystudio107/craft-seomatic/commit/07c2856a5c054b91970bb11b1e67eb7d1a159702>

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.36”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.6”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Posted an issue for Solspace as well: https://github.com/solspace/craft-calendar/issues/147

**Comment by webrgp** [comment]
Thanks Andrew!
