### ISSUE TITLE
twitter:site and twitter:creator meta tags render with curly bracket at end of handle

### ISSUE THREAD

**Issue by jmauzyk** [nystudio107/craft-seomatic#1171]
### Describe the bug
Meta tags for `twitter:site` and `twitter:creator` are rendering with a curly bracket appended to the handle, e.g.
`<meta name="twitter:site" content="@myhandle}">`

Content SEO settings have Twitter Creator Source set to Same as Site Twitter Handle. I've confirmed the Twitter Handle does not have a curly bracket at the end as entered into Site Settings > Social Media.

### Versions
- Plugin version: 3.4.35
- Craft version: 3.7.46

**Comment by khalwat** [comment]
Addressed in: <https://github.com/nystudio107/craft-seomatic/commit/c3c0717e15e1cb0678c24e1949fc04ca67d0e830> & <https://github.com/nystudio107/craft-seomatic/commit/d39b37b1cfec19128298210a8ff38520ab840b80>

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.36”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.6”,
```
Then do a `composer clear-cache && composer update`
