### ISSUE TITLE
Licensing issue with the SEOmatic - Prod vs Develop

### ISSUE THREAD

**Issue by quickstar** [nystudio107/craft-seomatic#1173]
Hi everyone

What is the recommended approach to deal with the license for a prod/dev scenario? I always get a notification `There’s a licensing issue with the SEOmatic plugin.` Which for sure is true, since the lic is bound to our production environment.

Since our project.yaml is tracked in git, also the `licenseKey` is checked in to source control. Other plugins are allowing the usage of environment variables for such scenarios. Unfortunately I was not able to get this to work for SEOmatic. Any recommendation?

**Comment by khalwat** [comment]
Pixel & Tonic, the creators of Craft CMS are the ones that handle plugin licensing, this isn't something that plugin developers are able to manage.

So I'd suggest emailing support@CraftCMS.com with your inquiry.

SEOmatic isn't any different from other plugins in this regard.
