### ISSUE TITLE
SEO preview overlays product sidebar in Craft Commerce

### ISSUE THREAD

**Issue by aarmitage** [nystudio107/craft-seomatic#1174]
The SEO preview overlays the sidebar when scrolling on a product entry page in Craft Commerce.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Commerce > Products
2. Choose a product entry and scroll
3. SEO preview overlays the entry sidebar as it scrolls with the content in the entry, and isn't fixed below the existing sidebar entry options.

### Expected behaviour
The SEO preview should be fixed below the sidebar entry options and appear on scroll to the bottom of the product entry page.

### Screenshots
[https://vimeo.com/726663056/9b70fe8d77](https://vimeo.com/726663056/9b70fe8d77)

### Versions
- Plugin version: 3.4.30
- Craft version: Craft CMS 3.7.43 + Commerce 3.4.15

**Comment by khalwat** [comment]
This is very likely an issue with Commerce -- I've seen this before when the HTML wasn't properly formed. 

ref: https://github.com/craftcms/commerce/issues/1376

**Comment by aarmitage** [comment]
Thanks for linking in the original issue @khalwat.
