### ISSUE TITLE
Transform mode (fit) gives correct preview (but wrong expected result)

### ISSUE THREAD

**Issue by JeanLucEsser** [nystudio107/craft-seomatic#1176]
### Describe the bug
I think this capture will explain the issue better than I could with words.

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/14908712/177343293-1eeddcba-e37c-4c53-a0b9-75a982c4f7d0.png">

As you can see from the inspector, the fit transform is correctly applied, the source image is correct. The issue is with the preview where the div background covers the available space where it should fit. It probably emulates how Twitter will render it, but if we're given the option for `Fit` shouldn't we expect the system to generate an image where the original fits inside some white (or black) filling?

BTW, related to the transform option, why isn't there a `Same as SEO...` for the `Twitter Image Transform Mode` (and Facebook fwiw)? When overriding, the SEO override applies to both Twitter and Facebook so it would make sense to be able to have the `Same as...` option in the settings.

**Comment by JeanLucEsser** [comment]
Closing the issue because:

The plugin uses Craft's fit, which does not fill empty space to respect an aspect ratio. So in our case, the social media platform will crop our fitted image anyway, hence rendering the option irrelevant. There won't be any difference between doing the crop on our side or letting the social media platform do it on their side. The end result will look the same.

The preview correctly emulates what the end result will be.

**Comment by bossanova808** [comment]
So yeah the preview (sort of) matches what e.g. Facebook will actually do.

But this isn't really a solution to the problem - that is, is there a solution to use an existing image and some sort of transform that _will_ produce an image that is _actually_ fitted to the bounds?  Or are we stuck at the point of having to make images that are social media friendly with padding etc. (which goes against the general magic of using the existing content for SEO purposes...)

**Comment by khalwat** [comment]
@bossanova808 the preview should be showing you what will be displayed on the social media platform. It uses the same CSS for the image preview that the social media sites use.

**Comment by bossanova808** [comment]
Yep it's close, not exactly the same as what I see when I actaually share on FB, but within cooee, as they say down here.

But the other question remains - is there actually a way to achieve what everybody else in the universe understands as 'fit image' vs. the Craft thing here (which is really a version of crop)...because otherwise, once can't really use existing images for these SEO things as they're basically always cropped.

**Comment by khalwat** [comment]
That'd be a great question for P&T... I think I recall they might have added a new letterbox transform recently?

**Comment by bossanova808** [comment]
Lol, fair call on the handball there!  I'll go looking!

**Comment by bossanova808** [comment]
Ok yep it's there, in 4.4 - but you'd need to add it here for it to be usable in this context, I think?

![image](https://github.com/nystudio107/craft-seomatic/assets/731309/7981a44e-ba5c-4974-bc8c-82f1a826d64d)
