### ISSUE TITLE
URGENT: Entry pages won't load after SEOMATIC upgrade

### ISSUE THREAD

**Issue by mediagirl** [nystudio107/craft-seomatic#1178]
### Describe the bug
I updated Craft and SEOmatic to the latest versions and am unable to load any entry pages in the control panel. Everything else is working correctly from what I can tell. The error when trying to load an entry page is: 

`Unable to find the template “twigfield/twigfield” in "seomatic/settings/_includes/fields/_seoTitle.twig" at line 19`

### To reproduce
Steps to reproduce the behaviour:
1. Attempt to visit any entry page
2. See error message: **Unable to find the template “twigfield/twigfield” in "seomatic/settings/_includes/fields/_seoTitle.twig" at line 19.**

### Expected behaviour
I expect the entry page to load.

### Versions
SEOmatic 3.4.36 
Craft CMS 3.7.47.1

**Comment by mrwijsman** [comment]
Same here

**Comment by khalwat** [comment]
Please see: https://github.com/nystudio107/craft-twigfield/issues/2

For a solution/fix

**Comment by russback** [comment]
@khalwat I'm seeing this issue on our staging server. It's fine locally.

I've run `composer update` and even used composer to remove and then require seomatic on the staging server, but I still get the issue.

yii2-composer is allowed (see below).

Any suggestions?

```
{
  "require": {
    "codemonauts/craft-readonly-field": "1.0.2",
    "craftcms/cms": "3.7.61",
    "craftcms/feed-me": "4.5.3",
    "craftcms/redactor": "2.10.10",
    "doublesecretagency/craft-inventory": "2.1.1",
    "enupal/stripe": "4.0.10",
    "flipboxfactory/saml-idp": "1.3.8",
    "masugadesign/labreports": "1.0.0",
    "mmikkel/cp-field-inspect": "^1.4",
    "nystudio107/craft-seomatic": "3.4.44",
    "putyourlightson/craft-elements-panel": "^1.1",
    "putyourlightson/craft-log-to-file": "^1.2",
    "spatie/craft-ray": "^1.1",
    "spicyweb/craft-quick-field": "^1.0",
    "verbb/navigation": "1.4.31",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "nystudio107/craft-autocomplete": "^1.10",
    "roave/security-advisories": "dev-latest",
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
			"modules\\": "modules/",
			"bsccp\\": "modules/bsccp"
    }
  },
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true,
      "treeware/plant": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.4"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}

```

**Comment by khalwat** [comment]
@russback Not sure, but you could try removing vendor entirely:

```
rm -rf vendor/
```

...and then doing a composer install from scratch:

```
composer install
```

**Comment by russback** [comment]
That worked - thanks.
