### ISSUE TITLE
Sitemap is generating links starting with @web/@web instead of the domain

### ISSUE THREAD

**Issue by brycekirk** [nystudio107/craft-seomatic#1179]
### Describe the bug
Sitemap is generating links starting with `@web/@web` instead of the domain. If I force a re-gen by going to Plugin Settings > Sitemaps > Turn everything off > Save > Turn everything on > Save, the sitemap it regenerates is correct. But then at some point, the sitemap reverts back to the `@web/@web` issue.

### Versions
- Plugin version: 3.4.36
- Craft version: Craft Pro 3.7.47

**Comment by khalwat** [comment]
This is going to very likely be some kind of a config setup issue -- please ensure that your `@web` alias is properly defined in your `config/general.php` file

**Comment by brycekirk** [comment]
It is set correctly, and all other elements using `@web` are working as expected. It doesn't make any sense...when I regenerate the sitemap, it looks good. And then in a few days, it's reset all the URLs back to `@web/@web`

**Comment by khalwat** [comment]
Do you have multiple sites on the same VPS? If so, do they have separately configured cache prefixes?

**Comment by brycekirk** [comment]
I'm not sure if there are multiple sites. I don't believe so? The host is fortrabbit / standard.

**Comment by khalwat** [comment]
So all SEOmatic does is ask Craft what the site URL should be for a given URL.

I can only presume that sometimes, somehow, this is not set properly in your environment. I have not heard of any other reports of this, so I'm assuming it's something specific to this site/environment.

**Comment by brycekirk** [comment]
Fair enough. I'll keep digging. Appreciate the prompt responses.
