### ISSUE TITLE
Ampersand appearing as &amp;

### ISSUE THREAD

**Issue by j-greig** [nystudio107/craft-seomatic#118]
Category name of Learning & Enterprise is displayed as Learning &amp; Enterprise in the SEO preview.

**Comment by khalwat** [comment]
Can you show me a screenshot just so I can see exactly what this is looking like for you?

**Comment by j-greig** [comment]
![preview](https://user-images.githubusercontent.com/616194/40322080-16238bfc-5d29-11e8-9b30-88aff12e8281.png)

You know what I think it renders fine on Twitter/Facebook, you only see the ampersand in the sidebar preview!

**Comment by j-greig** [comment]
![screen shot 2018-05-21 at 19 01 44](https://user-images.githubusercontent.com/616194/40322175-71dd4af0-5d29-11e8-858f-3d7d8c9f5ecd.png)

**Comment by khalwat** [comment]
Sorry, can you show me a screenshot of where it does _not_ look like you're expecting it to? That screenshot above seems right to me with the SEO Preview?

**Comment by khalwat** [comment]
Oh I see, you're talking about in the description below, not in the title. I missed that.

**Comment by khalwat** [comment]
So I'm not seeing this behavior here:

![google chromescreensnapz1185](https://user-images.githubusercontent.com/7570798/40325116-986d9d44-5d08-11e8-921f-c15306201d3e.png)

I think it's possible that the `&` in this case is already encoded as `&amp;` perhaps in whatever source you're pulling it from?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/ef416e7ab58407c439837f2c20a52de671d24be7

**Comment by liquidcomau** [comment]
We're having a similar issue with our site guys, see here:
https://www.liquid.com.au/insights/be-netflix-not-blockbuster-how-to-evolve-in-a-volatile-property-market

Output:

<meta content="https://www.liquid.com.au/index.php?p=actions/assets/generate-transform&amp;transformId=62" property="og:image">

Fails to generate the image.

**Comment by khalwat** [comment]
Looks to me like there is an issue with your image transforms on your server?

https://www.liquid.com.au/index.php?p=actions/assets/generate-transform&amp;transformId=77
