### ISSUE TITLE
Can we have all language site urls in the sitemap?

### ISSUE THREAD

**Issue by parthi-me** [nystudio107/craft-seomatic#1180]
### Question
Can we have all language site URLs in the sitemap?
Our SEO agency recommends the following,
_We need an individual sitemap for each country. We need only one sitemap, with all the URLs in it (all language URLs) for countries with different languages._

Currently, each language sitemap is accessed separately. Can we have a single sitemap for a site group?

### Additional context
We have a multisite with multi-languages. We have site groups that are used to combine language sites.
for example: 
site group 1:
    site1.com
    site1.com /fr/
Site group 2: 
    site2.com 
    site2.com/de

**Comment by khalwat** [comment]
SEOmatic already handles this via `hreflang` links in the sitemap (which is the best practice according to Google):

https://developers.google.com/search/docs/advanced/crawling/localized-versions

Putting all languages in one sitemap is a bad practice, and would not allow Google to easily understand what pages are associated with what languages / regions.

**Comment by parthi-me** [comment]
@khalwat https://developers.google.com/search/docs/advanced/crawling/localized-versions#example_2
- Check the above section of the sitemap example. Which says the translated pages are listed on the same sitemap. Which doesn't happen with SEOmatic. Let me know if any settings that I missed to update. :)

**Comment by khalwat** [comment]
SEOmatic will do that exactly that, you just need to have the set groups set up appropriately:

https://nystudio107.com/docs/seomatic/technologies.html#multi-site-language-locale-support

...or turn off the **Site Groups define logically separate sites** setting

**Comment by bmilagre** [comment]
This question is somehow similar to mine, so I am writing this here.

We have several multisites with multi-languages. Each multisite is separated in a group. Due to the many xml files it would generate per multisite, we come over the limit of 500 sitemap indexes thats allowed in the Search Console.

Is there a possibility to merge e.g. all entry categories of the multisites and output them as one sitemap?

**Comment by khalwat** [comment]
Currently there is no way to do that @bmilagre

**Comment by bmilagre** [comment]
@khalwat Do you think there will be ever a possibility to support these cases?

As a temporary solution do you think it could work if we disable the default sitemap and add our own custom sitemap. Would that still support the build in support of Regenerate Sitemaps Automatically or Submit Sitemap Changes ?

**Comment by khalwat** [comment]
@bmilagre It's possible, but it's a bit of an edge case. Your idea of disabling the sitemaps and using your own should work, if you do it through the hooks SEOmatic provides:

https://nystudio107.com/docs/seomatic/advanced.html#registersitemapsevent
