### ISSUE TITLE
Auto decoding URLs?

### ISSUE THREAD

**Issue by emilyo-cogapp** [nystudio107/craft-seomatic#1181]
Hello I am trying to set an SEO image value in a template using `do`, but the URL contains an encoded `%2F` which is needed in order for the URL to be valid but seomatic seems to be converting it to a `/` which then 404s the image.

It does seem to be seomatic doing this as when I dump out the variable I'm passing, it's correct. I'm just wondering if you could advise on a way to stop this from happening? Full code snippet below, but let me know if you need any more info.

Thanks!

### Additional context
```
{% set seoImage = entry.worksPrimaryImage.one() %}
{% set seoImageUrl = seoImage.getIIIFUrl() ~ '/full/800,/0/default.png' %}
{% do seomatic.meta.seoImage(seoImageUrl | raw)
  .ogImage(seoImageUrl | raw)
  .twitterImage(seoImageUrl | raw)
%}
```

**Comment by khalwat** [comment]
That's odd that a URL needs an encoded character to be valid? That seems like a server-side issue that shouldn't be, but in any event... you could try encoding the entire URL before passing it into SEOmatic, it should only decode it once.

**Comment by emilyo-cogapp** [comment]
@khalwat Yes it's annoying. We're working with a IIIF server and the IIIF protocol is defined as `/filepath/crop/size/rotation/format` but we also have a subdirectory so the `/` for that subdirectory needs to be encoded in order for IIIF to not think it's the beginning of the 'crop' portion of the URL (definitely not a great system!)

Anyway, that suggestion worked great. Thank you!

**Comment by ammonhaggerty** [comment]
Reviving this old thread. I'm having this exact same issue. In my case, I'm working with images Firebase. For some stupid reason they also use %2F in their URL path, which breaks if turned into a leading slash.  

Here's an example (you can see the two following "COMMUNITY"):
https://firebasestorage.googleapis.com/v0/b/groupy-203e1.appspot.com/o/COMMUNITY%2F2023404%2F56278947.png?alt=media

If you convert those to "/" the image path breaks. URL encoding the entire path also doesn't work. Is there any way to prevent SEOmatic from decoding? 

BTW, here's the rationale why, which doesn't make it any less frustrating: https://stackoverflow.com/questions/66761317/why-the-slashes-in-the-url-of-my-cloud-storage-need-to-be-encoded-as-2f

**Comment by khalwat** [comment]
@ammonhaggerty did you try what was mentioned above, encoding the entire URL before passing it into SEOmatic?
