### ISSUE TITLE
Include GTM on staging

### ISSUE THREAD

**Issue by dansiberry** [nystudio107/craft-seomatic#1182]
Hi , 
I've included the code to force GTM to render regardless of the environment: 
 {% do seomatic.script.get('googleTagManager').include(true) %}
I added it as the top of master layout template
However, it's still not rendering on staging. Any idea why this might be? 
Thanks

**Comment by khalwat** [comment]
It's possible you need to include the container itself, too:

```twig
{% do seomatic.script.container().include(true) %}
{% do seomatic.script.get('googleTagManager').include(true) %}
```

Also, did you clear caches? https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting

**Comment by dansiberry** [comment]
Thanks for your help! In the end it was the cache

**Comment by khalwat** [comment]
I recommend clearing all caches on deploy, for exactly situations like this: https://craftcms.stackexchange.com/a/39557/819
