### ISSUE TITLE
SiteNavigationElement schema for JsonLd apperas only in a single variant

### ISSUE THREAD

**Issue by Romanavr** [nystudio107/craft-seomatic#1183]
### Question
I am trying to make JsonLd schema for "@type": "SiteNavigationElement"
It should look something like this:
```
{
	"@context": "https://schema.org",
	"@graph": 
	[
      {
          "@context": "https://schema.org",
          "@type":"SiteNavigationElement",
          "@id":"#table-of-contents",
          "name": "Section 1",
          "url": "https://www.example.com/page#toc-1"
      },
      {
          "@context": "https://schema.org",
          "@type":"SiteNavigationElement",
          "@id":"#table-of-contents",
          "name": "Section 2",
          "url": "https://www.example.com/page#toc-2"
      },
      ....
```
But I ran into a problem with the fact that I always have only 1 element of type "SiteNavigationElement"
My code looks something like this:
```
{% for node in nodes %}
        {% do seomatic.jsonLd.create({
            'type': 'SiteNavigationElement',
            'name': node.title,
            'url': node.url
        }, true) %}
{% endfor %}
{% do seomatic.jsonLd.render(SiteNavigatioJsonLd) %}
```
If I debug the array itself with nav.elements, then everything is OK, all the elements are there.
But at the moment of rendering, there is always only 1 left.
I dug a little into the sources of SEOmatic, especially work of MetaContainers, and I assume that this is due to the fact that the schema type is used as a key in the array and overwrites value in array.
Or maybe I'm just doing something completely wrong?

**Comment by khalwat** [comment]
So you need to add a `key` -- I think this isn't well documented, so it's my fault not yours. Something like:

```twig
{% for node in nodes %}
        {% do seomatic.jsonLd.create({
            'key': 'nav-' ~ node.title,
            'type': 'SiteNavigationElement',
            'name': node.title,
            'url': node.url
        }, true) %}
{% endfor %}
```

If no `key` is provided, SEOmatic uses the `type` for the key, which would cause it to overwrite each time you add a new one: https://github.com/nystudio107/craft-seomatic/blob/develop/src/models/MetaJsonLdContainer.php#L151

**Comment by Romanavr** [comment]
@khalwat I should have noticed this earlier while digging through the code.
Please add this to your documentation, it will save someone hours of life.
Many thanks for the help! 🤟 ✌️
