### ISSUE TITLE
devMode not overriding Environment setting

### ISSUE THREAD

**Issue by jmauzyk** [nystudio107/craft-seomatic#1186]
### Describe the bug
The `devMode` config setting isn't overriding the **Environment** SEOmatic plugin setting. With `devMode` set to `true` and the environment set to `live`, it displays the message below in Tracking Scripts and renders tracking scripts on the front end.

### To reproduce
Steps to reproduce the behaviour:
1. Enable `devMode`.
2. Set environment to `live` under Plugin Settings.
3. Navigate to Tracking Scripts settings. The message below displays.
4. Load a page on the front end and inspect the source. The Google Tag Manager script or similar will be rendered.

### Expected behaviour
Should override environment setting, display correct environment name, disable tracking scripts and robots.

### Screenshots
<img width="1162" alt="Screen Shot 2022-07-15 at 4 03 42 PM" src="https://user-images.githubusercontent.com/21298596/179322739-b4ca3781-8073-497d-9195-04c3745d33e8.png">

### Versions
- Plugin version: 3.4.36
- Craft version: 3.7.48

**Comment by khalwat** [comment]
If you manually set the SEOmatic environment, SEOmatic will respect that, regardless of the `devMode` setting:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/Environment.php#L74

This is working as intended.

If you let SEOmatic determine the environment automatically, based on the `ENVIRONMENT` variable, then it will override what it determines automatically if `devMode` is set.

**Comment by jmauzyk** [comment]
The Environment setting instructions read

> The server environment, either `live`, `staging`, or `local`. If `devMode` is on, SEOmatic will override this setting to `local` Development.

This coincides with how I remember this setting working previously. I take it this behavior has changed? If so, the instructions should be updated to reflect the fact that `devMode` no longer overrides this setting.

Additionally, the warning pictured reads

> The `live` SEOmatic Environment setting has been overriden to `live`, because the `devMode` config setting is enabled. Tracking scripts are disabled, and the `robots` tag is set to `none` to prevent search engine indexing.

This is also confusing if the behavior has changed, because in this case `devMode` has nothing to do with the `live` setting, nor are tracking scripts being disabled or `robots` set to `none`.

**Comment by khalwat** [comment]
So the documentation is still correct; but what has changed is that you can manually specify the environment that you want as well.

If you do manually override it, rather than letting SEOmatic determine it for you based on the `ENVIRONMENT` env var, we assume you want it set to that environment regardless of anything else (`devMode` included).

I agree that the display in your particular case is not correct, it shouldn't say anything about `devMode` if you have manually set the environment.

**Comment by jmauzyk** [comment]
Based on what you're describing, I think the documentation is incorrect in how it is displayed, or at least confusing.

<img width="874" alt="Screen Shot 2022-07-21 at 10 45 34 AM" src="https://user-images.githubusercontent.com/21298596/180269316-5bd37e9c-32fe-4266-b5b2-012c6323414d.png">

The note "If `devMode` is on, SEOmatic will override this setting to `local` Development" appears directly above the **Environment** field. However, based on what you're saying, any environment designated in that field will be applied regardless of `devMode` or anything else. So shouldn't that note be moved up to the instructions for the **Manually Set SEOmatic Environment** lightswitch?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/0d18e6b5b851d79a4e3740d755c9f1518c965775 & https://github.com/nystudio107/craft-seomatic/commit/4483b0f689d67b676c88bce7644d7c02289c4166

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.37”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.7”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
> The note "If `devMode` is on, SEOmatic will override this setting to `local` Development" appears directly above the **Environment** field. However, based on what you're saying, any environment designated in that field will be applied regardless of `devMode` or anything else. So shouldn't that note be moved up to the instructions for the **Manually Set SEOmatic Environment** lightswitch?

You're right, it should. I will address that as well. Thank you!
