### ISSUE TITLE
seomatic 500 errors

### ISSUE THREAD

**Issue by Mseye1956** [nystudio107/craft-seomatic#1187]
### Question
500 errors in control panel in different settings sections eg
GET /admin/seomatic/global/general/default HTTP/1.0
GET /admin/seomatic/edit-content/general/section/pages/default HTTP/1.0
GET /admin/seomatic/tracking/gtag/default HTTP/1.0

### Additional context
Meta is showing on front end but sitemaps not working

**Comment by khalwat** [comment]
Can you please provide:

The version of SEOmatic

The version of Craft CMS

Any logs of these errors from your `web.log` file?

**Comment by Mseye1956** [comment]
Hi Andrew,
Thanks for reply it is OK now after reinstalling. Kind regards Martin



On 18 Jul 2022, 17:58, at 17:58, Andrew Welch ***@***.***> wrote:
>Can you please provide:
>
>The version of SEOmatic
>
>The version of Craft CMS
>
>Any logs of these errors from your `web.log` file?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nystudio107/craft-seomatic/issues/1187#issuecomment-1187759994
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>
