### ISSUE TITLE
SEOmatic gives an internal server error when trying to open an entry.

### ISSUE THREAD

**Issue by dynamicdreamz1** [nystudio107/craft-seomatic#1188]
unable to edit pages on the website - get internal server error [Siena Internal Server Error.jpg](https://prnt.sc/Lin0007fQynU)

### Versions
- Plugin version: 3.4.36
- Craft version: 3.7.48

**Comment by seamofreality** [comment]
Experiencing the same, unfortunately. 

- SEOmatic 3.4.36
- Craft Pro 3.7.48

> Twig Template Loading Error – craft\web\twig\TemplateLoaderException
Unable to find the template “twigfield/twigfield” in "seomatic/settings/_includes/fields/_seoTitle.twig" at line 19.

I updated SEOmatic, some other plugins and possibly Craft CMS via the "Update all" button in the backend. Afterwards the error occurred.

After manually requiring the package `nystudio107/craft-twigfield` (it was a change described in your changelog) via `composer require nystudio107/craft-twigfield` in the console the error went away.

**Comment by khalwat** [comment]
Please see this issue for a resolution:

https://github.com/nystudio107/craft-twigfield/issues/2
