### ISSUE TITLE
"Internal Server Error" when attempting to access Global SEO or Tracking Scripts section via Control Panel

### ISSUE THREAD

**Issue by edhebert** [nystudio107/craft-seomatic#1189]
Attempting to access the "Global SEO" or "Tracking Scripts" sections of SEOMatic via the Control Panel returns an "Internal Server Error" message.

Craft CMS 3.7.47.1
SEOmatic 3.4.36

In web.log "2022-07-19 11:41:40 [-][391][c2b2cb4a381f63731f39fa03492f0727][error][craft\web\twig\TemplateLoaderException] craft\web\twig\TemplateLoaderException: Unable to find the template “twigfield/twigfield” in "seomatic/settings/_includes/fields/_seoTitle.twig" at line 19. in /home/taptiteo/craft/vendor/craftcms/cms/src/web/twig/TemplateLoader.php:116"

**Comment by khalwat** [comment]
Please see the resolution here: 

https://github.com/nystudio107/craft-twigfield/issues/2

**Comment by edhebert** [comment]
Unfortunately, negative. Still getting the error. Tried both suggestions for composer update `composer update nystudio107/craft-twigfield` and `composer require nystudio107/craft-twigfield "^1.0.8"` Did not get the 'allow-plugins' message.

![image](https://user-images.githubusercontent.com/1420609/179843636-df1d02b2-716f-4aab-a08d-c04d833630aa.png)

![image](https://user-images.githubusercontent.com/1420609/179844382-71d01e93-a144-426f-8536-d39a1e60d48a.png)

**Comment by khalwat** [comment]
Please ensure that you do add the items to `allow-plugins` that the linked to issue states. It should look like this in your `composer.json`:

```json
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true
    },
    "optimize-autoloader": true
  },
```

**Comment by edhebert** [comment]
It's in there.

```
   "config": {
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "7.4"
        },
        "allow-plugins": {
            "craftcms/plugin-installer": true,
            "yiisoft/yii2-composer": true
        }
    },
```

**Comment by khalwat** [comment]
@edhebert delete the `vendor/nystudio107/craft-seomatic` and `vendor/nystudio107/craft-twigfield` directories, and re-install with `composer install`

Also, you might want to check to ensure you're running Composer 2.x

**Comment by edhebert** [comment]
Success - Thank you!
