### ISSUE TITLE
How to show the seo image in a template?

### ISSUE THREAD

**Issue by shifuma** [nystudio107/craft-seomatic#1196]
### Question
I'm trying to output the SEO image for an entry. I've overridden the image for this entry via a field called `seo`.

From the docs, I thought `{{ entry.seo.metaGlobalVars.seoImage }}` would do it, but I get back `{{ seomatic.helper.socialTransform(8674, "base", 0, "crop") }}`. How can I get the URL of that image?

**Comment by shifuma** [comment]
And straight after I open this issue, I find the answer: `{{ entry.seo.metaGlobalVars.parsedValue('seoImage') }}`

Thanks for playing rubber duck with me today 😁

**Comment by khalwat** [comment]
Glad you got it sorted!
