### ISSUE TITLE
Google Site Manager reporting 'Unbound XML namespace prefix.' for one section's sitemap

### ISSUE THREAD

**Issue by stevehurst** [nystudio107/craft-seomatic#1197]
### Question
Our client is reporting that one of our section's sitemaps is reporting a 'Unbound XML namespace prefix' error, and not indexing pages within. The settings for this section are the same as every other section. We've tried removing and re-adding the sitemap to Google and get the same error. Any ideas? The website is https://kalypso.com and the sitemap in question is https://kalypso.com/sitemaps-1-section-people-1-sitemap.xml

### Additional context
We're running Craft 3.7.47.1 and SEOmatic 3.4.36

<img width="1206" alt="Screen Shot 2022-08-17 at 9 14 09 AM" src="https://user-images.githubusercontent.com/20077/185157680-a9374736-4a66-499b-84be-cdc2237ade2a.png">
<img width="1212" alt="Screen Shot 2022-08-17 at 9 14 23 AM" src="https://user-images.githubusercontent.com/20077/185157808-e38e735b-953d-41fc-ba04-6e1b7aeb9831.png">

**Comment by khalwat** [comment]
Seems like it is OK to me? https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=https%3A%2F%2Fkalypso.com%2Fsitemaps-1-section-people-1-sitemap.xml&submit=Validate+Sitemap

**Comment by khalwat** [comment]
Will re-open if more information is provided
