### ISSUE TITLE
Facebook image is not using eager loaded image

### ISSUE THREAD

**Issue by samuel-clara** [nystudio107/craft-seomatic#1198]
When setting SEO Image Source for a specific entry to {{ seomatic.helper.socialTransform(entry.heroAsset[0], "base", 3, "crop") }}, to use an eager loaded asset, I receive a recommendation from "Blitz Recommendations" plugin to eager load this asset.

I noticed that doing so instead of accessing SEO image from Asset field is solving the eager loading issue for the ld-json part but not for the facebook OpenGraph tags ("Facebook OpenGraph Image Source" is set on "same as SEO image"). I presume this because if I set "Facebook OpenGraph Image Source" to "custom url" the Blitz recommendation does not appear.

I've tried even to set the same value in the facebook tab but the problem persists.

Not sure if it is a Seomatic issue, a Blitz Recommendations issue or if I'm doing something wrong

**Comment by khalwat** [comment]
If you are setting that manually in that way, you will need to also copy & paste that custom code to the Twitter Image and OpenGraph Image settings as well.

**Comment by samuel-clara** [comment]
I've tried this but the Blitz recommendation is still there.

If I don't set it manually, which I would prefer the SEO images are not eager loaded by default, right?

**Comment by khalwat** [comment]
Correct if they are set to a specific asset -- they are done via a separate query, I'm not really sure how they could be eager loaded in a manner that would make any difference in terms of performance.

For that to work, they'd have to somehow be combined with the `entry` query or such, but they are completely disconnected.
