### ISSUE TITLE
Sitemap disappeared

### ISSUE THREAD

**Issue by alexisAkenza** [nystudio107/craft-seomatic#1199]
Hello,

We have been using SEOmatic for about one year now. Until recently, we used the plugin's default settings to create the Sitemap of our website.

We just saw that our Sitemap is now missing from our website: https://akenza.io/sitemaps-1-sitemap.xml

I am not sure what generated this issue, as I don't recall making any changes to SEOmatic recently.

Could you help me solve this problem?
Thank you.

**Comment by khalwat** [comment]
I just loaded that URL, and the sitemap is there...?

Also, please make sure you update to the latest version of SEOmatic.
