### ISSUE TITLE
Unparsable structured data -  Parsing error: Missing ',' or '}'

### ISSUE THREAD

**Issue by BluestormDigital** [nystudio107/craft-seomatic#1201]
There are issues of parsing error with it missing either ',' or '}' within the <script type="application/ld+json"> code of the SEOMatic Plugin on a client's website as detailed by Google Search Console. I would like to know if this is a known issue and if there is a fix that can be implemented through the plug in?

We are currently using 

SEOmatic version: 3.4.37
Craft version: Craft Pro 3.7.52

**Comment by khalwat** [comment]
This is not a known issue with the plugin.

I would need to see details to attempt to assist you in diagnosing it; give me the live URL to the page that it is claiming has an issue?

**Comment by khalwat** [comment]
Will re-open if more information is provided.

**Comment by andrewmenich** [comment]
Just dropping a note for others that stumble upon this. If you're getting this error using Google's Rich Results Test, make sure there aren't any new lines before or after your JSON.
