### ISSUE TITLE
Detect titleSource on an entry

### ISSUE THREAD

**Issue by ambidustrious** [nystudio107/craft-seomatic#1202]
I would like to suppress the global site name in a title if a custom title was used on the entry.seoMatic title field.

This: 
Custom Title

Not this:
Custom Title | Site Name

Is there a way to accomplish this?

**Comment by khalwat** [comment]
Yes, you can do that by changing the **Site Name Position** in your SEO Settings field.

In general, I recommend against using SEO Settings fields, however, and probably you should be setting this in Content SEO as per: https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade
