### ISSUE TITLE
SEOmatic generates incorrect meta tags when query string is added

### ISSUE THREAD

**Issue by tur-ner** [nystudio107/craft-seomatic#1203]
### Describe the bug
When there is no query string in the URL, SEOmatic correctly generates the meta tags for facebook links. It uses the values provided by the SEO field. However, for certain entries when a query string is provided, it uses the default/global values for the meta tags. The query strings do not interact with SEOmatic and are isolated from any craft functionality. We tried to clear the front-end template caches for SEOmatic however it did not work. 

The list of entries that get incorrectly generated meta tags is seemingly arbitrary. There is no defining difference between an entry that works and one that is broken. The only consistent factor is the query string.

### Expected behaviour
SEOmatic would generate the same values for all possible query strings. 

### Versions
- Plugin version: 3.4.25
- Craft version: 3.7.46

**Comment by khalwat** [comment]
Can you provide me with an example that does not work, and provide the expected result as well as the actual result?

**Comment by khalwat** [comment]
Also, you are running an older version of SEOmatic. I would suggest updating to the latest, which is currently [3.4.37](https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.37)

**Comment by tur-ner** [comment]
> Can you provide me with an example that does not work, and provide the expected result as well as the actual result?

Here is an entry that works fine: https://www.departures.com/travel/mexico-city-guide-best-shopping-style-art-design
And here is it not working: https://www.departures.com/arts/mexico-city-guide-best-shopping-style-art-design?extlink=sm-dp-socialshare-fb-o

**Comment by khalwat** [comment]
So after looking at the source for that page for a bit, I have a couple of notes:

* Probably you should leverage SEOmatic for the custom JSON-LD you're generating; that'd unify it with the JSON-LD it already generates, and get it out of the head. There are a bunch of examples of doing this here: https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

* Unless you really want to manually override things on a per-entry basis, typically it's best to not use an SEO Settings field, and rather pull the SEO information from existing entry data, as described in the **Meta Cascade** section here: https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

* It appears that you have some kind of static caching involved that is causing the page output to look like this:

```html
<meta content="https://www.departures.com/actions/assets/generate-transform?transformId=30755" property="og:image">
```

(this is from the page where you're saying it works properly) -- this is what Craft generates if an image transform has been requested, but it's still pending generation.

So if I had to guess, something is going on with the caching layer that you have on the website. The only thing that could cause SEOmatic to not generate an `og:image` tag is if somehow the values passed into it are empty.

I suspect something more is going on here than an outright bug or issue in SEOmatic. Happy to help you track it down if I can, though.
