### ISSUE TITLE
Site URL Override not overriding OG:URL or LD+JSON

### ISSUE THREAD

**Issue by justenh** [nystudio107/craft-seomatic#1205]
Setting the "Site URL Override" does not update the URL used in the site's OG link, Schema data, or canonical link.

We are deploying our site to a non-standard environment and need to be able to have all URLs point to a different domain than the one configured as `PRIMARY_SITE_URL` within the `.env` file.

We've setup an env var,`SEOMATIC_URL`, and set that within SEOMatic's Advanced tab (SEOMatic > Plugin Settings > Advanced). However, the URL seems to be used in the Sitemap.xml generation, and other areas, but not in the OG link, schema data, or canonical link.

Below is an example of the code generated by SEOMatic when the `PRIMARY_SITE_URL=https://primarysiteurl.com` and the `SEOMATIC_URL=https://seomaticurl.com`... You can see where `Humans.txt` is correct, but `og:url` is incorrect. Additionally, it seems like the entire LD+JSON snippet that SEOMatic renders at the bottom of the page is incorrect.

**META Tags (using a sub-page as an example)**
```
<meta name="robots" content="none">
<meta content="en_US" property="og:locale">
<meta content="abcsoupco.com" property="og:site_name">
<meta content="website" property="og:type">
<meta content="https://primarysiteurl.com/page/sub-page" property="og:url">
<meta content="..." property="og:title">
<meta content="... synthesizes the data from your repos to give you full visibility and empowers your team for continuous delivery." property="og:description">
<meta content="...>
<meta content="1200" property="og:image:width">
<meta content="630" property="og:image:height">
<meta content="... synthesizes the data from your repos to give you full visibility and empowers your team for continuous delivery." property="og:image:alt">
<meta content="https://github.com/abcsoupco" property="og:see_also">
<meta content="https://www.linkedin.com/company/abcsoupco/" property="og:see_also">
<meta content="https://www.facebook.com/abcsoupco" property="og:see_also">
<meta content="https://twitter.com/abcsoupco" property="og:see_also">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@abcsoupco">
<meta name="twitter:creator" content="@abcsoupco">
<meta name="twitter:title" content="Page Title">
<meta name="twitter:description" content="...synthesizes the data from your repos to give you full visibility and empowers your team for continuous delivery.">
<meta name="twitter:image" content="...>
<meta name="twitter:image:width" content="1200">
<meta name="twitter:image:height" content="630">
<meta name="twitter:image:alt" content="...synthesizes the data from your repos to give you full visibility and empowers your team for continuous delivery.">
<link href="https://seomaticurl.com" rel="home">
<link type="text/plain" href="https://seomaticurl.com/humans.txt" rel="author"></head>
```

**JSON+LD (using a sub-page as an example)**
```
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@graph": [
        {
            "@type": "WebPage",
            "author": {
                "@id": "https://primarysiteurl.com#identity"
            },
            "copyrightHolder": {
                "@id": "https://primarysiteurl.com#identity"
            },
            "copyrightYear": "2022",
            "creator": {
                "@id": "https://primarysiteurl.com#creator"
            },
            "dateModified": "2022-07-12T06:40:38-07:00",
            "datePublished": "2022-03-02T15:06:00-08:00",
            "description": "...",
            "headline": "...",
            "image": {
                "@type": "ImageObject",
                "url": "https://optimise2.assets-servd.host/..."
            },
            "inLanguage": "en-us",
            "mainEntityOfPage": "https://primarysiteurl.com/page/sub-page",
            "name": "...",
            "publisher": {
                "@id": "https://primarysiteurl.com#creator"
            },
            "url": "https://primarysiteurl.com/page/sub-page"
        },
        {
            "@id": "https://primarysiteurl.com#identity",
            "@type": "Corporation",
            "address": {
                "@type": "PostalAddress",
                "addressCountry": "US",
                "addressLocality": "New York",
                "addressRegion": "NY",
                "postalCode": "10022",
                "streetAddress": "..."
            },
            "description": "...",
            "email": "hello@mail.com",
            "name": "Our Company",
            "sameAs": [
                "https://twitter.com/abcsoupco",
                "https://www.facebook.com/abcsoupco",
                "https://www.linkedin.com/company/abcsoupco/",
                "https://github.com/abcsoupco"
            ],
            "telephone": "(877) 609-3771",
            "url": "https://primarysiteurl.com"
        },
        {
            "@id": "#creator",
            "@type": "Organization"
        },
        {
            "@type": "BreadcrumbList",
            "description": "Breadcrumbs list",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "item": "https://seomaticurl.com",
                    "name": "Home",
                    "position": 1
                },
                {
                    "@type": "ListItem",
                    "item": "https://seomaticurl.com/page",
                    "name": "Page",
                    "position": 2
                },
                {
                    "@type": "ListItem",
                    "item": "https://seomaticurl.com/page/sub-page",
                    "name": "Sub Page",
                    "position": 3
                }
            ],
            "name": "Breadcrumbs"
        }
    ]
}
</script>
```

### Versions
- Plugin version: 3.4.36
- Craft version: Craft Pro 3.7.48

Thank you for your help,
Justen

**Comment by khalwat** [comment]
> Setting the "Site URL Override" does not update the URL used in the site's OG link, Schema data, or canonical link.

This is expected behavior; I'll explain what's going on.

The Site URL Override feature overrides anywhere that a site URL is referenced.

For the asset-related URLs such as your OG, SEOmatic essentially does `{{ asset.url }}` so Craft is going to return a URL to the asset, using whatever you have set up for the Asset Volume settings. So if you want those to be different somehow, you'd change your settings there.

For the Canonical URL, by default for entires, SEOmatic effectively does `{{ entry.url }}` so it's going to give you whatever URL Craft says is that element's URL. You can change this Twig expression in the Content SEO settings in SEOmatic if you like, to put whatever custom logic in there you need.

In general I'd say that fighting Craft may be a little bit of work overall, but SEOmatic does let you do it.

Also if you're doing this in the context of a headless setup, I'd note that SEOmatic does have both a GraphQL and an API endpoint that can be utilized as well: 

https://nystudio107.com/docs/seomatic/advanced.html#headless-spa-api

**Comment by justenh** [comment]
@khalwat Thanks for the quick response. 

Our scenario is that our production server is being hosted by https://Servd.host, but our domain is actually proxying the site through a custom NGINX. As such, we need all of our URLs to be either relative root, or in the case of SEO, not the `PRIMARY_SITE_URL`, but the proxy'd URL, which would be the `SEOMATIC_URL`.

I totally understand about assets, and our asset volumes are all S3 and not tied to our `PRIMARY_SITE_URL`. However, when you say...

> The Site URL Override feature overrides anywhere that a site URL is referenced.

I would anticipate that to include the Canonical and LD+JSON URLs (non image assets). Especially, when other URLs such as humans.text, and sitemap.xml do exactly that.

If the issue I outlined is intended behavior, do you have any suggestions for how I can force SEOMatic to return the Canonical URL, `og:url`, and Schema URLs to use the `SEOMATIC_URL` from our .ENV file?

Thanks again! 
Justen

**Comment by justenh** [comment]
@khalwat I also just updated my response to mention that the Schema LD+JSON data is part of this as well. The object references many site URLs, but only a portion of them, "Breadcrumbs", uses the correct SEO Override URL.

Thanks again for your help on this.
