### ISSUE TITLE
Facebook Opengraph image only displaying the default

### ISSUE THREAD

**Issue by brianhorace** [nystudio107/craft-seomatic#1206]
for my blogs i'm noticing that my facebook SEO images arent pulling from the image field I select, rather its displaying the default image. Seems to be working find in twitter.

https://fiscalnote.com/blog/policy-trends-automotive-industry

<img width="1440" alt="Screen Shot 2022-09-02 at 9 41 24 AM" src="https://user-images.githubusercontent.com/36520218/188171200-3d37cfe1-bcb7-44e1-a873-a072ff90554a.png">

<img width="1440" alt="Screen Shot 2022-09-02 at 9 41 12 AM" src="https://user-images.githubusercontent.com/36520218/188171268-72c7de57-334d-4ae4-8efd-dc84caf4b4ad.png">

<img width="1440" alt="Screen Shot 2022-09-02 at 9 40 58 AM" src="https://user-images.githubusercontent.com/36520218/188171283-a3a70903-8e4a-489c-9dfc-cc0818772d51.png">

<img width="1440" alt="Screen Shot 2022-09-02 at 9 40 55 AM" src="https://user-images.githubusercontent.com/36520218/188171314-c270e8bc-5621-4e07-9232-d38c962131fa.png">

<img width="1440" alt="Screen Shot 2022-09-02 at 9 40 40 AM" src="https://user-images.githubusercontent.com/36520218/188171389-34d6c3fa-7ebe-40bd-8514-b940cd183dc6.png">

**Comment by khalwat** [comment]
Show me the Content SEO settings for this section?

Generally, the best thing to do is to set up your Content SEO settings to pull from existing content (such as the Hero Featured Image in this case). The SEO Settings fields are meant to be used as a per-entry override as per:

https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

**Comment by brianhorace** [comment]
I think this is what you mean correct? The blog is set to pull from the hero but not in the  content seo sections. Are you saying in the content SEO settings we should pull from the hero?  What would be the fall back?

<img width="1440" alt="Screen Shot 2022-09-02 at 12 28 46 PM" src="https://user-images.githubusercontent.com/36520218/188198297-eee7a99d-1d0a-4145-beb2-b36eed936bd9.png">

<img width="1440" alt="Screen Shot 2022-09-02 at 12 29 30 PM" src="https://user-images.githubusercontent.com/36520218/188198336-6af5f59e-caa4-4621-bbf4-a8d3596f53dc.png">

**Comment by khalwat** [comment]
I want to see what the SEO Image settings are for Content SEO for that section.

I'd recommend you set them to pull from the Hero Features Image field... and not use the SEO Settings fields in your entry unless you need to override that mapping.

**Comment by brianhorace** [comment]
I hope I'm understanding the settings you need to see, I apologize if I'm still wrong here.

<img width="1440" alt="Screen Shot 2022-09-02 at 12 41 42 PM" src="https://user-images.githubusercontent.com/36520218/188200020-e6f9aa56-91bd-4e8e-a7f5-ba1b50e6b327.png">

<img width="1440" alt="Screen Shot 2022-09-02 at 12 41 23 PM" src="https://user-images.githubusercontent.com/36520218/188200022-01811844-13c1-463a-8c8d-6cd10a3a949c.png">

<img width="1440" alt="Screen Shot 2022-09-02 at 12 40 09 PM" src="https://user-images.githubusercontent.com/36520218/188200023-e0e4a442-aecc-45a2-a37d-6292f868eb54.png">

**Comment by khalwat** [comment]
Yes, that all looks correct. Re-save the settings on the General, Twitter, and Facebook pages for that Section in Content SEO, and then turn off the override you have set in the SEO Settings field, because you don't need it.

It will automatically pull from the field you've designated for every entry in that section. Then you only use the SEO Settings field if you want to manually override a setting.

**Comment by brianhorace** [comment]
Thank you so much
