### ISSUE TITLE
Breadcrumbs List does not render in multi site setup

### ISSUE THREAD

**Issue by ing-ivan-31** [nystudio107/craft-seomatic#1207]
### Question
Hello,

I have a Craftcms3 project with a multiple sites setup like this (they are all in the same single group):

![Screen Shot 2022-09-06 at 12 37 07](https://user-images.githubusercontent.com/7306140/188702739-b4b2fb51-0592-40b5-a335-043def833ee6.png)

My problem when i am trying to get the breadcrumbs only i am getting the homepage on the items, this is happening for all the pages

```
"breadcrumbList": {
   "@context": "http://schema.org/",
   "@type": "BreadcrumbList",
   "description": "Breadcrumbs list",
  "itemListElement": [
   {
    "@type": "ListItem",
    "item": "https://craft.local/",
    "name": "Homepage",
    "position": 1
    }
],
"name": "Breadcrumbs"
}
```

I don't know if I am missing something on the configuration of seomatic, the seomatic version used is **3.4.22**

### Additional context
![Screen Shot 2022-09-06 at 12 58 36](https://user-images.githubusercontent.com/7306140/188707004-fee241c4-fd7a-41d1-a788-5422edada966.png)
![Screen Shot 2022-09-06 at 13 00 56](https://user-images.githubusercontent.com/7306140/188706881-4686aa2b-3fc3-4bbe-8acb-ab85ea48137e.png)

![Screen Shot 2022-09-06 at 13 01 58](https://user-images.githubusercontent.com/7306140/188706895-16f98d59-f26c-415a-bde9-ace16f04cd4d.png)
![Screen Shot 2022-09-06 at 13 04 01](https://user-images.githubusercontent.com/7306140/188707099-943650b3-e085-46f1-9b76-da2d3436662f.png)

**Comment by khalwat** [comment]
The first thing I would suggest it to update to the latest version, which is [Version 3.4.37](https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.37) as of this writing.

**Comment by khalwat** [comment]
Also, I notice that you're using the JSON-LD endpoint, but you're not passing in a `siteId` parameter? Doing so will cause it to just return the default site's metadata.

https://nystudio107.com/docs/seomatic/advanced.html#meta-container-api-endpoints

**Comment by ing-ivan-31** [comment]
@khalwat,  the issue persists on my environment with the [version 3.4.37](https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.37) and also adding the siteId parameter, 

![Screen Shot 2022-09-06 at 16 10 56](https://user-images.githubusercontent.com/7306140/188752375-e95e2cca-28b3-435e-9405-2d9ab555475f.png)
![Screen Shot 2022-09-06 at 17 33 45](https://user-images.githubusercontent.com/7306140/188752377-63cfe663-2304-4594-a1d7-95082cca08fb.png)
![Screen Shot 2022-09-06 at 17 34 36](https://user-images.githubusercontent.com/7306140/188752380-7bd3f946-be68-431e-8dd0-4191cc000d9a.png)

**Comment by khalwat** [comment]
Did you fill in different information for each site in SEOmatic -> Site Settings?

<img width="818" alt="Screen Shot 2022-09-06 at 8 18 15 PM" src="https://user-images.githubusercontent.com/7570798/188761883-0a0b22a9-e3a2-4b13-be6d-9a94ed94ad65.png">

**Comment by ing-ivan-31** [comment]
Hi again @khalwat, thanks for the help and answers, related to your last question, I fill in all the different information for each site but I continue with the same problem, below some evidence:

![Screen Shot 2022-09-07 at 9 28 27](https://user-images.githubusercontent.com/7306140/188904996-c717d0e1-52c9-44b4-8438-1f77a9d18c58.png)
![Screen Shot 2022-09-07 at 9 28 36](https://user-images.githubusercontent.com/7306140/188905022-e6b49ab1-74c5-467a-bcd9-35024355034d.png)
![Screen Shot 2022-09-07 at 9 28 45](https://user-images.githubusercontent.com/7306140/188905038-a4685fea-94f9-4b4e-8985-f5d0cc818206.png)

**Comment by khalwat** [comment]
So I just did a test, and it seems to be working as expected.

I tried two simple tests:

URL #1: `http://localhost:8003/actions/seomatic/meta-container/meta-json-ld-container/?uri=/&siteId=1`

Output #1:
```
{
    "MetaJsonLdContainer": "<script type=\"application/ld+json\">{\"@context\":\"http://schema.org\",\"@type\":\"WebPage\",\"author\":{\"@id\":\"#identity\"},\"copyrightHolder\":{\"@id\":\"#identity\"},\"copyrightYear\":\"2020\",\"creator\":{\"@id\":\"#creator\"},\"dateModified\":\"2021-03-15T11:40:42-04:00\",\"datePublished\":\"2020-03-27T09:38:00-04:00\",\"headline\":\"Homepage\",\"image\":{\"@type\":\"ImageObject\",\"url\":\"http://localhost:8003/assets/site/_1200x630_crop_center-center_82_none/Screen-Shot-2022-03-22-at-12.56.42-PM.png?mtime=1650309044\"},\"inLanguage\":\"en-us\",\"mainEntityOfPage\":\"http://localhost:8003/\",\"name\":\"Homepage\",\"publisher\":{\"@id\":\"#creator\"},\"url\":\"http://localhost:8003\"}</script><script type=\"application/ld+json\">{\"@context\":\"http://schema.org\",\"@id\":\"#identity\",\"@type\":\"LocalBusiness\",\"priceRange\":\"$\"}</script><script type=\"application/ld+json\">{\"@context\":\"http://schema.org\",\"@id\":\"https://nystudio107.com/#creator\",\"@type\":\"Organization\",\"address\":{\"@type\":\"PostalAddress\",\"addressCountry\":\"US\",\"addressLocality\":\"Webster\",\"addressRegion\":\"NY\",\"postalCode\":\"14580\"},\"alternateName\":\"nys\",\"description\":\"We do technology-based consulting, branding, design, and development. Making the web better one site at a time, with a focus on performance, usability & SEO\",\"email\":\"info@nystudio107.com\",\"founder\":\"Andrew Welch, Polly Welch\",\"foundingDate\":\"2013-05-02\",\"foundingLocation\":\"Webster, NY\",\"image\":{\"@type\":\"ImageObject\",\"height\":\"1042\",\"url\":\"https://nystudio107-ems2qegf7x6qiqq.netdna-ssl.com/img/site/nys_logo_seo.png\",\"width\":\"1042\"},\"name\":\"nystudio107\",\"url\":\"https://nystudio107.com\"}</script><script type=\"application/ld+json\">{\"@context\":\"http://schema.org\",\"@type\":\"BreadcrumbList\",\"description\":\"Breadcrumbs list\",\"itemListElement\":[{\"@type\":\"ListItem\",\"item\":\"http://localhost:8003\",\"name\":\"Homepage\",\"position\":1}],\"name\":\"Breadcrumbs\"}</script>"
}
```

URL #2: `http://localhost:8003/actions/seomatic/meta-container/meta-json-ld-container/?uri=/&siteId=2`

Outpu #2t:
```
{
    "MetaJsonLdContainer": "<script type=\"application/ld+json\">{\"@context\":\"http://schema.org\",\"@type\":\"WebPage\",\"author\":{\"@id\":\"#identity\"},\"copyrightHolder\":{\"@id\":\"#identity\"},\"copyrightYear\":\"2020\",\"creator\":{\"@id\":\"#creator\"},\"dateModified\":\"2021-03-15T11:40:42-04:00\",\"datePublished\":\"2020-03-27T09:38:00-04:00\",\"headline\":\"Homepage\",\"inLanguage\":\"es\",\"mainEntityOfPage\":\"http://localhost:8003/es/\",\"name\":\"Homepage\",\"publisher\":{\"@id\":\"#creator\"},\"url\":\"http://localhost:8003/es\"}</script><script type=\"application/ld+json\">{\"@context\":\"http://schema.org\",\"@id\":\"#identity\",\"@type\":\"LocalBusiness\",\"priceRange\":\"$\"}</script><script type=\"application/ld+json\">{\"@context\":\"http://schema.org\",\"@id\":\"https://nystudio107.com/#creator\",\"@type\":\"Organization\",\"address\":{\"@type\":\"PostalAddress\",\"addressCountry\":\"US\",\"addressLocality\":\"Webster\",\"addressRegion\":\"NY\",\"postalCode\":\"14580\"},\"alternateName\":\"nys\",\"description\":\"We do technology-based consulting, branding, design, and development. Making the web better one site at a time, with a focus on performance, usability & SEO\",\"email\":\"info@nystudio107.com\",\"founder\":\"Andrew Welch, Polly Welch\",\"foundingDate\":\"2013-05-02\",\"foundingLocation\":\"Webster, NY\",\"image\":{\"@type\":\"ImageObject\",\"height\":\"1042\",\"url\":\"https://nystudio107-ems2qegf7x6qiqq.netdna-ssl.com/img/site/nys_logo_seo.png\",\"width\":\"1042\"},\"name\":\"nystudio107\",\"url\":\"https://nystudio107.com\"}</script><script type=\"application/ld+json\">{\"@context\":\"http://schema.org\",\"@type\":\"BreadcrumbList\",\"description\":\"Breadcrumbs list\",\"itemListElement\":[{\"@type\":\"ListItem\",\"item\":\"http://localhost:8003/es\",\"name\":\"Homepage\",\"position\":1}],\"name\":\"Breadcrumbs\"}</script>"
}
```

I know it's a little hard to read, but you'll see the different URLs, and two different titles: **Project ENGLISH** and **Project SPANISH**

Have you tried clearing SEOmatic's caches, or hitting the endpoints directly to see what you see there?

**Comment by QUACK07** [comment]
Hi [ing-ivan-31](https://github.com/ing-ivan-31), I think you need to update the **DynamicMeta.php** file following this lines because right now **getElementByUri** function is hardcoded with` __home__` and that uri doesn't exist

Line 282
`self::addMetaJsonLdBreadCrumbs($siteId, $uri);`
line 314 
`public static function addMetaJsonLdBreadCrumbs(int $siteId = null, string $uri = '')`
line 348 
`$element = Craft::$app->getElements()->getElementByUri($uri, $siteId, true);`

**Comment by ing-ivan-31** [comment]
> Hi [ing-ivan-31](https://github.com/ing-ivan-31), I think you need to update the **DynamicMeta.php** file following this lines because right now **getElementByUri** function is hardcoded with` __home__` and that uri doesn't exist
> 
> Line 282 `self::addMetaJsonLdBreadCrumbs($siteId, $uri);` line 314 `public static function addMetaJsonLdBreadCrumbs(int $siteId = null, string $uri = '')` line 348 `$element = Craft::$app->getElements()->getElementByUri($uri, $siteId, true);`

@khalwat what do you think about this? , i made the test for only homepage in each site id and effectively the url change but when i enter other URI only i am getting the homepage check the screenshots

![Screen Shot 2022-09-08 at 8 38 22](https://user-images.githubusercontent.com/7306140/189137782-643c2c5b-2ea4-4f4e-aae4-fe2c87ce0c7e.png)
![Screen Shot 2022-09-08 at 8 38 39](https://user-images.githubusercontent.com/7306140/189137788-0e49ae59-8ee5-419e-8b6a-713f6e4f50e9.png)
![Screen Shot 2022-09-08 at 8 39 00](https://user-images.githubusercontent.com/7306140/189137789-8fe9df2d-9073-4265-8960-f5f6c3c77037.png)
![Screen Shot 2022-09-08 at 8 39 17](https://user-images.githubusercontent.com/7306140/189137793-13938037-d8dc-442c-b2e2-4751bc60c671.png)

**Comment by khalwat** [comment]
So you have no element that is designated as being the homepage of the site (it would have the special URI of `__home__`), whether that be a single or an entry in a structure or the like?

If not, then SEOmatic can't automatically determine the home page properly for you.

**Comment by ing-ivan-31** [comment]
> So you have no element that is designated as being the homepage of the site (it would have the special URI of `__home__`), whether that be a single or an entry in a structure or the like?
> 
> If not, then SEOmatic can't automatically determine the home page properly for you.

You have right @khalwat, the homepage is missing on our craft configuration when i set the homepage all the breadcrumb lists started to work on our pages.

thank so much, for your help and support.

![Screen Shot 2022-09-09 at 12 58 08](https://user-images.githubusercontent.com/7306140/189419599-9f515781-94c9-4499-82c5-c3318d1dec18.png)
![Screen Shot 2022-09-09 at 13 22 12](https://user-images.githubusercontent.com/7306140/189419601-69c089dd-bc8f-48d3-9d67-81bf080f7e6d.png)
![Screen Shot 2022-09-09 at 13 27 30](https://user-images.githubusercontent.com/7306140/189419602-71e4a6f8-220e-43c3-837b-7ffc46a88d85.png)
