### ISSUE TITLE
Disable SEOmatic on page/template level

### ISSUE THREAD

**Issue by thaoms** [nystudio107/craft-seomatic#121]
For example, I'm having a newsletter template which doesn't need SEO and gives errors when importing because it contains javascript (JSON).

Is this possible?

**Comment by khalwat** [comment]
Yep, similar to what was discussed here: https://github.com/nystudio107/craft-seomatic/issues/119

You can do something like this:

```twig
{% do seomatic.config.renderEnabled(false) %}
```

More information is here: https://github.com/nystudio107/craft-seomatic#config-variables-seomaticconfig
