### ISSUE TITLE
How long takes to update the SEO configuration?

### ISSUE THREAD

**Issue by GeoWg** [nystudio107/craft-seomatic#1211]
![image](https://user-images.githubusercontent.com/14365649/191558989-a5a53799-d5dd-4858-b8bf-7c81b95f5c3a.png)
![image](https://user-images.githubusercontent.com/14365649/191559107-b3bce12b-be16-47a1-bce3-c01d2f1f7fa5.png)

I'm updating in my CraftCMS SEOmatic configurations, but it doesn't update on google, I already cleared the cache, does take a long time to refresh this data? I've made 2 days ago already
I'm using SEOmatic 3.4.37
Craft CMS:  Craft Pro 3.7.50

**Comment by khalwat** [comment]
The updates happen immediately in SEOmatic, and in the metadata it generates.

How long it takes Google to update their index is completely up to Google, and depends on your site, how much traffic it gets, how often Google crawls it, etc.
