### ISSUE TITLE
Content SEO tab appears blank

### ISSUE THREAD

**Issue by richardfrankza** [nystudio107/craft-seomatic#1215]
### Describe the bug

We've installed SEOMatic but don't see entry types here:

![image](https://user-images.githubusercontent.com/17523844/192709182-079cdece-fe10-4f1b-bbb6-686e17f7cb02.png)

Also the dashboard is empty

![image](https://user-images.githubusercontent.com/17523844/192709249-09377418-9427-49e4-8894-09bccbd128cd.png)

We don't know how to debug this further. We believe we have "public urls" for the content types as per the documentation, but please advise troubleshooting steps for this?

### Versions
- Plugin version: 4.0.8
- Craft version: 4.2.5.1

**Comment by antonatflow** [comment]
We have managed to find our issue to resolve the above:
The issue was resolved by updating our `.env` file:
...
~~PRIMARY_SITE_URL=/web/~~ PRIMARY_SITE_URL=/
...
