### ISSUE TITLE
Serialization of 'Closure' is not allowed (Cache.php:249)

### ISSUE THREAD

**Issue by neildcuk** [nystudio107/craft-seomatic#1216]
Hi there, we are having sporadic issues with a rather large Craft 3 site — the above error occasionally occurs on page load, but clears after a refresh.

It appears to be centred around the use of `Craft::$app->getCache()->getOrSet` within `MetaContainers.php` on line 273. This sends what appears to be a function as the `$value` argument which `getOrSet` attempts to serialise on line 249 of `vendor/yiisoft/yii2/caching/Cache.php`. This then results in the error in question.

I'm not sure how to trigger this, as this is not a site I work on day-to-day, but it appears to be the result of using SEOMatic on a page. I am happy to attempt to provide more details if needed but this is a client site and therefore we are subject to non-disclosure agreements. Hopefully this is enough to go on for now, but do let me know if there's anything else I can supply.

If you could please let us know if this use of `getOrSet` is indeed valid and that you would not expect to see an error here, we can try to figure out what might be causing it.

![seomatic-closure-error](https://user-images.githubusercontent.com/5774929/192758994-19059e4b-1994-45e8-afdf-995c22972595.jpg)

I believe the template trigger would be in our main layout file and looks like this:

```
{% hook 'seomaticRender' %}
```

There also looks to be some prior work done to an object named `seoMaticMeta` which I presume is used by SEOMatic in some way before the hook is run:

```
{% if seoImage is defined %}
	{% set fbImage = seoImage.getUrl('ogFacebook') %}
	{% set twImage = seoImage.getUrl('ogTwitter') %}
	{% set canonicalUrl = entry.url %}
	{% if entry.type == 'places' and craft.request.getSegment(4) != '' %}
	{% set canonicalUrl = canonicalUrl ~ '/' ~ craft.request.getSegment(4) %}
	{% endif %}
	{% set seomaticMeta = {
		seoTitle: entry.title,
		seoDescription: seomaticMeta.og.description|default(entry.type.handle == 'events' ? entry.eventSummary : entry.summaryText),
		seoKeywords: entry.body,
		seoImage: seomaticMeta.seoImage,
		canonicalUrl: canonicalUrl,
		twitter: {
			card: seomaticMeta.twitter.card,
			site: seomaticMeta.twitter.site,
			creator: seomaticMeta.twitter.creator,
			title: entry.title,
			description: seomaticMeta.og.description,
			image: twImage,
		},
		og: {
			type: seomaticMeta.og.type,
			locale: seomaticMeta.og.locale,
			url: entry.url,
			title: entry.title,
			description: seomaticMeta.og.description,
			image: fbImage,
			site_name: seomaticMeta.og.site_name,
			see_also: seomaticMeta.og.see_also,
		}
	} %}
{% endif %}
```

(I have no reason to believe any of this has failed but do let me know if you need more information there.)

- Plugin version: 3.4.37
- Craft version: 3.7.54

**Comment by khalwat** [comment]
So this looks like very old code that was likely left over from a Craft 2 version of the site. I would delete all of that code.

`{% hook 'seomaticRender' %}` doesn't even exist in SEOmatic for Craft 3/4, and the rest of the code looks like a relic from the past as well.

I think very likely what is needed here is a good audit on the site to remove anything that is not relevant for SEOmatic for Craft 3/4.

lmk if you need anything further

**Comment by neildcuk** [comment]
Hi there @khalwat — just an update on this. It turns out the code I was looking at was actually out of date from the repo on my end. We had upgraded CMS to Craft 3 recently and I didn't have the updated code locally.

It turns out we were using SEOMatic correctly, but also in an incorrect way: 

```
{% do seomatic.meta.seoImage(seoImage) %}
```

This would have been fine except that `seoImage` was actually a full class instance, not a string—which is why the error occurred.

Thanks for your help!

**Comment by khalwat** [comment]
Ah got it, that makes sense!

**Comment by khalwat** [comment]
I'd also have a look at:

https://nystudio107.com/docs/seomatic/issues.html#upgrading-from-seomatic-1-x-for-craft-cms-2-x

and:

https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

...because _most_ of the time, you shouldn't need to be writing any Twig code at all, and instead should just set up mappings in Content SEO.
