### ISSUE TITLE
Versions with Craft 3

### ISSUE THREAD

**Issue by DianyelaMaldonado** [nystudio107/craft-seomatic#1217]
### Question
How can I use or return to a specific version, compatible with craft 3?  👀

**Comment by khalwat** [comment]
If you want the Craft 3 version, you can either set the semver version to `^3.0.0` in your `composer.json` file, or you can install it via the Plugin Store in the Craft CP.

**Comment by DianyelaMaldonado** [comment]
thanks @khalwat  but I'm not referring to a version of Craft CMS :C , I mean using a specific version of **Craft-Seomatic**, for example 3.4.14.

**Comment by khalwat** [comment]
You can do that if you want, by putting that _specific version_ into the `composer.json` file. More information here:

https://nystudio107.com/blog/composer-for-the-rest-of-us

I wouldn't really recommend it, though. It's better to receive all of the updates possible, and use a semver like `^3.0.0` which will ensure you get the latest updates.

Is there a reason you want to use a specific version of SEOmatic?
