### ISSUE TITLE
Disabled Tracking Scripts following Craft 4 upgrade.

### ISSUE THREAD

**Issue by mikeymeister** [nystudio107/craft-seomatic#1218]
### Describe the bug
We've had an odd outcome following an upgrade of a site from craft 3 to 4, including the required seomatic upgrade (versions below). Following the upgrade the gtag tracking script "enabled" setting had changed to disabled.

### To reproduce
Steps to reproduce the behaviour:
1. Upgrade a craft 3 site with a tracking script enabled
2. See that the script is now disabled.

### Expected behaviour
Upgrading craft and seomatic shouldn't change settings of features present in both previous and new versions.

### Versions
- Plugin version: 3.4.37 -> 4.0.7
- Craft version: 3.7.48 -> 4.2.1.1

**Comment by khalwat** [comment]
Are you sure this isn't because you're running it in local dev? SEOmatic automatically disables tracking scripts if the environment is anything but production, or if `devMode` is on.

I'm not aware of any issues regarding upgrading from Craft 3 to Craft 4, and the corresponding versions of SEOmatic.

**Comment by mikeymeister** [comment]
We got the same result when the migrations/upgrades ran on the production server too, that's the first place it was noticed. Would the CP settings page display the setting as disabled (a turned-off lightswitch) in a non-production environment or just display that it was being overridden? 

I checked in the db and didn't see any changes to the json data when it was disabled in the CP (initially after the upgrade) compared to once I had manually reenabled the scripts using the switch. I wasn't sure if something had changed in the way that data was stored or read in c4.

With no one else experiencing the issue, I suppose it's got to be something specific to this project or a glitch in the matrix. Thanks for you quick response.

**Comment by murphy1484** [comment]
We've experienced the same after a  Craft 4 upgrade
Craft: 3.8.13 -> 4.4.13
Seomatic: 3.4.56 -> 4.0.27

**Comment by khalwat** [comment]
@murphy1484 where was the upgrade done? Are we sure it isn't due to the environment as mentioned above?

**Comment by murphy1484** [comment]
@khalwat the upgrade was indeed done on the production env and the client noticed that no data was gathering in GTM.

**Comment by khalwat** [comment]
I don't suppose you have a copy of the db (actually all I need is the `seomatic_metabundles` table) from _after_ you did the update, but _before_ you toggled the lightswitch to turn the script back on?

**Comment by murphy1484** [comment]
I'm afraid I don't

**Comment by walshmichael** [comment]
Also have experienced this with all Craft 4 and 5 upgrades.

The initial production database state for `seomatic_metabundles` table has **include** set to `"include":false`, even though it is actually toggled on when viewing in Craft CMS admin.

After performing the Craft 4/5 upgrade, manually toggling on the lightswitch and resaving causes `seomatic_metabundles` table to update the include prop to `"include":"1"` as would be expected.

Perhaps root cause is a change in the handling of the toggling behaviour between SEOMatic for Craft 3 and 4/5?

**Comment by khalwat** [comment]
@walshmichael the code is largely the same between the versions, and there weren't any changes to the `seomatic_metabundles` format.

It doesn't make sense to me that the table in the db could have `include: false` -- was it a textual value or an actual boolean?

Either way, the value in the db should reflect what is shown on the frontend. My guess is that it may have something to do with the upgrade being done in local dev, where scripts should be overridden by the environment to have that set to `false`.

But the problem would only surface itself if that was somehow saved in the db, and then you pushed that db to production.

**Comment by oranges13** [comment]
We are experiencing this also with a craft 3.9 -> craft 4 upgrade.

Additionally on the upgraded site, the sidebar navigation links for SeoMatic are failing to appear.

QA on Craft 4
![QA - on Craft 4](https://github.com/user-attachments/assets/9028fe27-23f0-441c-8c73-9e9202a77f9c)

versus Production on Craft 3.9
![Prod - on Craft 3.9](https://github.com/user-attachments/assets/cc4e07e2-4094-41f7-afc7-a4baa654199a)

**Comment by khalwat** [comment]
@oranges13 you can start a new issue if you like; as for the navigational sidebar not appearing, probably that is a permissions issue of some kind.
