### ISSUE TITLE
Description Overrides - odd behaviour

### ISSUE THREAD

**Issue by scott-davidjones** [nystudio107/craft-seomatic#1219]
### Question
I am working on a multisite project currently which uses SEOMatic - this plugin is new to me and I cannot get my head around an odd issue. I Have set products to use SEO Description of 'No Override' and then in the Content SEO i have set the Seo Description to be "From Field" and Source Field "Description". The plugin seems to choose a random segment of the specified field as the meta description. An example:

Product Description:
```
This is the first sentence. In the first paragraph of my description.

A Second sentence. In paragraph 2. 

Other text
```
On the Main site the meta description for the product would show ```A Second sentence. In paragraph 2.```
On the ES version of the site the meta description is being set to ```In paragraph 2``` and i cannot fathom why. 

I expect to see the full text in the specified field in the description but that only happens if i go to the individual product and override the Seo Description Source - something i don't want to do on all the products (thousands of them)

Have i missed something in the setup/config that would cause this behaviour?

### Additional context
Craft Version: Craft CMS 3.7.30.1
SEOMatic Version: 3.4.23

**Comment by khalwat** [comment]
Screenshot from your Content SEO Settings? It sounds like you're using the Summary From Field setting, even though in your description, that doesn't appear to be the case.

Also, before we go any further, please update SEOmatic to the latest version -- that's 3.4.39 at the time of this writing.

**Comment by scott-davidjones** [comment]
Thanks for getting back to me - We cant update the plugin as client has frozen all upgrades at present. However, it turns out the client had multiple Content SEO with incorrect settings and the one they directed me to, because they were the 'expert', was setup correctly, but was in fact the wrong one. After spending a few hours going through and setting all COntent SEO up correctly the issue disappeared..

**Comment by khalwat** [comment]
Glad it's fixed I guess... but I'd try to update when you're able as well :)
