### ISSUE TITLE
Content SEO section doesn't update properly when editing section in Craft

### ISSUE THREAD

**Issue by steverowling** [nystudio107/craft-seomatic#122]
If you edit an existing section in Craft to remove the URL definition, so the section still exists, but no longer has URLs, SEOMatic doesn't update its Content SEO section to remove the section.

In testing the Content SEO section correctly updates to reflect adding and deleting sections in Craft, but doesn't correctly update if you remove URLs from a section as described above.

Admittedly it's an edge case, but as you've covered the other cases so well, it would nice to have!

**Comment by khalwat** [comment]
So this is weird... because I actually do have code in place to handle this. I'll check out why it's not working as expected.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/bb88f9f6ce6c9b1e25efe9e1bc5519a96adea0ad
