### ISSUE TITLE
`str_contains` only exists in php8 - plugin is broken in php 7.x after release 3.4.30

### ISSUE THREAD

**Issue by danieltott** [nystudio107/craft-seomatic#1221]
### Describe the bug
Running `composer upgrade` on a site running php 7.4 results in the following error:

```
Call to undefined function nystudio107\seomatic\helpers\str_contains()
```

### To reproduce
Steps to reproduce the behaviour:
1. On Craft 3.x, hosted on php 7.4
2. Install the latest seomatic

### Expected behaviour

[The minimum specs for Craft 3.x are `PHP 7.2.5+`](https://craftcms.com/docs/3.x/requirements.html#recommended-system-specs)

I would think that a plugin for Craft 3.x should follow those, or at least make it clear with a major version that the php version requirements are changing.

My guess is this can be resolved by checking if `str_contains` exists, and if not, use the old way.

### Versions
- Plugin version: `3.4.39`
- Craft version: `3.5.19.1`
- PHP version: `7.4`

**Comment by khalwat** [comment]
Wow, this is not good. I'm surprised this is the first time it's been run into. Also surprised my IDE is not warning me here.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/b1b0af7bd0f934de26963f292e693e932dec24bd

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.40”,
```
Then do a `composer clear-cache && composer update`
