### ISSUE TITLE
Unable to edit entries/products/categories

### ISSUE THREAD

**Issue by daniellelecomte** [nystudio107/craft-seomatic#1223]
### Describe the bug
While attempting to make any content edits in Craft, the CP times out and throws an internal server error. 

### To reproduce
Go to any entry/category or product entry and the page just loads and loads, eventually timing out. 
Console shows:
```
https://.../index?fieldType=SeomaticExpressionField&twigfieldOptions=%7B%22singleLineEditor%22%3Atrue%7D
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: [::1]:443
Referrer Policy: origin-when-cross-origin
```

### Expected behavior
Be able to successfully edit content.

### Screenshots
What I see as the pages are hanging: https://d.pr/i/3NzaXJ

### Versions
SEOmatic 3.4.39 & Twigfield 1.0.16
Craft version: 3.7.55.3

**Comment by khalwat** [comment]
As discussed in Discord, that endpoint is only ever hit when a page that has a Twigfield is on it. And even if you're using an SEO Settings field, no Twigfield is used on the Entry or Category editing pages at all.

So I suspect something else is doing on here...

**Comment by khalwat** [comment]
Just waiting on the latest version of SEOmatic being deployed to Staging so I can investigate the issue further.

**Comment by khalwat** [comment]
Will re-open the issue if additional information/access is provided.

**Comment by khalwat** [comment]
May be related: https://github.com/nystudio107/craft-seomatic/issues/1229

**Comment by daniellelecomte** [comment]
Hey Andrew! Finally getting back to this and still having timeout issues - now affecting any SEOmatic settings pages. It's taking 5+ minutes to get a settings page to load, if it loads without getting an internal server error. 

Updated Craft to 3.7.63.1 and SEOmatic to 3.4.48. Do you still have the access I provided in Discord?

Here's some of what I see while the page is trying to load: https://d.pr/i/njcoL1 (3.5 mins in and still waiting)
Show's what's pending still after 10 minutes: https://d.pr/i/Oij6hB

Any version past 3.4.32 gives me trouble. Thanks!
