### ISSUE TITLE
Hreflang & noindex

### ISSUE THREAD

**Issue by veronika-g** [nystudio107/craft-seomatic#1224]
### Hreflang & noindex
Hi! 
My client sent me feedback that some pages with "noindex" still have hreflang pointing to them. Is it possible to turn the hreflang off for specific pages? 

They also sent me this article: https://sitebulb.com/hints/international/noindex-url-has-incoming-hreflang/

Do you have some advice how I can fix this issue? (except of turning off noindex)

Kind regards,
Veronika

**Comment by khalwat** [comment]
Yes, you can turn off the `hreflang` for specific pages via some custom twig code. This issue may help:

https://github.com/nystudio107/craft-seomatic/issues/858#issuecomment-801905911
