### ISSUE TITLE
Google Analytics Tag field missing

### ISSUE THREAD

**Issue by EKNathanN** [nystudio107/craft-seomatic#1225]
### Describe the bug
The 'Google Analytics Tracking ID' field within 'Tracking Scripts' is missing in the latest update. Reverting to the previous version resolved the issue. Also seems to be a console error suggesting a syntax error (missing closing bracket) is causing it.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Seomatic plugin
2. Click on Tracking Scripts
3. Select Google Analytics (old)
4. Notice Google Analytics Tracking ID field is missing. Only label is visible.
5. Open console in inspector tools to see syntax error

### Screenshots

![image](https://user-images.githubusercontent.com/86960732/197755551-ff7d5105-94c9-44b1-851e-1a031f9faf50.png)

### Versions
- Plugin version: 3.3.40
- Craft version: 3.7.57

**Comment by khalwat** [comment]
Fixed in: https://github.com/nystudio107/craft-twigfield/releases/tag/1.0.19

You can update via:

```
composer update nystudio107/craft-twigfield
```
