### ISSUE TITLE
GraphQL : return BreadcrumbList as array of EntryInterfaces in own field

### ISSUE THREAD

**Issue by denisyilmaz** [nystudio107/craft-seomatic#1226]
### Is your feature request related to a problem? Please describe.
The automatic generated _BreadcrumbList_ by SEOmatic is amazing. We are using it in several projects to actual render the breadcrumbs in the frontend.
All our projects are relying on GraphQL. Currently, the only way to retrieve the _BreadcrumbList_ is to call  …
```gql
seomatic(asArray:true) {
    metaJsonLdContainer
}
```
… and then `JSON.parse()` the response to access the values.

### Describe the solution you would like
It would be awesome if it would be possible to query the breadcumblist inside the seomatic field separately as an array of `EntryInterface` objects or something similar.  Even a field that only returns a string would already be a huge step forward.

As we don't render the JSON-LD objects via the frontend but via SSG loading the full `metaJsonLdContainer` is not really necessary in these cases.

**Comment by khalwat** [comment]
So the tough part about this is that the way the containers work, what is actually added into the container can vary, which doesn't work very well in terms of GraphQL.

The breadcrumbs contained therein are really intended for JSON-LD output/consumption, and not for display on the frontend.

Maybe you could create an endpoint that returns what you want instead?

**Comment by denisyilmaz** [comment]
hm, ok, you say a frontend should not rely on the json-ld output of seomatic to create a visible breadcrumb? I'm just curious as sites like https://craftsnippets.com/articles/breadcrumb-created-from-url-for-craft-cms#breadcrumb-with-seomatic suggest seomatic for exactly that purpose.

my idea was only to return this array `seomatic.jsonLd.get('breadcrumbList').itemListElement` either as string or array within its own gql-field.

**Comment by khalwat** [comment]
It's something that people have figured out you can do, yes, but that wasn't the intended functionality.
