### ISSUE TITLE
Twigfield autoload 

### ISSUE THREAD

**Issue by wmdhosting** [nystudio107/craft-seomatic#1229]
### Describe the bug
When SEO field is in entry >> twigfield loads >> and slowdown loading of other elemnts..

### To reproduce
![Snag_ca09d02](https://user-images.githubusercontent.com/76176291/199045100-10db7bf8-5885-4b02-8012-a424f11bf071.png)

### Versions
- Plugin version: 4.0.10
- Craft version: 4.3

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/a0c67a7735852c946e4f439daaf6055d7eeb63ec & https://github.com/nystudio107/craft-seomatic/commit/c40c79ed0522cf93437c4278b1f780eead829245

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.41”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.11”,
```
Then do a `composer clear-cache && composer update`
