### ISSUE TITLE
Google Analytics Tracking ID input box not appearing

### ISSUE THREAD

**Issue by alexagui** [nystudio107/craft-seomatic#1230]
### Describe the bug
On Craft CMS 4.2.8 the Google Analytics (old) **Tracking ID** input box isn’t appearing.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "/admin/seomatic/tracking/googleAnalytics/default"
2. Enable Google Analytics (old)

### Expected behaviour
I expect to see an input box to enter the tracking ID.

### Screenshots
![Image 2022-10-31 at 4 01 19 PM](https://user-images.githubusercontent.com/685/199101117-6ec0bda2-a803-4afb-822c-26a6dc114cc9.jpg)

### Versions
- Plugin version: 4.0.10
- Craft version: 4.2.8 Pro

**Comment by alexagui** [comment]
I tried upgrading locally to Craft CMS 4.3.1 but I still don't see the input box for Universal Analytics tracking ID.

**Comment by khalwat** [comment]
Please update to SEOmatic 3.4.41 (Craft 3) or 4.0.11 (Craft 4), it fixes this issue
