### ISSUE TITLE
Error Seomatic field

### ISSUE THREAD

**Issue by LieselotV** [nystudio107/craft-seomatic#1231]
### Describe the bug
I got an error on each page where I add a seomatic field.

### To reproduce
Steps to reproduce the behaviour:
1. I created a seo field names 'pageSearchEngineOptimalisation' (see printscreen below)
2. I add it as a field in sections on each page.
3. I get an error on each webpage I add this filed.
4. I tried to change the costum seo fields or just leave them blank (disabled), but the errors stays.

### Expected behaviour
No error

### Screenshots
screenshots
![Schermafbeelding 2022-11-02 om 10 11 22](https://user-images.githubusercontent.com/44613082/199451201-ad4afc37-bc65-45b3-9651-396e9dffd8c8.png)
<img width="718" alt="Schermafbeelding 2022-11-02 om 10 19 09" src="https://user-images.githubusercontent.com/44613082/199451873-6f1d8451-7d14-4256-a870-f68ab49f37c2.png">

### Versions
- Plugin version: 4.0.2
- Craft version: Craft Pro 4.3.1

**Comment by khalwat** [comment]
So I think this might be a regression in Craft CMS; what's happening is if none of the checkbox fields are checked, the value that is being saved _should_ be an empty array `[]` but instead, it's saving it as an empty string `''` for some reason.

I'll add a check to guard against this. I suspect it's a regression in Craft 4.3

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/aa379022d1c5d43b5635a998baaa03db5f042e8e

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.12”,
```
Then do a `composer clear-cache && composer update`

**Comment by LieselotV** [comment]
It fixed the problem. Thank you for your quick solution.
