### ISSUE TITLE
SEOmatic is not creating valid sitemaps

### ISSUE THREAD

**Issue by mark-pixeldeluxe** [nystudio107/craft-seomatic#1232]
### Describe the bug
SEOmatic creates a broken sitemap, whenever i go to /sitemap.xml it gives me:

XML Parsing Error: XML or text declaration not at start of entity
Location: /sitemaps-1-sitemap.xml/
Line Number 1, Column 5:
----^

It looks like it generates spaces in front of where the xml starts.

### Screenshots
![image](https://user-images.githubusercontent.com/116743272/199544337-0a4d8149-3e58-4cfd-8711-2acefe226760.png)

### Versions
- Plugin version: 4.0.9
- Craft version: 4.2.3

**Comment by khalwat** [comment]
Are you positive this is an SEOmatic issue? The sitemaps that I have do not include any spaces in front of them:

https://devmode.fm/sitemaps-1-sitemap.xml

https://devmode.fm/sitemaps-1-section-about-1-sitemap.xml

(choose "view source)

I think this is more likely to be some kind of project or devops issue on your end. Happy to help if I can!

Check to see if you have some stray spaces or such in your config files or something setup strangely in your server config.

**Comment by bartdigitalpulse** [comment]
Checking in from 2025 here with the same issue. This was because a dev left a stray newline at the start of web/index.php above `<?php`. Removing this newline fixed the issue. 

php 8.2.28
Craft Pro 4.15.2
SEOmatic 4.1.13

**Comment by khalwat** [comment]
@bartdigitalpulse yep that'd do it. That would appear on _every_ page coming from your webserver, by the way, not just XML sitemaps. It's just that the HTML spec is more forgiving.
