### ISSUE TITLE
location of security.txt configurable

### ISSUE THREAD

**Issue by FrDH** [nystudio107/craft-seomatic#1235]
### Is your feature request related to a problem? Please describe.
Our client requests the security.txt file to be located in the `.well-known` directory as described by https://securitytxt.org/ (step 1).

### Describe the solution you would like
Maybe an option where to safe the file?

### Describe alternatives you have considered
creating a symlink or manually copy/pasting the file to the directory

**Comment by khalwat** [comment]
Unfortunately, that is outside of the Craft root, so you'd need to do it with a symlink

**Comment by jamesmacwhite** [comment]
If it's just a URL access requirement you could setup a route for .well-known/security.txt to point to the SEOMatic location potentially?
