### ISSUE TITLE
[FR] - Robots by Content Type

### ISSUE THREAD

**Issue by mortscode** [nystudio107/craft-seomatic#1237]
### Question
How would you suggest I go about defining the `<meta name="robots" ... >` tag for a single entry type?

Google is suggesting that I leverage their `<meta name="robots" content="max-image-preview:large">` setting for recipes, but I'm noticing that other recipe sites are going all-in with stuff like: `<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">` in their meta robots tags.

I can hard-code it into my layout, but SEOmatic is adding a 2nd `<meta name="robots" content="all">` tag as well. Is that an issue to have 2 tags?

My hope is to test these robots settings on a handful of posts in hopes of my recipe images getting a wider preview on mobile in their google search results.

**Comment by khalwat** [comment]
So via Twig you'd do it like this:

```twig
{% set robotsTag = seomatic.tag.get("robots") %}
{% if robotsTag %}
    {% do robotsTag.content("index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1") %}
{% endif %}
```

...but I'll leave this open as a FR, because it's certainly something I could implement directly in SEOmatic as well:

https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag

**Comment by khalwat** [comment]
Working on a custom component that looks something like this:

<img width="1082" alt="Screen Shot 2022-11-10 at 4 28 55 PM" src="https://user-images.githubusercontent.com/7570798/201209743-261a99fa-da77-4af1-ba03-0483e8052355.png">

**Comment by khalwat** [comment]
Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.42”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.12”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
lmk how you go...

**Comment by khalwat** [comment]
Here it is in action:


https://user-images.githubusercontent.com/7570798/201255069-330a719c-bb7d-4fdc-b0a9-f018109974d1.mov

**Comment by chrismlusk** [comment]
This looks great and works well. Thank you!

**Comment by gbowne-quickbase** [comment]
Is this in the `3.4.42` release? I've got that on my local and still see the normal robots dropdown field both at the content level and at the page level
<img width="496" alt="image" src="https://user-images.githubusercontent.com/39066452/201763649-672d9810-f0fe-4ca7-862b-018f5a4806e5.png">
