### ISSUE TITLE
The 'Facebook Opengraph Image Transform Mode' field title and description is not removed when the field is is deselected in settings. 

### ISSUE THREAD

**Issue by DA-HarryCooper** [nystudio107/craft-seomatic#1240]
### Describe the bug
The 'Facebook Opengraph Image Transform Mode' field title and description is not removed when the field is is deselected in settings. 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/79839672/202162146-414bb0fe-8ff1-4117-a8b7-524bc1ded0d9.png">
<img width="339" alt="image" src="https://user-images.githubusercontent.com/79839672/202162424-a60abf1b-ab3a-4cce-a427-4535a8b45777.png">

### To reproduce
Steps to reproduce the behaviour:
1. Go to Settings > Fields > SEO
<img width="890" alt="image" src="https://user-images.githubusercontent.com/79839672/202162769-fb8529ff-36ad-469e-bceb-ab3c66cefae3.png">
2. Deselect the 'Facebook Opengraph Image Transform Mode' field
<img width="339" alt="image" src="https://user-images.githubusercontent.com/79839672/202162424-a60abf1b-ab3a-4cce-a427-4535a8b45777.png">
3. See the field title and description has not been removed.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/79839672/202162146-414bb0fe-8ff1-4117-a8b7-524bc1ded0d9.png">

### Expected behaviour
The field title and description should be removed.

### Screenshots
See images inline.

### Versions
- Plugin version: 3.4.42
- Craft version: 3.7.55.3

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/20d7925f590e80673862530996b712636ad00207 & https://github.com/nystudio107/craft-seomatic/commit/867942f36df8ad4f5b9b3023972ac2db89667ded

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.43”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.14”,
```
Then do a `composer clear-cache && composer update`
