### ISSUE TITLE
Error calling unknown `getFields()` method on Neo block type models

### ISSUE THREAD

**Issue by yoannisj** [nystudio107/craft-seomatic#1242]
### Describe the bug

When extracting text from a NEO field, a  `Calling unknown method: benf\neo\models\BlockType::getFields()`  is thrown from `nystudio107\seomatic\helpers\Text::extractTextFromNeo()`.

A quick look at the [history](https://github.com/nystudio107/craft-seomatic/commits/v4/src/helpers/Text.php) of this helper file shows that a similar issue occurred and was fixed for Matrix block types and SuperTable block types by changing `getFields()` to `getCustomFields()`. I quickly tried making the same change in `extractTextFromNeo` locally in the vendors folder and it does the trick!

### To reproduce
Steps to reproduce the behaviour:
- Install SEOmatic and Neo plugins
- Create a `bodyBlocks` Neo field and define block types using a nested text field
- Add the `bodyBlocks` field to the field layout of a `myEntryType` entry type
- Create an entry of type `myEntryType` and add blocks to its `bodyBlocks` field
- Write the following code in a Twig template:

```
{% set entry = craft.entries.type('myEntryType').one() %}
{% if entry %}
  {% set bodyText = seomatic.helper.extractTextFromField(entry.bodyBlocks) %}
{% endif %}
```

### Expected behaviour
The `bodyText` twig variable should contain text from fields nested in the Neo blocks from the `bodyBlocks` field, without throwing an error.

### Versions
- Plugin version: 4.3.2.1
- Craft version: 4.0.13

**Comment by khalwat** [comment]
If only all bug reports were this good... thank you!

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/404f1cbbc7874d2185551b29812b56b8a5a53054

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.14”,
```
Then do a `composer clear-cache && composer update`
