### ISSUE TITLE
Confusion over Google Tag Manger and Google Ads/gtag.js

### ISSUE THREAD

**Issue by sunscreem** [nystudio107/craft-seomatic#1243]
Hey Folks,

Weird one I can't suss out.

We need google tag manager AND it seems we need gtag.js for google ads conversions.

When both are switched on in SEOMatic, the gtag.js script won't render (we get the error in the source code) unless I add a analytics tag... the thing is the analytics tag is already being fired from google tag manager.

TL;DR - How do you have tag manager AND gtag.js (for google ad conversions)?

**Comment by khalwat** [comment]
You would typically set up gtag inside of Google Tag Manager in these cases. 

https://www.analyticsmania.com/post/gtag-vs-google-tag-manager/

**Comment by sunscreem** [comment]
Thank @khalwat - Google specifically advise not to do this now. When you cut and paste the gtag.js code into a tag manager (html snippet) they show a warning and link to a help article saying why not to do this. 

I'll have a read of that article now. Thank you.

**Comment by sunscreem** [comment]
FYI: 

![image](https://user-images.githubusercontent.com/7523595/203298185-9e576861-67f8-4173-b225-734e38dc6e4d.png)

**Comment by khalwat** [comment]
Right, you likely wouldn't do it via custom HTML tags
