### ISSUE TITLE
[4.x]: "Showing your unsaved changes." keeps popping up after not making any changes 

### ISSUE THREAD

**Issue by dima-ogrenich** [nystudio107/craft-seomatic#1244]
### Describe the bug
I have the same problem https://github.com/craftcms/cms/issues/11106, only it disappears if turn off  seomatic.

**Comment by khalwat** [comment]
This was fixed, please update to SEOmatic 4.0.15

If you still see the issue after updating, please ensure that you clear your caches.

**Comment by dima-ogrenich** [comment]
I have same issue for:

**Application Info**
PHP version	8.1.12
OS version	Linux 3.10.0-1160.49.1.el7.x86_64
Database driver & version	MySQL 5.7.36
Image driver & version	Imagick 3.7.0 (ImageMagick 6.9.12-34)
Craft edition & version	Craft Pro 4.3.3
Yii version	2.0.46
Twig version	v3.4.3
Guzzle version	7.5.0

**Plugins**
Blitz	4.2.3
Embedded Assets	3.1.0
Navigation	2.0.13
Neo	3.5.2
Redactor	3.0.2
Redactor Custom Styles	4.0.2
Redirect Manager	2.0.0
SEOmatic	4.0.15
Typed link field	2.1.4

**Comment by khalwat** [comment]
Did you clear all caches?

Also from that thread you pointed out, Typed Link field apparently causes this issue as well.

**Comment by dima-ogrenich** [comment]
I cleaned it. At the moment, this problem is present even after disabling  Typed Link field and Seomatic. It seems that the problem is different. Thanks!

**Comment by mcurry1213** [comment]
Also getting this issue after removing TypedLink field.

**Comment by khalwat** [comment]
@mcurry1213 make sure you update to the latest version of Craft, and the latest version of SEOmatic. I'm unable to reproduce the issue with both.

TypedLink field I believe still has the issue, however.
