### ISSUE TITLE
SEO field override lightswitch is automatically set to disabled when saving the element

### ISSUE THREAD

**Issue by mikesnoeren** [nystudio107/craft-seomatic#1245]
### Describe the bug
After #1239 got fixed there's been an issue where the override lightswitch within the seomatic field on any element is always set to disabled on-save which makes the field unusable.

### To reproduce
Steps to reproduce the behaviour:
1. Add a SEOmatic field to any element
2. Try to customise any of the values (title, description or image source)
3. Save the element and check back on the field, the changes you made have been saved, but the override lightswitch is set to disabled which causes your custom values to not be used.

### Versions
- Plugin version: 3.4.43 and 4.0.14
- Craft version: 3.6.2 and 4.3.3

**Comment by terryupton** [comment]
I am also seeing this issue and came here to post an issue.
I also reported it on Discord.

**Comment by khalwat** [comment]
This has been addressed & released:

Craft 3: Version 3.4.43 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.44

Craft 4: Version 4.0.15 -> https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.15
