### ISSUE TITLE
hreflang links gone in Craft 4

### ISSUE THREAD

**Issue by Leadstar-Johan** [nystudio107/craft-seomatic#1246]
### Question
Not sure if its a bug or just a setting that i havent found.
But when updating one of our sites from Craft 3.7.53.1 and SEOmatic 3.4.37 to Craft 4.3.1 and SEOmatic 4.0.12,
We lost the hreflang links in head of our pages.
For example our homepage has a Austrailan counterpart that used to get a hreflang link but now it doesnt.
I have pasted an example below how it looks like pre update and after update.
Would be awesome if someone could shed some light here!

Cheers 
Johan

### Additional context

**Our site head before update**

link href="https://example.com" rel="canonical"
link href="https://example.com" rel="home"
link href="https://example.com/ie" rel="alternate" hreflang="en-ie"
link href="https://example.com/za" rel="alternate" hreflang="en-za"
link href="https://example.com/au" rel="alternate" hreflang="en-au"
link href="https://example.com/nz" rel="alternate" hreflang="en-nz"
link href="https://example.com/ca" rel="alternate" hreflang="en-ca"
link href="https://example.com" rel="alternate" hreflang="x-default"
link href="https://example.com" rel="alternate" hreflang="en-gb"

**Our site head after update**

link href="https://example.com/" rel="canonical"
link href="https://example.com/" rel="home"

**Comment by khalwat** [comment]
Very likely something has gone awry with the update, because the code is largely the same on SEOmatic's end in both Craft 3 & Craft 4 versions of the plugin.

I'd make sure that all of your Craft  sites are enabled and have public URLs.

I'd also check that your sites are arranged in site groups as discussed here: https://nystudio107.com/docs/seomatic/technologies.html#multi-site-language-locale-support

**Comment by khalwat** [comment]
Will re-open if needed, but pretty sure the above will take care of it.

**Comment by Leadstar-Johan** [comment]
Hey Andrew, Yeah it was the sitemap settings that had gotten turned of during the update somehow, but all solved now. Thanks :) 
![image](https://user-images.githubusercontent.com/85494803/204295072-d62fd051-f2e4-44e6-8023-4241ab7cf931.png)
