### ISSUE TITLE
SEO vs. SEO Meta

### ISSUE THREAD

**Issue by joshuaseop2sinc** [nystudio107/craft-seomatic#1248]

**Comment by khalwat** [comment]
It's hard for me to tell from this screenshot, but this looks like two SEO Settings fields, just with different names?

I don't know how your site was set up, or by whom, but typically you'll not need to use an SEO Settings field at all, let alone two of them. SEO Settings fields are overrides to the Global SEO and Content SEO in SEOmatic, as described here:

https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

It also looks like it's a pretty old version of SEOmatic, so I would suggest updating to the latest.
