### ISSUE TITLE
Unable to enable/disable robots.txt/humans.txt or make changes in config txt it self 

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#125]
We are having troubles with saving configuration changes we make in the interface of the robots.txt/humans.txt 

After clicking the save button and seeing the page reload it give's the feedback that the changes are saved but everything falls back to the old (default) configurations.

Also trying to disable the robots or humans is also not being saved.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/03125f5e3c417acb50575d0a93746f6a09cb0548
