### ISSUE TITLE
Sitemap Generation Causes Expensive `COUNT` Query

### ISSUE THREAD

**Issue by markhuot** [nystudio107/craft-seomatic#1250]
When running the console command `seomatic/sitemap/generate` we're hit with an expensive query that's crashing the sitemap generation. The query is simply a `COUNT(*)` for articles but we have so many elements in our DB that it times out after a minute.

Not sure if there's anything you can do here, but high level, is it possible to get around/avoid the `COUNT(*)` when generating a sitemap?

The query and a resulting `EXPLAIN` are included next,

<details>

```sql
explain SELECT COUNT(*)
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `craft_elements` `elements`
   INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `elements`.`id`
   INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
   INNER JOIN `craft_content` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`entries`.`sectionId`='12') AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2022-12-06 17:25:34') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2022-12-06 17:25:34'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)) `subquery`
INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId`;
```

| id | select\_type | table | partitions | type | possible\_keys | key | key\_len | ref | rows | filtered | Extra |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | SIMPLE | entries | null | ref | PRIMARY,craft\_entries\_postDate\_idx,craft\_entries\_expiryDate\_idx,craft\_entries\_sectionId\_idx,craft\_entries\_sectionId\_postDate\_expiryDate\_idx | craft\_entries\_sectionId\_idx | 4 | const | 1174630 | 25.01 | Using where |
| 1 | SIMPLE | elements | null | eq\_ref | PRIMARY,craft\_elements\_dateDeleted\_idx,craft\_elements\_enabled\_idx,craft\_elements\_archived\_dateCreated\_idx,craft\_elements\_draftId\_fk,craft\_elements\_revisionId\_fk,craft\_elements\_archived\_dateDeleted\_draftId\_revisionId\_canon\_idx,craft\_idx\_bdzronbhgnaoaeemohidjvnnfnnjbcnufvmm,craft\_idx\_wtpncckpmdbrstkzdjrlxarkgloehgzzaoxu | PRIMARY | 4 | craft.entries.id | 1 | 5 | Using where |
| 1 | SIMPLE | elements\_sites | null | ref | PRIMARY,craft\_elements\_sites\_elementId\_siteId\_unq\_idx,craft\_elements\_sites\_enabled\_idx | craft\_elements\_sites\_elementId\_siteId\_unq\_idx | 4 | craft.entries.id | 1 | 50 | Using where |
| 1 | SIMPLE | content | null | ref | PRIMARY,craft\_content\_elementId\_siteId\_unq\_idx | craft\_content\_elementId\_siteId\_unq\_idx | 4 | craft.entries.id | 1 | 100 | Using index |
| 1 | SIMPLE | content | null | eq\_ref | PRIMARY | PRIMARY | 4 | craft.content.id | 1 | 100 | Using index |
| 1 | SIMPLE | elements\_sites | null | eq\_ref | PRIMARY | PRIMARY | 4 | craft.elements\_sites.id | 1 | 100 | Using index |
| 1 | SIMPLE | entries | null | eq\_ref | PRIMARY | PRIMARY | 4 | craft.entries.id | 1 | 100 | Using index |
| 1 | SIMPLE | elements | null | eq\_ref | PRIMARY | PRIMARY | 4 | craft.entries.id | 1 | 100 | Using index |

</details>

I believe the issue is caused by this `$totalElements` fetch, here: https://github.com/nystudio107/craft-seomatic/blob/e18d61d13ba10590f4a9e1f47936dc52bf6087c3/src/helpers/Sitemap.php#L120

Is it feasible to skip over the total count and just start rendering elements? I see the `sitemapLimit` is used if it's bigger than the total (which it would be in my case). Unfortunately the code never gets that far because it can't count the total to begin with. Maybe a way to just force the limit instead of the total?

### To reproduce
Steps to reproduce the behaviour:
1. With a sufficiently large DB call `./craft seomatic/sitemap/generate`
2. Wait for a timeout error

### Expected behaviour
A sitemap would be generated, without trying to count all elements in bundle first.

### Versions
- Plugin version: 3.4.26
- Craft version: 3.7.36

I realize this is an old Craft and old Plugin version, we're targeting a full update of Craft and SEOmatic this month, but so far in my local testing I haven't seen a benefit from the update for this issue.

**Comment by khalwat** [comment]
Running a simple `.count()` query is causing the db to go away? I'm surprised anything else works in the CP?

**Comment by khalwat** [comment]
@markhuot hit me up on Discord to discuss this if you're able... I'm a little confused how this could be the case.

**Comment by markhuot** [comment]
Most of the `.count()` calls are now abstracted to JSON queries that sometimes do time out in the CP for us, but are fine to ignore. E.g., this is called on the entries page and it does spin and spin before finally finishing several seconds later.

https://github.com/craftcms/cms/blob/926bd277f6022c20bbbc288c3bcd67691d312842/src/controllers/ElementIndexesController.php#L169-L174

However, what I think actually bit me here was RDS snapshot restores, which seems to pull data lazily out of an EBS snapshot. See: https://cintia.me/blog/post/lazy-rds/

After running the query a few times (waiting for it to time out) and then waiting the query started responding in ~6s reliably so I'm not sure there's anything you can/should do here.

Note: for future consideration, dropping the `COUNT(*)` entirely would be a nice feature because it would speed up sitemap generation not having to wait for that count to return. Similar to how the CP now offloads the `COUNT(*)` to an Ajax query so we don't have to wait for it to see the first page of entries. The first page of `limit 100 offset 0` is very fast even if the overall `COUNT(*)` doesn't work.
