### ISSUE TITLE
SEOmatic Vue 3 composable

### ISSUE THREAD

**Issue by LarsDol** [nystudio107/craft-seomatic#1251]
Hello! 

We're using SEOmatic quite often at [Digital Natives](https://digitalnatives.nl/). The setup usually involves heavy usage of the plugin's graphql API in combination with Vue.

I was wondering if there's a Vue 3 composable available for mapping the different fields into the page's head?
We have a basic implementation ready, but it takes quite some work to include all of the options. Being able to use a correct and complete composable for SEOmatic would really help us. I thought I'd ask here first before we create one ourselves :)

Thanks!

**Comment by khalwat** [comment]
Currently that doesn't exist, but I'd love to see it happen. Keep me updated, and let me know if I can assist!
