### ISSUE TITLE
Empty sitemaps

### ISSUE THREAD

**Issue by anchovy** [nystudio107/craft-seomatic#1253]
### Describe the bug
Site maps are randomly being generated with no content - we'll have the main `/sitemap.xml` file and then the expected 6 child sitemaps - but 50% of the time these will be empty.

Running `./craft seomatic/sitemap/generate` outputs all the expected information/details
```
Generating sitemap
Generating sitemap for category Capability, siteId 2
Query 1/1 - elements: 14
Processing element 1/14 - XXXX
Processing element 2/14 - YYY
....
Sitemap cache result:  for cache key: seomatic_sitemap_1categorygroupcapability2
---
Generating sitemap for single Homepage, siteId 2
Query 1/1 - elements: 1
Processing element 1/1 - Home
Sitemap cache result:  for cache key: seomatic_sitemap_1sectionhomepage2
---
Generating sitemap for structure Projects, siteId 2
Query 1/1 - elements: 39
......
........
```

But again the sitemaps are empty.
The only way I can consistently get full sitemaps is to go into the CMS and save an entry.

NB - We're running a headless craft install.

### To reproduce
Steps to reproduce the behaviour:
1. Go to sitemaps in browser and see they are empty.
2. in the command line regenerate sitemaps `./craft seomatic/sitemap/generate`
3. Go to sitemaps in browser and see they are still empty.
4. Save an entry
5. Sitemaps have content.

### Expected behaviour
1. Site maps will automatically re-generate if the cache/sitemap is cleared for whatever reason. 
2. If it was empty, `./craft seomatic/sitemap/generate` would populate them.

### Versions
- Plugin version: 4.0.9
- Craft version:  Craft Pro 4.3.1
--

**Comment by khalwat** [comment]
@anchovy can you please update to the latest version of SEOmatic (4.0.16 at the time of this writing) and ensure you still have the issue?

**Comment by khalwat** [comment]
Will re-open if more information is provided.

**Comment by bob-pixeldeluxe** [comment]
@khalwat I'm having the same issue on 4.0.16. The trigger for this is a space before the. <?xml tag
I checked for spaces before the php tag in the config files and main index.php but there are none.

**Comment by khalwat** [comment]
@bob-pixeldeluxe Please file a new issue with as many of the specifics of the problem you're having as possible.
