### ISSUE TITLE
Twig for reading images

### ISSUE THREAD

**Issue by ursbraem** [nystudio107/craft-seomatic#1254]
### Question
I have a section "Pages" with various entry types, like "Landing" or "Default".
The   fields differ from entry type to entry type. 

* On the "Landing" entry type, the image I need to use for SEO is `entry.heroImage`. 
* On the "Default" entry type, there's no hero, so I did make a field `entry.sharingImage`

Apparently, Seomatic Content SEO differs by section, but not further down by type. Right?
So I should have used the same field for the main image throughout all entry types in that section. 
Too late for that now.

Now I did this:

`{% switch entry.type %}{% case "landing" %}{{ seomatic.helper.socialTransform(entry.heroImage.collect()[0], "base", 1, "crop") }}{% default %}{{ seomatic.helper.socialTransform(entry.sharingImage.collect()[0], "base", 1, "crop") }}{% endswitch %}`

And for the alt text of the image:

`{% switch entry.type %}{% case "landing" %}{entry.heroImage.alt}{% default %}{entry.heroImage.alt}{% endswitch %}`

I'm under the impression this is correct, but I would appreciate any feedback if it's not or should be done otherwise preferrably.

**Comment by khalwat** [comment]
The Content SEO settings are on a per-entry type basis, so just set it to pull from the appropriate image field depending on the entry type:

<img width="586" alt="Screen Shot 2022-12-12 at 5 05 46 PM" src="https://user-images.githubusercontent.com/7570798/207165269-0dd9d6d6-4ca0-43de-a6ef-c1edd04ddccf.png">

**Comment by ursbraem** [comment]
ahhhhh! Thanks!
