### ISSUE TITLE
Internal Server error on Global SEO and Tracking Scripts tab

### ISSUE THREAD

**Issue by JordanMed** [nystudio107/craft-seomatic#1256]
### Describe the bug
When i go to the Global SEO or Tracking Scripts tab i receive an internal server error. The error shows as a 500 error in my console /admin/seomatic/global/general 500 & /admin/seomatic/tracking/gtag 500

This isn't a problem locally but it is a problem on my staging server and production server. 

### To reproduce
Steps to reproduce the behaviour:
1. Go to SEOMatic
2. Click on Global SEO or Tracking Scripts
3. See error message Internal Server Error

### Expected behaviour
I expect to see the dashboard for the Global SEO or Tracking Scripts. 

### Versions
- Plugin version: 3.4.41
- Craft version: 3.7.59

**Comment by khalwat** [comment]
Please provide the backtrace from the error?

**Comment by JordanMed** [comment]
yii\base\InvalidArgumentException: The file or directory to be published does not exist: /var/www/vendor/nystudio107/craft-code-editor/src/web/assets/dist in /var/www/vendor/yiisoft/yii2/web/AssetManager.php:461
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/AssetManager.php(35): yii\web\AssetManager->publish('/var/www/vendor...', Array)
#1 /var/www/vendor/yiisoft/yii2/web/AssetBundle.php(185): craft\web\AssetManager->publish('/var/www/vendor...', Array)
#2 /var/www/vendor/yiisoft/yii2/web/AssetManager.php(288): yii\web\AssetBundle->publish(Object(craft\web\AssetManager))
#3 /var/www/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle('nystudio107\\cod...', Array, true)
#4 /var/www/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('nystudio107\\cod...')
#5 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1566): yii\web\View->registerAssetBundle('nystudio107\\cod...')
#6 /var/www/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
#7 /var/www/storage/runtime/compiled_templates/ef/ef59c4e026f9236defed1e2b2a13c764473973ee2bd65af09b1f7e9af91ca379.php(86): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
#8 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1169): __TwigTemplate_e55406ee83743b15feb43f1e124eaa88ac0722fac470d658843548f5539d1e18->macro_includeJs('seoTitle', 'SeomaticExpress...', Array, Array)
#9 /var/www/storage/runtime/compiled_templates/ef/ef59c4e026f9236defed1e2b2a13c764473973ee2bd65af09b1f7e9af91ca379.php(258): twig_call_macro(Object(__TwigTemplate_e55406ee83743b15feb43f1e124eaa88ac0722fac470d658843548f5539d1e18), 'macro_includeJs', Array, 58, Array, Object(Twig\Source))
#10 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1169): __TwigTemplate_e55406ee83743b15feb43f1e124eaa88ac0722fac470d658843548f5539d1e18->macro_textField(Array, 'SeomaticExpress...', Array, Array)
#11 /var/www/storage/runtime/compiled_templates/79/792dc987846a646a6190892f24e6df03d1297dd2f1f8e14d18c1b1218d86cac1.php(314): twig_call_macro(Object(__TwigTemplate_e55406ee83743b15feb43f1e124eaa88ac0722fac470d658843548f5539d1e18), 'macro_textField', Array, 53, Array, Object(Twig\Source))
#12 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1169): __TwigTemplate_c9625a6c72e50abb5c2057b09e3ab12af4b7eb58bafc5c7d597ccbffd32f01f7___1810866179->macro_seoTitleField(Array, Array, Object(nystudio107\seomatic\models\Settings), Object(nystudio107\seomatic\models\MetaBundleSettings), Object(nystudio107\seomatic\models\MetaGlobalVars), '', 'global')
#13 /var/www/storage/runtime/compiled_templates/79/792dc987846a646a6190892f24e6df03d1297dd2f1f8e14d18c1b1218d86cac1.php(142): twig_call_macro(Object(__TwigTemplate_c9625a6c72e50abb5c2057b09e3ab12af4b7eb58bafc5c7d597ccbffd32f01f7___1810866179), 'macro_seoTitleF...', Array, 89, Array, Object(Twig\Source))
#14 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_c9625a6c72e50abb5c2057b09e3ab12af4b7eb58bafc5c7d597ccbffd32f01f7___1810866179->block_field(Array, Array)
#15 /var/www/storage/runtime/compiled_templates/0b/0b54e252e2d70ca5999d1028562cd975509d5d877099b9a3228ada419f2f0775.php(134): Twig\Template->displayBlock('field', Array, Array)
#16 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e18f64c1d30f29751d02910cd276315ccdaa6425663a599e92f292df34d864be->doDisplay(Array, Array)
#17 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/storage/runtime/compiled_templates/79/792dc987846a646a6190892f24e6df03d1297dd2f1f8e14d18c1b1218d86cac1.php(118): Twig\Template->display(Array, Array)
#19 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c9625a6c72e50abb5c2057b09e3ab12af4b7eb58bafc5c7d597ccbffd32f01f7___1810866179->doDisplay(Array, Array)
#20 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/storage/runtime/compiled_templates/79/792dc987846a646a6190892f24e6df03d1297dd2f1f8e14d18c1b1218d86cac1.php(51): Twig\Template->display(Array)
#22 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c9625a6c72e50abb5c2057b09e3ab12af4b7eb58bafc5c7d597ccbffd32f01f7->doDisplay(Array, Array)
#23 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /var/www/storage/runtime/compiled_templates/03/039c67ab25ec0f522de56a2b783d7a6a12646fffe2374fec05eec2b394d84c4e.php(83): Twig\Template->display(Array)
#25 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e2110e60851f39b5680b202730130b30ba7b91d92db7d6a58f12b5d6eb7ee9ab->doDisplay(Array, Array)
#26 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#27 /var/www/storage/runtime/compiled_templates/46/469991c9bde7a6d2210bf120ea455e3ecc14522ca9783baf5fcf6abe56e7b573.php(133): Twig\Template->display(Array)
#28 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_44b8775c50c7652ca2ff6bf57b2e5ece5ef9529793f7be7c86c1d263cbe64bf9->block_content(Array, Array)
#29 /var/www/storage/runtime/compiled_templates/57/578ce4129f5c0f4b7f44de32164402ef497c1a92ddce1dd29e77969e9dc62517.php(547): Twig\Template->displayBlock('content', Array, Array)
#30 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_9ac12c23b85e104363ca65c4c4dbefb09afa0267c708381af03c9a7724e7ea69->block_main(Array, Array)
#31 /var/www/storage/runtime/compiled_templates/57/578ce4129f5c0f4b7f44de32164402ef497c1a92ddce1dd29e77969e9dc62517.php(358): Twig\Template->displayBlock('main', Array, Array)
#32 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_9ac12c23b85e104363ca65c4c4dbefb09afa0267c708381af03c9a7724e7ea69->block_body(Array, Array)
#33 /var/www/storage/runtime/compiled_templates/13/136f6b9f297ee69077ed36ec3ccfec64add123d2e942b6d14f00519204932f92.php(91): Twig\Template->displayBlock('body', Array, Array)
#34 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2b39f2f9d199175575bb390cdfdd40a76db3bdbb60d56b885fe78f4ccac2b6c8->doDisplay(Array, Array)
#35 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#36 /var/www/storage/runtime/compiled_templates/bc/bc29e0d4688c98237b533575408b8b1c9d47eb583ef5b10af71d76812c659a9c.php(56): Twig\Template->display(Array, Array)
#37 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_3d69178e1aa429746d36e61fbb950170a990262d0c66ac38d70e41d835b9fb4a->doDisplay(Array, Array)
#38 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#39 /var/www/storage/runtime/compiled_templates/57/578ce4129f5c0f4b7f44de32164402ef497c1a92ddce1dd29e77969e9dc62517.php(172): Twig\Template->display(Array, Array)
#40 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_9ac12c23b85e104363ca65c4c4dbefb09afa0267c708381af03c9a7724e7ea69->doDisplay(Array, Array)
#41 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#42 /var/www/storage/runtime/compiled_templates/2c/2ca8fce5d5c72b1e7121db073e70b685382991ccbfc493708ced2537072f6510.php(44): Twig\Template->display(Array, Array)
#43 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_3cc3e5d3ad5ba449c49f8bebea75fde72f9c342fca57506236ad607554d46f76->doDisplay(Array, Array)
#44 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#45 /var/www/storage/runtime/compiled_templates/a3/a34be3546ff2f55a7362a4cd0bb3d5804219aff4c450e1679ebe5768dcb66b2f.php(85): Twig\Template->display(Array, Array)
#46 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_80008a2b9c3ed3afe4c7ddff3920339a53add66b8b9639945100f4576076807e->doDisplay(Array, Array)
#47 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#48 /var/www/storage/runtime/compiled_templates/46/469991c9bde7a6d2210bf120ea455e3ecc14522ca9783baf5fcf6abe56e7b573.php(53): Twig\Template->display(Array, Array)
#49 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_44b8775c50c7652ca2ff6bf57b2e5ece5ef9529793f7be7c86c1d263cbe64bf9->doDisplay(Array, Array)
#50 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#51 /var/www/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#52 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#53 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#54 /var/www/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('seomatic/settin...', Array)
#55 /var/www/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('seomatic/settin...', Array)
#56 /var/www/vendor/craftcms/cms/src/web/Controller.php(205): craft\web\View->renderPageTemplate('seomatic/settin...', Array, 'cp')
#57 /var/www/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php(418): craft\web\Controller->renderTemplate('seomatic/settin...', Array)
#58 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionGlobal('general', NULL, NULL, NULL)
#59 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#60 /var/www/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#61 /var/www/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('global', Array)
#62 /var/www/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('seomatic/settin...', Array)
#63 /var/www/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('seomatic/settin...', Array)
#64 /var/www/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest(Object(craft\web\Request))
#65 /var/www/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#66 /var/www/html/index.php(26): yii\base\Application->run()
#67 {main}

**Comment by khalwat** [comment]
Looks to me like there might be an issue with your deployment, somehow it didn't properly install the package `nystudio107/craft-code-editor`

You can try this on production:

```
composer update nystudio107/craft-code-editor
```

If that fails, you might need to delete the actual directory `vendor/nystudio107/craft-code-editor` and the install it again via:

```
composer install nystudio107/craft-code-editor
```
