### ISSUE TITLE
Site name position as global setting

### ISSUE THREAD

**Issue by yingban** [nystudio107/craft-seomatic#1258]
### Is your feature request related to a problem? Please describe.
As the site name position might be consistent in a website, would it be possible to add a global setting "siteNamePosition" usable in seomatic.php?

### Describe the solution you would like
I would like to have a global setting named "siteNamePosition" in seomatic.php with following options allowed: "Before", "After", "None".
The value would overwrite the value in Global SEO > General settings.

**Comment by khalwat** [comment]
So the global setting is what you set in **Global SEO > General settings**

It will be used everywhere by default, unless you override it on a per-section or per-entry basis explicitly.
