### ISSUE TITLE
Last update breaks all custom fields

### ISSUE THREAD

**Issue by atelieridc** [nystudio107/craft-seomatic#1262]
Since last update, this works {entry.title}, this not {{ entry.title }} for custom text.
Also the from field option, doesn't work.

**Comment by khalwat** [comment]
What version are you using?

Please update to the latest version, I released a patch an hour ago.

**Comment by atelieridc** [comment]
4.0.18 on Craft CMS 4.3.6.1. Just saw the patch, testing it now... and it works again, Thanks
