### ISSUE TITLE
GTM ID incorrect

### ISSUE THREAD

**Issue by angieherrera** [nystudio107/craft-seomatic#1263]
On a multi-site setup I manage, there are a few sites (not all of them) that have GTM IDs. In one particular site, the code is showing the wrong ID regardless of what I put in the Google Tag Manager ID field. It's the only site doing this; others are fine.

I tried disabling and re-enabling GTM for that site, and that did remove the GTM code, but on re-enabling it still showed the incorrect ID. I also cleared SEOmatic caches under the Caches utility, but that didn't do anything for this issue.

I'm not sure where it's pulling the incorrect ID from and why the front-end isn't updating. This is on Craft 3.7.61 and SEOmatic 3.4.42.

**Comment by khalwat** [comment]
First, I'd search your codebase to ensure it isn't something that's outside of SEOmatic.

If that's not the case, then you may want to check each site in the per-site settings for SEOmatic's GTM ID:

<img width="840" alt="Screen Shot 2023-01-11 at 3 14 25 PM" src="https://user-images.githubusercontent.com/7570798/211908473-e3e413d0-9eb9-4075-9545-bc34accb2ac8.png">

**Comment by angieherrera** [comment]
I hadn't searched the codebase, but a search for GTM-related stuff came up with nothing.

I did look at each site in the per-site settings (there are ~20 😅). Several do not have GTM enabled. The few that do are showing the correct ID in the source code except for this one site.

**Comment by khalwat** [comment]
If you turn OFF GTM in SEOmatic for that one site, does it still appear?

**Comment by angieherrera** [comment]
Turned out to be an issue with the script template! 🤦‍♀️
