### ISSUE TITLE
[FR]: Redirects in SEOmatic

### ISSUE THREAD

**Issue by mikesnoeren** [nystudio107/craft-seomatic#1264]
Happy SEOmatic user here. I find the plugin very useful for SEO optimization. However, I have noticed that it does not currently include the ability to add redirects.

Adding a page or section within the plugin where clients can easily add and manage redirects would greatly benefit them. This is important for SEO as it helps to maintain the integrity of website link structure and prevent loss of link juice during website (re)development.

Thank you for your time and consideration.

**Comment by khalwat** [comment]
This is something you'd use our SEOmatic plugin for:

https://plugins.craftcms.com/retour
