### ISSUE TITLE
Sitemap Last Modified Date Shows Wrong Date

### ISSUE THREAD

**Issue by ncaroyannis** [nystudio107/craft-seomatic#1267]
### Describe the bug
We have a set of sitemaps generated by seomatic which are showing the last modified date incorrectly.

### To reproduce
Steps to reproduce the behaviour:
1. Create a new section in CraftCMS
2. Add a new entry
4. Add another new entry for a later date
5. Generate the sitemaps - it will show the Last Modified date as the date of the first entry, but it should actually be the date of the newest entry

### Expected behaviour
The Last Modified date should show the newest entry's date, not the first entry found.

### Screenshots
<img width="806" alt="Screen Shot 2023-01-18 at 6 46 42" src="https://user-images.githubusercontent.com/5357396/213019883-27794ae3-147c-4596-ad14-8e06baf0c450.png">
<img width="805" alt="Screen Shot 2023-01-18 at 6 51 10" src="https://user-images.githubusercontent.com/5357396/213020254-132226bd-ded5-48dd-a13a-bc98c00d5223.png">

### Versions
- Plugin version: 3.4.48
- Craft version: 3.7.40

**Comment by khalwat** [comment]
So I just ran a test locally, and this seems to be working as expected.

**Before** adding a new entry to the `blog` section:

<img width="844" alt="Screen Shot 2023-01-24 at 12 02 09 PM" src="https://user-images.githubusercontent.com/7570798/214360853-a1c09e7c-9972-48b7-8fb9-b1883d9a8cd2.png">

<img width="844" alt="Screen Shot 2023-01-24 at 12 02 13 PM" src="https://user-images.githubusercontent.com/7570798/214360908-28c4b402-b53d-4ae7-81f3-820621ca73ac.png">

**After** adding a new entry to the `blog` section:

<img width="839" alt="Screen Shot 2023-01-24 at 12 08 36 PM" src="https://user-images.githubusercontent.com/7570798/214360969-177ee90e-d5c5-4469-9081-90d70a53a195.png">

<img width="839" alt="Screen Shot 2023-01-24 at 12 08 47 PM" src="https://user-images.githubusercontent.com/7570798/214361027-4f5cd11f-fd88-4455-963e-46564acc33e7.png">

As to why it's not updating in your case, here are some things to check:

* Are there any layers of caching involved here (static cache, browser cache, etc.)?
* Is the entry in the same site and entry type as the sitemap?
* Is the new entry live and propagated to the site in question?
