### ISSUE TITLE
Generate Dynamic Images

### ISSUE THREAD

**Issue by shifuma** [nystudio107/craft-seomatic#1268]
### Is your feature request related to a problem? Please describe.
I have a site with lots of content being added constantly via a feed. It would be nice to be able to generate social images based on the title/other content of the entry.

### Describe the solution you would like
Something very basic, setting a background color/image, then the text you would like to show.

### Describe alternatives you have considered
I'm looking into this: https://ghijk.co.uk/blog/generate-dynamic-social-share-images-in-craft-cms
It's a bit of a setup and doesn't come with the other major features of SEOmatic.

### Additional context
Sorry if this has already been asked! I had a look but couldn't see any similar requests.

**Comment by khalwat** [comment]
This is something that is in the works, stay tuned!
