### ISSUE TITLE
Sitemaps are not generated

### ISSUE THREAD

**Issue by mikewink** [nystudio107/craft-seomatic#1269]
### Describe the bug

For an unknown amount of time, SEOmatic does not create the XML sitemap correctly anymore. We use the plugin in a multitude of other projects, and it works fine there. We checked the settings and they are the same. Yet, in this one project, all we get is the note, as seen in the screenshot below. The index list works as expected.

I tried to recreate from the CP and via the CLI. Both ways do not report any error or fail.

### To reproduce

- I clear the sitemap caches in the CP
- I clear all the SEOmatic caches
- I run `php craft seomatic/sitemap/generate` to create sitemaps from the CLI

### Expected behaviour

I would expect that the system renders a list of entries when I click a link in the XML Sitemap Index.

### Screenshots

<img width="871" alt="Screenshot 2023-01-23 at 09 19 59" src="https://user-images.githubusercontent.com/85063626/213994106-fea70ab1-9578-42bb-b495-8eb0db936e8d.png">

### Versions
- Plugin version: 4.0.16
- Craft version: 4.3.5

**Comment by khalwat** [comment]
Please update SEOmatic to the latest version `4.0.19` at the time of this writing, and see if you continue to have the issue.

I will re-open the issue if you continue to have problems with it.

**Comment by mikewink** [comment]
Hello, sorry for the late reply. I was finally able to update our production site. It still does not work. I did the update locally first, and there it works as intended. 

I cleared all caches, ran the CLI command. Does the sitemap generation write any files to the system?

**Comment by khalwat** [comment]
Nope, it doesn't write anything to the file system, it saves them in the cache.

What is your caching method for this website?

**Comment by mikewink** [comment]
All I have done is switch on `ENABLE_TEMPLATE_CACHING=1` and `RUN_QUEUE_AUTOMATICALLY=1`. There is no special setup or alternative configuration. In `general.php` I have `'cacheDuration' => false` and that is it.

**Comment by khalwat** [comment]
So if you've done nothing, then Craft defaults to using file-based caching. I don't know what your server setup is, but perhaps something is deleting things from the cache?

**Comment by mikewink** [comment]
I will look into that. Could it be permission rights issues too? The server was set up pretty strict by the company IT department. Where would those files end?

**Comment by khalwat** [comment]
`storage/runtime/cache/`

https://craftcms.com/docs/3.x/config/#cache-component
