### ISSUE TITLE
Randomly hanging when trying to do image transformations

### ISSUE THREAD

**Issue by RosanaRufer** [nystudio107/craft-seomatic#127]
I had this issue before, and thought it was because my asset volumes were not correctly configured.

Now the volumes seem to be correctly configured and normal image transformations properly work. However I still experience the server randomly hangs (in local it hangs forever until I shut down MAMP, in production it can cause a 500 if I enable image transformations)
The error I can see in the logs is 

```
2018-05-31 20:48:38 [::1][1][-][error][nystudio107\seomatic\helpers\MetaValue::parseMetaString]
Error rendering `{seomatic.helper.socialTransform(object.entry.blogEntryThumbnail[0], "base", 2)}` 
-> An exception has been thrown during the rendering of a template ("The file 
"Existing_File_Name_600x300px_.png" does not exist,") in 
"__string_template__274ed3da0fd7e0bc1d5a4715863c4f5eb8c19c8746d0350692d62c0a6f2d1b6e"
at line 1.
```

I can't demonstrate this is caused by SEOmatic, It could be a misconfiguration in my multi-site, but I wanted to add this issue in case someone else had this problem and knows how to solve it.

In the next days, I will try to reproduce in my blank site like I did with the issue 107. Or, if I find the source of the problem, update the thread.

**Comment by RosanaRufer** [comment]
I think I've found the source of the problem and it has not, luckily to do with SEOmatic.

I have a multi-site where sites share the same images (because each site is in a different language), and the main site's index.php si under `web/` but the rest of the sites' index.php are under their `web/<language-name>/` folder. 
The Assets base path was starting with `@webroot`, which points to `web/` for the default site and `web/de` for dutch site... etc. Instead, it should be using `@root`, followed by the absolute path to the images directory.

Why it was *randomly failing* is because this wrong setting _works for the default site_ and image transformations stay cached after they were requested for the primary site, so they seemed to work until a new non-cached transformation was requested.

What I still don't know is why getUrl() worked for all sites but getUrl('imageTransformation') didn't.

**Comment by khalwat** [comment]
Ahh thanks for the info
