### ISSUE TITLE
Updated asset fields not reflected on page update in specific SEOMatic context

### ISSUE THREAD

**Issue by sonoflee** [nystudio107/craft-seomatic#1270]
Hello! I'm submitting this as a support request because I'm not 100% sure of whether this is a Blitz issue or an SEOMatic issue - I've posted the same info on the Blitz repo.  Happy to file as a bug report if needed. 

On a Craft site using Blitz and SEOMatic, with an image gallery system that uses assets with custom fields like "artist," "medium," "description," etc. 

- Custom templates are used to create work "entry" pages with a URL structure of site-url/work/assetId; the asset(image) and custom asset fields are displayed on that template. 
- On these "entry" pages, I'm also using these custom asset fields to create meta titles, descriptions, and other values, via  SEOMatic's "[do seomatic.meta](https://nystudio107.com/docs/seomatic/using.html#seomatic-variables)" method - `{% do seomatic.meta.seoTitle( asset.workCaption ??? asset.workTitle ??? asset.title )%}`

I recently ran into an issue when updating the artist name, title, and description for a work. 

On **production**, where Blitz is enabled, the updated asset field values are displayed correctly on the page when saved, but the SEOmatic-generated meta tags do not update - they still display the old information for page title, meta description, etc. Refreshing the Blitz cache for that page does not have any effect.

On the **development** version of the same site, where Blitz is disabled, the updated asset field values are displayed correctly on the page _and_ in the SEOmatic-generated meta tags when saved.  The page and meta tags are also both correct if I disable the Blitz cache on production with `do craft.blitz.options({ cachingEnabled: false }) %}`.

It seems like the SEOMatic values are being cached here in a way that doesn't want to refresh - related to not being an actual type of entry, maybe? - so wondering if there's a simple way to address. Any assistance is appreciated!

**Comment by khalwat** [comment]
SEOmatic caches things on a per-URI basis:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting

If you have a Twig expression in an SEOmatic field that has data coming from another source (in this case, an Asset), if you update the Asset itself, SEOmatic won't know that the cache needs to be invalidated.

You'll need to either bust the cache manually, or re-save the entry that uses the modified Assets (which will clear the cache for that entry).

You don't see it happen on development, because the caching layer lasts for only 30 seconds there.

**Comment by sonoflee** [comment]
Thanks for the quick answer, @khalwat - very helpful! In this case, since there isn't an entry per se (the asset itself is the "entry" that's the source of info for the template) it sounds like the cache would need to be cleared manually for these. 

Is there a way to query the date/time the SEOMatic container was cached?  I'm hoping I could programmatically bust the cache if the asset's _dateUpdated_ value is more recent.
