### ISSUE TITLE
SEO/Social image allows selecting an SVG, but then doesn't use the image

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#1271]
### Describe the bug
When you select and SVG as social or SEO image, the preview doesn't work. I believe it's due to the fact that the SVG cannot be cropped to the desired transform, and a transform is selected.

### To reproduce
Steps to reproduce the behaviour:
1. Add a SVG image as a social or seo image
2. Check-out the preview

### Expected behaviour
Disallow SVG's to be used or ignore the transform

### Versions
- Plugin version: 4.0.19
- Craft version: 4.2.5.2

**Comment by khalwat** [comment]
So it should work if you have the proper underlying support. SEOmatic just uses Craft transforms to transform the SVG, and if you have ImageMagick installed, it should work fine.

Test out a regular Craft transform with the resulting file type being JPEG and see if that works. If it doesn't very likely you will need to update your image driver for PHP to use ImageMagick.
