### ISSUE TITLE
Implementing Google Tag Manager for Conversion Tracking

### ISSUE THREAD

**Issue by libby98** [nystudio107/craft-seomatic#1272]
### Question
We've swapped over to Google Tag Manager for all conversion tracking (UA, GA4 and Google Ads). As a result, we've had to turn off the gtag within the plugin but we're no longer able to differentiate within the dashboard which leads have come through paid or organic search. 

We're still able to differentiate within Google Analytics but just not within the dashboard. Is it necessary to have the gtag.js enabled, or do I need an extra step when implementing tracking within Google Tag Manager?

**Comment by khalwat** [comment]
So this really has nothing to do with SEOmatic... but if you start using Google Tag Manager, typically you then set up everything inside of GTM.

**Comment by libby98** [comment]
Sorry, I guess my question is, do I need to add anything else from the plugin scripts to Google Tag Manager so we can start seeing these differences again?

Everything is set up within GTM and conversions are being tracked, just no differences between paid and organic.

**Comment by khalwat** [comment]
Nope, the script's purpose is just to add the GTM script to the page -- everything else should be set up inside of GTM
