### ISSUE TITLE
[FR] Possibility to set SEOmatic Site Name with env variable

### ISSUE THREAD

**Issue by Antimated** [nystudio107/craft-seomatic#1273]
### Is your feature request related to a problem? Please describe.
I would like to use an env variable for setting the Site name (default craft system setting) as well for the **SEOmatic site name**.
I tried this and it displays correctly in the **title tag** on the front-end. But when I try to display it on the front-end via `seomatic.site.siteName` it displays as `$SITE_NAME`

Title tag example:
![Screenshot 2023-01-27 at 09 36 43](https://user-images.githubusercontent.com/2869409/215043230-8acb226a-633e-4b7d-9ee1-b95e4b6d1fbb.png)

![Screenshot 2023-01-27 at 09 38 13](https://user-images.githubusercontent.com/2869409/215043496-aea4b8b5-b453-4b5a-9db1-2a7b9fd51de9.png)

### Describe the solution you would like
Support for .env variables (the same way you can use env variables for the Entity URL.)

**Comment by khalwat** [comment]
So this already works, you just need to parse it before display, via:

```twig
{{ seomatic.site.parsedValue('siteName') }}
```

docs: https://nystudio107.com/docs/seomatic/using.html#seomatic-variables
