### ISSUE TITLE
Issues with /sitemap.xml 302 redirect?

### ISSUE THREAD

**Issue by PhilReinking** [nystudio107/craft-seomatic#1274]
### Question
I got a question from our SEO team regarding the redirect happening from `/sitemap.xml` to `/sitemaps-1-sitemap.xml`.

We wonder why this is done with a `302` and not with a `301` redirect?
They also claim that this might be confusing for the Robots reading the sitemap?

Is there any way to serve the index sitemap from the `/sitemap.xml` path?

**Comment by khalwat** [comment]
It could be a 301 or a 302; the 302 is used because it's more correct for the situation.

I am not aware of any way this could be causing an issue with bots; it's been this way for years.  If the SEO company can provide any evidence or data that it does, I'd be happy to look at it.

**Comment by khalwat** [comment]
Also I forgot to mention that _most_ bots (including GoogleBot) look at your `/robots.txt` first, to know where to look for sitemaps.

SEOmatic by default will point them directly to `/sitemaps-1-sitemap.xml` in the `/robots.txt` that it generates for you (though you can override this to be anything you want).

So the `/sitemap.xml` -> `/sitemaps-1-sitemap.xml` redirect is there only for bots that do not obey `/robots.txt` and instead hard-code it to look for only `/sitemap.xml`
