### ISSUE TITLE
Print twitter cards without a handle

### ISSUE THREAD

**Issue by AramLoosman** [nystudio107/craft-seomatic#1275]
### Question
We've used this plugin for a customer which has no twitter account. It seems however, that the twitter card information is only put into the page if there is a twitter handle present.

As per twitters developer documentation the twitter:site and twitter:creator tags are not required for a vaild twitter card.
https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

 Is there a possibility to print the twitter card without having a twitter account/handle?

**Comment by khalwat** [comment]
Do said Twitter cards pass the Twitter Card Validator if they lack the Twitter handle?

At least at one point, I know Twitter required a Twitter handle to be there.

**Comment by khalwat** [comment]
Will re-open if additional information is provided.

**Comment by AramLoosman** [comment]
I've tested with the URL https://www.gdk-cds.ch/de/gesundheitsversorgung on https://cards-dev.twitter.com/validator and got no error.

The following screenshot shows the relevant section from the docs:
![grafik](https://user-images.githubusercontent.com/1239297/225337557-8245d401-3e01-434d-a2f8-efd4939f2ebe.png)

**Comment by ursbraem** [comment]
@khalwat Could you reopen?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/af5193ff8d222b66bc38651683732ae6c005036d & https://github.com/nystudio107/craft-seomatic/commit/79ecb66917b66a15f3c27614afb67dfbef5943a6

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.52”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.23”,
```
Then do a `composer clear-cache && composer update`

**Comment by ursbraem** [comment]
Thank you! Works!

![ScreenShot 2023-03-23 at 21 54 54@2x](https://user-images.githubusercontent.com/1446443/227357492-5dc9f11d-8937-48b8-a0fd-9a1eb3c8afec.jpg)

In the SEOMatic Module, there's still a warning:

![ScreenShot 2023-03-23 at 21 53 59@2x](https://user-images.githubusercontent.com/1446443/227357673-0e984379-45f7-4d3f-b0c7-1a960cebba57.jpg)

**Comment by khalwat** [comment]
Pushed a fix for the preview, do this again for the changes:

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.52”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.23”,
```
Then do a `composer clear-cache && composer update`

**Comment by ursbraem** [comment]
Perfect, thanks!
![ScreenShot 2023-03-24 at 13 10 27@2x](https://user-images.githubusercontent.com/1446443/227517821-f51b4f59-179c-4b16-92cd-584448308be2.jpg)
