### ISSUE TITLE
Local Business Schema per entry

### ISSUE THREAD

**Issue by iamtompickering** [nystudio107/craft-seomatic#1276]
### Is your feature request related to a problem? Please describe.
Currently you are able to add Local Business Schema globally to the site, but I am wondering whether it is possible to specify different Local Business Schema per entry on a site? Our usecase is that we have several location pages which require different information e.g. opening hours, contact numbers, location etc. 

### Describe the solution you would like
An option to set Local Business schema per entry. Possibly adding as an option which you can enable when creating an SEOMativ field type.

**Comment by khalwat** [comment]
Yes, you can do this using the Twig APIs to build the schema yourself.

https://nystudio107.com/docs/seomatic/using.html#twig-templating

Here are some examples that might help:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples
