### ISSUE TITLE
Override hreflang only work in the first page on paginated pages.

### ISSUE THREAD

**Issue by nnuyit** [nystudio107/craft-seomatic#1278]
### Describe the bug
We have several blog pages and we need to custom the hreflang tag.
We follow the example in your [documentation](https://nystudio107.com/docs/seomatic/using.html#link-meta-object-functions-seomatic-link), it only works in the first page.
We dump value of "alternate" in the second page, the value is correct, but it renders a default value which we do not want. 

### To reproduce
Steps to reproduce the behaviour:
1. Try to override the hreflang tag by any value on paginated pages. 
2. Go to second page.
3. The default value will be rendered even though the "alternate" variable is overridden

### Versions
- Plugin version: 3.4.48
- Craft version: Craft Pro 3.7.33

**Comment by khalwat** [comment]
Can you provide me with some Twig code, to show me what you're doing?

Also at a higher level, what are you wanting to change the `hreflang` to and for what purpose?

**Comment by khalwat** [comment]
Will re-open if additional information is provided.

**Comment by nnuyit** [comment]
In page one we are able to remove hreflang="de-de": view-source:
https://www.opswat.com/blog/category/advanced-threat-prevention
In page two it happen again: view-source:
https://www.opswat.com/blog/category/advanced-threat-prevention/p2


Nelson Nguyen
PHP Full Stack Web Developer
m: #sensitive#
e: ***@***.***

**Comment by khalwat** [comment]
What is the reason for wanting to remove the `de-de` hreflang? The hreflang will only appear if there is a translation of that element in that language
