### ISSUE TITLE
JsonLD image should include domain

### ISSUE THREAD

**Issue by jordikroon** [nystudio107/craft-seomatic#128]
According to the Google structured data validator tool, images should include the full domain.

Right now, it's rendered as an absolute url without the domain. E.g: /path/to/image.jpeg instead of https://domain.tld/path/to/image.jpeg.

Google will return an error when on that attribute saying that the url.image value is invalid.

**Comment by khalwat** [comment]
It's rendering it as whatever the asset URL returns as. If you have your Asset Volumes set up to use aliases with full URLs, it will return a full URL.

for instance, if you look at the JSON-LD here: https://nystudio107.com/blog/profiling-your-website-with-craft-cms-3s-debug-toolbar by viewing the source, you'll see:

```
<script type="application/ld+json">{"@context":"http://schema.org","@type":"WebPage","author":{"@id":"https://nystudio107.com/#identity"},"copyrightHolder":{"@id":"https://nystudio107.com/#identity"},"copyrightYear":"2018-04-09T10:09:00-04:00","creator":{"@id":"https://nystudio107.com/#creator"},"dateModified":"2018-04-09T10:19:27-04:00","datePublished":"2018-04-09T10:09:00-04:00","description":"Craft CMS 3 has some big changes under the hood, one of which is the addition of the Debug Toolbar that helps you profile and debug your websites","headline":"Profiling your Website with Craft CMS 3's Debug Toolbar","image":{"@type":"ImageObject","url":"https://nystudio107-ems2qegf7x6qiqq.netdna-ssl.com/img/blog/_1200x630_crop_center-center_82_none/craft-cms-debug-toolbar-debugging.jpg"},"inLanguage":"en","mainEntityOfPage":"https://nystudio107.com/blog/profiling-your-website-with-craft-cms-3s-debug-toolbar","name":"Profiling your Website with Craft CMS 3's Debug Toolbar","publisher":{"@id":"https://nystudio107.com/#creator"},"url":"https://nystudio107.com/blog/profiling-your-website-with-craft-cms-3s-debug-toolbar"}</script>
```

...with a fully qualified URL for the image.

That said, I can potentially look at forcing any `url` key to be a full URL if one is not provided.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/3b6909bc0550fd767e37060170b1404a4f34375c
