### ISSUE TITLE
[FR] - Add Mastodon card

### ISSUE THREAD

**Issue by anvme** [nystudio107/craft-seomatic#1280]
Add PreviewCard - Mastodon 
Doc:  https://docs.joinmastodon.org/entities/PreviewCard/

**Comment by khalwat** [comment]
From the description, it appears that it just uses Facebook OpenGraph tags to generate the cards? If that's the case, SEOmatic will already generate these for you...

**Comment by khalwat** [comment]
Yeah this isn't needed -- Mastodon just pulls from the Facebook OpenGraph data that SEOmatic already generates.
