### ISSUE TITLE
Inactive override settings seem to be used

### ISSUE THREAD

**Issue by ishetnogferre** [nystudio107/craft-seomatic#1282]
### Describe the bug
We've setup the SEO defaults in the global settings and on a SEO content level.
For the sitename, both say it should put the sitename AFTER the title, but both the snippet and in the database set it BEFORE.

### To reproduce
Steps to reproduce the behaviour:
1. Set the Global SEO "Site Name Position" to "After"
2. Set the Content SEO for (page) entry to "Same as Global Site Name Position".
3. Override a random item from the SEO General tab. 

### Expected behaviour
The siteName should be AFTER the title. Not using the "Custom Position > Before" that is greyed out.

### Screenshots
Below screenshots for the settings on the entry itself, the site and content settings and what is displayed in the database for that entry.

![SEO-entry-settings](https://user-images.githubusercontent.com/6649706/217490680-e4210fdc-97ef-4da4-8685-90d15fbbcec9.png)
![SEO-site-settings](https://user-images.githubusercontent.com/6649706/217490685-dfb4df87-d445-425c-964d-8ed64da29f33.png)
![SEO-content-settings](https://user-images.githubusercontent.com/6649706/217490674-24d9d120-99e7-4d8f-99c1-5466878f5b3c.png)
![SEO-table-settings](https://user-images.githubusercontent.com/6649706/217490691-8f8d10a4-af6f-4c98-9f58-2b004067caa8.png)

### Versions
- Plugin version: 4.0.19
- Craft version: 4.3.8

**Comment by khalwat** [comment]
I tried to reproduce this, but was unable to.

Are you seeing this behavior with any other sections in the same site?

**Comment by ishetnogferre** [comment]
I double-checked and it does seem to happen only with the pages section (structure). The others are fine.

When we for example make a new blog (other section) the settings are correct, but when a new page is made, the settings are the "before" one.

<img width="359" alt="Screenshot 2023-02-13 at 16 19 20" src="https://user-images.githubusercontent.com/6649706/218498206-1390864e-2fff-41c3-b04f-cb45009f051c.png">
**Blog section**

<img width="301" alt="Screenshot 2023-02-13 at 16 19 05" src="https://user-images.githubusercontent.com/6649706/218498201-e913b063-7875-491f-82c9-ed5c61f41521.png">
**Pages section**

**Comment by khalwat** [comment]
Do you have multiple entry-types or a multi-site setup?

SEOmatic allows you to save section settings on a per-entry type basis, as well as a per-site basis.

**Comment by ishetnogferre** [comment]
Pages only has 1 entry type and is used on 4 sites. All were on the correct settings, I changed some other global content settings and (re)saved there and that seemed to have fixed it now, so I'll guess this can get closed for now and we'll keep an eye on it and if it occurs again, reopen. Thanks!

<img width="369" alt="Screenshot 2023-02-14 at 09 29 34" src="https://user-images.githubusercontent.com/6649706/218681223-3d2a0283-dc29-43f3-9c76-f3bb487d424e.png">
