### ISSUE TITLE
Whether the sitemap generation could be set to run via Cron job

### ISSUE THREAD

**Issue by market-south** [nystudio107/craft-seomatic#1283]
### Question
Hi there, 

We have an e-commerce site that has 1000+ products with 12000+ variants and 700+ categories. The details of the products get synced with an ERP system overnight every day. We had the "Regenerate Sitemaps Automatically" enabled with the "Async Queue" plugin.  SEOmatic is doing a great job of generating a sitemap. 

The issue is that around 100,000+ jobs are queued every day that are triggered by SEOmatic. Considering the web server limitation we had to disable the automatic sitemap generation and run manually via CLI. But the change frequency is almost daily of the entries being updated with new data from ERP.  Which needs us to run the CLI command daily. which is not feasible in this case.

I wonder whether we could set up the sitemap generation via the CRON job.

**Comment by khalwat** [comment]
Sure, you could do it via Cron if you wanted to.

However, keep in mind that sitemaps are about _discovery_, not about indexing. What that means is that once Google or another indexing bot has a URL in its index, doesn't matter whether it is in the sitemap at all anymore.

So you might consider setting the Sitemap Limit setting to be `100`, so each sitemap will contain at most the 100 most recently changed URLs from each section.

This will limit the load on your server, and then also GoogleBot will have less to digest each time it looks at your sitemap to see what has changed.

**Comment by rellafella** [comment]
I had the same thought of switching to a cron for this too and was lead here.

> So you might consider setting the Sitemap Limit setting to be `100`, so each sitemap will contain at most the 100 most recently changed URLs from each section.

I can't see this `Sitemap Limit` setting either in the ui, or the config.php, are you able to point me in the right direciton?

Running SEOmatic v4.0.37

**Comment by khalwat** [comment]
SEOmatic -> Content SEO -> (section) -> Sitemap

<img width="1612" alt="Screenshot 2024-01-21 at 6 00 59 PM" src="https://github.com/nystudio107/craft-seomatic/assets/7570798/d937ec40-e2e4-4aac-bab8-16c23a469210">

**Comment by khalwat** [comment]
More information here:

https://nystudio107.com/blog/seo-myths-top-5-sitemap-myths-demystified

**Comment by rellafella** [comment]
Thanks Andrew, makes sense that this would be per-section now that I think about it
