### ISSUE TITLE
HREFLang tags are dependent on Sitemap status

### ISSUE THREAD

**Issue by brnquester** [nystudio107/craft-seomatic#1285]
### Describe the bug
The `hreflang` meta tags are not rendered or included for pages with Sitemap disabled. Even if the Plugin Settings > Tags has the `Add hreflang Tags` enabled. 

### To reproduce
Steps to reproduce the behaviour:
1. Go to `CMS > Content SEO`
2. Disable the Sitemap for any Entry section or single
3. Access any of the affected pages 
4. Check the source-code looking for `hreflang`. It won't be there.
5. By enabling back the Sitemap, the `hreflang` meta tag is restored.

### Expected behaviour
The `hreflang` tags to be independent or not affected by the Sitemap setting.

### Screenshots
N/A

### Further reasoning
We have many single entries that we don't want in the Sitemap because SEOmatic generates one separate sitemap file for each, but we still want the `hreflang` for them. We have added those pages in "Additional Sitemap URLs" in Site Settings > Sitemap.

### Versions
- Plugin version: v3.4.49
- Craft version:  v3.7.42

**Comment by khalwat** [comment]
> We have many single entries that we don't want in the Sitemap because SEOmatic generates one separate sitemap file for each, but we still want the hreflang for them. We have added those pages in "Additional Sitemap URLs" in Site Settings > Sitemap.

I do not really understand the rationale here? There's no downside to having these in a separate sitemap.

Unfortunately, disabling sitemaps for a section, or disabling the robots tag for a section is a signal for the hreflang tags to not be included.

I'd suggest not disabling the sitemaps for individual singles (again, there's no downside to it working this way), and this will eliminate your problem.

**Comment by brnquester** [comment]
> > We have many single entries that we don't want in the Sitemap because SEOmatic generates one separate sitemap file for each, but we still want the hreflang for them. We have added those pages in "Additional Sitemap URLs" in Site Settings > Sitemap.
> 
> I do not really understand the rationale here? There's no downside to having these in a separate sitemap.
> 
> Unfortunately, disabling sitemaps for a section, or disabling the robots tag for a section is a signal for the hreflang tags to not be included.
> 
> I'd suggest not disabling the sitemaps for individual singles (again, there's no downside to it working this way), and this will eliminate your problem.

Thank you for answering. If you're considering small or medium size project I agree with you 100%, but when you get to the enterprise level with website having over 20k pages, it starts to become a problem. Mainly, when there is different SEO teams auditing it. That's the first point.

The other aspect is that having a switch for hreflang and another for Sitemap that doesn't explain the correlation is at minimum confusing. That should be clearly documented. 

Unless the plug-in is not recommended for this size of a project, I would strongly recommend making these options independent. I'm not the first to complain about it. I'm happy to compile a list of related reports here.

**Comment by khalwat** [comment]
> Unless the plug-in is not recommended for this size of a project, I would strongly recommend making these options independent. I'm not the first to complain about it. I'm happy to compile a list of related reports here.

So your ideal solution here would be that hreflang tags should be included on a page regardless of whether sitemaps are enabled for the page?

What about the robots being disable for a page, should that affect the hreflang inclusion?

I found where both of these things were explicitly added, but unfortunately without a link to the issue that likely caused that to be done:

https://github.com/nystudio107/craft-seomatic/blob/develop/CHANGELOG.md#added-63

**Comment by khalwat** [comment]
Here's the line of code where it happens:

 https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/DynamicMeta.php#L537

IIRC, Google doesn't like it if you provide an `hreflang` to a URL that has `robots` disabled, which makes sense.

But thinking about it, I agree with you that probably there's no reason excluding it from a sitemap should always preclude it from inclusion in the `hreflang` links.

From what I can recall, I believe someone was using the SEO Settings field's **Include in Sitemap** as a signal to that this particular entry was one that they did not want indexed _at all_, thus it excludes it from the `hreflang` too. But unless `robots` is off for that page, Google will likely still find it and index it anyway, at some point...

**Comment by brnquester** [comment]
> > Unless the plug-in is not recommended for this size of a project, I would strongly recommend making these options independent. I'm not the first to complain about it. I'm happy to compile a list of related reports here.
> 
> So your ideal solution here would be that hreflang tags should be included on a page regardless of whether sitemaps are enabled for the page?
> 
> What about the robots being disable for a page, should that affect the hreflang inclusion?
> 
> I found where both of these things were explicitly added, but unfortunately without a link to the issue that likely caused that to be done:
> 
> https://github.com/nystudio107/craft-seomatic/blob/develop/CHANGELOG.md#added-63

That's correct for the `hreflang` being added to the page regardless of sitemap enabled for that specific page or not. First, because you have two separate toggles for that which has the implicit understanding that we can independently control them. Second, because for the purpose of SEO the sitemap is a support to the page, but the page is the ultimate index. 

About the robots, I never mentioned that. We have robots indexing pages all enabled. Sitemap is one support tool, robots guidance to index a page or not is another case. Which is not related to my report here.

I'm fine if you don't agree with it. However, I'm confident there are multiple cases where the users would like to control the two features independently. We're one of those. In my Craft experience so far, I have seen at least 3 major projects that needed that.  

But, it's up to you. Just a client feedback based on real use case that is frustrating.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/89b311ff01721caf03e5bc16bc0957258a1a2c35 & https://github.com/nystudio107/craft-seomatic/commit/2ac7313ae482b7247c8bc72d8ac547d8d565e898

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.50",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.21”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
lmk if this fixes it for you @bruno-canada ?

**Comment by brnquester** [comment]
> lmk if this fixes it for you @bruno-canada ?

Worked like a charm. I very much appreciate you reopening this thread and fixing it. 

This fix would and will avoid issue reports like https://github.com/nystudio107/craft-seomatic/issues/1246 and https://github.com/nystudio107/craft-seomatic/issues/1091

**Comment by khalwat** [comment]
Well, in those cases they would have still come back and wondered why nothing was in their sitemap... but I agree, it would be a more obvious thing to diagnose, most likely.
