### ISSUE TITLE
Long timeout for Google sitemap submission

### ISSUE THREAD

**Issue by nstcactus** [nystudio107/craft-seomatic#1288]
Hi,

Is there a reason for such a long timeout when submitting sitemaps to Google?

We have an issue on a site were the hosting provider blocks outgoing connections to google.com: no DB writes are possible until the sitemap submission times out (some transaction must keep a write lock on the DB).

We are going to sort this out with our hosting provider but setting a shorter timeout , just in case, would feel safer.

https://github.com/nystudio107/craft-seomatic/blob/7d0c49fa601dfd49749b7d222baad1160a00f335/src/services/Sitemaps.php#L249

**Comment by khalwat** [comment]
I could potentially increase the timeout there -- but I think even a very short timeout probably would make saving entries no fun. Probably the best thing to do is sort it out with your provider.

If I did change it, what do you suggest it gets changed to?

**Comment by nstcactus** [comment]
I think drastically reducing the `connect_timeout ` would help mitigating the issue. Something like 5 seconds seems pretty decent; if google.com cannot be connected in less than that, either Google is down and we're in a world of troubles, or it's time to consider a new hosting provider. 
The `timeout` can be kept to 120.

**Comment by khalwat** [comment]
I can certainly lower it to 5 seconds -- but a 5 second delay whenever editing an entry is still pretty annoying, I'd think. This should be fixed upstream by your hosting.

**Comment by nstcactus** [comment]
It's already fixed, I'm just suggesting as an improvement for your plugin.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/eb3d082bf0024634da881fa7d6196bf2325a6e21 & https://github.com/nystudio107/craft-seomatic/commit/d798e3315fd750625be1a9e6149323540f04e708

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.50",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.21",
```
Then do a `composer clear-cache && composer update`
