### ISSUE TITLE
Meta and title tags disappear after deploy

### ISSUE THREAD

**Issue by HannahDeWachter** [nystudio107/craft-seomatic#1290]
### Describe the bug
We have a multisite setup. On multiple occasions the SEO tags (meta and title tag) seem to disappear on one of the two sites: https://www.advocaat.be/nl. We see this because the tab name is the url of the site.
<img width="347" alt="Screenshot 2023-02-20 at 12 09 33" src="https://user-images.githubusercontent.com/55497252/220088837-cf8693ab-9a7c-45f0-bab9-46ce40b6f60a.png">

This always seem to occur after a deploy to the production environment. This does not happen on our staging environment nor locally. On the other site, the meta tags keep working.
#### Site A
<img width="462" alt="Screenshot 2023-02-20 at 12 07 31" src="https://user-images.githubusercontent.com/55497252/220090042-7ff7d62b-f830-49b9-8a18-425445b0a99e.png">

#### Site B
<img width="989" alt="Screenshot 2023-02-20 at 12 07 19" src="https://user-images.githubusercontent.com/55497252/220090092-d0f1dc9a-0655-4f6e-a768-51c00457821e.png">

### Versions
- Plugin version: 4.0.20
- Craft version: 4.3.10

**Comment by khalwat** [comment]
Very likely, this is some kind of issue with your deployment process. What specifically it is, I'm not sure. But SEOmatic won't just randomly disable itself.

**Comment by HannahDeWachter** [comment]
Hi @khalwat,
We run following commands when deploying:
```
executeCommand "composer install --no-dev" "Installing composer requirements..."
executeCommand "chmod +x ./craft"
executeCommand "./craft migrate/all"
executeCommand "./craft project-config/apply"
```

SEOmatic is not disabled, it just doesn't render any metadata anymore. 
If we log in and enable the debug bar, that also doesn't render. Could those 2 be related?

**Comment by khalwat** [comment]
I'd generally also clear all caches on deploy.

Very likely it's related that the debug toolbar doesn't render either, yes.

I'm going to close this, because I don't think it's a bug in SEOmatic, but I will continue to offer any help I can.

**Comment by HannahDeWachter** [comment]
Hi @khalwat, it looks like we managed to fix this. This was related to our Analytics setup.
