### ISSUE TITLE
Incorrect `$asset` argument type provided to Social Transform helper function

### ISSUE THREAD

**Issue by chrismlusk** [nystudio107/craft-seomatic#1291]
### Describe the bug
I'm seeing a lot of the following exceptions in my logs:

```
Warning: Object of class craft\elements\ElementCollection could not be converted to int
```

Reading the stack trace, it's coming from the `seomatic.helper.socialTransform` helper functions that are used when the meta values are being parsed. The error happens due to the `$asset` argument passed to the `ImageTransform::assetFromAssetOrIdOrQuery` helper method, since [it doesn't meet any of the conditionals to handle the asset before attempting to type cast](https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/ImageTransform.php#L275-L291).

### Versions
- Plugin version: 4.0.20
- Craft version: 4.3.9

**Comment by khalwat** [comment]
Show me your Twig code that is causing this to happen?

It sounds like you're passing in a collection to `seomatic.helper.socialTransform()` rather than an Asset?

**Comment by chrismlusk** [comment]
I haven't used that helper function.

### Revelent Content SEO settings
<img width="778" alt="Screenshot 2023-02-20 at 14 37 19" src="https://user-images.githubusercontent.com/5922913/220195394-03035e1c-220b-4b6b-be7a-5b662f9c2d33.png">

### Info from Sentry
The error is happening on `Providers` entries.

SEOmatic is first referenced in the stack track with a call to `MetaContainers::includeMetaContainers`. Once `MetaValue::parseString` is invoked, the value being parsed is logged in Sentry as:

```
{{ seomatic.helper.socialTransform(entry.portrait, "facebook", 1, "crop") }}
```

**Comment by khalwat** [comment]
I see -- and you are likely eager loading the `portrait` field in your templates?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/3cdaf26824022e3e9a37fa964943a4816e8cf5b4

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.21",
```
Then do a `composer clear-cache && composer update`

**Comment by chrismlusk** [comment]
That's what's odd — I'm not eager loading the `portrait` field in that `_entry.twig` or in any of the parent layouts that template extends from. I do in other contexts, e.g., an index page that renders a list of those provider entries, but that feels unrelated?

So, no idea why SEOmatic is receiving an `ElementCollection`. Either way, your fix will do the trick. Thanks!

**Comment by khalwat** [comment]
Not sure myself, but let me know if that fixes it for you!
