### ISSUE TITLE
Seomatic plugin Sitemap URL related

### ISSUE THREAD

**Issue by nikunjhm** [nystudio107/craft-seomatic#1292]
### Question
How to replace Site_URL/sitemaps-2-sitemap.xml to Site_URL/sitemap.xml seomatic

### Additional context
I need one Help regarding Seomatic plugin related help.

https://www.wackyworldstudios.com/robots.txt

https://www.wackyworldstudios.com/sitemaps-2-sitemap.xml (Getting 404)
https://www.wackyworldstudios.com/sitemap.xml

I'm getting  [sitemaps-2-sitemap.xml](https://www.wackyworldstudios.com/sitemaps-2-sitemap.xml) 404 URL in robots.txt so I want to change this site map url to [sitemap.xm](https://www.wackyworldstudios.com/sitemap.xml). Here is the robots.txt settings screenshot https://prnt.sc/BdVXbk12pjeV.

Please provide Feedback ASAP.

**Comment by khalwat** [comment]
This is probably going to end up being some kind of server or Craft configuration error.

Your robots.txt is displaying the correct sitemap URL, assuming that site ID 2 is your default site.

I'm not sure why it is a 404 error, unless you have sitemaps turned off of that site for some reason, or have some kind of other server or Craft configuration error.

The sitemap here: 

https://www.wackyworldstudios.com/sitemap.xml

Does not appear to be generated by SEOmatic.

Also please list your version of Craft CMS, and your version of SEOmatic.

**Comment by khalwat** [comment]
Will re-open if additional information is provided.
