### ISSUE TITLE
Sitelinks not working because schema type is "WebPage" instead of "WebSite"

### ISSUE THREAD

**Issue by noahcostello** [nystudio107/craft-seomatic#1296]
### Question
After configuring SiteLinks search box and testing it in google rich snippets test, I've discovered it is not working because SEOmatic defaults to setting the main type to "WebPage" and it needs to be "WebSite" to be valid for google to use the rich snippet. Google documentation shows type as WebSite: https://developers.google.com/search/docs/appearance/structured-data/sitelinks-searchbox

### Additional context
Config:
![image](https://user-images.githubusercontent.com/874274/222308310-9e59f980-2da8-4197-9845-5115f17ff1f7.png)

Test showing google not detecting the Sitelinks search structured data even though it is in the page: https://search.google.com/test/rich-results/result?id=gsJVpkZZmkl66_n903NTVg

Additionally, there is a behavior where a page on our site that doesn't match a category and renders a template via a custom route, does get rendered with "WebSite" schema. On those pages, Google detects the search box schema.

### Here is an example of two pages that render to the same template in craft, but get different schema types 

**In the first case it is rendered when it matches a single category and displays items from that category:**

top10erp.org/erp-software-comparison/best-fit/additive-manufacturing

Google **does not** detect the sitelinks search structured data in this case: https://search.google.com/test/rich-results/result?id=b4XrsAq3QtGVFrMF-5qffg
![image](https://user-images.githubusercontent.com/874274/222310782-363d30bb-5e91-46a8-89d6-57e98e6e02b3.png)

**In the second case it is rendered when a single category isn't matched and we have to display items from multiple categories, this gets routed to the same template:**

top10erp.org/erp-software-comparison/best-fit/aerospace-and-defense_and_additive-manufacturing

Google **does** detect the sitelinks search structured data in this case: https://search.google.com/test/rich-results/result?id=fzCSAZoR9HktJqvkqzcEgw
![image](https://user-images.githubusercontent.com/874274/222311054-b6f5c1cc-10fe-48d8-93e2-82915d6cb67d.png)

The only difference in the schema between those to pages is one is of type "WebPage" and the other "WebSite." Is there a config setting for this that I'm missing or is this a bug?

I've noticed that only pages on the site that get rendered via a custom route have the type set to "WebSite"

**Comment by khalwat** [comment]
Yes, you can change the schema type in your SEOmatic -> Global SEO -> General -> Main Entity of Page and for individual sections in SEOmatic -> Content SEO -> <click on a section> -> General -> Main Entity of Page
