### ISSUE TITLE
Location info → Entity Country fails to save

### ISSUE THREAD

**Issue by sergeifilippov** [nystudio107/craft-seomatic#13]
When submitting data in `SEOmatic > Site Settings > Creator > Creator Settings > Location Info`, **Entity Country** `/cp/seomatic/site/creator/default` fails to save on form submit. All other elements in the `Location info` section save fine.

- Nothing in logs
- Nothing in console.

Server Stack:

- Craft Pro 3.0.0-RC15
- yii 2.0.14.2
- Seomatic beta 3
- nginx 1.13.9
- php7.1 - 7.1.14
- percona-mysql.5.7 MySQL 5.7.21

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/4d35c49aa5c24bb76c68a3e4390ed4ee876c070a
