### ISSUE TITLE
SEOMatic content not being generated for entries of a structure

### ISSUE THREAD

**Issue by janhendrickx** [nystudio107/craft-seomatic#130]
Hi,

We've got a strange problem with SEOMatic: the SEO content for some entries in a structure aren't being generated, but the entry is being copied in the control panel without any changes the content of the copied entry is generated. So no changes have been made, just a quick copy and SEOMatic does its job. 
I added a screenshot: the left one is the original one that doesn't have any SEO content loaded, the right one is the copy, that, without any changes, has SEO content loaded.
Is this a bug? Our customer shares all it's posts on social media (especially Facebook) so I need to get this bug fixed...
![screen shot 2018-06-04 at 08 56 58](https://user-images.githubusercontent.com/17985717/40902864-bd384ad4-67d5-11e8-8ce3-196fa6cefd19.png)

**Comment by khalwat** [comment]
So do you have the SEO Content settings properly set up for this structure? Or are you using the SEO Settings field in the structure?

Something seems... not right. SEOmatic doesn't care if its a structure or a channel or what have you.

**Comment by janhendrickx** [comment]
Hi there! These are my SEOMatic settings (for this content type). I can't really see anything wrong with it, but an extra pair of eyes can do the trick might help... It's just weird that copying the entry fixes the problem...
![screen shot 2018-06-04 at 13 26 23](https://user-images.githubusercontent.com/17985717/40915107-12e4de46-67fb-11e8-892a-6f963cd247c6.png)

**Comment by khalwat** [comment]
Are you using an SEO Settings field as well?

**Comment by janhendrickx** [comment]
Thanks for the answer, I forgot about that (it's the first time I use it in Craft 3, in Craft 2 I always did used a SEO settings field). Now I have created a SEO settings field, but all fields of the content type are "custom fields. I had set it in the general settings for that content type since every entry in there has got a title, image and description. Now I've set up a SEO settings fields, but it doesn't load them (I already emptied all SEO cache). 
Am I missing something??

**Comment by khalwat** [comment]
In most cases, with SEOmatic for Craft CMS 3, you don't need to use SEO Settings fields at all. I was just asking if you were using them to gather information to try to understand what could be going on here.

**Comment by janhendrickx** [comment]
That's exactly why I like SEOMatic in Craft 3: Most of our sites have all the fields for SEO and it's no longer necessary to use a SEO settings field because of the general settings per content type. And because of your question I was thinking I was doing something wrong and that I've set them up. I was lucky though, our customer wanted to override the SEO fields on some of the entries, so I can leave it like that :-)

**Comment by khalwat** [comment]
Okay cool!
