### ISSUE TITLE
Site Name Position always using 'Before' option via GraphQL

### ISSUE THREAD

**Issue by plumduffer** [nystudio107/craft-seomatic#1300]
### Describe the bug
The option for Site Name Position is always being returned before a page title when fetching metaTitleContainer via GraphQL.

### To reproduce
Steps to reproduce the behaviour:
1. Set Site Name Position to anything other than 'Before' inside global seomatic settings.
2. Fetch metaTitleContainer for any page via GraphQL.
3. Notice the Site Name is always returned before the title, regardless of what option you picked.

### Expected behaviour
Expected the Site Name Position option to work with GraphQL. I have tried to update everything to latest versions and clearing caches etc.

### Versions
- Plugin version: 4.0.19
- Craft version: 4.3.6.1

**Comment by khalwat** [comment]
What is the Site Name Position set to in Content SEO for the section you are querying for?

Please provide your GraphQL query?

**Comment by khalwat** [comment]
Will re-open if more information is provided
