### ISSUE TITLE
Extending json entity

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft-seomatic#1301]
I am having issues trying to have this to be replaced via the native seomatic way / to be included to the main json. Especially the loop part. Please advise.

					<script type="application/ld+json">
						{
							"@context": "https://schema.org",
							"@type": "FAQPage",
							"mainEntity": [
								{% for question in questions %}
									{
										"@type": "Question",
										"name": "{{ question.title|trim('?', 'right') }} in {{ entry.title }}?",
										"acceptedAnswer": {
											"@type": "Answer",
											"text": "{% set content = question.contentBuilder.type('copy')[0] %}{{ content.copy|striptags }}"
										}
									}{% if not loop.last %},{% endif %}

								{% endfor %}
							]
						}
					</script>

**Comment by khalwat** [comment]
Some examples of exactly this are here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples#dev-mode-fm-about-page

**Comment by redkrupp** [comment]
Thanks but what is the scenario if I don't want to set the page type to faqpage as this FAQ block is just a tiny part of the listing / card entry.

**Comment by khalwat** [comment]
Then you can just create the `Question` and `Answer` JSON-LD objects as stand-alone objects, they'll be added to the JSON-LD that gets rendered, too.
