### ISSUE TITLE
Content SEO report shows sections are incomplete, but they aren't

### ISSUE THREAD

**Issue by chrismlusk** [nystudio107/craft-seomatic#1302]
### Describe the bug
Content SEO tab shows some sections as incomplete (e.g., missing a description or image), but all settings are updated and have content.

I have a multi-site setup with Site A, Site B, and Site C. Site C is brand new. 

There are three sections that I have enabled for all three sites. In Sites A and B, these three sections are 100% set up — and SEOmatic reflects this (100% score, green status icons, etc.).

After configuring the Content SEO for each section in Site C, SEOmatic shows that the Description and Image fields are missing for two of them.

<img width="728" alt="Screenshot 2023-03-26 at 13 14 27" src="https://user-images.githubusercontent.com/5922913/227795757-6153ee0b-7500-4738-bcab-a17fbd965e63.png">

And the Dashboard shows that the Keywords and Image Description are also empty.

To configure these sections for the new Site C, I used the "Copy Settings From" utility, so I'm copying from sites that are fully set up.

After that didn't change the status, I also tried emptying all of the fields, saving, and then manually adding in the content for each. No change.

I have cleared CP caches, too. Nothing.

The content is there, though, because I see those meta tags rendering as expected on the front end.

It's also very odd that this is only an issue with two of the three sections. 

### Expected behaviour
Content SEO (and Dashboard) for Site C should show as complete.

### Versions
- Plugin version: 4.0.22
- Craft version: 4.4.5

**Comment by khalwat** [comment]
Is it possible you have multiple entry types for these sections, which are not fully setup?

**Comment by chrismlusk** [comment]
Nope. One of those sections is a Single (and it's the homepage), and I just confirmed the other only has one entry type.

**Comment by chrismlusk** [comment]
@khalwat I'm not sure if this is related or even the cause of the issue, but I noticed today that — after clearing the SEOmatic caches — the Content SEO values disappeared on the sections showing up as incomplete in the dashboard.

So for example, before clearing caches, my "Home" single had custom values.

I then cleared the SEOmatic caches.

When I reloaded the homepage for this site, I noticed the title value was the default, e.g., "Home | Site Name" 

I went back to the CP and went to this site's Content SEO page, and sure enough all of the fields for the Home single were reset to the defaults.

**Comment by khalwat** [comment]
@chrismlusk that sounds unrelated -- but also concerning, because clearing caches has nothing to do with the values that SEOmatic stores in the `seomatic_metabundles` table.

**Comment by khalwat** [comment]
Does everything work as expected now, if you set the values to what they should be?

**Comment by chrismlusk** [comment]
Right, it made no sense that the cache would effect data in the DB 🤷🏼 

The values are still set to what I updated yesterday. In attempt to recreate the issue, I just went to Utilities > Cache and tried clearing every option individually to see if that did anything. Nothing happened. Then, I tried clearing all at once. No change. So, that's a relief.

Unfortunately I don't know what else to report. _Something_ caused those values to reset. And while I don't know this for a fact, I'm almost certain I am the only person on this project who edits anything in SEOmatic. (The CMS shows that nobody in the user group we've set up to have SEO permissions has logged in for a month.)

I _do_ know for a fact that the Content SEO values were indeed set prior to this incident. Updating them is what lead me to file this original issue.

The only other variable I can think of is that when this happened yesterday, I had just deployed a new bundle. Not that that makes any sense, though.

But I realize I've given you nothing concrete to further investigate this side quest.

My original issue still stands, though.

**Comment by chrismlusk** [comment]
An update for the incomplete Content SEO report:

Two new sections have been deployed for this site (Site C, in my original issue description). Both are Singles. After configuring the SEOmatic values, the Content SEO report shows those sections as 100% complete. 

So, the problem sections mentioned above are still showing as incomplete, but newly added sections are showing the expected status once they are updated.

**Comment by khalwat** [comment]
If this issue is still occurring, probably the only way I can diagnose it is if you send me your `composer.json` and a database dump for the site to:

andrew@nystudio107.com

**Comment by chrismlusk** [comment]
Just sent. Thanks.

**Comment by khalwat** [comment]
I did not receive it.

**Comment by chrismlusk** [comment]
That’s odd. 

![IMG_6628](https://user-images.githubusercontent.com/5922913/235505583-e74c3c0f-5776-4ee8-b3cc-766ab9f2e523.jpeg)

**Comment by chrismlusk** [comment]
Hey @khalwat, I've re-sent an email a couple times now. Are you still not receiving anything?

We are still consistently running into the problem where the Content SEO values reset on this specific site in question. So if I can get you my `composer.json` and database dump another way, just let me know.

**Comment by khalwat** [comment]
I have not -- can you just DM me it on Discord?

**Comment by khalwat** [comment]
I set up a local dev environment, and reviewed the settings.

It appears the it is correctly reporting what is not set up fully in the Content SEO and Global SEO settings.

**Comment by chrismlusk** [comment]
I think you see empty Content SEO settings because the DB dump I sent you was one where those values had already reset. 

There are two possibly related issues at play:
- After fully setting up Content SEO fields for a certain multi-site instance, SEOmatic continues to report the section as incomplete even though it is not.
- Then, after some time (potentially after deployments/cache clearing?), the SEO fields in these problem sections are reset. Any section that SEOmatic reports as complete does not get reset. Only ones that the plugin say are incomplete (even when they aren't).

I appreciate that this is confusing to explain. Happy to schedule a video chat if that can help.

**Comment by khalwat** [comment]
This ended up being a duplicate row in the `seomatic_metabundles` table for the same section

It is unknown how it got there to begin with
