### ISSUE TITLE
Fully encode URLs to meta tags image (og:image)

### ISSUE THREAD

**Issue by svale** [nystudio107/craft-seomatic#1305]
### Is your feature request related to a problem? Please describe.
We are using a `Custom URL` for our SEO Image Source  so that we can apply imgIX filters to the sharing image source.  
```
{% set params = { 
  'blend-color' : (entry.colors|first.color ?? '#D9EAD7')|trim('#'),
  'blend-size' : 'inherit',
  'blend-mode' : 'multiply',
} %}
{% set queryString = params|url_encode %}
{{ entry.image.one().url }}?{{queryString}}
```
This however generates a non standard ascii URL that when not fully escaped (as a consequence of editor controlled assets folder etc), that at least the Facebook scraper will not read. An example is:

`https://fivh.imgix.net/images/Grønne-tips/Forbruk/kosmetikkting.png?blend-color=D9EAD7&blend-mode=multiply&blend_size=inherit`
vs
`https://fivh.imgix.net/images/Gr%C3%B8nne-tips/Forbruk/kosmetikkting.png?blend-mode=multiply&blend_size=inherit&blend-color=D9EAD7
`

Unfortunately is doesn't help adding escape filters in the twig input (it actually does work for other fields like `Keywords` and `Description`, but not for `image`...)

### Describe the solution you would like
The problem is solved if the URL (or the path) is fully escaped, and this could be an extension of hos SEOMatic is currently escaping spaces (`%20`). I have a test running on a fork that look likes this: https://github.com/nystudio107/craft-seomatic/compare/develop-v4...svale:craft-seomatic:feature/encode-url-path .  I'd be happy to open a PR of this if that would be an option.

### Describe alternatives you have considered
If url encoding was preserved from the config field all the way through to the `og:image`-tag, we could alternatively also make it work with something like this

```
// in custom URL settings:
{{ rootURL }}/{{ imgPath|url_encode }}?{{queryString}}

```  

### Additional context
Craft 4.3.8.2
SEOMatic 4.0.2.3

### Thanks!
As always, thank you for providing fantastic plugins!!

**Comment by khalwat** [comment]
In your examples above, can you please clarify which is what you're expecting it to be, and which is the undesired current result?

**Comment by khalwat** [comment]
Do any of these Craft config settings help?

https://craftcms.com/docs/4.x/config/general.html#limitautoslugstoascii

https://craftcms.com/docs/4.x/config/general.html#convertfilenamestoascii

**Comment by svale** [comment]
Thank you for the quick reply! And spot on suggestions. 

While we already were limiting slugs to ascii, I had missed the 
[convertfilenamestoascii](https://craftcms.com/docs/4.x/config/general.html#convertfilenamestoascii) setting. Testing, and as expected limiting asset names (including I now know asset folder names) removes the need for further encoding. 

Problem solved! Now I only have to dare run `php craft utils/ascii-filenames` on 500 assets already propagated to S3 and ImgIX... 😓 

(And for the record: the first example  `.../images/Gr%C3%B8nne-tips/Forbruk/...` - with the charachter `ø` encode,  would be the desired version)
