### ISSUE TITLE
Content SEO Blank

### ISSUE THREAD

**Issue by sg-modlab** [nystudio107/craft-seomatic#1306]
### Question
Can you think of any reason why the Content SEO area is blank and not accessible?

### Additional context
Craft CMS 4.4.3
SEOmatic 4.0.22

<img width="1926" alt="CleanShot 2023-04-06 at 09 17 53@2x" src="https://user-images.githubusercontent.com/529067/230390562-9dd5a618-47b7-4696-97e0-764b7a9b31b6.png">

<img width="1926" alt="CleanShot 2023-04-06 at 09 19 36@2x" src="https://user-images.githubusercontent.com/529067/230390662-7ce10f2c-6fb7-4f7e-bad5-58a2dd812cd8.png">

**Comment by khalwat** [comment]
Are your sites enabled, with public URLs?

**Comment by sg-modlab** [comment]
I’ve got one site configured as such

Sorry just realized screenshot did not come through via email. here it is.

<img width="489" alt="CleanShot 2023-04-06 at 10 49 09@2x" src="https://user-images.githubusercontent.com/529067/230416380-c176967f-c3fb-49b7-8db3-8f450d750dcf.png">

**Comment by khalwat** [comment]
What about your Sections? Do they all have public URLs?

**Comment by khalwat** [comment]
I think you need to check **This site has its own base URL** and give it a URL.

**Comment by sg-modlab** [comment]
Sections definitely have urls (site pages are functioning).

I updated the site to mark that it has a unique base url and provided one. Then cleared caches. No change.

**Comment by khalwat** [comment]
Have you visited any of the pages on the frontend or in the CP? SEOmatic dynamically creates the metabundles as needed.

**Comment by sg-modlab** [comment]
Yes I did. I had updated the site very recently (craft updates and some template updates to some category templates). Shortly after I did an SEO audit and saw a lot of repeated titles which seemed odd. Noticing all our blog entries are defaulting to the site meta settings and so went to review that sections defaults and couldn't access it per my original post. I can see the SEO field for individual entries and seems I might be able to overwrite but that's not ideal of course. 

https://mod-lab.com/blog/nonprofit-branding-small-medium-or-large

**Comment by khalwat** [comment]
Let's schedule a video conference to look at this together... something isn't right here!

https://savvycal.com/nystudio107/chat

**Comment by khalwat** [comment]
Also this looks similar? https://github.com/nystudio107/craft-seomatic/issues/1215

**Comment by sg-modlab** [comment]
Yes, this looks exactly right. Will review settings again just to be sure. Scheduled some time and will let you know if find anything out.

•
Seth Giammanco (he/him)
Principal, Strategy & Technology
***@***.***
mod-lab.com

**Comment by sg-modlab** [comment]
So I reviewed that base url settings and they were set okay after making the change earlier today. This said, I also ran update for a few of the most recent Craft and one or two SEOMatic ones. Something in there seems to unlock the key and now seeing content SEO. working through getting my settings back in place. Hoping good to go.
