### ISSUE TITLE
Content SEO content disappeared

### ISSUE THREAD

**Issue by ammonhaggerty** [nystudio107/craft-seomatic#1307]
I've read a few other threads (including the one from yesterday) with the same general issue, but didn't see a clear solution. So requesting help with my empty Content SEO panel. Everything else seems to be fine. Seems to have disappeared after a recent update.

**Craft CMS** 4.4.6.1
**SEOMatic** dev-develop-v4 (using this was a fix for a problem I had in the past -- could be an issue?)

Dashboard looks normal, entry previews are still working correctly, nothing appears broken on the live site. But I can no longer access/change any page SEO settings.

Thanks in advance for any assistance.

**Comment by khalwat** [comment]
Did you try everything listed in the previous issues?

-- Ensure your Sections are enabled
-- Ensure your Sites have their own base URL
-- Ensure that your `PRIMARY_SITE_URL` is set properly
-- Check the web browser console for errors

I just spun up `dev-develop-v4` running Craft CMS `4.4.6.1` and Content SEO is appearing without issue.

**Comment by ammonhaggerty** [comment]
Thank you for the quick reply! 

Just to add a little more detail, I'm getting a "Mixed Content" error on both the Content SEO panel and Retour panel. Everything else is working correctly. Also strange that my local environment is working fine. 

It's possible it's an issue with .htaccess (I've ready your call to not use it but not an option in this case). But strange it's only affecting the production environment. I'll keep looking for any prod/dev config issues, but please let me know if you can think of something specific I should check.

**Comment by khalwat** [comment]
Yeah if it's only affecting one environment, it's almost always going to be some kind of config/setup issue on that environment.

**Comment by ammonhaggerty** [comment]
I spent a few hours looking through everything I could understand. Obviously I may be a little over my head, but I think I'm stumped. All the environmental configurations seem to be the same for local (dev) and production. 

Example of call in Content SEO that's causing problems is: http://www.#######.###?p=edit/actions/seomatic/content-seo/meta-bundles&site=default&sort=sourceName%7Casc&page=1&per_page=20&siteId=1

Same issue in Retour — it's using http instead of https. Can you think of any place to look? I feel I've exhausted the options I can think of.

Thank you!

**Comment by khalwat** [comment]
Probably your `PRIMARY_SITE_URL` or `SITE_URL` or `@web` alias is not set up correctly.

This is going to be a devops/environmental related issue. I'm happy to keep attempting to help you with it, but I don't think this is an issue with Retour or SEOmatic.
