### ISSUE TITLE
Robots.txt does not work for multisite with different domains

### ISSUE THREAD

**Issue by HannahDeWachter** [nystudio107/craft-seomatic#1308]
I have a multisite setup with 2 Site Groups with different domains, within each Site Group there are 3 different sites (same domain, different language).

I wanted to check the robots.txt of site 2 (https://site2.be/nl). I first went to https://site2.be/nl/robots.txt but this resulted in a 404, so I removed the "/nl" (https://site2.be/robots.txt) and this gave me the robots.txt of site 1 (https://site1.be). It seems like it takes the robots.txt of the primary site.

I have the setting "**Site Groups define logically separate sites**" on.

### Expected behaviour
https://site2.be/nl to have its own robots.txt

### Versions
- Plugin version: 4.0.23
- Craft version: 4.4.7

**Comment by khalwat** [comment]
That's not how `robots.txt` works, though. It must appear at the domain root:

https://www.robotstxt.org/robotstxt.html

> 
> How to create a /robots.txt file
> Where to put it
> The short answer: in the top-level directory of your web server.
> 
> The longer answer:
> 
> When a robot looks for the "/robots.txt" file for URL, it strips the path component from the URL (everything from the first single slash), and puts "/robots.txt" in its place.
