### ISSUE TITLE
SEO images don't update mtime when asset settings are changed

### ISSUE THREAD

**Issue by mlathrom** [nystudio107/craft-seomatic#1309]
### Describe the bug
The mtime param appended to seo images doesn't take into account changes to asset settings local focal point.

The mtime param is created in line 156 of src/helpers/imageTransform.php. It checks the "dateModified" on the asset. The problem is that "dateModified" only takes into account changes to the actual asset file, not the asset settings. "dateUpdated" checks the asset settings.

### To reproduce
Steps to reproduce the behaviour:
1. Navigate to asset used as an seo image
2. Change the focal point of that image
3. Navigate to the page that asset appears in the head of
4. Check mtime on seo image

### Expected behaviour
Asset focal point should update in seomatic image meta tags. Mtime should match time the focal point was updated.

### Versions
- Plugin version: 4.0.23
- Craft version: 4.4.7.1

**Comment by mlathrom** [comment]
I've tested a couple of solutions for this.

**Remove mtime param**
This fixed the issue with assets seomatic images updating when focal point is changed, but I'm not sure if the mtime param was added to solve some other issue.

**Check dateModified and dateUpdated and use the newest**
This will ensure that changes to the asset file and asset settings are taken into account when adding the mtime param.

**Comment by khalwat** [comment]
Addressed via: https://github.com/nystudio107/craft-seomatic/pull/1310

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.53”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.24”,
```
Then do a `composer clear-cache && composer update`
