### ISSUE TITLE
Include query params in hreflang

### ISSUE THREAD

**Issue by riasvdv** [nystudio107/craft-seomatic#131]
Our automated SEO tool complains about our html not containing the correct self-referencing `hreflang` attributes, this happens for example on paginated pages where the url is `example.com/blog?p=1` and the hreflang links to `example.com/blog`.

**Comment by khalwat** [comment]
hmmm. I'm going to have to have a think on this one, because there are definitely cases where you do not want any query params included

**Comment by khalwat** [comment]
I'd almost recommend that you switch over to segments rather than URL params for your pagination, not just for the `hreflang` but for general SEO reasons as well.

**Comment by khalwat** [comment]
@Rias500 can you give me a sample of the output from your SEO tool?

**Comment by khalwat** [comment]
So after thinking about it for a bit, I think what _probably_ makes the most sense is on the pages where you have paginated entries, you do something like this:

```twig
{% do seomatic.meta.canonicalUrl(pageInfo.getPageUrl(pageInfo.currentPage)) %}
```

**Comment by khalwat** [comment]
I added this:

* **`seomatic.helper.pageinate(PAGEINFO)`** - Given the `PAGEINFO` variable from the `{% paginate %}` tag as [described here](https://docs.craftcms.com/v3/templating/tags/paginate.html#the-pageInfo-variable), this will properly set the `canonicalUrl`, as well as adding the `<link rel='prev'>` and `<link rel='next'>` tags for you.

**Comment by khalwat** [comment]
I just realized that the above, while useful and awesome, doesn't help you regarding the `hreflang`, so I re-opened this

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/a995d8b037da90710529be9d301f2f53a2429804

Example output:
```html
<link href="http://craft3.test/it/?pg=1" rel="alternate" hreflang="it-it">
<link href="http://craft3.test/es/?pg=1" rel="alternate" hreflang="es">
<link href="http://craft3.test/?pg=1" rel="alternate" hreflang="en-us">
<link href="http://craft3.test/?pg=1" rel="alternate" hreflang="x-default">
```
