### ISSUE TITLE
SEO Image Source Override not Overriding Default SEO Image

### ISSUE THREAD

**Issue by thom-moresoda** [nystudio107/craft-seomatic#1311]
I'm having an issue where the SEO image source override (custom image & custom url) on particular entries is not overriding the default SEO image.

It seems to only affect channels & not structures

Craft - 4.3.1
SEOmatic - 4.0.23

- seomatic_metabundles in DB look correct
- Content SEO settings are set up
- Neither Custom URL or Custom Image override the default SEO image
- Transforms look to be running ok

Any help appreciated!

**Comment by khalwat** [comment]
Can you show me a screenshot of it not appearing as expected?

Did you copy the custom Twig code to the Facebook & Twitter image fields?

**Comment by thom-moresoda** [comment]
Default card SEO preview:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/88486436/234574131-79c00e81-1d0e-4ef0-92ed-d9740cc41304.png">

SEO Preview with a custom image override:
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/88486436/234574479-f7ccc185-8ef4-4b08-9fdb-187077baaa61.png">

Do you mind linking me to the docs re.  "custom Twig code to the Facebook & Twitter image fields" Its been ages since SEOmatic was implemented on this site so its probably something worth checking

**Comment by thom-moresoda** [comment]
@khalwat do you mind giving me some more detail on "custom Twig code to the Facebook & Twitter image fields"?

**Comment by devinpitcher** [comment]
We are seeing this too. Added the SEO field to blog articles (in a channel) but the image is not being overwritten. The title and description are, though. Querying with GraphQL.

```
PHP version: 8.2.6
OS version: Linux 5.15.89-0psh2
Database driver & version: PostgreSQL 15.3
Image driver & version: Imagick (ImageMagick 6.9.11-60)
Craft edition & version: Craft Pro 4.4.13
Yii version: 2.0.47
Twig version: v3.4.3
Guzzle version: 7.7.0
SEO: 4.0.27
```

**Comment by khalwat** [comment]
Take the custom Twig code that you have in your SEO Image field, and paste it into the Twitter Image and Facebook OpenGraph image fields (as opposed to having them set to "Same as SEO Image"

**Comment by khalwat** [comment]
@devinpitcher So you're saying that when the SEOmatic settings are overridden via a SEO Settings field, all of the other settings in the SEO Settings are properly overridden _except_ for the SEO Image?

Does the image preview properly in the CMS backend in the SEOmatic preview on the sidebar on the right?

**Comment by devinpitcher** [comment]
@khalwat No, the preview on the side is showing the wrong image. It's showing the one set in the Content SEO settings but is not being replaced by the one set in the SEO overrides. The title and description overrides _do_ show up correctly though.

**Comment by khalwat** [comment]
Can we arrange a video conference to have a look at this?

**Comment by devinpitcher** [comment]
> Can we arrange a video conference to have a look at this?

Sure! I'm on vacation at the moment, but I return to the office on Wednesday. Perhaps sometime Thursday or Friday?

I'll send an email to info@nystudio107.com to coordinate, or if there's another email to use, let me know.

**Comment by khalwat** [comment]
Let me know if you are back, and ready to have a look at this.

**Comment by steve-p96** [comment]
Hey @khalwat , it’s been a while — I’m experiencing the same issue as @thom-moresoda. Has there been any update or solution for this?

Craft Pro 4.5.5
SEOmatic 4.1.9

**Comment by khalwat** [comment]
@steve-p96 please start by upgrading to the latest version of SEOmatic.  As for a solution, no, because no one has gotten back to me with the information I need to attempt to debug what is going on.

**Comment by steve-p96** [comment]
@khalwat thanks for the fast reply!

I tried to update to the latest version of Craft and SEOmatic on my local machine, but unfortunately it had no impact on the issue

**Comment by khalwat** [comment]
@steve-p96 please describe the exact problem you're having, with screenshots if you can.

**Comment by steve-p96** [comment]
@khalwat 

Per default the source for the SEO Image is assigned to this source field: 

![Image](https://github.com/user-attachments/assets/68bf895d-2d22-4e21-807c-80de2f6dbcda)

which works as it should.

For each entry i have individual SEO-settings where i can override the default values:

![Image](https://github.com/user-attachments/assets/7abe717f-2a42-4fa8-884a-3d975aacdd99)

As you can see it works for every value except the image, where it still renders the default field (i blackened out client related parts, which are not relevant here)

If I switch to Custom URL (which does not work either) I can see the correct asset id:

![Image](https://github.com/user-attachments/assets/b48f14e6-2a11-4313-be4c-13f42e42f9cf)

**Comment by steve-p96** [comment]
@khalwat any updates on this?

**Comment by khalwat** [comment]
@steve-p96 so that's the SEO Image, but the image you're viewing that isn't changing are the Twitter and Facebook OpenGraph images. Are you allowing overrides on those as well?

**Comment by khalwat** [comment]
Basically, the SEO Image setting is used for the JSON-LD structured data.

If can _also_ be used for the Twitter Image and the Facebook OpenGraph image, if the Content SEO settings for that section are set to "Same as SEO Image". You might want to check those, and re-save the settings.

Otherwise, the Twitter Image and Facebook OpenGraph image can be set independently, and thus would need to be overridden independently.

**Comment by steve-p96** [comment]
@khalwat Thank you, that was the reason! It works now
