### ISSUE TITLE
remove site from robots.txt

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#1313]
### Question
I have a site that had a multisite which was removed for French but in robots.txt it's still showing up like this.

```
sitemap: $SITE_URL_FR/sitemaps-2-sitemap.xml
```

How do I remove this? cannot find anything in settings.

### Additional context
Add any other context or screenshots about the support request here.

**Comment by khalwat** [comment]
Edit the Robots.txt via Global SEO -> Robots

**Comment by CreateSean** [comment]
Andrew,

on this page I see this bit of code

```
# robots.txt for {{ siteUrl }}

Sitemap: {{ seomatic.helper.sitemapIndexForSiteId() }}
```

The solution was to delete that, save, then re-add it and save again.

Not ideal but it worked
