### ISSUE TITLE
Content SEO panel listing missing sections and listing duplicate sections

### ISSUE THREAD

**Issue by TheFunkyMonk** [nystudio107/craft-seomatic#1314]
### Describe the bug
This is a tough one to produce repro steps for, but if there's anywhere I can send a db backup please let me know.

I have a site with 9 sections that are a mix of structures and channels, no singles. When I go to the Content SEO panel to set up defaults, one of the structures is missing from the list and two structures are duplicated, with the duplicate for each showing incorrect data in the list view.

![Screenshot-2023-04-25-at-4 56 39-PM](https://user-images.githubusercontent.com/1728770/234432839-32991e89-6c54-4ab9-9ca3-0d01cbaf704b.jpg)

In this example, "Proposals" is a structure set to "none" for robots, and when I click into the duplicate listed item, I see the correct "none" setting in its robots section.

Is there some kind of cache I can clear out for this listing view? Not really sure how to proceed on this one.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Content SEO panel

### Expected behaviour
Sections represented in CMS settings should be represented in Content SEO panel.

### Versions
- Plugin version: 4.0.23
- Craft version: Craft Pro 4.4.7.1

**Comment by khalwat** [comment]
Could it be a case where you renamed a whole bunch of these sections?

What happens if you uninstall SEOmatic, and re-install it? (warning: you'll lose any SEO config if you do this, so try it in local dev)

**Comment by TheFunkyMonk** [comment]
I don't think these sections have been renamed much/at all, but some of them were created via the [Cloner](https://plugins.craftcms.com/cloner?craft4) plugin.

Uninstalling and reinstalling SEOmatic does resolve the issue. Is there a way to clean up this list without uninstalling SEOmatic? And, if not, can you confirm the only config that would be lost is what's under the main SEOmatic sidebar options and not SEO Settings fields on entries themselves?

**Comment by khalwat** [comment]
If I had to guess, something the Cloner plugin is doing is confusing SEOmatic.

You can go into the db and delete the `seomatic_metabundles` that correspond to the sections you're having issues with; SEOmatic will recreate them as needed.

The only thing that will be lost is the mappings for those section settings in Content SEO.
