### ISSUE TITLE
 Missing field "hasMerchantReturnPolicy" (in "offers")

### ISSUE THREAD

**Issue by DiaaHalawany12** [nystudio107/craft-seomatic#1315]
Hello, i got this message from Google Search Console and i don't understand the issue "
Missing field "hasMerchantReturnPolicy" (in "offers")"

Anyone can help?

**Comment by khalwat** [comment]
This is something you'd need to add yourself using the SEOmatic Twig API:

https://nystudio107.com/docs/seomatic/using.html#twig-templating

Examples here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples
