### ISSUE TITLE
Seeing "No Twitter Handle has been set. Set it here." but it is set

### ISSUE THREAD

**Issue by philipboomy** [nystudio107/craft-seomatic#1316]
### Describe the bug
When checking Twitter  setting of a section in content SEO e.g. **/seomatic/edit-content/twitter/section/episodelisting/default** then it says this "No Twitter Handle has been set. Set it here." but I click that link and check the field "Twitter Handle" then it is set.

### Screenshots
https://share.getcloudapp.com/xQuR5kkl
https://share.getcloudapp.com/4guNELLj

### Versions
- Plugin version: 4.0.24
- Craft version: 4.4.8

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/5e1edfa04b072c271c821cbb539f06db547550c6 & https://github.com/nystudio107/craft-seomatic/commit/2ceabc9eccb901ea37946b47615d4074125b4265

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.54”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.25”,
```
Then do a `composer clear-cache && composer update`
