### ISSUE TITLE
Sitemaps not getting generated

### ISSUE THREAD

**Issue by aloco** [nystudio107/craft-seomatic#1318]
### Describe the bug
Hi, we have a project where no sitemaps are getting generated, there is nothing in the logs, when creating the sitemaps via the CLI it seems like it skips all entries:

```
./craft seomatic/sitemap/generate
Generating sitemap
Generating sitemap for channel Blogs, siteId 1
---
Generating sitemap for single Home, siteId 1
---
Generating sitemap for channel Legal Pages, siteId 1
---
Generating sitemap for structure Pages, siteId 1
---
Generating sitemap for channel Blogs, siteId 2
---
Generating sitemap for single Home, siteId 2
---
Generating sitemap for channel Legal Pages, siteId 2
---
Generating sitemap for structure Pages, siteId 2
---
```

I don´t really know where to look into to pinpoint the issue

### To reproduce
Steps to reproduce the behaviour:
1. Install SEOMatic. 
2. Make sure all sitemaps are enabled in the Content SEO Settings
3. Create sitemaps via CLI or automatically by saving an entry

### Expected behaviour
Sitemaps should be generated

### Versions

Craft 4.4.8

<img width="783" alt="Screenshot 2023-05-08 at 15 35 06" src="https://user-images.githubusercontent.com/11661125/236838214-97027c2c-c5d0-4d2c-b31b-5f7254e95da9.png">

**Comment by khalwat** [comment]
Are you sure that URLs are enabled for all of your Craft Sites & Sections?

**Comment by aloco** [comment]
Hi, yes they have URLs, also the preview is working within Craft

**Comment by khalwat** [comment]
And if you go to view the actual sitemaps in the browser, what do you see?

I've looked at the code, and I'm not seeing anything relevant here; there must be some setting (Craft or SEOmatic) that is causing it to think your sections have no items in the sitemap.

**Comment by aloco** [comment]
The actual sitemaps are empty.

<img width="928" alt="Screenshot 2023-05-10 at 11 55 54" src="https://github.com/nystudio107/craft-seomatic/assets/11661125/0302535c-d29e-4f41-878c-d1c61bb11685">

I just checked the render function within SitemapTemplate.php and found out, that this is empty:
`$sitemapUrls = $metaBundle->metaSitemapVars->sitemapUrls;`

This issue is also new to me, never experienced something like this in other projects of us using SEOMatic - All sitemap settings are on, devMode is false, SEOMatic environment is live

**Comment by aloco** [comment]
Hi, I just solved this by reinstalling the plugin 🤷‍♂️not sure what was going on but I am happy it is working now
