### ISSUE TITLE
canonical doesn't seem to update after changing slug with special characters

### ISSUE THREAD

**Issue by FrDH** [nystudio107/craft-seomatic#1319]
### Describe the bug
We changed the slug of an entry from "patiënten" (note the "ë") to "patienten". Afterwards, we could visit both URLs, so "mysite.nl/patienten" and "mysite.nl/patiënten" both showed the same page. Not sure if this is intended behavior or a bug within Craft, but the canonical meta tag got updated only after clearing caches.

### To reproduce
Steps to reproduce the behaviour:
1. Go to the CP and create an entry with the slug "patiënten", save the entry.
2. Edit the entry slug to "patienten".
3. Visit the page with its original slug and check the canonical meta tag.

### Expected behaviour
I'd expect the canonical meta tag to point to the latest saved version of the entry, in this case to "patienten"

### Versions
- Plugin version: 3.4.51
- Craft version: 3.8.;2

Thanks in advance!

**Comment by khalwat** [comment]
SEOmatic is going to use whatever Craft outputs when you do `entry.url` -- so check that to ensure it is outputting what you expect.

Potentially this could also be an issue with caches not being cleared, but they should be cleared by SEOmatic whenever you save the entry. Maybe there's another layer of caching at work here?

I just tested it locally, and it's working as expected:

Entry with the slug `patiënten`:

<img width="703" alt="Screenshot 2023-05-09 at 12 54 16 PM" src="https://github.com/nystudio107/craft-seomatic/assets/7570798/7dd9a358-cad5-46fb-960a-606b53e47b71">

Entry with the slug changed to `patienten`:

<img width="703" alt="Screenshot 2023-05-09 at 12 55 18 PM" src="https://github.com/nystudio107/craft-seomatic/assets/7570798/50ab3f7a-e3f7-44e9-9017-8eeefda8c4ee">

So it's very likely something on your end, probably caching?
