### ISSUE TITLE
Imgix URLs for social images contain &amp; and are trying to set a 1:1 crop

### ISSUE THREAD

**Issue by wfendler** [nystudio107/craft-seomatic#132]
I've tried changing the settings throughout the plugin (turning crop on/off, uploading different sized images, etc) but it seems to keep the imgix URL the same: with `&amp;` and setting it to crop at 800 x 800 which is incorrect.
![screen shot 2018-06-04 at 5 15 10 pm](https://user-images.githubusercontent.com/511928/40944554-d71929b0-681a-11e8-82a5-7ba75ec03988.png)
![screen shot 2018-06-04 at 5 15 23 pm](https://user-images.githubusercontent.com/511928/40944555-d72b1c74-681a-11e8-8066-f97ae5f04098.png)

**Comment by khalwat** [comment]
How are the Imgix URLs getting there to begin with? Are you pasting in raw URLs into the fields?

**Comment by wfendler** [comment]
I'm not manually adding those but I do have the Imgix plugin. My assumption was the seomatic was aware of Imgix and used those URLs. Perhaps this is an Imgix plugin issue passing along this url improperly? I'm not familiar enough with plugin development to debug this properly.

I'd be happy to provide any more details.

**Comment by khalwat** [comment]
Yeah I think it might have something to do with the way the Imgix plugin works; I'm not really sure, I've never used it. It's probably an issue for the Imgix author, but I'd be happy to work with him to figure out a solution.

**Comment by wfendler** [comment]
Whoops. While going through some major image changes recently I forgot I wasn't using the Imgix plugin any longer. My images volumes are all S3 and all image references I'm making are using your ImageOptimize plugin. The transform method is set to Imgix. I believe that's the only place Imgix is referenced so perhaps there's something going on between SEOmatic + ImageOptimize? 🤔
