### ISSUE TITLE
A user without rights to a volume will still see all folders within that volume

### ISSUE THREAD

**Issue by jurgenkrol** [nystudio107/craft-seomatic#1320]
When a user is in a user group that has no rights to a certain volume, this user will still see all these volumes and their subfolders. This happens if he wants to select an image at, for example, "Site Settings" -> "Entity Brand", but also in other places in the plugin.

Steps to reproduce the behaviour:
1. Create a user in a user group without permissions for certain volumes
1. Go to SEOMatic -> "Site Settings"
2. Click on "Select Brand Image"
3. Now all volumes and folders are visible even if a user doesn't have permission to see them

This behavior does not happen in other places in Craft CMS.

- Plugin version: 3.4.53
- Craft version: 3.8.10.2

**Comment by khalwat** [comment]
Yes, currently it allows for the choosing of images from any Asset volumes. Is this causing an issue for you?

**Comment by jurgenkrol** [comment]
It is not a problem when the user has the permission to see all the volumes. But in this case the user is in a user group where the option "View volume" is unchecked for a specific volume in the settings of the user group. Nevertheless, he can still see the volume and the associated folders if he wants to select an image at, for example, SEOMatic -> "Site Settings" -> "Select Brand Image". In my view, this means that SEOMatic does not fully respect the access rights. By the way, the user cannot see files, only the volume and entire folder structure of that volume.

**Comment by khalwat** [comment]
By default, any relations field in Craft sees all volumes for Assets. The Assets field type goes out of its way to enforce whatever per-volume permissions exist:

https://github.com/craftcms/cms/blob/develop/src/fields/Assets.php#L640

As you can see, there is quite a bit of logic in the Assets field type; that logic does not exist in the "element select" relations by default.

So it's not so much a matter of SEOmatic not respecting permissions as it is SEOmatic doesn't do all the work that the Assets field does to enforce user access to particular volumes.

If this is creating some kind of issue for you, we can look into potentially replicating the code that the Assets field uses to determine allowed volumes. You could also just restrict certain uses from having access to these SEOmatic settings as well.

**Comment by khalwat** [comment]
For now, this is going to be a "won't fix" -- but we have a FR logged to allow for choosing the restrictions for this in a future version of SEOmatic.
