### ISSUE TITLE
Set Entry in Template and use that Entries SEO values

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#1324]
### Question
I'm building out a section where entries have sub-pages powered by a matrix and the url slug (using routes) determined by a block field like this.

Entry (entry.url)
-- matrix block 1 (entry.url/block-field-value)
-- matrix block 2 (entry.url/block-field-value)
-- matrix block 3 (entry.url/block-field-value)

Everything is working, however SEO from SEOmatic is not added to the sub pages. I looked at the docs for a tag that I can place in the template and pass in an entry so that it would use that entries seo values, but did not see it. Is there a way to do this?

ideally there'd be a tag like this or similar:

```twig
{% do seomatic.setEntry(entry) %}
```

Here is the sub-page template with minimal content (not sure it's important, but just in case)

```twig
{% extends '_layout' %}

{% set entrySlug = craft.app.request.getSegment('2') %}
{% set entry = craft.entries.slug(entrySlug).one() %}

{% block content %}
  <section class="py-12 bg-white">
    <div class="container">
      <div class="w-full">
        <h3>This is a sub page</h3>

        {% for block in entry.eventSchedule.collect() %}
          <h3 class="font-semibold text-green-700">{{ block.blockTitle }}</h3>
        {% endfor %}

      </div>
    </div><!-- /.container -->
  </section>
{% endblock %}
```

**Comment by khalwat** [comment]
Does this: https://nystudio107.com/docs/seomatic/using.html#helper-functions-seomatic-helper

```twig
{% do seomatic.helper.loadMetadataForUri(URI, SITE_ID)
```

Do what you want?

If you have routes that Craft doesn't know anything about in terms of what element should be injected on that resulting page, then probably you're going to have to do this manually.

**Comment by CreateSean** [comment]
That works perfectly - Thank you.

ended up with this:

```twig
{# seo - since craft doesn't manage these routes #}
{% do seomatic.helper.loadMetadataForUri(entry.uri) %}
{% set seoTitle = seomatic.meta.seoTitle %}
```

and then later in the template inside a matrix call this
```twig
{% do seomatic.meta.seoTitle(block.eventTitle ~ ' | ' ~ seoTitle) %}
```

which adds the block title to the meta title tag.
