### ISSUE TITLE
Exclude entries from sitemap

### ISSUE THREAD

**Issue by xinningsu** [nystudio107/craft-seomatic#1325]
### Question
There some entries only for some kinds of logged in user, so I don't want to put them in sitemap, any way to achieve that? thanks

### Additional context
Craft Pro 4.4.10
SEOmatic 4.0.19

cc @khalwat

**Comment by khalwat** [comment]
Yes, create an SEO Settings field, and set Robots to none for the entries that are only for logged in users.
