### ISSUE TITLE
Is it possible to fully disable querying and caching for specific elements or urls?

### ISSUE THREAD

**Issue by joshuapease** [nystudio107/craft-seomatic#1326]
### Question
I'm working on an ecommerce site with about 650,00 products.  We're running into issues with our Redis instance always being full.

From what I can tell, SEOMatic caches about 80-120kb of data for each URLs. Not a huge number in isolation, but for that many products, it ends up being 60-70 GB. 

Our Redis instance has an eviction policy of `volatile-lru`. Even though Redis self-manages and we get some level of caching, it's hard to keep important items in the cache for sustained periods of time (example: Sessions are also stored in Redis and get wiped out prematurely). We also can't cache slow-ish queries for very long, which causes some performance issues.

That issue leads me to ask if there's any way to fully bypass Seomatic for these products.

I've tried a few settings and events. But there always seems to be something queried and cached (even with render disabled).

### Additional context

I've played around with [disabling automatic rendering](https://nystudio107.com/docs/seomatic/v3/configuring.html#:~:text=Automatic%20Render%20Enabled) or using [events to exclude containers](https://nystudio107.com/docs/seomatic/v3/advanced.html#includecontainerevent) or element types.

Disabling automatic render reduces the number of cached items down from 3 to 1. However, the cached item that remains after disabling automatic render is the largest of the three (still around 80-90 kb). 

**Automatic Render Enabled**
<img width="964" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/2145998/e52ddaee-f904-4830-b901-10d9280d4a98">

**Automatic Render Disabled**
<img width="959" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/2145998/6379bd2b-f984-402a-be90-9154e96b0c55">

**Comment by khalwat** [comment]
So I have two solutions for you:

1) You can change the SEOmatic cache duration in SEOmatic -> Plugin Settings -> Advanced so that it doesn't cache items for extended periods of time

2) You can use a separate Redis database for your sessions; this is what I do currently, here's an example: 

https://github.com/nystudio107/devmode/blob/develop/cms/config/app.php#L37

https://github.com/nystudio107/devmode/blob/develop/cms/config/app.web.php#L31

I prefer #2 personally.

**Comment by joshuapease** [comment]
Thanks for the fast response! 

Moving sessions to their own DB makes a lot of sense. That was just one example of cache entries getting evicted, but there's a lot of other items in the default cache that are getting prematurely evicted too.

Another option we're considering is using a separate Redis DB for any caching important items our custom modules use. That would at least let us prevent some things things from getting evicted. 

However I'm not aware of any way to put Craft's internal cache calls or `{% cache %}` tags into a different cache component. 

We may need to go with #1 because of that. 

I did some quick and dirty local tests of a short `metaCacheDuration`. Although it adds about 12 queries to the page, the additional query time isn't drastically longer. 

Does that seem like a fair assessment of the performance hit we would take by essentially turning off caching? 

In closing... it seems like there's no real way to totally bypass SEOMatic on a page and avoid caching and/or queries?

**Comment by khalwat** [comment]
There is currently no way to bypass the caching, no. But by decreasing the amount of time meta items are cached, you should be able to have those evicted first (depending on. your Redis policy).

As for the performance hit, it can be significant, but it really depends on the rest of your infra. You can set it to never cache anything, I think, and see what the difference in performance looks like.

There's a good bit of parsing that goes on for the meta data, which is the reason for the two-level cache.
