### ISSUE TITLE
Tracking Script ID settings are blanked when modifying other SEO properties

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-seomatic#1327]
### Describe the bug

I have a very interesting and bizarre issue where it seems "something" keeps blanking the Google Tag Manager/Tracking ID field on Tracking Scripts within SEOMatic for one or more sites, this causes the tracking script to not render, given it's missing the key field required.

It certainly seems to be a process and not a user action, because I have personally seen the value blank, added the correct value and after sometime it's become blank again, with no user action occurring. The SEO plugin settings are under a user group which is restricted to developer and admins, which I am the only one.

We are using multi-site and have several sites using either the Google Tag Manager or Google Analytics GA4 implementation. A few days ago we noticed that our tracking IDs had been nuked completely but with no one making that change.

I appreicate this has very little information to go on and I'm trying to investigate/narrow down a more specific cause, but is there anything in the codebase recently that can be related?

This certainly has never happened throughout most the Version 3 lifecycle in regards to tracking scripts functionality. It is possible that there's something specific in our environment in play, but I'm trying to understand what might be the issue.

Edit: From @zizther, the way to reproduce the issue has been discovered.

### To reproduce
Steps to reproduce the behaviour:

1. Edit any SEOMatic settings not part of the Tracking Scripts settings e.g. Global SEO.
2. The Tracking ID field will be cleared/blanked

It appears to be not specific to a specific tracking script, but any.

### Expected behaviour

The tracking ID to not be modified unless changed via Tracking Scripts.

### Versions
- Plugin version: 3.4.56
- Craft version: 3.8.13

**Comment by zizther** [comment]
I have also come across this issue today as well but using Craft 4.4.13 and SEOmatic 4.0.27

I set GTM to be an environment variable `$GTM_ID` and when I edit content in the Global SEO section it removes the content from the GTM ID field within the Tracking Scripts section.

**Comment by jamesmacwhite** [comment]
Ah! That's an interesting find, for comparison, we do not have the Google Tag Manager ID value as an environment variable, but this also still happens.

I can also confirm, by modifying the global SEO properties, this causes the tracking ID to be wiped. This explains where the issue is coming from now!

For multi-site, modifying each global SEO removes the tracking ID for that site too.

**Comment by zizther** [comment]
Editing any other section besides the Tracking Script section causes all tracking script IDs to be removed, it is not specific to GTM or GA or the value input.

**Comment by jamesmacwhite** [comment]
Thanks for clarifying, I'm just happy you've found how it is able to be reproduced, I'm not going crazy and explains how this had happened! I'm going to assume it's something in a more recent change to the plugin. I don't remember this happening ever before.

**Comment by robzor** [comment]
Hi there, I am also experiencing this bug, this occurred with the Google Tag Manager > Tag Manager ID field. We are using an environment variable for it. 

Craft:  4.4.13
SEOMatic: 4.0.27

This has only happened since we updated to 4.0.27.

Thanks!

**Comment by khalwat** [comment]
Investigating

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/53b874a8655f61ff945bcbb18b1e7336fea02e93 & https://github.com/nystudio107/craft-seomatic/commit/08eb7fcd7b997eedf25d891ebc4d6d3277bd7fe1

Released as:

Craft 3: Version 3.4.57 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.57

Craft 4: Version 4.0.28 -> https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.28

**Comment by robzor** [comment]
Thanks!
