### ISSUE TITLE
Is there a way to exclude pages with "No-index, No-follow" or "none" from ".search" queries?

### ISSUE THREAD

**Issue by sander-lameco** [nystudio107/craft-seomatic#1329]
### Question
Is there a way to exclude pages with "No-index, No-follow" or "none" from `.search` queries?
I know you can add specific fields to the `craft.entries` query just like the SEO field which has the handle `seo`.
`craft.entries.search('*' ~ searchQuery ~ '*').seo.(':notempty:')` works for example.
But is there a way to specifically check for the robots value(s) like: `craft.entries.search('*' ~ searchQuery ~ '*').seo.metaGlobalVars.robots('not all')`?

### Additional context
Another way would be to create a custom Lightswitch in addition to the SEO robots field to check for in the entries query and exclude an entry from search.

**Comment by khalwat** [comment]
Yeah there's no easy way to do that unfortunately, because the SEOmatic data is stored in a JSON blob, and can't be searched directly as you're wanting to.

Honestly what I'd do is just use Craft's native Status lightswitch to just disable entries.
