### ISSUE TITLE
Twitter metatags are not being presented as expected

### ISSUE THREAD

**Issue by Robsondj** [nystudio107/craft-seomatic#1330]
### Question
Hey guys,
I'm facing some issues with Twitter metatags which aren't being shown as expected.
It's like this issue https://github.com/nystudio107/craft-seomatic/issues/1126

Do you have more information about this issue on Twitter?

### Additional context
I have these metatags on my website
<img width="1048" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/621503/618fce51-583d-4921-996d-10a18771dfb3">

 But when I test it the presented information doesn't correspond to the Twitter metatags, but just show the same text configurated to Facebook
 <img width="1047" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/621503/92983b21-19d1-4875-a0f7-2156f861cfcd">

**Comment by khalwat** [comment]
I'd suggest using Twitter's validator instead:

https://cards-dev.twitter.com/validator

...but if the meta tags are appearing in the source (as you've shown in the screenshot), then SEOmatic is doing the right thing. Probably it is the tool you're using to test things

**Comment by Robsondj** [comment]
I tried it on Twitter validator and on Twitter Composer as well, but it doesn't work.
<img width="1032" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/621503/10124151-e784-443a-ada1-629fe72dd499">

**Comment by khalwat** [comment]
Right, that's because you're testing it on a staging site, which has a `robots.txt` set to prevent indexing.

**Comment by Robsondj** [comment]
You were right about the robot.txt on Twitter Validator @khalwat. Thank you! But when I test it on Twitter the image doesn't appear for this page https://web-stage.bcwlabs.com/p/study-test-page-2
Do you know why?
<img width="611" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/621503/0201152a-9338-41d8-822c-cbe7596d69e3">

**Comment by khalwat** [comment]
I don't know why -- the tags look correct to me from your screenshot.

Is it possible you have code somewhere that is putting additional Twitter tags on the page, so there are duplicate tags?

**Comment by Robsondj** [comment]
The validator is not showing the preview anymore
<img width="1021" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/621503/90993eb6-c613-45d8-b5bb-25bd7f13ee41">

**Comment by khalwat** [comment]
It's telling you that the card preview has moved to Tweet Composer, which is apparently something new that they have added.

Viewing the source of the URL: https://web-stage.bcwlabs.com/p/study-test-page-2

I see the tags as expected:

```html
      <meta name="twitter:card" content="summary"/>
      <meta name="twitter:site" content="@BCWGlobal"/>
      <meta name="twitter:creator" content="@elonmusk"/>
      <meta name="twitter:title" content="BCW | Welcome to the Study test page"/>
      <meta name="twitter:description" content="👋 Hey, this is the description field!"/>
      <meta name="twitter:image" content="https://web-stage.bcwlabs.com/assets/_800x800_crop_center-center_82_none/MicrosoftTeams-image-6.png?mtime=1669066848"/>
      <meta name="twitter:image:alt" content="2022 HAROLD Interns, New York"/>
```

(though the creator should be set to the handle of your company, most likely)

**Comment by Robsondj** [comment]
This is just a test page, but a just want to confirm whether the image is not appearing because of a Twitter issue or the website.
I have seen some pages in production with the same behavior.
<br>
For instance, this is a test page in production with a different description for Twitter metatags https://www.bcw-global.com/p/seo-test-page?x-craft-preview=45DIkl9svi&token=q6nYLCPeHCyevGn4CGY6B52JKuKDc7KV
<br>
And this is a normal page on Production which shows the information and the image properly as well
https://www.bcw-global.com/insights/china/key-takeaways-from-chinas-2023-two-sessions
<br>
I want to figure out why the first link doesn't show the image properly and the second one show.
Also the first link doesn't show the description correctly

**Comment by khalwat** [comment]
> This is just a test page, but a just want to confirm whether the image is not appearing because of a Twitter issue or the website. I have seen some pages in production with the same behavior. 
> For instance, this is a test page in production with a different description for Twitter metatags https://www.bcw-global.com/p/seo-test-page?x-craft-preview=45DIkl9svi&token=q6nYLCPeHCyevGn4CGY6B52JKuKDc7KV 

Here are the Twitter tags for this page:

```html
      <meta content="https://twitter.com/BCWGlobal" property="og:see_also"/>
      <meta name="twitter:card" content="summary"/>
      <meta name="twitter:site" content="@BCWGlobal"/>
      <meta name="twitter:creator" content="@BCWGlobal"/>
      <meta name="twitter:title" content="SEO Test Page | BCW"/>
      <meta name="twitter:description" content="Page Description"/>
      <meta name="twitter:image" content="https://www.bcw-global.com/assets/BCW-Group.png"/>
```

Which uses this for the Twitter image: https://www.bcw-global.com/assets/BCW-Group.png

> And this is a normal page on Production which shows the information and the image properly as well https://www.bcw-global.com/insights/china/key-takeaways-from-chinas-2023-two-sessions I want to figure out why the first link doesn't show the image properly and the second one show. Also the first link doesn't show the description correctly

And here are the meta tags for this page:

```html
      <meta content="https://twitter.com/BCWGlobal" property="og:see_also"/>
      <meta name="twitter:card" content="summary"/>
      <meta name="twitter:site" content="@BCWGlobal"/>
      <meta name="twitter:creator" content="@BCWGlobal"/>
      <meta name="twitter:title" content="Key Takeaways from China’s 2023  “Two Sessions” | BCW"/>
      <meta name="twitter:description" content="In this memo, BCW China&#x27;s experts in government and public affairs provide a summary of the key takeaways from the Two Sessions, highlighting their significance in shaping China&#x27;s future direction."/>
      <meta name="twitter:image" content="https://www.bcw-global.com/assets/2-Sessions.png"/>
```

Which uses this for the Twitter image: https://www.bcw-global.com/assets/2-Sessions.png

What is the expected result in both cases?

**Comment by Robsondj** [comment]
In the first case, as you can see, the Twitter description metatag shows
`<meta name="twitter:description" content="Page Description"/>`
But on Twitter the description is **Page Excerpt** and the image doesn't appear
<img width="538" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/621503/3b2eb5f1-730e-4a6c-953f-cc904062b2cb">
<br>
The second one is according to his metatags

**Comment by Robsondj** [comment]
I posted it on Twitter and I saw that the image appears, maybe this is a problem with the preview, but the description is not correct yet.
<img width="548" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/621503/b18695c8-239c-40e9-b994-cfd169245c24">

**Comment by khalwat** [comment]
Twitter also caches Twitter cards, so it could be that as well -- or just Twitter acting weird.

But if the proper tags are there in the source, SEOmatic has done what it is supposed to do.
