### ISSUE TITLE
Sitename is not added to some single pages

### ISSUE THREAD

**Issue by grndctrl** [nystudio107/craft-seomatic#1333]
### Describe the bug
Sitename is not added, either before or after depending on global settings, for some pages.
for instance, I have a Home page where the title becomes `sitename | entry.title` or "Cyberfusion | Home" in this case. but for the About page the title just stays "About".

### To reproduce
Steps to reproduce the behaviour:
Have multiple single pages, all with the exact same SEO field. leave override fields disabled.

### Expected behaviour
Put the site name before every title.

### Screenshots
See SEO preview
<img width="2016" alt="Screenshot 2023-06-14 at 22 04 13" src="https://github.com/nystudio107/craft-seomatic/assets/60090827/e6449cfa-dc4f-4ac0-918d-ea4dcd6fe015">

### Versions
- Plugin version: 4.0.28
- Craft version: 4.4.14

**Comment by khalwat** [comment]
What are your Content SEO settings for the sections in question where it does not appear as you're expecting it to?

**Comment by grndctrl** [comment]
Both settings were "Custom position > Before" for Sitename, but hitting save on the Content SEO settings fixed it. I will just save it manually, but I expected it to also work hitting save on the entry itself.

**Comment by khalwat** [comment]
hmmm strange, you should not have to re-save those settings in Content SEO for it to take effect

**Comment by grndctrl** [comment]
That's what I thought. But I can't find anything different between the two pages. Nor do I remember anything different, besides that I added the About page much later. If anything pops up I let you know.

**Comment by remcoov** [comment]
Hi, we have exactly the same issue. This is new, never had this before.

**Comment by kevinmu17** [comment]
Hmmm. tried to crosscheck a project where this works as expected, both running the same version
```
SEOmatic | 4.0.27

SEOmatic | 4.0.27
```

**Comment by khalwat** [comment]
@remcoov @kevinmu17 please try the resolution that is indicated in this thread, which is to re-save the Content SEO settings for the affected sections in SEOmatic -> Content SEO

**Comment by J-Protz** [comment]
I have this same issue not just for singles. On creation the sitename is excluded despite it being the sitewide default. Resaving in "content" fixes. 

all versions:


```json
 "require": {
        "born05/craft-assetusage": "3.2.0",
        "carlcs/craft-uielementfields": "2.0.3",
        "craftcms/ckeditor": "3.5.1",
        "craftcms/cms": "4.5.3",
        "craftcms/element-api": "3.0.1.1",
        "craftcms/feed-me": "5.2.0",
        "craftcms/redactor": "3.0.4",
        "doublesecretagency/craft-matrixcolors": "3.0.0",
        "nystudio107/craft-retour": "4.1.13",
        "nystudio107/craft-seomatic": "4.0.30",
        "nystudio107/craft-vite": "4.0.6",
        "pennebaker/craft-architect": "4.0.1",
        "presseddigital/linkit": "4.0.4.1",
        "putyourlightson/craft-blitz-recommendations": "2.1.1",
        "servd/craft-asset-storage": "3.4.11",
        "solspace/craft-freeform": "4.1.6",
        "spacecatninja/imager-x": "4.2.2",
        "vaersaagod/matrixmate": "2.1.3",
        "verbb/navigation": "2.0.20",
        "verbb/super-table": "3.0.9",
        "vlucas/phpdotenv": "^3.4.0",
        "wbrowar/adminbar": "3.2.0"
    },

**Comment by khalwat** [comment]
Related: https://github.com/nystudio107/craft-seomatic/issues/1321

**Comment by khalwat** [comment]
Tracked this down; this should be fixed now for newly created sections.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.60”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.31”,
```
Then do a `composer clear-cache && composer update`

**Comment by J-Protz** [comment]
@khalwat will this fix sections already created, or only new ones? Thanks for the fix, will update today!

**Comment by khalwat** [comment]
Only newly created sections

**Comment by kevinmu17** [comment]
@khalwat yessir! nailed it for me. both problems **solved**! `Site Name Position Source` is now set to the correct `same as global Site Name Position` & the Site name is present after the title!

Thanks for the fast response!

**Comment by J-Protz** [comment]
@khalwat confirmed on my end, as well! Thank you!

**Comment by khalwat** [comment]
Awesome. Thanks for your help & patience guys.
