### ISSUE TITLE
Use field labels instead of field names in content settings

### ISSUE THREAD

**Issue by mikeymeister** [nystudio107/craft-seomatic#1335]
### Is your feature request related to a problem? Please describe.
When setting up content SEO settings and using the "from field" options, the select field options are displayed with field names. In some cases this section's field layout contains fields with custom labels. When this is the case it may not be clear which option relates to which field in this context.

### Describe the solution you would like
It would be great if the "from field" options contained the custom labels if/when they have been set.

### Describe alternatives you have considered
Not relabel generic fields and create a new field for each use case.

### Additional context
Craft Pro 4.3.6.1
Seomatic 4.0.19

**Comment by khalwat** [comment]
Can you provide me with a screenshot to show what you mean by custom field labels?

Also, I would recommend updating to the latest version of SEOmatic, which is 4.0.28 at the time of this writing.

**Comment by mikeymeister** [comment]
In one project we have a "Basic Rich Text" field, but in a certain section it is labelled as "Biography". It would be great if in the content SEO settings for that section, the author could select "Biography" from the dropdown rather than "Basic Rich Text".

<img width="418" alt="Screenshot 2023-06-19 at 09 11 21" src="https://github.com/nystudio107/craft-seomatic/assets/34517288/e7ce1ace-3683-4d62-8fea-5702d8e3e107">

 
<img width="324" alt="Screenshot 2023-06-19 at 09 12 06" src="https://github.com/nystudio107/craft-seomatic/assets/34517288/4d7ec457-9052-4a16-97b3-400b936d24d5">

Thanks

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/3ec86f4da243802942bbade0c0253a41b158579b

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.29”,
```
Then do a `composer clear-cache && composer update`
