### ISSUE TITLE
SEO Preview is not displayed for Product Pages

### ISSUE THREAD

**Issue by pom-pom** [nystudio107/craft-seomatic#1336]
### Question
For Craft Commerce Products, the SEO Preview in the sidebar doesn't appear.

It works for all other entries and categories.

Is there a setting that we missed? I only found the "Display Sidebar SEO Preview" Setting which we've set to yes.

Thanks a lot for your help!

**Comment by khalwat** [comment]
Show me a screenshot of what you're looking at please?

**Comment by pom-pom** [comment]
@khalwat here are some screenshots:

Regular Entry (with SEO Preview in the sidebar):
![CleanShot 2023-06-19 at 11 06 57@2x](https://github.com/nystudio107/craft-seomatic/assets/4548353/b3f59f55-8ebd-4f36-8f36-4e12c480d398)

Craft Commerce Product (SEO Preview missing in the sidebar):
![CleanShot 2023-06-19 at 11 06 02@2x](https://github.com/nystudio107/craft-seomatic/assets/4548353/e024c5ca-0e8e-412d-a654-5d00d506496e)

SEO Content Settings for the product:
<img width="1043" alt="CleanShot 2023-06-19 at 11 07 41@2x" src="https://github.com/nystudio107/craft-seomatic/assets/4548353/0a215d33-b74c-4426-aee4-ee7600a636f0">

Our goal would be to get an SEO Preview in the sidebar for our CraftCommerce products.

Thanks a lot for your help!

**Comment by khalwat** [comment]
Interesting, can you provide the version of Craft & Craft Commerce that you're using?

**Comment by pom-pom** [comment]
Sure. It's Craft CMS 4.4.14 / Craft Commerce 4.2.11

**Comment by khalwat** [comment]
Addressed via: https://github.com/nystudio107/craft-seomatic/commit/4d60b6ce9b63d4e17e15a0874edc8b9b99e259e9

Related issue: https://github.com/craftcms/commerce/issues/3199

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.29”,
```
Then do a `composer clear-cache && composer update`
