### ISSUE TITLE
Sitemap index empty

### ISSUE THREAD

**Issue by andres112** [nystudio107/craft-seomatic#1338]
### Describe the bug
Possible issue already reported in #1318, #1253, #997 . but the solution isn't clear so far. 

I have 3 different sites with the groupIds' 1, 3 and 4, unfortunately only the sitemap index generated is for the sitemaps-1, the other 2 are empty. Please consider the screenshots related here below:

### Expected behaviour
Get the sitemaps indexes for each of the sites(groupId).

### Screenshots

**localhost:4200/sitemaps-1-sitemap.xml**
<img width="936" alt="Screenshot 2023-06-20 at 14 29 35" src="https://github.com/nystudio107/craft-seomatic/assets/32916294/60e36339-693a-4121-a2dc-695893b2ccbb">

**localhost:4200/sitemaps-4-sitemap.xml** and **localhost:4200/sitemaps-3-sitemap.xml** 
<img width="894" alt="Screenshot 2023-06-20 at 14 28 36" src="https://github.com/nystudio107/craft-seomatic/assets/32916294/284af3f3-671b-48cc-86a1-81f5194ce543">

But curiously the section which belongs to the groupId=4 is correctly generated

**localhost:4200/sitemaps-4-section-ecosystemPage-8-sitemap.xml**
<img width="898" alt="Screenshot 2023-06-20 at 14 30 07" src="https://github.com/nystudio107/craft-seomatic/assets/32916294/af457602-52fd-4a81-a22f-407ed762ad04">

When I click from this screen in Back to index, return to the localhost:4200/sitemaps-**1**-sitemap.xml instead of localhost:4200/sitemaps-**4**-sitemap.xml

Is important to mention that the site with the groupId=1 is the primary.

### Versions
- Plugin version: ^4.0
- Craft version: 4.4.14

**Comment by khalwat** [comment]
Ensure that you have **This site has its own base URL** checked for each site in Settings -> Sites, with an appropriate **Base URL** entered.

**Comment by andres112** [comment]
Hi. thanks for the quick reply.

Yes all the 3 sites has the own site check box enabled, and using an alias as base Url  --> "@frontend"
<img width="274" alt="Screenshot 2023-06-20 at 16 58 12" src="https://github.com/nystudio107/craft-seomatic/assets/32916294/8a522178-7800-47ad-b654-5099ec9181a9">

And in the overview, all the sites have the base url as here below:
<img width="1013" alt="Screenshot 2023-06-20 at 17 03 22" src="https://github.com/nystudio107/craft-seomatic/assets/32916294/c8b164b5-730e-48a3-bab1-fc948a7d4850">

Important to mention: all the sites has the same Base URL because we are using Craft as Headless CMS and handling the routing at frontend based on the prefixed sections urls.

**Comment by andres112** [comment]
Hi @khalwat,
Any suggestion or hint about this issue. 😊

**Comment by khalwat** [comment]
I've been unable to replicate this locally.

SEOmatic stores separate settings for each site, can you ensure that Sitemaps are enabled for each of your sites in the SEOmatic -> Content SEO -> section -> Sitemaps?

**Comment by andres112** [comment]
Hi @khalwat. Yes I already verify the configuration for each site/entries and all of them have the sitemap enabled.
it's important to mention that all of sites have the same base url. as shown below 👇🏼 .

<img width="351" alt="Screenshot 2023-06-28 at 18 10 47" src="https://github.com/nystudio107/craft-seomatic/assets/32916294/3df9dd2d-5275-4982-bd2f-c949c8a1d756">

**Comment by khalwat** [comment]
Well, at this point with me being unable to replicate it, my best suggestion is that we do a video screen share to have a look at what's going on.

You can book it here:

https://savvycal.com/nystudio107/chat

**Comment by khalwat** [comment]
Will re-open if additional information is provided, or a conference call booked.
