### ISSUE TITLE
Including images in the sitemap which are stored in a matrix nested inside a neo field

### ISSUE THREAD

**Issue by jeroenbraspenning** [nystudio107/craft-seomatic#1339]
### Question
I'm working on a project which has a Neo field to layout the content. Inside the Neo field is a Matrix fields which has a couple of image variation fields. With this structure the client can create flexible layouts.

While inspecting the SEO i noticed that the sitemap only shows the images which are stored in top level fields. So the header and cover image, which are separate fields, are added to the sitemap. The nested images are ignored.

Is this behaviour intended and if that is the case are there ways for me to supply the images to the sitemap myself with some kind of hook?

### Additional context
Neo 2.13.19
SEOmatic 3.4.57 
Craft Pro 3.8.14

**Comment by khalwat** [comment]
Currently, there is no solution for providing images in the sitemap that are in nested fields inside of Neo blocks, unfortunately.

You could add them yourself using the event `RegisterSitemapUrlsEvent` or `RegisterSitemapsEvent`, depending on whether you want to add additional URLs, or if you want to add an entire sitemap for said images:

https://nystudio107.com/docs/seomatic/advanced.html#registersitemapurlsevent

**Comment by mihob** [comment]
@khalwat 

The ticket is quite old, but the issue is similar.

Should images from nested matrix fields (matrix field within a matrix field) be included in the sitemap? At the moment, it does not appear so.

**Comment by khalwat** [comment]
@mihob See the answer above, currently there is no support for traversing recursively through nested matrix fields to look for images to include in the sitemap.

**Comment by khalwat** [comment]
@mihob SEOmatic now does handle Content Block fields in Craft 5 however, and thinking about it, adapting that code to work with nested Matrix Block fields probably wouldn't be too bad. Are you running Craft 5?

**Comment by mihob** [comment]
@khalwat Yes, we are running craft 5

**Comment by khalwat** [comment]
Addressed in the above commits. Give this a shot and lmk how you go @mihob 

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.19”,
```
Then do a `composer clear-cache && composer update`
