### ISSUE TITLE
Remove hreflang from sitemap if all sites have the same language

### ISSUE THREAD

**Issue by Romanavr** [nystudio107/craft-seomatic#1340]
### Is your feature request related to a problem? Please describe.
I'd like to be able to remove hreflang from sitemaps if all my (sub)sites are in the same language, because then there's no point in adding hreflang.

### Describe the solution you would like
It would be possible to add a switcher in the settings or just this in the code, somewhere near here: https://github.com/nystudio107/craft-seomatic/blob/46dc01226cb5e1db3a5953d0dc48b1bc6982a6f2/src/helpers/Sitemap.php#L246

### Describe alternatives you have considered
I don't see any alternatives.

### Additional context
I have a main site + 50 subsites, they all use the same language so it doesn't make sense for me to add hreflang with the same language for all sitemaps.
Our SEO guy asks to remove this, however, as I can see from the code, for now I can't do it without your help.

**Comment by khalwat** [comment]
If these sub-sites are not translations of the primary site, you should turn off the **Site Groups define logically separate sites** option in SEOmatic -> Plugin Settings -> Advanced:

https://nystudio107.com/docs/seomatic/technologies.html#multi-site-language-locale-support

**Comment by Romanavr** [comment]
Thanks

**Comment by Romanavr** [comment]
@khalwat Sorry, but the problem still remains
I did what you suggested but it didn't work. Could you re-open please?
Or maybe I should do something I don't know.

`hreflang=*my lang*` still there + `rel="alternate"` not removed too.
The problem is relevant only for sitemaps

**Comment by khalwat** [comment]
Can you clarify exactly how your sites are set up? There are 50 sites, but are there any site groups?

Can you also clarify what the **Site Groups define logically separate sites** setting is set to?

Also, what is the problem that the SEO guy says will be solved by this?

**Comment by Romanavr** [comment]
> Can you clarify exactly how your sites are set up? There are 50 sites, but are there any site groups?
> 
> Can you also clarify what the **Site Groups define logically separate sites** setting is set to?
> 
> Also, what is the problem that the SEO guy says will be solved by this?

1. 4 site groups
2. It's OFF
3. By removing `hreflang` and `rel=alternate` across all sitemaps OR removing  `rel=alternate` and setting `hreflang=x-default` we will solve the problem that shows up in SEO tools during analysis(like ahrefs.com). I don't really know what impact this might have on SEO..
But in fact it just doesn't make sense logically to tag page with the `rel=alternate` and write the same language in the hreflang when all sites have the same language.

**Comment by khalwat** [comment]
Given that sitemaps are about discovery, and not about indexing or SERP, it'll have zero impact on the SEO.

I'm curious what the motivation is here from your SEO guy? Can you ask him what this will do/solve exactly?

I still plan on addressing it, I'm just curious what the explanation is.

**Comment by Romanavr** [comment]
> Given that sitemaps are about discovery, and not about indexing or SERP, it'll have zero impact on the SEO.
> 
> I'm curious what the motivation is here from your SEO guy? Can you ask him what this will do/solve exactly?
> 
> I still plan on addressing it, I'm just curious what the explanation is.

SEO guy reply:


> 
> Using the "rel=alternate" hreflang attribute when it is not necessary (i.e., when your website has only one language version) is unlikely to directly hurt your website's performance or SEO. Search engines generally handle incorrect or unnecessary hreflang annotations gracefully, and it is not considered a critical issue.
> 
> However, there are a few potential negative impacts to consider:
**Confusion for Search Engines**: Unnecessary hreflang annotations might cause confusion for search engines, leading to misinterpretation of your website's content. While this is unlikely to have a major impact, it's best to provide accurate information to search engines.
**Wasted Crawl Budget**: Search engine crawlers have a limited budget for each website, which means they allocate a certain amount of resources to crawl and index your content. By including unnecessary hreflang annotations, you might be wasting some of this crawl budget, which could be better used to crawl other relevant pages on your site.
**Maintenance Overhead**: If you add hreflang annotations unnecessarily, it adds a bit of extra complexity to your website's code. While this is not a significant concern, it does introduce some maintenance overhead, especially if you have to manage multiple pages or update your site in the future.
> 
> Overall, while using "rel=alternate" hreflang when it's not needed won't severely hurt your website, it's best practice to use this attribute only when you have multiple language versions of your site or when you have similar content targeted to specific regional audiences. For a single-language website, there's no real benefit in using hreflang, so it's better to avoid it to keep things simple and straightforward.

**Comment by khalwat** [comment]
I'm not particularly convinced by any of those arguments; it's all tangential speculation. 

In any event, as soon as I'm able to replicate the issue on my end, I'll be able to fix it. So onto that.

**Comment by khalwat** [comment]
Do you have a live URL where I can see the problem in evidence?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/5f1ae7c2ecf79bce0f120ab96b356ef88b70ad5e & https://github.com/nystudio107/craft-seomatic/commit/9e58b13ab3f3cdc82ab5de33fc6ca67ed86f28c9

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.60”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.31”,
```
Then do a `composer clear-cache && composer update`

**Comment by Romanavr** [comment]
Thanks!
