### ISSUE TITLE
Possible to set twitter:label/data attributes?

### ISSUE THREAD

**Issue by ammonhaggerty** [nystudio107/craft-seomatic#1341]
I'd like to add some less common attributes (label and data) to the meta information. I'm dynamically constructing the meta info, so using `seomatic.meta.setAttributes`. But my attempt to simply add the attributes aren't working.

Here's the part of the code that isn't working (everything else is working fine). 
```
{% do seomatic.meta.setAttributes({
  twitter: {
    label1: "Hosted by",
    data1: memberFirst ~ " " ~ memberLast,
    label2: "When",
    data2: eventTime|date('F j')
  }
}) %}
```
Thanks!

**Comment by khalwat** [comment]
You do do that with the `.tagAttrs()` method, to add arbitrary attributes:

https://nystudio107.com/docs/seomatic/using.html#extra-tag-attributes

```twig
{% set tag = seomatic.tag.get('twitter:card') %}
{% if tag | length %}
    {% do tag.tagAttrs({
        label1: "Hosted by",
        data1: memberFirst ~ " " ~ memberLast,
        label2: "When",
       data2: eventTime|date('F j')
    }) %}
{% endif %}
```

You can see the actual tag names for all of the Twitter tags here:

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/seomatic-config/globalmeta/TagContainer.php#L215
