### ISSUE TITLE
Filter url's (redirects) by response code in sitemap 

### ISSUE THREAD

**Issue by whitechandler73** [nystudio107/craft-seomatic#1342]
A recent sitemap audit suggests to remove url's that respond with redirects from the sitemap to improve seo. Is there currently a way to do this with seomatic?

**Comment by khalwat** [comment]
You can do it yourself if you want, see:

https://nystudio107.com/docs/seomatic/advanced.html#registersitemapurlsevent

But there is no way this is going to "improve SEO". Sitemaps are about discovery, not indexing, and they have nothing to do with the SERP.
