### ISSUE TITLE
Lock on saving entry

### ISSUE THREAD

**Issue by Thijmen** [nystudio107/craft-seomatic#1344]
### Describe the bug
On saving an entry, we are getting the following SQL lock:

```
General error: 1205 Lock wait timeout exceeded; try restarting transaction The SQL being executed was: UPDATE `craft_elements` SET `dateUpdated`='2023-07-13 12:47:05' WHERE `id`=3259207
```

Sometimes we see this error too:

```
UPDATE `craft_seomatic_metabundles` SET `dateUpdated`= │
│ '2023-07-13 12:41:48', `sourceDateUpdated`='2023-07-13 12:41:48' WHERE `id`=28
```

It doesnt happen on every entry though. Only on very specific ones. It's impossible to save these,  in such cases. Each times, it ends up with a lock timeout.

### To reproduce
Steps to reproduce the behaviour:
1. Save entry in admin

### Expected behaviour
Entry gets saved

### Versions
- Plugin version: 4.0.28
- Craft version: 4.4.14

**Comment by khalwat** [comment]
This is highly unlikely to be an issue with SEOmatic itself; it sounds more like a devops or hosting issue. Probably your database and / or PHP is hitting capacity.

Probably the questions is more appropriate for support@craftcms.com -- but I think it will end up being related to your specific SQL / PHP devops setup.

**Comment by Thijmen** [comment]
Our database is not even hitting a max CPU at all, plenty of capacity there. Any help would be greatly appreciated.

**Comment by khalwat** [comment]
I don't believe the issue you're running into has anything to do with SEOmatic.

A more appropriate support venue would be to contact Pixel & Tonic for support:

support@craftcms.com

...but I don't think this will end up being an issue with Craft, either. It's more likely to be something to do with your devops/server environment.

**Comment by khalwat** [comment]
You could also try joining the Craft CMS Discord:

https://craftcms.com/blog/discord

...and ask your question in the `#devops` channel
