### ISSUE TITLE
Google Tag Manager noscript template is output with <script> tags around it

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-seomatic#1346]
### Describe the bug

Since updating to 3.4.58, the Google Tag Manager noscript template is output as:

```html
<script><noscript>
<iframe src="https://www.googletagmanager.com/ns.html?id=xxxxxxxx" height="0" width="0" style="display:none; visibility:hidden"></iframe>
</noscript>
</script>
```

I have confirmed the `<script>` tag is not present in my actual noscript template, it appears to be added by the plugin.

Downgrading to 3.4.57 works fine. I'd hint there is a regression potentially, likely this: https://github.com/nystudio107/craft-seomatic/commit/eae2cc4e6c0b54c7f4555d049d51ca8d3bfbb0f6

### Versions
- Plugin version: 3.4.58
- Craft version: 3.8.16

**Comment by khalwat** [comment]
Regression from https://github.com/nystudio107/craft-seomatic/issues/1334

Will fix shortly.

**Comment by jamesmacwhite** [comment]
Thank you. Downgrading works fine for now.

**Comment by stefanfriedrich** [comment]
downgrading from 4.0.29 to 4.0.28 also works.

**Comment by khalwat** [comment]
Addressed in:

Craft 3: Version `3.4.59` -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.59

Craft 4: Version `4.0.30` -> https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.30
