### ISSUE TITLE
Section sitemaps - some duplicate entries, some missing

### ISSUE THREAD

**Issue by jamiepittock** [nystudio107/craft-seomatic#1347]
I have a section sitemap that lists 214 urls. We have 214 entries in this section so that looked correct.

However, a lot of the URLs are duplicates and there are around 100 entries that aren't listed.

Is this expected behaviour? I've tried clearing the cache.

I'd be happy to share the sitemap privately if you tell me where to send it.

### Versions
- Plugin version: 4.0.30
- Craft version: 4.4.16.1

**Comment by khalwat** [comment]
Definitely not expected behavior, but all SEOmatic does is loop through the entries in the section, and ask for their URLs. I'd be surprised if something was amiss with the code here.

Feel free to send me the sitemap however you like.

andrew@nystudio107.com

**Comment by jamiepittock** [comment]
@khalwat I've emailed you a couple of times but heard nothing. Have you seen them?

**Comment by khalwat** [comment]
I have not seen any emails from you, no.

**Comment by jamiepittock** [comment]
Any other suggestions then? I've sent emails to the address you gave.

**Comment by khalwat** [comment]
Found it — the email was in my junk mail folder

**Comment by khalwat** [comment]
I looked at the URL provided privately and do not see any duplicate entries in the sitemap. Closing, unless further information is provided.

If you replied to my last email @jamiepittock I did not receive it.
