### ISSUE TITLE
SEO-Image source returns faulty URL on multisite setup.

### ISSUE THREAD

**Issue by sandrodunkel** [nystudio107/craft-seomatic#1349]
### Describe the bug
When using a multilingual setup (using sites) and setting the Image source to «From Asset Field», SEOmatic returns an invalid asset URL. The primary domain is http://domain.com, all assets are therefore available under http://domain.com/assets/[…]. On a secondary domain using http://domain.com/fr, SEOmatic should still return the same asset URL. However, it returns http://domain.com/fr/assets/[…] which is not correct. This seems to work ok in the control panels' SEO preview, but the actual og:image gets an invalid asset URL.

### To reproduce
Steps to reproduce the behaviour:
1. Set up multilingual sites.
2. Choose «From Asset Field» as the «SEO Image Source»

### Expected behaviour
All assets should be returned using the primary site's URL, not the URL of the current site.

### Versions
- Plugin version: 4.0.9
- Craft version: 4.2.7

**Comment by khalwat** [comment]
So when you select "From Asset Field" it's effectively doing `assetField.getUrl()` -- so if that isn't returning the proper value, my guess is your Asset Volume isn't set properly (maybe it's a relative URL?) or your site URLs aren't set properly.

**Comment by sandrodunkel** [comment]
A relative URL in the Asset Volume has been the problem. Seems strange that SEOmatic can't handle the relative URL but a simple `assetField.getUrl()` in a twig template works perfectly fine. Nevertheless I now know how to fix this. Thanks!

**Comment by khalwat** [comment]
It's not that SEOmatic can't handle it, it's that social media sites **require** that the various social URLs are absolute URLs, and not relative URLs.

It makes sense if you think about it, because they need an absolute URL to reference the image, since there is no web page context.

**Comment by sandrodunkel** [comment]
You're right, of course *facepalm* Thanks for your help!
