### ISSUE TITLE
devMode <title> prefix setting won't save blank value

### ISSUE THREAD

**Issue by dreadfullyposh** [nystudio107/craft-seomatic#135]
If I remove the value from the devMode title prefix in the plugin settings, the value won't save and returns to the original value of [devMode]. 

I am able to override the setting with an empty string in a config file.

**Comment by khalwat** [comment]
Ah, I think it might be expecting a value. I'll check the validation rules.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6878bddfcabcfc33c2340c0d722c3fa2a17568f9
