### ISSUE TITLE
How to save manually values in entry object

### ISSUE THREAD

**Issue by QUACK07** [nystudio107/craft-seomatic#1350]
### Question
Hello team, I'm trying to update the robots value with a new value in this way
**$entryData->seomaticMeta->metaGlobalVars->robots = 'noindex';**
but when I save **Craft::$app->getElements()->saveElement($entryData);** this doesn't make any change on the entry

### Additional context
<img width="743" alt="Screenshot 2023-07-31 at 12 12 08" src="https://github.com/nystudio107/craft-seomatic/assets/17518469/dc1e73ff-9592-4330-9f52-fc77fddb0e86">

**Comment by khalwat** [comment]
Are you trying to update an SEO Settings field value? Or are you trying to change this in Global SEO or Content SEO?

**Comment by QUACK07** [comment]
I'm trying to update that SEO setting value, I got the field data from entry data with  **$entries = Entry::find()**

**Comment by khalwat** [comment]
If you validate the `metaGlobalVars` model after making the change, are there any errors in it?

**Comment by QUACK07** [comment]
no I'm not, let me validate

**Comment by QUACK07** [comment]
everything looks fine in the object 
Code:
```
echo("Robots {$entryData->seomaticMeta->metaGlobalVars->robots} \n");
$entryData->seomaticMeta->metaGlobalVars->robots = 'noindex';
echo("Robots updated {$entryData->seomaticMeta->metaGlobalVars->robots} \n");
Craft::$app->getElements()->saveElement($entryData);
```
```
Terminal
Robots noarchive 
Robots updated noindex 

```
No errors

**Comment by khalwat** [comment]
Right but what I'm saying is validate the `$entryData` model _after_ you do `saveElement()` -- if there are any errors, they will be listed on the model.

https://www.yiiframework.com/doc/api/2.0/yii-base-model#validate()-detail

**Comment by QUACK07** [comment]
there are no errors before of after saveElement() using 
`$entryData->validate();`

**Comment by QUACK07** [comment]
actually I got a success true on saveElement(); event
```
$success = Craft::$app->getElements()->saveElement($entryData);
 echo($success);
```
Terminal
`1`

**Comment by QUACK07** [comment]
I'm validating metaGlobalVars before and after saving but everything is true
 **$entryData->seomaticMeta->metaGlobalVars->validate()**

**Comment by khalwat** [comment]
Weird, not sure what to tell you without more context. What you're doing looks right on the surface.

**Comment by QUACK07** [comment]
it is an easy code, in a resume is this:
```
$entries = Entry::find()
                ->descendantOf($entryId)
                ->all();


foreach ($entries as $key => $entryData) {
      $entryData->seomaticMeta->metaGlobalVars->robots = 'noindex';
       Craft::$app->getElements()->saveElement($entryData);
}
```

**Comment by khalwat** [comment]
So you have it working, then?

**Comment by QUACK07** [comment]
nop, when I run the saveElement, it doesn't apply changes and does not show errors

**Comment by ing-ivan-31** [comment]
@khalwat,  i am working with @QUACK07 on this trying to save programmatically new data inside the **metaGlobalVars** object more on specific modify **the robots property**, i am trying to modify on this way:

````
$entries = Entry::find()
            ->descendantOf($this->mojocheckId)
            ->all();
            
foreach ($entries as $key => $entryData) {

     $metaBundleRecord = $entryData->seomaticMeta;

      if ($metaBundleRecord &&  $metaBundleRecord->validate(null, true)) {
                    $attributes = $metaBundleRecord->getAttributes(['metaGlobalVars']);

                    $attributes['robots'] = 'noindex';
                    $metaBundleRecord->setAttributes($attributes, false);

                    Craft::info(print_r($metaBundleRecord, true));
                    $metaBundleRecord->save();
                }
}
````

but the **save** method does not exist, maybe i am working with an incorrect approach, could you help us or guide us.

thank you

**Comment by khalwat** [comment]
Yeah so it's not actually a "MetaBundleRecord" -- it's a `MetaBundle` object that is saved in the field data on an entry:

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/models/MetaBundle.php

So what you'd need to do is modify the field data, and then save the Entry itself.

**Comment by khalwat** [comment]
Any more help needed on this? Perhaps the best way forward would be to do a screen share and look at your code together?

**Comment by QUACK07** [comment]
Oh, thanks! that is a good idea. let's make a date

**Comment by khalwat** [comment]
Book it here: https://savvycal.com/nystudio107/chat

**Comment by khalwat** [comment]
So this ends up not really being an SEOmatic thing, but rather being a Craft thing, in that when setting custom field values, you need to use `setFieldValue()` rather than setting the field values directly.

The details and discussion on this can be found here:

https://github.com/craftcms/cms/issues/5449

**Comment by khalwat** [comment]
Roughly:

```php
$seoFieldData = $entryData->seomaticMeta;

$seoFieldData->metaGlobalVars->robots = 'noindex';
$seoFieldData->metaGlobalVars->overrides['robots'] = true;

$entryData->setFieldValue('seomaticMeta',$seoFieldData);
```
