### ISSUE TITLE
og:locale is showing as en_EN instead of en_GB

### ISSUE THREAD

**Issue by jamiematrix** [nystudio107/craft-seomatic#1351]
### Describe the bug
The default `og:locale` value is being output as "en_EN" which, from what I can find, isn't a valid value. [Google](https://developers.google.com/search/docs/specialty/international/localized-versions?visit_id=638264864611818330-952292494&rd=1#language-codes) has "en_GB" and [this list of codes](https://sites.ualberta.ca/dept/chemeng/AIX-43/share/man/info/C/a_doc_lib/aixbman/baseadmn/locale.htm) also shows "en_GB".

I can't see a way to override what is set in `og:locale`, but the default value should be a valid one anyway.

### To reproduce
Steps to reproduce the behaviour:
1. View page source of site with a site in English

### Expected behaviour
Research (and an SEO team) suggest the value should be `en_GB`

### Versions
- Plugin version: 4.0.27
- Craft version: 4.4.13

**Comment by khalwat** [comment]
Can you please double-check your Site language settings in Craft?  I checked, and I see it outputting what I'd expect:

```html
<meta content="en_US" property="og:locale">
<meta content="es_ES" property="og:locale:alternate">
```

**Comment by jamiematrix** [comment]
Apologies! I thought I checked beforehand.

The site had been set to "English - en" instead of "English (United Kingdom) - en-GB".
