### ISSUE TITLE
Option to *not* submit section sitemap to search engines when content changes

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/craft-seomatic#1352]
### Is your feature request related to a problem? Please describe.
We have some channels with frequent or regular changes that have a high number of URLs, so these sitemap submissions pull focus from areas of the site that we want Google to index. Think of a catalog page with a thousand items that might contain counts of reviews. When a new review comes in, this would trigger the whole catalog to be submitted again, even if the content really hasn't changed.

### Describe the solution you would like
We'd like a lightswitch in the Content SEO section that would suppress the submission of content changes to search engines for that section. The sitemap should still be updated, but we'd rely on regular sitemap crawling to access these areas. A more complex version would be to apply the daily/weekly/monthly, etc. settings within Content SEO to submission frequency, but that sounds like be overkill and way too much overhead. 

### Describe alternatives you have considered
We've considered turning off those sections of the sitemap for a period of time and turning them back on as needed, but that requires regular human intervention and we worry about "confusing" the crawlers. We've also considered limiting the section to the most recently changed X items, but still worry we're getting enough frequent noise to these channels that we're submitting changes too frequently. 

### Additional context
I'd envision showing whether the sitemap is being sent upon changes on this view here, which shows a channel with >500 entries
<img width="1208" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/39066452/d4484b4e-e1d3-466c-81c4-6c0892a8ced7">

**Comment by khalwat** [comment]
Now that Google & Bing have both deprecated their endpoints, SEOmatic no longer submits sitemaps to endpoints.

https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping
