### ISSUE TITLE
Security.txt location is wrong

### ISSUE THREAD

**Issue by karensg** [nystudio107/craft-seomatic#1353]
### Describe the bug
Security.txt file is generated in the root folder, but should be under the `.well-known` directory.
More info: https://securitytxt.org/

### Versions
- Plugin version: latest
- Craft version: 4.4

**Comment by khalwat** [comment]
SEOmatic can't do that, because Craft doesn't exist there. You can create an alias, though if you want. However:

> For web-based services, organizations MUST place the "security.txt" file under the "/.well-known/" path, e.g., https://example.com/.well-known/security.txt as per [[RFC8615](https://www.rfc-editor.org/rfc/rfc9116#RFC8615)] of a domain name or IP address. **For legacy compatibility, a "security.txt" file might be placed at the top-level path or redirect (as per [Section 6.4](https://www.rfc-editor.org/rfc/rfc7231#section-6.4) of [[RFC7231](https://www.rfc-editor.org/rfc/rfc9116#RFC7231)]) to the "security.txt" file under the "/.well-known/" path.** If a "security.txt" file is present in both locations, the one in the "/.well-known/" path MUST be used

ref: https://www.rfc-editor.org/rfc/rfc9116#name-location-of-the-securitytxt

Emphasis mine.

**Comment by khalwat** [comment]
Actually, I was thinking about this wrong -- as long as no file exists in that path, it should work.

So might as well serve it up from there as well as the legacy location (or instead of)

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/4cb0fa4cc35c6facfa34ea28b694dc4222e4233a & https://github.com/nystudio107/craft-seomatic/commit/71a334b86f2004f8d7a9727fe2179516893ca2d6

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.62”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.32”,
```
Then do a `composer clear-cache && composer update`

**Comment by bartdigitalpulse** [comment]
> Actually, I was thinking about this wrong -- as long as no file exists in that path, it should work.
> 
> So might as well serve it up from there as well as the legacy location (or instead of)

@khalwat 

The legacy location doesn't exists anymore? I have to create a redirect to /security.txt  from /.well-known/security.txt otherwise I'll get a 404. 

Craft Pro 3.9.5
Seomatic 3.4.63

**Comment by khalwat** [comment]
The legacy location does not exist anymore. If you want to create a redirect for it, you can, but odds are good that bots will try both locations... and this is the new, preferred location.
