### ISSUE TITLE
Disabling regenerateSitemapsAutomatically from custom module

### ISSUE THREAD

**Issue by hatyi** [nystudio107/craft-seomatic#1355]
### Question
Hi there!
I've been a happy user of the SEOmatic plugin for a few years already in multiple projects.
In the past hour I was trying to disable the **Regenerate Sitemaps Automatically** setting from a custom module, but unfortunately I wasn't able to figure this out by myself, nor could I find any helpful information related to this in the [docs](https://nystudio107.com/docs/seomatic/).
Setting this attribute manually in the admin is not really a feasible solution for me in this scenario.
If I had the ability to disable this for a specific element type that would be the best, but if I could only do this "globally" that's also a good solution.

### Additional context
I'm importing a huge amount of products to a webshop, and I'd like to have control over the sitemap generation during this process, so ideally disable this automatic functionality when I start the import process and run the queue job(s) once the whole thing is finished.

Could you please provide some insights or point me to a direction where I can figure out how to do this?
Thanks in advance!

**Comment by khalwat** [comment]
Something like:

```php

use nystudio107\seomatic\Seomatic;

...

Seomatic::$settings->regenerateSitemapsAutomatically = false;
```

or you can do:

```php

$element->setScenario(Element::SCENARIO_ESSENTIALS);
```

before saving the element.
