### ISSUE TITLE
[FR] Option to generate single sitemap, instead of nested by CP section

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/craft-seomatic#1356]
### Is your feature request related to a problem? Please describe.
Our SEO team wants to have a single sitemap with all site pages in it, instead of the current sitemap of sitemaps because the way our entries are divided into sections does not always reflect the hierarchy of the pages within the site. They are also concerned that the additional links which need to be followed especially for *singles* within the site may keep important pages from being indexed regularly and efficiently. We have recently turned off auto submission of our sitemap. We have some large areas of the site which are updated frequently through Feed Me and don't merit frequent submission. These sections are low priority, but should be part of the sitemap for discoverability. 

### Describe the solution you would like
We would like a lightswitch on the Plugins Settings->Sitemap which would allow us to specify producing a single sitemap file with a collated list of all the pages currently within the sub sitemaps, as they are currently toggled to be added to the sitemap in the Content SEO section. For multi-site tenanted systems, this should be a single file per site.
Ideally, if they were sorted by section according to the priority, that would be a bonus.

### Describe alternatives you have considered
We are considering having a developer periodically build this file manually by copying the XML from the various sitemaps and collating it.

### Additional context
If you can allow sitemap submission via the CP or a console command, that would allow us to push new sitemaps as needed or scheduled on the server https://github.com/nystudio107/craft-seomatic/issues/734 like `./craft seomatic/sitemap/submit`

**Comment by khalwat** [comment]
This isn't going to happen; also the concerns of your SEO team are unfounded imo. Google actually recommends breaking things up into multiple sitemaps for crawling efficiency reasons.

If they are able to present me with some actual experiments that demonstrate the veracity of their claims, I'd be happy to re-open it.
