### ISSUE TITLE
[FR] Can't get "SEO Image Source" asset to access the asset's alt field

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#136]
All images on our site have `alt` fields tied to them. We'd like to dynamically generate our **SEO Image Description Source** content from something like `{seomatic.meta.seoImage.alt}`, but `{{ seomatic.meta.seoImage }}` doesn't return the asset, just a string  – `string(49) "{seomatic.helper.socialTransform(770, "base", 1)}"`.

Not really sure what I can do with that and need your help!

Maybe we just encourage everyone to use `alt` fields on their image assets and make that the default! (I'm kidding, but kind of serious)

**Comment by khalwat** [comment]
This might interest you:

https://github.com/nystudio107/craft-seomatic/issues/52
