### ISSUE TITLE
GraphQL seomatic pigbacking no longer present on ElementInterface

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-seomatic#1360]
Previously it was possible to use a GraphQL fragment across different element types by setting `ElementInterface` as the type condition (see below).

```gql
fragment seo on ElementInterface {
  seomatic(asArray: true) {
    metaTitleContainer
    metaTagContainer
    metaLinkContainer
    metaScriptContainer
    metaJsonLdContainer
    metaSiteVarsContainer
  }
}
```

In the current version of the plugin `seomatic` doesn’t appear to be present on that interface anymore, which caused some build crashes for us.

We can resolve this quickly by just duplicating that fragment to each element type, but this isn’t as nice as having a single interface shared across all (i.e. this is a low priority).

This was noticed updating a site from Craft 4.5.3 to 4.5.6.1 and SEOmatic from 4.0.30 to 4.0.31.

**Comment by khalwat** [comment]
I haven't changed anything at all in SEOmatic's GraphQL implementation.

Is it possible there is a Craft change, or something else is going on here?

**Comment by khalwat** [comment]
@joshuabaker I'm going to close this only because the GQL implementation hasn't changed at all, so I'm thinking it's unrelated to SEOmatic.

If you find otherwise, or there were some kind of Craft changes that necessitate a change on my end, feel free to comment and I'll re-open this.

**Comment by joshuabaker** [comment]
Yep, that’s cool. Thanks, @khalwat.

Anyone else experiencing this can see reference craftcms/cms#13758.
