### ISSUE TITLE
Syntax error on digitalproductmeta JsonLDContainer

### ISSUE THREAD

**Issue by mariuswestgaard** [nystudio107/craft-seomatic#1361]
### Describe the bug
I see the following error with stack trace in my logs when visiting a Digital Product entry in our website. The page does not crash, but leaves the error in our logs, and an error in the Json ld script on the site.

This is the outputted Json ld script value of availability: 
`"availability":"http://schema.org/{% if product.getIsAvailable() %}InStock{% else %}OutOfStock{% endif % }}"`

`2023-09-29 08:56:53 [-][-][-][error][nystudio107\seomatic\helpers\MetaValue::parseMetaString] Error rendering `http://schema.org/{% if product.getIsAvailable() %}InStock{% else %}OutOfStock{% endif % }}` -> Unexpected "}" in "__string_template__8521f8a5ab0d7d796779587cbe981f6c" at line 1. - http://schema.org/{% if product.getIsAvailable() %}InStock{% else %}OutOfStock{% endif % }}
2023-09-29 08:56:53 [-][-][-][error][Twig\Error\SyntaxError] Twig\Error\SyntaxError: Unexpected "}" in "__string_template__8521f8a5ab0d7d796779587cbe981f6c" at line 1. in /srv/app/nortek-craft-3/htdocs/vendor/twig/twig/src/Lexer.php:353
Stack trace:
#0 /srv/app/nortek-craft-3/htdocs/vendor/twig/twig/src/Lexer.php(294): Twig\Lexer->lexExpression()
#1 /srv/app/nortek-craft-3/htdocs/vendor/twig/twig/src/Lexer.php(195): Twig\Lexer->lexBlock()
#2 /srv/app/nortek-craft-3/htdocs/vendor/twig/twig/src/Environment.php(541): Twig\Lexer->tokenize(Object(Twig\Source))
#3 /srv/app/nortek-craft-3/htdocs/vendor/twig/twig/src/Environment.php(594): Twig\Environment->tokenize(Object(Twig\Source))
#4 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/web/twig/Environment.php(60): Twig\Environment->compileSource(Object(Twig\Source))
#5 /srv/app/nortek-craft-3/htdocs/vendor/twig/twig/src/Environment.php(408): craft\web\twig\Environment->compileSource(Object(Twig\Source))
#6 /srv/app/nortek-craft-3/htdocs/vendor/twig/twig/src/Environment.php(381): Twig\Environment->loadClass('__TwigTemplate_...', '__string_templa...', NULL)
#7 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/web/twig/Environment.php(41): Twig\Environment->loadTemplate('__string_templa...', NULL)
#8 /srv/app/nortek-craft-3/htdocs/vendor/twig/twig/src/Environment.php(462): craft\web\twig\Environment->loadTemplate('__string_templa...')
#9 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/web/View.php(591): Twig\Environment->createTemplate('http://schema.o...')
#10 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(283): craft\web\View->renderObjectTemplate('http://schema.o...', Array, Array)
#11 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(105): nystudio107\seomatic\helpers\MetaValue::parseMetaString('http://schema.o...', true, true)
#12 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(148): nystudio107\seomatic\helpers\MetaValue::parseString('http://schema.o...', true, true, 4)
#13 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(120): nystudio107\seomatic\helpers\MetaValue::parseArray(Array)
#14 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(87): nystudio107\seomatic\helpers\JsonLd::normalizeJsonLdArray(Array, 3)
#15 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/helpers/BaseJson.php(218): nystudio107\seomatic\helpers\JsonLd::processData(Array, Array, '65167535ab84d2....')
#16 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(85): yii\helpers\BaseJson::processData(Array, Array, '65167535ab84d2....')
#17 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/helpers/BaseJson.php(218): nystudio107\seomatic\helpers\JsonLd::processData(Array, Array, '65167535ab84d2....')
#18 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(85): yii\helpers\BaseJson::processData(Array, Array, '65167535ab84d2....')
#19 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/helpers/BaseJson.php(218): nystudio107\seomatic\helpers\JsonLd::processData(Array, Array, '65167535ab84d2....')
#20 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(85): yii\helpers\BaseJson::processData(Array, Array, '65167535ab84d2....')
#21 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/helpers/BaseJson.php(75): nystudio107\seomatic\helpers\JsonLd::processData(Object(nystudio107\seomatic\models\MetaJsonLd), Array, '65167535ab84d2....')
#22 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/helpers/Json.php(38): yii\helpers\BaseJson::encode(Object(nystudio107\seomatic\models\MetaJsonLd), 321)
#23 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(73): craft\helpers\Json::encode(Object(nystudio107\seomatic\models\MetaJsonLd), 321)
#24 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLd.php(257): nystudio107\seomatic\helpers\JsonLd::encode(Object(nystudio107\seomatic\models\MetaJsonLd))
#25 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(106): nystudio107\seomatic\models\MetaJsonLd->render(Array)
#26 [internal function]: nystudio107\seomatic\models\MetaJsonLdContainer->nystudio107\seomatic\models\{closure}(Object(craft\cache\FileCache))
#27 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/caching/Cache.php(607): call_user_func(Object(Closure), Object(craft\cache\FileCache))
#28 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(59): yii\caching\Cache->getOrSet('MetaJsonLdConta...', Object(Closure), 0, Object(yii\caching\TagDependency))
#29 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(260): nystudio107\seomatic\models\MetaJsonLdContainer->includeMetaData(Object(yii\caching\TagDependency))
#30 /srv/app/nortek-craft-3/htdocs/vendor/nystudio107/craft-seomatic/src/Seomatic.php(710): nystudio107\seomatic\services\MetaContainers->includeMetaContainers()
#31 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(yii\base\Event))
#32 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#33 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\web\\View', 'endPage', Object(yii\base\Event))
#34 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/web/View.php(180): yii\base\Component->trigger('endPage')
#35 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/web/View.php(1731): yii\web\View->endPage(false)
#36 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/web/View.php(462): craft\web\View->endPage()
#37 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/web/Controller.php(216): craft\web\View->renderPageTemplate('softwarelicense...', Array, 'site')
#38 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('softwarelicense...', Array)
#39 [internal function]: craft\controllers\TemplatesController->actionRender('softwarelicense...', Array)
#40 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#41 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#42 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#43 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('templates/rende...', Array)
#44 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#45 /srv/app/nortek-craft-3/htdocs/vendor/craftcms/cms/src/web/Application.php(280): yii\web\Application->handleRequest(Object(craft\web\Request))
#46 /srv/app/nortek-craft-3/htdocs/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#47 /srv/app/nortek-craft-3/htdocs/web/index.php(22): yii\base\Application->run()
#48 {main}`

It seems there's a syntax issue, and I've narrowed it down to the file "vendor/nystudio107/craft-seomatic/src/seomatic-config/digitalproductmeta/JsonLdContainer.php", and this line:

`'availability' => 'http://schema.org/{% if product.getIsAvailable() %}InStock{% else %}OutOfStock{% endif % }}',`

### To reproduce
Steps to reproduce the behaviour:
1. Setup a craft site with seomatic and digitalproduct.
2. Visit the digital product entry.
3. See error message in logs. The page does not crash, but leaves an error-message.

### Expected behaviour
Not having the error message.

### Versions
- Plugin version: 3.4.59
- Craft version: 3.8.17

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/9bf7877c738dc141411e72274c431f0294deffbb & https://github.com/nystudio107/craft-seomatic/commit/9dc60e662d10194daa6382ff82d75d814dcae2ce

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.62”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.32”,
```
Then do a `composer clear-cache && composer update`
