### ISSUE TITLE
Content SEO on disabled websites

### ISSUE THREAD

**Issue by dav729** [nystudio107/craft-seomatic#1363]
There is a website with 4 languages. The main site is enabled and all works fine. Other 3 are disabled. 
For the next language content is almost ready, but SEO doesn't work properly, because there are no entries in Content SEO for disabled websites.
If I enabled next language and click around, i see sections in Content SEO, all works fine. If i disable the website it disappears again. If i enable the website, Content SEO section settings are gone and I need to set it again.
Is it a standard behaviour?
Is there a way to prepare SEO part before enable the website?
Craft version 4.5.3, Seomatic version 4.0.30

**Comment by khalwat** [comment]
Yes, this is standard behavior. SEOmatic does not render metadata for anything that doesn't have public URLs (which includes disabled websites).

You can enable those websites in your development or staging environments, and set up the SEO as you see fit there. But the settings will be stored in the database, so you'll need to migrate the db to your production environments.

**Comment by dav729** [comment]
Thank you!

**Comment by khalwat** [comment]
Would it be helpful to you that you're able to add SEO data/mappings even with the sites being disabled?

**Comment by dav729** [comment]
Yes, it would be very useful for us. Since our agency is based Switzerland, quite some clients have more then one language on the website. But mostly it is not possible to go live with all languages active. Usually it is one and others are disabled and added later, when content is ready.
So it would be great to have this preview without enabling website itself. Perhaps it might be done with checkbox, something like "add SEO data even if disabled" for each website. Thank you an advance for any possible solution.
