### ISSUE TITLE
Sitemap rebuild jobs triggered when they shouldn't be

### ISSUE THREAD

**Issue by ryssbowh** [nystudio107/craft-seomatic#1365]
### Describe the bug

Sitemap rebuild jobs are being triggered even if it's disabled in Content SEO.

Not sure I'm doing something wrong here but I have a section for which there's gonna be more than 120000 entries, I disabled the sitemap for this section.
When I save one of them, jobs are being spawned to rebuild the sitemap for this section, they take an awful lot of time so something is being done but there is no sitemap xml for them at the end of the process.

Surprisingly it does not this for other sections I've disabled...

Is there a way to stop those jobs from happening ?

### Expected behaviour

Jobs should not be spawned for sections that have sitemaps disabled ?

### Versions
- Plugin version: 4.0.32
- Craft version: 4.5.6.1

**Comment by khalwat** [comment]
Correct, queue jobs should not be initiated for sections that do not have sitemaps enabled.

When you say "When I save one of them" -- to be clear, you're saving an entry in a channel, and sitemaps are disabled for that channel for all languages the channel is localized in?

Also if the channel is a Section, are sitemaps disabled for all entry types in that section?

You can check these settings in SEOmatic -> Content SEO -> click on the Section in question

**Comment by ryssbowh** [comment]
"sitemaps are disabled for that channel for all languages"... yep that was it, I somehow missed the sites menu at the top, I had a feeling I was doing something wrong :no_mouth:
