### ISSUE TITLE
Inheritance of seo settings on content seo level from global seo settings for seo page title, meta descriptione etc

### ISSUE THREAD

**Issue by simon-masta** [nystudio107/craft-seomatic#1367]
### Is your feature request related to a problem? Please describe.
We want to use the levels of settings (global, category, entry) as strict as possible. we have the issue, that the setting for "SEO Page Title" cannot be inherited directly from the setting on global level (the same is also not possible for meta description to inherit it from global seo settings). The dropdown option "Same as Global SEO Title Source" in the "content seo" tab is not available (for the option "site name position" it is available to set it to "same as on global settings". So inheritance is not possible and we have to set it for ALL content types and also for all languages of those which is a lot of work and completely unnecessary)

### Describe the solution you would like
the option "Same as Global SEO Title Source" (also for meta description etc.) in the dropdown on content level should be available the same as for meta description and other settings on "content seo" level. This should be the default value for those seo settings on the second level ("content seo" tab). That way it would still be definable on every level (if needed) but as default it only needs one single setup on global level.

### additional info
we use a special field for the combination of pagetitles "{{ object.entry.pageName ??? object.entry.title }}". so we want to set this variable on global level because it works for all levels beyond global. it would make the seomatic tool a lot more useful and efficient.

**Comment by khalwat** [comment]
All you need to do is leave a setting empty and it will automatically fall back on the parent setting. When SEOmatic combines settings, it eliminates any that are blank in the meta cascade:

https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

**Comment by simon-masta** [comment]
Hi Khalwat. 

Thank you for your reply. This behaviour is just not very clear. Why on some fields we have the dropdown option to set it on "same as global xxxx" (as it is on site name position) and on some we just have to leave it empty? And what does "leaving it empty" even mean? There is no "empty" setting in the dropdown. So I guess you mean we have to set it to "custom text" and then leave the input field empty (for "seo title source" (which is actually the "page title" but you call it "seo title" for some reason) AND "seo description source" which is actually the meta description, but you decided to call it "SEO description" for some reason AND "SEO Keyword source" which nobody uses anymore because it got useless)? I think you would really do good if you would make it more clear for the users.

And I am very much aware of the cascading setup of seomatic. And I love it (as I love the whole seomatic plugin)! But the UX of it for some fields is not good at all as I just wrote. I am using your plugin every day (working as SEO for a bigger marketing agency) and I would appreciate an improvement of this UX flaw. This would really help.

Thank you very much for your reply once again. We would be so happy to help you improve your plugin to be even more helpful.

kind regards
simon

**Comment by khalwat** [comment]
Agreed, the "Same As" settings should only exist for **peer** settings. A good example would be the Twitter Title settings, which are a peer of the SEO Title settings, and thus need a "Same As..." setting.

Settings that are merely inherited settings should not have a "Same As..." setting, because the meta cascade already handles that appropriately.

**Comment by khalwat** [comment]
To elaborate a bit more... what you generally _don't_ want to do is have the same SEO Description, for instance, for every page. Thus the global settings are really more of a fallback than anything else. You generally want to explicitly define them on a per-Section basis.

SEO Settings fields have an explicit "Override" lightswitch to make it clear that you are supposed to use that as an override of the existing Content SEO settings.

I thought about bringing that same UX to the Content SEO settings, but I want to encourage people to set up Content SEO for every section, because you really want that to be the baseline setting, with Global SEO uses only as a fallback (and for other global-only settings).

**Comment by simon-masta** [comment]
Hey Andrew
Thank you again very much for your valuable informations. This is very helpful to understand what is behind this thought.

Since we use a custom craft field for the combination of pagetitles "{{ object.entry.pageName ??? object.entry.title }}" we want to set it on global level because it works completely fine for all levels below global level. We would never set a specific value for "Page Title" or for "Meta Description" as a fallback on global, but in our case we want to set the craft variables ("{{ object.entry.pageName ??? object.entry.title }}") on the highest level possible since they are variables, which refer to fields we use entry specific. Especially for page titles we are sure, that it helps to have the option to have a specific "SEO page title" which can be different from the title of the entry in the backend. So we give our clients the opportunity to set an SEO optimized "pagename" instead of using the same title which is used in the backend since SEO titles are often longer and keywordoptimized which can be negative for finding entries in the backend of craft. If the client does not use the field "pagename" and leaves it empty, we just use the "title" for frontend (so the same as in the backend).

In the attached screenshot you can see fields we are providing for our clients directly on the entry level (not in the "SEO" tab on entry level. We chose to directly show it on the very top of the content tab of each entry). We made the experience that users have to have those fields directly on the very top of each entry, otherwise a lot of metainfo will not get set so we started this approach with the custom craft fields we use as variables in seomatic settings.

**Comment by khalwat** [comment]
@simon-masta I'm not seeing any attached screenshot?

**Comment by simon-masta** [comment]
<img width="1793" alt="Bildschirmfoto 2023-10-24 um 16 23 07" src="https://github.com/nystudio107/craft-seomatic/assets/148556684/7244056f-1d20-4bf7-bc44-d7f87de97750">

Sorry. there was some kind of uploading issue. here another try :)
