### ISSUE TITLE
Default description does not work for all sites

### ISSUE THREAD

**Issue by philippe-leeroy** [nystudio107/craft-seomatic#1369]
We have a craft project that has two sites.

For the french site, it work well, if the entry did not override the value, the default seo description  - set in the panel - is displayed. But for the english site, the default is always set to "This would be a customized SEO description".

Where we have set the default :
![image](https://github.com/nystudio107/craft-seomatic/assets/114526245/34c5233a-2084-4e98-84c6-d9589ba05fdb)

And now, in the entry, it's not the default in the panel (but the seomatic one)
![image](https://github.com/nystudio107/craft-seomatic/assets/114526245/c55ee4e3-7401-431c-99c7-0eb85320e0a9)

### Versions
- Plugin version: 4.0.32
- Craft version: 4.5.7

**Comment by khalwat** [comment]
SEOmatic supports separate settings for each language the site is localized in. Did you set the settings in the localized setting for each site? The dropdown menu is in the upper-left corner of the SEOmatic settings page.

**Comment by philippe-leeroy** [comment]
Yes, you can see in the screenshot that i'm on the same site "intact.ca", the english one. Plus, I have save several time, the entry and the global settings.

As I say the french site works perfectly.

**Comment by khalwat** [comment]
Have you also checked the corresponding Content SEO settings for both languages?

**Comment by philippe-leeroy** [comment]
Ok don't mind me ! It's been a long day... It was on the content section! Sorry for the bothering :)

**Comment by khalwat** [comment]
No worries at all! Also check out the new Debug Panel I added that may help you in the future:

https://x.com/nystudio107/status/1716419862589747322?s=20

**Comment by philippe-leeroy** [comment]
Yeah ! Great improvement!
