### ISSUE TITLE
Saving Google Tag Manager Settings successfully, disables it.

### ISSUE THREAD

**Issue by sergeifilippov** [nystudio107/craft-seomatic#137]
Today I added GTM id to the `Google Tag Manager Settings`, when I hit save, the response was a success.

However, the `Google Tag Manager Enabled` disables itself every time you save.

![gtm bug](https://user-images.githubusercontent.com/123676/41207151-aca2e3b6-6d64-11e8-9dbd-c907d0851400.gif)

- Craft Pro 3.0.10.3
- SEOMatic 3.0.20

**Comment by khalwat** [comment]
I can't replicate that here; is there any more information you can give me that might be useful?

**Comment by sergeifilippov** [comment]
Umm there are no errors in console or logs. I can send you snapshot of the db if that will help.

I've tested this on Local(macos with php7.1 + nginx + mysql5.7) and staging (ubnutu 18.04  + php7.1 + nginx + mysql5.7)

**Comment by khalwat** [comment]
Very interesting. Do you see the same behavior for any other of the Tracking Scripts that SEOmatic provides?

**Comment by sergeifilippov** [comment]
All of them.

I can send you the source/db snapshot if that helps. Just let me know how to best do it.

**Comment by khalwat** [comment]
So the interesting thing to me is that I fixed an issue that sounds very much like this a bit ago; but you're using the latest version, so it doesn't make sense.

**Comment by sergeifilippov** [comment]
Hmmm that is ..... weird alright.

What do you need from me to help find the issue?

**Comment by sergeifilippov** [comment]
Message me in Craft Slack if it's any easier/faster for you.`@sergeif`

**Comment by khalwat** [comment]
Can you check your `web.log` right after you click on Save? With `devMode` enabled, it should be logging _something_ about a validation error or such. You can search on `[seomatic]`

**Comment by khalwat** [comment]
This seems to be some kind of local config setup issue.
