### ISSUE TITLE
Content SEO - Channel appearing/showing twice

### ISSUE THREAD

**Issue by D3VM4TT** [nystudio107/craft-seomatic#1371]
### Describe the bug
In the Content SEO section, we have a "News" channel section that is being displayed twice for some reason. in the Content SEO table, it shows that the duplicate channel does not have a Description or Image. This is affecting the Content SEO Setup in the SEOmatic dashboard (it shows 94%). There is only 1 "News" channel section in our system. One of the "News" Content SEO Channels is completely setup, whilst with the other, it says its missing a Description and Image - Even when these fields are updated on the duplicate News entry.

### To reproduce
Steps to reproduce the behaviour:
Its working for the other channel sections (they are not duplicated). Creating new channel sections do not appear to be duplicated either

### Screenshots
![Screenshot_20231025_132221](https://github.com/nystudio107/craft-seomatic/assets/88676927/9a8b860b-fd36-45a9-a4f5-45a8324f68d3)

![Screenshot_20231025_132456](https://github.com/nystudio107/craft-seomatic/assets/88676927/7b15f7d9-4c61-4fc8-9c8c-14395628ca78)

![Screenshot_20231025_132543](https://github.com/nystudio107/craft-seomatic/assets/88676927/4854dab9-6067-4a60-8e4c-1eb4ebcdd125)

### Versions
- Plugin version: 4.0.33
- Craft version: 4.5.8

**Comment by khalwat** [comment]
Is it possible that you've had multiple channels named `news` or a category group named `news` that was subsequently renamed?

Just trying to track down how it got into this state -- but in order to fix if, find the two rows in the `seomatic_metabundles` table that have the same source handle (`news` in this case) and delete them both.

You'll then need to re-enter the mappings in Content SEO for the News section.

**Comment by D3VM4TT** [comment]
Hey @khalwat Thanks for the fast reply.

Deleting two rows in the `seomatic_metabundles` table that have the same source handle (`news` in this case).

Has worked in that it has removed both entries from the Content SEO screen.

![Screenshot_20231026_105242](https://github.com/nystudio107/craft-seomatic/assets/88676927/baa5ea16-cbf4-4e5f-8425-6059a3a23959)

However, I am not sure what you mean by

> You'll then need to re-enter the mappings in Content SEO for the News section.

Could you elaborate on how to get the news channel showing again in the Content SEO screen?

**Comment by khalwat** [comment]
Just visiting a URL on the frontend or editing something in that section in the CP should make it re-appear. It lazily ads the metabundles as needed
