### ISSUE TITLE
Seomatic always applies a transform to og:image, even when set to none

### ISSUE THREAD

**Issue by twosixcode** [nystudio107/craft-seomatic#1373]
### Describe the bug
Even with Global and Content SEO settings in Seomatic having the Transform Image lightswitch set to OFF, I still see a transform of `_1200x630_crop_center-center_82_none` applied to the image, based on viewing the page source.

I have cleared caches, tried a brand new entry, and also tried a bare-bones template with no twig in it. The result is always that the above transform is applied.

### To reproduce
Steps to reproduce the behaviour:
1. Disable (turn OFF) Transform Image lightswitch in Global and Content settings.
2. Strip relevant Entry template down to bare basics
3. Save an Entry, view source from the front end, observe the assigned SEO image used in `og:image` includes an applied transform of `_1200x630_crop_center-center_82_none`

### Expected behaviour
If the Transform Image option is OFF I would expect to see a reference to the orignal image in the `content` attribute of `og:image`  tag.

### Versions
- Plugin version: 4.0.31 
- Craft version: Craft Pro 4.5.6.1

**Comment by khalwat** [comment]
What are your settings for this image in the Facebook OpenGraph tab in SEOmatic?

**Comment by twosixcode** [comment]
Thanks for the reply.

(If I understand your question correctly) On the Entry itself, in FaceBook Tab, all lightswitches are OFF
<img width="383" alt="Screenshot 2023-10-30 at 13 29 37" src="https://github.com/nystudio107/craft-seomatic/assets/498260/b2f13251-f79e-4f45-b035-3239ab59d8ad">

If instead you were referring to Facebook settings within Global and Content SEO Settings pages (eg `admin/seomatic/global/facebook/` and `/admin/seomatic/edit-content/facebook/section/blog/`), on those pages the Transform Image Lightswitch is OFF

<img width="741" alt="Screenshot 2023-10-30 at 13 44 56" src="https://github.com/nystudio107/craft-seomatic/assets/498260/2fae47c2-fde8-4e8f-a953-6420efda2375">

**Comment by khalwat** [comment]
You're providing a screenshot from an SEO Settings field... what I'm talking about is your settings in SEOmatic -> Global SEO -> Facebook OpenGraph and your settings in SEOmatic -> Content SEO -> <pick a section> -> Facebook OpenGraph.

Have a read on how the "meta cascade" works in SEOmatic:

https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

**Comment by twosixcode** [comment]
> what I'm talking about is your settings in SEOmatic -> Global SEO -> Facebook OpenGraph and your settings in SEOmatic -> Content SEO -> -> Facebook OpenGraph.

Sorry, I updated my answer. Yes, I started by updating the Global and then Content SEO settings. Those are all Transform Image == OFF. The reason I am posting is because it is those settings that seem not to be respected, with regard to Transform Image lightswitch set to OFF.

I am referring to these settings pages `admin/seomatic/global/facebook/` and `/admin/seomatic/edit-content/facebook/section/blog/`

**Comment by khalwat** [comment]
Are you able to post screenshots of the relevant settings here? Because unless some kind of caching layer is involved (which is causing the underlying HTML to then not be updated), you definitely should be able to turn off that image transform.

**Comment by twosixcode** [comment]
**Global SEO**
<img width="475" alt="Screenshot 2023-10-30 at 15 33 25" src="https://github.com/nystudio107/craft-seomatic/assets/498260/f4e7458c-ca5f-4951-b6cd-a87ca7ffceb6">

**Global SEO > Facebook**
<img width="559" alt="Screenshot 2023-10-30 at 15 27 27" src="https://github.com/nystudio107/craft-seomatic/assets/498260/51b74bed-9ef0-4182-9c66-69a17c1f5fed">

**Content SEO > Blog > General**
<img width="481" alt="Screenshot 2023-10-30 at 15 25 40" src="https://github.com/nystudio107/craft-seomatic/assets/498260/e07e43a3-cc6f-4ad2-916c-e29ceb0d43a3">

**Content SEO > Blog > Facebook**
<img width="489" alt="Screenshot 2023-10-30 at 15 30 59" src="https://github.com/nystudio107/craft-seomatic/assets/498260/cba80b32-685a-471e-82fb-f0c4a6a91994">


**Caching**

No caching. Blitz is installed, but disabled in this environment. I have cleared SEOmatic caches, and even all caches, after making changes.

Blog details template content:
```
<html>
<head></head>
<body>
	test
</body>
</html>
```

**View source, showing the output in `og:image` with transform applied**

<img width="1225" alt="Screenshot 2023-10-30 at 15 48 13" src="https://github.com/nystudio107/craft-seomatic/assets/498260/9ff4d835-45af-401c-938f-d830c51d092d">

**Comment by khalwat** [comment]
I've seen it happen that the settings here can sometimes not stick -- can you try re-saving the FaceBook OpenGraph & Twitter settings for Global SEO and Content SEO for this section?

If that doesn't fix it, let's get together on a conference call and see what we can figure out:

https://savvycal.com/nystudio107/chat

**Comment by khalwat** [comment]
Will re-open if additional information is provided, or you book a session with me via the link above.

**Comment by twosixcode** [comment]
Thanks. I had to pause on this to work on other projects, but will be returning to this with more information if I'm unable to resolve it.

**Comment by khalwat** [comment]
Cool, I'm happy to jump on a video chat with you to help sort it out as well, when you're ready!

**Comment by twosixcode** [comment]
This appears to be resolved now, and came down to a Field setting on the SEOmatic field where the "Transform Facebook OpenGraph Image" was not checked under the "Choose the Facebook SEO settings fields to display" option.

<img width="491" alt="Screenshot 2023-11-10 at 10 10 09" src="https://github.com/nystudio107/craft-seomatic/assets/498260/0315c771-d9eb-44a6-99d0-db0c233a4e8a">

Its default state was apparently ON, and because it was not shown on the Entry as an option, we did not realize this is what was kicking in.

Making the option visible on the Entry, and then setting it to OFF, has cleared this up.

Thanks for the willingness to help.

**Comment by khalwat** [comment]
Thanks for letting me know, I'll see if I can make that more obvious in the UX!
