### ISSUE TITLE
Support multiple values for `alternateName` property

### ISSUE THREAD

**Issue by chrismlusk** [nystudio107/craft-seomatic#1375]
Currently, the `alternateName` property is rendered as a single string. So if I set the Alternate Entity Name field to "One, Two, Three" (see Site Settings > Identity > General Info), the output is:

```
"alternateName": "One, Two, Three"
```

I have a client requesting the ability to add multiple values that will be rendered as an array of strings:

```
"alternateName": ["One", "Two", "Three"]
```

[Google's documentation shows that multiple values are permitted](https://developers.google.com/search/docs/appearance/site-names#alternative) as an array of strings.

I know I can overwrite this in Twig to make it work for this client, but is this something SEOmatic might support?

**Comment by khalwat** [comment]
Yep, SEOmatic supports it if you set it to an array via Twig

**Comment by chrismlusk** [comment]
Yes, but that requires a developer to make overrides and updates in Twig, correct? 

My question is if you might consider making it possible for users to do this in the control panel.

**Comment by khalwat** [comment]
That's correct, it'd need to be done via Twig.

A comprehensive JSON-LD editor is something I've always had in mind to do, but it's actually a relatively complicated prospect.
