### ISSUE TITLE
EVENT_DEFINE_SIDEBAR_HTML IS NOT DEFINED error when updating to v 3.4.63 on Craft 3.5.19.1

### ISSUE THREAD

**Issue by johnwbaxter** [nystudio107/craft-seomatic#1377]
### Describe the bug
Update SEOMatic to 3.4.63 on site running Craft 3.5.19.1 and it has error saying "EVENT_DEFINE_SIDEBAR_HTML IS NOT DEFINED"

### To reproduce
Update SEOmatic version 3.3.30 running on Craft 3.5.19.1 to SEOMatic 3.5.19.1

### Expected behaviour
It to not error

* yes, we know Craft does need updating, and we will be starting that project next month :)

**Comment by khalwat** [comment]
Can you provide me with the relevant error log so I can track down where this is happening?

**Comment by khalwat** [comment]
Aha, you must be using the Campaign plugin?

**Comment by johnwbaxter** [comment]
I am using the Campaign plugin yes!!

**Comment by khalwat** [comment]
Related issue for Campaign: https://github.com/putyourlightson/craft-campaign/issues/434

**Comment by johnwbaxter** [comment]
Ahh ok! Thx Andrew!!

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/8f3e089f2d2ac9b1e0a2c71f79feadd0d1c2c263

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.64”,
```
Then do a `composer clear-cache && composer update`

**Comment by johnwbaxter** [comment]
Awesome, many many thanks!!
