### ISSUE TITLE
CanonicalLink->prepForRender() - noindex detection fails for multiple meta robots values

### ISSUE THREAD

**Issue by Abromeit** [nystudio107/craft-seomatic#1378]
###  Bug description 

I have noticed that seomatic does correctly avoid issuing a canonical tag if a post is set to meta robots=noindex or meta robots=none. This is the expected behavior.

In addition, one would expect that a combined value of "noindex, nofollow" would have the same effect on the generated HTML as the value "none". That is, no canonical tag should be output.

However, if you assign more than one value to the meta robots field, e.g. 
- "noindex, nofollow", 
- "max-snippet:-1,noindex" 
- "noarchive,noindex,notranslate"

a canonical tag _will_ be rendered in the HTML.

<img width="834" alt="example-values" src="https://github.com/nystudio107/craft-seomatic/assets/537920/42afd52a-e093-4c0a-b4d7-2a75fddbf3e2">

### To reproduce
Steps to reproduce the behaviour:
1. Make sure you're on a craft `live` environment or enforce the environment in the respecitve seomatic setting
2. Make sure the seomatic setting `Always include canonical links regardless of environment` is inactive / false
3. Create a new post / entry in your cms
4. Goto the post's SEO settings and add 2 or more values for the robots metatag
5. Save and publish the post
6. Inspect the frontend HTML result

### Versions
- Plugin version: v4.0.33
- Craft version: v4.5.9

### Presumed cause

In `src/models/metalink/CanonicalLink.php` the `prepForRender()` method expects the return value of `$robotsArray['content']` to be an array, if multiple values were entered. 

- https://github.com/nystudio107/craft-seomatic/blob/a3daa477e5b63b986a27572cdcf7bb8901971fa6/src/models/metalink/CanonicalLink.php#L81-L87

On my test instance i just var_dumped the value of `$robotsArray['content']` and **it is a string**, like one that would also be used for the final output. (Like "noindex,nofollow".) 

To solve this, you could probably use explode() on the string. But I suspect that there is already a more suitable solution in this project. For example, a method that can actually still return the raw array.

**Comment by khalwat** [comment]
Yeah the code was just wrong; since we render the attributes, its always going to be a string.

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/50c4e71ee2c3a1fb6f7c337433e99788e02a6334 & https://github.com/nystudio107/craft-seomatic/commit/7cd91f29fea7cbb68c684f04d291077cc580f239

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.64”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.34”,
```
Then do a `composer clear-cache && composer update`

**Comment by Abromeit** [comment]
Wow, thanks for the quick response! 

But now there is the problem that no canonical tag is displayed if `max-image-preview:none` is included in the selected values. 

https://github.com/nystudio107/craft-seomatic/blob/5813c5c53dccbc3dacf227ac584c8ee092c428b1/buildchain/src/vue/RobotsSelect.vue#L41

https://github.com/nystudio107/craft-seomatic/blob/7cd91f29fea7cbb68c684f04d291077cc580f239/src/models/metalink/CanonicalLink.php#L83

**Comment by khalwat** [comment]
Not doing well on this one, am I? :)

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/aaf8ea45ae6a3e0d4071e632d73d05aa101df366 & https://github.com/nystudio107/craft-seomatic/commit/8ba39a7f9bcd4ab7e36daeb3c2da075cd02e65b8

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.64”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.34”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
This working for you @Abromeit ?

**Comment by Abromeit** [comment]
@khalwat tested successfully – all fine now. 👍
