### ISSUE TITLE
How to get the assetId of the site-wide SEO Image?

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/craft-seomatic#1379]
### Question
We're using the Related Items plugin to share some content on the site, and as a backup image, we're pulling the SEO Image if it's been overridden with `entry.mySeomaticFieldName.metaBundleSettings.seoImageIds[0]` but I wasn't able to figure out how to get the imageId of the site's default Social SEO/share image. For now, I went into the content settings and hardcoded the ID as a backup value. But I'd love to allow the author's to change that within Craft. And maybe there's an easier way to retrieve what I'm using now without the deep dive into the `metaBundleSettings` ? 

### Additional context
Add any other context or screenshots about the support request here.

**Comment by khalwat** [comment]
Can you just use:

```twig
{% set image = seomatic.meta.parsedValue('seoImage') %}
```

...or in PHP:

```php
$image = Seomatic::$seomaticVariable->meta->parsedImage('seoImage');
```

...to get the resolved, parsed value for the given route. SEOmatic does a whole lot of combining for Field SEO, Content SEO, and Global SEO values that I wouldn't really recommend you doing on your own.

I mean you could do it, but it wouldn't be a supported use case.
