### ISSUE TITLE
[4.x] Sitemap Enabled value is incorrect when previously overridden value is reverted back to OFF

### ISSUE THREAD

**Issue by jrrdnx** [nystudio107/craft-seomatic#1380]
### Describe the bug
Working on a site where a section has entry URIs and therefore details pages, but not every entry in that section should have a detail page. I decided to use the SEO field to control this using the Sitemap Enabled field. Override is toggled ON then Sitemap Enabled toggled OFF, and the value is `false` correctly.

However, when reverting the Override toggle back to off and saving the entry, the Sitemap Enabled value is still incorrectly `false`.

If the Override switch is toggled ON and Sitemap Enabled is toggled ON before switching Override back to OFF and then saving the entry, the value is now `true`. Ideally, the value should revert back to `null` to match the default when Override is OFF.

### To reproduce
Steps to reproduce the behaviour:
1. In an entry, navigate to the SEO field and choose the Sitemap tab
2. For Sitemap Enabled, toggle the Override switch to ON. Confirm the Sitemap Enabled toggle switch is OFF. Save the entry.
3. Output `element.seo.metaSitemapVars.sitemapUrls` on the front-end, confirm the value is `false`
4. In the same entry, toggle the Override switch back to OFF and save the entry.
5. Output `element.seo.metaSitemapVars.sitemapUrls` on the front-end and the value is still `false`

### Expected behaviour
The Sitemap Enabled value should revert back to the section's setting of `null` when Override is switched to OFF.

### Versions
- Plugin version: 4.0.33
- Craft version: Pro 4.5.10

**Comment by khalwat** [comment]
So this is probably actually working as expected. If you just output `{{ element.seo.metaSitemapVars.sitemapUrls }}` you're only getting the value that is stored in the field.

When SEOmatic renders metadata for a page, it combines together the Field SEO, Content SEO, and Global SEO together in what I call the "Meta Cascade":

https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

When combining things together, it keeps in mind the status of the Override switch.

So I'm expecting that things are actually working as they should, in terms of the entries being in the sitemap or not. Simply looking at the value of `element.seo.metaSitemapVars.sitemapUrls` is only telling you the value set in the Field SEO setting, not the ultimate determiner of whether it'll be included in the sitemap or not.
