### ISSUE TITLE
Issue in 4.0.34: Calling unknown method: craft\console\Request::getPathInfo()

### ISSUE THREAD

**Issue by boboldehampsink** [nystudio107/craft-seomatic#1384]
### Describe the bug
```

Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getPathInfo()'
--
  |  
  | in /app/user/vendor/yiisoft/yii2/base/Component.php:300
  |  
  | Stack trace:
  | #0 /app/user/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(904): yii\base\Component->__call('getPathInfo', Array)
  | #1 /app/user/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(364): nystudio107\seomatic\services\MetaContainers->setMatchedElement('', 2)
  | #2 /app/user/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(54): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('/', NULL)
  | #3 /app/user/vendor/twig/twig/src/ExtensionSet.php(320): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()

```

### To reproduce
Steps to reproduce the behaviour:
I'm seeing this when running fixtures

### Expected behaviour
This didn't happen in the previous version

### Versions
- Plugin version: 4.0.34
- Craft version: 4.5.10

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/e9ffc88eae4bce64ac87f89ff1b6ac389ce0f4af & https://github.com/nystudio107/craft-seomatic/commit/4792522d8f9b671a7b70ae5218fd387f7b2d978c

Tagged and released:

Craft 3: Version `3.4.66` -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.66

Craft 4: Version `4.0.35` -> https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.35

**Comment by boboldehampsink** [comment]
Thanks Andrew!
