### ISSUE TITLE
Update to 3.4.64 breaks the CMS

### ISSUE THREAD

**Issue by 99ster** [nystudio107/craft-seomatic#1385]
### Describe the bug
The update to 3.4.64 breaks the CMS

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Update to 3.4.64.  Then go to view/edit any entry in the CMS."
2. Click on "view / edit the entry"
3. See error message "PHP Warning – [yii\base\ErrorException](https://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Undefined variable $element."

### Expected behaviour
That the update wouldn't break the CMS!

### Screenshots
<img width="1215" alt="Screenshot 2023-11-16 at 14 02 53" src="https://github.com/nystudio107/craft-seomatic/assets/26082907/e3895f32-3fab-409a-b842-cd209b0f7944">

### Versions
- Plugin version: 3.4.64
- Craft version: 3.9.5

**Comment by khalwat** [comment]
Sorry, it was a mistake when backporting an enhancement from the Craft 4 version of the plugin to the Craft 3 version of the plugin.

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/380b97353f44cc1f30b52ff8f93db3243900e046

Tagged & released as `3.4.65` -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.65
