### ISSUE TITLE
Problem with $element that is not set

### ISSUE THREAD

**Issue by martinhellwagner** [nystudio107/craft-seomatic#1387]
### Describe the bug
In the function `$this->setMatchedElement($uri, $siteId);` that is called in line 364 in the file `MetaContainers.php` and that is implemented starting on line 457 in the same file, the variable `$element` can't be found and is not set – that's why we're getting a server error (see screenshot).

Shouldn't there be something like `$element = null;` for the case that the variable `$element` can't be set?

### To reproduce
Steps to reproduce the behaviour:
Click on an element in the Control Panel

### Expected behaviour
Server error should not appear

### Screenshots
![Screenshot 2023-11-20 at 10 46 10](https://github.com/nystudio107/craft-seomatic/assets/19146752/d0fedad6-c2ce-4366-ad96-72fc64aeee57)

### Versions
- Plugin version: 3.4.64
- Craft version: 3.9.5

**Comment by khalwat** [comment]
This was already fixed; please update to the latest SEOmatic -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.66

**Comment by martinhellwagner** [comment]
Sweet, thanks! 🙏🏼
