### ISSUE TITLE
SEO Image Source > render output with overlay image, logo or watermark

### ISSUE THREAD

**Issue by srosenbrand** [nystudio107/craft-seomatic#1390]
It would be great to have the option to render the global and/or on section level generated SEO image source with a logo or overlay image. I have done some tests with the 'Share Previews Plugin' (https://github.com/alpshq/craft-share-previews/blob/master/README.md), but this plugin behaves unstable and has giving me errors and is unfortunately unreliable.

In SEOMatic settings I can see something like this:

<img width="1414" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/5593262/4fe1bd12-e5ff-4e12-aba5-f600a04809e0">

**Comment by khalwat** [comment]
Here's the FR: https://github.com/nystudio107/craft-seomatic/issues/52
