### ISSUE TITLE
Section Sitemap renders too many <image:title> per asset

### ISSUE THREAD

**Issue by sergeifilippov** [nystudio107/craft-seomatic#140]
Got a warning in `Google Search Console` about sitemap being generated.

`Invalid XML: too many tags` - `Too many tags describing this tag. Please fix it and resubmit.`

```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <url>
        <loc> https://www.example.com/ </loc>
        <lastmod> 2018-06-13T22:20:25+12:00 </lastmod>
        <changefreq> weekly </changefreq>
        <priority> 0.5 </priority>
        <image:image>
            <image:loc>
                https://some-bucket.s3.amazonaws.com/content/homepage/Some_File_Name.jpg
            </image:loc>
            <image:title> Some_File_Name </image:title>
            <image:title> Some_File_Name </image:title>
            <image:title> Some_File_Name </image:title>
            <image:title> Some_File_Name </image:title>
        </image:image>
        <image:image>
            <image:loc>
                https://some-bucket.s3.amazonaws.com/content/archive/entrance/Entrance-009.jpg
            </image:loc>
            <image:title> Entrance 009 </image:title>
            <image:title> Entrance 009 </image:title>
            <image:title> Entrance 009 </image:title>
            <image:title> Entrance 009 </image:title>
        </image:image>
    </url>
</urlset>
```

- PHP 7.1.18
- Craft - Craft Pro 3.0.11
- SEOmatic - 3.0.22

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/caf7ecb7ce6654679945e23fc6c782e4a0274fbc

It's also possible that you may be encountering an older bug; in that case uninstalling and re-installing the plugin will fix it. Or you can edit the `metaSitemapVars` column in the `seomatic_metabundles`

**Comment by sergeifilippov** [comment]
Fixed by editing the entries for the Section via CP in `Seomatic > Content SEO > Section > Sitemap`.

These rows were repeated x3.

<img width="940" alt="homepage - richmond mall 2018-06-14 14-54-37" src="https://user-images.githubusercontent.com/123676/41389070-f17a5278-6fe2-11e8-81ba-4dbf18b4280d.png">
