### ISSUE TITLE
[5.0.0-beta.1] error when saving entry with matrix

### ISSUE THREAD

**Issue by lukas-jansen** [nystudio107/craft-seomatic#1406]
### Describe the bug
When saving an entry that has a matrix field an error is getting thrown `Attempt to read property handle on null` 
https://github.com/nystudio107/craft-seomatic/blob/develop-v5/src%2Fseoelements%2FSeoEntry.php#L443
As the matrix block is now also an entry, but it doesn't have a section

### To reproduce
Steps to reproduce the behaviour:
1. Create an entry with a matrix block
2. Click save

### Versions
- Plugin version: 5.0.0-beta.1
- Craft version: 5.0.0-alpha.6

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/c6597fa3b5ae978b8c4610bf58616f26c9f7c426

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.0-beta.2”,
```
Then do a `composer clear-cache && composer update`
