### ISSUE TITLE
Issue upgrading from seomatic in craft2

### ISSUE THREAD

**Issue by hahnzilla** [nystudio107/craft-seomatic#141]
We have a couple of structures utilizing the same seo field. According to the github readme it seems like all you need to do is create a new field and associate that field with the entry types the old field is associated with.

After doing that, the entries I associated the new field with become unresponsive. As in, when I try to look at the entry in the admin the browser never loads and eventually throws a 504 from nginx.

I just verified that when I remove the seomatic plugin the entries load find (minus the seo of course).

I'm not sure what other info you'd need to help with this, so just let me know if some random log somewhere will make it super easy to debug.

**Comment by hahnzilla** [comment]
Here's the web and queue logs as request via slack.

[web.log](https://github.com/nystudio107/craft-seomatic/files/2099763/web.log)
[queue.log](https://github.com/nystudio107/craft-seomatic/files/2099764/queue.log)

**Comment by khalwat** [comment]
On my flight home, but I've not forgotten about you! I'll have a look at it this weekend. This is probably something specific to your setup, or an edge case I'm not handling correctly, because I've successfully used this upgrade path on a number of sites.

**Comment by hahnzilla** [comment]
No problem at all! Let me know if there's anything I can provide to help ya out.

**Comment by khalwat** [comment]
So I'm very confused by this log file. There appears to be no trace of SEOmatic anywhere in it... and it logs noting when it's loaded, and a bunch of other useful things.

Are we sure this is the correct `web.log`?

**Comment by hahnzilla** [comment]
I'm sure that log file was pulled from `storage/logs/web.log` after I ran into the issue. I can run through the process again and post the log files again. Maybe it works this time 😄 

Can you just verify that this is actually the process for upgrading though:

1. Create new SEO field.
2. Associate new SEO field with sections that have old SEO fields.

Maybe something that I did wrong was that I didn't add the new SEO field to every section that had an old SEO field. I just added it to a single one for testing. Maybe that has no bearing on the situation though.

**Comment by khalwat** [comment]
Do you have this site on local dev where I'd be able to screenshare in to see what's going on?

**Comment by hahnzilla** [comment]
Yeah, absolutely. I'm in the middle of upgrading Commerce 2 so I'd need a little bit of time to reset it back to where it was. I can do later today or anytime tomorrow. I'm on Central Time, but can be fairly flexible.

**Comment by khalwat** [comment]
Cool, hit me on on Craft Slack `@andrew.welch` and we'll work something out for tomorrow.

**Comment by hahnzilla** [comment]
For anyone who ran into this issue, have no fear. None of the blame rests on Seomatic. The issue was that Seomatic was trying to run transforms which just so happened would make the site hang. HOW FUN!

Anyways, to fix that I actually followed the instructions on https://github.com/craftcms/aws-s3. Mainly, adding a config/volumes.php to include the aws region. Then I set the config variable `generateTransformsBeforePageLoad` to false just to ensure none of them would cause a page to break.

You can all rest easy knowing that the seomatic upgrade scripts were flawless.
