### ISSUE TITLE
Using seomatic.helper.socialTransform with non PNG or JPG image and no transform name results in error

### ISSUE THREAD

**Issue by kerrig** [nystudio107/craft-seomatic#1411]
Site is using seomatic.helper.socialTransform with an image from a field in the CMS. The image is a webp and the code is not calling a specific transform which is causing the template to throw an error:
<img width="910" alt="Screenshot 2024-02-05 at 11 19 21 AM" src="https://github.com/nystudio107/craft-seomatic/assets/1864417/ba7708e1-a2eb-4769-aa6e-19217ed2d2dd">

The two main issues are because:
- The code is being called without a transform name
- The file is not a PNG or JPG which is the two allowed mime types (ALLOWED_SOCIAL_MIME_TYPES)

This is the code thats calling socialTransform:
`{% do seomatic.meta.seoImage(seomatic.helper.socialTransform(seoImage)) %}`

Here's the code that's failing (in src/helpers/ImageTransform.php):
```
if (!in_array($mimeType, self::ALLOWED_SOCIAL_MIME_TYPES, false)) {
     $transform->format = self::DEFAULT_SOCIAL_FORMAT;
}
```

Here's what I did to get it to work:
```
if (!in_array($mimeType, self::ALLOWED_SOCIAL_MIME_TYPES, false) && $transform !== null) {
     $transform->format = self::DEFAULT_SOCIAL_FORMAT;
}
```

Once I added the check that transform isn't null, it worked without issue and the SEO Image gets properly set with the webp image.

### Versions
- Plugin version: 4.0.38
- Craft version: 4.5.6.1

**Comment by khalwat** [comment]
So at the time, the various social media sites did not allow for `webp` images, but rather just `image/jpeg`, `image/gif` or `image/png`

It looks like since then, Facebook and Twitter have added support for `image/webp` so I think he best solution is to add that to the allowed types.

**Comment by khalwat** [comment]
Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.70”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.39”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.0-beta.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by kerrig** [comment]
@khalwat Tested and confirmed it's working! Thanks for the quick turnaround
