### ISSUE TITLE
[FR] - Seomatic creates more than 100GB caches

### ISSUE THREAD

**Issue by Sikatrih** [nystudio107/craft-seomatic#1413]
I have route /search/:searchKeyword. Seomatic trying to cache all URLs which is unlimited in this case and creates a huge amount of caches. Is it possible to disable caches (or seomatic at all) for this specific route? Thanks!

**Comment by khalwat** [comment]
Yes, you can disable SEOmatic on those page templates via:

```twig
{% do seomatic.config.renderEnabled(false) %}
```
