### ISSUE TITLE
Robots tag set to none for PRODUCTION.

### ISSUE THREAD

**Issue by bannid** [nystudio107/craft-seomatic#1414]
Currently we are getting this response back from our Craft instance in Production for all our pages even when we have set Robots to all:
![image](https://github.com/nystudio107/craft-seomatic/assets/21113405/670eb0b1-bc96-496e-8012-14fcaac8cdc3)

And we suspect that it was introduced with the following commit:
https://github.com/nystudio107/craft-seomatic/commit/c34b6d0b585abde52efaeac5e8ec7045c8f5772b
![image](https://github.com/nystudio107/craft-seomatic/assets/21113405/db30d97e-8ad7-404a-8a93-560092657a65)

The reason we suspect that the above line is causing us this issue is because we are running craft headless and our _baseCpUrl_ matches the _GraphQL_ in the first segment IE
_baseCpUrl: https://mycraft.com.au/_
_GraphQL: https://mycraft.com.au/api_

If we look at the implementation of _getIsCpRequest_ in https://github.com/craftcms/cms/blob/main/src/web/Request.php#L610
![image](https://github.com/nystudio107/craft-seomatic/assets/21113405/10230973-a291-401b-9ad3-1b9d20c0e7bb)

We can see it is determined by checking if the first segment matches the _cpTrigger_ setting, which in our case is **null** which leads us to the following section on https://craftcms.com/docs/4.x/config/general.html#basecpurl
![image](https://github.com/nystudio107/craft-seomatic/assets/21113405/af831ba1-620f-44ae-9b38-314ae185771a)

This means _cpTrigger_ is being set to _baseCpURL_, which in result is returning 
![image](https://github.com/nystudio107/craft-seomatic/assets/21113405/670eb0b1-bc96-496e-8012-14fcaac8cdc3)
for all our pages.

Could this be looked into please as our website has disappeared from Google and this may be the reason?

**Note: We have fixed our problem for the meantime by rolling back to 4.0.37**

**Comment by khalwat** [comment]
To be clear, the response you're getting back where `robots` is set to `none` is from a GraphQL request, and your entire site is a headless site?

**Comment by khalwat** [comment]
Addressed in:

Craft 3: https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.71

Craft 4: https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.40

Craft 5: https://github.com/nystudio107/craft-seomatic/releases/tag/5.0.0-beta.4
