### ISSUE TITLE
Articles do not inherit Site Name Position from global settings

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#142]
I'm looking for the following setup.

`Name of article | Site.com`

I've tried to get this going by first setting `Site Name Position` to `After` under `Global SEO`, then `Same as Global Site Name Position` under `Content SEO`

<img width="751" alt="step-1" src="https://user-images.githubusercontent.com/23015690/41468125-276ed950-70a9-11e8-818a-18ec23a93463.png">
<img width="924" alt="step-2" src="https://user-images.githubusercontent.com/23015690/41468126-279f0224-70a9-11e8-89cb-6e546245b3e9.png">

Yet articles still show up like `Site.com | Name of article` instead of the other way around.

So I looked at the SEO on article level, and I don't see any option to inherit global settings, rather it just gives me an article level choice which always defaults to `Before`

<img width="471" alt="step-3" src="https://user-images.githubusercontent.com/23015690/41468187-67cb3f7a-70a9-11e8-8a80-989aa211fe87.png">

Any ideas on what I'm missing?

I'm running version 3.0.22

Cheers!

**Comment by khalwat** [comment]
This was fixed in 3.0.22, but if you had it installed from a previous version, the stale data is still there. If you go to the Content SEO section for the given section, and click Save, it will save the appropriate data and fix this.

**Comment by ghost** [comment]
Unfortunately this doesn't solve it for me

**Comment by khalwat** [comment]
You went to the appropriate Content SEO page (on the right site), and clicked Save for the Content settings, Twitter settings, and Facebook settings @stianmandarin ?

**Comment by ghost** [comment]
@khalwat I did indeed

**Comment by khalwat** [comment]
Can you tell me exactly which part of it is not working for you then @stianmandarin ? Is it the title position for the title tag, twitter, or Facebook?

**Comment by khalwat** [comment]
@stianmandarin ?

**Comment by Wiejeben** [comment]
Hi! I have made a screen recording demonstrating the same problem to avoid confusion.

[https://youtu.be/Kybk24Tsnp8](https://youtu.be/Kybk24Tsnp8)

Versions:
PHP 7.2.7
Craft CMS 3.0.15
SEOmatic 3.0.25

**Comment by khalwat** [comment]
Okay @stianmandarin thanks for that, now I understand what's going on. You're talking about the SEO Settings _field_

This is a dup of https://github.com/nystudio107/craft-seomatic/issues/163

...which has been addressed in https://github.com/nystudio107/craft-seomatic/commit/39686005ed67685b474b39c180d423c1e8384871
