### ISSUE TITLE
JSON-LD Meta: Add support for "CourseInstance.CourseSchedule" 

### ISSUE THREAD

**Issue by PiessensLander** [nystudio107/craft-seomatic#1420]
### Is your feature request related to a problem? Please describe.
I'm integrating the meta info for a Courses page using the JSON-LD function. When trying to add a `courseSchedule`, nothing happens because the property doesn't exist in the SEOMatic codebase.

### Describe the solution you would like
Add support for the `courseSchedule` in [`/src/models/jsonld/CourseInstance.php`](https://github.com/nystudio107/craft-seomatic/blob/c6e55b9c725bb14f3a267c47d0ee059bbe0fb9df/src/models/jsonld/CourseInstance.php#L95)

### Describe alternatives you have considered
Manually adding the required properties, but this doesn't work.

### Additional context
More info about `CourseInstance`: [schema.org](https://schema.org/CourseInstance)

**Comment by khalwat** [comment]
It must be a relatively newly added property for schema.org. Do you know what version it was added in?

**Comment by PiessensLander** [comment]
@khalwat looks like it was added in version 17.0 back in May 2023: https://github.com/schemaorg/schemaorg/issues/3314

**Comment by khalwat** [comment]
Addressed via the commits above

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.72”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.41”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.0-beta.5”,
```
Then do a `composer clear-cache && composer update`
