### ISSUE TITLE
GraphQL argument types mismatch with Craft

### ISSUE THREAD

**Issue by paulnzime** [nystudio107/craft-seomatic#1428]
### Describe the bug
Consider the following Craft GraphQL query:
```
query {
  entry(siteId: 1, uri: "about") {
    id
    title
  }
}
```

If I then want to use variables I'd change this to:
```
query Page($siteId: [QueryArgument], $uri: [String]) {
  entry(siteId: $siteId, uri: $uri) {
    id
    title
  }
}
```

Now I want to include the seomatic data here to keep queries light. So I'll amend the query to this:
```
query Page($siteId: Int, $uri: [String]) {
  entry(siteId: $siteId, uri: $uri) {
    id
    title
  }
  seomatic(siteId: $siteId, uri: $uri) {
    metaTitleContainer
    metaLinkContainer
    metaScriptContainer
    metaJsonLdContainer
    metaTagContainer
  }
}
```

This then results in an error, specifically these:
`Variable "$siteId" of type "Int" used in position expecting type "[QueryArgument]"`
`Variable "$uri" of type "[String]" used in position expecting type "String"`

Your plugins GraphQL arguments file is defining the `uri` type as just a single `String` but everywhere else in Craft this is an array of `String`. This is also the case for `siteId` - `Int` vs `[QueryArgument]`. This then either prevents us having the performance saving of a single query or we're having to define the variable twice just to pass into seomatic.

### Expected behaviour
Ideally I'd only have to pass the variable into the query once and the same variable can be used for both Craft queries and seomatic.

### Versions
- Plugin version: 4.0.42
- Craft version: 4.5.6.1

**Comment by khalwat** [comment]
I'll have a look at it to see if this is something that can be changed in a non-breaking way.

**Comment by khalwat** [comment]
Ah -- so actually, the way you're using it (as a "piggyback" on an ElementQuery): https://nystudio107.com/docs/seomatic/advanced.html#piggybacking-graphql-queries

You don't need to specify those parameters at all, it will pluck them from the Element in the top level query, so your GQL query should look like this:

```gql
query Page($siteId: [QueryArgument], $uri: [String]) {
  entry(siteId: $siteId, uri: $uri) {
    id
    title
    seomatic {
      metaTitleContainer
      metaLinkContainer
      metaScriptContainer
      metaJsonLdContainer
      metaTagContainer
    }
  }
}
```
