### ISSUE TITLE
Sitemap not generating for section - no error logs

### ISSUE THREAD

**Issue by amclaughlin-prophix** [nystudio107/craft-seomatic#1433]
### Describe the bug
sitemap not being generate for a particular channel section. 

### To reproduce
Running generate from CLI a section and its children appear to been included in the sitemap as they are listed on the screen however they are not present in the xml file. The section is listed but no children are listed in the section xml. There is also no logs of any errors. 

### Expected behavior
Section entries should appear in sitemap under the respective section.

### Versions
- Plugin version: 4.0.42
- Craft version: 4.74 Pro

**Comment by khalwat** [comment]
Can you please provide me with a link to the sitemap in question, or put its contents in here, along with what you _think_ its contents should be?

Are you sure the section in question has public URLs, and `robots` hasn't been set to `none` for the entries in that section?

**Comment by amclaughlin-prophix** [comment]
Hello,

Thank you for the quick reply.

https://www.prophix.com/sitemaps-1-sitemap.xml

This is the section which is not working: https://www.prophix.com/sitemaps-1-section-useCase-1-sitemap.xml

If I clear the cache via the CLI and run the generate command for the section in question it shows that it was generated, however it is not present in the xml. If I then try to run the generate command again it fails.

***@***.***
***@***.***

Fails:

***@***.***

[A picture containing text, clipart    Description automatically generated]

**Comment by amclaughlin-prophix** [comment]
![1](https://github.com/nystudio107/craft-seomatic/assets/137820172/69793ec5-bf8a-4efc-b511-2ff7f0b5862f)

![2](https://github.com/nystudio107/craft-seomatic/assets/137820172/57ecdd7b-b8e9-44af-bf4e-37aa3cfc8351)

Failed:
![3](https://github.com/nystudio107/craft-seomatic/assets/137820172/a6316d18-b9c5-4475-bd9b-267e0fed2e08)

**Comment by khalwat** [comment]
It looks like it is working for all other sections -- did you check to make sure this section has public URLs, and that the `robots` is enabled for this section on the Content SEO settings?

**Comment by amclaughlin-prophix** [comment]
Yes,

You can see from the screen shot it does iterate over these section entries with a cleared cache...yet still nothing in the XML.

Then if I try to run the generate command again and it doesn't iterate over anything still nothing in the XML.

Robots is all, these URLs are public.



________________________________

**Comment by khalwat** [comment]
Probably we will need to arrange a screen share to see if we can get to the bottom of what is going on here:

https://savvycal.com/nystudio107/chat

**Comment by khalwat** [comment]
This ended up being that the **Canonical URL** field was empty for this particular section, and the **Exclude Non-Canonical URLs** setting was enabled in SEOmatic -> Plugin Settings -> Sitemaps so because the Canonical URLs didn't match the actual URLs, they were excluded from the sitemap.
