### ISSUE TITLE
SEOmatic: Issue with GA$ Tracking Scripts 

### ISSUE THREAD

**Issue by andrewchar3456** [nystudio107/craft-seomatic#1434]
Hi, I'm trying to add a GA4 Tracking ID to my Craft CMS website via "Tracking Scripts" in your plug-in. I'm simply putting my script in the Script Template in the google gtag.js and though it shows up in source code, etc it's not wiring up to Google Analytics. Am I missing something? Website here: https://www.ultimedinc.com/

**Comment by andrewchar3456** [comment]
I was able to figure it out. I had to add a </script> tag to cancel out an automatic <script> tag that was added. Once I did that, GA was able to track.

**Comment by khalwat** [comment]
Glad you got it sorted.

**Comment by andrewchar3456** [comment]
It is a bug that I navigated, I needed to add a </script> to my code. But, great plug-in!
