### ISSUE TITLE
Cannot use ::class with dynamic class name

### ISSUE THREAD

**Issue by ArpadGBondor** [nystudio107/craft-seomatic#1436]
### Describe the bug
We keep getting an error thrown from a dependency of this package:
Cannot use ::class with dynamic class name

It is coming from here:
/nystudio107/craft-code-editor/src/autocompletes/SectionShorthandFieldsAutocomplete.php:167

I think it is this line in the current version:
https://github.com/nystudio107/craft-code-editor/blob/d2d9c8706fc1a6f40253fc78762101ce9b5ac386/src/autocompletes/SectionShorthandFieldsAutocomplete.php#L174

### Expected behaviour
I think something like this would solve it:
https://github.com/nystudio107/craft-twigfield/commit/bff508e2e239fd55b8a17ea56fc60db5e655f418

I raised a ticket under the plugin's repo, but after the bug got fixed, the version of the plugin should be bumped here too, so we can start using the solution.
https://github.com/nystudio107/craft-code-editor/issues/7 

### Versions
- Plugin version:
    "nystudio107/craft-seomatic": "3.4.68",
- Craft version:
    "craftcms/cms": "3.8.5",
   PHP - 7.4.33

**Comment by khalwat** [comment]
Yeah this will be fixed upstream in that package, so when you update it, SEOmatic will automatically get the changes. Follow it on the issue you filed over there: https://github.com/nystudio107/craft-code-editor/issues/7

I'm guessing it's specific to that version of PHP or such.

**Comment by khalwat** [comment]
Addressed in the above commit
