### ISSUE TITLE
Type of nystudio107\seomatic\Seomatic::$schemaVersion must be string

### ISSUE THREAD

**Issue by cbovers** [nystudio107/craft-seomatic#1438]
### Describe the bug
When trying to install Seomatic on a fresh Craft CMS 5 installation. We get the error:

*** installing seomatic
PHP Compile Error 'yii\base\ErrorException' with message 'Type of nystudio107\seomatic\Seomatic::$schemaVersion must be string (as in class craft\base\Plugin)'

in /var/www/html/vendor/nystudio107/craft-seomatic/src/Seomatic.php:0

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
Failed to run craft plugin/install seomatic: exit status 1

### To reproduce
Steps to reproduce the behaviour:
1. ddev composer require nystudio107/craft-seomatic
2. ddev craft plugin/install seomatic
3. See error message "PHP Compile Error 'yii\base\ErrorException' with message 'Type of nystudio107\seomatic\Seomatic::$schemaVersion must be string (as in class craft\base\Plugin)'"

### Versions
- Plugin version: Using version ^3.3 for nystudio107/craft-seomatic
- Craft version: Craft CMS version 5.0.0-beta.9 (Yii 2.0.48.1)

**Comment by khalwat** [comment]
Yeah you need to set the semver to:

```json
"nystudio107/craft-seomatic": "^5.0.0-beta.1",
```

...in your `composer.json` and then do a:

```
composer update nystudio107/craft-seomatic
```
