### ISSUE TITLE
Craft 5 / Beta 11

### ISSUE THREAD

**Issue by wmdhosting** [nystudio107/craft-seomatic#1439]
Entry type Breadcrumb seems have issue in Chrome

Perhaps better to put Site on first place like Craft

![Snag_b79709e](https://github.com/nystudio107/craft-seomatic/assets/76176291/3f9a1146-db5d-4cf5-9476-9191e2bbf198)

**Comment by khalwat** [comment]
I'm not seeing that running beta 11 here on Chrome:

<img width="1175" alt="Screenshot 2024-03-25 at 09 02 34" src="https://github.com/nystudio107/craft-seomatic/assets/7570798/d73106a8-5a86-4f9f-9434-e1546c3c0a6a">
