### ISSUE TITLE
JSON-LD not fully rendering

### ISSUE THREAD

**Issue by joshworden** [nystudio107/craft-seomatic#144]
I'm having the same issue described in Issue #101. All of the organization information is filled in SEOmatic, but the only thing that renders is:

`<script type="application/ld+json">{"@context":"http://schema.org","@id":"https://www.trajectorywebdesign.com/#identity","@type":"LocalBusiness"}</script>`

Clearing SEOmatic/template caches has no effect.

Help!

**Comment by khalwat** [comment]
What version of SEOmatic are you using?

**Comment by khalwat** [comment]
I did some investigating, and it ends up being a change in Craft CMS 3.0.10 that breaks this: https://github.com/craftcms/cms/issues/3002

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/89591b0696ba0a3b50df0299daee139705c2231d
