### ISSUE TITLE
Summary from field not working with neo / supertable

### ISSUE THREAD

**Issue by ZapaNOR** [nystudio107/craft-seomatic#1441]
When trying to define a neo field as the source for the SEO description under "Content SEO", I get the following error:

``[nystudio107\seomatic\helpers\MetaValue::parseMetaString] Error rendering `{{ seomatic.helper.extractSummary(seomatic.helper.extractTextFromField(entry.neo_content)) }}` -> An exception has been thrown during the rendering of a template ("Getting unknown property: verbb\supertable\elements\db\SuperTableBlockQuery::0")``

The field in question is a **Neo** field, and it contains one or more blocks with **Super Table** fields attached to them.

### Versions
- Plugin version: 4.0.45
- Craft version: 4.8.5

**Comment by khalwat** [comment]
Addressed in the above commits. Let me know how it works out for you:

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.46”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.0-beta.9”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
`4.0.46` released -> https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.46
