### ISSUE TITLE
Facebook Image is corrupt because of get parameter on image url

### ISSUE THREAD

**Issue by tonioseiler** [nystudio107/craft-seomatic#1443]
### Describe the bug
When we add a custom image to an entry like this one:
https://www.embru.ch/schule
and we add a custom seo image, the image url published is:
https://www.embru.ch/files/Schule/content/bilder/_1200x630_crop_center-center_82_none_ns/Embru-Schulmoebel-Schultisch-Schulstuhl_v2.jpg?mtime=1711032008

Facebook says the following;
Corrupted Image: Provided og:image URL, https://www.embru.ch/files/Schule/content/bilder/_1200x630_crop_center-center_82_none_ns/Embru-Schulmoebel-Schultisch-Schulstuhl_v2.jpg?mtime=1711032008 could not be processed as an image. It may be corrupted or may have an invalid format.

If we manually remove the mtime parameter, everything works fine

=> how can we get rid of this param from you plugin?

**Comment by khalwat** [comment]
Currently, there is no way to remove that URL param. However, I'm not sure that's actually a problem for Facebook -- I ran this URL:

https://nystudio107.com/blog/seo-myths-top-5-sitemap-myths-demystified

through the OpenGraph debugger: 

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fnystudio107.com%2Fblog%2Fseo-myths-top-5-sitemap-myths-demystified

...and it displays no issue with the image URL, and it doesn't really make sense that a URL parameter would cause the error you mentioned above.

I think the issue might be with the image itself, or with a temporary hiccup with whatever you're using to validate the Facebook image.
