### ISSUE TITLE
The body tag is hidden when the scripts are loaded

### ISSUE THREAD

**Issue by dialedin-team** [nystudio107/craft-seomatic#1445]
### Describe the bug
I loaded the GTM script using the SEOMATIC plugin. When the GTM scripts are loaded, the body tag is hidden. Actually, this CSS(opacity: 0 !important; background: none !important;) is applied to body, and there is no setting related to this on the plugin side. Why is it applied? This results in a white flash upon page load.

### Versions
- Plugin version: 4.0.45
- Craft version: 4.8.6

**Comment by dialedin-team** [comment]
Sorry for the inconvenience. It's not a plugin issue; The issue stems from the **VWOCode** third-party script. When the GTM scripts are loaded, the body tag is hidden. Actually, VWOCode applies this CSS (opacity: 0 !important; background: none !important;) to the body. When the page is fully loaded, it will remove the CSS from the body, resulting in a flashing effect.

Thanks!

**Comment by khalwat** [comment]
Glad you got it sorted.
