### ISSUE TITLE
Append page number to pagniated page titles

### ISSUE THREAD

**Issue by rjdusk** [nystudio107/craft-seomatic#145]
Hiya,
I'm trying to figure out how I update the seoTitle for pagnaited pages, so page 2, 3 and so on in my index of blog posts.

So far I've been trying  `{% do seomatic.meta.seoTitle("hit")~'Hi' %}` with little success. Ideally what I want to do is append the `pageInfo.currentPage` to the page title, just something to indicate where you are in the index of blog posts.

**Comment by khalwat** [comment]
So you'd actually want to do something like this:

```
{% set pageTitle = seomatic.meta.seoTitle %}
{% do seomatic.meta.seoTitle("#{pageTitle} #{pageInfo.currentPage}") %}
```

This is using Twig string literals as per https://twitter.com/nystudio107/status/938018528527036416

**Comment by rjdusk** [comment]
Brilliant!

One curious observation, when I have devMode set to true I get
`Twig Runtime Error – Twig_Error_Runtime
Calling unknown method: nystudio107\seomatic\services\Helper::pageinate()`
Disabling devMode and everything comes back to normal, any ideas? Probably a separate issue so I'm happy to start this in a new issue.

**Comment by khalwat** [comment]
It's because I can't spell, apparently. It should be `paginate` not `pageinate` -- I updated the docs: 

https://github.com/nystudio107/craft-seomatic#pagination-and-seo

**Comment by rjdusk** [comment]
Awesome, and all is well!

**Comment by paulgoodfield** [comment]
@khalwat - I'm attempting to do the same thing on a site, but for some reason it's appending the page number twice. 

If my page title looks like this by default:

`News & Blogs | Site Name`

If I then add the following to the page..

```
{% set pageTitle = seomatic.meta.seoTitle %}
{% do seomatic.meta.seoTitle(pageTitle ~ " | Page #{pageInfo.currentPage}") %}
```

...the page title is displaying as:

`News & Blogs | Page 2 | Page 2 | Site Name`


Any idea why?

**Comment by khalwat** [comment]
I'd have to guess that somehow that Twig code you wrote is being executed twice.

**Comment by paulgoodfield** [comment]
@khalwat It looks like it's that `{% set pageTitle = seomatic.meta.seoTitle %}` line that is causing the issue.

If I do...
```
{% set pageTitle = "Blah" %}
{% do seomatic.meta.seoTitle(pageTitle ~ " | Page #{pageInfo.currentPage}") %}
```
...then the page title is displaying as:
```
Blah | Page 2 | Site Name
```

When I do...
```
{% set pageTitle = seomatic.meta.seoTitle %}
{% do seomatic.meta.seoTitle(pageTitle ~ " | Page #{pageInfo.currentPage}") %}
```
...the page title displays as:
```
News & Blogs | Page 2 | Page 2 | Site Name
```

It looks like the `{% set pageTitle = seomatic.meta.seoTitle %}` line is actually doing more than just getting the current seoTitle and setting it to the `pageTitle` variable?

I can't see anywhere else in my codebase where the seoTitle is getting used/set.

**Comment by khalwat** [comment]
That's really strange, because I'm not seeing that behavior here. 

```twig
{% set pageTitle = seomatic.meta.seoTitle %}
{% do seomatic.meta.seoTitle(pageTitle ~ " | Page #1") %}
```

...and the result is the expected:

```
Homepage | Page #1
```

I'm thinking somehow that code you have there is being included or otherwise somehow being executed more than once. That would cause it to keep appending the `| Page #{pageInfo.currentPage}` to the title.
