### ISSUE TITLE
Duplicated Section in Content SEO and Sitemap

### ISSUE THREAD

**Issue by samuelreichor** [nystudio107/craft-seomatic#1450]
Hi, we have encountered an issue where a channel named "jobs" was duplicated due to problems with project YAML rebasing. Later, we removed one of the duplicated sections, and now there is only one section named "jobs." Unfortunately, the jobs section was somehow double-indexed in both the sitemap and the content SEO.

Now I see the section twice in the sitemap and in the content seo, and when I edit one, the other one gets edited as well.

I'm not sure how to reproduce this issue for you, but perhaps there's a way to reindex everything? I've also tried disabling and then re-enabling the sitemap, but that didn’t resolve the problem. Reinstalling the entire plugin might help, but that's not feasible because I can't apply such a fix on the live system.

![image](https://github.com/nystudio107/craft-seomatic/assets/98765339/1dfff61d-508d-4b0a-8725-5ccc6d1daaf4)
![image](https://github.com/nystudio107/craft-seomatic/assets/98765339/b4bb9ac5-b9ba-429b-9036-ca92e0191e4c)

### Versions
- Plugin version: 4.0.45
- Craft version: 4.8.7

**Comment by khalwat** [comment]
You can go in and delete the redundant row in the `seomatic_metabundles` table in the database
