### ISSUE TITLE
SEO Title Source Field does not show all available fields

### ISSUE THREAD

**Issue by philipschilling** [nystudio107/craft-seomatic#1451]
Hello,

### Describe the bug
When I go to _Content SEO > [Select Channel] > General > SEO Title Source_ and select the option "From Field", in the dropdown "Source Field" only some but not all available fields are shown. I couldn't find a reason why certain fields would not shown up because there are fields with almost the same settings (e.g. same field type such as plain text, is field searchable, etc.) that do show up and others don't. Is it possible that the list ist limited to 10 fields?
<img width="1550" alt="Screenshot 2024-04-08 at 15 45 33" src="https://github.com/nystudio107/craft-seomatic/assets/4956295/dc4db7d3-410a-4a8d-9208-14c8d0d7576b">

Here are the field settings that I use:
![Page-Title-Field](https://github.com/nystudio107/craft-seomatic/assets/4956295/0043ebed-475f-47a9-95e0-ef4cb01444a1)

### Expected behaviour
I would like that all fields show up in the Source Field dropdown. I created new fields for SEO Title, SEO Description, etc. that I cannot select from the list.

### Versions
- Plugin version: SEO matic 5.0.0-beta.8
- Craft version: Craft Solo 5.0.0

**Comment by philipschilling** [comment]
I found the issue: I haven't added the fields to the entry type which I selected for a channel section. Therefore, they did not show up in the dropdown :-).

**Comment by khalwat** [comment]
Glad you have it sorted!
