### ISSUE TITLE
Set Meta Robots value on per-entry basis

### ISSUE THREAD

**Issue by philipschilling** [nystudio107/craft-seomatic#1452]
### Question
I would like to set the meta robots value on per-entry basis. An example could be the privacy policy or legal pages where I would like to use _noindex, follow_ instead of the site-wide setting _index, follow_. How can I do this?

### Additional context
I am looking for something like setting a Source Field as for SEO Title, SEO Description or SEO Keywords under _Content SEO > [[Select section]] > General_. However, for the meta robots field I can only set a value per section and not per entry:
<img width="733" alt="Screenshot 2024-04-08 at 18 24 30" src="https://github.com/nystudio107/craft-seomatic/assets/4956295/f5ee39d0-656f-4308-9009-c7d00c66faa0">

**Comment by khalwat** [comment]
Add an SEO Settings field to the Section in question, and set it to allow them to override the Robots setting. 

Then override the Robots setting on any pages you wish to exclude.

**Comment by philipschilling** [comment]
Many thanks. I didn't understand the [documentation](https://nystudio107.com/docs/seomatic/fields.html) but now it is clear that SEO Settings is not a _field_ but actually a _field type_ which you can select when creating a new field:

<img width="280" alt="Screenshot 2024-04-08 at 19 03 36" src="https://github.com/nystudio107/craft-seomatic/assets/4956295/7863521e-e946-43dd-85c4-606a2bce2c8f">

**Comment by khalwat** [comment]
Correct!
