### ISSUE TITLE
Craft 5 Type Error caused by missing SourceId when trying to edit matrix block (entry type)

### ISSUE THREAD

**Issue by rebkuhn** [nystudio107/craft-seomatic#1456]
### Error Message in matrix block edit screen
In Craft 5, when I want to edit a matrix block (entry type) which has its own entry url, i get the following error message:
```
TypeError
nystudio107\seomatic\services\MetaBundles::getMetaBundleBySourceId(): Argument #2 ($sourceId) must be of type int, null given, called in /path/to/my-site/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php on line 467
```
As soon as I remove the entry URI format from the matrix field settings or disable the seomatic plugin, the error disappears and the matrix block can be edited again.

### Versions
- Plugin version: SEOmatic 5.0.2
- Craft version: Craft CMS, 5.0.4 (Team Edition)

**Comment by rebkuhn** [comment]
... Additional note: The same error message also appears, when (pre-)viewing the matrix block entry in the frontend.

**Comment by khalwat** [comment]
I tried to reproduce this, but I was unable to.

Can you provided details (screenshots would be very helpful) of the Matrix entry type, and where the Matrix field lives, and a screenshot of what you were doing when the error was triggered?

**Comment by rebkuhn** [comment]
> I tried to reproduce this, but I was unable to.
> 
> Can you provided details (screenshots would be very helpful) of the Matrix entry type, and where the Matrix field lives, and a screenshot of what you were doing when the error was triggered?

@khalwat I forgot to mention that there is a matrix in matrix. Here are some screenshots. Hope that helps.

<img width="2279" alt="Bildschirmfoto 2024-04-12 um 09 55 02" src="https://github.com/nystudio107/craft-seomatic/assets/26826337/2fea0be8-25f3-4d5e-9362-1a1f8136e72f">

<img width="2381" alt="Bildschirmfoto 2024-04-12 um 09 44 29" src="https://github.com/nystudio107/craft-seomatic/assets/26826337/befd65a0-774a-450f-94b6-c5b11ee63b62">

**Comment by rebkuhn** [comment]
> @khalwat I forgot to mention that there is a matrix in matrix. Here are some screenshots. Hope that helps.

@khalwat I would just like to ask briefly whether you were able to look at the problem with the missing SourceId again or whether you need any additional information from me.

**Comment by khalwat** [comment]
First I need to set up a test case where I can reproduce the error; I'm going to try to do that shortly with the new information you have provided.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/c87ad6b3ece1ca5d924191a31b2f1f2b31f3298c

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.3”,
```
Then do a `composer clear-cache && composer update`
