### ISSUE TITLE
Allow to set noindex,follow in the SEO settings field

### ISSUE THREAD

**Issue by philipschilling** [nystudio107/craft-seomatic#1458]
### Is your feature request related to a problem? Please describe.
I use the SEO settings field to override on entry-level the Meta Robots settings. For example I would like the legal pages not to be indexed. There are 2 issues:
1. I can only select the option "noindex" but not "noindex, follow".
<img width="752" alt="Screenshot 2024-04-13 at 14 39 49" src="https://github.com/nystudio107/craft-seomatic/assets/4956295/c708269c-e950-4194-847c-797135bb4dde">

2. When I choose the option "noindex", in the HTML head on the page is shown:
<meta name="robots" content="none">

<img width="407" alt="Screenshot 2024-04-13 at 14 41 04" src="https://github.com/nystudio107/craft-seomatic/assets/4956295/2b067dee-1cf9-4a15-9e23-4f3111c29b65">

"none" translates according to [this page](https://www.conductor.com/academy/meta-robots-tag/#none) to "noindex, nofollow" and is not corresponding to my setting.

### Describe the solution you would like
1. It would be nice to have the option "noindex, follow" in the Meta Robots dropdown within the SEO settings field.
2. When "noindex" is chosen, the Meta Robots tag should be: <meta name="robots" content="noindex">

**Comment by khalwat** [comment]
So I'm guessing this is actually working as expected, and you're viewing things in your local development environment, or in a staging environment.

In those cases, SEOmatic forces `robots` to be `none` to prevent accidental indexing, overriding the `noindex` setting you have selected.

If you want to simulate the live environment locally, you can do so via SEOmatic Settings -> Plugin Settings -> General and then toggle on **Manually Set SEOmatic Environment**

**Comment by philipschilling** [comment]
You are right. I knew the configuration but forgot that the development environment overwrites the settings.

**Comment by redkrupp** [comment]
Not sure why it was closed. There is still no option to select - "noindex, follow" in the plugin settings.

https://capture.dropbox.com/jceuJE7akJag26uf

**Comment by spAnser** [comment]
*Update*

This was in fact a separate issue.

*Original Message:*
```
This is still not being respected. It seems to flip flop between `all` and `none` depending on page load as well sometimes.
```

**Comment by khalwat** [comment]
@EmptyStreets unless I'm confused, the original person who filed this issue had his issue solved, that's why I closed it.

@spAnser I'm unable to reproduce your issue; can you provide more information, hopefully in a new issue that is specific to the problem you're having?

**Comment by spAnser** [comment]
I actually think my issue might be slightly different. I'll see if I can get something reproducible setup and open a separate issue if I can.
