### ISSUE TITLE
Craft ImageOptimize + Imgix + SEOMatic

### ISSUE THREAD

**Issue by MikeMcChillin** [nystudio107/craft-seomatic#146]
I'm getting the same issue as mentioned in #132 

Using Craft ImageOptimize, with Imgix enabled, the image meta tags SEOMatic spits out contain `&amp;` instead of `&`, which breaks the image URL.

Broken output meta image:
```
<meta content="https://kleinschmidt.imgix.net/heros/Freight-Transportation-and-Logistics.jpg?crop=focalpoint&amp;domain=kleinschmidt.imgix.net&amp;fit=crop&amp;fm=jpg&amp;fp-x=0.5145&amp;fp-y=0.5385&amp;h=630&amp;ixlib=php-1.2.1&amp;q=82&amp;usm=50&amp;w=1200&amp;s=3dbbbebee57513a5e775f4b5dde7bbb8" property="og:image">
```

Working image link via ImageOptimize:
```
https://kleinschmidt.imgix.net/heros/Freight-Transportation-and-Logistics.jpg?auto=format&crop=focalpoint&domain=kleinschmidt.imgix.net&fit=crop&fp-x=0.5145&fp-y=0.5385&h=868&ixlib=php-1.2.1&q=61&usm=50&w=1984&s=12c8393dba12bc4807949ead5931fb56
```

**Comment by khalwat** [comment]
What version of SEOmatic are you using?

**Comment by MikeMcChillin** [comment]
@khalwat 
SEOmatic v`3.0.23`
ImageOptimize v`1.4.33`

**Comment by khalwat** [comment]
I think I see what's going on here; it may actually be a Yii2 bug/oversight. Let me look further into it.

**Comment by khalwat** [comment]
So I looked into this for a bit, and Yii2 is indeed calling:

```
htmlspecialchars($content, ENT_QUOTES | ENT_SUBSTITUTE, Yii::$app ? Yii::$app->charset : 'UTF-8', $doubleEncode);
```
For any content inside of meta tags; the thing is, I'm not sure this is wrong. I do think that the data inside of meta tags is supposed to be html entity encoded.

So then the question is... is this URL really broken? I realize that if you paste this into a browser URL bar, it doesn't work:

```
https://kleinschmidt.imgix.net/heros/Freight-Transportation-and-Logistics.jpg?crop=focalpoint&amp;domain=kleinschmidt.imgix.net&amp;fit=crop&amp;fm=jpg&amp;fp-x=0.5145&amp;fp-y=0.5385&amp;h=630&amp;ixlib=php-1.2.1&amp;q=82&amp;usm=50&amp;w=1200&amp;s=3dbbbebee57513a5e775f4b5dde7bbb8
```

...but when Facebook crawls the page, are we sure that it doesn't do an HTML entity decode before attempting to use the URL?

**Comment by khalwat** [comment]
https://webmasters.stackexchange.com/questions/76522/are-html-encoded-symbols-allowed-in-meta-description

**Comment by MikeMcChillin** [comment]
So it seems like Facebook and Slack are properly displaying the image via the `meta` tag. The SEO Previews within Craft show a broken image, however.

![seo-preview](https://user-images.githubusercontent.com/872219/41795175-755ba21e-7627-11e8-9a69-f79041b3bde6.jpg)
![screen shot 2018-06-22 at 2 08 56 pm](https://user-images.githubusercontent.com/872219/41795185-7d62ca0a-7627-11e8-8c4c-936f7ef10558.png)

**Comment by khalwat** [comment]
Yeah I'll see if I can fix it so the previews aren't broken, but I think SEOmatic is actually doing things the "right" way.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/34f4729d172fcf9b3f53b67a8529f37d64bbd5cf
