### ISSUE TITLE
Including indexable files within the XML sitemap via related download entries

### ISSUE THREAD

**Issue by mtwalsh** [nystudio107/craft-seomatic#1460]
### Question

We want to include indexable files within a product section's XML sitemap, the problem is the indexable files (assets) are not related to the product entries directly but instead via entries within a downloads section. It's these download entries that have the actual assets related to them. Is there any way to make these visible to SEOmatic when it's constructing the XML sitemap? Or is our only option to adjust the approach such that the assets are directly related to the product entries?

**Comment by mtwalsh** [comment]
Hmm, I'm wondering if we're better off adjusting the structure here so the assets are directly related to the products.

**Comment by khalwat** [comment]
That is one way to do it. Another way would be with a custom sitemap: https://nystudio107.com/docs/seomatic/advanced.html#registersitemapsevent

**Comment by mtwalsh** [comment]
We're going to adjust the structure (so the assets are directly related), thanks for the link though 👍
