### ISSUE TITLE
Google Web Stories

### ISSUE THREAD

**Issue by lucosius** [nystudio107/craft-seomatic#1462]
Hello there,

I'm trying to get Structured data information in my Web Stories but the problem is that if jsonLd container is placed outside amp-story tag then I have validation issues.

I turned off displaying of jsonLd with this:

`{% do seomatic.jsonLd.container().include(false) %}`

But how can I place the exact same information in the location I want? I couldn't find any shortcode that let me do that.

**Comment by khalwat** [comment]
You can manually render it via: 

```twig
{{ seomatic.jsonLd.render() }}
```
