### ISSUE TITLE
Unable to change SEO metafields after changing entry type

### ISSUE THREAD

**Issue by joelstrom** [nystudio107/craft-seomatic#1464]
### Describe the bug
We're unable to update SEO meta settings on a new entry after changing the entry type. Only way to get around it seems to be saving the entry once after changing the entry type.

### To reproduce
Steps to reproduce the behaviour:
1. Create new entry
2. Change entry type to another one
3. All metafields are "locked", editing them is not possible. Trying to override values is not possible.

### Expected behaviour
Fields would be editable just like other custom fields in the entry type without having to save the entry in between

### Screenshots
Creating new entry, everything looks normal:
<img width="1424" alt="Screenshot 2024-05-02 at 15 07 20" src="https://github.com/nystudio107/craft-seomatic/assets/15905441/c4508f95-495e-470f-bcd4-dbf1e4458bf5">

Changing entry type, fields get "locked":
<img width="1443" alt="Screenshot 2024-05-02 at 15 07 32" src="https://github.com/nystudio107/craft-seomatic/assets/15905441/56beb1f4-9fc2-468a-8819-d46fc76d2ccb">

### Versions
- Plugin version: 4.0.48
- Craft version: Craft Pro 4.8.10

**Comment by khalwat** [comment]
I wasn't able to reproduce this.

In order to edit any of those disabled fields, you need to turn on the **Override** light switch above it.

Could it perhaps be that?

**Comment by joelstrom** [comment]
Using the override buttons don't seem to do anything in this state. After activating them, we're unable to open the dropdowns or manually enter anything into the plain text fields. As you can see in the screenshot below, the dropdowns are greyed out:

<img width="1056" alt="Screenshot 2024-05-03 at 9 38 59" src="https://github.com/nystudio107/craft-seomatic/assets/15905441/8a8fb975-1012-4ea7-850a-844e4a63d555">

**Comment by khalwat** [comment]
Are you seeing any errors in the JavaScript console? I tried reproducing what you're doing on the latest Craft 4.x and SEOmatic 4.x and was unable to

**Comment by joelstrom** [comment]
No javascript errors unfortunately! Was trying to keep an eye out on any failed requests too, but can't see see anything.
The fields are in a disabled state and the value is what you see in the earlier screenshot also. Here is another where you see the html:

![Screenshot 2024-05-13 at 17 32 36](https://github.com/nystudio107/craft-seomatic/assets/15905441/0621308a-33b3-4a8a-a759-3f052ed9f711)

It's not a huge issue especially for us, but the client gets the impression that something is breaking.

**Comment by khalwat** [comment]
Yeah I can understand the client's concern. I just wish I could replicate it here. It's tough to fix it without being able to replicate it. Any help you can offer would be welcome in that regard.
