### ISSUE TITLE
How to update frontendTemplatesContainer via content migration

### ISSUE THREAD

**Issue by jrrdnx** [nystudio107/craft-seomatic#1465]
Updating a few settings via a content migration and have most of them working, e.g.:

```
$globalMetaBundle = Seomatic::$plugin->metaBundles->getGlobalMetaBundle(Craft::$app->sites->getPrimarySite()->id);

$globalMetaBundle->metaGlobalVars->siteNamePosition = 'after';
$globalMetaBundle->metaSiteVars->creator->genericName = 'Sample Name';

Seomatic::$plugin->metabundles->updateMetaBundle($globalMetaBundle, Craft::$app->sites->getPrimarySite()->id);
```

Unfortunately I'm having trouble updating the default robots template via:
```
$globalMetaBundle->frontendTemplatesContainer->data['robots']->setAttributes([
    'include' => 1,
    'templateString' => 'sample string'
]);
```

This particular method doesn't seem to have any affect. Any help would be greatly appreciated, thanks!

**Comment by khalwat** [comment]
Not sure, that looks right to me -- did you confirm that it's changed in the `seomatic_metabundles` table as expected after you've saved it?

**Comment by jrrdnx** [comment]
Confirmed it was an issue with the string I was attempting to save. The syntax I was using was working correctly. All good here, thanks!
