### ISSUE TITLE
Canonicals and hreflangs for paginated paginas

### ISSUE THREAD

**Issue by svondervoort** [nystudio107/craft-seomatic#1468]
### Describe the bug
We have several multi language sites with paginated content. In SEranking, but also in [TechnicalSEO](https://technicalseo.com/tools/hreflang/) and h[reflang.com](https://app.hreflang.org/results.php?runid=8f77cc3c40fb52061c66079aacc7a83f20240513064902) we get errors like:
> Confirmation (return) links missing on hreflang pages

> Missing return link

> Mismatched Hreflang Tags: en

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Expected behaviour
Now I've been reading some articles which suggest that the paginated links should not be `hreflang` but should be `canonicals` instead. [Article 1](https://hreflang.org/use-hreflang-canonical-together/) / [Article 2](https://www.searchviu.com/en/hreflang-canonical/) / Also the [article](https://moz.com/blog/seo-guide-to-google-webmaster-recommendations-for-pagination) you reference in in the [docs](https://nystudio107.com/docs/seomatic/using/pagination.html).

### Screenshots
One of the cases that give an error is: https://www.bleckmann.com/resources/p/2

```
<link href="https://www.bleckmann.com/resources/p/2" rel="canonical">
<link href="https://www.bleckmann.com/" rel="home">
<link type="text/plain" href="https://www.bleckmann.com/humans.txt" rel="author">
<link href="https://www.bleckmann.com/nl/resources" rel="alternate" hreflang="nl">
<link href="https://www.bleckmann.com/resources" rel="alternate" hreflang="x-default">
<link href="https://www.bleckmann.com/resources/p/2" rel="alternate" hreflang="en">
<link href="https://www.bleckmann.com/resources" rel="prev">
<link href="https://www.bleckmann.com/resources/p/3" rel="next">
```

### Versions
- Plugin version: 4.0.48
- Craft version: 4.9.2

**Comment by khalwat** [comment]
There's a setting in SEOmatic to disable hreflang tags for paginated entries:

SEOmatic -> Plugin Settings -> Tags -> Include Paginated hreflang Tags

If you want them disabled, you can turn them off.

That said, can you provide me with what the _expected result_ is that you'd like to be seeing gofr the paginated entries?

**Comment by svondervoort** [comment]
Thanks for the reply.

I wasn't aware of that option, I'll give it a go and see if that fixes the issue.

**Comment by svondervoort** [comment]
Sadly disabling it will give even more errors with the new error:
> Hreflang page doesn't link out to itself

Even though the result matches the desired links described in this [Article](https://hreflang.org/use-hreflang-canonical-together/).

So at the moment I'm not sure who is right, the "hreflang" testers or the articles.
I will have to dive deeper into it when I get the time, so for now I will just close this issue.
