### ISSUE TITLE
Duplicate section in Content SEO

### ISSUE THREAD

**Issue by cookie10codes** [nystudio107/craft-seomatic#1469]
### Describe the bug
Seeing history tracks, this is a known but. Don't know exactly how to fix myself tho. But looking at the Content SEO, I have duplicate channels listed. Non of both seems to be working or setting data.

### Screenshots
<img width="512" alt="Screenshot 2024-05-21 at 08 19 11" src="https://github.com/nystudio107/craft-seomatic/assets/20947573/7e6c6b74-5609-4290-a43b-f0c0021b4183">

### Versions
- Plugin version: 4.0.49
- Craft version: Craft Pro 4.9.4

**Comment by khalwat** [comment]
I'm not sure how this ended up happening your particular case, but you can go in and delete the duplicate rows from the `seomatic_metabundles` table in the database.
