### ISSUE TITLE
SEO Setting Fields

### ISSUE THREAD

**Issue by jasonmckinney66** [nystudio107/craft-seomatic#147]
We would like to display the General SEO Settings Tab on individual entries.
How does one access these options: 
https://github.com/nystudio107/craft-seomatic#seo-settings-field
We can't seem to find any panel that matches the screenshot provided in the documentation.
Thanks.

**Comment by khalwat** [comment]
Create an SEO Settings field, and add it to your Section layout as you would any other field, and away you go!
