### ISSUE TITLE
Sitemap URL inconsistencies

### ISSUE THREAD

**Issue by stevehurst** [nystudio107/craft-seomatic#1470]
Our client is reporting inconsistencies in their sitemap URLs that is causing errors for them in SEMrush and other reporting tools.

When I look at their sitemaps, I see a mix of complete URLs with domain name, and some that are only absolute links to pages. According to my client, this varies from week to week. I'm not able to find any canonical setting in the SEOmatic settings to make sense of this from section to section in Craft. How are they generated?

See here:
https://kalypso.com/sitemaps-1-sitemap.xml
https://kalypso.com/sitemaps-1-section-about-1-sitemap.xml
https://kalypso.com/sitemaps-1-section-caseStudies-1-sitemap.xml

Attaching images, since the live versions can be inconsistent.

<img width="852" alt="Screenshot 2024-05-21 at 10 49 52 AM" src="https://github.com/nystudio107/craft-seomatic/assets/20077/d9bdbd9e-8534-43a4-9673-727c25744001">
<img width="847" alt="Screenshot 2024-05-21 at 10 49 45 AM" src="https://github.com/nystudio107/craft-seomatic/assets/20077/654c34dd-e234-4ad2-b326-479809364a5b">
<img width="849" alt="Screenshot 2024-05-21 at 10 50 10 AM" src="https://github.com/nystudio107/craft-seomatic/assets/20077/8c4543aa-fc93-42e5-9ccc-0b05387b8169">

**Comment by khalwat** [comment]
How are you setting the site's URL? SEOmatic just asks Craft for the URL to the entries, so ensure that your primary site URL is set properly.

Also, is there anything special about the `about` section, which appears to have the URLs not be correct?

**Comment by stevehurst** [comment]
It looks like we were not setting either DEFAULT_SITE_URL or PRIMARY_SITE_URL in the .env file on production, but we have added both and cleared cache and the sitemaps all seem to be consistent now! I bet that was having a negative impact elsewhere. Thanks for the lead.

There was nothing specific or different set about the sections that did or didn't show the full URL. Weird, but it seems to be be consistent now.
