### ISSUE TITLE
`disallowRobots` does't override SEOmatic settings

### ISSUE THREAD

**Issue by Megafry** [nystudio107/craft-seomatic#1471]
### Describe the bug
Via the general settings the option `disallowRobots` was set to `true`, the goal being to prevent Google from indexing the project.
Unfortunately, the generated page ignores this setting because `environment` in `seomatic.php` is set to `live`

Shouldn't the general settings be more important than plugins?
Thanks for your feedback

### To reproduce
1. set `disallowRobots` in `general.php` or via the `.env` to `true`
2. set `environment` in `seomatic.php` to `live`
3. Check the generated page HTTP header.

### Expected behaviour
All pages need to respond with HTTP headers `X-Robots-Tag: none`

### Versions
- Plugin version: 4.0.48
- Craft version: 4.7.4

**Comment by khalwat** [comment]
You can just manually override the SEOmatic environment via SEOmatic -> Plugin Settings -> **Manually Set SEOmatic Environment**

Then you don't need to set anything in your `general.php` or in your `.env` file, because SEOmatic will take care of it all for you.
