### ISSUE TITLE
Internal Server Error when opening Site Settings

### ISSUE THREAD

**Issue by philipschilling** [nystudio107/craft-seomatic#1472]
### Describe the bug
I get the attached server error when I open SEOmatic > Site settings (https://www.domain.ch/admin/seomatic/site/identity?site=xyz) in the Control panel. I noticed that this error happens only for one site and does not produce for another site in a multi-site environment.

I cleared the Craft CMS caches which did not solve the issue.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "SEOmatic" in control panel
2. Click on "Site settings" in left menu bar
3. See error message "Internal Server Error" (Image below)

### Expected behaviour
It should be possible to open the site settings page for all sites in a multi-site environment without a server error.

### Screenshots
<img width="357" alt="Screenshot 2024-05-28 at 03 45 50" src="https://github.com/nystudio107/craft-seomatic/assets/4956295/40bdf39a-22b1-4257-a970-241bac72352f">

### Versions
- Plugin version: 5.0.3
- Craft version: Craft Solo 5.1.7

**Comment by khalwat** [comment]
Please include the actual error log so I can have a look at it? I'm not sure this is going to end up being an SEOmatic issue directly.

**Comment by philipschilling** [comment]
Just opened it as a replacement for the emails where the log file was attached.

[SeoMatic_TypeError.pdf](https://github.com/nystudio107/craft-seomatic/files/15463021/SeoMatic_TypeError.pdf)

**Comment by khalwat** [comment]
So as mentioned in our email exchange, I was unable to reproduce this.  The relevant Twig code is:

```twig
{{ forms.elementSelectfield({
    label: "Entity Brand"|t("seomatic"),
    instructions: "An image or logo that represents the entity that #{websiteVerb} the website.  The image must be in JPG, PNG, or GIF format." |t("seomatic"),
    id: "genericImageIds",
    name: "genericImageIds",
    viewMode: "large",
    elements: genericImageElements,
    elementType: elementType,
    criteria: {
        kind: ["image"],
    },
    jsClass: "Craft.AssetSelectInput",
    selectionLabel: "Select Brand Image"|t("seomatic"),
    sources: null,
    limit: 1,
    warning: false,
    errors: entity.getErrors("genericImageIds"),
}) }}
```
ref: https://github.com/nystudio107/craft-seomatic/blob/develop-v5/src/templates/settings/site/_includes/entity-partial.twig#L75

This ends up using the Craft template `_includes/forms/elementSelect.twig` which does this:

```twig
{% set elements = elements ?? [] -%}
```

...and then it ends up defaulting to this include `_elements/list.twig`: 

```twig
        {{ include('_elements/list.twig', {
            elements,
            viewMode,
            disabled,
            context: 'field',
            sortable: false,
        }) }}
```

...which loops through the elements and calls  `elementChip()`

```twig
    {% for element in elements %}
      <li>
        {% set element = elementChip(element, {
          context: context ?? 'index',
          size: size ?? (viewMode == 'large' ? 'large' : 'small'),
          inputName: inputName ?? ((name ?? false) ? "#{name}[]" : null),
          showActionMenu: showActionMenu ?? false,
          checkbox: selectable ?? false,
        }) %}
```

...which is where the error is. I'm passing in either an empty array, or an array of elements obtained thusly:

```php
            $variables['creatorImageElements'] = ImageTransformHelper::assetElementsFromIds(
                $variables['site']->creator->genericImageIds,
                $siteId
            );
```

ref: https://github.com/nystudio107/craft-seomatic/blob/develop-v5/src/controllers/SettingsController.php#L775

This is the same code that has been working on Craft 3 & 4, and I'm unaware of changes in Craft 5 that would affect it.

Given the nature of the error you reported, it almost seems like some part of the system isn't fully set up as expected... _somehow_ something that apparently isn't an Element is making its way to `elementChip()`

**Comment by philipschilling** [comment]
The Craft CMS support team found a solution which works for me. I add it here so that you are informed as well:

> I'm not exactly sure what caused this, but it looks like something was corrupted within the SEOmatic settings. These steps should resolve it:
> 
> Inside the database, go to the seomatic_metabundles table
> find row ID 2 - this will be the SEOmatic settings for the 'Superlager' site.
> in the metaSiteVars column replace the existing content with the content in the file I've attached
> With that, I'm able to load the SEOmatic Site Settings again.
> 
> The error was coming from "genericImageIds":["237"], in the existing json -- I'm not exactly sure what that would be, but maybe the 'Entity Brand' image?

**Comment by khalwat** [comment]
That doesn't look wrong to me, that would be the id of the Asset -- can you attach the file they gave you here so I can investigate it?

**Comment by philipschilling** [comment]
I attach the file. Not sure if that is really helpful to you without the database file. Only the **genericImageIds** changed from **237** to **1328**:
[seomatic-settings.json](https://github.com/user-attachments/files/15525042/seomatic-settings.json)

**Comment by khalwat** [comment]
Thanks, that was actually really helpful. I think what happened is if an Asset was deleted that was chosen as the Entity or Creator brand, `AssetTransformHelper::assetElementsFromIds()` would return an array with `null` in it.

This didn't seem to cause a problem on older versions of Craft (though it's still wrong/unintended behavior), which is likely why it hasn't surfaced as an issue yet.

The above commits should fix it going forward!

Thanks for your help & patience @philipschilling

**Comment by philipschilling** [comment]
It's great that you could fix it. Overall, SEOmatic runs extraordinary smooth.

**Comment by khalwat** [comment]
Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.78”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.50”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.4”,
```
Then do a `composer clear-cache && composer update`
