### ISSUE TITLE
Updated SEO description - not displaying correctly in template

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#1473]
Craft 4.5.13
SEOmatic 4.0.37

### Question
I'm using the SEOmatic description as a fallback summary in a search results page with the following code

```
{% set copy = entry.shortDescription
  ?? entry.summary 
  ?? seomatic.meta.parsedValue('seoDescription') 
  ?? '' %}
{# truncate the copy here #}
{% set excerpt = seomatic.helper.truncateOnWord(copy, 300) %}
```

It's working as expected **however** when updating the Seodescription for the entry it does not get updated in the search results template though it does in the meta tags

![image](https://github.com/nystudio107/craft-seomatic/assets/6899490/9392d250-f4c0-42d5-ac3b-4424dba80293)

metatag is updated correctly 
![image](https://github.com/nystudio107/craft-seomatic/assets/6899490/10403da5-88b6-471a-92e8-7fd6bc92fe83)

but search snippet is not update
![image](https://github.com/nystudio107/craft-seomatic/assets/6899490/f34062a0-a998-432a-a6ec-fd70991c2054)

I have cleared all site caches but this does not resolve the issue. 

Please advise.

### Additional context
Add any other context or screenshots about the support request here.

**Comment by CreateSean** [comment]
Any update available for this?

**Comment by khalwat** [comment]
To debug it... see what your variable `copy` evaluates to?

My guess would be that it's evaluating to `entry.shortDescription` or `entry.summary`?

Happy to help you continue to figure this out, so feel free to keep posting here, but I'm going to close the issue as I don't think it's an SEOmatic issue.

**Comment by CreateSean** [comment]
@khalwat 

Theh fields `entry.shortdescription` and `entry.summary` do not exist in this channel. I looked and the Global SEO description is being pulled into the search results not the seo description for the entry.

I then changed the code to this - prefixing the seomtatic.meta.... with entry:

```twig
            {% set copy = entry.shortDescription
              ?? entry.summary
              ?? entry.fullBio
              ?? entry.seomatic.meta.parsedValue('seoDescription')
              ?? '' %}
```

and then there was no text returned in the search results. If I remove the `entry` prefix it returns the global seo description value.

![image](https://github.com/nystudio107/craft-seomatic/assets/6899490/990cac63-306c-488a-bb9a-920703a71e78)

**Comment by khalwat** [comment]
I'm guessing that the `entry` you're referencing here is _not_ the entry that is associated with the route for the search results page?

Typically I don't really recommend using SEOmatic in this manner, but you can use `seomatic.helper.loadMetadataForUri(entry.uri) ` -> https://nystudio107.com/docs/seomatic/using/helper-functions.html#helper-functions

...to load the metacontainers for the entry in quest, so that what you're attempting to do will work.

**Comment by khalwat** [comment]
More on this topic is also here: https://nystudio107.com/blog/tips-for-using-seomatic-effectively#rendering-metadata-from-another-route

**Comment by CreateSean** [comment]
Thanks @khalwat  - tried, sort of worked but there was a different bug. I pushed client to go with my original recommendation of adding a dedicated field and they agreed now.

Please close this issue.
