### ISSUE TITLE
Some SEOmatic twig variables don't always render og tags properly in Craft 5

### ISSUE THREAD

**Issue by steveDL** [nystudio107/craft-seomatic#1478]
### Describe the bug
Not all SEOmatic variables render properly. 

### Screenshots

<img width="1108" alt="Screenshot 2024-06-03 at 21 03 09" src="https://github.com/nystudio107/craft-seomatic/assets/8135124/e0b56185-4f11-4793-92a9-f050174e841a">

<img width="340" alt="Screenshot 2024-06-03 at 21 05 41" src="https://github.com/nystudio107/craft-seomatic/assets/8135124/b8d9de00-dd21-4329-8cd3-c0330948dc81">

<img width="620" alt="Screenshot 2024-06-03 at 21 03 28" src="https://github.com/nystudio107/craft-seomatic/assets/8135124/7caea07a-ce53-4d01-beea-93133a9c8231">

### Versions
- Plugin version:
- Craft version:

**Comment by khalwat** [comment]
Please also include the version of Craft you're using, and the version of SEOmatic.

Are you letting SEOmatic render the meta tags automatically?

If so, I think something may be wrong with your setup / install. Check your error logs in `storage/logs` for errors.

I am unable to reproduce this issue on the latest version of Craft 5, with the latest version of SEOmatic.

**Comment by steveDL** [comment]
Hey @khalwat thanks for the quick reply. 

My craft and SEOmatic versions are in the picture above. Craft 5.1.7 and SEOmatic 5.0.3. I have also turned off automatic rendering. 

I will check the logs thanks

**Comment by khalwat** [comment]
Okay so if you turn automatic rendering on, does it then work as expected?

**Comment by steveDL** [comment]
The automatic rendering works fine, but not if I use variables. 

using variable for for example this ..

` <link rel="canonical" href="{{ seomatic.meta.canonicalUrl }}">`

renders this...

`<link rel="canonical" href="{{ entry.url }}">`

**Comment by khalwat** [comment]
Is there a reason you're not just using automatic rendering?

For manual rendering, it's expected that you instead just do `seomatic.tag.render()`, `seomatic.link.render()`, etc. and it will render them for you: https://nystudio107.com/docs/seomatic/configuring/plugin-settings.html#general-plugin-settings

What you're trying to do doesn't really make a lot of sense to me, because you're adding a lot of work for no real benefit I can see.

But if you really want to do it, you'd need to do something like:

```twig
 <link rel="canonical" href="{{ seomatic.meta.parsedValue('canonicalUrl') }}">
```

https://nystudio107.com/docs/seomatic/using/#seomatic-variables

**Comment by steveDL** [comment]
Thanks for your help here. I am still having issues as sometimes auto render is rendering $app_url do you have any idea why that might be?

Any sub-entry seems to render the $APP_URL by default instead of the rest of the entire URL. I have to override it add {{ entry.url }} but surely this should default to the entry full URL?

<img width="772" alt="Screenshot 2024-06-07 at 10 26 30" src="https://github.com/nystudio107/craft-seomatic/assets/8135124/91013c76-9052-4da4-bb23-8f7ceff6bae6">

**Comment by steveDL** [comment]
UPDATE: Just found this.. https://github.com/nystudio107/craft-seomatic/issues/822

**Comment by khalwat** [comment]
Glad you have it sorted
