### ISSUE TITLE
Every page throws Seomatic Errors

### ISSUE THREAD

**Issue by sergeifilippov** [nystudio107/craft-seomatic#148]
```
13:46:07.959 | error | nystudio107\seomatic\models\MetaTag::prepForRender | Meta tag `fb:app_id` did not render because it is missing attributes. Array (     [property] => fb:app_id )
-- | -- | -- | --
13:46:07.960 | error | nystudio107\seomatic\models\MetaTag::prepForRender | Meta tag `og:locale:alternate` did not render because it is missing attributes. Array (     [property] => og:locale:alternate )
13:46:07.967 | error | nystudio107\seomatic\models\MetaTag::prepForRender | Meta tag `og:image:alt` did not render because it is missing attributes. Array (     [property] => og:image:alt )
```

Every page I go to on the site throws the above in the Yii debug bad and the logs. If the content for `og:image:alt, og:image:alt, og:locale:alternate` are not specified, shouldn't the rendering of the elements be silent?

Any recommendations would be welcome. :)

**Comment by khalwat** [comment]
These aren't hard errors; they are shown only to let you know that something that could have rendered, didn't. So it's operating as designed.

**Comment by sergeifilippov** [comment]
Thanks @khalwat 

Is there a way to ignore them?

The reason I ask is these errors are being dumped into log files on each request in production mode. The client have not filled in this information (they well may never fill it out fully) but the logs are still being generated regardless.

**Comment by khalwat** [comment]
hmmmm. They should not be logged unless `devMode` is on. I'll have a look.

**Comment by sergeifilippov** [comment]
Let me know if you anything from me to help resolve this. 👍

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/51bef3aacbba826a19a4da5e71967710d932532f
