### ISSUE TITLE
Google Consent Mode v2 

### ISSUE THREAD

**Issue by DavidKabelitz** [nystudio107/craft-seomatic#1481]
Hi by EU law and regulations the Google Consent Mode v2 is needed. That also means that the Tag Manager Code needs to be adjusted. Will you change it by default?

**Comment by DavidKabelitz** [comment]
We can go around with it and use some Tag Manager Templates...thx :)

**Comment by khalwat** [comment]
Let me know the changes you made, and I can integrate them as default in SEOmatic.

**Comment by DavidKabelitz** [comment]
@khalwat That's what we used for Tag Manager and consent mode v2, but it's not always needed. Some cookie banner do work without.

`    <script type="text/javascript">
        // create dataLayer
        window.dataLayer = window.dataLayer || [];
        function gtag() {
            dataLayer.push(arguments);
        }

        // set „denied" as default for both ad and analytics storage, as well as ad_user_data and ad_personalization,
        gtag("consent", "default", {
            ad_user_data: "denied",
            ad_personalization: "denied",
            ad_storage: "denied",
            analytics_storage: "denied",
            wait_for_update: 2000 // milliseconds to wait for update
        });

        // Enable ads data redaction by default [optional]
        gtag("set", "ads_data_redaction", true);
    </script>

    <script type="text/javascript">
        // Google Tag Manager
        (function(w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s),
                dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-XXXXX'); //replace GTM-XXXXXX with Google Tag Manager ID
    </script>`

**Comment by MattAppleton** [comment]
Hello — I think this relates to this issue — wondering — what is a sensible way to implement cookie consent for gtag.js on a site running Blitz + SEOmatic?
