### ISSUE TITLE
Structured Data outputs SEO Title Source as site name

### ISSUE THREAD

**Issue by fishriver** [nystudio107/craft-seomatic#1482]
### Describe the bug
I have set a Site Name in the SEOmatic Site Settings and expect this value to be output in the WebSite structured Data as name. However, in my case the value of the field SEO Title Source is output instead.

```
{
  "@context": "http://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "name": "My input from the SEO Title Source field",
      …
```

### To reproduce
Steps to reproduce the behaviour:
1. Set a Site Name in the Site Settings of SEOmatic
2. Got to a page with Main Entity of Page set as "WebSite", set a SEO title (via SEO Title Source) different than the Site Name.
3. Inspect the structured data of that page.
4. The name property for the WebSite structured data shows whatever is set as SEO title.

### Expected behaviour
For the name property I expect the Site Name (set in Site Settings) to be output.

### Versions
- Plugin version: 5.0.3
- Craft version: Craft Pro 5.2.0

**Comment by khalwat** [comment]
This is working as expected. The `@webpage` `name` property is set to the title: https://github.com/nystudio107/craft-seomatic/blob/develop-v5/src/seomatic-config/globalmeta/JsonLdContainer.php#L33

The `@identity` `name` property is set to the Site Name: https://github.com/nystudio107/craft-seomatic/blob/develop-v5/src/seomatic-config/globalmeta/JsonLdContainer.php#L63

**Comment by fishriver** [comment]
Thank you for your fast response and sorry for calling it a bug. How do I provide the site name to Google as described in this [article](https://developers.google.com/search/docs/appearance/site-names)?

**Comment by khalwat** [comment]
Is it not picking it up already? Do you have a live site I can look at?

**Comment by fishriver** [comment]
I realized the issue was due to a misunderstanding on my part. Everything is working now. Thank you for your help!

**Comment by tibbis** [comment]
> I realized the issue was due to a misunderstanding on my part. Everything is working now. Thank you for your help!

I'm having the same problem where the homepage WebSite property "name" is set to SEOTitle instead of site name for google SERP name. What did you realize? 
My site: [https://comparesies.com/](https://comparesies.com/)

**Comment by khalwat** [comment]
Perhaps this helps? https://developers.google.com/search/docs/appearance/site-names

**Comment by tibbis** [comment]
> Perhaps this helps? https://developers.google.com/search/docs/appearance/site-names

exactly what I'm following and the "name" in JsonLd WebSite is wrong for me. So I could override it worst case but as a reference we check Nystodio107 homepage which has the same problem in my opinion:

<img width="1204" alt="Screenshot 2024-11-05 at 14 52 21" src="https://github.com/user-attachments/assets/1ebd318f-e16b-497c-be8b-f44316ed7504">

The `name` is set to _"Consulting, Branding, Design, Development"_ while the site name is:
`<meta content="nystudio107" property="og:site_name">`. According to the docs you need to set the home page's WebSite name to the site name for it to be displayed in SERP.

**Comment by khalwat** [comment]
The `name` in that context of the nystudio107 home page is the name of the MainEntityOfPage, which is a `WebPage`, so it makes sense that it would be set to the name of the page.

If the target object were `WebPage`, then I agree, it would make sense for it to be named "Nystudio107" instead.

**Comment by khalwat** [comment]
You make a good point, though, probably for the home page of nystudio107, the `MainEntityOfPage` should actually be `WebSite` rather than `WebPage`, with the name set as you mention to just the company name.

**Comment by tibbis** [comment]
Exactly! I will probably override the `name` of my homepage `WebSite` in my code. 

But I would suggest setting the `name` of `WebSite` to siteName if it's the root domain "homepage" as thats what google looks for in my understanding. 

Note that only one name per site is supported and:
> Not supported: https://example.com/news (this is a subdirectory-level home page)"

**Comment by khalwat** [comment]
So what it sets it to in the JSON-LD is the `seomatic.meta.seoTitle` so you could do:

```twig
{% do seomatic.meta.seoTitle('My Page Title') %}
```

Or you could just set it to what you want it to be in the homepage single's SEOmatic Content SEO settings.

**Comment by tibbis** [comment]
> So what it sets it to in the JSON-LD is the `seomatic.meta.seoTitle` so you could do:
> 
> ```
> {% do seomatic.meta.seoTitle('My Page Title') %}
> ```
> 
> Or you could just set it to what you want it to be in the homepage single's SEOmatic Content SEO settings.

Yes but I need to keep the title to something different than the siteName for the homepage as it tends to be different.

**Comment by khalwat** [comment]
So ideally, if the entry is the homepage, it would special-case it so that it would set the `name` of the `MainEntityOfPage` to be the `seomatic.site.siteName` instead, is that what you're proposing?

**Comment by tibbis** [comment]
> So ideally, if the entry is the homepage, it would special-case it so that it would set the `name` of the `MainEntityOfPage` to be the `seomatic.site.siteName` instead, is that what you're proposing?

Yes exactly!

**Comment by tibbis** [comment]
An you may also set `alternateName` as well as google has that as fall-back in the docs.

**Comment by khalwat** [comment]
Added it in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.6”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Since it sets both to: `seomatic.site.siteName` you can always change that via Twig if you want it something different from the name of the Craft site via:

```twig
{% do seomatic.site.siteName('my cool site name') %}
```

**Comment by khalwat** [comment]
Actually, I think you're right on this and I'm wrong. I think `name` should be set to `seomatic.site.identity.genericName` and `alternateName` should be set to `seomatic.site.identity.genericAlternateName`

I pushed the change, you can pull it down by doing:

```
composer clear-cache && composer update
```

...again. lmk!

**Comment by tibbis** [comment]
I think `name` should still be Site Name and not the legal entity name as google prefers that than the business names (xx .inc).

genericName is "The name of the entity that owns the site."

**Comment by khalwat** [comment]
Yeah I've reverted that based on your feedback. Do `composer clear-cache && composer update` to pull down the changes.

Really, I'm thinking we should add a "Site Alternate Name" field in Identity Settings at some point, but it's minor enough that it probably doesn't matter.

**Comment by khalwat** [comment]
Decided the time is now!

Added the **Site Alternate Name** property to Site Settings, used in the JSON-LD for the homepage, if the MainEntityOfPage is WebPage or WebSite

Do `composer clear-cache && composer update` to pull down the changes

**Comment by tibbis** [comment]
> Decided the time is now!
> 
> Added the **Site Alternate Name** property to Site Settings, used in the JSON-LD for the homepage, if the MainEntityOfPage is WebPage or WebSite
> 
> Do `composer clear-cache && composer update` to pull down the changes

Nice, effective! 👍
