### ISSUE TITLE
Not all sections for multisite showing in Content SEO

### ISSUE THREAD

**Issue by turnstylerj** [nystudio107/craft-seomatic#1485]
### Describe the bug
After adding a second site to my install and enabling all the sections for that site, SEOmatic's Content SEO section for that site is only showing 4 of the 6 sections. I have verified the sections are enabled and have entries on both sites.

![2024-06-25 at 16 23 55](https://github.com/nystudio107/craft-seomatic/assets/42223501/0b3e1b02-03bd-44f1-a000-a3b4609984b7)
![2024-06-25 at 16 24 39](https://github.com/nystudio107/craft-seomatic/assets/42223501/91768d1b-a1b3-4d80-bc49-1263ec22e74b)

### To reproduce
Steps to reproduce the behaviour:
1. Add a secondary site
2. Enable several sections for the new site

### Expected behaviour
All enabled sections are available in Content SEO for the second site

### Versions
- Plugin version: 5.0.4
- Craft version: 5.2.3

**Comment by khalwat** [comment]
They should become available once you've added content to the relevant sections. Let me know if you're not seeing that happen for you.

The meta bundles are created lazily as the sections are accessed, whether via the CP, or on the frontend.
