### ISSUE TITLE
Sitemap has not been generated yet

### ISSUE THREAD

**Issue by simajkeee** [nystudio107/craft-seomatic#1486]
### Question
We are experiencing an intermittent problem with sitemap generation. When the Ahrefs crawler tries to download sitemaps, it occasionally shows the error "Cannot download sitemap." When we try to load the sitemap pages in the browser, we encounter the message "Sitemap has not been generated yet." The sitemaps are not large, and it is a multilingual site. The problem can be reproduced for some sites. Plugin version 4.0.49.

### Additional context
Add any other context or screenshots about the support request here.

Seomatic sitemap settings
![seomatic](https://github.com/nystudio107/craft-seomatic/assets/37087698/fba8c284-2107-4639-893d-01feb926267a)

general.php
'runQueueAutomatically' => false,

in forge Daemons:
php craft queue/listen --verbose

Could you reccomend what can be done to fix the problem?

**Comment by khalwat** [comment]
I'm not sure why your sitemaps aren't being generated, they should be -- do you see any pending jobs?

Happy to help you solve this right now, but I'm also working on an update that will remove the need to use queue jobs to generate sitemaps, which should make things easier all around.

**Comment by simajkeee** [comment]
No, there are usually no pending jobs. Should we wait for the update you are working on instead of trying to solve it? Additionally, could you please let us know how long we might need to wait for the next update? Your guidance would be very helpful.

**Comment by khalwat** [comment]
If there are no pending jobs, what is likely is that the caches have been cleared, but the sitemaps haven't been regenerated yet. You can regenerate them manually using the CLI command:

```
./craft seomatic/sitemap/generate
```

https://nystudio107.com/docs/seomatic/configuring/content-seo.html#sitemap-generation

**Comment by simajkeee** [comment]
On our site, sitemaps are generated every night, but they still disappear. Additionally, we have set them to be generated after content updates, and they do not appear.

**Comment by khalwat** [comment]
SEOmatic 3.5.0, 4.1.0, and 5.1.0 (for Craft 3, 4, & 5 respectively) is out now. Give it a whirl!
