### ISSUE TITLE
How do I set custom Title and Description for 404 template

### ISSUE THREAD

**Issue by anstrx** [nystudio107/craft-seomatic#1487]
### Question
I tried 
` {% do seomatic.meta.seoTitle('some error title') %}` in my 404.twig file in the head section but the global seomatic title still shows up in the rendered 404 page. How do I override this?
### Additional context
Using latest version of Craft 3.x

**Comment by khalwat** [comment]
By default, SEOmatic does not render any metadata for `400`-class responses. This is because the metadata is largely for bots, which don't index 404 pages at all.

Probably you should just put the `<title>` in there yourself as you see fit.
