### ISSUE TITLE
Meta data for custom routes not working?

### ISSUE THREAD

**Issue by janhenckens** [nystudio107/craft-seomatic#1488]
### Describe the bug
We have a form with multiple steps, for which the routing is handled by a route and the template through a controller.

`$event->rules['<form:{slug}>/<step:\d{1}>'] = 'statik/lead/render-step';`

On the first step, which lives on the URL of an entry (`/client-defined-form-slug`,so the route doesn't apply there) , all meta data is displayed correctly

On step 2 (`/client-defined-form-slug/step2`), I'm trying set the metadata from the first step through `{% do seomatic.meta.seoTitle("My page title") %}` but that's not working.

Unsure how to proceed with debugging this so any advice you have would greatly help us along.
Thanks!

### Versions
- Plugin version: 4.10.2
- Craft version: 4.0.50

**Comment by khalwat** [comment]
For debugging, the SEOmatic debug toolbar panel can be very helpful:

https://nystudio107.com/docs/seomatic/advanced.html#debug-toolbar

For what you're trying to do for step 2, you can check out this section of the article and use `seomatic.helper.loadMetadataForUri()`:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#rendering-metadata-from-another-route

...or you can do what you're doing with `{% do seomatic.meta.seoTitle("My page title") %}` if you want to do it individually. Either should work, I'm not sure what "doesn't work" means, but it's possible you're running into caching issues?

Have a look here:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting

**Comment by janhenckens** [comment]
The debug toolbar isn't visible on that route - maybe that's part the issue?

"doens't work" referred to for example the title I'm trying to override like this

```twig
{% do seomatic.meta.seoTitle("My page title") %}
{% do seomatic.script.container().clearCache(true) %}
```

But that title isn't being added. I had the `clearCache()` method but that doesn't change anything in this case.

**Comment by khalwat** [comment]
Is it possible a non-200 result code is coming back from these pages?
