### ISSUE TITLE
Error while creating Sitemap

### ISSUE THREAD

**Issue by luke-nehemedia** [nystudio107/craft-seomatic#1489]
### Describe the bug
Since a couple of days the creation is sitemaps will fail for basically every section on the page. The error-massage is inserted below. 
I have no idea how I can investigate this further. Any ideas?

### To reproduce
Steps to reproduce the behaviour:
1. Edit a page
2. Click on save
3. See queue entry "Generating xyz sitemap"
4. See error message (see below)

### Expected behaviour
Just finishing creating the sitemap. 

### Screenshots

```
Query 1/1 - elements: 28
Processing element 1/28 - Page 1
...
Processing element 28/28 - Page28
Sitemap cache result: 1 for cache key: seomatic_sitemap_4sectiontextseite3
Exception 'yii\web\HeadersAlreadySentException' with message 'Headers already sent in /home/web1/craft4/vendor/nystudio107/craft-seomatic/src/helpers/Sitemap.php on line 113.'

in /home/web1/craft4/vendor/yiisoft/yii2/web/Response.php:369

Stack trace:
#0 /home/web1/craft4/vendor/yiisoft/yii2/web/Response.php(342): yii\web\Response→sendHeaders()
#1 /home/web1/craft4/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response→send()
#2 /home/web1/craft4/craft(14): yii\base\Application→run()
#3 {main}
```

### Versions
- Plugin version: 4.0.50
- Craft version: Craft Pro 4.10.4

**Comment by khalwat** [comment]
This probably isn't the actual error... basically something (probably some kind of error) has sent response headers back already.

Regardless, I've just released SEOmatic 4.1.0 which eliminates the queues for rendering sitemaps, give it a whirl!
