### ISSUE TITLE
Feature to hide a section under Content SEO

### ISSUE THREAD

**Issue by slebbo** [nystudio107/craft-seomatic#149]
This is not a real issue, and I'm sorry if I'm misusing this forum for feature wishes 😬.

Anyhow, I have some sections which don't any own urls and thus has no real use of seo-settings. 
Optimally, it would be great with the ability to hide sections like these from being listed in the Content SEO-tab in SEOmatic. Maybe with a lightswitch or something like that?

**Comment by khalwat** [comment]
It should automatically hide sections that don't have URLs. Are you finding that this isn't the case?

You have to turn URLs off for that section, though.

**Comment by khalwat** [comment]
This probably happened because the section had URLs at one point, but now no longer does. This was fixed in:

https://github.com/nystudio107/craft-seomatic/commit/bb88f9f6ce6c9b1e25efe9e1bc5519a96adea0ad

**Comment by slebbo** [comment]
Yes! 👍I can confirm that  SEOMatic 3.0.25  has this fixed. Thanks!
