### ISSUE TITLE
LinkedIn

### ISSUE THREAD

**Issue by paragonn** [nystudio107/craft-seomatic#1495]
### Is your feature request related to a problem? Please describe.
I have a client that uses LinkedIn primarily for their social SEO strategy. Currently, SEOMatic has views for Twitter and Facebook. Are there any plans to add LinkedIn?

### Describe the solution you would like
Add a view for LinkedIn.

### Describe alternatives you have considered
There are no alternatives.

### Additional context
Nothing to add.

**Comment by khalwat** [comment]
This already exists, go to SEOmatic -> Plugin Settings -> Appearance

<img width="976" alt="Screenshot 2024-07-17 at 11 00 56 AM" src="https://github.com/user-attachments/assets/bea92b42-5781-4b10-b1ec-43784b381932">


 It's really essentially the same as Facebook, and even uses the same metadata.

**Comment by paragonn** [comment]
Perfect -- thanks!

For some reason when I searched your documentation this detail didn't show up.
