### ISSUE TITLE
[Craft 4] Content SEO settings are not saved for the Craft Commerce 'product' type

### ISSUE THREAD

**Issue by Stalex89** [nystudio107/craft-seomatic#1499]
### Describe the bug

Changes for the Content SEO settings are not saved for the Craft Commerce 'product' type. All other entry types have no issue with saving changes. Neither error message appears in the console, nor endpoint failure received. Enclosing the video of the issue

Tried the following:

1. Clear all the cache
2. Disable all the plugins except Craft Commerce and SEOmatic
3. Resave product entries with `php craft resave/products` command
4. Duplicate the steps on the localhost server

Still the issue remains 
 
### To reproduce
Steps to reproduce the behaviour:
1. Install Craft Commerce, create some test product with the image
6. Go to "Content SEO" 
7. Click on item that has "product" type
8. Inside item settings, try to apply any changes and hit the "Save" button

### Expected behaviour
The changes are saved and reflected for the Craft Commerce 'product' type

### Versions
- Plugin version: 4.1.1
- Craft version: Craft Pro 4.11.3
- Commerce version: 4.6.8
- PHP version: 8.2.22
- Database: MySQL 49

https://github.com/user-attachments/assets/35813e94-f73e-4fab-a4e8-759bca3d5dd9

**Comment by khalwat** [comment]
I'm unable to reproduce this here, but I do note that you somehow have two products named "General" somehow listed in Content SEO. I think this might be causing the issue; go in to the `seomatic_metabundles` table and delete one of those two rows named "General" and see if that doesn't fix it.

**Comment by khalwat** [comment]
I made a change that effectively does the above for you:

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.3”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.3”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by Stalex89** [comment]
@khalwat the issue is resolved now, thank you very much! 🙂
