### ISSUE TITLE
Make robots.txt template setting a path instead of template textarea

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#15]
I would much rather see the `robots.txt` setting be simple a template path, so that we could keep this in source with all our other templates.

The only benefit I see of having it as a db-based setting is so non-developers could edit it, but it seems like that doesn't really happen.

**Comment by timkelty** [comment]
For that matter, I suppose you could just do away withe the Robots feature all together and just dump your example `robots.txt` template in the templates root dir.

I guess I don't see the benefit of it being part of the plugin (apart from providing an example templates/robots.txt content)

**Comment by khalwat** [comment]
So you can do this already, by altering the settings in the `FrontendTemplatesContainer.php` -- just set the path to whatever you want it to be on your setups, and it'll read the default template from there.

**Comment by timkelty** [comment]
👍 nice!
