### ISSUE TITLE
Content SEO > Image Source not remembered in entry page

### ISSUE THREAD

**Issue by marksimons** [nystudio107/craft-seomatic#150]
I set the Image source to my Asset field in Content SEO > SectionName > General > SEO Image Source. See below:

![screen shot 2018-06-22 at 10 02 34](https://user-images.githubusercontent.com/519951/41768347-ddb27cbc-7603-11e8-9e16-a90534e32f39.png)

But when I create a new entry in that section, the image source is set to "Custom Image" and not the Asset field I had selected in the Content SEO settings... See below: 

![screen shot 2018-06-22 at 10 07 20](https://user-images.githubusercontent.com/519951/41768450-27234282-7604-11e8-9b2e-194e8279d57a.png)

Actually, all of the field say Custom when in fact they have been preset in the Content SEO Settings.

Using latest version of Craft and SEOmatic

**Comment by khalwat** [comment]
So this is actually working as expected, I think I need to document it a bit better.

Basically, the overview looks like this:

Entry SEO > Content SEO > Global SEO

Meaning that it'll use the Entry SEO (if any) first, then the Content SEO, and then falling back on the Global SEO.

The intended behavior is that you'll use the SEO Settings field in the screenshot above when you want to _override_ the Content SEO that you set up in the first screenshot.

If you leave it blank, it falls back on the Content SEO Settings. If you put something in there, it'll override it.
