### ISSUE TITLE
og:type incorrect on homepage

### ISSUE THREAD

**Issue by smartpill** [nystudio107/craft-seomatic#1501]
### Question
I noticed our homepage has a `<meta content=“article” property=“og:type”>`  vs `<meta content=“website” property=“og:type”>` metatag. Could you direct me to where in SEOMatic that setting might be?

### Additional context
We have issues with entries that are on our homepage appearing in search results on Google with the site name and site description vs the article title and description. Site is [https:newhavenindependent.org](https:newhavenindependent.org)

**Comment by khalwat** [comment]
You set that setting in SEOmatic -> Content SEO -> (section) -> Facebook -> **Facebook OpenGraph Type**

Note that I don't think this will have anything to do with what you mentioned under "additional context"
