### ISSUE TITLE
Set SEO image to image field in a matrix.

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#1503]
craft 5.3.4
SEOmatic 5.1.2

### Question
I'm setting up content SEO on a new Craft 5 build -with content imported via feedme from a Craft 2 site. and I need to set the SEO Image source for SEOmatic to a image field in a matrix. How do I do that? Is this possible?

There will only ever be one matrix block with one image.

![image](https://github.com/user-attachments/assets/5855c07b-cbe4-4c62-b3d8-ee2240771ddd)

![image](https://github.com/user-attachments/assets/74c2ec34-dfe3-4181-929b-d150a20524bf)

### Additional context
Add any other context or screenshots about the support request here.

**Comment by khalwat** [comment]
Currently it's not possible to do this other than using custom Twig to do it, something roughly like:

```twig
{{ entry.myMatrix.one().assetfield.one().getUrl() }}
```

**Comment by CreateSean** [comment]
Two things,

I am unable to get that to work using:

`{{ entry.hero.one().collectionImaage.one().getUrl() }}`

second, when making changes to one entry type in the same section, the settings duplicate over to all other entry types.

So in the pages Channel I have entry type of Contact page and Our Team, I tried to set different options in the image setting but it whatever was saved last is applied to all entry types.

**Comment by khalwat** [comment]
Get it working in the page template for that section, and then paste the working code into the SEOmatic setting.

As for the entry types, you should be able to set settings on a per-entry type basis. There's a menu that lets you choose the entry type you're saving settings for.

**Comment by CreateSean** [comment]
weird that the entry types wasn't working yesterday but is today.

Have got this working in front end template `{{ entry.hero.one().collectionImage.one().url }}` but doesn't work in the SEOmatic settings

**Comment by CreateSean** [comment]
Additionally, I set up another section that has a dedicated image field - this is not being used as the SEO image as expected.

**Comment by khalwat** [comment]
Have you tried using the SEOmatic debug toolbar panel to see what the values look like for the variables on that page?

https://nystudio107.com/docs/seomatic/advanced.html#debug-toolbar

As for your second comment, can you give me more context? You're saying that pulling the image from a dedicated field is not working? Can you show screenshots of your SEOmatic settings?

Also did you set up the Global SEO settings to have a fallback image?

Is there an SEO Settings field that could be overriding things here?

**Comment by CreateSean** [comment]
So when I updated the global SEO image setting everything started working.

sorry for the hassle

**Comment by khalwat** [comment]
That sounds like a bug that I should address, though
