### ISSUE TITLE
hreflang in sitemaps.xml does not respect site groups

### ISSUE THREAD

**Issue by Megafry** [nystudio107/craft-seomatic#1505]
### Describe the bug
I have a project with 2 site groups, the main one has only one language.
Despite this, the hreflang-attribute is present in the sitemaps.xml

### To reproduce
1. create a project with 2 site groups (main, landingpage)
2. create 3 sites ( default DE, Landingpage DE, landingpage EN)
3. create a new section for blog 
4. create a blog entry 
5. check the sitemap for blog (default DE)

### Expected behaviour
The sitemap does not need to contain the hreflang attribute if the entry originates from a site group with only one site/language.

### Screenshots
![image](https://github.com/user-attachments/assets/2e52bbde-3967-4252-b439-de8ce1e35cd9)
![image](https://github.com/user-attachments/assets/d9452976-26f5-423c-92ac-01e934189142)

### Versions
- Plugin version: 4.1.2
- Craft version: 4.11.3

**Comment by khalwat** [comment]
You need to use site groups to tell SEOmatic how the various sites are related to each other.

Check out this section of the documentation:

https://nystudio107.com/docs/seomatic/multi-site.html#multi-site-language-locale-support
