### ISSUE TITLE
Og:url differs from canonical url (adds trailing slash)

### ISSUE THREAD

**Issue by mofman** [nystudio107/craft-seomatic#1507]
The og:url seems to differ from the canonical url and instead adds a trailing slash?

eg. 

`<meta content="https://www.mahlatini.com/us/" property="og:url">`

`<link href="https://www.mahlatini.com/us" rel="canonical">`

### Screenshots
<img width="684" alt="Screenshot 2024-09-03 at 11 18 20" src="https://github.com/user-attachments/assets/38904ff4-9492-4f19-b8c8-4cf616263be1">

### Versions
- Plugin version: 4.1.2
- Craft version: Craft CMS 4.11.5

**Comment by khalwat** [comment]
Can you show me your settings in SEOmatic for both the `og:url` and the `canonical url`?

**Comment by mofman** [comment]
Ah its actually an issue with craft

https://github.com/craftcms/cms/issues/5675

The work arround is:

```
{% set currentUrl = entry.url|trim('/', 'right') %}

{% do seomatic.meta.canonicalUrl(currentUrl) %}
```
