### ISSUE TITLE
My robots.txt files is showing a 404 not found, however I see it when I type in the url?

### ISSUE THREAD

**Issue by djamieson33** [nystudio107/craft-seomatic#1508]
### Describe the bug
I have two Craft websites with Seomatic and neither of them appear to be found properly by my seo tools when I run reports. When I am in Google Search Console it says there is no robots.txt file. Also, with SeoQuake plugin it says no robots.txt file found and as well, my Semrush reports keep saying 404 error. Finally, when I go to the page, the Inspect > Network tab in Google chrome also says 404.

### To reproduce
Steps to reproduce the behaviour:
1. Go to [www.dwaynejamieson.com/robots.txt](https://www.dwaynejamieson.com/robots.txt) and you can clearly see the file.
2. Also, go to [www.ucbradio.com/robots.txt](https://www.ucbradio.com/robots.txt) and the file is also there, but again displaying a 404 error.

### Expected behaviour
I expect Google, Semrush and the SEOQuake tool to see my robots.txt file on these sites.

### Screenshots

<img width="1424" alt="Screenshot 2024-09-05 at 11 07 15" src="https://github.com/user-attachments/assets/623d06f8-a97a-4efe-b96b-83c0548e2fcd">

### Versions
- Plugin version: 4.1.2
- Craft version: Happens on Version 4 website and my new Craft 5 website.

Any help is appreciated.

Dwayne

**Comment by djamieson33** [comment]
More information now as I'm digging into this:

## This is the same error on the second site:

<img width="934" alt="Screenshot 2024-09-05 at 11 38 58" src="https://github.com/user-attachments/assets/17428b4f-4d8a-44f1-ba9f-9113e249a68e">


## However, I don't get the 404 error if i put in my domain name followed by: /index.php?p=robots.txt. This appears to give a 200 status:

<img width="938" alt="Screenshot 2024-09-05 at 11 40 31" src="https://github.com/user-attachments/assets/d5923ac8-bd49-4e76-a3a3-4028fd0b3f3e">

I'm now investigating if this is related to my nginx setup.

Thanks in advance for any help given,
Dwayne

**Comment by khalwat** [comment]
These both are going to be some kind of a webserver configuration error, not an SEOmatic error. 404s should be routed through Craft, do you have that set up in your webserver config?

**Comment by djamieson33** [comment]
I'l check on that. Thanks for the quick response.

**Comment by djamieson33** [comment]
I'm using Ploi.io for the server config so I will need to look into that, I suppose.

**Comment by khalwat** [comment]
Yep. I'll close out the issue, because I'm 99% sure it's going to be a webserver config issue, but happy to still help you with it if you post here.

**Comment by djamieson33** [comment]
Do you mean that I need to:

- edit the file /public/web.config?
- Or something in my nginx config? 

What I know is:

- https://www.ucbradio.com/robots.txt shows content but generates a 404 error 
- If the url path is: /index.php?p=robots.txt I get a 200 response

I'm browsing your [nginx-craft/sites-available/](https://github.com/nystudio107/nginx-craft/tree/master/sites-available) files for ideas.

I'm still digging to solve this.

**Comment by khalwat** [comment]
Looks like with Ploi you can go to Manage > Configuration Files > NGINX configuration

This article may help: 

https://serverfault.com/questions/735706/getting-404-on-any-text-file-including-robots-txt-with-nginx

Also Ploi has excellent support, including a Discord channel in which you can ask support questions.

**Comment by djamieson33** [comment]
Than you Andrew! I was able to resolve it by removing this line from one of the nginx files. 

> location = /robots.txt  { access_log off; log_not_found off; }

Once I removed that line then I got my 200 response.

Thanks for your responses and your help. Love the plugin.

Dwayne

**Comment by khalwat** [comment]
Ah yes, that makes sense. Sorry, I should have thought of that sooner, it's mentioned here:

https://nystudio107.com/docs/seomatic/configuring/global-seo.html#troubleshooting

Glad you got it sorted.

**Comment by russback** [comment]
For anybody managing Craft sites using Laravel Forge, that line is part of the default nginx config Forge uses when creating a site, so you'll need to remove it, or create a custom nginx template from which to create each new site you host.
