### ISSUE TITLE
Old section appears as clone of current section

### ISSUE THREAD

**Issue by ishetnogferre** [nystudio107/craft-seomatic#1509]
### Describe the bug
Sometimes we have a section that appears two times in the overview, which leads to the same section. It also gets generated twice in the sitemaps
![Screenshot 2024-09-10 at 09 59 37](https://github.com/user-attachments/assets/905d1cc5-d2d5-4a66-b8bf-c6ee8a45d437)

We found out it sometimes happens when we have a new section that uses (almost all) the same data as a previously deleted one.
So the one with ID 10 has been deleted in the past and the one with ID 14 is the current one. Only difference we see right now is the template.
<img width="1002" alt="Screenshot 2024-09-10 at 09 56 39" src="https://github.com/user-attachments/assets/8285ccc2-6f2b-4cc7-9fbf-98cc45043090">
<img width="1368" alt="Screenshot 2024-09-10 at 09 57 24" src="https://github.com/user-attachments/assets/b49b5527-f711-4c99-8dbf-0da683eae144">

### To reproduce
Steps to reproduce the behaviour:
1. Add a new section
2. Delete this section
3. Re-add the section with same information
4. Check SEOMatic overview and sitemaps

### Expected behaviour
Only the new section should appear, not the "old" one as well.

### Versions
- Plugin version: 5.1.2
- Craft version: Craft Pro 5.4.0.1

**Comment by khalwat** [comment]
You're positive that you're using version 5.1.2 when reproducing this? There should be code in there that will prune the old outdated metabundles table.

**Comment by khalwat** [comment]
My bad -- this was actually fixed in 5.1.3, I just haven't released it yet. Will do shortly.

**Comment by khalwat** [comment]
Released -> https://github.com/nystudio107/craft-seomatic/releases
