### ISSUE TITLE
Validation error when trying to change Content SEO setting

### ISSUE THREAD

**Issue by agosman** [nystudio107/craft-seomatic#1510]
### Describe the bug
Trying to update the Content SEO setting `SEO Image Source` to `From asset field` results in the following error being logged, while the CP just shows a message that the settings have been saved:

```
[web.ERROR] [nystudio107\seomatic\services\MetaBundles::updateMetaBundle] Meta bundle failed validation: Array
(
    [typeId] => Array
        (
            [0] => Type Id must be no less than 1.
        )
)
type: single id: 4 from siteId: 1
```
 
### To reproduce
Steps to reproduce the behaviour:
1. Go to `SEOmatic / Content SEO / General`.
2. Click on the structure I want to change the settings for.
3. Change `SEO Image Source field` to `From asset field` and click `Save`.
4. See error message in the console, new setting is not being applied.

### Expected behaviour
The new setting to be applied.

### Versions
- Plugin version: 4.1.2
- Craft version: 4.12.1

**Comment by khalwat** [comment]
What is the section that the Content SEO is associated with when you're trying to save these settings?

**Comment by khalwat** [comment]
Released -> https://github.com/nystudio107/craft-seomatic/releases

**Comment by agosman** [comment]
Thanks!
