### ISSUE TITLE
Code meant to strip overlap, strips too much of the absolute url

### ISSUE THREAD

**Issue by euismod2336** [nystudio107/craft-seomatic#1512]
### Describe the bug
UrlHelper::mergeUrlWithPath removes too much when combining the parts back together again. Depending on your siteUrl it might strip different things. The TLD of your siteUrl is stripped of the beginning of the path. Related to https://github.com/nystudio107/craft-seomatic/issues/1376 This seems to only happen on the beginning of the path.

I thought about creating a PR but given there are several working solutions in the challenge, the point seemed moot :wink: 
https://www.craftcodingchallenge.com/challenge-14-testing-santas-patience/

### To reproduce
Steps to reproduce the behaviour:
1. Configure your siteUrl to end on `.com`
2. Create an entry with uri that starts with `commanding` or `modern` (or just overwrite the path value in the helper function)
3. Create sitemap via CLI

### Expected behaviour
I would expect the resulting url to be [siteUrl]/commanding or [siteUrl]/modern and not [siteUrl]/manding and [siteUrl]/odern

### Versions
- Plugin version: 4.1.3
- Craft version: 4.10.2

![image](https://github.com/user-attachments/assets/38f42f1d-a1da-444d-8a6a-d92abf1c84e6)

**Comment by khalwat** [comment]
Yeah the algorithm is fine, the path and URL just needed to be normalized first.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.4”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.4”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.4”,
```
Then do a `composer clear-cache && composer update`
