### ISSUE TITLE
Feedme fields incorrect

### ISSUE THREAD

**Issue by SayChi** [nystudio107/craft-seomatic#1520]
### Describe the bug
Using feedme to set seomatic fields is only partially working. It looks like there's some fields that it's trying to store in the `MetaGlobalVars` model instead of `MetaBundleSettings` model (and there's one that seems to just have a typo)

This is the list of fields:
- ogImageIds
- ogImageSource
- seoImageField
- seoImageIds
- seoImageSource
- togImageField
- twitterImageField
- twitterImageIds
- twitterImageSource

In twig these are described as properties of `metaGlobalVars`: templates/_includes/integrations/feedme/seo-settings.twig:53\
But in reality they are not in `models/MetaGlobalVars.php` but in `models/MetaBundleSettings.php`

And `togImageField` seems to be a typo of `ogImageField`

I haven't tested all of these fields, but I ran into it while setting `seoImageSource` and `seoImageField`

### To reproduce
Steps to reproduce the behaviour:
1. Create a feedme feed for a section that has a seomatic field
2. Set `seo[metaGlobalVars][seoImageField]` to 'Use default value' and 'From Asset Field'
3. Set `seo[metaGlobalVars][seoImageIds]` to 'Use default value' and the handle of another field
4. Run the import

### Expected behaviour
These fields get set in the entry

### Screenshots
![image](https://github.com/user-attachments/assets/5280eb4d-224f-4991-9fb0-38b91c96c5d8)

### Versions
- Plugin version: 4.1.4
- Craft version: 4.12.5

Can't confirm these problems existing in newer versions, but I can confirm the typo is still in the twig file as well as the config still describing those fields being part of `metaGlobalVars`

**Comment by khalwat** [comment]
Looking at it from the error message, though, it looks like it's trying to set the _field_ `seoImageField` on the `MetaGlobalVars` object, whereas the `seoImageField` exists in the `MetaBundleSettings` object

**Comment by khalwat** [comment]
Addressed in the above commits

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.5”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.5”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.5”,
```
Then do a `composer clear-cache && composer update`
