### ISSUE TITLE
GMT ID not rendering on second site in multi-site setup

### ISSUE THREAD

**Issue by paulwaddington** [nystudio107/craft-seomatic#1523]
### Question
Hi there! We've just converted an existing site to run a second site as a multi-site. The original site reders the GTM tracking code correctly, though even though the second site renders all of the meta data, it doesn't render the GTM ID

### Additional context
The existing site was www.hn-company.co.uk and the second site is www.hnclinical.com
Both sites are using Cloudflare, though I've been through and cleared SEOmatic template caches and also Cloudflare caches.

**Comment by khalwat** [comment]
SEOmatic stores its settings on a per-site basis. Make sure you set the settings as you want them for the new site:

<img width="668" alt="Screenshot 2024-10-14 at 1 59 32 PM" src="https://github.com/user-attachments/assets/26708de5-0afb-4838-99dd-b9cdeca75421">

**Comment by paulwaddington** [comment]
Hi Andrew,

Thank you for your reply… though the settings are site specific.




Paul Waddington

DDME
6 Harley Head Avenue, Halifax, HX3 8FD

M: 07870 651 374

https://www.ddme.uk <https://www.ddme.uk/>

**Comment by khalwat** [comment]
Can you show me screenshots from both site settings for GTM settings in SEOmatic for Tracking Scripts?

**Comment by paulwaddington** [comment]
Here you go Andrew…







Paul Waddington

DDME
6 Harley Head Avenue, Halifax, HX3 8FD

M: 07870 651 374

https://www.ddme.uk <https://www.ddme.uk/>

**Comment by khalwat** [comment]
@paulwaddington I'm not seeing any screenshots attached here?

**Comment by paulwaddington** [comment]
![gtm-hn-patient](https://github.com/user-attachments/assets/fae41ec8-3127-4cda-bfe0-5ff92b580baf)
![gtm-hn-company](https://github.com/user-attachments/assets/6aa5e0de-eb04-4533-8db8-3764b77c9935)

**Comment by paulwaddington** [comment]
Hi @khalwat, have you been able to review the acreen grabs?

**Comment by khalwat** [comment]
Okay so to test this, I have a two-site setup. Here are my settings for the first site:

<img width="866" alt="Screenshot 2024-11-04 at 18 25 24" src="https://github.com/user-attachments/assets/58e91b26-0fa4-4338-8bf5-0fe6c63d330f">

This is what SEOmatic outputs when I view the source of the first site:

```html
<script>dataLayer = [];
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','MY-FIRST-SITE');
</script>
```

...and here are my settings for the second site:

<img width="866" alt="Screenshot 2024-11-04 at 18 26 57" src="https://github.com/user-attachments/assets/c9db98cb-a531-4297-8e6b-77bce9f2332d">

This is what SEOmatic outputs when I view the source of the second site:

```html
<script>dataLayer = [];
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','MY-SECOND-SITE');
</script>
```

So it's definitely rendering a different ID for each site. 

Is there anything else that could be going wrong here? Could the GTM code you're seeing on your site be coming from anywhere else?
