### ISSUE TITLE
SEOmatic Not Processing Images 

### ISSUE THREAD

**Issue by viesrood** [nystudio107/craft-seomatic#1524]
Hello,

I’m encountering an issue where SEOmatic doesn’t convert images. To scale images, I use Image X in combination with imgix on my website, and I’m not sure if this affects SEOmatic.

URLs appear in the metadata like this: ‘/actions/assets/generate-transform?transformId’

Oddly enough, the same website works fine within my DDEV environment.

I’ve cleared all caches by now, but that hasn’t had any effect.
Could you give me some advice on how to solve this?

Best,
Jef

**Comment by khalwat** [comment]
Is there a setting in Imager X to do the transforms before page load?

Are you static caching the resulting HTML or something using Blitz or some other static caching method?

**Comment by viesrood** [comment]
A few paths were incorrect in my .env file. It wasn't related to Imager-x. The issue has been resolved.
