### ISSUE TITLE
Structured data issue - Breadcrumbs: Either 'name' or 'item.name' should be specified

### ISSUE THREAD

**Issue by robzor** [nystudio107/craft-seomatic#1525]
### Question
Hi there, the agency I am working with has run an "SEO report" on the latest site we built and it is coming back with this issue:

> "Structured data issue - 32 key pages found with invalid structured data. A value for the item name or name field is required to optimise data markup."

The suggested action is this:

> Action: Add item.name "home" to the URL id for https://www.senselearning.co.uk
`"@type": "ListItem", "position": 1, "name": "Home", "item": "https://www.senselearning.co.uk"`

Have I missed something in the config? If I run the Google Rich Results test on one of the 32 pages, for example: https://www.senselearning.co.uk/about-sense it says there a critical issue here:

![CleanShot 2024-10-16 at 4  13 12](https://github.com/user-attachments/assets/ddfc5b8c-8eb9-408f-a04b-358c2b9ea4ae)

Any help would be greatly appreciated!

### Additional context
Running Craft 5.4.5.1, 
SEOMatic 5.1.3
Navigation 3.0.4 (just in case that is affecting it!)

**Comment by robzor** [comment]
Ok, I think I might have rubber ducked this one:

In the 'Homepage' Entry Type I had the Title Field hidden, along with the Title Format field **left blank**. I have now changed that to 'Home' and that seems to have sorted it, will do some more testing to confirm!

![CleanShot 2024-10-16 at 4  23 39](https://github.com/user-attachments/assets/5345e8ee-8f6f-4469-9a07-25ba66c667f1)

**Comment by khalwat** [comment]
You got it :)
