### ISSUE TITLE
Slow queries for each page with large amount of section entries.

### ISSUE THREAD

**Issue by jodeba** [nystudio107/craft-seomatic#1526]
### Describe the bug
On a detail page of an Entry, Seomatic is always querying the [mostRecentElement](https://github.com/nystudio107/craft-seomatic/blob/629a637d11dc6c6134bdcd5dec6ec5ecc1d2540a/src/services/MetaBundles.php#L372). This query can be very slow (due to the ORDER BY) when you have a lot of Entries for that Section. In my case ~800ms with ~100000 entries. In the profiling, I even see this query happens twice.

![image](https://github.com/user-attachments/assets/20b22b3a-90f3-4ace-aff9-e01c864495b5)

But when I check the usage of the result, the last updated date is only used when building the sitemap. So is this necessary to query this every time?

It does not help to create extra indexes on the database.

### To reproduce
Steps to reproduce the behaviour:
1. Section with 100000 rows
2. Visit detailpage of entry

### Expected behaviour
No query of mostRecentElement on detail page

### Versions
- Plugin version: 4.1.5
- Craft version: 4.10.8

**Comment by khalwat** [comment]
Addressed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.6”,
```
Then do a `composer clear-cache && composer update`

**Comment by jodeba** [comment]
Hi @khalwat , thank you for the quick response, but I've got an error now:

Undefined variable $metaBundleDefaults
in /var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php at line 414

**Comment by khalwat** [comment]
Fixed, sorry about that. You can do a `composer clear-cache && composer update` again and it will pull the fix down.

**Comment by jodeba** [comment]
Thanks, the pages load a lot quicker!
I'll wait for the release to push it to production.
