### ISSUE TITLE
Intermittent Issue with <title> Tag Showing GENERAL_SYSTEM_NAME

### ISSUE THREAD

**Issue by romainpoirier** [nystudio107/craft-seomatic#1529]
### Describe the bug
Occasionally, the `<title>` tag in SEOmatic is not generated correctly and instead displays `GENERAL_SYSTEM_NAME`. However, the issue seems to resolve itself upon refreshing the page, though I have not been able to consistently reproduce the behavior. This issue has been noticed specifically when sharing the URL on social media.

Resaving the page via `/admin/seomatic/global/general` in the Control Panel does not fix the issue.

It's worth noting that I have sometimes used the "Copy Settings From" functionality from another site before resaving.

### To reproduce
1. Use the "Copy Settings From" feature to copy SEOmatic settings from another site.
2. Go to the specific page in the frontend and check the `<title>` tag.
3. Share the URL on social media to observe the title issue.
4. The `<title>` tag may show `GENERAL_SYSTEM_NAME`.

### Expected behaviour
The `<title>` tag should always reflect the correct SEO title set in SEOmatic without intermittently showing `GENERAL_SYSTEM_NAME`.

### Versions
- Plugin version: 5.1.5
- Craft CMS version: 5.4.9

**Comment by khalwat** [comment]
This is probably not an SEOmatic issue.

What is `GENERAL_SYSTEM_NAME` and where is it coming from?

**Comment by romainpoirier** [comment]
I think that this is coming from SEO Title Source (`/admin/seomatic/global/general`):
<img width="828" alt="Capture d’écran 2024-10-29 à 15 54 30" src="https://github.com/user-attachments/assets/a1513806-37c2-4850-9ba0-b34f9c65a499">

**Comment by khalwat** [comment]
Right, but where is that environment variable being set?

I'm not sure SEOmatic is going to parse that environment variable there. Or at the least, if it is combined with other text, it will not parse.

I'd suggest just putting text in there, or if you really want, you can put Twig in there that outputs the $GENERAL_SYSTEM_NAME environment variable via something like:

```twig
{{ getenv('GENERAL_SYSTEM_NAME') }}
```

https://craftcms.com/docs/5.x/reference/twig/functions.html#getenv

**Comment by romainpoirier** [comment]
> Right, but where is that environment variable being set?

It is, of course, defined and located in the `.env` file: `GENERAL_SYSTEM_NAME="My Website"`

> I'm not sure SEOmatic is going to parse that environment variable there.

So why does the field offer autocomplete?

<img width="824" alt="Capture d’écran 2024-10-29 à 17 26 52" src="https://github.com/user-attachments/assets/b5cc92e0-f07a-4628-9a71-0bc866069450">

**Comment by khalwat** [comment]
If you use the title source _alone_ it will work. But if you then combine a site name or other text to it, it won't parse properly. You can try an alias, or you can try the code I mentioned above.
