### ISSUE TITLE
Remove hreflang

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#153]
Any way to do this?

**Comment by khalwat** [comment]
Yep, sure, you can do it if you like (tho unless there's a really good reason to do so, it's probably best to leave it in).

You can do something like this:

```twig
{% do seomatic.link.get('alternate').include(false) %}
```

This works for any kind of tag in SEOmatic, as per:

https://github.com/nystudio107/craft-seomatic#twig-templating

**Comment by XhmikosR** [comment]
I was wondering @khalwat, should the tag be even included when there are no other languages?
