### ISSUE TITLE
Robots Disallow on a specific entry

### ISSUE THREAD

**Issue by airidasbrikas23** [nystudio107/craft-seomatic#1531]
### Question
There is an SEO field `robotsDisallow` that I put as a field to my entries in a a few sections, how can I utilize this field in modifying whether the page is indexed my search engines or not?

### Additional context
In SEOmatic > Content SEO > [Section name] General, Robots part allows to select how the whole section is treated, but I want to treat specific entries it it diffrentely - I want to noindex them.

**Comment by khalwat** [comment]
Instead, you should use an SEOmatic Settings field, and set it up such that the only field it shows is "Robots"

Then everything will "just work", including sitemaps.
