### ISSUE TITLE
Sitemap generation error referencing the Putyourlightson Campaign plugin

### ISSUE THREAD

**Issue by johnwbaxter** [nystudio107/craft-seomatic#1532]
### Describe the bug
There is a failed task for when SEOMatic tried to create a sitemap.

The error is: Getting unknown property: putyourlightson\campaign\elements\CampaignElement::section

{
    "description": null,
    "groupId": 1,
    "type": "campaign",
    "handle": "standard",
    "siteId": 1,
    "queueJobCacheKey": "seomatic_sitemap_queue_job_1campaignstandard1"
}

### Versions
- Plugin version: "nystudio107/craft-seomatic": "4.0.48",
- Craft version: "craftcms/cms": "4.7.4",

**Comment by khalwat** [comment]
Please update to the latest version of SEOmatic, it no longer uses queue jobs to generate sitemaps.

**Comment by johnwbaxter** [comment]
Oooh, ok, thank you sir!!
