### ISSUE TITLE
Fix presentation for Content SEO and select dropdown for Entry Types

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#1534]
### Describe the bug
The navigation dropdown for selecting Entry Types within the Content SEO panel is slightly broken.
See screenshot.

<img width="659" alt="Screenshot 2024-11-07 at 09 36 13" src="https://github.com/user-attachments/assets/beca9422-c825-4df7-9414-2bb6ad5b621d">

<img width="832" alt="Screenshot 2024-11-07 at 09 40 16" src="https://github.com/user-attachments/assets/053e64e3-5522-46d1-8d01-2d618bd2116a">

### Versions
- Plugin version: 5.1.5
- Craft version: Craft Pro 5.4.10

**Comment by khalwat** [comment]
Already fixed.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.6”,
```
Then do a `composer clear-cache && composer update`
