### ISSUE TITLE
Content SEO - Entry Type to pull through the data for each individual entry type to make content modelling easier for each individual type

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#1535]
It would be a nice nicer and easier experience when modelling Content SEO if when you change the Entry Type that the data is pulled through for the first entry that uses that entry type within that section. 

At the moment it just defaults to the first entry and uses that data regardless of what Entry Type you are modelling the SEO for.

This is difficult especially if the entry type doesn't have fields of the first entry type s the preview does not reflect that of the data for the Entry Type.

With the new Craft 5 approach I would argue this is essential for visual data modelling. 

**Some caveats that might need consideration and discussion.**

_**What if a section has an Entry Type but there are no entries using this? 
How can we illustrate if there is no data to pull from?**_

Could we pull this from another section if the entry type is used elsewhere?
1. Pull from an entry that uses that type in this section.
2. If 1 doesn't exist then pull from any entry that type across the site (the data modelling should be the same?)
3. If 2 doesn't exist then perhaps in this instance, it would be applicable to fall back to the first entry type? It might be prudent to show a notice to explain there is no entry that uses this type in this section. 

I'd argue that if you have created an entry type then somewhere it will be used in that section or in the site. 
So 3 shouldn't be necessary. 

Here are some examples.
I have a section called Technical Resources.
This section has 3 entry types;
- Technical Resource (General)
- Dimension Drawing
- Compliance Document

I have a section called Products (technical pages/entries data not commerce).
This section has 4 entry types;
- Product RCT
- Product CWT
- Product Collection
- Product Quote

Each type has some very specific fields and some are quite different from each other.
I'd like to see these reflected on the previews when modelling the content in the Content SEO settings.

@khalwat  - happy to open a discussion about this.
As mentioned, I feel this is important for the new direction of Craft from V5 and would be great to hear your ideas and thoughts.

Thanks for your time.

**Comment by khalwat** [comment]
Implemented in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.6”,
```
Then do a `composer clear-cache && composer update`
