### ISSUE TITLE
Extending Tracking Scripts

### ISSUE THREAD

**Issue by cbovers** [nystudio107/craft-seomatic#1536]
Hello 👋 

We would like to be able to add Tracking Scripts, e.g. Microsoft Clarity or CookieYes.
Is there a way that we can plug into the plugin, with our own, to add Tracking Scripts perhaps?

Kind regards,
Chris

**Comment by khalwat** [comment]
Yes, you can add your own if you like via the seomatic-config setup. This article has some details:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#customized-setup
