### ISSUE TITLE
Schema validation error on `founder` and `foundingLocation`

### ISSUE THREAD

**Issue by russback** [nystudio107/craft-seomatic#1537]
We are using the ahrefs.com site auditor and it's throwing up validation errors on https://ournameismud.co.uk/, specifically for `founder` and `foundingLocation`, both of which are just strings from the plugin settings.

What's odd is that when running through different online validators, it's not flagged as an issue. So when checking ahrefs support, they pointed out that the validators do not always follow specifications and therefore results may vary and have [this content online](https://help.ahrefs.com/en/articles/8223239-how-to-monitor-structured-data-issues-in-site-audit) to explain that.

Looking at the schema.org documentation for `founder`, `Person` [is expected](https://schema.org/founder) rather than a string, and for `foundingLocation`, `Place` [is expected](https://schema.org/foundingLocation).

Interested to hear thoughts on this and whether it's something that might be updated in a future SEOmatic version, if it needs a workaround in twig, or if it's not a concern given that popular validators appear to be be less strict compared to the schema.org spec.

**Comment by tibbis** [comment]
was just about to post this issue as well! Same issue with ahref:

1. Value of unexpected type for [`founder`](https://schema.org/founder). Expected types: [`Person`](https://schema.org/Person).
2. Value of unexpected type for [`foundingLocation`](https://schema.org/foundingLocation). Expected types: [`Place`](https://schema.org/Place).

**Comment by khalwat** [comment]
You're doing this largely for Google to consume your data for rich results, so I suggest using the Rich Results testing tool:

https://search.google.com/test/rich-results

For schema validation, use:

https://validator.schema.org/

...but understand that the answer really is that it doesn't matter.

I'm happy to make changes in SEOmatic as things change, so feel free to post any concerns you find.

I ran both tests on your site, with zero errors, and Rich Results being found:

https://validator.schema.org/#url=https%3A%2F%2Fournameismud.co.uk%2F

https://search.google.com/test/rich-results/result?id=pcS-FGOfuPalaH5CP8HdZQ
