### ISSUE TITLE
When Google Tag Manager and Google gtag.js are both enabled, an extra script opening tag gets injected into the body

### ISSUE THREAD

**Issue by mei-lu** [nystudio107/craft-seomatic#1538]
### Describe the bug
When Google Tag Manager and Google gtag.js are both enabled, an extra script opening tag gets injected.
When Google Tag Manager is disabled however, the issue goes away.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Tracking Scripts
2. Enable Google Tag Manager and Google gtag.js
3. On web page, parts of the script get injected into the beginning of `<body>` and an extra `<script>` tag is inserted that remains unclosed.
<img width="226" alt="image" src="https://github.com/user-attachments/assets/c6e5aa76-9296-4d73-8cc8-599ef789ff5b">
<img width="656" alt="image" src="https://github.com/user-attachments/assets/69916f8b-c303-4cf1-9113-d48d0778a465">
<img width="672" alt="image" src="https://github.com/user-attachments/assets/f44d6d0a-60a0-47c2-8e77-a9ab9d33d9fd">

### Expected behaviour
There should be no portion of the script injected into the `<body>`

### Versions
- Plugin version: 5.1.5
- Craft version: Craft Pro 5.4.8

<br class="Apple-interchange-newline">

**Comment by khalwat** [comment]
I just tried to replicate this, but am unable to. I end up with this:

```html
<script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments)};
gtag('js', new Date());
gtag('config', 'WOOF', {'send_page_view': true,'anonymize_ip': false,'link_attribution': false,'allow_display_features': false});
</script>
<script>dataLayer = [];
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','BARK');
</script>
```

...with no extra unclosed `<script>` tags. Are you sure they might not be coming from somewhere else in your code?

**Comment by mei-lu** [comment]
@khalwat I could only replicate it locally when I set my environment to production ("live"). Global search in our code for anything GA related comes up blank. Sorry I forgot to mention that in the original description.

**Comment by khalwat** [comment]
Right, that's what I did as well testing things... I set the SEOmatic environment to "live" so that the tracking scripts would render.

Are you sure there aren't any stray `<script>` tags anywhere in your templates?

I ask just because in a bare bones install, turning on both of those scripts did not result in what you reported initially.

**Comment by mei-lu** [comment]
@khalwat Thanks for looking into that. I think our script template got messed up. Adjusting that fixes it, appreciate you looking into this!
