### ISSUE TITLE
In Content SEO: hide sites not available for a given section

### ISSUE THREAD

**Issue by samuel-clara** [nystudio107/craft-seomatic#1539]
### Describe the bug
When changing site in the detail page "Content SEO" (e.g. seomatic/edit-content/general/section/home), the dropdown includes sites that are not available for a given section. Obviously clicking these leads to a server error.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Content SEO and click on a section that are not available in all published sites
2. Try to change to one of those non available sites
3. See error message "Internal Server Error"

### Expected behaviour
Non available sites for a given section should not be visible in the dropdown.

### Versions
- Plugin version: 5.1.6
- Craft version: 5.5.0.1

**Comment by khalwat** [comment]
Can you post the actual error message please?

**Comment by samuel-clara** [comment]
In the dev enviroment it's:
Attempt to read property "sourceName" on null
![meteorit 2024-11-14 at 17 55 44@2x](https://github.com/user-attachments/assets/56aaa547-342a-4935-a94d-6e98388f1543)

**Comment by khalwat** [comment]
So I'm trying to replicate your setup locally -- can you give me a screenshot of your Site Settings for the Section in question?

**Comment by khalwat** [comment]
Okay, I figured this out -- this is actually a regression from a PR -> https://github.com/nystudio107/craft-seomatic/pull/1467

It only affects Craft 5, so I'll fix it there. Thanks!

**Comment by khalwat** [comment]
Fixed in the above commit

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.7”,
```
Then do a `composer clear-cache && composer update`
