### ISSUE TITLE
Sitemap Question

### ISSUE THREAD

**Issue by daniellefrapp** [nystudio107/craft-seomatic#154]
Hi there, 

I seem to be having trouble setting up my sitemaps. For example this is what I have for the blog section: 
![screen shot 2018-06-25 at 12 04 37 pm](https://user-images.githubusercontent.com/33430386/41861715-029c0d4a-7870-11e8-9052-d4ece7a7fb3d.png) but when I click to go to the sitemap I get a 404, http://64.62.135.231/sitemaps/1/section/blog/1/sitemap.xml If I look at the error it's saying the template can't be found. Do I need to create a template or a route for this to work? Thanks!

**Comment by khalwat** [comment]
No, you shouldn't have to set up any templates at all; my guess is that it might be some kind of local server setup issue. SEOmatic should automatically "just work" in that regard.

What happens if you go to `http://64.62.135.231/sitemap.xml` ?

**Comment by daniellefrapp** [comment]
@khalwat I get a 404 too. I have the environment set to live. But I get a 404 trying to see my robots.txt too. Do you think it could be related to my htacess? Here is what's in it:

```
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Send would-be 404 requests to Craft
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
    RewriteRule (.+) index.php?p=$1 [QSA,L]
</IfModule>
```

**Comment by khalwat** [comment]
So I'm not sure what is wrong, potentially something with the server setup, but SEOmatic registers frontend template handlers for those URLs.

Does the rest of SEOmatic work as expected? What I'm doing is pretty straightforward, which is why I'm having a hard time thinking that this isn't some kind of server config setup issue.

Do any other plugins that register frontend template routes work on your setup?

**Comment by khalwat** [comment]
Also, do you see this problem in your local dev environment?

**Comment by daniellefrapp** [comment]
I figured it out, it was an issue with a plugin called Fallback Site that will fallback to a default language when a request is made to an entry in another language. 

Thanks for your help.

**Comment by khalwat** [comment]
No problem!

**Comment by khalwat** [comment]
Related: https://github.com/craftcms/cms/issues/3028
