### ISSUE TITLE
Add ability to disable sitemap per site basis

### ISSUE THREAD

**Issue by samuel-clara** [nystudio107/craft-seomatic#1540]
### Is your feature request related to a problem? Please describe.
When deploying a temporary landing page (I usually create a specific site/sites for the LP) to the production server I obviously have to change the environment to production. This makes adds the entire website to search engines, including the sections I add from time to time building the final website.

### Describe the solution you would like
It would be super useful to have te ability to disable the sitemap on a site basis.

### Describe alternatives you have considered
Now the only way is to disable the sitemap for each section and each site. Which is incredibly time consuming on a big site.

**Comment by khalwat** [comment]
If you disable the site itself, none of the sitemaps for any sections in that site should be enabled. Have you tried that?

**Comment by samuel-clara** [comment]
Yes but doing so I can't see all the entries for that site. And I need to see them locally and on the staging server.

**Comment by khalwat** [comment]
Keep in mind that if the URLs are indeed public, Google et al will often find and index them regardless of whether they are in a sitemap or not:

https://nystudio107.com/blog/seo-myths-top-5-sitemap-myths-demystified

With that said, maybe the best option for you would be to not disable the site, but rather toggle off the ** This site has its own base URL** setting?

SEOmatic will then not generate a sitemap for it, but also I _think_ then the URLs won't be publicly available as well (not 100% sure on the latter).
