### ISSUE TITLE
Dynamic locale per page?

### ISSUE THREAD

**Issue by tibbis** [nystudio107/craft-seomatic#1542]
### Question
I have one single site setup with a language "en" and no region. Then I have several pages that are specific for a region, en-fr, en-ch etc. As its a single site setup, I have a custom field to select the region on each entry to then apply to the html `<html lang="{{currentSite.language ~ "-" ~ countryCode}}">`. 

**Site A:** (lang: en)
example.com/en
- example.com/en-fr/page-1
- example.com/en-ch/page-2
...

**Site B** (lang: fr)
example.com/fr
- example.com/fr-fr/page-3
- example.com/fr-ch/page-4
...

But for example I also need to manually override quite some things like alternate urls, sitemap hreflangs, and the "InLanguage" value in seomatic jsonLd based on the field. 

I wanted to ask if there is a way to override the native locale value on a page, either craft or seomatic api so that it is handled automatic?

(The reason its a single site setup is that there are only 1-2 pages per region (30 regions) so doesn't make sense to make a multi site setup for these pages, only doing a new site if its a new language).

### Additional context
Craft Cms Pro 5 + seomatic plugin

**Comment by khalwat** [comment]
Yes, you can override anything in the generated meta tags or JSON-LD using the SEOmatic API:

https://nystudio107.com/docs/seomatic/using/

Some examples of custom JSON-LD are here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

**Comment by tibbis** [comment]
Yeah I know I can override this but it gets messy with alternate links and hreflangs in sitemaps, as it also needs to have a return-tag on the other page end. 

Was wondering if it's possible to make a module that overrides the currentSite.language of that page so everything else is automatically solved. Or if I can assess the language config of another page from a template?

**Comment by khalwat** [comment]
My best advice would be to leverage the system as much as possible; instead of rolling your own locales/translations, and have a site for each one.

You will end up doing a lot less work if you leverage what Craft already provides rather than trying to roll your own.

I realize it's just for a few pages, but Craft can handle that pretty well with localizing only a few pages in given languages.

If you're determined to do it the way you're describing, I'm pretty sure SEOmatic has the hooks to allow you to do what you want, but I'd need a whole lot more specifics on the project to help more than just general advice.

**Comment by tibbis** [comment]
I get your point with the multi-region site , but I read that craft cp will get quite slow with 50+ sites and as it’s the same language I thought it would be better to have a single site.

Do you think it’s still better to do multi regional for about 30 sites (same language) with couple of pages per site rather than 1 site with some custom hreflang handling performance wise?

**Comment by khalwat** [comment]
Can you point to me where you've read about the slowness of the Craft CP with a lot of sites? I just want to read up on the context.

I'll admit, I've never made a Craft site with 50+ sites, so I have no direct experience there. But I wouldn't think it should make that much of a difference performance-wise.

It might get a little unwieldy from a UX point of view, though.

My thought is that right now it's just a few pages that need to be in different languages, but would it ever scale up to be more than that? If so, leveraging the system would likely be a boon. But I don't know enough about your project.

There might be some clever way to do what you're attempting to do, like a custom module that dynamically sets the language, and then some hooks in SEOmatic to do what you want on that front. I'm just not sure if the custom work will end up being worth it in the end, or if it'll be more work and more fragile than embracing what Craft offers.

You know your project better than me, so your call on that front.

**Comment by tibbis** [comment]
Here is the mention about more queries due to several sites: https://craftcms.com/knowledge-base/how-much-content-can-a-craft-site-have#mind-your-site-count

But it may be exaggerated?

it’s basically a multi-regional site talking about a topic in different countries but in the same language (English expats as example).

**Comment by khalwat** [comment]
Yeah I think they are mostly talking about people who try to use Craft to manage multiple separate sites in one install. For localization purposes, which is what the system is intended for, I don't think you're going to run into an issue.

It probably would be less work to just try it leveraging Craft's sites, and see what the performance is vs. developing a custom solution to a problem that you aren't sure exists yet or not.
