### ISSUE TITLE
New Singles are not getting picked up in Content SEO settings

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#1544]
### Describe the bug
I am working on a new site Craft 5 and I have created some new singles today but these are not appearing at all in the Content SEO settings section. I have checked that they all have URIs, valid templates and Preview Targets. I can access them in the front-end and I can see the SEO previews on the entries in the back-end. However, they do not exist in the Content SEO settings section.
I do see older singles in there and these are fine.

### To reproduce
1. Create a new single section.
2. Head to SEOMatic > Content Settings 
3. New single does not appear in the list.

### Screenshots
<img width="1838" alt="Screenshot 2024-11-20 at 17 53 51" src="https://github.com/user-attachments/assets/224585f2-b6ac-42ec-88ec-fb7fb5bd5e6f">
<img width="1835" alt="Screenshot 2024-11-20 at 17 53 43" src="https://github.com/user-attachments/assets/948d1636-8451-40d4-a6c2-8ac5acba4493">
<img width="1835" alt="Screenshot 2024-11-20 at 17 55 37" src="https://github.com/user-attachments/assets/38a47252-7bae-4abf-bd71-9a327f3185e4">

The following are missing from the Content Settings:
- About Index
- Product Index
- Service Index
- Support Index

### Versions
- Plugin version: 5.1.6
- Craft version: Craft Pro 5.5.2

**Comment by khalwat** [comment]
Fixed.

Craft 3 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.5.8

Craft 4 -> https://github.com/nystudio107/craft-seomatic/releases/tag/4.1.7

Craft 5 -> https://github.com/nystudio107/craft-seomatic/releases/tag/5.1.7
