### ISSUE TITLE
SEO Preview zoomed out

### ISSUE THREAD

**Issue by turnstylerj** [nystudio107/craft-seomatic#1548]
### Describe the bug
I'm not sure whether this is intentional or not, but I noticed recently the SEO Preview sidebar section's items are zoomed out in Firefox. Looking at the vendor files, it looks like this is an inline style set in the table/sidebar preview twig files (which made me wonder if it was intentional, it just looked a little odd).

### Screenshots
![397050114-08cb5356-f584-4bfb-8079-f2d944499230](https://github.com/user-attachments/assets/d70fe8ce-d381-4180-9d4b-9df5dfaa66f7)
![2024-12-18 at 09 50 28](https://github.com/user-attachments/assets/1f4e1323-9011-4a03-89e7-9192ba597f1e)

### Versions
- Plugin version: 5.1.7
- Craft version: 5.5.6.1

**Comment by khalwat** [comment]
It's intentional. I'm not sure why Firefox is rendering it oddly; can you verify what it looks like in Chrome and Safari?

**Comment by AugustMiller** [comment]
Hey, Andrew! Looks like some time in 2024, Firefox added [support](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom#browser_compatibility) for the `zoom` property, where other browsers have had it… forever? 😅

What's worse—they are stacking this effect with the `-moz-transform` property, so we get 60% of 60%!

I don't know if this just means it's safe to use `zoom` exclusively, or if a `transform`-based solution (sans vendor prefixes) would provide better support, for now.

Screenshots attached!

&rarr; Both types of scaling applied:
![Image](https://github.com/user-attachments/assets/af41c55d-e129-47ff-88d8-8b1b6bccb0b0)

&rarr; Only `transform` applied:
![Image](https://github.com/user-attachments/assets/3c53a9c6-9176-4cf4-8c8d-76ffffcd9223)

&rarr; Only `zoom` applied:
![Image](https://github.com/user-attachments/assets/0a80c765-da6e-49ac-abf6-64691d24429b)
