### ISSUE TITLE
x-robots-tag on redirects

### ISSUE THREAD

**Issue by nathansnelgrove** [nystudio107/craft-seomatic#1549]
### Describe the bug
Hi! I'm not sure if this is a Retour thing or SEOMatic thing (both are installed in this site). I just went live with a client site and noticed that the redirects I've got in place all have `X-Robots-Tag:none` in the HTTP header. `none`, as far as I understand (and correct me if I'm wrong), would suggest `no-index; no-follow`. Isn't it problematic to have a `no-follow` on a 301's HTTP headers, because that would tell Google not to follow the redirect? 

### To reproduce
Steps to reproduce the behaviour:
1. Install SEOMatic and Retour.
2. Add a redirect in Retour.
3. Check the HTTP headers or use Search Console on the redirected URL to see the output.

### Expected behaviour
I think I just wouldn't expect an X-Robots-Tag at all? Or at least `X-Robots-Tag:noindex`.

### Versions
- Plugin version: 5.1.5
- Craft version: 5.4.9

**Comment by khalwat** [comment]
Retour does not add any headers. SEOmatic can add headers, but shouldn't for a redirect.

Craft also adds these headers, however. Are we sure it isn't coming from Craft?

SEOmatic has an option in Plugin Settings to disable adding the headers. Try turning that off and see if the header still appears.

All of that said, if the header is set on the URL that is `404`ing, that's what you want to have happen. You don't want Google to index a `404` redirect.

**Comment by nathansnelgrove** [comment]
I tried disabling that setting, but that resulted in `X-Robots-Tag:None` on the production site, which is not what I expected (I expected nothing there at all). 

I'm not sure where it's coming from. Where would I change it in Craft?

As far as that redirect, I definitely want `no-index`, but my SEO guy isn't sure about `nofollow`, and both are happening when X-Robots-Tag is set to `none`. He'd just prefer no X-Robots-Tags at all.

**Comment by nathansnelgrove** [comment]
Also, thank you for your speedy response!

**Comment by khalwat** [comment]
If you disabled that setting, SEOmatic will not add any headers at all, including `X-Robots`

Are we talking about headers, or are we talking about actual `<meta>` tags in the HTML?

**Comment by nathansnelgrove** [comment]
Great question! HTTP Headers. I don't know how they get there; this is part of front-end 101 I guess I missed.

**Comment by khalwat** [comment]
If you disabled that setting in SEOmatic, and the headers are still appearing, then the headers are _not_ coming from SEOmatic.

They could be coming from Craft, there's a setting for that:

https://craftcms.com/docs/5.x/reference/config/general.html#disallowrobots

But you'd have to explicitly turn it on.

**Comment by khalwat** [comment]
Also can you clarify _where_ you see this header set? Is it on the redirect itself, or the new page that it is being redirected to?

**Comment by nathansnelgrove** [comment]
I can clarify!

There are two separate issues here, which is not helping me much either. On a redirect, the SEO person reports that the original URL (which now 301s) has `X-Robots-Tag:None`, always.

On the page it's redirected to, the X Robots Tag stuff is all there and it looks right. 

Disabling the X-Robots-Tag in SEOMatic changes every page's X-Robot-Tag to `none` in my live environment. I can confirm that I do not have that config enabled in any environment. (I don't have it explicitly disabled either, but I doubt that matters.)

Disabling the X-Robots-Tag also disables canonical and referrer-policy stuff to, but I could see reasons why somebody would want 1 disabled and the other options enabled.

**Comment by khalwat** [comment]
> On a redirect, the SEO person reports that the original URL (which now 301s) has X-Robots-Tag:None, always.

This is fine, you don't want Google indexing pages that are redirected. I'd ask your SEO person to clarify this, because it doesn't make any sense to me.

> Disabling the X-Robots-Tag in SEOMatic changes every page's X-Robot-Tag to none in my live environment. I can confirm that I do not have that config enabled in any environment. (I don't have it explicitly disabled either, but I doubt that matters.)

In that case, I don't think that header is coming from SEOmatic. Disabling that setting causes SEOmatic to not add headers to anything.

**Comment by nathansnelgrove** [comment]
His issue is that with the X-Robots-Tag set to `none` on the redirect, that the `nofollow` implication of `none` tells Google not to follow the redirect, losing page authority. He doesn't *know* if that's the case, but because nobody seems to know if that's the case, he'd prefer not to find out on an actual client site.

And fair enough! I don't know where the heading is coming from; total mystery to me. I see nothing in Craft that should add it, and I don't know where to go looking next.

So, just a normal depressing day in web development! 

Thanks for your help (truly).

**Comment by khalwat** [comment]
Have you checked to see if that general config setting is set in Craft? That's the only other thing I can think of that could be setting that header (unless it is some other plugin somewhere).

You can also temporarily test this theory by disabling the SEOmatic plugin entirely and see if that header is still set.

I just searched through Retour's entire codebase, and it does not set the `X-Robots-Tag` explicitly anywhere, though there is a setting in Retour that lets you arbitrarily add headers to redirect responses.

You can check that in Retour -> Settings -> Advanced -> **Additional Headers**

By default, that's empty, so someone would have had to add a specific header in there if they wanted it there.

But it sounds to me like you have something in your `config/general.php` that is explicitly setting `disallowrobots` to `true`. https://craftcms.com/docs/5.x/reference/config/general.html#disallowrobots

That or perhaps some other plugin is doing it?

**Comment by nathansnelgrove** [comment]
This is all that's in my general.php file:

```
<?php
/**
 * General Configuration
 *
 * All of your system's general configuration settings go in here. You can see a
 * list of the available settings in vendor/craftcms/cms/src/config/GeneralConfig.php.
 *
 * @see \craft\config\GeneralConfig
 */

// use craft\config\GeneralConfig;
use craft\helpers\App;

return [
    // Global settings
    '*' => [
        // Default Week Start Day (0 = Sunday, 1 = Monday...)
        'defaultWeekStartDay' => 1,
    
        // Whether generated URLs should omit "index.php"
        'omitScriptNameInUrls' => true,

        // Don't allow admin changes anywhere
        'allowAdminChanges' => false,

        // Preload single entries as Twig variables
        'preloadSingles' => true,

        // Prevent user enumeration attacks
        'preventUserEnumeration' => true,

        'addTrailingSlashesToUrls' => false,

        // Set the @webroot alias so the clear-caches command knows where to find CP resources
        'aliases' => [
            '@webroot' => dirname(__DIR__) . '/web',
        ],
    ],

    'dev' => [
        // Dev mode
        'devMode' => true,
        'allowAdminChanges' => true,
    ],

    // Dev environment settings
    'staging' => [
        'allowUpdates' => false,
        // Dev Mode (see https://craftcms.com/guides/what-dev-mode-does)
        'devMode' => true,
    ],

    // Production environment settings
    'production' => [
        'devMode' => false,
        'allowUpdates' => false,
    ],
];
```

There are no additional headers added in Retour.

My whole plugin list is just S3, your plugins, CKEditor, and Formie. And it's all set up on Linode through Laravel Forge, generally following your instructions actually (thanks for all your great posts over the years by the way). So yeah.

I will see about disabling the plugin entirely and find out what happens then.

**Comment by nathansnelgrove** [comment]
OK, disabling the plugin sets `x-robot-tags` to `none`, which is really weird. So something somewhere else is doing this. Sorry for troubling you so much. Thank you for that suggestion.

**Comment by nathansnelgrove** [comment]
OK, this is going to sound so stupid, but I forgot to change `CRAFT_DISALLOW_ROBOTS` to `false` in my `.env` file, and I never thought to check that because *what a rookie mistake*, so here I am. Please ignore me. 

I need a stiff drink and a holiday.

**Comment by khalwat** [comment]
Glad we got it sorted out!
