### ISSUE TITLE
Non-admin users with permissions to access plugin settings cannot save settings

### ISSUE THREAD

**Issue by dreadfullyposh** [nystudio107/craft-seomatic#155]
When using a non-admin user with permissions granted to the SEOMatic plugin settings, the user receives a permission error when trying to save the settings page.

**Comment by khalwat** [comment]
Just to clarify, we're talking about the `seomatic/plugin` page yes?

Do they have the Craft **Access the CP** and **Access SEOmatic** permissions as well as the SEOmatic **Edit Plugin Settings** permission?

**Comment by dreadfullyposh** [comment]
Yes, the `seomatic/plugin` page

And yes to all the permissions. Here are screenshots of the relevant sections of the permissions page:

https://www.dropbox.com/s/khb7ivoqaank19o/Screenshot%202018-06-28%2008.31.44.png?dl=0

https://www.dropbox.com/s/d3wx443zcgn8vix/Screenshot%202018-06-28%2008.32.09.png?dl=0

**Comment by khalwat** [comment]
That's curious, because for that save method, it just uses Craft's built-in `plugins/save-plugin-settings` controller. I checked, and I'm not seeing any explicit permissions checks in that controller, or the methods it calls.

**Comment by khalwat** [comment]
Can I get the exact wording or a screenshot of the permissions error? I will try to duplicate it locally as well, but it can't hurt.

**Comment by dreadfullyposh** [comment]
Unauthorized
User is not permitted to perform this action

**Comment by khalwat** [comment]
@dreadfullyposh looks to be a Craft thing:

https://github.com/craftcms/cms/issues/3045

**Comment by dreadfullyposh** [comment]
Thanks!

**Comment by khalwat** [comment]
Not a Craft thing according to Brandon; I need to implement my own controller: https://github.com/craftcms/cms/issues/3045#issuecomment-401249370

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/9cf98c341e845df47c7a5856d6538ac0c226e56b
