### ISSUE TITLE
Allow X-Robots-Tags to be disabled independently in Settings

### ISSUE THREAD

**Issue by nathansnelgrove** [nystudio107/craft-seomatic#1550]
### Is your feature request related to a problem? Please describe.
I'd love to disable X-Robots-Tags in SEOMatic. Right now, it looks like I can do that, but disabling that in the Settings disables it in other places.

### Describe the solution you would like
I'd like to disable X-Robots-Tag on its own.

### Describe alternatives you have considered
None. This is a request from an SEO fellow, and I'm a little confused about how to go about it.

**Comment by khalwat** [comment]
You can do that now: 

SEOmatic -> Plugin Settings -> Tags -> **HTTP Headers Enabled**

**Comment by nathansnelgrove** [comment]
I mentioned this in another response, but just to be clear, that resulted in `X-Robots-Tag:none`, not no X-Robots-Tag at all.

Sorry if this is a Craft thing and not an SEOMatic thing. I'm just trying to do what I've been asked to do.

**Comment by khalwat** [comment]
If you disable that setting, SEOmatic does not send any headers at all, including `X-Robots`.

Are we talking about headers, or are we talking about actual `<meta>` tags in the HTML?
