### ISSUE TITLE
Entry Export data mapping to Feed Me import

### ISSUE THREAD

**Issue by svondervoort** [nystudio107/craft-seomatic#1552]
### Is your feature request related to a problem? Please describe.
We've got this question from a client where they would like to use the default Craft Export functionality in the CP Entry Index.
They then use the `Raw export (fastest)` version to export entry data. They then would like to manipulate some SEO data and re-import it using using FeedMe.

Now the only way to map SEOmatic SEO field in FeedMe is to map each field separately. But the issue is the `Raw export` returns a JSON (encoded) object which we can't map individual values to the fields. 

### Describe the solution you would like
Would it be possible to add a single (general) SEOmatic SEO field to FeedMe that maps the whole JSON object for import?
Or what would be the best approach for importing the updated data?

### Describe alternatives you have considered
Creating a custom importer to handle this logic instead of using FeedMe, but FeedMe is the preferred way.

### Additional context
We tried exporting to CSV and JSON, but both versions include a JSON encoded object for the SEOmatic SEO field.

**Comment by khalwat** [comment]
So the vast majority of the time, I suggest not using an SEOmatic field as discussed here:

https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

...but rather to set up the content mappings in the Content SEO settings.

The SEOmatic field is intended for the rare occasions that you need to override the Content SEO settings that map from fields in Craft CMS.

So your feature would be a pretty specialized one. My suggestion would be that you could write a custom exporter as part of a Craft CMS module that could do it if your client really wants it:

https://craftcms.com/docs/5.x/extend/element-exporter-types.html#creating-custom-exporter-types
