### ISSUE TITLE
Option to disable site based meta tags

### ISSUE THREAD

**Issue by colinmeinke** [nystudio107/craft-seomatic#158]
I have 4 sites, however they are all the same language, and they do not have separate URLs (the site is set based on IP and `web/index.php`).

That means this output doesn't make any sense:

![](https://www.dropbox.com/s/xj74wv9pdgc63s5/Screen%20Shot%202018-06-20%20at%2009.08.06.png?raw=true)

It would be nice to get an option to disable this site based output.

**Comment by khalwat** [comment]
You can disable it via Twig in SEOmatic by doing:

```twig
{% do seomatic.link.get('alternate').href(seomatic.meta.canonicalUrl) %
{% do seomatic.tag.get('og:locale:alternate').setAttributes({'property': ''}) %}
```

It sounds like a semi non-standard setup for Craft multi-site?

**Comment by colinmeinke** [comment]
Great, thanks! I guess it's fairly non-standard, although not that unusual. The use case is a site where different content is served per geo, but for legal reasons there is only one entry point (think Netflix).
