### ISSUE TITLE
Separator still shows when custom text Title is blank

### ISSUE THREAD

**Issue by colinmeinke** [nystudio107/craft-seomatic#159]
When I leave the Title blank for the `<title>`, as I only wish to use Site Name on my home page, I still get the separator. e.g. `Site Name |`. Is there any way to avoid this?

**Comment by khalwat** [comment]
Yes, you can set the Site Name Position to `none` and just title the homepage entry with your site name.

I will caution you that just the name of the site as a title probably isn't the best from an SEO POV though.

**Comment by colinmeinke** [comment]
@khalwat if custom position is set to none, and custom text is empty, for me the title is still affixed with the separator.
