### ISSUE TITLE
Ability to exclude individual entries/elements from sitemap

### ISSUE THREAD

**Issue by bwlng** [nystudio107/craft-seomatic#16]
Would you consider exposing a method outside of disabling an entry to exclude it from the sitemap (in a section where other entries should be included)? It looks as though the entry criteria is baked in `models/SitemapTemplate.php`, but it'd be handy if a field could be mapped to a sitemap setting that would prevent it from being included (for example, a "protected" or "index" lightswitch).

I see this being useful for clients who have pages they like to keep semi-private by setting a "noindex" meta tag and only distributing a link via e-mail or requiring a login before viewing.

If not a core feature, perhaps a way to add additional criteria during the render method or event within the elements loop to skip a line?

**Comment by khalwat** [comment]
So for me this ties into the Field discussion:

https://github.com/nystudio107/craft-seomatic/issues/14

...because if I implement an SEOmatic Field, then you could set any of the settings on a per-entry basis (including the Sitemap settings).

**Comment by bwlng** [comment]
I could get behind the field for this purpose, but it would also be nice to be able to “pull” from a field or override it in templates the way you can the content fields. In the event a page should be “private” it’d be a bummer if the client toggled the lightswitch to mark it private but Google was notified of its existence via the sitemap because they forget to change the sitemap setting and/or robots setting via the field.

With an override/mapping I could handle the intent for them to make it foolproof.

**Comment by khalwat** [comment]
Well, just not being in the sitemap doesn't mean anything really; the sitemap is just a way to make _sure_ that Google finds the links you want it to find. It actually does a pretty good job indexing content just by spidering your site.

So what you really want is a way to ensure that the Robots header and tag (which Google does respect) are set properly for the entry you want excluded.

**Comment by bwlng** [comment]
I also wouldn’t want to aid a human who might be digging through the sitemap for some reason. It might not be super sensitive content, but the type of content that only targets certain visitors (landing pages with special offers, for example, that are still part of the Pages structure within the CMS)

**Comment by khalwat** [comment]
In fact... I'm gonna even go so far as to say that if you'll be toggling on/off the external access to some URIs, then you could make a case that you _want_ it to be in the Sitemap.  Why?

Consider... you have a URL that gets indexed by Google. Client now doesn't want it indexed, or made a mistake and it never should have been indexed.

If you remove it from the sitemap & adjust the Robots tag, Google isn't going to re-crawl it for some time.

If you _keep_ it in the sitemap & adjust the Robots tag, now the sitemap says "hey Google, you need to index me, I changed!" and it comes in, sees that it shouldn't be in the index, and removes it.

:)

I get your scenario too, and understand what you mean. I'll do what I can!

**Comment by bwlng** [comment]
Thanks! It's probably an edge case, but I'll take what I can get ;)

**Comment by khalwat** [comment]
This is implemented as part of the Field https://github.com/nystudio107/craft-seomatic/issues/14
