### ISSUE TITLE
Using OptimizedImages as SEO Image

### ISSUE THREAD

**Issue by daniellefrapp** [nystudio107/craft-seomatic#160]
Sorry it's me again. I have a question about using OptimizedImages as SEO Image.

For blog post entries I have a featured image that I use OptimizedImages to create the different srcset for. I am also using that same field as my SEO image. Everything looks correct in the post screen. 
![screen shot 2018-06-29 at 10 27 44 am](https://user-images.githubusercontent.com/33430386/42097815-1687be98-7b87-11e8-86f9-bbf6ec620cd4.png)

But if I look at the source to og:image is referencing the global seo. However the twitter image is correct. Here is an example blog post: http://64.62.135.231/blog/five-engagement-best-practices-omnichannel-digital-ux

On my author pages I am NOT using OptimizedImages and the og:image and the twitter are using the correct image. Here is an example: http://64.62.135.231/blog/author/peter-basile

Am I doing something wrong, or can you not use an OptimizedImages as an SEO image. 

Also here are my breakpoint in OptimizedImages:
1408 16:9
1216 16:9
1024 16:9
768 16:9

**Comment by khalwat** [comment]
How are you using an Optimized Images field for the SEO image? Show me a screenshot of what your Content SEO settings look like for this section?

SEOmatic shouldn't let you choose an Optimized Images field with the AdminCP GUI.

**Comment by daniellefrapp** [comment]
Sorry I don't think I was very clear. I'm not using an Optimized Images field for the SEO image. I'm using a field that uses the Optimized Images field as an SEO image. 
![screen shot 2018-07-02 at 9 12 33 am](https://user-images.githubusercontent.com/33430386/42166184-378ac7e0-7dd8-11e8-8aa4-534ecb06a2d5.png)
![screen shot 2018-07-02 at 9 12 50 am](https://user-images.githubusercontent.com/33430386/42166185-379a8356-7dd8-11e8-85e5-6c5568f98bb1.png)
![screen shot 2018-07-02 at 9 12 55 am](https://user-images.githubusercontent.com/33430386/42166186-37a61b6c-7dd8-11e8-8e9e-ab1aca325825.png)
![screen shot 2018-07-02 at 9 13 20 am](https://user-images.githubusercontent.com/33430386/42166187-37b834aa-7dd8-11e8-8f9d-5c4b2ab0d6d6.png)
![screen shot 2018-07-02 at 9 13 26 am](https://user-images.githubusercontent.com/33430386/42166189-37ca2426-7dd8-11e8-846a-fd9b3d13d834.png)

**Comment by khalwat** [comment]
Okay, in that case there should be no issue -- the Optimized Images field won't even come into play.

Show me your Content SEO settings for the Section in question?

**Comment by daniellefrapp** [comment]
It's the last two screenshots, the section is called blog.

**Comment by daniellefrapp** [comment]
It looks like it works inside the SEO preview (see first screenshot in this post) but when you view the source code that's not the image its pulling.

**Comment by khalwat** [comment]
Sorry, I mean for Facebook -- that's the one you're having issues with yes?

**Comment by daniellefrapp** [comment]
Yes

**Comment by khalwat** [comment]
Ok, so can you give me a screenshot of your settings for Content SEO -> Facebook?

Also try clicking Save on those settings to see if perhaps there is stale data there.

**Comment by daniellefrapp** [comment]
Here you go
![screen shot 2018-07-02 at 11 06 11 am](https://user-images.githubusercontent.com/33430386/42171707-05ff74ea-7de8-11e8-9b23-3a6ae9e47a18.png)
![screen shot 2018-07-02 at 11 06 24 am](https://user-images.githubusercontent.com/33430386/42171708-06100634-7de8-11e8-8f49-15f6c7aa6f9c.png)

**Comment by khalwat** [comment]
Everything looks right to me. Try clicking Save on Content SEO -> Facebook

Also you're using the latest Craft CMS, and the latest SEOmatic, yes?

You're not changing the `og:image` via Twig or an SEO Settings field perchance?

**Comment by daniellefrapp** [comment]
Arrrgg... the hitting save worked. I'm sorry to bug you for something so easy to fix. I really thought I tried that.

**Comment by khalwat** [comment]
Glad we have it resolved!
