### ISSUE TITLE
Sitemap: Categorygroup items getting included in incorrect categorygroup sitemap.xml

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#161]
Client is facing an issue with the generated sitemaps by SeoMatic.

Categories from two different "category groups" are getting included in each other sitemap.xml

_This is the structure:_
http://url.com/sitemaps/1/categorygroup/categoryGroupOne/1/sitemap.xml
http://url.com/sitemaps/1/categorygroup/categoryGroupOne/2/sitemap.xml
http://url.com/sitemaps/1/categorygroup/categoryGroupTwo/1/sitemap.xml
http://url.com/sitemaps/1/categorygroup/categoryGroupTwo/2/sitemap.xml

So items from **categoryGroupOne** are being displayed in the sitemap from **categoryGroupTwo**.

I already tried the following:
- Empty cache
- Re-save category items
- Re-save category groups
- Re-save sitemap settings

Setup details:
- **Craft Pro** 3.0.13.1
- **SeoMatic** 3.0.24
- - Multi lang site

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/0807f28c22d155a6673e3cc28b364b8dfdd302ed
