### ISSUE TITLE
Sitemap: generated sub-sitemaps for sections and categorygroups output as a simple txt file

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#162]
Client is facing an issue with the generated sitemaps by SeoMatic.

The sub-sitemaps that are generated for sections and categorygroups are not generated as a correct .xml. It's getting output as a simple txt file without the xml markup.

We tried some things by changing the settings.
The issue occurs when the **"Sitemap Alt URLs"** option is **enabled**.
The moment we disable this option the sitemap is getting generated as a correct XML structered file.

Setup details:
- **Craft Pro** 3.0.13.1
- **SeoMatic** 3.0.24
- - Multi lang site

**Comment by khalwat** [comment]
Can you give me a URL to one of these sitemaps? Did you choose "View Source" in your browser and/or run it through a sitemap validator?

**Comment by khalwat** [comment]
I'm following the spec that Google recommends here:

https://support.google.com/webmasters/answer/189077?hl=en&visit_id=1-636662265398871188-4174827333&rd=1

...and the sitemaps I've checked do validate properly, and are consumed by Google.

I've noticed that if I visit the sitemap directly in Chrome, it displays as plain text, but if you choose "View Source" that it shows the structure of the document is correct.

**Comment by boldenamsterdam** [comment]
Hi @khalwat ,

It looks like your right.
Unfortunately I'm not able to share a link, we are currently testing this on a IP authorised staging environment.

But I asked the client if there SEO expert can also confirm your answer. 
When they do I will let you know.

Thanks for the quick response time!
