### ISSUE TITLE
How to set up the SiteLinks Search Box

### ISSUE THREAD

**Issue by YongYu123** [nystudio107/craft-seomatic#164]
I try to set up the SiteLinks Search Box in SEOmatic, but get some problem.
My setting is 
![site settings - tr3ndsideas 2018-07-05 17-19-54](https://user-images.githubusercontent.com/25882487/42303950-d4232696-8077-11e8-9070-eff63bb7376f.png)
While  the {search_term_string} looks become a variable, the output in front is https://query.example.com/search?q= , while  {search_term_string} is missing. 
So are there any method can fix this problem?

**Comment by khalwat** [comment]
I think SEOmatic may be parsing this as a template when in this case, it should not.  I'll get a fix in for you!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/910a2500c72c8e815161a9666354f9fe052c1f84
