### ISSUE TITLE
Open Graph locale format

### ISSUE THREAD

**Issue by samhernandez** [nystudio107/craft-seomatic#167]
The Craft 3 locale format seems to be incompatible with [Open Graph's specification](http://ogp.me/#optional) :

> `og:locale` - The locale these tags are marked up in. Of the format `language_TERRITORY`. Default is `en_US`.

```
<meta content="en-US" property="og:locale">
```

might need to swap the dash with an underscore

```
<meta content="en_US" property="og:locale">
```

In a recent support ticket, this caused problems for someone trying to implement Facebook comments with a site set to `en-GB`. Craft 2 locales had underscores. Yii2 uses PHP [`intl`](http://php.net/manual/en/book.intl.php) with ISO standard formats.

**Comment by khalwat** [comment]
Thanks for the heads up! Fixed in https://github.com/nystudio107/craft-seomatic/commit/138ed873a52a9476e85d91003ddfb93436bff094
