### ISSUE TITLE
Twitter summary card preview stuck

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft-seomatic#168]
When changing twitter card type from large image -> summary card then back to 'with large image' the preview seems to stay stuck on summary card: eg small image on left, text on right

**Comment by khalwat** [comment]
Is this for Global SEO settings, Content SEO settings, or via the SEO Settings field?

**Comment by khalwat** [comment]
I just tried to replicate this, and was unable to. Can you get me some steps to reproduce?

Also what version of SEOmatic are you using?

**Comment by alanski66** [comment]
I get this on the Content Seo settings for my news section, twitter card type set to 'Summary card with large image'
Seomatic 3.10.
![screenshot 2018-07-12 23 23 08](https://user-images.githubusercontent.com/1781739/42662764-c8b21926-862a-11e8-8583-a171c678a52c.png)

**Comment by khalwat** [comment]
hmmmm. And you're clicking Save after you make the changes ya?

How does it display in the sidebar preview when you're editing an entry in that section?

**Comment by alanski66** [comment]
AH interesting. Content Seo is set to summary card large image, but when opening an existing news item the entry seo twitter preview is just the summary card.  When i change the entry setting to large card image the entry preview goes to large card. Then when going back to Content Seo, the 'stuck preview' has changed  to large card - its like the entry settings are affecting the section settings?

**Comment by alanski66** [comment]
So i think i worked this out. I have two entry types for news one which is imported one which is created in CMS. I wanted my imported news to have a different image field to separate legacy news images from newer news images. So its reverting to default SEO instead of section SEO.

This leaves me with conundrum. I thought i'd be able to work around this by:
    {% switch entry.type %}
        {% case 'oldnews' %}
            {% set asset = entry.oldNewsImage.one() %}
            {% do seomatic.meta.ogDescription("{entry.body}") %}
            {% do seomatic.meta.ogImage("{asset.url}") %}
            {% set date = "" %}
        {% case 'news' %}
            {% set asset =  entry.image.one() %}
            {% do seomatic.meta.ogDescription("{entry.newsIntro}") %}
    {% endswitch %}

But no such luck.
{% do seomatic.meta.ogImage("{asset.url}") %}
This do instruction to override doesnt seem to override the output....

**Comment by khalwat** [comment]
So the Twig overrides definitely will work, but you could also do it by putting your Twig code into the SEO Image field, as described here:

https://github.com/nystudio107/craft-seomatic#content-seo-admincp-fields
