### ISSUE TITLE
Make referrer optional

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#170]
Hello!

Would it be possible to make the referrer header optional? I prefer adding such headers in our HTTP headers.

Thanks in advance!

**Comment by khalwat** [comment]
You can do that via Twig by doing:

```twig
{% do seomatic.tag.get('referrer').include(false) %}
```

as per: https://github.com/nystudio107/craft-seomatic#meta-object-get

Or if you want, you can set up your own default containers that don't include it at all, as per:

https://github.com/nystudio107/craft-seomatic#config-settings

FWIW, there's no harm in having it in both places. In a future version of SEOmatic, I may have it automatically add the header for you anyway (if you want)

**Comment by XhmikosR** [comment]
Thanks for the fast reply!

I'm pretty anal with this and I prefer only setting the headers when possible and not `meta` tags.
