### ISSUE TITLE
SiteLinks Search box: Invalid LDJSON output

### ISSUE THREAD

**Issue by rob-c-baker** [nystudio107/craft-seomatic#171]
When setting a Search Target URL Pattern to something like:

https://domain.com/search?q={search_term_string}

And the search query input to:

search_term_string

Expected LDJSON output would be:

`"potentialAction":{"@type":"SearchAction","query-input":"search_term_string","target":"https://domain.com/search?q={search_term_string}"}`

But ends up being:

`"potentialAction":{"@type":"SearchAction","query-input":"search_term_string","target":"https://domain.com/search?q="}`

SEOMatic Version: 3.0.23
Craft CMS Version: 3.0.12

**Comment by khalwat** [comment]
Update to the latest version of SEOmatic (3.1.2 as of this writing), this was fixed in 3.1.0:

https://github.com/nystudio107/craft-seomatic/blob/v3/CHANGELOG.md#310---20180711

**Comment by mattstein** [comment]
I'm experiencing the same thing with Craft 3.1.25 and SEOmatic 3.1.50, not with the control panel setting but with custom attributes in a template that are only relevant to one part of the site:

```twig
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}

{% do mainEntity.setAttributes({
    'potentialAction': { 
        'type': 'SearchAction', 
        'target': siteUrl ~ 'blog/search?q={keyword}',
        'query-input': "required name=keyword"
    },
}) %}
```

The resulting JSON doesn't include the bracketed variable:

```
...
"potentialAction": {
    "@type": "SearchAction",
    "query-input": "required name=keyword",
    "target": "https://foo.dev/blog/search?q="
},
...
```

Is there a trick to handing this off from a template? I can print directly to the template as expected with `{{ siteUrl ~ 'blog/search?q={keyword}' }}`.

**Comment by khalwat** [comment]
@mattstein pleased open a new issue if you think you're still having an issue, and reference this closed issue.

Any reason you're not using the built-in search option?

<img width="1491" alt="Screen Shot 2019-05-02 at 10 17 22 PM" src="https://user-images.githubusercontent.com/7570798/57117185-2a75e680-6d28-11e9-9943-c0a2fd3b3ce9.png">

**Comment by mattstein** [comment]
Apologies for the bad form, @khalwat. I'm only providing the `potentialAction` to a specific section within the site. But I'll open a new Issue and go into more detail there.
