### ISSUE TITLE
Trailing slash in sitemap.xml link to the sub-sitemaps

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#173]
Hello!

I'm having an issue where the sub-sitemaps have a trailing slash in `/sitemap.xml`.

```
https://foo.bar/sitemaps/1/section/pages/1/sitemap.xml/
```

My .htaccess section that's related to this:

```apache
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Force a trailing slash
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_URI} /+[^\.]+$
    RewriteRule ^(.+[^/])$ %{REQUEST_URI}/ [R=301,L]

    # Send would-be 404 requests to Craft
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
    RewriteRule (.+) index.php?p=$1 [QSA,L]
</IfModule>
```

This happens even without my custom rule to force trailing slashes. I do have `addTrailingSlashesToUrls` set to `true` though.

I'm using Craft CMS 3.0.16.1 and SEOmatic 3.1.2.

**Comment by khalwat** [comment]
That's very strange... perhaps you need to add `xml` to `defaultTemplateExtensions`? https://docs.craftcms.com/v3/config/config-settings.html#defaulttemplateextensions

I'm not sure why Craft would be adding a `/` to those URLs.

**Comment by XhmikosR** [comment]
Tried that, still the same :/

**Comment by XhmikosR** [comment]
If I set `addTrailingSlashesToUrls` to `false` then this goes away.

**Comment by khalwat** [comment]
Weird, it looks like with that setting, Craft will add that to any URL, regardless of whether there is a file extension on it or not:

From `UrlHelper.php`:

```
        // Put it all together
        if (!$showScriptName || $generalConfig->usePathInfo) {
            if ($path) {
                $url = rtrim($baseUrl, '/') . '/' . trim($path, '/');

                if (!$cpUrl && $generalConfig->addTrailingSlashesToUrls) {
                    $url .= '/';
                }
            } else {
                $url = $baseUrl;
            }
        } else {
            $url = $baseUrl;

            if ($path) {
                $pathParam = $generalConfig->pathParam;
                $params = $pathParam . '=' . $path . ($params ? '&' . $params : '');
            }
        }
```

**Comment by XhmikosR** [comment]
Should I report this to Craft then? I just happened to notice the issue in sitemap.xml.

**Comment by khalwat** [comment]
You can; I'm not sure if it's a bug or intended behavior. Seems a little odd to me but who knows?

Worst case, I can just `rtrim()` the URLs, but I wouldn't think it'd blindly add a `/` to anything passed in to `UrlHelper::siteUrl()` if it has a file extension.

**Comment by XhmikosR** [comment]
OK, I made an issue upstream https://github.com/craftcms/cms/issues/3123

**Comment by khalwat** [comment]
Looks like P&T fixed it for an upcoming release of Craft CMS: https://github.com/craftcms/cms/commit/1ec8cd1eb247219a4baf87e9f162bf499ccacb88
