### ISSUE TITLE
Large Twitter summary card not populating child pages.

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-seomatic#174]
We are seeing an issue with the Twitter card type not populating child pages from within the Content SEO settings, screenshot shown below: 

![image](https://user-images.githubusercontent.com/3185073/42998483-29b9f7a6-8c12-11e8-92e0-979edf4ffe95.png)

Running Craft 3.0.16.1 and SEOMatic 3.1.2

**Comment by khalwat** [comment]
Could it be related to this? https://github.com/nystudio107/craft-seomatic/issues/168

**Comment by khalwat** [comment]
Also I noticed that `Sitemaps` is missing from the screenshot -- could this be a permissions thing in some way?

**Comment by baileydoestech** [comment]
Yes is looks identical to the problem outlined in #168, when changing the Twitter card type at the entry level (say for an individual news item) the Content SEO preview appears to then get updated. In our case there is no custom SEO twig overrides, just vanilla OOTB functionality. 

Screenshot is from an author that raised the issue but can confirm this behavior occurs for admins as well.

**Comment by khalwat** [comment]
So @lukebailey Do you have multiple entry types as discussed in that issue?

**Comment by khalwat** [comment]
So this was a bug in older versions of SEOmatic that were fixed in an update -- but to propagate the fix to the already installed version, you need to go to the Twitter and Facebook pages, and click on Save.

Can you try this and confirm things are still not working as expected?

**Comment by baileydoestech** [comment]
We only have the one entry type and have tried re-saving the Twitter/Facebook settings on Content SEO for multiple sections but no change to the twitter card image size. 

The above observation still applied, changing the twiiter card type on an ENTRY seems to then affect the preview on the CONTENT SEO page. However only the individual entry that was changed manually actually updates, other entries in the section still do not receive the card type from content SEO.

Have also  just updated to the latest release from yesterday.

**Comment by baileydoestech** [comment]
Didn't mean to close that sorry!

**Comment by khalwat** [comment]
@lukebailey Just making sure I'm understanding you correctly:

Are you using an SEO Settings field in your entries? And is there where you are making changes to the card type?

If so, that's expected behavior. The changes made to an individual entry affect only that entry.

If you want to make changes that affect an entire section, you'd make your changes in the appropriate Content SEO section.

**Comment by baileydoestech** [comment]
Yes we have the SEO settings fields added to all our sections should authors wish to override any SEO settings at the individual entry level. However, we assumed that settings applied at the Content SEO level would still be inherited (at least initially) so that a common base line is used by all entries. 

Is this not the case if we have the SEO settings field added?

When we make changes at the individual level in the SEO settings fields this seems to affect the settings in the Content SEO section which is bizarre.

**Comment by khalwat** [comment]
Right, that's what should be happening. It should work like this:

SEO Settings field > Content SEO > Global SEO

...in terms of the priority. So what I need to test for you then is:

It seems very, very strange to me that the settings for an individual SEO Settings field would bleed out into other entries from that section.

These all have unique URLs yes?

**Comment by khalwat** [comment]
Alright so I did a test, and everything is working for me as expected.

Global SEO settings:

![google chromescreensnapz1271](https://user-images.githubusercontent.com/7570798/43152475-a24e9df2-8f3c-11e8-965c-83581f72ad30.png)

Content SEO settings:

![google chromescreensnapz1272](https://user-images.githubusercontent.com/7570798/43152487-ab699964-8f3c-11e8-92a9-cb9737a5da0c.png)

First entry with a blank (no override) SEO Settings field:

![google chromescreensnapz1273](https://user-images.githubusercontent.com/7570798/43152524-bfc07644-8f3c-11e8-9aff-cb49aa58932c.png)

Second entry with the Twitter Card set to be a Large image in the SEO Settings field:

![google chromescreensnapz1274](https://user-images.githubusercontent.com/7570798/43152551-ce8640dc-8f3c-11e8-960a-c2e7cb115c41.png)

**Comment by khalwat** [comment]
So here's what I think is happening. For the Content SEO settings and the preview image, SEOmatic uses the _first entry_ to give you something to preview.

So it's likely you made changes to whatever the settings should be to the first entry, and SEOmatic is displaying the end result in the Content SEO preview.

Which I'll admit is probably a bit confusing.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/1f18eeb5f1f252fcb5e615d10044b2f9a513eb6d

**Comment by baileydoestech** [comment]
Perfect works like a charm now!

**Comment by khalwat** [comment]
Great! Just so we're clear, this was always just a cosmetic issue with the preview shown in Content SEO; the actual metadata would have always been correct.
