### ISSUE TITLE
seomatic.helper.paginate caching wrong canonical, next, and prev

### ISSUE THREAD

**Issue by joshworden** [nystudio107/craft-seomatic#175]
So I’m experiencing a weird issue using {% do seomatic.helper.paginate(pageInfo) %} in a paginated query. Seomatic is caching the wrong title (set manually in the tempate), canonical etc (it caches whatever happened in the first request), and doesn’t properly render them on the paginated URLs. It gets cached with the first requested page, and renders that page title for all other requests of the paginated query, regardless of the page #.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/00b3bd68f5ccaf64d5140e319a17748900f27802
