### ISSUE TITLE
Extra space issues

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#176]
I just hit this weird issue. One of the content editors used this in the `canonical` url for a page:

```
<space>https://www.domain.tld/page/subpage/
```

This was rendered as

```html
<link href="https://www.domain.tld/ https://www.domain.tld/page/subpage/" rel="canonical">
```

Might be worth removing spaces from the beginning and the end of user editable fields.

We are using v3.1.3 with craft 3.0.16.1.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/3d14962fdbcf5c6c5204cfbee2ab50cea2adb9f2
