### ISSUE TITLE
Variable "seomatic" does not exist in Twig Template

### ISSUE THREAD

**Issue by sergeifilippov** [nystudio107/craft-seomatic#18]
When navigating to route `/cp/seomatic/global/general/default`, Craft throws `Variable "seomatic" does not exist.`

`vendor/nystudio107/craft-seomatic/src/templates/_includes/googlePreview.twig at line 1`

`{% set titleArray = seomatic.title.get('title').renderAttributes() %}`

### Server Stack:

- Seomatic beta 4
- Craft Pro 3.0.0-RC15
- yii 2.0.14.2
- nginx 1.13.9
- php7.1 - 7.1.14
- percona-mysql.5.7 MySQL 5.7.21

**Comment by khalwat** [comment]
So I have a guess... and that guess is that you have some other plugin installed that is doing something with Twig in its `init()` method.

**Comment by khalwat** [comment]
We think this might have to do with the Guide plugin: https://github.com/wbrowar/craft-3-guide

**Comment by khalwat** [comment]
@sergeifilippov Can you tell me if this is still happening with beta.6?

**Comment by sergeifilippov** [comment]
Still is :(. i even disabled the `Guide` plugin to test.

![image](https://user-images.githubusercontent.com/123676/37498918-bb1ed4f0-2925-11e8-997f-1ad4f216a6cc.png)

### Yii Debug Bar

![image](https://user-images.githubusercontent.com/123676/37498889-9c4a7462-2925-11e8-97d9-6909ef22d237.png)

**Comment by sergeifilippov** [comment]
After more debugging and some elbow grease I tacked it down to another extension.

[CP Clear Cache](https://github.com/mmikkel/CpClearCache-Craft)
