### ISSUE TITLE
Duplicate canonical URL's

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-seomatic#180]
Not really an issue, more of a nice to have...

Google lighthouse is discovering multiple canonical URLs which means sites using SEOMatic cannot quite get to the magically 100 score for SEO. 

![image](https://user-images.githubusercontent.com/3185073/43258713-993fa18a-90cb-11e8-9b8a-9909b5c9b3cd.png)

**Comment by khalwat** [comment]
This is an incorrect result; it's an error in LightHouse. See the thread here:

https://github.com/GoogleChrome/lighthouse/issues/3178

**Comment by baileydoestech** [comment]
FYI it looks like this has now been addressed in Lighthouse 3: https://developers.google.com/web/updates/2018/05/lighthouse3
