### ISSUE TITLE
Make Tracking scripts tabs not show as disabled

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#181]
OK, so in my staging environment, before I go to production, I tried to set up GTM. I entered all the info, hit Save, and then the tab shows as disabled. I know this is due to the staging environment, but this behavior can be very troublesome because it's false info IMO.

Better do something like you do with settings overwritten via a config file and just show a message that this won't render on not production env.

**Comment by XhmikosR** [comment]
BTW, can one use `production` instead of `live` for the environment config? If not, can you alias this?

**Comment by khalwat** [comment]
You can't alias it, but you can map it to whatever environment you like in the `config.php`

You're right, it probably should let you _appear_ to turn it on, even tho it's disabled in those environments.

**Comment by XhmikosR** [comment]
Can you clarify the related docs a bit? So that it's clearer?

Now, about hiding this, the problem is that we use a staging environment and I can't enable GTM since it just hides itself again :)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/68c69b241a98d0d0b000071be0dec60e8724e225

**Comment by XhmikosR** [comment]
Thanks!

Do you think maybe you could show a warning like you do about the environment? So that there's a visual hint that this doesn't any effect unless the environment is production?
