### ISSUE TITLE
SEO Title source in Content SEO not always working

### ISSUE THREAD

**Issue by emily-ep** [nystudio107/craft-seomatic#186]
We have a load of entries on the same channel and some are pulling through the entry title as set in the SEOmatic field and some are showing the website title twice. See here:

Title Source set to entry title:
<img width="1136" alt="screen shot 2018-07-30 at 15 37 43" src="https://user-images.githubusercontent.com/35136442/43404118-a933d958-940e-11e8-97c1-570811b8b156.png">

One entry not pulling through the entry title:
<img width="1625" alt="screen shot 2018-07-30 at 15 28 28" src="https://user-images.githubusercontent.com/35136442/43404274-fbf6d370-940e-11e8-9468-aa498b12adeb.png">

One entry in the same channel pulling through the entry title:
<img width="1619" alt="screen shot 2018-07-30 at 15 29 30" src="https://user-images.githubusercontent.com/35136442/43404286-01146502-940f-11e8-9842-8a2986bb1fba.png">

There are quite a few entries not pulling through the correct title and I can't tell what the common thread between them is. I'm thinking this might be an issue with SEOmatic itself?

Set up:
Craft CMS 3.0.13.2
SEOmatic 3.1.6

Thanks!

**Comment by khalwat** [comment]
So the preview in the Content SEO section is always going to show a preview from the first entry... so since that is named "Bliss" (presumably?) that's what you're going to see there.

The sidebar when you are previewing an entry, though, should always show the correct title for that entry (assuming the entry has been saved).

So my question to you is... when you view these entries on the frontend, is the title set correctly?

**Comment by emily-ep** [comment]
Ah! No, sorry, I should have been more clear. The title is also not working on the frontend. Both the tab in the browser and the title meta tag in the source also say 'Bliss | Bliss' rather than 'How my time on the neonatal unit led to an OCD diagnosis – Laura’s story | Bliss' as I expect.

**Comment by khalwat** [comment]
Yeah that definitely should not be happening... but I'm not sure its purely a bug in SEOmatic... or if it is, it's likely an edge-case. Because this would definitely be something that a whole lot more people would be noticing as wrong.

So then we need to look at what is specific to your setup. Are you using multiple entry types? Are you using Craft's standard routing for injecting elements in templates? Any other data points you can suggest that might help narrow this down?

Also just as a sanity check, go to SEOmatic -> Content SEO -> click on the section in question, and then click on Save. You can also try clearing the SEOmatic caches via Utilities -> Clear Caches.

**Comment by emily-ep** [comment]
Okay so I have done those sanity checks already but I did them again just to be sure and no change.

So after more investigation this is happening on all channels. We're using multiple entry types on one channel and the rest have just one entry type, but the issue is on all channels.
Here are the channel settings for one of them. The rest are set the same (using title field etc): 
<img width="1779" alt="screen shot 2018-07-31 at 14 21 07" src="https://user-images.githubusercontent.com/35136442/43472571-aa752a10-94e5-11e8-9569-cf48b6f9d047.png">

If it helps, here are the settings we're using for SEOmatic:
<img width="774" alt="screen shot 2018-07-31 at 17 21 51" src="https://user-images.githubusercontent.com/35136442/43472792-4da46bba-94e6-11e8-8cf7-b82ef9eaf983.png">

Here are the general settings as well:
<img width="841" alt="screen shot 2018-07-31 at 17 34 09" src="https://user-images.githubusercontent.com/35136442/43473436-07637900-94e8-11e8-9b98-f8b54b5b5127.png">

Also this is happening locally as well as on staging and live environments. We're wondering whether it could be something to do with parse order as it seems like it's just not finding the entry so it's falling back to the site-wide settings for SEOmatic. Could this be a thing? Is there anything that might be affecting that? 

I'm struggling to think what else could be affecting it. I've checked that it's not entries that contain certain components. There still seems to be no pattern between the entries which are not working so it's super confusing but I'll keep investigating.

Thanks!

**Comment by khalwat** [comment]
I'll see if I can work up a test case where this happens.

At some point, I might need access to your site or a copy of your db to properly debug it.

**Comment by khalwat** [comment]
So @emily-ep here's basically how it works. When a request happens, SEOmatic populates the meta containers with defaults. The first container is the Global container, which you control via the Global SEO settings in SEOmatic.

Then it looks for an element that matches the current request URI; e.g. `/blog/my-cool-post` matches the `entry` with the slug `my-cool-post` then it loads the meta container for the section that the matched element is from.

It layers that on top of the global container, overriding any settings with the match element's settings. Then if you have an SEO Settings field in the layout of that entry, it layers those settings on top.

SEO Settings field > Content SEO > Global SEO

What I think is likely happening here is that for whatever reason, apparently it's failing to find a matched `entry` and so it's falling back on the Global settings.

Unless you're doing some kind of custom routing, it makes no sense to me that this would just be failing, as it's a pretty basic part of how SEOmatic works. And it makes even less sense to me that it would be happening for _some_ entries, but not others.

**Comment by emily-ep** [comment]
Okay yeah that sounds the most likely. As far as I'm aware we're using regular routing.

I can give you access to the staging site where the bug is also happening? If you send me your email address I can send you the login details.

Thanks!

**Comment by khalwat** [comment]
You can shoot me the login credentials at:

andrew@nystudio107.com

I assume I can make non-destructive changes to an entry to experiment on the staging server?

Also it's possible to really debug it, I might need an ssh login as well. Here's my public ssh key:

`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFBiCxqUe7fi91zrVBbchc+ioCt7O13O1Dn/OIhG0jpTjV12o0jZLTbRU1/d/Am6Bxf/KlgrWLcEB5l+xs9tpPSfMIGXC9yUjl5LHR3dHMuF2PEuBLxThPBCCG5FGiQHT9vEMi8yXgRw8844AnIK5ik/Re2ozqrRyPGy8NLw7ZtmyqEX5yMHQpimdpkefN3PkyOfWOupy3EAZU7nHRn7YbmwgefkxWujlgxkyjCMavdBeJKezpZM+IHR27yno4/4SwKsFOIF1CrFCSozmgSOmA9LL3rv+aJtXoA7yq9VptFZ2FAebOdgn/nEoiVVYnbeWCdzQyp0veCS8Uk2R+7dWR andrew@kotak-2.local`

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/c2778b03534a1a019a3a789646d5437d14c9769a

For references, this happened if an Entry was first saved as a Draft, and later on was published.
