### ISSUE TITLE
seomatic.meta.seoTitle and seomatic.helper.paginate do not work on a paginated query

### ISSUE THREAD

**Issue by joshworden** [nystudio107/craft-seomatic#187]
Manually setting page title using `{% do seomatic.meta.seoTitle %}` doesn't work on a simple paginated query that has a `{% cache %}` tag anywhere in the template. Similarly, `{% do seomatic.helper.paginate %}` doesn't work either.

Instead, SEOmatic seems to be caching the first query regardless of the page number. So for instance, if I clear all cache, and query p2, that page title, canonical link, and next/prev tags will be cached and served for all pages (p3, p4 etc will all show the incorrect p2 canonical link).

Here's an example template:

```{% import 'macros' as macros %}
{% import 'site-macros' as siteMacros %}
{% extends "_layout" %}

{% block content %}
	{% if craft.app.request.pageNum > 1 %}
		{% do seomatic.meta.seoTitle(seomatic.meta.seoTitle ~ " - Page " ~ craft.app.request.pageNum ) %}
	{% endif %}

	{% cache globally using key craft.app.request.pathInfo ~ '/p' ~ craft.app.request.pageNum %}
	{% minify %}

 	<div class="container">
		
		{% set blogQuery = craft.entries.section('blog').limit(8).with('blogPostImage') %}

			{% paginate blogQuery as pageInfo, entries %}

			{% do seomatic.helper.paginate(pageInfo) %}

			{% if entries|length %}

				{{ siteMacros.blogList(entries, { columns: 2 }) }}

				{{ macros.pagination(pageInfo) }}

			{% endif %}
	</div>

	{% endminify %}
	{% endcache %}

{% endblock %}
```
Remove the cache tag and it works fine. 

And here's the really strange part: even if none of the seomatic calls are enclosed in the `{% cache %}` tag, as long as there's a `{% cache %}` tag anywhere in the template it doesn't work. It still caches the first query and serves that for all pages.

So for example, this also doesn't work:

```
{% import 'macros' as macros %}
{% import 'site-macros' as siteMacros %}
{% extends "_layout" %}

{% block content %}
	{% if craft.app.request.pageNum > 1 %}
		{% do seomatic.meta.seoTitle(seomatic.meta.seoTitle ~ " - Page " ~ craft.app.request.pageNum ) %}
	{% endif %}

 	<div class="container">
		
		{% set blogQuery = craft.entries.section('blog').limit(8).with('blogPostImage') %}

			{% paginate blogQuery as pageInfo, entries %}

			{% do seomatic.helper.paginate(pageInfo) %}

			{% if entries|length %}

				{{ siteMacros.blogList(entries, { columns: 2 }) }}

				{{ macros.pagination(pageInfo) }}

			{% endif %}
	</div>

	{% cache globally using key craft.app.request.pathInfo ~ '/p' ~ craft.app.request.pageNum %}
		<!-- Hello world -->
	{% endcache %}

{% endblock %}
```

**Comment by khalwat** [comment]
So I definitely can't replicate it not working by just having the `{% cache %}` tags present on the page; I think what you're running into is that the SEOmatic cache has already been established.

If you clear the SEOmatic caches, and try your example above, I think you'll find that it works properly.

But that doesn't help us in terms of fixing the root problem, which is that you want to cache the query, from which you can then `paginate` things... but if you put the `seomatic.helper.paginate(pageInfo) ` inside of the `{% cache %}` tag, it's not going to execute.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/162cc5643477b0b0f05e1b635192bc6178447b61

**Comment by khalwat** [comment]
@joshworden here is the code in my test template that's working fine for both caching and pagination (and the next/prev links)

```
{# @var craft \craft\web\twig\variables\CraftVariable #}
<!DOCTYPE html>
<html>
<head>
</head>
<body>

<div class="container padded-both banded">
    {% if craft.app.request.pageNum > 1 %}
        {% do seomatic.meta.seoTitle(seomatic.meta.seoTitle ~ " - Page " ~ craft.app.request.pageNum ) %}
    {% endif %}

    {% cache %}
        {# get all entries #}
        {% set blogQuery = craft.entries.section('blog').limit(2) %}

        {% paginate blogQuery as pageInfo, entries %}
        {% do seomatic.helper.paginate(pageInfo) %}

        {% if entries|length %}

            {% for entry in entries %}
                <p>{{ entry.title }}</p>
            {% endfor %}
        {% endif %}
    {% endcache %}
</div>

</body>
</html>
```
