### ISSUE TITLE
Sitemap settings not available for user group

### ISSUE THREAD

**Issue by 43north** [nystudio107/craft-seomatic#188]
Having a problem where the sitemap option under Content SEO is not available for a user group, despite having been given permission to access all SEOmatic settings. Under Content SEO for each section, it only shows General, Twitter and Facebook options. Running Craft 3.0.18 and SEOmatic 3.1.6.

![screenshot 2018-08-02 12 51 40](https://user-images.githubusercontent.com/1050192/43561683-1324cf16-9653-11e8-9df0-f287aece036a.png)

![screenshot 2018-08-02 12 51 17](https://user-images.githubusercontent.com/1050192/43561684-134f480e-9653-11e8-9146-3347655282de.png)

**Comment by khalwat** [comment]
Ooops! Fixed in https://github.com/nystudio107/craft-seomatic/commit/7a4af5a991168bc74280618cbbff897ca9958ea1
