### ISSUE TITLE
Unable to find the template "_sidebars/entry-preview.twig"

### ISSUE THREAD

**Issue by sergeifilippov** [nystudio107/craft-seomatic#19]
Entry creation view sidebar showing twig error relating to a missing template.

```
Error rendering `_sidebars/entry-preview.twig` -> Unable to find the template “_sidebars/entry-preview.twig”.
```

![sample event - richmond mall 2018-03-16 00-17-18](https://user-images.githubusercontent.com/123676/37460200-67aab616-28af-11e8-9797-1058adf43906.png)

### Server Stack:

Craft Pro 3.0.0-RC15
yii 2.0.14.2
Seomatic beta 3
nginx 1.13.9
php7.1 - 7.1.14
percona-mysql.5.7 MySQL 5.7.21

**Comment by khalwat** [comment]
So I have a guess... and that guess is that you have some other plugin installed that is doing something with Twig in its `init()` method.

**Comment by sergeifilippov** [comment]
Most likely it's the **Guide** Plugin

https://github.com/wbrowar/craft-3-guide

**Comment by khalwat** [comment]
Ah yes. I made some adjustments in beta.6 that _might_ make this better. I'll contact the author though.
