### ISSUE TITLE
Update broke site

### ISSUE THREAD

**Issue by keithmancuso** [nystudio107/craft-seomatic#191]
Ran an update to the latest verison and getting an error 

Call to a member function getAttributes() on string, see full error here?
<img width="1602" alt="screenshot 2018-08-05 18 54 57" src="https://user-images.githubusercontent.com/275913/43690931-1516f9d0-98e1-11e8-82dc-f2fe23f2763b.png">

**Comment by keithmancuso** [comment]
Its interesting cause you can load that doesnt involve loading and entry but if you go to and entry in the front end or backend i get the error

**Comment by khalwat** [comment]
Ooops, sorry! Fixed in https://github.com/nystudio107/craft-seomatic/releases/tag/3.1.11
