### ISSUE TITLE
Question about sitemap.xml lastmod

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#193]
Shouldn't sitemap.xml's lastmod change if one of the children sitemap's has new content? If I go to one of the sub-sitemap's I see the entries' lastmod is newer that the one in the index sitemap.

I'm using v3.1.11.

PS. Is there an email address I can contact you privately?

**Comment by khalwat** [comment]
So... that's arguable. When you submit a sitemap index, you're actually effectively submitting a number of sitemaps to Google. It's as if you've submitted a number of individual sitemaps, each of which will be consumed separately.

For support issues, github is probably the best place -- but if something needs to be private: andrew@nystudio107.com

**Comment by XhmikosR** [comment]
But wouldn't it make more sense if the lastmode was the lastmod date of the subentry?

Thanks for the email, I might need to contact your privately.

**Comment by khalwat** [comment]
It actually is:

```
                        $lines[] = '    <lastmod>';
                        $lines[] = '      '.$metaBundle->sourceDateUpdated->format(\DateTime::W3C);
                        $lines[] = '    </lastmod>';
```

Probably the sitemap index cache just is not cleared when an individual sitemap cache is cleared.

**Comment by XhmikosR** [comment]
So, this is a bug, right? Because I definitely see this on devMode too.

**Comment by khalwat** [comment]
Can you please provide me with some example output showing the error you're trying to report here? First the sitemap index that is showing an incorrect date, and then the sitemap itself that is showing a more recent modified date?

**Comment by khalwat** [comment]
Looks like this was what I suspected; the sitemap index cache just wasn't getting invalidated.

Fixed in https://github.com/nystudio107/craft-seomatic/commit/e803d475feeeeb901b78f752029c25b325b7847b

**Comment by XhmikosR** [comment]
@khalwat I'm still seeing this locally with dev-develop.

**Comment by XhmikosR** [comment]
Maybe you are wrongfully getting the first subitem's lastmod date? Because they seem to match in my case, but there are newer entries there.

**Comment by XhmikosR** [comment]
Again, please don't close the issues unless it's verified the issue is fixed. It doesn't make any sense.

**Comment by khalwat** [comment]
> Can you please provide me with some example output showing the error you're trying to report here? First the sitemap index that is showing an incorrect date, and then the sitemap itself that is showing a more recent modified date?

**Comment by XhmikosR** [comment]
Well, the index sitemap's lastmod is not my child's sitemap newest entry lastmod date.

**Comment by XhmikosR** [comment]
I honestly don't understand your approach to keep issues closed when it has not been confirmed by the reporter. That's so bad practice.

But anyway, here you go

index sitemap:
![1-index-sitemap](https://user-images.githubusercontent.com/349621/43961397-8cd01800-9cbd-11e8-99cd-083460c793cc.jpg)

homepage sitemap:
![2-homepage-sitemap](https://user-images.githubusercontent.com/349621/43961426-9b1e3400-9cbd-11e8-92ba-9e0e07477fa4.jpg)

**Comment by khalwat** [comment]
I've tested the fix, and it's working as expected. https://github.com/nystudio107/craft-seomatic/commit/93fdd9eab70eec7bb3be47185a873e405fd1c392

Will reopen the issue if you are continuing to have issues, once this version is released.

**Comment by XhmikosR** [comment]
@khalwat This is still present for me with 3.1.14.

**Comment by khalwat** [comment]
Please ensure you've tested it in local dev as well as staging and production environments, and that there is no additional level of caching that could be in the mix here?

**Comment by XhmikosR** [comment]
Tested locally, no caching.

For my homepage sitemap, the date changed after I saved the homepage again. For the other pages it still shows that old date even though I did edit some pages today.

**Comment by khalwat** [comment]
I did the exact same tests, and am seeing it change as expected.

I will redo them again.

**Comment by khalwat** [comment]
Argh, you're right -- this is a bug. I don't know how this worked in my initial testing. Fixed in https://github.com/nystudio107/craft-seomatic/commit/b31912f812a987834f58bfa825bd60f22b7afb6a

**Comment by XhmikosR** [comment]
Thanks!
