### ISSUE TITLE
Removing seomatic from {{ endBody() }} function

### ISSUE THREAD

**Issue by johnj24** [nystudio107/craft-seomatic#195]
Is there any way I can remove seomatic from rendering the json-ld scripts when I reference the `{{ endBody() }}` function?

I apparently need to use `{{ endBody() }}` if I want to pull `{% js %}..{% endjs %}` through from a partial template to a parent template using jQuery `.load()`.

It's not necessarily breaking anything. It's just code that doesn't need to be there.

More info here on why I have to use `{{ endBody() }}`: https://github.com/craftcms/cms/issues/3188

**Comment by khalwat** [comment]
Sure, so via Twig you can disable SEOmatic entirely for that template:

```
{% do seomatic.config.renderEnabled(false) %}
```

Or you can selectively disable whatever containers you want to disable, such as:

```
{% do seomatic.jsonLd.container().include(false) %}
```
