### ISSUE TITLE
Paginate error in DynamicMeta

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-seomatic#196]
PHP is throwing a type error in `DynamicMeta`.

```
Argument 1 passed to craft\web\twig\variables\Paginate::getPageUrl()
must be of the type integer, null given, called in
/project/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php on line 59
```

Adjusting the condition to check `currentPage` is set seems to rectify the issue. Perhaps it should be the `totalPages` instead?

```php
if ($pageInfo !== null && $pageInfo->currentPage) {
```

For context, there’s zero results on the page where I’m seeing this. The page info object getting passed to that method below, for reference.

```php
craft\web\twig\variables\Paginate#1
(
    [first] => null
    [last] => null
    [total] => 0
    [currentPage] => null
    [totalPages] => 0
)
```

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/a8185fd483cf4604e1d66f3916e01cdda8aa2ff3
