### ISSUE TITLE
Invalid sitemap.xml

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#198]
As reported in the other issue the current sitemap is invalid when it contains other namespaces likes image.

```
 Error Line 16, Column 16: Namespace prefix image on image is not defined
<image:image>

Error Line 17, Column 16: Namespace prefix image on loc is not defined
<image:loc>

Error Line 20, Column 18: Namespace prefix image on title is not defined
<image:title>
```

Not sure if other properties are being added in other cases; if so you should make sure you are adding the needed namespaces

**Comment by khalwat** [comment]
As stated in the other thread, you must have **Include Images & Videos in Sitemap** enabled in the Content SEO section for the namespace to be added.

You can see it added here: https://nystudio107.com/sitemaps/1/section/blog/1/sitemap.xml

...which also validates properly.

**Comment by XhmikosR** [comment]
All right, but this should not be allowed to happen IMO if it's invalid without any visual feedback or something.

**Comment by XhmikosR** [comment]
@khalwat: I don't think the current situation is right. I have images disabled in global sitemap's settings, but when one makes a new entry, it's toggled there by default. It should respect my global options, shouldn't it?

Otherwise one has to remember to disable it manually in each entry every time, which doesn't seem right to me.

**Comment by XhmikosR** [comment]
@khalwat: the current situation does not make any sense. I have sitemap images disabled yet every time a new page is created the option is enabled. And if the page has an image I get an invalid sitemap. Having to remember (or instruct the editors to remember) to toggle this off every time, does not seem ideal.

**Comment by khalwat** [comment]
I think your situation is atypical. Again, if you're going to have images included in a sitemap at all, it should be on in the Content SEO settings.

As for the default settings for the Field type, you can override them as you see fit: https://github.com/nystudio107/craft-seomatic#meta-bundle--container-settings

The global settings are what everything _falls back on_ if nothing more specific is set.

**Comment by XhmikosR** [comment]
But I don't specify **any** image in my pages nor in the Content SEO settings. Yet when I make a new Page, it has the Sitemap option to include images enabled by default.

**Comment by khalwat** [comment]
You're not understanding me.

1) Turn Image Sitemaps ON in any Content SEO section that _may_ have images included in the sitemap

2) Use a custom `seomatic-config` setup for the `fieldmeta` that has the defaults you want: https://github.com/nystudio107/craft-seomatic/tree/v3/src/seomatic-config/fieldmeta as discussed here: https://github.com/nystudio107/craft-seomatic#config-file-customization

The default setting for Fields are here: https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/fieldmeta/SitemapVars.php -- and set to `true` which is what most people will want.

If that's not what you want, override them.
