### ISSUE TITLE
Title differs from og:title

### ISSUE THREAD

**Issue by Lpizarro93** [nystudio107/craft-seomatic#199]
Hi,

I noticed that the <title> tags had different information to the meta title og:title tags. Is this a concern and if so, can it be fixed please? The issue occurs when you select to use the site name position before the title ![screenshot_726](https://user-images.githubusercontent.com/32542250/44158844-b0280800-a0ad-11e8-953e-129283ab43f4.png)

![screenshot_725](https://user-images.githubusercontent.com/32542250/44158855-b8804300-a0ad-11e8-8bb6-5663704bc93f.png)

**Comment by khalwat** [comment]
This is expected behavior; if you want to change it, you can change the **Twitter Site Name Position Source** and the **Facebook OpenGraph Site Name Position Source** settings.

By default, it does not include the site title, because both Twitter and Facebook display this information.
