### ISSUE TITLE
Unexpected hreflang displayed in <head> of entry

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#200]
In a multi site env. we have a channel with event entries.

Some of the events are not available in both languages.
So the entry is disabled on site level.

![screen shot 2018-08-16 at 09 58 20](https://user-images.githubusercontent.com/7466604/44195984-f8d9d280-a13a-11e8-82c4-ab99d7785cec.png)

But if we look in the source code of the event we still see a `hreflang alternate` to the entry that is disabled.

![screen shot 2018-08-16 at 09 49 13](https://user-images.githubusercontent.com/7466604/44195655-fd51bb80-a139-11e8-8afe-fdf7f30e1823.png)

**Comment by khalwat** [comment]
Interesting. I do this: 

```
                $url = $elements->getElementUriForSite(Seomatic::$matchedElement->getId(), $site->id);
                $element = $elements->getElementByUri($url, $site->id, true);
                if ($element !== null) {
```

...to figure out the URLs to add. I'll see if something might be flawed in this logic.

**Comment by khalwat** [comment]
I didn't set up a test-case for it, but I'm pretty sure this will take care of it: https://github.com/nystudio107/craft-seomatic/commit/3ace9b38f651741a65bac3f5d58ff315ef64abd4

You can pull from `dev-develop` if you want to confirm.

**Comment by boldenamsterdam** [comment]
@khalwat issue is now fixed with your change!

THNX!
