### ISSUE TITLE
Integrating Salesforce Lightning Error

### ISSUE THREAD

**Issue by Lpizarro93** [nystudio107/craft-seomatic#203]
We have SF lightning edition and would like to integrate our CRM (assuming it's Salesforce Lead option) to the forms. We've completed all the steps, however we get this error when authenticating:

cURL error 6: Could not resolve host: .salesforce.com; Unknown error (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) - What could be the issue here?

Thanks,

**Comment by khalwat** [comment]
I don't think this has to do with SEOmatic? @Lpizarro93
