### ISSUE TITLE
Commerce product types not showing in 'Content SEO'

### ISSUE THREAD

**Issue by tomdeleu** [nystudio107/craft-seomatic#204]
Title says it all really.

I have a fresh Craft 3 / Commerce 2 installation with SEOMatic installed. (everything up to date)
But the product types are not shown in the Content SEO settings section. All my other structures / channels are fine. Just not the product types.

Any pointers or things I can try?

**Comment by khalwat** [comment]
So I'm going to guess that you installed SEOmatic first, and Commerce later.

When SEOmatic is installed, it makes the metabundles for all of your sections and such. If you add them after the fact, it will add them dynamically as you visit the Section/Category Group/Product pages in the backend.

So you can either visit the Product pages in the AdminCP or you can uninstall and re-install SEOmatic (but you will lose configuration data if you do that).

Perhaps it should try creating these SEOmatic sections any time you visit Content SEO...?

**Comment by tomdeleu** [comment]
I actually think I installed Commerce first and not the other way. Wouldn't bet my life on it, but as I remember I did it in that order.

I just tried to visit some individual product pages in the admin but it had no effect. The product types do not appear in the Content SEO section. (I even modified some SEO titles / descriptions in the SEOmatic field on the product, to try and trigger it, but that had no effect either)

I would rather keep re-installing as the last method to try, because I do have a lot of settings applied at this point, so it would cause quite some rework.

**Comment by khalwat** [comment]
So now I'm super confused. What version of SEOmatic do you have installed, and what version of Craft Commerce?

**Comment by khalwat** [comment]
I see you say "everything up to date" -- but just confirming. Also do your Products Types have public URLs?

**Comment by tomdeleu** [comment]
Don 't worry, I would like to see the same questions confirmed haha:

Craft Pro 3.0.20
PHP 7.1.12
Commerce 2.0.0-beta.7
SEOmatic 3.1.14

Product types have public URL's yes. Example: https://cl.ly/1h242a3t161Y (not sure if the URI format is the best way to achieve what I want but hey... It is what it is for now :) )

**Comment by khalwat** [comment]
Can you hit me up on the Craft Slack as `andrew.welch` and let's do a screen share to see what might be going on here?

**Comment by tomdeleu** [comment]
Sure!

**Comment by khalwat** [comment]
This ended up being that @tomdeleu ran into a bug in older versions of SEOmatic where if you renamed a Section/Category Group /Product handle, it wouldn't properly propagate the change down to the meta bundles.

This has been fixed in subsequent versions of SEOmatic. The solution was to delete the corresponding `seomatic_metabundles` from the db, and let SEOmatic recreate them.
