### ISSUE TITLE
TypeError caused by DynamicMeta helper

### ISSUE THREAD

**Issue by juresrpcic** [nystudio107/craft-seomatic#205]
I get this error on a category entry page (a category that is "promoted" to be a full page).

```
Argument 1 passed to craft\services\Elements::getElementByUri()
must be of the type string, null given, called in
C:\web\mywebsite\vendor\nystudio107\craft-seomatic\src\helpers\DynamicMeta.php
on line 481
```

This issue is probably caused by this setting in my base twig:

```twig
{% set element = entry ?? category ?? null %}
{% if element is instance of('craft\\elements\\Category') %}
	{% set entry = category %}
{% endif %}
```

Which is really useful when using a generic Matrix page builder attached to both entries and category pages.

**Comment by juresrpcic** [comment]
Did some more testing, the issue remains even if I disable my "assign entry to category" hack in my base twig, to it's probably just due to a category page not having the same properties as a regular entry page.

**Comment by khalwat** [comment]
So the issue here is that SEOmatic is doing this:

```
                $url = $elements->getElementUriForSite(Seomatic::$matchedElement->getId(), $site->id);
```
And that's returning a `null` URL for some reason, despite the fact that an element matched as being injected into the templates by Craft.

I certainly can (and should) put in a check for null here, but I think there may be some other strange behavior going on here as well...

**Comment by juresrpcic** [comment]
If it helps, the website in question is also multi-site... I see your point, but not sure what exactly is causing this. Maybe once I set up SEOmatic more I'll figure it out (but will need that null check before I enable the plugin again).

**Comment by juresrpcic** [comment]
Also, if there's something you want me to run on that specific category page (like a dd() of the element) to help with debugging, let me know.

**Comment by khalwat** [comment]
I'm going to push a build to `dev-develop` to you shortly that you can give a try. Just have a few loose ends to tie up.

You can set your `composer.json` version for `'nystudio107/craft-seomatic'` to `'dev-develop'` in the interim if you like.

**Comment by khalwat** [comment]
Alright @juresrpcic go ahead and do a `composer update` to pull down the changes from `dev-develop` and let's see how we go.

**Comment by juresrpcic** [comment]
@khalwat have done it and it fixed the problem, thanks! Let me know if you need anything else tested.

**Comment by dowadidi** [comment]
I had the same issue and can confirm that the dev version fixed the issue.

**Comment by khalwat** [comment]
Great, this is live in SEOmatic 3.1.16 https://github.com/nystudio107/craft-seomatic/releases/tag/3.1.16
