### ISSUE TITLE
SEO settings field permission not correctly applied

### ISSUE THREAD

**Issue by xavierdemoor** [nystudio107/craft-seomatic#206]
![seomatic-bug](https://user-images.githubusercontent.com/27838311/44490904-f65a0a00-a65f-11e8-86cb-a927203f4e43.png)

When you give the permission to control SEO Image in the SEO settings field, you can control Transform SEO Image and SEO Image Transform Mode even if you don't have the permission.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/c8d5c215653550f052eb02d331cf1495a6278250
