### ISSUE TITLE
Override sitemap settings in template

### ISSUE THREAD

**Issue by bavocorteville** [nystudio107/craft-seomatic#207]
Is it possible to override the sitemap settings in a template?
I've tried this, but unfortunately it does not work.

```Twig
{% if not entry.projectContent.count() %}
    {% do seomatic.sitemap.sitemapUrls(false) %}
    {% exit 404 %}
{% endif %}`

**Comment by khalwat** [comment]
No, it's not possible to do that -- because your code won't even be run when the sitemap is loaded.

What are you trying to achieve?

**Comment by bavocorteville** [comment]
Ok, that makes sense. 

I have a structure for my projects, but only projects with at least one item from a matrix field will get a detail page. I can disable them one by one, but I was looking for a better solution.

**Comment by khalwat** [comment]
The SEO Settings field will let you do that... just override the sitemap on pages as you see fit.

**Comment by bavocorteville** [comment]
Alright, thank you for your time!
