### ISSUE TITLE
Json class conflict error

### ISSUE THREAD

**Issue by marknotton** [nystudio107/craft-seomatic#208]
I've just installed the latest version 3.1.14 on Craft CMS 3.0.21. Directly after clicking "install" in the CMS I get the following error: **Cannot use craft\helpers\Json as Json because the name is already in use**

It seems to be that line 30 in the file `vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php` is not necessary. The JSON class doesn't appear to be used here.

Given that your last update was a few weeks ago, and I'm the first to report this... I'm not going to rule out that this may be something with my local setup. But it should be noted that this error occurs even when I try installing it on a completely clean Craft installation too.

Happy to do further testing if you can suggest anything. 

```
yii\base\ErrorException: Cannot use craft\helpers\Json as Json because the name is already in use in /Users/marknotton/Clients/***/Website/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php:30
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
Copy Stacktrace Search Stackoverflow Search Google Error
PHP Compile Error – yii\base\ErrorException
Cannot use craft\helpers\Json as Json because the name is already in use
1. in /Users/marknotton/Clients/***/Website/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php at line 30
21222324252627282930313233343536373839                    use nystudio107\seomatic\models\jsonld\BreadcrumbList;
use nystudio107\seomatic\models\jsonld\Thing;
use nystudio107\seomatic\models\MetaJsonLd;
 
 
use Craft;
use craft\base\Element;
use craft\errors\SiteNotFoundException;
use craft\helpers\DateTimeHelper;
use craft\helpers\Json;
use craft\web\twig\variables\Paginate;
 
use yii\base\Exception;
use yii\base\InvalidConfigException;
 
/**
 * @author    nystudio107
 * @package   Seomatic
 * @since     3.0.0
                
2. yii\base\ErrorHandler::handleFatalError()
```

**Comment by khalwat** [comment]
So it is actually used on line 561: https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L561

The issue here is that I added my own `Json.php` class post facto, and it's in the same namespace as the `DynamicMeta.php` so it conflicts. No idea why I or anyone else hasn't seen this yet.

Fixed in: https://github.com/nystudio107/craft-seomatic/commit/f673ad8eea8e15394b5bd1a16d3327f7a6c83cc3

You can pull SEOmatic from `dev-master` should you like to test it.

**Comment by marknotton** [comment]
I've installed [dev-develop](https://github.com/nystudio107/craft-seomatic/tree/develop) and the error has gone. 

As always Andrew, very quick turn around. Thank you :)
