### ISSUE TITLE
Conflict in JsonLd class

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [nystudio107/craft-seomatic#209]
We're still getting a "Cannot use craft\helpers\Json as Json because the name is already in use" in helpers/JsonLd.php

As I'm sure you know this is because you also have a class called Json in the your own seomatic/helpers namespace.

This causes a fatal error on the front end of the website, could you possibly fix this?

**Comment by Wiejeben** [comment]
Not on my machine (PHP 7.2.9), but colleague is getting the same message. He is running PHP 7.0.0.

**Comment by Wiejeben** [comment]
Pull request: https://github.com/nystudio107/craft-seomatic/pull/210

**Comment by khalwat** [comment]
Thanks to @Wiejeben this has been fixed in https://github.com/nystudio107/craft-seomatic/commit/2780176db8c96be711e32ed33877597c0795bb33

**Comment by jlawrence-yellostudio** [comment]
@khalwat Thanks, I wonder why it worked in 7.2.x but not 7.0.x

**Comment by khalwat** [comment]
Language quirks ¯\_(ツ)_/¯
