### ISSUE TITLE
Entries using custom routes don't use Content SEO settings.

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#21]
I have a few custom routes set up for category pages on a few post types. I'm using custom routes so I can keep the user within the category when paginating prev/next entries, and showing related content.

SEOmatic doesn't treat my custom route entries the same as it would if it were viewed from the normal entry url. Instead, Global SEO settings are used.

Here's one of my custom routes: `'news/<category_slug:.*>/<post_slug:.*>' => ['template' => 'news/_entry'],`

What's the best way to get these entries to use the same Content SEO settings?

**Comment by khalwat** [comment]
What SEOmatic does to match Content SEO settings is it asks Craft to tell it what element should be injected at the current request URI. So it *should* match properly *if* you're getting an automatically propagated `entry` or `category` variable in your templates.

Is that not the case?

Sidenote: SEOmatic has a routine that can load metadata for a given URI manually:

```
seomatic.helper.loadMetadataForUri(URI, SITE_ID)
```

https://github.com/nystudio107/craft-seomatic#helper-functions-seomatichelper

I use this for my AMP pages, where there isn't an `entry` automatically injected, like this:

```
    {% set entrySlug = craft.app.request.getSegment(2) %}
    {% set entry = craft.entries.section("episodes").slug(entrySlug).one() %}
    {% do seomatic.helper.loadMetadataForUri(entry.uri) %}
```

**Comment by jsunsawyer** [comment]
Yeah, that's not the case.

I'm defining the entry based on the custom route.

I have an extended layout that handles some logic for entry/category/custom route views for my news pages.

In `_layout`:
```
{% if category_slug is defined %}
  {% set category = craft.categories.slug(category_slug).one %}
  {% set entry = craft.entries.section('news').slug(post_slug).one() %}
  {% set relatedTo = category %}
{% else %}
```

So what I'd like to do is just declare that the entry in my custom route is the same as it is without the category segment in the url.

In `_entry`: *edit – this could go in my _layout as well*
```
{% if category_slug is defined %}
  {# Tell seomatic to treat this entry as a normal news post #}
{% endif %}
```

**Comment by khalwat** [comment]
Okay so in that case just do what I mentioned above:

```
    {% do seomatic.helper.loadMetadataForUri(entry.uri) %}

```

**Comment by jsunsawyer** [comment]
Ah, misinterpreted that. Thanks!

**Comment by jsunsawyer** [comment]
Tested that out. It seems that only the `title` is updating. `og:url`, `canonical`, `description`, and `image` are not being updated. *Maybe some other fields too.*

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/4560d8506c4cb705e187b4399ce2d5da00f85935

**Comment by peter-tell** [comment]
Is there an equivalent of this in Seomatic for Craft 2.X?

**Comment by khalwat** [comment]
@page-8 not really, you'd be best off setting the metadata via Twig in the Craft 2.x version.
