### ISSUE TITLE
Google Webmaster Tools: "This is not a valid URL. Please correct it and resubmit."

### ISSUE THREAD

**Issue by whoisjuan** [nystudio107/craft-seomatic#212]
I manually submitted the Sitemap Index generated by SEOMatic in my Google Webmaster Tool, but Google is giving me URL errors for all the entries sitemaps.

All the elements in each of these sitemaps are throwing URL errors (for all the elements):
- https://www.waveguide.io/sitemaps/1/section/landingPages/1/sitemap.xml
- https://www.waveguide.io/sitemaps/1/section/mobileShots/1/sitemap.xml
- https://www.waveguide.io/sitemaps/1/section/patterns/1/sitemap.xml

I manually expected the sitemaps + checked the URLs validity in my browser, and everything seems to be correct.

What could be the issue?

**Comment by khalwat** [comment]
The only sitemap you should need to submit is your root `sitemap.xml` -- it contains links to the other sitemaps.

So for your site, the only one you need to submit is: https://www.waveguide.io/sitemap.xml

...but SEOmatic will actually submit the sitemap for you, so you shouldn't even have to do that.

In terms of the validity of the sitemaps, can you post the errors that Google is saying it has with those sitemaps?

**Comment by khalwat** [comment]
I noticed you have an `sitemap.xml` file already there:
```
<!--
 created with Free Online Sitemap Generator www.xml-sitemaps.com 
-->
```

...you'll need to delete this file for SEOmatic to work properly.

**Comment by whoisjuan** [comment]
You're right. There was an old sitemap.xml. Fixed that. I know that SEOMatic does the submission automatically, but I use the Google Webmaster Tools to track the index coverage and find crawling errors. That's how I found these. The exact errors I'm getting are: 

![image](https://user-images.githubusercontent.com/1447283/44754922-ce8ff980-aad8-11e8-82e2-05a07e1af3bc.png)

![image](https://user-images.githubusercontent.com/1447283/44754954-e7001400-aad8-11e8-98a9-e64836ffa18e.png)

![image](https://user-images.githubusercontent.com/1447283/44754972-fb441100-aad8-11e8-87d2-6c5122f2a206.png)

What's weird is that those are the sitemaps for each of the channels that have my entries. The sitemaps for my categories are not getting these errors.

Any clue?

**Comment by khalwat** [comment]
So what I need to see is the actual error, @whoisjuan  can you click on one of the example URLs to see what it's complaining about?

It looks to me like it's complaining about a url in an `<image>` tag in the sitemap...

**Comment by whoisjuan** [comment]
@khalwat this is the deepest I can go when trying to find the actual error:

![image](https://user-images.githubusercontent.com/1447283/44813114-dcec1d00-ab8d-11e8-989f-7ad8949a515d.png)

When I click on one of the links shown in the old console (the one from the above screenshots) it simply tries to take me to https://www.google.com/webmasters/tools/{Anchor-Text} where Anchor-Text is the ones that you see in the screenshots. That doesn't resolve to anything, and it shows a 404 inside the Google Console (I think that functionality is broken or buggy)

If you give me an email address, I can add you to the console, and you can inspect this yourself.

**Comment by khalwat** [comment]
So line 29 is:

```
<image:license>
    Df924F4C38Fe426Daab5Ebf615748Cde
</image:license>
```

This is supposed to be a URL to your license for the image as per: https://support.google.com/webmasters/answer/178636?hl=en

Just set it to nothing to have it not render, like this:

![google chromescreensnapz1337](https://user-images.githubusercontent.com/7570798/44813614-34978200-aba8-11e8-96a6-7f756b0780c3.png)

(I'm not sure what field you have it pulling data from currently)

**Comment by whoisjuan** [comment]
Thanks!! That solved the problem. I had all those fields mapping to the title. Appreciate it!
