### ISSUE TITLE
Issues with how SEOmatic utilizes Craft sites in a multi-site setup

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#213]
_**NOTE:** This is more of an issue with Craft and its multi-site setup than SEOmatic._

**Groups: Site vs Locale**

SEOmatic uses site groups to define unique sites. (https://github.com/nystudio107/craft-seomatic#multi-site-languagelocale-support)

Craft uses site groups for organization. (https://docs.craftcms.com/v3/sites.html#site-groups)

This allows users to:
- set up translations based on site group
- set up custom logic that targets sites within a site group

The original request for site group support was added with SEOmatic's use case in mind (https://github.com/craftcms/cms/issues/1668), but is not how groups are required to be used, which can cause confusion and inconsistency.

For instance, having my site groups based on languages makes SEOmatic think that each of those groups is its own site, so `og:locale:alternate` tags are only output for other sites within the same group, even though all sites within each language group should be rendered.

**Content is always rendered for a site**

Since there's no way to set a site as enabled or disabled, meta content for sites is always displayed.

Currently, our solution for this is to disable anything that SEOmatic would render for a disabled site (alternate tags, sitemaps, etc), and build these own our own, using some custom settings that we've defined in globals to detect whether a site is enabled or not. This takes away the usefulness of SEOmatic!

**What's missing?**

- There needs to be a clear differentiation between a site (unique website) and a locale (translated version of a website) (https://github.com/craftcms/cms/issues/3250)
- The ability to toggle a site on or off (https://github.com/craftcms/cms/issues/3005)
    - would allow plugins to omit the rendering of content for a disabled site
    - would allow options in a locale switcher to be disabled or hidden
    - would allow editors to draft/translate content before enabling a site

**Comment by khalwat** [comment]
Implemented via https://github.com/nystudio107/craft-seomatic/commit/89a5d50bdad0102b5a8ea769d19ba93a719ebedf

![google chromescreensnapz1336](https://user-images.githubusercontent.com/7570798/44809605-2db74200-ab9d-11e8-8654-f2499d763af1.png)

Turn this setting OFF if you're not using Site Groups to organize things by separate logical sites
