### ISSUE TITLE
Generating Sitemap is hitting the limits

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#214]
Looks like we are having an issue, we try to generate the sitemap for a blog section.

But the blog section contains 8000+ entries.

Is there a way that you can set some kind of pagination?
So we can generate the sitemap in batches of max 500/1000 entries per page.

We did found the limit option (max. 1000) and then the sitemap is generated so we are okay for now. But would be nice if we can include all 8000+ entries in the sitemap.

We already tried to change the execution time. But that didn't do the job. Unless we put it to 10-15 minutes.

**Comment by khalwat** [comment]
Ironically, I think the execution time for creating the sitemaps has gone up significantly due to some of the additional queries needed to support per-entry enabling/disabling of things.

FWIW, something that SEO companies such as Moz.com are experimenting with (and the reason that Limit control exists to begin with) is to provide only the new entries in the sitemap that they want Google to crawl. The assumption is that older entries, Google will have either already found, or will find organically.

They are putting their focus on putting into the sitemap new content that they want Google to discover, since typically newer content is what is more important to be "fed" into Google for indexing.

If something is removed from a sitemap, it is not removed from Google's index. It's just removed from the list of things that Google will scan when it processes your sitemap.

In any event, are we talking about reaching this limits in terms of CPU processing? If so, then I'd suggest:

-- Disabling **Include Images & Videos in Sitemap**
-- Disabling **Include Indexable Files in Sitemap**
-- Removing any SEO Settings fields that have per-entry sitemap settings
-- Setting the **Sitemap Limit** to something reasonable

Note that once created, SEOmatic does cache the sitemaps, so subsequent requests will be performant (the cache is, of course, broken when content is changed).

**Comment by boldenamsterdam** [comment]
Hi @khalwat 

Well at the moment what is happening is that the CPU will rise to 80-90% usage when it's starting trying to generate the sitemap for only the blog section. 
But after 60-120 seconds the job is getting canceled (server 500 error) because it's hitting the maximum execution time that is configured on the server. So in the end the sitemap will never be generated.

We did some test on our local machines trying to find out what would be needed to complete the job. But even with an execution time of 300 seconds the job got canceled.
So when we had set a max limit of 500 entries in the sitemap, the execution time was 120 seconds and we had a file size of 250kb.

If we would multiple these numbers with the total of 8200 entries we would end up with a file size of 4 MB. and an execution time of 32 min. We believe this is a little bit to much.

Disabling the include images & video-, indexable files in sitemap and removing the SEO Settings Field didn't work.

All the other sitemaps are being generated.

We will forward the information you provided from moz.com to our client.

**Comment by khalwat** [comment]
That seems very, very excessive. I am having a hard time understanding what would cause it to take 300 seconds to do 500 entries, that's quite slow.

I think a long term solution for something like this would be:

1) To identify what the actual bottlenecks are; for my tests locally, it isn't taking nearly that long to generate a sitemap
2) If the bottlenecks just can't be helped to either:
 - Break up the sitemaps into multiple pages as you mentioned
 - Have the generation of the singular sitemap take place in a background queue job where it does it in chunks

I'd really like some input on 1)  from you -- is there anything special about this Blog section? Is it using the SEO Settings field to individually adjust the status of certain entires?

**Comment by khalwat** [comment]
Yeah so just looking at the code without having to profile it, it went from doing very few db queries during the loop that generates the sitemap to doing a whole bunch of them to support the per-entry exclusion that you wanted.

There are some optimizations that I think could be done, but I'm not sure that'd get us within range.

**Comment by boldenamsterdam** [comment]
Hi @khalwat 

The 300 seconds was the maximum execution time we had set in the server config file. 
It took the server 120 seconds to generate a 500 entries sitemap. The file size was 250 kb.

We tried creating the sitemap of the blog section with and without the SEO Settings field. But both didn't succeed.

The blog section does have 3 different entry types. 
Not sure if that has any big impact on the DB queries?

**Comment by khalwat** [comment]
The number of entry types doesn't really matter. The following things would add to the number of db queries:

- Whether the site is multi-site or not (it needs to do an additional query per site to get the `hreflang` links)
- Whether or not you're including images/videos in the sitemap (it has to query for them per entry)
- Whether or not you're including indexable files in the sitemap (it has to query for them per entry)
- Whether or not you have an SEO Settings attached (it has to query to see whether to include/exclude on a per entry basis)

I'd need to profile it to see whether it's db-bound or CPU bound. Were you able to get any profiling data @boldenamsterdam ?

**Comment by khalwat** [comment]
I added some memoization caching to a bottleneck in the Sitemap generation that _might_ help: https://github.com/nystudio107/craft-seomatic/commit/d8ab7faa7cf0e186664503c2eb363885c887aa33

**Comment by boldenamsterdam** [comment]
Hi @khalwat ,

We have not been able yet to get any profiling data. What kind of stats are you looking for? Where can we find this?

We did run some tests between the `master branch` and `dev-develop` branch to see if there was a differents in execution time.

**Some PHP server info:**

```
$_SERVER['SERVER_SOFTWARE'] | nginx/1.6.2
max_execution_time 30
max_file_uploads 20
max_input_nesting_level 64
max_input_time 60
max_input_vars 1000
memory_limit 256M
```



> _**Master Branch**_

**Include Images & Videos in Sitemap** = FALSE
**Include Indexable Files in Sitemap** = FALSE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = 1000

Execution Time = **9 sec.**


**Include Images & Videos in Sitemap** = FALSE
**Include Indexable Files in Sitemap** = FALSE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = NONE (total entries 8165)

Execution Time = **NR**


**Include Images & Videos in Sitemap** = FALSE
**Include Indexable Files in Sitemap** = TRUE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = 1000

Execution Time = **14 sec.**

**Include Images & Videos in Sitemap** = FALSE
**Include Indexable Files in Sitemap** = TRUE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = NONE (total entries 8165)

Execution Time = **NR**


**Include Images & Videos in Sitemap** = TRUE
**Include Indexable Files in Sitemap** = TRUE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = 1000

Execution Time = **15 sec.**


**Include Images & Videos in Sitemap** = TRUE
**Include Indexable Files in Sitemap** = TRUE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = NONE (total entries 8165)

Execution Time = **NR**


> _**Dev Branch**_

**Include Images & Videos in Sitemap** = FALSE
**Include Indexable Files in Sitemap** = FALSE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = 1000

Execution Time = **11 sec.**


**Include Images & Videos in Sitemap** = FALSE
**Include Indexable Files in Sitemap** = FALSE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = NONE (total entries 8165)

Execution Time = **NR**


**Include Images & Videos in Sitemap** = FALSE
**Include Indexable Files in Sitemap** = TRUE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = 1000

Execution Time = **12 sec.**


**Include Images & Videos in Sitemap** = FALSE
**Include Indexable Files in Sitemap** = TRUE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = NONE (total entries 8165)

Execution Time = **NR**


**Include Images & Videos in Sitemap** = TRUE
**Include Indexable Files in Sitemap** = TRUE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = 1000

Execution Time = **19 sec.**


**Include Images & Videos in Sitemap** = TRUE
**Include Indexable Files in Sitemap** = TRUE
**Sitemap Alt URLs** = TRUE
**Sitemap Limit** = NONE (total entries 8165)

Execution Time = **NR**

**Comment by khalwat** [comment]
I meant profiling in terms of using something like Blackfire.io or NewRelic.com to get some performance data. That or if you can send me your db, can do some local timings.

I made some changes to the build in `dev-develop` that might help a little bit, but probably nothing drastic has changed, if you want to try it.

**Comment by khalwat** [comment]
Any word @boldenamsterdam ?

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-seomatic/commit/6a6e7b0b9801531b9e74ea924da58680519ecfa6

We now generate the sitemap via a queue job, and cache the result.
