### ISSUE TITLE
7.2 req in DaveChild/Text-Statistics

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#215]
Lord knows why, but a patch release (1.0.2 to 1.0.3) in https://github.com/DaveChild/Text-Statistics changed from requiring php 5.3 to 7.2…apparently everyone doesn't "do" semver

(╯°□°）╯︵ ┻━┻

At any rate – I'd say you should get rid of the carat and lock the version down to something that won't change.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/c0f553473bd45899c01a107645f5cfe68fde7356
