### ISSUE TITLE
[FR] - Entry Types

### ISSUE THREAD

**Issue by daniellefrapp** [nystudio107/craft-seomatic#216]
I have a question. Can you control the SEO fields at the entry type level rather then the section? 

So I have a section called Resources.

And here is all the pieces in those sections
 
index for all resources
Entry types: webinars, whitepapers, ebook, case studies
index for the individual Entry types
entry type called case study landing that has no index

each of these don't have the same number of meta fields, some I want to pull globally some I like to control at the entry level. Is this possible?

**Comment by khalwat** [comment]
Currently, no, there is no baked-in support for separate entry types in SEOmatic. I've been mulling over for a bit the best way to support them via the GUI.

One thing you could do is set the base defaults in the Content SEO section, and then use the SEO Settings field to allow for per-entry changes.

Of course, you can still do whatever you want via Twig: https://github.com/nystudio107/craft-seomatic#twig-templating

**Comment by daniellefrapp** [comment]
Cool thank you. I was about to go down the twig route but I wanted to check first.

**Comment by jan-dh** [comment]
Any chance this feature might get picked up? Entry types give an enormous flexibility to structure content in the CMS, however it's too bad that SEOmatic can't reflect those different content types on an entry type level. Specially for bigger websites a good default is really needed on that level. The GUI is just too much work to handle on a per entry base.

**Comment by khalwat** [comment]
The major issue here @jan-dh is the UX -- how do we present this information to the user.

And how do we do it in a way that doesn't add work for people who do not work the way you do. If they have common fields amongst their Entry Types that they use to pull images and content from, then we're potentially making them do 4-5x the work (depending on how many Entry Types they have) per Section.

The technical underpinnings of doing this are not difficult; coming up with a UX that works in a low-impact way is the more difficult part, and where the bulk of the work is.

**Comment by ScottHaggar** [comment]
Yep, got hung up on the same issue. Your rationale makes sense and I don't have any UX ideas for ya, but cracking that nut would make a great feature for future release.

**Comment by khalwat** [comment]
This is implemented in SEOmatic 3.3.0! https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.0

**Comment by jan-dh** [comment]
Yes! Thank you for this!
