### ISSUE TITLE
Update thru Cp dependency issue

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft-seomatic#218]
Trying to update to the latest release I get a dependency issue:

> Composer was unable to install the updates due to a dependency conflict.
> Composer output: Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for nystudio107/craft-seomatic 3.1.19 -> satisfiable by nystudio107/craft-seomatic[3.1.19].
> - nystudio107/craft-seomatic 3.1.19 requires davechild/textstatistics 1.0.2 -> satisfiable by davechild/textstatistics[1.0.2] but these conflict with your requirements or minimum-stability.
> 
> Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
> 
> User 1 Status 200 Route updater/index Log 101 Deprecated 0 Time 145 ms Memory 25.889 MB DB 84 9 ms Asset Bundles 16
>

**Comment by khalwat** [comment]
This was fixed in SEOmatic 3.1.19 as per: https://github.com/nystudio107/craft-seomatic/issues/215

So just update SEOmatic, and you should be all set.

**Comment by alanski66** [comment]
I think we have a recursion - I am trying to update to 3.1.19 when it occurs...

**Comment by khalwat** [comment]
Make sure there are no references to `davechild/textstatistics` in your root `composer.json` -- then doing `composer update` should work...

**Comment by khalwat** [comment]
You can also try making the version more explicit, with something like this:

```
        "nystudio107/craft-seomatic": "^3.1.20",
```

**Comment by khalwat** [comment]
Any luck @joomkit ?

**Comment by sergeifilippov** [comment]
I'm getting similar errors when running `composer require nystudio107/craft-seomatic:^3.1.20`

I've:

- run `composer clearcache`
- deleted `vendor` folder & `composer.lock` file
- made sure that `composer.json` does **not** have `davechild/textstatistics` mentioned

Error message:

```
  Problem 1
    - Can only install one of: davechild/textstatistics[1.0.2, 1.0.1].
    - Can only install one of: davechild/textstatistics[1.0.2, 1.0.1].
    - nystudio107/craft-seomatic 3.1.20 requires davechild/textstatistics 1.0.2 -> satisfiable by davechild/textstatistics[1.0.2].
    - Installation request for nystudio107/craft-seomatic ^3.1.20 -> satisfiable by nystudio107/craft-seomatic[3.1.20].
    - Installation request for davechild/textstatistics (installed at 1.0.1) -> satisfiable by davechild/textstatistics[1.0.1].
```

**Comment by alanski66** [comment]
Yeah. I changed the composer.json entry for seomatic to 3.1.20 and completely removed davechild and ran composer update. All good now thx

**Comment by khalwat** [comment]
@sergeifilippov see above
