### ISSUE TITLE
SEOMatic navigation not showing in menu

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft-seomatic#22]
I'm not seeing the menu navigation in the left nav column like your screenshots.

Craft 3 RC15
SEOMatic 3.0.0-beta.6
PHP 7.1.15

![screenshot 2018-03-15 16 23 58](https://user-images.githubusercontent.com/407465/37496039-808a1cf4-286d-11e8-8ae6-24ee1c9256a1.png)

**Comment by khalwat** [comment]
That's super-weird. Only on the Content SEO page, or on all of the pages? How are you even getting to Content SEO?

**Comment by mikestecker** [comment]
I was able to navigate to the Content SEO through the main SEOmatic link which goes to the dashboard and then clicking on the completion graph for Content

**Comment by mikestecker** [comment]
Also, you can see the code for the navigation isn't even outputting when I inspect the nav

![screenshot 2018-03-15 17 23 54](https://user-images.githubusercontent.com/407465/37497478-b9a22e98-2875-11e8-9965-681de1058618.png)

**Comment by mikestecker** [comment]
Here's a list of all my plugins in case one of them might be causing the issue:

Amazon S3	1.0.8
Cookies	1.1.9
Patrol	3.0.2
Mailgun	1.2.0
Element API	2.5.2
NSM Fields	0.0.10
FastCGI Cache Bust	1.0.6
PathTools	1.0.7
Simple Text	2.0.2
Anchors	2.0.3
Title Entries Field	1.0.5
Store Hours	2.0.6
Inlin	2.0.0
Stamp	2.0.0
Videos	2.0.0-beta.6
Minify	1.2.8
SVG Placeholder	1.0.3
ImageOptimize	1.4.23
Contact Form Honeypot	1.0.2
Contact Form	2.1.1
Typogrify	1.1.8
Control Panel Nav	2.0.3
Expanded Singles	1.0.3
Redactor	1.0.1
SEOmatic	3.0.0-beta.6

**Comment by khalwat** [comment]
So I'd immediately suspect Control Panel Nav	2.0.3
 -- can you try it without that installed?

**Comment by mikestecker** [comment]
That was it! I was actually thinking the same thing when I copied/pasted this list of plugins over to you.

**Comment by mikestecker** [comment]
Should I post an issue with @engram-design on the Control Panel Nav page and reference this?

**Comment by engram-design** [comment]
@mikestecker I noticed this when I installed SEOmatic as well, I'll be working on a fix shortly, but do feel free to create an issue on https://github.com/verbb/cp-nav/issues. I believe its an issue with CP Nav.

Sorry for the trouble @khalwat

**Comment by khalwat** [comment]
@engram-design if I'm doing something wrong, lmk!
