### ISSUE TITLE
Custom JSON-LD data

### ISSUE THREAD

**Issue by mikefrancis** [nystudio107/craft-seomatic#220]
Hi there,

I am trying to add some custom JSON-LD data, I was just wondering if there are any hooks to do this natively without having to fork the plugin?

**Comment by mikefrancis** [comment]
Ah have found it:

https://github.com/nystudio107/craft-seomatic#json-ld-meta-object-functions-seomaticjsonld

And it looks like the `offers` JSON-LD already exists, but how do you set it?

**Comment by khalwat** [comment]
There are some examples of working with JSON-LD objects in the documentation:

https://github.com/nystudio107/craft-seomatic#json-ld-meta-object-functions-seomaticjsonld

Let's say you want to add `offers` to the `mainEntityOfPage`, you'd do something like:

```twig
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}

{% set offersJsonLd = seomatic.jsonLd.create({
    'type': 'Offer',
    'name': 'Some prop',
    'url': 'Some url',
}) %}

{% do mainEntity.offers(offersJsonLd) %}

```
