### ISSUE TITLE
(Re)disable Content SEO for a Site's section after you've disabled that Section for the Site

### ISSUE THREAD

**Issue by frontedbe** [nystudio107/craft-seomatic#223]
When I disabled a certain section from a certain Site, the section is still available in the SEOMatic's Content SEO tab for that site, which it shouldn't? It will be more clear when you check the screenshots => [Screenshot A](https://cl.ly/0996f1daf4eb), [Screenshot B](https://cl.ly/754b9f00e13f)

It happens when you have a Section enabled for all Sites, then go to Content SEO for that section in a specific Site and save it, then go back to the Sections and disable it for that specific Site. The Section still occurs in the SEOMatic's Content SEO for that Site. Hope his makes any sense :D

**Comment by khalwat** [comment]
hmmmm. Yeah it probably shouldn't be in there! What version of SEOmatic are you using?

**Comment by frontedbe** [comment]
Latest => SEOmatic 3.1.20

**Comment by khalwat** [comment]
Will attempt to replicate, thank you!

**Comment by frontedbe** [comment]
Hi Andrew, experiencing a similar issue on a new multisite / multi language project => [screenshot](https://cl.ly/4c37e8527c02)

**Comment by khalwat** [comment]
Ah yes, this is something that SEOmatic currently doesn't take into account, but probably it should. It's a little bit sticky in terms of UX, but it can be done.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/7a33c65278f8320593d529254cd25927a257cb8a
