### ISSUE TITLE
[FR] Migrating from Sprout SEO

### ISSUE THREAD

**Issue by hisnameisjimmy** [nystudio107/craft-seomatic#224]
Is there a guide on migrating from Sprout SEO to Seomatic?

We're planning on moving to Craft 3 once Craft NEO is done being migrated, and we like the documentation and continuous improvement approach to Seomatic. However, migrating from Sprout seems like it would be a bummer, especially as we've used it to customize a lot of titles/meta.

Do you guys have any ideas on how to best approach this?

**Comment by khalwat** [comment]
So currently there is no migration tool, though I can keep this around as a FR.

Here's how I'd approach it tho; from the docs:

> If feasible, we think the best way to update sites using SEOmatic is to start fresh, and explore how the conceptual changes in the plugin affect how you use it. In most cases, you don't even need to use an SEOmatic Field, and the setup is cleaner and easier without it! We hope you love it!

Now I realize that you're saying that you customized things from an SEO POV on a per-entry basis; but modern SEO works best if it's pulling from content that's actually on the page. You might find that just setting up the Content SEO settings to pull / summarize from existing content fields is the easiest thing to do.
