### ISSUE TITLE
Content Section Sitemap Settings

### ISSUE THREAD

**Issue by awilli1186** [nystudio107/craft-seomatic#226]
When setting the `Structure Depth` setting for a structure section, I assumed the `All` option would output urls for all entries at any level of the structure, yet choosing this option outputs zero urls. If I select a specific level, it only outputs the urls for that level.

The field description `Controls a how deep to go into a Structure when adding URLs into the sitemap.` leads me to believe selecting the level will output all urls that level and down, but that does not appear to be the case.

**Comment by khalwat** [comment]
Hmmm, if setting it to `All` doesn't output the entire structure, then it's definitely a bug.

The number you choose specifies how many levels deep to go. So if you set it to `1` then it will only display the top level entries in a structure in the sitemap.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/db6c07998e22545479fb96bd52fb19e55d7c568f

**Comment by awilli1186** [comment]
Awesome thanks!
