### ISSUE TITLE
[FR] Possible to disable multi-site functionality?

### ISSUE THREAD

**Issue by elivz** [nystudio107/craft-seomatic#227]
I suspect I know the answer to this, but figured it's worth a shot: Is it possible to make SEOmatic use one configuration for all sites in a multi-site setup? I have four sites that will all need the exact same settings. I have spent a long time setting up all the Content SEO configurations, site identity, etc. on the first site, but it looks like I will now have to go through and make all the same edits for each of the other sites as well. And remember to make any future changes to all of the sites as well.

Obviously I see the logic for this from a flexibility standpoint. It just doesn't work well for my particular use case, unless I am missing something.

**Comment by khalwat** [comment]
Currently there is not, but this has come up before... and I'm mulling over what the best solution might be.

Options I've considered:

1 - Having a "master" site per site-group that it uses data from, and only overrides it with the specific site data if there is something entered there
2 - Having there be a button that copies the data from another site
3 - A way to just plain disable the multiple sites altogether

I'm not really sure what the right answer is, honestly. Would love input.

**Comment by elivz** [comment]
I'd probably lean towards #1, although I can see arguments for the others. I like the idea of being able to override specific fields from a sub-site, while falling back on the "master" site's data by default. On a big site it is just very time-consuming to get everything set up for one site, let alone to replicate that for each translation. Presumably even for a truly multi-lingual site, you would still want the similar settings under Content SEO (pulling from all the same fields, etc.). I imagine this has the potential to get fairly complex from an interface perspective and in your code though.....

Anyway, thanks for considering! I will probably go ahead and manually copy everything over for this project (since I can't imagine you will decide on and implement a solution before we need to launch), but it would be nice to have as an option for future projects.

**Comment by khalwat** [comment]
So a quick and easy way you can copy the data over is by looking in the `seomatic_metabundles` table with Sequel Pro or whatever your tool of choice is. It's just saved as JSON, you should be able to copy the containers you need without _too_ much fuss.

**Comment by Djive** [comment]
+1000 for this :)
We have much more than 4 sites which all share the exact same settings. 
Setting up SEO for all sites will be a very time consuming process.

Thinking option number 1 is the best but even option number 2 would be a huge time saver (something like 'Propagate seo settings across all enabled sites'

Looking forward to this!
Cheers

**Comment by khalwat** [comment]
The other thing I've been thinking of is potentially something very much like Craft's "translation method" for sections, etc. 

I think that might be overcomplicating things tho, and instead a better model might be just to have a "Master" for each Site Group -- and then if you want to change things on a site-specific level, you can.

Basically for each Site Group there would be a "Master" setting that can be override by site-specific settings as needed/desired, and they'd be coalesced into one meta bundle at runtime.

**Comment by Djive** [comment]
Yes, having a Master setting per Site Group sounds like the best and most flexible option for multi-site.
Do you have any hint on timetable for this? 
Definetly looking forward to this!

Thanks!

**Comment by exophunk** [comment]
For now, another option would be to simply "one time sync" settings from one site to another, as copying the settings in `seomatic_metabundles` to the row of the other site.

So you could add a button in the CP to `Sync from Site "English" to Site "German"` for example and simply copying the SEO settings to speedup the process if you have lots of sites.


If it helps anyone, here is a somewhat ugly SQL update command to copy all settings from site `1` to site `2`. Make sure you backup before and get your site id's right. (it only updates for content sections)

```


UPDATE seomatic_metabundles t1
SET sourceAltSiteSettings = (
	SELECT sourceAltSiteSettings from seomatic_metabundles t2
    WHERE sourceSiteId = 1
    AND t1.sourceId = t2.sourceId
), sourceDateUpdated = (
	SELECT sourceDateUpdated from seomatic_metabundles t2
    WHERE sourceSiteId = 1
    AND t1.sourceId = t2.sourceId
), metaGlobalVars = (
	SELECT metaGlobalVars from seomatic_metabundles t2
    WHERE sourceSiteId = 1
    AND t1.sourceId = t2.sourceId
), metaSiteVars = (
	SELECT metaSiteVars from seomatic_metabundles t2
    WHERE sourceSiteId = 1
    AND t1.sourceId = t2.sourceId
), metaSitemapVars = (
	SELECT metaSitemapVars from seomatic_metabundles t2
    WHERE sourceSiteId = 1
    AND t1.sourceId = t2.sourceId
), metaContainers = (
	SELECT metaContainers from seomatic_metabundles t2
    WHERE sourceSiteId = 1
    AND t1.sourceId = t2.sourceId
), redirectsContainer = (
	SELECT redirectsContainer from seomatic_metabundles t2
    WHERE sourceSiteId = 1
    AND t1.sourceId = t2.sourceId
), frontendTemplatesContainer = (
	SELECT frontendTemplatesContainer from seomatic_metabundles t2
    WHERE sourceSiteId = 1
    AND t1.sourceId = t2.sourceId
), metaBundleSettings = (
	SELECT metaBundleSettings from seomatic_metabundles t2
    WHERE sourceSiteId = 1
    AND t1.sourceId = t2.sourceId
)
WHERE sourceSiteId = 2
AND sourceBundleType = 'section'
```

**Comment by zenoachtig** [comment]
Is there any progress on this? I'm currently working around having to manually set each field for each site by dynamically setting the SEO meta in my Twig templates. However, this leaves the Dashboard thinking that no fields have been set, which would confuse my client. If there's a better solution I'd love to hear it, as well as a timetable on the Master Site idea :)

**Comment by khalwat** [comment]
@zenoachtig can you give me some more specifics on the setup you have where this is becoming an issue for you?

Do you have many sites that are localizations of the main site or...?

**Comment by zenoachtig** [comment]
Thanks for the instant reply!

> @zenoachtig can you give me some more specifics on the setup you have where this is becoming an issue for you?

I am building a site for a hotel chain, with each site representing a separate hotel containing bedrooms, meeting rooms, and other pages. I've got one big "Hotels" site group for all the hotels, and a "General" site group for the main site (and possible other main sites). I've already turned off the "Site Groups define logically separate sites" option, because I'm not using them that way.

When I set up the SEO fields to pull their values from content fields for one site, and then go look at the Dashboard of another site, again none of the sources are set up correctly. Next to it being annoying to source the fields by hand over and over again, it also means that my client needs to remember to set these fields correctly when they add a site (= hotel) to their chain.

Having a Master setting would greatly improve this. Or am I missing a setting / functionality somewhere?

**Comment by khalwat** [comment]
So you're not missing a setting; right now you need to manually fill in each section, although you can automate it somewhat via:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#customized-setup

In terms of status, I'm still deciding on what the best way to do this might be. While I like the idea of a "master" page, this doesn't really have an analogue in terms of how Craft works.

_Probably_ the best way to approach it might be to mimic Craft, and allow you to set up a propagation method:

![Screen Shot 2019-12-11 at 4 53 27 PM](https://user-images.githubusercontent.com/7570798/70663649-c957af00-1c36-11ea-98f8-3a9e1fe2f005.png)

...and then the question is whether this should be a global setting (that affects Global SEO, Content SEO, Site Settings, etc. or whether it should be changeable on a per-section basis.

I'm guessing the latter, which then complicates things a bit more in terms of where those settings would be... probably in the Content SEO listing.

**Comment by khalwat** [comment]
So I think this works pretty well:

<img width="272" alt="Screen Shot 2020-02-21 at 11 03 47 PM" src="https://user-images.githubusercontent.com/7570798/75086558-bc432000-5503-11ea-8fe0-74d0d799a86d.png">

Because it radically speeds up the entry process (tho granted, you do have to copy the data multiple times). But I think in cases where you might want to start out with the same data, but then change it later, this additional "manual" step is probably a better fit than the "Propagation Method" I discussed above.

**Comment by Djive** [comment]
how to activate this copy thing :)

**Comment by khalwat** [comment]
It'll be in the next release :)

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/a83ed957c7105972e6282f1ea73e65a99fe031ce
