### ISSUE TITLE
Breadcrumbs don't render in multi site setup

### ISSUE THREAD

**Issue by goemaeret** [nystudio107/craft-seomatic#228]
Hello,

I have a Craftcms3 project with a multiple sites setup like this (they are all in the same single group):

<img width="993" alt="schermafbeelding 2018-09-20 om 08 13 30" src="https://user-images.githubusercontent.com/1711221/45799251-21f70100-bcad-11e8-9142-a53b13b64d10.png">

Problem is that the function `seomatic.jsonLd.get('breadcrumbList')` only returns a single list item 'home' on every page.

Am I missing something? Some sort of setting that needs to be enabled/disabled to maken the breadcrumbs work correctly in a multi site environment?

Thanks in advance,
Thomas

**Comment by khalwat** [comment]
The way it builds the automatic breadcrumbs is it looks for elements that match the current route, and builds them from that. For instance, on this page:

https://nystudio107.com/blog/using-vuejs-graphql-to-make-practical-magic

We get these breadcrumbs:

```
{
  "@context": "http:\/\/schema.org",
  "@type": "BreadcrumbList",
  "description": "Breadcrumbs list",
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https:\/\/nystudio107.com\/",
        "name": "Homepage"
      },
      "position": 1
    },
    {
      "@type": "ListItem",
      "item": {
        "@id": "https:\/\/nystudio107.com\/blog",
        "name": "Blog Index"
      },
      "position": 2
    },
    {
      "@type": "ListItem",
      "item": {
        "@id": "https:\/\/nystudio107.com\/blog\/using-vuejs-graphql-to-make-practical-magic",
        "name": "Using VueJS + GraphQL to make Practical Magic"
      },
      "position": 3
    }
  ],
  "name": "Breadcrumbs"
}
```

It is possible you're using some kind of custom routing or such?

**Comment by khalwat** [comment]
@goemaeret ?
