### ISSUE TITLE
Allow Google Tag Manager tracking script to render in any environment

### ISSUE THREAD

**Issue by zesda** [nystudio107/craft-seomatic#229]
**Version: 3.1.21**

Referring to the instruction for the **Script Template** setting;
> The script that will render on the page. **Note that this script will not render in local development or staging environments.**

Seems a bit silly to disable this outright for any environment other than production, seeing as the GTM setup would need to be tested for a new site before it's go-live at some point?

For my company, we specify an environment variable within our GTM container which picks up the domain name of the site the tracking snippet is being loaded from, meaning that Triggers and Tags will not run for anything other than a live environment.

Perhaps, giving the SEO administrator the option to select the environments they'd want to be loaded or not loaded in with a group of checkboxes? 

It's a bit of a bummer that we're having to get our devs to hack in code to force this to run without switching over our configuration environments for seomatic or Craft. Thanks for considering!

**Comment by khalwat** [comment]
So you can change this if you like as per: https://github.com/nystudio107/craft-seomatic#tracking-scripts

...by doing:

```twig
{% do seomatic.script.get('googleTagManager').include(true) %}
```

You can also change the `dataLayer` there as well via:

```twig
{% do seomatic.script.get('googleTagManager').dataLayer({
    'woof': 'bark'
}) %}
```

...or other properties as well.  The reason it is disabled by default in environments other than production is that for the majority, having it accidentally on can be detrimental. But you're free to override this behavior as described above.

Also if you deal with that at all, you can customize how SEOmatic creates the default containers, and you could remove that automatic disabling in other environments as per:

https://github.com/nystudio107/craft-seomatic#config-file-customization
