### ISSUE TITLE
Clicking last item in breadcrumb nav results in error

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft-seomatic#23]
Like the title says :-)

Craft 3 RC15
SEOMatic 3.0.0-beta.6
PHP 7.1.15

![screenshot 2018-03-15 16 27 28](https://user-images.githubusercontent.com/407465/37496128-ee0b8470-286d-11e8-95a5-5274db791e5a.png)
![screenshot 2018-03-15 16 27 42](https://user-images.githubusercontent.com/407465/37496135-f79bffe2-286d-11e8-96c6-839632d41826.png)

**Comment by mikestecker** [comment]
My guess is that the page you are on shouldn't be clickable?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6074bca4cc021ae836d9792dbefcd8045cac0a92
