### ISSUE TITLE
Structured data error for searchAction

### ISSUE THREAD

**Issue by dowadidi** [nystudio107/craft-seomatic#230]
When testing the SiteLinks Search Box, I received the following error:

![image](https://user-images.githubusercontent.com/3625639/45813017-c0955900-bcd1-11e8-936f-cc97c3da11e1.png)

![image](https://user-images.githubusercontent.com/3625639/45813080-eae71680-bcd1-11e8-9d03-09af0c318b73.png)

**Comment by khalwat** [comment]
That's interesting... it looks to  me like it is correct, according to Google's examples?

 https://developers.google.com/search/docs/data-types/sitelinks-searchbox

Here's their example:

https://search.google.com/structured-data/testing-tool

...perhaps we need the `required name=` syntax in there.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/02515f8bcc6c5a3ac95368751c6a20d2ea3e6d53
