### ISSUE TITLE
[FR] CORS headers for headless endpoints

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#231]
Would be great if we could set `allowedOrigins` via config, e.g.:

```
        'allowedOrigins' => [
            '*'
        ],
```

Similar example from CraftQL: https://github.com/markhuot/craftql/blob/497789a1110a7c18dfef989a627a47d1776ba7c1/src/Console/ToolsController.php#L79-L89

**Comment by khalwat** [comment]
Wouldn't this be something that should be configured server-side?

**Comment by timkelty** [comment]
It could be, but it is a lot more convenient to do this closer to the controller. This way one can easily set CORS headers, only for the endpoints that SEOmatic creates, without having to do apache/nginx acrobatics.

**Comment by khalwat** [comment]
With the looming CraftQL support, I'm gonna call this one closed. lmk if you disagree @timkelty
