### ISSUE TITLE
Nested JSON-LD incorrectly outputs 'key' and 'include' params

### ISSUE THREAD

**Issue by alexr8** [nystudio107/craft-seomatic#233]
Adding in nested JSON-LD in Twig creates a 'key' and 'include' parameter which throws an error in google's structured data testing tool. For example:
```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{% set eventsJsonLd = seomatic.jsonLd.create({
  'type': 'Place',
  'name': 'my place name',
  'address': seomatic.jsonLd.create({
    'type': 'PostalAddress',
    'streetAddress': 'my street address',
  },false)
},false) %}

{% do mainEntity.location(eventsJsonLd) %} 
```
This outputs the following:
```

"location": {
  "@context": "http://schema.org",
  "@type": "Place",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "my street address"
  },
  "include": true,
  "key": "place",
  "name": "A place name"
},
```

**Comment by adteulade** [comment]
Same issue here everytime I try to use nested JSON-LD I'm getting an error in the Structured data testing tool:

include | true  (INVALID_PREDICATE)
key | mainEntityOfPage  (INVALID_PREDICATE)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/aa9e99ad19c25fd506824031e6e74afde9e4a7fd
