### ISSUE TITLE
SEO settings tabs not working when creating new entries in some instances

### ISSUE THREAD

**Issue by glitchedmob** [nystudio107/craft-seomatic#235]
When creating a new entry that has an SEO settings field, and you change the entry type to another that also has an SEO settings field, the tabs in that field will not work until you save the entry and edit it again. 

I threw together a quick [video](https://www.youtube.com/watch?v=W7gl0Axg7oQ) to show exactly what I'm talking about

**Comment by khalwat** [comment]
Interesting. Does it work if you straight away edit that entry type tho?

**Comment by glitchedmob** [comment]
Yes it does. The bug only happens when you change to a different entry type

**Comment by khalwat** [comment]
Fixed via PR!
