### ISSUE TITLE
FB Pixel + Live mode = Broken entries

### ISSUE THREAD

**Issue by jhealey5** [nystudio107/craft-seomatic#236]
When I enable FB pixel integration, and devmode is turned off (live site) the matrix blocks of content on entries get replaced by FB `noscript` tags. 

I'm unable to find out why it's happening, but manually adding FB pixel to the site doesn't cause the issue to happen. And moving my script tag (`main.js` - nothing to do with fb pixel) to the head of the document instead of before the closing body tag also stops the issue happening.

![image](https://user-images.githubusercontent.com/1771431/46393076-a305bd80-c6db-11e8-8c8f-7c87d81bf5ca.png)

**Comment by khalwat** [comment]
I will have a look.

**Comment by khalwat** [comment]
What exactly does your `main.js` do?

**Comment by khalwat** [comment]
Can you point me at the live site? Are we sure the HTML is valid for the site, with opening and closing `<head></head> and also <body></body>` tags?

**Comment by jhealey5** [comment]
> What exactly does your `main.js` do?

It's the main script file for the site, it does all the things :)



> Can you point me at the live site? Are we sure the HTML is valid for the site, with opening and closing `<head></head> and also <body></body>` tags?

The live site is http://flowhub.com

Validator is throwing a paddy for some things (saying no title, but there is, for eg), but it should be all alright really. And I would of thought manually adding the pixel script would cause the same problem otherwise.

Is there any difference with the way you handle it (other than adding the id etc) over just including it as a snippet?

**Comment by khalwat** [comment]
I did check over the code, and I'm having a hard time figuring out how it alone could be doing this. All it does is render the head and the body scripts; it's really weird to me that it would be somehow affecting content coming in from matrix blocks.

**Comment by khalwat** [comment]
So the HTML validator is finding a few issues:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fflowhub.com%2F

The way you implemented the the tracking pixel, this:

```
<noscript>
  <img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=226113547773956&ev=PageView&noscript=1"/>
</noscript>

```
...shouldn't be in the `<head></head>`, it should be inside the `<body></body>` tags. 

The validator also seems really confused by _something_ about the HTML on that page; my guess is that it's the root of the problem.

**Comment by jhealey5** [comment]
@khalwat Yeah I'm not sure what on earth could be causing it, it's strange how it doesn't happen if I manually embed it though.

I've removed that `<noscript>` tag from the head and that's calmed down the validator with all the issues, and have just tested it again but it still happens. One of the pages in question where it happens is here https://validator.w3.org/nu/?doc=https%3A%2F%2Fflowhub.com%2Flearn%2Fhow-to-calculate-cannabis-taxes - The rest of those issues on the validator aren't anything to worry about I don't think.

**Comment by khalwat** [comment]
I find it really interesting that the problem goes away if your main JavaScript (the one that does everything) is not included. Is it possible that something is going on with that?

I set up a test page to include the Facebook Pixel, and it's working properly.

**Comment by khalwat** [comment]
Will re-open if you get more info @jhealey5

**Comment by jhealey5** [comment]
@khalwat Sorry, finally had some time (and it happen on more clients) to delve into this.

Figured out it was due to multiple things but they all boiled down to the body tag. I had a vue component `<body-videos>` that is being incorrectly captured as the opening `body` tag and so it's inserting the body scripts here in the source.

![image](https://user-images.githubusercontent.com/1771431/59506172-7ecfc280-8e9f-11e9-8cbf-5de097d7237b.png)

It's easily fixed on my end by renaming the vue component. I had a look to see where it was coming from but it seems to get quite deep with Yii Events and that's way above my head.

Not sure if you'll bother fixing (if possible/it's your problem) as it's quite an edge case, and now I know why I can prevent it happening in future. Thought you might want to know :)

Thanks.

**Comment by khalwat** [comment]
This is something that'd need to be fixed in Yii2. They must not be expecting any other tags to start with `<body`
