### ISSUE TITLE
Conflict between SEO field and Content SEO settings, specifically for Sitemaps

### ISSUE THREAD

**Issue by nathanchicken** [nystudio107/craft-seomatic#237]
Hi there. 

I'm having an issue where the Content SEO is being ignored, because there's an SEO field present, even though the specific settings in that SEO field are off....

To explain:

Let's say I have a section: `news`. Under content SEO eg: 

`../seomatic/edit-content/general/section/news/en_gb` I have set "Include Indexable Files in Sitemap" to be off. 

But I've also created an `seo` field, applied it to the `news` section, and its settings look like this...basically, we just want people to be able to add an alternative description, title, image, if the automatically generated one isn't to the clients' liking.

![image](https://user-images.githubusercontent.com/4581082/46400455-6beed680-c6f2-11e8-99dd-8ba386210895.png)

You can see that the "Sitemap Tab" is off, so it can't be controlled. But when the sitemap.xml is generated, the "Include Indexable Files in Sitemap" is `true` when it should be false. The result is that files that shouldn't be in the sitemap are being added, which is a bit of an issue as we have gated files attached to the entry.

If I turn _on_ the indexable files in the `seo` field, eg: 

![image](https://user-images.githubusercontent.com/4581082/46400527-93de3a00-c6f2-11e8-975b-5d126fc59c93.png)

Then go to edit a post, I can see that the field is set to true. I don't believe we ever had that particular setting on in the first place, but _despite_ this I think that even though the setting might be still lingering in the field table.

As it is I either have to go through, and turn that lightswitch off for every single post, or do some sort of database update. I believe that when you remove the setting in the field, the logic in 

`../vendor/nystudio107/craft-seomatic/src/models/SitemapTemplate.php` should be taking this into consideration. 

I *think* at around line 214, in `nystudio107/craft-seomatic/src/models/SitemapTemplate.php` there's this line:

```
// Make sure this entry isn't disabled
$this->combineFieldSettings($element, $metaBundle);
```

I think that's where it gets merged in with the entry settings, and pulls in 'true' when it should just plain ignore it, as the setting is off. 

Thanks.

**Comment by khalwat** [comment]
hmmmm. Yeah so what's going on here is that under the hood, the SEO Settings field defaults to certain settings... and although you have them turned off in the GUI, that's just not allowing people to edit them. The defaults still propagate down.

I'll see if I can't figure out a better way to do this.

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-seomatic/commit/7c9bc99380eb0bfa0db9c47ad090c599351aacfd

For the entries that already have the Field in it, unfortunately they already have data in them... probably the easiest thing to do (if there isn't a ton of data in there already) is to delete the field, and re-add it once this version is released.

If that's not feasible, you can show that tab, and disable it for existing entries.
