### ISSUE TITLE
Selecting field for description results in raw twig code in preview

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft-seomatic#24]
This isn't consistent in all my sections, but I've noticed it more than 3-4 times... when choosing a field for the SEO description, sometimes I see the raw twig code in the preview after clicking save.

Craft 3 RC15
SEOMatic 3.0.0-beta.6
PHP 7.1.15

![screenshot 2018-03-15 16 32 26](https://user-images.githubusercontent.com/407465/37496264-ba79ea92-286e-11e8-8f78-31ddde107238.png)

**Comment by khalwat** [comment]
So that's something that should be rendered obviously... if you can find any rhyme or reason to it, I'd appreciate knowing what that is.

**Comment by khalwat** [comment]
@mikestecker ?

**Comment by mikestecker** [comment]
I'd say you can close this, I can't seem to replicate it now. Maybe you inadvertently fixed it...
