### ISSUE TITLE
Link to humans.txt is wrong

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-seomatic#242]
When domain doesnt direct to craft web folder, but craft install is in subfolder itself, for example: domain.com/craft/web
humans .txt file path doesnt takes this subfolder into account, and is like this:
domain.com/humans.txt

I think its something related to this:
nystudio107/craft-retour#20

(by the way - i mistakenly added this issue to repo of 2.x version before)

**Comment by khalwat** [comment]
Where are you seeing this file path to `humans.txt` ?

**Comment by khalwat** [comment]
I see, I think you  mean here?

```
<link type="text/plain" href="/humans.txt" rel="author">
```

**Comment by piotrpog** [comment]
@khalwat 
Yes, thats the place.

**Comment by khalwat** [comment]
Unfortunately, unrelated to the Retour resources issue.

Fixed in https://github.com/nystudio107/craft-seomatic/commit/30d46db89a3fa37146900dc1356ad758c9199859
