### ISSUE TITLE
MetaContainer increasing server response time on a site

### ISSUE THREAD

**Issue by jhealey5** [nystudio107/craft-seomatic#244]
We've got seomatic running on a couple of sites, but one in particular seems to have a problem with meta containers taking much longer to load than other sites.

![image](https://user-images.githubusercontent.com/1771431/46997088-aa36bd80-d116-11e8-8783-3d02a9531ada.png)

On another site it's all done in around 26.5ms, but here as you can see it's taking almost 400ms to do the same thing.

Do you have any ideas what could be causing this and/or how to fix it?

**Comment by khalwat** [comment]
So are you running in `devMode` or is this in production @jhealey5 ?

**Comment by jhealey5** [comment]
> So are you running in `devMode` or is this in production @jhealey5 ?

This was in production, local site was fine. However this morning when I checked to make sure, it's normal. I'm not sure what happened there then, maybe one of the changes we made yesterday fixed it. 

Not sure why the content of my post disappeared either...

I'll close this for now as it could of just been a hiccup. Cheers!
