### ISSUE TITLE
MetaLinkContainer missing hreflang tags in JSON endpoints

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#246]
The Meta Container endpoints (/actions/seomatic/meta-container/all-meta-containers/?uri=/) _only_ have `<link href="http://localhost:8089/" rel="alternate" hreflang="x-default">`…while a frontend request has the following in the `<head>`: 

```
<link href="http://localhost:8090/" rel="alternate" hreflang="en-gb">
<link href="http://localhost:8091/" rel="alternate" hreflang="nl">
<link href="http://localhost:8092/" rel="alternate" hreflang="de">
<link href="http://localhost:8093/" rel="alternate" hreflang="en-gb">
<link href="http://localhost:8089/" rel="alternate" hreflang="en-us">
<link href="http://localhost:8089/" rel="alternate" hreflang="x-default">
```

I'm expecting those same tags in the JSON.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/f2a640ac161644a6c7a797c1d23ed38577233272
