### ISSUE TITLE
[FR] CraftQL support?

### ISSUE THREAD

**Issue by tomdavies** [nystudio107/craft-seomatic#247]
I'm building a decent size (tens of thousands of articles) headless Craft site using Nuxt + CraftQL, and would ideally like to use Seomatic to handle generating the article SEO metadata.

I know I can query for meta containers from the plugin's endpoints, but I thought it would be awesome to be able to pull Seomatic metadata from CraftQL along with the entry data in one hit over GraphQL, especially when pulling multiple articles in one query so as to not request storm the Craft backend (e.g. we have a background build task to generate all our articles as flat HTML in batches).

I've got this about 80-90% working in a custom module by attaching the data I want from Seomatic's `MetaContainers` service to entries with URLs via a custom behaviour, and then using the `AlterSchemaFields` event that [Mark recently added to CraftQL](https://github.com/markhuot/craftql/issues/137) to add a field to that plugins `EntryInterface`. 

However, while it works but feels more fragile than I'd like as it essentially requires mirroring on my part of the shape of Seomatic's data structures, which smells to say the least. That said, I'm now _semi-reasonably_ sure it's not actually a huge amount of work to do, it's just I'm not doing it in the right place.

[I saw here that back in the summer you expressed an interest adding CraftQL support](https://github.com/markhuot/craftql/issues/134) to Seomatic. Is official support still on the cards? Would you consider accepting a PR if you don't have time to implement?

**Comment by khalwat** [comment]
It's definitely something I want to be doing for sure. I know that Tim Kelty has also expressed interest in this. Maybe we can get some input from him, and from Mark Huot?

**Comment by khalwat** [comment]
It's still `waiting for release`: https://github.com/markhuot/craftql/issues/134

Looks like I could try playing with it now all of `dev-develop` tho

**Comment by abdusco** [comment]
Any updates on this?

**Comment by roelvanhintum** [comment]
The required event to add data to CraftQL is released, so this would leave us to add it to this plugin.

**Comment by khalwat** [comment]
Will have a looksie; in the meantime, understand that you can obtain this meta information via an XHR to one of SEOmatic's endpoint's currently:

https://github.com/nystudio107/craft-seomatic#headless-spa-api

**Comment by roelvanhintum** [comment]
@khalwat I did some researching, but i'm missing some seomatic knowledge. At least it provides the basic logic to hook into CraftQL. The missing part is collecting everything from Seomatic.
What i did:

Added to `src/Seomatic.php`
```php
// CraftQL Support
if (class_exists(\markhuot\CraftQL\CraftQL::class)) {
    Event::on(
        SeoSettingsField::class,
        'craftQlGetFieldSchema',
        [new CraftQLSchema, 'handle']
    );
}
```

Created a new class `CraftQLSchema.php`
```php
<?php

namespace nystudio107\seomatic\helpers;

use nystudio107\seomatic\models\MetaBundle;

use markhuot\CraftQL\Events\GetFieldSchema;
use markhuot\CraftQL\Types\VolumeInterface;

class CraftQLSchema
{
    public function handle(GetFieldSchema $event)
    {
        $event->handled = true;

        $object = $event->schema->createObjectType('MetaBundle');
        $object->addStringField('metaTitle')
            ->resolve(function (MetaBundle $metaBundle, $args) {
                return 'Not sure what to do here.';
            });

        $object->addStringField('metaTag')
            ->resolve(function (MetaBundle $metaBundle, $args) {
                return 'Not sure what to do here.';
            });

        $object->addStringField('metaLink')
            ->resolve(function (MetaBundle $metaBundle, $args) {
                return 'Not sure what to do here.';
            });

        $object->addStringField('metaScript')
            ->resolve(function (MetaBundle $metaBundle, $args) {
                return 'Not sure what to do here.';
            });

        $object->addStringField('metaJsonLd')
            ->resolve(function (MetaBundle $metaBundle, $args) {
                return 'Not sure what to do here.';
            });

        $event->schema->addField($event->sender)->type($object);
    }
}
```

Example query:
```gql
query HomeQuery {
  entry(section: home) {
    id
    url
    title
    ... on Home {
      seo {
        metaTitle
        metaTag
        metaLink
        metaScript
        metaJsonLd
      }
    }
  }
}

```

**Comment by khalwat** [comment]
@roelvanhintum very cool -- so the way SEOmatic actually works is that if you give it an arbitrary URI, it will resolve and return the meta containers for that URI.

The idea is that it should work for any URI, regardless of whether that matches a specific element or Section. But that isn't to say it couldn't work the way you have it roughed it.

Then to return the data, you can get a good idea how that'd be done by looking at the existing controller:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/controllers/MetaContainerController.php

**Comment by roelvanhintum** [comment]
@khalwat thanks, i'll look into it. Looks like i can use `getContainerArrays` with different element retrieval logic.

**Comment by roelvanhintum** [comment]
@khalwat I'm having some trouble retrieving the entry from CraftQL. https://github.com/markhuot/craftql/issues/266

**Comment by khalwat** [comment]
Here's what Mark commented to me:

```php
Event::on(\markhuot\CraftQL\Types\VolumeInterface::class,\markhuot\CraftQL\Events\AlterSchemaFields::EVENT, function (\markhuot\CraftQL\Events\AlterSchemaFields $event) {
    $seoMaticField = $event->schema->createObjectType('SEOMaticData');
    $seoMaticField->addStringField('MetaTitleContainer')->resolve(function ($root) {
        // $root contains the data returned by the field below
        // use $root to return $root->MetaTitleContainer somehow
    });
    $seoMaticField->addStringField('MetaTagContainer')->resolve(/* same as above */);
    $seoMaticField->addStringField('MetaLinkContainer')->resolve(/* same as above */);
    $seoMaticField->addStringField('MetaScriptContainer')->resolve(/* same as above */)
    $seoMaticField->addStringField('MetaJsonLdContainer')->resolve(/* same as above */)

    $event->schema->addField('seoMatic')
        ->type($seoMaticField)
        ->args()
        ->resolve(function ($root, $args) {
           // using $args['uri'] query the DB and return
           // the meta data for the uri. Whatever you return
           // here will be passed down to each of the deeper fields
        });
});
```

This is probably the best example, https://github.com/markhuot/craftql/issues/137#issuecomment-424507618

**Comment by roelvanhintum** [comment]
@khalwat please see #390 
I did copy some logic from MetaContainerController.php which could be a little more abstract. It should work and it usages the entry requested through CraftQL.

**Comment by khalwat** [comment]
Very cool @roelvanhintum -- I will probably abstract that bit away but this is great progress!

**Comment by khalwat** [comment]
Added via https://github.com/nystudio107/craft-seomatic/pull/390/ thanks to @roelvanhintum !

**Comment by roelvanhintum** [comment]
@khalwat nice to see you cleaned it up and abstracted logic! I do wonder what the reason is to query by uri and siteId, i know this plugin needs that to build the tags, instead of retrieving those from an entry? Usually you would retrieve an entry anyway. Is it possible to support both of the queries below?

Correct me if i'm wrong, but this is how it works in the develop branch:
```gql
{
  seoMatic (uri: "/", siteId: 1) {
      metaTitleContainer
      metaTagContainer
      metaLinkContainer
      metaScriptContainer
      metaJsonLdContainer
  }
}
```

This is what i proposed, allowing Craft to handle the uri etc.
```gql
query HomeQuery {
  entry(section: home) {
    id
    ... on Home {
      seoMatic {
        metaTitleContainer
        metaTagContainer
        metaLinkContainer
        metaScriptContainer
        metaJsonLdContainer
      }
    }
  }
}
```

**Comment by khalwat** [comment]
I see what you're going for.. but this would need to work for:

* Entries
* Categories
* Products
* Solspace Calendar Events

...and it'd also need to work for URLs where there is no entry or other element associated with the URI at all. For example, a home page that has no element injected into it.

Since CraftQL doesn't support Commerce yet, and there are other elements with URLs that CraftQL doesn't support yet... we'll need this generalized case working.

If you'd like to use the basis of what is in `develop` to layer on support for the above, I'd be game. I do like the idea of getting everything in one query _when you can_ but I do need to support the generalized case first.

So you'd just need to support Entries and Categories with the above method.

**Comment by khalwat** [comment]
lmk if you'd like this issue re-opened, or would like to PR to layer on top of this base solution the `entries` and `categories` case @roelvanhintum ?

**Comment by roelvanhintum** [comment]
@khalwat how should the current field work in craftql? When i try this:
```gql
{
  seomatic(uri: "/", siteId: 1) {
    metaTitleContainer
    metaTagContainer
    metaLinkContainer
    metaScriptContainer
    metaJsonLdContainer
  }
}
```
I get the following error: `Cannot query field \"seomatic\" on type \"Query\".`

Regarding the entries etc: I could make a PR where all elements are supported, but this would involve allowing ellements to be passed to the container helper.

p.s. The current one still uses the Entry's: https://github.com/nystudio107/craft-seomatic/blob/develop/src/listeners/GetCraftQLSchema.php#L81

**Comment by khalwat** [comment]
This is what I get when I try the same @roelvanhintum 👍 

<img width="1460" alt="Screen Shot 2019-05-15 at 10 37 42 PM" src="https://user-images.githubusercontent.com/7570798/57822597-3028ee80-7762-11e9-9c3e-65ac4a820c3d.png">

> p.s. The current one still uses the Entry's: https://github.com/nystudio107/craft-seomatic/blob/develop/src/listeners/GetCraftQLSchema.php#L81

Ah yes, good point. I'm not sure why I didn't realize this!

**Comment by khalwat** [comment]
Okay, I think you'll like this compromise: https://github.com/nystudio107/craft-seomatic/commit/c219fa45c88ce872ec6f9453db68d3ef90f221d4

You can pass in parameters, and SEOmatic will use them:

```gql
{
  seomatic (uri: "/", siteId: 1) {
      metaTitleContainer
      metaTagContainer
      metaLinkContainer
      metaScriptContainer
      metaJsonLdContainer
  }
}
```

Or you can also piggyback the SEOmatic query on the Entry query:

```gql
{
  entry(section: homepage) {
    id
    title
    ... on Homepage {
      seomatic {
        metaTitleContainer
        metaTagContainer
        metaLinkContainer
        metaScriptContainer
        metaJsonLdContainer
      }
    }
  }
}
```

The bonus is that this should work for any kind of element query. Thoughts @roelvanhintum ?

**Comment by roelvanhintum** [comment]
Yeah, looks great! Both work as expected. :D
Thank you!

The error came from switching between branches in my project, which disabled the SeoMatic plugin... sorry.

**Comment by khalwat** [comment]
Wonderful! Thanks for your patience @roelvanhintum ! I think this was worth it though.
