### ISSUE TITLE
Allow categories fields to be used to populate keywords

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#25]
This would be super useful for channel post types as our categories usually clearly define the post.

**Comment by jsunsawyer** [comment]
On 2nd thought, this is probably a bad idea. There's a lot of overlap in categories and most of our content would have the same keywords.

I think I was just wanting something easy vs accurate!

**Comment by khalwat** [comment]
Google ignores the Keywords tag anyway. I wouldn't lose sleep over it.
