### ISSUE TITLE
Best Way to Approach Fallback Title Tags?

### ISSUE THREAD

**Issue by danpayne88** [nystudio107/craft-seomatic#252]
I'm attempting to move all SEO configurations to be managed through SEOMatic. One challenge that I'm running into is that, in our current set-up, we have fallbacks for certain SEO fields. The biggest example being we have a field called "SEO Title" and if that is populated, our entry will use that for the page title. If it's not, we use the entry title as a fallback. In many cases, "SEO Title" is not populated if the entry title is sufficient.

My question is, what is the best way to handle that type of situation in SEOMatic? This may be an enhancement request to have a fallback field option but am curious if there's an efficient way to handle that situation currently, rather than having to populate all SEO Title fields or not use any of the SEO Title fields and have to use the entry title instead?

Thanks!

**Comment by khalwat** [comment]
So the way I'd handle this is to set up the Content SEO settings for your sections to pull from the Title field.

Then I'd add an SEO Settings field to the Section, with just the things enabled that you might want to override, and boom, you're done.

It'll automatically use the SEO Settings if they are populated with data, and if not, it will fall back on the Content SEO settings that pull from the `entry.title` or wherever you want to pull things from.

If you want to get even more sophisticated, you can put actual Twig code in the fields in the Content SEO as well:

https://github.com/nystudio107/craft-seomatic#content-seo-admincp-fields

**Comment by khalwat** [comment]
lmk if this answers your question fully?

**Comment by danpayne88** [comment]
That's perfect! Thanks, @khalwat!

**Comment by danpayne88** [comment]
So I'm following your suggestion and have run into another question / potential enhancement request. Basically, I have the same custom title field for every entry in a section. That section has loads of individual entries and not all entries have that field populated. As mentioned above, I would like to pull the title from that field if it's populated and pull from the entry title if it's not. 

What I'm running into is I'm having to set each individual entry's SEO Title Source to that custom field manually, which is not really a viable solution with hundreds of entries in a section. Is there a way to set each entry to use the same SEO settings without having to resave each one individually?

My big end goal is just to use that custom field and use the entry title as a fallback if not populated so if there's a different workaround entirely, certainly open to that as well.

Thanks!

**Comment by khalwat** [comment]
You can set this all up in the Content SEO settings, and just set it up once for each section. Something like:

```
{{ object.entry.customField | default(object.entry.title }}
```

This is discussed here: https://github.com/nystudio107/craft-seomatic#content-seo-admincp-fields

**Comment by danpayne88** [comment]
Man, you've thought of everything. This plugin is great. Thanks, @khalwat!
