### ISSUE TITLE
Allow SitemapController::actionSitemapIndex to accept a site param

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#256]
If you are using Craft headless, you may need to use the controller directly to serve your sitemap.

In this case, you'd need to be able to specify a siteId.

#### Example:

- siteId: 1, siteUrl: https://cms.site.com (server w/ craft)
- siteId: 2, siteUrl: https://site.com (server w/ node/express)
- siteId: 3, siteUrl: https://site.de (server w/ node/express)

https://site.com/sitemap.xml would proxy https://cms.site.com/actions/seomatic/sitemap/sitemap-index?groupId=1&siteId=2

https://site.de/sitemap.xml would proxy https://cms.site.com/actions/seomatic/sitemap/sitemap-index?groupId=1&siteId=3

**Comment by khalwat** [comment]
Eagerly awaiting the PR @timkelty

**Comment by khalwat** [comment]
https://github.com/nystudio107/craft-seomatic/pull/257

**Comment by timkelty** [comment]
Fixed by #257
