### ISSUE TITLE
Pulling SEO Image from matrix

### ISSUE THREAD

**Issue by proximo7** [nystudio107/craft-seomatic#258]
I'm curious how I could pull an SEO Image from a specific matrix asset field. In the previous version I was able to use these tags:
`{% for block in entry.contents.type('image').limit(1) %}
{% for image in block.image.limit(1) %} 
{% set seomaticMeta = seomaticMeta | merge({
    og: { 
        image: [  image.getUrl('facebook') ],
        type: seomaticMeta.og.type,
        locale: seomaticMeta.og.locale,
        url: entry.url,
        title: entry.title,
        description: seomaticMeta.og.description,
        site_name: seomaticMeta.og.site_name,
        see_also: seomaticMeta.og.see_also
    }
}) %}
{% endfor %}
{% endfor %} `

Could the seomatic.helper tag be used instead? As in: {seomatic.helper.extractSummary(seomatic.helper.extractTextFromField(object.entry.contents))}
If so, how would I call the specific field from this matrix field?

**Comment by khalwat** [comment]
So you can still do it the way you were doing it before, the syntax has just changed a bit:

https://github.com/nystudio107/craft-seomatic#twig-templating

**Comment by proximo7** [comment]
I've tried this but it's not pulling the image - only the default for the section.

 {% for block in entry.contents.type('image').limit(1).all() %} 
 {% for image in block.image.limit(1).all() %} 
        {% do seomatic.meta.seoImage("{image.getUrl('facebook')}") %}
 {% endfor %} 
 {% endfor %}

**Comment by khalwat** [comment]
```twig
{% for block in entry.contents.type('image').limit(1).all() %}
    {% for image in block.image.limit(1).all() %}
        {% do seomatic.meta.seoImage(image.getUrl('facebook')) %}
    {% endfor %}
{% endfor %}
```
^ this should do the trick
