### ISSUE TITLE
[FR] normalize __home__ in headless endpoint

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#259]
https://site.com/actions/seomatic/meta-container/all-meta-containers?uri=__home__&siteId=1&asArray=1

Just because you are other places, seems consistent to do here too.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/21ad931dab79806574974b5df5b264d911b945fc
