### ISSUE TITLE
Sitemap section XMLs are not being generated 

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#262]
The main site map is being generated properly with the reference to the sections but in the individual section sitemaps, we are getting the following:

```
<!--  This sitemap has not been generated yet.  -->
<urlset> </urlset>
```

**Comment by danpayne88** [comment]
I'm experiencing the same issue.

**Comment by khalwat** [comment]
So if you visit the AdminCP, this should kick off a task that generates them.

**Comment by ghost** [comment]
Hmmm I was seeing the task show up in the queue in the sidebar briefly but the sitemap XMLs never generated. Once I downgraded to 3.1.23, the site maps were able to generate. I was able to replicate the issue on my local and a dev environment. Not sure if it's relevant but we just pushed to a new URL from a staging environment

**Comment by ghost** [comment]
Confirmed that once I upgrade back to 3.1.26 and clear my SEOMatic cache, the XML isn't generating again

**Comment by danpayne88** [comment]
I experienced the same thing as @tmmfernandez - I could see the task appear in the queue in the sidebar briefly but the sitemap XMLs would never generate for the section that it said was updating, nor any other section.

**Comment by khalwat** [comment]
Ahhh okay yeah this is in local dev... in local dev, the cache lasts for just 30 seconds so it's normal. I'll add in some code to mitigate this, but in local dev you're going to see this.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/0649040216707cb1a34bd34be9491990df500aa0

**Comment by ghost** [comment]
We are having the issue on a production environment, not on local dev; however, the fix sort of resolved the issue with the site map generating at all. 

I upgraded back to 3.1.26 and updated the SitemapTemplate.php file - now if i access the sitemap section template, the XML doesn't generate on first load, but it does properly generate on subsequent loads. I don't ever seem to have it properly generating by accessing the AdminCP like you mentioned.

**Comment by khalwat** [comment]
@tmmfernandez if you go in and edit an entry in a section, do you not see a task spawn to generate the sitemap for that section?

**Comment by ghost** [comment]
Nope, the only task I see spawn is for Updating element slug

**Comment by khalwat** [comment]
hmmmm. Yeah that doesn't make sense to me. You're editing an `entry` in that Section yes? That should trigger this:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/MetaBundles.php#L393

I can't see many ways this code path could fail?

**Comment by ghost** [comment]
Hmmm weird, I had tried it in one of my sections and didn't see a task, but I tried on a different section, and I did see the task; however, even in the section that had the task show up, the sitemap was still blank until I refreshed the sitemap

**Comment by ghost** [comment]
Yeah, once I save the entry, I see the task pop up for that section. When I go to view the sitemap, it's blank even if there was a cached version. So it's like the sitemap generation task is clearing the cache, but not generating it afterwards

**Comment by khalwat** [comment]
Attempting to reproduce.

**Comment by khalwat** [comment]
@tmmfernandez The behavior you mention in your above post, is this in local dev, or on a production site?

**Comment by ghost** [comment]
production

**Comment by khalwat** [comment]
Do you have SEOmatic knowing that it's running in production via the multi-env config mentioned here? 

https://github.com/nystudio107/craft-seomatic#plugin-settings

**Comment by khalwat** [comment]
Aha, never mind -- I see what's going on.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/releases/tag/3.1.27
