### ISSUE TITLE
[FR] Add automatic handling of Solspace Calendar Events

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#264]
I've got SEOmatic installed but Solspace Calendar events are not getting seo data and there doesn't appear to be a way to configure from within the SEOmatic plugin. FWIW events are calendar specific elements and not entries.

Please advise.

**Comment by khalwat** [comment]
Correct, there is currently no automatic integration with Solspace Calendar. You can set things yourself manually via Twig:

https://github.com/nystudio107/craft-seomatic#twig-templating

Do you want this to be a Feature Request?

**Comment by CreateSean** [comment]
@khalwat Thank you, I've got title and description working. and OG Image.

Yes, please make this a feature request to integrate with Solspace Calendar.

**Comment by khalwat** [comment]
Auto-extracted Event JSON-LD structured data from a Solspace Calender event ->

<img width="1160" alt="Google ChromeScreenSnapz468" src="https://user-images.githubusercontent.com/7570798/57425668-22b3b780-71ea-11e9-826b-c160fae1161e.png">

<img width="430" alt="Google ChromeScreenSnapz469" src="https://user-images.githubusercontent.com/7570798/57425675-29422f00-71ea-11e9-948c-129010d6b0a7.png">

https://github.com/nystudio107/craft-seomatic/blob/develop/src/seoelements/SeoEvent.php#L24

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/07e1291e7dfe1ef059c613e0586122b38d23d821
