### ISSUE TITLE
No SEO data in non-standard configuration

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#265]
I have a DJ blog where all entries are in one blog but on the front end I have a listing page that lists only entries for one particular DJ based on the url like this domain.com/djs/507/firstName-LastName

On this listing page, I'm not able to set SEO data since users are not an entry. How can I set SEOmatic to work with this set up?

**Comment by khalwat** [comment]
You can do whatever you want via Twig:

https://github.com/nystudio107/craft-seomatic#twig-templating

...or you can make a Single for this page, and then set things up via Content SEO
