### ISSUE TITLE
Sitemap 404

### ISSUE THREAD

**Issue by jwmatlock** [nystudio107/craft-seomatic#268]
In sitemap validators and in Google reports, our sitemap is failing because it's not found and returns a 404. The sitemap does load in our browser though: https://www.nytix.com/sitemaps/1/sitemap.xml

Are we missing something?

**Comment by khalwat** [comment]
Probably there is just some lag in Google indexing it -- maybe at one point there was a 404 potentially?

**Comment by jwmatlock** [comment]
Other site crawlers are showing 404 errors for both the robots.txt and sitemaps. When I pull up the robots.txt it showing a 404 for me: https://www.nytix.com/robots.txt

**Comment by jwmatlock** [comment]
I just noticed that if I'm logged in as the admin, it doesn't return a 404, but actually loads. Is there a reason it would be blocking those who are not logged in?

**Comment by khalwat** [comment]
So the robots.txt 404 is likely your Nginx config:

https://github.com/nystudio107/craft-seomatic#robots

> If you are running Nginx, make sure that you don't have a line like:
> 
> location = /robots.txt  { access_log off; log_not_found off; }
> 
> ...in your config file. A directive like this will prevent SEOmatic from being able to service the request for /robots.txt. If you do have a line like this in your config file, just comment it out, and restart Nginx with sudo nginx -s reload.
> 
>

**Comment by khalwat** [comment]
hmmm, this is really strange... could there be something else in place that would be preventing Craft from registering frontend routes?  This doesn't work on your site either:

https://www.nytix.com/sitemap.xml

**Comment by jwmatlock** [comment]
I just figured it out. If you recall on an issue related to Retour, we had made some changes to the app config file. I just tried reverting those changes back to the original app file and robots and sitemap were accessible again. Here is our altered app file:

```
return [
	'bootstrap' => ['debug'],
    'modules' => [
        'debug' => [
            'class' => 'yii\debug\Module',
            // uncomment and adjust the following to add your IP if you are not connecting from localhost.
            'allowedIPs' => ['**.***.***.**'],
        ]
    ]
];
```
