### ISSUE TITLE
Content SEO Event Schema

### ISSUE THREAD

**Issue by Brian11f** [nystudio107/craft-seomatic#270]
SEOmatic -> Content SEO -> Event Page -> General

For event schema, location and startDate are listed by google as required fields. After entering the business event type from the Main Entity Page dropdown for Content SEO. There isn't a way to add this additional information to the JSON LD data.

https://user-images.githubusercontent.com/16297587/48169086-b2fa5980-e2a6-11e8-9614-f837326e671a.png

**Comment by khalwat** [comment]
Right, this is something that you'd need to add via Twig currently. At some point perhaps this could be added, but the general problem is there are hundreds of different schema types, and adding mappings for all of them a little crazy.

You can do it via Twig as discussed here: https://github.com/nystudio107/craft-seomatic#json-ld-meta-object-functions-seomaticjsonld

If you want to open up a Feature Request to add this or other specific schema type arguments, feel free!

**Comment by KasimMahroof** [comment]
Hi @khalwat,

Has there been any update on this issue?

**Comment by khalwat** [comment]
You can add this information via Twig @KasimMahroof  -- that's the way forward here.

**Comment by klick** [comment]
That link seems to be gone. Is there an updated version? I have gone through the documentation and tried several things but no luck. Google requires `StartDate` and `location` for the metadata to validate.

Thanks in advance!

Edit: This Project is still on Craft 3.

**Comment by khalwat** [comment]
@klick some examples are here: https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

**Comment by klick** [comment]
Thank you Andrew. As always, shortly after my post I figured it out myself. ^^
