### ISSUE TITLE
Sitemap issue with multi-site

### ISSUE THREAD

**Issue by Djive** [nystudio107/craft-seomatic#271]
We have 130 sites, in a multi-site setup.
Every time we create or update new entry, a sitemap is generated.
This takes a lot more time than create/update from Craft.

Can we speed it up somehow?
Or configure it to work differently, at different time?

https://github.com/nystudio107/craft-seomatic/issues/267
The global _Automatically Generate Sitemaps_ option seems like something we would definetly need now, since at the moment we have to get into all 130 sites and all sections and manually turn off the sitemap generation. When do you think this will be live?

Thanks!

**Comment by khalwat** [comment]
Yeah I think #267 will solve it for you. In the interim, you can drop back to version `3.1.24` which does not generate sitemaps via a queue.

I will close this issue only because it will be solved by an existing issue.

**Comment by khalwat** [comment]
Additional info: unfortunately, queues are a little "dumb" in that you can't schedule them, so I can't have it only regenerate the sitemaps at a given time. It's also very difficult to look into the queue (in a compatible way) to see if there are other pending queue jobs.

So I think a global switch to turn off the automatic regeneration is probably the best bet.

Question: when you resave a single section, it should only trigger the sitemap regeneration for the sites where that Element exists. Or does it exist in all 130 sites?

**Comment by Djive** [comment]
Some elements exist in one site and some on all sites.

We are in the process of populating sites with content and with sitemap generation for every entry we save and/or copy to other sites, we had a queue of thousands of sitemap generations, which would take a lot of time to finish processing due to sitemap generation being a rly slow process.

Looking forward to the global switch to turn off the automatic regeneration :)
Thanks!

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/releases/tag/3.1.31

Please see the docs here: https://github.com/nystudio107/craft-seomatic#sitemap-generation

**Comment by Djive** [comment]
Updated and tested.
All works as advertised.
Thank you very much!
