### ISSUE TITLE
[FR] Favicons, app icons, web app manifest

### ISSUE THREAD

**Issue by missmatsuko** [nystudio107/craft-seomatic#273]
Okay, so this isn't strictly SEO-related, but neither is humans.txt (as far as I know) and that can be configured in SEOmatic. Maybe this feature is better suited to a separate plugin that extends this one, though.

I spent some time yesterday getting [this Webpack plugin](https://github.com/romanlex/app-manifest-webpack-plugin) to generate favicons, app icons, and these app manifest files:
- manifest.json
- browserconfig.xml
- yandex-browser-manifest.json

I was thinking it'd be convenient if SEOmatic could generate these files and inject the links into `<head>` since it would keep the manifest data synced with the site settings data.

SEOmatic already has fields for Entity Name, Entity Description, and Entity Brand whose values could be pulled into these files. Although, ideally there would be separate fields for favicon image and manifest theme/background color.

This library might be useful: [favicon](https://github.com/letrunghieu/favicon).

**Comment by khalwat** [comment]
So I did consider doing this; but as you noted, I build these things during deployment using a webpack plugin. I haven't decided whether it makes sense to have this in SEOmatic or not; certainly it could be convenient.

Choose a "site icon" and let SEOmatic generate all of the transforms and various files for you.

**Comment by missmatsuko** [comment]
Also it would mean the name and description in the web app manifest could sync with what's set in SEOmatic for the site name and description. I think that would be a pain to do through the Webpack plugin.

**Comment by khalwat** [comment]
For better or for worse, I think I've settled on this probably not being something that it makes sense to add to SEOmatic.
