### ISSUE TITLE
Content SEO table and SEO field in Single 

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft-seomatic#274]
I use the SEO Settings field in Singles.
When entering data in the field, the information in the general table is not updated.

![1](https://user-images.githubusercontent.com/496132/48994270-642c3b00-f153-11e8-9f09-8e0cbd314250.png)
![2](https://user-images.githubusercontent.com/496132/48994271-67bfc200-f153-11e8-95d5-341eca04d829.png)

**Comment by khalwat** [comment]
So it looks like you're putting in a SEO description via the SEO Settings field, but not putting one in via the Content SEO settings.  The latter is what it is measuring in that display.

Does that make sense?
