### ISSUE TITLE
[FR] LinkedIn and Hubspot Support

### ISSUE THREAD

**Issue by stevehurst** [nystudio107/craft-seomatic#275]
The current social and tracking settings are great. However, we also use LinkedIn and Hubspot, and would like to offer our content editors and site admins access to IDs and script settings alongside Google Analytics and our other social settings within SEOmatic.

LinkedIn Features:

- Insights Tracking Code
- Social previews / meta tags

Hubspot Features:

- Tracking Code

**Comment by khalwat** [comment]
So you can already do this now if you use custom `seo-settings` config files as discussed here:

https://github.com/nystudio107/craft-seomatic#meta-bundle--container-settings

...but I think it'd make sense to bake this in as well. For HubSpot, there's a public site where I can easily see how it'd be implemented:

https://knowledge.hubspot.com/articles/kcs_article/reports/install-the-hubspot-tracking-code

...but no such thing exists for LinkedIn; the closest I could find is this:

https://www.linkedin.com/help/lms/answer/65513/adding-the-linkedin-insight-tag-to-your-website?lang=en

...which doesn't show me the script code needed. Would you be able to assist with this?

**Comment by stevehurst** [comment]
Good to know on the custom settings! I'll dig into it and see if it makes sense to do it now or wait for the baked version.

LinkedIn Insights Script (see **_linkedin_data_partner_id** for the variable):

```
    <script type="text/javascript">
        _linkedin_data_partner_id = "XXXXXX";
    </script>
    <script type="text/javascript">
        (function(){var s = document.getElementsByTagName("script")[0];
        var b = document.createElement("script");
        b.type = "text/javascript";b.async = true;
        b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
        s.parentNode.insertBefore(b, s);})();
    </script>
    <noscript>
        <img height="1" width="1" style="display:none;" alt="" src="https://dc.ads.linkedin.com/collect/?pid=296561&fmt=gif" />
    </noscript>
```

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/1d277159a90cac5fbcac49661cb8d0509e3d84ed & https://github.com/nystudio107/craft-seomatic/commit/ca2c7734ab8ee2dc79eca0161f03858dfb67c71f
