### ISSUE TITLE
Enhance Response Times when hitting API Endpoints

### ISSUE THREAD

**Issue by camposcristian** [nystudio107/craft-seomatic#277]
We're about to receive a considerable load of traffic and we've performed a load test using load impact.

What we've found out is that SEO Matic is becoming our bottleneck at the moment:

![image](https://user-images.githubusercontent.com/1928706/49055645-178a4380-f1d7-11e8-943f-a0bd6eee54cb.png)

Any tips or considerations in order to increase the response ratio?

Thanks!

**Comment by khalwat** [comment]
Currently the level 2 cache that exists for the "normal" rendering doesn't exist for accessing data via controller endpoint; I will look into adding this shortly, however.  That will help out considerably.

**Comment by khalwat** [comment]
I added a cache in https://github.com/nystudio107/craft-seomatic/commit/c89c5cb9fd93cb9fc29f086ae71a3f4419638984

If you want to set your semVer to `dev-develop` you can give it a test @camposcristianeze
