### ISSUE TITLE
Structured data error for searchAction - again

### ISSUE THREAD

**Issue by simoncox** [nystudio107/craft-seomatic#279]
As https://github.com/nystudio107/craft-seomatic/issues/230 - but I have updated to latest version 3.1.34 - and am getting this in Google Structured Data testing tool - I am not using an on-site search so am not sure where i can turn this off or is this the same issue as before?
![screenshot 2018-11-28 at 20 59 25](https://user-images.githubusercontent.com/90435/49181911-a078ba80-f350-11e8-9cbf-e565782348ae.png)

**Comment by khalwat** [comment]
So this is configured in SEOmatic -> Site Settings -> Miscellaneous

But if the fields are left blank (which is the default), it shouldn't be rendering. Let me check on that.

**Comment by khalwat** [comment]
So it looks like in fixing #230 I broke the ability to leave it blank, and have it not render.

**Comment by simoncox** [comment]
Thanks - yes can confirm that all settings in my Miscellaneous are blank.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/8ee360fffd617f140b9d55e0507d08b7655756fd
