### ISSUE TITLE
Can't access SEOmatic via Client Account

### ISSUE THREAD

**Issue by bryantwells** [nystudio107/craft-seomatic#28]
The client account has the correct permissions, but is missing the SEOmatic nav item is unavailable in the CP.

**Comment by khalwat** [comment]
My guess is that the user doesn't have all of the permissions that they need.

They'll need the general permission to access the SEOmatic plugin:

![google chromescreensnapz1086](https://user-images.githubusercontent.com/7570798/37545625-d54e6ccc-293f-11e8-9bed-f6824c1aa698.png)

And they'll need the SEOmatic permissions as appropriate:

![google chromescreensnapz1087](https://user-images.githubusercontent.com/7570798/37545636-e4abfd56-293f-11e8-8527-79974aaa7e54.png)

And finally, they'll need permission to edit the appropriate site(s):

![google chromescreensnapz1088](https://user-images.githubusercontent.com/7570798/37545651-f6557dca-293f-11e8-89b1-72e5b093b24c.png)

I set up a test account with the appropriate permissions, and it worked as expected, showing them only the sections they have access too:

![google chromescreensnapz1089](https://user-images.githubusercontent.com/7570798/37545662-0a2a703a-2940-11e8-86a0-e94796b18088.png)

**Comment by bryantwells** [comment]
Ah, I missed the first checkbox. Sorry for the unneeded issue — thanks for the detailed response and all your work!
