### ISSUE TITLE
getLocalizedUrls with routed templates

### ISSUE THREAD

**Issue by HyeinKang** [nystudio107/craft-seomatic#281]
Hello, thank you for the great plugin.

I'd like to use some pages to have `hreflang` correctly.

For example, if there is a page with route setting: 'search/<location:([^\/]+)>' => ['template' => 'searchTemplate']'. Which does not have co-responding site with other languages in cp.

However, I'd like to have the page to have <link href="[SITE_NAME]/sv/sok/sok-objekt" rel="alternate" hreflang="sv"> on the page: "/search/helsinki".

I thought `getLocalizedUrls` from the helper function would fetch a list of links by given. However it seems like the line: `if (Seomatic::$matchedElement)` in `function getLocalizedUrls` returns always null if there is no co-responding entries when page is rendered(In this case, page rendered created with route). And since `Seomatic::$matchedElement` and `$element` in the function seems like set by `function setMatchedElement` from the beginning and can not be overridden with getLocalizedUrls's parameters(i.e. {{ seomatic.helper.getLocalizedUrls(page.uri) }} ).

Is it expected behaviour?
Please let me know if you need more information.

br,
Hyein

**Comment by khalwat** [comment]
Oh heya @HyeinKang -- was great to meet you in Berlin!

I will have a look at that to see if it's not using `Seomatic::$matchedElement` properly.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/f67fa18e43929438acac6853a27863595b8a3343

**Comment by HyeinKang** [comment]
Thank you Andrew for quick fix!
Yes, it was very nice to meet you there! Take care until next time!
