### ISSUE TITLE
Illegal string offset 'metaGlobalVars'

### ISSUE THREAD

**Issue by m8brgarc** [nystudio107/craft-seomatic#282]
For some reason when I clear the cache or maybe it's randomly.  I get a site-wide 500 internal error and I have to reload the database from a back up.

The error that seems to be causing this is generated here:

`2018-12-10 11:13:03 [-][-][pe83s5hessh94uk0hr0b950dd1][error][yii\base\ErrorException:2] yii\base\ErrorException: Illegal string offset 'metaGlobalVars' in /var/www/staging/thebayouchurch/vendor/nystudio107/craft-seomatic/src/fields/SeoSettings.php:220
Stack trace:
#0 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(2, 'Illegal string ...', '/var/www/stagin...', 220)
#1 /var/www/staging/thebayouchurch/vendor/nystudio107/craft-seomatic/src/fields/SeoSettings.php(220): craft\web\ErrorHandler->handleError(2, 'Illegal string ...', '/var/www/stagin...', 220, Array)
#2 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/base/Element.php(1937): nystudio107\seomatic\fields\SeoSettings->normalizeValue('{\xE2\x80\x9CbundleVersi...', Object(craft\elements\Entry))
#3 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/base/Element.php(793): craft\base\Element->normalizeFieldValue('seo')
#4 /var/www/staging/thebayouchurch/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(738): craft\base\Element->__get('seo')
#5 /var/www/staging/thebayouchurch/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(200): nystudio107\seomatic\services\MetaContainers->loadFieldMetaContainers()
#6 [internal function]: nystudio107\seomatic\services\MetaContainers->nystudio107\seomatic\services\{closure}(Object(yii\caching\FileCache))
#7 /var/www/staging/thebayouchurch/vendor/yiisoft/yii2/caching/Cache.php(575): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#8 /var/www/staging/thebayouchurch/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(206): yii\caching\Cache->getOrSet('seomatic_metaco...', Object(Closure), NULL, Object(yii\caching\TagDependency))
#9 /var/www/staging/thebayouchurch/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(47): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('', '1')
#10 /var/www/staging/thebayouchurch/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#11 /var/www/staging/thebayouchurch/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#12 /var/www/staging/thebayouchurch/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#13 /var/www/staging/thebayouchurch/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#14 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#15 /var/www/staging/thebayouchurch/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#16 /var/www/staging/thebayouchurch/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#17 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('pages', Array)
#18 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('pages', Array)
#19 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/web/Controller.php(156): craft\web\View->renderPageTemplate('pages', Array)
#20 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('pages', Array)
#21 [internal function]: craft\controllers\TemplatesController->actionRender('pages', Array)
#22 /var/www/staging/thebayouchurch/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /var/www/staging/thebayouchurch/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('render', Array)
#25 /var/www/staging/thebayouchurch/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#26 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('templates/rende...', Array)
#27 /var/www/staging/thebayouchurch/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#28 /var/www/staging/thebayouchurch/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#29 /var/www/staging/thebayouchurch/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /var/www/staging/thebayouchurch/web/index.php(21): yii\base\Application->run()
#31 {main}`

Any ideas?

**Comment by khalwat** [comment]
This has been fixed in https://github.com/nystudio107/craft-seomatic/commit/37472bbea6ec3109c902a05fb3e17887d9c80721

I will push an update out today.
