### ISSUE TITLE
Upgrade from C2 - C3 issues

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#283]
I have a Craft 2 site that we're in the middle of upgrading where we are displaying the SEO image on the front end  in C2 but in C3 the image doesn't get pulled.

I added in the new SEOmatic settings field (handle `seoNew`) But cannot get the template to render the SEO image.

here is my simplified template:

```
{% paginate entries.limit(10) as pageInfo, entries %}

{% for entry in entries %}
    <li class="col-sm-10 col-sm-offset-1 feat-box">
      <div class="content">

        {# more code where post Image is set if it exists #}
        
        {% set seoImageSrc = entry.seo.seoImage ?? '/assets/imgs/placeholder-ilc.jpg' %} 
        {% set seoImage = craft.imager.transformImage(seoImageSrc, { width: 460, height: 295, mode: 'crop' }) %}

        <div class="col-sm-5">
          <a href="{{ entry.url }}" class="img-container">

            <div class="testing">
                  seoImage - {{ dump(seoImageSrc) }} <br>
            --  {{ seomatic.meta.parsedValue('seoDescription')}}
            </div><!-- /.testing -->

            {% if postImage is not null %}                      
              <img src="{{ postImage.url(croppedImage) }}" alt="Featured image">
            {% else %}
              <img src="{{ seoImage }}" alt="Featured image" data-test="seoimage">
            {% endif %}
            {# {% if entry.membersExclusive == "1" %} #}
              <img src="/assets/imgs/member-exclusive.png" alt="Member Exclusive" class="member-exclusive test-3">
            {# {% endif %} #}
          </a>

      </div>
    </li>
{% endfor %}
```

This line ` {% set seoImageSrc = entry.seo.seoImage ?? '/assets/imgs/placeholder-ilc.jpg' %} ` uses the old SEO field (handle `seo`) If I change that to the new seo handle `seoNew` I end up with errors.

![image](https://user-images.githubusercontent.com/6899490/49820892-1b75a400-fd47-11e8-880d-585ceaeae4b3.png)

In the testing div where I dump code this `{{ dump(seoImageSrc) }}` returns the fallback source and this `{{ seomatic.meta.parsedValue('seoDescription')}}` returns the listing page SEO description not the entry currently in the loop as I expect.

How can I get the SEO image for each entry in the for loop to display as it did in Craft 2?

**Comment by khalwat** [comment]
This code:

```
        {% set seoImageSrc = entry.seo.seoImage ?? '/assets/imgs/placeholder-ilc.jpg' %} 
        {% set seoImage = craft.imager.transformImage(seoImageSrc, { width: 460, height: 295, mode: 'crop' }) %}
```

looks to be left over from your Craft 2.x code. The property `.seoImage` won't exist. If you have an SEO Settings field, it will automatically coalesce the image settings from the field type, so your code probably should just be:

```
        {% set seoImageSrc = seomatic.meta.seoImage %} 
```

I've removed the Imager image transforms as well, because SEOmatic will do them for you.

**Comment by CreateSean** [comment]
Unfortunately that did not resolve the issue.  I suspect this is because `seomatic.meta.seoImage` is looking at the listing page, and not the entries in the for loop.

**Comment by khalwat** [comment]
I see -- okay since you're looping through entries, you'd probably want to do something like this:

```
        {% set seoImageSrc = entry.seoNew.metaGlobalVars.seoImage ?? '/assets/imgs/placeholder-ilc.jpg' %} 
        {% set seoImage = craft.imager.transformImage(seoImageSrc, { width: 460, height: 295, mode: 'crop' }) %}
```

**Comment by CreateSean** [comment]
When I did that I get an imager exception

```Requested image “{seomatic.helper.socialTransform(10972, "base", 0, "crop")}” does not exist in path “D:\sites\iHRS\siteroot”```

Not sure why that would happen if he image exists, which it does. Is this an issue now with Imager or with SEOmatic?

**Comment by khalwat** [comment]
I see okay, try this:

```
        {% set seoImageSrc = entry.seoNew.metaGlobalVars.parsedValue('seoImage') ?? '/assets/imgs/placeholder-ilc.jpg' %} 
```

This should give you the already transformed image, so I removed the Imager transform. You can add it back in if you want to have the fallback on the placeholder be transformed.

**Comment by CreateSean** [comment]
That works perfectly. Thank you for the help.

**Comment by khalwat** [comment]
Normally I wouldn't really advise doing it this way... because you're mixing SEO meta with things that are displayed on the frontend... but it's doable.
