### ISSUE TITLE
[FR] Remember selected site in breadcrumbs (CP)

### ISSUE THREAD

**Issue by jeroenlammerts** [nystudio107/craft-seomatic#284]
The breadcrumbs in the control panel (admin) doesn't remember the selected site.

/admin/seomatic/edit-content/general/section/home/nl (for example a home section in a dutch site)
Clicking "Content SEO" in breadcrumbs links to /admin/seomatic/content
Which should be /admin/seomatic/content/nl

This is also a problem in other settings pages in the plugin.

**Comment by khalwat** [comment]
Ah yes, good point!

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/dab351882036a01ebb22e1ee153246c68f3ee81b
