### ISSUE TITLE
SEO Images not updating after updating from Craft 2 to Craft 3

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#286]
As discussed in Slack, am posting an issue here so we can schedule a screenshare.

> On a craft 3 site that was updated from craft 2 the custom SEO images are not showing up. We can fix this by opening each entry and saving it and then it automatically works again. However there are HUNDREDS of entries. Is there a way to do force every entry to re-save without doing it one by one? cc/ @andrew.welch

Andrew responded to save section, that didn't work, moved to a thread copied below.

> That didn't work. Resaved the section 2 times and opened entires to check. The SEO preview didn't update. But it does when I save one by one.
> 
> createsean [21 hours ago]
> Tested on another upgraded site and confirmed that didn't fix it there either.
> 
> andrew.welch [21 hours ago]
> Clear your data/template caches? It does the same thing when it saves them either way
> 
> createsean [19 hours ago]
> Andrew, I cleared cache, saved the channel, waited, checked some entries and SEO image is not updated. Tried this three times
> 
> andrew.welch [18 hours ago]
> Doesn’t make sense to me. If you inspect the element, what is the URL for the images?
> 
> createsean [18 hours ago]
> Pasted image at 2018-12-18, 4:00 PM
> 
> createsean [18 hours ago]
> I'm in the control panel and not seeing he correct image. I've set SEOmatic to pull from the photos field but it's not as you can see from the screenshot.
> 
> 
> createsean [18 hours ago]
> the tiny thumb on the left is not what is on the right. The one on the right is the default SEO image
> 
> andrew.welch [18 hours ago]
> I don’t know, I’ve never seen that before. And it doesn’t make sense that saving a single entry fixes it, but resaving the section does not
> 
> andrew.welch [18 hours ago]
> Because in the end, they do the same thing
> 
> createsean [17 hours ago]
> Would this be an SEOmatic bug or a craft bug? Should I hit up craft support or post it on SEOmatic github....
> 
> andrew.welch [17 hours ago]
> I think it’s most likely something to do with your local environment, but it could be an SEOmatic bug. I’d be a little surprised if it was, since I’d think it would affect quite a few people if so
> 
> andrew.welch [16 hours ago]
> What is your local dev environment?
> 
> andrew.welch [16 hours ago]
> And have you had issues with tasks in the past for anything?
> 
> createsean [1 hour ago]
> Andrew, this is happening on 3 different environments. ONe is a client server which I have no control over and the other is on my forge server. The third environment is with Mamp Pro for windows. 2 different sites, 3 different environments everything is latest Craft and latest SEOmatic
> 
> andrew.welch [1 hour ago]
> I thought about this overnight, and I think I might have some idea what is going on. It would only affect imported entries
> 
> createsean [36 minutes ago]
> One site has entries imported by feedme a couple of years ago, but newer entries are also being affected
> 
> andrew.welch [27 minutes ago]
> But it would depend on how the import was done
> 
> andrew.welch [26 minutes ago]
> File an issue, we will have to block off some time to do a screen share

**Comment by khalwat** [comment]
The problem was that you had the Content SEO settings for that section set to “Custom Image” for both the Twitter Card and the Open Graph Image… and then your SEO Settings field did not override it (because you don’t expose those settings). So it always used a custom image for both the Twitter and Facebook settings.

So changing the settings in the Twitter & Facebook settings to “Same as SEO Image” for the Products/Publications section fixed it. Any other sections where you see this behavior, you should similarly change.

So not actually a bug, expected behavior in this case
