### ISSUE TITLE
Missing hyphen on vendor prefixed inline style is causing overflow in the preview pane on entries.

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#29]
craft/vendor/nystudio107/craft-seomatic/src/templates/_sidebars/_includes/sidebar-preview.twig

This is happening in Firefox. `moz-transform` should be `-moz-transform`.

**Comment by jsunsawyer** [comment]
Possibly some other style issues associated with the preview display in Firefox as well.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/86ebec0c8dc2ce8f008df762fe4f266ca4cb044e
