### ISSUE TITLE
Getting meta data on page where entry variable is manually set

### ISSUE THREAD

**Issue by jayhlee** [nystudio107/craft-seomatic#290]
I'm trying to set meta data on a page where I'm manually setting the entry variable, just like the issue [raised here](https://github.com/nystudio107/seomatic/issues/158). However, I'm having trouble getting this to work for SEOmatic on Craft 3. 

Is there a new way to set the meta data to pull from the manually set entry variable? Thanks!

**Comment by khalwat** [comment]
Yes, you'd do it the way it's discussed here:

https://github.com/nystudio107/craft-seomatic#seomatic-variables

e.g.:

```twig
{% do seomatic.meta.setAttributes({
  "seoTitle": "Some Title",
  "seoDescription": "This is my description. There are many like it, but this one is mine."
  })
%}
```

-or-

```twig
{% do seomatic.meta
  .seoTitle("Some Title")
  .seoDescription("This is my description. There are many like it, but this one is mine.")
%}
```

(they both do exactly the same thing)

**Comment by jayhlee** [comment]
Thanks, Andrew. I know I can change the seoTitle and seoDescription by adding a custom string. But the issue I’m specifically having is dynamically populating the seoTitle and seoDescription from the entry Content SEO.

In short, I have an “attorneys” section which displays each attorney’s profile via an attorneys/_entry twig file. I have the Content SEO set up for that section so that the SEO Title Source pulls from the title and the SEO Description Source grabs the “Summary From Field” from a custom “biography” source field.

SEOMatic automatically populates the template with the right Content SEO field values for each “person” entry. So loading up attorneys/john-doe works fine and outputs all the Content SEO values that are set for that attorney entry.

However, for each attorney profile page, I have additional pages (e.g. attorney/john-doe/publications) that are using the same attorneys/_entry template. I’ve created custom routes to get the subpages to work. I also manually set each subpage “entry” by having the entry be defined by via the second segment (which is the entry slug). 

```
{% set attorneySlug = craft.app.request.getSegment(2) %}
{% set thirdSeg = '' %}

{% if craft.app.request.getSegment(3) != '' %}
	{% set thirdSeg = craft.app.request.getSegment(3) %}
	{% set entry = craft.entries().section('attorneys').slug(attorneySlug).one() %}
{% endif %}
```
So I'm trying to do something like this, but it's not working:

```
	{% do seomatic.meta.setAttributes({
	  "seoTitle": "#{seomatic.meta.seoTitle}", 
	  "seoDescription": "#{seomatic.meta.seoDescription}"
	  })
	%}
```
I also tried using `#{{ object.seomatic.meta.seoTitle }}` and `#{{ object.seomatic.meta.seoDescription }}`, but I just get an error message saying that "object" doesn't exist. 

So I'm not sure how to write the values for the "seoTitle" and "seoDescription" so that the Content SEO values are properly pulled from the attorney entry page.

**Comment by khalwat** [comment]
```
	{% do seomatic.meta.setAttributes({
	  "seoTitle": "#{seomatic.meta.seoTitle}", 
	  "seoDescription": "#{seomatic.meta.seoDescription}"
	  })
	%}
```
^ doing this is essentially telling it to set the `seomatic.meta.seoTitle` to the current value of `seomatic.meta.seoTitle` so nothing would change in that case.

You should be able to do just:

```
	{% do seomatic.meta.setAttributes({
	  "seoTitle": entry.title, 
	  "seoDescription": entry.description
	  })
	%}
```

...or whatever field you use for the description, and so on.

**Comment by khalwat** [comment]
Another option since you already have an entry, is you can do:

```
{% do seomatic.helper.loadMetadataForUri(entry.uri) %}
```

...which will pre-populate the SEO data with the information from the entry

**Comment by stephanedemotte** [comment]
@khalwat How can i overwrite all field in once, 
I've multiple seo field in my entry, but i want to switch

I've try with

```
{% do seomatic.meta.setAttributes(entry.seo.metaGlobalVars) %}
```

But it's no working, i've to loop into the object and set it one by one ?

Thanks !!
