### ISSUE TITLE
Simple page titles

### ISSUE THREAD

**Issue by bradhardinge** [nystudio107/craft-seomatic#291]
Hello, bit of a newbie question here. The title tags are obviously auto generated on pages via what is set in "Content SEO". What about simple pages that don't have content defined via singles/channels etc.

For example, I'm working on a number of member pages with conditional logic/forms etc but no content sections/entries. These pages are all using the Global SEO title. What's the best way to set the titles of these pages?

**Comment by khalwat** [comment]
You can either create a Single for those pages... and then set the mappings in the Content SEO settings, or use Twig to set the values to whatever you like, as per:

https://github.com/nystudio107/craft-seomatic#seomatic-variables

e.g.:

```
{% do seomatic.meta.setAttributes({
  "seoTitle": "Some Title",
  "seoDescription": "This is my description. There are many like it, but this one is mine."
  })
%}
```

-or- 

```
{% do seomatic.meta
  .seoTitle("Some Title")
  .seoDescription("This is my description. There are many like it, but this one is mine.")
%}
```

(they do the same thing)
