### ISSUE TITLE
Invisible linebreak in sitemap

### ISSUE THREAD

**Issue by sjelfull** [nystudio107/craft-seomatic#295]
When validating /sitemaps_1_sitemap.xml, it's marked as invalid in some validators.

Turns out there is an invisible linebreak character. I verified it by pasting the output into something like Sublime.

**Comment by khalwat** [comment]
I'm unable to reproduce this by doing `curl -O` on the sitemap in question, so I don't think this is actually an issue. I will re-open if you have more information
