### ISSUE TITLE
ArgumentCountError when trying to render sitemap XML for a section on the front-end

### ISSUE THREAD

**Issue by rob-c-baker** [nystudio107/craft-seomatic#302]
The full reported error:

`Too few arguments to function yii\queue\redis\Queue::run(), 0 passed in /[removed]/vendor/nystudio107/craft-seomatic/src/models/SitemapTemplate.php on line 141 and at least 1 expected`

Occurs when trying to render the sitemap XML for a specific section with a URL that looks like this:

https://[domain]/sitemaps_1_section_pages_1_sitemap.xml

... As referenced by the sitemap index here:

https://[domain]/sitemap.xml

Craft version: 3.1.3
Seomatic version: 3.1.38

**Comment by rob-c-baker** [comment]
Looking again it looks like taking Craft's Queue system out of the hands of:

`\yii\queue\redis\Queue`

...Seems to fix the issue (commenting out the array element in the components section of the array in config/app.php).

**Comment by khalwat** [comment]
So Craft's `queue->run()` takes no parameters at all:

https://github.com/craftcms/cms/blob/develop/src/queue/Queue.php#L93

...whereas the default Redis queue does:

https://github.com/yiisoft/yii2-queue/blob/master/src/drivers/redis/Queue.php#L55

Probably you're going to need write a wrapper for the Redis queue

**Comment by ghost** [comment]
@khalwat Any plan to fix that?

**Comment by khalwat** [comment]
@bozhao2016 Should have already been fixed: https://github.com/nystudio107/craft-seomatic/blob/3b6d92d028144b8e83378a03e16dea1335af8678/src/helpers/Queue.php#L41

It will not attempt to automatically run the queue if it doesn't implement Craft's `QueueInterface` -- make sure you're using the latest version of SEOmatic.

**Comment by ghost** [comment]
Hello @khalwat, Sorry for that. It works fine. 
I just checked supervisor log, the sitemap is created in my staging server. Just bought SEOmatic last month, want to replace the old free SEO plugin. When I try to run "./craft seomatic/sitemap/generate" from, saw the error. 
But in fact the sitemap had created by yii queue worker which hosted in supervisor.

Thanks for your time

**Comment by khalwat** [comment]
@bozhao2016 actually, you're right, I missed that case -- fixed in https://github.com/nystudio107/craft-seomatic/commit/44e23b2d4a4b499e035d09780a2be5da48a25f29
