### ISSUE TITLE
SEOMatic Sitemaps

### ISSUE THREAD

**Issue by jhealey5** [nystudio107/craft-seomatic#303]
I'm not really sure if this has always been this way, or if it's a recent update that's caused it, but we have a few sites that seem to have really messed up Sitemaps.

Sitemaps are being generated like this https://trov.com/sitemap.xml
```
<sitemap>
<loc>
https://trov.com/sitemaps_1_section_about_3_sitemap.xml
</loc>
<lastmod> 2018-05-31T07:41:42-07:00 </lastmod>
</sitemap>
<sitemap>
<loc>
https://trov.com/sitemaps_1_section_footer_3_sitemap.xml
</loc>
<lastmod> 2018-12-31T00:59:16-08:00 </lastmod>
</sitemap>
<sitemap>
<loc>
https://trov.com/sitemaps_1_section_mobility_3_sitemap.xml
</loc>
<lastmod> 2018-05-31T07:46:51-07:00 </lastmod>
</sitemap>
<sitemap>
<loc>
https://trov.com/sitemaps_1_section_map_3_sitemap.xml
</loc>
<lastmod> 2019-01-10T06:06:17-08:00 </lastmod>
</sitemap>
<sitemap>
<loc>
https://trov.com/sitemaps_1_section_landingPages_3_sitemap.xml
</loc>
<lastmod> 2019-01-15T13:14:26-08:00 </lastmod>
</sitemap>
<sitemap>
<loc>
https://trov.com/sitemaps_1_section_contact_3_sitemap.xml
</loc>
<lastmod> 2018-05-31T07:43:38-07:00 </lastmod>
</sitemap>
```

When we use a third party to generate the sitemap, it's creating a traditional sitemap.

Are we doing something wrong or is this a bug?

**Comment by khalwat** [comment]
No, this isn't a bug, it's a feature! SEOmatic uses Sitemap Indexes to break things up into smaller chunks:

https://support.google.com/webmasters/answer/75712?hl=en

**Comment by chancez** [comment]
> No, this isn't a bug, it's a feature! SEOmatic uses Sitemap Indexes to break things up into smaller chunks:
> 
> https://support.google.com/webmasters/answer/75712?hl=en

As far as I can tell. sitemap indexes seem to be completely broken with google. The following shows a bunch of people hitting issues with google discovering URLs with sitemap indexes:

https://www.google.com/search?q=google+Sitemap+index+0+discovered+urls&rlz=1C5GCEA_enUS878US878&oq=google+Sitemap+index+0+discovered+urls&aqs=chrome..69i57j69i64.5769j0j7&sourceid=chrome&ie=UTF-8

Can an option be added to create a single sitemap instead of using sitemap indexes?

**Comment by khalwat** [comment]
I don't believe that's correct that anything is broken:

> For a sitemap index, there is processing of the index file itself, and the child sitemaps. They are distinct steps. Dont happen all together. A sitemap index could contain hundreds or even thousends of sitemaps. 
>  
> Ie so far your index file HAS been processed, the child sitemaps NOT yet. Only after processing of the child sitemaps can be 'Discovered' be updated. 
>  
> In short discovered=0 does NOT mean anything is broken.

**Comment by chancez** [comment]
The child-sitemaps are never discovered is the issue. If you submit the children sitemaps individually, manually, it does however work, and google does begin to visit. Without this, google never finds the child-sitemaps.

**Comment by khalwat** [comment]
@chancez I've not run into that... Google definitely supports sitemap indexes, and some of the largest sites on the web use them.

Here's what I see for nystudio107.com (which uses SEOmatic):

<img width="1367" alt="Screen Shot 2020-08-31 at 2 11 46 PM" src="https://user-images.githubusercontent.com/7570798/91752188-f4eb4280-eb93-11ea-8d24-e5bfc93c9761.png">

What are you seeing instead?

**Comment by chancez** [comment]
<img width="1490" alt="Screen Shot 2020-08-31 at 11 19 04 AM" src="https://user-images.githubusercontent.com/1400401/91752848-d11c0280-eb7b-11ea-9b0f-eec2e6f969d3.png">

**Comment by chancez** [comment]
I just realized, after trying this through the URL inspector, we're getting a header `x-robots-tag: noindex` in the response, which might be contributing here.

**Comment by chancez** [comment]
Well, that comes from here: https://github.com/nystudio107/craft-seomatic/commit/216fec1b17ab0042a8cbf15945752dbd863b33c3 so maybe this is intended? It's hard to tell if that's causing these issues.

**Comment by khalwat** [comment]
Right, it's intentional that sitemaps aren't indexed. That means that the sitemap itself won't show up in search results. It does not mean that Google won't process it.

**Comment by khalwat** [comment]
@chancez How long has the site been live?

**Comment by chancez** [comment]
@khalwat I've had the sitemap index submitted for a few weeks (at least two). I've removed it and re-added it since though to see if it made any difference (most recently this was on the 28th).
