### ISSUE TITLE
[object,object] showing after install.

### ISSUE THREAD

**Issue by philipboomy** [nystudio107/craft-seomatic#304]
Seems like there is a little issue here after installing
https://cl.ly/00d7a6f2c048

**Comment by khalwat** [comment]
This is because you have no Sections defined; this was fixed in 3.1.39

**Comment by neokoenig** [comment]
Oddly, I see this in 3.1.44, just FYI

**Comment by khalwat** [comment]
Can you give me a screenshot of exactly where you're seeing it @neokoenig ?

**Comment by neokoenig** [comment]
Sure, here you go:

![image](https://user-images.githubusercontent.com/381268/53682996-8bb31680-3cf3-11e9-9d68-5c9c9b1fe0f8.png)

PS: This is with no sections defined of course
