### ISSUE TITLE
Multisite crumbs and subnav switches back to default site

### ISSUE THREAD

**Issue by jeffreyschmitz87** [nystudio107/craft-seomatic#305]
1) Have a multisite
2) Click on the SEOmatic menu - item
3) Switch from the default site to another site using the dropdown

When clicking on one of the subnav items (e.g. Global SEO) the URL does not contain the site handle which results in switching back to the default site. The same happens when clicking on one of the crumbs.

**Comment by khalwat** [comment]
What version of SEOmatic are you using @jeffreyschmitz87 ? I believe this was fixed in 3.1.37: https://github.com/nystudio107/craft-seomatic/blob/v3/CHANGELOG.md#3137---20181219

Will re-open if you're still seeing this in a more recent version.
