### ISSUE TITLE
How to remove/uninstall this plugin?

### ISSUE THREAD

**Issue by ryanpcmcquen** [nystudio107/craft-seomatic#308]
I am no longer using this plugin and am curious if there is any cleanup besides just removing it with `composer` ...

**Comment by khalwat** [comment]
Just uninstall it via the CP, and then remove it from your `composer.json` and away you go.

**Comment by ryanpcmcquen** [comment]
@khalwat, I have done that, but there still appear to be some database remnants ...

**Comment by khalwat** [comment]
There should not be; what  kind of remnants?

**Comment by ryanpcmcquen** [comment]
@khalwat, the `seomatic_metabundles` table is the most obvious thing. I didn't dig deeper than that though.

**Comment by khalwat** [comment]
That table is removed when you uninstall the plugin:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/migrations/Install.php#L209

**Comment by ryanpcmcquen** [comment]
@khalwat, strange, that didn't happen in our case ... is that compatible with Project Config? I can just remove it manually.
