### ISSUE TITLE
[FR] Supporting Environmental Vars in SiteName

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#309]
Hi Andrew,

Are there plans to support the environmental vars that Craft has rolled out in it's 3.1 versions within SEOmatic? Currently I am setting my site name via a var called $DEFAULT_SITE_NAME. 
So within the page and Somatic I am setting this:
<img width="324" alt="screenshot 2019-02-05 at 16 17 17" src="https://user-images.githubusercontent.com/5698596/52287148-8c10f980-2961-11e9-9b18-2b4343e2dc11.png">
<img width="774" alt="screenshot 2019-02-05 at 16 13 35" src="https://user-images.githubusercontent.com/5698596/52287149-8ca99000-2961-11e9-83aa-2b0d122c8f47.png">

Thanks.

**Comment by khalwat** [comment]
I'll have a look into what it'll take to support this in Craft 3.1!

**Comment by khalwat** [comment]
Implemented in 3.1.41 https://github.com/nystudio107/craft-seomatic/releases/tag/3.1.41

**Comment by khalwat** [comment]
btw, even though this was implemented, I don't think `DEFAULT_SITE_NAME` is a great candidate for an environment variable. It's going to be the same no matter what environment we're in.

**Comment by terryupton** [comment]
That’s fair comment. The reason I did that was so I could use it in a base
config.yaml file as part of my boilerplate as it is used in several places within that file.

**Comment by terryupton** [comment]
Do you have a better approach?
