### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft-seomatic#31]
Please see the attached PDF. The cause is unknown it has appeared after the upgrade to the Beta v9.
[Database Exception – yii_db_Exception.pdf](https://github.com/nystudio107/craft-seomatic/files/1823593/Database.Exception.yii_db_Exception.pdf)

**Comment by khalwat** [comment]
Uninstall the plugin, update to beta.10, then re-install it and you should be all set. Sorry about that.

**Comment by redkrupp** [comment]
Hey,

I've just uninstalled the plugin, cleared the craft cache and composer clear-cache then installed the beta.10. The error is still there :(

**Comment by redkrupp** [comment]
Update: I have manually dropped the seomatic table in the DB, uninstalled and installed the plugin. It does work now.

**Comment by khalwat** [comment]
It was a regression in beta.8 unfortunately; I've reverted it in beta.10

**Comment by khalwat** [comment]
What happened was it was trying to merge your existing settings with the new meta bundle settings, but it was faulty in two ways:

1) The version number of the bundle never got updated, so it tried to update the meta bundle settings every request

2) The merge it was doing was causing some of the data to be erroneously duplicated, so the db column grew in size with each update

So eventually, it would grow the db column to the point where it was too large. Not good.
