### ISSUE TITLE
Element API integration

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#312]
Hi

I'm trying to integrate Seomatic in the Element Api. But it doesn't seem to give the right values. 

How can I get the raw content of the seoTitle, seoDescription and the url of the seoImage? 

The title of the page I'm testing is 'Case'. 
```
var_dump($entry->seo->metaGlobalVars->seoTitle);
Output: string(58) "{seomatic.helper.extractTextFromField(object.entry.title)}"

var_dump($entry->seo->metaGlobalVars->parsedValue('seoTitle'));
Output: string(0) ""
```

Thanks for the help! 
Katia

**Comment by khalwat** [comment]
Probably the reason that isn't working is that there is no `entry` in the context of the Element API.

I'm guessing you might just want to use the existing controllers that SEOmatic provides for obtaining meta information?

https://github.com/nystudio107/craft-seomatic#meta-container-api-endpoints

**Comment by ghost** [comment]
Using the existing endpoints works. But it would be nice if I could get this information (entry details and seo details of the entry) just in one call to the element api :). 

But if that's not possible, we can always use the existing api endpoints.

**Comment by khalwat** [comment]
So you're already in the Element API, you can make whatever calls to SEOmatic that you like. Check out what the controller does:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/controllers/MetaContainerController.php#L208

Ignoring the caching layer for now, you would end up doing something like:

```php
                Seomatic::$plugin->metaContainers->previewMetaContainers($uri, $siteId, true);
```

But really it might be easiest to just run the controller action directly from your code to get back the info you want:

```php
$result = Craft::$app->runAction('seomatic/meta-container/all-meta-containers', $params);
```

**Comment by ursbraem** [comment]
Bottom line: should I use seomatic for a headless site with element api, is it a valid use case and robust/versatile enough? or just add some custom fields to each entry type?

**Comment by khalwat** [comment]
Yes, it is a robust, valid use-case.

You can also use it with GraphQL if you prefer.

See: https://nystudio107.com/docs/seomatic/Advanced.html#headless-spa-api
