### ISSUE TITLE
Project Config is overriding the environment setting

### ISSUE THREAD

**Issue by mvdesign** [nystudio107/craft-seomatic#313]
I'm using Craft 3.1.8 and SEOmatic 3.1.42.

When I make any adjustment that triggers a Project Config update, pushing that config to the live site changes my SEOmatic environment setting from Live to Local development. 

I have tried setting the environment in config/general.php but that doesn't prevent project config from overriding my environment setting.

In my general.php config:

```
// Live environment settings     
'live' => [     
    // Base site URL     
    'siteUrl' => null,     
    // Dev Mode (see https://craftcms.com/support/dev-mode)     
    'devMode' => false,     
    // Don't allow updates on the live site. Updates should come from local.     
    'allowUpdates' => false,     
    // Disable project config changes on live site     
    'allowAdminChanges' => false,     
    // SEOmatic environment     
    'environment' => 'live',     
],     
```

My .env file has the ENVIRONMENT set to "live"

This is my first time using SEOmatic (and Craft, for that matter), so it's quite possible that I'm missing something obvious. I'd love your help in figuring out how I can get this setting to take.

**Comment by khalwat** [comment]
I see... so the real issue here is that you need to set up a full multi-environment config for SEOmatic. This isn't something you add to your `general.php` it's a separate file.

See here for details: https://github.com/nystudio107/craft-seomatic#multi-environment-config-settings

**Comment by mvdesign** [comment]
You mean I was supposed to R *all the words* in TFM? 

Sorry. It was of course there the whole time. Thanks for graciously pointing me in the right direction. Have a nice day.

**Comment by khalwat** [comment]
No worries!
