### ISSUE TITLE
Upgrade Craft 3.1 bug 

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#314]
After upgrading to Craft 3.1 an annoying bug appears in the controlpanel and on our live website. So for now disabling the plugin seems to be the only solution. Any ideas? :-( 

> in httpdocs/vendor/nystudio107/craft-seomatic/src/fields/SeoSettings.php at line 228 – yii\helpers\BaseArrayHelper::merge(['bundleVersion' => '1.0.22', 'sourceBundleType' => 'field', 'sourceId' => null, 'sourceName' => null, ...], 'Seo description...')
222223224225226227228229230231232233234                                    $config['metaGlobalVars']['mainEntityOfPage'] = $mainEntity;
            }
        }
        // Create a new meta bundle with propagated defaults
        $metaBundleDefaults = ArrayHelper::merge(
            ConfigHelper::getConfigFromFile('fieldmeta/Bundle'),
            $config
        );
 
        return MetaBundle::create($metaBundleDefaults);
    }
 
    /**
                
>  in /httpdocs/vendor/craftcms/cms/src/base/Element.php at line 2013 – nystudio107\seomatic\fields\SeoSettings::normalizeValue('SEo Tite', craft\elements\Entry)
2007200820092010201120122013201420152016201720182019                     
        if (!$field) {
            throw new Exception('Invalid field handle: ' . $fieldHandle);
        }
 
        $behavior = $this->getBehavior('customFields');
        $behavior->$fieldHandle = $field->normalizeValue($behavior->$fieldHandle, $this);
        $this->_normalizedFieldValues[$fieldHandle] = true;
    }

**Comment by khalwat** [comment]
Is there any chance you can get me a more full excerpt of the log so I can see what is going on here @beeldr ?

**Comment by ghost** [comment]
Thanks for your reply @khalwat. There are some other Craft 3.1 update bugs (have contacted the Craft Dev team). I guess these bugs are related. So if needed i'll give you an update and detailled description.

**Comment by khalwat** [comment]
Great! I will close this issue pending further info.
