### ISSUE TITLE
Page trigger segments not showing in hreflang urls

### ISSUE THREAD

**Issue by chasegiunta** [nystudio107/craft-seomatic#315]
More info on this issue here (and the bug that this commit actually **did** fix!) https://github.com/nystudio107/craft-seomatic/commit/4b305ec0340b5983795fe86e08533bedb2ccad8c

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6882433ffa05bcae0b139e27eca972eb83d73f0e
