### ISSUE TITLE
[FR] Add field to SEO Settings field for dynamic canonical URL's

### ISSUE THREAD

**Issue by naboo** [nystudio107/craft-seomatic#317]
I'm running quite a lot of multi-site installations with Craft+SEOmatic. One issue here with SEOmatic is that if you have `Propagate entries across all enabled sites?` disabled on some Section and you have `Add hreflang Tags` enabled under Plugin Settings SEOmatic will add canonical URL's to all your Site Group sites different language versions.

This means that among your meta tags you'll get invalid URL references to URL's that doesn't exist.

What I do is simply that I turn this setting off - which is totally fine. But I would like to be able to give the client the ability to manually map entries across sections themselves. 

So let's say that they have **Entry A** in **Site A** (English) and create **Entry B** in **Site B** (Swedish). These are both the "About us" page in their respective language. It would now be nice if the SEO Settings field could have some sort of "*Dynamic Canonical URL's*" field/section in which the client simply would take the absolute URL, paste it into each entry and set the correct locale and let SEOmatic output this together with the other predefined canonicals. 

This feature could then also be used to map canonicals to anything - maybe a company has a set of sites and would like to add in references to some central site for language version of terms & conditions or similar. There are some good use-cases.

This could of course simply be done using my own Craft field - but having things integrated into one and the same place is nicer :)

**Comment by khalwat** [comment]
Well, it sounds like what you really want here is some way for it to know whether an entry exists in another locale, and only add the hreflang tags if it does.

But it should be doing this already. When it goes to render the hreflangs for a given page, it looks for the element that matches, and then loops through all of your sites to find the URLs for the same element in different sites.

You're saying this is not working? Is there somewhere I can see this happening?

**Comment by naboo** [comment]
So in this case there is no way for SEOmatic to know and/or detect any related entries since the entries aren't related in any way. They aren't set to propagate across sites. So for example you might have this setup for your "Pages" Section:

Site A (en)
- About us
- Contact us
- Products

Site B (sv)
- Om oss (" About us")
- Personal ("Staff")

Site C (gb)
- Blog
- About us
- Our services

Since the entries aren't being propagated across the Pages Section each individual site has its own set with no relation between each other.

But you as the creator knows that the About us (en) Om oss (sv) and About us (uk) are the same. So here you manually could add these URLs and set the canonical yourself.

= To test it
1. Create 3 sites.
2. Create a section, set it to not propagate.
3. Create 2 entries for each site with different titles/slugs in each site.

If you don't disabled hreflang you'll get wrong canonicals. If you disabled it you see the need to have some sort of manual mapping available.

**Comment by khalwat** [comment]
This sounds like a complicated custom use-case, which would be perfect for using Twig for. You can adjust the canonical URL, and the alternate hreflang URLs as you see fit via Twig:

https://github.com/nystudio107/craft-seomatic#link-meta-object-examples

```twig
    {% set alt = seomatic.link.get('alternate') %}
    {% do alt.href([
            'http://example.com',
            'http://example.com/es'
        ]).hreflang([
            'x-default',
            'es',
        ])
    %}
```

Perhaps that's the best option here?
