### ISSUE TITLE
Content SEO edit HREF to entries not working

### ISSUE THREAD

**Issue by solivan** [nystudio107/craft-seomatic#318]
The URL to edit entries under the Content SEO is not working. When I click on any of the entry names to edit I get:

```
Internal Server Error

Server Error  
```

The URL generated is:

https://www.mysiteurl.com/customcpname/seomatic/edit-content/general/section/home/default

This is on a fresh install of Craft 3.1.10 running the latest version of SEOmatic

**Comment by khalwat** [comment]
Can you check your `storage/logs/web.log` to see exactly what this error is?

It's very likely going to end up being some kind of a server config issue.

**Comment by solivan** [comment]
Andrew, I pulled the logs. What am I looking for specifically? My site is hosted on Arcustech, specifically a Craft centric plan.

**Comment by khalwat** [comment]
So you'll need to find where the "Internal Server Error" is listed. Or you can attach the logs here, whatever is easiest.

**Comment by solivan** [comment]
I see the following:

``
2019-02-14 08:36:44 [-][1][3dsutsf6dl1bkm45t1pvqprmng][error][TypeError] TypeError: Argument 1 passed to craft\services\Fields::getLayoutById() must be of the type integer, null given, called in /storage/account/www/public_html/craft/vendor/nystudio107/craft-seomatic/src/helpers/Field.php on line 280 and defined in /storage/account/www/public_html/craft/vendor/craftcms/cms/src/services/Fields.php:974
Stack trace:
#0 /storage/account/www/public_html/craft/vendor/nystudio107/craft-seomatic/src/helpers/Field.php(280): craft\services\Fields->getLayoutById(NULL)
#1 /storage/account/www/public_html/craft/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php(957): nystudio107\seomatic\helpers\Field::fieldsOfTypeFromSource('section', 'home', 'text', false)
#2 /storage/account/www/public_html/craft/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php(503): nystudio107\seomatic\controllers\SettingsController->setContentFieldSourceVariables('section', 'home', 'Single', Array)
#3 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionEditContent('general', 'section', 'home', 'default')
#4 /storage/account/www/public_html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /storage/account/www/public_html/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /storage/account/www/public_html/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-content', Array)
#7 /storage/account/www/public_html/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-content', Array)
#8 /storage/account/www/public_html/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('seomatic/settin...', Array)
#9 /storage/account/www/public_html/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('seomatic/settin...', Array)
#10 /storage/account/www/public_html/craft/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#11 /storage/account/www/public_html/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /storage/account/www/public_html/public/index.php(21): yii\base\Application->run()
#13 {main}
2019-02-14 08:36:44 [-][1][3dsutsf6dl1bkm45t1pvqprmng][info][application] $_GET = [
    'p' => 'myCPUrl/seomatic/edit-content/general/section/home/default'
]
``

**Comment by khalwat** [comment]
Oh! My bad, this is not a server issue at all... glad we looked at the logs!

I'm guessing you have no fields/field layouts in your Homepage single?

**Comment by solivan** [comment]
Happy I could be of help. Yup, It's a fresh install. Totally barebones.

**Comment by khalwat** [comment]
Yeah I'll add a fix for this; it'll also go away once you have a field layout in place.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/a53a832c6e78c4f10a6f1bcdaab7152a13b5baf9
