### ISSUE TITLE
Add aggregate rating to Json-ld

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#319]
Hi,

I'm trying to add an aggregate rating to my json-ld data of a simple article page.
After, two hours of searching and trying, I ended up with this but without success : 
```twig
{% set aggregateRating = seomatic.jsonLd.create({
        "aggregateRating": {
                'ratingValue': avg,
                'bestRating': '5',
                'worstRating': '1',
                'ratingCount': totalVotes,
            }
        }) %}

{% do seomatic.jsonLd.add(aggregateRating) %}
```

Can you give me, please, some help to resolve this issue ?

Thanks in advance !

**Comment by khalwat** [comment]
So you're almost there. Probably you want to add this to the `mainEntityOfPage` which is a JSON-LD object for your article (presumably) that already exists. So something like:

```
{% set myRating = seomatic.jsonLd.create({
    'type': 'AggregateRating',
    'ratingValue': avg,
    'bestRating': '5',
    'worstRating': '1',
    'ratingCount': totalVotes,
}, false) %}

{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{% do mainEntity.aggregateRating(myRating) %}

```

There are some more examples up here: https://github.com/nystudio107/craft-seomatic#json-ld-meta-object-functions-seomaticjsonld

**Comment by LouisCuvelier** [comment]
Thank you !

Note for someone who is trying to do the same :
Don't forget to clear Craft's caches 😉

**Comment by ersindemirtas-pp** [comment]
@khalwat example works great, but there is no validation for this. So whenever you add the AggregateRating to mainEntityOfPage there is no check weather the AggregateRating is supported by Search Engines. I think it will be useful to have a check against the json-ld model rules.

One example case is WebPage json-ld model. Aggregate rating will be included webpage json-ld but its not supported.

**Comment by khalwat** [comment]
Well, it is valid JSON-LD schema.org -- whether _Google_ in particular decides it's applicable to a given type is a separate concern.
