### ISSUE TITLE
Sitemap disabled returns error

### ISSUE THREAD

**Issue by marknotton** [nystudio107/craft-seomatic#32]
If I disable the "Sitemap Enabled" option in the "Content SEO > Sitemap" section. Then attempt to view the section sitemap, this error is returned: 

> error on line 1 at column 39: Extra content at the end of the document

I suspect this shouldn't return anything at all. Unless this is expected behaviour given I'm trying to see a sitemap that shouldn't exist anyway. 

Just thought this might be worth sharing.

**Comment by khalwat** [comment]
Ah yep, what it does is it just outputs this:

```
<?xml version="1.0" encoding="UTF-8"?>
```

Whereas really, it should just be throwing a 404.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/fe0b4a54d2e3020d2c0206e09d07be0f11522e77

**Comment by marknotton** [comment]
Super quick resolution! Nice one.

**Comment by khalwat** [comment]
Keep the problems simple, and we're good. :)
