### ISSUE TITLE
[BUG] 504 gateway time-out with SEOMatic installed and active

### ISSUE THREAD

**Issue by michtio** [nystudio107/craft-seomatic#322]
I'm running into a previous "closed" issue that SEOMatic is causing a 504 gateway time-out.

When it is enabled, the site won't load, and it gives a 504 gateway time-out.
I can connect to the admin panel, and go around, but when I try editing an entry, again the gateway time-out occurs, the entries consist out of a pagebuild with 9 matrix blocks, 2 blocks contain a supertable, spoon is used to sort the blocks. And some blocks have about 10 fields. 

Whenever I disable SEOMatic the Craft website works perfectly again. 

In the previous issue it states that when the "generate metadata" switch is flicked off, the error doesn't occurs, I have no such luck. Even with that setting "off" I still get the gateway time-outs on the front-end templates and whenever I try editing an entry. So I needed to disable it completely.

This issue also suddenly occurred.

Using the latest version: 3.1.43

This error doesn't occur in local dev tho, it does on the staging server.

**Comment by michtio** [comment]
@khalwat I found the issue:

Whenever an asset is chosen to display as SEO Image, and that asset is removed SEOMatic hangs. When trying to load the entry or the template.

**Comment by khalwat** [comment]
That's really interesting, I'll have a look.

Just so I can reproduce this, is this a Content SEO setting where you've set a Section to use a particular image as an SEO image, and then you're deleting that Asset?

I just want to have the proper recipe so I can try to reproduce and then fix the issue.

**Comment by khalwat** [comment]
So I tried reproducing this as follows:

* I have an Asset field in an Entry
* I set the Content SEO for that Section to pull the SEO Image from the Asset field
* I selected an Asset from the Asset field
* I deleted the Asset

...but nothing hung?

Can you help give me steps to reproduce this issue?

**Comment by chasegiunta** [comment]
@khalwat This sounds very similar to the SVG asset transform I was having last week. Just in case, @michtio for reference, might be helpful to provide the asset type, and the image driver available being used locally and on the staging server.

**Comment by khalwat** [comment]
So if they are related @chasegiunta it's likely in how Craft is handling (or not) certain edge cases regarding transformed images.

**Comment by khalwat** [comment]
Will re-open if we can get steps to reproduce.

**Comment by michtio** [comment]
So,

I tried reproducing this a couple of times:

- When I enter an asset in the global SEO settings that was in the volume `images` ( the asset is a jpg image ) and attached it to use as a global SEO image, everything works fine.
- When the asset is removed ( not through the admin CP of the assets, just the file deleting from the local tree or the server ) so it shows the "broken" image file, asset index rebuilding hasn't been run yet up to this stage.
- Global SEO Image shows the broken link
- Try editing an entry or going to the front-end templates, the gateway time-out appears.

I'm not using any Craft Transforms on the field.
