### ISSUE TITLE
All meta containers and meta script container actions throw TypeError when passing `asArray=true`

### ISSUE THREAD

**Issue by chrislam** [nystudio107/craft-seomatic#323]
Steps to reproduce:
- Enable a tracking script (I enabled Google Analytics)
- Make a request to the all meta containers action for any uri, also specifying `asArray=true`

If you do not specify `asArray=true` the action returns a valid response with the script tag content as the MetaScriptContainer value.

Disabling the tracking script allows the action to return a valid response but obviously there are no scripts returned.

**Comment by chrislam** [comment]
Definitely only a problem with the Meta Script Container as I can reproduce the same issue using the meta script container action but cannot for the other specific container actions (tested title, tag, link)

**Comment by khalwat** [comment]
@chrislam can you delete your logs in `storage/logs/` and then cause the error to happen, and see if any errors are logged in your `web.log`? Search on `[error]` or `stack trace`

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/3590f2f01b59f40e19a5e83c069f53afc0de9d4e
