### ISSUE TITLE
Question: multi-site handeling subdomains

### ISSUE THREAD

**Issue by aproskam** [nystudio107/craft-seomatic#326]
Hi @khalwat ,

I'm doing some homework before I start on this new project. 
And I have some questions about what the best approach would be for this website setup in combination with SEOMatic.

It's a hotel branch with multiple locations.
For each location they would like to have a separate website.
I think the Craft multi-site is the perfect solution for this.

So I had the following in mind:

Create a portal page where you land, and from there you choose the location what leads to a subdomain with the website of the location.

|-Portal (hotel.com)
|-Hotel A (a.hotel.com)
|--English Site
|--Chinese Site
|--German Site
|-Hotel B (b.hotel.com)
|--English Site
|--Chinese Site
|--German Site
|-Hotel C (c.hotel.com)
|--English Site
|--Chinese Site
|--German Site

Questions:

1. Could this be any issue for SEOMatic to handle? 

2. Is there something what I should be aware of, or keep in mind if you look at the setup that I have in mind?

Cheers!

**Comment by khalwat** [comment]
Nope, structuring it that way with site groups is exactly how SEOmatic is expecting you to do it.

Check out:

https://github.com/nystudio107/craft-seomatic#multi-site-languagelocale-support
