### ISSUE TITLE
Environment stuck on devMode

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft-seomatic#327]
My mulit-env config.php

  // Staging environment settings
    'staging' => [
        // Prevent administrative changes from being made on staging
        'allowAdminChanges' => true,
        'devMode' => true,
        'suppressTemplateErrors' => false,
        'enableTemplateCaching' => true
    ],

    // Production environment settings
    'production' => [
        // Prevent administrative changes from being made on production
        'allowAdminChanges' => true,
        'devMode' => false,
        'suppressTemplateErrors' => false,
        'enableTemplateCaching' => true
    ],

SEOmatic environemnt settings says "if devMode is on, SEOmatic will override this setting to local Development."

Well it keeps overriding despite the above. Seems 'stuck' :)

**Comment by khalwat** [comment]
You need to set up a multi-environment config for SEOmatic; that means following the steps described here:

https://github.com/nystudio107/craft-seomatic#multi-environment-config-settings

Please make your `seomatic.php` look like the example and put it in `config/` and all will be well.
