### ISSUE TITLE
Suggestion: Remove Facebook/Twitter from Site Settings progress

### ISSUE THREAD

**Issue by darylknight** [nystudio107/craft-seomatic#328]
Many sites I work on don't have either Facebook or Twitter - so the Site Settings progress wheel is always saying that it's not completely set up:

![image](https://user-images.githubusercontent.com/1250017/53078090-1b8ae080-34fc-11e9-8701-938a9fbb7807.png)

Does a presence on a social network have an impact on search ranking, and is there a good reason why social networks are included on the Site Settings progress?

**Comment by khalwat** [comment]
Well, it does have to do with SEO tangentially, in that when someone shares a link to your site, if you have these accounts, you can have metadata that allows you to control how your brand is represented.

But it does not affect SERP directly, no. But SERP isn't all there is to SEO... so I think it's probably good as a reminder that you very well may want to set up these accounts for a client, even if they never use them directly.

What I do plan to do long-term for the setup is to have them be checkboxes that you can manually check off if you _know_ you don't want to do a certain thing.
