### ISSUE TITLE
Dynamic SEO title based on search query

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#329]
Hi,

I'm trying to update the SEO title of my search page dynamically based on my search query.
Presently, I'm doing this : 
```twig
    {% set searchQuery = craft.app.request.getParam('q') %}
    {% do seomatic.title.container().clearCache(true) %}
    {% if searchQuery is defined %}
        {% do seomatic.meta.seoTitle("Recherche pour : " ~ searchQuery) %}
    {% else %}
        {% do seomatic.meta.seoTitle("Faites une recherche") %}
    {% endif %}
```
Of course, the above code is not inside a `{% cache %}` tag

But It doesn't work. The SEO title is only updated when I manually clear caches in control panel.
Any idea of what I'm doing wrong ? 🤔

**Comment by khalwat** [comment]
So this issue was recently fixed:

https://github.com/nystudio107/craft-seomatic/issues/325

It'll be out in a release this coming week, but if you need it sooner, you can set your semver to `dev-develop` to get it now.

**Comment by LouisCuvelier** [comment]
Oh nice, thanks. I will wait for the release 😉
