### ISSUE TITLE
Unexpected results when trying to output SEOmatic variables via twig

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#33]
Outputting `{{ seomatic.meta.seoTitle }}` on an entry returns `{seomatic.helper.extractTextFromField(object.entry.title)}` instead of the title of the entry.

https://github.com/nystudio107/craft-seomatic#seomatic-variables

**Comment by khalwat** [comment]
That's what it should be doing, though. That's what it is set to.

**Comment by jsunsawyer** [comment]
If anyone else runs into this issue. I just needed to use `{{ seomatic.meta.parsedValue('seoTitle') }}`.

**Comment by khalwat** [comment]
I added documentation on this here:

https://github.com/nystudio107/craft-seomatic#seomatic-variables
