### ISSUE TITLE
Add Table to MainEntityOfPage

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#330]
Hi,

I'm trying to add a table element to my page with Json-Ld. I'm doing like this, following the same methodology that you explained in #319 : 
```twig
    {% set tableJsonLd = seomatic.jsonLd.create({
        'type': 'Table',
        'about': entry.title
    }, false) %}

    {% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
    {% do mainEntity.table(tableJsonLd) %}
```

But, the table method doesn't exist.
Am I doing something wrong or is it not implemented yet ?

**Comment by khalwat** [comment]
So are you saying that the main entity of the page is a [Table](https://schema.org/Table) ?

Probably you'd want to do something like:

```
    {% set tableJsonLd = seomatic.jsonLd.create({
        'key': 'mainEntityOfPage',
        'type': 'Table',
        'about': entry.title
    }) %}
```

...since you want to create JSON-LD that overwrites the current `mainEntityOfPage`
