### ISSUE TITLE
Content SEO section name doesn't change after changing section name

### ISSUE THREAD

**Issue by timprint** [nystudio107/craft-seomatic#331]
I had to change a section a name and handle after entries had already been added to the section. The section name in /seomatic/content has not updated automatically which seems to be causing an error on the front end. Should that name update itself or is there something I can do to force it to?

**Comment by timprint** [comment]
Craft 3.1.15
SEOMatic 3.1.42

**Comment by khalwat** [comment]
So the display name shouldn't really matter -- what is the error on the frontend that you're seeing @timprint ?

**Comment by timprint** [comment]
I've fixed it. Wasn't an error in SEOMatic. Sorry to bother you and thanks for replying. @khalwat

**Comment by khalwat** [comment]
No worries!

**Comment by redkrupp** [comment]
+1.

Section names aren't updating/changed in the content seo tab after renaming of some sections. Utilites - Clear caches hasn't helped.

Craft CMS 3.1.16

SEOmatic
3.1.45

Screenshots

Current sections
https://d.pr/free/i/P3qbQP

Content SEO tab

https://d.pr/free/i/7qBCYU

**Comment by ArpadGBondor** [comment]
I'm looking for a solution to update section names on the Content SEO tab after the section name got changed.

There are years of historic changes on the website that I'm maintaining, and it's confusing that in seomatic I have multiple Resources options. (It's difficult for our client to understand.)

Seomatic 
3.4.68

Do you have a better idea than manually editing the seomatic_metabundles records in mysql?

**Comment by astuteo** [comment]
Same issue for me. I updated section names and handles in my dev environment and SEOmatic updated accordingly. But after deploying to production, the production DB still has the old section names (showing zero entries) under Content SEO.

Craft CMS 5.5.7
SEOmatic 5.1.11

**Comment by khalwat** [comment]
@astuteo SEOmatic Probably because the changes are applied via Project Config in such a way that Craft CMS never fires the events in question that SEOmatic listens for. File a new issue if you like, despite it seeming similar, I don't think it has to do with this now closed issue.

**Comment by stevehurst** [comment]
Just now experiencing the same issue as astuteo. Did not find a new issue to comment on.

is there a way to re-apply section and entry type settings to Content SEO? Not only is my Section showing the old name and handle, but it is not updating with new Entry Types added.

**Comment by khalwat** [comment]
File a new issue with as much information as possible, including steps to reproduce, and I'll get it addressed.
