### ISSUE TITLE
JSON-LD not fully rendering

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#333]
Hi,

I'm having the same kind of problem than #144 but it is for a "HowTo".
Seomatic doesn't render **only** the "step" property. All others properties are rendered fine.

```twig
{% do seomatic.jsonLd.create({
        'type': 'HowTo',
        'name': "Étapes pour devenir coursier " ~ entry.title,
       "estimatedCost": "1000",
       "performTime": "01:00",
       "prepTime": "01:00",
       "totalTime": "01:00",
       "supply": "Test",
       "tool": "Test",
       "yield": "test",
       "step": "STEP"
}) %}
```

Is that a bug ?

**Comment by khalwat** [comment]
It looks like the property name in SEOmatic is actually `steps`: https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/jsonld/HowTo.php#L120

I realize this isn't what schema.org is presenting; probably they changed the name of the property at some point, and I haven't synced their changes yet.

**Comment by LouisCuvelier** [comment]
Yes, they replaced it by "[step](https://schema.org/step)".
Thanks for the help.

**Comment by LouisCuvelier** [comment]
I'm re-opening this issue because I'm facing the same kind of problem with `Question` type.

I'm trying to reproduce [this example](https://search.google.com/structured-data/testing-tool) from Google.

Here's my code : 
```twig
        {% set mainEntity = seomatic.jsonLd.create({
            'type': 'Question',
            "name": entry.title,
            "text": entry.resume|striptags,
            "answerCount": 1,
            "upvoteCount": craft.starRatings.totalVotes(entry.id),
            "dateCreated": entry.postDate|date("Y-m-d"),
            "author": {
                "type": "Person",
                "name": "Someone"
            },
            "acceptedAnswer": {
                "type": "Answer",
                "text": entry.body|striptags,
                "dateCreated": entry.postDate|date("Y-m-d"),
                "upvoteCount": craft.starRatings.totalVotes(entry.id),
                "url": entry.url,
                "author": {
                    "type": "Organization",
                    "name": "Coursier Job"
                }
            },
        }, false) %}

        {% set mainEntityOfPage = seomatic.jsonLd.get('mainEntityOfPage') %}
        {% do mainEntityOfPage.mainEntity(mainEntity) %}
```
 This is half working. `acceptedAnswer` and `answerCount` doesn't render at all.
So, I checked to this file https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/jsonld/Question.php

It seems that It's not up to date compare to Schema.org. Am I right ?

**Comment by khalwat** [comment]
Very curious. It almost looks like this one didn't get properly parsed.

**Comment by LouisCuvelier** [comment]
Do you need more informations to resolve this ?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/702ee2384a3e4e827595642d389be1ecabe31d8f
