### ISSUE TITLE
[FR] Clarify dashboard information

### ISSUE THREAD

**Issue by jwb009** [nystudio107/craft-seomatic#334]
It's currently not clear to me what the checklist items are telling me on the dashboard. Are these items that I've handled? Or items that need my attention?

Perhaps changing the list style to include a **✓** or an **×** and adding color would help.

<img width="313" alt="screen shot 2019-02-28 at 9 55 26 am" src="https://user-images.githubusercontent.com/7241260/53579361-07b82d80-3b3f-11e9-9e00-7646ef34eee0.png">

**Comment by khalwat** [comment]
I agree

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/05776f5dcec9af0c02e6fe8803da44ba354233f4
