### ISSUE TITLE
Sitemaps breaks if section have underscore in handle

### ISSUE THREAD

**Issue by nettum** [nystudio107/craft-seomatic#335]
If I have one or more underscores in the section handle I will get a 404 when trying to request the sitemap for that section.
![image](https://user-images.githubusercontent.com/798156/53654330-c793a080-3c4d-11e9-809e-839cf2772209.png)

The generated sitemap will only work for `myTestSection`. Requests against `test_section`will get 404:
![image](https://user-images.githubusercontent.com/798156/53654590-61f3e400-3c4e-11e9-89c0-0c85ab210f9a.png)

Both sections work if I rollback to v3.1.37, this seem to happen after release [v3.1.38](https://github.com/nystudio107/craft-seomatic/releases/tag/3.1.38), commit bc3e451

**Comment by khalwat** [comment]
Interesting, will have a look

**Comment by nettum** [comment]
:+1: 
cbeb089 also related.

**Comment by khalwat** [comment]
How is that related?

**Comment by nettum** [comment]
Well, it's related in the sense that it fixes wrong generated urls for custom sitemaps after the 
bc3e451 change (guessing here now)?  
So depending on how this could be fixed it may also need to be changed.

**Comment by nettum** [comment]
Any suggestions on how to fix this? 
If sitemaps still need to be on the root-level could a possible solution be to use dash (`-`) instead of underscore (`_`) in the sitemap filenames, as dash is not allowed in section handles?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6034d157e3bde96359833f0f268e4de3598a6ddd
