### ISSUE TITLE
twitter handle bug

### ISSUE THREAD

**Issue by eheiser** [nystudio107/craft-seomatic#336]
Was filling out the seo data alongside a client when the server crashed once we filled out the twitter handle. I've included a text transcript from the error screen. If we blanked out the twitter handle things went back to normal. Really strange, any idea what could cause it?

![error](https://user-images.githubusercontent.com/86934/53667908-aee9b180-3c72-11e9-9e9d-741b8230b13c.jpg)
[error.txt](https://github.com/nystudio107/craft-seomatic/files/2921134/error.txt)

**Comment by khalwat** [comment]
What version of SEOmatic are you using? This is a bug that was fixed a pretty long time ago:

https://nystudio107.com/plugins/seomatic/changelog#3-0-20-2018-05-31

Let me know if for some reason you're still experiencing it with a current version of SEOmatic?

**Comment by khalwat** [comment]
Ah, I think I can see from the dump that you're using an up to date version of SEOmatic, I'll have a look.

**Comment by khalwat** [comment]
Can you give me a screenshot of what you're entering in the CP that causes this to happen? I've tried to reproduce it here, but can't.

**Comment by eheiser** [comment]
see screenshot, I enter fairtradegent as twitter handle, save and the crash
happens.
Craft version is 3.1.3 - seomatic at latest version.
Best regards,
Erwin

Erwin Heiser | Focus! bvba
focus-webdesign.be | erwin.heiser@gmail.com
+ 32 (0)4 87 544 302  | skype: stookstudio

**Comment by chambaz** [comment]
I'm seeing this error as well by the way.

**Comment by khalwat** [comment]
@eheiser @chambaz can I see a screenshot of what text you've entered in what field, before which clicking on Save causes this error to happen?

**Comment by eheiser** [comment]
![screenshot_04](https://user-images.githubusercontent.com/86934/53759291-3b3ce400-3ec0-11e9-94de-17047eda8240.jpg)

**Comment by eheiser** [comment]
Input was FairTradeGent in the Twitter Handle field

**Comment by khalwat** [comment]
So I'm still unable to reproduce this in any of my environments, but I added some code that _might_ protect against it.

Can you try out 3.1.45? https://github.com/nystudio107/craft-seomatic/releases/tag/3.1.45

**Comment by eheiser** [comment]
With SEOMatic at 3.1.45 and Craft at 3.1.15 the error is gone. Nice one!

**Comment by khalwat** [comment]
Still totally baffled about how this could happen but... we'll take it as a win.

**Comment by chambaz** [comment]
@khalwat Yep that did the trick for me! Thank you for jumping on this so fast.
