### ISSUE TITLE
Google Tag Manager should not be initiated in the live preview?

### ISSUE THREAD

**Issue by bqkode** [nystudio107/craft-seomatic#337]
Is there a reason for GTM being initiated in Live preview, but FB, GA and GTAG are not?
If my memory serves me well, I think it was not initiated in the deprecated SEOmatic?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/79985b0c0ffe24af0e7fe3af15e038077fd88c5e

You can just add the code to the GTM template in SEOmatic, since it won't be automatically updated
