### ISSUE TITLE
impossible to change canonicalUrl for paginate results

### ISSUE THREAD

**Issue by nicolasbinet** [nystudio107/craft-seomatic#338]
hi,
We're evaluating your plugin for one project, and we're failing to change the canonicalUrl on a paginated results.
`{% do seomatic.meta.canonicalUrl('https://www.our-wonderful-domain.com/news') %}`
Are we missing something ?
Nicolas

**Comment by khalwat** [comment]
Does it work for you in cases where the results are _not_ paginated?

Have you tried clearing the cache via:

```
{% set tagContainer = seomatic.tag.container() %}
{% do tagContainer.clearCache(true) %}
```

**Comment by nicolasbinet** [comment]
It does work when it's not paginated.
but I found that this order of execution works : 

```
{% paginate newsCriteria as pageInfo, entriesOnPage %}
{% do seomatic.helper.paginate(pageInfo) %}
{% do seomatic.meta.canonicalUrl(alias('@web') ~ '/news') %}
```

**Comment by khalwat** [comment]
Ah yes, I'm sorry -- that's the correct pattern to use.

**Comment by nicolasbinet** [comment]
no problem.
thanks a lot for your help.
