### ISSUE TITLE
Disabling category group for site in sitemap

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-seomatic#339]
I want to disable category group from specific sites in sitemap.
I know that currently Craft doesn't actually allow disabling category groups for sites. 
But can such category group be removed from sitemap generated by seomatic?

I have craft install with multiple sites, on separate domainsand some categories are used only in one site.

**Comment by khalwat** [comment]
You should be able to disable it via Content SEO for the appropriate site/category, no?

**Comment by piotrpog** [comment]
Indeed I can - thanks for help.
