### ISSUE TITLE
SEO Preview appears for sections without URLs

### ISSUE THREAD

**Issue by mgburns** [nystudio107/craft-seomatic#34]
Sections without URLs are understandably omitted from the Content SEO page. I would expect the same behavior with the SEO Preview panel.

**Comment by khalwat** [comment]
Yep, that definitely should be happening as well.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/8d020598cf294f6aa8c4d7ca118231c5187c6e27
