### ISSUE TITLE
How best to handle Environment setting with the new Project Yaml approach

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#340]
So with the introduction of the Project Yaml way of managing settings and changes in Craft 3.1 - what is the recommended way to manage the Environment setting in the SEOmatic Plugin settings?
Typically, this would be changed per environment, but recommended by P&T  - the 'allowAdminChanges' => true, should only be enabled on one version. In my case this is enabled on the local dev only. 

So this means I am unable to change the staging site to 'staging' in the SEOmatic Plugin settings and likely the same problem for the Live site too (not got that far yet).

Any thoughts or suggestions on how to approach this now?

Perhaps this setting should read from the main .env file for the environment?

**Comment by khalwat** [comment]
You should use a multi-environment config as described here:

https://github.com/nystudio107/craft-seomatic#multi-environment-config-settings

This will override the project config setting.
