### ISSUE TITLE
Updating SEOmatic data requires manual cache clearance

### ISSUE THREAD

**Issue by peteeveleigh** [nystudio107/craft-seomatic#341]
When updating content within an SEOmatic field it's necessary to clear the SEOmatic cache manually.
Is this by design or some weirdness of my site? I haven't noticed this behaviour before.
Could this cache clearing be made automatic when the entry is saved?

Craft 3.1.14
SEOmatic 3.1.44

**Comment by khalwat** [comment]
So after an element is saved:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/Seomatic.php#L568

It will trigger `invalidateMetaBundleByElement()`:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/MetaBundles.php#L393

This should invalidate any caches associated with the element. Are you seeing any of the messages logged?

**Comment by peteeveleigh** [comment]
I'm not seeing them logged on the production server. But I do see them in logs on my local build.

Just tried switching the production site to devmode for a moment and made a change to the SEO data for the homepage. It didn't change and I still don't see anything in the log.

I'm looking in store/web.log - is that where I should see it?

**Comment by khalwat** [comment]
So I think that in general, it's probably safe to say that this functionality is not broken. While I'm open to the idea that this is the case, a code review I did didn't find anything out of the ordinary, but more importantly, I think an awful lot more people would be complaining if this were broken.

So then it's down to finding out what's different about your particular setup.

What information can you provide?

**Comment by peteeveleigh** [comment]
Hmm I tend to agree with you here. Has to be something peculiar to my site.
I'll have a dig around and see if I can find out some more.
I do have a custom plugin but that's sending/fetching data to a remote inventory management system when things are purchased. Shouldn't be interfering with your plugin. I'll take a closer look there.

**Comment by khalwat** [comment]
Let me know if you find anything. Again, I'm totally open to it being an issue in SEOmatic, I'm just unable to reproduce that locally, and the (lack of) complaints from others makes me conclude it may be an environmental issue.

Will re-open the issue if you find any additional data.
