### ISSUE TITLE
Support for Google Tag Manager Container Environments

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-seomatic#343]
Google Tag Manager itself supports something called environments. This allows you to define specific environments within a single container, which can then be deployed on your dev, staging and live sites. Typically Google suggests using environments for non-live i.e. dev/staging.

https://support.google.com/tagmanager/answer/6311518?hl=en

To use environments requires a slightly different container snippet to be applied, as it will include additional key values like `gtm_auth`, `gtm_preview`, `gtm_cookies_win` etc. The src for Google Tag Manager would look something like this:

```
https://www.googletagmanager.com/gtm.js?id='+i+dl+'&gtm_auth=ABCDEFGHIJKLMNOP&gtm_preview=env-5&gtm_cookies_win=x
```

Coming from a Craft 2 project, I created a bespoke implementation of initialising/modifying the dataLayer with my own twig macros and having an environment specific Google Tag Manager snippet
using multi-environment functionality with `config/general.php`. Given SEOMatic in Craft 3 has a lot more options and environment variable support, this is something I'd like to transition over to SEOMatic, but I'm not sure it's currently possible to use GTM environment container snippets, given I'd need to override the full src for GTM in both the JS and ns.html snippet as above, with the additional query keys.

Is this something you think SEOMatic can provide or can the GTM script template be overridden so it can be done?

**Comment by khalwat** [comment]
So SEOmatic gives you full access to the template that is included both in the `<head>` and in the `<body>` so you should be able to make whatever changes you need to, and get it working via SEOmatic.

Of course, you can always do it your bespoke way as well, and still use SEOmatic for SEO.

**Comment by jamesmacwhite** [comment]
@khalwat Thanks for your response. Overriding the provided template seems like the way to go then! Given it looks like you've implemented the same way I did with Craft 2 manually, I'll give the SEOmatic way a shot for sure!

I wasn't sure if you could override the original Twig templates in full. Sounds like it's possible however, so I'll peak into the plugin.

Thanks again.

**Comment by jamesmacwhite** [comment]
@khalwat I'm sorry, I'm going to have to ask, how do I override the original templates for including the GTM container that are originally within `vendor/nystudio107/craft-seomatic/src/templates/_frontend/scripts`? Apologies if this is covered somewhere, I have been searching on template overrides, but didn't see anything and tried to specify a different templatePath with the `{% do seomatic.script.get('googleTagManager') %}` or this something I should use the `seomatic-config` for?

**Comment by khalwat** [comment]
You can just edit the script via SEOmatic -> Tracking Scripts:

<img width="1453" alt="Screen Shot 2019-03-11 at 8 45 05 PM" src="https://user-images.githubusercontent.com/7570798/54167112-a0ec1b80-443e-11e9-8b7a-c02ad6609afb.png">

**Comment by jamesmacwhite** [comment]
@khalwat So simple! Thanks!
