### ISSUE TITLE
[FR] Content SEO sort order

### ISSUE THREAD

**Issue by raptureaid** [nystudio107/craft-seomatic#344]
Can the listing of site sections be set to display alphabetically by name by default? As new sections are added to a site, they're appended to the bottom of the listing. This can make it hard to find a section name within large lists.

**Comment by khalwat** [comment]
This is a reasonable thing to do

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/f692741e7c8e80c39c85947e0bfda0322ffc2c72
