### ISSUE TITLE
Disabling sitemap for whole sites

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-seomatic#346]
Right now we can disable sitemap for specific sections in specific sites. But we cant disable it for whole site with one switch.
Adding such functionality would be pretty usefull.

**Comment by khalwat** [comment]
In SEOmatic -> Plugin Settings there is the setting **Sitemaps Enabled** that should do what you want... but this is global, for all sites.

**Comment by piotrpog** [comment]
@khalwat 
Yeah, i know its global. Thats i propose making this language dependent.
