### ISSUE TITLE
php warning: transliterator_transliterate():

### ISSUE THREAD

**Issue by eheiser** [nystudio107/craft-seomatic#347]
Currently running into a php warning in the frontend: 
`transliterator_transliterate(): Could not create transliterator with ID &quot;Any-Latin; Latin-ASCII; [\u0080-\uffff] remove&quot; (transliterator_create: unable to open ICU transliterator with id &quot;Any-Latin; Latin-ASCII; [\u0080-\uffff] remove&quot;: U_INVALID_ID)`

You can see the full stack at http://mred.be.188-93-153-169.glonet-backup.be/

If I disable SEOmatic, the error goes away. I'm guessing it's a server issue as I just moved this Craft install and we didn't have this issue on the former server. Please advise, thanks!
(both craft and seomatic at latest version)

**Comment by khalwat** [comment]
Yeah this is going to end up being some kind of server config issue, as the function that's throwing the error is a built-in PHP function:

http://php.net/manual/en/transliterator.transliterate.php

Apparently the answer is:

```
Your system’s ICU lib is outdated. Update to a more recent version.
```

so... get your devops folks to update the server, or better yet, spin up a modern VPS.

**Comment by bymayo** [comment]
Is there anyway of knowing which version we need? As this tripped us up recently on a deployment

**Comment by eheiser** [comment]
My issue was solved by disabling that extension. Probably not the best solution but then neither is the hosting this site is on.

**Comment by khalwat** [comment]
I don't know the answer in terms of what the latest version that's required would be. I'd just be Googl'ing -> https://www.google.com/search?q=Could+not+create+transliterator+with+ID&oq=Could+not+create+transliterator+with+ID&aqs=chrome..69i57.450j0j7&sourceid=chrome&ie=UTF-8
