### ISSUE TITLE
Consider hiding/disabling plugin settings if 'allowAdminChanges' => false,

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#348]
Consider hiding/disabling the plugin settings page if 'allowAdminChanges' => false, - as this results in an error when trying to update anything here. Similar to how craft hide the 'settings' when 'allowAdminChanges' => false.

```
Not Supported – yii\base\NotSupportedException
Changes to the project config are not possible while in read-only mode.
```

**Comment by khalwat** [comment]
This was fixed in 3.1.46 -> https://github.com/nystudio107/craft-seomatic/commit/a9e0698ee0bb8f4bff1144aaf01c5b8ac88828f2
