### ISSUE TITLE
Grouped Websites, alternate does not return all Urls.

### ISSUE THREAD

**Issue by TomHell** [nystudio107/craft-seomatic#349]
I have 4 Website Groupes.
1. Group (CH/DE/AT) | 2. Group IT | 3. Group EN | 4. Group FR
All of that pages have the same content which is settled by a NEO Field.
If I use Plugin-Settings and output the hreflang + canonical Tags, than the output is correct.

**1. Problem** 
{%  set links = seomatic.link.get('alternate') %} does not return all pages but the plugin does it if is still set to automatically. To disable the Plugin-Option: **Site Groups define logically separate sites** does not change anything.

Might be a bug?
Thanks for checking that.

**Comment by khalwat** [comment]
I'm not sure I understand the issue; you're saying that the output is correct... but in what circumstances is the output not correct?

**Comment by khalwat** [comment]
Will re-open if more information is added.
