### ISSUE TITLE
Canonical-Url is only lowercase

### ISSUE THREAD

**Issue by TomHell** [nystudio107/craft-seomatic#350]
My language parameter has a format like this _/en-CH/_. How ever,... the Canonical-Url output is _/en-ch/_ which is currently wrong (only lowercase) but the output for the hreflang-tag is _/en-CH/_ which is correct.

**Comment by khalwat** [comment]
I'm not seeing anywhere that I explicitly am changing the case on anything for the URL?

Might there be something else going on here...?

**Comment by khalwat** [comment]
Will re-open if more information is added.
