### ISSUE TITLE
Some PHP errors after update to 3.1.46

### ISSUE THREAD

**Issue by Djive** [nystudio107/craft-seomatic#351]
Can we do something about these errors? Thanks!

[20-Mar-2019 14:10:53 Europe/Zagreb] PHP Warning:  include(/home/site/vendor/composer/../nystudio107/craft-seomatic/src/services/Helper.php): failed to open stream: No such file or directory in /home/site/vendor/composer/ClassLoader.php on line 444
[20-Mar-2019 14:10:53 Europe/Zagreb] PHP Warning:  include(/home/site/vendor/composer/../nystudio107/craft-seomatic/src/services/Helper.php): failed to open stream: No such file or directory in /home/site/vendor/composer/ClassLoader.php on line 444
[20-Mar-2019 14:10:53 Europe/Zagreb] PHP Warning:  include(): Failed opening '/home/site/vendor/composer/../nystudio107/craft-seomatic/src/services/Helper.php' for inclusion (include_path='.:/opt/alt/php72/usr/share/pear') in /home/site/vendor/composer/ClassLoader.php on line 444
[20-Mar-2019 14:10:54 Europe/Zagreb] PHP Warning:  include(/home/site/vendor/composer/../nystudio107/craft-seomatic/src/helpers/JsonLd.php): failed to open stream: No such file or directory in /home/site/vendor/composer/ClassLoader.php on line 444
[20-Mar-2019 14:10:54 Europe/Zagreb] PHP Warning:  include(/home/site/vendor/composer/../nystudio107/craft-seomatic/src/helpers/JsonLd.php): failed to open stream: No such file or directory in /home/site/vendor/composer/ClassLoader.php on line 444
[20-Mar-2019 14:10:54 Europe/Zagreb] PHP Warning:  include(): Failed opening '/home/site/vendor/composer/../nystudio107/craft-seomatic/src/helpers/JsonLd.php' for inclusion (include_path='.:/opt/alt/php72/usr/share/pear') in /home/site/vendor/composer/ClassLoader.php on line 444
[20-Mar-2019 14:10:54 Europe/Zagreb] An Error occurred while handling another error:
Error: Class 'nystudio107\seomatic\helpers\JsonLd' not found in /home/site/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLd.php:265
Stack trace:
#0 /home/site/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(74): nystudio107\seomatic\models\MetaJsonLd->render(Array)
#1 [internal function]: nystudio107\seomatic\models\MetaJsonLdContainer->nystudio107\seomatic\models\{closure}(Object(yii\caching\FileCache))
#2 /home/site/vendor/yiisoft/yii2/caching/Cache.php(597): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#3 /home/site/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(100): yii\caching\Cache->getOrSet('MetaJsonLdConta...', Object(Closure), NULL, Object(yii\caching\TagDependency))
#4 /home/site/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(279): nystudio107\seomatic\models\MetaJsonLdContainer->includeMetaData(Object(yii\caching\TagDependency))
#5 /home/site/vendor/nystudio107/craft-seomatic/src/Seomatic.php(716): nystudio107\seomatic\services\MetaContainers->includeMetaContainers()
#6 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(yii\base\Event))
#7 /home/site/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#8 /home/site/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\View', 'endPage', Object(yii\base\Event))
#9 /home/site/vendor/yiisoft/yii2/web/View.php(174): yii\base\Component->trigger('endPage')
#10 /home/site/vendor/craftcms/cms/src/web/View.php(1307): yii\web\View->endPage(false)
#11 /home/site/vendor/craftcms/cms/src/web/View.php(394): craft\web\View->endPage()
#12 /home/site/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('500', Array)
#13 /home/site/vendor/craftcms/cms/src/controllers/TemplatesController.php(229): craft\web\Controller->renderTemplate('500', Array)
#14 [internal function]: craft\controllers\TemplatesController->actionRenderError()
#15 /home/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /home/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /home/site/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('render-error', Array)
#18 /home/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render-error', Array)
#19 /home/site/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#20 /home/site/vendor/yiisoft/yii2/web/ErrorHandler.php(108): craft\web\Application->runAction('templates/rende...')
#21 /home/site/vendor/craftcms/cms/src/web/ErrorHandler.php(137): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#22 /home/site/vendor/yiisoft/yii2/base/ErrorHandler.php(111): craft\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#23 /home/site/vendor/craftcms/cms/src/web/ErrorHandler.php(68): yii\base\ErrorHandler->handleException(Object(yii\base\ErrorException))
#24 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\base\ErrorException))
#25 {main}
Previous exception:
yii\base\ErrorException: include(/home/site/vendor/composer/../nystudio107/craft-seomatic/src/helpers/JsonLd.php): failed to open stream: No such file or directory in /home/site/vendor/composer/ClassLoader.php:444
Stack trace:
#0 /home/site/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(2, 'include(/home/b...', '/home/brinjeinf...', 444)
#1 /home/site/vendor/composer/ClassLoader.php(444): craft\web\ErrorHandler->handleError(2, 'include(/home/b...', '/home/brinjeinf...', 444, Array)
#2 /home/site/vendor/composer/ClassLoader.php(444): include()
#3 /home/site/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/brinjeinf...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('nystudio107\\seo...')
#5 /home/site/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLd.php(265): spl_autoload_call('nystudio107\\seo...')
#6 /home/site/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(74): nystudio107\seomatic\models\MetaJsonLd->render(Array)
#7 [internal function]: nystudio107\seomatic\models\MetaJsonLdContainer->nystudio107\seomatic\models\{closure}(Object(yii\caching\FileCache))
#8 /home/site/vendor/yiisoft/yii2/caching/Cache.php(597): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#9 /home/site/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(100): yii\caching\Cache->getOrSet('MetaJsonLdConta...', Object(Closure), NULL, Object(yii\caching\TagDependency))
#10 /home/site/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(279): nystudio107\seomatic\models\MetaJsonLdContainer->includeMetaData(Object(yii\caching\TagDependency))
#11 /home/site/vendor/nystudio107/craft-seomatic/src/Seomatic.php(716): nystudio107\seomatic\services\MetaContainers->includeMetaContainers()
#12 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(yii\base\Event))
#13 /home/site/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#14 /home/site/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\View', 'endPage', Object(yii\base\Event))
#15 /home/site/vendor/yiisoft/yii2/web/View.php(174): yii\base\Component->trigger('endPage')
#16 /home/site/vendor/craftcms/cms/src/web/View.php(1307): yii\web\View->endPage(false)
#17 /home/site/vendor/craftcms/cms/src/web/View.php(394): craft\web\View->endPage()
#18 /home/site/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('vijesti/_catego...', Array)
#19 /home/site/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('vijesti/_catego...', Array)
#20 [internal function]: craft\controllers\TemplatesController->actionRender('vijesti/_catego...', Array)
#21 /home/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /home/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 /home/site/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('render', Array)
#24 /home/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#25 /home/site/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#26 /home/site/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#27 /home/site/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#28 /home/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /home/site/public_html/index.php(21): yii\base\Application->run()
#30 {main}

**Comment by khalwat** [comment]
This looks like a Composer error, and probably not something related to SEOmatic (even though the error is being thrown about SEOmatic).

I'd suggest deleting your `vendor/` folder and re-installing it via `composer install`
