### ISSUE TITLE
Content SEO settings per-section don't appear to be set on entries within that section

### ISSUE THREAD

**Issue by harrison-drift** [nystudio107/craft-seomatic#352]
Sorry for the weird title, I couldn't think of a more succinct way of wording it.

Basically, I've set up the Content SEO tab of the plugin to say that for a section called Articles, each meta description of the entries within should be taken from the field Standfirst. However, when making a new entry, the SEOmatic field has "Custom Text" selected by default, not my option set from the Content SEO tab.

The actual value that is present when viewing the source of the entry is valid and correctly using the Content SEO default, but in the CMS it looks wrong and is misleading.

I personally have had this reported to me more twice already by two separate clients.

I'm using Craft 3.1.19 and SEOmatic 3.1.46 with PostgreSQL 11.2

**Comment by khalwat** [comment]
So this is actually working as expected; but what is expected probably isn't very good. You can read a discussion on it here: https://github.com/nystudio107/craft-seomatic/issues/248
