### ISSUE TITLE
Truncate site name instead of text in title 

### ISSUE THREAD

**Issue by ul8** [nystudio107/craft-seomatic#356]
When I have a title such as

_really long title really long title really long title really long title | My Site Name_

This gets truncated to something like

_really long title really long... | My Site Name_

Is there any setting to instead truncate it to something like 

_really long title really long title really long...._

This is because keywords in the title are more important to us than the site name.

Thanks!

**Comment by khalwat** [comment]
There isn't a setting to do this. If you wanted to do this, probably you could just disable the placement of the site name (set it to `none`).

**Comment by ul8** [comment]
Thanks! That's good enough.
