### ISSUE TITLE
GTM dataLayer is overwritten when using multiple {% do %} tags in the same template

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-seomatic#357]
I've been playing around with the `{% do seomatic.script.get('googleTagManager').dataLayer() %}` template tag and noticed that if I declare some simple values like this:

```twig
{% do seomatic.script.get('googleTagManager').dataLayer({
    'entryId': entry.id,
    'entryTitle': entry.title,
}) %}
```

Works great, then if I wanted to add additional array that's been created in a for loop and merged, such as:

```twig
{% set arrayObject = [] %}
{% for item in exampleCriteria.all() %}
    // Template code and various Twig stuff
    {% set arrayObject = arrayObject|merge([{
        'exampleKey': 'someValue',
        'anotherKey': 'anotherValue',
    }]) %}
{% endfor %}
```
Then wanting to output this to the dataLayer as an array of items:

```twig
{% do seomatic.script.get('googleTagManager').dataLayer({
    'additionalProperty': arrayObject
}) %}
```
The dataLayer only now contains the second `{% do %}` tag data and has overwritten the data in the first tag. The reason why the array is added this way is because it cannot be done in the loop directly because, otherwise the `additionalProperty` key would be duplicated each time. Instead, the desired output would be for one or more array items under 'additionalProperty', which does work, but overwrites anything previously in the dataLayer.

Is the use of multiple `{% do %}` tags in the same template supported in this way, or should a single do tag be used in the same template, specifically because of this?

**Comment by khalwat** [comment]
Similar to the other issue you opened, you should probably build your `dataLayer` array via Twig's [merge](https://twig.symfony.com/doc/2.x/filters/merge.html) filter, and then pass _that_ in.
