### ISSUE TITLE
Feature Request: Appending to GTM dataLayer with push syntax?

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-seomatic#359]
I love the built in functionality to add keys and objects to the GTM dataLayer, but was wondering if you'd considered having the option for pushing information to the dataLayer dynamically, mainly for actions that are event based.

https://developers.google.com/tag-manager/devguide

Example:

```js
dataLayer.push({'event': 'event_name'});
```

`event_name` would be raised in the dataLayer, which could be the basis of a trigger. This can be used on an HTML event handler like `onclick` or as part of some JS callback or function.

Using push, would not overwrite the existing dataLayer information and the event would be appended, whenever triggered.

Just wondering what your thoughts were?

**Comment by khalwat** [comment]
So this is really a Twig limitation, I think. In this case, `dataLayer` is just a Twig array, and unfortunately it doesn't allow for `.push` or the like.

However, you can use [merge](https://twig.symfony.com/doc/2.x/filters/merge.html)
