### ISSUE TITLE
Documentation: Recommended Twig fallback logic for custom SEO description / image fields

### ISSUE THREAD

**Issue by mgburns** [nystudio107/craft-seomatic#36]
We have what I imagine is a pretty common setup for a "Recipes" channel on our Craft 3 site:
- Recipe entry types have a "Image" and "Body" field
- Recipe entry types also have optional "SEO Image" and "SEO Description" fields

For both, the logic we're looking to implement for the SEO Description Source and SEO Image Source fields is use the SEO field first, falling back to the main fields.

Two questions on this:
- Your README has a lot of examples that use the following Twig logic: `entry.field1 ?? entry.field2`. This works if a field may not exist, but for text fields it won't fallback properly to `field2` if `field1` has an empty text value.
- What's the recommended logic for fallback asset sources for `SEO Image Source`

Here's what I've currently got:

SEO Description Source (Custom Text):

```twig
{seomatic.helper.extractTextFromField(object.entry.seoDescription|length ? object.entry.seoDescription : object.entry.body)}
```

SEO Image Source (Custom Text):

```twig
{seomatic.helper.socialTransform(object.entry.seoImage.one() ?? object.entry.image.one() , "base", 1)}
```

Both of these appear to be working correctly, but just wondered if there wasn't a cleaner way to approach it.

Thanks!

**Comment by khalwat** [comment]
I may write a helper function like:

```
seomatic.helper.firstNonEmptyField(field1, field2, field3)
```
...just to make things a little cleaner from a templating POV.

This really is kind of a Twig discussion, not an SEOmatic discussion, but perhaps there's a way I could make it easier.

**Comment by mgburns** [comment]
Agreed, but given the common use case I thought it might warrant a callout in your documentation as a gotcha.

A related thing that I'd point out here is that I assume the `Transform SEO Image` lightswitch doesn't apply when you're using a `Custom URL`. If that's true it'd be more clear if that field was only revealed when using an source that points at an asset.

I guess another nice to have would be some logic that handled element queries so that you could do something like this:

```twig
{entry.seoImage ?? entry.heroImage}
```

And get the properly transformed URL. But then again, maybe that's too magical. :) Great plugin, feel free to close this issue.

**Comment by khalwat** [comment]
I'm just excited to see someone using the Schema.org models that I baked into it; makes me very happy!

**Comment by khalwat** [comment]
So I started to implement `firstNonEmptyField()` when I realized there's really no way for me to do it. If you pass in `entry.someField` and `entry` is `null` it's going to error before it even hits my function.

So I'll just try to come up with some better examples in the docs.
