### ISSUE TITLE
Unable to install due to sourceHandle char limit

### ISSUE THREAD

**Issue by vikdialpad** [nystudio107/craft-seomatic#360]
See the error I'm getting below. It's a result of us having some handles longer then 64 characters for certain entires. As a result the plugin won't install. I don't think it should be limited to 64 char as handles aren't. Is this something that can be addressed as it's preventing us from installing?

`db_1        | 2019-03-28 18:40:08.855 UTC [117] ERROR:  value too long for type character varying(64)
db_1        | 2019-03-28 18:40:08.855 UTC [117] STATEMENT:  INSERT INTO "dp_seomatic_metabundles" ("bundleVersion", "sourceBundleType", "sourceId", "sourceName", "sourceHandle", "sourceType", "sourceTemplate", "sourceSiteId", "sourceAltSiteSettings", "sourceDateUpdated", "metaGlobalVars", "metaSiteVars", "metaSitemapVars", "metaContainers", "redirectsContainer", "frontendTemplatesContainer", "metaBundleSettings", "dateCreated", "uid",`

**Comment by khalwat** [comment]
Ah you're right, I will increase this!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/5d7dd9c6f9d37c651bcec3e407e0854b960e5428
