### ISSUE TITLE
[FR] Allow "environment" to be set to an environment variable

### ISSUE THREAD

**Issue by benface** [nystudio107/craft-seomatic#361]
It would be great if we could set `environment` to a `$SEOMATIC_ENVIRONMENT` variable in `project.yaml`. I know the same thing can be achieved with [Multi-Environment Config Settings](https://github.com/nystudio107/craft-seomatic#multi-environment-config-settings), but overriding that setting is the only reason I would need a `seomatic.php` config file, and it just seems a little cleaner to use [environmental settings](https://docs.craftcms.com/v3/extend/environmental-settings.html) since they became a thing. Thank you for considering it. :)

**Comment by khalwat** [comment]
I've implemented this in a different way in https://github.com/nystudio107/craft-seomatic/commit/ea8d09164feb585819d588d0c8dcbdb564725528

The only complication with using Project Config for it is that we need some way to show the available choices, too... from a GUI perspective.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/4177cb74f4a5391d661aa1c0fe79d2321fa86163

![Google ChromeScreenSnapz1501](https://user-images.githubusercontent.com/7570798/55341915-8b827400-5475-11e9-8943-0e96ae6a8beb.png)

**Comment by benface** [comment]
Awesome! Thank you @khalwat!
