### ISSUE TITLE
Can't create new sections after installing the plugin

### ISSUE THREAD

**Issue by jondialpad** [nystudio107/craft-seomatic#362]
Just started using the plugin and it works great for our setup but we just noticed that it is causing an SQL error when creating new sections. It seems to be assigning a null value for the primary key of `dp_seomatic_metabundles` table. 

The error output is attached, please let me know what else you would need to identify the issue.

Below is the system info:
**Application Info**
PHP version: 7.1.27
OS version: Linux 4.9.0-8-amd64
Database driver & version: PostgreSQL 9.6.10
Image driver & version: Imagick 3.4.3 (ImageMagick 6.9.7-4)
Craft edition & version: Craft Pro 3.1.20
Yii version: 2.0.16.1
Twig version: 2.7.4
Guzzle version: 6.3.3
Imagine version: 0.7-dev

**Plugins**
Cookies: 1.1.11
Element API: 2.5.4
FastCGI Cache Bust: 1.0.8
Feed Me: 3.1.16
Field Manager: 2.0.5
Google Cloud Storage: 1.3.0
Imager: v2.1.7
Inlin: 2.1.1
Neo: 2.2.8
Redactor: 2.3.2
Redirect plugin for Craft: 3.1.0.20
SEOmatic: 3.1.46
Super Table: 2.1.16

[PDOException Error.txt](https://github.com/nystudio107/craft-seomatic/files/3036071/PDOException.Error.txt)

**Comment by khalwat** [comment]
So this is very strange, because the `id` is something that should be auto-assigned by the database (Postgres in this case). If you uninstall and re-install the plugin, what happens?

**Comment by jondialpad** [comment]
Uninstalling and reinstalling seem to be fixing the issue. Is there any way to preserve the data we have put in the plugin settings? Uninstalling doesn't seem to be keeping the data in the database. I tried both soft uninstall and completely removing the plugin.

**Comment by khalwat** [comment]
I have tried locally to reproduce what you're seeing, but I'm entirely unable to. I don't really understand how it could get into this state.

Can you send me a db dump of the `seomatic_metabundles` tables from your existing db? Send them to: `andrew@nystudio107.com`
