### ISSUE TITLE
[FR] Broadcast event when clearing SEOmatic caches

### ISSUE THREAD

**Issue by cmalven** [nystudio107/craft-seomatic#363]
Plugins that provide a static-caching alternative to Craft's built-in caching – such as [Blitz](https://github.com/putyourlightson/craft-blitz) currently have no way of knowing when SEOmatic settings have changed, so although SEOmatic's cache has been cleared, the site will continue to show the statically-cached content until the plugin's own cache is cleared.

As proposed in https://github.com/putyourlightson/craft-blitz/issues/93, it would be great if SEOmatic could throw an event whenever it clears its own caches, allowing other caches to do their thing as well.

**Comment by khalwat** [comment]
Thanks!

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/604ff36a28edb5044d956a9a902976d9109e9851
