### ISSUE TITLE
seomatic/sitemap/generate infinite loop on commerce items

### ISSUE THREAD

**Issue by danieltott** [nystudio107/craft-seomatic#364]
This is a new upgrade to craft 3 and seomatic 2

I had been noticing the "Generating ... sitemap" queue action hanging around for a long time. The loop would close and then start over again, and it was always on the same handle.

Trying out the console command on my local machine works great:
```
danielott$ ./craft seomatic/sitemap/generate --handle=item
Generating sitemap
Generating sitemap for product Item, siteId 1
Processing element 1/785 - FLP1-GF-2B-W1
Processing element 2/785 - FLP1-GF-2B
Processing element 3/785 - DCAP-PV
Processing element 4/785 - MF4S-XF-XM-PL
Processing element 5/785 - MF4S-QM-QM-PL
Processing element 6/785 - MF2S-XF-XM-PL
Processing element 7/785 - MF2S-QM-QM-PL
...
Processing element 782/785 - ST-0026
Processing element 783/785 - DCAP-REPK
Processing element 784/785 - DGAU-0192
Processing element 785/785 - DGAU-0191
---
```

But on my test server, which is on fortrabbit, it just loops through the same section over and over again, no matter if i specify a handle or not:
```
Processing element 394/789 - AS-DP0V-0043-SS


cms3-ri-dev:~$ php ./craft seomatic/sitemap/generate --handle=marketing
Generating sitemap
Generating sitemap for structure Marketing, siteId 1
Processing element 1/789 - XTFT-1MS0-LT
Processing element 2/789 - XTHA-HSTS
Processing element 3/789 - XTHA-HNS0
Processing element 4/789 - XTHA-HHSU
Processing element 5/789 - XTHA-HHSB
Processing element 6/789 - XTHA-FRS0
Processing element 7/789 - XTHA-4FS0-QD
Processing element 8/789 - XTHA-3MS0-RS
Processing element 9/789 - XTHA-2TS0-QD
Processing element 10/789 - XTHA-2MSA-XH
Processing element 11/789 - XTHA-2MS0-XH
Processing element 12/789 - XTHA-2MS0-RS
...
Processing element 783/789 - DCAP-0060
Processing element 784/789 - DCAP-0030
Processing element 785/789 - DCAP-0020
Processing element 786/789 - ST-0026
Processing element 787/789 - DCAP-REPK
Processing element 788/789 - DGAU-0192
Processing element 789/789 - DGAU-0191

Processing element 1/789 - XTFT-1MS0-LT
Processing element 2/789 - XTHA-HSTS
Processing element 3/789 - XTHA-HNS0
Processing element 4/789 - XTHA-HHSU
Processing element 5/789 - XTHA-HHSB
Processing element 6/789 - XTHA-FRS0
Processing element 7/789 - XTHA-4FS0-QD
Processing element 8/789 - XTHA-3MS0-RS
Processing element 9/789 - XTHA-2TS0-QD
...
Processing element 783/789 - DCAP-0060
Processing element 784/789 - DCAP-0030
Processing element 785/789 - DCAP-0020
Processing element 786/789 - ST-0026
Processing element 787/789 - DCAP-REPK
Processing element 788/789 - DGAU-0192
Processing element 789/789 - DGAU-0191

Processing element 1/789 - XTFT-1MS0-LT
Processing element 2/789 - XTHA-HSTS
Processing element 3/789 - XTHA-HNS0
Processing element 4/789 - XTHA-HHSU
Processing element 5/789 - XTHA-HHSB
Processing element 6/789 - XTHA-FRS0
Processing element 7/789 - XTHA-4FS0-QD
Processing element 8/789 - XTHA-3MS0-RS
Processing element 9/789 - XTHA-2TS0-QD
```

**Comment by danieltott** [comment]
Sorry I hit command-enter before finishing this issue. In the repeating error above, it is still running through the `items` Commerce product type, even if I specify `--handle=somethingelse`, and it just never stops. No errors or anything.

So one big difference between fortrabbit and my local is that I have to run the console through `php`:

`php ./craft seomatic/sitemap/generate --handle=marketing`

So I was wondering if that had something to do with it. I don't know enough about the command line and `php` to know if there's something there or not.

**Comment by danieltott** [comment]
Although, it does say `Generating sitemap for structure Marketing` which is correct - it's just the actual _elements_ that are wrong (and the fact that it repeats forever). So now I'm really not sure what the issue is.

**Comment by danieltott** [comment]
Here is the "marketing" command on my local machine:
```
danielott$ ./craft seomatic/sitemap/generate --handle=marketing
Generating sitemap
Generating sitemap for structure Marketing, siteId 1
Processing element 1/248 - Pneumatic Cylinder Hand Pumps
Processing element 2/248 - Pneumatic Cylinder Hand Pump Specifications
Processing element 3/248 - Pneumatic Cylinder Hand Pump Models
Processing element 4/248 - Pneumatic Cylinder Hand Pump Accessories
Processing element 5/248 - Pneumatic Cylinder Hand Pump Support
Processing element 6/248 - Pneumatic Cylinder Hand Pump Certifications
Processing element 7/248 - Vacuum Cylinder Hand Pumps
...
Processing element 246/248 - Build A Custom Hose
Processing element 247/248 - Find an Adapter
Processing element 248/248 - Ralston Hydraulic Hand Pumps
---
```

**Comment by khalwat** [comment]
So just to be clear -- everything works 100% correctly on your local machine, even specifying just the `marketing` handle, yes?

If so, are we sure that the database that's on production is identical? How are you syncing the db's up?

**Comment by khalwat** [comment]
If this is an _environmental_ issue, where it works fine in one environment, but not another... this is almost always something different/wrong in one environment vs. the other.

**Comment by danieltott** [comment]
To the first point - yes it's working correctly locally.

I did not sync the db - I need to basically upgrade production in place so we don't lose any data so I am testing that out. So I used a dump from production (on craft 2) and ran upgrades etc - the same way that I did locally. So the databases started out the same, but since have diverged (which is fine for now).

I suppose I could just trash it and start over again to see if it works.

I agree there's probably something funky going on with the environment difference, I just have no idea what it would be.

**Comment by khalwat** [comment]
I don't know either... just saying in general, if it works right in one environment, but not another... I start by looking for differences in the environment.

I'm certainly open to the idea that this could be a bug in SEOmatic in some way but... that it's working fine/as expected locally makes me think that's less likely.

**Comment by danieltott** [comment]
OK - I deleted all of the rows from the `craft_queue` table and restarted php and now everything is working properly. ¯\_(ツ)_/¯ 

I'll reopen if this comes up again.

Thanks for your time Andrew - you rock.

**Comment by khalwat** [comment]
Aha so what was actually going on was that there were a ton of queue jobs to generate the sitemaps in the queue.

SEOmatic will add a new job to the queue any time that an entry in that section is changed. You can disable this behavior (temporarily) via the Plugin Settings.

SEOmatic tries to be smart about it, and doesn't queue up a new job every time an element is saved as part of the "Resaving Elements" task, but it's possible some other part of the process is causing it. So just disable the automatic regeneration of the sitemap when doing the transition, and then re-enable it when you're done.

Glad you got this sorted!

**Comment by danieltott** [comment]
Oh interesting - that does explain some things. Is there a way to programmatically disable and re-enable auto-regeneration? We do have a process can update a ton of products in a short amount of time. If not, I can just disable it altogether and then just rely on using the console to generate the sitemap.

**Comment by khalwat** [comment]
Yes. You can do what Craft does during bulk re-saves, and what the latest versions of FeedMe do when importing things... which is to set the element's scenario to `Element::SCENARIO_ESSENTIALS` so that SEOmatic knows a bulk operation is going on, and it should not to try regenerate the sitemaps:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/MetaBundles.php#L423

You could also just disable the setting programatically via something like:

```php
$oldSetting = Seomatic::$plugin->settings->regenerateSitemapsAutomatically;
Seomatic::$plugin->settings->regenerateSitemapsAutomatically = false;
// Do your stuff
Seomatic::$plugin->settings->regenerateSitemapsAutomatically = oldSetting;
```

Probably the preferred way would be to change the element's scenario tho:
```
$element->setScenario(Element::SCENARIO_ESSENTIALS);
// Do your stuff
```

**Comment by danieltott** [comment]
OK that is great! Would it make sense to run this after the batch is complete?

```php
Seomatic::$plugin->sitemaps->invalidateSitemapIndexCache();
```

**Comment by khalwat** [comment]
Sure, that's not a bad idea!
