### ISSUE TITLE
Changes to the project config are not possible while in read-only mode

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-seomatic#365]
Updating to the latest SEOMatic (running Craft 3.1.21) we are seeing a migration failure on our staging site that seems to mimic this https://github.com/craftcms/cms/issues/3653 and https://github.com/craftcms/cms/issues/3957. 

We prevent admins changes to staging/production through the general config file. 

Unsure if its SEO related or due to a Craft change in 3.1.21 though (the error thrown calls out SEOMatic).

**Comment by baileydoestech** [comment]
Brute forcing this (keep refreshing the admin panel) and the migration seems to eventually go through but obviously not keen to proceed with this on a live site.

**Comment by khalwat** [comment]
Can you give me a stack trace from the error?

**Comment by baileydoestech** [comment]
Hmm so possibly a red herring as the stack trace suggests a missing entry in craft_info:

![image](https://user-images.githubusercontent.com/3185073/55569134-ec6dae80-56f8-11e9-8e2c-30679e4906b7.png)

Message in the UI definitely flagged an SEOMatic migration failure though

**Comment by baileydoestech** [comment]
Raised with Pixel and Tonic to see if this is a Craft issue:

https://github.com/craftcms/cms/issues/4101
