### ISSUE TITLE
Switching to "same as SEO Image" doesn't respect transform settings

### ISSUE THREAD

**Issue by danieltott** [nystudio107/craft-seomatic#366]
If you create Twitter and Facebook image settings with transforms turned on, but then later switch it to "same as SEO Image", "Transform Twitter/Facebook Image" lightbox remains switched on even when hidden. 

I discovered this by turning off transforms in the main SEO Image settings, but was still seeing transforms in the `og:image` etc output. 

To reproduce: 
In Global SEO -> General, turn on image transforms.
In Twitter and/or Facebook, turn on image transforms.
Go back to Global SEO -> General, turn off image transforms.
Go to Twitter, set Twitter Image Source to "Same as SEO Image"

At this point the transform settings are hidden. Hit save, and go look at the templates - you'll see transforms for Twitter/Facebook images, but not the general one. 

This is true in the "Content SEO" sections as well.

**Comment by danieltott** [comment]
I was able to mitigate this in the short term by selecting "From asset field", turning off the "Transform Twitter Image" switch, then selecting "Same as SEO Image" again (works without saving in the middle). Craft is saving fields even if they're hidden.

**Comment by khalwat** [comment]
I'm trying to decide if this is a bug or not. The reason being, you almost always do want to have those transforms applied, regardless of whether the image is the same as the SEO image.

I guess it boils down to semantic, in terms of whether "Same As SEO Image" refers to the image alone, or the image and its actual dimensions.

**Comment by danieltott** [comment]
My feeling is that this *is* a bug - "Same as SEO Image" should be "same as seo image," unless the transform settings were not hidden. Then the source would be the same, but the settings would remain specific to the context (main,twitter,facebook). But in this case, "same as seo image" is not actually "same." 

I'm starting to think maybe the right solution here is to just not hide the image transform settings for each context. The "same" is really referring to the image source, since the transforms are different for each context anyway.

BTW, my use-case for turning off transforms is that I'm using imgix to serve images, and overwriting the `seoImage`, `ogImage`, and `twitterImage` paths in twig at runtime.

**Comment by khalwat** [comment]
If you used ImageOptimize or Imager to replace Craft transforms with Imgix transforms, it'd all work transparently, FWIW.

Anyway, I like your idea of just not hiding the transform switches.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/89f19964ce74ce6be51d8be4c02311a3b72c044f
