### ISSUE TITLE
Setting Tag Maganger include status not working

### ISSUE THREAD

**Issue by nilsenpaul** [nystudio107/craft-seomatic#367]
When using `{% do seomatic.script.get('googleTagManager').include(false) %}` to disabled Google Tag Manager from rendering if no cookie consent is given, it still gets rendered.

    {% set consentInfo = craft.ccc.consentInfo %}
    {% if not consentInfo.consentSubmitted or consentInfo.consent.statistics == false %}
        {% do seomatic.script.get('googleTagManager').include(false) %}
    {% endif %}

I use this in a template that gets extended, and can't figure out what I'm doing wrong.

**Comment by khalwat** [comment]
Since you're doing this based on a variable that can be different per-user, you'll need to bust the cache like this:

```twig
{% set consentInfo = craft.ccc.consentInfo %}
{% if not consentInfo.consentSubmitted or consentInfo.consent.statistics == false %}
    {% do seomatic.script.get('googleTagManager').include(false) %}
    {% do seomatic.script.container().clearCache(true) %}
{% endif %}
```

Have a look at the [Advanced SEOmatic tips](https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting) article for more.
