### ISSUE TITLE
Content SEO section name doesn't change after changing section name

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft-seomatic#368]
Section names aren't updating/changed in the content seo tab after renaming of some sections. Utilites - Clear caches hasn't helped.

Craft CMS 3.1.16

SEOmatic
3.1.45

Screenshots

Current sections
https://d.pr/free/i/P3qbQP

Content SEO tab

https://d.pr/free/i/7qBCYU

_Originally posted by @EmptyStreets in https://github.com/nystudio107/craft-seomatic/issues/331#issuecomment-470715961_

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/c03037453927a814cb627523216732e00e6fe5d8
