### ISSUE TITLE
rel="alternate" on disabled sections

### ISSUE THREAD

**Issue by chrisrowe** [nystudio107/craft-seomatic#370]
On a multisite installation I'm seeing SEOmatic output a `<link rel="alternate"` tag with a href pointing to the site homepage for all locales regardless of status. It should be omitting this tag when the section is disabled on a locale.

**Comment by khalwat** [comment]
Can you elaborate on this a bit @chrisrowe ?

Is there an element associated with the site homepage?

What do the tags look like, and what do you believe they should look like?

**Comment by chrisrowe** [comment]
@khalwat Sure! There is an element associated with the site homepage on all sites.

<img width="761" alt="Screenshot 2019-04-16 at 09 14 34" src="https://user-images.githubusercontent.com/220456/56189377-1774ce00-6028-11e9-9046-e5e6ba077287.png">

shows the `rel="alternative"` tags we're seeing even though the newsroom section is disabled for most sites.

<img width="399" alt="Screenshot 2019-04-16 at 09 12 46" src="https://user-images.githubusercontent.com/220456/56189288-da104080-6027-11e9-9ce1-ba6cb65f83c1.png">

I wouldn't expect those to appear for disabled sites.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/47973ee5e0d4dcb587b20d7898d4c1d5de816a33

**Comment by chrisrowe** [comment]
Thanks Andrew, any ETA on a release?

**Comment by khalwat** [comment]
You can pull from `dev-develop` right now to try it out  -- would actually be helpful to have verification "in the file" so in your `composer.json` something like:

```
...
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
...
        "nystudio107/craft-seomatic": "^3.0.0",
...
    }
...
```

**Comment by chrisrowe** [comment]
Yeah our weird CI doesn't permit that, I'll just wait it out. Thanks again!

**Comment by khalwat** [comment]
You can do it now if you want via Twig. If you do this:

```twig
    {% set alt = seomatic.link.get('alternate')%}
    {{ dump(alt) }}
```

...and you'll see something like this: 

```php
object(nystudio107\seomatic\models\MetaLink)[3875]
  public 'crossorigin' => null
  public 'href' => 
    array (size=3)
      0 => string 'http://craft3.test/' (length=19)
      1 => string 'http://craft3.test/' (length=19)
      2 => string 'http://craft3.test/es/' (length=22)
  public 'hreflang' => 
    array (size=3)
      0 => string 'x-default' (length=9)
      1 => string 'en-us' (length=5)
      2 => string 'es' (length=2)
```

So if you wanted to change this to whatever you want, you could do something like this:

```twig
    {% set alt = seomatic.link.get('alternate') %}
    {% do alt.href([
            'http://example.com',
            'http://example.com/es'
        ]).hreflang([
            'x-default',
            'es',
        ])
    %}
```

...to change it to be whatever you want.

**Comment by chrisrowe** [comment]
@khalwat I'm still seeing this issue despite updating to 3.1.49 and clearing caches etc. Not sure what else could be causing this or if theres any more info I can provide to help you replicate?

**Comment by khalwat** [comment]
I did test this locally, where I had a single that I disabled some of the sites, and it properly did not appear anymore. The relevant code:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L534

Not sure how/why that'd be different than your environment, but you can always use the Twig code above as well.

**Comment by chasegiunta** [comment]
@chrisrowe @khalwat I can confirm this wasn't fixed.

Not only that (and this is probably a sep issue), but given the scenario where all sites are enabled for a section (so authors could enabled & add content for an alternative page later), but the alternate entries for a page are disabled, those rel="alternate" links are still output.

**Comment by khalwat** [comment]
Here's my setup.

Sites:

![Google ChromeScreenSnapz1531](https://user-images.githubusercontent.com/7570798/57235851-d9007c80-6ff1-11e9-916c-04240ed9e3a1.png)

Note that "French" is _not_ in the same site group as the other 3.

Homepage Single:

![Google ChromeScreenSnapz1530](https://user-images.githubusercontent.com/7570798/57235895-efa6d380-6ff1-11e9-870e-16f056f8cdc7.png)

With everything on, it outputs the proper `alternate` links:

```html
<link href="http://craft3.test/it/" rel="alternate" hreflang="it-it">
<link href="http://craft3.test/es/" rel="alternate" hreflang="es">
<link href="http://craft3.test/" rel="alternate" hreflang="en-us">
<link href="http://craft3.test/" rel="alternate" hreflang="x-default">
```

Now if we disable one via the Section settings for the Homepage Single:

![Google ChromeScreenSnapz1532](https://user-images.githubusercontent.com/7570798/57235972-1238ec80-6ff2-11e9-8fc6-4c78fe7e4989.png)

It properly no longer appears:

```html
<link href="http://craft3.test/es/" rel="alternate" hreflang="es">
<link href="http://craft3.test/" rel="alternate" hreflang="en-us">
<link href="http://craft3.test/" rel="alternate" hreflang="x-default">
```

Please give me similar details on your setup to show the site settings, sections settings, and expected and actual results.

**Comment by khalwat** [comment]
> Not only that (and this is probably a sep issue), but given the scenario where all sites are enabled for a section (so authors could enabled & add content for an alternative page later), but the alternate entries for a page are disabled, those rel="alternate" links are still output.

Please open a separate issue for this if it is a different issue.

**Comment by chasegiunta** [comment]
Sites:
![image](https://user-images.githubusercontent.com/1377169/57239097-925e5280-6ff0-11e9-9dac-c328088e1784.png)

Retail Structure:
![image](https://user-images.githubusercontent.com/1377169/57239154-b0c44e00-6ff0-11e9-8b23-153ad56773da.png)

Output:
```
<link href="https://applause.test/es/" rel="alternate" hreflang="es">
<link href="https://applause.test/fr/" rel="alternate" hreflang="fr">
<link href="https://applause.test/de/" rel="alternate" hreflang="de">
<link href="https://applause.test/retail" rel="alternate" hreflang="en">
```

This is the latest, SEOmatic 3.1.50

**Comment by chasegiunta** [comment]
I can confirm that disabling a site for the homepage single **does** correctly not output rel="alternative" link for it

**Comment by chasegiunta** [comment]
So some quick tests with multiple Singles, Channels, and Structures seems to show that Single's, rel="alternate" links for disabled sites (via their section settings) are correctly not output, while Channels & Structures still incorrectly output them

**Comment by khalwat** [comment]
Same result here, it's working for me for a Channel:

With the Blog Channel set like this:

![Google ChromeScreenSnapz1533](https://user-images.githubusercontent.com/7570798/57243817-04d92d80-7005-11e9-8533-82db2c76d46e.png)

The result is this:
```html
<link href="http://craft3.test/it/blog/some-blog" rel="alternate" hreflang="it-it">
<link href="http://craft3.test/es/blog/some-blog" rel="alternate" hreflang="es">
<link href="http://craft3.test/blog/some-blog" rel="alternate" hreflang="en-us">
<link href="http://craft3.test/blog/some-blog" rel="alternate" hreflang="x-default">
```

If I then disable Italian:

![Google ChromeScreenSnapz1534](https://user-images.githubusercontent.com/7570798/57243880-2df9be00-7005-11e9-8a4c-b0d3608f48c0.png)

Then I get the expected result of:

```html
<link href="http://craft3.test/es/blog/some-blog" rel="alternate" hreflang="es">
<link href="http://craft3.test/blog/some-blog" rel="alternate" hreflang="en-us">
<link href="http://craft3.test/blog/some-blog" rel="alternate" hreflang="x-default">
```

This is when I'm on the blog entry page, e.g.: `http://craft3.test/blog/some-blog`

**Comment by khalwat** [comment]
@chasegiunta Are you sure you're not disabling the sections that you're _indexing_ on these pages, rather than disabling the _single_ itself (which is the targeted element for this page)?
