### ISSUE TITLE
New SEOmatic 3.x field requires a re-save to use custom entry images

### ISSUE THREAD

**Issue by aaronbushnell** [nystudio107/craft-seomatic#372]
We've migrated a site from Craft 2.x to 3.x and upgraded SEOmatic along with it. I've added the new SEOmatic field on entries that had the previous field and it does look like the data is being pulled in successfully (based on the migration work done in #53).

However, when viewing the source of these entries the `og:image` and `twitter:image` is defaulting to the site-wide images instead of the custom ones set within the entry (on the SEOmatic 2.x field).

If I re-save the entry in the control panel it changes the source to use the correct image, but only if I do this through the control panel directly. I cannot use `./craft resave/entries` to have the same effect.

Is there a faster/better way to ensure the custom images set on the SEOmatic 2.x field is being used in the new one without manually re-saving each entry? Happy to provide a database export/logs if that's useful.

**Comment by khalwat** [comment]
Same issue as https://github.com/nystudio107/craft-seomatic/issues/297

Would you mind posting the above in that issue?

And yes, a database would be really helpful.
