### ISSUE TITLE
Could not install because requirements could not be resolved

### ISSUE THREAD

**Issue by svale** [nystudio107/craft-seomatic#373]
Hi! 

Composer would not let me install craft-seomatic because of a version-conflict with  `davechild/textstatistics` (see output  below). I have this package installed already (in v1.0.3) as a dependency of `topshelfcraft/wordsmith`which has a looser requirement of  
```
"davechild/textstatistics": "^1.0"
```
As Seomatic asks for `1.0.2`specifically, I ended up downgrading  `davechild/textstatistics` to 1.0.2 in my root composer.json. But it feels like a wrong solution. And probably is, but it ended up being what worked in this case. 

Any suggestion for a better approach? And would you consider changing the Seomatic requirement to `^1.0`?

Thank you!

```shell
➜ ... git:(develop) ✗ composer require nystudio107/craft-seomatic:3.1.48
./composer.json has been updated                                      
Loading composer repositories with package information
Updating dependencies (including require-dev)                         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: davechild/textstatistics[1.0.2, 1.0.3].
    - Can only install one of: davechild/textstatistics[1.0.3, 1.0.2].
    - Can only install one of: davechild/textstatistics[1.0.2, 1.0.3].
    - nystudio107/craft-seomatic 3.1.48 requires davechild/textstatistics 1.0.2 -> satisfiable by davechild/textstatistics[1.0.2].
    - Installation request for nystudio107/craft-seomatic 3.1.48 -> satisfiable by nystudio107/craft-seomatic[3.1.48].
    - Installation request for davechild/textstatistics (locked at 1.0.3) -> satisfiable by davechild/textstatistics[1.0.3].


Installation failed, reverting ./composer.json to its original content.

```
---
Maybe related to https://github.com/nystudio107/craft-seomatic/issues/218

**Comment by khalwat** [comment]
So the reason I did this was explained here:

https://github.com/nystudio107/craft-seomatic/issues/215

Given the jump from 5.6 to 7.2 in a patch release... I don't see any great option other than to lock it down.

You could also use Typogrify to do what WordSmith does, if that helps.

**Comment by svale** [comment]
Right, I see. Yeah, that's quite a stretch for a patch release...

I'll have a look at Typogrify.

 Cheers

**Comment by khalwat** [comment]
Yeah sorry I don't have a better answer, I just don't know what else I can do in this case.

It's on the package maintainer.
