### ISSUE TITLE
Set "Content SEO" on dynamic route or section without URI

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#376]
Hi,

I'm facing a problem. I want to have the best solution without setting SEO settings for each entry and I want to manage SEO only on the Admin Panel's side. So, usually, I manage this in SEOmatic > Content SEO.

But, what if I have a dynamic route ?

For exemple, my entry have multiples cities and I want a unique URL to each city, like this : `offers/{city}/{slug}`. But, to do this, I can't set a section URI format because it is only for one URL.

So, I manage my URL with a dynamic route like this : `offers/*/{slug}`. If *'s token does exist and is related to the entry, I show my page otherwise I exit to 404.

(I know that I can create multiple same entries related to only one city at each time, but, I would like something scalable and highly maintainable.)

Can SEOmatic manages dynamic routes in a near future ? Is this even possible ?

I hoped I was clear 😅
Thanks for your time

**Comment by khalwat** [comment]
So you can do it right now... using the built in Twig function `seomatic.helper.loadMetadataForUri` -- check out an example if that in use here:

[Rendering Metadata from another Route](https://nystudio107.com/blog/tips-for-using-seomatic-effectively#rendering-metadata-from-another-route)

**Comment by LouisCuvelier** [comment]
Thank you !

**Comment by LouisCuvelier** [comment]
Just one more question : what about the sitemap ?

**Comment by LouisCuvelier** [comment]
How the sitemap is managed by this method ?

**Comment by LouisCuvelier** [comment]
Answered in #386
