### ISSUE TITLE
Modifing individual landingpages

### ISSUE THREAD

**Issue by Onlogist2019** [nystudio107/craft-seomatic#378]
Im new to SEOMatic and I have done the Global SEO setup through SEOMatic on Craft. 
Now, I would like to setup every Landingpage individually - unfortunately I am only able to do a generic setup for all my landingpages. 

If its already possible to set up LPs individually, maybe someone could point me in the right direction. 

Cheers

**Comment by jamesmacwhite** [comment]
For individual SEO, you can use the SEO Settings field. Although, could you create a section called "Landing pages" where all your landing page entries would sit under and the configure the SEO by the section?

**Comment by Onlogist2019** [comment]
After clicking on "Landingpage" SEOMatic will only show me a general Setup. 

![1](https://user-images.githubusercontent.com/49973970/56738851-c70b1800-676d-11e9-8dbb-eaf3601ebc5c.png)
![2](https://user-images.githubusercontent.com/49973970/56738852-c7a3ae80-676d-11e9-8275-79950353bfcd.png)
![3](https://user-images.githubusercontent.com/49973970/56738853-c7a3ae80-676d-11e9-8ffe-1def7dc0aef7.png)

**Comment by khalwat** [comment]
@Onlogist2019 You can use an SEO Settings field as per: https://github.com/nystudio107/craft-seomatic#seomatic-fields

Or you can do it via Twig as per: https://github.com/nystudio107/craft-seomatic#twig-templating
