### ISSUE TITLE
Tracking scripts settings on multi-site setup

### ISSUE THREAD

**Issue by fthues** [nystudio107/craft-seomatic#379]
We have a project that consists of four localized sites, all in the same site group since they're just translations. All sites need the same tracking functionality (Google Analytics and Tag Manager). 

I have found that the tracking scripts get rendered on the primary site only, which is where I have enabled the functionality. Do I need to manually copy all the tracking settings to each site or is there a way to tell SEOmatic (maybe via a template function?) to just use the primary site's tracking script settings? Thanks!

**Comment by khalwat** [comment]
Yes, all of SEOmatic's settings are on a per-site basis, so you'd need to copy them to each site.

You could also do it via Twig if you wanted to, though: https://github.com/nystudio107/craft-seomatic#twig-templating
