### ISSUE TITLE
Getting error trying to use multi-site tracking scripts

### ISSUE THREAD

**Issue by keithmancuso** [nystudio107/craft-seomatic#38]
Loving the new seomatic so far but got an error i thought I should let you know about

I have a multi-site setup and when i got to tracking scripts and I try to switch to any of the other sites i get

Internal Server Error
Undefined index: healthcare

Site settings and global seo both seem to work with multi-site

**Comment by khalwat** [comment]
healthcare? Is the site somehow related to healthcare or something? Can you get me a full stack trans on this error?

**Comment by khalwat** [comment]
Never mind, I found it. Fixed in https://github.com/nystudio107/craft-seomatic/commit/393bcc6a59b72a5f0e0250c28521c8abc01eed9d

**Comment by keithmancuso** [comment]
That was fast, thanks!  And yea healthcare was the sitename and I should have mentioned that
