### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by lindseydiloreto** [nystudio107/craft-seomatic#380]
```
/admin/seomatic/site/miscellaneous/en_us
```

"Miscallaneous"

<img width="512" alt="Ω 2019-04-25 at 8 39 57 PM" src="https://user-images.githubusercontent.com/5309692/56782124-955c7600-679a-11e9-9f94-aeccd983baf6.png">

**Comment by khalwat** [comment]
thx fixed in <https://github.com/nystudio107/craft-seomatic/commit/032b9bc01bd75fc7a2dda4488d9b2706b1728e6c>
