### ISSUE TITLE
Error 500 after deactivation of Include x-default hreflang Tag

### ISSUE THREAD

**Issue by pau-ker** [nystudio107/craft-seomatic#382]
I got an Internal Servererror after set Include x-default hreflang Tag to false. 
I cant even log into the Backend. How can i set it back to the inital state?

Thanks!

**Comment by khalwat** [comment]
This is fixed in: https://github.com/nystudio107/craft-seomatic/commit/183a2f1e8c1af718482a54749b8fa0c5db8ce738

You can disable the setting either via Project Config (if you're using the `project.yaml` or via the `config.php` -- just change the `addXDefaultHrefLang` setting to `true`
