### ISSUE TITLE
[FR] Do a better job dynamically syncing up new Content SEO (was: Commerce product types missing)

### ISSUE THREAD

**Issue by mcjackson18** [nystudio107/craft-seomatic#383]
Craft: Craft Pro 3.1.23
Craft Commerce: 2.1.3.1
Seomatic: 3.1.49

When a new product type is added or a product type handle is changed it doesn't display in the 'Content SEO'. I've also check the seomatic_metabundles table and the updates are not made in there. Likewise when a product type is deleted it isn't removed from the metabundles table.

If I uninstall Seomatic and reinstall they are displayed but product types can't be add/edited after.

Is sounds similar to this issue - https://github.com/nystudio107/craft-seomatic/issues/204

**Comment by khalwat** [comment]
If you navigate to the commerce type either in the CP or on the frontend, it'll create it.

Probably it should do a better job syncing this up in general, though

**Comment by khalwat** [comment]
This is addressed in SEOmatic 3.2.18
