### ISSUE TITLE
Content SEO settings not being applied

### ISSUE THREAD

**Issue by jwb009** [nystudio107/craft-seomatic#384]
I have my Content SEO Image Source set to pull from an Asset Field for a section. The entries in this section also have the SEO Fieldtype so I can override things on occasion. The problem is that the SEO field is defaulting the SEO Image Source to 'Custom Image' instead of the Asset Field I selected. This causes the entry to fall back to the Global SEO Image. 

I have to manually select the correct SEO Image Source and resave each entry to get the correct image displayed. Is there any better way to do this? Thanks!

This site is an upgrade from C2 > C3 so I was also using the old SEOmatic fieldtype, and upgraded per the wiki.

Craft CMS 3.1.23
SEOMatic 3.1.48

**Comment by khalwat** [comment]
So this is actually normal, it's just probably confusing.

The SEO Settings field is meant to be an _override_ of your Content SEO settings. If you leave a blank "custom image" (as is the default), it just falls back on the Content SEO settings.

This is probably poor UX, and there's an issue here discussing it further: https://github.com/nystudio107/craft-seomatic/issues/248

**Comment by jwb009** [comment]
Thanks for the reply! So I guess my issue is that it's _not_ actually falling back to the Content SEO settings. Maybe images will help explain:

Here's the image setting for Content SEO for my 'projects' section:
<img width="407" alt="Screen Shot 2019-05-03 at 9 28 18 AM" src="https://user-images.githubusercontent.com/7241260/57144238-44461680-6d86-11e9-8cbd-4b59e2b6341a.png">

Global SEO image setting:
<img width="320" alt="Screen Shot 2019-05-03 at 9 28 39 AM" src="https://user-images.githubusercontent.com/7241260/57144286-5de75e00-6d86-11e9-8b40-4fc4e4e7b75e.png">

A project entry which hasn't had any SEO overrides applied:
<img width="1001" alt="Screen Shot 2019-05-03 at 9 33 09 AM" src="https://user-images.githubusercontent.com/7241260/57144344-82433a80-6d86-11e9-96b9-af47ee1f755d.png">

You can see that the entry is pulling the title and description correctly from Content SEO settings, but the image is not. That's falling back to the Global SEO image, not 'Feature Photo' field as it should.

**Comment by khalwat** [comment]
This, sadly, moves us to _another_ known existing issue -> https://github.com/nystudio107/craft-seomatic/issues/297#issuecomment-457288553

**Comment by jwb009** [comment]
Ah right on.  I'll watch that issue, and manually resave entries in the meantime. Thanks again!

**Comment by khalwat** [comment]
Not the entries… you should just need to save each Content SEO section.

**Comment by jwb009** [comment]
I did try that, but it didn't seem to do anything.

**Comment by khalwat** [comment]
You have to re-save it from both the Twitter and the Facebook sub-tabs.

**Comment by jwb009** [comment]
Oh man, that never crossed my mind. Works great now. Thanks Andrew

**Comment by khalwat** [comment]
Sorry for the bug, I know it's a stupid one.

**Comment by jwb009** [comment]
No worries...pretty minor in my book.
