### ISSUE TITLE
Named query parameter is stripped from `potentialAction.target`.

### ISSUE THREAD

**Issue by mattstein** [nystudio107/craft-seomatic#385]
My keyword's getting stripped out of `search?q={keyword}` similarly to [an earlier issue](https://github.com/nystudio107/craft-seomatic/issues/171), but in a Twig context rather than the SEOmatic control panel setting that applies to the entire site.

I'm trying to make search links available only on a subset of the site's pages rather than the entire site. To do this, I'm using `setAttributes` in a Twig template to modify the main entity in relevant pages:

```twig
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}

{% do mainEntity.setAttributes({
    'potentialAction': {
        'type': 'SearchAction',
        'target': siteUrl ~ 'blog/search?q={keyword}',
        'query-input': "required name=keyword"
    },
}) %}
```

What I'd expect is for the output to include `search?q={keyword}`, but the rendered target omits `{keyword}`:

```
...
"potentialAction": {
    "@type": "SearchAction",
    "query-input": "required name=keyword",
    "target": "https://foo.dev/blog/search?q="
},
...
```

Trying to escape with filters has no effect:

- `'target': siteUrl ~ ('blog/search?q={keyword}'|raw),`
- `'target': siteUrl ~ ('blog/search?q={keyword}'|escape),`

Using character entities (`&#123;keyword&#125;`) renders the entity numbers rather than the corresponding characters.

Wrapping any part of the target value in `verbatim` tags...

```
'target': siteUrl ~ '{% verbatim %}blog/search?q={keyword}{% endverbatim %}'
```

...renders in some useless intrigue...

```
"target": "https://foo.dev/blog/search?q={{ (_variables.keyword ?? object.keyword)|raw }}"
```

The same approach with `raw` tags renders something still worthless but slightly closer: 

```
"target": "https://foo.dev/{% raw %}blog/search?q={keyword}{% endraw %}"
```

I can work around this using JavaScript like a barbarian, but ideally the `{keyword}` wouldn't get parsed away or there'd be some simple way to escape the braces and allow them to be rendered in the result.

- Craft 3.1.25
- SEOmatic 3.1.50
- PHP 7.2 and 7.3

**Comment by khalwat** [comment]
So here's a hacky way it can be done:

```twig
{% do seomatic.site.siteLinksSearchTarget("{keyword}") %}
{% do mainEntity.setAttributes({
    'potentialAction': {
        'type': 'SearchAction',
        'target': siteUrl ~ "blog/search?q={seomatic.site.siteLinksSearchTarget}",
        'query-input': "required name=keyword"
    },
}) %}
```

This outputs:
```JSON
"potentialAction": {
    "@type": "SearchAction",
    "query-input": "required name=keyword",
    "target": "http://craft3.test/blog/search?q={keyword}"
    },
```

This works because the `siteLinksSearchTarget` is a key that doesn't get parsed; a "magic" key if you will: https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/MetaValue.php#L41

This works, but it's not something I'd tell my mother I did.

Perhaps a better long-term solution is to add a flag to the base `MetaItem` model indicating whether it should be parsed as Twig.

Or a way to set that for a particular field, or maybe even (ugh) a magic string like `<!` that will cause it to strip the prefix, and then not parse the string.

**Comment by mattstein** [comment]
Works great @khalwat, and I won't tell your mother either. Thank you!

**Comment by khalwat** [comment]
Unsatisfied with the above answer, I fixed this via https://github.com/nystudio107/craft-seomatic/commit/8ebff6af6b874ebffac3cfd6b29d0248a246b263

* If a meta value with the key of `target` (used for schema.org `SearchAction`s) doesn't have a `{` as the first character, it is not parsed as Twig

This means that your original code:

```twig
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{% do mainEntity.setAttributes({
    'potentialAction': {
        'type': 'SearchAction',
        'target': siteUrl ~ 'blog/search?q={keyword}',
        'query-input': "required name=keyword"
    },
}) %}
```

works unmodified, and generates:
```
    "potentialAction": {
        "@type": "SearchAction",
        "query-input": "required name=keyword",
        "target": "http://craft3.test/blog/search?q={keyword}"
    },
```

**Comment by mattstein** [comment]
Even better @khalwat, thanks again!
