### ISSUE TITLE
Facebook Article Author

### ISSUE THREAD

**Issue by johnj24** [nystudio107/craft-seomatic#387]
Is there a setting in SEOMatic that sets the Facebook Article Author? I noticed in SEOMatic for Craft 2 that an article:author meta property is output automatically, but in SEOMatic for Craft 3 there is not.

**Comment by khalwat** [comment]
This is something that could be added -- though often times the author isn't a person it's an organization. You can add it yourself pretty easily as well:

```twig
{% do seomatic.tag.create({
    'property': 'og:author',
    'content': entry.author.fullName
}) %}
```
