### ISSUE TITLE
Incorrect x-default

### ISSUE THREAD

**Issue by dmatthams** [nystudio107/craft-seomatic#389]
I have both a 'en' (primary) and an 'en-gb' locale on my site, but the generated meta shows the en-gb as url as the 'x-default'.

The 'en-gb' used to be the primary site before reshuffling so this could be the problem?

P.S blown away by the detail & documentation of this plugin 👌

**Comment by khalwat** [comment]
@dmatthams so it uses whatever your first site is for the x-default (because there's no Craft way to set a concept of a "default" site)

**Comment by dmatthams** [comment]
Ok that makes sense, will just hard-code in.
