### ISSUE TITLE
Unable to save SEO titles from entries

### ISSUE THREAD

**Issue by cenergydigital** [nystudio107/craft-seomatic#394]
When I go into 'Entries' and switch from Page to SEO -- I'm unable to enter and save an SEO title and have it display.

Craft CMS 2.7.2
SEOmatic 1.1.56

Any help is appreciated!

This is for https://www.flattech.com/us/

Pro version.

Thank you!

Jamison

**Comment by khalwat** [comment]
This is for the Craft 3.x version of SEOmatic. The Craft 2.x version is here: https://github.com/nystudio107/seomatic
