### ISSUE TITLE
SEOMatic outputting local set up values on live site

### ISSUE THREAD

**Issue by solivan** [nystudio107/craft-seomatic#395]
I have a single site install that is live (DevMode is off in the Craft settings file, SEOMatic is set to live) and SEOMatic's settings recognizes it as such but, the Robots.txt is outputting as if its configured for a local set up. 

```
# local - disallow all

User-agent: *
Disallow: /
```

Likewise, the meta robots tag output is `<meta name="robots" content="none">` X-Robots-Tag: none.

What can I do to troubleshoot this, Andrew?

**Comment by khalwat** [comment]
What is your `ENVIRONMENT` `.env` variable set to?

**Comment by solivan** [comment]
Yup total noob move on my part. .env was indeed set up incorrectly. Thanks for the support, Andrew! Have a great weekend.
