### ISSUE TITLE
TypeError prevents new Sections from being created

### ISSUE THREAD

**Issue by mattstein** [nystudio107/craft-seomatic#396]
If I attempt to create a new Section from the control panel, specifically with SEOmatic 3.2.0, I'm met with a type error:

```
Return value of nystudio107\seomatic\seoelements\SeoEntry::mostRecentElement() must implement interface craft\base\ElementInterface, null returned
```
<img width="1043" alt="Screen Shot 2019-05-20 at 9 45 49 PM" src="https://user-images.githubusercontent.com/2488775/58069047-aeadd380-7b48-11e9-8c72-86fb1db4f05f.png">

If I step back to 3.1.50, I'm able to create the Single as expected. Disabling 3.2.0, creating the Section, the re-enabling works fine too.

- SEOmatic 3.2.0
- Craft 3.1.27

**Comment by mark-chief** [comment]
Prevents creation of new category groups too. Same version as above.

**Comment by khalwat** [comment]
Ooops. Fixed in https://github.com/nystudio107/craft-seomatic/commit/5b2b38e958c48b93ecfa1e5c06da76e1a4531c07

I will release 3.2.1 with this fix shortly

**Comment by mattstein** [comment]
Thank you!
