### ISSUE TITLE
SEOmatic update failure Integrity constraint violation

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [nystudio107/craft-seomatic#398]
I have a site that is running `3.1.49` and am getting this error:

```
Integrity constraint violation: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "migrations_pkey"
DETAIL:  Key (id)=(2) already exists.
The SQL being executed was: INSERT INTO "migrations" ("type", "pluginId", "name", "applyTime", "dateCreated", "dateUpdated", "uid") VALUES ('plugin', 7, 'm190518_030221_calendar_events', '2019-05-21 17:41:42', '2019-05-21 17:41:42', '2019-05-21 17:41:42', '386bd5f6-8ac9-4450-967a-57a8e3ea3a94')
```

It's worth noting that this project is running `postgres` and I have had some other weird issues in the past with how it auto-increments the ID column values. I'm not sure if the migration fails because of that or not. 

I'm running `Craft CMS 3.1.27` and `PHP 7.2.15`. Thanks for the help!

**Comment by khalwat** [comment]
I have several sites running Postgres that haven't run into this issue. Are you also using Project Config?

**Comment by khalwat** [comment]
I'm reasonably certain that what is going on here is you're running the migration in multiple environments, and then deploying the database with the resulting migration done -- but not also simultaneously deploying the `project.yaml` file.

What I would suggest as a workflow would be to run the migrations locally, then deploy the resulting `project.yaml` file and either let the migrations run on that new environment, or only after you've deployed the `project.yaml` do you attempt to copy the database down.

This isn't really an SEOmatic thing, it's going to happen with any plugin that runs migrations with your current workflow.

**Comment by DynamiteGoesBoom** [comment]
What you described is how I am working on all of my projects. I never deploy the database to any of the environments. I do, from time to time, refresh local/staging's db from production. But I never deploy db's to prod. I refresh the db's so that we are working with the latest content.

There's definitely something going on with SEOMatic's migration. I first emailed Craft Support about it and they said to reach out to you about it, I just recently updated Craft the same way without issue. 

What else can I try?

**Comment by khalwat** [comment]
I don't think this has anything to do with SEOmatic at all; the error you gave is this:

```
Integrity constraint violation: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "migrations_pkey"
DETAIL:  Key (id)=(2) already exists.
The SQL being executed was: INSERT INTO "migrations" ("type", "pluginId", "name", "applyTime", "dateCreated", "dateUpdated", "uid") VALUES ('plugin', 7, 'm190518_030221_calendar_events', '2019-05-21 17:41:42', '2019-05-21 17:41:42', '2019-05-21 17:41:42', '386bd5f6-8ac9-4450-967a-57a8e3ea3a94')
```

This is not SEOmatic that attempts to add anything to the `migrations` table, it is Craft. And Craft is saying that a migration with that id already exsits.

The only way that makes sense is if the migration was already run on the database in question.

If you look at the migration in question, it doesn't do anything with the tables mentioned above: https://github.com/nystudio107/craft-seomatic/blob/v3/src/migrations/m190518_030221_calendar_events.php

**Comment by DynamiteGoesBoom** [comment]
That makes sense. I think the thing happening here is that prod has an older version of Project Config. When I dump from that and import it into Staging, that has a newer version of Project Config, then it causes errors like that. Does that sound right?

**Comment by DynamiteGoesBoom** [comment]
Although now, I just pulled prod's project config and imported the db locally. After that I tried upgrading SEOMatic again and get the same error:

```
Integrity constraint violation: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "migrations_pkey"
DETAIL: Key (id)=(1) already exists.
The SQL being executed was: INSERT INTO "migrations" ("type", "pluginId", "name", "applyTime", "dateCreated", "dateUpdated", "uid") VALUES ('plugin', 7, 'm190518_030221_calendar_events', '2019-05-21 19:03:15', '2019-05-21 19:03:15', '2019-05-21 19:03:15', 'ed33b0b4-6518-4fd2-b173-cb8d4d4a48ec')
```
What else can I do?

**Comment by khalwat** [comment]
Delete the row in the migrations table that it is complaining about. Or have the proper version of the `project.yaml` deployed where it has the updated schema version for the SEOmatic plugin in it.

Again, I think this is a generic "plugin migration" issue
