### ISSUE TITLE
Custom SEO Image On Entry Misbehaving

### ISSUE THREAD

**Issue by theskyfloor** [nystudio107/craft-seomatic#399]
When I try to override an SEO image on an entry via the custom SEO fieldset the field starts saving the same image over and over again on each subsequent save... this is the default image set in the content SEO settings. The by product of this bug is that I can't actually override the SEO image either. Thanks!

<img width="872" alt="Screen Shot 2019-05-21 at 4 48 31 PM" src="https://user-images.githubusercontent.com/8887839/58133400-57ac0b00-7be9-11e9-9a75-51af809ac1f5.png">

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-seomatic/commit/1ca809b7c80903fbabb509fd8a27ba4778e3e5c5
