### ISSUE TITLE
SEOmatic for Craft 3 is not ready yet

### ISSUE THREAD

**Issue by Saboteur777** [nystudio107/craft-seomatic#4]
Sorry for trolling. :) Tried to set the title as generic as possible to only close this issue when it is ready to roll. (hidden subscription for a **SEOmatic for Craft** 3 notification)

**Comment by khalwat** [comment]
aha, but what if I close this issue now? What is your next play @Saboteur777 ?? 🗡

**Comment by mbanta88** [comment]
Following:)

**Comment by Saboteur777** [comment]
@khalwat  Hmhm... I might open up another one! 👊

**Comment by Emkaytoo** [comment]
So I saw one issue on the repo landing page and I thought to myself "I hope someone just put an issue that it's not ready yet."

Lo and behold, I was not disappointed.

**Comment by khalwat** [comment]
https://github.com/nystudio107/craft-seomatic/releases/tag/3.0.0-beta.1

:)

**Comment by Saboteur777** [comment]
Awesome, thanks! :) :+1:

**Comment by darylknight** [comment]
FYI, this is the first result on Google:
![image](https://user-images.githubusercontent.com/1250017/42687882-f0ec8aa2-86a2-11e8-9c6e-88408f23c15b.png)
