### ISSUE TITLE
[FR] Ability to get meta bundle data and use it in page templates

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-seomatic#40]
I have a search results page with results that contain entries from different sections, and I want to display a page description for each entry on my search results page. I could get this from the same fields in the entries that SEOmatic pulls from, but it would be easier to get the data from SEOmatic directly.

Having a function, like `seomatic.bundles.getByUri()`, would make it easy to pull page titles, descriptions, and other info that's already been processed by SEOmatic.

**Comment by khalwat** [comment]
The `seomatic.helper.loadMetadataForUri()` function that SEOmatic provides loads all of the meta containers associated with a given URI into the containers on the current page. Effectively, it allows you to load up the meta data for any URI onto a given page. I use this for the AMP versions of my pages, for instance, which don't have an `entry` injected into them like this:

```
{% if entry is not defined %}
    {% set entrySlug = craft.app.request.getSegment(2) %}
    {% set entry = craft.entries({
        "section": "episodes",
        "slug": entrySlug,
    }).one() %}
{% endif %}

{% do seomatic.helper.loadMetadataForUri(entry.uri) %}
```

How in this case, what @wbrowar is looking for is different; he wants to iterate through entry metadata, and output for users to read on the page.
