### ISSUE TITLE
[FR] CraftQL support lack of asArray option

### ISSUE THREAD

**Issue by minyan-gu** [nystudio107/craft-seomatic#401]
Hello,

Thanks for adding the support on CraftQL, now we can finally query our SEO content using GraphQL.

However, it seems lack of support for the `asArray` option, to us it is a very important use case that the query response only returns data w/o html render. It is our static site generator's job to add those HTML tags accordingly.

As per the readme, I believe the asArray feature already exists, so would you be able to quickly add this option in GraphQL schema? So I can query sth like below:

      seomatic(asArray: true) {
        metaTitleContainer
        metaTagContainer
        metaLinkContainer
        metaScriptContainer
        metaJsonLdContainer
      }

**Comment by khalwat** [comment]
Yeah that's exactly how I'd add that option, and it shouldn't be too hard to do. The issue that I ran into is that it's returning an arbitrarily deep nested JSON array, and having that play nice with CraftQL was something I hadn't figure out yet.

**Comment by khalwat** [comment]
Filed this asking for more info https://github.com/markhuot/craftql/issues/276

**Comment by khalwat** [comment]
![Google ChromeScreenSnapz012](https://user-images.githubusercontent.com/7570798/58739084-7de65d80-83d6-11e9-93ca-5d0bc22384dc.png)

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/a37795183205b417e2e58ba5820595bd0427f583

**Comment by codyjames** [comment]
I keep getting
```
 "{
  "error": "String cannot represent non scalar value: array(0)"
}"
```
when trying to use this. Any ideas?

<img width="1026" alt="Screen Shot 2019-06-10 at 4 17 44 PM" src="https://user-images.githubusercontent.com/378665/59232956-6019b500-8b9b-11e9-9723-f4d6a97e2601.png">

**Comment by codyjames** [comment]
You can hold off on looking into this. I think I'm onto something.

**Comment by codyjames** [comment]
This goes away if I remove "metaScriptContainer" which is blank. So, I can just remove that one for our project.

**Comment by codyjames** [comment]
Also, thanks so much for adding this! We now get to remove a bunch of code!
