### ISSUE TITLE
EmptyCoalesce composer warning

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-seomatic#402]
The deprecated expression files are causing composer some confusion when generating the autoload. I haven’t encountered any issues (yet) so this is mainly cosmetic.

```
Warning: Ambiguous class resolution, "Twig_Node_Expression_EmptyCoalesce" was
found in both "/project/vendor/nystudio107/craft-emptycoalesce/lib/Twig/Node
/Expression/EmptyCoalesce.php" and "/project/vendor/nystudio107/craft-seomatic
/lib/Twig/Node/Expression/EmptyCoalesce.php", the first will be used.
```

Can [nystudio107/craft-seomatic](https://github.com/nystudio107/craft-seomatic) not just depend on [nystudio107/craft-emptycoalesce](https://github.com/nystudio107/craft-emptycoalesce)?

**Comment by khalwat** [comment]
Yeah this is fine, it's a soft warning. If you want to get rid of the warning, you can uninstall the Empty Coalesce plugin.
