### ISSUE TITLE
Setting a custom canonical link on the 'View all' version of a category page

### ISSUE THREAD

**Issue by j-greig** [nystudio107/craft-seomatic#403]
One question - on the unpaginated 'View all' page for a product category ('/products/category-slug/all') how would you set the canonical link to be ('/products/category-slug')?

I've found `{% do seomatic.meta.canonicalUrl() %}` and have placed `{% do seomatic.meta.canonicalUrl('https://pah.com') %}` in the <head> of the main _layout.twig template as a test, but I don't think I'm using it correctly as nothing changes in the <head> markup... where does it need to go in the templates?

**Comment by j-greig** [comment]
PS. The "Automatic Render Enabled" switch is _on_ and I've cleared the SEOmatic cache on my local machine.

**Comment by j-greig** [comment]
Ahhh, it's because I was calling `{% do seomatic.helper.paginate(pagination) %}` in the pagination block further down the page (even though it's not needed on the 'View all' page)

**Comment by khalwat** [comment]
Correct @j-greig
