### ISSUE TITLE
Hreflang tags are being created for disabled entries

### ISSUE THREAD

**Issue by gavinplatt** [nystudio107/craft-seomatic#404]
We're experiencing an issue with version 3.2.2. where hreflang tags are being generated even when an entry is disabled in that language. 

E.g. where `en` is the default language and that entry is enabled, and we also have an `es` entry that's disabled, a `<link href="sitename.com/es/entry-slug" rel="alternate" hreflang="es">` tag is being output.

Expected behaviour is that the hreflang tag would only be generated if that language version of the entry is enabled.

**Comment by khalwat** [comment]
I'm going to need as much information as possible about your setup, because I'm unable to replicate this here.

Can you give me screenshots of how these entries are disabled?

**Comment by chasegiunta** [comment]
As always, I'll try to dig in where I can when I get the opportunity.

![unknown](https://user-images.githubusercontent.com/1377169/58205972-5f30ea00-7ca5-11e9-9db5-7d888eb75201.png)

![unknown-1](https://user-images.githubusercontent.com/1377169/58205989-6a841580-7ca5-11e9-87af-d5b3fe1a3caa.png)
![image](https://user-images.githubusercontent.com/1377169/58206020-78399b00-7ca5-11e9-8d06-ec925e4cc8cf.png)

**Comment by khalwat** [comment]
I should be hitting this condition:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L536

or this condition:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L582

But it appears it is not?

**Comment by chasegiunta** [comment]
Cool. That'll help me debug when I get around to it.

**Comment by khalwat** [comment]
So here's the problem code in question:
```php
                    if (!empty($element->enabledForSite) && !$element->enabledForSite) {
                        $includeUrl = false;
                    }
```

This has two issues with it. The first is that `$element->enabledForSite` comes from the db looking like this:

```php
[enabledForSite] => '0'
```

...which unfortunately evaluates to `true` for the first conditional. Fixed in https://github.com/nystudio107/craft-seomatic/commit/62a01f5a46eec6524cad5722546c4fc006776bf3
