### ISSUE TITLE
Query param page triggers showing in rel="alternate" URLs

### ISSUE THREAD

**Issue by chasegiunta** [nystudio107/craft-seomatic#405]
Related to #375 - which was addressed for page triggers like `/p2/` and was fixed with https://github.com/nystudio107/craft-seomatic/commit/11846dbd05df201124f56c2ae9f14319145f45ce (the right fix was to remove pagination triggers from URLs altogether)

Query param page triggers don't seem to be removed.

What should be this:
```
<link href="http://craft3.test/es/bloges" rel="alternate" hreflang="es">
<link href="http://craft3.test/blog" rel="alternate" hreflang="en-us">
<link href="http://craft3.test/blog" rel="alternate" hreflang="x-default">
<link href="http://craft3.test/blog" rel="prev">
<link href="http://craft3.test/blog/p3" rel="next">
```

Is outputting as this:
```
<link href="http://craft3.test/es/bloges?page=2" rel="alternate" hreflang="es">
<link href="http://craft3.test/blog?page=2" rel="alternate" hreflang="en-us">
<link href="http://craft3.test/blog?page=2" rel="alternate" hreflang="x-default">
<link href="http://craft3.test/blog" rel="prev">
<link href="http://craft3.test/blog?page=3" rel="next">
```

**Comment by khalwat** [comment]
This is an error of omission; it should be fixed via https://github.com/nystudio107/craft-seomatic/commit/84dc47b0b1611e6f874e66ab0d39a250870f3e2d
