### ISSUE TITLE
Look up Latitude/Longitude never seems to work

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#406]
Hi Andrew,

One thing I have not been able to get to work in SEOmatic is the Latitude/Longitude lookup. Every site I have tried it on I get the following error:
`No location found. Perhaps the address is wrong/incomplete?`

I then resort to using this web service instead.
https://www.latlong.net/

This isn't a major issue to me, but though i'd mention it in case you want to investigate.

An example address is attached:
<img width="1265" alt="Screenshot 2019-05-24 at 17 06 10" src="https://user-images.githubusercontent.com/5698596/58341498-46136f00-7e46-11e9-8290-c6b151f1dee3.png">

**Comment by khalwat** [comment]
Ah yes. This is due to Google now requiring an API to do said lookup. Probably it makes sense to just remove the feature, sadly.

**Comment by terryupton** [comment]
Yeah no worries. Better removed than redundant :-).

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/8ca15f564e5bbcafb065a15a1d31a8174a8fac35
