### ISSUE TITLE
Replace "steps" by "step" in HowTo JSON-LD

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#409]
Hi,
Like I said in February (see #333), "steps" was replaced by "step".

Is it possible to update this please ? 🙏🏼
I'm having a lot of errors from Google Search Console because of this.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6a948be732ba141fa1ba1fe1e5256800808431e3

**Comment by khalwat** [comment]
btw @LouisCuvelier I'll be coming out with a nice article on my blog tomrrow about custom JSON-LD that you might find interesting!

https://nystudio107.com/blog

**Comment by LouisCuvelier** [comment]
Thanks ! Count on me, I will read that meticulously 🔥
