### ISSUE TITLE
og:image:url not converting white spaces

### ISSUE THREAD

**Issue by wei2go** [nystudio107/craft-seomatic#411]
Seems like Open Graph doesn't like white spaces in og:image:url tag, giving out error:

**Indicates that a URL property has whitespace characters, which is not allowed.**

If we have assets folder / file name containing white spaces, it's not automatically converted into %20 by SEOMatic.

Is this something you can look into please?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/4e32cbcb23fb0bc6fe560925fd1477304bf4f5e7
