### ISSUE TITLE
Impossible to invoke a method ("src") on a null variable.

### ISSUE THREAD

**Issue by jacksoncool** [nystudio107/craft-seomatic#412]
Andrew, 

When I'm using the following code in a template page I get the error written in the issue title above.  The code below is being used on a "pagebuilder" type page where the image is a simple block.

One thing to note my Asset field is part of a neo field. 

               {% if module.image %}
                {% set img = module.image.one().optimizedImagetransform %}
              
                        <img src="{{ img.src(1200) }}"
                        srcset="{{ img.srcset() }}"
                        sizes="100vw" />
             
                {% endif %}

also, i get this issue if an image is in the image field or not.

**Comment by khalwat** [comment]
So the issue here is `optimizedImageTransform` is null. Why is it null? I'm not sure. Make sure you're using the right handle for the field, make sure the field is actually added to the Asset Volume layout that the image is coming from, etc.

**Comment by jacksoncool** [comment]
yes. and yes. note: also the field name is "optimizedImagetransform". 

See the attachments:
 
<img width="379" alt="Screen Shot 2019-05-28 at 1 35 32 PM" src="https://user-images.githubusercontent.com/4122361/58499253-c4755700-814d-11e9-8417-c5321d76dbd1.png">
<img width="442" alt="Screen Shot 2019-05-28 at 1 34 56 PM" src="https://user-images.githubusercontent.com/4122361/58499256-c4755700-814d-11e9-925d-20218f698c27.png">

**Comment by jacksoncool** [comment]
sorry, let me add a new screen shot. 

I've changed the name a couple of times cause, i thought it was the same problem.

**Comment by khalwat** [comment]
Glad you got this working.
