### ISSUE TITLE
Solspace Calendar event time question

### ISSUE THREAD

**Issue by mgburns** [nystudio107/craft-seomatic#417]
We're using SEOmatic to render JSON-LD metadata for Solspace Calendar events (thanks for https://github.com/nystudio107/craft-seomatic/commit/07e1291e7dfe1ef059c613e0586122b38d23d821!).

One thing we've noticed is that the event times appear to be off by four hours, presumedly due to time zone issues. I'm not sure if this is a Solspace issue or an SEOmatic issue, but I thought I'd start here.

For context, we've got the calendar Time Zone set to floating as recommended by Solspace:
http://docs.solspace.com/craft/calendar/v2/setup/faq.html#how-does-calendar-handle-timezones

**Comment by mgburns** [comment]
I submitted a similar issue to the Solspace support team and here’s what they came back with:

```
You'll likely need to switch to using {{event.startDateLocalized|atom}} instead. Long story short, there's an issue where either Craft and/or Calendar is doing something funny that conflicts when trying to use the |date or similar filter (.format works fine for example). :)
```

Is this something I can implement in my templates or does it require updates to this plugin?

**Comment by khalwat** [comment]
So this is something you can definitely update via the SEOmatic Twig API https://github.com/nystudio107/craft-seomatic#twig-templating

But I should probably also switch to that as well.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6dc75b5afc347a377c47d912ba93a54b9341af33
