### ISSUE TITLE
Page hangs and times out if creator (Entity Brand) logo is missing

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#418]
I was seeing bad page hangs and times-outs locally using Valet but I but immediate refresh (cmd+r) the page would load instantly.

If I load another page, the same occurs, if I re-navigate back to a page that worked after a refresh it happens all over again.

After digging around and some help on Discord I found the issue to be a missing image. The missing image was used in the creator (Entity Brand) logo.

This could also extend to other Entity Brand images such as Identity Settings but I have not tested this theory.

**Comment by khalwat** [comment]
To be clear, this only happens to you in local dev, correct?

**Comment by terryupton** [comment]
I have briefly tested this and it does seem to only affect local dev using Valet.
However, my staging and production environment use Apache so it's not a complete test. But I did remove the same asset on production and the page loaded without issue and did not hang.

**Comment by khalwat** [comment]
I've done a bunch of tests with this, and it appears to be just your local dev timing out
