### ISSUE TITLE
Breadcrumbs not rendering in multi site

### ISSUE THREAD

**Issue by skramstad** [nystudio107/craft-seomatic#419]
It's basically the same issue as this https://github.com/nystudio107/craft-seomatic/issues/228 . If I'm not on the default site, seomatic is unable to render pages, only HOME.

Quote from the other issue:
> Problem is that the function seomatic.jsonLd.get('breadcrumbList') only returns a single list item 'home' on every page.

So the default site gives me an array with two (2) items. However the same page in another language gives one (1) instead, and that is home. I have no idea why but maybe you are able to solve it.

Reproduce the problem: Install craft 3, multi site, pages as structure, and create one page for each language and compare the data / array.

Anyway, I'm using this code to solve the issue. https://craftcms.stackexchange.com/a/28471

Thanks.
-------------
Craft Pro 3.1.29
Seomatic 3.2.7

**Comment by khalwat** [comment]
Did you group your multi-sites under the same site group?

Do you have actual localized content on the other sites where the breadcrumbs do not appear?

**Comment by mildlygeeky** [comment]
I'm having the same issue, though without multi-site.

#228 describes the issue well for me — my guess is that SEOmatic isn't considering sites that are not set for their homepage to be below the root when it tries to step through out the routing / segments. In my case, the site lives at https://www.domain.com/us/

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/0ca8a0380c65d330ab3022cf14901a337bf2e1e9

Thx @mildlygeeky !
