### ISSUE TITLE
Can't Disable Robots.txt or Humans.txt

### ISSUE THREAD

**Issue by danpayne88** [nystudio107/craft-seomatic#42]
Going to SEOmatic > Global SEO > Settings > Robots.txt or Humans.Txt, and clicking the lighswitch field appears to disable as expected. However, when I click save, and the page reloads, the lightswitch field shows as enabled again. This happens every time I attempt to disable and then save on robots.txt or humans.txt. 

Screenshot below:

![image](https://user-images.githubusercontent.com/24421677/37987736-e1418f1a-31b3-11e8-95b8-de0b9ef28f5f.png)

**Comment by khalwat** [comment]
Well, this is not good!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/cc4e5bd83e820e38c95a55624416bfaac932a1ce

**Comment by danpayne88** [comment]
Thank you!
