### ISSUE TITLE
404 includes canonical `link` header

### ISSUE THREAD

**Issue by mattstein** [nystudio107/craft-seomatic#424]
My 404 pages [omit canonical URL tags](https://github.com/nystudio107/seomatic/issues/211) in the page markup like I'd hope, but still send a bogus canonical `link` header `foo.com/404`:

```
link: <{seomatic.meta.canonicalUrl}>; rel='canonical'
```

This is true on the 404 template (`/404`) as well as any page at all that results in a 404: 

- `/foo`
- `/bar`
- `/why-confetti-is-appropriate-for-ui`
- etc.

I would expect this header to be dropped along with the meta tag. I tried emptying it out from the template with `{% do seomatic.meta.canonicalUrl(null) %}` and `{% do seomatic.meta.canonicalUrl('') %}`, neither of which had any effect. It looks like the only way to prevent these link headers from appearing is to disable SEOmatic's headers altogether, which seems a bit extreme.

---

- Craft CMS 3.1.30
- SEOmatic 3.2.7

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/1b50afae9fe11eb4ef89877e78c9cd2eb4830b07

If you're able to switch to `dev-develop` to verify on your end, that'd be fantastic.

**Comment by mattstein** [comment]
Confirmed! Updating to `dev-develop` made that `link` header go away. Returning to 3.2.9 brought it back.

**Comment by khalwat** [comment]
Thx @mattstein
