### ISSUE TITLE
Validation error with numeric source names

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#426]
Discovered this having a single with the name "404":

![Screen Shot 2019-06-20 at 9 37 28 AM](https://user-images.githubusercontent.com/18329/59853651-4fa5cf00-933f-11e9-9263-c469dd5db5c6.png)

Saving entry via CLI:
```
$ docker-compose exec app bin/craft resave/entries --elementId=7710
Resaving 1 entry ...
    - Resaving 404 (7710) ... done
Done resaving entry.

2019-06-20 09:37:33 [-][-][-][error][nystudio107\seomatic\services\MetaBundles::updateMetaBundle] Meta bundle failed validation: Array
(
    [sourceName] => Array
        (
            [0] => Source Name must be a string.
        )

)
 type: single id: 14 from siteId: 1
```

**Comment by khalwat** [comment]
Oh fun. It's because I'm using the [AttributeTypecaseBehavior](https://www.yiiframework.com/doc/api/2.0/yii-behaviors-attributetypecastbehavior)

Looks like I'll have to allow for numbers in the validator as well.

**Comment by khalwat** [comment]
Actually, it looks like it doesn't even implement that behavior. So how that field would ever get typecast as a number, I don't know.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6ba339776109b7e91212933496cfbaad0f47592d
