### ISSUE TITLE
Invalid Argument when trying to set page title

### ISSUE THREAD

**Issue by cookie10codes** [nystudio107/craft-seomatic#427]
Hi all,

I made a custom route for my search page in Craft 3. All of my other pages are served by SEOMatic. I've found this URL [https://nystudio107.com/blog/tips-for-using-seomatic-effectively#robust-twig-api](url) about setting the page title for custom routes. But If I do that like this:

`{% extends "_layouts/default" %}

{% set bodyClass = "search" %}

{% set searchQuery = craft.app.request.getParam('q') %}
{% set searchUrl = '/' ~ currentSite.language ~ '/' %}
{% set pageEntries = [] %}
{% set pageInfo = [] %}
{% set limit = 12 %}

{% do seomatic.title.get("title").content("Search") %}

{% if searchQuery %}
    {% set entries = craft.entries()
        .search('commonBody:*' ~ searchQuery ~ '* OR  commonIntroduction:*' ~ searchQuery  ~ '* OR  title:*' ~ searchQuery  ~ '* OR  slug:*' ~ searchQuery)
        .section('projects')
        .section('expertises')
        .section('news')
        .section('jobs')
        .site(currentSite.handle)
        .orderBy('score')
        .limit(limit) %}`

I get the error that I have an invalid argument "Property content doesn't exist"

Is there someone who can help me?

Thanks!
Stefanie

**Comment by khalwat** [comment]
probably the easiest way to do it would be this: 

```
{% do seomatic.meta.title("your title here") %}
```

What we're doing is changing one of the SEOmatic meta variables that is used to set values in various SEOmatic tags.

more here -> https://github.com/nystudio107/craft-seomatic#seomatic-variables

As for your issue, if you wanted to do it that way, you'd do:

```
{% do seomatic.title.get("title").title("Search") %}
```
