### ISSUE TITLE
Double encoded apostrophe

### ISSUE THREAD

**Issue by its-me-mario** [nystudio107/craft-seomatic#429]
I'm seeing double encoded (straight) apostrophe characters in the <title> and <meta> tags, JSON-LD seems okay.

I created a [this test page](https://www.visitstockton.org/test/) to show the outcome.

**Comment by khalwat** [comment]
So on your test page, the title tag looks like this:

```
<title>Testing curly ’ &amp; straight &amp;#039; apostrophes</title>
```

So I'm not sure it's double-encoded, but I will investigate what is going on here.

**Comment by its-me-mario** [comment]
The `&amp;#039;` should be `&#039;` in order for it to display as a single quote.

**Comment by khalwat** [comment]
ahhhhhhhh I see what you're saying. Sorry about that, I get it now.

**Comment by khalwat** [comment]
How is this title being set @its-me-mario ? In other words, is SEOmatic just pulling it from an entry's title? Or are you setting it manually via template or...?

If it is being pulled from an entry's title, are we sure it isn't encoded in the entry already?

**Comment by khalwat** [comment]
As a test, I set an entry's title to the following **Custom Text**:

```
This is someone's "woof" title
```

...this ended up (properly) rendering the following tag:

```
<title>🚧 Craft3 | This is someone&#039;s &quot;woof&quot; title</title>
```

So this appears to be working properly, and not double-encoding. What is different with your setup?

**Comment by its-me-mario** [comment]
In Craft: **Content SEO > Pages > General > SEO Title Source**
I have "Custom Text" selected with this value: `{object.entry.metaTitle ??? object.entry.title}`

In the case of the sample page I setup, it's using the title value (object.entry.title)

**Comment by khalwat** [comment]
That's where the double-encode comes from, then. Try instead:

```twig
{{ (object.entry.metaTitle ??? object.entry.title) | raw }}
```

**Comment by its-me-mario** [comment]
Perfect, that did it. Thanks!
