### ISSUE TITLE
Ability to Globally Disable Sitemap

### ISSUE THREAD

**Issue by danpayne88** [nystudio107/craft-seomatic#43]
In the near term, I'm looking to implement SEOmatic for one specific Helper Function and then gradually incorporate additional functionality into the rest of the site. Basically, I want to use that one function and then have nothing else change from an SEO perspective on the site until I can more fully vet & test the impact. 

To that end, I would love to be able to globally disable the sitemap in the same way that you can the automatic metadata rendering. We have a sitemap in place that functions as needed, but it looks like that sitemap is overwritten by SEOMatic's, and SEOMatic's sitemap continues to overwrite it even when all individual section sitemaps are disabled. 

If it wasn't clear, the use case is implementing SEOMatic into an existing site that is already fairly well set-up from an SEO perspective, as opposed to implementing this at the start of the build.

**Comment by khalwat** [comment]
You're very likely missing out on all of that luscious JSON-LD Structured Data in whatever current SEO setup you have :)

That aside, I agree, there probably should be a way to globally disable sitemaps. I'll have a look at that.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/a12777203e0f16ca48074494d6910fef508f6ab4

![google chromescreensnapz1111](https://user-images.githubusercontent.com/7570798/38032855-98974e8a-326c-11e8-9be2-9e71a629da66.png)

**Comment by danpayne88** [comment]
Awesome - thank you! 

And agreed on JSON-LD - we definitely are missing on that. I just want to make sure that when we roll that out, I've had sufficient time to vet the set-up for that and any other items, and right now I'm on deadline for another project :).
