### ISSUE TITLE
Minor typo - "appended"

### ISSUE THREAD

**Issue by lindseydiloreto** [nystudio107/craft-seomatic#430]
```
/admin/seomatic/site/identity/en
```

<img width="506" alt="Ω 2019-06-25 at 9 35 46 PM" src="https://user-images.githubusercontent.com/5309692/60151378-598d5f00-9791-11e9-91f6-7b9745ca2244.png">

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/29ce587cef03f50cc3d2ad8f07fb38deef97c62b
