### ISSUE TITLE
HTML Validation issue

### ISSUE THREAD

**Issue by solivan** [nystudio107/craft-seomatic#431]
The HTML Validator is not liking the new src attribute numeric value.

`Error: A script element with a src attribute must not have a type attribute whose value is anything other than the empty string, a JavaScript MIME type, or module.

    From line 49, column 1; to line 49, column 126

    </footer>↩<script async src="https://www.googletagmanager.com/gtag/js?id=UA-00000XX-1" type="676869c575b1aded0c71959f-text/javascript"></script>`

**Comment by khalwat** [comment]
The code that SEOmatic uses is based on what Google provides:

https://github.com/snowplow/snowplow/wiki/Integrating-javascript-tags-with-Google-Tag-Manager#12-integrating-the-container-tag-on-your-website

Specifically the code is:
```twig
{% if googleTagManagerId.value is defined and googleTagManagerId.value and not craft.app.request.isLivePreview %}
{{ dataLayerVariableName.value }} = [{% if dataLayer is defined and dataLayer %}{{ dataLayer |json_encode() |raw }}{% endif %}];
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'{{ googleTagManagerUrl.value }}?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','{{ dataLayerVariableName.value }}','{{ googleTagManagerId.value }}');
{% endif %}
```

Which is the same as what Google provides, but with some things set via Twig variables. So I'm pretty sure any website that uses GTM, whether integrated via SEOmatic or otherwise, the validator is going to complain about.

**Comment by solivan** [comment]
Yeah, sorry about that. It seems they made a change on their end and are now including that type attribute. Previously my output on that line was:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-11122233-1"></script>

**Comment by solivan** [comment]
@khalwat I've been reviewing this. Your referenced code is for the Google Tag Manager, not global site tag (gtag.js) which is what I am using. According to Google (https://developers.google.com/analytics/devguides/collection/gtagjs/) the gtag.js tag should be 

`<script async src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"></script>
`

Which is what I was seeing before and whose output validates via the w3c validation tool. However, the new output is adding an invalid type attribute.

`<script async src="https://www.googletagmanager.com/gtag/js?id=UA-00000XX-1" type="676869c575b1aded0c71959f-text/javascript"></script>`

Listen, If google messed it up, that's fine (well not really, but little we can do about it) I just want to make sure its not a regression on your end. Sorry to be a pita, I have OCD when it comes to HTML validation.

**Comment by khalwat** [comment]
Okay my bad, I misread your initial post.

In any event, this is not being added by SEOmatic:

```
type="676869c575b1aded0c71959f-text/javascript"
```

Here's the template SEOmatic uses for gtag:

```twig
{% set gtagProperty = googleAnalyticsId.value ?? googleAdWordsId.value ?? dcFloodlightId.value ?? null %}
{% if gtagProperty %}
<script async src="{{ gtagScriptUrl.value }}?id={{ gtagProperty }}"></script>
{% endif %}
```

https://github.com/nystudio107/craft-seomatic/blob/v3/src/templates/_frontend/scripts/gtagBody.twig

**Comment by solivan** [comment]
No worries. I figured it wasn't on your end. It is what it is. Thank you for looking into it. Have a happy 4th of July!

**Comment by solivan** [comment]
Andrew... I figured out what was happening and of course, it had nothing to do with SEOMatic. Unbeknownst to me, one my admins enabled Cloudflare's "Rocket Loader" feature which was injecting that bit of code into the JS. In reviewing the issue, I added some JS manually and noticed that the same attribute applied to the new script—which led me to check on Cloudflare. My apologies for the wasted time. Just wanted you to know in case you see this come up again support-wise from some Noob Crafter like me.

**Comment by khalwat** [comment]
> On Jun 29, 2019, at 11:47 PM, Ric Solivan <notifications@github.com> wrote:
> 
> Andrew... I figured out what was happening and of course, it had nothing to do with SEOMatic. Unbeknownst to me, one my admins enabled Cloudflare's "Rocket Loader" feature which was injecting that bit of code into the JS. I added some JS manually and noticed that the same attribute applied—which led me to check on Cloudflare. My apologies for the wasted time. Just wanted you to know in case you see this come up again support-wise from some Noob Crafter like me.
> 
> 

Ahhhhh that makes sense :)

I should have noticed that from the attribute set there.

/Andrew
