### ISSUE TITLE
Robots meta tag and sitemaps

### ISSUE THREAD

**Issue by sm9** [nystudio107/craft-seomatic#432]
Is it possible to stop entries that have the robots meta tag set to 'None' or 'No Index' from appearing in the XML sitemaps? I've noticed error messages about this in Google Webmaster Tools saying: 

> Submitted URL marked ‘noindex’

**Comment by khalwat** [comment]
Not automatically, no. But if you use an SEO Settings field you can do it that way.

It's a soft error to have a submitted URL with `None`, but I agree with you this could be better. 

Fixed in https://github.com/nystudio107/craft-seomatic/commit/d2b26b5182f4ef2347ff4a1c0e18b422457bf488
