### ISSUE TITLE
parsedValue when looping through matrix retreives parent pages meta data

### ISSUE THREAD

**Issue by padmedia** [nystudio107/craft-seomatic#433]
I've created an entry field in matrix - When I loop through the related entries, I'm attempting to grab the seoDescription. Rather than grabbing seoDescription of the related entry, its taking the description from the parent entry.

Example Code:

```
{% if block.type == "relatedSolutions" %}

	 {% for solution in block.relatedSolutions.all() %}

	 	{% set description = solution.seo.metaGlobalVars.parsedValue('seoDescription') %}

		{{ description }}

	 {% endfor %}

{% endif %}
```

**Comment by khalwat** [comment]
I'm assuming that `seo` is an SEO Settings field?

What you're attempting to do isn't an intended use-case. What's happening is the `seoDescription` likely has Twig code in it to pull from a field in the the _current_ `entry`.

What are you attempting to accomplish here? If it's just to get the description, I'd recommend pulling that from the actual description field in the entry.
