### ISSUE TITLE
Add required info to invalidateContainerCacheById()

### ISSUE THREAD

**Issue by putyourlightson** [nystudio107/craft-seomatic#437]
The `invalidateContainerCacheById()` method triggers an `InvalidateContainerCachesEvent` event, passing in a `sourceId`, however without an element type, the correct source cannot be determined. Is it a section, category group, etc.?
https://github.com/nystudio107/craft-seomatic/blob/3.2.12/src/services/MetaContainers.php#L654-L673

I'm not sure what the best course of action is, but for me personally it would be helpful if the event data would allow a plugin to retrieve the individual paths to be invalidated as in the `invalidateContainerCacheByPath()` method.
https://github.com/nystudio107/craft-seomatic/blob/3.2.12/src/services/MetaContainers.php#L681-L696

For refernece, here is where I'm trying to make this work in the Blitz plugin:
https://github.com/putyourlightson/craft-blitz/blob/2.1.0/src/drivers/integrations/SeomaticIntegration.php#L38-L46

**Comment by khalwat** [comment]
So given a `sourceId` you can get the meta bundle by doing `Seomatic::$plugin->metaBundles->getMetaBundleBySourceId()`

Then once you have that, you can get the source type by doing `Seomatic::$plugin->seoElements->getSeoElementByMetaBundleType()`

**Comment by putyourlightson** [comment]
It looks like `getMetaBundleBySourceId()`requires more than just a `sourceId`...

```
public function getMetaBundleBySourceId(string $sourceBundleType, int $sourceId, int $sourceSiteId)
```

**Comment by khalwat** [comment]
Alright so I updated the `InvalidateContainerCachesEvent` so that it passes in the `sourceType` if the cache that is being cleared is an entire Section/ProductType/CategoryGroup, etc.

Then you can do:

```php
if ($e->sourceType !== null) {
    // Handle invalidating an entire source
    $metaBundle = Seomatic::$plugin->metaBundles->getMetaBundleBySourceId($e->sourceType, $e->sourceId, $e->siteId);
    $seoElement = Seomatic::$plugin->seoElements->getSeoElementByMetaBundleType($metaBundle->sourceBundleType);
    $query = $seoElement::sitemapElementsQuery($metaBundle);
    ...
} elseif ($e->uri !== null) {
    // Handle invalidating just $e->uri
    ...
} else {
    // Handle invalidating everything
    ...
}
```

You can then execute the `$query` and loop through the results to see the look at the `$element->url` or whatever. It may seem a little convoluted, but it's future-proofed in terms of working with any Element type that has URIs.

This will be in SEOmatic 3.2.14, but you can try it now via `dev-develop`

**Comment by putyourlightson** [comment]
Thanks! I had to tweak the code a bit, here it is for reference:

```
$metaBundle = Seomatic::$plugin->metaBundles->getMetaBundleBySourceId($e->sourceType, $e->sourceId, $e->siteId);
$seoElement = Seomatic::$plugin->seoElements->getSeoElementByMetaBundleType($metaBundle->sourceBundleType);
$query = $seoElement::sitemapElementsQuery($metaBundle);
```
