### ISSUE TITLE
$ENVIRONMENT variable isn't dynamic, requires "saving" the plugin settings page

### ISSUE THREAD

**Issue by Joobs** [nystudio107/craft-seomatic#439]
SEOmatic 3.2.12

I've set SEOmatic to look at the $ENVIRONMENT .env variable, but it requires saving the plugin settings page in order for it to update.

For example if I copy the `staging` database over to `production`, the robots meta tags are all set to none. If I save the plugin settings page, SEOmatic recognises we are now in production and the robot meta tags are set to index.

I was expecting the settings to automatically pick up what was in the .env file.

**Comment by khalwat** [comment]
Could this be a result of things being cached in some way? It definitely should be parsing this directly, without any need for saving the settings.

**Comment by Joobs** [comment]
I don't think it is being cached, I wouldn't know what is caching it. My templates don't have any cache tags, and my setup/config is pretty much what Craft gives you out of the box.

I'm experiencing this on my localhost (default MAMP setup), and on the staging server. They aren't mirrors of each other.

I have some `{% if craft.app.config.general.custom.craftEnv != "production" %}` tags in the templates which do register changes in the `$ENVIRONMENT` .env variable.

**Comment by khalwat** [comment]
So this is where it determines the environment: https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/Environment.php#L67

Basically, it gets the `$env` from your settings, and if we're running Craft 3.1 or later, it parses it as an environment variable. This should convert things like `$ENVIRONMENT` into their text values.

Then to help people who do not set the SEOmatic Environment to an environment variable, it looks at the Craft `ENVIRONMENT` variable, and if it looks like a dev or staging or production variable, it maps it.

**Comment by khalwat** [comment]
In my tests, this seems to be working as expected. Can you give me some more information on what is in your `.env` (obviously exclude anything private) and maybe a screenshot of your SEOmatic Settings?

**Comment by Joobs** [comment]
```
# The environment Craft is currently running in ('dev', 'staging', 'production', etc.)
ENVIRONMENT="dev"
# The secure key Craft will use for hashing and encrypting data
SECURITY_KEY="###"
# The database driver that will be used ('mysql' or 'pgsql')
DB_DRIVER="mysql"
# The database server name or IP address (usually this is 'localhost' or '127.0.0.1')
DB_SERVER="127.0.0.1"
# The database username to connect with
DB_USER="root"
# The database password to connect with
DB_PASSWORD="root"
# The name of the database to select
DB_DATABASE="databasename"
# The database schema that will be used (PostgreSQL only)
DB_SCHEMA="public"
# The prefix that should be added to generated table names (only necessary if multiple things are sharing the same database)
DB_TABLE_PREFIX=""
# The port to connect to the database with. Will default to 5432 for PostgreSQL and 3306 for MySQL.
DB_PORT="3306"
DEFAULT_SITE_URL="http://website.localhost"
BASE_URL="http://website.localhost"
BASE_PATH="/Users/user/Sites/website/web"
BACKUP_COMMAND="/Applications/MAMP/Library/bin/mysqldump -h localhost -u root -proot --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --single-transaction --no-data --result-file=\"{file}\" {database} && /Applications/MAMP/Library/bin/mysqldump -h localhost -u root -proot --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --no-create-info --ignore-table={database}.assetindexdata --ignore-table={database}.assettransformindex --ignore-table={database}.cache --ignore-table={database}.sessions --ignore-table={database}.templatecaches --ignore-table={database}.templatecachecriteria --ignore-table={database}.templatecacheelements {database} >> \"{file}\""
RESTORE_COMMAND="/Applications/MAMP/Library/bin/mysql -h localhost -u root -proot {database} < \"{file}\""
```

![seomatic-settings](https://user-images.githubusercontent.com/458935/61129486-cd7b7700-a4b4-11e9-8a19-b0680646b7fc.jpg)

**Comment by khalwat** [comment]
> I don't think it is being cached, I wouldn't know what is caching it. My templates don't have any cache tags, and my setup/config is pretty much what Craft gives you out of the box.

> I'm experiencing this on my localhost (default MAMP setup), and on the staging server. They aren't mirrors of each other.

SEOmatic has its own caches; you can clear them by clearing the data caches (which is something that I do on every deploy). If you save the plugin settings, it also clears these caches.

Can you try instead of saving the plugin settings, just going to Utilities -> Clear Caches to clear the caches, and see if things then show up as expected?

**Comment by Joobs** [comment]
Yes - clearing the cache has the same effect as saving the plugin setting. e.g. the SEOmatic environment setting is updated with what's in the .env file.

At the moment we don't automatically clear the cache as part of the deployment workflow.

**Comment by khalwat** [comment]
You might want to build a cache clearing step into your deployment process.

In lieu of that, if you do change things in your `.env` file, manually clear the caches.
