### ISSUE TITLE
SEOMatic script templates and Blitz

### ISSUE THREAD

**Issue by john-henry** [nystudio107/craft-seomatic#442]
Hi Andrew,

So while not necessarily an SEOmatic issue, it's one I feel worth asking your advice on.

I'm using SEOmatic and Blitz

Which is fine but the issue comes around any GDPR functionality specifically as a use case.

We are using a GDPR plugin called _GDPR Cookie Consent_ which allows a few configuration options but at it's core, sets a cookie and allows a bit of logic to check what has been set etc.

To integrate this with SEOmatic we have used gtag.js and added the logic straight into the script templates field in the control panel. For example

`{% if ipAnonymization.value or craft.cookieConsent.getConsent('default-marketing') != true %}`

More on that [here](https://github.com/elleracompany/craft-cookie-consent#example-using-seomatic) in their docs.

Now of course with Blitz enabled this is only going to run once .

I had thought a good solution was to use Blitz's [dynamic content ](https://putyourlightson.com/craft-plugins/blitz/docs#/?id=dynamic-content) and putting ``` {% set seomaticTemplatePath = '_includes/meta' %}
{% hook 'seomaticRender' %} ``` into an include but alas both those tag aren't used anymore in Craft 3 version of SEOmatic

Is there anything I'm missing that could escape the rendering of SEOmatic outside of the Blitz equation?

**Comment by khalwat** [comment]
What I'd do is instead of using Twig with CookieConsent, I'd do it via JavaScript.

When you go static cache, most of what you'd do dynamically via Twig, you then move to doing dynamically via JavaScript

Also `{% hook 'seomaticRender' %}` doesn't do anything in the Craft 3 version of SEOmatic -- that's vestigial from the Craft 2.x version of SEOmatic.

**Comment by khalwat** [comment]
If that doesn't help enough lmk!
