### ISSUE TITLE
[FR] Add Setting to disable Social Media Preview

### ISSUE THREAD

**Issue by kmgdevelopment** [nystudio107/craft-seomatic#443]
The new "Social Media Preview" in the live preview area is displaying even though I have "Display Sidebar SEO Preview" turned off in the plugin settings. It should be possible to disable the Social Media Preview.

**Comment by khalwat** [comment]
**Display Sidebar SEO Preview** is specifically referring to the sidebar.

You'd like an additional option for disabling the Craft 3.2 Preview target for **Social Media Preview**?

**Comment by kmgdevelopment** [comment]
Correct.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/5bdf496284f85edecf28ca7a28fd8cfc9421e2ef
