### ISSUE TITLE
Social Media Preview Doesn't Import Template-Level OG Meta

### ISSUE THREAD

**Issue by kmgdevelopment** [nystudio107/craft-seomatic#444]
I have a more complex social media preview setup on one of my sections, so I've used the plugin's template tags to override the plugin's default social media image source.

````
{% if entry.resourcesPreview|length %}
	{% do seomatic.meta.setAttributes({
		'seoImage': entry.resourcesPreview.one.url('ogImgResource'),
		'seoImageWidth': 1200,
		'seoImageHeight': 630
	}) %}
{% elseif entry.resourcesMainImg|length %}
	{% do seomatic.meta.setAttributes({
		'seoImage': entry.resourcesMainImg.one.url('ogImg'),
		'seoImageWidth': 1200,
		'seoImageHeight': 630
	}) %}
{% endif %}
````

However the Social Media Preview doesn't take these template-level overrides into account, so the previews are inaccurate. Ideally SEOMatic would use the OG meta from the template itself to generate the preview, rather than the base plugin settings.

**Comment by khalwat** [comment]
Unfortunately there isn't a way I can think of that this could reasonably be done.

Probably if you wanted consistency here, you'd need to put Twig code into the SEOmatic fields in the CP as per: https://github.com/nystudio107/craft-seomatic#content-seo-control-panel-fields
