### ISSUE TITLE
SEO description complex expression

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#445]
I've got a channel with a redactor field handle of `copy` and a textarea field handle of  `SEOdescription`. What I want to do is set up the SEO description to use the SEO field first and if that is empty go to the redactor copy field.

Following the docs I set the SEO description source to Custom text and placed this in the field:

`{entry.seoDescription ??? entry.copy}`

However if the seo Description field is empty it doesn't use the copy field.

I'm having the same issue with the SEO title using the following:

`{entry.seoTitle ??? entry.alternateTitle ??? entry.title}`

please advise

**Comment by khalwat** [comment]
Have you tried:

```twig
{{ object.entry.seoDescription ??? object.entry.copy }}
```

If that fails, understand that for Rich Text Fields if you just do `entry.someRichText` you're actually getting an `craft\redactor\FieldData` object back. So you probably want something like:

```twig
{{ object.entry.seoDescription.getParsedContent() ??? object.entry.copy }}
```

**Comment by khalwat** [comment]
Related: https://github.com/nystudio107/craft-seomatic/issues/441

**Comment by CreateSean** [comment]
adding `|striptags` after the copy field removed all the html and was the only extra piece needed.

Thank you

`{{ object.entry.seoDescription ??? object.entry.copy|striptags }}`

**Comment by CreateSean** [comment]
Revisiting this as I would the option to have fallbacks for SEO Image source. I want to select an Asset Source and if that is not used then fallback to a different asset.

So primary asset would be the SEO image asset field and if that is empty then use the Book Cover asset field. 

Is this possible? It doesn't seem so from the options in the select.
