### ISSUE TITLE
Source Name and Source Template must be a string

### ISSUE THREAD

**Issue by romainpoirier** [nystudio107/craft-seomatic#446]
I got this kind of error in the `storage/logs/web.log` file:

```
[-][1][-][error][nystudio107\seomatic\services\MetaBundles::updateMetaBundle] Meta bundle failed validation: Array
(
    [sourceName] => Array
        (
            [0] => Source Name must be a string.
        )

    [sourceTemplate] => Array
        (
            [0] => Source Template must be a string.
        )

)
```

Required fields are not empty, and this error also happens after adding `{% do seomatic.config.renderEnabled(false) %}`.

What does that means, and how to fix this?

**Comment by khalwat** [comment]
What version of  SEOmatic are you running? Do you have any sections that have only numeric names?

**Comment by romainpoirier** [comment]
I am using `3.2.16` and yes, one section name is `404` (handle is `error404`).

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/3cb883eccb52455622f9e551ed3486bb2d5d0ca1
