### ISSUE TITLE
New Single page is not showing up in the Content SEO page

### ISSUE THREAD

**Issue by romainpoirier** [nystudio107/craft-seomatic#448]
I have created a new Single page, which is listed in the Content SEO page (`admin/seomatic/content`) in dev environment.

Unfortunately, despite `project.yaml` is up to date on staging and production environments, this page does not show up in the list on these environement.

So I can't update the settings for this one, and got this kind of error generated in the logs : `2019-07-26 12:58:41 [-][1][-][error][nystudio107\seomatic\services\MetaBundles::updateMetaBundle] Meta bundle failed validation: Array`.

How can I do to get this new page in Content SEO page, without deleting / uninstalling anything? For reference, I am using the latest version of the plugin (`3.2.17`) and the section name is `404` (handle is `error404`).

**Comment by khalwat** [comment]
There's nothing more to the log than what is shown here? I'd be expecting a listing of the attribute that failed?

**Comment by khalwat** [comment]
I set up a test environment and verified the fix: https://github.com/nystudio107/craft-seomatic/commit/ca738ae97b99871a82427298b4676d47624ed68a
