### ISSUE TITLE
Channel Entries Share Images Not Loading

### ISSUE THREAD

**Issue by beckbailey** [nystudio107/craft-seomatic#449]
I cannot get my social media sharing image to load for entries of a channel.
See the attached screenshots of my admin setting but no og:image tag loads in the source code.
I tried this several different ways, emptied cache, cleared template caches etc. 

Thanks for your help in advance.
![seomatic-admin](https://user-images.githubusercontent.com/1824287/62165108-b37ec880-b2eb-11e9-8240-a02fd348d914.png)
![seomatic-code](https://user-images.githubusercontent.com/1824287/62165113-b5488c00-b2eb-11e9-80ff-08e567a0546a.png)

Oddly a previous dev on this same install had a similar issue back in 2016. It sounds like it was resolved then. I thought it was worth a mention: https://github.com/nystudio107/seomatic/issues/129

**Comment by khalwat** [comment]
What are your settings in Content SEO for Twitter / Facebook for this section?

**Comment by khalwat** [comment]
@beckbailey ?

**Comment by beckbailey** [comment]
Hi - please keep this open. I'm working on sending some screenshots and details. I should have it for you within a day.

**Comment by beckbailey** [comment]
I think we may be running into problems when the preview doesn't load properly and that's causing confusion. See screenshot_19 for the og tag and the _20 for is showing on the preview in the admin.

What is the difference between setting a share image under the SEO data tab > custom image for a section or editing under the SEO Matic > Content SEO > Section > General settings?  Does one take precedence over the other? 

![Screenshot_19](https://user-images.githubusercontent.com/1824287/62333291-e1514200-b490-11e9-9605-cd218e322e47.png)
![Screenshot_20](https://user-images.githubusercontent.com/1824287/62333292-e1e9d880-b490-11e9-85d9-bc5a8fc685c2.png)

**Comment by khalwat** [comment]
Whatever you have in the SEO Settings field will take precedence over what you have set in Content SEO.

However, you should make sure that your Content SEO settings for Facebook and Twitter are set to "Same as SEO Image" if you plan to override just the SEO image in the SEO Settings field.

**Comment by beckbailey** [comment]
Thanks for the explanation. Do you have any idea why the SEO Preview wouldn't be correct or how we could correct that?

**Comment by khalwat** [comment]
We should probably do a screen share to have a look at your settings and such; it should and does work.

Have you tried my suggestion of looking at the Content SEO settings for Twitter and Facebook for this section for the various image settings? Screenshots would help...

**Comment by beckbailey** [comment]
Here's a PDF with some screenshots/explanations.
Yes I think a screen share may be a good idea. 
[seomatic.pdf](https://github.com/nystudio107/craft-seomatic/files/3479070/seomatic.pdf)

**Comment by khalwat** [comment]
@beckbailey are you on Craft Discord? Can you reach out to me there as `andrew.welch` to set up a good time to do a screen share?

**Comment by beckbailey** [comment]
@khalwat I tried to send you a message on discord but it said: Your message could not be delivered because you don't share a server with the recipient or you disabled direct messages on your shared server, recipient is only accepting direct messages from friends, or you were blocked by the recipient.

**Comment by beckbailey** [comment]
My discord handle is beckbailey if you want to reach out to me instead.

**Comment by beckbailey** [comment]
I set up a server on discord - it's blocking my message to you at the present @khalwat

**Comment by khalwat** [comment]
This ended up being because the seomatic settings were being overridden via Twig on an inherited site.
