### ISSUE TITLE
Support for Commerce 2

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-seomatic#45]
Support for Commerce 2 needs to be added; this will be done after GA release, once Commerce 2 hits beta.

**Comment by pauljohnston** [comment]
Hi Andrew,

Any update on this?

How can I feed product related structured data in on product pages in the meantime? Would I just create my own for those pages and disable it for the product pages, or is there a way to add to the existing ones? I could only see site related ones in the docs.

Thanks

**Comment by khalwat** [comment]
This was implemented in SEOmatic 3.1.0

**Comment by keithmancuso** [comment]
So so good, thanks!
