### ISSUE TITLE
Feature Request - new tracking scripts?

### ISSUE THREAD

**Issue by sam327** [nystudio107/craft-seomatic#450]
I'm adding two tracking scripts to a site - for Houzz and Pinterest - and it'd be nice if these were options in the tracking code sections.

Additionally, there could be an additional empty field/block, called "Additional Scripts", which I could just copy and paste extra tracking code into.

Obviously, I can add them in a template file (and that's what I'm doing right now). But a)
I really like that the tracking scripts get disabled in devMode. And b) consolidating *all* my tracking scripts into the same section would make management a lot easier.

**Comment by khalwat** [comment]
So at some point it probably makes sense to just start using Google Tag Manager. It is possible for you to add your own custom scripts, however, as described here: https://nystudio107.com/blog/tips-for-using-seomatic-effectively#customized-setup
