### ISSUE TITLE
[FR] Make it more obvious what is going on with the ENVIRONMENT variable

### ISSUE THREAD

**Issue by TC72** [nystudio107/craft-seomatic#454]
I'm not sure if this is an SEOMatic or Craft issue but I wanted to raise it here in case it helps anyone else caught in this kind of issue.

In craft there are 2 places to set the debug environment:
in craft/.env as the ENVIRONMENT variable
in craft/config/general.php as devMode

ENVIRONMENT takes priority if it is set to 'live', setting devMode to true does not enable dev mode.
If ENVIRONMENT is set to 'dev' then the devMode setting is used to decide if the site should be in dev mode.

Where SEOMatic is involved is that it uses the ENVIRONMENT value to decide if the robots tag of the site should be set to none. It's handled here:
[https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/globalmeta/TagContainer.php#L60](url)

The code only shows it matching 3 strings, live, staging and local but it has a list of values to match ENVIRONMENT to for each of those cases, so ENVIRONMENT being 'dev' is the same as local.

My site looked as if it wasn't in dev mode because devMode was correctly set to false but SEOMatic was putting this onto the site:
<meta name="robots" content="none">

I found out when my customer rang me to ask why their site had vanished from google search results. I found from the source code that the ENVIRONMENT value needed to be changed to live but doing this made no difference, it turned out this value was cached by Craft. When I cleared the cache SEOMatic started correctly showing robots all.

I'm not sure if this is just down to me using devMode the same way I always did in craft 2 and ENVIRONMENT is now the right way to do this kind of thing, if it is then that value shouldn't be cached.

**Comment by khalwat** [comment]
So this is all a result of SEOmatic _trying_ to do the right thing to help you out.

SEOmatic does a few things to ensure that staging/development sites don't get indexed by Google. I've seen many times where the reverse of your issue happens, and people end up with public websites that Google is indexing, diluting the content.

This can be much harder to disavow and fix than a website that isn't indexed.

So SEOmatic looks at `ENVIRONMENT` and if it looks like it's set to something `dev`-ish, it'll end up proactively disabling indexing as you've seen above.

I'm not sure what the right solution is. Perhaps I shouldn't try protecting people from themselves, but on the balance, I decided it was worse to have a not-ready site indexed, and diluting content than a production site with indexing off if the developer doesn't have the environment set correctly.

**Comment by TC72** [comment]
I agree with what you're doing but in this situation it would have been great if SEOmatic could have shown me why this was happening. I had set the SEOmatic environment to live but had no idea craft settings would override this.
Maybe you could display next to the environment setting what the overall setting will be and what is causing it to override that setting, or show it in the dashboard.

**Comment by khalwat** [comment]
That's a really good idea!

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/839e8fe624262a26dc92b3e20b7b7804a6b37f95

![Screen Shot 2019-08-16 at 10 17 45 AM](https://user-images.githubusercontent.com/7570798/63174389-da3d3e80-c00f-11e9-8371-20b980fbd97b.png)

![Screen Shot 2019-08-16 at 10 18 19 AM](https://user-images.githubusercontent.com/7570798/63174855-cf36de00-c010-11e9-8f4c-08079355f707.png)

**Comment by ccsantos23** [comment]
I have these in my .env:
ENVIRONMENT="production"
SEOMATIC_ENVIRONMENT="live"

But my dashboard shows this:
![image](https://user-images.githubusercontent.com/7131501/63463002-ce8fb480-c421-11e9-8020-7af610e98497.png)

The "overriden" message was confusing, because it is indeed set to "live".
But why would tracking scripts be disabled, and robots set to none?

**Comment by khalwat** [comment]
@ccsantos23 ah looks like I need to parse those environmental variables, thanks. I will address this.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/4b5a077004cfd0f7a70791c87e7ad262f9d39ad6

**Comment by adampatterson** [comment]
I know this is old, but why is the Environment values saved to project schema? 

`project.yaml` is in version control, most deployment processes are going from staging to prod.  

So staging ends up setting SEOmatic on prod to staging, disables `robots.txt`

Then you have to update the admin settings, modifying the `project.yaml`, where the next deployment fails because there are uncommitted changes.

You can use an ENV variable, but it's written as a suggestion. The default settings are setup as a gotcha left for people to experience and figure out. 

Why not leverage Crafts variables like `CRAFT_ENVIRONMENT`?
