### ISSUE TITLE
Exclude or ignore channel index from Dashboard and Content SEO

### ISSUE THREAD

**Issue by bjrnblm** [nystudio107/craft-seomatic#455]
We have a setup sort of like this:

Single:
- Products Page
    - Products Page

Channel:
- Product Detail
    - Product 1
    - Product 2
    - Product 3

The Products Page, Product 1, Product 2 and Product 3 have their correct SEO tags
The Product Detail channel index has no own page and no SEO tags filled.

It keeps on showing as a red "D" on the Dashboard and Content SEO page for Product Detail.

Is it possible to ignore Product Detail index SEO tags and only calculate the score on Product 1, Product 2 and Product 3 SEO tags?

**Comment by khalwat** [comment]
Currently no, it doesn't do that. It's a tough balance to strike between reminding people they need to fix something, and telling SEOmatic that you never plan to update them with valid information.

In the end, I think it's fine to have poor grades for some sections, as long as you're aware of why.

You could always just set up the SEO settings for the Products Page single in SEOmatic, to make that go away as well.
