### ISSUE TITLE
[FR] Write a custom importer for Feed Me

### ISSUE THREAD

**Issue by philbarbato** [nystudio107/craft-seomatic#456]
I'm migrating a couple hundred blog posts that have custom SEO Title and Description data. Feed Me shows just one field for SEO Metadata. Do you know if it's possible to dump some JSON, or XML, or other data format here that will properly map to the SEOMatic fields?

<img width="1372" alt="Screen Shot 2019-08-13 at 3 50 42 PM" src="https://user-images.githubusercontent.com/1010600/62972608-6bc76900-bde2-11e9-9656-a8828aa06bba.png">

**Comment by khalwat** [comment]
This is something that you'd a custom importer for FeedMe.

Or you could import them to a regular old Craft field named appropriately, and set SEOmatic to pull from those fields via the Content SEO settings.

**Comment by chrisrowe** [comment]
@philbarbato Do you have any code you'd be willing to share on this. I have the same requirements. 

@khalwat Apologies I posted in the C2 repo https://github.com/nystudio107/seomatic/issues/386 Still no plans to support this now P&T acquired FeedMe?

**Comment by khalwat** [comment]
It's something I've considered, I'll re-open it as a FR

In general, I don't love the idea because I think custom writing  SEO descriptions, keywords, titles, etc. usually (but not always) isn't a wonderful idea.

But I do recognize the need so... will keep it open as a FR.

**Comment by chrisrowe** [comment]
Bless you.

Totally agree, but clients will be clients.

**Comment by philbarbato** [comment]
@chrisrowe We ended up creating a dedicated Craft field for the SEO description as Andrew suggested.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.0
