### ISSUE TITLE
Feature request: add attributes to <script> element like the GTM container

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#457]
Hi Andrew,

Would be nice to have the possibility to add attributes to the tracking scripts <script> elements that are being injected by SEOmatic.

Like the GTM container and all the other trackings scripts.

With this feature it becomes easier to make JavaScript manipulations to the <script> element.

**Comment by khalwat** [comment]
What exactly is it that you're trying to do?

If you just need to edit what is presented, you can edit the template that SEOmatic uses to render the various tracking scripts yourself. There's an editor built into it.

**Comment by khalwat** [comment]
Will re-open if additional info is added. SEOmatic should have the support built-in that you need.

**Comment by boldenamsterdam** [comment]
Hi @khalwat ,

In our case we would like to see this feature because we are dealing in Europe with the GDPR law.

So there are cookiebot tools that allow you to block GTM, GA etc. containers until the users accept specific privacy settings of the website. This blocking is being done by putting attributes on the script tags.

See step 3 of this tool how it's implemented: [CookieBot](https://www.cookiebot.com/en/help/)

That's a reason why we would like to see this feature 🙂

**Comment by khalwat** [comment]
Isn't this something you can do already in SEOmatic, though? You can edit the full template that is used to include these scripts, adding whatever attributes you need @boldenamsterdam

**Comment by boldenamsterdam** [comment]
Hi @khalwat 

We finally had some time to dive into this, but unfortunately still without result.

In the documentation we can not find a function what makes it possible to set custom attributes to the <script> elements. 

Can you give an example like how we could set the "type" attribute to a script element with the current functions SEOmatic comes with?

We are trying to achieve something like this:

```
<script type="text/plain">
   {{ seomatic.script.get('googleTagManager').templateString }}
</script>
```

Cheers for the help!

**Comment by khalwat** [comment]
@boldenamsterdam you can edit the tracking scripts to do or be whatever you want via SEOmatic -> Tracking Scripts

The Twig code used for them is all there, and editable by you
