### ISSUE TITLE
Feature Request - Google Optimize support

### ISSUE THREAD

**Issue by solivan** [nystudio107/craft-seomatic#458]
Andrew, Google optimize [https://marketingplatform.google.com/about/optimize/](url) is a great optimization tool, natively integrated with Google Analytics, and hopefully, one you can incorporate support for it in the future. It looks like its a minor addition/config change to the Global Site Tag (gtag.js) snippet.

**Comment by khalwat** [comment]
I'm not a fan of using JavaScript to do A/B testing -- but if you want to use it, you can. SEOmatic's template that it uses for gtag is fully editable by you, you can just add this to it:

```
   gtag('config', 'GA_TRACKING_ID', { 'optimize_id': 'OPT_CONTAINER_ID'});
```

...as per: https://support.google.com/optimize/answer/7513085?hl=en

**Comment by solivan** [comment]
Your response got me thinking and after some research last night, I came to realize you are right in regards to A/B testing. Thank you for your feedback.
