### ISSUE TITLE
Broken Seo Image Source image drastically slows site/throws render errors

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/craft-seomatic#459]
We upgraded from 2.x to 3.2.x and experienced major site slowdowns and slow template renders which we finally sorted out were because the Seo Image Source was a broken image. It had been re/moved during upgrades so was no longer available. 

<img width="192" alt="Screen Shot 2019-08-16 at 9 33 12 AM" src="https://user-images.githubusercontent.com/39066452/63171743-3dc46d80-c00a-11e9-842c-7aa2df6b838b.png">

I couldn't figure out in the code where to check to see if the image was a 404, but the app did throw some errors:
<img width="1572" alt="Screen Shot 2019-08-16 at 9 45 01 AM" src="https://user-images.githubusercontent.com/39066452/63171923-8da33480-c00a-11e9-91fa-aea02cabfec4.png">

Ideally, if the image weren't available, I'd expect the plugin to fail gracefully, and/or alert the user on the main SeoMatic plugin page of the problem. I know this isn't normal behavior, but it took us a good while to figure out why the site rendering slowed down on production to > 60s per page. 

I'll help any way I can to fix this problem with you!

**Comment by khalwat** [comment]
Where is this "SEO Image Source" setting that you've taken a screenshot of? (Global SEO, Content SEO, or in a SEO Settings field)?

I actually do try to catch these issues: https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/ImageTransform.php#L106

```php
            // If we're not in local dev, tell it to generate the transform immediately so that
            // urls like `actions/assets/generate-transform` don't get cached
            $generateNow = Seomatic::$environment === EnvironmentHelper::SEOMATIC_DEV_ENV ? null : true;
            try {
                $url = $assets->getAssetUrl($asset, $transform, $generateNow);
            } catch (\Exception $e) {
                $url = $asset->getUrl();
            }
            if ($url === null) {
                $url = '';
            }
```

I'm honestly not sure how/why this doesn't handle the case you mention.

**Comment by gbowne-quickbase** [comment]
@khalwat Thanks for such a fast, thorough response! 

This broken image shows on the Global SEO tab. 
I saw that try/catch when I was looking into the code, and knew immediately you were trying to cover for this exact problem, so I was confused myself. I dove in a bit deeper to see if I could make a PR to cover this case, but had diminishing returns as I got deeper in. 

I'm guessing that since it *was* an asset, craft is still returning a valid asset ID, with a valid asset URL. In the process of moving from C2->C3 that image got clobbered or moved and not cleaned up by the content people setting up C3. 

When we replaced that image with a valid asset the code was screaming fast.

**Comment by gbowne-quickbase** [comment]
I dove into the code in this method a bit, and wondered if a `file_exists($asset->getFilename())` would be enough to determine that the file actually exists, but also wanted to make sure that if the app were deployed onto a server that might not have an `/etc/hosts` record with the external name of the server, it wouldn't error out as it tries to go to the internet to find a local file.

**Comment by khalwat** [comment]
Related issues:

https://github.com/nystudio107/craft-seomatic/issues/418

https://github.com/nystudio107/craft-seomatic/issues/425

https://github.com/nystudio107/craft-seomatic/issues/322

**Comment by khalwat** [comment]
Should be fixed via https://github.com/nystudio107/craft-seomatic/commit/1fac44d312da800b134e267f3bed233ccb543f7c
