### ISSUE TITLE
Randomly empty sitemaps files whereas site has content

### ISSUE THREAD

**Issue by romainpoirier** [nystudio107/craft-seomatic#460]
In my deploy script, I always run `clear-caches/all`. I think that after this, almost all sitemaps are cleared and empty like below (except the main `sitemaps.xml` file) whereas they all have content that has seen tracked by SEOmatic previously:

```
<!--  This sitemap has not been generated yet.  -->
<!--  If you are seeing this in local dev or an  -->
<!--  environment with `devMode` on, caches only  -->
<!--  last for 30 seconds in local dev, so it is  -->
<!--  normal for the sitemap to not be cached.  -->
<urlset> </urlset>
```

_Sometimes_, it seems that these manual steps can help to force the sitemap completion: `admin/seomatic/edit-content/sitemap/section/{sectionName)/{locale}` → `View Section Sitemap` → wait a few seconds → `View Section Sitemap` again.

Why does this happen, and how can I force the the sitemaps to be regenerated automatically again?

_Example for reference: https://www.charleroi.be/sitemap.xml_

**Comment by khalwat** [comment]
So the reason it works this way is that for very large sitemaps, it takes to long to generate them in response to a web request.

So instead, the sitemaps are generated via a queue job. But as you noted, something needs to prime the pump.

If you visit a sitemap that hasn't been cached yet, you'll get the above message, but it also returns a [503 http status code](https://httpstatuses.com/503) with the `retry-after` header set to 60 minutes from now.

This tells bots like GoogleBot when they can come back to retry fetching the sitemap.

If you prefer to create the sitemaps manually, you can use the console command bundled with SEOmatic as part of your deploy process:

```
./craft seomatic/sitemap/generate
```

https://github.com/nystudio107/craft-seomatic#sitemap-generation
