### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by hiasl** [nystudio107/craft-seomatic#462]
1.) The link to Documentation here https://plugins.craftcms.com/seomatic is broken
2.) The broken link (Error 404) has a double navigation :-)

**Comment by khalwat** [comment]
yep, I'm just in the middle of moving/improving things! You can find it here in the interim:

https://github.com/nystudio107/craft-seomatic/blob/v3/README.md

**Comment by khalwat** [comment]
The docs have been restored, and are hopefully more useful now as well!

https://nystudio107.com/plugins/seomatic/documentation
