### ISSUE TITLE
[FR] Have selected site persist when changing level 1 page under plugin

### ISSUE THREAD

**Issue by bqkode** [nystudio107/craft-seomatic#463]
For example;

I have set up two sites `Site A` and `Site B`.
When I then go to any of the SEOmatic pages `Site A` is then selected. Which is fine the first time.

Then, when I'm choosing `Site B`, it's reverting back to `Site A` when navigating to another level 1 page (Dashboard, Global, Content SEO, etc). It's however persisting when navigating on level 2 (General, Twitter, Facebook, etc.).

I'd expect it to persist the same way Entries does. A selected site is selected until another selection is made.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/7038fde5f7955e4c5e46f9bc4b4085aa4ec21c6e
