### ISSUE TITLE
Be able to set robots to None for a site at the global level?

### ISSUE THREAD

**Issue by ccsantos23** [nystudio107/craft-seomatic#464]
We have a site that's not ready yet so I thought setting Robots to None at the Global SEO level should do it.  But when I checked the Content SEO settings, all the Robots were still set to All.  I tried setting one of the sections to Robots None.  But when I checked an entry in that section, the SEOmatic Settings field showed Robots All.
So it looks like there's no "blank" mode for Robots at the levels below Global.  They're not inheriting the parent settings.

**Comment by khalwat** [comment]
SEOmatic does this automatically for you based on the SEOmatic Environment setting: https://nystudio107.com/docs/seomatic/Configuring.html#multi-environment-config-settings

**Comment by ccsantos23** [comment]
Oops, sorry I wasn't clear.  This is regarding multi-site, not multi-environment.  We have several language sites, and the Spanish one isn't ready so I was hoping to set robots to none in Global SEO.  I ended up setting robots with `{% do seomatic.meta.robots("none") %}` for my sites that are in the "disabled" group.
In any case, the Robots settings were not honoring the parent level defaults.  I realize now that the entry level Robots dropdown does have a blank option, but it defaults to "all" instead of blank.  (I had the same problem with the Title on the SEOmatic field; it defaults to entry.title at the entry level instead of blank.)

**Comment by khalwat** [comment]
Can you elaborate @ccsantos23 ? Because both the title and the robots should default to blank:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/fieldmeta/GlobalVars.php

**Comment by ccsantos23** [comment]
@khalwat Let's say I set these for my section:
- SEO Title Source:  From Field -> Title
- Robots:  None - Do not index...

There is an existing entry in the section, and it has Robots: All.
When I created a new entry, it shows:  `SEO Title Source: From Field->Title`, and `Robots: None`.  (Should have been blank to pick up the parent values.)

Then if I changed the SEOmatic `Content Settings` for the section so that it has `Robots: All`, it had no effect on the entry settings.  The recently-created entry still had `Robots: None` instead of picking up the parent setting.

I think the same thing is happening between Global and Content settings.  On the Content settings there is no blank option for the Robots.

**Comment by khalwat** [comment]
Okay so apologies for not getting back to you sooner on this one @ccsantos23 but I now understand what's going on here.

The way it works currently is for new entries, the SEO Settings field defaults to the settings in your Content SEO settings.

After that initial default, you can set the SEO Settings field to whatever you like, and changes to the Content SEO settings will not affect existing entries, only new entries.

This will be resolved once this issue is resolved: https://github.com/nystudio107/craft-seomatic/issues/488
