### ISSUE TITLE
hreflang tag is not getting included in single entry 

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#465]
Hi @khalwat 

A client is having an issue with one specific single entry (two language setup) that does not what to include the `hreflang` tag except the ```rel="alternate" hreflang="x-default"```.

Already trying to force it by putting the following code in the template:

```
  {% set entry = craft.entries.section('careersIndex').siteId(currentSite.id).one() %}
  {% do seomatic.helper.loadMetadataForUri(entry.uri) %}
  {% do seomatic.link.get('alternate').include(true) %}
  {% do seomatic.link.get('og:locale:alternate').include(true) %}
```

But this generates a twig runtime error:

```
Impossible to invoke a method ("include") on a null variable.
```
 
Already emptied cashes, re-saved the sections, disabled/enabled for specific language, enabled/disabled sitemaps.

But also when I check the database it saves the seomatic_metabundle for this entry like this:

**column:** sourceSiteId = 1
**column:** sourceAltSiteSettings
```
{"1":{"id":"45","sectionId":"25","siteId":"1","enabledByDefault":"1","hasUrls":"1","uriFormat":"careers","template":"careers/index","language":"en"},"2":{"id":"46","sectionId":"25","siteId":"2","enabledByDefault":"1","hasUrls":"1","uriFormat":"werken-bij","template":"careers/index","language":"nl"}}
```

**column:** sourceSiteId = 2
**column:** sourceAltSiteSettings
```
{"1":{"id":"45","sectionId":"25","siteId":"1","enabledByDefault":"1","hasUrls":"1","uriFormat":"careers","template":"careers/index","language":"en"},"2":{"id":"46","sectionId":"25","siteId":"2","enabledByDefault":"1","hasUrls":"1","uriFormat":"werken-bij","template":"careers/index","language":"nl"}}
```

Not sure if that's correct. Any idea what I can try?

It only happens with this specific entry, all the other single sections work fine.

**Comment by khalwat** [comment]
If you're getting this:
```
Impossible to invoke a method ("include") on a null variable
```

That means the tag doesn't exist. This is the code that adds it:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L400

If I had to guess, `::getLocalizedUrls()` probably isn't returning an array of URLs. Why for only this entry, I don't know:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L475

**Comment by boldenamsterdam** [comment]
I think the entry is not being saved correctly to the database.
Because the data in the column ```sourceAltSiteSettings``` are for both sites exactly the same.

I will try to make a complete new entry.
I'll give you a status update when I know more.

**Comment by khalwat** [comment]
Thanks @boldenamsterdam !

**Comment by boldenamsterdam** [comment]
Hi @khalwat ,

It's fixed after re-creating the entry, all the expected hreflang tags are injected by seomatic. 
So the previous one must have been corrupt.

You can close this issue, thanks for the help!
