### ISSUE TITLE
[FR] Support for GraphQL in Craft 3.3

### ISSUE THREAD

**Issue by Hyra** [nystudio107/craft-seomatic#466]
Heya,

Does the roadmap include any plans for support of the new native GraphQL implementation in Craft 3.3?

The current implementation only supports the entries scheme, and doesn't translate SEO fields into an array.

**Comment by khalwat** [comment]
There is no documentation at all yet for this, so while it's on my list, it's unlikely to happen until after DotAll 2019

100% I do plan to add support for it tho.

**Comment by Hyra** [comment]
Awesome stuff 🙇

**Comment by Jones-S** [comment]
Now that the conf is over, do you have some estimate when we could expect graphql support?
Unfortunately I have another plugin where I would like to try some new features with graphql support, but I can't move forward and update to craft 3.3 without seomatic graphql support.
No pressure though :), just wanted to ask, so I can plan a version bump in the future.

**Comment by khalwat** [comment]
So I already added native GraphQL support to ImageOptimize -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.2

The plan is to add it next to Retour, and then SEOmatic. I'm going to guess by next week if all goes smoothly, but that's not a promise! :)

**Comment by Jones-S** [comment]
Even if it's not a promise, I am totally happy seeing that it's probably not gonna take months. Thx

**Comment by khalwat** [comment]
If it takes months, it means I have taken up sheep herding

**Comment by Jones-S** [comment]
🐑🐑🐑🐑🐑🐑🐑🐑🐑 😂

**Comment by khalwat** [comment]
Implemented in SEOmatic 3.2.28 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.2.28

**Comment by Hyra** [comment]
Great. Stay awesome!
