### ISSUE TITLE
Selected site is not respected when switching between SEO settings

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#467]
If I'm on **Site A** and switch to **Site B**, then navigate to **Content SEO**, **Site A** is selected.

This makes it so you have to re-select any non primary sites over and over.

**Comment by khalwat** [comment]
dup of https://github.com/nystudio107/craft-seomatic/issues/463

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/7038fde5f7955e4c5e46f9bc4b4085aa4ec21c6e
