### ISSUE TITLE
[FR] Sitemap generation - hide sitemap when entire channel/structure/etc is set to no-follow/no-index.

### ISSUE THREAD

**Issue by sam327** [nystudio107/craft-seomatic#468]
I've set up a big password-protected section on a site for 'internal use only' sort of docs, and I don't want it to be indexed or otherwise show up. I've added a line in the robots to disallow that whole folder.

But I noticed something weird in the sitemap...

In my main sitemap.xml I've got this:

````
<sitemapindex>
<sitemap>
    <loc>
        https://www.mywebsite.com/sitemaps-1-section-MyHiddenDocuments-1-sitemap.xml
    </loc>
    <lastmod>
        2019-09-01T00:00:00-00:00
    </lastmod>
</sitemap>
...
</sitemapindex>
````

And in THAT MyHiddenDocuments sitemap, it's just got this:
````
<urlset>
</urlset>
````

I understand why it breaks up the sitemap into a big sitemapindex - that all makes sense. 

But I would really prefer that in the main sitemap, if the child sitemap is empty, the link for that section wouldn't show up at all. Right now, this tips people off that there are hidden sections. And I'd rather it not do that.

**Comment by khalwat** [comment]
So from looking at the code, if you turn off **Sitemap Enabled** for a given section in SEOmatic -> Content SEO -> settings -> Sitemap then it will not include this sitemap URL.

I assume you're instead indicating that this section shouldn't be enabled via some other method?

**Comment by khalwat** [comment]
If an section has its robots set to `none` or `noindex` in Content SEO, don't add it to the sitemap index: https://github.com/nystudio107/craft-seomatic/commit/f9170b61b1a3df9a379688abaf38b2a7a348d202
