### ISSUE TITLE
Please make it possible to use assets of related entries as seo image

### ISSUE THREAD

**Issue by nilsenpaul** [nystudio107/craft-seomatic#47]
My setup:

- `Workshops` section
- `Workpieces` section
- Workshops has a content relation to/with workpieces.
- I want the workpiece's image as the SEO image for the workshops.

Is this possible? I can't get this to work, even when I use `{entry.workpiece.one.images.one.url}` as a customer URL.

**Comment by nilsenpaul** [comment]
Ok, sorry, I found the way already:

`{{object.entry.workpiece.one.images.one.url}}`

But, this way the image doesn't get transformed. Would it be possible to recognize `{{object.entry.workpiece.one.images.one}}` as an asset, and then using that as a SEO image?

**Comment by khalwat** [comment]
So if you want it transformed, check out the `seomatic.helper.` functions:

https://github.com/nystudio107/craft-seomatic#helper-functions-seomatichelper

...specifically `seomatic.helper.socialTransform`. You'd probably want something like:

```
{{ seomatic.helper.socialTransform(object.entry.workpiece.one.images, "base") }}
```
