### ISSUE TITLE
Sitemap error (first line)

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft-seomatic#470]
We get errors on all sitemaps:
https://talentor.com/sitemaps-1-sitemap.xml

the first line looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
```

and it looks like this is the problem. But no clear how to solve it.
Is it a bug on seomatic side or on our own?

**Comment by khalwat** [comment]
This ended up being an issue on @davidhellmann 's end where he had blank spaces in his `config/general.php`

**Comment by harrymee123** [comment]
@khalwat Is there anything else that can cause this? My `<?xml version="1.0" encoding="UTF-8"?>` doesn't start until line 3, and `config/general.php` looks fine.

**Comment by khalwat** [comment]
Nothing else that is related to SEOmatic that I'm aware of @harrymee123 -- check all of your `config/` files?

**Comment by harrymee123** [comment]
@khalwat Ahh thought I got them all. Turns out I still had empty spaces above the `<?php` tag in `db.php` and `routes.php` files.
