### ISSUE TITLE
Breadcrumb Error for "position" Property

### ISSUE THREAD

**Issue by kmgdevelopment** [nystudio107/craft-seomatic#473]
I just got a Google Search Console error on Friday that said the breadcrumbs on my site were invalid. I ran a page through the Structured Data Testing Tool and got these errors/warnings:

1. The property _position_ is not recognized by Google for an object of type _Thing_.
2. A value for the _position_ field is required.

![gsc-position](https://user-images.githubusercontent.com/1093524/65458171-e92ec200-de01-11e9-92cc-11e14216f672.jpg)

It looks like Google is now requiring the `position` property to exist outside the `item` element within the `itemListElement`. From looking at the [schema.org docs](https://schema.org/itemListElement) I think this is correct syntax.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/9e1a8f9aadb57b7e0163bebde78b98a6db4d1b00
