### ISSUE TITLE
Schema cache - Commerce Variants

### ISSUE THREAD

**Issue by dannylewin** [nystudio107/craft-seomatic#474]
Hi,

I'm manually overriding prices in the schema for products.

But found that if I clear the cache and test a variant using Googles Schema testing tool, then go test the main product, the variant data has been cached for all the variants including the main product.

**Comment by khalwat** [comment]
Will have a look

**Comment by khalwat** [comment]
@dannylewin so if you're manually changing prices via Twig for product schema, and it can be different depending on various parameters, but the URL is still the same... then you'll need to invalidate the container cache:

```twig
{% do seomatic.jsonLd.container().clearCache(true) %}
```
