### ISSUE TITLE
Content SEO: No Data Available

### ISSUE THREAD

**Issue by johnj24** [nystudio107/craft-seomatic#476]
I've got to be missing some so obvious here, but within SEOMatic > Content SEO I'm only getting back "No Data Available".

I have two sections with public URLs and a couple thousand Commerce products with public URLs.

Any idea where I can start to look?

Thank you!

**Comment by khalwat** [comment]
@johnj24 what happens if you uninstall, and then re-install the plugin?

**Comment by johnj24** [comment]
@khalwat brought it down to my local, but didn't seem to change anything. Still showing data not available.

**Comment by khalwat** [comment]
I'm not clear if you tried uninstalling and re-installing the plugin via the CP?

**Comment by johnj24** [comment]
Yeah, sorry, I uninstalled and reinstalled. Nothing changed.

**Comment by khalwat** [comment]
If you view the JavaScript console, are there any errors?

If not, we might need to set up a screen sharing session at some point to have a look at what's going on here.

**Comment by johnj24** [comment]
Great suggestion. Here's the error:

"Failed to load resource: the server responded with a status of 404 (Not Found)"
It's referring to this template: test.local/index.php?page=admin/actions/seomatic/content-seo/meta-bundles&sort=sourceName%7Casc&page=1&per_page=20&siteId=1

**Comment by khalwat** [comment]
So this is very likely going to end up being some kind of local dev configuration error, because that's just a controller action. I'd expect other things to be failing as well.

**Comment by johnj24** [comment]
Vuetable failed to load.

`load-error Error: Request failed with status code 404
    at e.exports (createError.js:15)
    at e.exports (settle.js:18)
    at XMLHttpRequest.f.<computed> (xhr.js:77)
loadFailed @ Vuetable.vue:772`

**Comment by johnj24** [comment]
The same errors are showing on the production site as well.

**Comment by johnj24** [comment]
I tried removing SEOMatic entirely via composer and I get this error: `[RuntimeException]                                                           
  Could not delete /Applications/MAMP/htdocs/site/vendor/nystudio107/craft-s  
  eomatic/.env.example:`

**Comment by johnj24** [comment]
Andrew, I've gone as far as removing the plugin entirely and installing it back. I get the same errors on my local and my production sites. I can send the DB if you need it.

**Comment by khalwat** [comment]
Message me on the Craft Discord at `andrew.welch` and let's set up a time to do a screen sharing?

**Comment by khalwat** [comment]
For anyone reading this, the action URL that SEOmatic was trying to use was:

```
http://example.test:8888/index.php?page=admin/actions/seomatic/content-seo/meta-bundles&sort=sourceName%7Casc&page=1&per_page=20&siteId=1
```

The issue is that the `pathParam` config setting was changed to `page` which is _also_ a URL param that SEOmatic passes in (see `&page=1` above).

That ends up stomping on the path, changing it to be `1` which obviously has no CP trigger or action trigger in it, causing it to throw a 404 error, being unable to find the template.

Changing the `config/general.php` setting to remove the `"pathParam" => "page"` fixes the issue.

**Comment by wfendler** [comment]
Just received a similar error on Craft 3.3.9 with SEOmatic 3.2.28 (trial) on a local Docker installation.

I tried enabling/re-enabling the plugin as well as re-saving each section and I'm still getting "no data available" when viewing the Content SEO page. There is no `pathParam` defined in my general config right now either.

There's a warning in the console `Vuetable.vue:800`: 

```
vuetable: pagination-path "links.pagination" not found. It looks like the data returned from the sever does not have pagination information or you may have set it incorrectly.
You can explicitly suppress this warning by setting pagination-path="".
```

**Comment by khalwat** [comment]
@wfendler do you have any sections that have URLs enabled?

**Comment by wfendler** [comment]
I don't. I should have mentioned the site is in headless mode - sorry!

**Comment by khalwat** [comment]
You can't currently have `headlessMode` enabled to have it work with SEOmatic.

They will be making some changes in 3.4 that should allow headlessMode to work with SEOmatic, but for now, you can't have it on

https://github.com/nystudio107/craft-seomatic/issues/485

https://github.com/craftcms/cms/issues/4520#issuecomment-531040417
