### ISSUE TITLE
Custom `author` JSON-LD

### ISSUE THREAD

**Issue by markhuot** [nystudio107/craft-seomatic#479]
Hi, I'm trying to overwrite the `author` key of my primary entry's JSON-LD from `#identity` to a custom author per-entry. E.g., I have a blog with many blog posts. Each post has a unique author. On the blog post page I want to have `author` return the user data of the author and not the `#identity` of the site.

Am I understanding correctly that this is hardcoded?

https://github.com/nystudio107/craft-seomatic/blob/fe3a6ac63365ebbdd1d89b675fac0e7c23f82072/src/seomatic-config/entrymeta/JsonLdContainer.php#L48

Is there a way to override this somehow?

**Comment by khalwat** [comment]
So the way SEOmatic works is that when a new meta bundle is created, it is created from the presets you linked to above. You can actually customize those presets if you want, as per:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#customized-setup

Then via the CP UI, you can customize some of the settings in each meta bundle for global, content (per section), or entry (via the SEO Settings field).

These settings are then used to create the meta containers for a given route, but they are injected into your templates so you can use the Twig APIs to change them to be anything you like:

https://nystudio107.com/docs/seomatic/Using.html#twig-templating

So you can easily via Twig override or change absolutely anything that SEOmatic does. It's only after Twig has been executed and the page is done rendering that the final meta items are injected into the page.

Some good examples of how you can customize things can be found in these two articles:

[Advanced SEOmatic Tips](https://nystudio107.com/blog/tips-for-using-seomatic-effectively)

[Annotated JSON-LD Structured Data Examples](https://nystudio107.com/blog/annotated-json-ld-structured-data-examples)

The latter especially has a whole bunch of real-world examples and recipes that you can use.
