### ISSUE TITLE
OpenGraph and TwitterCard configs are not being rendered in the head?

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#48]
We configured the general SEO settings together with the OG and Twitter settings, not sure if it's the new way how Seomatic is working, but we expected that these configurations would be rendered in the <head> element?

Is this something you now have to define your self in the head which meta you want to have templated?

We were mostly missing the share image, so we now fixed it by setting the meta image in the layout by templating: 

`<meta property="og:image" name="twitter:image" content="{{ seomatic.meta.parsedValue('seoImage') }}" />`

Or is this a bug?

We are running:
- Craft CMS 3.0.0-RC17.1
- Seomatic 3.0.0-beta.19

**Comment by khalwat** [comment]
No, this is something that should be happening automatically.

**Comment by khalwat** [comment]
Other than setting up the configuration and filling in a Twitter Handle and a Facebook ProfileID or ApplicationID, you shouldn't have to do anything to get the meta tags to render.

https://devmode.fm/ is a website where SEOmatic 3.0.0-beta.19 is running, and if you view the source, you'll see the `og:image` and `twitter:image` tags.

So what I'd suggest doing is running the site in local dev with `devMode` enabled, and then look at the Yii2 debugger. Filter the logs by `seomatic` and you should see a message as to why any particular tag didn't render.

**Comment by khalwat** [comment]
@boldenamsterdam ?

**Comment by boldenamsterdam** [comment]
@khalwat We had Eastern Holidays so we where offline.

Thanks for your reply, your answer explains a lot. 

We didn't specify the 

> Twitter Handle

 and the 

> Facebook ProfileID 

after specifying it's working as we expected in the first place.

But then we have the question, why do you have to specify the Twitter Handle and the FB ProfileID to setup the Twitter Card and the OG specs? It's something we didn't expected.

**Comment by khalwat** [comment]
Twitter requires a Twitter handle for associated Twitter cards. Facebook technically does not require a Profile ID or App ID for OpenGraph, but it's a best practice to have a Facebook account if you're using OpenGraph, for attribution reasons.

**Comment by toddpadwick** [comment]
I have this same issue. My client doesnt have facebook or twitter, but i'd still like the images to show when people share them. So surely I should not need the IDs.

**Comment by khalwat** [comment]
For Twitter, you would, because it's a mandatory property (you must have a Twitter handle for it to be a valid Twitter card). For Facebook... it's not strictly mandatory, but it's a pretty good idea for attribution reasons.

I think that in the long-run, it's likely your client would be best served by creating a Facebook account if they want links on Facebook to display the information of their choosing.

For Twitter, the same applies, except that a Twitter handle is mandatory for Twitter cards to validate... but it is true that Twitter will fall back on OpenGraph tags if no Twitter cards are present.

I'd suggest just putting a random number like `1234` in the Facebook profile ID field. It's not ideal, but it'll do what you want. Ideal would be the client makes a Facebook account. :)

**Comment by toddpadwick** [comment]
Hi 
Thanks for your fast response!
I tried adding a fb id but still didnt work. See attached. Something still seems to be actually preventing any images from being added. see both screen grabs attached.
![screen shot 2018-04-25 at 09 13 00](https://user-images.githubusercontent.com/36191462/39233712-1e805afc-4869-11e8-8c20-231cf405b29b.png)
![screen shot 2018-04-25 at 09 13 14](https://user-images.githubusercontent.com/36191462/39233713-1e96a5aa-4869-11e8-8373-496a371b2e1c.png)

**Comment by XhmikosR** [comment]
I'm also hitting this. I get no `og:image` at all. I will try to add the ID, but IMO this shouldn't happen.
