### ISSUE TITLE
Robots meta tag - is 'all' a valid parameter

### ISSUE THREAD

**Issue by satcreative** [nystudio107/craft-seomatic#480]
I've been informed by my clients SEO management company that `<meta name="robots" content="all">` isn't a valid parameter (based on the [Moz docs](https://moz.com/learn/seo/robots-meta-directives)). They've requested I change it to `<meta name="robots" content="index, follow">` instead. 

I see by selecting 'All...' in Seomatic setting, I should be getting index and follow. 

![Screenshot 2019-10-07 at 11 07 24](https://user-images.githubusercontent.com/12640985/66303518-147dda80-e8f3-11e9-94e4-5ba761399037.png)

Are they correct in thinking `<meta name="robots" content="all">` isn't correct or is `all` the correct syntax and implies `index, follow`?

**Comment by khalwat** [comment]
Your SEO management company is wrong.

https://developers.google.com/search/reference/robots_meta_tag#directives_1

> `all`
> There are no restrictions for indexing or serving. This directive is the default value and has no effect if explicitly listed.

Now it's true that different search engine companies may treat these values differently, but Google accepts it, and most search engines follow Google.

However, let's say they don't, and the search engine doesn't know what `all` means (which I find unlikely but...). The default value that search engines assume is `index, follow`:

> Default values. A web page with index and follow Robots Meta tag values will be indexed and crawled normally, just as it would without the directives:
> `<meta name="robots" content="index, follow">`

If you want an amusing example, go to the pages you were linked to: 

https://moz.com/learn/seo/robots-meta-directives

...and view the source. Lo and behold, you will see:

> `<meta name="robots" content="all">`

Moz uses SEOmatic. But Moz also has not deemed this to be an issue, so...

I'm a little worried that this SEO company is reporting this as an issue; you might consider advising your client to consider their options in finding another such company to assist them.

**Comment by satcreative** [comment]
Thanks for the quick response.
