### ISSUE TITLE
JS error in Craft Commerce CMS

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#482]
Hi @khalwat ,

Receiving the following .js error in my browser console when I visit a product entry in the CMS.

![Screenshot 2019-10-08 at 12 05 38](https://user-images.githubusercontent.com/7466604/66387410-31cea980-e9c4-11e9-9c48-8da3fd7fee78.png)

All the product entries have a SEOmatic Settings field

**Setup:**
Craft CMS: **3.2.9**
Craft Commerce: **2.1.11**
SEOmatic: **3.2.9 and >**

**Comment by khalwat** [comment]
This error should not affect anything functionality-wise, but I will track it down.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/7dfb48b9332d6cee0c756799860ad8d3c6875a53
