### ISSUE TITLE
[FR] Add GraftQL piggy backing with Craft CMS 3.4

### ISSUE THREAD

**Issue by webvader** [nystudio107/craft-seomatic#483]
I'm a little confused how the piggy backing works and we do not get results we are excepecting. If we test the following query in CraftQL:

```
{
    entry(section: homepage) {
    id
    title
    ... on Homepage {
      seomatic {
        metaTitleContainer
        metaTagContainer
        metaLinkContainer
        metaScriptContainer
        metaJsonLdContainer
      }
    }
  }
}
```

Everything works as expected.
But if we translate this query to the native GraphQL plugin, like this:

```
{
  entries(section: homepage) {
    id
    title
    ... on homepage_homepage_Entry {
      seomatic {
        metaTitleContainer
        metaTagContainer
        metaLinkContainer
        metaScriptContainer
        metaJsonLdContainer
      }
    }
  }
}
```

The SeomaticInterface is not found. I suppose the native GraphQL is not picking up the SeomaticInterface? We also tried using the fieldName (seoContainer) but GraphQL expects a string but we  get the following error: Expected a value of type String but received: instance of nystudio107\\seomatic\\models\\MetaBundle. The query looks like this:

```
{
  entries(section: homepage) {
    id
    title
    ... on homepage_homepage_Entry {
       seoContainer
    }
  }
}
```

Any help is appreciated.

**Comment by khalwat** [comment]
The "piggybacking" can't work until this happens: https://github.com/craftcms/cms/issues/5056

So for now, you'll need to have separate queries.

**Comment by khalwat** [comment]
Actually going to keep this open as a FR as a reminder for Craft 3.4

**Comment by wfendler** [comment]
The notes in the docs that mention piggybacking are only relevant when using CraftQL until Craft 3.4 is released, is that correct? Is there any way around this limitation right now or does piggy backing simply not work? (If so, I'd suggest removing/editing that part of the docs for anyone else who might encounter this! 🙏)

**Comment by khalwat** [comment]
It simply does not work until support is added in Craft core, and I add additional code to support _that_.

This wasn't known at the time that the docs were updated, because what I had "just worked" with the CraftQL plugin, so there was some expectation that it would "just work" with the native GraphQL as well.

I will edit the docs.

**Comment by wfendler** [comment]
Totally makes sense!

Using Gatsby's pages I can't pass the URI that I get from one GraphQL query into another query for the SEO data. So, I think we'll have to turn those into programmatically created pages to pass the URI as context. That change shouldn't be too difficult and there may be other benefits to this change though. I'll keep an eye out for that 3.4 update in case we still need this. Thanks 🙏

**Comment by abdusco** [comment]
Any updates on this, now that 3.4 is released?

**Comment by khalwat** [comment]
Not yet, no @abdusco 

Although Craft 3.4 has been recently released, the aforementioned documentation on how all of this works has still not been published

**Comment by roelvanhintum** [comment]
@khalwat is this what you are looking for?
https://github.com/craftcms/cms/blob/develop/src/gql/TypeManager.php#L27

**Comment by khalwat** [comment]
Right, so that documents the events, but not the broader concepts. I'm hoping I don't have to reverse engineer it, and GraphQL documentation will be forthcoming.

But if it doesn't arrive soon-ish, I guess I'll have to.

**Comment by joshuabaker** [comment]
@brandonkelly Are we able to get an example approach to @khalwat to unblock this or, better yet, that documentation he’s seeking? There seems to be quite a few of us waiting on this now. 😊

**Comment by khalwat** [comment]
@joshuabaker There is a work-around currently too, which is just that you use an additional GraphQL query to obtain the SEO information.

Usually this exact GraphQL query isn't an issue, if you're using it with a static site generator or a caching layer.

There is probably enough in the HEREDOC comment to allow me to figure it all out, I was just hoping for more. But I will see if I can start taking a look at it soon-ish.

**Comment by maikueo** [comment]
I looked at the comment in the link posted by @roelvanhintum and added this to my SiteModule:

```
// Modifications to GraphQL fields
Event::on(TypeManager::class, TypeManager::EVENT_DEFINE_GQL_TYPE_FIELDS, function (DefineGqlTypeFieldsEvent $event) {
            if ($event->typeName == 'EntryInterface') {
               // Make Seomatic tags available to all entries.
                $event->fields['seoTags'] = [
                    'name' => 'seoTags',
                    'type' => SeomaticInterface::getType(),
                    'args' => SeomaticArguments::getArguments(),
                    'resolve' => SeomaticResolver::class . '::resolve',
                    'description' => 'This query is used to query for SEOmatic meta data.'
                ];
            }
        });
```

I'm new to Craft, so this might not be totally correct or even a good way to do it...
It exposes an "seoTags" field on all Entries. You can still use the Seomatic params (like "asArray"), you just don't need to pass in a "uri".


GraphQL:
```
    seoTags(asArray: true) {
      title: metaTitleContainer
      meta: metaTagContainer
      link: metaLinkContainer
      json: metaJsonLdContainer
    }
```

You might also need to add a few imports at the top of your SiteModule

```
use craft\events\DefineGqlTypeFieldsEvent;
use GraphQL\Type\Definition\Type;
use craft\gql\TypeManager;

use nystudio107\seomatic\gql\arguments\SeomaticArguments;
use nystudio107\seomatic\gql\interfaces\SeomaticInterface;
use nystudio107\seomatic\gql\resolvers\SeomaticResolver;
```

Making an extra request was just going to complicate things for us, so maybe this is useful to somebody else in the meantime. :blush:

**Comment by khalwat** [comment]
@maikueo this is fantastic, thank you! I will roll this into SEOmatic 3.3.6!

**Comment by joshuabaker** [comment]
@maikueo Oof. Skills. 💯

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/b58e60ca94b159b160a20f9b014d19dc7b27c0bb

You can set your semver to `dev-develop` and then do `composer update` to give it a whirl now.

**Comment by maikueo** [comment]
@khalwat wow, so fast!! Thanks so much!
