### ISSUE TITLE
Canonical output assumes URL should be lower-cased

### ISSUE THREAD

**Issue by russback** [nystudio107/craft-seomatic#486]
We have our site languages set as `en-GB`, `en-CA`, `fr-CA`, etc, and have found that the output of this is lower-cased to `en-gb` etc via the `prepForRender()` method of the `CanonicalLink` class that  meta links are parsed through. 

I appreciate we could disable auto render but it seems a shame to have to do that to avoid this.

I'm not sure why lowercasing meta links should be a feature, or at least the practice of lowercasing the href?

**Comment by khalwat** [comment]
So lower-casing the entire URI is a feature in that it normalizes case to ensure that whatever the case that ends up getting entered, the canonical URL is always lowercase.

For similar reasons, you'll note that every slug/URL coming from Craft will be converted to all lowercase as well.

I think you might consider changing your site to use all lowercase, but barring that, if you want a flag or such, I can add it. Let me know.

**Comment by russback** [comment]
We're not able to revert to lowercase as the site integrates with another application that has the same URL convention, and it is a valid lang string.

It took me a while to track it down as the `canonicalUrl()` methods don't behave in the same way - it appears limited to the auto render output.

At the moment we've had to make a change to the vendor source, so would be very grateful if you could add a config flag for it.

Thanks Andrew.

**Comment by khalwat** [comment]
I agree it's valid, I'm just mentioning that there are other reasons for also making the change site-wide. Maybe something for a later date!

You're correct that it isn't done until render time:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/metalink/CanonicalLink.php#L74

I'll put in a config setting or such for you.

**Comment by russback** [comment]
Thanks, Andrew.

Do you know when that will be available?

**Comment by khalwat** [comment]
Added a setting in: https://github.com/nystudio107/craft-seomatic/commit/dd25bd90a48f7a1672a029c9b6f0fef91c76f163

I'll likely release this early next week, but you can start using it now if you set the semVer to: `dev-develop`
