### ISSUE TITLE
Structured JSON-LD is being output on a 404 page

### ISSUE THREAD

**Issue by darylknight** [nystudio107/craft-seomatic#489]
We've got a site listing job vacancies and outputting all the normal stuff through SEOmatic. The client has just flagged that if someone visits the vacancy page if it's disabled (or expired), the structured data related to that page is still being put on the page. They're concerned about data leaking.

![image](https://user-images.githubusercontent.com/1250017/67196190-ffc93880-f402-11e9-9168-ee032bae492d.png)

Can/should we be preventing this? And how can we achieve it?

**Comment by khalwat** [comment]
You can prevent that (though I don't see this as a problem, as Google will not index a page with a 404 result code) by doing:

```twig
{% do seomatic.jsonLd.container().include(false) %}
```

**Comment by binarymonkey84** [comment]
> You can prevent that (though I don't see this as a problem, as Google will not index a page with a 404 result code) by doing:
> 
> ```
> {% do seomatic.jsonLd.container().include(false) %}
> ```

I think this _is_ a problem despite Google not indexing it, as entry data may be confidential. Leaking the data out anywhere in the server response shouldn't happen if the entry is disabled.

**Comment by khalwat** [comment]
I agree @binarymonkey84 -- added that in https://github.com/nystudio107/craft-seomatic/commit/34d293ab80cb2fbc46dd1965de6ea0d494baf5dd

**Comment by darylknight** [comment]
Thanks Andrew. Do we need to do anything after updating or will it just work?

**Comment by khalwat** [comment]
You don't need to do anything other than ensure that your data caches are cleared on deploy.
