### ISSUE TITLE
Invalid Image Content Type

### ISSUE THREAD

**Issue by welford-media-ops** [nystudio107/craft-seomatic#492]
Hi

We are running version 3.1.38 and are having issues with SEO images on Facebook. Facebook debug reports the image as having an invalid image content type, however the preview within our sites admin area is displayed correctly.

![image (10)](https://user-images.githubusercontent.com/56311170/67274485-7116f300-f4b8-11e9-96c7-18fe8e21a5c0.png)

Visiting the URLs in the screenshot work correctly, the only thing I can think of is that the whitespaces within the link are causing the issue. The plugin is configured with Automatic Render enabled so I would have assumed that these URLs would have been escaped during render, but it appears as though they are not.

Please can you advise?

**Comment by khalwat** [comment]
This is very likely going to be some kind of an issue with your server setup, and not SEOmatic. The content type is something that your server should be sending along in the response header.

Here's an example live site that uses SEOmatic: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fnystudio107.com%2F

**Comment by welford-media-ops** [comment]
Hi, thanks for the response, however after upgrading to the latest version it would appear that URLs are now being escaped correctly. It seems something has changed since 3.1.38 which now replaces whitespaces with the correct URL encoding.

Thank you for taking the time to respond.
