### ISSUE TITLE
Missing model type

### ISSUE THREAD

**Issue by PixelGarden** [nystudio107/craft-seomatic#493]
Following error is thrown:

`Class 'nystudio107\seomatic\models\jsonld\JsonLdType' not found in /home/xxxx/craft/vendor/nystudio107/craft-seomatic/src/models/jsonld/DataType.php:24`

Which is caused by JsonLdType missing in models/jsonId folder:

```
use nystudio107\seomatic\models\jsonld\JsonLdType;
```

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/48c73b77e656d9625af8fc46c7106d2d1774acf6
