### ISSUE TITLE
Can't save custom SEO image when using search

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#494]
I think I found a bug. 🤷‍♂️

On Content SEO > SEO Image Source, when I select a custom image (for any section), if I use the search to find my image, and save, it didn't save nothing. But, if I just scroll to find my image and save, it saves correctly.

Using search seems to broke SEOmatic saving 😅

**Comment by khalwat** [comment]
I was unable to reproduce this.

I'm guessing that if this is an issue, it's likely an issue with Craft.

SEOmatic just uses standard Craft UX for an Assets field, the picker (including the Search) all comes from Craft.
