### ISSUE TITLE
Invalid sitemap on some validators due to whitespace and newlines

### ISSUE THREAD

**Issue by ThinkGraphical** [nystudio107/craft-seomatic#495]
We noticed [Woorank](https://woorank.com/) hinting that our SEOmatic generated sitemap was invalid.

We tried a couple of online sitemap validators, some had no issues with it, some had.

After contacting Woorank support we got following answer:

-------------------

Your site's sitemap index contains whitespace and newlines in the values for lastmod and loc [URL]/sitemaps-1-sitemap.xml
```
    <loc>
      [URL]/sitemaps-1-section-aboutSingle-1-sitemap.xml
    </loc>
    <lastmod>
      2019-06-25T15:40:18+02:00
    </lastmod>
```
should become
```
    <loc>[URL]sitemaps-1-section-aboutSingle-1-sitemap.xml</loc>
    <lastmod>2019-06-25T15:40:18+02:00</lastmod>
```
as shown on the xml example on https://support.google.com/webmasters/answer/183668?hl=en

-------------------

Although Google Search Console has no problem with this,
can we please fix this just for the sake of completeness!?

**Comment by ThinkGraphical** [comment]
Never mind, seems to be fixed in the latest version.
By removing the `\r\n` from `implode("\r\n", $lines)`

Thanks!

**Comment by khalwat** [comment]
WooRank is wrong, the sitemaps were valid -- but yes, I've minimized the sitemaps anyway :)

**Comment by khalwat** [comment]
Ironically the example XML they link to in the Google doc has spaces and linefeeds in it :)
