### ISSUE TITLE
Easy fix for crop-position/focalpoint problem in social transforms in combination with e.g. image optimizers

### ISSUE THREAD

**Issue by Tim-Wils** [nystudio107/craft-seomatic#497]
Hi Andrew,
I can make this real short :)
I'm working with https://github.com/aelvan/Imager-Craft with the option "'useForNativeTransforms' => true". When I have set a focal point there it's ignored. This is because it's always return the default center-center position in src/helpers/ImageTransform.php.

If you add this 1 line to the 'base' in static private $transforms, it's all solved:
'position' => null

Screenshot for the fix:
![afbeelding](https://user-images.githubusercontent.com/90032/67942000-1b88c780-fbd7-11e9-950e-4d9941537362.png)

Grts,
Tim

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/e74a0a4ab90a6d090e2ce3493f71a09458fbb8ec

**Comment by Tim-Wils** [comment]
Hi Andrew,
There's single-quotes around the null in your fix, the quotes shouldn't be there :)
'position' => 'null', should be:
'position' => null,

Tim

**Comment by khalwat** [comment]
Ooops! Fixed in https://github.com/nystudio107/craft-seomatic/releases/tag/3.2.31

**Comment by khalwat** [comment]
I had to roll this back, as it was causing inexplicable slowdowns in the CP and frontend:

https://github.com/nystudio107/craft-seomatic/releases/tag/3.2.32
