### ISSUE TITLE
Same as SEO Image setting not respected when using twig in custom url

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#498]
Craft 3.3.14
SEOmatic 3.2.29

When using Content SEO settings for a channel I want the SEO image to pull from a SEO Image field and if that is empty then use the image in the Book Cover field.

However the only way this works is if you place the twig code in SEO Image custom URL setting on the general tab, then copy to the facebook tab, and copy again to the twitter tab.  Using the **same as SEO image** option causes nothing to work. 

When I place the following code in all 3 locations it works as expected.

```{{ object.entry.seoImage.one().url ??? object.entry.bookCover.one().url }}```

![general-tab](https://user-images.githubusercontent.com/6899490/68027730-809cf580-fc89-11e9-87d1-799ef662a44b.jpg)
![twitter-tab](https://user-images.githubusercontent.com/6899490/68027731-809cf580-fc89-11e9-8c61-e34b06ba9bfb.jpg)

**Comment by khalwat** [comment]
I attempted to reproduce this locally, but cannot:

![Screen Shot 2019-11-01 at 9 21 42 AM](https://user-images.githubusercontent.com/7570798/68027829-c3f76400-fc89-11e9-9d97-1463cf097f62.png)

![Screen Shot 2019-11-01 at 9 22 27 AM](https://user-images.githubusercontent.com/7570798/68027837-cbb70880-fc89-11e9-9741-ce32f3080c3e.png)

**Comment by darylknight** [comment]
I just came to report the same thing. Here's some screenshots to demonstrate for https://qeprize.org/news/17-year-old-create-the-trophy-competition-winner-attends-qeprize-award-ceremony-at-buckingham-palace.

General Settings:
![image](https://user-images.githubusercontent.com/1250017/70441750-a5149a80-1a9d-11ea-9483-0a8354eec61f.png)

For that article, SEOmatic is showing the correct image in the social preview sidebar:

![image](https://user-images.githubusercontent.com/1250017/70441963-05a3d780-1a9e-11ea-9ede-208b8bf1cc71.png)


![image](https://user-images.githubusercontent.com/1250017/70441785-b78ed400-1a9d-11ea-81a5-f88ca91b5792.png)

But on the social tab for that channel in SEOmatic, it's using the global fallback:

![image](https://user-images.githubusercontent.com/1250017/70442007-1b190180-1a9e-11ea-80de-be1d7a190e29.png)

```
<meta content="17-year-old Create the Trophy competition winner attends QEPrize award ceremony at Buckingham Palace" property="og:title">
<meta content="The Queen Elizabeth Prize for Engineering is a global £1 million prize that celebrates a ground-breaking innovation in engineering." property="og:description">
<meta content="https://qeprize.org/uploads/images/_1200x630_crop_center-center_82_none/QEP_Placeholder_Images_72dpi_6.jpg?mtime=1573486196" property="og:image">
<meta content="1200" property="og:image:width">
<meta content="630" property="og:image:height">
```

On the frontend, it's using that purple fallback image, even though it should be using the one in the sidebar on the entry's social preview.

**Comment by khalwat** [comment]
...and what are the image settings for the SEO Image for Twitter @darylknight ?

**Comment by darylknight** [comment]
Sorry, missed the important bit. That's why I think it's not working correctly; it's meant to be the same as the SEO Image, but it's using the global settings instead:

![image](https://user-images.githubusercontent.com/1250017/70459128-33981480-1abc-11ea-940a-a063ee816967.png)

**Comment by darylknight** [comment]
Anything else I can do to help diagnose this?

**Comment by khalwat** [comment]
> On Dec 16, 2019, at 4:07 AM, Daryl Knight <notifications@github.com> wrote:
> 
> Anything else I can do to help diagnose this?
> 
> 

Message me on Discord, we’ll need to set up a screen share.

**Comment by darylknight** [comment]
Chatted with Andrew and it turns out my issue was because the General settings were outputting a URL:

`{ object.entry.seoImage[0].url ??? object.entry.articleCoverImage[0].url }`

Twitter and Facebook were set to "Same as SEO Image" which expects an object to apply the social transform. When Twitter then tried to apply a transform to the URL, it doesn't work.

The fix for me was to just use the same code as general settings in Twitter and Facebook.

**Comment by khalwat** [comment]
If put something like this in the SEO Image field: 

```twig
{{ "" ??? "https://nystudio107-ems2qegf7x6qiqq.netdna-ssl.com/img/blog/_1200x675_crop_center-center_82_line/human-tower-base.jpg" }}
```

I can leave Twitter + Facebook on "Same as SEO Image" and it just works fine. But if I use: 
```twig
{ "" ??? "https://nystudio107-ems2qegf7x6qiqq.netdna-ssl.com/img/blog/_1200x675_crop_center-center_82_line/human-tower-base.jpg" }
```

 then it fails. So I think that something changed in how these string template syntax stuff is parsed
and/or something is wrong with the empty coalescing operator, maybe only in conjunction with the above (?)

So try using `{{ }}` instead of single `{ }` syntax and see if it doesn't just work for you

**Comment by terryupton** [comment]
I have also just come across this and https://github.com/nystudio107/craft-seomatic/issues/498#issuecomment-571947595 has also solved the issue for me. 
Is it worth adding to the docs @khalwat or making this the default behaviour? 
It's a little confusing initially.

A secondary point, should we be setting the crops/transforms ourselves when setting a custom image url? As it seems to use the original image and not pass it through the SEOmatic transform settings.

In my instance I am taking the first image from a superTable field like so:
` {{ object.entry.imageCredits.one.image[0].url }}`
