### ISSUE TITLE
[Question] Sitemap splitting

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft-seomatic#5]
Just a question cause we run into a problem as we build our Craft 2 Sitemap Plugin with Images.
On https://bestwebsite.gallery I've round about 2500 entries and every entry has 1 - XX (sometimes up to 20) Images. 

For our Plugin can't handle the amount of data and the sitemap creation failed every time. We give up the development cause C3 and your Announcement that you include Sitemaps in Seomatic.

Our thougts was to split the sitemap in smaller pieces.

Maybe you handle all the stuff in another way.
Maybe it's a good hint.

Cheers

**Comment by khalwat** [comment]
So yes, the sitemap built into SEOmatic automatically splits things up into separate sitemaps, with one sitemap per Section/Category.

https://twitter.com/nystudio107/status/957794188938174464

It also allows you to choose a limit of how many entries should be in each sitemap. Given that Google has a crawl budget, and only has so much time to index your site, something SEO people are experimenting with is putting only the XXX most recent entries into the sitemap.

So when Google looks at the sitemap, it has a smaller list of things to digest. Older pages are most likely in the index anyway, so it's a way to urge Google to index your new hotness quicker.

**Comment by davidhellmann** [comment]
Good point!
