### ISSUE TITLE
Markdown in titles

### ISSUE THREAD

**Issue by andrewfairlie** [nystudio107/craft-seomatic#500]
Hi @khalwat 

Bit of a weird one this, and it's one that I can definitely work-around away from SEOMatic by having a separate title field.

I have a request from a client to be able to add basic formatting to article titles (certain words bold etc.) and so I figure allowing them to do so in the title field and then rendering that as markdown is a way to do it, but the Meta title outputs with the markdown syntax.

![image](https://user-images.githubusercontent.com/1772888/68110475-ff419f00-fee4-11e9-8c81-89cb43c14d4b.png)

Is there a way that we can make SEOMatic strip out markdown syntax for meta titles?

Cheers!

Edit: also, 500th issue 🎉

**Comment by khalwat** [comment]
Yeah sure, so all of the fields in SEOmatic are parsed as Twig, so you can do something like set the title to:

```twig
{{ object.entry.title | md }}
```

...in the SEO Title field in Content SEO or via Twig template or however you want to do it.
