### ISSUE TITLE
Cannot use 'False' as class name as it is reserved

### ISSUE THREAD

**Issue by jasonmccallister** [nystudio107/craft-seomatic#501]
I installed the Webhooks plugin and whenever I visit the "create a new webhook" page I get the following error:

```
Cannot use 'False' as class name as it is reserved in /var/www/html/vendor/nystudio107/craft-seomatic/src/models/jsonld/False.php:24
```

It appears as "An unknown error occurred" error session when trying to create a new webhook.

**Comment by khalwat** [comment]
errrr... aren't these things namespaced tho?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/45fd2c03b90a359b5355131e1f805fa857a7d8b2

If you want to test it out now, you can set your semver to:

```
        "nystudio107/craft-seomatic": "dev-develop as 3.2.21",
```

Reserved class names in PHP 7 -> https://www.php.net/manual/en/reserved.other-reserved-words.php

**Comment by howells** [comment]
@khalwat  I have this exact issue using Craft 3.7.63.1, Seomatic 3.4.48, and Webhooks 2.4.1. Any idea how I can rectify? (Shall I open up a new issue?)

Error as it appears in the logs:

```
2023-01-24 09:22:54 - error - yii\base\ErrorException:64
yii\base\ErrorException: Cannot use 'False' as class name as it is reserved in /srv/app/delve/htdocs/vendor/nystudio107/craft-seomatic/src/models/jsonld/False.php:24
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
```
