### ISSUE TITLE
[FR] Add Tracking Scripts for Mixpanel, HotJar, Custom Scripts

### ISSUE THREAD

**Issue by ileider** [nystudio107/craft-seomatic#502]
It would be great to be able to add more Tracking Scripts (ie. Google Analytics, Facebook Pixel, etc) for other popular services. And eventually arbitrary Custom Scripts. Thanks!

**Comment by khalwat** [comment]
Google Analytics & Facebook Pixel are already supported. Much beyond that, and it might make sense to use Google Tag Manager (which is already supported too) to manage the marketing scripts you're injecting.
