### ISSUE TITLE
Caching and GDPR

### ISSUE THREAD

**Issue by mattfordham** [nystudio107/craft-seomatic#503]
Hi there. I am using the code below within a site's main layout template to exclude the scripts for folks who have not accepted the GDPR terms. This works, however the results appear to be cached by SEOmatic. After accepting GDPR terms (and setting the cookie), the "SEOmatic metadata caches" need to be cleared in order to have the scripts loaded. Perhaps I am misunderstanding the way `do seomatic.script.get` tags are intended to be used?

```
{% if craft.cookies.get('gdprAccepted') != 'true' %}
    {% do seomatic.script.get("googleAnalytics").include(false) %}
    {% do seomatic.script.get("gtag").include(false) %}
    {% do seomatic.script.get("facebookPixel").include(false) %}
    {% do seomatic.script.get("googleTagManager").include(false) %}
    {% do seomatic.script.get("hubSpot").include(false) %}
    {% do seomatic.script.get("linkedInInsight").include(false) %}
 {% endif %}
```
Thank you!

**Comment by khalwat** [comment]
So I think you can simplify it a bit and just don't include the entire script container if they don't consent:

```twig
{% if craft.cookies.get('gdprAccepted') != 'true' %}
    {% do seomatic.script.container().include(false) %}
{% endif %}
```

And then since you're modifying this via Twig on a per-page basis, you will need to bust the cache as per [SEOmatic Caching and Cache Busting](https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting)

```twig
{% if craft.cookies.get('gdprAccepted') != 'true' %}
    {% do seomatic.script.container().include(false) %}
    {% do seomatic.script.container().clearCache(true) %}
{% endif %}
```

**Comment by mattfordham** [comment]
Perfect, thank you!
