### ISSUE TITLE
Breadcrumb error at Search Console

### ISSUE THREAD

**Issue by DavidKabelitz** [nystudio107/craft-seomatic#504]
Hi, first of all awesome plugin and we love it a lot.

Some issues are on our list and i am not sure how to solve it. The schema.org model for the breadcrumbs that are generated does not have the position field set. That causes some errors at the google search console. 

This error appears just on subpages. All root pages do have position set to 1. In out case we have a single page and a channel. The channel pages are subs of the single.

Url Structure looks like this:
/single-ov and a channel set with this url setup
/single-ov/channel-items

In this case both positions are not set.

**Comment by khalwat** [comment]
Can you give me a public URL I can check against @DavidKabelitz ?

**Comment by DavidKabelitz** [comment]
sure https://www.holtmann.de/messen/markeninszenierung

**Comment by khalwat** [comment]
Here's a page on my site that uses SEOmatic's automatic breadcrumbs which seem to work:

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fnystudio107.com%2Fblog%2Fusing-tailwind-css-with-gatsby-react-emotion-styled-components

At the URL that you gave me, I'm actually seeing *two* `BreadcrumbList` types:

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.holtmann.de%2Fmessen%2Fmarkeninszenierung

Any idea where the second one might be coming from?

**Comment by DavidKabelitz** [comment]
That's what i am asking you ;)

Maybe the mix of our setup of Channel and Single?

Is your /blog Page also a single page and all Sites inside that Channel pages?

Or Setup is like that:

Single Page Url: exhibitions
Channel: exhibitions/{slug}

So we use "Exhibitions" at both.

Don't know if it's important. We use the plugin "Navigation" for the menu setup.

**Comment by DavidKabelitz** [comment]
Looks like the navigation Plugin and its Breadcrumb function causes the error. Will remove all of it...maybe that's the fix

**Comment by DavidKabelitz** [comment]
Yes it's fixed. We just removed all schema.org elements out of the breadcrumb function and now it works perfect. Thanks for your help.
