### ISSUE TITLE
Reset SEO field

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#505]
Is there any option to reset a SEOmatic field, so that the default values comes back?
If not, would that be a nice feature to have? Maybe reset all info for a whole section, category group etc?

**Comment by khalwat** [comment]
In general, I recommend against using SEO Settings fields, since modern SEO should come from content.

As for the issue you're mentioning, I think it's likely the same as this one: https://github.com/nystudio107/craft-seomatic/issues/488
