### ISSUE TITLE
Twitter og:image not showing up when URL is shared (on Homepage only)

### ISSUE THREAD

**Issue by romainpoirier** [nystudio107/craft-seomatic#506]
I have an OG image issue when sharing my website URL on Twitter.

While the `og:image` tag is correctly set by SEOmatic in the `<meta>`, and while Facebook get the image, Twitter don't.

Global SEO > Twitter > Twitter Card Type is set to `Summary Card with Large Image`.

I tried to debug using the [Card Validator](https://cards-dev.twitter.com/validator), but I didn't get any error. However, when I tried another URL that the Homepage, Twitter gets the image ([example](https://www.charleroi.be/vivre/logement/se-loger)).

Do you have any idea why Twitter fails to get it only on the Homepage? Thank you!

```
https://www.charleroi.be
<meta content="https://www.charleroi.be/assets/images/_1200x630_crop_center-center_82_none/394A8584.jpg?mtime=1562161837" property="og:image">
```

**Comment by khalwat** [comment]
I'm not seeing any Twitter meta tags on this site at all; you'll need to fill in the site's Twitter handle in the Site Settings. Twitter _requires_ this for Twitter cards to appear:

https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup

**Comment by romainpoirier** [comment]
This website doesn't have and will not have a Twitter account, so unfortunately I guess we won't be able to show up the Twitter Card image...

What's strange is that despite this, the Twitter Card image still shows up on others pages, even without Twitter handle or Twitter specific meta tags (only regular og tags).

**Comment by khalwat** [comment]
Twitter will look for supported OpenGraph tags if Twitter Card data is missing; see **Twitter Cards and Open Graph** here: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup

But I've found the support isn't as consistent as implementing Twitter cards directly.
