### ISSUE TITLE
Robots.txt is not clearing its own cache for different siteUrls

### ISSUE THREAD

**Issue by danieltott** [nystudio107/craft-seomatic#508]
I have a sort-of-headless Craft site that feeds content to our main site (and `stable` staging site), and I'm setting `siteUrl` based on the referrer. This works perfectly, and does work as intended in the robots.txt generated by SEOmatic with an empty cache. The problem is that SEOmatic is serving this cached version of robots.txt no matter what the siteUrl is set to, which is causing the wrong robots.txt to be served to the different environments.

There may be a good solution to this outside of changes to SEOmatic - I'm not sure. But it seems to me if `siteUrl` is different, we _probably_ don't want to use the same version of the file.

**Comment by danieltott** [comment]
Perhaps adding `siteUrl` into the key for `getOrSet`?

```php
$html = $cache->getOrSet(
  $this::CACHE_KEY . $template . $siteId,
// could become 
$html = $cache->getOrSet(
  $this::CACHE_KEY . $template . $siteUrl,
```

I'm not sure what the implications of something like this would be. I acknowledge that this setup is non-standard so I understand if this isn't fixable.

**Comment by danieltott** [comment]
Or, maybe using the fully-qualified url for robots.txt as the key would work?

**Comment by khalwat** [comment]
So you're changing the `siteUrl` based on the referrer -- have you considered using multiple sites, and each having a different `siteUrl`?

Adding to the cache key probably would be okay, but I'd make it something like:

```php
$html = $cache->getOrSet(
  $this::CACHE_KEY . $template . $siteId . $siteUrl,
```

I'm just a little concerned about changing this caching behavior in a case where it seems like just using multi-site would be the more appropriate way to do things? Or am I missing something in the implementation?

**Comment by danieltott** [comment]
I'm not sure multiple sites is what I want - the content is all the same, except that the siteUrl is different. So for instance when I use `getUrl()`, I need the domain to be different.

So here's the setup: 
cms.domain.com -> Actual Craft site installation/admin access/etc
www.domain.com -> Frond-end site that calls for data from cms.domain.com
www.domain.stable.com -> Staging site that calls same data from cms.domain.com

We have a dev version of the CMS running elsewhere that runs devmode etc, but we have this stable staging site that needs to be able to access the production version of the cms content.

So cms.domain.com needs to know which siteUrl to use to serve the data back.

This works perfectly for everything so far - this is the first thing that I've run into where it isn't working correctly.

For now I've just disabled robots.txt in SEOmatic to work around it, so if this is to edge-casey I  understand and am not totally screwed. I just thought maybe there could be a better way to cache these things. I was digging around in the craft source a bit - it seems like they cache based on url? I'm not entirely sure because it wasn't super clear and I'm far from a php expert.

**Comment by khalwat** [comment]
Hopefully on the non-production domains, the environment is set right for SEOmatic so that search engines are blocked from indexing?

**Comment by danieltott** [comment]
No so the problem here is that the _CMS_ environment is `production` but the front-end is a stable staging environment

**Comment by khalwat** [comment]
Yeah unfortunately on this one, I think it's working as intended. I realize it isn't working for you but it's reasonable for SEOmatic to assume a different `siteId` should be in play for a separate site.

**Comment by danieltott** [comment]
In case anyone comes across this in the future, you can now solve this via the [Site URL Override](https://nystudio107.com/docs/seomatic/Configuring.html#advanced-plugin-settings) seoMatic setting 🙌
