### ISSUE TITLE
siteUrlOverride config isn't being used

### ISSUE THREAD

**Issue by wfendler** [nystudio107/craft-seomatic#509]
I have a headless setup (with `headlessMode` off so we can use this plugin) so I'm trying to use the `siteUrlOverride` config option so that our CMS URL isn't being included in our GraphQL queries but it doesn't seem to be working.

I've changed some other settings like `pluginName` and that comes through immediately so I've verified the file is in the correct location and being read by craft and the plugin.

My `config/seomatic.php` file:
```php
<?php
return array(
  '*' => array(
    'pluginName' => 'SEO',
    'siteUrlOverride' => 'https://google.com',
  ),
  'dev' =>  array(
    'siteUrlOverride' => 'https://google.com',
    'globalMetaOverride' => array(
      'robots' => 'noindex',
    ),
  ),

  'staging' => array(
    'siteUrlOverride' => 'https://google.com',
    'globalMetaOverride' => array(
      'robots' => 'noindex',
    ),
  ),

  'production' =>  array(
    'siteUrlOverride' => 'https://google.com',
    'globalMetaOverride' => array(
      'robots' => 'all',
    ),
  )
);
```

(Set to google.com only for testing purposes of course!)

Some other potentially relevant notes: 
When I change `separatorChar` I've needed to re-save the entry before I see a change in the GraphQL explorer's response. I've also noticed that the `robots` settings here don't override what's set in the CP. Lmk if I should file other issues for those, I just wanted to first make sure there wasn't something wrong with my config file in case there's one root cause to this or if I'm simply misunderstanding how this is designed to work.

- Craft 3.3.16.1 (Pro Trial)
- SEOmatic 3.2.34

**Comment by khalwat** [comment]
`siteUrlOverride` is something from the Craft 2.x version of SEOmatic; it isn't a thing in SEOmatic for Craft 3. Same with `globalMetaOverride` -- you can see the settings variables here:

https://nystudio107.com/docs/seomatic/Configuring.html#multi-environment-config-settings

You can learn more about advanced SEOmatic usage here:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively

If you have further issues, sure, feel free to file them!

**Comment by wfendler** [comment]
Thanks! I suppose looking at the proper docs will help. 🤦‍♂️

I copied [GlobalVars.php](https://github.com/nystudio107/craft-seomatic/blob/fe3a6ac63365ebbdd1d89b675fac0e7c23f82072/src/seomatic-config/globalmeta/GlobalVars.php) and put it at `config/seomatic-config/globalmeta/GlobalVars.php`. I edited the `canonicalUrl` but it's not working when I use the GraphQL explorer. All URLs in the markup are using localhost.

I've checked the other config files and they all seem to reference this field. I'm trying to get all of the SEO markup with the proper URL for our gatsby site. Is this the right approach to getting it to give me the right URL with a headless setup?

**Comment by khalwat** [comment]
Please check the documentation for those files:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively

https://nystudio107.com/docs/seomatic/Advanced.html#config-settings

Changes there **only** apply to newly created sections. In your case, since these are globals, that will have been created long ago. The config settings exist to allow for customization of repeated installations, not for the use I think you're intending.

Can you open a new issue that states what you're trying to accomplish, or contact me on Discord at `andrew.welch` to discuss what you're trying to accomplish?

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/67442bfd2e207875cf149072bcf0b365a4a02c57
