### ISSUE TITLE
Invalid price format

### ISSUE THREAD

**Issue by mcjackson18** [nystudio107/craft-seomatic#510]
When a product has a price over £1000 the mircodata price is in displayed with a comma - `"price":"3,700.00"` which is an invalid format.

According to http://schema.org/price guidelines - "Use '.' (Unicode 'FULL STOP' (U+002E)) rather than ',' to indicate a decimal point. Avoid using these symbols as a readability separator."

Thanks

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/089cc10381724e7ca30c7f476397190caf2d23bc

**Comment by mcjackson18** [comment]
Thanks!

**Comment by mcjackson18** [comment]
Thanks for the quick update. I've updated the plugin but the price is still displaying with a comma. I've tried clearing the SEOmatic caches, re-saving the product and re-saving the product type.

How can I get a product to use the updated price format?
