### ISSUE TITLE
No OG image output

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#511]
Original site was built on Craft 2, upgraded to Craft 3 last year. As part of the migration to C3 we added the SEOmatic field to all channels field name (SEO New).

However we just discovered after updating to the latest Craft 3.3.15.1 and SEOmatic 3.2.34 that a number of sections are not outputting the OG image at all including the homepage.

Locally I tested the home page by deleting and re-adding the seo Image (set to the hero image), then removing the legacy SEOmatic field and saving the entry, then by removing the current SEOmatic field and saving. No changes.

SEOmatic appears to be outputting all the usual SEO tags except OG image.

When viewing source locally on the homepage this is what I see:

```
<!-- >>> BLOCK BEGIN >>> head -->
--

<!-- 0.01ms <<< BLOCK END <<< head -->
<title>🚧 Home Page \| IHRSA</title><meta name="generator" content="SEOmatic">
<meta name="description" content="Home Page">
<meta name="referrer" content="no-referrer-when-downgrade">
<meta name="robots" content="none">
<meta content="/IHRSA" property="fb:profile_id">
<meta content="en_US" property="og:locale">
<meta content="IHRSA" property="og:site_name">
<meta content="website" property="og:type">
<meta content="http://ihrs.test/" property="og:url">
<meta content="Home Page" property="og:title">
<meta content="Home Page" property="og:description">
<meta content="https://www.instagram.com/ihrsa/" property="og:see_also">
<meta content="https://www.youtube.com/user/IHRSALive" property="og:see_also">
<meta content="https://www.linkedin.com/company/ihrsa/" property="og:see_also">
<meta content="https://www.facebook.com/IHRSA" property="og:see_also">
<meta content="https://twitter.com/ihrsa" property="og:see_also">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@ihrsa">
<meta name="twitter:creator" content="@ihrsa">
<meta name="twitter:title" content="Home Page">
<meta name="twitter:description" content="Home Page">
<link href="http://ihrs.test/" rel="canonical">
<link href="http://ihrs.test/" rel="home">
<link type="text/plain" href="http://ihrs.test/humans.txt" rel="author">
<link href="http://ihrs.test/" rel="alternate" hreflang="x-default"></head>
```

In addition to the homepage there are several other sections where OG image is not outputting.

Please advise.

**Comment by khalwat** [comment]
Go to SEOmatic ->  Content SEO, click on the Section in question, then click on FaceBook, check the settings there, and then click on Save.

Clear caches, then reload the page.

**Comment by khalwat** [comment]
More here: https://github.com/nystudio107/craft-seomatic/issues/297

**Comment by CreateSean** [comment]
Andrew,

The agency I built this site for (originally on C2) did some testing on the staging server and things appear to be random. Quote:

> On the staging site, I just tried to update the Home Page single entry Title tag. I did this by going to SEOMatic > Content > Home Page. 
> 
> The title on the front end did not update. However, if I went into the SEO tab within the entry and updated it there, it works?
> 
> Something weird is going on here. Half the fields in the SEO tab work and half don't. Then half the fields in the SEOMatic Content section work and half don't. We need to get to the bottom of this so the client knows where to update their SEO content.


Another client update:

> Singles: [used Contact form and Improve Your Club entries for testing]
> 
> SEO Tab in Entry:
> Title field: works
> Description field: works
> Keyword field: works - but as soon as you save it, the keywords disappear but still appear in source code 
> Image field: Doesn't work 
> 
> SEOMatic fields:
> Title field: doesn't work
> Description field: doesn't work
> Keyword field: doesn't work - oddly enough when you use Custom Text and populate this field, the keywords tag disappears completely in the source code
> Image field: doesn't work 

Please advise.

**Comment by khalwat** [comment]
I think you're going to need to do some testing to see what is going on here; without access, I cannot tell.

Did you try what was discussed in the thread I linked you to here?

**Comment by CreateSean** [comment]
Did you mean to try this:

> it's not re-saving each entry, it's just re-saving each Content SEO section. Specifically, going to the General, Twitter, and Facebook sub-tabs for each, and clicking Save on each.

It's not my direct client - I'll ask about getting you access to the control panel and repo.

**Comment by khalwat** [comment]
Yes, I mean that. Please try that first.
