### ISSUE TITLE
seomatic.link.create only creates/adds the last one created

### ISSUE THREAD

**Issue by samueljonasson** [nystudio107/craft-seomatic#512]
In an effort to have my stylesheet links appear next to the link tags generated by Seomatic I am doing this.  
```
{% do seomatic.link.create({"rel": "stylesheet","href": "https://use.typekit.net/xjl0abs.css" }) %}
{% do seomatic.link.create({"rel": "stylesheet","href": "http://example.com/assets/css/site.min.css" }) %}
```
However, only the latter is actually included.  Is that by design?  It is like you can only add on link with "rel" set to "stylesheet".

**Comment by khalwat** [comment]
So... you probably should not be using SEOmatic to add links to your CSS style sheets... I mean I guess you can, but it's not really what it's intended for.

Anyway the issue is you just need to pass in a unique key for each, such as:

```twig
{% do seomatic.link.create({"key": "css1", "rel": "stylesheet","href": "https://use.typekit.net/xjl0abs.css" }) %}
{% do seomatic.link.create({"key": "css2", "rel": "stylesheet","href": "http://example.com/assets/css/site.min.css" }) %}

```
