### ISSUE TITLE
Sitemap Submap is empty

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#514]
Craft 3.3.16.1
SEOmatic 3.2.34

One of my sites is generating empty sub sitemaps. I saw this [thread](https://github.com/nystudio107/craft-seomatic/issues/162) and followed the instructions you provided:

> I've noticed that if I visit the sitemap directly in Chrome, it displays as plain text, but if you choose "View Source" that it shows the structure of the document is correct.

Viewing source on one empty sub sitemap showed the items as expected. However another empty map did not show anything when viewing source.

**Comment by khalwat** [comment]
You will need to provide me with a URL so I can inspect it myself.

**Comment by khalwat** [comment]
Closing. Will re-open if more info is provided.
