### ISSUE TITLE
Channel not showing in SEO Content table

### ISSUE THREAD

**Issue by kblizeck** [nystudio107/craft-seomatic#515]
I have a Providers channel that is not showing the SEO Content table. I haven't renamed or modified the Channel in any way, and SEOMatic was just recently installed and updated.

Craft: 3.2.10
SEOMatic: 3.2.35 

![Screen Shot 2019-12-03 at 3 28 42 PM](https://user-images.githubusercontent.com/9886123/70095795-dba46e00-15e2-11ea-97ff-6c1745fdb881.png)
![Screen Shot 2019-12-03 at 3 28 18 PM](https://user-images.githubusercontent.com/9886123/70095796-dba46e00-15e2-11ea-91bd-833b93685946.png)

**Comment by khalwat** [comment]
Navigate to the channel on the frontend or CP, and it should appear.

**Comment by kblizeck** [comment]
Hi @khalwat - I navigated to the channel in both the frontend and the CP, and it still doesn't show in the Content table.

**Comment by khalwat** [comment]
Is it possible that it is paginated, and is appearing on Page 2 of the list?

**Comment by kblizeck** [comment]
@khalwat Negative, it says "Displaying 1 to 20 of 20 items" and it should appear between Press Releases and Service, if that list is truly alphabetical.

**Comment by khalwat** [comment]
Was this channel named something else, and then renamed?

One last question, sorry... does this channel Provider have public URLs?

**Comment by kblizeck** [comment]
@khalwat We are generating the URLs via Routes. Here's a screenshot of the Channel settings.
![Screen Shot 2019-12-10 at 7 32 13 AM](https://user-images.githubusercontent.com/9886123/70538396-3f68f280-1b1f-11ea-9a87-9e2441b65b0e.png)

**Comment by khalwat** [comment]
Aha yep, if you do it that way, SEOmatic can't know about the link between a given entry in the channel, and a route, because nothing is auto-injected by Craft.

Instead, you'll need to do it manually via Twig ala:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#rendering-metadata-from-another-route

**Comment by kblizeck** [comment]
🤦‍♀ Thank you for your assistance @khalwat!
