### ISSUE TITLE
[FR] GraphQL feature notices or GraphQL mode

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-seomatic#516]
There are some SEOmatic features that are not accessible to the front-end when using Craft as a headless CMS. For example, if you were to add tracking scripts to the front-end you would do that directly in your front-end application and SEOmatic’s tracking settings would be ignored (unless they are used by the back-end). This could be confusing to clients who have admin access (which ignores the SEOmatic user permissions).

It would be nice to have a way to either hide the UI for these features so they don't appear in SEOmatic’s settings, or to display a warning that these features aren’t used on the front-end (maybe have a "headlessMode" or "graphqlMode" setting to turn this on).

**Comment by wbrowar** [comment]
My specific use case here is that I'll be handing admin rights of a site over to a client and instead of telling them that SEOmatic has certain features that they need to ignore (and making a list of those somewhere), it would be great to let SEOmatic let them know what is available to them.

**Comment by khalwat** [comment]
So in the case of tracking scripts, you can use those with your front-end application. When you get the meta containers, you can get the script container, and add those scripts via Vue Meta or Helmet or what have you.

Unless there are other things you've found, I think this issue should be closed?

**Comment by khalwat** [comment]
@wbrowar mentioned to me that this is a non-issue.
