### ISSUE TITLE
[FR] Sitemap info in GraphQL

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-seomatic#517]
When using Craft as a headless CMS, having the ability to get all of SEOmatic’s sitemap data via GraphQL would allow content admins to use SEOmatic to configure their sitemap within the CMS and then allow the front-end to build its sitemaps from that data.

**Comment by khalwat** [comment]
Added in 3.4.18

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.18”,
```
Then do a `composer clear-cache && composer update`
