### ISSUE TITLE
seomatic-tokens.js javascript error

### ISSUE THREAD

**Issue by pieterjandebruyne** [nystudio107/craft-seomatic#519]
Hi,

If I try to make a new field ( /craft/settings/fields/new ) (doesn't have to be a seomatic field) there is a javascript error caused by seomatic-tokens.js

```
Uncaught TypeError: Cannot read property 'value' of null
    at Module.52 (seomatic-tokens.js:22)
    at i (bootstrap:79)
    at n (bootstrap:45)
    at bootstrap:152
    at bootstrap:152

This is causing the error :
21 let el = document.querySelector('.seomatic-keywords');
22 let keywords = el.value.split(',').map((value, index) => {
23    if (value !== '') {
24        return { id: index, name: value };
25     }
26 });
```

Version:
seomatic: 3.2.37
Craft CMS 3.3.18.1

**Comment by khalwat** [comment]
yep, same as: https://github.com/nystudio107/craft-seomatic/issues/482

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/7dfb48b9332d6cee0c756799860ad8d3c6875a53

**Comment by TomHell** [comment]
Hi Andrew,
currently I struggled into same (not 100% sure) problem. There is something wrong/broken for class **.seomatic-keywords** in **seomatic-token.js** on line 9 in backend. This error occurs always when I start to create/edit an entry of a section where I use SEOmatic.

**Setup**
- Craft 3.3.20.1 (error was in Version 3.3.15 too)
- SEOMatic 3.2.34

**Chrome console**
> Uncaught TypeError: Cannot read property 'value' of null
>     at Module.52 (seomatic-tokens.js:9)
>     at a (seomatic-tokens.js:9)
>     at r (seomatic-tokens.js:9)
>     at seomatic-tokens.js:9
>     at seomatic-tokens.js:9

**Line where error starts**
```
var n=r(23),
o=document.querySelector(".seomatic-keywords"),u=void 0;o.value&&(u=o.value.split(",").map((function(e,t){if(""!==e)return{id:t,name:e}})));
```

Thanks for helping to find the problem.

**Comment by khalwat** [comment]
@TomHell this is a soft error that will not affect any functionality in the backend... however, if you update to the latest version of SEOmatic, it should be fixed.

**Comment by TomHell** [comment]
@khalwat, I still updated to the latest version 3.2.39 today and the error is not gone. Backend is not effected by this error which is good.

```
Uncaught TypeError: Cannot read property 'value' of null
    at Module.52 (seomatic-tokens.js:9)
    at a (seomatic-tokens.js:9)
    at r (seomatic-tokens.js:9)
    at seomatic-tokens.js:9
    at seomatic-tokens.js:9
```
