### ISSUE TITLE
Cannot suppress og:locale:alternate meta tags

### ISSUE THREAD

**Issue by webtrend** [nystudio107/craft-seomatic#520]
Per the instruction when I include the following line in my template
`{% do seomatic.link.get('og:locale:alternate').include(false) %}`
I get an error:

> Impossible to invoke a method ("include") on a null variable.

I am not sure why is it throwing an error about the variable being null because the rendered page does have those tags.

**Comment by khalwat** [comment]
Ah, I see! It's actually a tag:

```html
<meta content="es_ES" property="og:locale:alternate">
```

...not a link, so you'd want:

```twig
{% do seomatic.tag.get('og:locale:alternate').include(false) %}
```

**Comment by seb-jones** [comment]
Hi,

I think the [docs](https://nystudio107.com/docs/seomatic/Technologies.html#multi-site-language-locale-support) for this need to be updated? They still suggest doing the following:

```twig
{% do seomatic.link.get('alternate').include(false) %}
{% do seomatic.link.get('og:locale:alternate').include(false) %}
```

Which leads to the error specified in this issue.

**Comment by khalwat** [comment]
Thx @seb-jones --fixed in https://github.com/nystudio107/craft-seomatic/commit/6d87a1e04d4af22d998182ee60c03eae5f0e5fca & rebuild & deployed the changed docs
