### ISSUE TITLE
Cannot append seoKeywords with comma

### ISSUE THREAD

**Issue by webtrend** [nystudio107/craft-seomatic#521]
`{% if keywords is defined %}
	{% do seomatic.meta.seoKeywords(seomatic.meta.seoKeywords ~ ", " ~ keywords|title) %}
{% endif %}`

Per the code above, I want comma to append to the existing keywords followed by the additional keywords. The issue is that  The keyword(s) is appended to the existing string without any comma or space. In other words there is no separator in the rendered html content. I have tried single quotes and double quotes both and none of them work
Is there a way to do this?

**Comment by khalwat** [comment]
So first, in general, I would not worry about the `keywords` tag, since it's ignored entirely by Google.

However, assuming you have a reason to care about the `keywords` tag... I tested your code here, and it's working as expected.

```twig
{% do seomatic.meta.seoKeywords("hello, there") %}

{% set keywords = "hello" %}
{% if keywords is defined %} {% do seomatic.meta.seoKeywords(seomatic.meta.seoKeywords ~ ", " ~ keywords|title) %} {% endif %}
{{ seomatic.meta.seoKeywords }}
```

Outputs:

```
hello, there, Hello
```

And if I view the source, I see this tag:

```html
<meta name="keywords" content="hello, there, Hello">
```
