### ISSUE TITLE
No aliasing of Twitter creator / site

### ISSUE THREAD

**Issue by qrazi** [nystudio107/craft-seomatic#522]
**Issue**:
When a twitter handle clashes with a defined alias, the resulting meta-elements in the DOM of pages has the value of the alias, instead of the expected twitter handle.

This was supposed to be resolved in 3.0.20, but either seems to have been untested or broken again over time. Right the fix in 3.0.20 check the incorrect key and a second check needs to be added to prevent alias resolving.

**Expected result**:
`<meta name="twitter:creator" content="@Foo">`

**Actual result**:
`<meta name="twitter:creator" content="/some/path/to/the/project/module/map">`

**Steps to reproduce**:

- when site name is "Foo"
- when SEOmatic Twitter creator is "Same as site Twitter handle"
- when a module / plugin (e.g. named "Foo") is installed that defines an alias `Craft::setAlias('@Foo', '/some/path/to/the/project/module/map');`
- then SEOmatic resolves the initial handle to "@{seomatic.site.twitterCreator}", which resolves to "@Foo" which is then resolved into "/some/path/to/the/project/module/map"
- then the DOM of the page contains `<meta name="twitter:creator" content="/some/path/to/the/project/module/map">`

**Comment by khalwat** [comment]
Thanks, I'll have a look

**Comment by khalwat** [comment]
Fixed via your PR, thanks! Will be in SEOmatic 3.2.38
