### ISSUE TITLE
Create a single sitemap instead of chunked

### ISSUE THREAD

**Issue by ian-p** [nystudio107/craft-seomatic#524]
Is there a way to force a single sitemap file generation instead of chunks? We have a process that processes the file and would like to avoid crawling the chunks.

If it's not possible is there a way to get a flat list of URLs of all the generated chunks? 
Can the chunks generated with default settings be more than one level deep?

**Comment by khalwat** [comment]
There is no way to generate just one flat sitemap file, the easiest thing to do is probably to crawl the sitemap index to get a list of all of the sitemaps, and then crawl each one individually.

Short of that, you could probably combine all of the above if you wanted to... but you'd still need to crawl the sitemap index to get a list of all of them.
