### ISSUE TITLE
single bracket syntax shortcut not working as intended

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#527]
I have found when using the following syntax, it fails and falls back to the default global description.
`{ entry.metaDescription ??? entry.excerpt }`
However, if I use the object. syntax then this works.
`{{ object.entry.metaDescription ??? object.entry.excerpt}}`

Is this a bug or intended? The docs seem to point at this being a bug.
https://nystudio107.com/docs/seomatic/Configuring.html#content-seo

A few screenshots to illustrate.
<img width="1309" alt="Screenshot 2020-01-03 at 11 20 28" src="https://user-images.githubusercontent.com/5698596/71720898-1df7df80-2e1b-11ea-8c78-0cd98f28bd00.png">
<img width="1312" alt="Screenshot 2020-01-03 at 11 20 39" src="https://user-images.githubusercontent.com/5698596/71720902-1fc1a300-2e1b-11ea-9a68-eab3df79489d.png">

**Comment by khalwat** [comment]
I probably should just document the double bracket syntax instead. It's not really a bug, more of a quirk in how Craft's object template parsing regex works.

**Comment by terryupton** [comment]
Did you mean document the double bracket (object) syntax? As it is the single syntax that doesn't work.

**Comment by khalwat** [comment]
yep sorry, edited the post
