### ISSUE TITLE
How to print seo field values if set from field?

### ISSUE THREAD

**Issue by tjheffner** [nystudio107/craft-seomatic#529]
Hey there, thanks for the amazing plugin! I have one issue I'm bumping into that I haven't seen answered in the docs anywhere yet--

I have a section with an "SEO Settings" field on it for entry-specific SEO settings. I'm trying to render the SEO description as part of my search results. This works perfectly when the SEO description field is custom text, e.g. `entry.seoSettings.metaGlobalVars.seoDescription,` will print the custom text as expected.

Where my issue comes in is when the seoDescription is set to populate based on a field value. e.g. if I set the source "From Field", I would expect `entry.seoSettings.metaGlobalVars.seoDescription,` to now print out the contents of that selected field (in this case, postBody). but instead it outputs `{seomatic.helper.extractTextFromField(object.entry.postBody)}` as a string. 

What am I missing here?

**Comment by tjheffner** [comment]
Alternatively, if there was a way to see _what_ the given source field is, so I could just pull that data instead. but it doesn't appear to get stored. At the very least it's not surfaced from kint.

**Comment by khalwat** [comment]
So what you need to do is render the description first, which you can do with something like:

```twig
{{ seomatic.meta.parsedValue('seoDescription') }}
```

**Comment by danielenstrom** [comment]
@tjheffner did you solve this? I'm having the same issue on a search results page :)
