### ISSUE TITLE
Data migration from the old Craft 2.x SEOmatic_Meta Field

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-seomatic#53]
See if there is some way that data can be migrated from the old SEOmatic_Meta field when users are upgrading from Craft 2.x. This is primarily of concern when custom SEO data has been entered in the Title, Description, Keywords, or Image fields.

It's not an issue if the Field was set to _pull_ data, since that can and should be configured via SEOmatic 3's Content SEO field.

c.f.: https://github.com/nystudio107/craft-seomatic#upgrading-from-seomatic-1x-for-craft-cms-2x

**Comment by johnwbaxter** [comment]
Certainly if people are putting custom SEO keywords/title/desc into that fieldtype rather then just configuring where it came from, you need to migrate that. Otherwise, to go to C3 then they would need some dev chops to get that pretty darned important over to the newly upgraded site.

**Comment by khalwat** [comment]
Yep, I agree!

https://github.com/craftcms/cms/issues/2668

**Comment by khalwat** [comment]
So this is coming along quite well; I plan to have it released in the next version, which should be coming out tonight.

It implements a faux `Seomatic_Meta` field type to be able to read in the old SEOmatic 2.x field data. So then if you add a new SEO Settings field to a Section, it will automatically grab the data from the old field and import it into the new one.

While this does require a small manual step of adding a Field, I'm doing it this way because the way the plugin works is fundamentally different: in most cases, you wouldn't need a Field at all, instead you'll just set up the mappings in the Content SEO settings. I want to encourage that.

But if you do have older sites that you're bringing over that contain a bunch of custom SEO in an Seomatic_Meta FieldType, this will migrate it for you.

I'm also looking into a way to read these field settings to automagically configure the Content SEO settings for you, if you've set up a Field that auto-pulled from existing content in Craft 2.x

**Comment by khalwat** [comment]
Implemented in SEOmatic 3.0.0-beta.21:

https://github.com/nystudio107/craft-seomatic/releases/tag/3.0.0-beta.21

**Comment by johnwbaxter** [comment]
Nice!!

**Comment by khalwat** [comment]
It will migrate your "pull from field" settings from an old Craft 2.x FieldType to your Content SEO settings.

It will also migrate data on a per-entry basis if you add an SEO Settings Field to a Section that has an old SEOmatic Meta FieldType in it.

![google chromescreensnapz1127](https://user-images.githubusercontent.com/7570798/38431339-eadfd7bc-3991-11e8-8aa1-65c3863282da.png)

![google chromescreensnapz1128](https://user-images.githubusercontent.com/7570798/38431342-ef175d82-3991-11e8-86cd-1d7f7870e597.png)
