### ISSUE TITLE
Opening Hours aren't saved anymore

### ISSUE THREAD

**Issue by sjadema** [nystudio107/craft-seomatic#530]
Since updating to `3.2.38`, the opening hours under `/admin/seomatic/site/identity/default` aren't saved anymore. You can still select them, but after the page refresh the values are gone. This might happen because of a JS error that occurs as well:

```js
Uncaught TypeError: Cannot read property 'value' of null
    at Module.52 (seomatic-tokens.js:23)
    at a (bootstrap:79)
    at r (bootstrap:45)
    at bootstrap:152
    at seomatic-tokens.js:9
```

In the 3.2.38 release, that file was changed at those lines.

**Comment by khalwat** [comment]
I just attempted to reproduce this, but can't. I entered some random opening hours, clicked on Save, and they were saved:

<img width="863" alt="Screen Shot 2020-01-09 at 8 40 14 AM" src="https://user-images.githubusercontent.com/7570798/72072352-bda1eb80-32bb-11ea-860a-11dc9150c646.png">

Perhaps try clearing caches or the like? That JavaScript error is old, and in any event shouldn't be relevant here.

**Comment by sjadema** [comment]
Did some extensive digging and found out it has something to do with PHP 7.4. When running on 7.3, everything works fine but when swapping to 7.4, the opening hours aren't saved anymore. I haven't found out why this is happening.

**Comment by khalwat** [comment]
Is there anything at all in any of the log files @sjadema ?

**Comment by sjadema** [comment]
No, that's where i started. Eventually a database query is performed to update the record:

```sql
UPDATE `craft_seomatic_metabundles` SET `dateUpdated`='2020-01-13 22:38:45', `sourceId`=1, `sourceSiteId`=1, `sourceDateUpdated`='2020-01-13 22:38:45', `metaSiteVars`='{\"siteName\":\"TPP Fivelpoort\",\"identity\":{\"siteType\":\"Organization\",\"siteSubType\":\"LocalBusiness\",\"siteSpecificType\":\"Dentist\",\"computedType\":\"Dentist\",\"genericName\":\"TPP Fivelpoort\",\"genericAlternateName\":\"\",\"genericDescription\":\"\",\"genericUrl\":\"\",\"genericImage\":\"\",\"genericImageWidth\":\"\",\"genericImageHeight\":\"\",\"genericImageIds\":\"\",\"genericTelephone\":\"+31596362116\",\"genericEmail\":\"info@tpp-fivelpoort.nl\",\"genericStreetAddress\":\"Opwierdermeerweg 3\",\"genericAddressLocality\":\"Appingedam\",\"genericAddressRegion\":\"\",\"genericPostalCode\":\"9902 SG\",\"genericAddressCountry\":\"Netherlands\",\"genericGeoLatitude\":\"\",\"genericGeoLongitude\":\"\",\"personGender\":\"Male\",\"personBirthPlace\":\"\",\"organizationDuns\":\"\",\"organizationFounder\":\"\",\"organizationFoundingDate\":\"\",\"organizationFoundingLocation\":\"\",\"organizationContactPoints\":\"\",\"corporationTickerSymbol\":\"\",\"localBusinessPriceRange\":\"$$$\",\"localBusinessOpeningHours\":[{\"open\":null,\"close\":null},{\"open\":[],\"close\":[]},{\"open\":null,\"close\":null},{\"open\":null,\"close\":null},{\"open\":null,\"close\":null},{\"open\":null,\"close\":null},{\"open\":null,\"close\":null}],\"restaurantServesCuisine\":\"\",\"restaurantMenuUrl\":\"\",\"restaurantReservationsUrl\":\"\"},\"creator\":{\"siteType\":\"Organization\",\"siteSubType\":\"LocalBusiness\",\"siteSpecificType\":\"\",\"computedType\":\"Organization\",\"genericName\":\"\",\"genericAlternateName\":\"\",\"genericDescription\":\"\",\"genericUrl\":\"\",\"genericImage\":\"\",\"genericImageWidth\":\"\",\"genericImageHeight\":\"\",\"genericImageIds\":[],\"genericTelephone\":\"\",\"genericEmail\":\"\",\"genericStreetAddress\":\"\",\"genericAddressLocality\":\"\",\"genericAddressRegion\":\"\",\"genericPostalCode\":\"\",\"genericAddressCountry\":\"\",\"genericGeoLatitude\":\"\",\"genericGeoLongitude\":\"\",\"personGender\":\"\",\"personBirthPlace\":\"\",\"organizationDuns\":\"\",\"organizationFounder\":\"\",\"organizationFoundingDate\":\"\",\"organizationFoundingLocation\":\"\",\"organizationContactPoints\":[],\"corporationTickerSymbol\":\"\",\"localBusinessPriceRange\":\"\",\"localBusinessOpeningHours\":[],\"restaurantServesCuisine\":\"\",\"restaurantMenuUrl\":\"\",\"restaurantReservationsUrl\":\"\"},\"twitterHandle\":\"\",\"facebookProfileId\":\"149183768878689\",\"facebookAppId\":\"\",\"googleSiteVerification\":\"\",\"bingSiteVerification\":\"\",\"pinterestSiteVerification\":\"\",\"sameAsLinks\":{\"twitter\":{\"siteName\":\"Twitter\",\"handle\":\"twitter\",\"url\":\"\"},\"facebook\":{\"siteName\":\"Facebook\",\"handle\":\"facebook\",\"url\":\"https://www.facebook.com/TPPFivelpoort\"},\"wikipedia\":{\"siteName\":\"Wikipedia\",\"handle\":\"wikipedia\",\"url\":\"\"},\"linkedin\":{\"siteName\":\"LinkedIn\",\"handle\":\"linkedin\",\"url\":\"\"},\"googleplus\":{\"siteName\":\"Google+\",\"handle\":\"googleplus\",\"url\":\"\"},\"youtube\":{\"siteName\":\"YouTube\",\"handle\":\"youtube\",\"url\":\"\"},\"instagram\":{\"siteName\":\"Instagram\",\"handle\":\"instagram\",\"url\":\"\"},\"pinterest\":{\"siteName\":\"Pinterest\",\"handle\":\"pinterest\",\"url\":\"\"},\"github\":{\"siteName\":\"GitHub\",\"handle\":\"github\",\"url\":\"\"},\"vimeo\":{\"siteName\":\"Vimeo\",\"handle\":\"vimeo\",\"url\":\"\"}},\"siteLinksSearchTarget\":\"\",\"siteLinksQueryInput\":\"\",\"additionalSitemapUrls\":[],\"additionalSitemapUrlsDateUpdated\":null,\"additionalSitemaps\":[]}' WHERE `id`=1
```

The opening hours are an empty array at this point. I have yet to find out why this happens.

**Comment by khalwat** [comment]
hrm okay. I don't have a PHP 7.4 environment set up yet, but sounds like I need to get one

**Comment by sjadema** [comment]
It's strange because other date(time) fields are still working. The `postDate` field when editing an entry for example. This makes me think it has to do with the plugin and not with Yii / Craft (checked both changelogs + code changes as well).

**Comment by khalwat** [comment]
Oh right, I'm on board with this likely being an issue with the plugin. It's just somewhat mysterious. If I had to guess, it'd be somewhere in here:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/controllers/SettingsController.php#L1132

or here:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L654

**Comment by sjadema** [comment]
Yeah, checked that flow. The `$values` variable contains the correct values in https://github.com/nystudio107/craft-seomatic/blob/ea40d15bf182761e5f69eec52f46354b884609ef/src/helpers/DynamicMeta.php#L673 though. I'll investigate some more in the morning.

**Comment by khalwat** [comment]
Any luck?

**Comment by sjadema** [comment]
Sorry man, kind of busy and the project had to be released so I decided to run it with PHP 7.3 for now. I'll investigate some more in the upcoming weekend.

**Comment by sjadema** [comment]
Did some more research and found out that it's a bug with with `json_encode()`. When saving a `\nystudio107\seomatic\records\MetaBundle`, eventually `\yii\helpers\BaseJson::encode()` is executed via `\craft\helpers\Db::prepareValueForDb()`.

 This tries to process the data in `\yii\helpers\BaseJson::processData()` which wrongly encodes instances of `\DateTimeInterface` as per https://github.com/yiisoft/yii2/issues/17760. It's actually a ['bug'](https://bugs.php.net/bug.php?id=79041) in PHP which doesn't seems like it's fixed so Yii rolled out a [fix](https://github.com/yiisoft/yii2/blob/master/framework/CHANGELOG.md#2032-january-21-2020).

Seems to not be an issue with your plugin after all :) Now we just have to wait for Craft to update to Yii 2.0.32.

**Comment by khalwat** [comment]
Phew, wow, thanks for getting to the bottom of this!
