### ISSUE TITLE
og:type not showing up when updated 

### ISSUE THREAD

**Issue by mariovass** [nystudio107/craft-seomatic#531]
I have tried to update the og:type for channel type under the content seo tab and it does not change on the front-end I have also tried to clear cache with no luck. this is quite important for us if we need to define all blogposts as articles rather than website.

see loom video for more info. https://www.loom.com/share/2981b94d0a2a4c24aaaf6ee63ed10930

**Comment by khalwat** [comment]
I've tried to replicate this, but cannot do so locally, which makes me think it's likely something specific to your site.

How are you clearing the caches, and what caches are you clearing?

**Comment by khalwat** [comment]
Is it possible that you're using an SEO Settings field in that Section that is overriding the changes you're making to Content SEO here?

**Comment by khalwat** [comment]
I'm going to assume that you _do_ have an SEO Settings field, in which case, this should fix the issue:

https://github.com/nystudio107/craft-seomatic/commit/6d9d8419db19fb4fa6430402a505ab611db4a317
