### ISSUE TITLE
Using custom string template for images in Content SEO does not work as expected

### ISSUE THREAD

**Issue by Mosnar** [nystudio107/craft-seomatic#534]
If I select "Asset from field" for a particular section's SEO Image Source and then select a field on an entry, I get the following tags with that image generated:
- og:image
- twitter:image
as well as the appropriate JSON LD schema markup

However, suppose I have two fields: `seoImage` and `listingPageImage` - ideally, I'd want to use the seoImage if one is set and then fallback to the listing page image, since it's required. To do this, I might use the following Custom URL for my SEO Image Source:
```twig
{seomatic.helper.socialTransform(object.entry.seoImage[0], "base", 1, "crop") ??? seomatic.helper.socialTransform(object.entry.listingPageImage[0], "base", 1, "crop")}
```

Or maybe even:
```twig
{seomatic.helper.socialTransform(object.entry.seoImage[0] ??? object.entry.listingPageImage[0], "base", 1, "crop")}
```

When I use this method, I only get the JSON-LD schema and the other meta tags do not render.

In fact, using this also does not work:
```twig
{seomatic.helper.socialTransform(object.entry.listingPageImage[0], "base", 1, "crop")}
```

Related:
- Craft 3.3.20.1 Pro
- SEOmatic 3.2.38
- PHP 7.3

**Comment by khalwat** [comment]
Same as this, yes? https://github.com/nystudio107/craft-seomatic/issues/498

Somehow it ended up being that the single bracket syntax was causing the issue -- try changing `{` to `{{`

**Comment by Mosnar** [comment]
Ah! Not sure how I missed that issue! Yep - same problem, didn't realize I had to set the twig template on Twitter and Facebook. Thanks!

**Comment by khalwat** [comment]
Well, "have to" is strong... I'm not happy that it doesn't "just work" but I'm not sure what the right answer is.

So if you go custom for the SEO image, the issue is that it now resolves to just a string. And Craft can't then do an image transform on a string.
