### ISSUE TITLE
[FR] Improve the way overrides are handled & displayed in SEO Settings fields

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-seomatic#535]
So in general, I like this idea. The change was originally made from the behavior that you want (which mostly existed already) to the current behavior because people complained that the "override" wasn't obvious.

However, I think if we had a field that clearly said "Use Content SEO Setting" or something like that, perhaps that'd be ideal.

I think it's primarily because I chose poor UX, in that the field were just blank by default. People expected them to show whatever was set in the Content SEO settings.

But if we put "Default" or "Same as Content SEO" or what have you, perhaps that's enough of a cue to make it nice for everyone.

Alright so I dove in thinking this would be a quick easy change, but now I remember the issue.

What _really_ should happen here is when settings are in a Field context, there should be:

1. A preview of the current setting (whether text or image or whatever)
2. An Override light switch that toggles:
  a. Hides the preview of the current setting
  b. Shows the UX letting people override the setting

This is how I've _really_ wanted to do this, because I think it's better UX, and more clearly shows what is going on.

ref: https://github.com/nystudio107/craft-seomatic/issues/488

**Comment by geenious** [comment]
I think this would be great. I just got this ask from a client:

"Can you set the field to show the robot's value even if the field is set to the default value for all pages and templates?"

Specifically referring to the blank Robots dropdown. Even if it just said "Global default set"

**Comment by FreekVR** [comment]
+1 for this, would really love to show _somewhere_ for the entry-specific settings what the default is, if only for reference.

**Comment by LarsDol** [comment]
+1

**Comment by brianlarson** [comment]
Seems to me like the blank values should simply go away and just show whatever the default value is since that's what it is under the hood. I got confused because changing robots appeared as if it wasn't saving when changing from blank/empty to All. It also appeared as if Entity wasn't saving since it was also empty. Or simply put (default) after the value instead of it being blank.

**Comment by khalwat** [comment]
@brianlarson yeah I agree the UX here is not good. It's in the cards to get it addressed, sorry for that.

**Comment by brianlarson** [comment]
Not a big deal at all! Such a great plugin.

**Comment by johndwells** [comment]
I'm jumping in here to vote for an improvement. I had always thought that the SEO Settings field could _override_ whatever defaults have been set for the channel's Content Settings.

For me, I would be more than happy to see a simple lightswitch/toggle that either says: use the Content Settings for this entry, or let me set my own. I feel like this would probably be the simplest to implement, and be only minimally inconvenient to the editor (they might have to set up a bunch of the same switches & toggles just to override one field).

Unless I'm misunderstanding how to leverage the SEO Settings field + the Content Settings?

**Comment by matthewmrotter** [comment]
Client wants us to circle back around on this - any idea if it'll get implemented soon?

**Comment by khalwat** [comment]
> Client wants us to circle back around on this - any idea if it'll get implemented soon?

It's high on my list of new features, but bug fixes take priority

**Comment by khalwat** [comment]
> I'm jumping in here to vote for an improvement. I had always thought that the SEO Settings field could override whatever defaults have been set for the channel's Content Settings.

> For me, I would be more than happy to see a simple lightswitch/toggle that either says: use the Content Settings for this entry, or let me set my own. I feel like this would probably be the simplest to implement, and be only minimally inconvenient to the editor (they might have to set up a bunch of the same switches & toggles just to override one field).

Yep that's the idea... in addition to showing a preview of what it's set to currently, if you're not overriding it.

**Comment by khalwat** [comment]
So at _long last_ we're about ready to test out the new UX for this long-standing FR/issue.

The idea is that the SEO Settings field is a per-entry _override_ over what you've set in your Global SEO & Content SEO settings. But we've done a poor job of representing that from a UX point of view (with blank fields that confused people).

So now we have an explicit **(0 ) Override** lightswitch next to each field:

<img width="711" alt="Screen Shot 2021-08-11 at 6 28 58 PM" src="https://user-images.githubusercontent.com/7570798/129112036-0d2620c4-fecf-4ee3-888d-8167f5b0ab05.png">

With the Override toggle off, you see the inherited settings, in a disabled state. If you toggle the Override on, you get to choose what the overridden settings should be. Here's a move of it in action:

https://user-images.githubusercontent.com/7570798/129112037-57c98802-c7a6-471f-972d-7ee61cecbb8b.mov

I'm planning to make a version available to people who subscribe to this thread really soon, to test out and solicit feedback, if you're willing! Many thanks!

**Comment by engram-design** [comment]
This is excellent news, looks great, and makes it so much clearer (to clients) what's going on. We've had a few lately question SEO when they look at the field, as they're confused when it's "blank"

**Comment by brianlarson** [comment]
A killer improvement. Kudus! 🎈

**Comment by johndwells** [comment]
Yes! This is a perfect solution. I can't wait to share this with our clients - maybe via 3.7's new 
"what's new" HUD! 🚀

**Comment by khalwat** [comment]
Oh, good idea @johndwells -- a nice opportunity to try that functionality out.

**Comment by khalwat** [comment]
Feedback wanted:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.0”,
```
Then do a `composer clear-cache && composer update`
