### ISSUE TITLE
SEO Keywords not updating as expected

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#536]
Craft 3.3.20.1
SEOmatic 3.2.38

Using Content SEO the keywords in the template are not reflecting what they should.

The keywords meta tag always shows the Global SEO keywords not what is set for each section.

Currently testing with one section on the staging site, About Landing, and going to content SEO I set the SEO keywords source to either **from field** or **keywords from field** and select any field that is populated - this does not get reflected on the front end.

I also tried custom text and that did not update either.

Can provide login credentials to staging site if that will help.

**Comment by khalwat** [comment]
Have you tried clearing caches? I'm unable to replicate this locally.

Example, view this source of this page:

https://nystudio107.com/blog/using-the-craft-cms-graphql-api-on-the-frontend

```html
<meta name="keywords" content="graphql, craft, added, layer, gives, website, here&#039;s, formalized, headless, structured"> 
```

![Screen Shot 2020-01-22 at 12 41 58 PM](https://user-images.githubusercontent.com/7570798/72919039-beec0300-3d14-11ea-9202-fcb29e098bfa.png)

![Screen Shot 2020-01-22 at 12 42 41 PM](https://user-images.githubusercontent.com/7570798/72919054-c4494d80-3d14-11ea-9575-6b149f54783a.png)

**Comment by CreateSean** [comment]
So manually clearing the cache works.

However when I make an update to the settings I once again have to clear the cache

**Comment by khalwat** [comment]
So I don't know what cache this is being stored in... can you elaborate on your caching setup?

**Comment by CreateSean** [comment]
Up until last week we were using native caching but the task queue would never finish running so we switched to using the Cache Flag plugin and that resolved a number of issues. Was hoping that it would fix this  as well. however it did not.

When testing I cleared all cacheflag cache and that did not update the SEO keywords, it only updated when I cleared all native cache.

Hope this helps.

**Comment by khalwat** [comment]
Well, SEOmatic clears its caches whenever you change these settings, so it's not that. It must be some other caching layer somewhere.
