### ISSUE TITLE
Applying Content SEO to nested entries

### ISSUE THREAD

**Issue by martinsmith** [nystudio107/craft-seomatic#537]
We have a 'Structure' with nested entries and we're using Entry Types.  Under 'Content SEO' we can only see the Parents (Level 1), although SEOmatic does acknowledge there are X number of Entries "within" that Parent?  Is it not possible to apply SEO to the individual Entries?

**Comment by khalwat** [comment]
This was answered on Discord:

generally you'll set up the mappings in Content SEO, and be done with it. You specify sources to pull the SEO data from, and that's it. It'll "just work"

If you really truly want to be able to edit things on a per-entry basis (which generally I discourage) yep, that's what the SEO Settings field is for

The settings in Content SEO will apply to all of the entries in that structure, nested or not
