### ISSUE TITLE
data-vocabulary.org schema deprecated

### ISSUE THREAD

**Issue by mark-chief** [nystudio107/craft-seomatic#540]
Hi, dropping this here, not a bug just an FYI.

Keep awesoming.

v3.2.39

> Search Console has identified that your site is affected by 1 Breadcrumbs issues:
> Warnings are suggestions for improvement. Some warnings can enhance your appearance on Search; some might become errors in the future. The following warnings were found on your site:
> 
> data-vocabulary.org schema deprecated
> 
> We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

**Comment by khalwat** [comment]
Can you give me some more details on this? SEOmatic doesn't use data-vocabulary.org ?

**Comment by mark-chief** [comment]
You Sir, are absolutely correct!

There was a manually added Breadcrumb that included it. Sorry!
