### ISSUE TITLE
Social Preview appears in share when no entry url is defined but a preview target is created

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#541]
I have noticed that the Social Preview appears in share if I add a preview target to a section that doesn't have an entry uri or template.

The following is an example:
<img width="1592" alt="Screenshot 2020-01-23 at 11 37 32" src="https://user-images.githubusercontent.com/5698596/72981480-c377f080-3dd4-11ea-8d41-d4f9f911d19e.png">

Then on the actual entry the share shows the Social Preview:
<img width="1941" alt="Screenshot 2020-01-23 at 11 35 26" src="https://user-images.githubusercontent.com/5698596/72981500-d1c60c80-3dd4-11ea-8300-b1b83107191a.png">

However, this results in a blank screen when clicked. 

Is it possible to fix this so the social preview doesn't appear at all for pages without entry uri or templates?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6f2c078f8ace5f4600eff8f81715678b48bb7fbb
