### ISSUE TITLE
Social image preview not appearing in commerce products

### ISSUE THREAD

**Issue by kaspar-allenbach** [nystudio107/craft-seomatic#542]
1. The images on social media previews are no longer appearing

![Bildschirmfoto 2020-01-27 um 09 50 09](https://user-images.githubusercontent.com/762213/73160880-7785be00-40ea-11ea-8e35-7a8b1341a666.png)

2. The image is defined

![Bildschirmfoto 2020-01-27 um 09 51 11](https://user-images.githubusercontent.com/762213/73160938-984e1380-40ea-11ea-83ab-5600c4ba21e4.png)

3. In the console it says:

`TypeError: o is null  seomatic-tokens.js:23:4`

Craft CMS 3.3.20.1
seomatic: 3.2.39

**Comment by khalwat** [comment]
When you say "no longer" -- I assume they used to show up? What changed?

Also how are these configured? Via Content SEO or...?

**Comment by khalwat** [comment]
This should _also_ be fixed in https://github.com/nystudio107/craft-seomatic/commit/8a3fe885b35332194253f5dd014c3f804f43bcca

Let me know if it's not when 3.2.41 comes out, and I can re-open.

**Comment by kaspar-allenbach** [comment]
works nicely

**Comment by khalwat** [comment]
Thanks for following up! Glad it's working for you again.
