### ISSUE TITLE
[FR] SEO Images within Super Table

### ISSUE THREAD

**Issue by outline4** [nystudio107/craft-seomatic#543]
Hi, 

My setup is the following:  
I use a Matrix as a page builder, and within the matrix a Super Table field with images and captions for a jQuery image gallery. Those images are my clients portfolio images and the captions are rather important. 

<img width="824" alt="Bildschirmfoto 2020-01-27 um 22 29 53" src="https://user-images.githubusercontent.com/145828/73217077-8787b700-4157-11ea-8231-2cfdb5e9e01d.png">

I've tried to add a caption field on the assets within the super table, and configured it on "Image Sitemap Fields" within "Content SEO -> Sitemap". Cleared caches etc. But nothing shows up. 

How on earth can I get these images with captions into the sitemap.xml?  
Is Super Table even supported? 

Any help would be highly appreciated! 

Craft 3.3 and the latest SEOmatic. 

Thanks  
Stefan

**Comment by khalwat** [comment]
It looks like only Matrix blocks and SuperTable blocks are currently supported. I'm not sure how much work would be involved making SuperTable work as well, but can convert this into a FR

**Comment by khalwat** [comment]
turns out it wasn't too bad... added in https://github.com/nystudio107/craft-seomatic/commit/d1ee6afe39ed4425382e2173a9db3cf039d0fd02
