### ISSUE TITLE
Calling unknown method: craft\services\Gql::invalidateCaches()

### ISSUE THREAD

**Issue by eheiser** [nystudio107/craft-seomatic#546]
Currently on Craft CMS 3.3.11 and after updating SEOMatic to the latest version, any time I try to save an edit I get the above error. Any idea what's causing this?

![screenshot_02](https://user-images.githubusercontent.com/86934/73375667-67bdd380-42bc-11ea-9aca-838cebf6a53f.jpg)

**Comment by khalwat** [comment]
Can you update to the latest version of Craft CMS 3.3.x? My guess is they added this at some point, probably in 3.3.12 -> https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#3312---2019-10-22
