### ISSUE TITLE
Content settings are not displaying in web pages

### ISSUE THREAD

**Issue by scandella** [nystudio107/craft-seomatic#548]
Maybe I misunderstand the way SEOmatic works, but when I put some entry fields in SEO Title Source of the SEO content panel of some sections, the SEOmatic preview (like the Google one) of these entries reflect these settings. But when I look at the corresponding pages in the website, the metadata are everywhere the same: they reflect the Global SEO site settings, not the Content SEO settings.
I'm missing something? Should I put some SEOmatic's twig tags in my template?
Sorry for the confusion.

**Comment by khalwat** [comment]
@scandella you're not missing anything, it should automatically add the tags to your pages. Can you show me some screenshots of your settings?

**Comment by khalwat** [comment]
Will re-open if additional information is provided.
