### ISSUE TITLE
Google Product Feed

### ISSUE THREAD

**Issue by oddnavy** [nystudio107/craft-seomatic#549]
We're attempting to set up an automated feed for our Craft Commerce products to a Google Merchant account and are struggling to find where to configure some of the structured data.

It looks like we need to add [brand](https://support.google.com/merchants/answer/6324351) and [GTIN](https://support.google.com/merchants/answer/6324461).

I can see the properties in the  [Product model](nystudio107/craft-seomatic/src/models/jsonld/Product.php) but can't see anything in the documentation around how to set the values in the CMS and have them flow through to the structured data.

**Comment by khalwat** [comment]
There isn't a way to set them in the CMS, but you can set them via Twig. Here are some examples for you:

https://nystudio107.com/docs/seomatic/Using.html#json-ld-meta-object-functions-seomatic-jsonld

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

https://nystudio107.com/blog/tips-for-using-seomatic-effectively

**Comment by oddnavy** [comment]
Thanks @khalwat! 

For anyone else attempting the same thing, we copied `seomatic-config/productmeta/JsonLtdContainer.php` across into our craft `src/config` and added the following:

```php
'brand' => '{product.getDefaultVariant().brand}',
'gtin13' => '{product.getDefaultVariant().gtin}',
```
