### ISSUE TITLE
Use Facebook image from page content

### ISSUE THREAD

**Issue by Jed-Lehmann** [nystudio107/craft-seomatic#550]
I have a website where the author wants to link to a post on Facebook and select the image/s from that post as the image for the Facebook post. So each Facebook post would have a different image. 

I see the "Facebook OpenGraph Image Source", but it appears all of the options are choosing one generic image for all Facebook posts. 

How can we get around this? 

Thanks
Jed

**Comment by khalwat** [comment]
So I'm a little confused about your question, but if you want each entry to have its own Facebook image, you can either:

1) Set up Content SEO to pull the image from an Assets field in the entry (which can be different per entry)

2) Add an SEO Settings field where they can choose the image to use on a per-entry basis

Does this answer your question?

**Comment by Jed-Lehmann** [comment]
Thanks for the response. 

To clarify, I am looking to _not_ have the website determine the Facebook image, but let Facebook handle it (as they normally choose the right image). So I have changed the setting to “Custom image” and left the image selection blank. This seems to be working. 

Your option 1 would also work, but would require some more development for all the unique templates. I might go down that path in future.

**Comment by khalwat** [comment]
I see. So Facebook scrapes the page for images if no og:image is present. It just gives them more than one image to choose from based on images that are on the page.

You can leave it that way, or you can also provide a list of images for them to choose from via something like this:

https://github.com/nystudio107/craft-seomatic/issues/307#issuecomment-579051778
