### ISSUE TITLE
500 Server Error for Section Sitemap

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#551]
I'm encountering a 500 error for a single section sitemap.
Plugin has been updated to latest version. Cleared the caches.

**Comment by khalwat** [comment]
Is it a 500 error, or a 503 error?

Can you give me the relevant stack trace from the `storage/logs/queue.log` and/or `storage/logs/web.log`?

**Comment by ghost** [comment]
from web.log:

`Stack trace:
#0 /home/spfarchitect/craft_spfa_live/vendor/nystudio107/craft-seomatic/src/helpers/UrlHelper.php(68): craft\helpers\UrlHelper::isAbsoluteUrl(NULL)
#1 /home/spfarchitect/craft_spfa_live/vendor/nystudio107/craft-seomatic/src/models/SitemapTemplate.php(374): nystudio107\seomatic\helpers\UrlHelper::absoluteUrlWithProtocol(NULL)
#2 /home/spfarchitect/craft_spfa_live/vendor/nystudio107/craft-seomatic/src/models/SitemapTemplate.php(279): nystudio107\seomatic\models\SitemapTemplate->assetSitemapItem(Object(craft\elements\Asset), Object(nystudio107\seomatic\models\MetaBundle), Array)
#3 [internal function]: nystudio107\seomatic\models\SitemapTemplate->nystudio107\seomatic\models\{closure}(Object(yii\caching\FileCache))
#4 /home/spfarchitect/craft_spfa_live/vendor/yiisoft/yii2/caching/Cache.php(575): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#5 /home/spfarchitect/craft_spfa_live/vendor/nystudio107/craft-seomatic/src/models/SitemapTemplate.php(343): yii\caching\Cache->getOrSet('seomatic_sitema...', Object(Closure), NULL, Object(yii\caching\TagDependency))
#6 /home/spfarchitect/craft_spfa_live/vendor/nystudio107/craft-seomatic/src/services/Sitemaps.php(150): nystudio107\seomatic\models\SitemapTemplate->render(Array)
#7 /home/spfarchitect/craft_spfa_live/vendor/nystudio107/craft-seomatic/src/controllers/SitemapController.php(81): nystudio107\seomatic\services\Sitemaps->renderTemplate('SeomaticSitemap...', Array)
#8 [internal function]: nystudio107\seomatic\controllers\SitemapController->actionSitemap(1, 'section', 'news', 1)
#9 /home/spfarchitect/craft_spfa_live/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/spfarchitect/craft_spfa_live/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /home/spfarchitect/craft_spfa_live/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('sitemap', Array)
#12 /home/spfarchitect/craft_spfa_live/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('sitemap', Array)
#13 /home/spfarchitect/craft_spfa_live/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('seomatic/sitema...', Array)
#14 /home/spfarchitect/craft_spfa_live/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('seomatic/sitema...', Array)
#15 /home/spfarchitect/craft_spfa_live/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#16 /home/spfarchitect/craft_spfa_live/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /home/spfarchitect/craft_spfa_live/web/index.php(21): yii\base\Application->run()
#18 {main}
2020-02-05 19:34:27 [47.155.70.110][1][8a91a0449750ebb2963b633eee855696][info][application] $_GET = [
    'p' => 'sitemaps/1/section/news/1/sitemap.xml'
]`

**Comment by khalwat** [comment]
None of these line numbers are matching up... which makes me think you're running an old version of SEOmatic.

Update to the latest version of SEOmatic, this issue should be fixed. Basically, there's an asset that has `null` for a URI and older versions of SEOmatic didn't safeguard this.

Update to the latest SEOmatic and you should be good to go.
