### ISSUE TITLE
Users are still shown the dashboard without permission

### ISSUE THREAD

**Issue by darylknight** [nystudio107/craft-seomatic#553]
If you disable the Dashboard user permission, and a user clicks on SEOmatic in the sidebar, it still shows them the Dashboard. Could that be changed so they're shown the first available section they have access to?

**Comment by khalwat** [comment]
Curious someone would have access to something else, but not the Dashboard...

Fixed in https://github.com/nystudio107/craft-seomatic/commit/879e9c3b889992234c811d15e1628cc7897d200e

**Comment by darylknight** [comment]
Thanks! I know it's an edge case and it's not a big deal, just noticed it wasn't working as intended. 
I give the client access to update Site Identity so they can control their own information, but;
- I've set up SEO global defaults under Globals (So I handle social networks automatically and just give them an image field)
- Each content section has SEO fields on the entries, so I don't want them to be able to change how that's set up under Content SEO
- I can't give them access to the Tracking Code section, because any code on the site has to be GDPR/CCPA compliant and they'll break it
- I don't want them to access plugin settings
- The User Manual plugin, for some reason, has URLs which means SEOMatic wants to set SEO information for it and show it in the dashboard. It's an easy fix for me to just set it up under content SEO but it's what flagged me noticing that they could still see the dashboard with the permission off.
