### ISSUE TITLE
Ability to customize individual entries SEO title/desc meta

### ISSUE THREAD

**Issue by getpopulum** [nystudio107/craft-seomatic#554]
Is there a way to customize the SEO title/meta of each post, within the post? 

It seems like you can only update the Content Setting in settings, but there's no way to customize each post depending on different circumstances.

**Comment by khalwat** [comment]
I generally don't recommend doing this, because it's usually better to set up SEOmatic to pull from existing content that appears on the page -- but you can do it using an SEO Settings field:

https://nystudio107.com/docs/seomatic/Fields.html#seo-settings-field
