### ISSUE TITLE
[very minor] styling issues in 3.4

### ISSUE THREAD

**Issue by darylknight** [nystudio107/craft-seomatic#556]
Spacing of UI elements is a bit off in 3.4. Obviously very minor but flagging anyway!

![image](https://user-images.githubusercontent.com/1250017/74327931-b75cce80-4d95-11ea-8907-da685b33e6ce.png)

![image](https://user-images.githubusercontent.com/1250017/74327942-bb88ec00-4d95-11ea-88ff-de19625966c2.png)

**Comment by khalwat** [comment]
Huh. Interesting, thanks, I'll get it addressed.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/538cb67cdd1cbc27ca3531fc8a3b6c4a126d3edf
