### ISSUE TITLE
Alternate link incorrect href in {% paginate %}

### ISSUE THREAD

**Issue by mortscode** [nystudio107/craft-seomatic#557]
Issue where `seomatic.link.get('alternate')` tag is displaying the url w/o the `/p2`, `/p3`, etcetera appended to the string.

## Example:
For the url: `https://themodernproper.com/recipes/season/spring/p2`,
The links rendered are:
```
<link href="https://themodernproper.com/recipes/season/spring" rel="alternate" hreflang="x-default">
<link href="https://themodernproper.com/recipes/season/spring" rel="prev">
<link href="https://themodernproper.com/recipes/season/spring/p3" rel="next">
```
The "alternate" link should render the current page url (with the `/p2`) for its `href` attribute. The `prev` and `next` links seem to be rendering correctly.

### From main template:
```
{% set results = {
  section: 'postEntries',
  with: [
      ['featuredImage', {
        withTransforms: ['image800', 'image400', 'image200']
      }]
    ],
} %}

{% set entries = craft.entries(results) %}

{% include 'results/_posts-results' with entries.all %}
```
### in _posts-results partial:
```
{% set entries = entries.limit(18) %}

{% paginate entries as pageInfo, pageEntries %}
{% do seomatic.helper.paginate(pageInfo) %}

...
```

**Comment by khalwat** [comment]
This is actually the correct, desired result. For paginated pages the `hreflang` should point to the first unpaginated page.
