### ISSUE TITLE
Problem with icons in menu

### ISSUE THREAD

**Issue by samueljonasson** [nystudio107/craft-seomatic#558]
After upgrading to 3.4 the SEOmatic icon in the menu displays incorrectly

![image](https://user-images.githubusercontent.com/1074267/74428483-fd2a9d00-4e50-11ea-9ec4-cda6a21e02a1.png)

**Comment by khalwat** [comment]
This is going to end up being something with Craft or more likely your local setup. Try clearing all of your caches.

SEOmatic isn't in control of the display of these, not are there even icons there:

<img width="212" alt="Screen Shot 2020-02-13 at 7 28 31 AM" src="https://user-images.githubusercontent.com/7570798/74435457-7b2b7b80-4e32-11ea-8705-518393dcc7eb.png">

**Comment by samueljonasson** [comment]
I will have a look.  I did already try to clear the cache but it did not help.  I assumed this had something to do with SEOmatic because the icon there in front of the SEOmatic title has an absolute path to my G:\ dev drive.  The other icons in the menu don't.

**Comment by khalwat** [comment]
I've not seen anyone else have this issue, which I'd expect to hear about fairly quickly if it was a universal problem.

Also based on what you said, I'm assuming it used to work, but now no longer does after upgrading to Craft 3.4? This would make me strongly thing it's something local or an issue with Craft 3.4

**Comment by samueljonasson** [comment]
I believe you are correct.  I just don't understand why this is only happening on the SEOmatic plugin in the control panel.  It did work before so it is fair to assume that something is wrong with Craft or the update procedure.  

I solved the issue temporarily by replacing the icon using the Control Panel Nav plugin.

I really like SEOmatic by the way.  Thank you for your effort.
