### ISSUE TITLE
Sitemap Limit breaks Calendar sitemap

### ISSUE THREAD

**Issue by its-me-mario** [nystudio107/craft-seomatic#559]
In Content SEO, if we go to a (Solespace) Calendar and change the Sitemap limit from None to 1000, then back to None, the sitemap disappears.
![Screen Shot 2020-02-13 at 4 22 34 PM](https://user-images.githubusercontent.com/788170/74487607-25c88c00-4e7d-11ea-918f-2e45564167e0.png)

We have multiple sites that have this same issue.  The only way to get it back is to set the limit to 1000. This also doesn't seem to be an issue with any other section.

We're using Craft 3.3.20, SEOmatic 3.2.38. With most of these sites, we're typically working with 100-300 event entries.

**Comment by khalwat** [comment]
On the page with the malformed XML, if you do View Source do you see anything?

Can you have a look at your `storage/logs/queue.log` do you see any errors?

Are you sure it's not just re-generating the sitemap?

**Comment by spib** [comment]
@khalwat In SeoEvent.php `sitemapElementsQuery()` the `$metaBundle->metaSitemapVars->sitemapLimit` field is an empty string when set to 'None' rather than `null` which seems to be the problem.

**Comment by its-me-mario** [comment]
<img width="677" alt="Screen Shot 2020-02-14 at 8 18 40 AM" src="https://user-images.githubusercontent.com/788170/74543798-43d8cf80-4f03-11ea-808f-c18337e1f4c4.png">

@spib has better details on this issue but the logs didn't have any errors. I see that it is regenerating the sitemap because the xml changes each time I change the limit from None to anything else.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6ae4b6c31a161362d624708eb6305d4a9c145ab4

You can set your `semver` to `dev-develop` to try it out now if you like.
