### ISSUE TITLE
seomatic.jsonLd.create doesn't allow prop values of 0 or "0"

### ISSUE THREAD

**Issue by robmcfadden** [nystudio107/craft-seomatic#562]
This works fine when there's a rating, but remove the props altogether when there's not. Also tried with "0".

```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{% set aggregateRating = seomatic.jsonLd.create({
  'type': 'AggregateRating',
  'bestRating': 5,
  'ratingValue': 0,
  'reviewCount': 0,
}, false) %}
{% do mainEntity.aggregateRating(aggregateRating) %}
```

**Comment by khalwat** [comment]
If I had to guess, it's probably because this value is treated as 'empty' and so is pruned out.

Is this creating a problem for you?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/e50c2b802dc55a4ea2d58903964a1e6f275a58d9

You can set your semver to `dev-develop` to test it out if you like.
