### ISSUE TITLE
Wrong (hreflang) Alternate hrefs in a multisite setup?

### ISSUE THREAD

**Issue by Jones-S** [nystudio107/craft-seomatic#565]
Hey there

Sorry to bother you again.
I have the following setup: Multisite (English and German) where I defined a `base Url` specifically for both of them:

<img width="1265" alt="Screenshot 2020-02-25 at 17 03 37" src="https://user-images.githubusercontent.com/7059580/75265230-e2610c80-57f0-11ea-839b-61e4dc15fde1.png">

First I thought I would have to define the `base Url` for the german page like
`localhost:3000/de` but because I define the URI pattern later on in my sections, I could not do that because it would repeat itself...

<img width="887" alt="Screenshot 2020-02-25 at 17 07 32" src="https://user-images.githubusercontent.com/7059580/75265588-69ae8000-57f1-11ea-9bf6-842266246eae.png">

Here you see the metaLinkContainer values if I set the baseUrl with the language directory (e.g. `localhost:3000/de` while having the uri specified within the section's settings to also contain a language:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/7059580/75265445-34099700-57f1-11ea-8158-e4c2abc1bc65.png">
(See the `de/de/home`...)

So as I said I just set the `baseUrl` for both the sites to the root of the domain.
But now I have this weird results within the seomatic return values:

I am on the page 
`http://localhost:3000/de` and I get the following seomatic values:
<img width="814" alt="image" src="https://user-images.githubusercontent.com/7059580/75265946-f35e4d80-57f1-11ea-8da3-ca374da247cd.png">

If I am on the default page `http://localhost:3000` (english) I get the correct results:
<img width="781" alt="image" src="https://user-images.githubusercontent.com/7059580/75266014-0a9d3b00-57f2-11ea-8c83-e3c4383fd43a.png">

Now my question: Is this all how it is supposed to run?
Why is the first case showing the same value three times?
And how can I fix this?

Thank you in advance.

PS: versions:
```
"craftcms/cms": "3.4.8",
"nystudio107/craft-seomatic": "^3.2.43",
```
Also I have to mention that I work with a headless craft installation...

Edit:
I then thought, well maybe I need to remove the `/de` part within my section and move it to the `baseUrl` of the second site:
So I have a `base URL` of `localhost:3000/de` for the german page and my sections look like this:
<img width="877" alt="Screenshot 2020-02-25 at 17 43 02" src="https://user-images.githubusercontent.com/7059580/75267275-5356f300-57f6-11ea-8cee-d4690a86eb58.png">

But still I would get weird results:
On `localhost:3000`
<img width="791" alt="image" src="https://user-images.githubusercontent.com/7059580/75267485-9749f800-57f6-11ea-908f-14d31aa14f5a.png">

and on `localhost3000/de`
<img width="805" alt="image" src="https://user-images.githubusercontent.com/7059580/75267701-ded08400-57f6-11ea-8f3f-6b2614632cab.png">

**Comment by khalwat** [comment]
Are your sites in the same site group as per: https://nystudio107.com/docs/seomatic/Technologies.html#multi-site-language-locale-support

?

**Comment by Jones-S** [comment]
Yes they are in the same site group.

**Comment by khalwat** [comment]
So SEOmatic is being used on a number of multi-site setups. I'm not sure exactly what is going on with yours, but in general, it works correctly, and generates the appropriate hreflang URLs as far as I'm aware.

Have you had a look at the Craft docs on setting up a multi-site?

https://docs.craftcms.com/v3/sites.html

Also here's a good video on the subject:

https://www.youtube.com/watch?v=i4koSgkv014

In general, the site URL should be the unique part, e.g. one of the following:

https://examplegerman.com/
https://german.example.com/
https://example.com/de

And you would not include the localization in the entry format, because that'd require replicating it each time for each Section.

**Comment by Jones-S** [comment]
Thank you for your input on that. I checked the resources you provided and I can only confirm that everything is setup correctly. I have two sites in a group, I can switch between the sites when editing entries (if fields are translatable) etc.

I see the point that the site should include the unique part, and that's what I corrected yesterday already.

I did found out about something else though:
If I query just a standard page like

```
{
  "siteId": 2,
  "uri": "meine-deutsche-seite"
}
```
⚠️ I am leaving away the `/de` part!
(I get the pages result with either `/de/meine-deutsche-seite` or `meine-deutsche-seite`)

Then I get correct hreflang results (after all I really only have to query the slug and not the uri?):
<img width="752" alt="image" src="https://user-images.githubusercontent.com/7059580/75325353-f81a1480-5878-11ea-84a4-02baec0f0cdc.png">

But when I query my home page, which has the same slug `home` for both my German and my English page:

```
{
  "siteId": 2, // == the German version
  "uri": "home" 
}
```
<img width="666" alt="image" src="https://user-images.githubusercontent.com/7059580/75325744-a32ace00-5879-11ea-85b8-953020fe4007.png">

It does not matter if I query
`"uri": "home"` or `"uri": "/home"` or `"uri": "/de/home"` or `"uri": "de/home"`
I would always get the same results listed above.

(Of course If I switch to `siteId: 1`, my default English page, I would only get correct results with `"uri": "/home"` or "uri": "home".

So I think it has something to do with slugs and uris...
It also seems confusing (if the fact that it is indeed a `uri`) that I get the correct SEO for my German page when querying:
```
{
  "siteId": 2,
  "uri": "/home"
}
```
I would expect to not get anything because within the site with id = `2` there is no uri `/home` – only `/de/home`...

Thank you for your input.
cheers

**Comment by khalwat** [comment]
So I'm not 100% sure I'm understanding you correctly, however you state:

> I would expect to not get anything because within the site with id = 2 there is no uri /home – only /de/home...

That's not how Craft works. The `/de/` part isn't part of the URI, it's part of the site URL.

So when you pass in the URI, you do it _without_ any country code prefix, and using the `siteId` to specify which site.

Does this answer your issue?

**Comment by Jones-S** [comment]
Alright. I see. Nonetheless it leaves me with the weird `/de/de/home` I am getting in either case. (I think it is linked to the fact that both sites (`siteId` 1 & 2) have the slug (which is in this case also the `uri`): _home_).

**Comment by khalwat** [comment]
It looks to me like you have `de` both as part of the site URL _and_ as part of the entry's URI -- if this is correct, that's why it'd be duplicated like that.

You do not want it as part of the entry's URI:

<img width="887" alt="Screenshot 2020-02-25 at 17 07 32" src="https://user-images.githubusercontent.com/7059580/75265588-69ae8000-57f1-11ea-9bf6-842266246eae.png">

**Comment by Jones-S** [comment]
Unfortunately no.
As I said, I only changed the place of the `de`
> I see the point that the site should include the unique part, and that's what I corrected yesterday already.

So right now I have:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/7059580/75390075-f0458900-58e7-11ea-898a-01870d79f994.png">
And:
<img width="1431" alt="Screenshot 2020-02-26 at 22 52 47" src="https://user-images.githubusercontent.com/7059580/75391700-e1aca100-58ea-11ea-8de0-44efaaf48a1c.png">

If I then query this:
<img width="963" alt="Screenshot 2020-02-26 at 22 56 53" src="https://user-images.githubusercontent.com/7059580/75391989-73b4a980-58eb-11ea-93ba-9d803f55de3b.png">
I get this weird double `/de/de`

I have clearly not set the `de` in both places (site and section uri settings).
I really hope, I am not totally missing something here. You must think I'm a total douche repeating myself 😅 .

I then thought, maybe it is important that the site has a `/` at the end, so I changed things to:
<img width="218" alt="image" src="https://user-images.githubusercontent.com/7059580/75392205-d0b05f80-58eb-11ea-813a-8b7ae52512a2.png">
(The default page has `/` set as `base Url` which results in `localhost:3000` without a slash).

But still i would get this weird double `/de/de` for the translated page...

**Comment by Jones-S** [comment]
Oh jeez, I think I know what it is.
This is very stupid.
Although the slug on the translated German page is showing this:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/7059580/75392370-2b49bb80-58ec-11ea-83a1-cf069838e1ea.png">

Somehow it must have had a wrong (outdated) entry in the database.
So just **saving** the German entry **again**, would bring me the seomatic alternate links from

`localhost:3000/de/de/seite-1` to `localhost:3000/de/seite-1`

Thanks for standing by 😅. At least I have the hope that this may help somebody one day...
Cheers``

**Comment by khalwat** [comment]
Ahhh, glad you have it sorted @Jones-S !
