### ISSUE TITLE
GraphQL : Wrong canonical URLs in metaLinkContainer

### ISSUE THREAD

**Issue by denisyilmaz** [nystudio107/craft-seomatic#567]
Thanks for adding the support for site handle in GraphQL.
Unfortunately there is still a bug with the metaLinkContainer field. It was there before `3.2.45` as well. I hoped this would be resolved by the latest update.

```gql
seomatic(uri: $uri, site: $lang, asArray: false) {
   metaLinkContainer
}
```

When querying for a page of type `Single` that is not the default the default site (ex. handle `site_de`, the metaLinkContainer **correctly** retrieves the canonical links for the other languages.

```
"metaLinkContainer": "<link href=\"http://localhost/de/german-uri\" rel=\"canonical\"><link href=\"http://localhost/de/\" rel=\"home\"><link href=\"http://localhost/en/english-uri\" rel=\"alternate\" hreflang=\"en\"><link href=\"http://localhost/de/german-uri\" rel=\"alternate\" hreflang=\"x-default\"><link href=\"http://localhost/de/german-uri\" rel=\"alternate\" hreflang=\"de\">"
```

but when querying for the same page in the default site language (ex. handle `site_en`), the metaLinkContainer retrieves the english URI for all other languages:

```
"metaLinkContainer": "<link href=\"http://localhost/en/english-uri\" rel=\"canonical\"><link href=\"http://localhost/en/\" rel=\"home\"><link href=\"http://localhost/en/english-uri\" rel=\"alternate\" hreflang=\"en\"><link href=\"http://localhost/de/english-uri\" rel=\"alternate\" hreflang=\"x-default\"><link href=\"http://localhost/de/english-uri\" rel=\"alternate\" hreflang=\"de\">"
```
ex.: `<link href=\"http://localhost/de/english-uri\" rel=\"alternate\" hreflang=\"de\">`

`SEOMatic 3.2.45`
`CraftCMS 3.4.8`

**Comment by khalwat** [comment]
I will have a look, this is very strange that it works for non-default sites, but does not work for the default site.

**Comment by denisyilmaz** [comment]
I just checked and switched the default page and have to correct myself. The behavior is exactly the other way around:

The default language correctly returns the corresponding alternate links, but the non default page only returns the slug of its own language for all other languages.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/7fc82c9acf47c4a012132c472f23641d51a17cee

You can test it by setting your semver to: `dev-develop` and doing a `composer update`

lmk!

**Comment by denisyilmaz** [comment]
I updated and everything works as expected. thanks a lot!
