### ISSUE TITLE
seomatic.site.creator.genericUrl not working

### ISSUE THREAD

**Issue by ryanmwc** [nystudio107/craft-seomatic#568]
When I view my generated humans.txt file, I see `URL: {{ siteUrl }}` verbatim in the text under `/* TEAM */`, so it appears that `{{ seomatic.site.creator.genericUrl }}` in the "Humans.txt Template" field in the CP isn't outputting the actual site url, just the Twig code.

**Comment by khalwat** [comment]
So I just tested this, and am unable to reproduce it. Can you ensure that there isn't some caching layer or physical `humans.txt` file that is present on the server?

**Comment by khalwat** [comment]
Will re-open if more info is provided
