### ISSUE TITLE
Preview is not showing. 

### ISSUE THREAD

**Issue by circa42** [nystudio107/craft-seomatic#569]
I've got a SEO image field and have indicated the source field to be that same field in General settings. I've also tested "Same as ..." and "From Asset Field..." in the Twitter/FB settings and nothing seems to allow me to preview the image. 

Upon save, the image still doesn't appear. In the Share » Social Media Preview also doesn't show. 
<img width="1824" alt="n3QbUZ" src="https://user-images.githubusercontent.com/1124514/75721074-8b45b680-5c8c-11ea-9a6d-514f0570f1c8.png">

**Comment by khalwat** [comment]
What are your Twitter and Facebook settings for this Section's Content SEO?

**Comment by khalwat** [comment]
Will re-open if more info is provided
