### ISSUE TITLE
No Facebook Profile ID has been set. Set it here.

### ISSUE THREAD

**Issue by mark-chief** [nystudio107/craft-seomatic#57]
'No Facebook Profile ID has been set. Set it here.'

This message appears in the side column of all entries when there is no Facebook Profile ID set. Not all websites/companies are suitable for facebook and will see this each time they load an entry.
<img width="249" alt="screen shot 2018-04-04 at 12 26 41" src="https://user-images.githubusercontent.com/18699249/38305102-7fc825e0-3803-11e8-97fd-1d75a0451385.png">

Nice be able to hide this, or show that warning on the Social Media Settings page instead.

**Comment by khalwat** [comment]
hmmmm. Yeah I think I agree with you.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/4e2953d1eb11fa68d9dbf870ba4413050826a757
