### ISSUE TITLE
FR: Add multiple departments for opening hours

### ISSUE THREAD

**Issue by TomDeSmet** [nystudio107/craft-seomatic#571]
As the title says, it would be nice to be able to add and output multiple departments with their own opening hours.

https://search.google.com/test/rich-results?utm_campaign=devsite&utm_medium=jsonld&utm_source=local-business

**Comment by khalwat** [comment]
This is something you can do, but you'd need to do it via the Twig API: https://nystudio107.com/docs/seomatic/Using.html#twig-templating
