### ISSUE TITLE
My og:image and twitter:image are not picking up passed parameters

### ISSUE THREAD

**Issue by webtrend** [nystudio107/craft-seomatic#575]
I am passing the seo image to the page in question. This is the code in my head section
`{% if imageUrl is defined %}
    {% do seomatic.meta.seoImage(imageUrl) %}
{% endif %}`

However, both og:image and twitter:image meta values are showing the Global values instead of `imgeUrl` 
Can you tell me what I am doing incorrectly?

**Comment by khalwat** [comment]
So you actually need to set the ogImage and twitterImage yourself as well, they don't automatically propagate down, to allow for developers who want separate images for each.

More here: https://github.com/nystudio107/craft-seomatic/issues/253
