### ISSUE TITLE
SEO Description Source does not convert html text to plain text as it should.

### ISSUE THREAD

**Issue by gertst** [nystudio107/craft-seomatic#576]
When choosing a Redactor field as source for the SEO Description Source, the html text has issues to convert it to the plain text that is used in the SEO fields.

Example: 
```
<h2>My title</h2>
<p>My paragraph</p>
```
has no space between the elements when converted:
`My titleMy paragraph`

**Comment by khalwat** [comment]
It probably should convert newlines to spaces

**Comment by gertst** [comment]
That would already be better, but will not be enough:
List items are not starting on a next line in Redactor HTML and will still miss a space if you only convert newlines to spaces.
Eg:
`<ul><li>item 1</li><li>item 2</li></ul>`
Ideally, ul and ol lists should be prefixed with a dash or number. But a space would be a good start ;-)

Thanks for taking care!

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/88de8d6361c2357eedeae164f6005edce8f8594b
