### ISSUE TITLE
GraphQL: Canonical link is not determined using the site handle for multi-site setups

### ISSUE THREAD

**Issue by OscarBarrett** [nystudio107/craft-seomatic#577]
On a multi-site project, we are making server-side GraphQL requests for the SEOmatic metadata. We are communicating to Craft via an internal IP with no hostname and providing a site handle to the query.

SEOmatic falls back to the default site when generating the canonical (and author) URLs and does not take the site handle provided into account.
The `home` meta link does use the correct domain.

There is the siteUrl override in the Global Settings which hints at this being deliberate, but that override can't be customised per site.

Is there another way to get correct domain in there as defined for the site?

**Comment by khalwat** [comment]
Can you show me some code so I can see exactly what you're doing?

**Comment by OscarBarrett** [comment]
I've done some further testing and it actually looks like it uses the server name/IP that the request came from.

For example, if you have two sites set up with their own Base URLs:
![image](https://user-images.githubusercontent.com/3511332/76860811-973d9500-6896-11ea-83d3-9dd93e461fa8.png)


And the following SEOmatic settings:
- `Global SEO -> General -> Canonical URL` set to the default (`{seomatic.helper.safeCanonicalUrl()}`)
- `Global SEO -> Humans` enabled
- `Plugin Settings -> Site URL Override` unset

GraphQL returns the following

```bash
curl -XPOST "127.0.0.1/api" -H "Content-Type: application/graphql" -d '
{
  seomatic(uri: "/", site: "site1") {
    metaLinkContainer
  }
}'
```

```json
{
  "data": {
    "seomatic": {
      "metaLinkContainer": "<link href=\"http://127.0.0.1/\" rel=\"canonical\"><link href=\"http://site1.localhost/\" rel=\"home\"><link type=\"text/plain\" href=\"http://127.0.0.1/humans.txt\" rel=\"author\"><link href=\"http://site2.localhost/\" rel=\"alternate\" hreflang=\"en\"><link href=\"http://site1.localhost/\" rel=\"alternate\" hreflang=\"x-default\"><link href=\"http://site1.localhost/\" rel=\"alternate\" hreflang=\"en\">"
    }
  }
}
```

--------

```bash
curl -XPOST "127.0.0.1/api" -H "Content-Type: application/graphql" -d '
{
  seomatic(uri: "/", site: "site2") {
    metaLinkContainer
  }
}'
```

```json
{
  "data": {
    "seomatic": {
      "metaLinkContainer": "<link href=\"http://127.0.0.1/\" rel=\"canonical\"><link href=\"http://site2.localhost/\" rel=\"home\"><link type=\"text/plain\" href=\"http://127.0.0.1/humans.txt\" rel=\"author\"><link href=\"http://site2.localhost/\" rel=\"alternate\" hreflang=\"en\"><link href=\"http://site1.localhost/\" rel=\"alternate\" hreflang=\"x-default\"><link href=\"http://site1.localhost/\" rel=\"alternate\" hreflang=\"en\">"
    }
  }
}
```

As can be seen, the canonical and author meta links use the IP address. All other meta links use the base URL as defined for the site. Requests from the GraphQL explorer will use the hostname that you accessed the CP from.

**Comment by khalwat** [comment]
Having a look at this to see if I can't figure out what's going on here this week.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/e3dd97ff7cf79939d1235a6add700037752ae88f

**Comment by OscarBarrett** [comment]
Thanks!
