### ISSUE TITLE
Processing large sitemaps uses a lot of memory and can fail

### ISSUE THREAD

**Issue by Mosnar** [nystudio107/craft-seomatic#578]
On one site in particular, I have a little over 5000 product pages alone. I limit my queue to 512MB and found that this limit was being hit. I'm able to succeed in generating the sitemap if I run it manually via SSH with no memory limit and regenerate only that section; however, I suspect regenerating all sections would have negative results.

On my smaller staging environment, I don't even get half-way through generating the products sitemap before mmap blows up:
```
mmap() failed: [12] Cannot allocate memory
bash: line 1: 25899 Segmentation fault      php /var/app/current/craft seomatic/sitemap/generate --handle products
```

After a little tracing, I think some of this has to do with Yii's logging - in particular, the FileTarget class implodes the log messages before writing them:
https://github.com/yiisoft/yii2/blob/master/framework/log/FileTarget.php#L109

When I attempt to process the entire sitemap via CLI on my smaller staging server, I eventually run into this error:
```
[..]
Processing element 3003/5225 - ***
Processing element 3004/5225 - ***
Processing element 3005/5225 - ***
Processing element 3006/5225 - ***
Processing element 3007/5225 - ***
Processing element 3008/5225 - ***
Processing element 3009/5225 - ***
Processing element 3010/5225 - ***

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal Error 'yii\base\ErrorException' with message 'Out of memory (allocated 639635456) (tried to allocate 3680455 bytes)'

in /var/app/current/vendor/yiisoft/yii2/log/FileTarget.php:107

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
```

**Comment by khalwat** [comment]
I'm not sure what to do here other than disable logging during the sitemap generation, which seems like it might be a bad idea?

Can you just up the memory limit or run the job queue in a context where there is no memory limit, ala: https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms

?

**Comment by Mosnar** [comment]
We handled this offline in Discord and came up with https://github.com/nystudio107/craft-seomatic/pull/583

**Comment by khalwat** [comment]
There ain't no question who the man is!

Thanks @Mosnar -- rolling it into 3.2.48 as I type.
