### ISSUE TITLE
ArgumentCountError after saving Global Settings

### ISSUE THREAD

**Issue by mark-chief** [nystudio107/craft-seomatic#58]
This occurred when I saved the Global Settings page (I do not think all the fields were filled in)

I am now unable to access the page`http://domain.com/admin/seomatic/global`, and I am unable to access any entries that have the SEOmatic field after saving them.

```Too few arguments to function nystudio107\seomatic\services\Helper::extractTextFromField(), 0 passed in /srv/users/serverpilot/apps/site/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1605 and exactly 1 expected```

Full Stack trace: https://pastebin.com/nEGJJx25

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/350b4bb56a9ef763610f6318e210627c315d6959
