### ISSUE TITLE
Hreflang disappeared after the update

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft-seomatic#580]
Hello.
After updating Seomatic from v3.2.42 to v3.2.47 hreflang tags are dissapeared.

**Before updating:**

![before2](https://user-images.githubusercontent.com/496132/76684906-a9ae9900-6620-11ea-84ef-8dc871036c27.jpg)

**After:**

![after2](https://user-images.githubusercontent.com/496132/76684939-f72b0600-6620-11ea-845b-8c04dfd80592.jpg)

Steps to reproduce:
1. Update Seomatic

Craft Pro 3.4.9
SEOmatic 3.2.42
SEOmatic 3.2.47

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/992d0352f495ef6a9800c68150b2aa60b19c67ea

You can update by changing your semver to: `dev-develop`

lmk how you go!

**Comment by khalwat** [comment]
I just double-checked this with 3.2.48 and the `hreflang` is appearing. Make sure that your elements are enabled for all sites.

**Comment by umkasanki** [comment]
Ok, Thanks. I'll check it

**Comment by umkasanki** [comment]
Hello @khalwat .
I tried updating my site and the Seomatic plugin. I also tried installing the Seomatic plugin on the newly installed site. In both cases, the site uses 1 language and the `<link href="https://site.co/" rel="alternate" hreflang="x-default">` tag is missing. The hreflang tag only appears if I add additional languages.

1 language:
![1-lang](https://user-images.githubusercontent.com/496132/77232354-95831280-6bb1-11ea-82ea-e5e0461583cf.png)

Multiple languages:
![2-lang](https://user-images.githubusercontent.com/496132/77232364-a6cc1f00-6bb1-11ea-8995-5907461e1222.png)

My Seomatic setting's:
![изображение](https://user-images.githubusercontent.com/496132/77232379-c19e9380-6bb1-11ea-8a83-3d0b2cc6d5a7.png)

Maybe I made a mistake in configuring the plugin???
But earlier, the `<link href="https://site.co/" rel="alternate" hreflang="x-default">`  tag was displayed by default, with the same settings ...

**Comment by karensg** [comment]
@khalwat,
I see in the code indeed that you need to have at least two sites to have the `x-default` included:
https://github.com/nystudio107/craft-seomatic/blob/82f4a25b28fd622393da6592dc9e5ccee7fc5be3/src/helpers/DynamicMeta.php#L454

I think that it should be included for sites with only 1 language as well: https://support.google.com/webmasters/answer/189077

This is the commit where it went wrong, I believe:
https://github.com/nystudio107/craft-seomatic/commit/0e5ceb5b95655244f43889009a54aa06947950ad

**Comment by khalwat** [comment]
@karensg I looked at the document you referenced, but I don't see anything to indicate that if there is only one version of a page, that an `x-default` tag should be included for it?

> Use the x-default tag for unmatched languages
> 
> The reserved value hreflang="x-default" is used when no other language/region matches the user's browser setting. This value is optional, but recommended, as a way for you to control the page when no languages match. A good use is to target your site's homepage where there is a clickable map that enables the user to select their country.

> Consider adding a fallback page for unmatched languages, especially on language/country selectors or auto-redirecting homepages. Use the the x-default value:
<link rel="alternate" href="http://example.com/" hreflang="x-default" />

Neither of these indicate this to me?

The point of `x-default` is to tell Google what page to use if the browser's chosen language doesn't match any of the languages the page is localized in. If there's only one page, there isn't a default... it's the only one.

**Comment by karensg** [comment]
You are right, thanks for looking in to that.
