### ISSUE TITLE
Site URL Override and aliases

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-seomatic#585]
The "Site URL Override" field in Plugin Settings has a couple of issues. It doesn't seem to parse aliases or environment variables when generating sitemaps. If you set that field to an environment variable or alias and save the plugin settings, then view the sitemap, it displays the alias/variable in the URLs as a string.

The other issue isn't a big deal, but the field doesn't display aliases in autocomplete like it does for environment variables.

**Comment by khalwat** [comment]
Yep you're right, this field doesn't allow for aliases/environment variables, and it probably should

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/5db6a377e0da8dd3884e19d49474c04b1604d36e & https://github.com/nystudio107/craft-seomatic/commit/933e24772c3d48ab0aec10579bf0fe5ca0f44d61
