### ISSUE TITLE
Best way to support new eventAttendanceMode from Google for Events?

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft-seomatic#586]
Google has added several new event data types: 

> On March 17, 2020, we added several optional properties: eventStatus, eventAttendanceMode, and previousStartDate. Due to COVID-19, we encourage you to add these new properties so people can understand the status of your event and how they can attend.

Any guidance on the best way to integrate this? I'm guessing a custom status and injecting the metadata manually?

Just thought this might be helpful for others if they are getting Search Console Errors about these new properties.

**Comment by khalwat** [comment]
The `eventStatus` property already exists:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/jsonld/Event.php#L184

So you'd just need to add it to the `mainEntityOfPage` the same way you would any other, via Twig. A bunch of examples:

https://nystudio107.com/docs/seomatic/Using.html#json-ld-meta-object-functions-seomatic-jsonld

https://nystudio107.com/blog/tips-for-using-seomatic-effectively

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

If you need something more specific, let me know!

**Comment by jonlongnecker** [comment]
What about `eventAttendanceMode` and `previousStartDate`? I'm specifically getting Console errors about `eventAttendanceMode.` Can I just make a custom field and pass that through the same way or does SEOMatic need to add support for it first?

**Comment by khalwat** [comment]
`previousStartDate` exists already: https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/jsonld/Event.php#L255

`eventAttendanceMode` I just added: https://github.com/nystudio107/craft-seomatic/commit/5e3f4b444ed9c1e2fe9182a7f76b6653ecdda657

**Comment by jonlongnecker** [comment]
In implementing this I'm running into what may be a bug. I'm trying to add the `VirtualLocation` type:

````
{% set locationRenderedJsonLd = seomatic.jsonLd.create({
    '@type': "VirtualLocation",
    'url': 'https://test.com'
}, false) %}
````

But it keeps spitting out:

````
"location": {
     "@type": "Thing",
     "url": "https://test.com"
},
````

Not sure where "Thing" is coming from when I'm specifically setting it as `VirtualLocation`?

**Comment by khalwat** [comment]
Ah man I think there was a fault merge, hang on a tick

**Comment by khalwat** [comment]
Nope, there wasn't, it's there:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/jsonld/VirtualLocation.php

**Comment by khalwat** [comment]
Yeah it all works, but you should leave the `@` off of `type`:

```twig
{% set locationRenderedJsonLd = seomatic.jsonLd.create({
    'type': "VirtualLocation",
    'url': 'https://test.com'
}, false) %}
```

**Comment by jonlongnecker** [comment]
Huh, that's weird. I had to use `@type` for the address version of this. I guess the online location is sort of up a level higher than that one.

**Comment by khalwat** [comment]
You shouldn't ever have to use `@type` unless you aren't instantiating a JSON-LD object.

However, I probably should make it handle the case where `@type` is passed in tho. https://github.com/nystudio107/craft-seomatic/commit/91597e6a064fea23e8200aaa372d02fd14507168
