### ISSUE TITLE
Pinterest Preview Settings

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft-seomatic#587]
I noticed you can turn on a Pinterest preview with SEOMatic, but there aren't any options to set specific settings for Pinterest itself. For example, generally your Pinterest image will be a completely different size and ratio than other social sharing images (much more vertical). 

Right now it just pulls the main featured image that is shared by all other social networks.

I'd love to see an option to be able to set a specific field for the main Pinterest image via content settings.

**Comment by khalwat** [comment]
There's no way to do this that I'm aware of, because Pinterest just grabs the image from the `og:image` 

Am I missing something? How are you setting the Pinterest sharing image?

**Comment by jonlongnecker** [comment]
Yeah I guess Pinterest is kind of weird that way in that it allows you to grab from all images instead of just one. Works backwards a bit.

Right now I have a custom field where you can upload a Pinterest image, and it's visually hidden at the top of the page. So when you invoke the Pinterest modal it's the first image that shows up. But it's not attached to the main meta tag. 

Sounds like I just need to turn off the Pinterest preview in my case since you can't set an image separately from Facebook.

**Comment by khalwat** [comment]
How are you tagging that first image? Anything special that SEOmatic could potentially look for?

**Comment by jonlongnecker** [comment]
No it's just the first image at the top of the page. [This](https://tinyshinyhome.com/kids-favorite-books-games) is a good example of an article we just posted. It's hidden when viewing the page, but if you use the Pinterest button at the bottom or browser extension it shows up as the first option.

I'm not sure there's anything SEOMatic can do here atm...

<img width="1323" alt="Screenshot 2020-03-27 10 53 57" src="https://user-images.githubusercontent.com/2390/77780237-486fc800-7019-11ea-9431-a27547e8bb1d.png">
<img width="1320" alt="Screenshot 2020-03-27 10 53 46" src="https://user-images.githubusercontent.com/2390/77780257-502f6c80-7019-11ea-9920-888ff452f01a.png">
