### ISSUE TITLE
SEOmatic metadata caches, Yii debug toolbar, and PHP memory exhausted

### ISSUE THREAD

**Issue by zsackett42** [nystudio107/craft-seomatic#588]
Context:

Our project has a "Basic Page" section and entry type. The field layout includes an "SEO Settings" field. Upon trying to add or remove fields from its field layout, we encounter "PHP Fatal error: memory size exhausted" consistently. The behavior does not occur on other entry types. 

After troubleshooting and debugging we've discovered that clearing the SEOmatic metadata caches _or_ disabling the debug toolbar resolve the issue. We're not really sure what the underlying connection is (or if the underlying issue is actually with the Yii debugger).

Details:
- Craft versions 3.4.5 and 3.4.10.1
- SEOmatic versions 3.2.42 and 3.2.48
- PHP 7.3.15
- memory_limit: 1024M

PHP error logs, consistent across different Craft and SEOmatic versions:
```php
[24-Mar-2020 13:22:28 America/New_York] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 67108872 bytes) in /var/www/html/vendor/yiisoft/yii2-debug/src/panels/EventPanel.php on line 48
[24-Mar-2020 13:22:28 America/New_York] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 67108872 bytes) in /var/www/html/vendor/opis/closure/src/SerializableClosure.php on line 383
```

Log files, trying to add a field to the "Basic Page" field layout (Craft v3.4.5, SEOmatic v3.2.42):

[phperrors.log](https://github.com/nystudio107/craft-seomatic/files/4377396/phperrors.log)
[web.log](https://github.com/nystudio107/craft-seomatic/files/4377458/web.log)

**Comment by khalwat** [comment]
Unfortunately this doesn't give me enough information to debug what is going on; I tried to reproduce it locally, but am unable to.

If we could do a screenshare some time via Tuple I could have a look at it tho?

**Comment by zsackett42** [comment]
@khalwat I figured as much. I'd be happy to screenshare any time tomorrow, or whenever you're available. Thanks for the reply.

**Comment by khalwat** [comment]
yep, you or Will ping me via Discord when you're ready -- have Tuple installed and ready to go: https://tuple.app/
