### ISSUE TITLE
Creator opening times not saving

### ISSUE THREAD

**Issue by billythekid** [nystudio107/craft-seomatic#589]
Yeah as the title says, I'm trying to fill in teh opening times leaving sunday and saturday blank but adding values for the rest. on save these are empty again.

3.2.49 on Craft 3.4.10.1

**Comment by khalwat** [comment]
@billythekid Anything in your `storage/logs/web.log`? Search on `[error]`

**Comment by billythekid** [comment]
@khalwat nothing on [error] (and it doesn't error in the flash message, says it saved fine)

I have the web.log file clean from just that save/reload if you want it. Seems a bit big to paste in here.

**Comment by khalwat** [comment]
Screenshot of what you're trying to save so I can try to reproduce here?

**Comment by billythekid** [comment]
> Screenshot of what you're trying to save so I can try to reproduce here?

<img width="419" alt="Screenshot 2020-03-27 at 22 27 06" src="https://user-images.githubusercontent.com/330170/77805874-f5c6f800-707a-11ea-82cb-471504f31348.png">
on the site settings>creator tab, obvs

**Comment by billythekid** [comment]
full page screenshot here (after reload)

![Screen Shot 2020-03-27 at 22 34 21-fullpage](https://user-images.githubusercontent.com/330170/77805926-23ac3c80-707b-11ea-946c-4f963e8e088f.png)

**Comment by khalwat** [comment]
Really interesting, this one appears to be a regression in Yii2, in terms of how it serializes objects for saving to the DB.

Fixed in https://github.com/nystudio107/craft-seomatic/commit/4c5ba05f050d8fd787374f3e68fc7934f20e6017
