### ISSUE TITLE
Non-admin users cannot access Site Settings > Social Media

### ISSUE THREAD

**Issue by lukehmu** [nystudio107/craft-seomatic#59]
We get a:
`Unauthorized`
`User is not permitted to perform this action`
error

All of the other settings pages work.

Here's a screenshot of their user group settings:
![image](https://user-images.githubusercontent.com/1893145/38308063-cb8589b4-380d-11e8-913f-f8c3a2bbbd4a.png)

Thanks,
Luke

Craft 3 RC17.1
SEOmatic 3.0.0-beta.20

**Comment by khalwat** [comment]
Right you are! Fixed in https://github.com/nystudio107/craft-seomatic/commit/85097bc0d6c456f979a7bae0261d5c308be7f718
