### ISSUE TITLE
Separate Site URL Override for Sitemaps OR use element’s URL instead

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-seomatic#590]
When used, the Site URL Override option in settings makes all links generated in a sitemap relative to the value in the Site URL Override field. This means the URLs for sitemap pages use the Site URL Override value, and the links to elements in the sitemap use this value, as well. Assets, on the other hand, seem to use their own URL (in my current situation, I'm not using Craft to host assets, so I didn't test assets hosted on the same server as the CMS).

In a situation where a sitemap isn't hosted on the front-end, could a separate setting be made to allow you to override `siteUrl` for only links to other sitemap pages?

On the other hand, should entries and other elements just link to their own URLs, instead of factoring in the value of Site URL Override? It seems like this option goes against the purpose of this field, though.

**Comment by khalwat** [comment]
As discussed, what you're trying to do is invalid; sitemaps need to exist in the same top level domain as the URLs and sitemap indexes they contain:

https://www.sitemaps.org/protocol.html
