### ISSUE TITLE
BlogPosting a section in SEOmatic panel not working

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#591]
Hi,

I'm trying to set a whole blog channel to be a BlogPosting type in Json LD but I'm seeing a weird thing.

If I set the section as BlogPosting, on SEOmatic CP, all entries are set as WebPage, even if the SEO field is left empty on each entries.
To have BlogPosting working, I have to set the SEO field as BlogPosting on each entries. Any idea ?

Craft : 3.4.10.1
SEOmatic : 3.2.49

**Comment by khalwat** [comment]
@LouisCuvelier what happens if you remove the SEO Settings field?

What happens if you re-save one of the entries with the SEO Settings field in place, but with it set to a blank (empty) value?

**Comment by LouisCuvelier** [comment]
@khalwat 

> what happens if you remove the SEO Settings field?

Ok, so I removed the field from the section and the entire website (I tested each case. The entry correctly switches back to `BlogPosting` defined in the SEOmatic panel.

> What happens if you re-save one of the entries with the SEO Settings field in place, but with it set to a blank (empty) value?

If I set back the field, leave blank the "Main Entity of Page" and re-save the entry, it comes back to `WebPage`

**Comment by khalwat** [comment]
@LouisCuvelier can you go to the Content SEO settings for the section in question, and re-save the settings there for Genera, Twitter, and Facebook?

**Comment by LouisCuvelier** [comment]
@khalwat Nothing change.

**Comment by khalwat** [comment]
@LouisCuvelier This should be fixed in SEOmatic 3.3.3 -- can you confirm?

**Comment by LouisCuvelier** [comment]
@khalwat Yes, I confirm. Thanks !
