### ISSUE TITLE
[RFC] Option to migrate from ethercreative/seo

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#594]
Hi,

It would be great if there is an automated option to migrate the data from ethercreative/seo fields to SEOmatic. We want to move away from Ether as there are some open bugs that seem to get unattended, but this would require the content and redirects to be migrated.

**Comment by khalwat** [comment]
Interesting idea. Would you be able to furnish a database that could be used for testing while developing such a feature?

**Comment by khalwat** [comment]
I will say @lenvanessen that what it says here re: migrating from SEOmatic for Craft 2 to SEOmatic for Craft 3 applies to migrating from other SEO plugins as well:

https://nystudio107.com/docs/seomatic/Issues.html#upgrading-from-seomatic-1-x-for-craft-cms-2-x

That is, if you set up the Content SEO mappings, you may not actually have to migrate data.

**Comment by lenvanessen** [comment]
@khalwat I would be able to furnish a database. I'll check the mappings as well.

**Comment by lenvanessen** [comment]
![Schermafbeelding 2020-04-09 om 09 56 25](https://user-images.githubusercontent.com/23024452/78871722-6b05d600-7a48-11ea-92e2-d45157b5d6a9.png)
More cries from the community

**Comment by lenvanessen** [comment]
@khalwat if you're looking for another approach for this, made this small conversion script:
https://github.com/lenvanessen/craft-ether-to-seomatic

`./craft craft-ether-to-seomatic/migrate/all-fields`

It's pretty specific for our set-up, but anyone that can make use of it just needs to change the mappings. For migrating you need to have a ethercreative and seomatic field in the same section/entrytype and the rest will follow by running the command.

**Comment by khalwat** [comment]
Thanks @lenvanessen ! That URL is a 404 though?

This might also be useful: https://twitter.com/nystudio107/status/1252233028698427392?s=20
