### ISSUE TITLE
Blitz Cache is cleared erroneously because of SEOmatic

### ISSUE THREAD

**Issue by martinhellwagner** [nystudio107/craft-seomatic#597]
We're using Blitz to cache our most frequented sites on a Craft install where SEOmatic is enabled as well. Even though we have the `Clear Cache Automatically` parameter in Blitz disabled and no Cron Job or Daemon running to clear/refresh the cache, the cache gets refreshed whenever an entry is created or saved. When disabling SEOmatic, the cache is not refreshed automatically – like it should.

The problem even happens when `Automatic Render Enabled` in SEOmatic is set to `false` and when all of the code referencing SEOmatic (like `seomatic.meta`) is deleted. Not really sure what, but _something_ in SEOmatic is invalidating the cache whenever an entry is created or saved.

I've also opened an issue in the Blitz repo for this: https://github.com/putyourlightson/craft-blitz/issues/204

**Comment by khalwat** [comment]
SEOmatic doesn't have any Blitz-specific code in it, but it's possible Blitz listens for an event that SEOmatic throws, and invalidates its caches as a result.

The only thing Blitz related at all in the code base is:

* Added `/cache/` to the default paths excluded in `robots.txt` to auto-exclude the default Blitz `/cache/blitz/` path

Happy to work with Ben on this to help narrow it down tho!

**Comment by martinhellwagner** [comment]
Cool, thanks! 😍

**Comment by martinhellwagner** [comment]
@khalwat 

The problem definitely lies with SEOmatic + Blitz. When I comment out this line in the SEOmatic integration of Blitz, everything works as expected:

```
Blitz::$plugin->refreshCache->refreshAll();
```

Seems like the a `nystudio107\seomatic\events\InvalidateContainerCachesEvent` doesn't send any data about its URI, Site ID, Source or Source Type, thus leading to a full cache refresh?

**Comment by bencroker** [comment]
See https://github.com/putyourlightson/craft-blitz/issues/204#issuecomment-611978588
