### ISSUE TITLE
Conflict with {catchAll} route

### ISSUE THREAD

**Issue by Hyra** [nystudio107/craft-seomatic#598]
In our Craft setup we have an entry type with uri format `{slug}`

I believe this is why we can't access SEOMatic's `/robots.txt` and sitemaps, because it tries to match an entry.

Do you guys know if there's either another way to retrieve the sitemaps, or how the uri format can be altered to make an exception for robots.txt?

**Comment by khalwat** [comment]
Can you show me exactly what is in your `config/routes.php` and/or screenshots of your Entry type?

**Comment by Hyra** [comment]
`config/routes.php` only has a graphql route:


``` 
return [
    'graphql' => 'graphql/api'
];
```

The entry type uri format:

<img width="1427" alt="Screenshot 2020-04-08 20 20 48" src="https://user-images.githubusercontent.com/380836/78819396-76b8b480-79d6-11ea-918b-b13d2c3bc015.png">

**Comment by Hyra** [comment]
Oh dear .. 
Turns out someone had added a catchall route. Mystery solved ><

![image (2)](https://user-images.githubusercontent.com/380836/78887155-a790fc00-7a5f-11ea-9d17-c572059bf415.png)

**Comment by khalwat** [comment]
yep, that'd do it heh :)
