### ISSUE TITLE
Social Preview Images do not show anywhere

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft-seomatic#600]
It's been like this for a while now, on every site I've been creating and I really can't figure out how to get it to work. Screenshot for example... I've tried making it "Same as SEO". It doesn't work. I've tried choosing it's own Open Graph image. It doesn't work. Am I missing something?

![Screen Shot 2020-04-10 at 11 14 47 AM](https://user-images.githubusercontent.com/18017918/79012973-7fb39e00-7b1c-11ea-9265-c898c42d6871.png)

**Comment by khalwat** [comment]
Check the JavaScript console for errors? Do you have your Asset volumes set up properly?

**Comment by khalwat** [comment]
Will re-open if additional info is provided.

**Comment by brandondeweese** [comment]
@khalwat — so sorry for not getting back to you. Still having this issue. Im assuming it has something to do with the asset folder?

THe link says: http://vv2020.build/admin/img/hero/_1200x630_crop_center-center_82_none/still2-2.jpg?mtime=1589396116

<img width="1009" alt="Screen Shot 2020-06-05 at 10 02 59 AM" src="https://user-images.githubusercontent.com/18017918/83903873-bfa99280-a713-11ea-9542-137160e820ee.png">
