### ISSUE TITLE
[FR] Noindex and rel=canonical mixed 

### ISSUE THREAD

**Issue by aiv2903** [nystudio107/craft-seomatic#602]
Currently, Seomatic can output a canonical tag when a page is marked as noindex. John Mueller from Google [advises](https://www.reddit.com/r/TechSEO/comments/8yahdr/2_questions_about_the_canonical_tag/e2dey9i/?context=1) against applying noindex and rel=canonical together on the same URL since they are contradictory pieces of information and it's a mixed signal. 
What are your thoughts on that, and if it's an issue, could it be changed?

**Comment by khalwat** [comment]
I'd certainly defer to John Mueller on it.

> This is also where the guide that you shouldn't mix noindex & rel=canonical comes from: they're very contradictory pieces of information for us. We'll generally pick the rel=canonical and use that over the noindex, but any time you rely on interpretation by a computer script, you reduce the weight of your input :) (and SEO is to a large part all about telling computer scripts your preferences).

Sounds like what should happen is the canonical tag gets removed if the page is marked in some way as to not be indexed.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/832e0bb20416969979e4c261dbb2230e7a7bc9af
