### ISSUE TITLE
Plugin breaks live-preview and "share" url

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#603]
For some reason, when you open the live preview after enabling seomatic, it just shows the small seomatic box normally shown at the right side.

Also, the "share" button URL changes to https://xxxxx.xx/seomatic/preview-social-media?elementId=932&siteId=11 Instead of the regular URL for previewing a draft/entry

**Comment by khalwat** [comment]
So I don't think this is SEOmatic breaking anything; I think it's likely that you don't have any preview targets set up for that section? Check your Section Settings:

<img width="1327" alt="Screen Shot 2020-04-16 at 4 31 45 PM" src="https://user-images.githubusercontent.com/7570798/79503966-0aeed100-8000-11ea-80d5-525c276c0e8a.png">
