### ISSUE TITLE
Accessing seo fields for content in twig

### ISSUE THREAD

**Issue by tomkiss** [nystudio107/craft-seomatic#605]
I can't seem to fathom this, wondering perhaps it's not possible?

```
{%- for entry in entries %}
  {{entry.seoDescription}} - nope
  {{entry.meta.seoDescription}} - nope
  {{entry.seomatic.meta.seoDescription}} - nope
  {{entry.seomatic.seoDescription}} - nope
{%- endfor %}
```

🤷‍♂️

Can easily enough create a new description field for the channels entries, then map the seomatic description to that field, but was hoping to not have to do that.

**Comment by khalwat** [comment]
You can do this as per:

https://nystudio107.com/docs/seomatic/Fields.html#template-access

```twig
{{ entry.mySeoSettingsField.metaGlobalVars.seoTitle }}
```

Note that the values will be unparsed at that point, so you might want to do:

```twig
{{ entry.mySeoSettingsField.metaGlobalVars.parsedValue('seoTitle') }}
```

**Comment by tomkiss** [comment]
Amazing, thank you.

I have trawled the docs, not sure how I didn’t find this. Thanks!
