### ISSUE TITLE
SEOMatic UI doesn't understand emoji

### ISSUE THREAD

**Issue by adrienne** [nystudio107/craft-seomatic#606]
**Issue:**

The name of the topmost channel is actually "📄 Pages"

![image](https://user-images.githubusercontent.com/89705/79447522-d98ceb80-7f94-11ea-817b-2564bed6fdc8.png)

**Desired Behavior:**

The channel name should render correctly if it has 4-byte characters in it (assuming the database collation and mysql charset are set correctly, which they definitely are in this case.)

**Version Info:**

Craft Pro 3.4.15
SEOMatic 3.2.51

**Comment by adrienne** [comment]
Just for reference, here's how the channel appears in the Entries list:
![image](https://user-images.githubusercontent.com/89705/79502859-15e83800-7fe5-11ea-9b39-8a2b5636af71.png)

**Comment by khalwat** [comment]
I'm attempting to reproduce this, but I can't even seem to get the emoji into Craft to begin with. Same issue as here: https://github.com/craftcms/cms/issues/4508

<img width="1700" alt="Screen Shot 2020-04-17 at 10 49 48 AM" src="https://user-images.githubusercontent.com/7570798/79582167-66b96880-8099-11ea-8b37-3f2920110723.png">

I even nuked the db to start from scratch with `utf8mb4` but no dice:

```
MariaDB [craft3]> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_unicode_ci   |
+--------------------------+----------------------+
1 row in set (0.000 sec)
```

What am I missing here?

**Comment by khalwat** [comment]
So @adrienne this _should_ work for you: https://github.com/nystudio107/craft-seomatic/commit/c3e88c58dd4e498193ecafa1b0f9232584fadd33

Set your semver to `dev-develop` and do a `composer update`

I haven't been able to test this, because it already "just works" if you're using Postgres, and as per above, I can't seem to get Craft to allow me to save an emoji in a Section name at all using MariaDB

**Comment by adrienne** [comment]
@khalwat - you need to configure everything to use UTF8MB4 in MariaDB in order for emoji to work. It has nothing to do with Craft itself; Craft displays emoji just fine as long as you have the right MariaDB configuration.

First, add the following config to `my.cnf` (or add a file in `mysql.cnf.d/` or `mariadb.cnf.d/` or however it's set up on your machine):

```
[client]
# Default is Latin1, if you need UTF-8 set this (also in server section)
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
# Default is Latin1, if you need UTF-8 set all this (also in client section)
character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci
character_set_server   = utf8mb4
collation_server       = utf8mb4_general_ci
character-set-client-handshake = FALSE
```

- Create the database as utf8mb4 , collation utf8mb4_unicode_ci
- Then run a Craft install (it will set up the table collation automatically)

**Comment by adrienne** [comment]
@khalwat - `dev-develop` does in fact fix the problem. Any idea when it'll end up in a release? This has to go to production soonish.

![image](https://user-images.githubusercontent.com/89705/79630266-b6814980-8104-11ea-826c-53ec7cc9900f.png)

**Comment by khalwat** [comment]
It probably won't be released for another week or two; but you can leave it at `dev-develop` for now if you need to launch. Or launch without the emojis in there.
