### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by EternalBlack** [nystudio107/craft-seomatic#61]
>  This plugin will cost $99.00 once Craft 3 GA is released.

I was wondering what this actually means to the enduser. I mean Seomatic for Craft 2 was free for everyone. I can see that $99 is not much for a company, but for someone like me (private person that would like to use it for their own portfolio site) I neither can nor want to afford it. Which ultimately leaves me with either switching to another (free) alternative for SEO or ditching Craft 3 (or Craft itself) completly as it doesn't fit my need anymore.

This may be the wrong repo but same applies to the Transcoder plugin

> This plugin will cost $59.00 once Craft 3 GA is released.

Or did I get something wrong?

**Comment by khalwat** [comment]
We think SEOmatic brings enormous value to the table. It implements things that would take many hours of custom development work to achieve, which would cost far more than the plugins price. 

Many people were rather surprised that the version for Craft 2 was ever free to begin with, and they ya have a point. 

However, it’s up to you to decide whether the plugin brings value to you. If not, no problem. You can implement something custom or something free.

**Comment by khalwat** [comment]
One other general comment on your particular website... if your site is working for you running Craft 2.x, I think there may not be a compelling need to upgrade it immediately.

If it's working, and doing what you're wanting it to do, and you don't need any of the features that Craft CMS 3 brings to the table... no reason you can't continue using Craft CMS 2.x!

**Comment by EternalBlack** [comment]
Thank you for the quick response. I totally agree that SEOmatic is a very nice plugin and the price is reasonable for companies, even though I was hoping for something like "Free for Craft Solo licenses, $99 for Craft Pro licenses" or something like that. As someone that uses craft solely for his portfolio with no intent to generate money from/with my website this would have been nice. So hobbyist are unfortunately somewhat left behind in all of this.
I also see your point that I'm not forced by anyone to upgrade to Craft 3. For me "not upgrading because I don't need the features" is not really a good reason. With this mindset I would still run Windows98 which is not going to happen. Striving for new technologies and the latest version is something I think is quite normal. I don't really like the idea of building something that is doomed to be deprecated in the near future.
All in all, thank you for your answer but in my case it seems like I unfortunately need to keep an eye out for an alternative to Craft itself or SEOmatic, ~~even though I don't think you have much competition in the realm of craft SEO-plugins so it's more likely for me to drop Craft itself.~~ Found [SEO](https://github.com/ethercreative/seo), which has a rich feature-set that suites all my needs and best of all: It's free!
Thanks anyway!

**Comment by kinoli** [comment]
Would love to see a light version of this for smaller sites and people to get their feet wet without the massive price tag. Competitors will come in if you don't give a free option. Capitalism is a blessing!

**Comment by khalwat** [comment]
I've thought about a free version, but the way the plugin system works in Craft, you can try the full version out for free for as long as you like in local dev. So I think that gives people a chance to try it out to decide if it's "worth it" to them.

That solves one part of the problem; for sites where it just doesn't make sense to spend on a plugin, I totally understand. And for those cases, you can roll your own in Twig, or use a free plugin to handle it.

I have thought about an "SEOmatic Lite" but it always ends up being troublesome to provide something that's actually useful, while also not providing something that is _so_ useful that there's no reason to buy the paid/supported version.

**Comment by ghost** [comment]
@khalwat 
I must totally agree with @EternalBlack here. 99$ seems a very fair price for any professional, commercial website. But for smaller websites or even hobbie developers it is not an option. Also thinking about how much the whole craftcmc licence cost compared to one plugin.

... I dont want to devaluate the plugin itself. it is just great. Even more a pitty that I cant use it for some projects any more.

**Comment by khalwat** [comment]
I hear ya @jacfab -- right now, my options are limited. But when P&T introduces editions for plugins, that will allow for more flexibility.

For instance, P&T has a Solo license that's free; but it has some limitations. When the ability to do something like that is available to plugins as well, I'll be looking at it very seriously.

I actually think it'd be beneficial in the long run to allow people to use SEOmatic or other plugins for free on their personal or non-commercial sites.

**Comment by ghost** [comment]
Sounds good Andrew!
