### ISSUE TITLE
[FR] Save Global/Content SEO Settings to project config file (project.yml)

### ISSUE THREAD

**Issue by denisyilmaz** [nystudio107/craft-seomatic#610]
I have searched both the documentation and the issues here on GitHub but can't find anything related, so I guess its a FR.

I have a website with dev/staging/production levels + many section types for which I need special settings each. Till now I had to sync all settings through all stages manually.

Is there any way to set the field settings (use field XY for SEO Title for type XY etc) via the `/seomatic.php` config file or even better can this be synced via the `project.yml` project config file itself?

**Comment by khalwat** [comment]
The reason SEOmatic doesn't use Project Config for this is that if AllowAdminChanges is off (which you'd normally have off with Project Config), that'd mean that people couldn't modify them in production environments, which I think would be detrimental to how people use SEOmatic.

SEOmatic treats SEO as content, so you'd need to use a content syncing strategy such as perhaps: https://nystudio107.com/blog/database-asset-syncing-between-environments-in-craft-cms

**Comment by denisyilmaz** [comment]
Thanks for the clarification. Makes sense. I will have a look at the syncing strategy you mentioned
