### ISSUE TITLE
Entries not inheriting settings from Content SEO

### ISSUE THREAD

**Issue by raptureaid** [nystudio107/craft-seomatic#612]
I've recently noticed a change in the way the `ld+json` data is being output for newly created entries. If SEO fields on the entry are blank, they are no longer inheriting the settings defined in Content SEO for the entry type, but rather they are inheriting settings from Global SEO.

For example:

**Global SEO**
![Screen Shot 2020-04-22 at 9 50 48 AM](https://user-images.githubusercontent.com/5720326/79990271-db681a80-847e-11ea-882e-24349f94c3b7.png)

**Content SEO** (event)
![Screen Shot 2020-04-22 at 9 54 03 AM](https://user-images.githubusercontent.com/5720326/79990676-53cedb80-847f-11ea-8679-49971620d636.png)

**Event entry**
![Screen Shot 2020-04-22 at 9 55 32 AM](https://user-images.githubusercontent.com/5720326/79990840-8973c480-847f-11ea-861b-8ac3443fcc02.png)

**Output**
```
{
    "@context": "http://schema.org",
    "@graph": [
        {
            "@type": "WebPage",
            ...
        },
        ...
    ]
}
```

**Expected output**
```
{
    "@context": "http://schema.org",
    "@graph": [
        {
            "@type": "Event",
            ...
            "location": {
                "@type": "Place",
                "address": {
                    "@type": "PostalAddress",
                    ...
                },
                ...
            },
            ...
        },
    ]
}
```

Entries created last year are still outputting the correct `ld+json` data, whereas those created in the last few months are incorrect.

**System info**
Application | Version
-- | --
PHP version | 7.2.19
Craft edition & version | Craft Pro 3.4.16
SEOmatic | 3.2.51

**Comment by khalwat** [comment]
Can you go in and re-save the Content SEO settings for the appropriate sections?

**Comment by raptureaid** [comment]
Re-saved the Content SEO settings for the Events section and then added a new event entry. Still seeing the wrong output (Global SEO instead of Content SEO) on the entry.

**Comment by khalwat** [comment]
Is there any custom routing being done here?

Let's do a screen share to have a look at this.

**Comment by raptureaid** [comment]
Nothing that hasn't been in place and working for quite some time. There's a `{% redirect %}` to send users back to the top level event page if trying to view an expired event.

**Comment by raptureaid** [comment]
I've done some more poking around with other sections/entries across the site. This seems directly tied to the SEO settings field being available on the entry.

When the SEO settings field is present on an entry the output is from **Global SEO** settings.

Removing the SEO settings field from the entry results in the output coming from the **Content SEO** settings.

**Comment by khalwat** [comment]
@raptureaid contact me on Craft Discord as `andrew.welch` or email me: `info@nystudio107.com` and let's arrange a time to us doing a screen share?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/19d5c7d185f8eb9c086ac05baeac6d57333b361c
