### ISSUE TITLE
Content SEO when using a Route instead of an Entry URI

### ISSUE THREAD

**Issue by ursbraem** [nystudio107/craft-seomatic#613]
I have some channels where the detail page url is based on the hypothetical position of the parent page in the structure. Does that make sense? An example.

/quirky-translated-path/jobs
/quirky-translated-path/jobs/slug-of-article

Now in accordance with craft support it came up that instead of hardwiring this path in Settings > Section > Entry URI Format, I'd rather set a route in Settings > Routes:

![image](https://user-images.githubusercontent.com/1446443/80273935-f5039f00-86d6-11ea-9b7c-799a8407d03e.png)

I did that and removed the entry URIs:

![image](https://user-images.githubusercontent.com/1446443/80273908-a35b1480-86d6-11ea-83f0-5ecc386f8ccc.png)

This works. 

But now SEOmatic doesn't recognize the channels anymore. According to the docs, it tests for an URI. So in "Content SEO" it doesn't offer those channel for configuring.

What do you recommend? Will there be a conflict with craft routing if I re-add the URI format? Is there a way SEOmatic can see the URI from the route?

**Comment by khalwat** [comment]
If there's no URI, SEOmatic can't automatically fill in the info for you, so you'll have to do it manually via Twig. Have a look at: 

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#rendering-metadata-from-another-route

**Comment by ursbraem** [comment]
Thanks @khalwat - I will do that. But my issue starts a step before: in the cp > seomatic, I don‘t see that entry at all, I guess because URI is empty. Should I fill in anything and trust the route overrides it? Won‘t that be a conflict?

**Comment by khalwat** [comment]
SEOmatic will not show any sections have have no URIs.

You don't strictly need to assign URIs to them if you plan to set the info manually via Twig.

**Comment by ursbraem** [comment]
I've let this simmer a little. If anyone else lands here, I think it's actually as simple as that: 

// I have the entry already
{% set entry = craft.entries().section('news').slug(slug).one() %}

// so I just need to add this:
{% do seomatic.helper.loadMetadataForUri(entry.uri) %}
{% do seomatic.script.container().include(false) %}

**Comment by ursbraem** [comment]
Now I DID run into an issue with this setup. The problem is, if I enter some bogus URI in said field, the content will appear in various locations; search and SEO crawlers found `www.mysite.com/myjob` (with an incomplete presentation), which should be `www.mysite.com/quirky-translated-path/jobs/myjob`

I think the most robust solution is to stick with the URI field and hard wire the quirky, translated path there, wdy think @khalwat?
