### ISSUE TITLE
HowTo with video not changing mainEntityOfPage

### ISSUE THREAD

**Issue by johnj24** [nystudio107/craft-seomatic#616]
This seems like it should be adding attributes to the main entity, but it's not changing anything. The Main Entity of Page is set to `Creative Work > How To` in the SEOMatic Content SEO settings.

```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}

{% do mainEntity.setAttributes({
  'video': {
    'type': 'VideoObject',
    'name': 'Video title goes here',
    'thumbnail': 'URL to video thumbnail goes here',
    'embedUrl': 'URL to video player goes here',
  },
}) %}
```
Am I missing something? Here's an example of what I'm trying to accomplish with the video property: https://developers.google.com/search/docs/data-types/how-to#video

**Comment by khalwat** [comment]
Yep, this looks right to me -- do you see any errors in the Yii2 Debug Toolbar? Set the Category to `seomatic` and see if anything helpful is output.

You can also try creating the `VideoObject` as you can see me doing here with the `AudioObject` and assigning that:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples#dev-mode-fm-episode-page

**Comment by johnj24** [comment]
Ugh, it was on my end. Need to watch out for those `{% cache %}` tags.
