### ISSUE TITLE
"Leave Site?" Confirmation dialogue when no changes made.

### ISSUE THREAD

**Issue by MattWilcox** [nystudio107/craft-seomatic#617]
As of 3.3.1 when going to:

- SEOmatic > Global SEO
- SEOmatic > Site Settings
- SEOmatic > Content SEO > any entry

and then trying to navigate away, with no changes made, the "Leave Site?" pop-up appears interrupting navigation.

**Comment by johndwells** [comment]
I'm also getting this, but when editing an entry that has an SEO Settings custom field, with the "Main Entity of Page" setting displayed.

**Comment by juddlyon** [comment]
I get the same issue when browsing through _Global SEO, Content SEO, and Site Settings._

My _Content SEO_ is blank but I'm guessing I have something misconfigured elsewhere.

- Craft CMS: 3.4.18
- SEOmatic: 3.3.2

**Comment by darylknight** [comment]
Still happening on 3.3.4

![image](https://user-images.githubusercontent.com/1250017/82316627-c2974a00-99d5-11ea-863b-567654d65f8a.png)

**Comment by CreateSean** [comment]
I'm getting this issue when trying to copy settings from English while on the French side.

![copy-settings-fail](https://user-images.githubusercontent.com/6899490/82824610-a123db80-9e77-11ea-9b67-c915ca4934e2.gif)

So this issue is closed, I'm going to create a new one and reference this

**Comment by juddlyon** [comment]
I've isolated this but haven't solved the problem. For me it's an issue with _vue-treeselect_ and _Main Entity of Page_ under _Global SEO › Settings › General._ 

When I delete the setting entirely, the browser dialog goes away. When I select certain Main Entities and not others it appears/disappears. This includes sub-types and levels above it. I can't ferret out what the pattern is.

- SEOmatic 3.3.4
- Craft CMS 3.4.20

**Comment by MattWilcox** [comment]
We're still getting this also - it never seemed to be fixed

**Comment by raptureaid** [comment]
Can confirm the SEO settings field presence on an entry triggering the "Leave site?" confirmation dialog. It also causes Craft to create new drafts when the "Preview" button is pushed, even though the user has not yet made any changes.

**Comment by sunscreem** [comment]
Yeah just adding the to the list - all up to date here and still got this issue.

**Comment by joshuabaker** [comment]
@khalwat Poke 😅

**Comment by khalwat** [comment]
I have not forgotten... it's really silly, but it ends up being harder to fix than you'd expect.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/8bd05df6b94e176435b7ae577bca5e1a4d932829
