### ISSUE TITLE
Duplicate Content SEO entries

### ISSUE THREAD

**Issue by j-borg** [nystudio107/craft-seomatic#618]
When updating a Content SEO entry, the entry appears twice in the Content SEO list.

![Screenshot 2020-05-01 at 14 18 59](https://user-images.githubusercontent.com/5683616/80804913-e6295a80-8bb6-11ea-8ace-06325f9539dc.png)

The entries seem to be identical, except for the `typeId` in the database. For one it's `NULL`, for the other `0`. Maybe related to [this](https://github.com/nystudio107/craft-seomatic/commit/07a7191636fe98e182d3d090e579c44c35a7ad7b#diff-f5008f1cb3eafe5afed05835d5756cfa) change in 3.3.1?

Reproduced in multiple Craft installations, for single sites as well as multisites. All with versions mentioned below.

| Application        | Version           |
| ------------- |:-------------|
| PHP      | 7.3.9 |
| Craft      | Craft CMS PRO 3.4.17.1      |
| MySQL  | 5.7.26   |
| SEOmatic | 3.3.1      |

**Comment by robmcfadden** [comment]
I'm experiencing this as well on the most recent versions of everything.

**Comment by khalwat** [comment]
I'm not sure why `groupBy` isn't taking care of that. It is on Postgres as far as I can tell:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/controllers/ContentSeoController.php#L108

**Comment by darylknight** [comment]
I'm getting this too on mariadb locally after updating to 3.3.1

**Comment by khalwat** [comment]
Yep, I figured out what it is, no worries. Will have a fix soon.

**Comment by redkrupp** [comment]
Mariadb 10.3 since last update.

https://i.imgur.com/pZsxoaV.png

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/dd164e176082fae05bc3a0a1ad465fb463757b52

**Comment by uksitebuilder** [comment]
Downloaded trial today - This is still an issue

**Comment by khalwat** [comment]
Correct, I am rolling out the release that has this fix in it today.

You can grab it now if you set your semver to `dev-develop`

**Comment by khalwat** [comment]
https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.2

**Comment by knynkwl** [comment]
@khalwat I am currently running into this problem and I am on `3.3.35`, how should I go about fixing it?

**Comment by khalwat** [comment]
You can delete the duplicate rows in the `seomatic_metacontainers` database table @knynkwl
