### ISSUE TITLE
Single bracket Twig expressions not working

### ISSUE THREAD

**Issue by its-me-mario** [nystudio107/craft-seomatic#619]
When editing Content SEO Control Panel Fields, the single brace syntax isn't working correctly.

**This Doesn't Work:**
`{ entry.metaTitle ??? entry.displayTitle ??? entry.title }`

metaTitle will be the only one that will display, displayTitle and title will not be used if they have a value. The Site Name will be used if metaTitle is empty

**This Works:**
`{{ object.entry.metaTitle ??? object.entry.displayTitle ??? object.entry.title }}`

displayTitle and title will be used if they have a value

**Using:**
Craft: 3.4.15
SEOmatic: 3.2.51

**Comment by khalwat** [comment]
It's possible they may have changed something in how object strings are parsed. I'll update the documentation.

**Comment by khalwat** [comment]
Yeah this is specific to the null coalescing operator and object syntax, so I removed the incorrect example

https://github.com/nystudio107/craft-seomatic/commit/397f9391d2d5519439fe41010ded8d0b2295664f
