### ISSUE TITLE
getLocalizedUrls example and Tag entry SEO Meta

### ISSUE THREAD

**Issue by daniellefrapp** [nystudio107/craft-seomatic#62]
Neither of these are issues with the plugin they are both questions. 

First question:
I struggling to figure out how to use this help class ( seomatic.helper.getLocalizedUrls(URI, SITE_ID) ) to build a language switcher. Do you have an example code implementations? 

Second question:
Is there a way to NOT use the global meta for a tag entry? 

Thank you! Really Enjoying your plugin!

**Comment by khalwat** [comment]
> I struggling to figure out how to use this help class ( seomatic.helper.getLocalizedUrls(URI, SITE_ID) ) to build a language switcher. Do you have an example code implementations?

So roughly something like:

```twig
{% set localizedUrlsArray = seomatic.helper.getLocalizedUrls() %}
{% for localizedUrls in localizedUrlsArray %}
   {{ "site id: #{localizedUrls['id']) - language: #{localizedUrls['language']) - url: #{localizedUrls['url'])" }}
{% endfor %}
```
> Is there a way to NOT use the global meta for a tag entry?

Can you expand on the question? I'm not sure what you mean?

**Comment by daniellefrapp** [comment]
@khalwat Sorry I was a bit vague. So it the other content type to can specify fields the the title, meta description, keywords, image, and image description pull from. But tags are a bit different than the other content type like an entry or category. Right now the meta data for tags is just using what I set globally but I didn't know if there was a way to change that. What I'm trying to avoid is duplication meta descriptions and titles.  Does this make sense?

Thank you so much for the sample code localized urls!

**Comment by khalwat** [comment]
I'm still confused, unfortunately @daniellefrapp  -- Tags as implemented by Craft don't have their own URLs, and thus wouldn't have their own SEO settings?

**Comment by daniellefrapp** [comment]
Sorry, I forgot to mention I am using craft routes to give them their own urls, so I can have a tag lndex page.

**Comment by khalwat** [comment]
Okay. In that case, you'll need to override any SEO settings that you want to via Twig (there's no settings pages in the AdminCP that SEOmatic can latch onto):

https://github.com/nystudio107/craft-seomatic#twig-templating

**Comment by daniellefrapp** [comment]
Gotcha. Thank you

**Comment by daniellefrapp** [comment]
@khalwat 
Sorry for being a pain. I am just getting back to this tag index page. I see in the documentation that you can reference an entry title or category title to override the meta data. But can you use a custom variable? 

Here is a snippet of code of what I'm trying to do in the tag index template: 
```
{% set tag = craft.tags.slug(tag).one() %}
{% set tagTitle = tag.title|capitalize %}

{% do seomatic.meta
.seoTitle("{tagTitle}")
seoDescription("Learn more about {tagTitle}")
%}
```

**Comment by khalwat** [comment]
Sure, you could do that... but you probably don't want to. Instead, do this:

```
{% do seomatic.meta
.seoTitle(tagTitle)
seoDescription("Learn more about #{tagTitle}")
%}`
```

**Comment by daniellefrapp** [comment]
Awesome, thank you.

**Comment by daniellefrapp** [comment]
Humm, when I tried the I got "Internal Server Error Server Error"

Edit I was missing the ". " on .seoDescription("Learn more about {tagTitle}") it's working fine now. Thanks again!
