### ISSUE TITLE
[FR] Provide "Same As URLs" via GraphQL

### ISSUE THREAD

**Issue by OscarBarrett** [nystudio107/craft-seomatic#620]
They appear in the meta and JSON-LD containers but aren't formatted in a way that makes it easy to use them for social links etc.

**Comment by michtio** [comment]
Could definitely use this @khalwat on multiple projects, will make some content management a lot easier along the way :+1:

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/98ceb3b258ed5c8d8e8153366408e4c0c1628569

 you can give it a whirl by setting your semver in your `composer.json` to:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.25",
```
 ...and then doing a `composer update`
