### ISSUE TITLE
SEOmatic and version 2

### ISSUE THREAD

**Issue by bonfirekennys** [nystudio107/craft-seomatic#621]
I recently purchased SEOmatic for a clients website based off some pretty good reviews. The clients website is running Craft CMS 2.9.2 . I can only find a version 3 copy to download to install through a FTP. Is there any way this will work with the Craft CMS 2.9.2? If not what do you recomend? 

I am new to using Craft CMS so detailed instructions would help immensely. 

Thankyou!

**Comment by khalwat** [comment]
SEOmatic for Craft 2.x is entirely free, but is unsupported at this point:

https://github.com/nystudio107/seomatic

This supported version of SEOmatic that you purchased only works on Craft CMS 3 or higher. You can contact Pixel & Tonic for a refund if you don't intend to use it with Craft CMS 3.
