### ISSUE TITLE
FR: Improved UI for fallbacks

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#625]
Setting up fallback options for images and SEO description in the Content SEO area is currently difficult and prone to error.

Typically I have 3 SEO specific fields per channel - SEO Title, SEO Description, and SEO Image which are the preferred options. But clients don't always fill those in so I like to use smart fallbacks - perhaps a summary field or a hero image is used.

I am aware that this can be done using the custom text option like this:

`{{ object.entry.seoTitle ???  object.entry.title }}`

or 

`{{ object.entry.seoDescription ??? object.entry.summary ??? seomatic.helper.extractTextFromField(object.entry.productsServicesContentBuilder)  }}`

However it's frustrating and difficult to write these out for each section and and then for the **general, twitter,** and **facebook** tabs as the SAME as SEO option doesn't work everytime.

Additionally when working with a channel that has many entry types the number of fallback options becomes unwieldy especially when writing out the long text needed.

What I'd like to see is **From Field** and then have a fallback option appear below the field listing other fields to choose from. Ideally you'd be able to set further fallbacks until you were done.

See screenshot.
![seomatic](https://user-images.githubusercontent.com/6899490/81194941-36bfff80-8f8b-11ea-8efc-a3cc782100e5.jpg)

**Comment by khalwat** [comment]
It looks like you're fighting how everything works a bit. What I'd suggest doing is:

- Set up the Content SEO mappings to use the default values as needed
- Provide an SEO Settings field that the client can use to override things _if they really want to_

...and then be done with it.

**Comment by CreateSean** [comment]
After talking with Andrew in discord, I learned about the the per entry type settings available as of 3.3.0 and that pretty much solves my issue.

Thank you.
