### ISSUE TITLE
3.3.1 Content SEO, duplicate entries while saving

### ISSUE THREAD

**Issue by DavidKabelitz** [nystudio107/craft-seomatic#626]
Hi,

new issue. Saving an entry at the content seo section causes an error dialog "leaving page without saving" even when it's saved it will generate a second entry at the content seo section. So all sections are doubled...

thx for helping out.

**Comment by khalwat** [comment]
Duplicate of:

https://github.com/nystudio107/craft-seomatic/issues/618

https://github.com/nystudio107/craft-seomatic/issues/617

**Comment by sunscreem** [comment]
@khalwat FYI - Just updated and tested this in production and no more duplicates :)

**Comment by khalwat** [comment]
https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.2
