### ISSUE TITLE
Setting logo in creator results in correct "logo" but incomplete "image"

### ISSUE THREAD

**Issue by EpocSquadron** [nystudio107/craft-seomatic#629]
In a new build, we've populated all of the required information for the "Creator" to be output into json+ld, however we notice that two ImageObjects are output, one of which is incomplete. I can only see the one field for Logo in the Seomatic > Site Settings > Creator section, so I'm not even sure where the second ImageObject is coming from. We are not modifying the json+ld in the template.

Here's an example of what we're seeing:

```json
        {
            "id": "<url>#creator",

            "image": {
                "@type": "ImageObject",
                "height": "40",
                "width": "200"
            },
            "logo": {
                "@type": "ImageObject",
                "height": "60",
                "url": "<correct url>",
                "width": "300"
            },
```

What am I missing?

**Comment by khalwat** [comment]
@EpocSquadron Make sure you've set up an Asset Volume, and have configured it to have public URLs.
