### ISSUE TITLE
3.3.2 broke Content SEO settings in when sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by Mosnar** [nystudio107/craft-seomatic#630]
It looks like the fix employed to stop duplicates broke the controller action and now responds with an error. 

Here's the stack trace:
https://gist.github.com/Mosnar/0e74d3de7c54f48565f58d763ebe68d1

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/5b485c8540e403931d73c7b6a0a9cdf24676f205
