### ISSUE TITLE
PHP Compile Error

### ISSUE THREAD

**Issue by mediagirl** [nystudio107/craft-seomatic#633]
Craft CMS: 3.4.18
SEOmatic v3.3.2

I'm seeing this PHP Compile Error in my local environment:
`Cannot use craft\helpers\UrlHelper as UrlHelper because the name is already in use`
`Line 16: \craft-seomatic\src\helpers\Manifest.php`

SCREENSHOT:
https://www.screencast.com/t/OCibYtR7O

**Comment by khalwat** [comment]
I believe this is specific to the version of PHP that you're using, but I've fixed it in https://github.com/nystudio107/craft-seomatic/commit/e89b3ce833ba566f2bb98fad25e0b6db8fc53a08

**Comment by mediagirl** [comment]
Indeed, switching to a different PHP version removes the error. Thank you for the quick fix!
