### ISSUE TITLE
Meta Robots Tag in SEO Field

### ISSUE THREAD

**Issue by masonry47** [nystudio107/craft-seomatic#634]
Hello! 

From our understanding if the Robots field within the SEO Settings field...

![Screen Shot 2020-05-12 at 11 17 12 AM](https://user-images.githubusercontent.com/48130527/81719696-007af800-9443-11ea-853c-b0102804e658.png)

defaults to blank, which means it will default to whatever the settings are in Content SEO for that section, which is great.  The issue we are having is if the user does use the field within the entry, and manually selects whatever is selected as the default in the Content SEO settings, it still shows blank.  So as far as what outputs everything works fine.

The issue though is for a content editor or publisher, seeing "blank" is confusing.  In addition when they manually select "All" it reverts to blank.  Again, we know that it is doing this because they are selecting what is already the default.   But it appears to the user that something is broken, because they select something and it still shows blank.  It did not seem to do this in older versions of SEOMatic.

Thoughts?  Thanks!

**Comment by khalwat** [comment]
This is (currently) behaving as expected. I agree with you that it's sub-optimal, though.

The plan is to address it in: https://github.com/nystudio107/craft-seomatic/issues/535
