### ISSUE TITLE
No XML tag on single

### ISSUE THREAD

**Issue by mikegraham00** [nystudio107/craft-seomatic#636]
We have a multisite setup. The homepage sitemap for one of the sites is not rendering correctly. This is all that is there:

`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"/>`

Any ideas why?

**Comment by khalwat** [comment]
Is it possible that the single is not enabled for that site?

Can you give me a live URL to look at?

**Comment by mikegraham00** [comment]
It is definitely enabled. It's the homepage for that site.

This is the page: https://training.epichelicopters.com/
Here's the sitemap https://training.epichelicopters.com/sitemap.xml

Thanks.

**Comment by khalwat** [comment]
When I view that sitemap, I see a number of sitemaps listed...?

```
<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>https://training.epichelicopters.com/sitemaps-1-section-course-2-sitemap.xml</loc><lastmod>2020-03-03T19:22:17-06:00</lastmod></sitemap><sitemap><loc>https://training.epichelicopters.com/sitemaps-1-section-discoveryFlights-2-sitemap.xml</loc><lastmod>2020-05-13T21:11:14-05:00</lastmod></sitemap><sitemap><loc>https://training.epichelicopters.com/sitemaps-1-section-pages-2-sitemap.xml</loc><lastmod>2020-03-03T19:27:10-06:00</lastmod></sitemap><sitemap><loc>https://training.epichelicopters.com/sitemaps-1-section-trainingHome-2-sitemap.xml</loc><lastmod>2020-02-28T12:40:02-06:00</lastmod></sitemap></sitemapindex>
```

**Comment by khalwat** [comment]
Aha I see, you're talking about the last sitemap in the list:

https://training.epichelicopters.com/sitemaps-1-section-trainingHome-2-sitemap.xml

What is this homepage? Is it a Single or a Structure or...?

**Comment by mikegraham00** [comment]
Yeah sorry about that. Should have been more specific.

That homepage is a single.

**Comment by mikegraham00** [comment]
I think I fixed it. I had a URL set for that section ('/'), even though it was a homepage. I checked the "homepage" box and saved the section and now the sitemap looks correct.

https://training.epichelicopters.com/sitemaps-1-section-trainingHome-2-sitemap.xml

Thanks. Sorry for the time waster.

**Comment by khalwat** [comment]
Glad to hear you got it sorted
