### ISSUE TITLE
2 different <title> Tags in source code

### ISSUE THREAD

**Issue by simonleimeister** [nystudio107/craft-seomatic#637]
Hey everyone

I set up <title> tags for various singles with seomatic. They are displayed correctly in the source code. However, there is an additional <title> tag by default which is parsed before the seomatic title tag and therefore indexed by search engines. 

Do you have any ideas how to only use the seomatic title tag? Does that need to be fixed within seomatic or with craft in general?

Thanks in advance

Simon

**Comment by khalwat** [comment]
SEOmatic wouldn't add two titles -- this other `<title>` tag must be coming from your templating code.

Do a global search through your templates for `<title>` and I bet it'll turn up.
