### ISSUE TITLE
Unique custom text content for structures

### ISSUE THREAD

**Issue by simonleimeister** [nystudio107/craft-seomatic#638]
Hey everyone

our content management uses "structures" to create blog posts. I tried to assign unique custom text to each to each post and also manage indexing with seomatic content seo. Do you have any suggestion how to edit individual content within a structure, since I can't open them via the conten seo modul in seomatic? Is that even possible?

Thanks in advance
Simon

**Comment by khalwat** [comment]
You'd set up the Content SEO settings to pull from the fields in your Structure, as discussed here:

https://nystudio107.com/docs/seomatic/Configuring.html#content-seo

This will pull the unique content from each structure entry into the SEO tags.

If you really, truly want to add _additional_ SEO data per entry, you can do that by adding an SEO Settings field, as discussed here:

https://nystudio107.com/docs/seomatic/Fields.html#seo-settings-field
