### ISSUE TITLE
HSTS headers overwritten

### ISSUE THREAD

**Issue by cookie10codes** [nystudio107/craft-seomatic#639]
We’re encountering some issues when setting HSTS headers on our hosting.
The plugin is overwriting the settings we’ve set in `.htaccess`

`<IfModule mod_headers.c>
    Header always set Strict-Transport-Security "max-age=300; includeSubDomains; preload"
</IfModule>`

Is there any setting we can enable to disable this overwrite behaviour?

#example of page without SEOMatic
> $ curl -I https://<host>
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Mon, 18 May 2020 10:19:07 GMT
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Strict-Transport-Security: max-age=300; includeSubDomains; preload
Location: https://<host>/nl/
Cache-Control: max-age=3600
Expires: Mon, 18 May 2020 11:19:07 GMT
Front-End-Https: on

#example of page with SEOMatic
> $ curl -I https://<host>/nl
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 18 May 2020 10:19:11 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: Craft CMS
X-Powered-By: SEOmatic
X-Robots-Tag: all
Link: <https://<host>/nl/>; rel='canonical'
Referrer-Policy: no-referrer-when-downgrade
Set-Cookie: CRAFT_CSRF_TOKEN=9a03ffa817e2d5bd6203f8942eb86b8858a94af4f6ed4fac55acd6ce2ce93760a%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A40%3A%22hrCwmMAoHWjrodsKoAmUsoxsL6YisheZMriql-SX%22%3B%7D; path=/; secure; HttpOnly
Vary: Accept-Encoding
Front-End-Https: on

Thanks for looking into this

**Comment by khalwat** [comment]
I don't think this has anything to do with SEOmatic? It looks to me like something is wrong with your setup... first of all, the server claims to be Nginx... and Nginx doesn't use `.htaccess` files at all (that's an Apache thing).

Also the first request doesn't seem to be just that SEOmatic isn't installed, it appears that it isn't hitting the CMS at all (there's no `X-Powered-By: Craft CMS` tag).

This is going to end up being a devops setup issue, SEOmatic will not strip headers.

**Comment by stijntilleman** [comment]
```
I don't think this has anything to do with SEOmatic? It looks to me like something is wrong with your setup... first of all, the server claims to be Nginx... and Nginx doesn't use .htaccess files at all (that's an Apache thing).
```
It's a basic apache, behind a nginx proxy. That explains the header. It most definitely is using a `.htaccess` file, but that's not the whole point of this discussion. 

```
Also the first request doesn't seem to be just that SEOmatic isn't installed, it appears that it isn't hitting the CMS at all (there's no X-Powered-By: Craft CMS tag).
```
The `/` isn't handled by php. So these are the bare headers without any tampering. So where are the headers going forward?

**Comment by khalwat** [comment]
Right, so load up the URL where you think it's SEOmatic that is changing the headers... but _uninstall_ SEOmatic first.

You should get the same result. SEOmatic doesn't remove any headers you may or may not have set.
