### ISSUE TITLE
Bug? Items missing from content SEO screen

### ISSUE THREAD

**Issue by sunscreem** [nystudio107/craft-seomatic#640]
I'm on the latest version of craft and SEOMatic

There seems to be an issue where the home page is showing up twice AND it's missing one of our entries types:

![image](https://user-images.githubusercontent.com/7523595/82227140-45a99900-991f-11ea-9c9c-ba686f2cb836.png)

If I search it comes up okay:

![image](https://user-images.githubusercontent.com/7523595/82227198-565a0f00-991f-11ea-9fe8-d9bf69a34520.png)

Am I missing a option somewhere? Or is this a bug?

**Comment by khalwat** [comment]
I know you stated you're on the latest version of SEOmatic, but can you give me the version number you have installed please?

**Comment by sunscreem** [comment]
hey @khalwat 

![image](https://user-images.githubusercontent.com/7523595/82302993-45a6a900-99b2-11ea-9775-cf34e4ff768e.png)

:)

**Comment by brianlarson** [comment]
Given the timing and that this is also in Content SEO here is a _potentially_ related issue. Trying to be helpful and not annoying! #642

**Comment by khalwat** [comment]
I'm at a loss of how this could happen -- if you're in local dev, can you try uninstalling and re-installing SEOmatic to see if it fixes itself?

It'd be helpful to have a database dump of the `seomatic_metabundles` table to see what might be going on here... and we might need to do a screen share to diagnose this.

**Comment by sunscreem** [comment]
Sorry for the delay - sure. Best way to send you that?

**Comment by khalwat** [comment]
You can send that to info@nystudio107.com or you can message me on the Craft discord at andrew.welch

**Comment by sunscreem** [comment]
Done :)

I'll close this.

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-seomatic/commit/a886785173e666f146a70615f786f50d868d3c2a

Can you set your semver to `dev-develop` and then do a `composer update` to test @sunscreem  ?

**Comment by sunscreem** [comment]
Hey @khalwat. Done.

That popped it in the list now :)

Its coming up twice though:

![image](https://user-images.githubusercontent.com/7523595/83502522-9f7e9700-a4b9-11ea-9239-2ea73e62d580.png)

**Comment by khalwat** [comment]
Which is coming up twice then? Just the one structure @sunscreem ?

**Comment by sunscreem** [comment]
Yeah - thats correct sir.

**Comment by khalwat** [comment]
In the database dump that you emailed me, I only see one entry in `seomatic_metabundles` for Malcolm Allan Properties -- can you re-send a new dump so I can look at it?

You can also then try (after sending me the dump) deleting those rows from the `seomatic_metabundles` and seeing if a refresh fixes things.

**Comment by sunscreem** [comment]
Thanks Andrew.

Took a db dump and sent it. As you saw no duplicates in there.

I manually deleted that DB row.

I checked the Content SEO and it was gone (including the duplicate)

Then hit the entry.

Then went back and it's back in the list and NOT duplicated now.

So - all good I think.

**Comment by khalwat** [comment]
Okay, I just pushed a change that I think should finally do what I we want. Can you please make sure your semver is `dev-develop` and do a `composer update` again? https://github.com/nystudio107/craft-seomatic/commit/ab67fa8fabe9f3f599b97d5c0b1db16e95c4243a

**Comment by sunscreem** [comment]
Yup - all good sir.

Thank you.
