### ISSUE TITLE
Correct way to dynamically set seoImage in template?

### ISSUE THREAD

**Issue by tomkiss** [nystudio107/craft-seomatic#644]
Hello, 

I have a bunch of dynamic templates where I am setting metadata (title, description, keywords and image) dynamically. All the metadata is set correctly apart from the image, which is ignored and the default global image is set. Automatic Render is Enabled, assets are on GCP and not local.

Craft 3.4.20 / Seomatic 3.3.3

**Failed test**

So here's my simple test template:

```
{%- set seoImage = craft.assets().filename('custom.png').one() %}
{% do seomatic.meta.setAttributes({
  "seoTitle": "Test",
  "seoImage": seoImage
 }) %}

{% extends "_layouts/basic" %}
{% block content %}

<!-- Block content -->
{{ seomatic.meta.seoImage.url }}

  
{% endblock %}
```

**Output (simplified)**

```
[...]
<title>Test</title>
<meta content="default.png" property="og:image">

[...]

<!-- Block content -->
custom.png

[...]
```

The title is correctly set, but the custom image is not rendered in the meta tags. However, it does render correctly in the block.  I should note that this issue still occurs when there is no global image set (i.e: there is no metadata image output at all).

**Successful test**

I've tried a number of different methods and the only way I could get the image to set, is by doing the following:

```
{%- set seoImage = craft.assets().id(123).one() %}
{%- do seomatic.meta.seoImage(seomatic.helper.socialTransform(123, "base", 1, "crop")) %}
{%- do seomatic.meta.twitterImage(seomatic.helper.socialTransform(123, "twitter-large", 1, "fit")) %}
{%- do seomatic.meta.ogImage(seomatic.helper.socialTransform(123, "base", 1, "fit")) %}
```
This results in both the meta tag and outputted value in the content block being correct.

However, this isn't how I've seen others do it. I'm wondering if there is something I'm doing wrong. Is there a "proper" way to achieve this.

**Comment by khalwat** [comment]
You're doing it right. SEOmatic has separate variables for the the SEO Image, Twitter Image, and Facebook Image -- this was done because people wanted separate control over each image.

There is this, however: 

https://github.com/nystudio107/craft-seomatic/issues/498

https://github.com/nystudio107/craft-seomatic/issues/253

**Comment by tomkiss** [comment]
Great, thanks for confirming.
