### ISSUE TITLE
Syntax for using overridden seoTitle + dynamic title 

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft-seomatic#645]
I have a resources section on a site I'm building and want to add "Resources" into the title.

So it should say "Title of Entry | Resources | Site Name."

I've successfully done this in the past with:

````{% do seomatic.meta
 .seoTitle("{entry.title} | Resources")
 .siteNamePosition("after")%}
````
However, on this site, the client often overrides the seoTitle with a longer version via an SEOmatic custom field. So I don't want `entry.title`, I want the overriden version of the title.

I cannot figure out the syntax to use seoMatic's version of the title. I've tried:
````{% do seomatic.meta
  .seoTitle("{seomatic.meta.seoTitle} | Resources")
  .siteNamePosition("after") %}
````
(doesn't render the tag at all)

````{% do seomatic.meta
  .seoTitle("{seomatic.seoTitle} | Resources")
  .siteNamePosition("after") %}
````
(tries to render something, but the output is blank)

````{% do seomatic.meta
  .seoTitle("{seomatic.meta.parsedValue('seoTitle')} | Resources")
  .siteNamePosition("after") %}
````
(this throws an exception on the page)

The docs say I should be able to reference the SEOmatic title, but I can't figure out how to get it to work. What am I missing?

P.S. I have been clearing caches between each template code test.

**Comment by khalwat** [comment]
I can't really tell from these code fragments exactly what you're doing, but I would do something like:

```twig
{% do seomatic.meta.seoTitle(seomatic.meta.seoTitle ~ ' | Resources') %}
```
