### ISSUE TITLE
{% do seomatic.meta.seoDescription("test") %} doesnt output meta tag.

### ISSUE THREAD

**Issue by MattWilcox** [nystudio107/craft-seomatic#646]
According [to the docs](https://nystudio107.com/docs/seomatic/Using.html#meta-variables-seomatic-meta) `{% do seomatic.meta.seoDescription("test") %}` should control `the description that is used for the <meta name="description"> tag`.

However, when used, no `<meta name="description" value="test" />` is inserted into the page. `test` is only showing up in the Open Graph JSON.

**Comment by khalwat** [comment]
When I do exactly what you have here:

```twig
{% do seomatic.meta.seoDescription("test") %}
```

I see this in my page source:
```html
<title>🚧 Craft3 \| :scream: Homepage</title><meta name="generator" content="SEOmatic">
<meta name="description" content="test">
```

So it's definitely working. My guess is maybe you already have an existing `<meta name="description">` tag on your page? You'll need to remove it.
