### ISSUE TITLE
Site URL Override not applied to og:url or mainEntityOfPage

### ISSUE THREAD

**Issue by dbrookes** [nystudio107/craft-seomatic#647]
I have a single site install, with a base URL for that site set to a string `https://craft.mydomain.com`, in my SEOmatic settings I've set Site URL Override to `https://mydomain.com`, and cleared all caches.

Running the following GaphQL query shows that `og:url` meta tag inside `metaTagContainer`, `mainEntityOfPage` and `url` inside `metaJsonLdContainer` remains the same as the Craft URL (https://craft.mydomain.com) which is causing problems for Google, but the other references have changed. This seems to be happening to all pages across the site.

```
{
  seomatic(uri:"/") {
    metaTagContainer
    metaJsonLdContainer
  }
}
```

Craft CMS 3.5.0-beta.2
SEOmatic 3.3.4
PHP 7.4.4
PostgreSQL 10.13

**Comment by khalwat** [comment]
In the case of things like assets, the URL comes from whatever `asset.url` returns -- perhaps you need to change the volume settings for your Asset Volume?

**Comment by dbrookes** [comment]
It's not anything to do with assets, asset urls output by SEOmatic are all correct.

This is for a headless setup, so my Craft site lives on `https://craft.mydomain.com`, and I've set Site URL Override in the SEOmatic settings to `https://mydomain.com`:

When running the GraphQL query above in the control panel:

### Within `metaTagContainer`

Expected: 

`<meta content="https://mydomain.com" property="og:url">`

Received:

`<meta content="https://craft.mydomain.com" property="og:url">`
(Override did not work for this `og:url` property, it's using the Craft site Base URL still)

### Within `metaJsonLdContainer`

Expected:

`"mainEntityOfPage\":\"https://mydomain.com"`

Received:

`"mainEntityOfPage\":\"https://craft.mydomain.com"`

This affects all pages site wide, but Site URL Override has worked on all other properties other than these 2 above - as far I can see my settings are correct so it just looks like the URL replacement isn't working for these properties.

**Comment by dbrookes** [comment]
I was able to resolve this by setting Canonical URL in content SEO settings to `https://mysite.com/{entry.uri}` rather than the default(?) of `{entry.url}` which is weird as the canonical URL output before was correct.

Guess site URL override just don't work for that field?

**Comment by khalwat** [comment]
The Site URL Override kicks in whenever something asks for a site URL. In the case of `{entry.url}` it'll only do something if the URL isn't already a full URL (it could be going to a CDN, for instance).

If you set it to something like: `{entry.uri}` that then wouldn't be a full URL, so it'd probably work, because it'd turn it into a complete URL automatically.
