### ISSUE TITLE
Section types not showing up in Content SEO tab

### ISSUE THREAD

**Issue by peirix** [nystudio107/craft-seomatic#648]
After updating to 3.3.4 my «frontpage» section disappeared from the Content SEO list. Looking in the `seomatic_metabundles` table in SQL, I see that they both have `sourceId` set to `1`. Changing one of them manually to something else will make all my sections appear in the list, but when I save one of them it creates duplicates of everything and sets everything back to where one section type overrides the other.

**Comment by khalwat** [comment]
Can you provide a screenshot please?

**Comment by khalwat** [comment]
Important to note here: `sourceId` conflict seems to stem from Digital Products not having a unique `typeId`

**Comment by peirix** [comment]
Not sure how much of the db you want a screenshot of, but here's part of it:

![image](https://user-images.githubusercontent.com/347175/82986629-7c09a700-9ff6-11ea-866b-26a56ea01c7b.png)

**Comment by khalwat** [comment]
Yeah this is only happening because you have Digital Products installed. I will have a look.

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-seomatic/commit/a886785173e666f146a70615f786f50d868d3c2a

Can you set your semver to `dev-develop` and then do a `composer update` to test @PieterxJan ?

**Comment by peirix** [comment]
Yeah, that worked. Thanks.

So now PieterxJan won't have to test it. :D
