### ISSUE TITLE
Saving Content SEO on digital products throws error

### ISSUE THREAD

**Issue by peirix** [nystudio107/craft-seomatic#649]
Saving the Content SEO page of a digital products throws this error:

`
TypeError: Return value of nystudio107\seomatic\seoelements\SeoDigitalProduct::getElementRefHandle() must be of the type string, null returned in /home/forge/[craftproject]/vendor/nystudio107/craft-seomatic/src/seoelements/SeoDigitalProduct.php:83
`

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/4795c99079c940dedc8c35cb31f4595be724c46f
