### ISSUE TITLE
Preview errors

### ISSUE THREAD

**Issue by aarmitage** [nystudio107/craft-seomatic#65]
Craft CMS 3.0.1
Seomatic 3.0.0-beta.21

Sidebar SEO Preview on entries is working fine when there is no SEO field assigned to the section. In Global SEO settings we have only set an image and no other info. All of our SEO settings have been made in the Content SEO section of the SEOmatic plugin. The entries are correctly loading the Content SEO into the SEO Preview.

When we add the SEO field to the section to allow clients to make overrides if needed on a per entry basis, the SEO Preview is changed when the entry is next saved or hard refreshed. The SEO Preview now shows as being empty but loading in our image we set in the Global SEO.

It looks like when there isn't a field present, the SEO Preview looks for Content SEO and uses Global SEO as a fallback. When a field is present however it looks for the field values, and uses Global SEO as a fallback, this means that the Cotent SEO is being skipped. What the SEO Preview in fact need to do when a field is present, is look for field values, fallback to Content SEO, and then fallback to Global SEO.

The twitter cards etc generated by the url of the page are correct and using the Content SEO so it seems that the correct checks are in place on the front end, it's just the SEO Preview sidebar in the CP that is misleading for users.

**Comment by khalwat** [comment]
Same as: https://github.com/nystudio107/craft-seomatic/issues/55

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/dd8181058cd279b86af2f605894dc37ab159e919
