### ISSUE TITLE
Unable to Copy settings from English to French - "Leave Site?" Confirmation dialogue

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#650]
Craft 3.4.20
SEOmatic 3.3.4

When attempting to copy settings from the English site to the French site I get the leave site option and the page reloads without any of the settings copied over. See gif

A similar issue is reported in this closed issue: https://github.com/nystudio107/craft-seomatic/issues/617

![copy-settings-fail](https://user-images.githubusercontent.com/6899490/82824805-ffe95500-9e77-11ea-834d-568cb88e939a.gif)

*** **update** ***
so it appears that the settings are copied over, but I'm still getting that dialog which is what convinced me that they settings were not copying over.

**Comment by khalwat** [comment]
Same as: https://github.com/nystudio107/craft-seomatic/issues/617
