### ISSUE TITLE
siteUrlOverride applies to both sitemap.xml links as well the frontend links

### ISSUE THREAD

**Issue by denisyilmaz** [nystudio107/craft-seomatic#652]
Hi, i have a headless craft installation with a JS frontend that uses the GraphQL endpoints.

I want to add the sitemaps to google without having to route through the frontend.
CUrrently, SEOmatic uses the frontend url for the links to each sections `sitemap.xml` file:

>> `http://localhost/en/sitemap.xml`
```xml
<sitemap>
    <loc>
        http://localhost:4200/en/sitemaps-1-section-projects-2-sitemap.xml
    </loc>
    <lastmod>2020-05-26T08:50:00+02:00</lastmod>
</sitemap>
```
here the sitemap.xml links are incorrect as I would need to route via frontend back to the backend.

I tried to change `siteUrlOverride` to use the url to the backend which works:

>> `http://localhost/en/sitemap.xml`
```xml
<sitemap>
    <loc>
        http://localhost/sitemaps-1-section-projects-2-sitemap.xml
    </loc>
    <lastmod>2020-05-26T08:50:00+02:00</lastmod>
</sitemap>
```
Now the problem is, even that the links to the sections `sitemap.xml` are correct, the page links are using `siteUrlOverride` as well resulting in invalid links inside the `sitemap.xml` itself. Ex. `http://localhost/projects/some-example-project` which should stay as `http://localhost:4200/projects/some-example-project`.

Is there any settings I'm unaware of to get this expected result?

Thanks!

**Comment by khalwat** [comment]
Sitemaps _must_ be hosted from the same domain/port as the URLs they contain:

https://www.sitemaps.org/protocol.html

> Note: A Sitemap index file can only specify Sitemaps that are found on the same site as the Sitemap index file. For example, http://www.yoursite.com/sitemap_index.xml can include Sitemaps on http://www.yoursite.com but not on http://www.example.com or http://yourhost.yoursite.com. As with Sitemaps, your Sitemap index file must be UTF-8 encoded.

I'm not sure what you're trying to do is possible?

**Comment by denisyilmaz** [comment]
oh, I'm so sorry. as I was writing this my head was totally in another use case for the sitemap.xml file and not for indexing via search engine. so I mixed two unrelated infos together. you're right, I need to route from frontend through backend myself via htacces/nginx settings. closing this now.
