### ISSUE TITLE
[FR] Referrer-Policy needs to be updated

### ISSUE THREAD

**Issue by csgrant83** [nystudio107/craft-seomatic#655]
The Referrer-Policy is currently set to the default value of no-referrer-when-downgrade. I believe this should be something that can be set in the admin cp, so that an admin can chose to upgrade the policy. Right now if I use this plugin, I cannot update the policy short of turning off automatic rendering... which kind of defeats the point of this plugin from my point of view. For reference, I would like to be able to set the referrer policy to strict-origin-when-cross-origin.

**Comment by khalwat** [comment]
@csgrant83 So you can configure this via Twig if you like:

```twig
{% set referrerTag = seomatic.tag.get("referrer") %}
{% if referrerTag | length %}
    {% do referrerTag.content("strict-origin-when-cross-origin") %}
{% endif %}
```

Little is hard-coded in SEOmatic, via the Twig API you can change just about everything: https://nystudio107.com/docs/seomatic/Using.html#seomatic-tags-containers

I agree this should be a CP setting though. I'll make it a FR.

**Comment by csgrant83** [comment]
Thank you, I saw the docs on modifying containers, but could not figure out the format. Appreciate it!

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/eed26ae2cebdd76d79bd1381ca643dc172b1a7ba

<img width="1037" alt="Screen Shot 2020-06-02 at 1 05 45 AM" src="https://user-images.githubusercontent.com/7570798/83482056-57d21e00-a46d-11ea-8f1c-6b5b71ebd8df.png">
