### ISSUE TITLE
Robots from Seomatic field doesn't override Content SEO robots field config

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#656]
Hi @khalwat  

For a structure section I have set the Robots config in the Seomatic Content SEO to ```None - Do not index or follow links on this page```

When I want to make an exception on entry level in the same section, by using the seo settings field, and try to override the robots Content SEO setting to ```All - Index this page and follow links (default)```  the override is not being applied. 

The canonical and alternate locale links are not being displayed/loaded.

Craft CMS: 3.1.34.3
Seomatic: 3.2.38 - 3.3.5

If more info is needed please let me know

**Comment by khalwat** [comment]
Does the reverse work @boldenamsterdam ? If you have Content SEO set to something `all` and individually override things to `none` ?

**Comment by boldenamsterdam** [comment]
Hi @khalwat , yes the other way around it works. I will probably use this as a workaround for now.

**Comment by khalwat** [comment]
That helps, will do a test-case.

**Comment by NickLanger1990** [comment]
will this issue be fixed or do i just have to use the workaround?

**Comment by khalwat** [comment]
This issue will be fixed, but you can use the work-around for now.

**Comment by khalwat** [comment]
I'm attempting to fix this issue, but I can't seem to make it happen. I have Content SEO set to:

<img width="789" alt="Screen Shot 2020-07-24 at 9 46 08 PM" src="https://user-images.githubusercontent.com/7570798/88446333-1cadf480-cdf7-11ea-8360-c21e10c6b12b.png">

...and then I have an SEO Settings field in that section, which I set to All:

<img width="789" alt="Screen Shot 2020-07-24 at 9 45 28 PM" src="https://user-images.githubusercontent.com/7570798/88446358-6991cb00-cdf7-11ea-9b4e-d9c6804a25bd.png">

...and if I view the source (after ensuring my site is in Live Production), I see:

```html
<meta name="robots" content="all">
```

Which is what I'd expect. What am I missing here @boldenamsterdam & @NickLanger1990 ?

**Comment by NickLanger1990** [comment]
Your are right. Its now working as aspected. The only buggy thing is that when i set the content seo of a structue type to none and than set the section to all and save, the section seo tab for robots is empty after reload but the code is actually working.
its just not getting display in the cp-panel for robots. 
![2020-07-26 22_00_39-Window](https://user-images.githubusercontent.com/45926167/88488139-9ecf2200-cf8b-11ea-904b-92b8f9fa76d7.png)

Can you reproduce that?

**Comment by khalwat** [comment]
@NickLanger1990 this is expected behavior, but it is poor UX, I agree. See here for details: https://github.com/nystudio107/craft-seomatic/issues/535

**Comment by boldenamsterdam** [comment]
Hi @khalwat 

That's strange. We are also experiencing the same, we are not able to reproduce the issue anymore.
Since we created the issue the website has been update to SEOmatic 3.3.8. 

Thanks for coming back on this issue.

For our own peace of mind, we will try to reproduce locally with an older SEOmatic version.
