### ISSUE TITLE
Document hiding canonical when noindexed

### ISSUE THREAD

**Issue by juddlyon** [nystudio107/craft-seomatic#657]
The changelog from version 3.3.0 says that the canonical link is not output when robots is set to noindex or none, which happens depending on how you set your environment label and dev mode.

It'd be helpful to document this under [Multi-Environment Config Settings](https://nystudio107.com/docs/seomatic/Configuring.html#multi-environment-config-settings). I'm trying to test a dynamic canonical variable before taking it live and couldn't figure out why it wasn't showing up. I tried changing either the environment or the dev mode but it required both at the same time to figure it out.

Apologies in advance if I overlooked something here. Thanks!

**Comment by khalwat** [comment]
Ah good point @juddlyon -- I will document it. https://github.com/nystudio107/craft-seomatic/commit/f8bc9abf1d2280133c634cbf7bef8c7ae9c25d62
