### ISSUE TITLE
Error when pulling meta from field

### ISSUE THREAD

**Issue by iamtompickering** [nystudio107/craft-seomatic#658]
I am experiencing issues when setting the meta description to be pulled from a field that exists in my entry. The field I'm trying to set this option to pull from is a Redacto field. When set, it brings up the following error on the front end. 

<img width="2034" alt="Screenshot 2020-06-02 at 13 36 14" src="https://user-images.githubusercontent.com/6592882/83520828-3d805a80-a4d6-11ea-984b-3c89374294bd.png">

It is worth noting that this site is running an English and Chinese site, and this is happening on the Chinese site only. No issues when setting this on the English site. 

Craft Version: 3.4.9
SeoMatic Version: 3.2.46

**Comment by khalwat** [comment]
This is what it says it is, malformed UTF-8 characters. The error is actually being thrown by Yii2, but I added a catch for this in Version 3.3.3 -> https://github.com/nystudio107/craft-seomatic/blob/v3/CHANGELOG.md#333---20200512

Please update to the latest version.
