### ISSUE TITLE
FR: Option to disable content SEO for specific sections

### ISSUE THREAD

**Issue by richhayler** [nystudio107/craft-seomatic#659]
Personally it would be really nice if there was an option to "disable" all SEO settings in "content SEO" for specific entry sections.

Some sections on my site are configured as containers for content that only gets used within another section's templates and will never be rendered as a standalone page. I also have sections that are content holders for other information that I want to omit from SEOmatic treatment.

Rather than configure each of the current SEO options for these sections, it would be great to have a simple option to toggle content SEO off for these sections.

Additionally it would be great to be able to detect "content SEO off" within a section's template as part of a conditional query so alternative meta data could be inserted in place of SEOmatic generated content.

**Comment by khalwat** [comment]
The way to toggle these off is to not have public URLs for the sections.

If a section has no public URLs, then SEOmatic will not add any metadata to it.

If a section _does_ have public URLs, understand that Google will find these URLs and crawl them, one way or another. If they will never be rendered as a stand-alone page, then turn off the public URLs for the page.

If these pages really should be available on the frontend, but for some reason you don't want Google indexing them, you need something there telling Google that. So you would want to have SEOmatic working on these page, and set the Indexing to None and disable the sitemaps for them as well.

Does this help @richhayler or is there some other complication here?

**Comment by richhayler** [comment]
Hi Andrew,

Thanks very much for the explanation. This definitely helps me. I guess what I was trying to achieve is to be able to "preview" component-style content blocks (using live preview) that would only be used within other section templates and avoid having to configure SEOmatic for these component sections – instead inserting a very simple nofollow, noindex meta tag. On reflection not a great approach.

I have since removed the urls from these sections. However now when I review the SEOmatic dashboard for a particular site in my multi-site setup it seems to reflect that the "content SEO" section is not completely setup despite me configuring each available option.

Could it be that the dashboard view for "Content SEO" is still "seeing" the sections I have removed URLs for?

I've included a few screenshots to help explain what I'm talking about.

<img width="1338" alt="Screenshot 2020-06-04 10 16 32" src="https://user-images.githubusercontent.com/2505643/83702351-cec70c80-a64f-11ea-963f-cede79ae0beb.png">

<img width="1343" alt="Screenshot 2020-06-04 10 16 50" src="https://user-images.githubusercontent.com/2505643/83702362-d686b100-a64f-11ea-8865-7c2e3b251c4d.png">

**Comment by richhayler** [comment]
And one follow on question - what do the inner circles (green, amber, red) within the "Content SEO" reflect? I looked through the docs but couldn't find anything to answer my question. Thanks.

**Comment by khalwat** [comment]
If you mouse over each section of the radial bar chart, it will explain will show you the grade. Basically, it's the number of A's, B'c, C's, D's, etc.

As for the checkboxes not being checked, I think this is actually a bug introduced in a recent version of SEOmatic (3.3.0 or later).

**Comment by richhayler** [comment]
Thanks Andrew 👍

**Comment by khalwat** [comment]
I've filed an issue for that here: https://github.com/nystudio107/craft-seomatic/issues/662
