### ISSUE TITLE
iso8601 Deprecation error

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-seomatic#66]
`entrymeta/JsonLdContainer.php` and `categorymeta/JsonLdContainer.php` is using the iso8601 filter, which results in this deprecation error:

`DateTime::iso8601() is deprecated. Use the |date('Y-m-d\TH:i:sO') filter instead.`

**Comment by khalwat** [comment]
booooooooooooo. I'm bummed they removed this.

**Comment by khalwat** [comment]
Brandon says that we should actually be using `| atom`

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/56e316a7d49eb8a93a9e85647be25d23a917ef00
