### ISSUE TITLE
Multi-site: Primary site url displayed in twitter and Facebook previews

### ISSUE THREAD

**Issue by richhayler** [nystudio107/craft-seomatic#660]
When viewing the twitter and Facebook SEO previews within "Global SEO" setting for any site within a multi-site setup it appears to use the primary site's url instead of the current selected site URL.

**Comment by khalwat** [comment]
@richhayler is this only the previews in "Global SEO" or also the previews in the sidebar or on Content SEO as well?

**Comment by richhayler** [comment]
@khalwat, ah you're right, it's also the sidebar previews. Twitter, Facebook and LinkedIn all show the primary site URL instead of the selected site's url.

For additional context, I have one site group with 4 sites defined and each site has it's own base URL defined.

**Comment by richhayler** [comment]
Incidentally, the preview for Google displays the selected site's url correctly.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/e3dd97ff7cf79939d1235a6add700037752ae88f
