### ISSUE TITLE
Home page specific SEO title option

### ISSUE THREAD

**Issue by richhayler** [nystudio107/craft-seomatic#661]
Similarly to the option under "Global SEO > Twitter > Twitter Site Name Position"  it would be nice to have the same facility specifically for a website's home page or alternatively the option to only insert the site name without any page title or separator. For example;

- **Home page** - "Site Name"
- **Other Pages** - "Page Title | Site Name"

_In my particular case I am using a "structure" section to manage my home page and the website's main section pages._

I can add a conditional in my section template as follows:

```
{% if entry.uri == "__home__"%}
  {% do seomatic.meta.seoTitle ("Some Title") %}
{% endif %}
```

But this title then has the site name and seperator appended to it (per "content SEO" settings) which is only what I want for the other entries (apart from the homepage) in the section.

**Comment by richhayler** [comment]
In my particular case I am using a "structure" section to manage my home page and the website's main section pages.

**Comment by richhayler** [comment]
Ok, I figured this out. This might be useful to add to the docs for others who need to cater for this specific setup.

```
{% if entry.uri == "__home__"%}
  {% do seomatic.meta.seoTitle ('Some Title') %}
  {% do seomatic.meta.siteNamePosition('none') %}
{% endif %}
```

**Comment by khalwat** [comment]
Glad you got it sorted!
