### ISSUE TITLE
Settings for certain sections not saving; data not available in GraphQL query

### ISSUE THREAD

**Issue by howells** [nystudio107/craft-seomatic#663]
Hi - 

Not sure which information you need to help me debug an issue, but I'm finding for a handful of sections, after having configured and saved the section settings in SEOmatic, the 

1) Section configured correctly: https://cln.sh/4qouep (no errors are reported on save, for example)
2) Description and image statuses red in SEOmatic dashboard: https://cln.sh/5zVEd8
3) No data returned with GraphQL query, using:

```
seomatic {
 metaTitleContainer
 metaTagContainer
 metaLinkContainer
 metaScriptContainer
 metaJsonLdContainer
}
```

It does work for some sections, however, so I'm struggling to understand why it would be fine for some but not others? Every section has an SEOmatic configuration associated with it: https://cln.sh/Citv0f

**Comment by khalwat** [comment]
Can you give 3.3.7 a whirl? I fixed something that could be affecting this -- but ultimately I will probably need to add `typeId` support in the GraphQL layer.

**Comment by howells** [comment]
Hi Andrew - I updated to 3.3.7, and went through each section and re-saved the settings, but unfortunately none of them changed their status to green.

However, it does look like the data is fetching correctly via graphql, so we're getting there for sure!

**Comment by khalwat** [comment]
hrm. The fix I put in was for the checkboxes on the home page, let me have a look here.

**Comment by khalwat** [comment]
@howells can you send me a database dump of the `seomatic_metabundles` table? andrew@nystudio107.com

Many thanks!

**Comment by khalwat** [comment]
From the db dump it looks like you have just 2 sections? Is that correct?

**Comment by howells** [comment]
Hi Andrew sorry for the delay - no there are 15 sections in total - did you see the full database dump I emailed you?

**Comment by khalwat** [comment]
I'm having a look at it!

**Comment by khalwat** [comment]
Sorry @howells picking this back up -- are you able to do a test where you uninstall and reinstall the plugin in local dev, to see if that fixes the issue? I'm wondering if there might have been some data improperly saved at some point along the way.

**Comment by howells** [comment]
Hard to remember now but I did reinstall it: I recall that while it didn't immediately sold the problem, it eventually did end up working so I have no idea what steps I'd have taken deliberately to fix it! 🤷‍♂️
