### ISSUE TITLE
SEOMatic metadata output including token string in url.

### ISSUE THREAD

**Issue by cap-akimrey** [nystudio107/craft-seomatic#664]
We've just noticed recently that the site metadata and json-ld object that SEOMatic is dynamically generating has started including "?token=<key>" strings appended to some urls. 

We noticed this because we use DeadLinkChecker for daily crawling, and this behavior is leading to a lot of 400 Bad Request errors in the reports. No idea if this is affecting other crawlers such as the google bot, yet, though. 

The site is using SEOMatic 3.3.5, Craft 3.4.20.

It seems related to the Meta Cache feature?

![Screen Shot 2020-06-04 at 12 04 53 PM](https://user-images.githubusercontent.com/41020122/83790002-27e96d00-a65d-11ea-83c1-94fa89b9ce4a.png)
![Screen Shot 2020-06-04 at 12 04 31 PM](https://user-images.githubusercontent.com/41020122/83790004-28820380-a65d-11ea-88de-0aeaaa636f89.png)

**Comment by khalwat** [comment]
I think these are likely coming from your Live Preview, which adds a token. Not sure how/why they could get indexed though?

**Comment by cap-akimrey** [comment]
Live Preview would make sense.

As far as I know, though, our practices haven't changed. I did update the plugin before this started popping up, but I'd be hard pressed to say which version I upgraded from, so I couldn't connect a specific update version where this might have started. v3.3.4, maybe? 

I initially had the Meta Cache duration set to unlimited and changed it to One Hour a little over an hour ago, which cleared the existing tokens, and I'm not yet seeing new ones bubble up.

**Comment by khalwat** [comment]
Since it only appears to be appearing in the auto-generated breadcrumbs, I've changed it in https://github.com/nystudio107/craft-seomatic/commit/aa7f5d2462aaac2c6f6fd1aba7171be4ec13fc3f so that it will strip the query string from these URLs

Can you set your semver to `dev-develop` and give it a whirl? You can set the cache duration back down to "infinite" and give it a whirl?

**Comment by cap-akimrey** [comment]
Education moment - how does one set a semver?

**Comment by khalwat** [comment]
So a semver is a Semantic Version -- this might help with that: https://twitter.com/nystudio107/status/1076453266228199425?s=20

Basically, your `composer.json` probably looks something like this for the SEOmatic entry:

```json
    "nystudio107/craft-seomatic": "^3.1.12",
```

Change it to look like this:

```json
    "nystudio107/craft-seomatic": "dev-develop",
```

Then do `composer update`

**Comment by cap-akimrey** [comment]
Aha. Looks like you've updated the production branch, though? I've updated to v3.3.8 and set the Meta Cache Duration back to Unlimited. Whirling.

**Comment by khalwat** [comment]
Yep, I decided to push it out. Feel free to let me know if you have a further issue with this.
