### ISSUE TITLE
[FR] Support league/csv: ^8.2|9.0

### ISSUE THREAD

**Issue by leevigraham** [nystudio107/craft-seomatic#665]
Feedme supports league/csv: ^8.2|^9.0. It would be great if this plugin did as well so we can use  league/csv: ^9.0 in our projects / plugins.

**Comment by khalwat** [comment]
I tried to do this a while ago, but it ends up being that the API actually is different. So it's not a matter of just changing the semver unfortunately.

**Comment by leevigraham** [comment]
> I tried to do this a while ago, but it ends up being that the API actually is different. So it's not a matter of just changing the semver unfortunately.

Yep… I'll have a look at doing it myself over the weekend and shoot a PR if I sort it. The issue was mainly a placeholder and a reminder.

**Comment by khalwat** [comment]
@leevigraham I think this is posted to the wrong repo? SEOmatic doesn't use this package

Do you want to file it again for Retour?

**Comment by leevigraham** [comment]
Oops. Yep Retour it is.
