### ISSUE TITLE
Make "Site URL Override" multisite

### ISSUE THREAD

**Issue by Toni-hr98** [nystudio107/craft-seomatic#667]
I have a multisite with 3 sites. They all have their own url. But i need to override it for all 3 of them. But the plugins sections isn't multisite functional... is it possible to fix this?

![Schermafbeelding 2020-06-10 om 15 38 02](https://user-images.githubusercontent.com/56109782/84274633-620cb000-ab30-11ea-8504-13d107cea319.png)

**Comment by khalwat** [comment]
@Toni-hr98 So you should be able to make the site URL override work with a multi-site setup, if you use the `config.php` and set it up in a multi-environment way for each site.

**Comment by hendrikbunnick** [comment]
I'm using Craft in a Multi-Site setup with the following Settings in config/general.php
```
        'siteUrl' => [
            'en' => '',
            'de' => 'de'
        ],
```
If i set `siteUrlOverride` in the `config/seomatic.php`
The Url defined in `siteUrlOverride` gets applied to both Sites `en` + `de` which results in a wrong alternate Url for `de` in the MetaLinkContainer, which is then obviously missing the "de" Slug in the resulting Url.

It would be really handy if `siteUrlOverride` would also support an the same multi-setup syntax as `siteUrl` does.

Using a fully qualified Url in siteUrl and leaving siteUrlOverride blank, would preserve the `de` Slug but,
would result in a wrong base Url for me.

Can you please advice how to achieve this?

**Comment by sarahschuetz** [comment]
Running in the same Problem. Any news on how to handle this?

**Comment by denisyilmaz** [comment]
I was able to overwrite it like this:

`seomatic.php`
```php

 $perSiteSettings = [
    'de' => [
        'siteUrlOverride' => '@primarySiteUrl/de'
    ],
    'en' => [
        'siteUrlOverride' => '@primarySiteUrl/en'
    ]
];
return [
    '*' => [
        'siteUrlOverride' => $perSiteSettings[Craft::$app->getSites()->getCurrentSite()->handle]['siteUrlOverride'],
    ]
];
```

**Comment by khalwat** [comment]
Looks like a good way to handle it @denisyilmaz -- tho since it's a multi-environment config, this would work too:

```php
return [
    'de' => [
        'siteUrlOverride' => '@primarySiteUrl/de'
    ],
    'en' => [
        'siteUrlOverride' => '@primarySiteUrl/en'
    ]
];
```
