### ISSUE TITLE
Humans.txt url

### ISSUE THREAD

**Issue by Toni-hr98** [nystudio107/craft-seomatic#668]
A SEOmatic field to change the Humans.txt url (author)

**Comment by Toni-hr98** [comment]
I have 3 headless multisites with 1 CMS. In my craft settings -> website -> basic-urls I want to fill my backend CMS url ( so not the frontend url ). But when i do this and I query it in my graphql it gives me a canonical url with the CMS url. Even when i change the "canonical" field in SEOmatic to the frontend-url. So the canonical field in SEOmatic doesn't work or affect anything in this matter.

```
query seomatic($slug:String) {
    seomatic (uri: $slug, siteId: 4, asArray: true) {
        metaLinkContainer
    }
}

Outputs the wrong canonical url.
```

Now you could say, change the "Site URL Override" in SEOmatic -> plugins, so the canonical url changes to the frontend url. But this doesn't support multisite. So im kinda stuck... 

And the Humans.txt url always links to the first basic-url site. This should be fixed to by adding a field to change it

**Comment by khalwat** [comment]
@Toni-hr98 So you should be able to make the site URL override work with a multi-site setup, if you use the `config.php` and set it up in a multi-environment way for each site.

**Comment by Toni-hr98** [comment]
So if i copy the **config.php** from "node_modules -> nystudio107 -> craft-seomatic -> src" to the config map and rename it to seomatic.php. What should I do next?

**Comment by Toni-hr98** [comment]
How can i fill this field
    'siteUrlOverride' => '',
With 3 different frontend url's
