### ISSUE TITLE
Using cloudnary filesystem

### ISSUE THREAD

**Issue by matevisky** [nystudio107/craft-seomatic#67]
The image transformation in case of cloudnary is tricky. Do you have any best pratice how to utilize it? Cloudanry has its own transformation system, and I would like to use that, and not Craft's own...

On the frontend side I can overwrite the tags, but on the CP side it will be still crapy I guess?

Anyhow thx for the great work, hope you have some good workaround to resolve this

**Comment by khalwat** [comment]
Did you may be mean to post this for ImageOptimize? https://github.com/nystudio107/craft-imageoptimize

Post an issue there if you like?

**Comment by matevisky** [comment]
I tried out with googlecloud filesystem as well, and it is not working
Error rendering `{seomatic.helper.socialTransform(object.entry.headerImage.one(), "facebook", )}` -> Unexpected token "punctuation" of value ")"
So even if I am adding the image manually it is not working, is there any trick what I can do to make this work or troubleshoot?

Thx
