### ISSUE TITLE
Entry URLs incorrect when using GraphQL

### ISSUE THREAD

**Issue by howells** [nystudio107/craft-seomatic#670]
I've only just noticed that in all instances, an entry's URL is incorrect when using GraphQL, e.g. the `og:url` or `canonical` tags: it falls back to the homepage URL. (I'm only using GraphQL so I can tell if it would work with regular twig tags).

My site's base url is set to an env variable, `$SITE_URL` if that makes a difference, and the Canonical URL setting in Content SEO settings for each section is set to `{entry.url}`.

**Comment by khalwat** [comment]
Show me what you're passing into GraphQL when trying to retrieve an entry?

**Comment by howells** [comment]
hey Andrew - sorry I've since confirmed this is working okay, sorry to waste your time on this one
