### ISSUE TITLE
Facebook tabs not showing?

### ISSUE THREAD

**Issue by sunscreem** [nystudio107/craft-seomatic#675]
This might be me being dumb, but I'm not seeing facebook tab on entries:

![image](https://user-images.githubusercontent.com/7523595/85722634-66b59480-b6ea-11ea-8158-5d79b4a4a1d1.png)

The preview is showing (bottom right).

Anything I should be checking? Been all through the settings and can't spot anything

**Comment by khalwat** [comment]
@sunscreem you need to enable that in the Field Settings for the SEO field you've created -> https://nystudio107.com/docs/seomatic/Fields.html#seo-settings-field
