### ISSUE TITLE
Scheme issue on Craft Commerce

### ISSUE THREAD

**Issue by amityweb** [nystudio107/craft-seomatic#676]
Does SEOMatic add the Schema code before closing </body>

Because we use Craft Commerce but we are not selling products at the moment so dont show prices. 

But the schema is including prices and Google has now indexed the prices which causes an issue as we have not set correct prices yet. 

I cannot for the life of me see where in the settings to disable this. Either disable price or just dont use schema. 

Thanks

**Comment by amityweb** [comment]
I have found a setting whereby I can set Products to EntryType Web Page. I have done that. I have changed all entry types and the General Site settings to WebPage, then cleared all caches. But this code is still showing in the footer:

`<script type="application/ld+json">{"@context":"http://schema.org","@graph":[{"@type":"Product","mainEntityOfPage":`

etc

**Comment by khalwat** [comment]
What you'd need to do is get the Main Entity of Page (which in this case will be a Product) and change it as you see fit.

There are some examples of doing just that here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

...as well as here:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively

**Comment by amityweb** [comment]
I have copied JsonLdContainer.php to 

config/seomatic-config/productmeta/JsonLdContainer.php 

then deleted the whole offers section, but the offers with price is still showing on the product page.

**Comment by khalwat** [comment]
The `config/seomatic-config/productmeta/JsonLdContainer.php` file only applies to newly created meta containers. If you uninstalled, and then re-installed the plugin, it would create the new meta containers with your changes.

You already have one created, so you'd need to use the techniques in the articles that show getting the mainEntityOfPage and changing it.

e.g.: https://nystudio107.com/docs/seomatic/Using.html#json-ld-meta-object-functions-seomatic-jsonld

```twig
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}

{% set offersJsonLd = seomatic.jsonLd.create({
    'type': 'Offer',
    'name': 'Some prop',
    'url': 'Some url',
}, false) %}

{% do mainEntity.offers(offersJsonLd) %}
```

That's just an _example_, check the code to do what you need it to do.

**Comment by amityweb** [comment]
Sorry I am finding this way over the top, just need a setting to not add the json at the bottom, why is it so complicated to get this line removed from my html?

**Comment by amityweb** [comment]
Thanks, adding that last code you sent me to the product page template allows me to override the output, so will do that. BUT I just want the price section removed, I dont want to have to recreate all other tags just to hide price. 

Ideally you should add some setting in there to disable it on sections, its a very long/complex page you expect people to understand and I could not even see that I should be adding the codes to the page template files, I just experimented here and it did it. 

Thanks for your help.

**Comment by amityweb** [comment]
This does the trick to remove it:

```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{% set offersJsonLd = '' %}
{% do mainEntity.offers(offersJsonLd) %}
```
