### ISSUE TITLE
Redirect dashboard requests when not authorised to access

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-seomatic#677]
At present, SEOmatic is throwing a 403 when someone tries to access `/cptrigger/seomatic` without permissions to view the dashboard.

Instead, please can we redirect to the first page they do have access to.

Version: 3.2

**Comment by khalwat** [comment]
hmmmm. This is a little dicey, is there something sensitive on the dashboard that you don't want to give people access to?

**Comment by joshuabaker** [comment]
To be honest, it’s mostly expectation management. Some less technically savvy clients will assume we’ve not configured things, when actually keywords don’t really matter and lots of settings can be inherited (but have a negative score impact if not present).

It’s also excessive information for most use cases. We use Dashboard Begone for a lot of sites too for the same reasons.

Hope that gives some context. 😊

**Comment by jsunsawyer** [comment]
I just had a client reach out about this as well. Disabling the dashboard permissions used to work as a way to bypass the dashboard altogether.

We disable the dashboard for the same reason @joshuabaker listed. I had to reenable this for this client, but probably have several other clients that just aren't even touching SEO and would experience this same issue.

Regardless of whether we should be able to disable it or not, the SEO dashboard permission setting being unchecked, but other SEO options being checked will result in this error when clicking SEO from the sidebar in the CP.
