### ISSUE TITLE
Canonical urls doesn't add trailing slash when addTrailingSlashesToUrls is enabled

### ISSUE THREAD

**Issue by sjelfull** [nystudio107/craft-seomatic#678]
### Describe the bug
I have enabled `addTrailingSlashesToUrls` but SEOmatic doesn't add trailing slashes to canonical entry urls.

### Expected behaviour
Canonical entry URLs should have trailing slashes at the end.

### Screenshots

![image](https://user-images.githubusercontent.com/10508/86528837-21445480-beac-11ea-8775-1e7bae63bd8d.png)

### Versions
- Plugin version: 3.3.8
- Craft version: 3.5.0-beta.2

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/f19db16ec4edadb640cfee790b62a82c87910a82
