### ISSUE TITLE
og:url is different from canonical url

### ISSUE THREAD

**Issue by sjelfull** [nystudio107/craft-seomatic#679]
### Describe the bug
As you can see, the `og:url` and canonical URL is not the same.

The Base URL of the site and Site URL override is both set to a different url, which is applied to the canonical url but not the og:url.

### Screenshots

![image](https://user-images.githubusercontent.com/10508/86597090-8c208900-bf9b-11ea-9756-b7b9c585b535.png)

![image](https://user-images.githubusercontent.com/10508/86597307-d3a71500-bf9b-11ea-9c40-c4bc74ef4021.png)

### Versions
- Plugin version: 3.3.8

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/e3dd97ff7cf79939d1235a6add700037752ae88f
