### ISSUE TITLE
Redundant Canonical URLs with Automatic Render enabled

### ISSUE THREAD

**Issue by TimothyLoyer** [nystudio107/craft-seomatic#68]
Automatic Rendering is causing redundant canonical URLs (in Link Header _and_ HTML meta tag), which result in the Lighthouse SEO audit to fail a test. There may also be [implications with Google's search ranking](https://webmasters.googleblog.com/2013/04/5-common-mistakes-with-relcanonical.html).

I spent some time with the developers of Lighthouse yesterday trying to determine whether this is a bug, and it seems that the best practice would be to only specify rel=canonical once. Could this redundancy either be removed, or the ability to modify the behavior be exposed in the control panel settings for SEOmatic?

[Here is the discussion at the Lighthouse repo](https://github.com/GoogleChrome/lighthouse/issues/3178).

**Comment by khalwat** [comment]
huh. I assumed that it'd be fine to do both... I also do the same thing with the `robots` tag as well (it's sent as a header, too).

**Comment by auralon** [comment]
I have the same issue (I sent you a direct email, @khalwat, to question whether this is to be determined as a bug or not).

Can we get an option to turn this off?  I'm currently having to patch the plugin after each update to stop the header being sent, so that Lighthouse scores higher in its audit.

**Comment by khalwat** [comment]
@auralon Yeah I think it makes sense that have an option to disable this in the meantime.

I want to stress that it's by no means definitive (yet) that sending them via header + tag has any negative effect, other than the lighthouse strike.

**Comment by auralon** [comment]
> I want to stress that it's by no means definitive (yet) that sending them via header + tag has any negative effect, other than the lighthouse strike.

@khalwat exactly.  I'm just guessing that it has a negative effect, based on Lighthouse flagging it, but it would be nice to have definitive proof that it does present an SEO issue.

Also, thanks for the great plugins! :+1:

**Comment by khalwat** [comment]
The resolution here was that this is a bug in Lighthouse:

>  got confirmation from John Mueller himself (praise be unto him) that this is a bug. We should only fail when there are multiple different canonical URLs.

https://github.com/GoogleChrome/lighthouse/issues/3178#issuecomment-381181762
