### ISSUE TITLE
SEOmatic field with multi-language not working

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#680]
### Describe the bug
I've a blog post entry with two language French and English. I've added a SEOmatic field to this blog post. But, the same SEOmatic field settings are applied to the two languages at the same time.

### To reproduce
Steps to reproduce the behaviour:
1. Create a multisite
2. Create an entry field with an SEOmatic field
3. Set some SEOmatic settings on the first language.
4. Save
5. Change language for the entry
6. See that SEOmatic field settings are defined on the first language

### Expected behaviour
Have SEOmatic field settings for each language.

### Versions
- Plugin version: 3.3.8
- Craft version:  3.4.22.1

**Comment by khalwat** [comment]
I don't think this has anything to do with SEOmatic; I think you need to set the translation method for the SEO Settings field to be what you're wanting it to be.

<img width="743" alt="Screen Shot 2020-07-07 at 10 56 26 PM" src="https://user-images.githubusercontent.com/7570798/86869800-33d5ae00-c0a5-11ea-84d1-3ed6923295d8.png">

**Comment by LouisCuvelier** [comment]
You were right. Thanks !
