### ISSUE TITLE
TypeError: SettingsController::actionEditContent()

### ISSUE THREAD

**Issue by saadirfan** [nystudio107/craft-seomatic#681]
### To reproduce
We recently updated the SEOmatic plugin and now gettings following 
"`Argument 5 passed to nystudio107\seomatic\controllers\SettingsController::actionEditContent() must be of the type integer or null, string given`"
while updating the Content SEO settings from the 
SEOmatic > Content SEO > [Section Name] > General

The issue is there for all section types and sites hosted in my multi-site network. 

I see [Issue 318](https://github.com/nystudio107/craft-seomatic/issues/318) had a somewhat similar error statement, but it was marked solved. 

Following is from my web.log:

```
2020-07-06 17:15:19 - error - TypeError
TypeError: Argument 5 passed to nystudio107\seomatic\controllers\SettingsController::actionEditContent() must be of the type integer or null, string given in /opt/mysite/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php:445
Stack trace:
#0 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionEditContent('general', 'section', 'blog', 'festival', '', NULL)
#1 /opt/mysite/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /opt/mysite/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /opt/mysite/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-content', Array)
#4 /opt/mysite/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-content', Array)
#5 /opt/mysite/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('seomatic/settin...', Array)
#6 /opt/mysite/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('seomatic/settin...', Array)
#7 /opt/mysite/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /opt/mysite/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /opt/mysite/web/index.php(21): yii\base\Application->run()
#10 {main}
```
Screenshot with devMode enabled:
<img width="1610" alt="Screen Shot 2020-07-06 at 7 50 20 PM" src="https://user-images.githubusercontent.com/1347439/86669840-006e2300-bfc2-11ea-8f0d-9c313406a893.png">

I've tried downgrading to 3.3.8, but no luck.

### Versions
- PHP 7.1.33
- PostgreSQL 9.6.2
- Craft Pro 3.1.21
- SEOmatic 3.3.9

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/26a98d45c12982e4e77470249eaa9d14b3a25388
