### ISSUE TITLE
SEOmatic not honouring sendPoweredByHeader config

### ISSUE THREAD

**Issue by peteeveleigh** [nystudio107/craft-seomatic#686]
Have set my installation up with `sendPoweredByHeader` set to false.
This is removing the note that the site is powered by Craft but I still see SEOmatic being shown in the headers.

To reproduce
```
'sendPoweredByHeader' => false
```

Load the site, examine the headers.
```
x-powered-by:  SEOmatic
```

- Plugin version: 3.3.10
- Craft version: 3.4.27 Pro

**Comment by khalwat** [comment]
SEOmatic has a separate setting for it in the Plugin Settings -> Tags -> Generator Enabled setting
