### ISSUE TITLE
About removing keywords from dashboard's checklist

### ISSUE THREAD

**Issue by JeanLucEsser** [nystudio107/craft-seomatic#687]
### Question
I'm following up on this tweet: https://twitter.com/JeanLucEsser/status/1283307588399124480?s=20

Although SEO Keywords are ignored by Google (making them irrelevant to I guess more than 90% of use cases), they remain a key part of the Dashboard Setup Checklist, going as far as dropping the Global score from 100% (A) to a mediocre 83% (C).

I suggest removing this item from the Dashboard, both for Global and Content.
What do you think?

### Additional context
<img width="259" alt="Capture d’écran 2020-07-15 à 20 09 41" src="https://user-images.githubusercontent.com/14908712/87580067-28066f00-c6d7-11ea-9cfb-eba5bc7afe5f.png">

**Comment by khalwat** [comment]
So I still think it's okay to set this up, just so other search engines that do use Keywords still (and other meta engines like Pinterest) have access to them.
