### ISSUE TITLE
Entry SEO preview images not rendered when using cloud-based asset volumes

### ISSUE THREAD

**Issue by croxton** [nystudio107/craft-seomatic#69]
Tested with images stored in a Google Cloud Storage volume.

The image in the SEO preview in the sidebar of entries is blank. The image request 404s, e.g.:

    https://www.mywebsite.com/admin/entries/[path]/_1200x630_crop_center-center_82_line/my-image.jpg?mtime=xxx

If the url instead pointed to Asset's `generate-thumb` action with the `uid`, it would work:

    https://www.mywebsite.com/index.php/admin/actions/assets/generate-thumb?uid=xxx&width=1200&height=630&v=xxx

**Comment by khalwat** [comment]
Very strange. It's just using Craft transforms to return the image. What happens if you attempt the same thing via frontend templating?

**Comment by croxton** [comment]
Hmm, odd.

This yields nothing:

    {% set asset = entry.myImageField.one() %}
    {{ asset.url }}

But this yields the path:

    {% set asset = entry.myImageField.one() %}
    {{ asset.getPath() }}

Craft bug maybe?

**Comment by khalwat** [comment]
Yeah I'm thinking it's either a Craft bug or maybe a config/setup bug. Gonna close the issue, but let me know what you figure out! I'm reasonably sure that SEOmatic isn't involved in this, we just ask for the transformed URL and assume Craft/whatever handles that end of it properly.
