### ISSUE TITLE
sitemap.xml not generating on Heroku hosted site

### ISSUE THREAD

**Issue by entwurf** [nystudio107/craft-seomatic#690]
sitemap.xml not being generated when hosted on Heroku.

Run './craft seomatic/sitemap/generate ' and terminal indicates they have been created but when navigating to /sitemaps-1-section-activities-1-sitemap.xml get the below message...

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<!--  This sitemap has not been generated yet.  -->
<!--  If you are seeing this in local dev or an  -->
<!--  environment with `devMode` on, caches only  -->
<!--  last for 30 seconds in local dev, so it is  -->
<!--  normal for the sitemap to not be cached.  -->
<urlset> </urlset>
```

The main /sitemaps.xml works fine.

Craft and seomatic are set to production mode.

Any ideas what's causing this issue?

**Comment by khalwat** [comment]
I'd need more information -- it's not an issue across the board with Heroku-related sites, because many run and use SEOmatic.

What is your caching method that you're using? Hopefully Redis?

**Comment by khalwat** [comment]
@entwurf Do you have an errors in your `storage/logs/queue.log`?

**Comment by khalwat** [comment]
Happy to re-open if more information is made available.

**Comment by mikejdegroot** [comment]
Hi @khalwat, I'm a developer with Entwurf so I'll pick this up from here.

We are running a multi site headless craft installation with Seomatic plugin. visiting one of our sites urls with /sitemap.xml appended to the url returns the following, seems correct:

![Screenshot 2020-08-10 at 17 03 20](https://user-images.githubusercontent.com/27430574/89804250-d1505180-db2b-11ea-9357-b9c9769532e9.png)
 
However, visiting the first link directly the sitemap seems improperly formatted, see below:

![Screenshot 2020-08-10 at 17 09 53](https://user-images.githubusercontent.com/27430574/89804722-7703c080-db2c-11ea-8207-63df1eed1b47.png)

I am aware this could be a browser issue, but strange that it is formatted correctly on the top level map. Below is the output of inspecting the code from the browser:

![Screenshot 2020-08-10 at 17 12 14](https://user-images.githubusercontent.com/27430574/89804999-df52a200-db2c-11ea-95b7-617c4ab58923.png)

Thanks

**Comment by mikejdegroot** [comment]
update: validating the second misformatted sitemap does pass online validation tests, so I suspect this is a non-issue. However, we are seeing issues on another non headless site we manage, which I believe is what the first ticket is referring to. I will investigate this and come back on this thread. Apologies for the deviation

**Comment by mikejdegroot** [comment]
Hi @khalwat, 

deleted my previous messages as they were irrelevant. The problem we are seeing relates to a live heroku project in a production environment. As the OP ticket states, it works in development mode as expected, but in production on everything but the top level site map it displays the message: 
`<!--  This sitemap has not been generated yet.  -->`

We have `runQueueAutomatically` set to false and have a task scheduler running the command `./craft seomatic/sitemap/generate`. Manually running that command in the heroku terminal outputs the following:

`Generating sitemap
Generating sitemap for structure Activities, siteId 1
Processing element 1/1 - Balade en  calèche
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionactivities1

Generating sitemap for single Contact, siteId 1
Processing element 1/1 - Contact
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectioncontact1

Generating sitemap for structure Content Pages, siteId 1
Processing element 1/3 - Cookies
Processing element 2/3 - Politique de confidentialité
Processing element 3/3 - Conditions générales de vente
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectioncontentPages1

Generating sitemap for single Gallery, siteId 1
Processing element 1/1 - Galerie
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectiongallery1

Generating sitemap for single History, siteId 1
Processing element 1/1 - L’histoire
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionhistory1

Generating sitemap for single Homepage, siteId 1
Processing element 1/1 - Bienvenue
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionhomepage1

Generating sitemap for single Private Events, siteId 1
Processing element 1/1 - Événements privés
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionevents1

Generating sitemap for single Wines, siteId 1
Processing element 1/1 - Les Vins
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionwines1

Generating sitemap for structure Activities, siteId 3
Processing element 1/1 - Horse carriage ride
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionactivities3

Generating sitemap for single Contact, siteId 3
Processing element 1/1 - Contact
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectioncontact3

Generating sitemap for structure Content Pages, siteId 3
Processing element 1/3 - Cookies
Processing element 2/3 - Privacy Policy
Processing element 3/3 - Terms & Conditions
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectioncontentPages3

Generating sitemap for single Gallery, siteId 3
Processing element 1/1 - Gallery
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectiongallery3

Generating sitemap for single History, siteId 3
Processing element 1/1 - History
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionhistory3

Generating sitemap for single Homepage, siteId 3
Processing element 1/1 - Welcome
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionhomepage3

Generating sitemap for single Private Events, siteId 3
Processing element 1/1 - Private Events
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionevents3

Generating sitemap for single Wines, siteId 3
Processing element 1/1 - Wines
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionwines3

Generating sitemap for single Account Forgot Password, siteId 2
Processing element 1/1 - Account Forgot Password
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionaccountForgotPassword2

Generating sitemap for single Account Login, siteId 2
Processing element 1/1 - Account Login
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionlogin2

Generating sitemap for single Account Pages, siteId 2
Processing element 1/4 - Dashboard
Processing element 2/4 - Profile Edit
Processing element 3/4 - Special Offers
Processing element 4/4 - Order
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionaccount2

Generating sitemap for single Account Register, siteId 2
Processing element 1/1 - Account Register
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionregister2

Generating sitemap for structure Content Pages, siteId 2
Processing element 1/4 - Cookies
Processing element 2/4 - Livraison
Processing element 3/4 - Conditions Générales de Vente
Processing element 4/4 - Politique de Confidentialité
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectioncontentPages2

Generating sitemap for structure Customer Pages, siteId 2
Processing element 1/3 - Cart
Processing element 2/3 - Checkout
Processing element 3/3 - Order confirmation
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectioncustomer2

Generating sitemap for product Olive Oil, siteId 2
Processing element 1/2 - Vierge Extra
Processing element 2/2 - Vierge Extra intense
Sitemap cache result: 1 for cache key: seomatic_sitemap_2productoliveOil2

Generating sitemap for structure Product Sections, siteId 2
Processing element 1/5 - Vins
Processing element 2/5 - Nos vins de propriété
Processing element 3/5 - Nos vins de marque
Processing element 4/5 - Huile d'olive
Processing element 5/5 - Tous les produits
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionproductSections2

Generating sitemap for product Wine, siteId 2
Processing element 1/13 - Château Fontainebleau
Processing element 2/13 - Château Fontainebleau
Processing element 3/13 - Louis Baptiste
Processing element 4/13 - Louis Baptiste
Processing element 5/13 - Jean-Max
Processing element 6/13 - Jean-Max
Processing element 7/13 - Arcades de Fontainebleau
Processing element 8/13 - Fontainebleau
Processing element 9/13 - Fontainebleau
Processing element 10/13 - Fontainebleau
Processing element 11/13 - Le Petit Fontainebleau
Processing element 12/13 - Le Petit Fontainebleau
Processing element 13/13 - Le Petit Fontainebleau
Sitemap cache result: 1 for cache key: seomatic_sitemap_2productwine2

Generating sitemap for single eShop Contact, siteId 2
Processing element 1/1 - Contact
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectioneshopContact2

Generating sitemap for single eShop homepage, siteId 2
Processing element 1/1 - Bienvenue
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectioneshopHomepage2

Generating sitemap for single Account Forgot Password, siteId 4
Processing element 1/1 - Account Forgot Password
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionaccountForgotPassword4

Generating sitemap for single Account Login, siteId 4
Processing element 1/1 - Account Login
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionlogin4

Generating sitemap for single Account Pages, siteId 4
Processing element 1/4 - Account Pages
Processing element 2/4 - Profile Edit
Processing element 3/4 - Special Offers
Processing element 4/4 - Single Order
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionaccount4

Generating sitemap for single Account Register, siteId 4
Processing element 1/1 - Account Register
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionregister4

Generating sitemap for structure Content Pages, siteId 4
Processing element 1/4 - Cookies
Processing element 2/4 - Shipping
Processing element 3/4 - Terms & Conditions
Processing element 4/4 - Privacy Policy
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectioncontentPages4

Generating sitemap for structure Customer Pages, siteId 4
Processing element 1/3 - Cart
Processing element 2/3 - Checkout
Processing element 3/3 - Order confirmation
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectioncustomer4

Generating sitemap for product Olive Oil, siteId 4
Processing element 1/2 - Extra Virgin
Processing element 2/2 - Vierge Extra intense
Sitemap cache result: 1 for cache key: seomatic_sitemap_2productoliveOil4

Generating sitemap for structure Product Sections, siteId 4
Processing element 1/5 - Wine
Processing element 2/5 - Wineyard wines
Processing element 3/5 - Nos vins de marque
Processing element 4/5 - Olive Oil
Processing element 5/5 - All Products
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectionproductSections4

Generating sitemap for product Wine, siteId 4
Processing element 1/13 - Château Fontainebleau
Processing element 2/13 - Château Fontainebleau
Processing element 3/13 - Louis Baptiste
Processing element 4/13 - Louis Baptiste
Processing element 5/13 - Jean-Max
Processing element 6/13 - Jean-Max
Processing element 7/13 - Arcades de Fontainebleau
Processing element 8/13 - BIB Fontainebleau
Processing element 9/13 - BIB Fontainebleau
Processing element 10/13 - BIB Fontainebleau
Processing element 11/13 - Le Petit Fontainebleau
Processing element 12/13 - Le Petit Fontainebleau
Processing element 13/13 - Le Petit Fontainebleau
Sitemap cache result: 1 for cache key: seomatic_sitemap_2productwine4

Generating sitemap for single eShop Contact, siteId 4
Processing element 1/1 - eShop Contact
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectioneshopContact4

Generating sitemap for single eShop homepage, siteId 4
Processing element 1/1 - Welcome
Sitemap cache result: 1 for cache key: seomatic_sitemap_2sectioneshopHomepage4`


But still, I cannot see the sitemaps. As for caching, to my knowledge we have not added anything extra for caching, though I can see redis in the composer lock. Is there something we might need to do to cache the site map?

Thanks, any help greatly appreciated

**Comment by khalwat** [comment]
> On Aug 11, 2020, at 6:02 AM, mikejdegroot <notifications@github.com> wrote:
> 
> But still, I cannot see the sitemaps. As for caching, to my knowledge we have not added anything extra for caching, though I can see redis in the composer lock. Is there something we might need to do to cache the site map?
> 
> 

If you are hosting on Heroku, you will 100% want to have the caching method setup to use Redis — otherwise it uses the default, which is file-based, which doesn’t work with Heroku’s ephemeral file system

Since the generated sitemaps are stored in the cache, this very well could be the issue. A number of people use SEOmatic on Heroku, so I don’t think there is an issue with SEOmatic and Heroku in general.

/andrew

**Comment by mikejdegroot** [comment]
@khalwat Thanks for your advice with this. I have found that with `runQueueAutomatically` set to true the sitemaps are generated and are viewable. Setting it to false and implementing the redis caching we still have the same issue. Is it possible that setting `runQueueAutomatically` false is breaking the functionality? If so, do you know if we can set it to true but still run some jobs with our task runner?

**Comment by khalwat** [comment]
> On Aug 12, 2020, at 6:34 AM, mikejdegroot <notifications@github.com> wrote:
> 
> @khalwat Thanks for your advice with this. I have found that with runQueueAutomatically set to true the sitemaps are generated and are viewable. Setting it to false and implementing the redis caching we still have the same issue. Is it possible that setting runQueueAutomatically false is breaking the functionality? If so, do you know if we can set it to true but still run some jobs with our task runner?
> 
> 

If you set that to false, you have to manually generate the sitemap — is that manual generation not working for you somehow?

**Comment by mikejdegroot** [comment]
Yep, I run the command, everything outputs correctly (as above) and I still see the sitemaps not generated error

**Comment by khalwat** [comment]
I think something is not correctly set up on your Heroku instance
