### ISSUE TITLE
Don't send an X-Robots-Tag header for tokenized requests

### ISSUE THREAD

**Issue by mtwalsh** [nystudio107/craft-seomatic#693]
### Describe the bug
When sharing a draft entry from Craft CMS it will generate a tokenized URL. In the event that someone actually links externally to the tokenized URL Craft implemented a [fix](https://github.com/craftcms/cms/issues/5698) to ensure they would not be indexed by the search engines. But this results in two `X-Robots-Tag` headers being returned, one from Craft and one from SEOmatic.

### To reproduce
Steps to reproduce the behaviour:
1. Save a draft in Craft CMS and then use the Share button to view it, which should generate a tokenized URL.
2. Inspect the response headers and note both `X-Robots-Tag: none` (from Craft CMS) and `X-Robots-Tag: all` (from SEOmatic).

### Expected behaviour
I would suggest that for tokenized URLs SEOmatic should not return an `X-Robots-Tag` header.

### Screenshots
![image](https://user-images.githubusercontent.com/1246553/88090843-1533e480-cb86-11ea-9e6c-aa439cbbc294.png)

### Versions
- Plugin version: 3.3.8
- Craft version: 3.4.25

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/94e943d15bcfae006c2b4e26f4841d3557596b78 & https://github.com/nystudio107/craft-seomatic/commit/cb0d8ef94d52b4cb6db959d45993b38f20745147

It'll now send `none` during a preview for the tag, and won't send any headers at all as well.

**Comment by mtwalsh** [comment]
Thanks for the quick response!
