### ISSUE TITLE
More options for "environment" in the plugin settings

### ISSUE THREAD

**Issue by michtio** [nystudio107/craft-seomatic#694]
### Describe the solution you would like

Currently as the environment settings we have the following:

`Environment
The server environment, either live, staging, or local. If devMode is on, SEOmatic will override this setting to local Development.`

It would be nice if SEOMatic could take some more variables into consideration:

eg: 

#### Production
- production
- release
- live

#### Staging
- staging
- sandbox
- beta
- alpha

#### Local Development
- local
- dev
- development

**Comment by khalwat** [comment]
This shouldn't be needed. _You_ can have as many environments as you want. You just need to map your environments to the 3 environments that SEOmatic knows and cares about.

Also in determining these "automatically" (which you can manually override as you see fit), SEOmatic does take a number of variations into consideration:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/Environment.php#L32
