### ISSUE TITLE
GraphQL all entries have robots:no-index in generated meta tags

### ISSUE THREAD

**Issue by andrewmumblebee** [nystudio107/craft-seomatic#695]
### Question
Heya, i've been trying out SEOmatic on a new site for my company, everything seems to be working smoothly. However, i noticed that the robots meta tag aren't getting the correct content. I saw that you need to be on a production environment to get them to not be marked as no-index, so i changed the environment variable to production.

However, all my entries are still marked as no-index on the robots tag. 😕 

I'm currently using the trial, so wonder whether that is why?

We will be purchasing the plugin before releasing the site, but i want to make sure that this is not a bug beforehand.

Whilst i'm here i'm also experiencing a similar issue with your Retour plugin, no data is being returned in the GraphQL query. Will open an issue over on that repo if it's unrelated to using the trial.

Thank you! 🙂 

### Additional context

![image](https://user-images.githubusercontent.com/29373199/88266213-b7f37c80-ccc6-11ea-92c6-a5df0a50a761.png)

**Comment by khalwat** [comment]
Which environment variable did you change to be production @andrewmumblebee ? If `devMode` is on, SEOmatic will override that setting, and assume you're not in `live` production. See here for details:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/Environment.php#L67

**Comment by andrewmumblebee** [comment]
Hi @khalwat I had changed the environment variable in craft's .env file to "production" as below.

`ENVIRONMENT="production"`

Weirdly it's now working again, i did restart the nginx web server & php service & cleared out the caches, so potentially that helped.

Will close this for now, cheers!
