### ISSUE TITLE
X-Default included with meta tags even if the Plugin option for it is Off 

### ISSUE THREAD

**Issue by mizziness** [nystudio107/craft-seomatic#696]
### Describe the bug
Even with the plugin setting to include `x-default` turned **off**, `x-default` is still being included in `seomatic.link.get('alternate')`

### To Reproduce
1. Go to Craft CMS admin > SEO > Plugin Settings > Tags 
2. Turn the option to include `x-default` links to **OFF** (is on by default I believe). Save Changes.
3. Refresh front-end of website and view data dump or meta tags

100% reproducible 10/10 times.

*Additionally, I think the x-default value here is wrong - it is pointing to the default site url in english when there is a site in french, so wouldn't it default to the french language page?*

### Expected behaviour
I would expect to see the list of alternate links *without* having an `x-default` entry. (I also think the value is incorrect.)

### Screenshots
Admin Settings:

![image](https://user-images.githubusercontent.com/4164335/88310047-39560980-ccdd-11ea-8b5d-8fa26ed9c78d.png)

HTML:

![image](https://user-images.githubusercontent.com/4164335/88311846-67d4e400-ccdf-11ea-91c7-45af023f00ec.png)

Data Dump:

![image](https://user-images.githubusercontent.com/4164335/88312044-aa96bc00-ccdf-11ea-8d4a-8f434dccee15.png)

### Versions
- Plugin version: SEOmatic 3.3.8
- Craft version: Craft Pro 3.4.29.1

**Comment by khalwat** [comment]
SEOmatic will use whatever you have set as the _primary_ set to be the `x-default` per:

https://support.google.com/webmasters/answer/189077?hl=en

> The reserved value hreflang="x-default" is used when no other language/region matches the user's browser setting. This value is optional, but recommended, as a way for you to control the page when no languages match. A good use is to target your site's homepage where there is a clickable map that enables the user to select their country.

You're right that it appears this setting isn't respected in SEOmatic, however! Fixed in https://github.com/nystudio107/craft-seomatic/commit/b4fbe2db121ba26b7b2e80735fab6d18111ebcce

Thanks for the report!

Except in very rare circumstances, you almost always want to leave this setting on, though.
