### ISSUE TITLE
Changing Entry Type adds in "Source Field"

### ISSUE THREAD

**Issue by matthewmrotter** [nystudio107/craft-seomatic#697]
### Describe the bug
When you change the entry type, the "Source Field" dropdown is added even when "Custom Text" is selected.

### To reproduce
Steps to reproduce the behaviour:
1) New Entry (with a section that has SEOMatic enabled and multiple entry types. Ours has SEOMatic on its own tab).
2) Change Entry Type
3) Become sad and confused when "Custom Text" is selected but the "Source Field"  dropdown is still visible.

### Expected behaviour
Changing the entry type shouldn't affect the SEOMatic layout

### Versions
- Plugin version: 3.3.3
- Craft version: 3.4.19.1

**Comment by khalwat** [comment]
Ah this is very likely just a cosmetic issue, I think I know what is likely going on

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/b6ad668cb3d6b33fdc04b45f99b83121acf38f28
