### ISSUE TITLE
Adding seomatic within a gql query for a lot of entries will cause query timeouts.

### ISSUE THREAD

**Issue by enigmatix** [nystudio107/craft-seomatic#698]
### Describe the bug
First let me say thank you for adding the seomatic resolver to graphql for easy retrieval.  Conceptually it has made our lives much easier!

When fetching seomatic properties within a gql query, the query changes from being able to reliably return over 1000 results to 200 at best, otherwise the server times out before it can return a result (> 60 sec).  I expect this is due to heavy per page processing or some other dependency in the gql resolver.  Note that our query has been stripped back to just returning the seomatic fields for test purposes still cannot return mass results, so i don't expect a interaction issue with other resolvers or craft features.

While we will implement pagination to work around the issue, it would also be ideal to have this as performant as possible.

```
### To reproduce
query entries(
  $site: [String],
  $slug: [String],
  $relatedToAll: [Int]
) {
    entries(
    site: $site,
    slug: $slug,
    relatedToAll: $relatedToAll
  ) {
    id
    seomatic {
        metaTitleContainer
        metaTagContainer
        metaLinkContainer
        metaScriptContainer
        metaJsonLdContainer
    }
}
```

### Expected behaviour
The query should return in a relatively similar timeframe with the resolver included in the query.

### Versions
- Plugin version: 3.3.8
- Craft version:  3.4.23.1

**Comment by khalwat** [comment]
Yeah this isn't the intended use-case for the SEOmatic GraphQL API. It is intended so that you can get back the SEO data for a single entry.

What is your use-case here?

**Comment by enigmatix** [comment]
Thanks for the speedy reply @khalwat 

We're using craft as a headless CMS, and generating a static site via nuxt.js & GraphQL.  We have about 6000 pages we need to generate from around 1500 unique entries, using a 3-way multisite that shares content but is customised per global region.  Generating pages at this volume has a range of technical challenges including:
* speed
* memory
* server load
* caching
* ... some other thing that will come up after i pass this current hurdle

Fetching the seomatic data 1500 times for the pages presents us with the following issues:
* api load could potentially cause crashing
* memory management when generating due to axios/apollo/query overhead causes npm to consistently fail with out-of-memory errors (OOM)
* long generation times and a lot of opportunities for individual queries to fail due to load or other circumstance.

We can 'kind of' get around the issue by running the version of the query in the original message as a long-running query in console and then cache the result for access via the web.  At the moment, I do this via the web incrementing the 'limit' by 100 until i get to where i need to.  It's all a bit fragile.

Our goal is to fetch the full page payload as per the query above up front (probably paginated), including the seomatic data, so that we can compile those pages efficiently.  We need to minimise the live api calls as much as possible for both speed and preventing OOM errors

Nuxt has made some awesome progress in the last few months to their build and memory management, but sheer volume will always find a way to push limits and find bottlenecks!  

Perhaps if the tag meta was generated and stored in a field or similar (maybe a selectable option), a resolver would work more speedily.  Really just some form of cache would do it.

**Comment by khalwat** [comment]
@enigmatix SEOmatic does have a cache, but it will only be active in production environments (make sure `devMode` is off), and the cache is on a per-route basis. So the first time through, everything will be slow.

I don't have a great solution for you here except to do what you're doing, which is to paginate the queries.
