### ISSUE TITLE
Google console sitemap crawl - will it show 'successful' when using seomatic?

### ISSUE THREAD

**Issue by williamhn11** [nystudio107/craft-seomatic#699]
### Question
Hi - I am porting over a site from one environment to another and have purchased and am using seomatic on the new site. The old site had manual sitemaps, etc, and I was used to submitting to google manually. My question is on the new site - do I ALSO have to submit an overall sitemap.xml (placed in the root directory) or is this now "automatic". The reason for the question is that in google console it does not show that the sitemap(s) (in the new seomatic site) have been successfully crawled (as it did in the manual site)
Thanks!!
BTW where does seomatic put the sitemaps?!

**Comment by khalwat** [comment]
This is automatic now, you shouldn't need to manually submit the sitemap. Check out here for details:

https://nystudio107.com/docs/seomatic/Configuring.html#sitemap
