### ISSUE TITLE
hreflang tag 

### ISSUE THREAD

**Issue by daniellefrapp** [nystudio107/craft-seomatic#70]
For pages that are not entries the hreflang tag  is not correct for example for the blog index:

The German site the url is http://localhost.dev.applause.com/de/blog/ but the hreflang tag is 
<link href="http://localhost.dev.applause.com/es/de/blog" rel="alternate" hreflang="es">

Another issue I'm having is the not all blog posts will have a translate version. If they don't can the  hreflang tag just not appear? Currently they still do.

Lastly the site I'm working with has 4 languages  English (default en_US) German(DE), French(FR) and Spanish(ES). But only ES comes up in the hreflang tag is there a way to change that?

**Comment by khalwat** [comment]
It looks like your response was cut off; can you show me what the `hreflang` tag is?

**Comment by daniellefrapp** [comment]
Opps sorry about that. The hreflang tag is 
 
`<link href="http://localhost.dev.applause.com/es/de/blog" rel="alternate" hreflang="es">`
on this page: http://localhost.dev.applause.com/de/blog/

**Comment by daniellefrapp** [comment]
This problem appears to be constant with any page that is not an entry page.

**Comment by khalwat** [comment]
So I think I need to know more about your setup; I did a test locally and things appeared to be working as expected.

Can you show me what your `general.php` looks like? Or however your define all of your site URLs?

**Comment by daniellefrapp** [comment]
I attached the general.php

 but the sites are setup in craft here is a
screencap of the sites:
![screen shot 2018-04-17 at 10 38 20 am](https://user-images.githubusercontent.com/33430386/38885906-6475eb30-4242-11e8-84a8-0b26eb0825f6.png)


and here is a sreencap of my custom routes:

![screen shot 2018-04-17 at 10 39 18 am](https://user-images.githubusercontent.com/33430386/38885919-69eda30a-4242-11e8-9d2a-58687ab57e79.png)

​​

**Comment by khalwat** [comment]
hmmm... the screenshots and other info don't appear to be showing up here @daniellefrapp

**Comment by daniellefrapp** [comment]
@khalwat Can you see the screenshots now?

**Comment by daniellefrapp** [comment]
here is the general.php
```
<?php
return [
    // Global settings
    '*' => [
        // Default Week Start Day (0 = Sunday, 1 = Monday...)
        'defaultWeekStartDay' => 0,

        // Enable CSRF Protection (recommended)
        'enableCsrfProtection' => true,

        // Whether "index.php" should be visible in URLs
        'omitScriptNameInUrls' => true,

        // Control Panel trigger word
        'cpTrigger' => 'batman',

        // The secure key Craft will use for hashing and encrypting data
        'securityKey' => getenv('SECURITY_KEY'),
    ],

    // Dev environment settings
    'dev' => [
        // Base site URL
        'siteUrl' => null,

        // Dev Mode (see https://craftcms.com/support/dev-mode)
        'devMode' => true,
    ],

    // Staging environment settings
    'staging' => [
        // Base site URL
        'siteUrl' => null,
    ],

    // Production environment settings
    'production' => [
        // Base site URL
        'siteUrl' => null,
    ],
]
```;

**Comment by pauljohnston** [comment]
We have (what looks to be) the same issue where only the es alternate tag is showing

`<meta content="en-US" property="og:locale">`
`<meta content="es-ES" property="og:locale:alternate">`
`<meta content="it-IT" property="og:locale:alternate">`
`<meta content="ja-JP" property="og:locale:alternate">`
`<meta content="de-DE" property="og:locale:alternate">`
`<meta content="fr-FR" property="og:locale:alternate">`
`<meta content="en-US" property="og:locale:alternate">`
`<meta content="en-GB" property="og:locale:alternate">`
`<link href="http://mysite.dev/es/" rel="alternate" hreflang="es-es">`

Is there anything I can provide to help debug the issue?

**Comment by khalwat** [comment]
@pauljohnston This appears to be a different issue; I'll create a separate GitHub issue for you: https://github.com/nystudio107/craft-seomatic/issues/113

**Comment by khalwat** [comment]
Did you manage to get this sorted @daniellefrapp ?

**Comment by daniellefrapp** [comment]
Just checked looks like it's fixed. Thanks!

**Comment by Hanvandam** [comment]
Unfortunately this is closed - I have the same problem, on https://sailandbikeholland.com everything works fine, but in all languages except English, Google finds broken links ; in the SEOmatic rendered hreflangs, SEOmatic takes the current language as the x-default, so I see with double language- links like
link rel="alternate" hreflang="en" href="https://sailandbikeholland.com/nl/faqs 
nl : //sailandbikeholland.com/nl/nl/faqs 
de : //sailandbikeholland.com/de/nl/faqs 
es : //sailandbikeholland.com/es/nl/faqs 
fr : //sailandbikeholland.com/fr/nl/faqs
it : hreflang="it" href="https://sailandbikeholland.com/it/nl/faqs 
(I shortened the texts for it did not show up)
FAQ is on my website not en entry, but a section. Any idea how I can solve this ?
Greetings,
Han

**Comment by khalwat** [comment]
@Hanvandam it looks like your using Craft 2.x and the Craft 2.x version of SEOmatic; this repository and thread is for the Craft 3.x version of SEOmatic.

**Comment by Hanvandam** [comment]
That's right, Craft CMS 2.7.4 and SEOmatic 1.1.56.
Problem unsolvable or can I find a solution anywhere ? ....
