### ISSUE TITLE
Twitter cards not using the focal point when preview in the Content Settings

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#700]
### Describe the bug
I am seeing an issue in the content settings in SEOmatic on twitter cards that appear to not use the focal-point setting for cropping images. 

This is in the Content SEO > Entry  · Twitter

Screenshots best illustrate this;

Twitter Not Honouring Focal Point
<img width="1582" alt="Screenshot 2020-07-28 at 19 31 20" src="https://user-images.githubusercontent.com/5698596/88706568-efb85500-d108-11ea-934b-8084576ca73b.png">

Facebook is ok:
<img width="1000" alt="Screenshot 2020-07-28 at 19 27 26" src="https://user-images.githubusercontent.com/5698596/88706660-0fe81400-d109-11ea-9299-0c7f54d0b140.png">

The Page/Render is ok and the actual image is ok:
<img width="720" alt="Screenshot 2020-07-28 at 19 33 44" src="https://user-images.githubusercontent.com/5698596/88706862-589fcd00-d109-11ea-8d2a-512e03342c47.png">
<img width="1579" alt="Screenshot 2020-07-28 at 19 32 36" src="https://user-images.githubusercontent.com/5698596/88706864-5a699080-d109-11ea-886d-ccf50e987a3f.png">

**Comment by khalwat** [comment]
@terryupton can you give me the image you're using so I can attempt to reproduce it here?

Is the correct image used on the frontend, and the issue is only the previews?

**Comment by terryupton** [comment]
@khalwat - I have dropped this over to you in Discord.

Yes it was only the previews on the content settings area, as they show ok on the entry preview and the entry sidebar and on the front-end. It was on Twitter too. Not Facebook.
