### ISSUE TITLE
turn off Automatic Render Enabled and render scripts manually

### ISSUE THREAD

**Issue by kos76** [nystudio107/craft-seomatic#701]
### Question
If I disable Automatic Render Enabled in the admin panel
and in the code in the <head> tag I add scripts, for example
{% do seomatic.script.render ()%}
{% do seomatic.link.render ()%}
no scripts are displayed
When Automatic Render Enabled is enabled, they are displayed correctly
What could be the reason?

### Additional context
    <head>
        <link rel="dns-prefetch" href="//maps.googleapis.com" />
        <link rel="dns-prefetch" href="//www.googletagmanager.com" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"/>
        <meta name="referrer" content="origin-when-cross-origin"/>
        {% include '/thirdPartySnippet/headBlock.html' %}
        <meta property="og:type" content="website">
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="630">
        <link rel="shortcut icon" type="image/png" href="/dist/img/favicon.png"/>
        <link rel="preload" as="image" href="/dist/img/preloader.gif">
        {% do seomatic.script.render() %}
        {% do seomatic.link.render() %}
        {{ sentryScript() }}
        {{ head() }}
    </head>

**Comment by khalwat** [comment]
So you need to output them like this:

```twig
{{ seomatic.script.render() }}
{{ seomatic. link.render() }}
```

Using `{% do %}` executes the function, but never outputs anything.
