### ISSUE TITLE
Allow me to exclude channels from SEOmatic

### ISSUE THREAD

**Issue by zenbug** [nystudio107/craft-seomatic#702]
SEOmatic tells me my setup is incomplete unless I configure every section, but some sections are effectively categories and will never be displayed as content that would require its own SEO.

It would be great if I could tell SEOmatic to ignore certain sections.

**Comment by khalwat** [comment]
If the section doesn't have URLs, then SEOmatic won't be active for it. If the section has URLs, then someone will hit it on the frontend, so it should be configured.

Turn off URLs for your categories, and you should be good to go!

**Comment by zenbug** [comment]
I had a feeling I'd learn that this is a non-issue and also that I'd learn something. 

Thanks as always, Andrew!
