### ISSUE TITLE
Error 400 "Bad Request" on Craft actions when SEOmatic is enabled. No errors when SEOmatic is disabled.

### ISSUE THREAD

**Issue by adamtsai1** [nystudio107/craft-seomatic#704]
Hi, this is an odd issue I am running into that I hope someone can help me navigate. I am experiencing a bug in Craft when performing ajax actions (like saving entries, opening modals, etc.) that comes back as an error 400. The client recently upgraded Craft and many of its plugins, so I began disabling plugins one by one until I narrowed it down to SEOmatic; once I disabled SEOmatic, everything began working correctly. When I re-enabled it, the errors came back. One odd thing we noticed is that if we delete the cookie named CRAFT_CSRF_TOKEN, the error goes away. This is unusual because we've disabled csrf protection in the Craft config. Any guidance on things to check/try would be greatly appreciated. The client is on seomatic version 3.3.8 and Craft 3.4.26. Thanks!

**Comment by khalwat** [comment]
@adamtsai1 Can you update to the latest SEOmatic (which is at [version 3.3.13](https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.13) currently), clear your caches, and let me know if this issue persists?

Can you show me the actual errors form your logs? More info on that here:

https://nystudio107.com/blog/zen-and-the-art-of-craft-cms-log-file-reading

**Comment by adamtsai1** [comment]
@khalwat I've updated to 3.3.13 and cleared caches, but the issue persists.

Thanks for the info on the Craft logs. Unfortunately it doesn't appear as though any useful errors have been logged, unless I'm looking in the wrong place: https://prnt.sc/ttbykt.

**Comment by khalwat** [comment]
I mean look directly in your `storage/logs/web.log`

**Comment by khalwat** [comment]
@adamtsai1 It's pretty likely this is going to end up being some kind of environment or server setup issue.

Are you able to replicate it in local development or in staging or other environments?

**Comment by adamtsai1** [comment]
[web.log](https://github.com/nystudio107/craft-seomatic/files/5023500/web.log)

**Comment by adamtsai1** [comment]
@khalwat Yes I forgot to mention this, but the error is happening in both production and staging, but not my local VM. So I think you are probably right. Do you have any ideas on how I might troubleshoot this?

**Comment by khalwat** [comment]
Here's what I need you to do. As per:

https://nystudio107.com/blog/zen-and-the-art-of-craft-cms-log-file-reading

...delete all of your logs in `storage/logs/` -- then make the problem happen, and then add all of the logs generated here so I can see them.

As for diagnosing it, it's likely going to be a server config issue of some sort, so it'll depend on what stack you're using. My guess is that this problem won't end up being specific to SEOmatic.

**Comment by adamtsai1** [comment]
That log I linked to is the result of the process you described. I did skim through it and did not see anything that seemed suspect, but maybe there's something in there that will catch your eye. What else can I provide at this point that might give any insight into what could be causing this?

**Comment by khalwat** [comment]
There should be more than one log, though -- are you saying there's no `web-404s.log` or other log files in there?

**Comment by adamtsai1** [comment]
We have queue.log, web-404s.logs, and workflow.log, but none of them produced any new entries as a result of the error.

**Comment by khalwat** [comment]
As per the above... and you please send me _all_ of these logs after deleting them all, then performing the action that makes the wrong behavior happen, and then attach them all here?

**Comment by adamtsai1** [comment]
Ok, here's what we came up with. Thanks for your patience.

[web.log](https://github.com/nystudio107/craft-seomatic/files/5036929/web.log)
[web-404s.log](https://github.com/nystudio107/craft-seomatic/files/5036930/web-404s.log)
[workflow.log](https://github.com/nystudio107/craft-seomatic/files/5036931/workflow.log)

**Comment by khalwat** [comment]
Do you have a live URL I can look at?

**Comment by adamtsai1** [comment]
Unfortunately this only appears to be happening in the Craft admin. I can see if the client would be willing to grant access.

**Comment by khalwat** [comment]
This is going to end up being some kind of a configuration error on the production server. If you want me to have a look at it, ping me on the Craft Discord or email me at info@nystudio107.com and we can arrange a time.

**Comment by theskyfloor** [comment]
Did anyone every figure this out? Cant prove it is SEOmatic but having similar issues.

**Comment by khalwat** [comment]
@theskyfloor disable SEOmatic and see if the issues persist.

I don't think this is going to end up being an issue with SEOmatic, because it doesn't do anything with requests but I'd be happy to help you figured out what's going on.

 If you want me to have a look at it, ping me on the Craft Discord or email me at info@nystudio107.com and we can arrange a time.

**Comment by theskyfloor** [comment]
Thanks! I will try it out and let you know.

**Comment by adamtsai1** [comment]
@theskyfloor For some reason this started working for us in both staging and production, though apparently no changes were made on the server configurations. The IT guy says CSRF protection has been turned off in both environments this whole time, so I'm not sure what has changed. I will follow up if I discover any new information.

**Comment by khalwat** [comment]
Small side note @adamtsai1 -- would recommend that CSRF protection be on in general. If there were issues you ran into with it being on, I'd recommend working through them.

**Comment by stigzelm** [comment]
Hello, 

We are having this exact same issue on one of our projects.

When SEOMatic is enabled we are getting the error "400 - Your browser sent an invalid request." on all of the ajax requests in admin (saving, queue handling, image modal opening).

When SEOMatic is disabled we do not get this error.

Also we noticed that when you clear your browser data and login again it works for a while, but then it always comes back after a while.

So this seems to have something to do with either the sessionID or the CSRF token being invalid, but I have no idea why this only happens when SEOMatic is enabled.

Any idea?

**Comment by khalwat** [comment]
@stigzelm As per my email reply, I believe this will very likely end up being something devops related in your setup, and not an issue in SEOmatic. I've been unable to find any evidence that SEOmatic is causing the issue, but I do believe that it is probably bringing the problem to the fore.
