### ISSUE TITLE
Sitemap Limit

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft-seomatic#705]
![8vwv3pk](https://user-images.githubusercontent.com/1551388/89231174-9bc8d700-d606-11ea-96c9-627ee96f5a61.png)

what is the solution to comply with google's standards? Section has over 500k entries.

I'm aware of the recommendation to include only new entries in the sitemap by setting the limit in content options but that's not the solution I am looking for.

Thanks.

**Comment by khalwat** [comment]
@EmptyStreets that's the only solution I'm aware of. SEOmatic already minimizes the sitemaps... and it already divides them up into separate SiteMap Indexes... so you're just coming up against a hard limit from Google.

You can turn off:

- Include Images & Videos in Sitemap
- Include Indexable Files in Sitemap
- Sitemap Alt URLs

but really, the right solution is just have a hard limit on the number of entries in the sitemap. SEOmatic always lists the newest entries first, which is what you want. It makes Google re-crawl the new/updates content.

Having every single item in the sitemap is largely a pointless exercise, as the sitemap will get so large that GoogleBot will expend all of its crawl budget long before it gets to the end of the sitemap.

Pages that aren't in the sitemap don't fall out of the Google Index at all, so...
