### ISSUE TITLE
PHP error when using a non-native queue runner

### ISSUE THREAD

**Issue by angrybrad** [nystudio107/craft-seomatic#706]
### Describe the bug

[This feature](https://github.com/nystudio107/craft-seomatic/issues/528]) only works with Craft's native queue runner because the code is manually calling `$queue->release()` here: https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/SitemapTemplate.php#L127

`release()` is part of Craft's [QueueInterface](https://github.com/craftcms/cms/blob/develop/src/queue/QueueInterface.php#L51)

If you've configured Craft to use any other Yii 2 [queue based drivers](https://github.com/yiisoft/yii2-queue/tree/master/src/drivers), you'll get an error:

> yii\base\UnknownMethodException: Calling unknown method: yii\queue\sqs\Queue::release()

You could check if the configured queue implements QueueInterface, which would make the feature only work with Craft's native queue runner.  There is already precedent for this in Craft because you already lose the progress/UI in the Craft control panel if you're using a non-native driver.

### Versions
- Plugin version: Latest
- Craft version: 3.x

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/32fb75f822287df35bdf1ba0a4a13e8618159eb2
