### ISSUE TITLE
Large amounts of cache files

### ISSUE THREAD

**Issue by jripmeester** [nystudio107/craft-seomatic#708]
Lately i've been getting lots of inodes suspension on a server as i'm over 2.000.000 inodes.
Some digging around led me to the cache folder of craft of on of our websites which currently holds 1.6 milj files spread over different folder. I've not checkt them all obviously but randomly checkt a lot of them and they all seemed to be meta cache for SEOmatic. After some reading i've found that SEOmatic cache the meta data on a uri basis. But the website only has about a 1000 pages. So i got wondering that maybe that query strings from marketing campagnes may be the cause, but i can't find a setting to ignore the query string.

I'm probably doing something wrong but i don't really know where to start looking. So my question: does this scenario ring a bell? What causes it and how to prevent the large amount of cache files.

### Additional context
Craft CMS 3.4.27
SEOMatic 3.3.9

**Comment by khalwat** [comment]
Query strings don't factor into the SEOmatic cache -- but if you have a large amount of URLs, I'd suggest moving away from the default file-based cache, and using Redis instead:

https://craftcms.com/docs/3.x/config/#redis-example-2
