### ISSUE TITLE
Include an option to exclude pages set to noindex from the sitemap

### ISSUE THREAD

**Issue by andypullen** [nystudio107/craft-seomatic#709]
In order to create a page that is not indexible by search engines, we set robots for the page to noindex or none. However, since we submit the sitemaps to search engine webmaster tools, they will find the page and return errors due to the noindex value.

It would be ideal to either globally or maybe per page set whether the page is included in the sitemap if noindex or none is set on Robots.

**Comment by khalwat** [comment]
SEOmatic already does this -- for each item in the sitemap, it looks to see if Robots is set to `none` and if so, it doesn't include it in the sitemap on a per-entry basis:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/jobs/GenerateSitemap.php#L145

It also does this for the sitemap indexes, so if you have robots set to `none` via Content SEO, it'll exclude that entire section:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/SitemapIndexTemplate.php#L155

Can you show me how to reproduce a case where this isn't working?

**Comment by andypullen** [comment]
I may have my templates or SEOmatic settings misconfigured, but here's what I've tried. Initially, I set a template to run `{% do seomatic.meta.robots("none") %}` which successfully sets the robots meta value to none, and it's after that that Google Webmaster Tools sent an error because the page was submitted in the sitemap but set to not index. I've since also explicitly turned off Robots in the SEO field on the page, and the page no longer shows up in the sitemap as expected.

The page URL is https://willamette.cc/posts/updates/fall-2020-plans and the sitemap section is https://willamette.cc/sitemaps-4-section-posts-2-sitemap.xml if you want to take a look.

(edited: my mistake – explicitly turning off Robots in the SEO field does remove the page from the sitemap as expected)

**Comment by khalwat** [comment]
Okay I see, you're doing it via template. Unfortunately, that won't work for keeping it out of the sitemap, you'd need to use the Content SEO settings and/or an SEO Settings field in the section to do it.

**Comment by andypullen** [comment]
Thanks – I see that now. That would, however, still be my enhancement request :)

Cheers!

**Comment by khalwat** [comment]
I'm not even sure how it'd be possible -- at the time when the sitemap is generated, the Twig template you wrote that set it to `none` isn't being rendered or accessed at all.

I'm not even sure how that'd work, honestly.
