### ISSUE TITLE
Google Analytic Firing with Preview URL

### ISSUE THREAD

**Issue by masonry47** [nystudio107/craft-seomatic#710]
Hi there!

We were wondering if there is a way to prevent GA from tracking on preview links.   We know that it does not render when using "Live Preview" within the entry, but it does seem to fire when using a preview link to view a disabled page or a draft of page by clicking the "Share" > Primary Entry Page button in the entry.  And Craft adds the /?x-craft-preview=MHl3IynoC2&token=DfeIDmfV0a7ZcFCYCmi2S35e2UVzYr7B query string to allow for viewing.  

Thanks a bunch!

- Plugin version: 3.3.3
- Craft version: 3.4.19.1

**Comment by khalwat** [comment]
@masonry47 can you please update to the latest version of SEOmatic, and let me know if the issue is resolved? 

The current version is 3.3.13

**Comment by masonry47** [comment]
Thanks, just updated and still seems to be firing with the preview link.  Thanks!

**Comment by khalwat** [comment]
Can you please paste in here what you have set for the GA script? The default is:

```twig
{% if trackingId.value is defined and trackingId.value %}
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','{{ analyticsUrl.value }}','ga');
ga('create', '{{ trackingId.value |raw }}', 'auto'{% if linker.value %}, {allowLinker: true}{% endif %});
{% if ipAnonymization.value %}
ga('set', 'anonymizeIp', true);
{% endif %}
{% if displayFeatures.value %}
ga('require', 'displayfeatures');
{% endif %}
{% if ecommerce.value %}
ga('require', 'ecommerce');
{% endif %}
{% if enhancedEcommerce.value %}
ga('require', 'ec');
{% endif %}
{% if enhancedLinkAttribution.value %}
ga('require', 'linkid');
{% endif %}
{% if enhancedLinkAttribution.value %}
ga('require', 'linker');
{% endif %}
{% set pageView = (sendPageView.value and not seomatic.helper.isPreview) %}
{% if pageView %}
ga('send', 'pageview');
{% endif %}
{% endif %}
```

The `seomatic.helper.isPreview` should be handling things correctly here:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/Helper.php#L85

**Comment by masonry47** [comment]
Well, we are just using the tracking settings within the plugin to output GA.

**Comment by khalwat** [comment]
@masonry47 right -- can you show me what is in the settings for that? I'm trying to see if maybe you have old code in there

**Comment by masonry47** [comment]
All we are doing is going to seomatic > tracking scripts and enabling Google gtag.js and then placing the google tracking ID in the proper field.  We have nothing custom in the template.  Sorry if I am not following you on this.  Thanks!

**Comment by khalwat** [comment]
Can you take a screenshot of what this page looks like for you? Scroll to this same position, so I can see the scripts please

<img width="1524" alt="Screen Shot 2020-08-15 at 11 41 01 PM" src="https://user-images.githubusercontent.com/7570798/90326000-cf81f600-df50-11ea-8808-ee75fd09ab58.png">

**Comment by khalwat** [comment]
@masonry47 I've added some addition logic in https://github.com/nystudio107/craft-seomatic/commit/6c9be383bdf6843246314a64e667e8a7540dc9ad

But I tested all permutations of previews/non-previews, and it's working as expected.

Please update to version 3.3.16

**Comment by matthewmrotter** [comment]
We updated this line to make sure it didn't fire if the x-craft-preview  param is present: 

`{% set pageView = (sendPageView.value and not craft.app.request.isLivePreview and not craft.app.request.getParam("x-craft-preview")) %}`

and that seemed to fix it

**Comment by matthewmrotter** [comment]
We are running into an issue with caching though. When you view the page using that x-craft-preview it'll cache the "send page view" variable to false. When you view the live page that will still be set to false until you clear the cache. Is there any way to not set the seoMatic cache when that param is present?

**Comment by khalwat** [comment]
@matthewmrotter I think you actually found the bug. SEOmatic's check already does the equivalent of what you're doing via Twig... so you shouldn't need to modify it. `{% if seomatic.helper.isPreview %}` already does the checks you mention.

The issue is that it's getting cached... so what should _really_ happen is that if the request is any type of preview request, it shouldn't get cached.

Everything worked as expected in my tests, because I was doing them in local dev, where the caches only last 30 seconds.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/444cdac02324585c405e09538d7351429af46a8d
