### ISSUE TITLE
All Sitemap Tasks are failing

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft-seomatic#711]
### Describe the bug
All our Sitemap Tasks are failing:
![image](https://user-images.githubusercontent.com/764292/89473529-5f6eb580-d783-11ea-94d5-809d5cd997f3.png)

### Versions
- Plugin version: 3.3.11
- Craft version: 3.4.29.1

**Comment by khalwat** [comment]
That would mean that the passed in `siteId` doesn't appear to have a `siteGroup` -- which I'm not sure how that could even happen, but you might want to have a look at it.

I've handle the error more gracefully here tho: https://github.com/nystudio107/craft-seomatic/commit/36a1b87315284e8dd03cf49c57d8e99049259dd3

**Comment by davidhellmann** [comment]
@khalwat changed this one file on our Stage Env. Looks finde, fix it for live with the new SEOmatic release. Thank you!
