### ISSUE TITLE
Noindex, nofollow Entries in sitemap

### ISSUE THREAD

**Issue by maximilian-schwarz** [nystudio107/craft-seomatic#712]
### Describe the bug
If you set a entry to noindex,nofollow the entry is shown in the sitemap.
I think this is not the best practice.

### To reproduce
Steps to reproduce the behaviour:
1. Choose any entry
2. Set entry to noindex, nofollow

### Expected behaviour
If i set a entry to noindex,nofollow the entry isn't in the sitemap.

**Comment by khalwat** [comment]
@Maximilian-Schwarz How are you setting this entry to `noindex,nofollow` exactly? If you set it to `none` either in Content SEO or via an SEO Settings field, it will not include it in the sitemap.

https://github.com/nystudio107/craft-seomatic/blob/v3/src/jobs/GenerateSitemap.php#L146

**Comment by khalwat** [comment]
Will re-open if additional information is given

**Comment by ItagMichael** [comment]
I'm also observing this problem. Site is running Craft 3.4.30, plugin version 3.3.18.

The entry has an SEO Settings field, with the robots value set to None (also tried No index,) yet still appears in the XML sitemap.

**Comment by khalwat** [comment]
@ItagMichael Could there be something more going on here? 

I've tried to reproduce this, but thus far have been unable to do so. Can you show me screenshots of your Global SEO, Content SEO, and SEO Settings field for the Robots settings?

Is there more than one SEO Settings field in this entry perhaps?

**Comment by ItagMichael** [comment]
Thanks @khalwat. Only one SEO field on the entry.

Not at all conclusive, but after messing with it briefly it appears the Content SEO level influences the sitemap but the entry level settings do not. Setting the content level to 'None' removes every entry from the sitemap. Setting an individual entry back to 'All' does not override this for that entry. Unless I am misunderstanding something I would expect that it should.

Screenshots at their original settings:

**Global**
<img width="243" alt="seo-global" src="https://user-images.githubusercontent.com/12288422/96390101-59229e00-11f6-11eb-9e5b-aebd5a58d229.png">

**Content**
<img width="216" alt="seo-content" src="https://user-images.githubusercontent.com/12288422/96390104-5e7fe880-11f6-11eb-8525-75c380e54b87.png">

**Entry**
<img width="278" alt="seo-entry" src="https://user-images.githubusercontent.com/12288422/96390105-60e24280-11f6-11eb-971d-5203821a3f1e.png">

**Comment by ItagMichael** [comment]
@khalwat Just wanted to bump this one, can you let me know if I've done something wrong based on the above screenshots?

**Comment by khalwat** [comment]
@ItagMichael sorry, yes, if you set it to `none` at the Content SEO level, you cannot then selectively turn it on for just a few entries currently.

The reason is that when a request for a sitemap comes in, that's for an entire section, and it can't know ahead of time whether despite it being disabled, it is then re-enabled for just a few entries.

The work-around for now is to enable it at the Content SEO level, and use the field to selectively disable entries you don't want in the sitemap.

**Comment by ItagMichael** [comment]
Hi @khalwat ,

Sorry if I'm confused here, but what you describe appears to be the opposite of my goal & the screenshots.

I'd like to hide entries from the sitemap that are set to None on the entry level. In the above screenshot the content level is set to All, and the entry is set to None, yet still appears in sitemap.

**Comment by khalwat** [comment]
What you're trying to do should definitely work @ItagMichael -- I've replicated it in a local testing environment.

Shall we set up a time to screen share and have a look at what might be going on here?

**Comment by juddlyon** [comment]
I have the same issue for Category pages: set to noindex via a field but showing up in the XML sitemap. I noticed the Category Group is duplicated under CONTENT SEO so maybe that's a hint? I try to fix that in the DB first and will report back.

**Comment by joshuapease** [comment]
Running into the same issue (I think). 

We don't have any custom Sitemap settings. So by default, all of our entries are showing up in the sitemaps. 

However, we have a SEO Settings field on all of these entries. 

Even though we set that field to Robots: `none` or `noindex`, the entry still appears in the sitemap. 

However, I enabled the Sitemap tab, and played around with enabling / disabling the entry in the sitemap. After doing that a bit, the Robots: `none` or `noindex` flag started working as expected. Not quite sure why. 

Happy to set up a time to screenshare. 

![image](https://user-images.githubusercontent.com/2145998/117742539-dbd27100-b1b9-11eb-9a0f-2d45615a3dd3.png)

**Comment by turnstylerj** [comment]
We just had a client reach out to us about this same issue. Will use the sitemap settings workaround @joshuapease posted, but it seems like setting robots to noindex or none in the SEO Settings field on each entry should automatically exclude the entry from the sitemap, correct?

@joshuapease's experience with this behavior fixing itself after playing with the Sitemap tab and playing with the toggle seems like there may still be a bug here.

**Comment by khalwat** [comment]
@turnstylerj can you file a new issue with complete details please?
