### ISSUE TITLE
Unable to set Canonical URL to environment variable

### ISSUE THREAD

**Issue by markmiddleton** [nystudio107/craft-seomatic#713]
### Describe the bug
In the settings "Global SEO" -> "General" -> "Canonical URL"  The field is populated with the local site URL, but cannot be changed manually to a different value, or be set to an .env variable.

### To reproduce
1. Go to "Global SEO" -> "General" -> "Canonical URL" 
2. Set the value of the field to an ENV variable, for example $CANONICAL_URL, then save the settings
3. The value is not stored and is reverted to the default site url.

### Expected behavior
After entering a valid ENV variable name and saving the settings, we would expect to see that variable name in the settings, and the value of that URL to be populated in the meta information on the front end.

### Versions
- Plugin version: 3.3.12
- Craft version: 3.4.30

**Comment by khalwat** [comment]
Wow, that was a weird one. Fixed in https://github.com/nystudio107/craft-seomatic/commit/e4b3184a5634432155a699860c8cf23b93e019a6
