### ISSUE TITLE
Hide title separator character when no title is provided

### ISSUE THREAD

**Issue by Wiejeben** [nystudio107/craft-seomatic#715]
### Is your feature request related to a problem? Please describe.
When a page does not have a title, I would like the websites name to be shown without the separator.

### Describe the solution you would like
Current situation without a title: "| Buffalo Hides" but what I would like to see is just "Buffalo Hides"

### Describe alternatives you have considered
I would overwrite the title, however with GraphQL there is no indicator whether the provided title is empty, especially with the title prefixes.

### Additional context
Headless website, calling SEOmatic on every page even if its a 404. 404's don't have a title currently so the title becomes "| Buffalo Hides". I could filter out all of the prefix icons and check if the first character matches the title separator and if that's true trim it off.

**Comment by khalwat** [comment]
Changed in https://github.com/nystudio107/craft-seomatic/commit/d29278e85cf25db5a07e5d6d56bd3adbb0907f10

**Comment by Wiejeben** [comment]
Thanks for implementing this so quickly!

When testing 3.3.14 the title now disappears when no title is provided (instead of just showing the site name), only the prefix remains being added. This is both in the preview as on the actual page.

Craft 3.5.2 on PHP 7.2

**Comment by khalwat** [comment]
@Wiejeben can you give me a screenshot or example of what you mean please?

**Comment by Wiejeben** [comment]
With title it works fine:
![Screenshot 2020-08-11 at 13 56 41](https://user-images.githubusercontent.com/2922378/89894590-9e18cb80-dbda-11ea-93a9-a4f9ff0d4519.png)

Without title it looks like this:
![Screenshot 2020-08-11 at 13 56 50](https://user-images.githubusercontent.com/2922378/89894618-aa048d80-dbda-11ea-9224-fe1fa41b4265.png)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/fa43f698d62776da527abcc3ad20d1e82ec47d07
