### ISSUE TITLE
Expected a value of type \"String\" but received: instance of nystudio107\\seomatic\\models\\MetaBundle

### ISSUE THREAD

**Issue by satcreative** [nystudio107/craft-seomatic#716]
I have recently upgraded from the [SEO](https://github.com/ethercreative/seo) plugin to the SEOmatic. I have assigned an SEOmatic field to all entries and defined the Global/Content/Entry level SEO. However I am now seeing an error in my GraphQL playground, which is resulting in a failed build of my Gatsby site. 

When I query the SEOmatic field on most entry types I get the error `Expected a value of type \"String\" but received: instance of nystudio107\\seomatic\\models\\MetaBundle`. Although this is not the case with one particular entry type, which instead delivers the SEOmatic data correctly. I thought this might be, as this particular entry type has been newly added and never had the old SEO plugin applied to it. However I have made a new 'test' entry type, to see if this is the case, and that is also giving the error message. 

Below are screenshots of my query and the output they generate in the GraphQl playground:

![Screenshot 2020-08-10 at 10 07 14](https://user-images.githubusercontent.com/12640985/89767945-d04efe00-daf2-11ea-953e-6039e73eb185.png)
![Screenshot 2020-08-10 at 10 18 45](https://user-images.githubusercontent.com/12640985/89768190-33409500-daf3-11ea-9cb3-2994fe4dc692.png)

Below is a screenshot of the error in my terminal when trying to build the Gatsby site:

![Screenshot 2020-08-10 at 10 24 05](https://user-images.githubusercontent.com/12640985/89768628-c083e980-daf3-11ea-8620-7c6a7fc07c68.png)

Any ideas why some entries wouldn't be looking for the SEOmatic Metabundle?

### Versions
SEOmatic - 3.3.13
Craft CMS Pro - 3.4.27
--

**Comment by khalwat** [comment]
Perhaps you have an SEO Settings field named `seomatic` ? You'll need to rename that field and its field handle for the this to work as expected.

**Comment by satcreative** [comment]
Yeah, that was the issue. Thanks
