### ISSUE TITLE
Initializing tracking scripts through a callback function

### ISSUE THREAD

**Issue by dyerc** [nystudio107/craft-seomatic#719]
### Question
I need to support a cookie opt-in notice and I have seen the other information / examples surrounding this use case where the cookie is checked before adding the tracking scripts to the page. Such as:

```
{% if craft.cookies.get('cookiesAccepted') != 'true' %}
  {% do seomatic.script.container().include(false) %}
  {% do seomatic.script.container().clearCache(true) %}
{% endif %}
```

What I would ideally like to facilitate is the tracking scripts loading immediately after the user opts-in, rather than waiting for them to trigger a page reload. Something along the lines of:

```
<head>
<script>
window.seomaticScripts = function() {
  {{ seomatic.script.callback() }}
  // Google Analytics would load here along with any other scripts
};

if (optinCookieSet()) {
  seomaticScripts();
}
</script>
</head>
```

Then once the user opts-in within my notice I could call `seomaticScripts()` to load them immediately. It would also remove the cache-busting necessity because the cookie checking is offloaded to JavaScript.

Can you see any issues with an approach like this? Would it be a useful feature for SEOmatic or is it something you've discounted in the past as not being the best solution?

**Comment by khalwat** [comment]
So this is something that it's already possible for you to do on your own if you want, either via code, or via editing the Twig in the SEOmatic Tracking Scripts settings.

Another approach many people take is they use Google Tag Manager, which SEOmatic can load for you, and then they use it to handle all of the machinations described above.

That being the case, I'm not sure it makes sense to bake it into SEOmatic. The Tracking Scripts are really there just to make it simple for the base case.

**Comment by kevinmu17** [comment]
> Another approach many people take is they use Google Tag Manager, which SEOmatic can load for you, and then they use it to handle all of the machinations described above.

This approach has GDPR implications. GTM is not allowed to load in certain countries (Germany for instance) so we need total control in loading trackings scripts after consent is given. Can you point us in the right direction how to get all the trackings scripts by code? Can't find it in the docs :)

PS: we really love this plugin, the amount of work (& probably love) you put in is out of this world! We are now using it in our scaffold build as default! Thanks for this!

**Comment by khalwat** [comment]
By editing the Twig code that appears on the SEOmatic -> Tracking Scripts -> Google Tag Manager page

**Comment by kevinmu17** [comment]
I see, looking with my eyes closed XD thanks!!
