### ISSUE TITLE
Change helper.paginate behaviour for canonical

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#720]
### Is your feature request related to a problem? Please describe.
As you can see on [this guide](https://www.searchenginejournal.com/technical-seo/pagination/) (Paragraph "Canonicalize to the First Page"), SEOmatic seems to use a wrong SEO strategy for paginated pages by setting the canonical URL to the first page.

### Describe the solution you would like
As said in the guide linked above, the canonical URL should be the paginated page itself and not the first page.
What do you think about making this as a default behavior ?

**Comment by khalwat** [comment]
Here's the receipts for how we ended up where we landed on the way it works now: https://github.com/nystudio107/craft-seomatic/issues/375#issuecomment-488369209
