### ISSUE TITLE
Character indicator in wrong position in Settings

### ISSUE THREAD

**Issue by darylknight** [nystudio107/craft-seomatic#722]
### Describe the bug
Under all settings windows (as an example, SEOmatic > Global SEO > General) the 'characters remaining' indicator is in the wrong position:

![image](https://user-images.githubusercontent.com/1250017/90486499-b55b3a00-e141-11ea-835b-c962d613c316.png)

### Versions
- Plugin version: SEOmatic 3.3.16
- Craft version: 3.5.5

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/c426911a9f6574073aeadd054427c06d1a5b0963
