### ISSUE TITLE
Cannot override custom attributes

### ISSUE THREAD

**Issue by seamusmh** [nystudio107/craft-seomatic#723]
### Describe the bug
I am attempting to force an entry template to use a related entry's SEO image instead of it's own. I've tried the following, all to no avail.

{% for podcast in entry.relatedPodcast.all() %}
	{% do seomatic.meta.seoImage(podcast.seo.metaGlobalVars.seoImage) %}
{% endfor %}

-------

{% set seoimg = '' %}
{% for podcast in entry.relatedPodcast.all() %}
	{% set seoimg = podcast.seo.metaGlobalVars.seoImage %}	
{% endfor %}
{% do seomatic.meta.seoImage(seoimg) %}

-------

{% set seoimg = '' %}
{% for podcast in entry.relatedPodcast.all() %}
	{% set seoimg = podcast.seo.metaGlobalVars.parsedValue('seoImage') %}	
{% endfor %}
{% do seomatic.meta.seoImage(seoimg) %}

-------

{% set seoimg = '' %}
{% for podcast in entry.relatedPodcast.all() %}
	{% set seoimg = podcast.seo.metaGlobalVars.seoImage %}	
{% endfor %}

 {% do seomatic.meta.setAttributes({
            seoImage: seoimg,
            canonicalUrl: siteUrl,
            twitter: {
                image: seoimg
            },
            og: {
                image: seoimg,
            }
        }) %}

###
What is the most efficient way to handle this situation? Each podcast show will get a custom SEO image and I want it to cascade down to all related episodes so they don't need to add it on a show by show basis.

### Versions
- Plugin version: 3.3.14
- Craft version: 3.5.4

**Comment by khalwat** [comment]
Any of these things should work -- have you cleared the cache? in local dev, the cache only last 30 seconds, so you should see the changes pretty quickly.

**Comment by khalwat** [comment]
Happy to walk you through this if you like, but this type of thing definitely works... my guess is it's just a caching issue as mentioned above.

**Comment by seamusmh** [comment]
Very well could wind up being cache, this is a big complex site. Seems like half the time cache is part of the problem. 

In this case, it seems like something else is stopping "do seomatic.meta" from doing it's thing. But I'll do some more tests and figure out what is getting in the way and report back if there is something notable. 

Thanks for verifying that it _should_ work.
