### ISSUE TITLE
Character count in SEOmatic fields is overlapping text

### ISSUE THREAD

**Issue by danystad** [nystudio107/craft-seomatic#724]
Since updating sites to Craft 3.5, the character count on the SEOmatic fields is off to the left and overlapping the text content of the fields. This is the case in both the SEO Settings Field and in the Content SEO section.

![seomatic_character_count](https://user-images.githubusercontent.com/869009/90691865-54129400-e231-11ea-9199-6ea5e549e1cc.png)

- Plugin version: SEOmatic 3.3.16
- Craft version: 3.5.5

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/c426911a9f6574073aeadd054427c06d1a5b0963
