### ISSUE TITLE
Sudden errors on /sitemap.xml and unable to resolve.

### ISSUE THREAD

**Issue by cjativa** [nystudio107/craft-seomatic#725]
### Describe the bug
Hi -- I am unsure if this is a bug or a support request, but our sitemap.xml is unavailable at http://barnesfoundation.org/sitemap.xml.

You can see the error in the screenshots section, but it indicates 
```
This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.
```

There's no further error messages indicating what is wrong with the file, nor anything being logged in the web.logs/queue.logs of the craft folder. I've run the CLI command `./craft seomatic/sitemap/generate` to regenerate the sitemaps, to no avail. The command never displays an error and completes normally, but the sitemap.xml displays the same error text. 

It may be that only that general sitemap.xml file is corrupted/unusable, as I can access the section sitemaps, like this one 
https://barnesfoundation.org/sitemaps-1-section-exhibition-1-sitemap.xml, but I'm unable to get that sitemap.xml to be regenerated properly.

I've tried disabling and re-enabling the SEOmatic plugin, but that doesn't resolve it. The only solution is to uninstall and reinstall the plugin, but then all of our settings (the ones not stored in `seomatic.php`) are removed and we'd have to manually repopulate them.

Is there any additional logging we can turn on to see if any error is occurring when the sitemap is trying to be regenerated, or can you point us in a direction to look? Perhaps a way to take a back-up of our SEOmatic settings that we can restore after uninstalling/reinstalling the plugin?

### To reproduce
Steps to reproduce the behaviour:
1. Go to https://barnesfoundation.org/sitemap.xml
2. See the error message

### Expected behaviour
You should see the fully populated sitemap.xml, but instead you're shown an error. However, the sub-sitemap.xml's appear to render correctly, such as https://barnesfoundation.org/sitemaps-1-section-exhibition-1-sitemap.xml.

### Screenshots
![image](https://user-images.githubusercontent.com/41299115/90715181-82b35d80-e277-11ea-8713-b3ef8f56fd0d.png)

### Versions
- Plugin version: 3.3.8
- Craft version: 3.3.20.1

**Comment by khalwat** [comment]
If you choose "View Source" you'll see:

```

  An internal server error occurred.


```

Check your `storage/logs/web.log` and `storage/logs/queue.log` for errors.

**Comment by khalwat** [comment]
Also please update to the latest version of SEOmatic, and let me know if you still experience the errors.
