### ISSUE TITLE
SEO Preview not rendering custom SEO description

### ISSUE THREAD

**Issue by moondawg69** [nystudio107/craft-seomatic#726]
### Describe the bug

Multiple sites, latest version of the plugin (3.3.16), I can reproduce this issue where any 'custom text' entered in the SEO Description field is not rendering in the main SEO Preview window but it does render in the Sidebar Preview for Google as intended. The main SEO preview shows  the Content SEO default text as set.

Clients have reported this to me, and stated this worked as intended in previous versions.

### Expected behaviour

To be able to view the entered 'custom text' in the SEO Description field in the main SEO Preview window.

### Screenshots

<img width="949" alt="Screenshot 2020-08-20 at 19 41 45" src="https://user-images.githubusercontent.com/1304000/90820572-7b4c8c80-e329-11ea-9833-d0fd1d4dbf80.png">

### Versions
- Plugin version: 3.3.16
- Craft version: 3.5.5

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/16760f8845bfe458075791082ec97459876b94e7
