### ISSUE TITLE
Error when creating sitemap

### ISSUE THREAD

**Issue by ammonhaggerty** [nystudio107/craft-seomatic#729]
I'm seeing this error when trying to view the sitemap from either within the admin console or directly to the URL:
`error on line 2 at column 6: XML declaration allowed only at the start of the document`

When I look at the Queue log I see this:
`2020-08-25 16:12:10 [-][149][-][info][nystudio107\seomatic\services\{closure}] Meta container cache miss: sitemaps-1-section-pages-1-sitemap.xml/1`

Thanks!

**Comment by ammonhaggerty** [comment]
When I view the sitemap xml, it's valid, but starts on the second line.

**Comment by khalwat** [comment]
@ammonhaggerty I've run into this before, and it ended up being that the server was misconfigured in some way, and thus was adding a newline where it should not be.

**Comment by ammonhaggerty** [comment]
Thanks @khalwat - do you have any memory of where to start looking for the issue? I've been trying to track it down for two days now. I'm about to give up and manage the sitemap by hand.

**Comment by khalwat** [comment]
I think someone had stray characters in one of their config files in the `config/` dir -- like db.php or general.php or the like.

It's definitely not a bug in SEOmatic (not that this makes it any better for you, I know)

**Comment by khalwat** [comment]
I think they had a linefeed above the:

```

<?php
```
in one of the `.php` files in `config/` now that I think of it. Which adds a linefeed to the output from the webserver, which normally doesn't matter with HTML... but for XML it matters.

Ironically, if you roll your own sitemaps, if I'm right, you'll get the same error anyway.

**Comment by ammonhaggerty** [comment]
That was it!! Found it in one of the plugin config files. Thank you so much!
