### ISSUE TITLE
Sitemap not working

### ISSUE THREAD

**Issue by limesquare-nl** [nystudio107/craft-seomatic#73]
In the plugin settings i've enabled the sitemap but it's not working.
https://limesquare.nl/sitemap.xml

The section sitemaps are working.
https://limesquare.nl/sitemaps/1/section/cases/1/sitemap.xml

Any idea's?

**Comment by khalwat** [comment]
Should be fixed via https://github.com/nystudio107/craft-seomatic/commit/8f07f8aba27de55e85f2bce0fbb63cf1060126ce

**Comment by limesquare-nl** [comment]
I will check it when it's released.

**Comment by khalwat** [comment]
Give it a whirl: https://github.com/nystudio107/craft-seomatic/releases/tag/3.0.0-beta.24

**Comment by limesquare-nl** [comment]
It's working now.
See:
https://limesquare.nl/sitemap.xml
