### ISSUE TITLE
How can we get the product variant image for the SEO img

### ISSUE THREAD

**Issue by 3dgroup** [nystudio107/craft-seomatic#730]
I can't seem to find anywhere about being able to use a field on commerce variant. I would assume most people would have the product image within the variant and not on the main product element. Is this possible or is it something I would need to request as a new feature.

**Comment by khalwat** [comment]
You can do this yourself via Twig now by putting whatever Twig you like in the image field:

https://nystudio107.com/docs/seomatic/Configuring.html#content-seo-control-panel-fields

But if you'd like some automatic way for this to happen, I'd be open to discussing a FR.

When you visit a page, my understanding is that Commerce injects the `product` onto the page -- does it also inject a `variant` for URLs that match a given route?

If not, I'm not sure how SEOmatic could automatically know which variant to choose to use?

**Comment by 3dgroup** [comment]
It injects product and that always has a defaultVariant object. So you could add the feature to use a default variant field.

**Comment by khalwat** [comment]
@3dgroup does every product _always_ have a `defaultVariant` object? If so, I tend to agree, that might be the best way to go.

**Comment by 3dgroup** [comment]
@khalwat Yes, it always has a `defaultVariant` getter which is an object of `craft\commerce\elements\Variant`.

**From commerce docs:**

"The product itself is never sold, just a variant of a product. Even a product with no variants has a default variant behind it."

"Returns the default Variant model. If no variant is set as the default, it returns the first variant found. For product types without multiple variants, this is the product’s implicit variant."

**Comment by khalwat** [comment]
We're doing this now:

```php
                'sku'              => '{product.getDefaultVariant().getSku()}',
                'offers'           => [
                    'type'          => 'Offer',
                    'url'           => '{seomatic.meta.canonicalUrl}',
                    'price'         => '{product.getDefaultVariant().getPrice()|number_format(2, ".", "")}',
                    'priceCurrency' => '{{craft.commerce.paymentCurrencies.primaryPaymentCurrencyIso()}}',
                    'offeredBy'     => [
                        'id' => '{parseEnv(seomatic.site.identity.genericUrl)}#identity',
                    ],
                    'seller'        => [
                        'id' => '{parseEnv(seomatic.site.identity.genericUrl)}#identity',
                    ],
                    'availability'  => 'http://schema.org/{% if product.hasUnlimitedStock or product.totalStock > 0 %}InStock{% else %}OutOfStock{% endif %}',
                ],
```
