### ISSUE TITLE
twitter:image:height and twitter:image:width are not correct

### ISSUE THREAD

**Issue by nflorentin** [nystudio107/craft-seomatic#737]
Hi,

Metas twitter:image:height and twitter:image:width are not matching the real width and height of the image.

SEO Image source for Twitter config:
{ object.entry.seoMetaImage[0] ? seomatic.helper.socialTransform(object.entry.seoMetaImage[0], "twitter-large") : seomatic.helper.socialTransform(object.entry.eventMainImage[0], "twitter-large") }

The displayed meta are the following:

```
<meta name="twitter:image" content="https://linksium.sleede.com/uploads/events/_800x418_crop_center-center_82_none/event.jpg?mtime=1597412253">
<meta name="twitter:image:width" content="800">
<meta name="twitter:image:height" content="297">
```

As the filename indicates, the image dimensions are 800x418 but the meta twitter:image:height indicates 297px.

The og:image:width and og:image:height are okay. 

Perhaps I'm missing something...

Thanks for your help on that.

**Comment by khalwat** [comment]
If you're changing the image source manually, you're going to need to change the height and width yourself manually as well.

SEOmatic precomputes it when it's just set to an Asset, but it can't know exactly what you're doing if you change it with custom code.

**Comment by nflorentin** [comment]
I thought that using seomatic method socialTransform would be the "seomatic" way and okay for image height and width metas.

Thanks for clarifying!

**Comment by khalwat** [comment]
Well, from SEOmatic's point of view, you've just set your `twitter:image` to a glob of text. It then uses Twig to evaluate that glob of text into whatever it resolves to (hopefully a URL). But that's all it knows about.
