### ISSUE TITLE
Keywords from field outputs twig code

### ISSUE THREAD

**Issue by limesquare-nl** [nystudio107/craft-seomatic#74]
When i choose at SEO Keywords Source "Keyword from field" twig code rendered in the html.

`<meta name="keywords" content="{seomatic.helper.extractKeywords(seomatic.helper.extractTextFromField(object.entry.subtitel))}">`

**Comment by khalwat** [comment]
Is this via an SEO Settings field, or via Content SEO?

**Comment by limesquare-nl** [comment]
Content SEO

**Comment by khalwat** [comment]
I believe this is caused by an issue with the TextRank library that I'm using:

https://github.com/DavidBelicza/PHP-Science-TextRank/issues/4

If there is no response from them, I can attempt a work-around or fork the project.

**Comment by limesquare-nl** [comment]
I see there is already a [fork](https://github.com/nexxome/PHP-Science-TextRank/commit/79558be89a381102346fbcdacbb534dd1cd2bbea) that has a fix

**Comment by khalwat** [comment]
Ah, great find, thanks. I guess I can just use this fork.

**Comment by khalwat** [comment]
I tried reaching out to them as well: https://twitter.com/nystudio107/status/986562188658790401

Interestingly, the issue only happens if the input text is too short... but that's not very helpful when we're generating these things in an automated way (and thus the input can very well be any length).

**Comment by DavidBelicza** [comment]
Now, version 1.0.4 has this fix: https://github.com/DavidBelicza/PHP-Science-TextRank/releases/tag/1.0.4

**Comment by khalwat** [comment]
Thanks @DavidBelicza !

@limesquare-nl give a `composer update` a go!

**Comment by limesquare-nl** [comment]
It's working now. Thanks!!
