### ISSUE TITLE
Json-LD multiple reviews not working

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#741]
### Describe the bug
I'm trying to reproduce a Json-LD schema with a product that have multiples reviews like [this exemple 2](https://schema.org/Review). For one review (without array), it's working. But, if I give an array, it's not working.

### To reproduce
Steps to reproduce the behaviour:

With an array it returns no review at all.
```twig
{% set mainEntityOfPage = seomatic.jsonLd.get('mainEntityOfPage') %}
{% do mainEntityOfPage.review(seomatic.jsonLd.create([
  {
    "key": "A1",
    "type": "Review",
    "author": "Ellie",
    "datePublished": "2011-04-01",
    "description": "The lamp burned out and now I have to replace it.",
    "name": "Not a happy camper",
    "reviewRating": {
      "@type": "Rating",
      "bestRating": "5",
      "ratingValue": "1",
      "worstRating": "1"
    }
  },
  {
    "key": "A2",
    "type": "Review",
    "author": "Lucas",
    "datePublished": "2011-03-25",
    "description": "Great microwave for the price. It is small and fits in my apartment.",
    "name": "Value purchase",
      "reviewRating": {
      "@type": "Rating",
      "bestRating": "5",
      "ratingValue": "4",
      "worstRating": "1"
    }
  }
], false)) %}
```

But, with only one review, it's working :
```twig
{% do mainEntityOfPage.review(seomatic.jsonLd.create({
  "key": "eee1",
  "type": "Review",
  "author": "Ellie",
  "datePublished": "2011-04-01",
  "description": "The lamp burned out and now I have to replace it.",
  "name": "Not a happy camper",
  "reviewRating": {
    "@type": "Rating",
    "bestRating": "5",
    "ratingValue": "1",
    "worstRating": "1"
  }
}, false)) %}
```

### Expected behaviour
An array of reviews like in [this exemple 2](https://schema.org/Review).

### Versions
- Plugin version: 3.3.18
- Craft version: 3.5.8

**Comment by khalwat** [comment]
@LouisCuvelier check out how I do that in some of the examples here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples#dev-mode-fm-episode-page

Specifically, look at the array of people used for `actor` and `director`
