### ISSUE TITLE
Robots shows on empty selected option on admin panel

### ISSUE THREAD

**Issue by belkin** [nystudio107/craft-seomatic#742]
### Describe the bug
On some entries on specific sections and sites, we're having an issue with the robots field on version 3.2.42. When I chose "None - Do not index or follow links on this page" and after saving the robots field is showing an empty option but in front-end, everything seems to be working as intended.
 
I've already tried to update it to the latest version (3.3.18) but I'm still getting this UI issue.

### To reproduce
1. Make an SEO field with robots field checked and attach it to an entry type.
2. Choose "None - Do not index or follow links on this page" and save.
3. Go back to the entry and check the robots field.

### Expected behavior
When I chose "None - Do not index or follow links on this page", it needs to show "None - Do not index or follow links on this page" instead of an empty option.

### Screenshots
![image](https://user-images.githubusercontent.com/3419659/92698656-f6afc580-f34c-11ea-8835-b2d548e704a4.png)
![image](https://user-images.githubusercontent.com/3419659/92698689-016a5a80-f34d-11ea-98d8-66183667b0cc.png)
![image](https://user-images.githubusercontent.com/3419659/92698759-0f1fe000-f34d-11ea-936f-fcbe7992642a.png)

### Versions
- Plugin version: 3.2.42 / 3.3.18
- Craft version: 3.3.20.1

**Comment by khalwat** [comment]
This is not a bug, this is poor UX. The empty selection is intended to indicate "no change". See a longer discussion of this poor UX here: https://github.com/nystudio107/craft-seomatic/issues/535
