### ISSUE TITLE
"Non-standard implementation" report from Google Tag Assistant

### ISSUE THREAD

**Issue by bryantAXS** [nystudio107/craft-seomatic#743]
### Question
We've recently relaunched a website we manage, migrating the site to Craft and using SEOMatic. Since the relaunch we've seen some metrics do a pretty big jump (pages/session has doubled, and sessions/user has increased) and we want to make sure we're not double tracking our analytics.

Originally we were using the "Google Analytics" tracking script injected by SEOMatic, but switched to "Google gtag.js" this past week with a fairly out-of-the-box setup: https://share.getcloudapp.com/2NuyDjyP

Also, we used Google Tag Assistant to verify 40 URLs on the site, and some of the URLs are reporting back a "non-standard implementation." Do you know what that could mean? https://share.getcloudapp.com/NQurX1De

Thanks Andrew!

### Additional context

I also used Google [Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) to view events sent when visiting the site. I didn't notice any duplicate events. Are any of SEOMatics events fired on the server-side as opposed to the front-end that I'm not able to see with this tool?

**Comment by khalwat** [comment]
To be clear, SEOmatic doesn't do anything other than include the appropriate script tags, and optionally automatically send a page view.

It does not do anything server-side at all.

From what you describe, it _does_ sound like some kind of double tracking is going on. 

I don't have a lot to go on here, but I'm not seeing anything obviously wrong.
