### ISSUE TITLE
Sitemap generates with /uk/us/ instead of /us/ 

### ISSUE THREAD

**Issue by mblode** [nystudio107/craft-seomatic#744]
### To reproduce
Steps to reproduce the behaviour:
1. Set default multisite locale to "@web/uk"
2. Set another multisite locale to "@web/us"
3. Clear Craft CMS cache
4. Generate sitemaps for all entries via CLI
5. Go to http://site.test/us/sitemap.xml
6. Click on first sitemap link
7. On the next page, the URL is prefixed with /uk/us instead of /us
8. The same is happening for http://site.test/us/sitemap.xml

### Expected behaviour

I expect that the sitemaps to be prefixed with "/us" only. Otherwise it generates links to 404 pages

### Screenshots

<img width="1290" alt="Screen Shot 2020-09-14 at 9 14 42 pm" src="https://user-images.githubusercontent.com/7183998/93079368-5a304f00-f6cf-11ea-9815-964b6069459a.png">

The path for entry URLs include "/uk". I believe this caused because the default multi site is found at @web/uk instead of just @web at it probably things that is the default.

### Versions
- Plugin version: 3.3.18
- Craft version: 3.5.8

**Comment by khalwat** [comment]
Can you tell me how `@web` is being set here?

**Comment by mblode** [comment]
Hey @khalwat I've removed the use of @web from the site URLs and they are now set to "/uk" and "/us". I've cleared the cache and regenerated the sitemaps. I'm still having the same issues

**Comment by khalwat** [comment]
I think what you should do is put `@web` back, but define it explicitly to be whatever fixed URL you want (probably via a `.env` variable) and see if you still have issues.

e.g.: https://github.com/nystudio107/devmode/blob/master/cms/config/general.php#L19 & https://github.com/nystudio107/devmode/blob/master/cms/example.env#L20

**Comment by mblode** [comment]
Amazing, that worked!! Thank you so much
