### ISSUE TITLE
Url Masking issue

### ISSUE THREAD

**Issue by knynkwl** [nystudio107/craft-seomatic#745]
### Question
We have a client that wanted to do some URL for a site. On some pages, the SEO tags are not generating.

Original: https://insider-prod.preproduction.io/tb/the-list-of-300-people-transforming-business-in-2020-9
Mask: https://www.businessinsider.com/tb/the-list-of-300-people-transforming-business-in-2020-9

None of the custom fields that are added in the CMS are being generated on the masked URL but they appear on the original URL.

**Comment by khalwat** [comment]
I don't understand what you mean by "Url Masking" -- can you explain?

I can't really tell what could be wrong from here, but my guess is maybe this is some kind of multi-site setup, and some fields don't exist on one of the sites or something?

**Comment by khalwat** [comment]
Will re-open if more information is presented.
