### ISSUE TITLE
"Dynamic" Breadcrumbs: exclude top-level, only show for pages with at least 2 levels 

### ISSUE THREAD

**Issue by jayhlee** [nystudio107/craft-seomatic#747]
### Is your feature request related to a problem? Please describe.
SEOMatic always prints `BreadcrumbList`, regardless of what page level you're on. For example, it'll even show on the homepage. According to [Google's docs](https://developers.google.com/search/docs/data-types/breadcrumb), they recommend specifying breadcrumbs if there's at least two `ListItem`s.  

Furthermore, SEOMatic counts the top level element (`example.com`) as a `ListItem`. But Google recommends not including the top level, as it "doesn't add any information," according to them.  

### Describe the solution you would like
1. SEOMatic only outputs `BreadcrumbList` if the page is at least 2 levels (not including the top level/homepage.) For example, `BreadcrumbList` would print for `mydomain.com/level1/level2` but not `mydomain.com/level1` or `mydomain.com`
2. SEOMatic excludes the top level/homepage as a `ListItem`, which in turn changes the `ListItem` `position` number.

### Describe alternatives you have considered
I know I can override the breadcrumbs. But having these crumbs already baked into SEOMatic (see what I did there) would be more tasty.

**Comment by khalwat** [comment]
Seem like a reasonable change.

**Comment by khalwat** [comment]
I'm sitting down to implement this, and just noting a couple of concerns:

1. People who depend on `BreadcrumbList` appearing on every page could potentially have broken code based on the changes
2. People who depend on their being a Homepage link as the first entry in each breadcrumb could potentially have broken code

I'm mulling it over, because while the changes you mention are indeed technically correct (or at least what Google recommends), I don't see any validation errors or warnings when using the breadcrumb implementation as-is (which is in compliance with schema.org recommendations too).

So I'm starting to wonder whether the changes here would do more harm than good.

Thoughts @jayhlee ?

**Comment by jayhlee** [comment]
Yeah, it seems like the potential of broken code for those who depend on how `BreadcrumbList` currently works may not be worth it. I ended up rolling my own custom JSON-LD `BreadcrumbList`, so I've been able to find a solution. 

While there may not be a validation error, it seems like `BreadcrumbList` showing up on every page may be, at worst, just a misapplication of `BreadcrumbList`. (The example on schema.org also seems to follow Google's recommendation.)

Which, by and large, isn't a big deal, given that there's already a cloud of ambiguity that often follows trying to apply schema types and properties. 

Thanks for looking into this, Andrew!

**Comment by khalwat** [comment]
Yep, great input from you on this. Google will change how they do this tomorrow anyway :)

**Comment by leevigraham** [comment]
Came to report the same issue… Maybe seomatic could have a config variable for `includeRoot`, and `includeCurrentEntry` for breadcrumb json output? 

I'm using the `seomatic.jsonLd.get('breadcrumbList')` function to output html breadcrumbs in a partial twig file so it's not a big deal to add the homepage manually in that template.

**Comment by WHITE-developer** [comment]
@khalwat We are looking into this right now cause it looks like Google now [(sometimes) adds the home breadcrumb](https://www.google.com/search?q=site%3Awhite.nl+plugins) to the search results. Maybe a config variable isn't that bad idea. We can't find anything else what it could be.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d3d0311da54b190013d91eb6d686f144d7f33d4d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.3”,
```
Then do a `composer clear-cache && composer update`
