### ISSUE TITLE
[FR] The ability to override the default sitemap.xsl

### ISSUE THREAD

**Issue by rob-c-baker** [nystudio107/craft-seomatic#748]
It would be helpful for a couple of our sites to add some branding  / customisation to the XSL stylesheet(s) that make the sitemap XML readable and navigable.

We also have some higher-ups in the company that don't like the off-site link in the footer or the information disclosure it gives away about technologies being used on the sites.

### Proposed Solution
Add configuration variables for defining paths to different Twig templates. An alternative would be the ability to define a different URL for the XSL that is rendered in the sitemap XML.

### Stuff I Tried
Adding a sitemap.xsl file to the NGINX / Apache document root works to an extent _(because the web server sees there is a file present at that URL so serves that before the request gets as far as Craft)_ but it would be great to have the power of Twig in that context.

**Comment by khalwat** [comment]
@rob-baker-ar Probably I will just remove that SEOmatic link, or provide a way for you to turn it off.

Would that be sufficient?

**Comment by rob-c-baker** [comment]
A way to turn it off or removal would work for the main issue.

As long as the stylesheet reference in the XML stays as a simple request to /sitemap.xsl then it should be possible to override it for custom styling if there really is the hunger for that later.

**Comment by khalwat** [comment]
Removed in https://github.com/nystudio107/craft-seomatic/commit/6259e6fa2aa9fb3ce14e9efd9712fe1455671c02
