### ISSUE TITLE
Changing Creator settings, adding creator property, changing default Publisher property

### ISSUE THREAD

**Issue by jayhlee** [nystudio107/craft-seomatic#749]
### Is your feature request related to a problem? Please describe.
The `Creator` settings are ostensibly used to define the entity that created the website. Often, the site `creator` would be different than the `identity` (person/organization that owns the site). 

This introduces some unintended situations because the [`creator` Schema property,](https://schema.org/creator) when used on, say `CreativeWork`, is intended to define the creator/author of the CreativeWork (or Article, NewsArticle, etc.). However, because SEOMatic links the `publisher` property for `Article` to `creator`, the `publisher` property is linking to the "creator" of the website, not the "creator" of the CreativeWork, which in most cases is the site `identity` (owner of website).

### Describe the solution you would like
I propose changing the label "Creator" (in the `Site Settings>Creator` settings) to "Site Creator" or another label that makes a distinction between the Site Creator and creator (when used as a property). In fact, perhaps "Site Developer" would even be better label because it doesn't include the term "creator."

In the Content SEO, it'd be nice to have a "Creator" field appear if it's a property within the selected "Main Entity of Page." The default selection would be set to the "Site Owner" (Site Settings>Identity), although that could be customized. For example, an article `creator` could be set to a specific person/author rather than just the Site Owner.

Also, for the default `publisher` property, I'd propose changing it so that instead of linking to the `creator` property, it links to the `identity` property. The `publisher` is more often the Site Owner/`identity` rather than the Article author/`creator` or the Site Developer/Creator.

### Describe alternatives you have considered
I know I can override the property values, which I have been doing. But it'd be nice to see the aforementioned changes. :)

**Comment by khalwat** [comment]
I think a "Creator" in Content SEO is (currently) outside the scope of SEOmatic.

The main reason is that what you _really_ want is a JSON-LD builder, which allows you to create arbitrarily nested JSON-LD.

I say this because no matter what I provide by default, there will be something more that you (or someone else) will want to do with it... which is totally fair.

But I think for now, it makes sense for people who want to go to this extent to just use the rather robust Twig API to "do the thing": https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

(I really do appreciate and value all of your suggestions tho @jayhlee -- they have been great!)

**Comment by jayhlee** [comment]
Thanks, Andrew. 

Quick related question: Is there a way to disable the default properties from automatically being ouputted? 

Even if the "Main Entity of Page" is left blank on both the Global SEO and Content SEO, `WebPage`, `Identity`, `Creator`, and `BreadcrumbList` are automatically created. I'm hoping to create and set the attributes for the properties/types in my templates so I can fully control the JSON-LD on a per template basis.

**Comment by khalwat** [comment]
@jayhlee You have full control over what is rendered by using the Twig API:

https://nystudio107.com/docs/seomatic/Using.html#seomatic-tags-containers

**Comment by khalwat** [comment]
@jayhlee Some nice examples are here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

https://nystudio107.com/blog/tips-for-using-seomatic-effectively
