### ISSUE TITLE
Cannot switch to other sites in the CP

### ISSUE THREAD

**Issue by dowadidi** [nystudio107/craft-seomatic#75]
The site switch in the CP is nog working for me.
When trying to switch to an other site, seomatic stays on the last site added.

- the CP url seems to be correct (`/cms/seomatic/dashboard/<sitehandle>`)
- it happens on all pages
- and there are no errors being reported in the debugger

**Comment by khalwat** [comment]
Confirmed here; must be some kind of regression.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/0ab391ba1752a342bcc4588cf30d7abd519dd5d2

**Comment by dowadidi** [comment]
That was quick! Thanks!

**Comment by khalwat** [comment]
Give it a whirl: https://github.com/nystudio107/craft-seomatic/releases/tag/3.0.0-beta.24
