### ISSUE TITLE
Double X-Robots-Tag

### ISSUE THREAD

**Issue by WHITE-developer** [nystudio107/craft-seomatic#750]
### Describe the bug
Since 3.5.10, Craft has the setting `disallowRobots` to override the `X-Robots-Tag`. Right now that tag is added twice to the request, one from Craft and the other from SEOmatic.

### To reproduce
Steps to reproduce the behaviour:
1. Update Craft to 3.5.10
2. Set `disallowRobots` to `true` in `general.php` config
3. Make sure seomatic is on local by for example enabling `devMode`
4. Load a page and see `X-Robots-Tag` twice in the request header

### Expected behaviour
As it is now a Craft core feature, I guess SEOmatic should check the setting

### Versions
- Plugin version: 3.3.18
- Craft version: 3.5.10.1

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/a736d210780f1ab99787460d91511bc1666a124b
