### ISSUE TITLE
Can't save Site settings > Identity > Site owner entity type

### ISSUE THREAD

**Issue by nickchartier11** [nystudio107/craft-seomatic#751]
Hi,

We seem to have a problem with saving Sub type entity types in site settings > Identity > Site owner entity type. Whenever we select a sub type (in our case Organization > Local Business > Entertainment Business) and save, it appears to save correctly the input information. However if we make other modifications in the SEOmatic settings on the same page and save, it reverts back to the "parent type (in our case Organization). W e have the same issue with main entity of page in Global Seo settings.

Here are screen recordings to showcase the issue: http://recordit.co/52ojkqCPBC & https://recordit.co/oZuePttv9e

**Comment by khalwat** [comment]
@nickchartier11 Check your `storage/logs/web.log` for errors?

I've been unable to reproduce this locally, so any additional information you can provide would be helpful.

**Comment by sunscreem** [comment]
Hey @nickchartier11 did you solve this one?

I think we are seeing this on one of our sites too and I thought it quicker to ask before I start digging in to it.

**Comment by nickchartier11** [comment]
No we did not. We also saw it on a second site

**Comment by sunscreem** [comment]
@khalwat Can confirm same issue here on a site. 

Non log files being generated at all on save, nothing in the console.

The XHR request just gives a 200 with no other response. 

Same issue under `global SEO > general setting > main entity of page`.

Plugin version: 3.3.18
Craft version: 7.4.10

Anything else to try?

**Comment by sunscreem** [comment]
@nickchartier11 I just updated to the latest release and this seems to be fixed.

@khalwat As you were sir.

**Comment by khalwat** [comment]
@nickchartier11 please update to the latest version of SEOmatic
