### ISSUE TITLE
[Graphql] Multiple seo field in the same entry

### ISSUE THREAD

**Issue by stephanedemotte** [nystudio107/craft-seomatic#753]
Hello 

I have two field in the same entry.
But in graphql, `seomatic` field only return the last one.
If i try to target the seomatic field via the key i've got an error.

<img width="1792" alt="Screen Shot 2020-09-19 at 11 31 15 AM" src="https://user-images.githubusercontent.com/2158130/93670761-be566880-fa6b-11ea-93de-c80a643ebee9.png">

Can we do that ?

Thanks !

**Comment by khalwat** [comment]
Having more than one SEOmatic field per entry isn't a supported pattern. One is going to stomp over the other regardless, and you won't have control over the order of that.

I'd remove one of the fields.
