### ISSUE TITLE
"Your Sitemap appears to be an HTML page. Please use a supported sitemap format instead."

### ISSUE THREAD

**Issue by steve14four** [nystudio107/craft-seomatic#755]
`/sitemaps-1-sitemap.xml ` returns a nicely formatted view of my sitemap, and when I hit the same URL with `curl` or Insomina App, I get a correctly formatted XML response, but when I submit the URL to Google Search Console I get an error 'Sitemap could not be read. Sitemap is HTML'.

I have tried to replicate the issue by setting my user agent in `curl` to match what the GoogleBot users, but did not have any luck. 

I found some relevant code in `SitemapController.php actionSitemapStyles()`, but was unable to trace back through the code as to what triggers that code to run and what decides if it should return the styled version vs the plain XML. 

This site just went live and replaced a Wordpress site. I have removed the previous sitemap URL's from the Google Search Console. I have tried clearing the caches in Craft CMS and in CloudFront (it's hosted on AWS). 

Can anyone point me in the right direction of what might be causing this issue? The only relevant comment I have found related to a similar issue with another CMS/Plugin and they suggested waiting for Google to catch up, but that seems odd when I submit the error and it attempts to fetch the URL then and displays the error.

**Comment by khalwat** [comment]
I'm not sure what to tell you here, other than I don't think there's anything wrong with the current implementation. It returns plain old XML, but links to an XLS stylesheet that can optionally be used.

But that's up the client. It actually is not returning HTML at all, it's returning XML (even though you see it formatted in what looks like an HTML page to you).

Here are all of the sitemaps from Nystudio107.com that are submitted and indexed by Google, without issue:

<img width="1030" alt="Screen Shot 2020-09-26 at 1 29 34 PM" src="https://user-images.githubusercontent.com/7570798/94346711-86679c00-fffc-11ea-918c-2c46bdb2b8a1.png">

**Comment by steve14four** [comment]
Looks like Google just needed some time. We haven't touched anything over the weekend, but it's working now. 

I wish Google would provide more feedback on what they are seeing as a response to help debug issues like this.

**Comment by khalwat** [comment]
I wish that too for sure :)
