### ISSUE TITLE
Settings: input fields are missing 

### ISSUE THREAD

**Issue by croxton** [nystudio107/craft-seomatic#758]
### Describe the bug
On settings pages, certain input fields are missing. These appear to be fields that can be set with environmental variables because they have a tip below 'This can be set to an environment variable. Learn more'. Only the tip shows, but not the input field above.

In the console there is a JS error:
```
Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at s.constructor.trigger (garnish.js:838)
    at s.constructor.setJobInfo (CP.js:894)
    at default:862
trigger	@	garnish.js:838
setJobInfo	@	CP.js:894
(anonymous)	@	default:862
```

### To reproduce
Steps to reproduce the behaviour:
1. Go to Tracking Scripts > Google gtag.js
2. The Google Analytics Tracking ID field is missing

### Versions
- Plugin version: 3.3.19
- Craft version: 3.5.11.1

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.21
