### ISSUE TITLE
Console command seomatic/sitemap/generate spawns queue/run

### ISSUE THREAD

**Issue by paweltatarczuk** [nystudio107/craft-seomatic#759]
### Describe the bug

The `seomatic/sitemap/generate` console command runs the queue the same way as the `queue/run`.

This is unexpected because:
- Stopping the queue processing service does not necessarily mean the queue is not being processed
- Restarting the queue processing service does not necessarily mean all queue processes are restarted

### To reproduce
Steps to reproduce the behaviour:
1. Diable all `queue/run` processes
2. Ensure there are jobs waiting to be processed in the queue
3. Run `seomatic/sitemap/generate`
4. There are no waiting jobs in the queue any more

### Expected behaviour
The `seomatic/sitemap/generate` should not process queue by it's own.

### Versions
- Plugin version: 3.3.16
- Craft version: 3.5.5

**Comment by khalwat** [comment]
You can disable this behavior via the `runQueueAutomatically` Craft CMS general config setting:

https://craftcms.com/docs/3.x/config/config-settings.html#runqueueautomatically

If that is set to `false`, SEOmatic won't run the queue immediately. 

It runs the queue immediately in an attempt to satisfy the external request for the sitemap page.

**Comment by paweltatarczuk** [comment]
@khalwat Sorry but this won't help at all.

Console controller runs this:

```
Craft::$app->getQueue()->run();
```

This simply starts queue processing no matter what you set for `runQueueAutomatically`, besides it is already set to `false`. Also docs says it is for something else:

> Whether Craft should run pending queue jobs automatically when someone visits the control panel.

**Comment by khalwat** [comment]
So here's the thing. All of the SEOmatic sitemaps are generated via a queue job. When people run the console command, the expectation I think is that the sitemaps will be generated then and there.

What I can do as an alternative is create _another_ command that simply queues the job if you like?

**Comment by khalwat** [comment]
Added a `--queue` flag that can be passed to the `seomatic/sitemap/generate` flag to cause the sitemap generation jobs to be queued, but not run:

https://github.com/nystudio107/craft-seomatic/commit/d24c50535ffa2a33e9737dee5fb37c4214b5a78f

You can test it now by setting your semver in your `composer.json` to:

```json
    "nystudio107/craft-seomatic": "dev-develop as 3.2.22",
```

...and then doing a `composer update`

lmk!

**Comment by paweltatarczuk** [comment]
This will work for me, thanks!

FYI This module is not the only one that is running the queue within a console command, this seems like a pretty common practice and it's not helping with automatic deployments (sometimes there are two different queue processes both with different codebase). ;)

**Comment by khalwat** [comment]
Here's an article I wrote on deployments that might be useful to you @paweltatarczuk https://nystudio107.com/blog/executing-atomic-deployments

**Comment by paweltatarczuk** [comment]
@khalwat Thank you, very nice article! BTW I'm using ansible for multi-node provisioning and ansistrano for atomic deployments, executed by GitHub Actions, but still, there are very helpful Craft related insight that could be handy ;)

**Comment by khalwat** [comment]
Yep, I've used Ansible in the past -- found the tooling around Buddy.works to be much more enjoyable, especially the way it caches things, handles custom Docker containers, etc.

Anyway GL!
