### ISSUE TITLE
Robots.txt returns 404 status code

### ISSUE THREAD

**Issue by limesquare-nl** [nystudio107/craft-seomatic#76]
The robots.txt return a 404 status code while it's rendered.

Example at:
https://limesquare.nl/robots.txt

**Comment by khalwat** [comment]
I think this might have to do with your server setup, and not SEOmatic. I tried it on a few different hosts and it appears to be working correctly:

Local dev test:

```
andrew@kotak ~ $ curl -I http://craft3.test/robots.txt
HTTP/1.1 200 OK
Server: nginx/1.13.3
Date: Tue, 17 Apr 2018 13:53:01 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
X-Powered-By: Craft CMS
```

Live:

```
andrew@kotak ~ $ curl -I https://devmode.fm/robots.txt
HTTP/1.1 200 OK
Server: nginx/1.13.6
Date: Tue, 17 Apr 2018 13:53:59 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: Craft CMS
X-Cache: MISS
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer-when-downgrade
```

Note that the 200 status code is returned, which is the default return status code for controllers. This being the case, it's likely that any route to a controller on the frontend will also return a `404` on your server.

**Comment by limesquare-nl** [comment]
I've fixed it. In the default Laravel Forge environment i've commented the following line in the nginx configuration file. Now it's working fine.

`location = /robots.txt  { access_log off; log_not_found off; }`

**Comment by khalwat** [comment]
Ah yes, that'd definitely do it. If you're using Nginx, this might help too:

https://github.com/nystudio107/nginx-craft

**Comment by xavierdemoor** [comment]
This happens with Laravel Homestead too in local dev.

**Solution:**

- Log in to vagrant with SSH
- Edit /etc/nginx/sites-available/<name of the site>
- Comment out: location = /robots.txt  { access_log off; log_not_found off; }
- Reload nginx
- Voilà !

**Comment by khalwat** [comment]
Yep, this is in the docs here: https://github.com/nystudio107/craft-seomatic#robots
