### ISSUE TITLE
Caching issue with creator entity brand image

### ISSUE THREAD

**Issue by sunscreem** [nystudio107/craft-seomatic#760]
### Describe the bug

Could be PEBKAC here of course, but I'm getting an image (from a previous website our current site was forked from this) in our json schema.

### Expected behaviour

No image to be loaded in the schema.

### Screenshots

![image](https://user-images.githubusercontent.com/7523595/94829300-48a2b300-0402-11eb-9713-a9baadc2dd84.png)

![image](https://user-images.githubusercontent.com/7523595/94829322-4b9da380-0402-11eb-95c4-b5f785e611d9.png)

### Versions
- Plugin version: 3.3.18
- Craft version: 7.4.10

**Comment by jreb** [comment]
Am seeing the same issue, where when you remove an entity brand, it still remains in the schema, so no clear way to remove completely.

**Comment by khalwat** [comment]
Can you replace it with a different image?

**Comment by jreb** [comment]
You can replace it with a different image and that works. I think the issue is when you delete the image from the entity brand field, it doesn't seem to be removed.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/449081c97e7d82c0e75f780cd59a35b3af7d018b

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.46”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Released as 3.3.46 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.46
