### ISSUE TITLE
Main entity of page field.

### ISSUE THREAD

**Issue by jreb** [nystudio107/craft-seomatic#761]
Hi there, in global seo > general settings, when I change the main entity of page, it doesn't appear to change the type in the first line of schema in the html. I want to change this from 'creativework' to 'organization' ideally.

<script type="application/ld+json">{"@context":"http://schema.org","@graph":[{"@type":"CreativeWork","author":...

Am i looking in the wrong place to change this? Any help very much appreciated :)

**Comment by khalwat** [comment]
What version of SEOmatic are you using? Can you update to the latest version (3.3.21) and let me know if this is still happening? https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.21

**Comment by jreb** [comment]
Hi there, I think I have worked it out... I didn't realise it was being overwritten on the content SEO level! Sorry about that :)
