### ISSUE TITLE
SEOMatic Preview Overtaking Entry Preview

### ISSUE THREAD

**Issue by ExterroDMM** [nystudio107/craft-seomatic#763]
### Describe the bug
When clicking Preview or Share in Craft CMS Entry screen, the SEOMatic preview is appearing instead of the Craft content entry preview.

### To reproduce
Steps to reproduce the behaviour:
1. Go to an entry
2. Click on Preview or Share button
3. See error where SEOMatic preview overrides the entry content preview

### Expected behaviour
The expected behavior is that we will be able to preview the Craft CMS entry webpage. Instead, that preview function is being hijacked by SEOMatic, rendering us unable to see previews of our content while creating it.

### Screenshots
<img width="595" alt="SEOMatic 1" src="https://user-images.githubusercontent.com/64930317/94981085-38fb9b00-04e4-11eb-9c7c-8a9045dfd277.png">
<img width="594" alt="SEOMatic 2" src="https://user-images.githubusercontent.com/64930317/94981087-3ac55e80-04e4-11eb-8549-1967a9037b4a.png">

### Versions
- Plugin version: 3.3.21
- Craft version: Craft CMS 3.5.12.1

**Comment by khalwat** [comment]
This is no an issue with SEOmatic, this is an issue with Craft CMS, and missing preview targets for the channel in question.

Apparently the issue can happen when upgrading from Solo to Pro.

See here for details: https://github.com/nystudio107/craft-seomatic/issues/684#issuecomment-658467862

**Comment by ExterroDMM** [comment]
@khalwat that worked, thank you!
