### ISSUE TITLE
Cache isn't clearing on save

### ISSUE THREAD

**Issue by darylknight** [nystudio107/craft-seomatic#764]
### Describe the bug
A client just updated the field SEOmatic uses for the SEO Title Source. It's a plain text field on an entry. Here are the settings for that section's titles:

![image](https://user-images.githubusercontent.com/1250017/95219040-99991980-07fd-11eb-8e45-390c5cc02d49.png)

When they save the entry, the SEO title stays the same. It only updates once I clear the SEOmatic metadata caches manually:

![image](https://user-images.githubusercontent.com/1250017/95219269-db29c480-07fd-11eb-867e-1578da5eceb4.png)

There is no other caching on the frontend, and I'm not manually doing anything with the title in the templates.

### Versions
- Plugin version: 3.3.21
- Craft version: 3.5.12.1

**Comment by khalwat** [comment]
What is that first screenshot from @darylknight ? Global SEO settings? Content SEO settings? an SEO Settings field?

**Comment by darylknight** [comment]
The first screenshot is under Content SEO settings. So it's saying to use the `SEO - Title` field, and if it's blank, fall back to the entry title. Here's the full screenshot of the fields being used on the entry:

![image](https://user-images.githubusercontent.com/1250017/95299247-0c4dd780-0886-11eb-8e4c-4c27a1305549.png)

The reason there are normal fields _and_ an SEO settings field on there with only the robots setting is because it was all set up using normal fields, then we needed to add the ability to exclude some pages from indexing later.

**Comment by khalwat** [comment]
Do you have any other caching layers in the mix here that could be interfering?

**Comment by darylknight** [comment]
No, there's no external caching tech on the site, and I'm not using cache tags

**Comment by khalwat** [comment]
Should you be using `???` vs. `??` here? Also I'm assuming `seoTitle` is a regular plain text field?

**Comment by darylknight** [comment]
Changing it to `???` still has the same issue. The field is correct after clearing SEOmatic metadata, it just doesn't clear them on save. Yes, `seoTitle` is a plain text field.

**Comment by darylknight** [comment]
Update - looks like this could be the same as #622 . The SEO caches clear correctly on all other pages, this is only happening on the home page, which is in a Structure, slug set to `__home__`.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/a0fcd9ef2c00fe07bf69682699dda87c04fee62c
