### ISSUE TITLE
`canonicalUrl` being set as an array somewhere causing Error

### ISSUE THREAD

**Issue by adampatpattison** [nystudio107/craft-seomatic#765]
### Describe the bug
I am sporadically getting the following error:

`yii\base\ErrorException: strpos() expects parameter 1 to be string, array given in /var/www/html/vendor/nystudio107/craft-seomatic/src/models/MetaGlobalVars.php:210`

Upon inspecting the code, this is where `canonicalUrl` is being checked on init set in `MetaGlobalVars.php` but for some reason it is set as an array.

### To reproduce
I wish I knew! It's really random which is super worrying for me and not very helpful for you.

### Expected behaviour
Not throw the err

### Versions
- Plugin version: 3.3.21
- Craft version: 3.5.12.1

**Comment by khalwat** [comment]
I'm not sure how that could ever be an array either, but I'm guarding against that now: https://github.com/nystudio107/craft-seomatic/commit/798847a191c7b12a04cd84721c992a52431593f6

**Comment by adampatpattison** [comment]
Excellent as always, thanks Andrew!
