### ISSUE TITLE
Headless multisite sitemap where sites share the same hostname

### ISSUE THREAD

**Issue by jamealg** [nystudio107/craft-seomatic#766]
### Question
I'm using seomatic on a headless multisite where both sites' API endpoints share the same URL. More specifically, I have two front ends that each have their own unique URLs but both access Craft from the same URL. For example, I have `site1.com` and `site2.com` both pulling data from `siteapi.com/siteID/endpoint.json`. Both sites share the same IA but are distinct sites and not just localized versions of each other.

From what I understand, seomatic's sitemap.xml is using the hostname to determine which sitemap to deliver. Unfortunately my infrastructure precludes that approach. Is there any other mechanism to pull a sitemap for a given site other than this? 

I've checked the docs and other issues but I haven't seen this use case specifically mentioned. I'd appreciate any insight you can provide.

**Comment by khalwat** [comment]
It's not using the hostname to determine what site to deliver, but rather whatever site Craft CMS thinks the request is from.

SEOmatic does create an endpoint for each site, as evidenced here: https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/Sitemaps.php#L310

So each URL is:

```
/sitemaps-SITE_GROUP_ID-sitemap.xml
```

...where `SITE_GROUP_ID` is the `$site->getGroup()->id`

See here for more on how the grouping works for multi-site: https://nystudio107.com/docs/seomatic/Configuring.html#sitemap
