### ISSUE TITLE
Bad spacing results in confusing messaging

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#767]
<img width="699" alt="Screen_Shot_2020-10-13_at_8_56_12_AM" src="https://user-images.githubusercontent.com/18329/95863678-7bb64200-0d32-11eb-9612-55232169c35d.png">

Was asked "is the ID going to be overridden"? In fact the message applies to the environment message, I believe.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/ddc5057cf14e150e18d4c5f79456e1d95ee60c8e
