### ISSUE TITLE
Extra line of code rendering google tag invalid. 

### ISSUE THREAD

**Issue by hitennainaney** [nystudio107/craft-seomatic#768]
Although i've copy pasted the right code from Google Tag manager - the plug in is adding an additional line of code which i assume is invalidating the embed. 

It's adding '<script type="text/javascript">' on line 28. 

![image](https://user-images.githubusercontent.com/53337533/95886736-04170000-0d90-11eb-9b1e-5635932f3812.png)

Could you please help me work around it?

Cheers,
H

**Comment by khalwat** [comment]
Just remove the `<script>` and `</script>` tags in the code you've pasted in. I'd actually suggest that you use the default code provided with SEOmatic tho, which is:

```
{% if googleTagManagerId.value is defined and googleTagManagerId.value and not seomatic.helper.isPreview %}
{{ dataLayerVariableName.value }} = [{% if dataLayer is defined and dataLayer %}{{ dataLayer |json_encode() |raw }}{% endif %}];
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'{{ googleTagManagerUrl.value }}?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','{{ dataLayerVariableName.value }}','{{ googleTagManagerId.value }}');
{% endif %}
```
