### ISSUE TITLE
Change hreflang for 1 locale

### ISSUE THREAD

**Issue by limesquare-nl** [nystudio107/craft-seomatic#77]
Is it possible to change the hreflang when only 1 locale is set.

**Comment by khalwat** [comment]
What would you like to see it changed to? You should be able to change it via Twig to whatever you like:

https://github.com/nystudio107/craft-seomatic#twig-templating

Roughly, something like:

```
{% do seomatic.link.get("alternate")
  . hreflang("es")
  .href("https://example.com/es/")
%}
```

**Comment by limesquare-nl** [comment]
now it's display:
`<link href="https://limesquare.nl/" rel="alternate" hreflang="x-default">`

i would like to make it:
`<link href="https://limesquare.nl/" rel="alternate" hreflang="nl">`

**Comment by khalwat** [comment]
I think the former is actually what you'd want it to display. Remember, we're talking about language _alternates_ here, and in this case, Dutch is the default language for this URL, no?

https://support.google.com/webmasters/answer/189077?hl=en

But if you do want to change it, you can do it with the aforementioned Twig code.
