### ISSUE TITLE
Leaving section URI empty returns no relevant SEOmatic data in GraphQL

### ISSUE THREAD

**Issue by Wiejeben** [nystudio107/craft-seomatic#770]
### Describe the bug
I have got pages where the URI is irrelevant, right now I'm using filler URIs mainly for SEOmatic functionality. When I provide no URI to a section it would stop giving back SEOmatic data in the Native Craft GraphQL API.

### To reproduce
Steps to reproduce the behaviour:
1. Create an entry section without a URI
2. Apply a SEOmatic field
3. When editing the entry, provide a SEO page title
4. Request data from GraphQL

```graphql
{
  entry(section: "contactThankYou") {
    id
    title
    seomatic {
      metaTitleContainer
      metaTagContainer
      metaLinkContainer
      metaScriptContainer
      metaJsonLdContainer
    }
  }
}
```

5. The page title will not be of the contact thank you page.

### Expected behaviour
I understand that all fields related to the current URI is impossible to figure out (because there is none), however retrieving data such as the title, robots and description should be possible I think.

### Versions
- Plugin version: 3.3.21
- Craft version: 3.5.13.2

PHP 7.3.23, MySQL 5.7

**Comment by khalwat** [comment]
This is expected behavior. SEOmatic does not do anything for Sections that have no URI, because the assumption is that they are private.
