### ISSUE TITLE
JSON LD breadcrumbs not using SEO Title for breadcrumbs

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#771]
### Describe the bug
When searching google for "IHRSA sales and marketing" the search results breadcrumbs are displaying the Full Page title and not what is in the SEO title source setting field.

viewing page source I see this in the json-ld generated by SEOmatic

```
{"@type":"ListItem","item":"https://www.ihrsa.org/","name":"Home Page","position":1},{"@type":"ListItem","item":"https://www.ihrsa.org/improve-your-club/","name":"Improve Your Club (Landing)","position":2}],"name":"Breadcrumbs"}]}
```

Where Position 2 name is **Improve Your Club (Landing)** but in that entries SEO settings it is set to the **Alternate Title** field which contains *Improve Your Club* and what I would expect to appear. 

Please advise

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Screenshots

![Screenshot 2020-10-19 101130](https://user-images.githubusercontent.com/6899490/96510037-f13a7a80-122a-11eb-9540-86433dd43f29.jpg)

### Versions
- Plugin version: 3.3.9
- Craft version: 3.4.27

**Comment by khalwat** [comment]
Yeah that's not how this feature works... it uses the name of the actual entry itself.

It tracks backwards for each segment, and it'd be quite slow if it needed to load the meta containers for each URL segment in order to try to determine whether you have a custom SEO title set or not.
