### ISSUE TITLE
mainEntity missing on 'QAPage' pages

### ISSUE THREAD

**Issue by jamiewade** [nystudio107/craft-seomatic#772]
### Describe the bug
A few of the pages on one of our clients site are using `QAPage` as the **Main Entity of Page** (under Content SEO).

We have been alerted in Google Search Console that the required attribute `mainEntity` is missing for these pages.

I wasn't sure if this was a bug within the plugin, or we are missing some information in the plugin that means `mainEntity` doesn't have enough information to render?

### Versions
- Plugin version: 3.3.21
- Craft version: 3.5.13.2

**Comment by khalwat** [comment]
I don't know, I need more information. Where can I look at the public page that demonstrates this?

Do you have screenshots of the relevant SEOmatic settings pages?

**Comment by jamiewade** [comment]
@khalwat Sorry Andrew! Here is one of the pages in question: https://www.businessreviewed.com/privacy

Here's a copy of the Structured Data tool report: https://search.google.com/test/rich-results?id=HDthM7A4TLfLEA42bwTCKg

And finally, a screenshot of the settings:

![screenshot](https://user-images.githubusercontent.com/6672331/96612140-522e8500-12f5-11eb-903d-4e0c15581662.jpg)

**Comment by khalwat** [comment]
Ah yes, unfortunately you'll have to do a bit of Twig for this, to set the `mainEntity` -- but fortunately, I've documented an example of that here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples#dev-mode-fm-about-page

You can see the rich results here:

https://search.google.com/test/rich-results?id=gFmc4ZghXS5YDafC2DcmTw
