### ISSUE TITLE
Content SEO not updating

### ISSUE THREAD

**Issue by smockensturm** [nystudio107/craft-seomatic#773]
### Question
Hello. Content SEO is not updating when a section name / handle is changed. CP does not reflect what is really happening with... content!

### Additional context
We have two sections with identical display names. fwiw.

How are these updated? When? Anything we can do to "recompile" SEOmatic's Content SEO entries?

**Comment by khalwat** [comment]
You can delete the appropriate rows from the `seomatic_metabundles` table in the database.

That said, if you rename a section, it should rename in Content SEO. Are you able to reproduce this?

**Comment by smockensturm** [comment]
Ah thanks. I checked out that table and there were two rows with the same `sourceId` 

From before the section name change I guess. Ditched the bogus one and all is well.

Yes, renaming sections works perfectly now. All good.
