### ISSUE TITLE
Empty Sitemap

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#774]
### Describe the bug
We have a couple of singles where the sitemap is definitely enabled in both SEOmatic settings and the SEOmatic field for the entry. However the generated sitemap is empty.

```<!--  This sitemap has not been generated yet.  -->
<!--  If you are seeing this in local dev or an  -->
<!--  environment with `devMode` on, caches only  -->
<!--  last for 30 seconds in local dev, so it is  -->
<!--  normal for the sitemap to not be cached.  -->
<urlset> </urlset>```

You can see an example of this here: https://www.ihrsa.org/sitemaps-1-section-internationalLanding-1-sitemap.xml

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Expected behaviour
A clear and concise description of what you expected to happen.

### Screenshots
If applicable, add screenshots to help explain your problem.

### Versions
- Plugin version: 3.3.9
- Craft version: 3.4.27

**Comment by khalwat** [comment]
Please check your logs for details... it looks like many (most?) of the sitemaps generate properly, from looking at https://www.ihrsa.org/sitemaps-1-section-aboutLanding-1-sitemap.xml

There must be some kind of issue with this section in particular, and perhaps the server logs will help you find out what it is.

**Comment by khalwat** [comment]
I checked all of the 30 or so sitemaps that SEOmatic is generating for you; the following fail to generate a sitemap for:

https://www.ihrsa.org/sitemaps-1-categorygroup-articleTopics-1-sitemap.xml
https://www.ihrsa.org/sitemaps-1-section-clubDeveloperDetail-1-sitemap.xml
https://www.ihrsa.org/sitemaps-1-section-internationalLanding-1-sitemap.xml

So look for commonalities with them. Do they have URLs disabled? Is there an issue with the multi-site setup for them?

Also it's very likely that if SEOmatic encounters an error generating them, it'll be logging that error, so check your `queue.log` for errors as well (sitemaps are generated via queue jobs).

**Comment by CreateSean** [comment]
I looked at queue.log and searched for `categorygroup`, `articleTopics`, `clubDeveloperDetail`, and `internationalLanding` and got no results.

categorygroup-articleTopics - is a category group
clubDeveloperDetail - is a channel
internationalLanding - is a single.

All of those have urls and we are not using multi-site

**Comment by khalwat** [comment]
1. Delete all of your logs in `storage/logs`
2. Replicate the problem by reloading the sitemap page
3. Email ALL of the logs to me

**Comment by khalwat** [comment]
So the error is in the `web.log` that you sent me:

```
So the error is:

2020-10-30 11:01:42 [-][-][-][warning][yii\caching\Cache::getOrSet] Failed to set cache value for key "MetaTagContainergeneralseomatic_metacontainer_publications\/music-licensing-in-the-united-states1page1publications\/music-licensing-in-the-united-states"
2020-10-30 11:01:42 [-][-][-][info][application] $_GET = [
    'p' => 'publications/music-licensing-in-the-united-states/'
    'hsa_ver' => 'test’
]

```

This is a low-level caching error from the Yii2 framework, so this is very likely something awry with your server setup.

What caching method are you using for Craft? Are you setting it to anything different in `config/app.php` ?

**Comment by CreateSean** [comment]
Andrew,

Nothing cache related in config/app.php

We do have cache flag installed https://plugins.craftcms.com/cache-flag

I don't have access to the server config, but I can email the server guy - is there something in particular that he should look at?

**Comment by khalwat** [comment]
If you have changed nothing, then you will be using file-based caching.

Make sure it isn't out of disk space, that there's nothing misconfigured with the way PHP temporary files/directories are stored, etc.

It's likely you'll run into other caching issues as well, as this is a lower-level issue.

**Comment by CreateSean** [comment]
@khalwat 

The server guy responded with:

> Disk space is fine. 65% usage. Any other problems with caching going on? I don't know how the plugin is supposed to work so I'm not sure how valid the comments are regarding caching.


and the project manager has asked me to follow up with you to resolve this.

**Comment by khalwat** [comment]
I'm really not sure what to tell you, other than the error is not from SEOmatic, but rather from the Yii2 caching method which is trying to store the cached information.

_something_ with the caching setup is likely not right. I'd suggest having it switch over to Redis as a caching method for the server

**Comment by CreateSean** [comment]
Looking locally I see the sitemap generated correctly. based on what you stated it seems clear that there is an issue with the live server. Sorry for the trouble

**Comment by roelvanhintum** [comment]
How did you solve this? I'm running into the same problem. I'm using a docker environment and redis with a separate queue listener.

**Comment by roelvanhintum** [comment]
@khalwat this seems to be related to `runQueueAutomatically` being turned off. Even running `php /var/www/craft seomatic/sitemap/generate` on deploy doesn't fix this. With `runQueueAutomatically` turned on i do get the expected results.

Every time for example `sitemaps-1-section-page-1-sitemap.xml` is loaded, i'm seeing the queue runner do the following. 
```log
Query 1/1 - elements: 16 
Processing element 1/16 - Example
...
Processing element 16/16 - Last example
Sitemap cache result: 1 for cache key: seomatic_sitemap_1sectionpage1 
```
(redacted actual titles)

The result is always (with `runQueueAutomatically` turned off):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="sitemap-empty.xsl"?>
<!-- This sitemap has not been generated yet. -->
<!-- If you are seeing this in local dev or an -->
<!-- environment with `devMode` on, caches only -->
<!-- last for 30 seconds in local dev, so it is -->
<!-- normal for the sitemap to not be cached. -->
<urlset>
</urlset>
```

**Comment by khalwat** [comment]
Is it possible you have some kind of frontend caching that's interfering here @roelvanhintum ?

**Comment by roelvanhintum** [comment]
@khalwat, yes there is a varnish cache, but even switched off it has no effect on this.

**Comment by roelvanhintum** [comment]
Weird thing is it does work on another website using the same setup with also `runQueueAutomatically` disabled. This one does have an active varnish cache. This one is not up-to-date yet, using:
Craft Pro 3.6.10
SEOmatic 3.3.35

**Comment by khalwat** [comment]
You sure ensure that your Varnish cache is not interfering; perhaps it is caching the sitemap page while it is still being generated.

**Comment by roelvanhintum** [comment]
When it's still loading the SEOMatic correctly returns an 503 code. This prevents varnish from caching it.

**Comment by roelvanhintum** [comment]
@khalwat thanks for your patience with me. Exactly as you discussed on devMode.fm it was a config problem. Sorry about that.

Solution: In this case the config was wrong which caused the file cache to be used instead of redis. With the queue separated it will never work (queue was in a different container).

**Comment by khalwat** [comment]
Ah, makes total sense. Glad you got it sorted!
