### ISSUE TITLE
Sitemaps aren't loaded from the redis db

### ISSUE THREAD

**Issue by jripmeester** [nystudio107/craft-seomatic#775]
### Question
To be honest i don't know if this is a bug or i missed someting in the configuration.

We use redis caching on our Craft 3.5.14 website with SEOMatic 3.3.22.
We created the sitemaps in the console to be sure that they were generated.
We checked the redis db if the key of the generated sitemap is there and it is.

But still when we vist the sitemaps url we get the message:
This sitemap has not been generated yet.

Some well placed var_dumping learned us that the correct key is being parsed but still the cache gives false on its existence.
A small snippet from the dumps:

string(47) "heiming-ab-site989f98a661e12334570b543a3c8a3dab"
  | string(22) "below is the right key"
  | string(47) "heiming-ab-site9188c6839fc04cee5105a5acb6df36ca"
  | bool(false)
  | string(47) "heiming-ab-sitec3fa226a453653cf8038e93dee825cc7"

Or am i barking at the wrong tree and is this something Craft is handling?
 
Any help is appreciated.

**Comment by khalwat** [comment]
That's interesting, are you having issues with your Redis cache for other things as well?

If I understand what you're saying correctly, the correct cache key is used to save the sitemap, and the correct cache key is used to retrieve it, but it returns `false` ?

**Comment by jripmeester** [comment]
@khalwat I've print_r-ed my ass of last friday and after two hours of investigating, calling with host, refreshing caches en rebuilding. It suddenly started working. Host says they didn't change anything...

Which is probably even more frustrating than it not working because it keeps you guessing. So for now we can ignore this and hopefully it stays this way.
