### ISSUE TITLE
SEO field - set seo image from commerce product variant fields

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-seomatic#776]
Right now, using SEO field we can attach SEO image functionality to product asset fields, but not fields attached to product variants.

**Comment by khalwat** [comment]
I've looked into what it'd take to support this under the hood, and unfortunately I think the verdict for now is that you need to add the Asset to the Product itself, rather than the variant. This is to ensure that it will always exist regardless of the variant chosen.
