### ISSUE TITLE
Robots = all in settings but none appears on the site 

### ISSUE THREAD

**Issue by tyssen** [nystudio107/craft-seomatic#777]
### Describe the bug
I have robots set to all under Global SEO and under Content SEO for each section (and entry type) but on the front end, all pages have robots set to none.

This is on a staging site but the site owners have things set up so that all changes are made on staging and then they run migration scripts which will copy everything including the database from staging to production, so no changes actually get made directly on production.

The strange thing is, on the production site, there's just one page that has robots set to none. And it's that one page that I'm trying to fix. I've tried changing the SEO settings field for that page to All but when I save, it reverts back to having no value again. I've seen a couple of other issues that mention this but it seems with the other issues, that the setting wasn't saved properly in the global/content settings. 

### To reproduce
Steps to reproduce the behaviour:
1. Check all general / content SEO robots settings = all
2. Check source of pages; robots = none
3. Clear Craft caches
4. Check source again; robots = none
5. Try saving individual page robots to all; robots = none on the front end

### Expected behaviour
Robots should equal all for all pages on the front end.

### Versions
- Plugin version: 3.3.18
- Craft version: 3.5.11.1

**Comment by khalwat** [comment]
So for the Staging site, this is expected behavior; SEOmatic is protecting you from Google indexing your staging site. This is discussed here:

https://nystudio107.com/docs/seomatic/Configuring.html#general-plugin-settings

> Environment - The server environment, either live, staging, or local. If devMode is on, SEOmatic will override this setting to local Development. This setting controls whether certain things render; for instance only in the live production environment will Google Analytics and other tracking tags send analytics data. SEOmatic also automatically sets the robots tag to none for everything but the live production environment.

On production, for the one page that is not set to "all" can you tell me more? What section is it? Is it just one entry in a section, or an entire section? Is the sitemap active for it?

**Comment by tyssen** [comment]
It's just one entry in a section. It's the largest section on the site. But the entry type that the entry uses is only used on that one entry. Not sure if that's relevant.

The sitemap is active for that section and the page with robots set to none appears in the sitemap.

**Comment by khalwat** [comment]
Ping me on Discord to set up a screen sharing session; I think I'd need to take a closer look at the setup here.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/d117e770b5ef71b6ccd7bf4c1b1a8153f18e26bd
