### ISSUE TITLE
Seomatic uses non unicode safe string functions when builds meta value from entity atrributes

### ISSUE THREAD

**Issue by spushchin** [nystudio107/craft-seomatic#778]
### Describe the bug
Seomatic metavalue length is limited to 4096 characters. When seomatic cuts metavalue string to fit this requirement it uses strlen and substr PHP functions. Since those functions are not Unicode safe, when a multibyte character is at this position it breaks it and produces non-valid Unicode string. This leads to further exceptions when you try to use it in JSON responses. For example in GraphQL API. 
```
2020-11-06 13:54:01 [-][1][-][error][nystudio107\seomatic\models\MetaJsonLd::render] yii\base\InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded. in craftcms/vendor/yiiso
Stack trace:
#0 craftcms/vendor/yiisoft/yii2/helpers/BaseJson.php(67): yii\helpers\BaseJson::handleJsonError(5)
#1 craftcms/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(73): yii\helpers\BaseJson::encode(Array, 1)
```
craft-seomatic/src/helpers/MetaValue.php:261
```
// Ensure we aren't passed in an absurdly large object template to parse
            if (strlen($metaValue) > self::MAX_TEMPLATE_LENGTH) {
                $metaValue = substr($metaValue, 0, self::MAX_TEMPLATE_LENGTH);
            }
```

### To reproduce
Steps to reproduce the behaviour:
1. Create  content entity with some text that is longer than 4096 characters and contains Æ, Ø, and Å only for example
2. Try to call GraphQL seomatic function in GraphQL explorer
```
query SEOmaticDoesNotWork{
  seomatic(uri: "<your created entity URL>", asArray: true) {
    metaJsonLdContainer
  }
}
```

3. In the web.log you will see
`2020-11-06 13:54:01 [-][1][-][error][nystudio107\seomatic\models\MetaJsonLd::render] yii\base\InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded. in `

### Expected behaviour
There should be no errors with such API call

### Versions
- Plugin version:3.3.19
- Craft version: Craft CMS 3.5.14

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/d47426ff29d57fca0de88101617e0ad794cb4cb4
