### ISSUE TITLE
[FR] Migrate data from the `seomatic_settings` table

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-seomatic#78]
Look into migrating data from the old `seomatic_settings` table from the Craft 2.x version of the plugin where applicable.

Some of this data won't have a 1:1 mapping, given the new architecture of the plugin, and it's mostly settings that are entered once on the Site Settings pages.

Still, look to see what could potentially be migrated.

**Comment by timkelty** [comment]
Want!

**Comment by khalwat** [comment]
So all this will really migrate are things that are pretty easy to migrate yourself, that is things like the Company Name, and so on.

The bulk of the useful migration of data is already done via the Field

**Comment by timkelty** [comment]
Sorry, didn't read 😛
