### ISSUE TITLE
JsonLd product availability not checking for all variants

### ISSUE THREAD

**Issue by WHITE-developer** [nystudio107/craft-seomatic#780]
### Describe the bug
When using multiple variants, the JsonLd only checks for the default variant

`'availability'  => 'http://schema.org/{% if object.product.getDefaultVariant().getIsAvailable() %}InStock{% else %}OutOfStock{% endif %}'`

I think there should be checked for all available stock like

`'availability'  => 'http://schema.org/{% if object.product.totalStock > 0 %}InStock{% else %}OutOfStock{% endif %}'`

### Versions
- Plugin version: 3.3.22
- Craft version: 3.5.15.1

**Comment by khalwat** [comment]
Seems like a reasonable change. How backwards compatible is `totalStock`? Has it been in Commerce since day 1?

**Comment by khalwat** [comment]
mmmm one rub though is the Commerce docs say:

> The total stock of all variants. Will show zero if all variants are set to unlimited quantity.

So perhaps something like this:

```twig
{% if object.product.unlimitedStock or object.product.totalStock > 0 %}InStock{% else %}OutOfStock{% endif %}
```

Changed in: https://github.com/nystudio107/craft-seomatic/commit/8cb459d288104eefd50d8bd4a9c73fa646e64ae8
