### ISSUE TITLE
Tracking ID Fields Allow Whitespace

### ISSUE THREAD

**Issue by M-Drummond** [nystudio107/craft-seomatic#781]
### Is your feature request related to a problem? Please describe.
When adding the GTM or GA codes to the site, any whitespace before or after will stop the tracking code from working.  

### Describe the solution you would like
Clear the whitespace from before / after the code.  

### Describe alternatives you have considered
It's easy to check, but it'd be nice to just be able to paste in code that's gone through a thousand email fw:fw: messages into the field

### Additional context
I'm aware that this is exteremely minor.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/35f0d45196f146cfbf18fbe2e2b0a5367135ebee

You can set your semver in your `composer.json` to this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.25",
```

And then do `composer update` and test it in your environment?
