### ISSUE TITLE
W3C warning on SEOmatic GTM tracking script type attribute

### ISSUE THREAD

**Issue by ryanmasuga** [nystudio107/craft-seomatic#782]
### Question
We're using the Google Tag Manager tracking script. I'm validating pages using the W3C Validator at https://validator.w3.org/nu/ and getting a warning about the GTM script tag: 

> **Warning** The `type` attribute is unnecessary for JavaScript resources.

![w3c-error](https://user-images.githubusercontent.com/988995/99815881-ec623280-2b18-11eb-8818-82a5bf0e4f21.jpg)

And the source: 

![line12](https://user-images.githubusercontent.com/988995/99815892-f2581380-2b18-11eb-9c74-38819a562a55.jpg)

It's not possible to edit the script tag itself in SEOmatic's script editor, and I'm not seeing anywhere else I can edit it. If I am able to update that, I'd like to not have that change blown away with an SEOmatic update.

Am I missing where this can be changed?

Craft 3.5.15
SEOmatic 3.3.22

**Comment by khalwat** [comment]
It's totally fine to have `type="text/javascript"` in that `<script>` tag. There is currently no way to remove it, but it's also completely harmless, and just being explicit.

**Comment by khalwat** [comment]
Removed in https://github.com/nystudio107/craft-seomatic/commit/ae54adc5b2329bf1877570836d79398be1280c10
