### ISSUE TITLE
seomatic.helper.getLocalizedUrls does not behave as described

### ISSUE THREAD

**Issue by MattWilcox** [nystudio107/craft-seomatic#783]
### Describe the bug

`seomatic.helper.getLocalizedUrls(URI, SITE_ID) - Return a list of localized URLs for a given URI that are in the SITE_ID site's group. Both URI and SITE_ID are optional, and will use the current request's URI and the current site's SITE_ID if omitted`
From https://nystudio107.com/docs/seomatic/Using.html#config-variables-seomatic-config

If I am reading this correctly; `{{ dump( seomatic.helper.getLocalizedUrls ) }}`, when called on a site that belongs to a Site Group, should produce an array of URI's for other sites that are in the same Site Group - and not include URIs for sites that are not in the same Site Group.

However, when called it is not restricting its output to the site group to which the calling site belongs.

I have four Sites, in two Groups.
<img width="986" alt="Screen Shot 2020-11-22 at 18 45 27" src="https://user-images.githubusercontent.com/814039/99914119-166f4c80-2cf3-11eb-9f6f-16691281acb9.png">

I call this code in a template when accessing the primary site URL
`{{ dump( seomatic.helper.getLocalizedUrls ) }}`

I get four items output, not two.
<img width="544" alt="Screen Shot 2020-11-22 at 18 47 27" src="https://user-images.githubusercontent.com/814039/99914210-c1800600-2cf3-11eb-854a-e560718de122.png">

### Expected behaviour

The output of the tag should allow me to have translations for the site group to which the viewed site belongs, omitting other site groups.

As it stands, the following code does not in fact provide "other language versions" of the current page for the current site group, but rather every other language version of the current page regardless of whether it's in the GLLM group or the Busnes group.

```
{% for localizedUrls in seomatic.helper.getLocalizedUrls()  %}
	{% if localizedUrls['language'] != craft.app.language %}
		{% if localizedUrls['language'] == 'en-GB' %}
			<a href="{{ localizedUrls['url'] }}" lang="en-GB">
				English
			</a>
		{% elseif localizedUrls['language'] == 'cy-GB' %}
			<a href="{{ localizedUrls['url'] }}" lang="cy-GB">
				Cymraeg
			</a>
		{% endif %}
	{% endif %}
{% endfor %}
```

### Versions
- Plugin version: 3.3.23
- Craft version: 3.5.15.1

**Comment by MattWilcox** [comment]
PS: I suspect that SITE_ID should in fact be groupID `{{ currentSite.groupId }}`? Or at least something in SEOmatic ought to be looking up the groupId of the passed siteId.

**Comment by khalwat** [comment]
So it should be restricting it to just URLs from the site group that the site is in:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L598

What is your **Site Groups define logically separate sites** setting in SEOmatic -> Plugin Settings -> Advanced set to?

**Comment by MattWilcox** [comment]
Wow; I did not know about that control; but yes reading that it's obvious I should turn it on... and yes that worked! Thanks.

Is there a reason why that's not on by default? Can't think why you'd want the other behaviour, but I may be missing something (else) obvious. Perhaps worth a mention in the docs that the behaviour also relies on that toggle being on?

**Comment by khalwat** [comment]
It is on by default so... ¯\_(ツ)_/¯ 

https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/Settings.php#L125

**Comment by MattWilcox** [comment]
Huh! Must have been something in our default build that got flipped at some point by accident. Cheers Andrew; I'll toggle that on our vanilla base project.
