### ISSUE TITLE
Keywords should not constitute towards an 'A' grade? And a general discussion on the grade system...

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#784]
### Question
As far as I know keywords are dead and redundant as a META field, certainly for Google. I appreciate there might be some search engines that still use these. However, I understand that the main-stream ones do not.
Therefore, I wonder if these should wight in on the Grading at all? I would tend to ignore them, but my OCD wants an A Grade and if Keywords are omitted then it gives a 'B' grade.

The other comment, I have on this, is if SEOmatic should look up the chain (from content to Global) and base the score on this, so if content keywords are missing, but global have been added, should that still give an A rating?    

Any thoughts? I'm open to discuss further on Discord, if it helps.

I have to admit, I am not a fan of the Grade score, and wonder if there is a better way? As there are sometimes genuine reasons, not to complete all the content settings. This might be down to the page use themselves (members area pages), setting the meta-data within the template, or falling back on global data for any reason.
All of which potentially illustrate to a poor rating and set up, which in turn clients might question.

**Comment by khalwat** [comment]
Going to disagree here, because it's pretty simple to set SEOmatic up to extract keywords from existing content... and while Google does not use keywords, other search engines do.
