### ISSUE TITLE
Meta description striping + symbol character (plus symbol) in content settings (source from field)

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#785]
### Describe the bug
I have noticed a bug in the meta description is stripping the + (plus symbol) when setting this from a field in the content settings.
I have not tested other characters.  

### To reproduce
Steps to reproduce the behaviour:
1. Create a field and enter some text that contains a + (plus symbol) 
2. In content settings use the SEO Description Source from field as the field that contains this content.
3. See that the + (plus symbol) has been stripped  in the preview and source code.

### Expected behaviour
I expect the + (plus symbol) to remain within the description.

### Screenshots
Some screenshots to illustrate:

 **Entry Page (with source field) (introduction)**
<img width="1038" alt="Screenshot 2020-11-25 at 14 05 34" src="https://user-images.githubusercontent.com/5698596/100238000-97168e80-2f27-11eb-9492-d90fa6d90257.png">

**SEO Contents Settings for above page**
<img width="1162" alt="Screenshot 2020-11-25 at 14 08 35" src="https://user-images.githubusercontent.com/5698596/100238117-bb726b00-2f27-11eb-8fd8-57f22d9d6aa9.png">

**Output of the bug in the preview, source code and front-end**
<img width="673" alt="Screenshot 2020-11-25 at 14 10 11" src="https://user-images.githubusercontent.com/5698596/100238304-f379ae00-2f27-11eb-8746-94918b274bf9.png">

<img width="1224" alt="Screenshot 2020-11-25 at 14 05 11" src="https://user-images.githubusercontent.com/5698596/100238176-cd540e00-2f27-11eb-96ab-7cd39c85aa1b.png">

<img width="668" alt="Screenshot 2020-11-25 at 14 05 28" src="https://user-images.githubusercontent.com/5698596/100238234-de9d1a80-2f27-11eb-935b-86047d6af32a.png">

### Versions
- Plugin version: 3.3.24
- Craft version: Craft Pro 3.5.15.1

**Comment by terryupton** [comment]
Were you able to replicate this at all @khalwat?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/bfec69498b20daf381220a2fb43b5d01140390fb

**Comment by elunaj** [comment]
@khalwat my team is currently dealing with this issue. I saw that a fix was added but later reverted back here: https://github.com/nystudio107/craft-seomatic/commit/7a286feb3354d85710c487bcce74438d465492d8

Is there a solution you could point us to? Appreciate any help you could provide. Thanks.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/1a556d393f16d84a1afcfbd2397c357e0812aef7

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by elunaj** [comment]
Great, that takes care of the bug -- thank you!
