### ISSUE TITLE
Robots / "None - do not index or follow links on this page" selection not sticking

### ISSUE THREAD

**Issue by michaelfromtheoutfit** [nystudio107/craft-seomatic#786]
### Describe the bug
On a page entry, if you select "None - do not index or follow links on this page" the selection is not sticking. The front-end is functioning correctly in that the `<meta name="robots" content="none">` tag is appearing as expected. It's simply that the dropdown in the control panel shows an empty selection rather than displaying your selection.

### To reproduce
Steps to reproduce the behaviour:
1. Go to any entry with an SEOmatic field
2. In the "Robots" field, select "None - do not index or follow links on this page"
3. Save entry
4. Revisit entry and see that the field no longer has that selection in the dropdown, and in fact - the dropdown selection is empty

### Expected behaviour
After selection "None - do not index or follow links on this page" when you revisit that entry in the CMS, the dropdown should display "None - do not index or follow links on this page" as the selected value

### Screenshots
![Screen Shot 2020-11-30 at 1 50 19 PM](https://user-images.githubusercontent.com/4431398/100651127-fd7a2300-3312-11eb-8ce6-56aeb537f309.png)

### Versions
- Plugin version: 3.3.24
- Craft version: 3.5.15.1

**Comment by khalwat** [comment]
So this is probably not a bug, but rather poor UX.

The SEO Settings field is an override, and if any values are empty, it doesn't override the Content SEO settings.

If you set the value of a field to something that's the same as the Content SEO settings, it says "Oh, this is the same, it's not override anything" and it sets it to empty.

More here: https://github.com/nystudio107/craft-seomatic/issues/535

**Comment by michaelfromtheoutfit** [comment]
Understood! Thank you sir.
