### ISSUE TITLE
Default settings do not appear anymore when creating a new entry

### ISSUE THREAD

**Issue by petertindemans** [nystudio107/craft-seomatic#787]
### Describe the bug
Since a few weeks we noticed that the default values that are set in the plugin config are not applied anymore when creating new items. To be more specific the source fields

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Content SEO"
2. Set some default value for "Source field"
3. Now create a new entry

### Expected behaviour
I would expect that the default source field would apply on new entries (it did in the past).

### Screenshots
Default settings > Content SEO > [[ Section ]]
![Schermafbeelding 2020-12-02 om 22 22 24](https://user-images.githubusercontent.com/19586163/100932904-dd05c080-34ec-11eb-98ea-66c160d6aeca.png)

Settings when creating a new item:
![Schermafbeelding 2020-12-02 om 22 19 02](https://user-images.githubusercontent.com/19586163/100932970-ee4ecd00-34ec-11eb-877c-b957efd01519.png)

### Versions
- Plugin version: SEOmatic 3.3.18
- Craft version: Craft CMS 3.5.16

**Comment by khalwat** [comment]
So unless I'm misunderstanding something here, this is not a bug.

The SEO Settings field is an override... any anything that is blank or empty in it will cause it to not override the existing settings in Content SEO.

You won't see the settings from Content SEO reflected in the SEO Settings field... this is bad UX that we have an issue about fixing: https://github.com/nystudio107/craft-seomatic/issues/535
