### ISSUE TITLE
Should gTag now be the default (top) option in tracking section?

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#788]
So Google seems to want to push people down the route of gtag with their latest GA4 and how the step by step process is now offered in Google Analytics. I wondered whether the order should be adjusted on the tracking section to put gtag as the first option. It also looks like they use a different structure for the tracking ID.

Rather than the old `UA-XXXXXX-XX` it now seems to use `G-XXXXXXXXXX` - so perhaps the little note should also be updated to reflect this - just for transparency and help avoid confusion for anyone setting it up.

**Comment by khalwat** [comment]
Yeah probably this should happen... I've been wanting to vette the changes in GA4

**Comment by sunscreem** [comment]
Yeah, quick thought on this, it would save client confusion if it could say `GA4` in the left menu too.

**Comment by sg-modlab** [comment]
Can the GA4 tag be added via SEOMatic or best to do outside of it?

**Comment by khalwat** [comment]
@sg-modlab It should be pretty easy for me to add it in, I just want to do a little more testing

**Comment by khalwat** [comment]
SEOmatic can already implement GA4. Most of the work is in the Google Analytics admin where you set up a new property; gtag is meant to be used to send data to it as per: https://developers.google.com/analytics/devguides/collection/ga4

I'll be updating the verbiage to make this more clear.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/cb53e5e95d6a00af40f8677d1d3a5e38c88424bc
