### ISSUE TITLE
Large Twitter Cards without Twitter username?

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft-seomatic#789]
If I tweet a link to one of my sites, despite having "Summary Card with Large Image" selected, it always shows the smaller default Summary card. Perhaps this is a dumb question but is that because I don't have a username entered? Sorry, if it says this in the documentation... I couldn't find it.

**Comment by khalwat** [comment]
Yes, you need to have a Twitter handle entered for Twitter Cards to work properly.
