### ISSUE TITLE
Content SEO Title field not pulling Global settings (before, after...)

### ISSUE THREAD

**Issue by juresrpcic** [nystudio107/craft-seomatic#79]
Here's what I'm doing on a fresh install of `3.0.0-beta.24`

- working on my auto-generated titles
- first set Global SEO - Site name position to "After"
- went into my Content SEO sections (have a bunch on this site) and I can see the Site name position source is set (as by default) to "Same as Global Site Name Position"
- the SEO Preview still shows the site name it on the left though (didn't pull through the Global change to "after")
- after resaving a few Content SEO sections without doing anything to them (just pressed "save"), _some_  of the sections showed an update (moved site name to "after") and some didn't (still stuck on "before")
- to hard force the change, I selected something in the dropdown (ie. custom position) and then changed back to "Same as global" and then it saved properly (only needed in the sections that didn't work by simply resaving with no changes)

**Comment by khalwat** [comment]
Interesting. Will try to reproduce!

**Comment by juresrpcic** [comment]
Also spotted that the ones that didn't get fixed by saving were empty (sections didn't have any entries yet - so showed "SITE NAME | Home" - instead of "Home | SITE NAME").

**Comment by khalwat** [comment]
I've investigated this, and it appears to be because you've been using beta version that had stale data in some of the settings from earlier beta versions.
