### ISSUE TITLE
Setting robots value by entry type or entry

### ISSUE THREAD

**Issue by russback** [nystudio107/craft-seomatic#791]
### Question
Is it possible to set a robots value at an entry level? And on that note, on an entry type level, rather than just section level?

**Comment by khalwat** [comment]
Yep, you can do that. SEOmatic has separate settings per entry type in Content SEO. There's a dropdown menu on the top left.

**Comment by russback** [comment]
Sorry, I'm only seeing that available by Section, not for Entry Types within each Section? For example I have a Pages section with different Entry Types and I can only set robots at the Pages level.

Also it would mean I would need to set up a new Section just for pages that I don't want indexed, which creates a bit of a confusing setup for editors and duplication of field layouts. Would it be possible to add a setting to define robots at an Entry level that overrides settings at a higher Entry Type or Section level?

**Comment by khalwat** [comment]
Can you give me a screenshot please? Are you not seeing this?

<img width="701" alt="Screen Shot 2020-12-10 at 7 44 12 AM" src="https://user-images.githubusercontent.com/7570798/101774048-918a7e00-3abb-11eb-9737-c3bda966b9e5.png">

**Comment by russback** [comment]
I'm not seeing that first dropdown:

<img width="505" alt="Screenshot 2020-12-10 at 12 52 23" src="https://user-images.githubusercontent.com/2589006/101774961-b47e5780-3ae6-11eb-8452-8c66bae46dd2.png">

**Comment by khalwat** [comment]
And you definitely have entry types for the "Pages" Section?

Do you have other sections with the same name of "Pages" perchance?

**Comment by russback** [comment]
Sorry, I had the wrong type selected! I can see that now.

What's your view on a per-entry setting to avoid having to create Entry Types just to achieve that?

**Comment by khalwat** [comment]
If you really, truly need per-entry settings, you can do that using the SEO Settings field. Generally, it's probably not needed though.

**Comment by russback** [comment]
OK thanks.

I’m seeing an issue though I think.

I have a Section which has 4 Entry Types. I am trying to set 1 of them to index and others not to. However when I switch between Entry Types in the Content Settings, the change applied to 1 Entry Type appears to be applied to all Entry Types.

[This video](https://www.awesomescreenshot.com/video/2039641?key=9d11e44f82d1f27b1828c7cfdf9808ab) shows me changing the settings.

Also on the frontend when viewing an Entry that is of Entry Type Gift Listing (this is the Entry Type I want to be indexed), robots is set to none. I have checked the SEO Settings on the Entry, and the Robots field does not have a value selected so it doesn’t seem to be an override causing this.
