### ISSUE TITLE
Cannot translate plugin menu in control panel

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-seomatic#792]
I don't mean the main menu link which is configurable by config. But sub-links like "Global SEO". When I translate it using static translations, title appears on "global seo" page in an alternate language, but menu links stays english.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/5078b81b458822b9112a6e1dd485466256de5a4d
