### ISSUE TITLE
Unexpected Content SEO UI behavior

### ISSUE THREAD

**Issue by jmauzyk** [nystudio107/craft-seomatic#794]
### Describe the bug
Noticing a couple issues with Content SEO edit pages for channels with multiple entry types. First is that when navigating to a Content SEO edit page from the Content SEO index, the page loads without any `typeId` query param. As a result, it seems like the edit page loads the most recently updated Content SEO settings for that channel, even if it is for the wrong entry type. Second is that the selected entry type is not maintained when switching between different settings panes within the Content SEO edit page, which is confusing and can lead to accidentally updating settings for the wrong entry type.

### To reproduce
Steps to reproduce behavior 1:
1. Go to a Content SEO edit page for a channel with multiple entry types.
2. Select an entry type that is not first in the entry type list, then set the SEO Image Source (different than what is set for the first entry type) and save.
3. Go back to the Content SEO index. From there, select the Content SEO edit page you just edited.
4. When edit page loads, the entry type selector will be set to the first entry type in the list, but the Content SEO settings in the main pane will be those from the entry type that was last edited.

Steps to reproduce behavior 2:
1. Go to a Content SEO edit page for a channel with multiple entry types.
2. Select an entry type that is not first in the entry type list.
3. Select the Twitter settings pane.
4. When Twitter settings pane loads, the entry type is reset to the first in the list and the `typeId` query param has been removed from the URL.

### Expected behavior
Content SEO edit page main pane should display settings for the selected entry type on load. Selected entry type should be maintained when switching between different settings panes in the Content SEO edit page.

### Versions
- Plugin version: 3.3.26
- Craft version: 3.5.16

**Comment by khalwat** [comment]
Will have a look @jmauzyk

**Comment by Mosnar** [comment]
This one just bit me - it's really easy to overlook if you're making lots of updates.

**Comment by khalwat** [comment]
Related? https://github.com/nystudio107/craft-seomatic/issues/814

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/a0f6551885fcd1101044a543c7b9728409316989

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.37”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.37

Let me know if you have further issues with it
