### ISSUE TITLE
Setting noindex,nofollow on pages that have query string parameters

### ISSUE THREAD

**Issue by rob-c-baker** [nystudio107/craft-seomatic#796]
If I call:

```twig
{% if craft.app.request.get('token')|length > 0 %}
    {% do seomatic.tag.get('robots').content('noindex,nofollow') %}
{% endif %}
```

On a layout template, above the call to `{{ head() }}` then if the page with the parameter we are testing for is found then the robots tag is set. When the page is reloaded, with or without the parameter we are testing for, it always renders `noindex,nofollow` in the robots tag, until the cache expires **and the version without the parameter** is refreshed / hit with an empty cache.

I suspect the cache is being populated with the content of the twig call above and then used, on subsequent pages loads, essentially ignoring the call when the cache is primed and valid.

### Expected behaviour

There ought to be a way to safely set different robots tag values (and other meta / link tag values) based on the presence or otherwise of GET parameters.

In our case, a third party has linked to our site with parameters that should not be there (i.e. `token`) and that URL (along with hundreds of others) has appeared in Google along with the correct version (with no parameters) and is thus diluting our "link juice" - it's a "duplicate" page.

Seems to be related: https://github.com/nystudio107/craft-seomatic/issues/325

### Additional Problem

The other problem seems to be that when we successfully set `noindex` the canonical tag does not render unless you call:

```twig
{% do seomatic.link.get('canonical').include(true) %}
```

I can understand why this was done, but it prevents us from being able to point search engines at the right URL when the wrong one is hit.

### Versions

- Plugin version: 3.3.24
- Craft version: 3.5.16

**Comment by khalwat** [comment]
SEOmatic's caching does not take query string parameters into account. I think the proper solution to the problem here is already implemented. If you have the following URLs:

```
/product/widget
/product/widget?color=red
/product/widget?color=red&size=small
```

These will _all_ properly have the canonical URL pointed to:

```
/product/widget
```

You don't need to tell Google not to index the pages that have query strings associated with them, as long as the canonical URL is pointed to the right place, Google will understand what the relationship between the pages are, and your search juice will not be diluted.

https://www.hallaminternet.com/avoiding-the-seo-pitfalls-of-url-parameters/

If I'm missing something here, please let me know.

**Comment by rob-c-baker** [comment]
> You don't need to tell Google not to index the pages that have query strings associated with them, as long as the canonical URL is pointed to the right place, Google will understand what the relationship between the pages are, and your search juice will not be diluted.

This is true but it's also true that if you can mark the incorrect variants with `noindex` and resubmit the URLs they will disappear from Google's index faster. It's also true that canonical URLs are just a suggestion, looking through the various search consoles we have for the sites we run, there are several cases where Google picks a different URL than the one we mark as canonical.

I have also investigated how we might issue noindex with custom Module code or via headers at the NGINX level. While this is possible it has issues: When setting headers with NGINX the robots value often conflicts with the value on-page. When using a Module, we have to re-process the HTML and swap out the robots meta tag values.

We may end up with adding rules to robots.txt along the lines of `Disallow: /*token=*` for this example and then for any others in the future. It's not my preferred solution - it obscures the state of the page for content editors / marketing teams, but it should work.

I may also end up writing a plugin that will whitelist URL parameters and offer various ways of dealing with the case where a parameter is not allowed (the parameter sparking this issue is not something our site(s) define - they have been added by a 3rd party).

**Comment by rob-c-baker** [comment]
Something else just popped into my head:

We have had SEO advice on this and there are a [few](https://blogs.perficient.com/2017/11/14/pagination-canonicalization-seo-your-technical-guide) [examples](https://yoast.com/rel-canonical/) [out](https://ahrefs.com/blog/canonical-tags/) [there](https://www.hallaminternet.com/how-use-canonical-tags-properly/) that talk about having canonical tags for paginated pages point to the URL for the current page rather than always to page 1.

This would work fine in this issue's scenario if using URL path segments for page number but if using URL parameters (as it often the case out in the wild) the canonical will be wrong on any page other than the first.

_Edit: This: https://nystudio107.com/docs/seomatic/Technologies.html#pagination-and-seo might address this aspect - I am looking into it, but in our case we are not using Craft's `{% paginate %}` tag for complex reasons not directly related to this task_

_Second Edit: I can call `{% do seomatic.helper.paginate(pageInfo) %}` with a manually created `craft\web\twig\variables\Paginate` object which produces the correct prev/next link tags but no canonical renders for some reason._

**Comment by khalwat** [comment]
> This is true but it's also true that if you can mark the incorrect variants with noindex and resubmit the URLs they will disappear from Google's index faster. It's also true that canonical URLs are just a suggestion, looking through the various search consoles we have for the sites we run, there are several cases where Google picks a different URL than the one we mark as canonical.

Technically _everything_ is just a suggestion to Google :)

Let me know what your preferred solution might be from me. While I could certainly add an option that would allow for the query string to be taken into account as a cache key, understand that:

- This would result in a potentially massive cache, depending on how your site is hit with query strings
- It could also potentially be a source of an external attack, if the attackers decided to try to fill up your cache or bring your site to its knees with tons of uncached hits
- I'm not entirely sure it would actually result in the behavior changing the way you want it to

Google picks the URLs that appear in SERP via their own proprietary algorithm, which is constantly changing. It emphasizes _intent_ as well, and they will rewrite the SERP to reflect advertising, user intent, and a number of other factors that are entirely outside of your control.

How about this for a middle-ground suggestion:

What if you could opt-in to what parameters would or could be part of the caching mechanism?

**Comment by rob-c-baker** [comment]
It seems to me at the moment that meta data set via calls into the seomatic variable in templates is saved as part of the cache and then on subsequent page loads the cached data takes effect on-page even if the template sets something different on the next page load.

If there was a way to override / tweak the contents of the meta data after being loaded from the cache or before it gets rendered (an event or a hook?) then we could achieve all of this, with a very slight performance hit. i.e. just a check for the presence of an non-existent event handler for most sites and for those that choose to tap in to the event - performance is however good or bad their event code is.

I don't like the idea of polluting a cache as you say, nor the potential as a DOS attack vector.

As you mention, I'm not sure an opt-in approach for parameters would work in all cases for us either as if it is a presence check for the parameter, it would not catch all the scenarios we have. If it considers the value of the parameter too, then the cache size issue is worse.

Given a choice, we would prefer the event route if it's an option?

**Comment by khalwat** [comment]
There's a way to do that now -- you can tell SEOmatic to not cache, check this out:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting

You could do this only if there were URL params or such, so that normal hits wouldn't be uncached.

**Comment by rob-c-baker** [comment]
OK, after re-reading that link I think we can make it work. I mis-understood how the multi-level cache works. I didn't want to invalidate caches too much for performance reasons.

If we can do `{% do seomatic.script.container().clearCache(true) %}` and equivalents for the other types of containers in Module code via an event (probably `Container::EVENT_INCLUDE_CONTAINER` ?) then that would get us there... I suppose for specific page conditions we would be disabling **only** that second level cache.

I need to have a play with that and will do the rest of today / tomorrow. I'll close this issue off if necessary.

Thank you!

**Comment by rob-c-baker** [comment]
Just working out implementation - can't see how to do this from `EVENT_INCLUDE_CONTAINER` at the moment due to order of execution:

- `Container::prepForInclusion()` calls the EVENT_INCLUDE_CONTAINER event
- But that happens within a call to `$cache->getOrSet()` so only happens if the cache is not primed
- `Container::$clearCache` is a property that can be set to true but this property is checked before the above call to `$cache->getOrSet()`

If I could call a function within that event to invalidate a specific container cache, that would work. Otherwise unless I am missing something (I could well be!) I will need either a different event, a different approach, or to resort to using Twig for this. The reason I'm not a big fan of that is that I would either need an include dedicated to this task in a bunch of different places, or a lot of copy pasting between templates.

**Comment by khalwat** [comment]
So if you wanted to do it in PHP, probably you can listen to the same View event that SEOmatic does before it includes the containers:

```php
        // Handler: View::EVENT_END_PAGE
        Event::on(
            View::class,
            View::EVENT_END_PAGE,
            function () {
                Craft::debug(
                    'View::EVENT_END_PAGE',
                    __METHOD__
                );
                // The page is done rendering, include our meta containers
                if (self::$settings->renderEnabled && self::$seomaticVariable) {
                    self::$plugin->metaContainers->includeMetaContainers();
                }
            }
        );
```

That would be very similar to modifying settings via Twig.

**Comment by rob-c-baker** [comment]
Got there in the end!

I have hooked into that event roughly like this:

```php
    Event::on(
        View::class,
        View::EVENT_END_PAGE,
        function () {
            $seomatic = Craft::$app->getPlugins()->getPlugin('seomatic');
            if ($seomatic) {
                // do stuff with $seomatic->metaContainers
            }
        },
        null,
        false
    );
```

Many thanks for your help.

Closing.
