### ISSUE TITLE
SEOmatic Field Tabs Stop Working in 3.3.26

### ISSUE THREAD

**Issue by strandofgenius** [nystudio107/craft-seomatic#799]
I am using the SEOmatic field type to add additional settings for entries and categories. When editing any section type or category, clicking the tabs to switch between "General", "Twitter", "Facebook" etc. doesn't switch the panes. I can confirm that it works in 3.3.25.

### Versions
- Plugin version: 3.3.26
- Craft version: 3.5.15.1

**Comment by khalwat** [comment]
This is very strange, I tested this in my local environment, and it seems to be working fine:

<img width="724" alt="Screen Shot 2020-12-18 at 8 48 06 AM" src="https://user-images.githubusercontent.com/7570798/102621590-c6c34b80-410d-11eb-83da-c11d2fc22d96.png">
<img width="724" alt="Screen Shot 2020-12-18 at 8 48 10 AM" src="https://user-images.githubusercontent.com/7570798/102621594-c75be200-410d-11eb-8fea-981f3f2cff2e.png">

**Comment by strandofgenius** [comment]
I checked a couple of different things first trying with a clean install.

1. Install Craft 3.17.1
2. Install SEOmatic 3.3.26
3. Create SEOmatic field
4. Create a new section & add the field
5. Click "new entry"
Before saving the entry I am unable to have the panes switch when clicking the tabs. After I've added the title of the entry click create I am then able to switch between the seo tabs.

On a site that was already populated with content and had version 3.3.25 and then updated to 3.3.26, I wasn't able to switch between the tabs right off the bat. I went to Utilities > Cache > Clear all caches. I went back to my entry and could then switch between tabs. However, when creating a new entry I had the same effect happen as I explained above until I first clicked create new entry first.

**Comment by strandofgenius** [comment]
I'm also noticing that these toggles don't expand until I've clicked save to save the SEOmatic field. Clearing the cache does not seem to get those lightswitches to work.

![Screen Shot 2020-12-18 at 3 03 49 PM](https://user-images.githubusercontent.com/11370639/102661561-ac579500-4142-11eb-81f5-bfc00c9d63dd.png)

**Comment by khalwat** [comment]
Ahh very helpful, thank you.

Fixed in https://github.com/nystudio107/craft-seomatic/commit/6f7d2f41c255288300964d91b440147219daf8a7

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.2.27",
```

Then do a `composer update`
