### ISSUE TITLE
Environment variable not being parsed for Google Analytics Key

### ISSUE THREAD

**Issue by peteeveleigh** [nystudio107/craft-seomatic#801]
When setting the Google Analytics Key via an Environment Variable, the variable name is being rendered in the code snippet rather than being replaced with its value.

### To reproduce
Create an environment variable for the GA key.
e.g. $GOOGLE_ANALYTICS_KEY = 'UA123456'

Use the key in the SeoMatic Tracking Script settings.

Render the template and inspect the generated source.

### Expected behaviour
The key name should be replaced with its value in the rendered template.

### Versions
- Plugin version: 3.3.26
- Craft version: Pro 3.5.17

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/1c0f6c7a1c49b70781a4839048b325cba078d10d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.2.28",
```

Then do a `composer update`
