### ISSUE TITLE
Google Tag Manager ID as env variable now fails

### ISSUE THREAD

**Issue by juddlyon** [nystudio107/craft-seomatic#802]
I've been setting the tag manager container ID via environment variable and it broke during a recent update. The variable isn't swapped so the ID is the string of $GTM_ID. 

_Tracking › Google Tag Manager › Google Tag Manager ID › $GTM_ID_

**Doesn't work:**
Craft CMS 3.5.17.1
SEOmatic 3.3.26

**Still works**
Craft CMS 3.5.14
SEOmatic 3.3.22

I noticed this field doesn't have the lightbulb and message of _This can be set to an environment variable. Learn more_ , maybe I shouldn't be using an env var? I figured it would behave the same as _Google Analytics Tracking ID_.

Any help is greatly appreciated, I have 30+ sites so the more I can do with ENV vars and less in the DB the better.

**Comment by juddlyon** [comment]
I noticed the ENV var language tooltip disappears when you are using a ENV var so you can disregard that part of my message.

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-seomatic/commit/1c0f6c7a1c49b70781a4839048b325cba078d10d

I will release it tonight

**Comment by juddlyon** [comment]
Thank you sir!
