### ISSUE TITLE
Paginated tags not cache busting when Include Paginated hreflang Tags setting disabled

### ISSUE THREAD

**Issue by jmauzyk** [nystudio107/craft-seomatic#803]
### Describe the bug
When the __Include Paginated `hreflang` Tags__ setting is enabled, paginated tags work as expected with mysite.com/blog generating:
```
<link href="https://www.mysite.com/blog" rel="canonical">
<link href="https://www.mysite.com/blog/p2" rel="next">
```
and mysite.com/blog/p2 generating:
```
<link href="https://www.mysite.com/blog/p2" rel="canonical">
<link href="https://www.mysite.com/blog" rel="prev">
<link href="https://www.mysite.com/blog/p3" rel="next">
```

When this setting is disabled however, the paginated tags are output based on whichever page was accessed and cached first. So if I directly access mysite.com/blog/p2 first, then go to the first page, mysite.com/blog generates:
```
<link href="https://www.mysite.com/blog/p2" rel="canonical">
<link href="https://www.mysite.com/blog" rel="prev">
<link href="https://www.mysite.com/blog/p3" rel="next">
```

Also worth noting that even when the setting is enabled and SEO caches are busted, canonical is set to the paginated page itself rather than the first page. Based on [your comments in other issues](https://github.com/nystudio107/craft-seomatic/issues/375#issuecomment-488369209) it seems like this is not working as intended. 

### To reproduce
Steps to reproduce the behaviour:
1. On a production site, disable the __Include Paginated `hreflang` Tags__.
2. Clear all SEOmatic caches.
3. Directly access the URI of the second page of a series of paginated pages. Inspect the code and make note of the canonical, prev, and next tags.
4. Now navigate to the first page in the series. Inspect the code. Canonical, prev, and next tags match those generated for page 2.

### Expected behaviour
Expected paginated tags to bust caches even when __Include Paginated `hreflang` Tags__ setting is disabled. Expected canonical URI to point to first page.

### Versions
- Plugin version: 3.3.26
- Craft version: 3.5.17.1

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/e92130c9af41b19571ef658e1b2ce68ca129c709 & https://github.com/nystudio107/craft-seomatic/commit/a19996a8c787e521fb73be79950f751b3f643418
