### ISSUE TITLE
Manually set canonical and home links have query string stripped

### ISSUE THREAD

**Issue by rob-c-baker** [nystudio107/craft-seomatic#804]
### Describe the bug

When doing something like:

```twig
{% do seomatic.link.container.getData('canonical').href('https://host.com/segment?query=value') %}
```

The rendered tag comes out like:

```html
<link rel="canonical" href="https://host.com/segment">
```

This is because in `CanonicalLink::prepForRender()` (or equivalent in other link classes) this line  `$url = preg_replace('/\?.*/', '', $url);` causes it to be stripped:.

### Expected behaviour

This line: `$url = preg_replace('/\?.*/', '', $url);` has the comment _"The URL should be stripped of its query string already, but because Craft adds the `token` URL param back in via UrlHelper, strip it again"_, so this line could instead strip just that parameter.

### Versions

- Plugin version: 3.3.24
- Craft version: 3.5.16

**Comment by khalwat** [comment]
Why do you want a query string to be part of the canonical URL for a page?

**Comment by rob-c-baker** [comment]
I'm manually trying to set the canonical in a paginated set of pages.

The below from here: https://www.searchenginejournal.com/technical-seo/pagination (as well as a number of other sources including the SEO consultant my company is using) indicates that canonical tags on pages within a paginated set should be self referencing.

![image](https://user-images.githubusercontent.com/39988088/103672286-02ff0480-4f74-11eb-9e18-a81de1a96656.png)

> Complement the rel=”next” / “prev” with a self-referencing rel=”canonical” link. So /category?page=4 should rel=”canonical” to /category?page=4.
> 
> This is appropriate as pagination changes the page content and so is the master copy of that page.

I realise it's technically possible to have Craft not use GET parameter based page parameters but we have a lot of URLs out in the wild that do as a historical artefact (and also some in our company think that page numbers as GET parameters is the correct approach - I'm on the fence right now).

**Comment by khalwat** [comment]
hmmmm. So you think the conclusion we came to here isn't correct?

https://github.com/nystudio107/craft-seomatic/issues/375#issuecomment-488369209

I'm seeing conflicting information on this, maybe the best practice has changed... this link seems to imply canonicalization to the first page is wrong:

https://ahrefs.com/blog/rel-prev-next-pagination/

But here:

https://www.searchenginejournal.com/pagination-seo/295627/

It seems that John Mueller is saying it doesn't matter:

> Rel=canonical is just a suggestion, it’s not a directive that Google is forced to follow. So when Google sees that page two is different from page one, Google will ignore the rel=canonical.

**Comment by khalwat** [comment]
@rob-baker-ar see if this change gives you the desired result: https://github.com/nystudio107/craft-seomatic/commit/0ee420091e704bc2664bc94e2bb0d76a6a5fe858

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.30",
```
Then do a `composer update`

**Comment by rob-c-baker** [comment]
@khalwat I have been trying that change and it does not appear to be working. Exactly why I'm not sure.

After a call to: `{% do seomatic.helper.paginate(pageInfo) %}` :

I'm getting correct `prev` / `next` URLs rendered, with GET param based page numbers, but no canonical.

If I manually do something like: `{% block head %}<link rel="canonical" href="{{ seomatic.meta.canonicalUrl }}">{% endblock %}`  (outputted within head tag in layout) then I still get the fist page as the `href` attribute (no GET params).

At a glance, it looks like the call `$url = self::sanitizeUrl($url);` just below the change in your above commit internally strips all query string parameters. `prev` and `next` are not affected because in `DynamicMeta::paginate()` those URLs don't go through `DynamicMeta::sanitizeUrl()`.

> hmmmm. So you think the conclusion we came to here isn't correct?
> 
> #375 (comment)

That seems to relate more towards `alternate` link tags and only mention canonicals in passing. The concepts may well be the same.

> It seems that John Mueller is saying it doesn't matter:
> > Rel=canonical is just a suggestion, it’s not a directive that Google is forced to follow. So when Google sees that page two is different from page one, Google will ignore the rel=canonical.

I'm not sure the conclusion here is that it doesn't matter - just that Google will ignore canonicals when it thinks they are wrong / not valid / not what it's looking for. This can often be seen in Google search console - I often get tasks for our various sites to fix (or reduce) indexing errors or warnings found in search consoles.

You could say that a lot of link & meta tags tags are just a suggestion but in this case, a canonical pointing to the correct URL of a paginated page would, for example, allow search engines (, bots and whatever else potentially looks at a canonical) to discount pages that have arbitrary get parameters as a result of tracking links, or erroneous trailing slashes, schemes, etc.

**Comment by khalwat** [comment]
Circling back after the holidays @rob-baker-ar -- I think we can depend on the URL returned from `$pageInfo->getPageUrl` as being trusted, due to the way it is generated.  https://github.com/nystudio107/craft-seomatic/commit/f6f44ace2fb20c860ae7d9b894f42013199f3693

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.30",
```
Then do a `composer update`

**Comment by rob-c-baker** [comment]
Thank you @khalwat this looks like it's working.

**Comment by khalwat** [comment]
Great. I will do the release today, so you can switch your semver back
