### ISSUE TITLE
Poor TTFB performance / no caching?

### ISSUE THREAD

**Issue by Youniteus** [nystudio107/craft-seomatic#805]
### Describe the bug
The plugin seems to increase the TTFB with around 200ms for page request. 
Is there a way to improve the performance of the plugin?

### To reproduce
Steps to reproduce the behaviour:
1. Have the plugin enabled. With the following Craft configuration:

```
// in .env
ENVIRONMENT="production"

// in general.php
'enableTemplateCaching' => true, 
'devMode' => false
```

2. Load any page.
```
// TTFB of homepage
#0: 0.2644670009613
#1: 0.20720100402832
#2: 0.18521189689636
#3: 0.20827198028564
#4: 0.23184490203857
#5: 0.24145817756653
#6: 0.23502206802368
#7: 0.24922394752502
#8: 0.23207712173462
#9: 0.2580931186676
count: 10
avg: 0.23128712177277
```
3. Disable the plugin.
4. Load the same page. 
```
// TTFB of homepage
#0: 0.43984484672546
#1: 0.42591214179993
#2: 0.41300296783447
#3: 0.43641996383667
#4: 0.43256902694702
#5: 0.40005111694336
#6: 0.43755078315735
#7: 0.45796084403992
#8: 0.43569898605347
#9: 0.5008270740509
count: 10
avg: 0.43798377513886
```

### Expected behaviour
Better performance. The plugin almost doubles the TTFB of every page.
The plugin also increases the amount of db queries with 112.

There's a short section on caching in the documentation (https://nystudio107.com/docs/seomatic/Using.html#a-word-about-cache-tags), but the results above seem to indicate that the caching is broken or that more performance improvements could be made by improving the caching. 

Any suggestions on improving the performance of the plugin?

### Versions
- Plugin version: 3.3.28
- Craft version: 3.5.11.1

**Comment by AndyCormack** [comment]
Adding a +1 to this, also getting some significant increases in TTFB after a recent round of updates.

Plugin version: 3.3.22
Craft version: 3.5.15.1

**Comment by khalwat** [comment]
So what I'd be interested in seeing @Youniteus are some Yii2 debug profiles of your pages:

https://nystudio107.com/blog/profiling-your-website-with-craft-cms-3s-debug-toolbar

There is no question that SEOmatic will add _some_ overhead, but if you were to implement what it is doing for your site on your own, you'd see at least that much overhead added, or more.

SEOmatic implements a two-level cache, as described here:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting

So it should be performant on cache-hits. The only exceptions to this are that it does not cache non-200 result code responses, so if your webserver is returning a 404 or the like, that could be a problem.

The only other things I can think of that would cause the caching system to not work as intended would be if `devMode` is on (which it doesn't seem to be) or if the SEOmatic environment is set to something other than Production in the Plugin Settings.

I'd like to do a sanity check to make sure it's none of the above first. @AndyCormack I'm not aware of any changes to the plugin that should result in a regression.

Everyone please update to the latest version, which is 3.3.29 at the moment.

**Comment by AndyCormack** [comment]
Thanks for the reply @khalwat, it could very well be related to Craft itself as I updated the whole lot at once. I'll do some deeper investigating and report back if I find anything more conclusive.

**Comment by khalwat** [comment]
@AndyCormack Make sure you update to the latest version first

**Comment by AndyCormack** [comment]
@khalwat will do!

**Comment by khalwat** [comment]
Will re-open if more info is provided

**Comment by davidhellmann** [comment]
Interesting Topic. Have the same Problem:
Craft: 3.6.7
SEOmatic: 3.3.33

My Settings (local)
```
        'disabledPlugins' => [''],
        'allowUpdates' => true,
        'allowAdminChanges' => true,
        'devMode' => false,
        'enableTemplateCaching' => true,
        'isSystemLive' => true,
```

![image](https://user-images.githubusercontent.com/764292/109625961-3ad39400-7b40-11eb-8a6c-a9ed42964b0a.png)

The duplicates are interesting:
![image](https://user-images.githubusercontent.com/764292/109626452-dcf37c00-7b40-11eb-9cd3-c8665ccfb206.png)


With SEOmatic disabled:
```
        'disabledPlugins' => ['seomatic'],
        'allowUpdates' => true,
        'allowAdminChanges' => true,
        'devMode' => false,
        'enableTemplateCaching' => true,
        'isSystemLive' => true,
```

![image](https://user-images.githubusercontent.com/764292/109626069-5d65ad00-7b40-11eb-9068-73b5500e0fba.png)


![image](https://user-images.githubusercontent.com/764292/109626399-ccdb9c80-7b40-11eb-9d45-cd54cdfd41ca.png)

**Comment by khalwat** [comment]
@davidhellmann did you see https://github.com/nystudio107/craft-seomatic/issues/805#issuecomment-754734829 ?

The profiling information we'd need to see would be the queries themselves. SEOmatic will add _some_ overhead, but 500ms for a cached hit seems much higher than I'd expect.

**Comment by KarlBishop** [comment]
Was there any more news on this? I'm also quite often seeing a big increase in response time with SEOMatic enabled.

E.g. SEOMatic disabled:
![image](https://user-images.githubusercontent.com/2892126/151720572-dbe195dd-0d3c-4ac4-90ee-1af774b55111.png)

SEOMatic enabled, ~worst case (sometimes it's not as bad):
![image](https://user-images.githubusercontent.com/2892126/151720597-87373c14-43f9-4c12-b6ca-8e6a8bf399a1.png)


I'd be happy to try to provide some profiling information but I'm not sure exactly how to do this.

> The profiling information we'd need to see would be the queries themselves.

Does this mean the output of the Craft Debug Toolbar's Database Queries panel?
Here is a CSV of the DB Queries output from my worst case example (this is from a 404 template, so pretty minimal content-wise):
[database_queries_export.csv](https://github.com/nystudio107/craft-seomatic/files/7967132/database_queries_export.csv)

If that's no good, could you give me instructions on how I could share the right info please?

**Comment by khalwat** [comment]
@KarlBishop is this with `devMode` on? If so, SEOmatic's cache is disabled, and while the increase you're showing is unusually high, it should be significantly lower on staging/production with `devMode` disabled, which causes SEOmatic's cache to kick in.

**Comment by KarlBishop** [comment]
@khalwat Ahh yes, you're right, that was with `devMode` on...

With `devMode` off it's not such a big difference.

E.g.:
SEOMatic enabled (first load after switching off devMode, so I guess this is before it's been cached):
![image](https://user-images.githubusercontent.com/2892126/151904960-4a391e45-ca43-4672-b60b-02a2dd018016.png)

SEOMatic enabled (after refreshing):
![image](https://user-images.githubusercontent.com/2892126/151905246-0d727c68-6967-4be1-8f8c-8acbf18b5c1c.png)

SEOMatic disabled:
![image](https://user-images.githubusercontent.com/2892126/151905153-56846ae2-474d-47dc-bbd5-b612398305cc.png)
