### ISSUE TITLE
Twitter & FB entry settings tabs are blank

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#806]
### Describe the bug
Craft 3.5.17.1
SEOmatic 3.3.29

On all entries the FB and Twitter tabs are blank 

![image](https://user-images.githubusercontent.com/6899490/103653463-91eb2d00-4f32-11eb-82f2-cd80716d7485.png)

Additionally the sitemap tab has some text but no settings to choose from.

Global SEO setup is 100%
site settings setup is 88% only missing Facebook Profile ID

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Versions
- Plugin version:3.3.29
- Craft version:3.5.17.1

**Comment by khalwat** [comment]
@CreateSean please check your web browser console log for errors

I tried to reproduce this, but can't:

<img width="822" alt="Screen Shot 2021-01-05 at 11 16 49 AM" src="https://user-images.githubusercontent.com/7570798/103670394-85bd9a80-4f47-11eb-8474-5b0529f314b5.png">

**Comment by CreateSean** [comment]
Checked and there are no console errors, FWIW this is happening locally as well as the staging site.

**Comment by CreateSean** [comment]
User error - once I updated the field settings all is good.
