### ISSUE TITLE
og:image tag is missing

### ISSUE THREAD

**Issue by gudehus** [nystudio107/craft-seomatic#808]
### Describe the bug
In the header all meta tags for the image are there (width, height, alt) but the og:image tag with the url is missing.
In the entry backend the image is shown correctly in the examples in the sidebar.
This is also true for the twitter image

**Comment by khalwat** [comment]
What version of SEOmatic are you using? Please ensure you've updated to the latest

**Comment by gudehus** [comment]
Just updated to the very latest version.
But still no og:image
Have a look here.
https://www.juligudehus.net/en/snowfake

But there is an entry where the image url is shown.
https://www.juligudehus.net/en/interviews-statements-portraits

Same structure, same SEO settings.

The formula for the image is 
{{ ( (object.entry.headerImages.one ends with '.svg')?seomatic.helper.socialTransform(object.entry.images.one, "base", 1, "crop"): seomatic.helper.socialTransform(object.entry.headerImages.one, "base", 1, "crop")) }}

On both pages the header image is a jpg.

Regards
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
mail@joerggudehus.de
www.joerggudehus.de


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. 
Details entnehmen Sie unserer Datenschutzerklärung (https://joerggudehus.de/dsgvo.html).

Hier können Sie sich AnyDesk zur Fernwartung herunterladen

https://get.anydesk.com/BEI2iuF8/AnyDesk-gudehus.dmg

**Comment by khalwat** [comment]
@gudehus Please test that code in your frontend Twig template and ensure that it renders the correct result there.

Also provide a screenshot of your Facebook & Twitter Content SEO image settings?

**Comment by gudehus** [comment]
The code is working. AND I can also see the correct image in the entry in the control panel sidebar preview..


Here are the screenshots


mit freundlichen Grüßen
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
mail@joerggudehus.de
www.joerggudehus.de


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. 
Details entnehmen Sie unserer Datenschutzerklärung (https://joerggudehus.de/dsgvo.html).

Hier können Sie sich AnyDesk zur Fernwartung herunterladen

https://get.anydesk.com/BEI2iuF8/AnyDesk-gudehus.dmg

**Comment by khalwat** [comment]
The screenshots didn't make it... but if it's working in the sidebar, something else must be overriding it when it comes to displaying it on the frontend.

Do you have any code in your templates that might be altering it?

**Comment by gudehus** [comment]
No, only a css minifier and a Mamoto script.

mit freundlichen Grüßen
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
mail@joerggudehus.de
www.joerggudehus.de


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. 
Details entnehmen Sie unserer Datenschutzerklärung (https://joerggudehus.de/dsgvo.html).

Hier können Sie sich AnyDesk zur Fernwartung herunterladen

https://get.anydesk.com/BEI2iuF8/AnyDesk-gudehus.dmg

**Comment by khalwat** [comment]
@gudehus I'm at a loss -- I'd be happy to set up a screen sharing session with you to have a look at it though.

**Comment by gudehus** [comment]
When is the best time for you. I’m in Berlin Germany so we have a little time discrepancy.
Tomorrow at noon would be fine. That is 6 pm for me.

I can offer Cisco Webex.

Regards
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
mail@joerggudehus.de
www.joerggudehus.de


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. 
Details entnehmen Sie unserer Datenschutzerklärung (https://joerggudehus.de/dsgvo.html).

Hier können Sie sich AnyDesk zur Fernwartung herunterladen

https://get.anydesk.com/BEI2iuF8/AnyDesk-gudehus.dmg

**Comment by khalwat** [comment]
@gudehus are you able to get on the Craft Discord to coordinate this? 

https://craftcms.com/blog/discord

My handle on there is: andrew.welch

**Comment by gudehus** [comment]
My handle is gudehus


mit freundlichen Grüßen
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
mail@joerggudehus.de
www.joerggudehus.de


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. 
Details entnehmen Sie unserer Datenschutzerklärung (https://joerggudehus.de/dsgvo.html).

Hier können Sie sich AnyDesk zur Fernwartung herunterladen

https://get.anydesk.com/BEI2iuF8/AnyDesk-gudehus.dmg

**Comment by khalwat** [comment]
This ended up being because the conditional Twig statement needed to be added into the Twitter and Facebook settings directly.
