### ISSUE TITLE
Too few arguments when generating sitemap with Redis-queue configured

### ISSUE THREAD

**Issue by jerome2710** [nystudio107/craft-seomatic#809]
```
Too few arguments to function yii\queue\redis\Queue::run(), 0 passed in /.../vendor/nystudio107/craft-seomatic/src/console/controllers/SitemapController.php on line 112 and at least 1 expected
```

See: https://github.com/nystudio107/craft-seomatic/blob/v3/src/console/controllers/SitemapController.php#L112

Related to:
- #302
- #369

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/44e23b2d4a4b499e035d09780a2be5da48a25f29
