### ISSUE TITLE
504 on local site after installing plugin

### ISSUE THREAD

**Issue by sjenset** [nystudio107/craft-seomatic#81]
Hi.

Not the best described issue I am afraid, but I don't really have anything from logs (that I could find) which would enable to me to document it further.

Basically, I installed the plugin on a production-site, configured it, and everything works great.

I sync the site down to my local development-environment, and when attempting to visit said dev-site I get 504 Gateway Time-out.

This never happened before installing the plugin, and if I deactivate the plugin and re-sync my database from prod => dev I can use the site as I normally would.

Have looked at my nginx, php-fpm and mariadb logs without spotting anything out of the ordinary.

Any ideas at all? (Here's to hoping for a miracle!)

**Comment by khalwat** [comment]
So a 504 is a gateway timeout, which in our context typically means that the webserver can't connect to PHP https://httpstatuses.com/504

I'm having a hard timing thinking how the plugin could be causing this. It's almost certainly some kind of local dev setup issue though.

Let me know what you figure out!

**Comment by sjenset** [comment]
Yeah, I mean - normally I would agree with you 100 %.

However - and this is the weird part. Say we start with having the plugin installed on my local site, i.e. site throws 504-error.

`composer remove nystudio107/craft-seomatic` -> site works again
`composer require nystudio107/craft-seomatic` -> back to 504'ing

Rinse and repeat ad naseum

I don't really see how the plugin could be causing this either, but at the same time I'm having a rough time tracking down exactly what type of local configuration is causing this to only happen when said plugin is installed

**Comment by sjenset** [comment]
Okay, it seems that I can leave the plugin installed/enabled, as long as I don't activate the lightswitch that "Controls whether SEOmatic will automatically render metadata on your pages". If I flip that to active, the 504'ing begins.

At this point, I am boggled.

**Comment by darylknight** [comment]
Just ran in to this issue myself. Eventually tracked down the 504 error I've been having all day to SEOmatic. Site works without SEOmatic installed. Then installed SEOmatic and turned off “automatically render metadata”. Still worked. Turned that lightswitch back on, site won’t load.

**Comment by robbelaloo** [comment]
Have encountered this issue yesterday and got this out of my nginx log:

`2018/11/16 09:26:08 [error] 4308#0: *25 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: cm-2018.test, request: "GET /sw.js HTTP/2.0", upstream: "fastcgi://unix:/Users/xxxxxx/.valet/valet.sock", host: "cm-2018.test", referrer: "https://cm-2018.test/sw.js"`

`2018/11/16 10:19:41 [error] 4310#0: *157 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: cm-2018.test, request: "GET /admin/seomatic HTTP/2.0", upstream: "fastcgi://unix:/Users/xxxxxx/.valet/valet.sock", host: "cm-2018.test"`

I ended up playing around with timeout settings that could at least give the pages some more time, but no success.
Deleting the vendor folder and composer.lock file and running `composer update` only helps to get it back running 1 time. I can visit 1 page, but when going to another it's back to the 504.

As long as seomatic is installed I can't seem to fix the issue.

**Comment by nfourtythree** [comment]
I am having issues with this on my homestead box in local dev. If I disable SEOmatic everything is fine, with it enabled I get timeouts.

Unfortunately, haven't have time to properly investigate it. So for anyone else having a similar issue as a temporary workaround I just used a multi-environment config and set `renderEnabled` to `false` for my local env.

**Comment by khalwat** [comment]
@nfourtythree yeah that definitely should not be necessary, though. Can you check to see if you have missing assets locally for things like the Entity Brand?

There's an issue filed regarding this: https://github.com/nystudio107/craft-seomatic/issues/418

Often times our local dev environment may not have all of the assets that are available on production.

**Comment by PhilRedm** [comment]
I've recently encountered this same type of error after loading my production db to my local environment. I was able to fix it by re-syncing assets from product to local.

**Comment by khalwat** [comment]
Updating to the latest SEOmatic might address it @PhilRedm
