### ISSUE TITLE
Structured data for FAQ page with html

### ISSUE THREAD

**Issue by WHITE-developer** [nystudio107/craft-seomatic#810]
### Question
In a project we are working on we added structured data on the FAQ page for Q&A. [The Google docs](https://developers.google.com/search/docs/data-types/faqpage) point out that the [Answer can handle some HTML tags](https://developers.google.com/search/docs/data-types/faqpage#answer) and show these in the search results.
Seomatic escapes these tags, so I'm not sure if Google will pick them up correctly.

Any idea if that will work and if it won't, how to get the raw tags in there?

### Additional context
Example json
```
{
    "@type": "Question",
    "acceptedAnswer": {
        "@type": "Answer",
        "text": "\u003Cp\u003EAntwoord 1\u003C/p\u003E\u003Cul\u003E\u003Cli\u003Euitleg a\u003C/li\u003E\u003Cli\u003Euitleg b\u003C/li\u003E\u003Cli\u003Euitleg c\u003C/li\u003E\u003C/ul\u003E\u003Cp\u003EMeer antwoord\u003C/p\u003E"
    },
    "name": "Vraag 1"
 },
```
What I think it should be, but not sure about
```
{
    "@type": "Question",
    "acceptedAnswer": {
        "@type": "Answer",
        "text": "<p>Antwoord 1</p><ul><li>uitleg a</li><li>uitleg b</li><li>uitleg c</li></ul><p>Meer antwoord</p>"
    },
    "name": "Vraag 1"
 },
```

**Comment by khalwat** [comment]
The HTML is in a JSON context here, so I do think it should be escaped. Google should have no issue consuming it and rendering it properly, but let me know if you run into any issues.
