### ISSUE TITLE
Help Needed: SEO Setting Fields

### ISSUE THREAD

**Issue by simonleimeister** [nystudio107/craft-seomatic#813]
Hey everyone

I'm quite new to craft as well as seomatic and would very much appreciate your help with an issue I have with seomatic:
I understand that [SEO Setting Fields](https://nystudio107.com/docs/seomatic/Fields.html#seo-settings-field) are the means of choice if I want to handle Title and Description individually for entries. However, what I cannot find is how to enable this fields. I could find this option anywhere in seomantic, and also neither in the general craft settings nor the entry settings. Have I overlooked something or do I need IT support?

An additional question: Will the SEO Setting Fields only work for Entries or can I also enable them for categories.

Many Thanks in advance! 

Best,
Simon

**Comment by khalwat** [comment]
I would suggest setting up the Content SEO mappings that _pull_ from existing content in Craft CMS as described here: https://nystudio107.com/docs/seomatic/Configuring.html#content-seo

**Comment by khalwat** [comment]
If you need further assistance, please feel free to add questions to this thread, btw!
