### ISSUE TITLE
Sitemap files with more than 1000 urls

### ISSUE THREAD

**Issue by linontano** [nystudio107/craft-seomatic#815]
### Question
Can the seomatic plugin divide sections with more than 1000 urls into multiple sitemaps? I currently don't see that it does.

**Comment by khalwat** [comment]
Currently, no it does not. It does divide each section into a separate sitemap, but it does not further paginate each into sub-sitemaps.

It's useful to keep in mind that sitemaps are just a way to point search engines at content that you want them to index. What many people are doing is only putting the most recent 10 or so entries into a sitemap, to ensure that GoogleBot spends its crawl budget on your new content.

Content that is already in the index will remain there, whether or not it is in a sitemap. The sitemap just helps with _discovery_ so there is questionable value in having every single entry in a sitemap.
