### ISSUE TITLE
Secondary site url is the primary site url

### ISSUE THREAD

**Issue by 1stevengrant** [nystudio107/craft-seomatic#816]
Hey Andrew, I'm trying to work out why this is happening.

I have 1 Craft instance running 2 sites in multi-site. Each site is in its own group and the should be reading the URL from an environment variable in the sites config.

However, looking at the secondary site, anything URL related is pointing at the primary URL.

I've gone through the SEO settings for both sites and updated their config settings but it hasn't made any difference.

Other meta settings are fine, just the URL is off. What have I missed?

**Comment by khalwat** [comment]
When you say the URL is off, what URL do you mean?

Can you show me examples?

**Comment by 1stevengrant** [comment]
Sure, here's a sample of the home page

```html

  <meta name="description" content="Harvest Ayr is an upcoming church plant in Ayrshire, Scotland.">
  <meta name="referrer" content="no-referrer-when-downgrade">
  <meta name="robots" content="all">
  <meta content="en_GB" property="og:locale">
  <meta content="Harvest Ayr" property="og:site_name">
  <meta content="website" property="og:type">
  <meta content="https://harvestayr.church/" property="og:url">
  <meta content="Welcome \| Harvest Ayr" property="og:title">
  <meta content="Harvest Ayr is an upcoming church plant in Ayrshire, Scotland." property="og:description">
  <meta content="https://cdn.harvestglasgow.church/content/_1200x630_crop_center-center_82_none/iStock-1189533592.jpg?mtime=20210114183525&amp;focal=none&amp;tmtime=20210122163449" property="og:image">
  <meta content="1200" property="og:image:width">
  <meta content="630" property="og:image:height">
  <meta content="View of Ayr" property="og:image:alt">
  <meta content="https://www.instagram.com/harvestayr" property="og:see_also">
  <meta content="https://www.youtube.com/channel/UCj3g5iMKXuhVjd8E-WwaEBg" property="og:see_also">
  <meta content="https://facebook.com/harvestayr" property="og:see_also">
  <link href="https://harvestayr.church" rel="canonical">
  <link href="https://harvestglasgow.church" rel="home">
  <link type="text/plain" href="https://harvestglasgow.church/humans.txt" rel="author">

```

here's the control panel view for SEO

![](https://d.pr/i/GLjBuW+)

**Comment by 1stevengrant** [comment]
just noticed actually, should the SEO field be `translate for each site group` or `translate for each site`? Currently set as `translate for each site`

**Comment by khalwat** [comment]
I would actually recommend that you do not use an SEO Settings field unless you find you actually need it. Instead, set up your mappings / settings via Global SEO and Content SEO as discussed here:

https://nystudio107.com/docs/seomatic/Issues.html#upgrading-from-seomatic-1-x-for-craft-cms-2-x

**Comment by 1stevengrant** [comment]
We got it, the plugin setting was using the `siteUrl` override. Removed that and everything is good.
