### ISSUE TITLE
[FR] - Add Plausible into Tracking Scripts 

### ISSUE THREAD

**Issue by mariovass** [nystudio107/craft-seomatic#817]
We have quite a few clients moving away from GA and onto a simpler and more GDPR compliant analytics. Would be great to add this one into tracking scripts.

https://plausible.io/

**Comment by khalwat** [comment]
Another one people might want is:

https://usefathom.com/

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/a39a9d3e875fe828b1232c7a2713cae4849d955d

**Comment by davidhellmann** [comment]
Hey @khalwat 
Is it also possible to add https://withcabin.com/ :D
For sure not urgent.
