### ISSUE TITLE
Add view sitemap link to SEOmatic CP

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#819]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Having a link to view the generated sitemap(s) from the CP would be helpful. Also looked in the docs and could not find where it says the sitemap file exists.

I did eventually find that it's at domain.com/sitemap.xml

### Describe the solution you would like
A clear and concise description of what you would like to have happen.

### Describe alternatives you have considered
A clear and concise description of any alternative solutions or features you have considered.

**Comment by khalwat** [comment]
This will be addressed in the documentation
