### ISSUE TITLE
Social media live previews shouldn't show the viewport selector

### ISSUE THREAD

**Issue by Mosnar** [nystudio107/craft-seomatic#821]
### Describe the bug
Craft 3.6 introduced the device preview selector for previewing on different viewports. This doesn't really make sense for SEO previews (and potentially other use-cases.)

To do this in a non-fragile way, we'll probably need changes to Craft to let it know not to show the option for specific preview targets. If @brandonkelly says "no", feel free to close this out as a nitpick. 

### Screenshots

![image](https://user-images.githubusercontent.com/3810939/106403873-a0781780-63fe-11eb-8808-a45b519d3d8e.png)

### Versions
- Plugin version: 3.3.30
- Craft version: Craft Pro 3.6.1

**Comment by khalwat** [comment]
Yeah I'm not sure this is a bug in SEOmatic really... I'm not aware of anything I can do to prevent this from showing.

I'd suggest filing it against Craft, since they'd need to change the code or implement a new feature in order for this to work.
