### ISSUE TITLE
Canonical Url is blank

### ISSUE THREAD

**Issue by spib** [nystudio107/craft-seomatic#822]
### Describe the bug

The Canonical Url field on an entry appears blank after saving

This was formerly open under #769 but that ticket attributed it to runQueueAutomatically, when I don't think they're related

### To reproduce
Steps to reproduce the behaviour:
1. We add a Canonical Url for an entry
2. Click on Save
3. Re-open the same entry and the field is blank

### Expected behaviour
Canonical url should be saved and show in the Canonical Url field on the entry

### Screenshots
* This is prior to saving
![image](https://user-images.githubusercontent.com/512036/106491081-66fee500-64ae-11eb-8b46-9b76d4a21b3c.png)
* This is after saving and re-opening
![image](https://user-images.githubusercontent.com/512036/106491249-94e42980-64ae-11eb-94e2-d6f20e963d52.png)
* The data does seem to be in the database
![image](https://user-images.githubusercontent.com/512036/106491316-a5949f80-64ae-11eb-84ac-eac49646f2e8.png)
* If I modify tab-general.twig to spit out the raw value, it looks correct. Wondering if it could be the autocomplete that's the problem??
![image](https://user-images.githubusercontent.com/512036/106491582-eb516800-64ae-11eb-8dc7-625ab0314c63.png)
![image](https://user-images.githubusercontent.com/512036/106491625-fa381a80-64ae-11eb-89d8-36e02e7bc4bc.png)

### Versions
- Plugin version: 3.3.30
- Craft version: 3.5.14

**Comment by khalwat** [comment]
So this is really bad UX, not a bug.

The SEO Settings field is an _override_ for Global and Content SEO settings. If any setting in the SEO Settings field matches what the value already is, it says "this isn't an override at all, it's the same thing" and sets it to blank (which means "no change/override").

See here for more: https://github.com/nystudio107/craft-seomatic/issues/535

**Comment by spib** [comment]
Hi @khalwat - thanks for the quick reply. However, in this case, the Canonical Url isn't the same as the default - it's a totally different value. I tested it by putting in https://www.google.com (which could not possibly be the default) and I see the same behavior.

![image](https://user-images.githubusercontent.com/512036/106631958-2918c400-6575-11eb-8b8e-1532342b2522.png)

This doesn't feel like the same issue as #535 to me?

**Comment by khalwat** [comment]
Is this field set to translate across different sites?

**Comment by spib** [comment]
> Is this field set to translate across different sites?

No, it's set to 'Not translatable', but this Craft instance does have 2 sites (one en and one fr) if that helps.

**Comment by khalwat** [comment]
I'm a little confused, in some of your screenshots you're highlighting the Robots tag setting, not the Canonical URL setting? Can you clarify?

What have you set the Canonical URL to in your Global SEO settings and Content SEO settings for this section?

**Comment by spib** [comment]
Sorry for the confusion, where it looks like I'm highlighting the Robots field, it's because I've removed the canonical field from the template and just spitting out the raw value of canonical url. There's a screen grab above showing the template change I made for debug purposes.

As for the settings, this is what we have

Global SEO->Canonical Url - {seomatic.helper.safeCanonicalUrl()}
Content SEO->Canonical Url - blank

**Comment by khalwat** [comment]
Can you set the Content SEO canonical URL to something default-ish, like `{entry.url}` or such?

**Comment by spib** [comment]
Yeah, changed as follows

Global SEO->Canonical Url - {seomatic.helper.safeCanonicalUrl()}
Content SEO->Canonical Url - {entry.url}
Entry->Canonical Url - 'https://www.google.com'

We're still seeing the same issue, the Canonical Url field is empty on the entry UI after saving, even though I can see the `metaGlobalVars->canonicalUrl` is correct in the field in the `craft_content` table

**Comment by khalwat** [comment]
Alright, I think at this point we'll need to do a screen sharing and have a look at it together.

Are you able to ping me on the Craft Discord at `andrew.welch` to coordinate a time?

**Comment by spib** [comment]
Thanks for your help today @khalwat - we confirmed that this was a conflict with the SimpleMap plugin and the built-in Craft `forms.autosuggestField`, not something specific to SEOMatic. Closing this issue
