### ISSUE TITLE
Include Fathom Analytics in Tracking Scripts

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft-seomatic#823]
I've gotten away from using GA on all of my sites in favor of Fathom Analytics. It's not as robust but gets me all the information I need for myself and for my clients, clearly and effectively. From what I can tell, it's grown in popularity. It would be cool to be able to add in their main tracking code using this plugin. Just a suggestion.

**Comment by john-henry** [comment]
IMHO It would seem like a lot of overhead to include that as there is no real configuring to be done.

You likely have similar but this is what I add to my layout templates. I use a custom domain too. So I don't know if it's worth the extra calls to DB just to fetch this info

```
{% if craft.app.config.env != 'dev' and craft.app.response.statusCode != '404'  %}
<!-- Fathom - beautiful, simple website analytics -->
<script src="https://xxx.domain.com/script.js" site="XXXXXXX" defer></script>
<!-- / Fathom -->
{% endif %}
```

**Comment by khalwat** [comment]
It actually wouldn't be any extra db calls, because it's included with the container.

The argument for adding it is that non-developers (marketing, SEO, etc.) types could go in and enable/disable scripts like this without needing to change the code.

GTM-lite.

**Comment by john-henry** [comment]
Cool Good to know

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/0ea70af44d1fd40ce37b77722faea32556ee3f94
