### ISSUE TITLE
Sitemaps in a headless cms

### ISSUE THREAD

**Issue by edwwaarrdd** [nystudio107/craft-seomatic#824]
### Question
We have a multilingual site setup where all the content is fetched via graphql queries from a central CMS url.
cms.example.org
and the front-end domains are example.org, example.org/en-us, .... (made in a nuxt stack).

Now when I try to access the sitemaps from cms.example.org/sitemap.xml it redirects to example.org/sitemaps-1-sitemap.xml

When I access the link directly cms.example.org/sitemaps-1-sitemap.xml it works but all sitemap.xml links are not going to the cms url but to the front-end url. so example.org/sitemap.... instead of cms.example.org/sitemap....

When I change the "Site URL Override" to cms.example.org the sitemap links are correct but the content links are also changed from example.org/entry to cms.example.org/entry.

Is there a way to use the "Site URL Override" without overriding the content url's?
Or some other settings that I can use?

Thanks in advance!

### Additional context
php 7.4.13
Craft Pro 3.5.17.1
Seomatic 3.3.30
PostgreSQL 13.1

**Comment by khalwat** [comment]
Yeah unfortunately you can't have a sitemap on a different domain than the links it lists. That's not an SEOmatic limitation, that's a limitation of sitemaps in general: 

https://www.sitemaps.org/protocol.html

> Note: A Sitemap index file can only specify Sitemaps that are found on the same site as the Sitemap index file. For example, http://www.yoursite.com/sitemap_index.xml can include Sitemaps on http://www.yoursite.com but not on http://www.example.com or http://yourhost.yoursite.com. As with Sitemaps, your Sitemap index file must be UTF-8 encoded.

So you're going to have to figure out another way to do this. What some people have done is as part of their Nuxt build process, they suck down the sitemap from the CMS and serve that up statically themselves.

**Comment by wbrowar** [comment]
Hey, @edwwaarrdd I had the same situation come up when using Craft with Nuxt. My solution in the end was to use a scraper in Node that fires during a pre-build script. In Nuxt you might be able to write a plugin to do this, but mine was part of a bigger set of tools I already had in place.

I added the script below, but you may need to rewrite it to fit your setup.

The gist of it is that it requests the sitemap index during the first request, pull that page contents down, find all of the sub pages in the index, then scrape all of those. All of the files are put into the Nuxt static folder before build, so they just get moved over to where they need to be in the `dist` directory during build. Along the way I have the script replace all of the CMS URLs with the front-end URLs so the index still works.

Here's my script (extracted from a bigger setup, so things like the logging can be ignored):

```JavaScript
const requestSync = require('sync-request');

methods.log('verbose', `Scraping page: ${page.src}`, verbose);
const request = requestSync('GET', page.src);
if (request.statusCode === 200 || page.allow404) {
  // Output page to dist
  let pagBody = request.body;
  if (options.replacements) {
    Object.keys(options.replacements).forEach((key) => {
      pagBody = pagBody.replace(/${key}/g, options.replacements[key]);
    });
  }
  fs.outputFileSync(page.dist, pagBody);
  methods.log('verbose', `Wrote file: ${page.dist}`, verbose);

  // Extract URLs form sitemap index and parse secondary pages
  if (page.type === 'sitemap') {
    methods.log('verbose', `Extracting sitemap URLs from ${page.src}`, verbose);
    const removedDates = request.body.toString().replace(/(<lastmod>(.....)+<\/lastmod>)/ig,"");
    const removedTags = removedDates.replace(/(<([^>]+)>)/ig,",");
    const replacedRoots = removedTags.replace(new RegExp(page.sitemapRootSrc,"g"),page.sitemapRootDist);
    const subSitemaps = replacedRoots.split(',').filter((item) => item !== '');

    if (subSitemaps) {
      subSitemaps.forEach((subPage) => {
        const subPageRequest = requestSync('GET', subPage);

        if (subPageRequest.statusCode === 200) {
          fs.outputFileSync(subPage.replace(page.sitemapRootDist, paths.starter.static), subPageRequest.body);
        }
      });
    }
    methods.log('dump', subSitemaps, verbose);
  }
}
```

_Please note, I'm using `sync-request` here but you could probably re-write this to use the regular `request` package as long as you can do it in the right order._

Hope this helps!

**Comment by edwwaarrdd** [comment]
@wbrowar Thanks for the help!
We'll try to implement it that way way

**Comment by edwwaarrdd** [comment]
For people that also have the same problem we solved it by using `@nuxtjs/proxy` and adding this to the nuxt.config.js
```
proxy: {
    '/*sitemap.xml': process.env.CMS_BASE_URL,
    '/*sitemap.xsl': process.env.CMS_BASE_URL,
  },
```
This way all requests ending in sitemap.xml get proxied to the cms url.

**Comment by yvanavermaet** [comment]
> Yeah unfortunately you can't have a sitemap on a different domain than the links it lists. That's not an SEOmatic limitation, that's a limitation of sitemaps in general:
> 
> https://www.sitemaps.org/protocol.html
> 
> > Note: A Sitemap index file can only specify Sitemaps that are found on the same site as the Sitemap index file. For example, http://www.yoursite.com/sitemap_index.xml can include Sitemaps on http://www.yoursite.com but not on http://www.example.com or http://yourhost.yoursite.com. As with Sitemaps, your Sitemap index file must be UTF-8 encoded.
> 
> So you're going to have to figure out another way to do this. What some people have done is as part of their Nuxt build process, they suck down the sitemap from the CMS and serve that up statically themselves.

For your reference, that is not what that text is saying. The text says that the Sitemap index file can only specify **other Sitemaps** that are on the same domain. It does not say anything about the urls inside the sitemaps.

Further down the page ('Sitemap file location') the protocol does describe that the urls inside a sitemap should have the same protocol+host as the sitemap itself though .

However, in 2008 (Google: https://searchengineland.com/sitemapsorg-update-you-can-now-store-your-xml-sitemap-files-anywhere-13476 and Bing: https://blogs.bing.com/webmaster/2008/02/27/microsoft-to-support-cross-domain-sitemaps/) both Google and Bing have decided to implement the sitemaps protocol a bit differently. It is allowed to specify urls from another domain than the sitemap IF you add a reference in the robots.txt to the sitemap (which is on another domain) proving your ownership.

So on www.example.com we add 'Sitemap: www.otherdomain.com/sitemap.xml' to the robots.txt, then this sitemap.xml may contain urls that link to www.example.com

So even though @edwwaarrdd has resolved his issue using a proxy, the initial request is a perfectly valid use case.
Even though following a protocol is a perfectly good idea, I believe the plugin should follow the current SEO standards (Google, and Bing). Since this is Open Source, I can't make you though 😅
