### ISSUE TITLE
[FR] - Change / Add sitemap attributes for Google News Sitemap

### ISSUE THREAD

**Issue by linontano** [nystudio107/craft-seomatic#825]
### Question
Is it possible to add attributes other than the default ones for a specific sitemap? I need to implement a google news sitemap for the site I manage and it requests additional attributes and I don't know how to add. I attach characteristics that the sitemap should have: https://support.google.com/news/publisher-center/answer/9606710?hl=en

**Comment by khalwat** [comment]
Currently this is not possible, but I'll turn this into a FR as implementing news sitemaps is on my list!

**Comment by khalwat** [comment]
Added via: https://github.com/nystudio107/craft-seomatic/commit/45d6e69453e958c3de9732503b4dc2c1476c4aaa
