### ISSUE TITLE
Discrepancy with Entry Structure Name & Handle

### ISSUE THREAD

**Issue by strandofgenius** [nystudio107/craft-seomatic#826]
### Describe the bug
I have 2 entry types. One is a single called Careers with a uri of `careers` and points to a template of `careers/index` and another that is a structure that had been called Careers then changed to Job Listings with a uri of `careers/{slug}` and pointing to a template of `careers/_entry`. 

If I look at the contact SEO I can see the careers single and still a careers structure with only 1 entry, but should be seeing job listings instead and that it would have at least 10 entries. If I click on either of them they look like they have the same exact thing and can't see Job Listings as an option in the Content SEO section.

I can however type in the search field for job listing and it will display then.

### Versions
- Plugin version: 3.3.30
- Craft version: 3.6.2

**Comment by khalwat** [comment]
Is it possible that it's just paginated, and you'd see Job Listing if you went to the next page of Content SEO listings?

**Comment by strandofgenius** [comment]
Here is a screenshot of what I have in the Content SEO tab. I don't see any pagination and the one I highlighted doesn't exist in the sections settings of the craft admin. I have 14 entry types and the one that is missing is the Job Listings entry type.

If I look at the SEOmatic metabundles in the db I can see a reference to the old Careers structure as well as the Job Listings structure.

I tried clearing the cache several times and that didn't seem to do anything either.

![🚧⚙_SEOmatic_-_Content_SEO_-_Paulsen-2](https://user-images.githubusercontent.com/11370639/106976983-104c1200-671f-11eb-9b20-923aba4284b4.jpg)

![🚧⚙_Sections_-_Paulsen](https://user-images.githubusercontent.com/11370639/106977094-41c4dd80-671f-11eb-8716-e2d0c2c1a1a4.jpg)

**Comment by khalwat** [comment]
Are you able to go into the database and delete any of the `seomatic_metabundles` tables that corresponds to the Careers channel/structures? It sounds like somehow stale data is in there. Don't worry, it'll re-create them as needed.

**Comment by strandofgenius** [comment]
Sorry, just updated my comment to say 
> If I look at the SEOmatic metabundles in the db I can see a reference to the old Careers structure as well as the Job Listings structure.

**Comment by khalwat** [comment]
Right, delete the one that is a reference to the old Careers structure

**Comment by strandofgenius** [comment]
Ah yes that did it, I can now see the other entry type. Thanks for your help.
