### ISSUE TITLE
Assets are not imported via feedme

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#827]
### Describe the bug
When importing via Feed Me, it is unclear what the field value is expecting.
As is the case with normal asset fields, I would expect this to be expecting a URL. However, unlink an asset field, there is no "Create asset from URL" checkbox.

<img width="683" alt="Screen_Shot_2021-02-08_at_1_45_14_PM" src="https://user-images.githubusercontent.com/18329/107266822-0e7e9900-6a14-11eb-84ac-735939833f32.png">

When I import, using a full-url as the value, nothing appears to be imported into the SEOmatic field.

### Versions
- Plugin version: 3.3.30
- Craft version: 3.6.4.1

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/pull/828
