### ISSUE TITLE
Can image immediate image transforms be disabled for GraphQL requests?

### ISSUE THREAD

**Issue by kara-todd** [nystudio107/craft-seomatic#829]
I have a site that has 1500+ articles which all have SEO images which I would like to generate transforms for. I am using a query as follows:

```graphql
  query {
    entries( section: "news"  ) {
      seomatic {
        metaTitleContainer
        metaTagContainer
        metaLinkContainer
        metaJsonLdContainer
      }
    }
  }
```

However, this seems to try and run all image transforms immediately... which quickly causes the server to run out of memory or disk space from `tmp` files. I ran into this issue with transforms before, and I was able to leave the request as the transform url... However, I know this isn't ideal for social sharing. Still at least subsequent requests would serve the correct asset url.

Is there a way to run these transforms in bulk in the background or to allow them to be transformed at request time? Or... another solution I'm not aware of? :)

**Comment by khalwat** [comment]
The image transforms are just Craft transforms, so once they've been generated, they won't need to be generated again. So it won't have to re-create them every time.

**Comment by kara-todd** [comment]
thanks @khalwat I think that means "no" for the initial generation. I was able to get past this issue by running a node script to call the await the transforms in batches. That way I could get through them all without DDOS-ing the server.

I'll close this issue since I don't think any further action is needed.
