### ISSUE TITLE
Server environment in config/seomatic.php doesn't seem to do anything

### ISSUE THREAD

**Issue by marknotton** [nystudio107/craft-seomatic#83]
> 3.0.0-beta.3

When changing the environment in the `config/seomatic.php` file, nothing happens to the robots.txt

`'environment' => 'staging'`

This requests seems to always return "local" despite my explicit instruction to be something else. 

`{{ seomatic.config.environment }}`

I understand that I have to manually save the robots.txt settings in order for it to update the database... but still nothing. 

My current workaround is to refer to my .env file instead:

```
{% switch getenv('ENVIRONMENT') %}

{% case "production" %}

# Production 

{% case "staging" %}

# Staging

{% case "dev" %}

# Dev

{% default %}

# Default

{% endswitch %}
```

**Comment by khalwat** [comment]
If `devMode` is on, it will always default to `local` development

Maybe I should have it default only of it isn't explicitly set?

**Comment by marknotton** [comment]
Ah, if that's the intended behaviour I'd leave it as it is. Makes sense actually. Sorry I didn't notice that myself.

**Comment by khalwat** [comment]
It is, but maybe it's a little heavy-handed. I'll see if I can't figure out something more sensible.
