### ISSUE TITLE
multisite sitemaps issue

### ISSUE THREAD

**Issue by mikejdegroot** [nystudio107/craft-seomatic#830]
Hi,

We are having an issue where we cannot find where the sitemaps for our craft multi site are being generated to. Our setup is as follows:

Headless multi site, accessed via graphQl.
7 sites:

Default/API site: https://content.example.com
en_ca site: https://www.example.com/en-ca
fr_ca site: https://www.example.com/fr-ca
en_us site: https://www.example.com/en-us
fr_fr site: https://www.example.com/fr-fr
en_gb site: https://www.example.com/en-gb

visiting the url https://content.example.com/sitemaps-5-sitemap.xml (or any other sitemap id number) we are shown a blank sitemap. We have both generated the sitemaps manually and have runqueueautomatically switched on. In a mulitsite setup, where do the sitemaps get generated to? We use the plugin on several other single site setups and have never had a problem. 

Thanks in advance

**Comment by khalwat** [comment]
So I probably can't help you without actual real world examples to look at and diagnose.

But in general, the sitemap index will be at https://sitename.com/en-ca/sitemap.xml -- and that will list all of the other sitemaps.

**Comment by mikejdegroot** [comment]
Ok. so to be clear, our (elsewhere hosted javascript) sites are on https://www.example.com/en-ca and the backend craft installation is hosted on https://content.example.com.

Are you saying that the site maps for /en-ca/ will be hosted on https://www.example.com/en-ca and not https://content.example.com ? 

I cant see how this is possible because the https://www.example.com/en-ca and https://content.example.com DNS points to different servers.

Thanks

**Comment by khalwat** [comment]
The sitemaps will be where the Craft CMS sites point to. This thread might be useful to you: https://github.com/nystudio107/craft-seomatic/issues/824

**Comment by mikejdegroot** [comment]
Ok thanks for this
