### ISSUE TITLE
Allow breadcrumb generation based on ancestors/children for structure sections

### ISSUE THREAD

**Issue by tigitz** [nystudio107/craft-seomatic#831]
### Is your feature request related to a problem? Please describe.

Given these entries:
![image](https://user-images.githubusercontent.com/1524501/107546392-9909f880-6bcc-11eb-8e16-176985042647.png)

We would like the breadcrumbs to be:

```
Relocation > Paris
```

But since the logic is based on URL fragments and not flexible we can't.

### Describe the solution you would like

This is what I came up with:
```php
// src/helpers/DynamicMeta.php:451

if ($lastElement && $element) {
            if ($lastElement->uri !== '__home__' && $element->uri) {
                foreach ($lastElement->getAncestors()->all() as $ancestor) {
                    if ($ancestor && $ancestor->uri) {
                        $position++;
                        $uri = $ancestor->uri === '__home__' ? '' : $ancestor->uri;
                        try {
                            $id = UrlHelper::siteUrl($uri, null, null, $siteId);
                        } catch (Exception $e) {
                            $id = $siteUrl;
                            Craft::error($e->getMessage(), __METHOD__);
                        }
                        $crumbs->itemListElement[] = MetaJsonLd::create('ListItem', [
                            'position' => $position,
                            'name' => $ancestor->title,
                            'item' => UrlHelper::stripQueryString($id),
                            '@id' => $id,
                        ]);
                    }
                }

                try {
                    $id = UrlHelper::siteUrl($lastElement->uri, null, null, $siteId);
                } catch (Exception $e) {
                    $id = $siteUrl;
                    Craft::error($e->getMessage(), __METHOD__);
                }
                $crumbs->itemListElement[] = MetaJsonLd::create('ListItem', [
                    'position' => ++$position,
                    'name' => $lastElement->title,
                    'item' => UrlHelper::stripQueryString($id),
                    '@id' => $id,
                ]);
```

But I was wondering if you were open to a new settings to change the strategy to use when generating breadcrumbs. I could provide the logic above in a PR with the related settings.

### Additional context
This in a context of a total site revamp, our company SEO Guru would like to keep certain url the same and would like to avoid redirections. Claiming it would negatively impact `backlink juice`, a term I'm not familiar with.

**Comment by khalwat** [comment]
Sounds like your SEO Guru may be a bit too mystic:

https://twitter.com/methode/status/757923179641839616

Search on "SEO Best Practice" here:

https://moz.com/learn/seo/redirection

Search on "Do 301 redirects affect SEO?" and make sure you read to the bottom to get modern practices:

https://ahrefs.com/blog/301-redirects/

I probably wouldn't roll your proposed changes into SEOmatic, but you definitely could do them yourself in a custom module or plugin.

You could take the generated breadcrumbs, and replace them with whatever you want, either via Twig or PHP. If you want additional guidance on this path, let me know!

**Comment by tigitz** [comment]
Alright, noted. Just for my own understanding, what would be the downside of my proposal that makes you think it wouldn't be a good idea ? From my POV it seems introducing flexibility in the way seomatic users can generate their breadcrumbs would make seomatic even more powerful.

Thanks a lot for the provided info! I'll share it and hopefully convince him.

**Comment by khalwat** [comment]
Primarily because I believe it's assuming a structure, which isn't the case in many cases.

In any event, if you do want to do something custom, SEOmatic still 100% allows you to do it, either view the Twig API or the PHP API.
