### ISSUE TITLE
Using seomatic.helper.truncate() Function

### ISSUE THREAD

**Issue by AdamChlan** [nystudio107/craft-seomatic#832]
### Question
I'm looking to use this function - seomatic.helper.truncate(TEXT, LENGTH, SUBSTR) -  to ensure I have a unique title and description for a certain channel that has a tendency to have duplicate values for those fields. Below is an example of how I am using it.

```{% set title = entry.title %}
{% set date = entry.eventStartDateTime | date('F d, Y') %}
{% set cleanTitle = seomatic.helper.truncate(title, 70, date) %}

{% do seomatic.meta
    .seoTitle(cleanTitle)
%}
```

If I read the docs correctly, I would assume the length of truncation would be 70, and my title would be truncated an additional amount based on how long the date field text is, so the date can appear as well. Am I interpreting that correctly? 

My output for the code above just displays the title, and not the date. I can get the date to show up if I change my truncation length to something very low, like 5. But the title does not appear. 

If you have a working example of this in action, I would appreciate seeing it.

**Comment by khalwat** [comment]
Yeah that's not correct. The last parameter is what is appended to the string if and only if it's actually been truncated.

So you probably want something like:

```twig
{% set date = entry.eventStartDateTime | date('F d, Y') %}
{% set cleanTitle = seomatic.helper.truncate(title, 70 - (date | length)) ~ date %}

{% do seomatic.meta
    .seoTitle(cleanTitle)
%}
```

**Comment by AdamChlan** [comment]
Thanks @khalwat this get me straightened out.
