### ISSUE TITLE
Misplacement of closing bracket SEOmatic 3.3.31

### ISSUE THREAD

**Issue by john-henry** [nystudio107/craft-seomatic#833]
https://github.com/nystudio107/craft-seomatic/blob/aa85b1d5bf2be50bf6757e8f09a6b0ca5c0cf5f2/src/seomatic-config/globalmeta/JsonLdContainer.php#L40

Causing a slew of errors on site

`'id' => '{parseEnv(seomatic.site.identity.genericUr)l}#identity',
`
should be

`'id' => '{parseEnv(seomatic.site.identity.genericUrl)}#identity',`

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.32
