### ISSUE TITLE
Set Environment on a per-site base

### ISSUE THREAD

**Issue by jan-dh** [nystudio107/craft-seomatic#834]
### Is your feature request related to a problem? Please describe.
When launching a multisite setup sometimes the launch times differ. In order to make sure that the analytics etc. only work when launched this would be a handy feaure.

### Describe the solution you would like
Be able to override the default settings on a per site base

**Comment by khalwat** [comment]
You should already be able to do this via the multi-environment away `config.php` file: 

https://github.com/nystudio107/craft-seomatic/blob/v3/src/config.php#L53
