### ISSUE TITLE
Incorrect `og:locale` in GraphQL response

### ISSUE THREAD

**Issue by marcoeh** [nystudio107/craft-seomatic#835]
### Describe the bug
In our multi-site setup (two languages) the `og:locale` is always set to the default language.

### To reproduce
Steps to reproduce the behaviour (let me know if you can't easily reproduce and need more info):
Compare the repsonse (`language` and `og:locale`) of
```bash
curl \
  -H "Content-Type: application/json" \
  -d '{
        "query": "query { entry(site: \"de\", uri: \"test-seite\") { language, seomatic { metaTagContainer } } }"
      }' \
  https://lucid-craft-2021.lucid.build/api
```
=> correct for default language (German)

```bash
curl \
  -H "Content-Type: application/json" \
  -d '{
        "query": "query { entry(site: \"en\", uri: \"test-page\") { language, seomatic { metaTagContainer } } }"
      }' \
  https://lucid-craft-2021.lucid.build/api
```
=> incorrect for English

### Expected behaviour
Return og:locale based on language of requested entry.

### Versions
- Plugin version: `3.3.31`
- Craft version: Craft Pro `3.6.5.1`

**Comment by khalwat** [comment]
You don't specifically state it, but it appears that you're using this on a headless site. If that's the case, you'll need to pass in the optional `siteId` parameter along with your query:

https://nystudio107.com/docs/seomatic/Advanced.html#headless-spa-api

**Comment by marcoeh** [comment]
Correct, we have set `headlessMode` to `true`.

I checked with your suggestion and it does not seem to work as expected:
<img width="1332" alt="Screenshot 2021-02-12 at 17 11 19" src="https://user-images.githubusercontent.com/6922319/107793259-5f64f900-6d56-11eb-8d0f-f15cf4cfe204.png">

On another note, do you have an idea why `content` inside of `metaTagContainer` is not behaving properly (set to `{seomatic.helper.extractSummary(seomatic.helper.extractTextFromField(object.entry.pageBuilder))}` in the response). This only happens on my local dev setup (Craft Nitro 2.0.0-beta.3 with PHP 7.4 and mysql 8.0), regardless of the specified `ENVIRONMENT` (dev, staging, production).

Here is our [repo](https://github.com/wearelucid/lucid-craft-2021) if you want to have a look.

Thanks for your help Andrew.

**Comment by khalwat** [comment]
Verified it and fixed in: https://github.com/nystudio107/craft-seomatic/commit/ebe39113de1f65c54dad459721c2b84184c47d57

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.33”,
```
Then do a `composer update`
