### ISSUE TITLE
Getting SEO image 

### ISSUE THREAD

**Issue by croxton** [nystudio107/craft-seomatic#836]
### Question
I'd like to use Imgix for SEOmatic image transforms, so that I can use static caching without Craft's generate transform urls being cached the first time a page is requested - and I don't want to set `generateTransformsBeforePageLoad = true` for performance reasons. 

I can parse the `seomatic.meta.seoImage` string ( and `seomatic.meta.ogImage`, `seomatic.meta.twitterImage`) to extract the asset ID, but it's hacky. For example:
```twig
{% set seoImageAssetId = seomatic.meta.seoImage | replace('{seomatic.helper.socialTransform(', '')|replace('/,.*/', '') %}
{% if seoImageAssetId matches '/^\\d+$/' %}
    {% set seoImage = craft.assets.id(seoImageAssetId).one() %}
    {% if seoImage %}
        {% do seomatic.meta.seoImage( seoImage.path | imgix({ width:1200, height:630, crop:'focalpoint', fit:'crop', 'fp-x': 0.5, 'fp-y': 0.5, signed: true }) ) %}
    {% endif %}
{% endif %}
```

Is there a more elegant way to do this?

**Comment by khalwat** [comment]
A more elegant way would be to use a plugin that entirely replaces Craft transforms to use Imgix (such as ImageOptimize) because then all transforms would just automatically go through Imgix.

Barring that, the solution you've posted seems workable.
