### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by clarknelson** [nystudio107/craft-seomatic#837]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.

For some reason when I disable the plugin the error goes away. Thought it might be related to this Craft 2 error: https://github.com/nystudio107/seomatic/issues/33. 

I've restarted the server and tried to make sure everything is up to date: 
- Craft 3.6.5.1
- SEOmatic 3.3.32

I found this in the Nginx logs:

```
2021/02/15 16:57:17 [error] 3607#3607: *730 upstream sent too big header while reading response header from upstream, client: 99.46.148.171, server: dev.cascadeapartments.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "dev.cascadeapartments.com"
```

The dashboard (`/admin/login`) all works fine, its just the front-end that is giving me a 502.

Any idea where I can turn next? Thanks :)

**Comment by khalwat** [comment]
It's very unlikely that this is an issue with the plugin itself, and most likely that this is some kind of an Nginx configuration issue.

I realize that it works with the plugin not installed, and doesn't work with it installed... but probably it's just surfacing a problem with the Nginx config (especially given the error)

The only thing SEOmatic does is optionally add a couple of headers... but you can turn them off in SEOmatic -> Plugin Settings

It's pretty unlikely that this would ever cause an issue unless the Nginx config isn't quite right. Have a look here:

https://ma.ttias.be/nginx-proxy-upstream-sent-big-header-reading-response-header-upstream/#:~:text=If%20the%20HTTP%20headers%20contain,configurations%20to%20your%20location%20block.

**Comment by clarknelson** [comment]
Thank you! It was some of the added headers interacting with my config. Disabling "generator enabled" and "http headers" in the tags section seems to work.
