### ISSUE TITLE
Google Tag Manager code ends up in body instead of head

### ISSUE THREAD

**Issue by royslampaq** [nystudio107/craft-seomatic#838]
When I set 'Head' as the Script Render Location in the Google Tag Manager settings, the resulting code ends up in the tag, the same as when I choose 'Body Begin'. Changing it to 'Body End' does change the position as expected.

I'm using the latest version (3.3.30); on another site I have access to, which runs on 3.3.8, the code ends up in the right place, but I can't find difference in settings or such which might cause this issue.

**Comment by khalwat** [comment]
So you probably shouldn't be _changing_ the render locations for the various parts of the GTM script, unless you have a very strong reason for doing so?

The built-in locations (one in the head, the other in the body) are what Google recommends for GTM installations.

What are you trying to accomplish?

**Comment by khalwat** [comment]
Will re-open if more info is provided
