### ISSUE TITLE
Site Title Position in SEO field - doesn't remember setting

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#839]
### To reproduce
Steps to reproduce the behaviour:
1. edit an entry with an SEO field and change the site title position to none
2. save and in the preview it appears to be correct but the settings dropdown does not change.

### Expected behaviour
settings dropdown should show the correct setting after saving.

### Screenshots
![Screenshot 2021-02-16 090534](https://user-images.githubusercontent.com/6899490/108073988-adb81780-7036-11eb-9cc8-39aed766e016.png)

### Versions
- Plugin version: 3.3.30
- Craft version: 3.6.2

**Comment by khalwat** [comment]
So you're saying it's working, but the position isn't reflected in the GUI?

**Comment by CreateSean** [comment]
@khalwat Yes that's correct.

**Comment by khalwat** [comment]
I can't reproduce this here. My presumption is that you're setting it to the same value it's already set to, and since the SEO Settings field is considered an override, it'd defaulting back to a blank entry, which is intended to indicate "no change"
