### ISSUE TITLE
[FR] Add protocol if missing from image URL

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft-seomatic#84]
I have set up my asset volumes to be protocol-relative as per the recommendation (`//s3.us-east-2.amazonaws.com`), however it seems that Twitter cards aren't picking up the images even though I can see it in the page source. I'm thinking that they need the protocol in the URL? Can you add a line that detects if it exists and if not, adds either http or https?

**Comment by khalwat** [comment]
So I think it's a good idea that I add this feature. But in general, I'm not sure you'd really want or need a protocol-less URL for images, unless you have a site that really does work both http and https

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/eba4eb8cc6773a847691173727c2f305d61b652b
