### ISSUE TITLE
Mapping SEO image through Feedme not working 

### ISSUE THREAD

**Issue by sg-modlab** [nystudio107/craft-seomatic#840]
### Describe the bug
Trying to map an asset to the SEO image via Feedme is not working. Not sure if that is something to share here or something for Feedme.

### To reproduce
Steps to reproduce the behaviour:

Here is a snippet of the JSON being read by Feedme:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/529067/108218690-eb827200-7102-11eb-9922-2dba5f13149b.png">

### Expected behaviour
The image (which is confirmed to be in our assets) will be mapped and shown as a custom image in the SEO field associated with entry. Mapping the filename of the image should work.

### Versions
- Plugin version: 3.3.32
- Feedme version: 4.3.5.1
- Craft version: 3.5.17.1

**Comment by khalwat** [comment]
I'm not sure exactly how this is intended to work -- @engram-design do you have any idea?

**Comment by khalwat** [comment]
I talked with @engram-design about it, and he said:

> Must be a feed me issue
> It should fine an existing asset if they have it set to that in feed me
> They should try and run the debug action in feed me

So maybe give that a go, and potentially file an issue with P&T?

**Comment by khalwat** [comment]
@sg-modlab did this end up working for you?

**Comment by sg-modlab** [comment]
Thanks for following up. Been in deep with other issues on this project had kind of moved on. No, don't have a solution yet and no response on issue posted.

https://github.com/craftcms/feed-me/issues/813

**Comment by khalwat** [comment]
Could this be because the Asset IDs in SEOmatic are actually stored here: https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/MetaBundleSettings.php#L92

...and what is here is just the URL or Twig for the image? https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/MetaGlobalVars.php#L74

**Comment by sg-modlab** [comment]
@khalwat your questions is a bit beyond what I personally could answer quickly (or maybe at all :-).

**Comment by khalwat** [comment]
Okay so I'm not super familiar with how FeedMe works, but I think my initial guess was right. It looks like FeedMe is attempting to import assets into the various fields in `metaGlobalVars`:

`seoImage` - https://github.com/nystudio107/craft-seomatic/blob/v3/src/templates/_includes/integrations/feedme/seo-settings.twig#L70

`twitterImage` - https://github.com/nystudio107/craft-seomatic/blob/v3/src/templates/_includes/integrations/feedme/seo-settings.twig#L149

`ogImage` - https://github.com/nystudio107/craft-seomatic/blob/v3/src/templates/_includes/integrations/feedme/seo-settings.twig#L132

...which is a reasonable enough assumption. But actually, that is a text field that is intended to be either a URL to an image, or Twig code that resolves to a URL to the image.

The asset IDs actually should be stored in `metaBundleSettings`:

`seoImageIds` - https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/MetaBundleSettings.php#L92

`twitterImageIds` - https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/MetaBundleSettings.php#L164

`ogImageIds ` - https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/MetaBundleSettings.php#L224

**Comment by engram-design** [comment]
@sg-modlab I've just added a [PR](https://github.com/nystudio107/craft-seomatic/pull/865) for better (fixed) support for asset and the images that you can map to SEO settings. I don't believe it was working correctly by uploading remote assets, or trying to match existing ones.

**Comment by khalwat** [comment]
You're the best @engram-design

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/68e57920b367f5c9d39bda9597abcc99b9a71257

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.39”,
```
Then do a `composer clear-cache && composer update`

**Comment by RedLucas** [comment]
So this doesn't seem to totally work for me. I've been dealing with what I thought were two separate issues in my testing. (I tested on a local instance and the result was that the SeoImage (but not the Twitter and Facebook for what it's worth) was appearing, but only the thumbnail, not the SEO preview. 

I figured there was a problem with my transformer locally, so I rolled it out on a Servd dev server, and got a similar result, but without the thumbnail even working. (the thumbnail was a broken image icon)

I then realized that I didn't know which volume it was saving that image to, and after some searching, I couldn't find that image in my assets in either case, in any of my Asset volumes. 

My conclusion is that, while I can set a default volume for regular asset fields, I am not able to do so for these SEOmatic fields. As a result, I don't know where these assets are actually being saved to.

i took a look at the logs and the code does create an asset for the fields correctly.
`Blog: Data to update for seoSettings: {"metaGlobalVars":{"seoDescription":"With businesses making the move to serve their customers primarily online and the footfall of customers in physical stores dropping dramatically, the value of SEO has been rediscovered. This post will offer a guide to businesses looking to enhance their organic reach and traffic, by providing some SEO solutions to issues they might be experiencing. ","canonicalUrl":null},"metaBundleSettings":{"seoImageIds":[961871],"twitterImageIds":[961872],"ogImageIds":[961871]}}`

However, in the database, those assets' volumeIds are NULL.

**Comment by khalwat** [comment]
That makes complete sense @RedLucas thank you. I will have a look to see if I can figure out how FeedMe expects that.

**Comment by khalwat** [comment]
I'm hoping it's as simple as adding something like this: https://github.com/craftcms/feed-me/blob/develop/src/templates/_includes/elements/assets/groups.html

**Comment by khalwat** [comment]
@sg-modlab @RedLucas think we might finally have this: https://github.com/nystudio107/craft-seomatic/commit/1dfddcb994030e210bd64132473df13451384540

It'll at least dump the imported images in the first volume id it can find (you can always move them later if needs be)

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.40”,
```
Then do a `composer clear-cache && composer update`

thx @engram-design

**Comment by engram-design** [comment]
@RedLucas For some background, the integration will upload remote images into the first available folder. This is because unlike something like an asset field, or a user photo, there's no nominated folder for SEO fields, and we need to select a folder for it to be uploaded into. There's no setting (that I recall) in Feed Me's mapping that let you set this, and maybe that needs a bit more tweaking.

But, as the output shows, it's successfully uploaded the image, because you've got an ID back, it's probably just added it to the first folder in your `volumefolders` db table.

However, I can see that there's the possibility it can upload it to the first folder without a `volumeId` as you've stated, which are temporary directories. This should be fixed in https://github.com/nystudio107/craft-seomatic/pull/867

Sorry @khalwat 😅

But, it'd be ideal if we can nominate a default folder in the mapping screen, I'm just not sure if its possible in Feed Me at the moment...

**Comment by khalwat** [comment]
Going to close the issue because @engram-design was able to verify the fix on his end. I can re-open it if there are further problems.

**Comment by RedLucas** [comment]
Can confirm that this does resolve my issue.
