### ISSUE TITLE
Don't overwrite SEOmatic environment from live if it is specifically set to live 

### ISSUE THREAD

**Issue by jsmrtn** [nystudio107/craft-seomatic#842]
We need to have the SEOMatic environment set to live, even on a staging environment, as it allows us to run automated scans of the website for a11y and performance.

We have manually set the SEOmatic environment to live, but because the `.env` environment is set to staging, it automatically supersedes whatever we set in the plugin.  

![Screenshot_2021-02-18_at_15 11 31](https://user-images.githubusercontent.com/1694957/108741584-cb054e00-752e-11eb-8c45-9b52539ddc86.png)

I appreciate the overwrite is likely to save people from themselves, but I would suggest sometimes you have to let people do what they're asking, even if it is at potential detriment. Perhaps it is worth having a different SEOmatic environment that, when set, forces the plugin to operate as live.

**Comment by khalwat** [comment]
You could set the ENVIRONMENT variable in your `.env` to `live` and that'll do the trick.

**Comment by jsmrtn** [comment]
I can't–we use Servd for our staging deployment and `ENVIRONMENT` is a reserved keyword–hence why I've asked 😀

**Comment by khalwat** [comment]
I'll add an "ignore `ENVIRONMENT` variable setting"

**Comment by khalwat** [comment]
Added **Manually Set SEOmatic Environment** https://github.com/nystudio107/craft-seomatic/commit/58859b3e14ada4291bd41cdc78de4ae934e94ce0

This already worked as expected if you override the settings via the `config.php` file but it's reasonable you might want to do so via an environment variable as well, so added the above.
