### ISSUE TITLE
Fields Setup in Content SEO is not respected

### ISSUE THREAD

**Issue by kaspar-allenbach** [nystudio107/craft-seomatic#844]
When I set up the default fields for the seo fields in the Content SEO it is not reflected in the entries.

### Step 1: Go to ContentSEO
![Bildschirmfoto 2021-02-25 um 17 26 05](https://user-images.githubusercontent.com/762213/109183919-ba531300-778e-11eb-876b-c3955846bfb3.png)

### Step 2: Define the default fields which should be taken in the entries:
![Bildschirmfoto 2021-02-25 um 17 26 17](https://user-images.githubusercontent.com/762213/109184024-d5258780-778e-11eb-8e36-7081ef8a2559.png)

### Step 3: In the respective entry  the fields are still blank and not setup with the default fields I defined in content seo:

![Bildschirmfoto 2021-02-25 um 17 26 23](https://user-images.githubusercontent.com/762213/109184114-f0909280-778e-11eb-9715-c96a35e8057b.png)

What do I do wrong? I want the fields to grab the content from the fields I defined in Content SEO

Craft v: 3.6.7
SEOMatic: 3.3.32

**Comment by khalwat** [comment]
You did nothing wrong. The SEO Settings field is an _override_ -- it isn't intended that it'll reflect what is set in your Content SEO settings. You use it in case you want to _override_ the settings.

This is bad UX, and it's on the list to make it better: https://github.com/nystudio107/craft-seomatic/issues/535
