### ISSUE TITLE
503 Error for Sitemaps after clearing cache

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-seomatic#846]
### Describe the bug
We are seeing 503 errors thrown for all XML sitemaps after clearing the SEOMatic caches. Refreshing again and the issue resolves itself (and is cached) but is becoming a weekly problem when we rebuild environments (which clears the cache). Seems consistent across environments and becoming an issue when Google bots are the ones to first hit the sitemap (which is likely) but getting a 503 error. My assumption is that this is run via a job so should not ever get to this point?

### To reproduce
Steps to reproduce the behaviour:
1. Clear SEOMatic sitemap caches
2. Navigate to a XML sitemap for the site
3. See error message 503 Service Unavailable in the console
4. Refresh page and error dissapears

### Expected behaviour
Should not throw 503 error

### Screenshots
![image](https://user-images.githubusercontent.com/3185073/109795925-725d4180-7c0f-11eb-976e-2652001a77f5.png)

### Versions
- Plugin version: 3.3.32
- Craft version: 3.6.6

**Comment by khalwat** [comment]
This is not a bug, this is expected behavior.

The 503 error is `Service Unavailable` and SEOmatic sets the `Retry-After:` header so the bots know that they should check back in a minute. https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/SitemapTemplate.php#L168

SEOmatic generates the sitemaps via queue job, because very large sitemaps can take a long time to generate. Then it caches the result, which is what is normally returned.

But if you clear the cache, now the sitemaps will need to be regenerated again. Someone visiting a sitemap page causes the queue job to be pushed, a 503 status code with `Retry-After:` header set, and the new sitemap will be regenerated and cached.

This is all normal, and works fine. But if you want to immediately regenerate all sitemaps after caches have been cleared, you can use the CLI command:

```
- seomatic/sitemap                                 SEOmatic Sitemap command
    seomatic/sitemap/generate                      Generate a sitemap. You can pass in a --handle and/or a
                                                   --siteId
```

**Comment by baileydoestech** [comment]
Thanks - makes sense (although strange our alerting has not triggered this before if it has always retruned 503)

I feel that a `202 Accepted` response with the `Retry-After` would be more semantically correct though:

`indicates that the request has been accepted for processing, but the processing has not been completed; in fact, processing may not have started yet. The 202 response is intentionally non-committal. Its purpose is to allow a server to accept a request for some other process (perhaps a batch-oriented process that is only run once per day) without requiring that the user agent's connection to the server persist until the process is completed`

Whereas a 503 response is as follows (which isn't what has happened here, we are just waiting for the job to be processed):

`The server is currently unable to handle the request due to a temporary overloading or maintenance of the server`

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.3

Another argument would be 5XX errors can often be used to trigger auto-scaling events or instance replacements

**Comment by khalwat** [comment]
mmmm you make a good case for 202 -- but I'm fairly certain that I read that Google is expecting a 503 in this case, to trigger its bots to come back later.

See "Telling Google you're busy" here: https://yoast.com/http-503-site-maintenance-seo/

I'm not sure `Retry-After` is even looked at for 202 codes?

**Comment by baileydoestech** [comment]
Yeah same I can't find any explict mention that `Rety-After` is accepted on 202 responses. However the spec has statements like this:

`If the action cannot be carried out immediately, the server SHOULD respond with 202 (Accepted) response instead. `

Would be interested if Google/Bing etc actually have official guideance on bot behaviour (just descends into a guessing game on StackOverflow otherwise). The workaround (running the queue job straight after clearing the cache) is enough to not worry about this - just the semantics seem off to me.

**Comment by khalwat** [comment]
I'm with you. I'd love a definitive answer too, and I'd obviously be happy to implement whatever that answer ends up being.

The issue is despite looking high and low, I haven't found anything explicitly _from_ Google.
