### ISSUE TITLE
Error after updating to 3.3.34 (Manifest not found)

### ISSUE THREAD

**Issue by petertindemans** [nystudio107/craft-seomatic#847]
I've installed the latest updates, including the last SEOMatic version. After that I noticed that I get a error when opening entries where the SEOMatic settings is present as a field. Channel entries without the SEO settings are working normally.

Error when opening entry:
Class 'nystudio107\seomatic\helpers\Manifest' not found

### To reproduce
Steps to reproduce the behaviour:
1. Enable dev mode
2. Go to Entries
3. Click on a random entry where the the SEO Settings are present
4. See error message: Class 'nystudio107\seomatic\helpers\Manifest' not found

### Versions
- Plugin version: 3.3.34
- Craft version: 3.6.8

**Comment by khalwat** [comment]
Fixed in 3.3.35 -- sorry about that!

https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.35

**Comment by petertindemans** [comment]
Thanks for the quick response!
