### ISSUE TITLE
Access to the nested JSON values with JS

### ISSUE THREAD

**Issue by Stalex89** [nystudio107/craft-seomatic#848]
### Question
I'm trying to fetch SEOmatic data with GraphQL to the Nuxt.js, however I'm having an issue with accessing nested data inside the JSON array. Object values are represented as strings and give me an error while trying to parse the value.
Stringify-parse trick also didn't work for me.

Accessing the values as seomatic.metaTitleContainer["title"] returns me undefined.

Can you tell me please how can I access values from the nested JSON strings, or is it possible to enhance the plugin to return the complete JSON structure? Thank you 

### Additional context
Add any other context or screenshots about the support request here.

**Comment by khalwat** [comment]
All you should need to do is convert the string to `JSON.parse()` -- assuming you requested the data with `asArray: true`

**Comment by khalwat** [comment]
Will re-open if more information is provided.
