### ISSUE TITLE
Add `og:image:width` and `og:image:height` for transformed images

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-seomatic#85]
I'm getting the following error in Facebook's Sharing Debugger for an image set via `og:image`:

> The provided 'og:image' properties are not yet available because new images are processed asynchronously. To ensure shares of new URLs include an image, specify the dimensions using 'og:image:width' and 'og:image:height' tags.

I think I can fix this in my template, but it would be great if SEOmatic could provide these meta tags for the transformed image used for `og:image`.

**Comment by khalwat** [comment]
This is a trickier problem than it might seem at first, but I'd like to get it done.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/91f44a40efeb13841d3263de289cca5b511f4a58

**Comment by khalwat** [comment]
You will need to re-save the Twitter and Facebook settings for your Global SEO and Content SEO pages for existing SEOmatic setups for this to propagate.
