### ISSUE TITLE
Configure SEO image transform quality

### ISSUE THREAD

**Issue by matthillco** [nystudio107/craft-seomatic#852]
### Is your feature request related to a problem? Please describe.
The default value of 82% quality for social share image transforms is not suitable for all cases. It would be useful to have an optional override for this value. 

### Describe the solution you would like
Can this value be exposed in either a config file setting, or in the control panel UI (or both)?

**Comment by khalwat** [comment]
Are you looking for something higher quality or lower quality? All of the social media sites end up rendering their own version of your image anyway, so you may not have full control over this.

I'm thinking that if this is of a concern, probably you should provide your own SEO image via custom Twig in the SEO Image field as per:

https://nystudio107.com/docs/seomatic/Configuring.html#content-seo

**Comment by matthillco** [comment]
OK that makes sense, thanks, I can definitely do it that way. Cheers.
