### ISSUE TITLE
Remove page from sitemap.xml

### ISSUE THREAD

**Issue by NickSL8** [nystudio107/craft-seomatic#853]
Hi,

I have a question regarding the sitemap.xml of Seomatic. I would like to disable a specific page from the sitemap.xml although it's still enabled. It seems it's only possible to disable entire sections, but not a single page within a structure. Is there any way to fix this?

Kind regards,
Nick

**Comment by khalwat** [comment]
So a couple of things real quick:

- If the page is not in the sitemap, but it is still enabled in the Craft backend, that means it's still publicly available, so bots will still find it and index it
- A page being in the sitemap is only a way to tell Google what to crawl; removing it from the sitemap doesn't remove it from Google's index

So I think you probably want to disable the entry (which will remove it from the sitemap) or just let it be in the sitemap if you intend to keep the URL publicly available.

If you _really_ want to, you can add an SEO Settings field to the channel, and remove just certain entries from the sitemap, but if bots can continue to crawl the public URL, there isn't much point in it.

**Comment by NickSL8** [comment]
Hi khalwat, 

Thanks for the quick response.

The problem is that we don't want to disable the entry. We just want the page removed from the sitemap.xml. The page itself has a no index no follow, but is still in the sitemap. Is there any way to accomplish this?

Kind regards,
Nick

**Comment by khalwat** [comment]
yes, as per the previous response, you can set that in an SEO Settings field for that entry.

**Comment by andreasbecker** [comment]
Is there a Twig tag as well to exclude a page from the sitemap? We have a page where we set 

```
{% if isPromotion %}
   {% do seomatic.meta.robots("none") %}
{% endif %}
```

 and that page should also not be part of the sitemap. Would be great if we could do this programmatically like for the robots

**Comment by khalwat** [comment]
There is not @andreasbecker because Twig is never executed in the context of a sitemap.

You could use an SEO Settings field to selectively remove things from the sitemap, however.

Also, keep in mind that removing something from a sitemap does _not_ remove it from Google's index.

**Comment by icreatestuff** [comment]
@khalwat is it possible to retrieve the applied 'Sitemap Enabled ' setting on a per entry level within a template?

I've looked at the [Config Variables](https://nystudio107.com/docs/seomatic/using.html#config-variables-seomatic-config) page but couldn't see anything that would bring back that setting when used with the `{{ entry.seo.metaGlobalVars.parsedValue('') }}` tag.

**Comment by khalwat** [comment]
@icreatestuff Probably this should be on a new issue, but you can use:

```twig
{% if seomatic.sitemap.sitemapUrls %}
    {# they are enabled #}
{% endif %}
```

**Comment by icreatestuff** [comment]
Thanks @khalwat, that's just what I needed. Yes, sorry it probably should have been 🫣
