### ISSUE TITLE
AddDynamicMetaEvent don't work?

### ISSUE THREAD

**Issue by espensgr** [nystudio107/craft-seomatic#854]
I'm trying to add metadata to content that is not part of Craft. I have setup a small REST api in a module with Craft as a backend and NuxtJS as a frontend. So the content is fetched from another api and mapped to what we need from it and output with an controller and a service from Craft.

We get the default metadata in the endpoint, but we want to add images, title, description etc from the api fetch. Just the same way you can do in the twig template with `{% do seomatic.meta.setAttributes() %}`.

So i checked the documentation and found AddDynamicMetaEvent, added the example but it fails on the `EVENT_INCLUDE_CONTAINER `.

```
"name": "Exception",
"message": "Undefined class constant 'EVENT_INCLUDE_CONTAINER'",
"code": 0,
"type": "Error",
```
I guess this is a bug, or the wrong class name on the documentation? this may be tagged as a question rather than a bug in that case.
And is this the right approach for my use case, maybe add a bit more info to the documentation on how to use it?

### Versions
- Plugin version: 3.3.33
- Craft version: 3.6.7

**Comment by khalwat** [comment]
I'd need to see your code, but I think the docs are correct:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/base/Container.php#L90

https://github.com/nystudio107/craft-seomatic/blob/v3/src/base/ContainerInterface.php#L41

But yes, your approach seems like a way to do what you want.

**Comment by espensgr** [comment]
Yeah the Container class is not in the docs  for this: https://nystudio107.com/docs/seomatic/Advanced.html#adddynamicmetaevent
It uses the `DynamicMeta` helper and `AddDynamicMetaEvent` event.

**Comment by khalwat** [comment]
Can you show me your code that is not working / throwing the error please? The class you're referencing does exist, I especially need to see your `use` declarations.

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L66

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L301

**Comment by espensgr** [comment]
Yeah sure, i just copied the example code:
```
use nystudio107\seomatic\events\AddDynamicMetaEvent;
use nystudio107\seomatic\helpers\DynamicMeta;
use yii\base\Event;

Event::on( DynamicMeta::class, DynamicMeta::EVENT_INCLUDE_CONTAINER, function(AddDynamicMetaEvent $e) {
    // Add whatever dynamic meta items to the containers as you like
} );
```
i then get:
```
"name": "Exception",
"message": "Undefined class constant 'EVENT_INCLUDE_CONTAINER'",
"code": 0,
"type": "Error",
```

**Comment by khalwat** [comment]
Ah I see, you're right, the docs are wrong, sorry about that. Fixed in https://github.com/nystudio107/craft-seomatic/commit/b08c0b2269dc83d9b22cb2e28b37e8d124af5e22

So the code example should be:

```php
use nystudio107\seomatic\events\AddDynamicMetaEvent;
use nystudio107\seomatic\helpers\DynamicMeta;
use yii\base\Event;

Event::on( DynamicMeta::class, DynamicMeta::EVENT_ADD_DYNAMIC_META, function(AddDynamicMetaEvent $e) {
    // Add whatever dynamic meta items to the containers as you like
} );
```

**Comment by espensgr** [comment]
Nice!
But still, how do i actually use this event?
Don't really see how to add like a custom title to a certain uri.
Maybe add an more extensive example in the docs?

**Comment by khalwat** [comment]
Well, at this time, you can use PHP and the SEOmatic API to add whatever you like to the various containers. Check out some of the code in the DynamicMeta class to see how it's fetching tags and changing them and such:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L149

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L503

**Comment by espensgr** [comment]
okey, so i did this:
```php
$title = Seomatic::$seomaticVariable->title->get();
$title->title = $tildeling->title;

$title = Seomatic::$seomaticVariable->tag->get( 'og:title' );
$title->content = $tildeling->title;

$nyDesc = ContentService::instance()->nl2br( $tildeling->comment1 ?: $tildeling->comment2 ?: null );
$description = Seomatic::$seomaticVariable->tag->get( 'description' );
$description->content = $nyDesc;

$description = Seomatic::$seomaticVariable->tag->get( 'og:description' );
$description->content = $nyDesc;

if (isset( $tildeling->publicmedia->mainimage )) {
    $image = Seomatic::$seomaticVariable->tag->get( 'og:image' );
    $image->content = $tildeling->publicmedia->mainimage;
}
```
And it works, but is there a better way to set the title, description and image on a higher leves so i don't have to add it to the `og`, and `twitter` separately?

**Comment by khalwat** [comment]
Nope, it looks right -- they are separate variables so you can have different images and descriptions if you want them.
