### ISSUE TITLE
sameAsLinks returns messed up array

### ISSUE THREAD

**Issue by TomDeSmet** [nystudio107/craft-seomatic#855]
### Describe the bug
This is very weird. I updated to the latest SEOmatic and Craft (could be a Twig implementation Craft issue too) and the following code stopped working:

```
{% set socialServices = seomatic.site.sameAsLinks|filter(v => v.url and v.url != '') %}
{% if socialServices|length %}
    {% for socialService in socialServices %}
        <a href="{{ socialService.url }}">Click me</a>
    {% endfor %}
{% endif %}
```

The problem is that `socialService.url` says that there is no key `url` in an array with keys `handle`.
But if I dump`socialService` I get an array that includes the 'url' key among others. No key `handle` as this is a key in the `seomatic.site.sameAsLinks` array.

If I dump `seomatic.site.sameAsLinks['youtube']['url']` I get the correct value.

But if I do somthing like:

```
{% for key in seomatic.site.sameAsLinks|keys %}
    <a href="{{ seomatic.site.sameAsLinks[key]['url'] }}">Click me</a>
{% endfor %}
```

It goes wrong again with the same error.

**Comment by khalwat** [comment]
Doesn't sound like an SEOmatic issue per-se -- but show me what this outputs:

```twig
{{ dump(seomatic.site.sameAsLinks) }}
```

And also what this looks like after going through your filtering:

```twig
{{ dump(socialServices) }}
```

**Comment by TomDeSmet** [comment]
The first one dumps this:

```
array(6) {
  ["linkedin"]=>
  array(4) {
    ["siteName"]=>
    string(8) "LinkedIn"
    ["handle"]=>
    string(8) "linkedin"
    ["url"]=>
    string(44) "https://www.linkedin.com/company/myharmoney/"
    ["account"]=>
    string(0) ""
  }
  ["twitter"]=>
  array(4) {
    ["siteName"]=>
    string(7) "Twitter"
    ["handle"]=>
    string(7) "twitter"
    ["url"]=>
    string(31) "https://twitter.com/my_harmoney"
    ["account"]=>
    string(0) ""
  }
  ["youtube"]=>
  array(4) {
    ["siteName"]=>
    string(7) "YouTube"
    ["handle"]=>
    string(7) "youtube"
    ["url"]=>
    string(56) "https://www.youtube.com/channel/UCPt33EmN0XAv1a8KyH6RFaQ"
    ["account"]=>
    string(0) ""
  }
  ["instagram"]=>
  array(4) {
    ["siteName"]=>
    string(9) "Instagram"
    ["handle"]=>
    string(9) "instagram"
    ["url"]=>
    string(0) ""
    ["account"]=>
    string(0) ""
  }
  ["pinterest"]=>
  array(4) {
    ["siteName"]=>
    string(9) "Pinterest"
    ["handle"]=>
    string(9) "pinterest"
    ["url"]=>
    string(0) ""
    ["account"]=>
    string(0) ""
  }
  [""]=>
  array(1) {
    ["handle"]=>
    string(0) ""
  }
}
```

The second dump is what triggers the error: `Key "url" for array with keys "handle" does not exist.`

**Comment by khalwat** [comment]
You're saying that this:

```twig
{{ dump(socialServices) }}
```
...generates the error `Key "url" for array with keys "handle" does not exist.` ? That doesn't make much sense to me...

**Comment by TomDeSmet** [comment]
Exactly! Makes no sense at all!

We have tried all possibilities and we got very strange errors. I have no idea what is going wrong since updating but this should be a basic array filtering.
The dumps show correct arrays but accessing the arrays seems to go wrong. It’s totally weird. 😞

Even when looping through `seomatic.site.sameAsLinks` like
```
{% for s in seomatic.site.sameAsLinks %}
{{ s.url }}
{% endfor %}
```
`s.url` triggers that error. Which wasn’t the case before the update and which shouldn’t happen.
Maybe it’s not a seomatic issue but I have no idea where this could originate from.

**Comment by TomDeSmet** [comment]
I took another look at it after a good night's sleep and noticed I did a JS style check instead of a Twig style check on `v.url`.
There was an empty line in the SEOmatic social links so url didn't exist. Changing it to `v.url is defined` solved it.
