### ISSUE TITLE
[FR] Add Facebook domain verification 

### ISSUE THREAD

**Issue by chrismlusk** [nystudio107/craft-seomatic#856]
Any plans to add a field to Social Media settings for the `meta facebook-domain-verification` tag? https://developers.facebook.com/docs/sharing/domain-verification/verifying-your-domain/#meta-tags

**Comment by bymayo** [comment]
Would be nice to have this also. We've had a couple of clients request adding this recently, but have to manually do it instead of allowing them to add it.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/34e76e27418fc0040ca59af123e3e8c383c1ba2f
