### ISSUE TITLE
Manually set a translation for a entry

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#858]
Hi,

Seomatic automatically sets rel="alternate" when a entry is propagated in a section. However, we clone the content manually, so the content has a different id, but is still a translation of the original piece.

Can we manually, trough a field or hooking into seomatic plugin, tell seomatic that a translation exists so that seomatic sets the alternate's correctly?

**Comment by khalwat** [comment]
mmmmm sounds like your fighting the built-in Craft translation system, so it may be a little involved, but you definitely can do all of this via Twig.

You can get the tag via: 
```twig
    {% set alt = seomatic.link.get('alternate') %}
    {% do alt.href([
            'http://example.com',
            'http://example.com/es'
        ]).hreflang([
            'x-default',
            'es',
        ])
    %}
```

see: https://github.com/nystudio107/craft-seomatic/issues/370#issuecomment-484095678

**Comment by lenvanessen** [comment]
We know;) but we need different publication dates for the translations, hence we can’t use the built-in system;(

**Comment by khalwat** [comment]
That's okay, you can use the technique above

**Comment by palomamtnez** [comment]
Hi @khalwat 
I have the same scenario as @lenvanessen; i have multiple sites with multiple languages but the content is the same from entry to entry in the different sites but translated and with a different entry ID 
 
I have used this method to add the hreflang and has worked fine! 
I still have a question though. How would I modify the sitemaps to add the alternate versions of the entry? 
Would I have to hook into an event when the sitemaps are generated or what would you suggest?

Thanks!

**Comment by khalwat** [comment]
I'd recommend you work with the built-in translation system that Craft provides if possible @palomamtnez -- but there are events for sitemaps if you want to do something custom via PHP:

https://nystudio107.com/docs/seomatic/advanced.html#registersitemapurlsevent
