### ISSUE TITLE
gtag.js script code does not load

### ISSUE THREAD

**Issue by D3strukt0r** [nystudio107/craft-seomatic#860]
### Describe the bug
When trying to use `Google gtag.js` I noticed that the part which should initialize gtag, is not appearing

`{% set gtagProperty = googleAnalyticsId.value ?? googleAdWordsId.value ?? dcFloodlightId.value ?? null %}`

This is the problematic code. I fixed it by using 

```twig
{% set gtagProperty = null %}
{% if googleAnalyticsId.value and googleAnalyticsId.value|length > 0 %}
    {% set gtagProperty = googleAnalyticsId.value %}
{% elseif googleAdWordsId.value and googleAdWordsId.value|length > 0 %}
    {% set gtagProperty = googleAdWordsId.value %}
{% elseif dcFloodlightId.value and dcFloodlightId.value|length > 0 %}
    {% set gtagProperty = dcFloodlightId.value %}
{% endif %}
```

`googleAnalyticsId.value` is not null, which means, it takes the first value, which is an empty string in my case. My version, checks if it's not null (redundant but anyways), and checks it's lenght.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "SEOmatic", "Tracking Scripts", "Google gtag.js"
2. Click on "Google gtag.js Enabled" to turn on
3. Use default code in "Script Template"

### Expected behaviour
Should show the code:

```twig
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments)};
gtag('js', new Date());
gtag('config', '...', {'send_page_view': true});
```

### Screenshots
-

### Versions
- Plugin version: 3.3.26
- Craft version: 3.5.17.1

**Comment by khalwat** [comment]
Isn't `googleAnalyticsId.value` required?

**Comment by D3strukt0r** [comment]
@khalwat Not to my knowledge, could have also been changed in later versions. But I also hope it wouldn't, because all i needed here was the `googleAdWordsId` and not the `googleAnalyticsId`

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/83dea919197f6464e214436bd20e28b3d509361f

So all the check for `gtagProperty` is trying to do in the main header script is ensure that _one_ of the properties is set. This can be fixed by using the `???` empty coalescing operator that is built into SEOmatic:

```twig
{% set gtagProperty = googleAnalyticsId.value ??? googleAdWordsId.value ??? dcFloodlightId.value ??? null %}
```

The problem arises in the body script, where it's actually using it in the `id=` URL param. We can fix that the same way:

```twig
{% set gtagProperty = googleAnalyticsId.value ??? googleAdWordsId.value ??? dcFloodlightId.value ??? null %}
{% if gtagProperty %}
<script async src="{{ gtagScriptUrl.value }}?id={{ gtagProperty }}"></script>
{% endif %}
```
