### ISSUE TITLE
Adding conditions around Tracking Script template

### ISSUE THREAD

**Issue by peteeveleigh** [nystudio107/craft-seomatic#862]
With the need to manage consent for tracking scripts I've been trying to add a conditional around the Seomatic tracking script templates. We are using Complete Cookie Consent (CCC) to manage which cookies the user wants. This provides an object with a record of what the user has/hasn't permitted.

It appears that SEOMatic doesn't have access to this CCC object - if I dump it out in the tracking script template then it is empty.

How would you suggest I achieve this? Is it possible to prevent SEOMatic automatically injecting the tracking script and instead include it manually on my layout template where I can use the conditionals?

I've seen that it's possible to remove auto meta tags and inject them with `seomatic.tag.render()`, and `seomatic.link.render()`. Is there something similar for the tracking scripts?

**Comment by khalwat** [comment]
Yep, you can do the exact same thing with tracking scripts that you do with the other tags.

Here are some examples:

https://nystudio107.com/docs/seomatic/Using.html#extra-tag-attributes

https://nystudio107.com/docs/seomatic/Using.html#script-meta-object-examples
