### ISSUE TITLE
Ability to set base URL used for OG / Twitter / SEO Images

### ISSUE THREAD

**Issue by roberttolton** [nystudio107/craft-seomatic#866]
### Is your feature request related to a problem? Please describe.
I think this might have become an issue from a change in SEO Matic, because it used to work before.

### Describe the solution you would like
A way to set the Base URL that is prepended to image paths given to functions like `seomatic.meta.twitterImage()` and `seomatic.meta.ogImage()`.

This is because my Base URLs of my sites are like so: `http://website.dev/en/` (English) and `http://website.dev/ja/` (Japanese)

So when I give a path such as `uploads/folder/image.jpg` SEO Matic renders the URL `http://website.dev/en/uploads/folder/image.jpg` which is a 404 because my images are stored in `uploads` not `en/uploads`.

So if in the functions I could pass a second param, or set via a config setting the URL I would like to use. Though not sure how either of those options scales well with multiple sites / domains.

### Describe alternatives you have considered
I am currently fixing this via Nginx rewrites: `rewrite ^/en/uploads(.*)$ /uploads$1 permanent;`

**Comment by khalwat** [comment]
So this is unlikely to end up being an SEOmatic issue or change, but potentially is a Craft CMS issue/change. SEOmatic doesn't do anything special, it just does Craft CMS image transforms.

If you want absolute URLs to your assets, you shouldn't be using relative URLs.

Can you clarify on where/how you are "giving a path" like `uploads/folder/image.jpg`?

**Comment by khalwat** [comment]
Will re-open if more information is provided

**Comment by roberttolton** [comment]
@khalwat Sorry for the delayed reply.

What I meant was, when I use `seomatic.meta.twitterImage()` or `seomatic.meta.ogImage()` and passing it a URL to an image in an Assets Field, like `module.image[0].url`

I'm doing this in my `posts/_entry` template, outside of my `{% block content %}` where I'm basically setting-up some things like this (SEO variables, etc).

I'm using a root-relative URI in my alias used in my Volumes for my uploads, starting with a forward-slash. Would that be the issue? If so, I figure there wouldn't be any second-guessing / site-url prepending by any URL parsing function if the protocol and domain were present.

Think I may have answered my own question here.

**Comment by khalwat** [comment]
yep I think so... any social media URLs have to be fully qualified absolute URLs
