### ISSUE TITLE
Global or Content SEO Image Transform Mode not being applied to new entries

### ISSUE THREAD

**Issue by Wiejeben** [nystudio107/craft-seomatic#868]
### Describe the bug
When I set the SEO Image Transform Mode inside Content SEO to fit and create a new entry the transform is still set to crop. Even if the transform mode field is hidden inside the SEO Settings field, crop is still being applied.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Content SEO.
2. Set the SEO Image Transform Mode of the relevant section to fit instead of crop. 
3. Create a new entry in that section and checkout the SEO Image Transform Mode option inside the SEO Settings field.

### Expected behaviour
I expected the Content SEO options to be the default for any newly created entries. I also expect any existing entries within the section to apply the new SEO Image Transform Mode if it wasn't already altered.

### Screenshots
Send an example with video on Discord to Andrew personally.

### Versions
- Plugin version: 3.3.40
- Craft version: 3.6.12
- PHP version: 7.4.16

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/3f7080d8b422c2d66710900594d6c22b64f5f96b

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.41”,
```
Then do a `composer clear-cache && composer update`
