### ISSUE TITLE
SEO Image gets language prefix appended in URL

### ISSUE THREAD

**Issue by Timusan** [nystudio107/craft-seomatic#869]
### Describe the bug

SEO Image gets language prefix appended in URL.

### To reproduce
Steps to reproduce the behaviour:
1. Set your SEO Image (from field or from custom image)
2. Save
3. View source

### Expected behaviour

It should take the direct asset url, eg. `https://example.com/assets/foo.jpg` but it takes `https://example..com/en/assets/foo.jpg` which leads to a 404.

Other assets on the site coming from the same asset volume and even from the same field get the correct URL when used in a Twig template (for example). Only SEOMatic seems to splice in that language prefix.

### Versions
- Plugin version: 3.3.39
- Craft version: 3.6.12

**Comment by khalwat** [comment]
Please show how your asset volumes are configured; I'm assuming they are not using full URLs?

That results in a non-absolute URL, and the various SEO images are _required_ to be full URLs.

**Comment by khalwat** [comment]
Likely related: https://github.com/nystudio107/craft-seomatic/issues/866

**Comment by Timusan** [comment]
You are correct, this appeared to be a configuration issue. The Base URL was `/assets/images` and had to be `@web/assets/images` to be a fully qualified URL without a language prefix.

This is solved, thank you for the quick response on this one! It is strange, however, that using these same assets in twig templates does produce a URL without a language prefix.
