### ISSUE TITLE
Setting unknown property: nystudio107\seomatic\models\MetaBundle::id

### ISSUE THREAD

**Issue by inghamemerson** [nystudio107/craft-seomatic#87]
Hello,

Running into an error after upgrading a Craft 2.6.29** install to 3. Its only happening on a couple of structure pages. Also seeing the same error in the admin when trying to manage settings for those pages.

Craft CMS 3.0.4
SEOMatic 3.0.2

![screen shot 2018-04-24 at 4 03 16 pm](https://user-images.githubusercontent.com/1165937/39216643-c4a13cde-47d9-11e8-8b65-eda56509fe53.png)

**Comment by khalwat** [comment]
Did you re-create a new SEO Settings field with the same name as an older Seomatic_Meta field? if so, I think it may be this:

https://github.com/craftcms/cms/issues/2800

**Comment by inghamemerson** [comment]
@khalwat digging into it, thanks for the quick reply!

**Comment by inghamemerson** [comment]
Closing, deleting the field and creating a new one seems to have solved the issue, although not without some other core issues popping up. Thank you for the help.

**Comment by khalwat** [comment]
I'm adding some code that will prevent this from happening in the future, if the same field handle is re-used. It will be in the 3.0.3 release.

But this is at least somewhat of a more core Craft 3 issue as well, imo.

**Comment by khalwat** [comment]
Safeguards against this have been put into place in SEOmatic 3.0.3:

https://github.com/nystudio107/craft-seomatic/releases/tag/3.0.3

**Comment by inghamemerson** [comment]
You rock, this is great stuff. Thanks for making the plugin and supporting it so well!
