### ISSUE TITLE
Full site URL is prepended to og:image URL

### ISSUE THREAD

**Issue by pelmered** [nystudio107/craft-seomatic#872]
### Describe the bug
We have site URL with sub directory URLs, for example `example.com/uk`

The generated URL in the `og:image` meta tag includes the `/uk/` part in the image URL which results in a broken link.

The full URL: `https://example.com.test/uk/uploaded/images/articles/image.jpg`

### Expected behaviour
The full URL should be: `https://example.com.test/uploaded/images/articles/image.jpg` (without the `/uk/` part)

I have not done anything weird here and the SEO previews works. 

### Versions
- Plugin version: 3.3.40
- Craft version: 3.6.12

**Comment by khalwat** [comment]
Very likely you are not using fully qualified URLs for your Asset Volumes.

See: 

https://github.com/nystudio107/craft-seomatic/issues/869

&

https://github.com/nystudio107/craft-seomatic/issues/866

Also see:

https://nystudio107.com/blog/multi-environment-configuration-for-craft-cms-3#aliases-in-craft-cms

&

https://craftcms.com/docs/3.x/sites.html#site-url

**Comment by pelmered** [comment]
@khalwat Ah, yes. Thanks! That solved this. 

Sorry. I tried searching before but did not find. It's weird because everything else works great. 

Thank you for the quick response!
