### ISSUE TITLE
Sections with no entries generating empty sub-sitemaps

### ISSUE THREAD

**Issue by jayato3** [nystudio107/craft-seomatic#873]
I have a section for "Event Landing Pages" which currently does not have any entries (because there are no upcoming events). However, there's a link to a sub-sitemap for the section which is empty. Google Search Console reports that it "Couldn't fetch" this sub-sitemap and this is causing concern with our SEO partner. 

Is it possible to prevent sections with no entries from being added to the sitemap index?

**Comment by khalwat** [comment]
Sure, it's reasonable to do this from a completeness point of view.

It will have absolutely zero impact on the crawl-ability of SERP rankings of the site though.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/062a2c97f042987e16fb8984f0a51ee223ce7d08

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.41”,
```
Then do a `composer clear-cache && composer update`
