### ISSUE TITLE
403 error when I try to disable google analytics in tracking scripts

### ISSUE THREAD

**Issue by johnwbaxter** [nystudio107/craft-seomatic#874]
### Describe the bug
My client has added a GA code to the google analytics and I want to disable that as I need to use gtag. When I click to disabled analytics, i get sent to a page that says 403 forbidden.

### To reproduce
Steps to reproduce the behaviour:
1. Go to example.com/admin/seomatic/tracking/googleAnalytics/default
2. Click on the lightswitch field to disable google analytics
3. See error message in screenshot below.

### Expected behaviour
For it to save my setting change

### Screenshots
![2021-04-26_14-51](https://user-images.githubusercontent.com/338729/116093838-ed3a5a00-a69e-11eb-973a-3832e0fed7c1.png)

### Versions
- Plugin version:3.3.40
- Craft version:Craft CMS 3.6.12

**Comment by khalwat** [comment]
Are you saying just clicking on the lightswitch caused that error to appear?

**Comment by khalwat** [comment]
I'm pretty sure this isn't going to end up being an SEOmatic issue, not with a 403 error being thrown (Forbidden isn't something that makes sense to me).

I went to `admin/seomatic/tracking/googleAnalytics/default` and enabled/disabled the setting and saved it without incident.

**Comment by khalwat** [comment]
Any word @johnwbaxter ?

**Comment by johnwbaxter** [comment]
@khalwat Not yet no, the hosts cannot trace the issue. I plan to nuke the vendor folder and reinstall it but haven't had time to do so yet.

**Comment by johnwbaxter** [comment]
@khalwat Well, this is interesting, it's the code in the "Script Template" that is triggering the error
On a whim I took it out and then saved the setting and it worked this time, but the then code block gets re-injected into that settings page, and when you hit save again, it triggers the error
```
{% if trackingId.value is defined and trackingId.value %}
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','{{ analyticsUrl.value }}','ga');
ga('create', '{{ trackingId.value |raw }}', 'auto'{% if linker.value %}, {allowLinker: true}{% endif %});
{% if ipAnonymization.value %}
ga('set', 'anonymizeIp', true);
{% endif %}
{% if displayFeatures.value %}
ga('require', 'displayfeatures');
{% endif %}
{% if ecommerce.value %}
ga('require', 'ecommerce');
{% endif %}
{% if enhancedEcommerce.value %}
ga('require', 'ec');
{% endif %}
{% if enhancedLinkAttribution.value %}
ga('require', 'linkid');
{% endif %}
{% if enhancedLinkAttribution.value %}
ga('require', 'linker');
{% endif %}
{% set pageView = (sendPageView.value and not seomatic.helper.isPreview) %}
{% if pageView %}
ga('send', 'pageview');
{% endif %}
{% endif %}
```
The code block in question

**Comment by johnwbaxter** [comment]
Closing this as its some kind of server side issues not the plugin.
