### ISSUE TITLE
[Potential Bug] - Canonical on paginated pages could be wrong.

### ISSUE THREAD

**Issue by OwenMelbz** [nystudio107/craft-seomatic#875]
Was reading "5 common mistakes with rel=canonical" by Google (albeit from 2013) https://developers.google.com/search/blog/2013/04/5-common-mistakes-with-relcanonical

This seems to suggest you should **not** canonical page 2 back to page 1 - as it's saying that page 2 is the same as page 1, which is wrong, and could lead to lesser indexing of content on other pages.

The following screenshot is from the "**Mistake 1:**" section

![image](https://user-images.githubusercontent.com/1094740/116119338-39dd5f80-a6b6-11eb-9b18-9bb7f84e1266.png)

Checking what SEOmatic generates it does point back to page 1 e.g.

![image](https://user-images.githubusercontent.com/1094740/116119748-a9ebe580-a6b6-11eb-8550-1ac030d461a9.png)

This could be something worth investigating to get clear understanding and action anything if needed.

Any thoughts?

**Comment by khalwat** [comment]
What version of SEOmatic are you using?

**Comment by OwenMelbz** [comment]
This site is on 3.3.38 - but I'm pretty sure this is has been a thing for a while now

**Comment by khalwat** [comment]
Please update to the latest version, there was a change related to this in 3.3.39

https://github.com/nystudio107/craft-seomatic/commit/1cb0718b07828614b93ce4969aab547fdfd8b580

https://github.com/nystudio107/craft-seomatic/blob/v3/CHANGELOG.md#fixed-1

**Comment by khalwat** [comment]
@OwenMelbz ?

**Comment by OwenMelbz** [comment]
Hi, sorry got snowed under :)

We're now running 3.3.40

![image](https://user-images.githubusercontent.com/1094740/116435717-9326c980-a843-11eb-987d-ff5592810a66.png)

However, when we're on /page/2 it's still showing the canonical as per previously shown.

![image](https://user-images.githubusercontent.com/1094740/116435969-d4b77480-a843-11eb-98b7-3f847a454662.png)

**Comment by khalwat** [comment]
that's really interesting, the change I linked to was undone by another commit on the same day... errantly so. Fixed in https://github.com/nystudio107/craft-seomatic/commit/24935fcf2bc4f9cdcb111a7a4529151da1c980bb

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.41”,
```
Then do a `composer clear-cache && composer update`

lmk...

**Comment by khalwat** [comment]
I will re-open this if the above version is deemed not working as expected.

**Comment by mtwalsh** [comment]
@khalwat Hi, I'm noticing this issue across a couple of sites, with SEOmatic versions `4.0.28` and `4.0.30`.

So to recap, the canonical tag on paginated pages beyond the first (2+) points back to the first page URL.

**Comment by khalwat** [comment]
@mtwalsh are you using SEOmatic's `seomatic.helper.paginate(PAGEINFO)` helper? 

https://nystudio107.com/docs/seomatic/using.html#helper-functions-seomatic-helper

If so, please provide more detail on your code, and a link to a live site where I can see the issue.

**Comment by mtwalsh** [comment]
@khalwat No, not using the helper, do have Automatic Render Enabled.

Aha, I've just added the helper and that has sorted it, apologies for taking up some of your time!
