### ISSUE TITLE
Sitemap Generator taking 220s?

### ISSUE THREAD

**Issue by MadMikeyB** [nystudio107/craft-seomatic#877]
### Question

Recently we noticed one of our sites constantly using 80% of 2GB memory_limit. After investigating further through our APM we see that Sitemap Generator is taking 220s to run, causing constant CPU spikes when any sitemap.xml page is loaded.

Does anyone know why this would happen and how we can mitigate this? This is causing constant autoscaling action on our ECS setup causing costs to be incurred.

### Additional context

![Screenshot 2021-04-29 at 17 29 01](https://user-images.githubusercontent.com/831828/116585994-dd29b100-a910-11eb-9a48-3a1eb58054af.png)

**Comment by khalwat** [comment]
Sitemaps are cached, so if it is hitting this every time you load that page, I would look into your caching setup to ensure it's working properly (especially an issue with load balancers), and perhaps using something like Redis for it.

**Comment by khalwat** [comment]
I will re-open this if additional information is provided or help needed.
