### ISSUE TITLE
Matomo settings typo

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#880]
There is a Fathom left over in the Matomo settings:

In the Tracking Scripts settings section under Matomo is the Matomo Script URL input. 

```
The URL to the Fathom tracking script. …
```
I think it should be:

```
The URL to the Matomo instance. …
```

I'm running on: 

- SEOMatic: 3.3.40
- Craft: 3.6.12.1

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/647e2d1bed1b32dfbd96a01950777621a3cd9708

It may not update for the existing install, though.

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.41”,
```
Then do a `composer clear-cache && composer update`
