### ISSUE TITLE
How to set up the hreflang tags properly?

### ISSUE THREAD

**Issue by Stalex89** [nystudio107/craft-seomatic#881]
### Question
I have a question regarding the canonical/alternative/default links setup.
The structure of the website is following:

https://example.com - Default (US)
https://example.com/uk - English (GB)
https://example.com/nl - Dutch (NL)
https://example.com/de - German (DE)
https://example.com/es - Spanish (ES)

So I'm expecting something like this:

```
<link rel="alternate" href="https://example.com" hreflang="x-default" />
<link rel="alternate" href="https://example.com/de" hreflang="de" />
<link rel="alternate" href="https://example.com/nl" hreflang="nl" />
<link rel="alternate" href="https://example.com/uk" hreflang="en-gb" />
<link rel="alternate" href="https://example.com/es" hreflang="es" />
```

However the plugin generates the default site also as an alternative language:

<img width="364" alt="Screenshot 2021-05-03 at 09 22 12" src="https://user-images.githubusercontent.com/23526237/116851033-f9b83880-abf1-11eb-8c7f-6c1c7801b87e.png">

<img width="459" alt="Screenshot 2021-05-03 at 09 22 43" src="https://user-images.githubusercontent.com/23526237/116851141-2ff5b800-abf2-11eb-82e9-1d356f8b624c.png">

<img width="295" alt="Screenshot 2021-05-03 at 09 22 53" src="https://user-images.githubusercontent.com/23526237/116851198-456ae200-abf2-11eb-90a6-a943d26b85f3.png">

Tried to set up tags with the code manually, but the sites becomes unindexable afterwards:

<img width="762" alt="Screenshot 2021-05-03 at 09 36 08" src="https://user-images.githubusercontent.com/23526237/116851634-08531f80-abf3-11eb-86d1-18c664217853.png">

<img width="1291" alt="Screenshot 2021-05-03 at 09 38 02" src="https://user-images.githubusercontent.com/23526237/116851767-50724200-abf3-11eb-8cf7-053f325a48d2.png">

Can you please give me a hint how to turn off the US language as an alternative?  Thank you

Craft version: Craft Pro 3.5.16
SEOmatic version: 3.3.18

**Comment by khalwat** [comment]
This is expected behavior, and I'm pretty sure the correct way to handle the hreflang tags.

The `hreflang="x-default"` is the default page that should be used if no language is specified... and after that, every available translation should be listed (including the page we are currently on).

Ref: https://developers.google.com/search/docs/advanced/crawling/localized-versions#all-method-guidelines

**Comment by Stalex89** [comment]
@khalwat Ok, I see, thank you for the tip.

Can I also ask:
1) how to specify some languages as a region - independent (for example, use 'es' as hreflang value instead of 'es-es'), and leave the 'en-gb' as region - specific at the same time? Is it possible to set up somewhere in the plugin or it is only possible to do manually with the code?
2) Does the order of links generation matter? (default link goes first, all alternate links next, or vice versa)

**Comment by khalwat** [comment]
The ordering of the links does not matter.

As for specifying the language you should be able to do that in the Sites settings in the Craft CMS CP.

**Comment by Stalex89** [comment]
@khalwat ok i seems to work for me, thank you

Can I ask one more question, how does the plugin deal with query strings and pagination ? What should be the proper hreflang and canonical links for the pages ?

Because currently I have an issue of conflicting hreflang and rel=canonical, as well as missing self-referencing hreflang

Example of query strings on my website (including localisation): www.example.com?type=test, www.example.com/de?type=test
Example of pagination on my website: www.example.com/p2 (where p2 is page 2)

**Comment by khalwat** [comment]
@Stalex89 I'm not clear on what the problem is you're experiencing here? Can you show me:

1) What it's doing now

2) What you want it to be doing

**Comment by Stalex89** [comment]
@khalwat sorry for the late response, let me try to explain the issue

**What it is doing now:**
We have a website with multiple languages (default language is EN) with the following url structure:

EN (Default): https://ctouch.eu
DE: https://ctouch.eu/de
ES: https://ctouch.eu/es
UK: https://ctouch.eu/uk
...

We have audited the website for SEO performance and we are having several issues regarding "Conflicting hreflang and rel=canonical" and "Missing self-reference" of urls. We assume that most of the issues are caused by the following:

1) Website uses plugin [GeoMate] (https://plugins.craftcms.com/geomate) for language redirection by user location. 
Plugin GeoMate uses query string '__geom=✪' to detect user's redirection from one language to another ([source](https://github.com/vaersaagod/geomate#redirectoverrideparam-string))

Example of the link: https://ctouch.eu/?__geom=✪
Canonical link: `<link href="https://ctouch.eu" rel="canonical">`
Home link: `<link href="https://ctouch.eu" rel="home">`
Alternative links: 
```
<link href="https://ctouch.eu/de" rel="alternate" hreflang="de">
<link href="https://ctouch.eu/es" rel="alternate" hreflang="es">
...
```

X-default: `<link href="https://ctouch.eu" rel="alternate" hreflang="x-default">`

Screenshot from site audit report:
<img width="1102" alt="Screenshot 2021-06-02 at 11 29 28" src="https://user-images.githubusercontent.com/23526237/120456696-2482e180-c396-11eb-9f05-74f831333209.png">

2) On some pages we are using the standard Craft pagination ([source](https://craftcms.com/docs/3.x/dev/tags.html#paginate)) which appends /p{number} to the url on particular page

Example of the link: https://ctouch.eu/academy/p2
Canonical link: `<link href="https://ctouch.eu/academy" rel="canonical">`
Home link: `<link href="https://ctouch.eu" rel="home">`
Alternative links: 
```
<link href="https://ctouch.eu/de/akademie" rel="alternate" hreflang="de">
<link href="https://ctouch.eu/es/academy" rel="alternate" hreflang="es">
...
```

X-default: `<link href="https://ctouch.eu/academy" rel="alternate" hreflang="x-default">`

Screenshot from site audit report:
<img width="971" alt="Screenshot 2021-06-02 at 11 41 50" src="https://user-images.githubusercontent.com/23526237/120458391-88f27080-c397-11eb-9eed-ce9627d41683.png">

3) Some urls with tokens are detected by crawler:

<img width="1188" alt="Screenshot 2021-06-02 at 11 43 33" src="https://user-images.githubusercontent.com/23526237/120458695-c5be6780-c397-11eb-8c98-2984263c04bc.png">

4) Conflicting occurs when page has query parameters:

Example of the link: https://ctouch.eu/academy?type=video
Canonical link: `<link href="https://ctouch.eu/academy" rel="canonical">`
Home link: `<link href="https://ctouch.eu" rel="home">`
Alternative links: 
```
<link href="https://ctouch.eu/de/akademie" rel="alternate" hreflang="de">
<link href="https://ctouch.eu/es/academy" rel="alternate" hreflang="es">
...
```

X-default: `<link href="https://ctouch.eu/academy" rel="alternate" hreflang="x-default">`

Screenshot from site audit report:
<img width="936" alt="Screenshot 2021-06-02 at 11 57 47" src="https://user-images.githubusercontent.com/23526237/120460849-c5bf6700-c399-11eb-8f0f-d18b3b9a5c96.png">

**What you want it to be doing**
We would like to get rid of hreflang and canonical conflicts to improve the SEO rating.

What I read from [here](https://webmasters.stackexchange.com/questions/110458/how-to-avoid-hreflang-return-errors-with-url-that-contain-parameters), I assume that all the pages that have query string in their urls and are non-canonical (which means this page is visible by Google as a duplicate of canonical link) should not have hreflang link specified (please correct me if I'm wrong, I'm not a specialist in SEO.)

Can you please give a hint how can we achieve it with the SEOmatic plugin ?

Hope that the issue is clear now, please ask me if something is still unclear.
Best regards

**Comment by Stalex89** [comment]
@khalwat Hello, can you please give any hints about how to get rid of hreflang. and canonical conflicts in the plugin?

**Comment by khalwat** [comment]
I will have a look

**Comment by khalwat** [comment]
> We have audited the website for SEO performance and we are having several issues regarding "Conflicting hreflang and rel=canonical" and "Missing self-reference" of urls. We assume that most of the issues are caused by the following:

Okay, this is getting pretty confusing, so let's take these one by one.

First of all, what tool are you relying on here for the auditing?

> 1. Website uses plugin [GeoMate] (https://plugins.craftcms.com/geomate) for language redirection by user location.
>    Plugin GeoMate uses query string '__geom=✪' to detect user's redirection from one language to another ([source](https://github.com/vaersaagod/geomate#redirectoverrideparam-string))
> 
> Example of the link: [https://ctouch.eu/?__geom=✪](https://ctouch.eu/?__geom=%E2%9C%AA)
> Canonical link: `<link href="https://ctouch.eu" rel="canonical">`
> Home link: `<link href="https://ctouch.eu" rel="home">`
> Alternative links:
> 
> ```
> <link href="https://ctouch.eu/de" rel="alternate" hreflang="de">
> <link href="https://ctouch.eu/es" rel="alternate" hreflang="es">
> ...
> ```
> 
> X-default: `<link href="https://ctouch.eu" rel="alternate" hreflang="x-default">`
> 
> Screenshot from site audit report:
> <img alt="Screenshot 2021-06-02 at 11 29 28" width="1102" src="https://user-images.githubusercontent.com/23526237/120456696-2482e180-c396-11eb-9f05-74f831333209.png">

I'm not sure this makes sense to me?

From what you've stated:

Canonical link: `<link href="https://ctouch.eu" rel="canonical">`
X-default: `<link href="https://ctouch.eu" rel="alternate" hreflang="x-default">`

These URLs are identical, yet the report says "Conflicting hreflang and rel-canonical" which is wrong. Then it also says "No self-referencing hreflang, which is wrong as well, there is indeed an `x-default`

Are you saying that all of this is because of the fact that the GeoMate plugin adding a query string?

AFAIK, the query string shouldn't be taken into account by this auditing tool -- so what exactly is the auditing tool? Have you cross-checked it with another auditing tool?

> **What you want it to be doing**
> We would like to get rid of hreflang and canonical conflicts to improve the SEO rating.
> 
> What I read from [here](https://webmasters.stackexchange.com/questions/110458/how-to-avoid-hreflang-return-errors-with-url-that-contain-parameters), I assume that all the pages that have query string in their urls and are non-canonical (which means this page is visible by Google as a duplicate of canonical link) should not have hreflang link specified (please correct me if I'm wrong, I'm not a specialist in SEO.)

This link is talking about errors in Google Search Console -- are you seeing errors in your Google Search Console?

Also this link is talking about something different, where they have a canonical URL that conflicts with the hreflang URL, which your pages do not.

> 
> Can you please give a hint how can we achieve it with the SEOmatic plugin ?
> 
> Hope that the issue is clear now, please ask me if something is still unclear.
> Best regards

Have you tried contacting the people who make your SEO auditing tool to determine what they are expecting these results to be?

From the information provided, I'm not seeing anything wrong.

**Comment by khalwat** [comment]
Will re-open if more information is provided.

**Comment by Stalex89** [comment]
@khalwat Hello, sorry for the long silence, the issue was "solved". 

Google Search Console was showing no errors, but the [Semrush](https://www.semrush.com) (audit tool we're using) was reporting hreflang errors on urls with query parameters.

So the "solution" for us was to do meta links injection manually and only for canonical urls without the query parameters.
[Reference](https://webmasters.stackexchange.com/questions/110458/how-to-avoid-hreflang-return-errors-with-url-that-contain-parameters)

![Screenshot 2021-07-21 at 11 04 29](https://user-images.githubusercontent.com/23526237/126462503-a035762d-dc65-4bc7-91c1-d3af4835c784.png)
![Screenshot 2021-07-21 at 11 04 38](https://user-images.githubusercontent.com/23526237/126462511-6b04eb39-4cd4-4609-ae16-10cb6ab9f69d.png)
![Screenshot 2021-07-21 at 11 05 32](https://user-images.githubusercontent.com/23526237/126462636-3a754e4d-0fd2-4229-beff-bc21b9842e47.png)

Thank you for your help.

**Comment by khalwat** [comment]
If Google Search Console wasn't showing any errors, I would ask Semrush's support what the expected values should be. Something doesn't sound right.

**Comment by GaronRoss** [comment]
@khalwat We having similar issues and wondered if this maybe a bug. The query string parameter is not getting added to the alternate hreflang.

eg. for https://www.murgitroyd.com/insights/design?page=2
the canonical is https://www.murgitroyd.com/insights/design
but the alternate hreflang should be https://www.murgitroyd.com/us/insights/design?page=2
not https://www.murgitroyd.com/us/insights/design

ie. the alternate hreflang is referring to the canonical url which won't necessarily be correct.

Please let us know if we've missed something.
![image](https://github.com/nystudio107/craft-seomatic/assets/151522733/31106969-d2f8-453b-aea5-064280f9c510)

**Comment by khalwat** [comment]
@GaronRoss so hreflang for paginated pages can be tricky. You generally don't want the `hreflang` to point to other paginated pages _unless_ the content is exactly the same for each paginated page (which it usually is not), so the `hreflang` by default points intentionally the first page of the translated paginated pages.

Another option is that you can also choose to omit `hreflang` tags entirely on paginated pages, which is a valid option as well.
