### ISSUE TITLE
500 error - Can't edit entries anymore

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#882]
No idea why, but $assetIds is an array of empty strings, probably because the asset was deleted at some point or due to an old bug, and now some entries have the following error:

TypeError Argument 1 passed to craft\services\Elements::getElementById() must be of the type int, string given, called in /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/nystudio107/craft-seomatic/src/helpers/ImageTransform.php on line 233 
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/services/Elements.php:456 craft\services\Elements::getElementById
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/nystudio107/craft-seomatic/src/helpers/ImageTransform.php:233 nystudio107\seomatic\helpers\ImageTransform::assetElementsFromIds
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/nystudio107/craft-seomatic/src/fields/SeoSettings.php:395 nystudio107\seomatic\fields\SeoSettings::getInputHtml
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php:248 craft\fieldlayoutelements\CustomField::inputHtml
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php:203 craft\fieldlayoutelements\BaseField::formHtml
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php:216 craft\fieldlayoutelements\CustomField::formHtml
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/models/FieldLayout.php:532 craft\models\FieldLayout::createForm
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/twig/twig/src/Extension/CoreExtension.php:1507 twig_get_attribute
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/helpers/Template.php:106 craft\helpers\Template::attribute
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/storage/runtime/compiled_templates/19/1964f3840025d6f763bceff7cf4f0d571a54dc8cf6b5acaf869b923677ad97b8.php:160 __TwigTemplate_a198fb3a5b9b98c7202ff0e8a6df8981f8a0cdc0dee3ae0bce3343024132d547::doDisplay
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/twig/twig/src/Template.php:378 Twig\Template::display
   Not sure why, but we're getting /home/onlyfans/domains/onlyfans.com/releases/20210503141910/storage/runtime/compiled_templates/4f/4fef1973203eb768d46d4c5f6f3c07d4e5439b0a3eb560558996662a5434f55d.php:124 __TwigTemplate_ccdb2da85126dcbe72bbc80f5a084752f1a57fcc1b66b7300f0ac74113ef55a6::doDisplay
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/twig/twig/src/Template.php:390 Twig\Template::render
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/twig/twig/src/TemplateWrapper.php:45 Twig\TemplateWrapper::render
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/twig/twig/src/Environment.php:318 Twig\Environment::render
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/web/View.php:390 craft\web\View::renderTemplate
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/web/View.php:451 craft\web\View::renderPageTemplate
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/web/Controller.php:257 craft\web\Controller::renderTemplate
    /home/onlyfans/domains/onlyfans.com/releases/20210503141910/vendor/craftcms/cms/src/controllers/EntriesController.php:250 craft\controllers\EntriesController::actionEditEntry

**Comment by khalwat** [comment]
What version of SEOmatic are you using?

**Comment by lenvanessen** [comment]
3.3.40

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/65badf07038516b90ae4a68654d2c10e0b1ec579

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.41”,
```
Then do a `composer clear-cache && composer update`
