### ISSUE TITLE
Q: Why do you include Meta Keywords?

### ISSUE THREAD

**Issue by nitech** [nystudio107/craft-seomatic#883]
I understand that Meta Keywords have been abandonned by search engines for a while now. So out of curiosity; why do include Meta Keywords - or at least - why do you indicate that Meta Keywords must be included for a site to be properly SEO optimized?

![image](https://user-images.githubusercontent.com/1279436/116968961-c5a64b80-acb5-11eb-8831-8a87d40129ea.png)

**Comment by khalwat** [comment]
They are abandoned by Google, but still used by Bing, and other search engines. SEOmatic also makes it very simple to set up a mapping to automatically extract the keywords from your content fields, so I think it makes to keep it in there.

**Comment by andreasbecker** [comment]
My client and his SEO agency want to deactivate the keywords meta tag for the whole site? Is this possible?

**Comment by khalwat** [comment]
It is not possible... but there's no downside to including the tag, as long as you aren't stuffing it with spammy-looking keywords. Also, search engines other than Google still use that tag, so I'm not clear on why that advice would be given.

https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag
