### ISSUE TITLE
AssetManager is not configured correctly in console/queue mode

### ISSUE THREAD

**Issue by elivz** [nystudio107/craft-seomatic#885]
### Describe the bug
SEOmatic instantiates your new craft-plugin-manifest package in console mode, in addition to web mode (when creating an entry via a queued task, for example). However, since Craft does not configure Yii's AssetManager component except in [web mode](https://github.com/craftcms/cms/blob/main/src/config/app.web.php), it ends up trying to access AssetManager's default `/assets` basePath, rather than Craft's `/cpresources`, which throws an error: "The directory does not exist: /var/www/html/web/assets"

### To reproduce
Steps to reproduce the behaviour:
1. Add some entries with Content SEO settings. They do not need an SEO custom field.
2. In the terminal, run `./craft resave/entries`
3. Watch your terminal window fill up with red.

### Expected behaviour
Not sure what SEOmatic is using the manifest for in console mode. I would assume it only needs that to render the CP UI, but maybe there is more to it than that. I would guess maybe adding some `if (Craft::$app->getRequest()->getIsCpRequest()) {}` statements in the right places would clear it up?

In the mean time, I have "fixed" it for myself by adding an `app.console.php` config file with just the following contents:

```php
return [
    'components' => [
        'assetManager' => function () {
            $config = craft\helpers\App::assetManagerConfig();
            return Craft::createObject($config);
        },
    ]
];
```

### Versions
- Plugin version: 3.3.40
- Craft version: 3.4.30

**Comment by khalwat** [comment]
huh, interesting. Having a look.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-plugin-manifest/commit/5c507c1946491dca9e94674573e21fb0b635924d & https://github.com/nystudio107/craft-seomatic/commit/fabd8fa5968e650244ebed06a8bc8c87064831de
