### ISSUE TITLE
SEOmatic removes trailing slash from canonical URL when I set it manually

### ISSUE THREAD

**Issue by jwrudzin** [nystudio107/craft-seomatic#887]
I'm manually setting a canonical URL that has a trailing slash using `{% do seomatic.meta.canonicalUrl %}` but SEOmatic is removing the trailing slash in the outputted tag. I have `addTrailingSlashesToUrls` set to false in my config, but I would still expect SEOmatic to keep a slash if I add it manually. Is this intentional or is this a bug?

**Comment by khalwat** [comment]
It's intentional, in that if you have it set to not have trailing slashes, it will remove any tailing slashes. URLs are normalized in a bottleneck function that does this.

What's the use-case here?

**Comment by jwrudzin** [comment]
Okay, I suspected that might be the case.

As for the use-case, we do not use trailing slashes anywhere on our site, and are 301 redirecting trailing slash URLs to their non-trailing slash equivalents. However, our SEO team has recommended that we include a trailing slash in our homepage canonical URL.

Let me know if you have any suggestions for how we can accomplish this!

**Comment by khalwat** [comment]
@jwrudzin that behavior seems inconsistent to me? Do you have any authority documents you can reference so I can learn the appropriate way forward?

**Comment by khalwat** [comment]
Will reopen if more information is provided
