### ISSUE TITLE
Adjustable image count on XML sitemap

### ISSUE THREAD

**Issue by rob-c-baker** [nystudio107/craft-seomatic#888]
### The Problem

I have a requirement for a section of ~6000 entries (which will scale up in due course) to display different numbers of images on an entry "detail" page. There is a specific asset field attached to the entry that has between 1 and ~20 images referenced that I need to pick the first `n` images from. There is a set of criteria to apply to arrive at the number of images shown on any particular entry. I can do that logic in a number of ways on the front end but I can't do that on an XML sitemap. It looks like I can show all of the images or none.

### Possible Solution

A way to modify the query criteria for the XML sitemap, maybe events that receive the entry query and asset query for customisation.

### Alternatives?

I can't see a way of modifying the queries at the moment so it looks like I may be on the road to writing a custom XML sitemap module for this section and adding it as an additional sitemap XML URL to SEOMatic.

**Comment by khalwat** [comment]
I guess my question would be... does it matter? The reason I ask is that all that is happening here is we're providing Google with a number of images that it can index, and may show up in Google Image Search.

Is there a downside to just all of the images being in the sitemap for a given entry here?

Here is where the asset handling is done FWIW:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/jobs/GenerateSitemap.php#L253

It checks any asset fields, as well as any assets embedded in Matrix blocks or other "blocky" fields like Neo, etc.

**Comment by rob-c-baker** [comment]
Having spoken to the stake holders about this again, it does not matter as much as I first understood. There is a preference to only have the images that are actually on the page from the SEO guy but he has said it's not that much of an issue at this point. That may change though.

I had not initially realised all images / videos from all asset fields are included - I think the downside is: the sitemaps are going to be a lot larger and take longer to generate - which I don't think is an issue at this point. I'll deal with it down the line if necessary.

I can see an argument for restricting images in sitemaps if there are license issues, but to be honest, we don't need that right now!
