### ISSUE TITLE
Metadata Caching issues related to Rel="Next" and Rel="Previous" and pagination when using Parameters

### ISSUE THREAD

**Issue by masonry47** [nystudio107/craft-seomatic#890]
Hi there,

We are using  {% do seomatic.helper.paginate(...) %} and it seems that since the dynamic metadata gets cached, the rel="next" link tag just shows whatever is cached which would be the wrong url at times.

So for example if you went to
_https://url.com/resources/_

The "next" link would be 
_<link href="https://url.com/resources/p2/" rel="next">_ which would be correct

Then if you went to "https://url.com/resources/?topic=news"

The next link should be _<link href="https://url.com/resources/p2/?topic=news" rel="next">_

But instead it still shows
_<link href="https://url.com/resources/p2/" rel="next">_

since that is stored in the cache. If you clear the metadata cache, the correct "next" link will show, but then it is cached, which would make the opposite scenario, show the incorrect "next" link.

Thanks for any info!

### Versions
- Plugin version: 3.3.41
- Craft version: 3.5.18

**Comment by khalwat** [comment]
I think the only easy solution I can think of here is to not use URL params for pagination, and rather to use segments (which is the Craft default):

https://craftcms.com/docs/3.x/config/config-settings.html#pagetrigger

Is that workable for you?

**Comment by khalwat** [comment]
In this context, what is `?topic=news` -- are you using this for some kind of category system or the like?

SEOmatic ignores URL query parameters for the cache keys (although it _does_ take pagination into account). So what is `?topic=news` here, and where is it coming from?

**Comment by masonry47** [comment]
Yes it is basically used to just to filter a large library of posts, the query grabs the parameter from the URL to determine which posts to display.  

Thanks for looking into this.

**Comment by khalwat** [comment]
Yeah SEOmatic does _not_ use the query string as part of the cache. This is intentional, because otherwise external request bots could "cache-bomb" you, and bog the server down.

I'd suggest switching to segment-based parameters if you are able, or you can bust the cache on these pages (at the cost of lower performance):

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting

**Comment by masonry47** [comment]
Segment based may be tough because the user can filter by multiple items, so the url could something like `https://url.com/resources/?topic=news&industries=travel`.

I definitely could be wrong, but It does seem that query strings are part of the cache, because we can get urls with parameters to show in the "next" link tag. Like so `<link href="https://url.com/resources/p2/?category=whitePapers" rel="next">`

But at that point when you come back to `https://url.com/resources/` the tag still shows `<link href="https://url.com/resources/p2/?category=whitePapers" rel="next">` when it should show `<link href="https://url.com/resources/p2/" rel="next">`

Is it possible to just exclude the "previous" and "next" tags from the cache?

Thanks!

**Comment by matthewmrotter** [comment]
We're using 

`  {% do seomatic.helper.paginate(pageInfo) %}`

to create our next and prev meta tags. Is there a way to pass a modified version of pageInfo that doesn't contain these params? Something like 

```
{% set pageInfo.prev = pageInfo.prev | replace('&ajax=1', '')  %}
 {% set pageInfo.next = pageInfo.next | replace('&ajax=1', '')  %}   
{% do seomatic.helper.paginate(pageInfo) %}

```

**Comment by khalwat** [comment]
@matthewmrotter SEOmatic uses the URL that Craft CMS says is the URL for that paginated page... so I think that's what it should be set to.

**Comment by khalwat** [comment]
@matthewmrotter check this issue I just closed out: https://github.com/nystudio107/craft-seomatic/issues/896
