### ISSUE TITLE
Fix logic to manage the globalmeta templates

### ISSUE THREAD

**Issue by zizther** [nystudio107/craft-seomatic#891]
Fix logic to manage the globalmeta templates (humans.txt, ads.txt, etc)

For reference:

It actually does the fallback logic here: https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/PluginTemplate.php#L66 but it does it backwards.

It should check for a frontend template first, and then if that doesn't exist, fall back on the built-in one
It is done right here: https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/helpers/PluginTemplate.php#L61

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/e5d617d6034ecbba2e7e613174d730221b046ad5

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.42”,
```
Then do a `composer clear-cache && composer update`
