### ISSUE TITLE
Invalid transform handle: 1200x630__center-center_82_none

### ISSUE THREAD

**Issue by tomkiss** [nystudio107/craft-seomatic#892]
### Describe the bug
I'm seeing some of my SEOmatic social image transforms are unable to generate.
The image is not output, with the images URL saying that the _Image transform cannot be created_. The URL generated is an untransformed URL and "Social Media Preview" also does not show the image.

Checking the `web.log` I can see this:

```
[error][craft\errors\AssetTransformException] craft\errors\AssetTransformException: Invalid transform handle: 1200x630__center-center_82_none in /vendor/craftcms/cms/src/services/AssetTransforms.php:860
Stack trace:
#0 /vendor/craftcms/cms/src/services/AssetTransforms.php(753): craft\services\AssetTransforms->normalizeTransform()
#1 /vendor/craftcms/cms/src/services/AssetTransforms.php(706): craft\services\AssetTransforms->_generateTransform()
#2 /vendor/craftcms/cms/src/controllers/AssetsController.php(1173): craft\services\AssetTransforms->ensureTransformUrlByIndexModel()
#3 [internal function]: craft\controllers\AssetsController->actionGenerateTransform()
#4 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#6 /vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#7 /vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#8 /vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction()
#9 /vendor/craftcms/cms/src/web/Application.php(581): craft\web\Application->runAction()
#10 /vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest()
#11 /vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#12 /web/index.php(22): yii\base\Application->run()
#13 {main}
```

This also occurs for the other transform size, `craft\errors\AssetTransformException: Invalid transform handle: 800x800__center-center_82_none`.

This is **super** weird. I can see other SEOmatic transforms working fine, at that same size - though many are likely cached prior to whatever is causing the issue.

### Things I've tried doing to overcome it:
 - Using different images
 - Downgrading to 3.3.4 (I could go back further but I'm not exactly sure when its started, in that it's seemingly intermittent)

### Versions
- Plugin version: 3.3.41
- Craft version: PRO 3.6.14

**Comment by khalwat** [comment]
So this is _probably_ a bug in Craft CMS, and not in SEOmatic if it is fixed by rolling back to an earlier version of Craft CMS.

From the error log, it looks to me like the transform name `1200x630__center-center_82_none` has something missing after the size, and before the position.

From what I can see, that is the transform type (crop, etc.). Are you using an SEO Settings field here?

**Comment by flynnt** [comment]
I also recently started to see this issue and I did a little digging. Most of what's going on can be isolated to the image transform helper here: `src/helpers/ImageTransform.php` - specifically, starting at line 103. The general idea is that the transform mode will inherit from `base` unless the mode has been overridden at a lower level, like in an SEO Settings field. It seems to be the case that in some circumstances, the mode value for certain entries' Facebook and Twitter images is set, but it's set to nothing, so the mode does get overridden by the local setting, but it ends up as `none`, which is invalid.

I can tell you that in my case, I am dealing with a site that recently got upgraded from Craft 2 to Craft 3. I am able to remedy/workaround the issue by ensuring that my SEO Settings field is set to display the Twitter and Facebook tabs, also ensuring that the SEO Image and mode checkboxes are checked within those tabs, and then setting and saving the mode at that level, which has the effect of updating the value for the mode from something invalid to something valid, like `crop` or whatever.

Hope this helps.

**Comment by tomkiss** [comment]
Aha!
Thank you both, that was super helpful. I first checked the crop setting on SEOmatics Global and Content settings which were all OK; then I enabled the transform mode on the SEOmatic field type... and bingo:

<img width="225" alt="Screenshot 2021-05-13 at 20 03 11" src="https://user-images.githubusercontent.com/183310/118174360-9f577d00-b426-11eb-86cf-71a0372b0809.png">

All of the transform fields across SEO image, Twitter image and Facebook image were coming up as having nothing selected in the dropdown.
Selected crop and everything working again.

Super weird, of course, I've no idea when this occurred but assume an update or something at some point corrupted that value somehow. FWIW this site _was_ Craft 2 but was upgraded over a year ago now.

Anyways, thanks again!

**Comment by flynnt** [comment]
Just following up. I didn't describe the transform correctly. The `none` part isn't completely relevant. For reference, the correct string for the standard social image transform is `_1200x630_crop_center-center_82_none`, whereas a bad one looks like `_1200x630__center-center_82_none`.

For what it's worth, I'm still experiencing this issue, and manually overriding things at the entry level doesn't always seem to fix things. I'm just going to keep debugging.

**Comment by tomkiss** [comment]
Apologies, I may have been a bit hasty in closing the issue!
(I can't undo that).

**Comment by flynnt** [comment]
No problem. I'll keep looking at my situation and may file a new issue.

**Comment by khalwat** [comment]
This is a bug, I will fix it -- there is supposed to be that blank entry in the dropdown. It means "no change" essentially.

**Comment by flynnt** [comment]
@khalwat Awesome, thanks. I've since realized the issue for me is that the incoming SEOmatic v2 data I have has `none` selected across the board for the site meta and social image transforms. When I migrate to v3, I end up with the blank line you mention above for the mode; however, "Transform SEO Image" is defaulted to `true` across the board after the migration, which seems to be how I end up trying to generate images with a transform that has no mode.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/f1b598042ed4acfb629c6357cf13f92ea40447f6
