### ISSUE TITLE
Best way to access SEO image asset from template?

### ISSUE THREAD

**Issue by mgburns** [nystudio107/craft-seomatic#894]
### Question
Is there an easy way to access the SEO image asset when it's pulled from an asset field via Twig or PHP/custom module? We need to add some special handling when an asset is sourced via the [Embedded Assets](https://plugins.craftcms.com/embeddedassets) plugin.

### Additional context
We're using the Embedded Assets plugin to facilitate the use of images from a third party DAM ([Brandfolder](https://brandfolder.com/)). The plugin works by saving a JSON file with external asset metadata, and then [modifying your template to handle rendering of embedded assets via their Twig API](https://github.com/spicywebau/craft-embedded-assets/blob/master/docs/templating.md). This works fine in our templates but doesn't work with the SEO image fields as it returns the URL to the raw JSON file as opposed to the external asset.

Thanks (again!) for your great work on this plugin. :)

**Comment by khalwat** [comment]
Yep, you can access it via Twig:

https://nystudio107.com/docs/seomatic/Using.html#twig-templating

 which you can actually use right in the SEO Image field:

https://nystudio107.com/docs/seomatic/Configuring.html#content-seo-control-panel-fields
