### ISSUE TITLE
robots.txt generates URLs to non-existent sitemaps.

### ISSUE THREAD

**Issue by OwenMelbz** [nystudio107/craft-seomatic#895]
### Describe the bug
When you disable sitemap generation - the robots.txt still outputs the paths to them, which all 404

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Plugin Settings"
2. Disable "Sitemaps enabled"
3. Visit robots.txt

### Expected behaviour
No sitemaps to be outputted.

### Versions
- Plugin version: 3.3.41
- Craft version: Craft Pro 3.6.14

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/c6c7820bd40b40593484b69f95b0cd59a7d6023d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.42”,
```
Then do a `composer clear-cache && composer update`
