### ISSUE TITLE
Pagination helper can get polluted by query strings

### ISSUE THREAD

**Issue by RedLucas** [nystudio107/craft-seomatic#896]
I'm currently using the default URL pagination scheme `/p2`, and I noticed the ability to stuff the pagination link tags using query strings, especially when the pagination links are cached. Meaning that people can put anything as a query string and it not only gets included into the pagination links, but also into the canonical and next/prev links as well when I use the paginate helper. 

I was able to prevent these query strings from being cached by using a clearCache on the link container, but I feel like there's a better option. 

Steps to reproduce the behaviour:
1. Set up a pagination query that implements the default `/p2` pagination scheme. 
2. Wrap the pagination widget in a cache twig tag.
3. Ensure template caching is enabled.
4. `{% paginate craft.entries(blogListQuery) as pageInfo, posts %}
{% do seomatic.helper.paginate(pageInfo) %}
{# See what happens when you don't have this {% do seomatic.link.container().clearCache(true) %} #}`
5. Visit the paginated list with a cold cache, and an inappropriate query string.
6. Visit it again without an inappropriate query string, and click the next paginated page. See that now the next page has query string back. 
7. Even if you handle the issue described for the UI pagination links, the canonical, next and prev links in the head are still always populating by the query strings added in the URL, which I'm not sure is ideal.

### Expected behaviour
I'd like a second parameter to seomatic.helper.paginate() to disallow query strings. Generally, if I'm using the default pagination option, I shouldn't be worried about query strings polluting my links (could this be a CraftCMS bug/feature)

### Versions
- Plugin version: 3.3.41
- Craft version: 3.6.14

**Comment by khalwat** [comment]
So potentially this is a Craft issue, depending on how you look at it. What SEOmatic does is it asks Craft's pagination helper for the URLs:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L117

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L125

So I'm using exactly what Craft CMS thinks these URLs should be.

Now, sure, I can provide some way to sanitize these things -- but I guess I'm not sure if this should be fixed upstream? Thoughts @RedLucas ?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/94a97a222ba088571424d1dfc78f34c893392341

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.42”,
```
Then do a `composer clear-cache && composer update`
