### ISSUE TITLE
Additional Sitemaps show up in all sites in a multisite setup

### ISSUE THREAD

**Issue by tcherokee** [nystudio107/craft-seomatic#897]
### Describe the bug
I am running a multisite setup and if I am trying to create a custom sitemap for a specific site, however, once I create add the custom URLs in the Site Settings > Additional Sitemap URLs section, the custom sitemap ends up showing up across all the various sites.

### Versions
- Plugin version: SEOMatic 3.3.40
- Craft version: Craft Pro 3.6.12.1

**Comment by khalwat** [comment]
Are all of these sites in the same site group?

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/ebbe123558aa15cc19af5fa6caa7b244e409ce91

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.43”,
```
Then do a `composer clear-cache && composer update`

**Comment by tcherokee** [comment]
This worked. Thanks a lot.
