### ISSUE TITLE
Getting category fields for title

### ISSUE THREAD

**Issue by lucosius** [nystudio107/craft-seomatic#898]
Hello there,

I have pages that are archives of entries by category and entry type. My structure looks like this:

Entry <- Archive by entry category and entry type <-Category 

I want to get some fields that are used for the category in the archives but cannot make it work. Any thoughts on how can I do that?

**Comment by khalwat** [comment]
Basically, you just need to figure out how to do this with Twig, then you can put it into your SEOmatic fields.

So... what would it look like in Twig?

**Comment by khalwat** [comment]
Will re-open if more info is provided
