### ISSUE TITLE
 Custom Image for the SEO Image Source on an entry is defaulting to the Global SEO Image Source

### ISSUE THREAD

**Issue by MD1618** [nystudio107/craft-seomatic#899]
### Describe the bug
Using a Custom Image for the SEO Image Source on an entry is defaulting to the Global SEO Image Source.
Not on all entries but a handful with no difference in settings.

### To reproduce
Not sure how you could reproduce.

### Expected behaviour
Using a Custom Image for the SEO Image Source on an entry use that image.

### Versions
- Plugin version: 3.3.41
- Craft version: Craft Pro 3.6.14

**Comment by khalwat** [comment]
Show me what you're setting it to, and how.

Usually when it defaults to the global setting, it's because whatever you have the Twig code set to has an error in it, or results in no image.

**Comment by MD1618** [comment]
I haven't set any TWIG code this is just a dropdown where I select an image asset. It's one entry the rest are fine. Tried different file types and image assets from other blog entries on the same site that are pulling through fine to the SEO preview.

**Comment by khalwat** [comment]
So just _one_ particular image is failing?

**Comment by MD1618** [comment]
The client has now confirmed it on two entries. As in two separate blog entries SEO Image Sources. 
Sorry, I am not sure how to give you more to work with. Really appreciate your quick responses though, many thanks.

**Comment by khalwat** [comment]
So I'm not aware of any issues with SEOmatic and image sources. I'd need to know more information to be able to assist further, unfortunately.

It could also be something with the server setup potentially as well.

**Comment by MD1618** [comment]
OK yeah, it is a possibility that something else is at play. 
Thanks for your time. I will get my tech lead on the case.

**Comment by khalwat** [comment]
lmk if I can help.

**Comment by khalwat** [comment]
@MD1618 is it possible the problem is the same as: https://github.com/nystudio107/craft-seomatic/issues/892

Try updating to the latest?

**Comment by MD1618** [comment]
Ah sweet! Thanks for the heads up I will get it updated today hopefully and
let you know how it goes.

Cheers 👍

**Comment by MD1618** [comment]
Hello,

Deployed the update and it seems to be fixed!

Many thanks for your excellent work. Totally appreciated!

All the best bud.
