### ISSUE TITLE
Can't edit a Category Group with the same handle as a Section

### ISSUE THREAD

**Issue by adampatpattison** [nystudio107/craft-seomatic#90]
I have a Section called Case Studies with the handle `caseStudy`
I also have a Category Group with the handle `caseStudy`

They are both listed in the Content SEO list and have different urls but the latter loads the formers form:
Section: /admin/seomatic/edit-content/general/section/caseStudy/default
Category Group: /admin/seomatic/edit-content/general/categorygroup/caseStudy/default

I will change the handles to be unique as a fix for now but I thought I best raise an issue.

**Comment by khalwat** [comment]
hrm. I actually didn't know that you could have Section and Category handles that are identical, I thought handles needed to be unique across Craft.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/7cf7545a61f8a2e5cfcd3d96d8b6dcf8dc64896d
