### ISSUE TITLE
Block Google News bot

### ISSUE THREAD

**Issue by lucosius** [nystudio107/craft-seomatic#901]
Hey,

I'm just wondering if there's possibility to block Google News bot from all the pages except the articles section? I can see that News taking all the content (including homepage, archives and etc.) but I need them to have only section that goes with articles. Is there's anyway to do it except adding the meta tag to all my template files?

**Comment by khalwat** [comment]
Can you clarify what you mean a bit more here? I'm not sure I understand the problem you're trying to solve. The more detail the better, if you could.

**Comment by khalwat** [comment]
Will re-open if more info is provided
