### ISSUE TITLE
Submit sitemap over 443?

### ISSUE THREAD

**Issue by danielenstrom** [nystudio107/craft-seomatic#903]
### Question
We're getting CURL error (due to firewall settings) when SEOmatic is trying to ping Google/Bing about new sitemaps. 

`2021-05-28 10:22:34 [-][1][-][error][nystudio107\seomatic\services\Sitemaps::submitSitemapForElement] Error submitting sitemap index to: http://www.google.com/webmasters/sitemaps/ping?sitemap=https%3A%2F%2F........... - cURL error 7: Failed to connect to www.google.com port 80: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Is it possible to make the connection via https/443 instead of port 80?

**Comment by khalwat** [comment]
You have port 80 closed on your firewall?

**Comment by danielenstrom** [comment]
Yes, due to some ISO certification thing we're not able to open port 80, and it's since google & bing change ip-addresses often we cannot just add IP tables to the firewall settings.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/eaf6c1f17a7f219f0024394bfa454031cf70ddaa

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.44”,
```
Then do a `composer clear-cache && composer update`
