### ISSUE TITLE
Admin user not authorized to view Social Media preview 

### ISSUE THREAD

**Issue by marionnewlevant** [nystudio107/craft-seomatic#905]
### Describe the bug
HTTP 403 - Forbidden User is not authorized to perform this action - when admin user tries to view Social Media live preview

### To reproduce
Steps to reproduce the behaviour:
1. Edit an entry
2. Pick Preview, and then Social Media Preview
3. HTTP 403 error and stacktrace (I have devmode on)

### Expected behaviour
admin user shouldn't be triggering this error: $this->requireAuthorization(Seomatic::SEOMATIC_PREVIEW_AUTHORIZATION_KEY . $elementId);

### Stacktrace
1. in /craft/vendor/craftcms/cms/src/web/Controller.php line 344
2. in /craft/vendor/nystudio107/craft-seomatic/src/controllers/PreviewController.php line 56
3. etc

### Versions
- Plugin version: 3.3.42
- Craft version: Craft Pro 3.6.15

### Possibly related to?
We are using S3. The SEO images in the source look like:
> <meta content=“https://dev.quorum.embark.pw/actions/assets/generate-transform?transformId=31” property=“og:image”>

and that url gives an error: Image transform cannot be created
and the log file is complaining about S3 errors (possibly related)
```
2021-06-04 13:58:49 [-][-][-][error][Aws\S3\Exception\S3Exception] exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "https://s3.us-west-1.amazonaws.com/quorumnew.images/heroes/_1920xAUTO_crop_center-center_none/Speed_Hero_022417.jpg"; AWS HTTP error: Client error: `PUT https://s3.us-west-1.amazonaws.com/quorumnew.images/heroes/_1920xAUTO_crop_center-center_none/Speed_Hero_022417.jpg` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>Q0G7RZ (truncated...)
 AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>Q0G7RZ31EKHKG9BW</RequestId><HostId>ZeJmpaasKWQ4zGZPPHKDMc45eYcKlK9e7RaHX2xjWqyIKi0+ULGwYNoo0qlIngawqNqsMy5P7pA=</HostId></Error>'
GuzzleHttp\Exception\ClientException: Client error: `PUT https://s3.us-west-1.amazonaws.com/quorumnew.images/heroes/_1920xAUTO_crop_center-center_none/Speed_Hero_022417.jpg` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>Q0G7RZ (truncated...)
 in /home/embark99/staging/quorum/site/releases/0cc5afd26bf6317d08244898e516f15334cbb9be/craft/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
```

**Comment by khalwat** [comment]
So regarding the S3 issue, it looks to me like your bucket permissions are not correct for the S3 bucket you're attempting to access.

Regarding the permissions error, I agree, an admin should never be triggering that error -- but looking at the code, I don't think anything is wrong.

Are we sure something else isn't afoot here?

**Comment by marionnewlevant** [comment]
Something else is most probably afoot. Are the `/actions/assets/generate-transform?transformId=31` urls reasonable? I seem to get them with and without `generateTransformsBeforePageLoad`

**Comment by khalwat** [comment]
Happy to do a screenshare with you to have a look -- ping me.
