### ISSUE TITLE
No address or id for localbusiness entities for content SEO

### ISSUE THREAD

**Issue by accarpenter** [nystudio107/craft-seomatic#910]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.

Semrush is giving me errors for structured data items being invalid because the Local Business structured data type requires an address and an @id and I don't see a way to add those to the content SEO section.  Is there a way around this?

### Additional context
Add any other context or screenshots about the support request here.

![1](https://user-images.githubusercontent.com/41807455/121252544-bd6d9d00-c86d-11eb-866b-3365e3dcf4c9.JPG)

**Comment by khalwat** [comment]
You'd need to add that yourself via Twig or via PHP using the SEOmatic APIs:

https://nystudio107.com/docs/seomatic/using.html#json-ld-meta-object-functions-seomatic-jsonld

There are a bunch of examples here:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

Feel free to ping me if you have any questions on it.

**Comment by accarpenter** [comment]
@khalwat 
`{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}

    {% set addressJsonLd = seomatic.jsonLd.create({
        'type': 'PostalAddress',
        'addressLocality': 'Austin',
        'addressRegion': 'TX',
        'postalCode': '78759',
        'streetAddress': 'Redacted Address',
    }, false) %}

{% do mainEntity.address(addressJsonLd) %}`

Going through the docs I was able to come up with the above, debugging it this does change the mainEntityOfPage if I output it directly to the page, {{ mainEntity }} - but it isn't actually changing the schema for the page.  I am just putting this on the page template.  Where am I supposed to put this so it changes the actual schema and not just the data?

**Comment by khalwat** [comment]
What type is your `mainEntityOfPage`? Is it something that _has_ and `address` property? https://schema.org/docs/full.html

Have you cleared caches (or just run it with `devMode` on)?

**Comment by accarpenter** [comment]
@khalwat Yeah that was it.  I just needed to resave the content seo page and it worked after. 

The mainEntity is RoofingContractor.  Any idea what @id it thinks is missing that is giving the other error?

![1](https://user-images.githubusercontent.com/41807455/121270377-388f7d00-c887-11eb-8b72-805175874f1b.PNG)

**Comment by khalwat** [comment]
What part of the JSON-LD is it claiming the error is on? I know it's the `@id` property, but what object? If it's the `mainEntityOfPage`, SEOmatic should have generated an `@id`

**Comment by accarpenter** [comment]
@khalwat Yes, for the mainEntityOfPage.  If I set it to website then it has the @id but for RoofingContractor it doesn't seem to.   It does for the global identity settings, but not for the mainEntityOfPage.  The audit says the @id is missing from the Local Business structured data type. 


![1](https://user-images.githubusercontent.com/41807455/121272841-94a8d000-c88c-11eb-9229-d025fcdcc9c4.PNG)

**Comment by khalwat** [comment]
Show me the entire `mainEntityOfPage` JSON-LD as text?

**Comment by accarpenter** [comment]
@khalwat 

'<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@graph": [{
            "@type": "RoofingContractor",
            "address": {
                "@type": "PostalAddress",
                "addressLocality": "Austin",
                "addressRegion": "TX",
                "postalCode": "78759",
                "streetAddress": "4413 Spicewood Springs Rd Ste 208A"
            },
            "description": "Orbit Roofing provides quality commercial roofing services in Austin, Texas, San Antonio, Texas, and the surrounding areas. We specialize in asphalt and tile.",
            "image": {
                "@type": "ImageObject",
                "url": "https://www.orbitroofs.com/assets/images/site/_1200x630_crop_center-center_82_none/Opengraph.jpg?mtime=1622919606"
            },
            "mainEntityOfPage": "https://www.orbitroofs.com/commercial-services",
            "name": "Orbit Roofing | Commercial Roofing Services In Austin Texas",
            "url": "https://www.orbitroofs.com/commercial-services"
        }, {
            "@id": "https://www.orbitroofs.com#identity",
            "@type": "RoofingContractor",
            "address": {
                "@type": "PostalAddress",
                "addressCountry": "US",
                "addressLocality": "Austin",
                "addressRegion": "Austin",
                "postalCode": "78759",
                "streetAddress": "4413 Spicewood Springs Rd Ste 208A"
            },
            "alternateName": "Rocket Contracting",
            "contactPoint": [{
                "@type": "ContactPoint",
                "contactType": "customer support",
                "telephone": "844.211.7744"
            }, {
                "@type": "ContactPoint",
                "contactType": "sales",
                "telephone": "844.211.7744"
            }, {
                "@type": "ContactPoint",
                "contactType": "emergency",
                "telephone": "844.211.7744"
            }],
            "description": "We are proud to serve our community with dependable service, solid workmanship, and high quality roofing materials. We specialize in replacing your roof quickly and professionally with minimal disruption to your daily life or business operations. We install premium roofing systems to fit your style and budget, providing maximum protection for your property. We use durable and attractive roofing materials from industry leaders to properly seal your roof and create adequate roof ventilation. We back our work with our own roofing warranties so that you can rest assured that your roof is expertly installed and that we will be there when you need us most.",
            "email": "info@orbitroofs.com",
            "founder": "Eli Champion",
            "foundingDate": "November 1st, 2020",
            "foundingLocation": "San Antonio",
            "geo": {
                "@type": "GeoCoordinates",
                "latitude": "30.374020",
                "longitude": "-97.759220"
            },
            "image": {
                "@type": "ImageObject",
                "height": "60",
                "url": "https://orbitroofs.com/assets/images/site/logo.png",
                "width": "200"
            },
            "logo": {
                "@type": "ImageObject",
                "height": "60",
                "url": "https://www.orbitroofs.com/assets/images/site/_600x60_fit_center-center_82_none/logo.png?mtime=1620509549",
                "width": "200"
            },
            "name": "Orbit Roofing",
            "openingHoursSpecification": [{
                "@type": "OpeningHoursSpecification",
                "closes": "17:00:00",
                "dayOfWeek": ["Monday"],
                "opens": "09:00:00"
            }, {
                "@type": "OpeningHoursSpecification",
                "closes": "17:00:00",
                "dayOfWeek": ["Tuesday"],
                "opens": "09:00:00"
            }, {
                "@type": "OpeningHoursSpecification",
                "closes": "17:00:00",
                "dayOfWeek": ["Wednesday"],
                "opens": "09:00:00"
            }, {
                "@type": "OpeningHoursSpecification",
                "closes": "17:00:00",
                "dayOfWeek": ["Thursday"],
                "opens": "09:00:00"
            }, {
                "@type": "OpeningHoursSpecification",
                "closes": "17:00:00",
                "dayOfWeek": ["Friday"],
                "opens": "09:00:00"
            }],
            "priceRange": "$$$$",
            "sameAs": ["https://www.facebook.com/Orbit-Roofing-112865557518935"],
            "telephone": "844.211.7744",
            "url": "https://www.orbitroofs.com"
        }, {
            "@id": "https://www.geniusesforhire.com#creator",
            "@type": "LocalBusiness",
            "address": {
                "@type": "PostalAddress",
                "addressCountry": "United States",
                "addressLocality": "Odessa",
                "addressRegion": "Texas",
                "postalCode": "79761",
                "streetAddress": "700 N. Grant Suite 104-A"
            },
            "email": "alex@geniusesforhire.com",
            "geo": {
                "@type": "GeoCoordinates",
                "latitude": "31.849670",
                "longitude": "-102.370910"
            },
            "name": "Geniuses For Hire",
            "priceRange": "$",
            "telephone": "18009308597",
            "url": "https://www.geniusesforhire.com"
        }, {
            "@type": "BreadcrumbList",
            "description": "Breadcrumbs list",
            "itemListElement": [{
                "@type": "ListItem",
                "item": "https://www.orbitroofs.com",
                "name": "Home",
                "position": 1
            }, {
                "@type": "ListItem",
                "item": "https://www.orbitroofs.com/commercial-services",
                "name": "Commercial Roofing Services",
                "position": 2
            }],
            "name": "Breadcrumbs"
        }]
    }
</script>'
