### ISSUE TITLE
Using keywords as part of craft site search

### ISSUE THREAD

**Issue by samuelbirch** [nystudio107/craft-seomatic#912]
Is it possible to use the seomatic keywords in a craft site search, so when searching across articles/pages/etc the keywords can be used as a search term?

Is some cases a slang term can be used to reference to a product or technique, which doesn't not necessarily appear as part of the content.

**Comment by khalwat** [comment]
Unfortunately, this isn't possible to do -- the keywords are generated dynamically, and are not saved in the content table.
