### ISSUE TITLE
Add attribute to tracking script tag

### ISSUE THREAD

**Issue by cstoerzer** [nystudio107/craft-seomatic#913]
### Question
I want to use cookiebot for GPDR cookie reasons in EU an therefore I have to add a custom parameter to the script tag:

`<script data-cookieconsent="ignore">`

I can setup anything else in the twig code, but could not figure out, how to get this done as the script tag itself is not part of the template.

Is this somehow possible with SEOmatic?

**Comment by khalwat** [comment]
Yes, you can do this already:

```twig
{% set tag = seomatic.script.get('googleAnalytics') %}
{% if tag | length %}
    {% do tag.tagAttrs({
        "type": "text/plain",
        "data-type": "application/javascript",
        "data-name": "google-analytics",
    }) %}
{% endif %}
```

See: https://nystudio107.com/docs/seomatic/using.html#extra-tag-attributes
