### ISSUE TITLE
Previews not in sync

### ISSUE THREAD

**Issue by iamtompickering** [nystudio107/craft-seomatic#917]
### Describe the bug
The SEO preview that is part of the SEOMatic field is not showing up-to-date data. I can see the latest SEO data has been updated in the preview on the right hand side (under the entry type, slug, postdate etc. field). 

Seems strange that the preview in the field is not showing the latest data?! Any ideas why this might be?

### Versions
- Plugin version: 3.3.16
- Craft version: 3.5.5

**Comment by khalwat** [comment]
Can you please show me a screenshot of this disparity? I'm unclear what you mean here.

**Comment by khalwat** [comment]
Will re-open if more information is provided.
