### ISSUE TITLE
Custom Sitemap has extra whitespaces

### ISSUE THREAD

**Issue by jan-dh** [nystudio107/craft-seomatic#918]
### Describe the bug
When adding a custom sitemap the output contains extra whitespaces before and after the content

### To reproduce
Steps to reproduce the behaviour:
1. Go to "admin/seomatic/site/sitemap/custom-site"
2. Insert some data in "Sitemap URL"
3. Inspect the output and see whitespaces added before and after the string. Same goes for the "Last Modification Date"

### Expected behaviour
No extra whitespaces added

### Versions
- Plugin version: 3.3.8
- Craft version: 3.4.24

**Comment by khalwat** [comment]
Here's what I see for output:

`sitemaps-1-sitemap.xml` ->

```
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="sitemap.xsl"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>http://localhost:8000/sitemaps-1-section-blog-1-sitemap.xml</loc><lastmod>2021-05-27T22:48:49-04:00</lastmod></sitemap><sitemap><loc>http://localhost:8000/sitemaps-1-product-clothing-1-sitemap.xml</loc><lastmod>2021-03-15T11:24:16-04:00</lastmod></sitemap><sitemap><loc>http://localhost:8000/sitemaps-1-section-homepage-1-sitemap.xml</loc><lastmod>2021-03-15T11:40:42-04:00</lastmod></sitemap><sitemap><loc>http://localhost:8000/sitemaps-1-section-sundaes-1-sitemap.xml</loc><lastmod>2021-05-22T18:27:47-04:00</lastmod></sitemap><sitemap><loc>http://localhost:8000/sitemaps-1-global-custom-1-sitemap.xml</loc><lastmod>2021-06-25T20:19:41-04:00</lastmod></sitemap><sitemap><loc>http://woof.com/sitemap.xml</loc><lastmod>2021-06-01T00:00:00-04:00</lastmod></sitemap></sitemapindex>
```

I'm not seeing any extra characters... can you show me exactly what you're seeing with screenshots and/or text?

<img width="1167" alt="Screen Shot 2021-06-25 at 8 21 37 PM" src="https://user-images.githubusercontent.com/7570798/123495924-a4961300-d5f3-11eb-912d-db3ecd8ddcd6.png">

**Comment by jan-dh** [comment]
Was an error on my side, sorry!
