### ISSUE TITLE
siteName override in template is not reflected in seo preview

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#92]
We have a specific section that acts as its own site with a unique site name. Using `{% do seomatic.site.siteName("The Natural") %}` on this sections layout file changes the `siteName` as expected, but these changes aren't reflected in the SEO preview.

Not a huge issue, but may be confusing to the client.

**Comment by khalwat** [comment]
Yeah that's something that unfortunately won't be reflected in the preview, because it can't know what you're doing in any particular template. So if you can do it via the AdminCP settings, that'd be more ideal.
