### ISSUE TITLE
SeoMatic (and Retour) reporting wrong schema version after upgrade

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/craft-seomatic#920]
### Question
We just upgraded both SeoMatic and Retour to the latest version last week, and on local and deploy environments we all get the same error shown below in the image about the wrong schema version being installed. 
We're on the latest version of these two plugins
- "nystudio107/craft-retour": "3.1.54",
- "nystudio107/craft-seomatic": "3.3.43"

We tried clearing the vendor directory and did a clean composer install after a cacheclear but no dice. Ideally we wouldn't want to fiddle with dbs in production and test/stage environments outside of the deploy process.

### Additional context
<img width="1181" alt="Screen Shot 2021-06-29 at 12 12 53 PM" src="https://user-images.githubusercontent.com/39066452/123832539-6fc7db80-d8d3-11eb-8c7a-614c048d1dd3.png">

**Comment by khalwat** [comment]
Related to https://github.com/nystudio107/craft-seomatic/issues/914

**Comment by gbowne-quickbase** [comment]
Thanks! We fixed locally by changing the schema in the `project.yaml` file which allowed us to at least run the `project/config apply`

**Comment by khalwat** [comment]
I believe this is actually a Project Config issue: https://github.com/craftcms/cms/issues/7795#issuecomment-871704218
