### ISSUE TITLE
Site Settings additional sitemaps form saves array of additional sitemaps improperly

### ISSUE THREAD

**Issue by RedLucas** [nystudio107/craft-seomatic#921]
### Describe the bug
If I were to have two additional sitemap URLs, and then delete the 0th index additional sitemap, the saved data in seomatic_metabundles table becomes an associative array. Because the second item becomes the 1th item, it causes this form as well as the site map generator to throw errors.

### To reproduce
Steps to reproduce the behaviour:
1. Go to /admin/seomatic/site/sitemap/en_us
2. Add two "additional sitemaps" and save.
3. Delete the first one.
4. This page should now fail with `yii\base\ErrorException Array to string conversion` and the sitemap generator itself (assuming uncached) will also fail with a similar issue. 

### Expected behaviour
Deleting the first item in the additional sitemaps should not cause any kinds of issues for the sitemap generator or the form itself.

### Screenshots
DB screenshots. 
Issue result:
<img width="656" alt="Screen Shot 2021-07-05 at 3 22 01 PM" src="https://user-images.githubusercontent.com/8796324/124521579-de5ddb00-dda4-11eb-8d0f-6d30a639fa3e.png">
Expected result:
<img width="646" alt="Screen Shot 2021-07-05 at 3 22 11 PM" src="https://user-images.githubusercontent.com/8796324/124521589-e61d7f80-dda4-11eb-8f0f-e97ec96b9e46.png">

### Versions
- Plugin version: SEOmatic | 3.3.43

- Craft version: Craft Pro 3.6.17

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/6fd0a6a6d0f131155c00210eee7f39001d9a0054

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.44”,
```
Then do a `composer clear-cache && composer update`
