### ISSUE TITLE
Title SEO field counter is not considering site name when calculating characters left

### ISSUE THREAD

**Issue by pelmered** [nystudio107/craft-seomatic#922]
There is miss match between the character counter in the SEO title field and the actual truncate title. It seems like the counter is not considering the site name that is added to the title. 

If I set the "Max SEO Title Length" in "Plugin settings" to 70. Then 70 will be used for the counter on the title field even if I have a site name that is 11 characters. The counter should start at 70 - 11 = 59.

If I set the max length to 59 in the settings, the counter will be correct, but then the titles are truncated at 59 - 11 = 48 characters. 

See this screenshot with max set to 70:
<img width="675" alt="Screenshot 2021-07-06 at 11 35 50" src="https://user-images.githubusercontent.com/680058/124595795-c0a27b80-de61-11eb-9e80-0f50e573a966.png">
Here the title is truncated to "This title will be truncated even if it shows it is of…"

I would also like to have the `truncateTitleTags` setting back that you had in SEOmatic 2 to control if you want to set a hard limit on the length or just have the counter be a recommendation. It would be great if this could be set in both the config file and then overridden in the template tags.

**Comment by khalwat** [comment]
Added the config settings you wanted in: Added the config settings you wanted in: https://github.com/nystudio107/craft-seomatic/commit/a465f4a6a38028054a67859a6a0acee28b44dc47

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.44”,
```
Then do a `composer clear-cache && composer update`
