### ISSUE TITLE
Entry type (SEO Image) field changes are affecting other entry types in section

### ISSUE THREAD

**Issue by eva-rose** [nystudio107/craft-seomatic#923]
### Describe the bug
We're experiencing something similar to the bug documented in #794. When modifying the SEO Image Source Field for a single entry type in a section, that field is also changed for all other entry types in that section.

NOTE: This is not happening consistently for us. We made one change which affected all entry types; when we changed a single entry type back, other entry types were not affected. So this may be challenging to reproduce. I was able to reproduce the same thing locally.

### To reproduce
Steps to reproduce the behaviour:
1. Go to SEOmatic > Content SEO > SectionName > Select Entry Type
2. Modify the field value for SEO Image Source Field and save
3. Navigate to another entry type and see that the field value has also changed there
4. Modify the field value for SEO Image Source Field and save
5. Return to the first entry type and see that the field value has not changed

### Expected behaviour
Changes to a field in one entry type should not affect field values for other entry types in that section. 

### Screenshots

`Article v5` entry type - SEO Image field set to `Open Graph Image`
<img width="695" alt="Screen Shot 2021-07-08 at 5 59 14 PM" src="https://user-images.githubusercontent.com/12650164/124996511-0b192900-e017-11eb-8d68-9a1439646742.png">

`Article (Legacy Shell)` entry type - change SEO Image field to `Open Graph Image - Legacy` and save
<img width="696" alt="Screen Shot 2021-07-08 at 5 59 39 PM" src="https://user-images.githubusercontent.com/12650164/124996510-0b192900-e017-11eb-84fc-88a98efcd6bc.png">

`Article v5` entry type - SEO Image field has changed to `Open Graph Image - Legacy`
<img width="688" alt="Screen Shot 2021-07-08 at 5 59 59 PM" src="https://user-images.githubusercontent.com/12650164/124996507-0a809280-e017-11eb-866c-9add2474dd9b.png">

`Article v5` entry type - change SEO Image field to `Open Graph Image` and save
<img width="669" alt="Screen Shot 2021-07-08 at 6 00 51 PM" src="https://user-images.githubusercontent.com/12650164/124996506-0a809280-e017-11eb-8142-63d80ee81a0a.png">

`Article (Legacy Shell)` entry type - SEO Image field is still set to `Open Graph Image - Legacy`
<img width="640" alt="Screen Shot 2021-07-08 at 6 01 10 PM" src="https://user-images.githubusercontent.com/12650164/124996503-09e7fc00-e017-11eb-9dba-3199394d9a80.png">

### Versions
- Plugin version: 3.3.41
- Craft version: 3.6.13

Thanks for your help in figuring this out!

**Comment by khalwat** [comment]
Please update to the latest version of SEOmatic -- I believe it will fix this.

**Comment by eva-rose** [comment]
Thanks, @khalwat! That would be my first inclination -- just thought I'd file this since the listed bugfix in the changelog pre-dated the version we're running. We'll update and I'll get back to you on whether or not it's resolved.
