### ISSUE TITLE
Internal server error due to open_basedir restriction

### ISSUE THREAD

**Issue by sebastian-lenz** [nystudio107/craft-seomatic#924]
### Describe the bug
Our customer is no longer able to open any of the edit pages which contain a SEOMatic input field in the Craft CP, all edit pages respond with an internal server error. When enabling the error reporting, the following error shows up: 

```
is_file(): open_basedir restriction in effect. File(/resources/76b9925f/css/styles.css) is not within the allowed path(s): (/var/www/default/:/tmp/)
in /var/www/default/vendor/nystudio107/craft-plugin-manifest/src/services/ManifestService.php at line 271
```

### To reproduce
Steps to reproduce the behaviour:
1. Set the php config option `open_basedir` to some value
2. Visit any page in the CP with a SEOMatic field

### Expected behaviour
There shouldn't be an error thrown.

### Screenshots
It looks like the call to `is_file` [right here](https://github.com/nystudio107/craft-plugin-manifest/blob/v1/src/services/ManifestService.php#L271) triggers a PHP warning which in production mode halts the entire system. Seems like you are testing something that's supposed to be an URL using `is_file`? If it's just for extra security, maybe we should silence the warnings (`@is_file`) right here.

### Versions
- Plugin version: 3.3.44
- Craft version: Craft Pro 3.6.17

**Comment by khalwat** [comment]
What version of PHP is being used here? I believe this might actually be due to a change in PHP

**Comment by sebastian-lenz** [comment]
The production site runs on PHP 7.4.21. I can replicate the issue on my local machine using the same PHP version.

**Comment by khalwat** [comment]
I'll likely need to do something similar to what I did here: https://github.com/nystudio107/craft-twigpack/issues/73

Very strange that only now this is happening, though.

**Comment by sebastian-lenz** [comment]
Ah, sorry, I did not find that issue, seems to discuss the very same problem though. It's not a misconfiguration on the PHP side, we are on a shared hosting and the basedir is just set to the path the customer files live in. Maybe the behavior of `UrlHelper::isAbsoluteUrl` has changed.

**Comment by khalwat** [comment]
@sebastian-lenz well, what I'm surprised about is that no one has reported this thus far. Which makes me think that the issue actually is misconfiguration, in that probably the site has no `SITE_URL` or `DEFAULT_SITE_URL` or what have you, which is causing it to look for the assets with something like `/cpresources/3563834/seomatic.css` or the like.

It will then first look to see if that exists on disk, which is what is throwing the error. Normally if the site URL was set, this would be a full URL.

**Comment by sebastian-lenz** [comment]
The site is setup using absolute urls, all configures Craft sites return complete urls, the environment variable `DEFAULT_SITE_URL` is also present and set to a complete, valid url starting with a protocol.

After investigating, it seems like you are indirectly relying on the Craft config variable `resourceBaseUrl` being set to an absolute path here:
- https://github.com/nystudio107/craft-plugin-manifest/blob/v1/src/services/ManifestService.php#L128
- https://github.com/nystudio107/craft-plugin-manifest/blob/v1/src/services/ManifestService.php#L133
- https://github.com/nystudio107/craft-plugin-manifest/blob/v1/src/services/ManifestService.php#L258
- https://github.com/nystudio107/craft-plugin-manifest/blob/v1/src/services/ManifestService.php#L263

By updating the config option `resourceBaseUrl` to include a protocol and hostname, the error can be avoided. I still don't understand why you pass a supposed url to `is_file`.

**Comment by khalwat** [comment]
The default value of `resourceBaseUrl` is `@web/cpresources` which should be a correct, full URL if `@web` is specified as such.

The reason it is looking for a file is that either file system paths or URLs can be passed in; for instance, there's no reason to do a HTTP access just to load in a `manifest.json` file.

I do plan to wrap the calls to `is_file()` in a try/catch block as I did in the Twigpack issue I linked to, however.

Using `@isFile()` I don't think will actually suppress thrown exceptions.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-plugin-manifest/releases/tag/1.0.5

You'll need to do a `composer update` to make sure you get the new version of this package, as it is a dependency of SEOmatic, not bundled in SEOmatic itself.

**Comment by sebastian-lenz** [comment]
Thanks for having a look at the issue!
