### ISSUE TITLE
Meta Data from Draft version of entry showing on Published entry

### ISSUE THREAD

**Issue by leesouthwart** [nystudio107/craft-seomatic#925]
When using the Meta field on an entry to set Title / Meta Description, values from a draft version is pulling through to the currently live version of the entry. Unsure if relevant but it is a Parent page in a structure that has 1 child.

To fix this all I had to do was re-save the main, live version of the entry. But regardless it was still something confusing we had to fix.

### To reproduce
Steps to reproduce the behaviour:
1. Create entry with SEOmatic plugin Meta field
2. Fill in some meta title/description
3. Create draft version and change the title/description
4. view page source of live version of the page

### Notes
- Doesnt seem to happen in my local version
- Re-saving the live entry fixed the problem

### Versions
- Plugin version: 3.3.43
- Craft version: 3.6.12 (pro)

**Comment by khalwat** [comment]
If this isn't reproducible locally, I'm thinking there might be something more at play here? Perhaps a caching layer or such?

If you are able to reproduce this locally, please let me know, and I will re-open this issue. I was also unable to reproduce it locally.
