### ISSUE TITLE
How to delete old sitemap links

### ISSUE THREAD

**Issue by marinastep** [nystudio107/craft-seomatic#926]
### Question 
In the generated sitemap we have old links that doesn't exist on the website anymore. We can't even find them in craft admin to disable. these links get 404 code and we receive an alert from Google search console on them 

### Additional context
These links don't exist https://microport.com/sitemaps-1-categorygroup-newsCategories-1-sitemap.xml 
![image](https://user-images.githubusercontent.com/87426487/125628762-61d64c0a-e699-413e-9b2f-cac3a9f8109c.png)

**Comment by khalwat** [comment]
I can see that the Twig template was deleted, but do the categories still exist in the Craft CP?

SEOmatic shouldn't display anything that no longer exists. If you can verify that you can't find them anywhere, can you try clearing your caches?

**Comment by marinastep** [comment]
Yes, these pages don't exist anymore in Craft CP. 
![image](https://user-images.githubusercontent.com/87426487/125641371-83881733-98f8-420c-8c73-425cb64395b8.png)

We run these commands after all our tries to change sitemap
php craft clear-caches/all
php craft gc/run
php craft seomatic/sitemap/generate

**Comment by khalwat** [comment]
Show me a screenshot of your category groups?

It looks like it's actually the category group named `newsCategories`  which you can see listed here:

https://microport.com/sitemaps-1-sitemap.xml

**Comment by marinastep** [comment]
Thanks! Exactly! They were in categories.
