### ISSUE TITLE
[FR] Preparse field not showing in Source Field list when configuring section SEO

### ISSUE THREAD

**Issue by nickdunn** [nystudio107/craft-seomatic#927]
### Describe the bug
I have added a hidden Preparse text field to all five entry types within my section which aims to concatenate several fields together (from a Neo field) to create a good SEO meta description. When I go to configure the SEO for these entry types, the field is not listed.

My redactor is "Page Hero (Introduction)":

<img width="271" alt="Screenshot 2021-07-15 at 22 43 31" src="https://user-images.githubusercontent.com/39560/125861821-40d99f65-7830-4fbd-9432-dc32ad2fe5e1.png">

And it's not listed:

<img width="596" alt="Screenshot 2021-07-15 at 22 44 23" src="https://user-images.githubusercontent.com/39560/125861876-18183d5a-13a8-4cd6-8bf7-bfd5c8f873f3.png">

I also spotted that while the UI allows me to configure the meta fields for each entry type individually, the dropdown list of fields seems to merge together fields from all of the entry types in that section. This also feels like a bug, but may be a deliberate decision for reasons I haven't figured out 

### Expected behaviour
SEOMatic seems to have support for some plugin text fields (RedactorField, NeoField, SuperTableField) so I expected a Preparse field to appear in this list.

Changing the Preparse field's visibility didn't make any difference. I was expecting even "invisible" Preparse to show in this list.

### Versions
- Plugin version: 3.3.43
- Craft version: 3.7.0

**Comment by khalwat** [comment]
SEOmatic definitely supports Redactor fields. I'm betting that the "Rich Text" field in the drop-down list, for instance, is actually a Redactor field.

**Comment by nickdunn** [comment]
Man, I must have been tired last night. Find and replace all mentions of Redactor with Preparse. It's a Preparse field I'm trying to use to concat several values into one. Sorry, my bad.

**Comment by khalwat** [comment]
Aha okay. Sure, that could be supported.

Also keep in mind that you can write Twig code in any of the SEOmatic fields, so you could do the concatenation that way as well.

ref: https://nystudio107.com/docs/seomatic/configuring.html#content-seo-control-panel-fields

**Comment by khalwat** [comment]
Implemented in: https://github.com/nystudio107/craft-seomatic/commit/906d34b830c06d797413fe3d5d64f195039ab818

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.46”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Released as 3.3.46 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.46
