### ISSUE TITLE
Run sitemap URLs through alias function

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-seomatic#928]
I noticed that sitemap URLs can contain raw aliases, like `@web`. Why dont run these URLs throught alias function?

**Comment by khalwat** [comment]
I can't imagine a scenario in which this could happen? Show me exactly what's going on here?

**Comment by khalwat** [comment]
I double-checked, and I don't think SEOmatic is at fault here. It is calling `SiteURL()` on the Element's URI:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/jobs/GenerateSitemap.php#L177

So any alias expansion should already be done.

Will re-open if more information is provided.
