### ISSUE TITLE
Content SEO settings not saving

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-seomatic#93]
@richardcalahan reports:

This is still happening despite running the latest version (3.0.5) including the fix mentioned above. Setting changes in Content SEO are not saving.

Tried clearing cache, uninstalling/reinstalling. Issue persists.

**Comment by khalwat** [comment]
So I'm unable to reproduce this. I tried on an existing install, and I also tried on a new install, and I was able to change the Content SEO settings without issue.

Can you ensure you're running the latest Craft CMS (3.0.4) and the latest SEOmatic (3.0.5)? I realize you stated you were running SEOmatic 3.0.5 but let's double-check everything.

**Comment by khalwat** [comment]
The easiest way to be _sure_ is to just delete all of your `vendor/` directory, and do a `composer update`

**Comment by khalwat** [comment]
The easiest way to be _sure_ is to just delete all of your `vendor/` directory, and do a `composer update`

**Comment by richardcalahan** [comment]
Yes, I'm running Craft CMS 3.0.4 and SEOmatic 3.0.5. Here's a little more info regarding my setup:

On my local machine, the plugin works as expected. On two separate server instances (dev and staging environments) these issues surface. All instances are running Craft Pro as a trial. 

The odd thing is not all settings / sections have this issue. As far as I can tell, only the "Content SEO" section is effected. All other sections on all instances work as expected.

I'm attempting to edit the Content SEO settings for a single entry, specifically the SEO title source.

**Comment by khalwat** [comment]
And you uninstalled the plugin _on the server_ where you're having the problem?

The difference I can think of between the environments is the database; uninstalling it and re-installing it on the server in question would eliminate that.

What other differences are there between environments?

**Comment by richardcalahan** [comment]
Just uninstalled/removed/installed (_on the server_) and same issue occurs.

Also created a new Single and still have the issue.

**Comment by khalwat** [comment]
Can you give me some specs on the server in terms of the PHP version?

Also are you seeing any errors logged in your `web.log`? Potentially enabling `devMode` on the server might give us more information as well.

I'd be happy to take a look at the issue live as well, if that's an option.

**Comment by richardcalahan** [comment]
If you can ping me at richard@madeby.holiday I can forward the site credentials your way.  Thanks for the great support on a Sunday.

**Comment by richardcalahan** [comment]
Also, no not seeing any errors in the web.log. devMode is enabled for both my local and the development server. 

I can confirm that the new values are posted to the server in the web.log, but for some reason they don't persist to the DB (on the development/staging servers)

There's a difference between my local and development setup on the server side:

Local:
PHP Version: 7.2.0
Postgres: 10.1

Development:
PHP Version: 7.2.1
Postgres: 9.6.6

**Comment by khalwat** [comment]
Email sent!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/34829b79b8b83cdfc3b2f814a008aa495965735f
