### ISSUE TITLE
Rich snippets doesn't contain promotional price

### ISSUE THREAD

**Issue by fusiondotweb** [nystudio107/craft-seomatic#930]
### Question
The rich snippets on the product pages shows only the old price and not the new/promo price. That way the products are rejected on shopping ads on Google.

How can we change the price to promo price in the snippets please?

For example this page https://electrovandeput.be/zonnebanken/collasunbanken/infrarood-zonnebank-ir1

We tested the page with: https://search.google.com/test/rich-results

Thnx a lot to help us with this issue.

Kind regards

**Comment by khalwat** [comment]
How is your promo price being set up? How is the product price being sent to SEOmatic?

**Comment by fusiondotweb** [comment]
As Related offers in the product information page

![Schermafbeelding 2021-07-19 om 18 06 35](https://user-images.githubusercontent.com/58050401/126191544-7b2cef6a-9cea-4f7c-8349-ffa9ccfef91e.png)

**Comment by fusiondotweb** [comment]
How is the product price being sent to SEOmatic?
I don't know :/ I have no settings to configure that

**Comment by fusiondotweb** [comment]
![Schermafbeelding 2021-07-19 om 18 08 41](https://user-images.githubusercontent.com/58050401/126191842-8c366154-fec4-4243-81dc-3b32a1d61685.png)

**Comment by khalwat** [comment]
Unfortunately, I don't speak the language shown here in the screenshots -- do you happen to have it available in English as well?

SEOmatic automatically takes the product's price, and uses that for the Product schema. If you want something different, you can do that yourself via Twig as described here:

https://nystudio107.com/docs/seomatic/using.html#json-ld-meta-object-functions-seomatic-jsonld

&

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

**Comment by khalwat** [comment]
This is what is uses for the price by default:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/productmeta/JsonLdContainer.php#L69

**Comment by philipboomy** [comment]
I understand I can set this myself but would it not make sense to use "salePrice" so when running promotions the JSONLD is showing the sales price?

**Comment by philipboomy** [comment]
I understand I can set this myself but would it not make sense to use "salePrice" so when running promotions the JSONLD is showing the sales price?

**Comment by khalwat** [comment]
@philipboomy Can you express to me in Twig what this might look like?

**Comment by philipboomy** [comment]
`'price' => '{{ product.getDefaultVariant().getSalePrice()|number_format(2, ".", "") }}',`

That will output the price (what the customer pays for the product) when product is on sale but also when it's not on sale. So salePrice is like "current price of product" so that is why I thought it might be the correct one to use in the JSONLD.

**Comment by khalwat** [comment]
Sounds great -- what versions of Commerce support this @philipboomy ? I just have to be careful about implementing something that will potentially break on older versions of Commerce.

**Comment by philipboomy** [comment]
I am not 100% sure but I believe it worked since I started using Craft Commerce V2

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/f3fb5ed829f6128863390309b2a8a4ba65e320a6 & https://github.com/nystudio107/craft-seomatic/commit/c296bfa0d63ee442d970c6ba77276bf910ff66d6

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.52”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.23”,
```
Then do a `composer clear-cache && composer update`
