### ISSUE TITLE
Google console warning about missing fields for videoObject

### ISSUE THREAD

**Issue by peteeveleigh** [nystudio107/craft-seomatic#931]
I'm currently investigating a reported issue where videoObject are showing errors in Google Console.
Looks like `uploadDate` and `thumbnailUrl` are both required. However looking at the spec at schema.org for a videoObject it uses `thumbnail`. With `thumbnailUrl` being part of the parent creativeWork object. I'm not sure I'm reading that correctly though.

An example of the problem can be seen here:
Page from site: https://moxitec.com/video/lightbox-studio

Rich text results: https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=message&id=VkRxI3cU45uL67zGYWXDmg

The page contains a Vimeo video and there is being included in the page with Dukt's videos plugin so I'm aware it may not be possible to extract the thumbnail. But should/could this be created from the SEO Image field in SEOMatic?

Really I guess I'm seeking some guidance on how I should set this up.

**Comment by khalwat** [comment]
Well, it sounds like you're already implementing some kind of custom JSON-LD to add the VideoObject via the SEOmatic APIs yes?

If that assumption is correct, then you just need to add those two missing attributes to the JSON-LD. As for where to get the thumbnail from, that's up to you. I'm pretty sure Vimeo has a way to get a thumbnail image, but I'm not sure about Dukt Videos.

Can you give me a bit more guidance on what you want help with here?

**Comment by peteeveleigh** [comment]
Hi Andrew

I’m not doing anything other than using SEOMatic Content SEO and have set the Main Entity of Page to “VideoObject”

But you’re right. I can use the SEOMatic API to add the missing attributes. I’ll crack on and do that. 

I think I was just needing a sanity check with regards to whether those attributes should be getting set by SEOMatic. I didn’t really understand why Google is throwing an error when they aren’t part of the VideoObject specification according to schema.org.

Many thanks
Pete

**Comment by khalwat** [comment]
yep, use the Twig APIs to add the missing attributes in!
