### ISSUE TITLE
check if job is already waiting in the queue

### ISSUE THREAD

**Issue by aloco** [nystudio107/craft-seomatic#932]
### Describe the bug
Not sure if this is a fr or a bug report. We are working with a big site and having around 27.000 news entries. Regenerating the sitemap for those entries takes very long, fair enough there are many entries ... However I am not sure when exactly the regenerate sitemaps for specific entry types is triggered, but I can see them multiple times in the queue for the same entry type. As far as I understand, those jobs are doing the same thing each time. Would it make sense to check if one of those jobs is already in the queue waiting before pushing it another time to the queue? Is there a way to disable the sitemap for a specific entry type?

<img width="836" alt="Screenshot 2021-07-22 at 13 19 15" src="https://user-images.githubusercontent.com/11661125/126636632-06a8b69a-21f5-475a-ba01-8cf0ce890cdc.png">

 
### Versions
- Plugin version: 3.3.44
- Craft version: 3.6.18

**Comment by khalwat** [comment]
It would make sense, but the Yii2 queue currently does not support introspection. Still, we do guard against it: 

https://github.com/nystudio107/craft-seomatic/issues/528

It is possible that what you're seeing above is for multiple sites? If not, it suggests a regression in: https://github.com/nystudio107/craft-seomatic/commit/52130525fa9c39775d485019fb8b53eb87126255

**Comment by aloco** [comment]
Hi,

yes there are two sites. However I found some more news sitemap jobs later in the queue. I also recognized that `queueJobCacheKey` is null. For some other entries like the home single, there is a cache key set

**Comment by khalwat** [comment]
That's very curious -- are you able to determine how that could ever be null? It's set here: https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/SitemapTemplate.php#L135

**Comment by aloco** [comment]
hm I don´t really know .. this is what I get

```
{
    "groupId": 1,
    "type": "section",
    "handle": "news",
    "siteId": 2,
    "queueJobCacheKey": null,
    "description": null
}
```

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/af530cc5da75fb27690255d4d41a4bf1d9c02e0f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.47”,
```
Then do a `composer clear-cache && composer update`
