### ISSUE TITLE
Undefined class constant ‘EVENT_REGISTER_GQL_SCHEMA_COMPONENTS

### ISSUE THREAD

**Issue by Odusanya** [nystudio107/craft-seomatic#933]
### Describe the bug
I run into a `Undefined class constant ‘EVENT_REGISTER_GQL_SCHEMA_COMPONENTS` error while trying to access my CraftCMS Admin dashboard. This error prevents login.

### To reproduce
Steps to reproduce the behaviour:
1. Update to the Craft and SEOmatic version stated below
2. Visit /admin, update the DB. DB updates successfully, then I run into the error message below
3. See error message `Undefined class constant ‘EVENT_REGISTER_GQL_SCHEMA_COMPONENTS`

### Expected behaviour
I should be able to access my admin panel successfully.

### Screenshots
![image](https://user-images.githubusercontent.com/22182946/126993969-bd1913c9-b18f-4440-b4a6-9918bd9332c3.png)

### Versions
- Plugin version: `3.3.22`
- Craft version: `3.4.0.1`

**Comment by khalwat** [comment]
Will fix, thx

**Comment by khalwat** [comment]
Fixed in: https://github.com/nystudio107/craft-seomatic/commit/fd356093f6217b93e7d726e0a9a8c75e8fc408c9

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.46”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
I will release the version today that fixes this issue

**Comment by khalwat** [comment]
Released as 3.3.46 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.46
