### ISSUE TITLE
SEOmatic displaying a generate-transform?transformId= even after turning off all transforms and clearing caches

### ISSUE THREAD

**Issue by brycekirk** [nystudio107/craft-seomatic#935]
### Describe the bug
With transforms on, the SEO preview pane wasn't showing the image, and the meta tags were displaying image paths with `generate-transform?transformId=`. I turned off all transforms and saved the entry (a category in this case). Now the image IS showing in the SEO preview, but the image meta tags are still using `generate-transform?transformId=` paths, even after clearing all caches in the Craft dashboard

### Expected behaviour
After removing transforms and clearing all caches, the image meta tags should be showing the correct image path

### Versions
- Plugin version: 3.3.41
- Craft version: Craft Pro 3.6.14

**Comment by khalwat** [comment]
This is likely going to end up being some kind of an environmental issue. Where are you seeing this happen, why type of server environment?

You may want to set the `generateTransformsBeforePageLoad` option in your `config/general.php` to `true`: https://craftcms.com/docs/3.x/config/config-settings.html#generatetransformsbeforepageload

**Comment by khalwat** [comment]
Also, please update to the latest version of SEOmatic -- the current version is 3.3.46

**Comment by brycekirk** [comment]
Updating seemed to do the trick. Should have tried that first, my bad. Thanks!
