### ISSUE TITLE
[FR] Pinterest tracking script option

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#936]
### Describe the solution you would like
Add an extra option in the tracking script tab for Pinterest analytics

### Describe alternatives you have considered
Add tracking script manually to the template

### Additional context
More info about Pinterest analytics can be found here:

- https://analytics.pinterest.com/
- Docs -> https://help.pinterest.com/en-gb/business/topics/add-tracking

**Comment by khalwat** [comment]
Looks like the base code is here: https://developers.pinterest.com/docs/ad-tools/conversion-tag/?

This is what we'd want to add ya? Something like this:

```html
<head>
  <!-- Pinterest Pixel Base Code --!>
  <script type="text/javascript">
    !function(e){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(
      Array.prototype.slice.call(arguments))};var
      n=window.pintrk;n.queue=[],n.version="3.0";var
      t=document.createElement("script");t.async=!0,t.src=e;var
      r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(t,r)}}("https://s.pinimg.com/ct/core.js");
    pintrk('load', 'YOUR_TAG_ID'​);
    pintrk('page');
  </script>
  <noscript>
    <img height="1" width="1" style="display:none;" alt="" src="https://ct.pinterest.com/v3/?tid=YOUR_TAG_ID&noscript=1" />
  </noscript>
  <!-- End Pinterest Pixel Base Code --!>
</head>
```

**Comment by khalwat** [comment]
Added in: https://github.com/nystudio107/craft-seomatic/commit/adbec977346564c4f2dd181b074419fad3b247b6

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.48”,
```
Then do a `composer clear-cache && composer update`
