### ISSUE TITLE
Option to remove "generator" meta tag in settings

### ISSUE THREAD

**Issue by carolinecblaker** [nystudio107/craft-seomatic#938]
### Is your feature request related to a problem? Please describe.
Alexa flagging "generator" meta tag (with "SEOmatic" value) as insecure meta tag, whatever that is, and client's website Alexa letter grade for Security has fallen to a "B" for this sole factor. Client relies on Alexa to watch website succeed online.

### Describe the solution you would like
Can we have a config item or CP lightswitch to turn the Generator meta tag on and off?

### Describe alternatives you have considered
I've considered figuring out how to remove it from every page manually in the code, but havent' confirmed that it's possible in my own research..

### Additional context
I think it's silly too.

**Comment by khalwat** [comment]
It's already an option, check under SEOmatic -> Plugin Settings -> Tags
