### ISSUE TITLE
Google Product feed: [price] doesn't match with page crawling

### ISSUE THREAD

**Issue by kaspar-allenbach** [nystudio107/craft-seomatic#939]
### Question
I'm not intirely sure this is a plugin issue. But I gotta start somewhere. Just close it if it's the wrong place.

- I've created a [google xml feed](https://kaspar-allenbach.ch/feeds/facebook.xml) for my craft commerce products.
- [Google is now deniyng product's](https://support.google.com/merchants/answer/6098334) who have a variant because It doesn't match the price with the correct variant.
- Google seems to be matching the feed with it's crawling results.
- So this means there must be a markup issue on the website because the feed doesn't throw any errors.
- [This product is denied ](https://kaspar-allenbach.ch/shop/oberland) because there are three variants and the price doesn't match the right variant.

Now is this a problem with the html markup on my side? Or is this a problem with the schema.org markup generated by seomatic?

The way google defines item groups is by assigning a `g:item_group_id` to each variant. I did that in the xml feed. But how to do that in the markup? Is it possible to generate a group ID in the schema.org markup of seomatic?

Thank you ☀️

**Comment by khalwat** [comment]
Probably you'd need to write some custom Twig as per:

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples

...to get the `mainEntityOfPage` for Product pages, and set the price to be what you want it to be. The default is here:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/productmeta/JsonLdContainer.php#L66

The price defaults to:
```twig
{product.getDefaultVariant().getPrice()|number_format(2, ".", "")}
```

If you want it to be something different, you'll need to grab modify the `mainEntityOfPage` as discussed in that article.

Closing, but lmk if you have any issues or questions.

**Comment by kaspar-allenbach** [comment]
I think I got it more or less.

This is how to merge variant offers into the json-ld tag:
(Based on the [FAQ example](https://nystudio107.com/blog/annotated-json-ld-structured-data-examples))

```

{% set variantsArray = [] %}
{% for item in product.variants %}

    {% if item.stock == 0 %}
      {% set itemStock = 'OutOfStock' %}
    {% else %}
      {% set itemStock = 'InStock' %}
    {% endif %}

    {% set variantsArray = variantsArray | merge([seomatic.jsonLd.create({
        'type' : 'Offer',
        'price' : item.price,
        'priceCurrency': 'CHF',
        'sku': item.sku,
        'url': entry.url ~ '?variant=' ~ item.sku,
        'availability': itemStock,
    }, false)]) %}

{% endfor %}

{% if product.variants | length > 1 %}
	{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
        {% do mainEntity.setAttributes({
             'offers' : [variantsArray]
          })
%}

{% endif %}
```

One Question. The parent node still contains `sku`  is it possible somehow to remove the `sku` because only the variants have SKU's not the main entity.

**Comment by khalwat** [comment]
You can just set the SKU to an empty string, and it'll be removed when rendering.
