### ISSUE TITLE
Per page adjustments not sticking

### ISSUE THREAD

**Issue by rjdusk** [nystudio107/craft-seomatic#94]
Hiya,
I have a SEO field setup in my pages for when I want to make [minor adjustments.](https://github.com/nystudio107/craft-seomatic#seomatic-fields) Problem is whenever a change is made and saved, they're not. I thought this might have been a issue similar to #93 , but the issue still appears to happen, even after updating to SEOmatic to 3.0.6.

This is a local dev environment (devmode on).

#### Env
- PHP version: 7.0.26
- MySQL: 5.6.38
- Craft edition & version: Craft Solo 3.0.4

#### Plugins 
- Asset Rev: 6.0.0
- CKEditor: 1.0.0-beta.2
- ImageOptimize: 1.4.31
- Minify: 1.2.8
- Redactor: 1.1.0
- SEO: 3.0.6
- Sprout Encode Email: 2.0.2
- Super Table: 2.0.6
- Typogrify: 1.1.10

Any insights would be fantastic!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/a594aceaded04291406029a7a5fa47d4d48f9ab4

Update to SEOmatic 3.0.8 and you should be good to go. Sorry about that.

**Comment by rjdusk** [comment]
Friggin' beautiful, thanks mate that did the trick!
