### ISSUE TITLE
GraphQL resolver fails for console requests.

### ISSUE THREAD

**Issue by johnnynotsolucky** [nystudio107/craft-seomatic#940]
### Describe the bug

When attempting to warm the graphql cache through a queued job or console command, the seomatic resolver fails with the error:

```
yii\base\UnknownPropertyException^ {#2812
  #message: "Getting unknown property: yii\console\Response::statusCode"
  #code: 0
  #file: "./vendor/yiisoft/yii2/base/Component.php"
  #line: 155
  trace: {
    ./vendor/yiisoft/yii2/base/Component.php:155 { …}
    ./vendor/nystudio107/craft-seomatic/src/models/metatag/RobotsTag.php:88 { …}
    ./vendor/nystudio107/craft-seomatic/src/models/MetaTag.php:201 { …}
    ./vendor/nystudio107/craft-seomatic/src/base/MetaContainer.php:71 { …}
    ./vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php:588 { …}
    ./vendor/nystudio107/craft-seomatic/src/helpers/Container.php:101 { …}
    nystudio107\seomatic\helpers\Container::nystudio107\seomatic\helpers\{closure}() {}
    ...
```

The error originates from both the `RobotsTag` and `CanonicalLink` classes when they attempt to access a web `Response`:

- https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/metatag/RobotsTag.php#L88-L90
- https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/metalink/CanonicalLink.php#L70-L72

### To reproduce

- Execute a gql query as a web request - observe the seomatic property has it's data set
- Execute the same query as a console request - observe the result contains error object and entry data with `seomatic: null`. Example console response:
```
{
    "errors": [
        {
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            }
        }
    ],
    "data": {
        "entries": [
            {
                "id": "2",
                "title": "Test",
                "seomatic": null
            }
        ]
    }
}
```

Example web controller and query:

```php
class GqlController extends \craft\web\Controller
{
    protected $allowAnonymous = true;

    public function actionTest()
    {
        $schema = \craft\helpers\Gql::createFullAccessSchema();

        $query = <<<GQL
query testSeoData(
    \$id: [QueryArgument] = null
) {
    entries(
        id: \$id
    ) {
        id
        title
        seomatic(asArray: true) {
            metaScriptContainer
            metaTitleContainer
            metaJsonLdContainer
            metaTagContainer
            metaLinkContainer
        }
    }
}
GQL;

        $result = Craft::$app->gql->executeQuery(
            $schema,
            $query,
            [],
            null,
            false
        );
        return $this->asJson($result);
    }
}
```

Example console controller:

```php 
class GqlController extends \craft\console\Controller
{
    public function actionTest()
    {
        $schema = \craft\helpers\Gql::createFullAccessSchema();

        $query = <<<GQL
query testSeoData(
    \$id: [QueryArgument] = null
) {
    entries(
        id: \$id
    ) {
        id
        title
        seomatic(asArray: true) {
            metaScriptContainer
            metaTitleContainer
            metaJsonLdContainer
            metaTagContainer
            metaLinkContainer
        }
    }
}
GQL;

        $result = Craft::$app->gql->executeQuery(
            $schema,
            $query,
            [],
            null,
            false
        );

        echo json_encode($result, JSON_PRETTY_PRINT);
    }
}
```

The `Container::getContainerArrays` function uses caching so the cache should be cleared between executing otherwise the error won't always appear.

### Expected behaviour

- SEOmatic resolver resolves with the correct container data for console requests.

### Versions

Tested with 

- Fresh Craft install with only SEOmatic installed
  - Plugin version: 3.3.46
  - Craft version: 3.7.7

and 
- Existing Craft site
  - Plugin version: 3.3.43
  - Craft version: 3.6.16

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/de171dbc715c0d85cb1cc64f8249a57f06f5880b

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.47”,
```
Then do a `composer clear-cache && composer update`

**Comment by johnnynotsolucky** [comment]
Thanks for the quick turnaround @khalwat, this change resolves our issue!
