### ISSUE TITLE
GraphQL error for `seomatic` piggyback

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-seomatic#941]
### Description

I’m getting the following error when using the `seomatic` directive after updating to 3.3.46.

```
Error: Cannot query field "seomatic" on type "EntryInterface".
```

The directive appears as expected in the introspection on `EntryInterface`.

#### Things I’ve tried:
- I’ve cleared the GraphQL, SEOmatic and all other caches
- I’ve tried nesting the directive within different types (e.g. `news_news_Entry`)
- I’ve resaved the section in the SEOmatic CP section and resaved all entries

### Versions
- Plugin version: 3.3.46
- Craft version: Craft Pro 3.7.8

**Comment by khalwat** [comment]
Can you check your GraphQL token permissions to ensure that SEOmatic is enabled?

**Comment by joshuabaker** [comment]
It wasn’t enabled. Issue resolved. Thank you. 👍🏻 

Is that a known migration issue, or something I missed in the release notes?
