### ISSUE TITLE
/* Google Tag Manager script did not render */ 

### ISSUE THREAD

**Issue by chadcrowell** [nystudio107/craft-seomatic#942]
### Question
I have a large site with SEOmatic and I was informed today by the SEO/PPC partner that there is no GTM script loading on the site. It was working fine since the site launched on Craft in April, and had no idea that it had stopped working. All of the settings in the Tracking Scripts section of SEOMatic are correct, it is enabled, the env is Live. When I view the page source, I see this just before the title and other SEOMatic tags:

`<script>/* Google Tag Manager script did not render */</script>`

I can't find any SEOMatic logs in the storage folder, or any other clue as to why GTM stopped working. Where can I look for a clue?

**Comment by khalwat** [comment]
What does the SEOmatic Environment say it is set to on SEOmatic -> Dashboard?

**Comment by chadcrowell** [comment]
Live

https://d.pr/i/cENYL0
https://d.pr/i/FlA73j

—

Chad Crowell
Swish Digital
***@***.***
https://swishdigital.co
541-203-0611

**Comment by khalwat** [comment]
If you're able to replicate this in local dev, we should jump on a conf call and have a look. Something isn't adding up for me.

**Comment by chadcrowell** [comment]
Looks like I can replicate on local. Thursday would be good for me if you can noon or later your time. Let me know what works for you and can can connect on discord

—

Chad Crowell
Swish Digital
***@***.***
https://swishdigital.co
541-203-0611

**Comment by khalwat** [comment]
Thursday works -- you can book a time here: https://savvycal.com/nystudio107/consulting

**Comment by khalwat** [comment]
This ended up being that the Twig code entered in the Body Script field was invalid.

**Comment by khalwat** [comment]
@chadcrowell see: https://github.com/nystudio107/craft-seomatic/issues/944

**Comment by chadcrowell** [comment]
Slick. Thanks much.
