### ISSUE TITLE
Query parameter is stripped from `potentialAction.target` object

### ISSUE THREAD

**Issue by chrismlusk** [nystudio107/craft-seomatic#945]
This is related to [an earlier issue](https://github.com/nystudio107/craft-seomatic/issues/385), but I'm trying to use the whole `EntryPoint` object instead of the shorthand format:

```twig
{# Recommended #}
'potentialAction': {
  'target': {
    'type': 'EntryPoint',
    'urlTemplate': siteUrl ~ 'search?q={keyword}'
  }
}

{# Shorthand #}
'potentialAction': {
  'target': siteUrl ~ 'search?q={keyword}'
}
```

This recommendation is from [Google's Advanced SEO docs](https://developers.google.com/search/docs/advanced/structured-data/sitelinks-searchbox#potential-action-target):

> But [the shorthand format] is non-standard and Google primarily supports it for Microdata simplicity. For best results, include the whole EntryPoint object.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/a2fc8747c1d8bda541b7c1e7d4f2a6754bf6cba3

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.48”,
```
Then do a `composer clear-cache && composer update`
