### ISSUE TITLE
Does not seem possible to augment JSON-LD data for GQL calls

### ISSUE THREAD

**Issue by mildlygeeky** [nystudio107/craft-seomatic#946]
Trying to use a module to add custom JSON-LD data:

```
Event::on(MetaJsonLdContainer::class, Container::EVENT_INCLUDE_CONTAINER, function (IncludeContainerEvent $e) {
    ...
}
```

But it seems this event never actually fires when using a GraphQL call.

Digging around, it seems this is because the various functions that ultimately lead to `prepForInclusion()` are only called on the `View::EVENT_END_PAGE` event.

Possibly related, these events seem to be attached with `EVENT_AFTER_LOAD_PLUGINS`, which I am wondering if gets called on a GQL request (as I was trying to come up with a PR that would add in handling for one of the GQL events, but none seem to be caught in SEOmatic's event attachment section for a GQL call).

**Comment by khalwat** [comment]
The `AddDynamicMetaEvent` is fired regardless -> https://github.com/nystudio107/craft-seomatic/blob/develop/src/services/MetaContainers.php#L217

But correct, `IncludeContainerEvent` is currently not fired unless a template is rendered. I can fix that.

**Comment by khalwat** [comment]
I think the right answer here is for you to use the `AddDynamicMetaEvent` -- I'm not sure I want to fire the `IncludeContainerEvent` on headless requests, because it has a fairly specific meaning.

**Comment by mildlygeeky** [comment]
Interestingly, I don't think that is firing either - the GQL event gets caught for each GQL call, but the Dynamic Meta Event does not:

<img width="1306" alt="Screen Shot 2021-08-15 at 7 43 11 AM" src="https://user-images.githubusercontent.com/273266/129477380-431e3a12-daa9-44b5-9385-d60eaa36cefa.png">

I don't know enough about `$previewingMetaContainers`, but this isn't a preview context.

**Comment by khalwat** [comment]
Will have a look, because it should be firing.

**Comment by khalwat** [comment]
The SEOmatic GQL resolver call chain:

```php
ContainerHelper::getContainerArrays()
Seomatic::$plugin->metaContainers->previewMetaContainers()
Seomatic::$plugin->metaContainers->loadMetaContainers()
```

...and then whether `$previewingMetaContainers` is set or not, it ends up calling:

```php
DynamicMetaHelper::addDynamicMetaToContainers()
```

...can you check to see if any caching is involved, or maybe it's getting to `addDynamicMetaToContainers()` but not firing the event because of the response status code?

```php
    /**
     * Add any custom/dynamic meta to the containers
     *
     * @param string|null $uri     The URI of the route to add dynamic metadata for
     * @param int|null    $siteId  The siteId of the current site
     */
    public static function addDynamicMetaToContainers(string $uri = null, int $siteId = null)
    {
        Craft::beginProfile('DynamicMeta::addDynamicMetaToContainers', __METHOD__);
        $request = Craft::$app->getRequest();
        // Don't add dynamic meta to console requests, they have no concept of a URI or segments
        if (!$request->getIsConsoleRequest()) {
            $response = Craft::$app->getResponse();
            if ($response->statusCode < 400) {
                self::addMetaJsonLdBreadCrumbs($siteId);
                if (Seomatic::$settings->addHrefLang) {
                    self::addMetaLinkHrefLang($uri, $siteId);
                }
                self::addSameAsMeta();
                $metaSiteVars = Seomatic::$plugin->metaContainers->metaSiteVars;
                $jsonLd = Seomatic::$plugin->jsonLd->get('identity');
                if ($jsonLd !== null) {
                    self::addOpeningHours($jsonLd, $metaSiteVars->identity);
                    self::addContactPoints($jsonLd, $metaSiteVars->identity);
                }
                $jsonLd = Seomatic::$plugin->jsonLd->get('creator');
                if ($jsonLd !== null) {
                    self::addOpeningHours($jsonLd, $metaSiteVars->creator);
                    self::addContactPoints($jsonLd, $metaSiteVars->creator);
                }
                // Allow modules/plugins a chance to add dynamic meta
                $event = new AddDynamicMetaEvent([
                    'uri' => $uri,
                    'siteId' => $siteId,
                ]);
                Event::trigger(static::class, self::EVENT_ADD_DYNAMIC_META, $event);
            }
        }
        Craft::endProfile('DynamicMeta::addDynamicMetaToContainers', __METHOD__);
    }
```

**Comment by khalwat** [comment]
I confirmed that `EVENT_ADD_DYNAMIC_META` is indeed triggered via GraphQL requests.

Make sure GraphQL caching isn't in the mix here via the [enableGraphqlCaching](https://craftcms.com/docs/3.x/config/config-settings.html#enablegraphqlcaching) `config/general.php` config setting.
