### ISSUE TITLE
Sitemap indexing entries set to noindex/none until sitemap toggle field is interacted with

### ISSUE THREAD

**Issue by turnstylerj** [nystudio107/craft-seomatic#947]
## Description
We had a client reach out because a handful of pages on their site were set to None/Noindex in the Robots section of the SEO Settings field, but still being added to the sitemap. Could be [this issue](https://github.com/nystudio107/craft-seomatic/issues/712), just filing a new issue with more information per request.

After reading through the previous issue, I tested enabling the "Sitemap" tab in the SEO Settings field and toggling the "Sitemap Enabled" option off for one of the entries. After clearing the cache for "SEOmatic sitemap caches" under Utilities, all of the noindexed entries were removed from the sitemap and now correctly display or hide in the sitemap when the Robots value changes.

## To reproduce
1. Create a structure with entries containing an SEO settings field with only the General tab enabled
2. Create several entries with at least one with the Robots field set to "None" or "Noindex"
3. Check the sitemap

### Expected behavior
The page(s) set to Noindex/None should not be in the sitemap

### Actual behavior
The page(s) set to Noindex/None are in the sitemap

## To fix
Steps to fix this behavior:
1. Enable the "Sitemap" tab for the SEO Settings field
2. Toggle the "Sitemap Enabled" field off for an entry that shouldn't appear in the sitemap
3. Clear the SEOmatic sitemap cache

This removed all entries that shouldn't have appeared in the sitemap, and now the Robots field functions as expected removing entries from the sitemap when they're set to none/noindex, regardless of the value in the Sitemap Enabled toggle.

## Versions
- Plugin version: 3.3.48
- Craft version: 3.7.8

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/5788ad4888aa9784b47e1467954acdaf7ae7bb27

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.0”,
```
Then do a `composer clear-cache && composer update`
