### ISSUE TITLE
Excluding a page from the sitemap is not working and including a broken link.

### ISSUE THREAD

**Issue by LinneaHarts** [nystudio107/craft-seomatic#948]
[XML Sitemap.xml.txt](https://github.com/nystudio107/craft-seomatic/files/6995331/XML.Sitemap.xml.txt)
I have a multi-lingual site with an entry for the 404 page, and even after turning off all the settings for the sitemap on all languages, it is showing up in the sitemap, but the link to sitemaps-1-section-notFoundPage-1-sitemap.xml is broken. 

Attached is the sitemap. Here is a screenshot of the settings on the 404 page.

<img width="1526" alt="Screen Shot 2021-08-16 at 16 50 52" src="https://user-images.githubusercontent.com/25594826/129627969-dc7e057b-a2cf-4022-a994-8825d359cfe5.png">

Craft 3.6.17
SEOmatic 3.3.48

Could be related to this issue: https://github.com/nystudio107/craft-seomatic/issues/712

**Comment by khalwat** [comment]
What is this 404 page? Is it an entry in a section, or a single, or...?

**Comment by khalwat** [comment]
From the sitemap you attached, it appears to me that the 404 page is a single. You should be setting the sitemap settings in Content SEO for the 404 Single, you don't need an SEO Settings field here at all.

I'd suggest turning sitemaps off in Content SEO for this section, and removing the SEO Settings field from the field layout.

**Comment by LinneaHarts** [comment]
Thank you for all the suggestions! I did all of that for all languages, cleared all caches, and re-ran the sitemap creation script, and that page still persists in the sitemap.

Yes, you are right it is a single.
![sitemap settings](https://user-images.githubusercontent.com/25594826/129731346-7fabe01c-794d-4453-b3d4-694f26add67c.png)

**Comment by khalwat** [comment]
What is the "sitemap creation script" that you're running?

Something definitely isn't right here -- perhaps we can do a screen share to have a look?

**Comment by LinneaHarts** [comment]
I'd be happy to do a screen share!

I'm running ./craft seomatic/sitemap/generate to generate the sitemap.

**Comment by khalwat** [comment]
I just did a test where I enabled and disabled the Sitemap on a Single and it worked properly, the sitemap index was no longer listed in the sitemap.xml page

So book a time that works for you for a video conference, some day after today:

https://savvycal.com/nystudio107/chat

**Comment by khalwat** [comment]
This was due to an extra row in the `seomatic_metabundles` table for these Single sections. Once deleted, they were regenerated, and worked fine.

I'll be looking over the db dump from @LinneaHarts to do a post-mortem on what could have gone awry here.
