### ISSUE TITLE
Entries don't refresh when deleted in control panel.

### ISSUE THREAD

**Issue by gixxy22** [nystudio107/craft-seomatic#952]
### Describe the bug
When deleting multiple entries in a section, Craft usually refreshes the page with the entries gone, if seo matic is enabled, this refresh doesnt happen until a manual page refresh.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/6e084e13bc9a2b84f2f7e96ab28b1127b1198aa3

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.1”,
```
Then do a `composer clear-cache && composer update`
