### ISSUE TITLE
SEOmatic error in Craft CMS preview: (Unable to locate message source for category 'image-optimize')

### ISSUE THREAD

**Issue by astuteo** [nystudio107/craft-seomatic#953]
### Describe the bug
Apologies for a poor bug report, but we recently created a new section that is failing to preview in Craft CMS for what appears to be reasons relating to SEOmatic. When opening the preview on production, all we see is the social media related items. When opening on local dev, I get the message: **"Error rendering `_frontend/preview/social-media.twig` -> An exception has been thrown during the rendering of a template ("Unable to locate message source for category 'image-optimize'.")."**

### To reproduce
Unfortunately, I'm not sure how to reproduce. This is only happening for us on a newer section we created within the past few months, so hard to discern what's causing it or how to recreate. Also, FWIW, we are not using (and have never used) your Image Optimize plugin on this project.

### Expected behaviour
A working Craft CMS preview.

### Screenshots
Just the error message above.

### Versions
- Plugin version: 3.4.1
- Craft version: 3.7.10

* Prior to updating, this was also failing on previous Craft CMS 3.6.16 install and SEOmatic v3.3.41

**Comment by khalwat** [comment]
Can you provide me with a full stack trace of the error please?

I just searched the entire SEOmatic codebase for `image-optimize` and came up empty.

**Comment by khalwat** [comment]
To be clear, this happens only when you click on the Preview button with the Social Media target yes?

**Comment by khalwat** [comment]
Fixed in 3.4.2 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.2

**Comment by astuteo** [comment]
Yessir, that was the broader issue that uncovered this one – no preview target set on the section – but any day we can make SEOmatic ever so slightly more robust against one-in-a-million exceptions is a great day! Thank you, Andrew!

**Comment by khalwat** [comment]
This is actually a regression that happened in an attempt to address a completely unrelated issue. Good catch, thank you!
