### ISSUE TITLE
Modification dates for custom sitemap URLs are formatted incorrectly in the human-readable template

### ISSUE THREAD

**Issue by OscarBarrett** [nystudio107/craft-seomatic#955]
### Describe the bug
When adding custom sitemap urls via the `SitemapCustomTemplate::EVENT_REGISTER_SITEMAP_URLS` event, modification dates are not displayed correctly when viewing the human-readable template.

### To reproduce
Steps to reproduce the behaviour:
1. Insert a custom item
```php
Event::on(SitemapCustomTemplate::class, SitemapCustomTemplate::EVENT_REGISTER_SITEMAP_URLS, function(RegisterSitemapUrlsEvent $e) {
    $e->sitemaps[] = [
        'loc' => '/foo',
        'changefreq' => 'always',
        'priority' => '1.0',
        'lastmod' => new DateTime(),
    ];
});
```
2. Navigate to the sitemap in the browser, e.g. `/sitemaps-1-global-custom-1-sitemap.xml`
3. Last Modified is displayed as `202 -08-2`. The value in the actual source is correct (e.g. `2021-08-24T13:57:52+08:00`)

### Expected behaviour
Should be displayed the same as the generated sitemap entries (e.g. `2021-08-24 13:57`).

### Versions
- Plugin version: 3.4.2
- Craft version: 3.7.10

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/1b01b947bb60855db9de46211d52fba79925c7fa

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.3”,
```
Then do a `composer clear-cache && composer update`
