### ISSUE TITLE
Sitemap being noindexed?

### ISSUE THREAD

**Issue by iamtompickering** [nystudio107/craft-seomatic#956]
### Describe the bug

Not sure if this is a bug or not, but an SEO agency has flagged up that the sitemap.xml file is being noindexed. And they have asked to disabled this so it can be indexed. 

Can you offer any insight as to why the sitemap.xml file is being noindexed? Is it possible to turn this off, or should it even be turned off?! 

I've had a look at a couple of articles which suggest it doesn't really matter if it is noindexed purely because it is not classed as a webpage which should be picked up in search engines. But there must be a reason they are requesting for it to be indexed. 

If you can shed any light on this, that would be super helpful!

**Comment by khalwat** [comment]
Yeah the sitemap itself should be set to noindex -- it's not a web page that should be indexed.

I'd be a little leary of that SEO agency tbh. 

ref: https://webmasters.stackexchange.com/questions/122735/why-did-yoast-put-a-no-index-tag-in-my-xml-sitemap
