### ISSUE TITLE
Breadcrumbs top level visible in Google

### ISSUE THREAD

**Issue by WHITE-developer** [nystudio107/craft-seomatic#957]
Breadcrumbs top level [became (sometimes) visible in Google search results](https://www.google.com/search?q=site%3Awhite.nl+plugins).
Not completely sure if it is due to the breadcrumbs as the json data seems fine.
Related issue https://github.com/nystudio107/craft-seomatic/issues/747

- Plugin version: 3.3.40
- Craft version: 3.6.11.2

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d3d0311da54b190013d91eb6d686f144d7f33d4d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by WHITE-developer** [comment]
Thanks! Setting works, only the position of other items now starts at 2. Guess that should become position 1.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/cf6223d075eda3c31cb34c57a629421b876beedc

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by WHITE-developer** [comment]
Yes, looking good, thanks!

One last thing and then everything is covered I hope: on the homepage it now doesn't have any "itemListElement" anymore which makes the rich results tester complain. On the homepage the whole breadcrumbs object can be left out I guess.

(And then hope this fixes the Google indexing problem)

**Comment by khalwat** [comment]
hrm, I thought I handled the case of an empty https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/DynamicMeta.php#L510

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/c9b720ee5d5f8e1f1f64f914662e41fea67dd2e5

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by WHITE-developer** [comment]
That's it :+1:, all fine now, thank you.
