### ISSUE TITLE
 Couldn't save tracking settings due to a Twig error

### ISSUE THREAD

**Issue by rellafella** [nystudio107/craft-seomatic#959]
### Describe the bug
When trying to save my Google Analytics settings I get an error saying " Couldn't save tracking settings due to a Twig error."

### To reproduce
Steps to reproduce the behaviour:
1. Go to "/seomatic/tracking/googleAnalytics/default" from control panel
2. Change a setting and click "save"
3. See error message " Couldn't save tracking settings due to a Twig error."

### Expected behaviour
Settings would be saved

### Screenshots
![CleanShot 2021-08-25 at 11 43 43](https://user-images.githubusercontent.com/36829732/130715279-234d457a-126d-4c51-b2ad-91f6974fa3b0.png)

### Versions
- Plugin version: 3.4.1 (also tried updating to 3.4.2)
- Craft version: 3.7.10 (pro)

**Comment by khalwat** [comment]
Scroll down to the fields where you enter Twig, and see what error it is saying happens in that field

It's trying to tell you that the Twig code entered in those fields is invalid.

**Comment by rellafella** [comment]
Ahh sorry I forgot to mention that part. There is no error in the "Script template" field, it only shows the dropdown at the top of the page.

**Comment by khalwat** [comment]
That's not making sense to me, the error is associated with field validation.

Check your `web.log` for the error, and post it here.

**Comment by rellafella** [comment]
It doesn't seem to be logging anything in my `web.log` but here's a video of what is happening.
https://cln.sh/aWVc1f

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d2d21f4beae5506086692a63a0db0f3173d597cd

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by rellafella** [comment]
That's done the trick! Thanks for the Quick fix! 🎉
