### ISSUE TITLE
TypeError on draft entry live preview

### ISSUE THREAD

**Issue by d--j** [nystudio107/craft-seomatic#961]
### Describe the bug
This is a follow-up of #958. The live preview of a draft entry does not work, when you have a SEO Field without overwrite in the draft.

### To reproduce
Steps to reproduce the behaviour:
1. A CraftCMS installation with two languages. SEOMatic with `addHrefLang` setting of `true`
2. A Section with a SEO Field with setting `sitemapEnabledFields` that includes `sitemapUrls`. Default value for "Sitemap Enabled" for this section is enabled.
3. Create a new draft entry, switch to Live Preview

### Expected behaviour
See a live preview

### Screenshots
![🚧⚙_Neuen_Eintrag-Typ_erstellen__Erster_Entwurf__-_elevaide](https://user-images.githubusercontent.com/100674/130983724-37b094dd-03fd-425f-8848-d7ae75474c54.png)

### Versions
- Plugin version: 3.4.3 (dev)
- Craft version: 3.7.10
- PHP version: 8

### Possible fix

change [isInherited](https://github.com/nystudio107/craft-seomatic/blob/fc7a90239e63048363643eef7c481bd3ac7ce1c6/src/services/Helper.php#L551-L552)
```diff
-        $explicitInherit = array_key_exists($settingName, $settingCollection->inherited);
-        $explicitOverride = array_key_exists($settingName, $settingCollection->overrides);
+        $explicitInherit = array_key_exists($settingName, (array)$settingCollection->inherited);
+        $explicitOverride = array_key_exists($settingName, (array)$settingCollection->overrides);
```

**Comment by khalwat** [comment]
hrm I'm not sure just typecasting this to an array will do it. I will have a look.

**Comment by d--j** [comment]
> hrm I'm not sure just typecasting this to an array will do it. I will have a look.

gets rid of this TypeError – I don't know if it has unintended side-effects, tho.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/33f0708d88c77bfc19f7b9a0c9b756d9997c6066

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.4”,
```
Then do a `composer clear-cache && composer update`
