### ISSUE TITLE
Override lightswitch preventing sitemap inclusion for elements with newly added SEO Settings field

### ISSUE THREAD

**Issue by jmauzyk** [nystudio107/craft-seomatic#964]
### Describe the bug
It looks like the addition of Override lightswitches for SEO Settings fields is preventing element URLs from being included in sitemaps in situations where a SEO Settings field is added to a section that previously did not have one. SEOmatic successfully generates sitemap URLs for the section according to the content settings at first, but once the SEO Settings field is added to the section, the sitemap returns 0 URLs. Clearing the cache, regenerating the sitemap, resaving via console, or resaving in the CP have no effect. In order to get the element URL to be added back to the sitemap, you have to first enable the sitemap override for the element and save, then disable the override and save again. After this it will successfully list the URL in that section's sitemap.

### To reproduce
Steps to reproduce the behaviour:
1. Find a section that does not have SEO Settings field and does have a sitemap enabled in SEOmatic.
2. Examine the sitemap for that section. It should successfully list the element URLs.
3. Add a SEO Settings field to the section and save.
4. Reload and examine the sitemap. It should now show 0 URLs.

### Versions
- Plugin version: 3.4.4
- Craft version: 3.7.0

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/bc518dd6d6a21ca3edc8e04dbf44447bf6348eb0

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.5”,
```
Then do a `composer clear-cache && composer update`
