### ISSUE TITLE
3.4.5 - Can't select images

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#965]
### Describe the bug
Since we updated to 3.4.x, we can't select images anymore for the SEO image source, or Image Source. You select "override" and then hit "select SEO image", but nothing happens. The modal stays away. It only works for entries are made in the same group as our primary site. For sites that are not in the same group, the event listeners are not attached.

As you can see in the screenshots below the event listeners is not added to the button, hence it does nothing. The screenshot where you see the  "Event" are from articles made on the primary site, or in the same group as the primary site.

Not 100% sure the primary site is related, but that's what we've seen ad common demoninator so far.

![Schermafbeelding 2021-08-30 om 15 52 53](https://user-images.githubusercontent.com/23024452/131350507-e396be6f-8b00-46ee-a569-06c78d43dcd4.png)
![Schermafbeelding 2021-08-30 om 15 54 53](https://user-images.githubusercontent.com/23024452/131350486-5b59f211-fa17-4a79-b772-274ee478c4f2.png)

### Versions
- Plugin version: 3.4.5
- Craft version: 3.7.10

**Comment by lenvanessen** [comment]
Same problem with removing and image preview, works on all sites, just the site that's outside of the group where the primary site lives:
![Schermafbeelding 2021-08-30 om 16 12 06](https://user-images.githubusercontent.com/23024452/131352930-feeec6da-1d83-4477-a943-2a1f5acceb32.png)

**Comment by khalwat** [comment]
Are you able to roll-back to pre-SEOmatic 3.4.x to ensure that it works there, and is not somehow related to a Craft update?

I ask because we're having difficulty replicating this issue here.

**Comment by khalwat** [comment]
Are there any JavaScript errors in your console?

Do you see anything asset-related not working elsewhere, or is it only in SEOmatic?

**Comment by lenvanessen** [comment]
@khalwat only on SEOmatic, no JS errors unfortunately.
I'll check about the rollback, report back in a couple of minutes

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/4ae6d05644f90f2eb7b1f1d41acb3d59ac84eb72

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.6”,
```
Then do a `composer clear-cache && composer update`
