### ISSUE TITLE
Seo Title Source: "From Title" fetches wrong Title

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#966]
### Describe the bug
I'm trying to trace this into the code a bit further to give a try and give a bit more insight into what's going on here. But in our installation, setting the SEO Title Source to "from Title field" will return a different title, in our case, it usuallly rotates two or three different titles to choose from, none of them the actual title of the entry.

You can see in the screenshot: 
Entry Title: Valorant Artisan Skin Collection
SEO title: Die Top 10 der bestwerteten Spier in FIFA 20 | EarlyGame

![Schermafbeelding 2021-09-03 om 10 14 11](https://user-images.githubusercontent.com/23024452/131974390-397f78e4-77b4-4b7c-ae62-90f8d8263ff2.png)

It's not just the preview, the actual SEO title is set to this value as well.

### To reproduce
Steps to reproduce the behaviour:
1. Create a new entry
2. Set SEO title field to "title"
3. Save

### Versions
- Plugin version: 3.4.6
- Craft version: 3.7.11

**Comment by khalwat** [comment]
I'm assuming this is a multi-site setup. Is there any rhyme or reason to the what titles is chosen? Are they different titles for the same entry (from different sites) or just randomly different titles?

**Comment by lenvanessen** [comment]
Yes, it's a multi-site set-up. The entries are not propagated to the different sites though. no rhyme or reasons, they are from the same site, and usually from the same 3 entries.

**Comment by khalwat** [comment]
So Content SEO pulls from the title, and the SEO Settings field is set to not override. Got it

**Comment by khalwat** [comment]
I'm unable to reproduce this by going to a section, and creating multiple new entries in that section. They are all named as expected.

How are the titles for your articles determined for this section? Just a title field where people enter text?

Is there any Twig code that could be altering things in SEOmatic?

Something isn't adding up here...

**Comment by khalwat** [comment]
This ended up being hard-coded Twig code that was entered into the Content SEO settings.
