### ISSUE TITLE
Breadcrumb bug on localized sites

### ISSUE THREAD

**Issue by AlexFUNBIT** [nystudio107/craft-seomatic#967]
**Related issue:**
https://github.com/nystudio107/seomatic/issues/267

This bug is persistent on section types: Structure + Channel.  (Singles work fine)
`index_page` URLs are always missing from JSON output.

**Any help or workaround are appreciated.** 🥇 

## SEOmatic Version: 3.4.6

![image](https://user-images.githubusercontent.com/10828933/131991713-9263099c-daa3-4eb5-bd61-92708b19eaa5.png)

## Section type: Structure

![image](https://user-images.githubusercontent.com/10828933/131990928-fdaf1ed3-ce36-4c02-8f2c-e64e76f87c3f.png)
_Screenshot: Section settings. Localized URLs_

![image](https://user-images.githubusercontent.com/10828933/131994230-0af3fef0-89e4-4196-adfe-55faf1ace831.png)

**JSON output**

```json
{
  "@type": "BreadcrumbList",
  "description": "Breadcrumbs list",
  "itemListElement": [{
      "@type": "ListItem",
      "item": "https://wopas.funbit.dev",
      "name": "Home",
      "position": 1
    },
    {
      "@type": "ListItem",
      "item": "https://wopas.funbit.dev/products/power-poles",
      "name": "Power poles",
      "position": 2
    },
    {
      "@type": "ListItem",
      "item": "https://wopas.funbit.dev/products/power-poles/poles",
      "name": "Poles",
      "position": 3
    }
  ],
  "name": "Breadcrumbs"
}

```

> Comment:
> JSON output are missing `product_index` page URL
> https://wopas.funbit.dev/products

## Section type: Channel

![image](https://user-images.githubusercontent.com/10828933/131991254-ce0c0d21-05ed-45a6-95e3-9ab353adb83a.png)
_Screenshot: Section settings. Localized URLs_

![image](https://user-images.githubusercontent.com/10828933/131994460-a8b29562-b170-4498-81a8-9063cb28fa80.png)

**JSON output**

```json
{
  "@type": "BreadcrumbList",
  "description": "Breadcrumbs list",
  "itemListElement": [{
      "@type": "ListItem",
      "item": "https://wopas.funbit.dev",
      "name": "Home",
      "position": 1
    },
    {
      "@type": "ListItem",
      "item": "https://wopas.funbit.dev/references/reference-demo",
      "name": "Reference demo",
      "position": 2
    }
  ],
  "name": "Breadcrumbs"
}
```

> Comment
> JSON output are missing `references_index` page URL.
> https://wopas.funbit.dev/references

**Comment by AlexFUNBIT** [comment]
I found a workaround by creating a single (Craft Admin) for the `index_page`.

**Maybe you are supposed to do that?**

> But often I just create template logic for the index_page in the source code, 
> not adding the section to Craft admin, at all. Is this wrong practice?

**Comment by khalwat** [comment]
If the index page isn't in the CMS, SEOmatic has no way of knowing it exists. So creating a Single is the right thing to do if you want SEOmatic to automatically handle it.

If you don't, then you can set the breadcrumbs yourself manually.
