### ISSUE TITLE
Alternate Links missing in GraphQL `metaLinkContainer` field

### ISSUE THREAD

**Issue by denisyilmaz** [nystudio107/craft-seomatic#969]
### Describe the bug
The `metaLinkContainer` field does not contain the `x-default` and `alternate` links of the queried entries. The queries shown here are only examples, i tried using `uri`/`id` and all other options, but the fields are emtpy.
```gql
{
  entry(uri:"example-uri", site:"english") {
    id
    siteId
    url
    title
    canonicalId
    seomatic(asArray:true) {
      metaLinkContainer
    }
  }
  languageSwitch: seomatic(uri:"suche", asArray:true, siteId:3) {
      metaLinkContainer
    }
}
```
does not show alternating urls in the `metaLinkContainer` field but these (we have two languages/sites active):
```json
"seomatic": {
        "metaLinkContainer": "{\"canonical\":{\"href\":\"https://example.test:8443/en/example-uri\",\"rel\":\"canonical\"},\"home\":{\"href\":\"https://example.test:8443/en\",\"rel\":\"home\"},\"author\":{\"href\":\"https://example.test:8443/humans.txt\",\"rel\":\"author\",\"type\":\"text/plain\"},\"publisher\":[]}"
      }
```

Settings are unchanged from the `config.php`. Renamed and copied into `config/seomatic.php`. So the rendering of alternate links is active.

The alternate links are _not_ rendered either with `asArray` set to `true`/`false`.

### To reproduce
Steps to reproduce the behaviour:
1. Install SEOmatic
2. Copy `config.php` to `config/seomatic.php`
3. Activate SEOmatic in public GraphQL schema (dont know if this is necessary)
4. Open GraphQL Explorer any query for entries with the `seomatic` field (as shown above)

### Expected behaviour
Alternate Links and the `x-default` link should be rendered to the `metaLinkContainer` field.

### Screenshots
Sites:
![image](https://user-images.githubusercontent.com/4189607/132307986-7ffadc22-534f-4a88-8120-e70a4044bea4.png)

Settings Page:
![image](https://user-images.githubusercontent.com/4189607/132308072-abf29cad-16b3-446f-886e-4a9e7b315e6c.png)

### Versions
- Plugin version: 3.4.6
- Craft version: 3.7.11

**Comment by khalwat** [comment]
I'm unable to replicate this @denisyilmaz -- is there more information you could provide that might assist?

**Comment by denisyilmaz** [comment]
Hm, thats strange. i will try to add as many info about the project as possible here.

One thing i found out is that non existing URI are rendering the alternate object but existing URI do not.

## URI does not exist

### Query
```gql
{
  languageSwitch: seomatic(uri:"false-uri", asArray:true) {
    metaLinkContainer
  }
}
```
### Response (partial)
```
{
   "alternate":[
      {
         "href":"https://example.test:8443/en/false-uri",
         "hreflang":"en",
         "rel":"alternate"
      },
      {
         "href":"https://example.test:8443/false-uri",
         "hreflang":"x-default",
         "rel":"alternate"
      },
      {
         "href":"https://example.test:8443/false-uri",
         "hreflang":"de",
         "rel":"alternate"
      }
   ]
}
```

… whereas all existing URI are not working

# Additional Information
- local Setup is done via Docker (project is in dev currently)
- for this particular project we have a try-licence
- Plugin is installed without any pre-existing config for it.

# Application Info
- PHP version	7.4.23
- OS version	Linux 5.10.25-linuxkit
- Database driver & version	MySQL 5.5.5
- Image driver & version	Imagick 3.4.3 (ImageMagick 6.9.11-60)
- Craft edition & version	Craft Pro 3.7.11
- Yii version	2.0.43
- Twig version	v2.14.6
- Guzzle version	7.3.0

# Plugin Info
- Calendar	3.3.3
- Embedded Assets	2.8.0
- Entries Subset	1.2.3
- Imager X	v3.5.2
- Maps	3.9.2
- Neo	2.11.9
- Redactor	2.8.8
- Related Entry Types	v0.3.2
- Scout	2.4.2
- SEOmatic	3.4.6

**Comment by khalwat** [comment]
Does this still happen if the entry-related plugins like Related Entry Types or Entries Subset are disabled?

**Comment by denisyilmaz** [comment]
i disabled all plugins, our custom module, re-applied the project-config and cleared all caches/data-caches, resaved an entry and tried again. nothing. same behavior. no error logs.

i also checked on our staging-server, where we dont use docker and this is not working as well.

**Comment by khalwat** [comment]
I have tried for a few hours today to find a way to reproduce this, but I've been unable to unless:

- The sitemaps or Robots are turned off for the given section in Content SEO
- The sitemaps or Robots are turned off via an SEO Settings field

I think we might need to do a screen share at some point to see what is going on:

https://savvycal.com/nystudio107/chat

**Comment by khalwat** [comment]
Will re-open if additional information is presented. Feel free to schedule a time to screen share:

https://savvycal.com/nystudio107/chat
