### ISSUE TITLE
Users can't access Social Media in Site Settings with proper permissions

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#97]
This is what my users' permissions looks like.

![screen shot 2018-05-02 at 10 54 34 am](https://user-images.githubusercontent.com/1007191/39541106-9290ebc4-4df9-11e8-8f08-963fe1aed39b.png)

Tested creating a new user after updating permissions. Still no access.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/71e3f7cb3107aa5fb62c64214b4f28894be2784b

Also did a global search to ensure I found all instances :)
