### ISSUE TITLE
Seo column on entry page shows on every entry the content of the first entry on the page

### ISSUE THREAD

**Issue by NickLanger1990** [nystudio107/craft-seomatic#970]
### Describe the bug
Seo column on entry page shows on every entry the content of the first entry on the page.

### To reproduce
- create two new entries
- clear cache
- check if the seo content in the column is on every entry the same as on the first one.

### Expected behaviour
content should be the same as defined in the entry

### Screenshots
![seomatic-preview-bug](https://user-images.githubusercontent.com/45926167/132347261-8054758c-bc4c-4902-a55e-63030e19d6ba.png)

### Versions
- Plugin version: 3.4.6
- Craft version: 3.7.11

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/57dff624846be99870ddce3b20aee2652cc05b86

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.7”,
```
Then do a `composer clear-cache && composer update`
