### ISSUE TITLE
Commerce Variant URLs (with query string) Cached

### ISSUE THREAD

**Issue by davist11** [nystudio107/craft-seomatic#971]
### Describe the bug
We are implementing a complex Craft commerce site with lots of variants. Variant URLs in Commerce use a query string, but Seomatic doesn't recognize a query string as a new URL, so we are seeing Seomatic data being cached across variants.

http://site.test/shop/lf-pn-a-00001?variant=26592
http://site.test/shop/lf-pn-a-00001?variant=26591

Are 2 separate variants, but the Seomatic data appears to be cached. We are manually specifying the url, title, and description:

```
{% do seomatic.meta.canonicalUrl(selectedVariant.url) %}
{% do seomatic.meta.seoTitle(selectedVariant.pimData.seoTitle %}
{% do seomatic.meta.seoDescription(selectedVariant.pimData.seoDescription %}
```

### To reproduce
Steps to reproduce the behaviour:
1. Install Craft Commerce
2. Setup multiple variants for a product
3. Setup custom seomatic meta data for the variants
4. Switch between the variants and see that the seomatic data gets cached

### Expected behaviour
I understand ignoring query strings to cache is a performance boost (for pagination requests and other tracking requests), but I'm wondering if there is some way to specify certain query strings _should_ affect the URL.

### Versions
- Plugin version: 3.3.41
- Craft version: Craft Pro 3.6.18

Let me know if there's any other helpful info I can provide. Thanks!

**Comment by khalwat** [comment]
I'm thinking about how to handle this... it could be done with per-section settings for allowed URL parameters or such, but this could get a little involved.

I suppose it's not possible for you to use an additional segment on the URL rather than a URL param for the variant?

**Comment by davist11** [comment]
I don't think so, unless I'm missing some hidden Commerce setting. I don't see any way to customize the variant URL.

https://github.com/craftcms/commerce/blob/main/src/elements/Variant.php#L578-L581

**Comment by khalwat** [comment]
Addressed in the above commits.

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.9”,
```
Then do a `composer clear-cache && composer update`

lmk how you go

**Comment by davist11** [comment]
Works beautifully! Thanks for the quick addition!

**Comment by davist11** [comment]
Any idea when you are gonna officially release 3.4.9?

**Comment by khalwat** [comment]
Version 3.4.9 released -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.9
