### ISSUE TITLE
Undefined array key "category" error when creating new category

### ISSUE THREAD

**Issue by astuteo** [nystudio107/craft-seomatic#973]
### Describe the bug
**Undefined array key "category" error** when trying to create the first category in a new category group

### To reproduce
Steps to reproduce the behaviour:
1. Create a new category group (in this case, it was the first group on this install)
2. Browse to the category group under "Categories" and click "+New Category"
3. See error message "yii\base\ErrorException: Undefined array key "category" in Users/username/sites/website-name/vendor/nystudio107/craft-seomatic/src/seoelements/SeoCategory.php:164

### Expected behaviour
I'd expect to be able to create a new category without error

### Versions
- Plugin version: 3.4.7
- Craft version: 3.7.12

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d693f1988a75222313ee62e98d995f2c51cb51fc

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.8”,
```
Then do a `composer clear-cache && composer update`

**Comment by brandonkelly** [comment]
Just fixed this on Craft’s end as well: https://github.com/craftcms/cms/issues/9811#issuecomment-916061730

**Comment by khalwat** [comment]
Oh interesting. I didn't realize it was because `category` was renamed @brandonkelly
