### ISSUE TITLE
Custom sitemap cache duration

### ISSUE THREAD

**Issue by OscarBarrett** [nystudio107/craft-seomatic#975]
### Is your feature request related to a problem? Please describe.
Currently the custom sitemap (with items added via `SitemapCustomTemplate::EVENT_REGISTER_SITEMAP_URLS`) is cached using the meta cache duration setting, which defaults to unlimited.

In our use case, the items we add to this sitemap are pages that use data sources outside of Craft, so for now we've resorted to setting the cache duration to 1 hour. However, unlimited would be fine for everything else.

### Describe the solution you would like
A separate cache duration option for custom sitemaps/sitemap URLs.

### Describe alternatives you have considered
Another option would be to use the lowest `changefreq` to automatically determine the cache duration.    
e.g. weekly => `60*60*24*7`, always => `30`, etc.

**Comment by khalwat** [comment]
What I'd suggest doing is busting the cache on a regular basis -- you can do this within your code that adds the custom sitemap via:

```php
use nystudio107\seomatic\Seomatic;
use nystudio107\seomatic\models\SitemapCustomTemplate;

Seomatic::$plugin->sitemaps->invalidateSitemapCache(SitemapCustomTemplate::CUSTOM_HANDLE, $siteId);
```
