### ISSUE TITLE
sitemap bug

### ISSUE THREAD

**Issue by LieselotV** [nystudio107/craft-seomatic#976]
Plugin craft-seomatic is correctly installed.

When I check if the sitemap of my website is valid. It says: the sitemap is not valid, and it gave this error: Incorrect http header content-type: "text/html; charset=UTF-8" (expected: "application/xml")

Site where I checked it: https://www.xml-sitemaps.com/

_"SEOmatic will automatically create a sitemap for each of your sections, but if you have additional sitemaps or individual URLs that are outside of the CMS that you want to include, you can add them here."_
I want to check where the sitemap is stored, but I can't find it. 

### Versions
- Plugin version: 3.4.7
- Craft version: Craft CMS 3.7.12

**Comment by khalwat** [comment]
I used this URL: https://www.xml-sitemaps.com/validate-xml-sitemap.html

To check these SEOmatic-generated sitemaps:

https://nystudio107.com/sitemaps-1-section-blog-1-sitemap.xml

https://nystudio107.com/sitemaps-1-sitemap.xml

...and they both were returned as valid, with no errors.  Please tell me what you are using to check the sitemaps, and also what sitemap URLs you are submitting.

**Comment by khalwat** [comment]
I checked out the controller, and it is returning the correct type:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/controllers/SitemapController.php#L91

```php
        $headers->add('Content-Type', 'text/xml; charset=utf-8');
```

```
❯ curl -I https://nystudio107.com/sitemaps-1-sitemap.xml
HTTP/2 200
server: nginx/1.15.8
date: Fri, 10 Sep 2021 13:37:12 GMT
content-type: text/xml; charset=utf-8
permissions-policy: interest-cohort=()
x-powered-by: Craft CMS
x-robots-tag: noindex
x-cache-status: MISS
last-modified: Friday, 10-Sep-2021 13:37:12 GMT
cache-control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
referrer-policy: no-referrer-when-downgrade
```

I'm going to guess that perhaps something went awry with the testing?

**Comment by LieselotV** [comment]
Sorry, I was wrong. Thanks

But when I pass it to google, it still gives this error
![Schermafbeelding 2021-09-10 om 15 52 23](https://user-images.githubusercontent.com/44613082/132864336-99e2b1b7-516a-4861-a1ad-d07eb1f6eaff.png)

**Comment by khalwat** [comment]
I can't help you without seeing the public URL you are trying to submit

**Comment by LieselotV** [comment]
redacted

**Comment by khalwat** [comment]
I'm not seeing anything wrong with either sitemap:

```
❯ curl -I https://REDACTED/sitemaps-1-sitemap.xml
HTTP/2 200
date: Fri, 10 Sep 2021 13:50:51 GMT
server: Apache
permissions-policy: interest-cohort=()
x-powered-by: Craft CMS
x-robots-tag: noindex
vary: Accept-Encoding
content-type: text/xml; charset=utf-8
x-varnish: 827573173 295964193
age: 3072
via: 1.1 varnish (Varnish/6.6)
accept-ranges: bytes
content-length: 447

❯ curl -I https://REDACTED/sitemap.xml
HTTP/2 302
date: Fri, 10 Sep 2021 14:42:20 GMT
server: Apache
permissions-policy: interest-cohort=()
x-powered-by: Craft CMS
location: https://REDACTED/sitemaps-1-sitemap.xml
content-length: 0
content-type: text/html; charset=UTF-8
x-varnish: 428998743
age: 0
via: 1.1 varnish (Varnish/6.6)
```

But I do see that Varnish is being used -- if this issue continues, it could be something do with your server/Varnish config.

But I'd give it a few days and try manually re-submitting the sitemap. Google sometimes displays old search console errors

**Comment by LieselotV** [comment]
Disabling Varnish solved the problem. Thank you.

**Comment by LieselotV** [comment]
![Schermafbeelding 2021-09-13 om 09 01 00](https://user-images.githubusercontent.com/44613082/133038266-e24fd611-ab6c-4bd0-b1fd-863062225ed4.png)

Hi, 
Google still doesn't find the sitemap. Do you have any tips how to solve this? 
I uploaded the sitemap last week on google search console and the status is 'success'. But still he can't find it.
Can you hide this comment (img) again after seeing it?
