### ISSUE TITLE
 Canonical URL Override Site wide

### ISSUE THREAD

**Issue by akdesign** [nystudio107/craft-seomatic#977]
Hello, 

I know that I can override the canonical URL on an individual page. My question is it possible to do the same site-wide,  I try the Site URL Override feature it works for everything else but not for the canonical URL.

**Comment by khalwat** [comment]
Can you give me a little bit more detail on what you're attempting to accomplish? Is this a site that is headless, and thus hosted on another domain?

You said everything but the Canonical URL works when you use the Site URL Override feature... where does the canonical URL not work? What is entered into the Content SEO settings for Canonical URL in the various sections?

**Comment by akdesign** [comment]
I was able to solve the problem by using the .create() function. But here is the situation was I'm working on a site that is set up on craft under live.test.com but I going to be public under test.com and live.test.com. I used the Site URL Override feature to override live.test.com  with test.com below is an example of the result I was getting when the SEO was generated.

`<meta content="https://live.test.com/drug-alcohol-testing" property="og:url">`
`<link href="https://live.text.com/drug-alcohol-testing" rel="canonical">`
`<link href="https://test.com" rel="home">`
`<link type="text/plain" href="https://test.com/humans.txt" rel="author">`

Thank you
