### ISSUE TITLE
Identity logo not showing up in Google's Rich snippets

### ISSUE THREAD

**Issue by jripmeester** [nystudio107/craft-seomatic#978]
### Question
We've setup SEOmatic as completly as possible (as it should be ofcourse) but our client pointed out that their logo isn't showing up in Google's Rich snippets tester. But our Creator logo is. Are we missing out on something here? The logo is in the sourcecode. Only difference is that the identity logo has a crop and the creator logo hasn't.

Page: https://www.nomios.fr/
Rich snippet test: https://search.google.com/test/rich-results?id=_0wqXeCWr4c03Ly2M3nGZA

Thanks!

**Comment by khalwat** [comment]
I don't see anything obviously wrong -- perhaps there's something you can check in your Google Search Console?
