### ISSUE TITLE
Alternate links missing in sitemaps

### ISSUE THREAD

**Issue by adamseabrook** [nystudio107/craft-seomatic#979]
### Bug
Alternate links do not appear in sitemap source if the additional sites were added after the primary site sitemap was first enabled.

### Reproduce
I do not have a site I can reproduce this bug on currently. But doing the fix below made the alternate links appear. My guess is that enabling additional sites does not trigger the already enabled sitemaps to add them.

### Fix
Disable, save, then re-enable the sitemap for every section makes it pickup the other sites and add them as alternates.

**Comment by khalwat** [comment]
This would also be fixed if the caches were manually cleared, or any entry in any of the sections were changed (which would invalidate the sitemap and cause it to be regenerated).

I think probably it's fine to not address this, since, the sitemap caches will naturally be cleared and the sitemaps regenerated as a course of using the CMS.

**Comment by adamseabrook** [comment]
Clearing the cache and saving entries does not actually fix the issue. Tried a few different methods and the only fix is to disable and reenable the Sitemap ALT URL option.

**Comment by khalwat** [comment]
Looking at the code, I'm thinking you may be right -- it looks like it may not sync the bundle settings to include the newly added site.

However, it shouldn't be necessary to toggle the setting from what I can see, just saving the Content SEO settings for the Section should do it.

Doing this automatically as I thought it was would obviously be best, however.

**Comment by mizziness** [comment]
I think this might be related to: https://github.com/nystudio107/craft-seomatic/issues/1060

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/b7727307a0f58cba26f2e4c904dc3ef8db0b8828

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.24”,
```
Then do a `composer clear-cache && composer update`

To trigger it, if you go to edit the new site, then click on Save, it should trigger the resaving of the MetaBundles.

lmk how you go!
