### ISSUE TITLE
Couldn't save tracking settings due to a Twig error.

### ISSUE THREAD

**Issue by torgeirbeyer** [nystudio107/craft-seomatic#981]
### Describe the bug
When trying to save HubSpot tracking script I get the error 
`Couldn't save tracking settings due to a Twig error.
`
The script is active and saved, and when I try to remove it this error occurs.

All the other tracking scripts can be activated and deactivated without problems.

The site is a multisite with 4 different languages/sites

### To reproduce
Steps to reproduce the behaviour:
1. Go to SeoMatic tracking scripts section
2. Click on Hubspot and deactivate the tracking script
3. See error message Couldn't save tracking settings due to a Twig error.

### Expected behaviour
Expected it to save as normal

### Screenshots

<img width="1214" alt="Skjermbilde 2021-09-17 kl  11 58 40" src="https://user-images.githubusercontent.com/43992745/133764619-5ac016ec-3c62-4935-aedf-4fabb2dd30f7.png">

### Versions
- Plugin version: 3.4.10
- Craft version: 3.7.13

**Comment by khalwat** [comment]
Addressed in the commit above.

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.11”,
```
Then do a `composer clear-cache && composer update`
