### ISSUE TITLE
Exclude page from sitemap programmatically if page is not self referential (canonical different from entry url)

### ISSUE THREAD

**Issue by yingban** [nystudio107/craft-seomatic#983]
### Question
I got a requirement from the SEO guy of my company.
I need to exclude an entry from the sitemap if entry.url != seomatic.meta.canonicalUrl. (apparently it's a common rule...)

Do I have to write a plugin for it or there is another way? 
Thanks !

**Comment by khalwat** [comment]
How would these be different? Are you doing something to make the canonical URL of some entries be different from the entry URL?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/0fd245b84049aae914f3c7b020719b4eff2c5302

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.11”,
```
Then do a `composer clear-cache && composer update`

**Comment by yingban** [comment]
@khalwat Thank you for the update.
My SEO colleague sent my this source https://sitebulb.com/hints/xml-sitemaps/canonicalized-url-in-xml-sitemaps/

> Your XML Sitemap should only contain URLs you wish for search engines to index. If a URL is canonicalised, this is an explicit statement to search engines that you do NOT wish for the URL to be indexed, and instead wish for the canonical URL to consolidate indexing signals. As such, including a canonicalised URL in a sitemap provides conflicting information to search engines, and may impact what they consider is the canonical URL, which may in turn mean that unintended URLs get indexed.

**Comment by khalwat** [comment]
I don't particularly agree with that assessment from sitebulb.com but nevertheless the option is there now! :)
