### ISSUE TITLE
Hreflang errors on pages with pagination segments in the url

### ISSUE THREAD

**Issue by brianrivet-tilt** [nystudio107/craft-seomatic#984]
I don't know if this is necessarily a bug or if there is a setting I'm not aware of. I am seeing errors in a semrush report on a site I'm working on where many of the pages in the news section are showing hreflang errors. The report shows the error as the page not having a self-referencing hreflang tag. When I look at the report, every page that shows this error has a pagination segment ('p2, p3, etc.) as the last segment of the url. When I look at the code output, here's what I see on one of the pages:

The page url is https://isomag.com/about-us/news/p10
The code output for the hreflang tags looks like this:
`
<link href="https://isomag.com/about-us/news/p10" rel="canonical">
<link href="https://isomag.com" rel="home">
 <link type="text/plain" href="https://isomag.com/humans.txt" rel="author">
 <link href="https://isiseal.com/about-us/news" rel="alternate" hreflang="en-in">
 <link href="https://isomag.com/about-us/news" rel="alternate" hreflang="x-default">
 <link href="https://isomag.com/about-us/news" rel="alternate" hreflang="en-us">
 <link href="https://isomag.com/about-us/news/p9" rel="prev">
 <link href="https://isomag.com/about-us/news/p11" rel="next">

`

I'm seeing the same thing here:
url: https://isomag.com/news/tag/bearingprotector/p2
Here's the code:
`
<link href="https://isomag.com/news/tag/bearingprotector/p2" rel="canonical">
 <link href="https://isomag.com" rel="home">
 <link type="text/plain" href="https://isomag.com/humans.txt" rel="author">
 <link href="https://isiseal.com/news/tag/bearingprotector" rel="alternate" hreflang="en-in">
 <link href="https://isomag.com/news/tag/bearingprotector" rel="alternate" hreflang="x-default">
 <link href="https://isomag.com/news/tag/bearingprotector" rel="alternate" hreflang="en-us">
 <link href="https://isomag.com/news/tag/bearingprotector" rel="prev">
 <link href="https://isomag.com/news/tag/bearingprotector/p3" rel="next"></head>

`

Notice how the hreflang tags don't include the pagination segment but the canonical does. I don't know if that is actually what is setting off the error, but as I understand it, the self-referencing hreflang tag should match the page's url.

I also noted that the first page of these listings does not trip the error in semrush and it does not have a pagination segment:

url: https://isomag.com/news/tag/bearingprotector/
code output: 
`
<link href="https://isomag.com/news/tag/bearingprotector" rel="canonical">
<link href="https://isomag.com" rel="home">
<link type="text/plain" href="https://isomag.com/humans.txt" rel="author">
<link href="https://isiseal.com/news/tag/bearingprotector" rel="alternate" hreflang="en-in">
<link href="https://isomag.com/news/tag/bearingprotector" rel="alternate" hreflang="x-default">
<link href="https://isomag.com/news/tag/bearingprotector" rel="alternate" hreflang="en-us">
<link href="https://isomag.com/news/tag/bearingprotector/p2" rel="next"></head>

`

The site is running Craft CMS 3.4.30 and SEOMatic v. 3.3.18. If updating will fix this issue I will take a look at that, but I wanted to see if you were aware of any issue that may cause this.

**Comment by khalwat** [comment]
I think there's some code missing here @brianrivet-tilt ?

**Comment by brianrivet-tilt** [comment]
weird. sorry. Guess I should have checked the preview.

Here it is 
The page url is https://isomag.com/about-us/news/p10
The code output for the hreflang tags looks like this:

```
<link href="https://isomag.com/about-us/news/p10" rel="canonical">
<link href="https://isomag.com" rel="home">
<link type="text/plain" href="https://isomag.com/humans.txt" rel="author">
<link href="https://isiseal.com/about-us/news" rel="alternate" hreflang="en-in">
<link href="https://isomag.com/about-us/news" rel="alternate" hreflang="x-default">
<link href="https://isomag.com/about-us/news" rel="alternate" hreflang="en-us">
<link href="https://isomag.com/about-us/news/p9" rel="prev">
<link href="https://isomag.com/about-us/news/p11" rel="next">
```

I'm seeing the same thing here:
url: https://isomag.com/news/tag/bearingprotector/p2
Here's the code:
```
<link href="https://isomag.com/news/tag/bearingprotector/p2" rel="canonical">
<link href="https://isomag.com" rel="home">
<link type="text/plain" href="https://isomag.com/humans.txt" rel="author">
<link href="https://isiseal.com/news/tag/bearingprotector" rel="alternate" hreflang="en-in">
<link href="https://isomag.com/news/tag/bearingprotector" rel="alternate" hreflang="x-default">
<link href="https://isomag.com/news/tag/bearingprotector" rel="alternate" hreflang="en-us">
<link href="https://isomag.com/news/tag/bearingprotector" rel="prev">
<link href="https://isomag.com/news/tag/bearingprotector/p3" rel="next">
```

Notice how the hreflang tags don't include the pagination segment but the canonical does. I don't know if that is actually what is setting off the error, but as I understand it, the self-referencing hreflang tag should match the page's url.

I also noted that the first page of these listings does not trip the error in semrush and it does not have a pagination segment:

url: https://isomag.com/news/tag/bearingprotector/
code output:
```
<link href="https://isomag.com/news/tag/bearingprotector/p2" rel="canonical">
<link href="https://isomag.com" rel="home">
<link type="text/plain" href="https://isomag.com/humans.txt" rel="author">
<link href="https://isiseal.com/news/tag/bearingprotector" rel="alternate" hreflang="en-in">
<link href="https://isomag.com/news/tag/bearingprotector" rel="alternate" hreflang="x-default">
<link href="https://isomag.com/news/tag/bearingprotector" rel="alternate" hreflang="en-us">
<link href="https://isomag.com/news/tag/bearingprotector" rel="prev">
<link href="https://isomag.com/news/tag/bearingprotector/p3" rel="next">
 ```

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/af19b7213c759e09828ee49f267ab217cd210fa0

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.11”,
```
Then do a `composer clear-cache && composer update`
