### ISSUE TITLE
Upgrading to 3.4.12+ - Broken SEO Image URLs using Imgix + ImageOptimize

### ISSUE THREAD

**Issue by itsmattsoria** [nystudio107/craft-seomatic#987]
After running the few updates that came out in the past few days going from version 3.4.10 to 3.4.12 I noticed that the SEO image previews in the entry editing screen in the admin in my staging environment were broken and then checked the out the metatags being generated (using automatic render enabled) were indeed pointing to the wrong URL — they were pointing to the URL of the un-transformed image at the Imgix domain I have set up using ImageOptimize, which I don't think exists and was returning a 403 error. 

Locally I am not using the Imgix source and the image previews and meta tag output were working properly, showing the transformed images in the `_twitterCard` directory for example (I have the auto-transforms enabled for all of the SEO images in the SEOmatic settings), however on staging where I am using the Imgix source, they were broken.

I was able to pinpoint it to the 3.4.12 update after downgrading to 3.4.11 and the image URLs are correct. 
As an example, the URL output for this page (https://bv.firebelly.co/who-we-are/sanjeev-krishnan) while on 3.4.12:
https://firebelly.imgix.net/uploads/circular/sanjeev-krishnan/Builders-Vision_headshot__0748.jpg

And then on 3.4.11, the correct URL:
https://firebelly.imgix.net/uploads/circular/sanjeev-krishnan/Builders-Vision_headshot__0748.jpg?auto=format&amp;crop=focalpoint&amp;domain=firebelly.imgix.net&amp;fit=crop&amp;fp-x=0.4777&amp;fp-y=0.279&amp;h=800&amp;ixlib=php-3.3.0&amp;q=82&amp;w=800&amp;s=b8a2f620ddb3d7caf80987d0f1a90827

That page is currently using 3.4.11 until I figure out this fix.

Any ideas on what might have changed on the version that would break this?

For some context, I'm running a multisite environment on **Craft Pro 3.7.13**, and I'm running **ImageOptimize 
1.6.36**. Again, this is only happening in the staging environment.

Thanks for your help!

**Comment by itsmattsoria** [comment]
Okay, after looking again I'm realizing I have two issues going on here.  The first issue with the un-transformed URL being used is still an issue, but on top of that I have the fact that the URLs are getting `&amp;` instead of `&`, which is returning a 403 error too. I think I read through another issue where someone was mentioning that happening. I'll go dig around to see if there was an answer to that.

**Comment by itsmattsoria** [comment]
I did find that issue, and saw you referenced a fix for it as well: #146 

Looking at this a little deeper, the images **are** getting the `&amp;`s still, but it looks like they're being parsed just fine by Slack, Facebook, etc. Not sure if that that is unintended or not, but again, seems to be interpreted fine regardless.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/ee91cfa5fb2420a2154f7f297b08da4fabf1009e

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.14”,
```
Then do a `composer clear-cache && composer update`

**Comment by itsmattsoria** [comment]
@khalwat that seemed to do it, thanks!
