### ISSUE TITLE
Robots directive for `max-image-preview`

### ISSUE THREAD

**Issue by chrismlusk** [nystudio107/craft-seomatic#988]
We have a few clients whose SEO consultants have requested their robots meta tag for blog pages get updated to:

```
<meta name="robots" content="max-image-preview:large">
```

This looks to be one of [Google's recommendations](https://developers.google.com/search/docs/advanced/mobile/google-discover) to help get content to appear in [Discover](https://developers.google.com/search/docs/advanced/mobile/google-discover).

We're setting this manually for now, but I wanted to see if this is something you've considered supporting.

**Comment by khalwat** [comment]
I think this is a good idea. Question is really from a GUI point of view, I'm thinking it should be an array of checkboxes rather than a dropdown menu.

**Comment by khalwat** [comment]
Same as: https://github.com/nystudio107/craft-seomatic/issues/1237

Will consolidate discussion there.

**Comment by khalwat** [comment]
Working on a custom component that looks something like this:

<img width="1082" alt="Screen Shot 2022-11-10 at 4 28 55 PM" src="https://user-images.githubusercontent.com/7570798/201209743-261a99fa-da77-4af1-ba03-0483e8052355.png">

**Comment by khalwat** [comment]
Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.42”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.12”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
lmk how you go

**Comment by khalwat** [comment]
Here it is in action:


https://user-images.githubusercontent.com/7570798/201255069-330a719c-bb7d-4fdc-b0a9-f018109974d1.mov
