### ISSUE TITLE
"Fit" vs "Crop" product the same result?

### ISSUE THREAD

**Issue by MattWilcox** [nystudio107/craft-seomatic#991]
### Describe the bug

When setting a Facebook OpenGraph Image Source you can also set the Facebook OpenGraph Image Transform Mode.
Changing between Crop and Fit produces no difference in the preview. Only "Stretch" changes the rendered preview after save.

This is using an SVG file, in case that matters.

### Screenshots

How the preview looks if Crop or Fit are selected.

<img width="841" alt="Screenshot 2021-09-30 at 10 41 24" src="https://user-images.githubusercontent.com/814039/135430705-f484dffb-8ddd-4a92-9a54-7dcf0564f1cc.png">

The source SVG is a square.

### Versions
- Plugin version: 3.4.15
- Craft version: 3.7.14

**Comment by khalwat** [comment]
Any way you can attach the original image?

**Comment by MattWilcox** [comment]
Had to zip it as GitHub doesn't support attaching svgs...
[emma-wood-interiors-square.svg.zip](https://github.com/nystudio107/craft-seomatic/files/7260726/emma-wood-interiors-square.svg.zip)

**Comment by khalwat** [comment]
Same as: https://github.com/nystudio107/craft-seomatic/issues/358
