### ISSUE TITLE
Webhooks Configuration 

### ISSUE THREAD

**Issue by BrandonJamesBorders** [nystudio107/craft-seomatic#992]
### Question
I have a headless Craft CMS build and am using the Webhooks plugin to trigger deployments. I'm unable to find a way to trigger the webhooks plugin to fire off a POST request when a user changes "settings" within the SEOmatic plugin (not actually settings as allowAdminChanges is set to false, but things like tracking scripts, content defaults, etc). 

![image](https://user-images.githubusercontent.com/6044898/135448740-7379c08e-0ee1-4b48-b2c1-d35a96139d56.png)

Any guidance would be great! Thank you!

**Comment by khalwat** [comment]
There's currently no way to do this. What's the use-case here?

**Comment by khalwat** [comment]
I'm guessing the idea is that you want to be able to trigger a deployment when various SEO settings are changed?

**Comment by khalwat** [comment]
So just to clarify... there are actually two separate things you might be interested in listening to.

* `nystudio107\seomatic\models\Settings` would cover anything changed in **SEOmatic → Plugin Settings**
* `nystudio107\seomatic\models\MetaBundle` would cover anything changed in **SEOmatic → Global SEO**, **SEOmatic → Content SEO**, **SEOmatic → Site Settings** and **SEOmatic → Tracking Scripts**

I'm assuming you _probably_ want an event for both?

**Comment by khalwat** [comment]
Actually, I think there is an existing event you can use:

`nystudio107\seomatic\services\MetaContainers`

The event is triggers is `InvalidateContainerCachesEvent` ->https://github.com/nystudio107/craft-seomatic/blob/develop/src/events/InvalidateContainerCachesEvent.php#L16

```php
/**
 * Throw an event after SEOmatic has cleared its caches.
 *
 * If both $uri and $sourceId are null, then SEOmatic is clearing ALL of its container
 * caches.
 *
 * If $uri is non-null, then SEOmatic is clearing its caches for just that $uri and
 * optional $siteId
 *
 * If $sourceId is non-null, then SEOmatic is clearing all caches that are owned by
 * the Section/Category/Product with the `id` of $sourceId
 *
 * @author    nystudio107
 * @package   Seomatic
 * @since     3.1.48
 */
```

Any time the settings are saved, it'll invalidate all of the SEOmatic caches with the parameters set like this:

```php
        // Trigger an event to let other plugins/modules know we've cleared our caches
        $event = new InvalidateContainerCachesEvent([
            'uri' => null,
            'siteId' => null,
            'sourceId' => null,
            'sourceType' => null,
        ]);
```

This should do it for you -- let me know if I'm incorrect, and you need something more.

**Comment by bryantcodesart** [comment]
For future travelers: 

Can confirm this works, e.g. for triggering revalidation when an seomatic change is made.  <img width="760" alt="image" src="https://user-images.githubusercontent.com/14097078/229977671-a76f984a-e6f6-454e-b5bc-0889d2e368c1.png">
