### ISSUE TITLE
<Title> to the top in <head>

### ISSUE THREAD

**Issue by LieselotV** [nystudio107/craft-seomatic#993]
### Question
Hi,
Seomatic adds the title, meta, links at the end of `<head>`. For better SEO, I was wondering how to display it at the beginning of `<head>`? 

I already tried to place an extra tag at the top: `<title>{{ seomatic.meta.seoTitle }}</title>`
On the homepage it displays correctly, but on other pages it output this:
`<title>{seomatic.helper.extractTextFromField(object.entry.title)}</title>`

Can you help me how to put the title tag on the top of the page? Now it's on line 45, what's really far.

### Additional context
view-source:https://studiomast.be/

**Comment by khalwat** [comment]
Currently, there is no way to control where this information is output.

What is the reason for wanting to control where the `<title>` tag is output?

**Comment by khalwat** [comment]
Will re-open if additional information is provided.
