### ISSUE TITLE
SEO Image Transform Mode is empty with no options

### ISSUE THREAD

**Issue by MattWilcox** [nystudio107/craft-seomatic#995]
### Describe the bug

When using the SEOmatic Field Type on an Entry, and flipping SEO Image Source Override on ... the SEO Image Transform Mode is empty with no options.

### Screenshots

<img width="673" alt="Screenshot 2021-10-07 at 17 19 02" src="https://user-images.githubusercontent.com/814039/136424691-c7899cfb-a18d-4930-b6a0-4bddeaaeb593.png">

### Versions
- Plugin version: 3.4.15
- Craft version: 3.7.16

**Comment by khalwat** [comment]
Are you seeing any errors in the JavaScript console?

Can you post a screenshot of *before* you flip the override switch?

Also a screenshot of the SEO Settings field's Settings (to see what is enabled/disabled)?

**Comment by MattWilcox** [comment]
Only errors seem unrelated: `Double-instantiating a menu button on an element` in garnish.js

Description overridden, Image Source not...

<img width="663" alt="Screenshot 2021-10-11 at 08 51 51" src="https://user-images.githubusercontent.com/814039/136752716-4760d2aa-3b78-4843-ae89-d842e38fa912.png">

Settings for the Section:

<img width="1259" alt="Screenshot 2021-10-11 at 08 53 46" src="https://user-images.githubusercontent.com/814039/136752975-0aca0aa9-2e65-437c-a7a5-36434a7717ad.png">

I see that it's set to automatic, but would expect that the field on the Entry would over-ride that general preference, as it does for other things.

Cheers Andrew!

**Comment by khalwat** [comment]
Screenshot of the SEO Settings field settings please?

**Comment by MattWilcox** [comment]
Not sure where you mean, I thought that was the last screenshot?

**Comment by MattWilcox** [comment]
[removed user error]

**Comment by MattWilcox** [comment]
[removed a follow up user error]

**Comment by MattWilcox** [comment]
Ignore me Andrew, got complete option blindness among all those tickboxes and missed the one I needed.

Yes, when the right fields are ticked, they do indeed show Image Transform Modes - though still think that entire UI should not be shown at all on the Field output if the SEO Field Settings don't allow it.

**Comment by khalwat** [comment]
I agree.

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/51a9fbb8602c75ab570414ea8a3d33419e35fd1b

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.16”,
```
Then do a `composer clear-cache && composer update`
