### ISSUE TITLE
Allow explicit inheritance/cascading options in dropdowns

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-seomatic#996]
### Problem

When you configure a setting (e.g. Robots) in the Content SEO section it will override the Globals SEO section. Once this is set, however, you cannot go back to ‘inheriting’ the Global SEO selection.

### Suggested solution

We’d like to be able to select an “Inherit from Global SEO”, or similar, option for applicable settings.

**Comment by khalwat** [comment]
Are you intending to use this as a global switch to turn on/off indexing, or the like?

In general, the idea is that we actually want Content SEO settings set up and overriding for everything if possible.

**Comment by joshuabaker** [comment]
Exactly.

Once you’ve set the Content SEO setting it’s much higher effort to go through changing the settings back and forth when needed (i.e. number of sections versus one global setting).

The alternative is to clear these out in the database somehow. Not keen on this approach though.

**Comment by khalwat** [comment]
The reason I ask is that for Robots, for example, SEOmatic automatically takes care of disabling indexing globally if your environment is local dev or staging or the like.

So what are you trying to accomplish? There may be more effective ways of doing it, depending on what you need to do.

**Comment by joshuabaker** [comment]
We want to be able to share sites with stakeholders whilst being populated with content, but not have these showing up in SERPs.

In this particular scenario, we’ve got multiple sites powered by a single Next.js app. It’d be a huge effort to set up a separate staging environment in this instance.

All that said, the underlying issue is being unable to revert back to inheriting from Global SEO in some scenarios when a setting is selected at the Content SEO level.

If I empty the ‘SEO Description Source’ field within a Content SEO section it will automatically inherit whatever is defined in Global SEO. We’d like to be able to do the same with Robots.

**Comment by khalwat** [comment]
Got it. All we need to do is provide you with a way to have an empty value, and away you go.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/a751c9941b4bc769b194eddcdf7dc1937578abea

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.16”,
```
Then do a `composer clear-cache && composer update`
