### ISSUE TITLE
Main sitemap index is empty for all except first site group

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-seomatic#997]
## Description

I have a headless multisite setup with two site groups. Each site with each group is independent. 

Ideally each site could have its own sitemap. Reading the docs and issues here, I understand that SEOmatic generates sitemaps based on site groups (i.e. `/sitemap-{siteGroupId}-*.xml`).

The issue is that only the first site group is having a sitemap index generated.

## Expected behaviour

`/sitemaps-1-sitemap.xml` will list out all section indices for `site.groupId = 1`

`/sitemaps-2-sitemap.xml` will list out all section indices for `site.groupId = 2`

## Current behaviour

✅  `/sitemaps-1-sitemap.xml` lists out all section indices for `site.groupId = 1`

❌  **`/sitemaps-2-sitemap.xml` is empty** or just has the same content as `/sitemaps-1-sitemap.xml` *

✅  `/sitemaps-2-section-{sectionHandle}-{siteId}-sitemap.xml` lists out all entries as expected

_* Based on the ‘Site Groups define logically separate sites’ setting._

## Versions

- Plugin version: 3.4.15
- Craft version: 3.7.9

**Comment by joshuabaker** [comment]
Just a quick note, as I mentioned headless; Proxying via the frontend is not an issue here. The issue here is only that the sitemap is empty. I’m referencing the URL directly (i.e. `http://craftinstall.dev/sitemap...`).

Am I missing something here?

**Comment by khalwat** [comment]
Are URLs enabled for all of the sites in question?

**Comment by joshuabaker** [comment]
Yeah, they’re showing up in their logically nested sitemaps (e.g. `/sitemaps-2-section-homepage-4-sitemap.xml`). It’s just the index sitemap that appears to be misbehaving.

**Comment by khalwat** [comment]
Have you tried just accessing the `/sitemap.xml` for each given site? It should be correct. e.g.:

https://site2.example.com/sitemap.xml

or 

https://somesite.com/fr/sitemap.xml

**Comment by joshuabaker** [comment]
It’s a headless site (SPA) so there’s only one Craft hostname.

Requesting from any of the Next.js domains just results in SEOmatic returning the primary sitemap via a redirect (i.e. `/sitemap.xml` → `/sitemaps-1-sitemap.xml`).

**Comment by joshuabaker** [comment]
I’m basing my understanding of how this works on this [comment](https://github.com/nystudio107/craft-seomatic/issues/766#issuecomment-706474738).

**Comment by joshuabaker** [comment]
So, it looks like I can get site-specific sitemaps by directly referencing the [`SitemapController`](https://github.com/nystudio107/craft-seomatic/blob/24031f0caf17eb6de766f8c794a7622da3cbbccd/src/controllers/SitemapController.php#L53) actions (i.e. `/actions/seomatic/sitemap/sitemap-index?groupId=2&siteId=2`).

**Comment by joshuabaker** [comment]
There’s definitely a bug here. Omitting the `siteId` parameter from the above-mentioned action request will load the wrong site group (i.e. site group 1 instead of site group 2).

**Comment by joshuabaker** [comment]
However, appending a `siteId` parameter to one of the standard `sitemap.xml` paths ‘just works’.

`/sitemaps-1-sitemap.xml?siteId=2` returns `/actions/seomatic/sitemap/sitemap-index?groupId=2&siteId=2`.

**Comment by khalwat** [comment]
Looks like it does this: 
```php
        $xml = Seomatic::$plugin->sitemaps->renderTemplate(
            Sitemaps::SEOMATIC_SITEMAPINDEX_CONTAINER,
            [
                'groupId' => $groupId,
                'siteId' => $siteId ?? Craft::$app->getSites()->currentSite->id,
            ]
        );
```

So if no `$siteId` is passed in, it falls back on the current site. Which will be right _except_ if it is a headless request.

Are you able to just pass in the appropriate `$siteId` as a URL param, or do you think I should set the `$siteId` to the first site in the given group, if it's not passed in?

The route for the sitemap index does not include a `siteId` anywhere in it, just a `groupId`:

```php
    public static function create(array $config = [])
    {
        $defaults = [
            'path' => 'sitemaps-<groupId:\d+>-sitemap.xml',
            'template' => '',
            'controller' => 'sitemap',
            'action' => 'sitemap-index',
        ];
        $config = array_merge($config, $defaults);

        return new SitemapIndexTemplate($config);
    }
```

**Comment by joshuabaker** [comment]
I have sitemaps working by passing a `siteId` parameter.

Is there a chance you can get this working a little more smoothly for headless installs?

**Comment by khalwat** [comment]
The plan is to allow you to request them via GraphQL or endpoint, which should neatly solve the problem for you as well I think?

**Comment by joshuabaker** [comment]
Either would be great, yeah. Thank you.

Is there an issue tracking that?

**Comment by khalwat** [comment]
SEOmatic is out with full support for sitemaps via GraphQL

**Comment by joshuabaker** [comment]
Amazing stuff as always! Thank you, @khalwat. 🙏🏻
