### ISSUE TITLE
Need to pass custom URL to canonical URL in sitemap automatically

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft-seomatic#998]
I have a press section on a site, and the channel has two entry types associated with it:

1. Press Release
2. In the News

Press releases generate their own page on the site, but "in the news" is more of a Daring Fireball style link out post. The problem is we've realized that SEOmatic is generating sitemap links for those link out posts when they aren't generating pages on the site, and need to find a way to make the sitemap show the outgoing link instead of the entry.url.

I'd like this to be automatic for the client (i.e. they don't have to remember to override the canonical field every time they post) - but since these aren't separate channels, I can't set the canonical URL override in the content settings.

I've also tried to override with twig in the templates, but I think because the page never gets rendered it doesn't update the sitemap even after clearing caches.

Is there another way to do this that I'm missing?

**Comment by khalwat** [comment]
SEOmatic allows you to have per-entry type settings. So in Content SEO settings for the "In the News" entry type, turn the sitemaps off, and you should be good to go.

The "Entry Type" menu is on the left:

<img width="522" alt="Screen Shot 2021-10-11 at 8 33 17 PM" src="https://user-images.githubusercontent.com/7570798/136871060-423ce663-ad96-4b31-a976-027c60947f1b.png">

**Comment by jonlongnecker** [comment]
So I've modified the Canonical URL for my specific entry type to use a custom field (`{entry.pressSourceLink}`), saved that section, cleared caches, re-saved all the entries, and the sitemap is still showing the `entry.url` on my local version of the site. Is there anything else I need to do for the sitemap to use the right URL?

**Comment by khalwat** [comment]
Did you disable sitemaps for that Entry Type?

**Comment by jonlongnecker** [comment]
No, they're still enabled -  I can see the entries from that type in the sitemap. But they're still using the `{entry.url}`.

**Comment by khalwat** [comment]
So you're saying you don't want to disable them from appearing in the sitemap, you want them to appear in the sitemap using a different URL?

**Comment by jonlongnecker** [comment]
Correct - is that not possible?

**Comment by khalwat** [comment]
It's not possible. An entry's URL is what will appear in the sitemap; if you have a different Canonical URL set for it, it won't even appear in the sitemap at all.

I'd suggest _disabling_ sitemaps for this entry type, as they are linking out to somewhere else, and thus shouldn't appear in your site's sitemap anyway.

**Comment by jonlongnecker** [comment]
Ok I'll try that, thanks.
