### ISSUE TITLE
Seomatic blows out entries csv export format making it unusable

### ISSUE THREAD

**Issue by playcraftSystems** [nystudio107/craft-seomatic#999]
### Describe the bug
On the entries page at the bottom there is an export button. When craft-seomatic is installed this csv export is unreadable. Several columns are mixed together and in the wrong location with seomatic data spread throughout the spreadsheet.

### To reproduce
Steps to reproduce the behaviour:
1. Have seomatic plugin installed.
2. Go the any Craft CMS entries page, head to the bottom of the page and select export button.
3. Select Raw or Expanded dataset, format csv, and click export. 

### Expected behaviour
A CSV with column data not mixed within other columns.

### Screenshots

![Screen Shot 2021-10-12 at 7 30 48 AM](https://user-images.githubusercontent.com/50718005/136975876-293464bd-ffaf-4924-b0df-4d41c6aa334d.png)

### Versions
- Plugin version: 3.3.46
- Craft version: Craft Pro 3.7.7

**Comment by khalwat** [comment]
Please upgrade to the latest version of SEOmatic & the latest version of Craft CMS.

I'm unable to replicate your issue using SEOmatic 3.4.15 and Craft Pro 3.7.16

**Comment by playcraftSystems** [comment]
Updated, still happening. 

Update screenshot
![Screen Shot 2021-10-12 at 11 00 40 AM](https://user-images.githubusercontent.com/50718005/137006389-c228aaee-9b66-4fcf-bf3a-4202d56c986b.png)
![Screen Shot 2021-10-12 at 11 00 08 AM](https://user-images.githubusercontent.com/50718005/137006393-5a4499e4-1b04-49be-a3ee-4d69231ef56b.png)
s

CSV screenshot
![Screen Shot 2021-10-12 at 10 59 05 AM](https://user-images.githubusercontent.com/50718005/137006413-32e29e5d-0d7f-41e3-b2fe-af462da6e3a1.png)

**Comment by khalwat** [comment]
Have you looked at the raw CSV files to determine if anything is actually wrong there? Could it be possible that this is just a display issue with the spreadsheet you're using?

I can't think of anything that SEOmatic could be doing that could affect this in any way. It's likely to be either an issue with Craft's CSV exporter, or an issue with whatever tool you're importing the CSV into.

**Comment by playcraftSystems** [comment]
You're correct. There is nothing wrong with the CSV. Anything I import the CSV into can't view the document correctly. Excel and Google sheets both fail by throwing Seomatic data across several fields where it doesn't belong. Is there any way I can export without the seomatic data?

**Comment by khalwat** [comment]
My guess is that the CSV exporter from Craft isn't escaping _something_ properly (either commas, or quotes, or the like). I'd suggest filing an issue here: https://github.com/craftcms/cms/issues

**Comment by playcraftSystems** [comment]
Thank you.

**Comment by brandonkelly** [comment]
Fixed for the next Craft release: https://github.com/craftcms/cms/issues/9958#issuecomment-942256717
